### ISSUE TITLE
Expression/formula as column mapping (calculated fields) 

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1004]
Hello,

I know that this is not the design of an entity-table mapping, but is there a way to create some kind of formula or expression mapping?
NHibernate has something like this [Nhibernate mapping property](https://ayende.com/blog/3936/nhibernate-mapping-property)
I would think about somthink like :

```
        [Table("CUSTOMER")]
	public partial class Customer
	{
		[Column("ID"), PrimaryKey,  NotNull] public int    Id { get; set; } 
		[Column(), NotNull] public string Name { get; set; } 
		[Column(),  NotNull] public string FirstName { get; set; } 
		[Column(), Nullable         ] public string Company { get; set; } 
		[Column(),  NotNull] public string ZipCode { get; set; }
		[Column(), NotNull] public string Town { get; set; }
                [Column(Expression="select s.STATUS from CUSTOMER_STATUS s where s.CUSTOMER_ID = {Id}")
public int CustomerStatus{ get; set; } 
	}
```

To access the Customer properties, you could write the property as curly brackets, or access it directly with column name :
`[Column(Expression="select s.STATUS from CUSTOMER_STATUS where s.CUSTOMER_ID = ID")]`

**Comment by Franki1986** [comment]
Maybe to explain a little more my problem. I am using a web grid and want to filter against the database. Now I have several columns that are bitmasks of options, so that every bit of the column stands for a boolean option.
So let's say that bit 1 stands for a boolean that says that a person has a certain permission to enter into a private zone.
In the grid I would like to bind it to a boolean column and filter later by a linq expression. 
So in my case the mappimg would be:

[Column(Expression="OPTIONS & 2" )]
public bool HasPermission{get;set;}

Amd the resulting select statement would be something like:

Select BinAnd(c.OTIONS, 2) as HasPermission from customers;

**Comment by sdanyliv** [comment]
Not near computer but it looks like ExpressionMethod or Association with ExpressionPredicate

**Comment by Franki1986** [comment]
ExpressionMethod will not work, because I would have to pass a parameter.
What would work, if it is possible to conditionally remove table alias for specific columns, the following should work:

Normal mapping:

```
[Column("(OPTIONS & 2)"), HideTableAlias]
public bool HasPermission{get;set;}
```

result would be:

`Select c.(BinAnd(c.OPTIONS, 2) ) as HasPermission from customers c;`

This does not work because of the table alias

This should work

```
[Column("(OPTIONS & 2)"), HideTableAlias]
public bool HasPermission{get;set;}
```

`Select (BinAnd(c.OPTIONS, 2) ) as HasPermission from customers c;`

**Comment by Franki1986** [comment]
Sorry, for asking another time, but is there no possibility for this? I think calculated fields are used often.

**Comment by sdanyliv** [comment]
Really can’t understand why ExpressionMethod should not work. Something like this:
```cs
[ExpressionMethod(“HasPermissionImpl”)]
property bool HasPermission { get; }

static Expression<Func<Customer, bool>> HasPermissionImpl(Customer c)
{
    return (c) => c.Status & 2 != 0
}
```
Not tested but something like this should work. Please look at samples in our tests.

**Comment by Franki1986** [comment]
I thought there would be something more generic. Because using the column name as sql statement or as sql expression with an additional attribute would be very intuitive and would fit in amy situation for calculated fields.
Is there a chance for a feature request? 
```
[column("select count(*) from CUSTOMER_ARTICLE"), UseColumnAsExpression = true] 
Public int ArticleCount{get;set;} 

Both mappings are intuitive and will fit calculated fields.. 

[column("BIN_AND(STATUS, 2)"), UseColumnAsExpression = true] 
Public bool HasPermission{get;set;}
```

**Comment by sdanyliv** [comment]
I don’t like this because of usage of string expressions. You can use expression method with `db` parameter and create query using linq expressions.

**Comment by Franki1986** [comment]
Good morning,

I testet it, but this is not a real calculated field, because it is only used to filter. The value is not mapped into the resulting class. So I can filter on HasPermission, but this value is not loaded to the result.

**Comment by Franki1986** [comment]
Good morning,

I have tested the ExpressionMethod, but this only works for filtering! The ExpressionMethod is not mapped into the property.
I used your example in the tests : [Property and ExpressionMethod line 90](https://github.com/linq2db/linq2db/blob/cf160d92b7062d1af7581abeb7185b20a0fdde94/Tests/Model/ParentChild.cs)

As a calculated field I would expect that this value is always mapped to the property.

**Comment by sdanyliv** [comment]
In example that you have used it is filter. Use sample proposed by me with db parameter.
I have no way to test that.

**Comment by Franki1986** [comment]
Sorry but this does not work.
I explain the situation:

```
        [Table("CUSTOMER")]
	public partial class Customer
	{
		[Column("ID"), PrimaryKey,  NotNull] public int    Id { get; set; } 
		[Column(), NotNull] public string Name { get; set; } 
		[Column(),  NotNull] public string FirstName { get; set; } 
		[Column(), Nullable         ] public string Company { get; set; } 
		[Column(),  NotNull] public string ZipCode { get; set; }
		[Column(), NotNull] public string Town { get; set; }
		[Column(), NotNull] public int Status { get; set; }
                
                [ExpressionMethod("HasPermissionImpl")]
                public bool HasPermission { get; set; }
                
                [ExpressionMethod("HasPermissionImpl2")]
                public bool HasPermission2 { get; set; }

                static Expression<Func<Customer, bool>> HasPermissionImpl()
                {
                    return (c) => (c.Status & 2) != 0;
                }

                static Expression<Func<Customer, MyDb, bool>> HasPermissionImpl2()
                {
                    return (c, db) => (c.Status & 2) != 0;
                }
	}
```

```
using(var dbContext = new MyDb())
{
    var result = dbContext.Customers.ToList(); // HasPermission is not in result and the expression is not called

    var result2 = dbContext.Customers.Where(c => c.HasPermission).ToList(); // HasPermission is applied for the where clause, but is not mapped as result field! 
}
```

Even if I use db as parameter, the expression is not called for field result.

**Comment by Franki1986** [comment]
I have created a custom Provider and a custom Sql builder to debug what is happening. An ExpressionMethod is not called for SqlFields and is not mapped to a property. 
I know that you don't like the idea of using string expressions, but there is also a way in entity framework for calculated field expressions over strings : [ef calculated fields](https://docs.microsoft.com/de-de/ef/core/modeling/relational/computed-columns) 

I  played with the linqToDB code and it would be a little change

```
// You can use property names in brackets.
[Column("iif(BinAnd([Status], 2)) != 0, 1, 0)"), IsCalculatedField=true]
public bool HasPermission{get;set;}
```

- ColumnAttribute and ColumnDescriptor have a property IsCalculatedField

- If IsCalculatedField is set, SkipOnInsert and SkipOnUpdate are set to true

- In BasicSqlBuilder in BuildExpression for SqlField, call 'StringBuilder.Append(table).Append('.');' only if IsCalculatedField is false, else replace all property names in brackets with the real sql column name. This would also work for recursive calculated fields.


In this case the resulting select would be:

```
//  [Status] is replaced with t1.STATUS
select iif(BinAnd(t1.STATUS, 2)) != 0, 1, 0) from CUSTOMER t1;
```

**Comment by sdanyliv** [comment]
Thanks for investigation!
Will look at this closer after vacation.

**Comment by Franki1986** [comment]
Hello, something new?

**Comment by sdanyliv** [comment]
I found time to look at this closer, if you do not need inheritance it can be easely done.
We can just add flag Persist to ExpressionMethod and if clas contain such property - we can create simple transformation that initializes object with this property

**Comment by sdanyliv** [comment]
For example:
```cs
db.Customers.ToList()
```
Can be automatically translated to:
```cs
db.Customers.Select(c => 
   new Customer 
   {
       Id = c.Id,
       FirstName = c.FirstName,
      ....
       HasPermission = (c.Status & 2) != 0
   }
).ToList();
```
The following solution has minimal impact on current fuctionality.

**Comment by sdanyliv** [comment]
I don’t think that is the right way.
Here is starting point:
https://github.com/linq2db/linq2db/blob/7148dacb92853746b8936cd29dc02cd174de2a9f/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs#L466
You can create transformation in this place, not sure, but looks like it is right starting point.

**Comment by sdanyliv** [comment]
This approach will not hide power of associations, extensions and other stuff. Linq2db will do other optimizations automatically.

**Comment by Franki1986** [comment]
Ok, no problem I also like the way with the ExpressionMethod, so it is compile safe.
I assume it will be part of version 2. Do you already have plans when it will be released?

**Comment by sdanyliv** [comment]
Really it can be done in 2 hours ;) Maybe less. Just need to switch from other stuff.

**Comment by Franki1986** [comment]
Oh I am sure, but if it is not so far away, I will wait for version 2, I only would have continued with my fork if there would be no chance.. But if it ia so, I will wait a bit, you are doing a good job and working a lot with test scenarios..

**Comment by sdanyliv** [comment]
Maybe you will try to generate Expression.New in place that i have mentioned?

**Comment by Franki1986** [comment]
I will give it a try tomorrow morning.

**Comment by sdanyliv** [comment]
Just call `HasPermission` It should be enough for builder to extract everything automatically.
Corrected sample below:
```cs
db.Customers.Select(c` => 
   new Customer 
   {
       Id = c.Id,
       FirstName = c.FirstName,
      ....
       HasPermission = c.HasPermission
   }
).ToList();
```

**Comment by igor-tkachev** [comment]
Let's add a flag like IsColumn/IsExpressionColumn/IsWhateverColumn to ExpressionMethod attribute. It will cover this case and will not conflict with the library design.

**Comment by Franki1986** [comment]
I debuged the code based on your query: 

```
db.Customers.Select(c => 
   new Customer 
   {
       Id = c.Id,
       FirstName = c.FirstName,
       HasPermission = c.HasPermission
   }
).ToList();
```

This query works only partialy.
As I understand you load the needed column fields and let the expression compile the desired function. So if you map the value for HasPermission, you will have to select also the fields that are used in the expression. So the query above won't work. You have to create it like this:

```
db.Customers.Select(c => 
   new Customer 
   {
       Id = c.Id,
       FirstName = c.FirstName,
       Status = c.Status,
       HasPermission = c.HasPermission
   }
).ToList();
```

I first expected the generated sql to create the expression like this or similar:

`select t.Id, t.FirstName, iif(BIN_AND(t.Status, 2) > 0, 1, 0) as HasPermission from Customers;` 

You generate this:

`select t.Id, t.FirstName, t.Status from Customers;` 

and compile the needed expression after. Just another way, but not like expected.
So everytime you select a calculated field you have to be sure to select even the fields that are used to calculate the field.
So this won't work:

```
db.Customers.Select(c => 
   new Customer 
   {
       Id = c.Id,
       HasPermission = c.HasPermission
   }
).ToList();
```

**Comment by sdanyliv** [comment]
I don’t understand why this do not work. You have to select ALL fields from your class and additional properties with ExpressionMethod.
Sorry i have no chance to check it till Monday.

**Comment by Franki1986** [comment]
I don't know how to explain. Everything works fine with your suggestion if you first select ALL fields. The place you suggested is also the right place and monday I will make a pull request in my fork with the changes. So that ExpressionMethod will have another property IsColumn.
But we have to explain in the documentation that every field that is accesed in the expression method has to be selected. In normal sql code you use those fields only in your calculated expression and don't have to load them too. So if you would calculate an expression based on three or four fields you have to load this three or four fields too. This would have an impact on the data size loaded from db. If you calculate your field on db level only the size of the calculated field is loaded. I don't know if I explained it enough, I will look if I find a better example to explain momday.

**Comment by sdanyliv** [comment]
I understand your point. Will handle it later.

**Comment by sdanyliv** [comment]
@Franki1986, i've created test and found problem that you have mentioned. Make your PR or post code that generates Select and i will finish it. 
There is idea don not materialize columns that marked as `IsColumn = false`, but currently we have issue with that and needs fix.

**Comment by Franki1986** [comment]
Currently I am not on my computer, but here is the code I used.
I am not so in to your code, so there could be parts that are already implemented or that can be simplified...

```
public class ExpressionMethodAttribute : Attribute
	{
		/// <summary>
		/// Creates instance of attribute.
		/// </summary>
		/// <param name="methodName">Name of method in the same class that returns substitution expression.</param>
		public ExpressionMethodAttribute(string methodName)
		{
			MethodName = methodName;
		}

		/// <summary>
		/// Creates instance of attribute.
		/// </summary>
		/// <param name="configuration">Connection configuration, for which this attribute should be taken into account.</param>
		/// <param name="methodName">Name of method in the same class that returns substitution expression.</param>
		public ExpressionMethodAttribute(string configuration, string methodName)
		{
			Configuration = configuration;
			MethodName    = methodName;
		}

		/// <summary>	Creates instance of attribute. </summary>
		/// <param name="configuration">	Connection configuration, for which this attribute should be
		/// 								taken into account. </param>
		/// <param name="methodName">   	Name of method in the same class that returns substitution
		/// 								expression. </param>
		/// <param name="isColumn">			True if the property should be mapped with this expression
		/// 								Method. </param>
		public ExpressionMethodAttribute(string configuration, string methodName, bool isColumn)
		{
			Configuration = configuration;
			MethodName = methodName;
			IsColumn = isColumn;
		}

		/// <summary>
		/// Mapping schema configuration name, for which this attribute should be taken into account.
		/// <see cref="ProviderName"/> for standard names.
		/// Attributes with <c>null</c> or empty string <see cref="Configuration"/> value applied to all configurations (if no attribute found for current configuration).
		/// </summary>
		public string Configuration { get; set; }

		/// <summary>
		/// Name of method in the same class that returns substitution expression.
		/// </summary>
		public string MethodName    { get; set; }

		/// <summary>	Indicates whether a property should be mapped with this expression Method. </summary>
		/// <value>	True if the property should be mapped with this expression Method. </value>
		public bool IsColumn { get; set; }
	}
```

```
		#region BuildSelectAllFieldsExpression

		/// <summary>	Creates a select expression based on the expression.Value <see cref="ITable"/>, that selects all fields
		/// 			of the item type of the <see cref="ITable"/>.</summary>
		/// <param name="expression"> The <see cref="ConstantExpression"/> containing the <see cref="ITable"/> in the expression Value. </param>
		/// <returns>	Returns the selecting <see cref="MethodCallExpression"/> on success, else the original passed expression. </returns>
		private static Expression BuildSelectAllFieldsExpression(ConstantExpression expression)
		{
			if (!(expression.Value is ITable))
			{
				return expression;
			}
			Type itemnType = null;
			Type iTableType = expression.Value.GetType();
			if (iTableType.GetTypeInfo().IsGenericType && iTableType.GetGenericArguments().Length == 1)
			{
				itemnType = iTableType.GetGenericArguments()[0];
			}
			if (itemnType == null)
			{
				return expression;
			}
			var ent = MappingSchema.Default.GetEntityDescriptor(itemnType);
			var members = ent.TypeAccessor.Members;
			List<MemberAccessor> selectingMembers = new List<MemberAccessor>();
			bool hasCalculatedField = false;
			foreach (MemberAccessor mInfo in members)
			{
				if (ent.Columns.Any(c => c.MemberName == mInfo.Name))
				{
					selectingMembers.Add(mInfo);
				}
				else
				{
					var expMethodAttr = MappingSchema.Default.GetAttributes<ExpressionMethodAttribute>(itemnType, mInfo.MemberInfo);
					if (expMethodAttr.Length > 0 && expMethodAttr.Any(e => e.IsColumn))
					{
						hasCalculatedField = true;
						selectingMembers.Add(mInfo);
					}
				}
			}
			if (!hasCalculatedField)
			{
				return expression;
			}
			var xParameter = Expression.Parameter(itemnType, "obj");

			var xNew = Expression.New(itemnType);

			var bindings = selectingMembers.Select(obj =>
			{
				var prop = Expression.PropertyOrField(xParameter, obj.Name);
				return Expression.Bind(obj.MemberInfo, prop);
			});

			var xInit = Expression.MemberInit(xNew, bindings);

			var lambda = Expression.Lambda(xInit, xParameter);

			var result = Expression.Call(typeof(Queryable), "Select", new Type[] { xParameter.Type, lambda.Body.Type }, expression, Expression.Quote(lambda));

			return result;
		}
		#endregion
```

```
#region ExposeExpression

		Expression ExposeExpression(Expression expression)
		{
			return expression.Transform(expr =>
			{
				switch (expr.NodeType)
				{
					case ExpressionType.MemberAccess:
						{
							var me = (MemberExpression)expr;
							var l  = ConvertMethodExpression(me.Member.ReflectedTypeEx(), me.Member);

							if (l != null)
							{
								var body  = l.Body.Unwrap();
								var parms = l.Parameters.ToDictionary(p => p);
								var ex    = body.Transform(wpi =>
								{
									if (wpi.NodeType == ExpressionType.Parameter && parms.ContainsKey((ParameterExpression)wpi))
									{
										if (wpi.Type.IsSameOrParentOf(me.Expression.Type))
										{
											return me.Expression;
										}

										if (DataContextParam.Type.IsSameOrParentOf(wpi.Type))
										{
											if (DataContextParam.Type != wpi.Type)
												return Expression.Convert(DataContextParam, wpi.Type);
											return DataContextParam;
										}

										throw new LinqToDBException($"Can't convert {wpi} to expression.");
									}

									return wpi;
								});

								if (ex.Type != expr.Type)
									ex = new ChangeTypeExpression(ex, expr.Type);

								return ExposeExpression(ex);
							}

							break;
						}

					case ExpressionType.Constant :
						{
							var c = (ConstantExpression)expr;

							// Fix Mono behaviour.
							//
							//if (c.Value is IExpressionQuery)
							//	return ((IQueryable)c.Value).Expression;

							if (c.Value is IQueryable && !(c.Value is ITable))
							{
								var e = ((IQueryable)c.Value).Expression;

								if (!_visitedExpressions.Contains(e))
								{
									_visitedExpressions.Add(e);
									return ExposeExpression(e);
								}
							}
							if (c.Value is ITable)
							{
								var e = BuildSelectAllFieldsExpression(c);
								if (e != c)
								{
									if (!_visitedExpressions.Contains(c))
									{
										_visitedExpressions.Add(c);
										return ExposeExpression(e);
									}
								}
							}
							break;
						}
				}

				return expr;
			});
		}

		#endregion
```

**Comment by sdanyliv** [comment]
Great we are working on implementation. So, be patient ;)

**Comment by Franki1986** [comment]
Let me know if I can do something..

**Comment by igor-tkachev** [comment]
Implemented ExpressionMethodAttribute.IsColumn parameter.

**Comment by sdanyliv** [comment]
Everything that are merged to master is going to version 2.
You can download latest package from MyGet.

**Comment by Franki1986** [comment]
I see, thanks!!
