### ISSUE TITLE
how to linqtodb  for .net core 2.0 using visual studio 2017

### ISSUE THREAD

**Issue by fopsdev** [linq2db/linq2db#1013]
hi there
i would like to play a bit with linqtodb.
i've installed 2.00 beta4 from nuget. 
but i'm not able to use the t4 templates which i would like to run over my sql server db.
so i have a very basic question. 
is it ready for use with .net core 2.0 inside visual studio 2017?
and what is this linqtodb.core for? is it needed as well?
and if its only the model generation that fails can i install an older version just for generating the models?
thanks for any enlightment.

**Comment by fopsdev** [comment]
i've copied the files manually and that helped.

**Comment by sdanyliv** [comment]
Anyway we have to check that.

**Comment by MaceWindu** [comment]
@ili looks like you were working on this recently?

**Comment by MaceWindu** [comment]
Should work with latest myget packages (should be up in about hour)
