### ISSUE TITLE
Proposed .NETCore implementations for oracle

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#1015]
Greetings!

So in the past few months, there have finally become some options in regards to having netstandard2.0 support for oracle. First there is commercial support in the form of DevArts commercial connector (https://www.devart.com/dotconnect/oracle/), and just a few days ago, oracle rolled out their public beta of the Oracle.ManagedDataAccess component (http://www.oracle.com/technetwork/topics/dotnet/downloads/odpnetcorebeta-4077982.html).

As far as I can tell, the SDK/API seems to be compatible with managed data access. The only difference here is that DevArt connector has a different assembly name.

In looking at the existing master branch, it seems like beginning to support Oracle could be as simple as the following...

1. Add additional assembly name to list of valid provider names in DetectProviderNames()
2. Add one additional clause to ProviderDetector constructor (to catch "Oracle.DevArt")
3. Remove the "Remove" clause of the tests csproj file, so as to allow oracle tests potentially running in the unit test runs as a part of the .net core 2.0 runs
4. Update oracle tests so as tests run correctly in 2.0 runs (recall complaints about mscorlib, and references to native driver stuff that has no environment pre-processor directive wrapped around it)
4. Ensure all unit tests pass as well as they did before
5. "Profit?"

I had approached this as a totally separate new driver, but there's enough about how to appropriately test, as well as some hard dependencies on "Proxy" which appears to not be public. Also with everything but the base namespace being identical, feel like there really is no point in re-writing all the tests etc (especially since it appears the oracle driver already has support for utilizing base namespace etc)

I'm curious if this sounds about right (assuming all we're talking about here is assembly names, and that the SDK/Namespaces are just compatible out of the box.

I'm also curious if you guys are interested in seeing a pull request for this work. I'm hurting to be able to deploy my oracle consuming services in docker container and need some mechanism.

**Comment by ronnyek** [comment]
As an update, I just removed hard fully qualified paths to oracle types, and added reference to the beta driver. Also needed to remove the oracle tests from netcoreapp1.0, only and was able to pass all the unit tests out of the gate except , except one condition in the oracle TestDataTypes test to do with LOB's. I'm debugging that test now, but could be a legitimate bug in the new dotnet core provider.

**Comment by ronnyek** [comment]
[Proposed Changes for oracle driver](https://github.com/ronnyek/linq2db/commit/ef0414e10cf0aee66f8cea26ce799858db3f494e)

Only one test fails, and fails for me for the .net 4.5.2 run as well (so it may be related to database configuration etc.). You think this would be an acceptable pull request?

**Comment by ronnyek** [comment]
Also, probably wouldn't be my choice to include DLL as a redist, but oracle hasn't yet put this into their nuget feed, so that part would be temporary

**Comment by sdanyliv** [comment]
@ronnyek, start with PR, we will review that.

**Comment by ronnyek** [comment]
Pull Request #1016, I see pull appveyor builds failing etc, but seem like a bunch of previous pull requests are doing the same thing?

**Comment by sdanyliv** [comment]
Yes, something happened with Travis build.

**Comment by sdanyliv** [comment]
Merged
