### ISSUE TITLE
Problem with Update when using inheritance

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1017]
If you look at my Demo Data Model in Pull Req 

https://github.com/linq2db/linq2db/blob/42888f042764cb5f2f1aa141b43313e093b4f4eb/Tests/Linq/UserTests/Issue994Tests.cs

If you will do this:

		using (var db = new TestDataConnection())
		{
			var dog = db.GetTable<Dog>().First();
			db.Update(dog);
			db.Update((Animal)dog);
		}

the first Update will work, the second one not!

**Comment by jogibear9988** [comment]
Problem is in QueryRunner.Update.cs

it uses type of "T", but problem is, you can also use a list of the base class, so it is possible that there are different types in update

**Comment by jogibear9988** [comment]
@sdanyliv @igor-tkachev @ili @MaceWindu  need help with this!

**Comment by jogibear9988** [comment]
I've implemented a fix for this, maybe someone of you can look

**Comment by jogibear9988** [comment]
I'm not sure if its the correct way to fix. Maybe someone wanted to force Update<Type>(obj) to use the "Type" instead of the object type, this will then not work any more.

**Comment by jogibear9988** [comment]
Problem with my change is now that something like:

		var bdog = new SuperBadDog();
		db.Insert((Dog)bdog);

will not work if only a mapping for dog exists...

**Comment by jogibear9988** [comment]
maybe we should introduce additional Update, Insert,... overloads wich can get a type parameter?

**Comment by sdanyliv** [comment]
Sorry for delay will find time to look at.

**Comment by jogibear9988** [comment]
thx

**Comment by jogibear9988** [comment]
if you have questions, feel free to ask!

**Comment by jogibear9988** [comment]
@sandyliv: anything I should or could help?
cause of tjemany failing tests, have you also looked at #1019 ?

**Comment by sdanyliv** [comment]
@jogibear9988, i'm really too busy this month (

**Comment by hardhub** [comment]
What should be made by code? Only animal table updated?
