### ISSUE TITLE
nuget install of linqtodb.sqllite fails

### ISSUE THREAD

**Issue by fopsdev** [linq2db/linq2db#1020]
install nuget ends with:

Package restore failed. Rolling back package changes...

(couldn't find further debug info...)
### Environment details
linq2db version: 2.0.0  beta 4
Database Server: SQLLite 

![image](https://user-images.githubusercontent.com/5448300/36590894-75de7742-1890-11e8-810c-fa181a02d540.png)

**Comment by sdanyliv** [comment]
Looks like you have to update your UWP tooling for supporting .NET Standard 2.0.
https://blogs.msdn.microsoft.com/dotnet/2017/08/25/uwp-net-standard-2-0-preview/

Just tested and package successfully installed.

**Comment by fopsdev** [comment]
@sdanyliv thanks, that solved the issue :+:
