### ISSUE TITLE
basic question on how to include eg. NotifyDataErrorInfo.ttinclude into template generation

### ISSUE THREAD

**Issue by fopsdev** [linq2db/linq2db#1021]
hi there
first thanks for this wonderful library, it really helps me to get up to speed with my wpf rich client development.
speaking of wpf development.
i really would like to have:

- NotifyDataErrorInfo.ttinclude
- NotifyPropertyChanged.ttinclude
- DataAnnotations.ttinclude

included in my generation process.
but i'm not sure how to enable them?

### Environment details
linq2db version: *2.0.0 beta 4*  
Database Server: *sqllite 3*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
@fopsdev, thanks for the kind words!
Some of them has been used In LinqPad driver: https://github.com/linq2db/linq2db.LINQPad/blob/master/Source/ConnectionViewModel.tt

**Comment by fopsdev** [comment]
@sdanyliv thanks, that looks like a great resource.
i've tried to get the DataAnnotations for my columns generated but i'm failing.
i've just included the DataAnnotations.include in my main.tt file. But there are no annotations generated
it really looks like i'm missing some basic information to make this work :)

```
...
<#@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"  #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\DataAnnotations.ttinclude"  #>
...

```

**Comment by sdanyliv** [comment]
@fopsdev, let's synchronize. What you are trying to achieve?
I'm not familiar with these templates, so i need to check it by myself, but i need more detailed input.
From start: usually we use T4 templates for generating DataModel from database (sample video): https://www.youtube.com/watch?feature=player_embedded&v=Qc-5UpMYQO0
If you need templates for generating ViewModel - i need more detailed input.
Thanks.

**Comment by fopsdev** [comment]
@sdanyliv thanks for catching up on this
i would like to generate ViewModel classes that i can use in my wpf application.
i would like to use a mvvm approach. the properties ideally would use setters like:
```
 public int LimbsRemaining
    {
        get { return this.limbsRemaining; }
        set { this.SetProperty(ref this.limbsRemaining, value); }
    }
```
and therefore trigger the change automatically.
as well i would put in some validation which should already take care of:
[required]
[fieldlength]
which could be extracted as well from the metadata of the database
does this make sense?

**Comment by fopsdev** [comment]
if i don't use the integrated .ttincludes i could also go with a custom baseclass approach
i somehow start to prefer that.
found a somewhat nice baseclass which i could use:
https://rehansaeed.com/model-view-viewmodel-mvvm-part4-inotifydataerrorinfo/
that would result in viewmodels like:
```
public class ZombieViewModel : NotifyDataErrorInfo<ZombieViewModel>
{
    private string name;
    private int limbsRemaining;
 
    static ZombieViewModel()
    {
        Rules.Add(new DelegateRule<ZombieViewModel>(
            "Name",
            "Name cannot be empty.",
            x => !string.IsNullOrEmpty(x.Name)));
        Rules.Add(new DelegateRule<ZombieViewModel>(
            "LimbsRemaining",
            "A zombie can't have less than zero limbs.",
            x => x.LimbsRemaining >= 0));
        Rules.Add(new DelegateRule<ZombieViewModel>(
            "LimbsRemaining",
            "A zombie can only have up to four limbs.",
            x => x.LimbsRemaining <= 4));
    }
 
    public string Name
    {
        get { return this.name; }
        set { this.SetProperty(ref this.name, value); }
    }
 
    public int LimbsRemaining
    {
        get { return this.limbsRemaining; }
        set { this.SetProperty(ref this.limbsRemaining, value); }
    }
}
```
so if i would like to use this baseclass i need to know:
- how i can add a baseclass to the model generation
- change the setter to use the SetProperty(...)
- add those rules depending on the metadata
i'm not familiar with t4 template generation but that sound doable right?

**Comment by sdanyliv** [comment]
Check readme:
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates
1. `BaseEntityClass` - base class for entities
2. Not checked, but if you change in your T4 template `GetBody` and `SetBody` for columns
  'GetColumn("Person", "PersonID") .GetBody.Add("some line")', then tempate will produce custom body.
3. Same as with body, there are additional properties, if you set them, then attributes will be generated. For example DataAnnotations.ttinclude supports the following properties.
```cs
partial class Property
{
	public string DisplayName;
	public bool   IsRequired;
	public string IsRequiredMessage;
	public int    StringLength;
	public string StringLengthMessage;
}
```
NotifyPropertyChanged.ttinclude - contains
```cs
partial class Property
{
	public bool         IsNotifying;
	public List<string> Dependents = new List<string>();
}
```
```cs
GetColumn("Person", "PersonID") .DisplayName = "Some Diaplay Name";
GetColumn("Person", "PersonID") .IsNotifying = true;
GetColumn("Person", "PersonID") .Dependents.Add("SomeOtherProp");
```
For sure you have to walk through all columns and convert current properties to specific for each template.

**Comment by sdanyliv** [comment]
Something like this before generation:
```cs
foreach (var table in Tables.Values)
{
   foreach(var column in table.Columns.Values)
  {
     column.IsNotifying = true;
     if (!column.CanBeNull)
        column.IsRequired = true;
     ... // fill other needed fields
  }
}
```

**Comment by fopsdev** [comment]
@sdanyliv 
thanks a lot for your help. didn't know that i first have to set the properties :)
will give it a shot later this week

**Comment by sdanyliv** [comment]
Me too, just analysed sorces ;)
Loks like Ihor invented very clever way how to extend models. BTW, you can set attributes by yourself. Analyse how it is done in DataAnnotations.ttinclude

**Comment by MaceWindu** [comment]
Closing answered/non-actionable issues. Feel free to reopen/continue discussion if it wasn't anwsered.
