### ISSUE TITLE
OpenAsync not being used during the query building phase resulting in a blocking call to Connection.Open

### ISSUE THREAD

**Issue by TheRubble** [linq2db/linq2db#1023]
Recently I've been load testing a .NET Core application running inside a docker container and very quickly (under 15 concurrent connections), I start seeing the following error's in the logs.

```c#
Error when load testing:
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred
while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that 
the instance name is correct and that SQL Server is configured to allow remote connections. (provider: 
TCP Provider, error: 40 - Could not open a connection to SQL Server) at 
System.Data.ProviderBase.DbConnectionPool.TryGetConnection(...
```

It appears to happen due to a low amount of sql connections in the thread pool, and blocking calls to the DB layer effectively deadlocking when put under a sudden burst of traffic.

A suggestion is to use OpenAsync on the db connection to help alleviate the problem, however I can't see this is possible when using Linq2DB with linq style syntax.

```c#
var results = from DataContext.Products p Where p.Id == 1 select p;
var product = results.FirstOrDefaultAsync(cancellationToken);
```

During the query generation phase it's opening the database without using Async and hence causing a block. There is an underlying issue when running on linux [Issue .NET Core](https://github.com/dotnet/corefx/issues/25620), which suggests a potential patch is on the way in 2.0.6 and 2.1. In short sporadic DNS resolution times are causing pain, I've verified it's not an issue when running the code on a windows machine.

The patch should help someway but calling async throughout I imagine would be the long term preference.

I'm more than happy to help out with addressing the issue, but thought I'd check my thinking first incase I'd missed something.

If I use the ExecuteAsync extensions directly, looking at the code this wouldn't have the same blocking issue but I'd lose the query generation stuff that's really useful.

As a mitigation I've manually raised the minimum connections in the connection pool, and also raised the min thread count in the .NET thread pool, but it's a temp work around and clearly doesn't scale as things should.

### Environment details
linq2db.core version: *1.10.2*  
Database Server: SQL Server 2017  
Operating system: Docker
Framework version: .NET Core 2.0

**Comment by sdanyliv** [comment]
Bug confirmed.
@igor-tkachev, there are steps to reproduce:

Everyting starts from here:
https://github.com/linq2db/linq2db/blob/1208921e0a9afa0fc97f7fcd279847418f4f3478/Source/LinqToDB/Data/DataConnection.QueryRunner.cs#L469 
Then after several steps it calls dataConnection.Command property which calls dataConnection.Connection which opens connection without **async** 

https://github.com/linq2db/linq2db/blob/1208921e0a9afa0fc97f7fcd279847418f4f3478/Source/LinqToDB/Data/DataConnection.QueryRunner.cs#L232

And problematic line in async variant
https://github.com/linq2db/linq2db/blob/1208921e0a9afa0fc97f7fcd279847418f4f3478/Source/LinqToDB/Data/DataConnection.cs#L867

Looks like this part needs refactoring.

**Comment by TheRubble** [comment]
Hi,

Thanks for the feedback, more than happy to give it a crack. On a side note there is a work around that I've got working and it's quite simple.

```c#
 await this.ExecuteAsync("select GETDATE()", cancellationToken);
```
If you run this before an connection is made, you can get the connection created as expected. Don't get me wrong it's not ideal but my throughput when from 17 rps, to 420 rps.

**Comment by sdanyliv** [comment]
Yes, in this case connection is cached and all work as expected. 
We have to fix that.

**Comment by TheRubble** [comment]
Isn't this going to cause quite a ripple in the code base? I've just looked at the source and I think it'd mean a mass migration to DBConnection from IDBConnection in order to get OpenAsync amongest other things.

Like I said more than happy to help out.

**Comment by sdanyliv** [comment]
Let's @igor-tkachev to decide how to refactor this. Async support is quite new functionality, and we can see has some weaknesses.
