### ISSUE TITLE
Firebird: should use true/false literals for boolean fields instead of 1/0

### ISSUE THREAD

**Issue by gryzunov** [linq2db/linq2db#1024]
linq2db generates following SQL

``` sql
-- Firebird
SELECT
	t1.ID,
	t1.Name,
	t1.IsDeleted
FROM
	Product t1
WHERE
	1 <> t1.IsDeleted
```
and it results to exception:
```
FirebirdSql.Data.FirebirdClient.FbException
  HResult=0x80004005
  Message=conversion error from string "1"
  Source=FirebirdSql.Data.FirebirdClient
  StackTrace:
   at FirebirdSql.Data.FirebirdClient.FbCommand.Fetch() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 651
   at FirebirdSql.Data.FirebirdClient.FbDataReader.Read() in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbDataReader.cs:line 207
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__2b`1.MoveNext() in c:\projects\linq2db\Source\Linq\QueryRunner.cs:line 329
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in c:\users\bambr\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 27
```

### DDL
``` sql
CREATE TABLE PRODUCT (
    ID         INTEGER NOT NULL,
    NAME       VARCHAR(64) NOT NULL,
    ISDELETED  BOOLEAN NOT NULL
);
```

### Code example

```c#
using System.Linq;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace ConsoleApp1
{
    [Table]
    public class Product
    {
        [PrimaryKey]
        public int ID { get; set; }

        [Column(CanBeNull = false, Length = 64)]
        public string Name { get; set; }

        [Column(CanBeNull = false)]
        public bool IsDeleted { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var conn = new DataConnection())
            {
                var products = from p in conn.GetTable<Product>() where !p.IsDeleted select p;
                var list = products.ToList();
            }
        }
    }
}

```
Valid SQL should be
``` sql
-- Firebird
SELECT
	t1.ID,
	t1.Name,
	t1.IsDeleted
FROM
	Product t1
WHERE
	true <> t1.IsDeleted
```

### Environment details
linq2db version: *1.10.0*  
Database Server: *Firebird 3.0.3*  
Database Provider: *FirebirdSql.Data.FirebirdClient 5.12.1*
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by Franki1986** [comment]
You are right with Firebird version > 3.0.  For fixing you problem did you try to use the 'DbType' of the Column attribute?

**Comment by gryzunov** [comment]
Yes, I tried 
```c#
        [Column(CanBeNull = false, DbType = nameof(DbType.Boolean))]
        public bool IsDeleted { get; set; }

        [Column(CanBeNull = false, DbType = nameof(DbType.Int16))]
        public bool IsDeleted { get; set; }

        [Column(CanBeNull = false, DbType = nameof(DbType.String))]
        public bool IsDeleted { get; set; }
```
with no luck.

**Comment by Franki1986** [comment]
Updated my answer..

**Comment by gryzunov** [comment]
Your workaround with custom sql converter did the work, thank you.
But I think you should consider add native support for boolean fields in Firebird >= 3.0 in some future version of linq2db.

**Comment by Franki1986** [comment]
I think you should reopen it, this is still only a workaround. Maybe edit your title to Firebird > version 3.

**Comment by sdanyliv** [comment]
It is still a problem. We have to handle Firebird version automatically.

**Comment by Usaga** [comment]
Any progress on this issue?

**Comment by sdanyliv** [comment]
@Franki1986, could you help in fixing this?

**Comment by Franki1986** [comment]
Do you already handle provider versions ? Or could this be done by specific db request ?
`SELECT rdb$get_context('SYSTEM', 'ENGINE_VERSION') 
from rdb$database;`

**Comment by sdanyliv** [comment]
Let’s start from global configuration, since it will take less efforts. Then we have to create Provider version and Provider Detector.

**Comment by Franki1986** [comment]
I Will have a look

**Comment by Franki1986** [comment]
What about if you want to support SMALLINT (or 1 and 0) and BOOLEAN as bool? Should this be possible? Or is it only a global configuration. I am not sure that people will upgrade db server and change all current column types.

**Comment by Franki1986** [comment]
Basically I have 4 changes:

[FirebirdConfiguration.cs](https://github.com/linq2db/linq2db/blob/ca56417ada5bf74bfc232bfe931bc2a2d6586474/Source/LinqToDB/DataProvider/Firebird/FirebirdConfiguration.cs#L24):

```
/// <summary>
/// Specifies that Firebird supports boolean types. Availiable from version 3.0.
/// </summary>
public static bool SupportBooleanType { get; set; }
```

[FirebirdDataProvider.cs](https://github.com/linq2db/linq2db/blob/ca56417ada5bf74bfc232bfe931bc2a2d6586474/Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs#L91):

```
if (value is bool)
{
	if (FirebirdConfiguration.SupportBooleanType)
	{
		dataType = dataType.WithDataType(DataType.Boolean);
	}
	else
	{
		value = (bool)value ? "1" : "0";
		dataType = dataType.WithDataType(DataType.Char);
	}
}
```
[FirebirdSqlBuilder.cs](https://github.com/linq2db/linq2db/blob/ca56417ada5bf74bfc232bfe931bc2a2d6586474/Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs#L19):

```
public FirebirdSqlBuilder(ISqlOptimizer sqlOptimizer, SqlProviderFlags sqlProviderFlags, ValueToSqlConverter valueToSqlConverter)
	: base(sqlOptimizer, sqlProviderFlags, valueToSqlConverter)
{
	if (FirebirdConfiguration.SupportBooleanType)
	{
		valueToSqlConverter.SetConverter(typeof(Boolean), (sb, dt, v) => sb.Append((bool)v ? "true" : "false"));
	}
}
```
[FirebirdSqlBuilder.cs](https://github.com/linq2db/linq2db/blob/ca56417ada5bf74bfc232bfe931bc2a2d6586474/Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs#L115):

```
// BOOLEAN type available since FB 3.0, but FirebirdDataProvider.SetParameter converts boolean to '1'/'0'
// so for now we will use type, compatible with SetParameter by default
case DataType.Boolean       :
	if (!FirebirdConfiguration.SupportBooleanType)
	{
		StringBuilder.Append("CHAR");
	}
	break;
```


But this works only global, for all boolean Types..

**Comment by sdanyliv** [comment]
How about to create old good PR? :)

**Comment by Franki1986** [comment]
Yea, wanted to, but stick with my master. Can I delete my fork to open another or will it break with my current PR for Skip values?

**Comment by sdanyliv** [comment]
You can create branch from master's commit which starts before your changes in master and create PR.
Next time ALWAYS create branch for each PR.
