### ISSUE TITLE
GetTable()-like method with name of table parameter

### ISSUE THREAD

**Issue by beercsaba** [linq2db/linq2db#1025]
Multiple tables with different names can be created for an entity type by using DataExtensions.CreateTable<...>(...) method, which is very cool especially for (unit-, or integration-) testing purposes.
But I did not find any GetTable<...>(...)-like method where i could define the name of the table (to override the default one defined by Table attribute), so i can't query these alternative tables just through sql.
How can i query type-safely these alternatively-named tables?

(The same with name of the schema could be useful too...)

**Comment by beercsaba** [comment]
I've found the way... the  ITable<...>.TableName(..) method...   Great!

**Comment by sdanyliv** [comment]
@beercsaba, our library is highly customizable. If you found blocker, just ask how to do smtng using linq2db. And maybe we have better solution ;)

**Comment by beercsaba** [comment]
Hi @sdanyliv!

I agree with You, Your library is well architected and easy to use, highly customizable. 
(I've found it about 1 week ago, and i like it very much!)
But in the same time not complete and not fully consistent. 
it is under continous active development, under continous evolution, and it is a pleasure for me to use it! ;)

about my task:
there are some Independent entities (tables without foreign keys), which are accessed from multiple components of the application.
I'm writing unit tests for each of these scenarios.
I don't want to create a different database or schema for these scenarios, there is no need for this complexity, because the tables are Independent, so it would be enough to create many tables for one entity.  Each of them can be in the same database and schema without any interference or problem.
Unit tests could be simpler in this way, i think you understand it.

To implement the scenarios i need the whole CRUD functionality. 
i've found, that
- Read can be achieved by GetTable<>().TableName(..) 
- Insert can be achived by DataConnection.Insert<>(entity, tableName=...)
- Update, Delete : i did not find a handy way...
- (InsertWIth...Identity would be also very useful..

Here comes the partial inconsistency of the library i've found and i've described at #1026 
(in short: DataExtensions.Insert handles database/schema/table-name overrides, but Update, Delete does not.)

i can send the code in private, if you would like to see it...

Thank you for your hard work to make linq2db better and better!

**Comment by jogibear9988** [comment]
There are also Update and Delete Statements for the object returned by GetTable! Does there the TableName override work?

**Comment by beercsaba** [comment]
Maybe it Works but somewhat magic setter Expressions must be passed to it and quite hard to use for generic purpose instead of simply pass the entity instance to it.
Or there is something i did not find out...
