### ISSUE TITLE
InsertWithIdentity..., Update and Delete with tablename, schemaname, databasename overrides (like Insert)

### ISSUE THREAD

**Issue by beercsaba** [linq2db/linq2db#1026]
DataExtensions.Insert has a variant where the tablename, schemaname and databasename can be overridden.
InsertWithIdentity..., Update and Delete should also have a variant like this.

Implementation: 
- CreateQuery method in QueryRunner.Insert class has tableName, schemaName and databaseName parameters and uses them correctly.
- CreateQuery method in QueryRunner.insertWithIdentity...,  QueryRunner.Update or QueryRunner.Delete has no parameters like these...

**Comment by sdanyliv** [comment]
From start check this issue:
https://github.com/linq2db/linq2db/issues/987
If you still need new API, it will be good to propose exact interface for these methods and unit tests.

**Comment by beercsaba** [comment]
Hi @sdanyliv!
workarounds described in #987 could help, but a more elegant way would be far better :)
And this elegant way is already implemented in DataExtensions.Insert, but the very same thing is not implemented in DataExtensions.Update, Delete and InsertWith...Identity variants.
There is nothing to invent, maybe exactly the same code would fit (or with minimal obvious modifications) in these other extension methods to make them consistent.

in code:
QueryRunner.Insert.CreateQuery(..) method has these tableName, databaseName, schemaName parameters and contains these rows:
`if (tableName    != null) sqlTable.PhysicalName = tableName;`
`if (databaseName != null) sqlTable.Database     = databaseName;`
`if (schemaName   != null) sqlTable.Schema       = schemaName;`

but QueryRunner.Update.CreateQuery(...) does not, it uses simply the names defined in its sqlTable instance (which comes from attributes, i think)

so IMHO, if these 3 parameters and these 3 lines of code would be added into every QueryRunner.xxx.CreateQuery method, then
- it would be elegant enough
- it would be consistent in itself

What do You think?

(or should i implement it and create a pull request?)

**Comment by sdanyliv** [comment]
@beercsaba, PR is always wellcome ;)

**Comment by beercsaba** [comment]
short and quite essential answer  :)

**Comment by sdanyliv** [comment]
From start just post API interface.

**Comment by sdanyliv** [comment]
Currently we are under high load, and help is very appreciated ;)

**Comment by sdanyliv** [comment]
There is sample API, shown on Update operation (same for others) :

**First variant**
```cs
public static int Update<T>([NotNull] this IDataContext dataContext, T obj, 
   string tableName = null, string databaseName = null, string schemaName = null)

// usage
db.Uppdate(obj, "OtherName", "DatabaseName");
```
**Second variant** - based on configured table
```cs
public static int Update<T>([NotNull] this ITable<T>, T obj) 

// usage
db.GetTable<Person>().TableName("OtherName").DatabaseName("DbName").Update(obj);
```
I like second variant because it is extendable and for example can be used with temp tables 
```cs
var tempTable = db.CreateTable<Person>("#TempTable");
tempTable.Update(obj);
```

**Comment by beercsaba** [comment]
Hi @sdanyliv,

i've done with the code, but sadly i have no time to step through the whole PR-creating process documented at your [guide](https://linq2db.github.io/articles/contrib.html) :(
may i create a branch and push my modifications there?

**Comment by sdanyliv** [comment]
It is better to create branch in your fork and create pull request. Then we will pickup your changes.

**Comment by sdanyliv** [comment]
If you are new in github, just download their Desktop version. It has everything for creating PR.

**Comment by beercsaba** [comment]
Hi @sdanyliv!
I've spend some time on preparing a PR (some cleanup, a test, etc...) in the last 2 days.
I've originally started the implementation in this repo and i did not switch to a fork yesterday.
Could you please give me permission to push and create a PR?

**Comment by jogibear9988** [comment]
Why dont you createa fork, push your changes to it and create a pull req?

**Comment by beercsaba** [comment]
why to create a fork (and later delete it) because of a single PR?
It's simpler for me to do it "in-place" :)

**Comment by sdanyliv** [comment]
You have to learn github way. There are many documentations.
Otherwise - send patch.

**Comment by beercsaba** [comment]
i'm on my way of learning the github way :)

**Comment by sdanyliv** [comment]
You do not need to delete fork ;) it’s your repository and you can play with your changes. And it is easies way to propose your suggestions for us.
Thanks for help!

**Comment by beercsaba** [comment]
there is a pull request with my simple implementation: #1042 
@sdanyliv started to review it, any reviews are welcome!
