### ISSUE TITLE
Replicate Left Join in Sql

### ISSUE THREAD

**Issue by felixvandal** [linq2db/linq2db#1029]
Hello there,

i stroll around the joins section but not where there is mention on how to replicate the fellowing sql code:

select tbl1.name, tbl2code
from tablePotato as tb1
left join tableTomato as tb2
on tb1.id = tb1.category

i know the exemple does not make anysense, but i want to get data from both table when i join them
i have tried the code here : https://linq2db.github.io/articles/Join-Operators.html#left-join
all those exemple only get result from one table
is there a way to do what i need?

Edit 1:
I now realise that i could move around the problem with a view.
With ITable i can reference a view, but that means i have to create a view for every scenario of cross reference that could happen.
Can we create a view with Linq2Db? Did i missed something with the join statement?

**Comment by Franki1986** [comment]
I am not shure what you want for end result. But a left join should work to get all potato and matching tomatoes.

`var query = from p in db.potatoes join t in db.tomatoes on p.id equals p.CategoryID  select new { p, t} `

**Comment by felixvandal** [comment]
Thank you for the tip.
I am sorry for the crude exemple and thank you for understanding it anyway XD.
I was missing the part with the select new{p,t}
For some reason i missed the Join operator on multiple columns part of the doc
