### ISSUE TITLE
Method DbConnection.BeginTransaction must return value

### ISSUE THREAD

**Issue by andrewvk** [linq2db/linq2db#104]
Method DbConnection.BeginTransaction must return object, that implements IDisposable and has Commit method. Typical use case:

``` c#
using (var tx = db.BeginTrabsaction())
{
  // Do smth
  tx.Commit();
}
```

**Comment by Shane32** [comment]
@sdanyliv @igor-tkachev I ran into this issue today; I wrote code `dataContext.BeginTransactionAsync(true, default)` and the transaction did not auto-commit.

I suggest that for version 4, we either: (a) remove the dead argument; or (b) set argument default to `false` and throw an exception if it is `true`.  I would be happy to submit a pull request if either of these options seem viable.

For reference, here is the current method:
```cs
		/// <summary>
		/// Starts new transaction asynchronously for current context with default isolation level.
		/// If connection already has transaction, it will be rolled back.
		/// </summary>
		/// <param name="autoCommitOnDispose">Not supported, see <a href="https://github.com/linq2db/linq2db/issues/104">issue</a>.</param>
		/// <param name="cancellationToken">Asynchronous operation cancellation token.</param>
		/// <returns>Database transaction object.</returns>
		public virtual async Task<DataContextTransaction> BeginTransactionAsync(bool autoCommitOnDispose = true, CancellationToken cancellationToken = default)
		{
			var dct = new DataContextTransaction(this);

			await dct.BeginTransactionAsync(cancellationToken).ConfigureAwait(Common.Configuration.ContinueOnCapturedContext);

			return dct;
		}
```

**Comment by Shane32** [comment]
I'm assigning this to the 4.0 milestone so it is not forgotten -- if we want to make any API changes, now's the time.

**Comment by Shane32** [comment]
As stated elsewhere in this issue, I would agree that it makes no sense to have 'auto-commit on dispose' in the first place, since an exception thrown within a transaction scope should always rollback and never auto commit.

**Comment by MaceWindu** [comment]
It's already removed in v4 : https://github.com/linq2db/linq2db/pull/2941

**Comment by Shane32** [comment]
Sorry, was looking at the master branch!  my bad!
