### ISSUE TITLE
Different mapping for database versioning

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1040]
If you have a database schema that on time to time changes, e.g. columns are added to tables or deleted from tables. You have different versions of the same database.
Now if you have a mapping based on a current database version, but want to support old databases, is there a way to handle the above described situation?

(I am using Firebird, there is no support for database schemas)

Let's say you have a table PERONS in version 1.0 with the columns:
NAME, FIRST_NAME, AGE

In version 1.1 you added the following column:
EMAIL

In your Lin2Db mapping you have something like this:

```
[Table("PERSONS")]
public partial class Person{
    [Column("NAME")]
    public string Name{get;set;}

    [Column("FIRST_NAME")]
    public string FirstName{get;set;}

    [Column("AGE")]
    public int Age{get;set;}

    [Column("EMAIL")]
    public string Email{get;set;}
}
```

So this call won't work, in database versions prior to 1.1:

```
using(var context = new MyDb())
{
    var result = context.GetTable<Person>().ToList();
}
```

Is there any way to create a compatibility?

**Comment by sdanyliv** [comment]
Set NoColumn attribute or IsColumn=False in mapping schema.
But better to keep off from such solutions, after years of usage you may have many of such kind workarounds.
[FluentMigrator](https://github.com/fluentmigrator/fluentmigrator) is good way to keep your database up to date.
Also usually we do not need a lot of specific stuff from entities. We just select data in way that we need and inroduce new objects.

```cs
IQueryable<PersonModel> GetPerson(IQueryable<Person> persons, int version)
{
    If (version > 1)
        return persons.Select(p => new PersonModel
           {
               FirstName = p.FirstName,
               LastName = p.LastName,
               FullName = p.FirstName + p.LastName
           });
      else
         ....
           
    )
}
```
In this case you can manipulate with queries easely without additional efforts and magic transformations. This technique works perfectly in web seververs and client applications and produces exact SQL that you need.
Later you can select only one field from PersonModel and everything will be optimized to select only one field and omit other calculations.

**Comment by Franki1986** [comment]
Ok, so the mapping that is used is always the most copletetly and if I want to select less I do it with a query.. 
Good point, thanks!

**Comment by sdanyliv** [comment]
Yes you have to think when using linq2db - it is query builder and not entity storage. Entitties are just way to tell to library which fields are present in table and then you can make queries and tranformations just by linq expressions. Usually it is enough for almost all complex databases and scenarios.
