### ISSUE TITLE
Partial update

### ISSUE THREAD

**Issue by voronov-maxim** [linq2db/linq2db#1044]
How to send update with only changed columns, without load full entity from database?

**Comment by sdanyliv** [comment]
It is natural way for linq2db, you do not need to select entity for updating. Thi is main diffrence between linq2db and change tracking ORMs
https://github.com/linq2db/linq2db#update

**Comment by voronov-maxim** [comment]
Thank

**Comment by feeleen** [comment]
Maybe linq2db "Update" method could have additional parameter with list of non-pk Properties to update?
If I use my own change tracking code to monitor properties that changed - then I want to pass these props to Update method. It's unnessesary to update every property in this case
