### ISSUE TITLE
p.caption cannot be conver

### ISSUE THREAD

**Issue by ben1628** [linq2db/linq2db#1048]
```cs
                XElement symbolTree =
                     new XElement("Symbols",
                     from c in db.PanelBars
                     join b in db.BarRoots
                     on c.BarNum equals b.BarNum into sr
                     from x in sr.DefaultIfEmpty()
                     join bb in db.BarChildren
                     on x.RootNum equals bb.RootNum into sr1
                     from y in sr1.DefaultIfEmpty()


                     group c by c.BarNum into g
                     select new XElement("Symbol",
                     new XAttribute("BarID", 1),
                     new XAttribute("BarText", g.First().Caption),
)
```
I think the problem is linq2db don't know how to get g.First().

Please help

**Comment by sdanyliv** [comment]
`g` is used somewhere later? Or just `g.First().Caption`?

**Comment by ben1628** [comment]
I’m using SQLite.  G is also used later. 1 was actually g.barnum and it reports it cannot be converted so I just replaced with a dummy constant, and now this error 

Any idea?

**Comment by sdanyliv** [comment]
Yes, i have idea ) 
It is not valid SQL. Easiest solution is to group elements on the client.
Envelope query before `group by` in `( ).ToArray()` and it should work.

**Comment by ben1628** [comment]
Luckily it is not a big table. I just do g.tolist()...

SQLite don’t have select top I think it use limit

Can we write sql expression to produce this in the server side?

Newbie with linq2db

**Comment by sdanyliv** [comment]
Unfortunately you are trying to select record from group. Which is not supported by SQL.
It is possible by using Window functions which is not supported by Sqlite.
But this query can be rewritten by using subqueries. I think it is not worse efforts in such situation ;)

**Comment by ben1628** [comment]
No problem there.

The database was ported from sql server.  It was using linq to sql before and it is working well.

I'm in the process of moving to SQLite so it is more cross platform.  Did take a look at linq2sql but it doesn't support SQLite as well as I like, EF Core produces way too many DLL.  

I finally find this amazing linq2db and now I can get rid of whole bunch of DLL.  It is such as light weighted product, I love it.

**Comment by sdanyliv** [comment]
Linq2db at first is linq to sql generator with rich customiztion and data modification routines. If you found that something is not convertible to SQL, just think how it should be converted (write sql by hands). Usually you will find that SQL is less flexible than linq2object. But when you get correct result in SQL - you can write linq queries in the same way.
Problem that you have discovered resolved by linq2sql in memory, like i have suggested, but from my point it is bad way when library hides how much data will be processed on the client side.

**Comment by sdanyliv** [comment]
Also we have better extensions for left joins https://github.com/linq2db/linq2db/wiki/Join-Operators#left-join

**Comment by sdanyliv** [comment]
That’s is difference between linq2db and other frameworks - we can show the way how to omit stored procs raw SQL and views just using linq ;)
High load systems have to think about performance everywhere and we propose ways how to do that and keep code ready for refactoring and optimizations.

So closing issue for now.
