### ISSUE TITLE
Count(COLUMN_NAME) not possible

### ISSUE THREAD

**Issue by StefanFutterer** [linq2db/linq2db#1049]
I'm trying to execute a "Select Count(COLUMN_NAME) from table X as a performance improvement. However, i can only execute Count(*) instead.

.Select(item => new { item.Column }).Count results in Count(*).

Count() itself does only accept delegates with a bool as result.

**Comment by jogibear9988** [comment]
@sdanyliv : do we support this already? if not, we could do it like this...

		[Sql.Extension("COUNT({expr})", IsAggregate = true)]
		public static decimal CountColumn<TEntity, TV>([NotNull] this IQueryable<TEntity> source, [NotNull] [ExprParameter] Expression<Func<TEntity, TV>> expr)
		{
			if (source == null) throw new ArgumentNullException("source");
			if (expr == null) throw new ArgumentNullException("expr");

			return source.Provider.Execute<decimal>(
				Expression.Call(
					null,
					MethodHelper.GetMethodInfo(Sql.CountColumn, source, expr),
					new Expression[] { source.Expression, Expression.Quote(expr) }
				));
		}

**Comment by StefanFutterer** [comment]
I implemented this as a temporary workaround in our solution and it works great. However, i would prefer int as result. However, i changed the result type to int as i think it's more convenient.

**Comment by sdanyliv** [comment]
There are ready built in extensions:
Sql.Ext.Count
Sql.Ext.CountExt

**Comment by StefanFutterer** [comment]
Works as expected. Thank you.
