### ISSUE TITLE
Datagridview with linq2db and sqlite

### ISSUE THREAD

**Issue by ben1628** [linq2db/linq2db#1050]
In the OK button I used to do

Datacontext.getchangedset()

And the do update insert according to what is changed.

In linq2db do we have something similar?

**Comment by MaceWindu** [comment]
No, linq2db doesn't have change tracking - you need to be explicit about what changes you want to perform.

**Comment by sdanyliv** [comment]
@ben1628 
You can add line to your TT file
```
<#@ include file="$(ProjectDir)LinqToDB.Templates\EditableObject.ttinclude" #>
```
And then entities will become EditableObjects with change tracking. These objects has needed properties,

**Comment by ben1628** [comment]
I add the above line to my TT file like this

<#@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.SQLite.Tools.ttinclude" #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"  #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\EditableObject.ttinclude" #>

a new .cs was created with no error.

However, I still cannot call getchangedSet()

Did I do anything wrong?  can u provide a code snippet of what I should expect, like

using (var db = new myDatabase())
{
   db.getchangedset();
}

**Comment by sdanyliv** [comment]
Chnange tracking is not supported by Linq2db. But these objects accumulates changes.
So pass to grid view list of these objects and for save analyse which are changed an provide manual update via db.Update method.

**Comment by sdanyliv** [comment]
Not familiar with this control but something like this:
```cs
_patients = db.Patients.ToList();
foreach (var p in _patients)
  p.AcceptChanges();
dataGridView.DataSource = _patients;
```
On save

```cs
foreach (var p in _patients)
   if (p.IsDirty)
   {
       db.Update(p);
       p.AcceptChanges();
   }
```

**Comment by ben1628** [comment]
Nice.

Couple of things,

1/ Need to move the EditableObject to first line before the related codes can be generated

2/ p.IsDirty is always true when I try to save.  It seems the control is calling beginEdit and endEdit when I enter and leave the cell.  I just remove AcceptChanges in the endEdit in tt file.  Don't know whether it is the correct way to do that.

For a large table, what kind of performance are we looking at to this looping.  My guess is datacontext getchangedset is doing the same thing. Any idea?

In any event, it is very nice.

**Comment by sdanyliv** [comment]
You can debug why IsDirty is set in your objects
AcceptChanges or RejectChanges should put IsDirty in false state

>For a large table, what kind of performance are we looking at to this looping. My guess is datacontext getchangedset is doing the same thing. Any idea?

They do also many other things. So this solution is fast enough.
Otherwise you need special grid that works with a lot of data. 
Which application type do you have?

**Comment by ben1628** [comment]
>>Otherwise you need special grid that works with a lot of data<<

interesting enough, I actually has that when I was using linq to sql on a table with 100K record.

In any case, the EditableObject does the job really well. 

Thanks.
