### ISSUE TITLE
datetime curent_timestamp T4 generates object

### ISSUE THREAD

**Issue by ben1628** [linq2db/linq2db#1058]
In my SQLite database, I have this column

currenDate (datetime_current_timestamp, not null)

It generates this

		#region Date : object

		private object  _currentDate;
		private object _originalDate;
		[Column, NotNull]
		public  object          Date // datetime current_timestamp
		{
			get { return _currentDate; }
			set { _currentDate = value; }
		}

how Can I modify the tt file so it will generate

private DateTime

Thanks

**Comment by sdanyliv** [comment]
I suggest to read whole document from start to understand what you can do with your model.
https://github.com/linq2db/t4models#customizing-generation-process
```cs
GetColumn("Table", "Date").Type = typeof(DateTime)
```

**Comment by ben1628** [comment]
GetColumn("Table_Name", "Date").Type = "DateTime";

Nice. Thanks.

**Comment by ben1628** [comment]
However, is there s simple way so TT will understand to

datetime current_timestamp to DateTime

since I have quite a few instances like this.

**Comment by sdanyliv** [comment]
You can try to enumerate all tables and their columns and correct Type by testing for example ColumnType or DataType property of column. Not sure about exact name.
Everything is in document.
