### ISSUE TITLE
Sqlite connection String

### ISSUE THREAD

**Issue by ben1628** [linq2db/linq2db#1061]
```xml
<add name="sqliteDB" connectionString="Data Source=N:\bin\data\sqliteDb.sqlite" providerName="SQLite" />
```
works.

However, How can I specify a relative path like

```xml
<add name="sqliteDB" connectionString="Data Source=data\sqliteDb.sqlite" providerName="SQLite" />
```

**Comment by MaceWindu** [comment]
It should work, we use relative pathes in our tests for sqlite and it works perfectly. Maybe your application run with current directory to set to some strange value?
You should check what Directory.GetCurrentDirectory() returns for you.

**Comment by jogibear9988** [comment]
Should work, I use this regularly...
If you still have Problems, we will reopen.
