### ISSUE TITLE
Only Generate Selected Tables and/or Stored Procedures

### ISSUE THREAD

**Issue by zhson** [linq2db/linq2db#1062]
I want to be able to generate selected Tables and/or Stored Procedures only.

Currently, the database I have is a bit messy, the naming standard is not best, so I want to be able to generate the tables and stored procedures that I need to use in the coding.

**Comment by sdanyliv** [comment]
You can remove not needed tables from generation by removing from Tables dictionary.
https://github.com/linq2db/t4models#useful-members-and-data-structures
But also you need to correct associations for that tables.
Same with stored procedures.

**Comment by MaceWindu** [comment]
Closed as answered
