### ISSUE TITLE
Issue in query for columns starting with #

### ISSUE THREAD

**Issue by Salalimo** [linq2db/linq2db#1064]
Running this query in a sql editor there is no issue 
```sql
SELECT
	t1.#colname
FROM
	[tablename] [t1]
``` 

Running this query causes an issue
```sql
SELECT
	[t1].[#colname]
FROM
	[tablename] [t1] 
```
Error is:
        `The quoted identifier '[#colname]' is illegal because its first character is '#', which is ambiguous. Please use another character instead.`

Creating a simple select using linq2db generates the query in the second format (adding [,]) that produces the error mentioned above:
 db.GetTable<tablename>().ToList()

Is there a workaround for this?

Thanks.

**Comment by sdanyliv** [comment]
Which provider do you use?

**Comment by MaceWindu** [comment]
I would suspect Sybase, as @Salalimo already reported issue for this provider...

**Comment by sdanyliv** [comment]
In [Sybase](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36271.1600/doc/html/san1393050529478.html) case it is strange that such identifier is allowed
>The first character of an identifier must be either an alphabetic character, as defined in the current character set, or the underscore (_ ) character.

Workaround is to create DataProvider descendant with corrected Convert method of t's own SQL Builder
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Sybase/SybaseSqlBuilder.cs#L172

But better to point us to specification which allows such kind of columns or we just add exception only for `#` starting symbol.

**Comment by Salalimo** [comment]
Yes I am using Sybase. I think that our db is very old perhaps the columns where created when that restriction was not there? I am not sure.. but now I cannot create a column starting with # even though there are some that are that same table.

Can you be a little more specific on how to extend the DataProvider class? 

Thanks.

**Comment by sdanyliv** [comment]
I’ll create simple patch and you can get it from MyGet. Some databases gives for us many surprises and we trying to fix that ASAP.

**Comment by MaceWindu** [comment]
I've created fix for this issue, but I would recommend to rename this column if possible.

**Comment by NetMage** [comment]
Sybase seems to include special characters in alphabetical - from http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/CACDEHJA.htm:

"Alphabetic characters include the alphabet, as well as the underscore character (_), at sign (@), number sign (#), and dollar sign ($). "

**Comment by MaceWindu** [comment]
That is Sybase IQ documentation. We support only Sybase ASE, and for ASE it is [not allowed](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36271.1600/doc/html/san1393050529478.html) to have # as starting character.

Still it is technically possible to create such identifier and use it in queries which I did in test for this issue: https://github.com/linq2db/linq2db/pull/1169/files#diff-dda23b53be35b18d0901b54bf29679f4R37
