### ISSUE TITLE
Column name mapping function

### ISSUE THREAD

**Issue by deluvas** [linq2db/linq2db#1074]
Hi,

I want to be able to specify a function that maps column names everywhere (e.g. map to underscore/snake_case). I don't want to manually specify it in each attribute nor auto-generate it via template. 

I searched through the wiki/issues/code but couldn't find an answer; any help is appreciated. Thank you.

Example:

````C#
MappingSchema.Default.ColumnNameResolver = columnName => columnName.ToSnakeCase();
````

**Comment by sdanyliv** [comment]
As i know it is not possible with your restrictions. Can you provide real case when it can be needed?

**Comment by deluvas** [comment]
>Can you provide real case when it can be needed?

@sdanyliv I am using snake case for my database columns, so I want to avoid cluttering the POCOs with column name constants.

**Comment by MaceWindu** [comment]
You can create and register your own MetadataReader and implement name modification in it (linq2db doesn't have such functions).
E.g. we use custom metadata provider, inherited from https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Metadata/MetadataReader.cs, which replace database object name with real name, fetched from database registry table.

**Comment by jogibear9988** [comment]
I'm looking to implement smth. when my current pull reqs. are merged.

I'm also looking for a way to change Table Name,...

**Comment by jogibear9988** [comment]
lok this branch is now merged: https://github.com/linq2db/linq2db/pull/1081

**Comment by jsheely** [comment]
Can someone explain how this works? Does not seem like the code ever gets initialized when trying @jogibear9988 link

I tried to adding it to my Startup.cs but it doesn't ever get called.

```
var ms = new MappingSchema();
var mb = ms.GetFluentMappingBuilder();
ms.EntityDescriptorCreatedCallback = (mappingSchema, entityDescriptor) =>
{
	entityDescriptor.TableName = entityDescriptor.TableName.ToLower();
	foreach (var entityDescriptorColumn in entityDescriptor.Columns)
	{
		entityDescriptorColumn.ColumnName = entityDescriptorColumn.ColumnName.ToLower();
	}
};
```

I just want to lower case the property names as a standard so I don't have to decorate every single property with the duplicate name but lower cased.

**Comment by MaceWindu** [comment]
I would suspect you attach callback to wrong mapping schema. If you didn't use some custom setup, you need to attach it to `MappingSchema.Default` instance

**Comment by jsheely** [comment]
@MaceWindu Yep I tried that as well. Still doesn't appear to get called

**Comment by MaceWindu** [comment]
Well, it's hard to say without actual code what is wrong. I can see only two options:
- you subscribed to wrong mapping schema
- you subscribed too late when descriptors already created

**Comment by MaceWindu** [comment]
Ok, you were right. It will not be called if configured like that. See #1592. For now you need to attach callback in your DbContext constructor https://github.com/jsheely/linq2db-column-mapping-example/blob/master/Components/Database/DbContext.cs#L13 to this.MappingSchema instance

**Comment by jsheely** [comment]
Perfect! Thank you for the advice.

**Comment by Dmitrij-Polyanin** [comment]
I have the same problem.
I tried to make callback just inside MappingSchema and tryed as sad upper in DataBaseConnection constructor, and it never calls
![image](https://user-images.githubusercontent.com/10674646/61208859-0019af80-a701-11e9-9389-76d9e03fe3b6.png)
