### ISSUE TITLE
LeftJoin with Linq fluent syntax?

### ISSUE THREAD

**Issue by hassanselim0** [linq2db/linq2db#1076]
All the Join examples on the wiki use linq's query syntax (eg: `from u in Users select u.Name`), but I'm used to the fluent/method syntax (eg: `Users.Select(u => u.Name)`).

Why can't I do something like the following:
```c#
db.Users.LeftJoin(db.Posts, u => u.Id, p => p.UserId);
```
Something like the `Join` that already exists in `System.Linq.Queryable` but would generate a Left Join instead of an Inner Join.
The current implementation of LeftJoin only accepts a `Func<T, bool>` and I have no idea how to make that work in fluent syntax.

Note: `LoadWith` isn't working properly for me, it still generates "n+1" queries instead of a single join query (even though I've seen old closed issues here saying that it's implemented).

### Environment details
linq2db version: *1.10.2* (Core)
Database Server: *MySQL 5.7.21*
Database Provider: *MySql.Data 6.10.6*
Operating system: *Windows 10 Pro*
Framework version: *.NET Core 2.0*

**Comment by jogibear9988** [comment]
query

				var q = from od in db.OrderDetail
					from o1 in db.Order.Where(o => o.OrderID == od.OrderID).DefaultIfEmpty()
					from o2 in db.Order.Where(o => o.OrderID == od.OrderID).DefaultIfEmpty()
					orderby od.OrderID
					select new
					{
						od.OrderID,
						o1.OrderDate,
						OrderID1 = o1.OrderID,
						OrderID2 = o2.OrderID,
					};

is

				var q = db.OrderDetail
					.SelectMany(od => db.Order.Where(o => o.OrderID == od.OrderID).DefaultIfEmpty(), (od, o1) => new {od, o1})
					.SelectMany(@t => db.Order.Where(o => o.OrderID == @t.od.OrderID).DefaultIfEmpty(), (@t, o2) => new {@t, o2})
					.OrderBy(@t => @t.@t.od.OrderID)
					.Select(@t => new {@t.@t.od.OrderID, @t.@t.o1.OrderDate, OrderID1 = @t.@t.o1.OrderID, OrderID2 = @t.o2.OrderID,});

**Comment by jogibear9988** [comment]
query 

				var q3 =
					from p1 in db.Parent
					from p2 in subquery.LeftJoin(o => o.ParentID == p1.ParentID)
					select new { p1, p2 };

is

				var q3 = db.Parent.SelectMany(p1 => subquery.LeftJoin(o => o.ParentID == p1.ParentID), (p1, p2) => new {p1, p2});

**Comment by jogibear9988** [comment]
I converted them using Resharper...

**Comment by sdanyliv** [comment]
@hassanselim0, at first we are thinking how to write linq experssion to be closer to sql. So linq queries are supported by default. With fluent syntax there are many possibilities to write expression that can not be converted to real SQL.
I’ll check maybe we can support this fluent syntax without additional superfluous calculations.

**Comment by sdanyliv** [comment]
@hassanselim0, different worlds ;) I’m writing linq queries to replace SQL, ususally with exact same syntax. Old scool, SQL Is the first because it gives optimal performance and i don’t need to check output (i do it always )) ) to get correct result.
Linq2db is compile time syntax check SQL generator with query optimizations.
And you can see that fluent syntax sometimes is more verbose and hard to understand, especially when you do grouping or trying to apply window functions.

Well, maybe it’s time to support fluent syntax in this case also. Will check.

**Comment by jogibear9988** [comment]
query syntax can always be converted to fluent syntax (or should as I know). Resharper can do that for you (and also the other way!)

**Comment by MaceWindu** [comment]
fixed by #1088
