### ISSUE TITLE
How to build .Net core nupkg file from Linq2db sources?

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#1079]
How to build .Net core nupkg from source?  
I mean to the same package as available at NuGet with:  `Install-Package linq2db.core`

**Comment by ili** [comment]
In current master & release branches linq2db & linq2db.core are merged in one solution and package, so you can just pack `Source/LinqToDB/LinqToDB.csproj`

In release1 branch there is linq2db.core.sln and `Source/project.json` to build core package (for dotnet core 1.1)

**Comment by MaceWindu** [comment]
Closing answered/non-actionable issues. Feel free to reopen/continue discussion if it wasn't anwsered.
