### ISSUE TITLE
CommandTimeout is not working.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1080]
Hi guys!
I have the following connection string:

`ConnectionString =
                                $"Server={_dbConnection.Host};Port={_dbConnection.Port};Database={_dbConnection.Database};" +
                                $"User Id={_dbConnection.Username};Password={_dbConnection.Password.Decrypt()};" +
                                $"Timeout=600;CommandTimeout=600"`

So, when i'm doing a simple query like: mainDb.Table.ToList();
where Table is a table from mainDb.
Sometimes is working good, sometimes id doesn't and gives an exception like - Exception while reading from stream...
The exception is given instantly after executing the query...That means, the CommandTimeout is not working, right?

Do somebody have the same issue?

**Comment by MaceWindu** [comment]
If it is SQL server, than there is no such option as CommandTimeout in connection string. SQL server supports connection timeout in connection string and command timeout should be set in code on command or connection instance

**Comment by ili** [comment]
Everything configured through connection string deals with .Net Provider (SqlServer, Npgsql... etc). We do not change or use connection string for any settings.

As mentioned @MaceWindu  you can manage command timeout using `db.CommandTimeout = 600`

**Comment by YXMagnuMXY** [comment]
Ok.
The problem is that i'm working with two databases simultaneously and i forgot in the connectionString of the second DB to put CommandTimeout :)

Sorry for disturbing you guys. You are working on a very good product, i just love it(is not only me for sure)!

**Comment by YXMagnuMXY** [comment]
PS: PostgreSQL Provider

**Comment by ili** [comment]
You are welcome! :)
