### ISSUE TITLE
Undefined error when using copy constructor in select

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1084]
Hello,

currently I am using Devextreme dx-Grid and Devextreme.ASPNET.Data. 
To make it short, it uses linq to produce queries. If you want to filter the header it loads all possible values of a column and shows them in a check box list, so that you can select as many as you want and then a filter is applied to the DB.
So far so good, everything works if you do it with a normal 'this.GetTable<T>()' as source. If you do it with a joined query this does not work..

This is the query that is working:

```cs
var test1 = db.GetTable<Person>()
                      .GroupBy(x => new { I0 = x.Number })
                          .OrderBy(g => g.Key.I0)
                           .Select(g => new { I0 = g.Count(), I1 = g.Key.I0 }).ToList();
```

The resulting SQL:

```sql
SELECT
	Count(*) as c1,
	t1.NUMBER
FROM
	PERSON t1
GROUP BY
	t1.NUMBER
ORDER BY
	t1.NUMBER
```

This query does not work:

```cs
var result = from k in this.GetTable<Person>() join ks in this.GetTable<Student>() on 
                       new Tuple<int, string>(k.Id, k.Number.ToString()) equals
                       new Tuple<int, string>(ks.Id, ks.Number) into joinedTable
                           from g in joinedTable.DefaultIfEmpty()
                            select new Person(k) {
                                IsBlocked = (k.StatusBitmask & 0x80) != 0, 
                                IsBlockedStudent = (g.StatusBitmask & 0x80) != 0 };
```

```cs
var test2 = result
                      .GroupBy(x => new { I0 = x.Number })
                          .OrderBy(g => g.Key.I0)
                           .Select(g => new { I0 = g.Count(), I1 = g.Key.I0 }).ToList();
```

The resulting SQL is:

```sql
SELECT
	Count(*) as c1,
	0 as c2
FROM
	PERSON k1
		LEFT JOIN STUDENT joinedTable ON k1.ID = joinedTable.ID AND Cast(k1.NUMBER as VarChar(11) CHARACTER SET UNICODE_FSS) = joinedTable.NUMBER
ORDER BY
	0
```

Linq2Db-Version. 1.10.2 and 2.0
DB-Provider: Firebird

I also posted the issue to [Devextreme](https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/229) but I think this is a problem how the sql is generated..

**Comment by sdanyliv** [comment]
Can you remove tuples and introduce anonymous objects? Looks like we do not support them.
Or rewrite query in the following way which is more readable:
```cs
 var result = from k in this.GetTable<Person>() 
       from ks in this.GetTable<Student>().LeftJoin(ks => ks.Id == k.Id && k.Number == ks.Number)
       select new Person(k) 
       {
               IsBlocked = (k.StatusBitmask & 0x80) != 0, 
               IsBlockedStudent = (ks.StatusBitmask & 0x80) != 0 
       };
```

**Comment by Franki1986** [comment]
I also tested the LeftJoin extension like you did, same result.

**Comment by sdanyliv** [comment]
Oh i see, it’s known problem with grouping calculated fields. Igor should rewrite this part.
Workaround is:
```cs
 var result = from k in this.GetTable<Person>() 
       from ks in this.GetTable<Student>().LeftJoin(ks => ks.Id == k.Id && k.Number == ks.Number)
       let isb =  (k.StatusBitmask & 0x80) != 0
       let isbs = (ks.StatusBitmask & 0x80) != 0
       select new Person(k) 
       {
               IsBlocked = Isb, 
               IsBlockedStudent = isbs
       };
```

**Comment by Franki1986** [comment]
I also tested it, the same result:

```
var result = from k in this.GetTable<Person>() 
       from ks in this.GetTable<Student>().LeftJoin(ks => ks.Id == k.Id && k.Number == ks.Number)
       let isb =  (k.StatusBitmask & 0x80) != 0
       let isbs = (ks.StatusBitmask & 0x80) != 0
       select new Person(k) 
       {
               IsBlocked = isb, 
               IsBlockedStudent = isbs
       };

var groupedResult = result.GroupBy(x => new { I0 = x.Number }).OrderBy(g => g.Key.I0).Select(g => new { I0 = g.Count(), I1 = g.Key.I0 }).ToList();
```

SQL:

--  Firebird
SELECT
	Count(*) as c1,
	0 as c2
FROM
	PERSON t2
		LEFT JOIN STUDENT t1 ON t1.ID = t2.ID AND t1.NUMBERR = Cast(t2.NUMBER as VarChar(11) CHARACTER SET UNICODE_FSS)
ORDER BY
	0

**Comment by sdanyliv** [comment]
Last chance of workaround
```cs
var result = from k in this.GetTable<Person>() 
       from ks in this.GetTable<Student>().LeftJoin(ks => ks.Id == k.Id && k.Number == ks.Number)
       select new Person(k) 
       {
               IsBlocked = Sql.AsSql((k.StatusBitmask & 0x80) != 0), 
               IsBlockedStudent = Sql.AsSql((ks.StatusBitmask & 0x80) != 0)
       };
```

**Comment by sdanyliv** [comment]
Missed  that you are using that constructor!
How to group elements if you require full Person object in constructor?
That’s your main problem. Everything is declarative and in case of grouping, constructor should be never called and used only for query generation. I think we have to throw exception that query improperly defined.

**Comment by Franki1986** [comment]
Yes, after looking to some questions to entity framework for this I came around that the copy constructor will never be called. The idea with throwing an exception is a good idea, I think ef does the same.
Should I rename the issue?

**Comment by sdanyliv** [comment]
Yes please.

**Comment by sdanyliv** [comment]
EF may silently process all records on the client. Absolutely correct but useless solution in that case.

**Comment by MaceWindu** [comment]
Actually looks like constructors also work as expected
