### ISSUE TITLE
Migration from LINQ to SQL 

### ISSUE THREAD

**Issue by alexey-tyulkin** [linq2db/linq2db#1085]
Are there any simple way migrate query from LINQ to SQL to ling2db?
There are N.dbml and N.cs, can i use its and make only select via linq2db

Thanks

**Comment by sdanyliv** [comment]
There is IMetaDataReader, please follow this issue https://github.com/linq2db/linq2db/issues/900. No special documentation for now.

**Comment by MaceWindu** [comment]
Looks like we don't have metadata reader for dbml file. We have very similar XmlAttributeReader, but from code I see that it expects other names for elements.

It will be great if you can take this code as a base, modify for dbml support and send a PR.

**Comment by alexey-tyulkin** [comment]
Hi @MaceWindu and @sdanyliv 
There is the original SystemDataLinqAttributeReader. It works well with my fix in PR #2019.
I think if you accept the PR you can close the issue.

**Comment by MaceWindu** [comment]
Closing for now. If somebody needs to import dbml directly, we can reopen.
