### ISSUE TITLE
Using Fluent Mapping Builder for joins

### ISSUE THREAD

**Issue by AlthalusDGr8** [linq2db/linq2db#1089]
Hello

I am trying to keep my concern between my object models and the persistence layer and therefore i am trying to avoid using attribute mapping on classes and use the FluentMappingBuilder instead.

Documentation is a bit scarce on how one can do this, but I managed to get specifying the properties, but got stuck when I was trying to map joins between tables.

Could you please provide me with examples how one would go about mapping one to one, a one to many and a many to many relationship using the builder please? :)

As examples i can provide the following:

User Table
Id
Username
Password

User Details Table
Id
User Id (links to id of user table) --> One User  to One User Detail Mapping
Name
Surname

User Communication Detail Table
ID
User Id (links to id of user table) --> One User to Many Communication Details
Communication Type
Value

Roles
Id
Role Name

UserRoles --> This will need to be a many to many relationship
Id
User Id (links to id of user table)
Role Id (links to id of role table)

### Environment details
linq2db version: *1.10.2*  
Database Server: *MSSQL Server*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Core 2.0*

**Comment by MaceWindu** [comment]
Joins using mapping defined by associations.
You can check Association attribute usage here: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/AssociationTests.cs
For fluent mapper associations defined using Association methods on entity mapping builder: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/EntityMappingBuilder.cs#L219

So, to create association you will need:
-  a property of proper type: SomeEntity or IEnumerable<SomeEntity> (this is how cardinality is set for one-to-one/one-to-many relations).
- for association you should specify how two tables should be joined using ThisKey/OtherKey which are PK/FK fields or using custom join predicate
- CanBeNull property defines type of join: Inner Join for false and Left Outer Join for true

If you need to perform joins from both relation sides - you need to add associations to both entities (for each kind of join you need, if you need different joins).

For many-to-many relation there is no special support in linq2db right now so you need to define mapping for link table and define required one-to-many associations between it and both entities.

**Comment by AlthalusDGr8** [comment]
I tried a simple example as follows:

_Entities:_
public class User 
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public UserDetail UserDetail { get; set; }
    }

    public class UserDetail 
    {
        public int Id { get; set; }

        public int UserId { get; set; }

        public string Line1 { get; set; }

        public string Line2 { get; set; }
    }

_Mapping Schema_
var mb = mappingSchema.GetFluentMappingBuilder();

mb.Entity<User>()
                .HasSchemaName("dbo")
                .HasTableName("User")
                .HasIdentity(x => x.Id)
                .Property(x => x.Name).HasColumnName("Name")
                .Association(x => x.UserDetail, x => x.UserDetail.UserId, x => x.Id);


            mb.Entity<UserDetail>()
                .HasSchemaName("dbo")
                .HasTableName("UserDetail")
                .HasIdentity(x => x.Id)
                .Property(x => x.Line1).HasColumnName("Line1")
                .Property(x => x.Line2).HasColumnName("Line2");

I get the following exception:
Association key 'UserId' not found for type 'PortableLibrary.ConsoleApp.User.

It seems as if it is reading the linkage the wrong way round.

**Comment by AlthalusDGr8** [comment]
Ok this works.  Thanks a lot :)
