### ISSUE TITLE
LoadWith() - Second layer of additional data.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1094]
Hi guys!
Example: I have 3 tables like - Tests; History and Users.

I am using the LoadWith() like that:
`var testsList = db.Tests.LoadWith(x=>x.History)` and this is working very well. Foreach test, is loading a list of histoies.

Now I have a problem, I want to load all Tests, with History inside(IEnumerable) + Users data.
Each history from History Table contains User ID.

How to load the second layer of additional data(If that is possible at all...)?

**Comment by MaceWindu** [comment]
This should work
```cs
db.Tests.LoadWith(x=>x.History).LoadWith(x=>x.History[0].User)
// or for non-indexable association type
db.Tests.LoadWith(x=>x.History).LoadWith(x=>x.History.First().User)
```

**Comment by MaceWindu** [comment]
Not sure right now if first LoadWith needed. Possibly it will load both records with second

**Comment by MaceWindu** [comment]
Checked documentation `db.Tests.LoadWith(x=>x.History.First().User)` should be enough.
BTW, example like that contained in LoadWidth xml help. Do you have any issues with help available from nuget?

**Comment by YXMagnuMXY** [comment]
Hmm...
I think this query `db.Tests.LoadWith(x=>x.History.First().User)` will not give the expected result.
I need a result like that:
Test1
        History1 + User(by user_id from History1 result)
        History2 + User(by user_id from History2 result)
Test2
        History3 + User(by user_id from History3 result)
        History4 + User(by user_id from History4 result)

In your query, we will have the result like:
Test1
        User(by user_id from History1 result)
        User(by user_id from History2 result)
Test2
        User(by user_id from History3 result)
        User(by user_id from History4 result)

Did i correctly understand this query?

**Comment by MaceWindu** [comment]
Did you tried it? It should load all associations in specified path, so it should work for you.

**Comment by YXMagnuMXY** [comment]
Yes, i tried it now, and it's working.
But the query db.Tests.LoadWith(x=>x.History.**First()**.User) contains this FIRST() that's confusing.
Expectations of this FIRST() was of returning only FIRST History, not an IEnumerable of History with First User.

Is working. Thank you!

**Comment by MaceWindu** [comment]
yep, we need First() or `[x]` to navigate to target property. I agree that it could be confusing.
