### ISSUE TITLE
New tests with create table fail for Firebird

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1095]
New tests from #1072 doesn't work for Firebird, because we generate incorrect create table statement for Firebird.
Related to #749

### Environment details
linq2db version: 2.0.0-rc2141

Database Server: Firebird 2.5 and 3.0

**Comment by sdanyliv** [comment]
Possible because string columns should have size.

**Comment by sdanyliv** [comment]
Nope. But i think i have pointed you in right way. Check your creation scripts and you will find that tables needs size for strings.

**Comment by jogibear9988** [comment]
In My Mapping, every String column has a size!

**Comment by jogibear9988** [comment]
see:

			var mappingBuilder = ms.GetFluentMappingBuilder();
			mappingBuilder.Entity<Animal>()
				.HasTableName("Animals")
				.Inheritance(x => x.Discriminator, "Dog", typeof(Dog))
				.Inheritance(x => x.Discriminator, "WildAnimal", typeof(WildAnimal))
				.Inheritance(x => x.Discriminator, "SuperWildAnimal", typeof(SuperWildAnimal))
				.Property(x => x.Name).IsColumn().IsNullable().HasColumnName("Name")
				.Property(x => x.AnimalType).IsColumn().HasColumnName("AnimalType").HasDataType(DataType.NVarChar).HasLength(40)
				.Property(x => x.AnimalType2).IsColumn().HasColumnName("AnimalType2").HasDataType(DataType.NVarChar).HasLength(40)
				.Property(x => x.Discriminator).IsDiscriminator().IsColumn().IsNullable(false).HasColumnName("Discriminator").HasDataType(DataType.NVarChar).HasLength(40)
				.Property(x => x.Id).IsColumn().IsNullable(false).HasColumnName("Id").IsPrimaryKey();

			mappingBuilder.Entity<Dog>()
				.HasTableName("Animals")
				.Property(x => x.Bla).IsNotColumn()
				.Property(x => x.EyeId).IsColumn().IsNullable().HasColumnName("EyeId")
				.Property(x => x.DogName.Second).HasColumnName("Second").HasDataType(DataType.NVarChar).HasLength(40)
				.Property(x => x.DogName.First).HasColumnName("First").HasDataType(DataType.NVarChar).HasLength(40)
				.Association(x => x.Bla, x => x.EyeId, x => x.Id);

			mappingBuilder.Entity<WildAnimal>()
				.HasTableName("Animals");

			mappingBuilder.Entity<SuperWildAnimal>()
				.HasTableName("Animals");

			mappingBuilder.Entity<Eye>()
				.HasTableName("Eyes")
				.Property(x => x.Id).IsColumn().HasColumnName("Id")
				.Property(x => x.Xy).IsColumn().IsNullable().HasColumnName("Xy").HasDataType(DataType.NVarChar).HasLength(40);

			mappingBuilder.Entity<Test>()
				.HasTableName("Test")
				.Association(x => x.TestAnimal, x => x.TestAnimalId, x => x.Id)
				.Property(x => x.TestAnimalId).IsColumn().IsNullable().HasColumnName("TestAnimalId")
				.Property(x => x.TestAnimal).IsNotColumn();

**Comment by MaceWindu** [comment]
also tests for #1057 have similar issue with boolean field for firebird and DB2

**Comment by jogibear9988** [comment]
"Second" is a reserved word on firebase.

https://firebirdsql.org/refdocs/langrefupd25-reskeywords-full-reswords.html

**Comment by jogibear9988** [comment]
Is the ReservedWords List not used for Create Table Statements? Or maybe not in Firebird? Maybe someone can hint me where to look?

**Comment by MaceWindu** [comment]
core isssue fixed by #1109, but now it fails for linq service. I will look into this issue today
