### ISSUE TITLE
Checking the structure of db, Updating the structure of db.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1097]
Hi guys!

I want to ask you if there is a possibility of checking the structure of the DB which the application is connected, and if is not matching the structure that should have, to update it in the DB? I mean, to update structure of tables,functions,constraints, and so on...

If there is no such possibility, it would be a good idea of creating such feature...Don't you think so?
PS: I'm using now PostgreSQL Provider

**Comment by stsrki** [comment]
From my own personal experience I think this is not a good idea. Even if this is possible it would be very dangerous to do it on production databases, not to mention that it would be really slow to check on every application startup. Linq2DB should stay an ORM and be the best tool for this thing.

If you need to do database schema migration I would recommend you [FluentMigrator](https://github.com/fluentmigrator/fluentmigrator). It does require more work in the beginning but you will have full control over your migrations.

**Comment by YXMagnuMXY** [comment]
Thank you for your answers.
I want just to describe my situation, and why I wanted to update the structure...
I have 2 databases, one that application is connected, and other for transferring data between.
First is MAIN DB, other is TEMPORARY DB. Also, I have in my application a procedure of Synchronizing data between this two databases.
Now, if I'm doing changes in the MAIN DB(adding column, renaming, adding constraint, etc...), and pressing the SYNC button in the application, it can crash, because the structure is not correct in the TEMPORARY DB. Now I want to make a check before SYNC if the structure is the same, and then to do this SYNC or to UPDATE STRUCTURE first, if the structure is not the same.

**Comment by YXMagnuMXY** [comment]
Thank you! You can close this case ;)
