### ISSUE TITLE
Group By with order does not work

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1100]
following query does not work:

    archiveData = s.GetTable<TagsArchiveDTO>()
                    .OrderBy(x => x.ModifiedTimeStamp)
                    .GroupBy(x => x.TagId)
                    .Select(g => g.First())
                    .ToList();

can we support this, by creating a subquery with orders the table?

**Comment by sdanyliv** [comment]
Such functionality is supported by databases that have Window Functions. Otherwise we have to introduce transformations for emulating such queries and user has to be aware that they may be not effective.
Usually i propose to wrie such query in SQL and decide does it needs automatic processing.

**Comment by jogibear9988** [comment]
That means, in Sqlite this does not work?

**Comment by jogibear9988** [comment]
or maybe smith like this could be introduced??

archiveData = s.GetTable<TagsArchiveDTO>()
                .OrderBy(x => x.ModifiedTimeStamp).AsSubQuery()
                .GroupBy(x => x.TagId)
                .Select(g => g.First())
                .ToList();

**Comment by sdanyliv** [comment]
Just write SQL that returns correct data and you will understand why it is not so easy. Then users are trying to use skip, last, something else and expects that we translates their needs into effective SQL. Usually they don’t need such complexity and just writes queries in linq way without knowledge how database works.

**Comment by sdanyliv** [comment]
> That means, in Sqlite this does not work?

That means that such queries is less effective in databases that do not have Window Functions.

Also i’m trying to understand what do you expect to get from this query?

**Comment by sdanyliv** [comment]
@jogibear9988, can we close that or you have new updates.

**Comment by sdanyliv** [comment]
@jogibear9988, there is sample how to create such queries:
https://github.com/linq2db/linq2db/issues/1129#issuecomment-386910284

**Comment by sdanyliv** [comment]
Closing as answered.

**Comment by sdanyliv** [comment]
To give appropriate decription we have to analyse what happened here, which is equal to read someones mind ;) This case is small part of underground analysis that have to be done.
It’s not easy in this case. If we understand query - we can transform it to correct one. I see huge work here at first sign.

**Comment by sdanyliv** [comment]
Grouping is always breaking order - it’s how databases work, so expecting correct order after that is bad idea. EF, for example, will evaluate groping on the client side. Linq2db is not work in that way. It can be weakness but also an a plus because whole table is not populated to application.

**Comment by jogibear9988** [comment]
i thought EF will do grouping in 2.1 on Server Side?

**Comment by sdanyliv** [comment]
Not in this case. I have no idea how to do that without Window Functions.

**Comment by jogibear9988** [comment]
and on sqlite you could throw, when you normaly would use a window function wich sqlite does not support

**Comment by sdanyliv** [comment]
And again. It’s too difficult to detect such situations. If you have a time, provide us with PR.
