### ISSUE TITLE
AssociationExtension Test Fail

### ISSUE THREAD

**Issue by yuzd** [linq2db/linq2db#1101]
![image](https://user-images.githubusercontent.com/16083659/38765757-f6f2a07a-3ff9-11e8-8e5b-2cadeceefa6f.png)

```c#
[Test, DataContextSource]
		public void ExtensionTest3(string context)
		{
                       Common.Configuration.Linq.AllowMultipleQuery = true;
			using (var db = GetDataContext(context))
			{
				
				var aa = db.Child.Select(_ => new {R = _, p = _.ParentList()}).FirstOrDefault();
				//error 

			}
		}
```
![image](https://user-images.githubusercontent.com/16083659/38765790-8e955d00-3ffa-11e8-96d6-03f27d40794b.png)
![image](https://user-images.githubusercontent.com/16083659/38765792-9d088f42-3ffa-11e8-9a1b-33891d630d71.png)

### Environment details
linq2db version: master branch code
Database Server: all
Database Provider: all
Operating system: all
Framework version: *.NET Framework 4.6.2*

**Comment by MaceWindu** [comment]
Confirmed

**Comment by MaceWindu** [comment]
My bad. It is not a bug. You need to run _create* tests first to create test databases.
Also make sure sqlite provider enabled for tests and set in "DefaultConfiguration" in UserDataProviders.json.

More details you can find here https://github.com/linq2db/linq2db/blob/master/CONTRIBUTING.md#run-tests

**Comment by MaceWindu** [comment]
I've tried it before closing this issue - you see this error, because you didn't run _Create.* tests first. They are required to initialize test databases, without it most of tests will fail.

**Comment by yuzd** [comment]
@MaceWindu 
i have run _Create().
the test code is modied by me

 
  Common.Configuration.Linq.AllowMultipleQuery = true;
			using (var db = GetDataContext(context))
			{
				
				var aa = db.Child.Select(_ => new {R = _, p = _.ParentList()}).FirstOrDefault();
				//error 

			}

**Comment by sdanyliv** [comment]
I see. Misunderstanding here, we though that our tests are broken. Reopening.

**Comment by sdanyliv** [comment]
@yuzd, what is ParentList? How you defined your model?

**Comment by yuzd** [comment]
I use the model in AssociationTest.cs
and i delete all Association Attributes of the model. 
because i want to test AssociationExtention.

**Comment by sdanyliv** [comment]
Looking at current linq2db tests and can not find this `ParentList` function definition.

**Comment by yuzd** [comment]
I am sorry.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	public static class AssociationExtension
	{
		[Association(ThisKey = "ParentID", OtherKey = "ParentID")]
		public static IEnumerable<Child> Children(this Parent parent)
		{
			throw new InvalidOperationException("Used only as Association helper");
		}

		[Association(ThisKey = "ParentID", OtherKey = "ParentID")]
		public static IQueryable<Child> QuerableChildren(this Parent parent, IDataContext db)
		{
			return db.GetTable<Child>().Where(_ => _.ParentID == parent.ParentID);
		}

		[Association(ThisKey = "ParentID", OtherKey = "ParentID")]
		public static Parent Parent(this Child child)
		{
			throw new InvalidOperationException("Used only as Association helper");
		}
		[Association(ThisKey = "ParentID", OtherKey = "ParentID")]
		public static IEnumerable<Parent>  ParentList(this Child child)
		{
			throw new InvalidOperationException("Used only as Association helper");
		}

		[Association(ThisKey = "ParentID", OtherKey = "ParentID")]
		public static IQueryable<Parent> QuerableParent(this Child child, IDataContext db)
		{
			return db.GetTable<Parent>().Where(_ => _.ParentID == child.ParentID);
		}
	}

**Comment by yuzd** [comment]
i see..thanks
