### ISSUE TITLE
Generic CRUD - GetLogicExclusion doesn't exist

### ISSUE THREAD

**Issue by arielware** [linq2db/linq2db#1103]
Hi, in the Creating Generic CRUD the function GetLogicExclusion doesn't exist. 

Thank you

Ariel

**Comment by sdanyliv** [comment]
Thanks, something outdated here.

**Comment by sdanyliv** [comment]
@arielware, we decided to remove this article since it is incorrect and outdated. Usually you do not need such generic class to work with linq2db.
