### ISSUE TITLE
AppVeyor buids pass with failing tests

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1104]
E.g. check this build https://ci.appveyor.com/project/igor-tkachev/linq2db/build/2.0.0.2158#L5307
It should fail due to failing tests, but reported as successful build.

**Comment by jogibear9988** [comment]
maybe this helps: https://help.appveyor.com/discussions/problems/4498-powershell-exception-in-test_script-does-not-fail-build
