### ISSUE TITLE
Alter Table using Linq2DB. Add new column to table.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1105]
Hi guys!
I am using PostgreSQL DataProvider and i know that there is a possibility of creating a table with indicated structure.
My problem is that i'm working with two databases and I want to compare if the schema is the same.
And I am getting the schema using linq2db. Now I have two structures of databases, and I'm comparing them. After that, i can see that One Column does not exist in the Second Database. 
In this case i just want to add column in the existing table using linq2db. Is that possible?

I'm not using the ordinary db.Execute because the columns can be of different data_type, default value, and so on...and the string of the "ALTER TABLE..." will be each time different for different columns.
I also don't want to delete the table and add new one, because it will lose the data, and i don't want to store data in application and insert it again...

In the schema info taken with linq2db we have schema->tables->columns->all properties of columns.

Is there a possibility of inserting a column with all properties from first database to second database that has the same table, but without this column...?

PS: I didn't find any information about this in documentation...Sorry for my bad English...

**Comment by sdanyliv** [comment]
You are talking about BulkCopy and want to exclude some columns from source entity?

**Comment by YXMagnuMXY** [comment]
No no no! I just want to add new column to existing table.
`ALTER TABLE table_name
ADD column_name datatype; `

**Comment by sdanyliv** [comment]
So, how we can help you here? Show you example how to use SqlBulder for generatig data types and column names?

**Comment by sdanyliv** [comment]
No, we do not have such functionality. Only CreateTable and DropTable.

**Comment by YXMagnuMXY** [comment]
Ok. Then i will use the db.Execute possibility from linq2db.
Thank you!

**Comment by sdanyliv** [comment]
Seems that already answered.
