### ISSUE TITLE
Random NRE in linq2db.dll

### ISSUE THREAD

**Issue by evilbloodydemon** [linq2db/linq2db#111]
I have application that uses NancyFx(self-hosting, if this relevant) + Mysql and when two simultaneous http-request are issued from browser (i.e. /torrents and /movies), i get NRE in linq2db.dll time to time. 
following expression tests are generated then by linq2db (+stacktrace): https://gist.github.com/evilbloodydemon/7ecdba48c8ad776884f7

**Comment by igor-tkachev** [comment]
Fixed.
