### ISSUE TITLE
How to call object's method right after all its properties filled?

### ISSUE THREAD

**Issue by emayblue** [linq2db/linq2db#1112]
Hi there,

I'm designing an object that keeps track of its changes and I want to turn
this tracking on right after properties of the object are filled. Unfortunately,
I cannot find any method that I could override. Also, there seems to be no 
interface that would do such task.

One of the interfaces I have checked is IQueryRunner. It seemed promissing as 
there is a property

Expression MapperExpression { get; set; }

However, I could not make it work.

I'm relatively new to LINQ, so maybe you could point me in the right direction.

Thanks in advance
Eugene

**Comment by ili** [comment]
Hello, @emayblue 

Not clear what are you expecting... `IQueryRunner` used to execute query, `MapperExpression` is used to map from `IDataReader` to query resulting object...

I don't think `IQueryRunner` is a suitable place for your aims. You see, we do make a goal to execute the query, for ex we can do `db.GetTable<Person>().Where(_ => _.DivisionId == 22).Set(_ => _.DivisionId, 1212).Update()`, how should it be tracked if we so not even selected any person with `DivisionId == 22`?

So i would suggest you to make any tracking on your side without trying to integrate this with linq2db, it would be much easier & reliable

**Comment by sdanyliv** [comment]
@ili, I think It should be callback.
```cs
Func<Expression<Action<object>>> AfterInstantiation
```
Then we can build materialization in more effective way;

**Comment by emayblue** [comment]
Yes, that's exactly what I'm looking for. Thanks, ili.

**Comment by MaceWindu** [comment]
OnEntityCreated event was added to IDataContext interface

**Comment by emayblue** [comment]
Thanks a bunch! You guys are awesome!

**Comment by CoskunSunali** [comment]
@MaceWindu I cannot seem to find the OnEntityCreated event within IDataContext interface. I am using the latest Nuget package. What am I missing?

**Comment by sdanyliv** [comment]
@CoskunSunali, not `IDataContext` but `DataConnection` has this event.

**Comment by CoskunSunali** [comment]
@sdanyliv Thank you, that is correct. For anyone reading this post in the future, it comes from the `IEntityServices` interface.

**Comment by MaceWindu** [comment]
Yep, it was moving from one type to another and changing names before stabilized :)

**Comment by MaceWindu** [comment]
OnEntityCreated in release notes:
https://github.com/linq2db/linq2db/wiki/Release-Notes-2.0.0#ientityservicesonentitycreated-delegate
there is no plans to introduce other events, but if you see benefits in it, you can fill feature request :)

**Comment by CoskunSunali** [comment]
Thanks, @MaceWindu!

Cheers.
