### ISSUE TITLE
Cannot access when i use  conn.ChangePassword("string") method.

### ISSUE THREAD

**Issue by thecco** [linq2db/linq2db#1113]
When I connect at sqlite database, throw exception "(26) : file is not a database".

I tried Sqlitebrowser's Set Encryption and this code.

```cs
SQLiteConnection conn = new SQLiteConnection("Data Source=database.sql;Version=3;");
conn.Open();
conn.ChangePassword("pw");
conn.Close();
```

```cs
SQLiteConnection conn = new SQLiteConnection("Data Source=database.sql;Version=3;Password=pw;");
conn.Open();
conn.ChangePassword((string)null);
conn.Close();
```

My environment.
Use ILinqToDBSettings

```cs
public class ConnectionSetting : ILinqToDBSettings
{
    private const string Provider = "SQLite";

    public IEnumerable<IDataProviderSettings> DataProviders { get { yield break; } }
    public string DefaultConfiguration => Provider;
    public string DefaultDataProvider => Provider;
    public IEnumerable<IConnectionStringSettings> ConnectionStrings
    {
        get
        {
            yield return new ConnectionStringSettings()
            {
                Name = "db",
                ProviderName = Provider,
                ConnectionString = "Data Source=database.sql;Version=3;Password=pw;"
            };
        }
    }
}
```

So. I want use password. 
How can I?

Thanks.

**Comment by sdanyliv** [comment]
Looks like you have the same problem:
https://github.com/linq2db/linq2db/issues/992#issuecomment-362912939

**Comment by ili** [comment]
@thecco for now settings are supposed to be constant, `DataConnection` reads and caches them on first creation.

So if you do need change connection string you should either change it at your program startup or use `DataConnection` constructor accepting connection string/connection.

**Comment by sdanyliv** [comment]
@thecco, you have to create DataConnection with connection string by yourself.
ILinqToDbSettings used only for static initialization.
Juts create for your model new constructor which retrieves connection string from somehere else.
This comment shows example: https://github.com/linq2db/linq2db/issues/992#issuecomment-362912939

Also if you have created DataConnection statically you have to recreate this object.

**Comment by thecco** [comment]
@sdanyliv

Is this what you mean?

```
public partial class DatabaseEngine : LinqToDB.Data.DataConnection
{
    public DatabaseEngine() : base("SQLite", "Data Source=database.db;Version=3;Password=pw;")
    {
        InitDataContext();
    }

    partial void InitDataContext();
}
```

But.. same result...

**Comment by ili** [comment]
> but throw exception.

Can you please provide exception details.

**Comment by thecco** [comment]
@ili 

I figured out the reason.
When I set password from SQLiteBrowser, it  used SQLCipher(aes-256-cbc).

How can I cipher in Linq2DB?

**Comment by thecco** [comment]
I solved it.

If set password using SQLiteConnection then set connectionstring like above.
but, when using other program(SQLiteBrowser, SQLiteEditor... ~~) must use  cipher.

**Comment by MaceWindu** [comment]
Well, if it doesn't work, we should figure out what we miss. Some providers have unexpected behavior when work with security configuration. Maybe SQLite is one of them and also needs special handling

**Comment by thecco** [comment]
@MaceWindu 

When I set password using SQLiteBrowser, is not working.
I guess Linq2DB is not support encryption type of SQLCipher.

**Comment by sdanyliv** [comment]
@thecco, 
Maybe this may help?
http://www.bricelam.net/2016/06/13/sqlite-encryption.html
We also just create connection and you have to provide correct connection string.

**Comment by thecco** [comment]
Is this thread closed?

**Comment by MaceWindu** [comment]
No, but we didn't have time to look at it yet...

**Comment by MaceWindu** [comment]
We plan to add new DataConnection events to next release (https://github.com/linq2db/linq2db/pull/1372)
this will allow you to plug-in `pragma key` calls to new connection.

Also we concidering to include helpers for `pragma key/pragma rekey` so people don't need to write them themselves, but no guaranty here
