### ISSUE TITLE
T4models generate incorrect comparison for Microsoft.SqlServer.Types SqlHierarchyId

### ISSUE THREAD

**Issue by TiraelSedai** [linq2db/linq2db#1115]
Hi. I've been generating POCO from MS SQL which uses FILETABLE that use HierarchyID type.

One of the methods generated was:
```cs
		public static MyTableName Find(this ITable<MyTableName> table, SqlHierarchyId PathLocator)
		{
			return table.FirstOrDefault(t =>
				t.PathLocator == PathLocator);
		}
```
Which is correct in all other cases but in this one == doesn't provide bool we are looking for, but instead it is SqlBoolean:
```cs
		public static SqlBoolean operator ==(SqlHierarchyId hid1, SqlHierarchyId hid2);
```
I've fixed it, but it's would be nice to see it included in t4 tool for anybody who would encounter it.
```cs
		return table.FirstOrDefault(t =>
				(t.PathLocator == PathLocator).IsTrue);
```

**Comment by igor-tkachev** [comment]
I think it should be rewritten in this way

```c#
return table.FirstOrDefault(t =>
	(bool)(t.PathLocator == PathLocator));
```
