### ISSUE TITLE
Oracle To_Number()/To_Char()  function or 

### ISSUE THREAD

**Issue by 273168121** [linq2db/linq2db#1124]
How can I do this? have sample code ? 
1.  LIKE  expression convert to sql   SELECT  T.A,TO_NUMBER(XX.B) AS B FROM TB ??   because it cant Compare string  value  "a">"b" in linqexpression.
2.  SQL LIKE  SELECT  SYSDATE FROM DUAL?  or execute sql directly?

**Comment by sdanyliv** [comment]
Let me guess.

1. 
```cs
var query = from t in table
select ConvertTo<int>.From(t.X)
```
2.
```cs
db.Select(() => Sql.CurrentTimestamp);
```

**Comment by 273168121** [comment]
Let me guess.

var query = from t in table
select ConvertTo<int>.From(t.X)
---------------------------------------
thx for reply  ! I'm debug thd code snippets that your provides  ,but  it didn't run on the database server SQL function transformation,  
here is  my code:
var lst_x= from n in ctx.Query<TbXX>() where n.col2== "xx" select ConvertTo<decimal>.From(n.col1); 
              return lst_x.FirstOrDefault();

**Comment by sdanyliv** [comment]
It is because linq2db decides to do evaluation on client side, which is Ok for your example.
Try to wrap conversion in `Sql.AsSql(ConvertTo.From(n.col1))` it should force to do server side calculation.

**Comment by sdanyliv** [comment]
Also ctx.Query<>() what is it? As i know we do not support FromSql query building. So you have client side evaluation, because Query returns IEnumerable.

**Comment by 273168121** [comment]
it is my extends method

**Comment by 273168121** [comment]
it cant convert to sql  , throw exception; 
I'm not found the db function in source code like To_number() or To_char() etc,  except To_date() function

**Comment by 273168121** [comment]
thx very much!!  call between function !!  its very powerful ORM!!!

**Comment by sdanyliv** [comment]
Thanks for good words. Maybe you will find useful our [join extensions](https://github.com/linq2db/linq2db/wiki/Join-Operators) or [Window Functions](https://github.com/linq2db/linq2db/wiki/Window-Functions-(Analytic-Functions)) or [Merge API](https://github.com/linq2db/linq2db/wiki/Merge-API).

Closing then if you already found your convert function.
