### ISSUE TITLE
How can I Create MySqlMetadata's name as I want,but not the same as my db's name?

### ISSUE THREAD

**Issue by traceless0929** [linq2db/linq2db#1130]
As we know, We should code "LoadMySqlMetadata("server ip", "DBname", "uid", "pwd");" in our t4 template,and then we run t4 template.we can get a dbcontext class file named "*.generated.cs" . 
The first class is named "public partial class DBname: LinqToDB.Data.DataConnection".

We can see the name is followed with our DB's name.

So how can I get the class with the name like  "public partial class NameIWant: LinqToDB.Data.DataConnection" but not the same as my db's name?

Oh, I use linq2db in my C# project (net core 2.0)

**Comment by sdanyliv** [comment]
Almost everything are configurable.
[Configuring generation process](https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#configuring-generation-process)

**Comment by traceless0929** [comment]
@sdanyliv ops , thank you for help.

**Comment by sdanyliv** [comment]
@MaceWindu, better to move this documentation to articles.
