### ISSUE TITLE
Repeated construction of context using FluentMappingBuilder gets slower each time

### ISSUE THREAD

**Issue by devinlyons** [linq2db/linq2db#1146]
### Issue
Repeatedly creating context classes when some attributes are set with the FluentMappingBuilder causes each construction to get slower. For a simple database, like the one in my example, it not very noticeable. However, for a complex database, the growth is much faster. I am using linq2db in a long running process that can run for days which makes this issue significant.

#### Workaround
To work around this, I just use a static boolean to tell me if the context has already been initialized. However, the implementation of linq2db does not lend itself to this solution.

#### Proposed Solution
Would it be possible to provide a virtual method to the DataConnection class provides an instance of the FluentMappingBuilder that can be overridden. This would allow linq2db to manage the initialization logic.

### Steps to reproduce
Create the Test database with an Example table and run the attached program.

```c#
using System;

namespace Linq2Db.FluentDataMapperIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            long i = 0;
            long lapSize = 10000;
            DateTime start = DateTime.Now;
            DateTime lastLapStart = start;

            while (true)
            {
                i++;
                TestDbContext context = new TestDbContext("SqlServer", "Server=<<sqlserveraddress>>;Database=Test;Trusted_Connection=True;");
                context.Dispose();

                if (i % lapSize == 0)
                {
                    DateTime now = DateTime.Now;
                    TimeSpan totalTime = now - start;
                    TimeSpan totalAverage = new TimeSpan(totalTime.Ticks / i);

                    TimeSpan lapTime = now - lastLapStart;
                    TimeSpan rollingAverage = new TimeSpan(lapTime.Ticks / lapSize);

                    lastLapStart = now;

                    Console.WriteLine($"Iteration {i}: Total: {totalTime}, Lap: {lapTime}, Average: {totalAverage}, Rolling: {rollingAverage}");
                }
            }
        }
    }
}
```

```c#
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace Linq2Db.FluentDataMapperIssue
{
    public class TestDbContext : DataConnection
    {
        public TestDbContext(string providerName, string connectionString)
            : base(providerName, connectionString)
        {
            this.Initialize();
        }

        public ITable<Example> Examples => this.GetTable<Example>();

        public void Initialize()
        {
            FluentMappingBuilder builder = this.MappingSchema.GetFluentMappingBuilder();

            builder.Entity<Example>()
                .HasPrimaryKey(e => e.Id)
                .HasIdentity(e => e.Id)
                .HasColumn(e => e.Description)
                .HasAttribute(e => e.Description, new NotNullAttribute());
        }
    }
}
```

```c#
namespace Linq2Db.FluentDataMapperIssue
{
    public class Example
    {
        public long Id { get; set; }
        public string Description { get; set; }
    }
}
```

### Environment details
linq2db version: *2.0-rc2*  
Database Server: *SqlServer*  
Operating system: *Windows 10*  
Framework version: *.NET Core 2.0*

**Comment by devinlyons** [comment]
Just to keep the data logic together. The context is on my companies private NuGet server because there are other programs that use the database. It easier for other developers to work with the context if they don't have to know about initializing the mapping.

**Comment by jogibear9988** [comment]
and why don‘t you like code in your constructor so mapping is only applied once?

**Comment by jogibear9988** [comment]
i think, problem is , if you mapp multiple times with fluent mapping, for each call we add a fluentMetadataReader. So I don‘t think this is smth. we would solve

**Comment by devinlyons** [comment]
It's a workable solution. However, it took me quite some time to find this issue. It's elusive and anyone who wants the initialization of their mapping logic near the data context can experience the bug unless they know to avoid it. It just seems like a situation where a simple fix and prevent a difficult bug. However, you are right, I have a solid workaround. A fix is unnecessary.

**Comment by sdanyliv** [comment]
@devinlyons, if you like EF way you can create new mapping schema each time and add it to data connection. Your sample changes mapping schema for specific data provider which should be immutable or guarded by singleton.
Also EF calls OnModelCreating only once per data context, so it’s why it works for others. And you have to understand that configuring mapping schema takes time - do it only once!

BTW, why you spend time in configuring schema? In my 5 years of linq2db experience i never use FluentMappingBuilder. Everything are accurately generated by T4 from real database.
