### ISSUE TITLE
Oracle managed for netcore packaging

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#1156]
A while ago I submitted https://github.com/linq2db/linq2db/pull/1016 which added support for the managed core driver that was published by oracle. (Incidentally they now allow nuget consumption via https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.12.0-beta2)

I currently can't actually choose any of the linq2db oracle packages that I am aware of and install them from nuget into my existing net core app. I suspect there are things we have to do for the nuget packaging of oracle for this to be able to work (letting it know that managed supports net 4.x and netstandard2).

If this is something that does in fact have to be changed, would anyone be able to make necessary changes so that either managed provider supports core and full framework, or provide necessary guidance so I can do that?

**Comment by ili** [comment]
I'll look closer this week

**Comment by ronnyek** [comment]
I dont know whether the nuget packages target netcore 2.0 or if they only target 2.1. You are definitely correct about them not being in full release state... currently beta2 of unknown beta counts, just trying to  help do what I can in hopes that when the library does FINALLY ship, we can start consuming it from our .net core apps

**Comment by ronnyek** [comment]
Is there anything I can do to help this effort out? (if its not already resolved) I realize you guys are busy, and probably (luckily) not oracle consumers

**Comment by MaceWindu** [comment]
I will check it this weekend, so we can include it into 2.1 release next week.
If you can fix it before weekend and send PR, it will also help.

**Comment by ronnyek** [comment]
I'm having difficulty getting the netcore tests running for the oracle provider... It does look like it could be as simple as removing any hard references to the oracle .net core library (if they even exist) and additionally add the Oracle.ManagedDataAccess.Core library from nuget along side the the oracle.ManagedDataAccess package. It would appear that for what linq2db would care about, they are namespace compatible.

**Comment by ronnyek** [comment]
I managed to get the oracle reference updated, and tests passing... pr is #1199 

I'd still like some assistance in figuring out the packaging of all of this, so ultimately we have a linq2db.Oracle.Core, or if core dll can just be added to oracle managed nuget, that would be even better.

If we wanted to expose this as a netcore nuget package, would we just need to make something of a clone of the linq2db.Oracle.Managed.nuspec like linq2db.Oracle.Core.nuspec?

**Comment by MaceWindu** [comment]
Closed by #1199, #1242
