### ISSUE TITLE
Where should I place fluent mappings?

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#1160]
Hi there!

I am wandering if I could use `fluent mapping` to define all mappings. I am not happy to see models polluted with attributes and tried to use `code first` way like EF does and it's work.

But only place where I think these mappings should be placed is constructor of "context" derived from  `DataConnection` . But every time I create new "context", I will get all mapping run again. 

Is there any "legal" way to use fluent mappings and not doing ugly things like this to get it run once:
```C#
    public class Context : DataConnection
    {
        public Context() : base(LinqToDB.ProviderName.SqlServer2012, "connection string")
        {
            if (mappingSchema == null)
                mappingSchema = InitContextMappings(this.MappingSchema);
        }

        public ITable<User> Users => GetTable<User>();
        public ITable<UserAddress> UserAddress => GetTable<UserAddress>();

        private static MappingSchema mappingSchema;

        private static MappingSchema InitContextMappings(MappingSchema ms)
        {
            ms.GetFluentMappingBuilder()
                .Entity<User>()
                .HasTableName("Users")
                .HasPrimaryKey(x => x.UserId).HasIdentity(x => x.UserId);

            ms.GetFluentMappingBuilder()
                .Entity<UserAddress>()
                .HasTableName("UsersAddresses")
                .HasPrimaryKey(x => new { x.UserId, x.AddressId })
                .Association<User>(x => x.User, (y, z) => y.UserId == z.UserId);

            return ms;
        }
    }
```

If I would have complex data model, this mapping initialization could consume some noticeable time to execute.

And second question: does L2DB caches it's context model build with "classic" way with model annotated with attributes, between `DataConnection` instances like it happens in EF?

**Comment by jogibear9988** [comment]
Why should this be an ugly way? You could also use the static constructor of your class

**Comment by Usaga** [comment]
So, there's nothing wrong having `MappingSchema` with mappings saved somewhere in static\global place?

**Comment by Usaga** [comment]
Nice! Thanks for good idea.

**Comment by Usaga** [comment]
And what about caching of Schema build with attributes-way? Is it cached or I should store MappingSchema same way as for fluent mapping?

**Comment by MaceWindu** [comment]
It is cached on MappingSchema instance level, so answer is: yes, you should reuse schema instance.

**Comment by Usaga** [comment]
Thank you.
