### ISSUE TITLE
Table Name Generation (extra ToLower())

### ISSUE THREAD

**Issue by Trigun27** [linq2db/linq2db#1161]
Good afternoon.
After the linq2db.SqlServer library was updated to version 2.0, the generation of table names from the database was changed.

An example is this:
**Old version:**
_MilestoneColor_Milestone_ -> _MilestoneColorMilestone_ 
_MilestoneGroup_Milestone_ -> _MilestoneGroupMilestone_

**New version:**
_MilestoneColor_Milestone_ -> _MilestonecolorMilestone_ 
_MilestoneGroup_Milestone_ -> _MilestonegroupMilestone_

The function SplitAndJoin has changed in DataModel.ttinclude

**Old version:**
```c#
static string SplitAndJoin(string value, string join, params char[] split)
{
  var ss = value.Split(split, StringSplitOptions.RemoveEmptyEntries)
    .Select(s => char.ToUpper(s[0]) + s.Substring(1));

  return string.Join(join, ss.ToArray());
}
```

**New version:**
```c#
static string SplitAndJoin(string value, string join, params char[] split)
{
  var ss = value.Split(split, StringSplitOptions.RemoveEmptyEntries)
    .Select(s => char.ToUpper(s[0]) + s.Substring(1).ToLower());

  return string.Join(join, ss.ToArray());
}
```
In new version additional method ToLower() executed. I would like to know is it a feature or some kind of a bug? It will be really sad to rewrite some code to support new tables name,which does not correlate with the c# code style.
### Environment details
linq2db version: *2.0.0*

**Comment by MaceWindu** [comment]
Looks like incorrect fix of ALLCAPS case.

**Comment by MaceWindu** [comment]
I would say it is a bug, so you just need to alter template locally and we will fix it in next releas
