### ISSUE TITLE
Failed to generate postgres DataModel with all functions from db schemas

### ISSUE THREAD

**Issue by AndreyKhm** [linq2db/linq2db#1162]
Hello. The RSDN topic http://rsdn.org/forum/prj.rfd/6989413.1 says that i must ask questions here, but i can't see here any button like "Ask question", so i will create the issue.

How i can get generated data model  from postgres db with all stored procedures, i.e. "functions", as they named in postgres? 

I'm using linq2db.Core 1.10.2. Here is code inside t4 template:
```
GetSchemaOptions.ExcludedSchemas = new[] { "Link" }; 
NamespaceName = "MyApi.Persistence.DataModel";
GenerateFindExtensions = false;
LoadPostgreSQLMetadata("localhost", "15432", "db", "postgres", "password");
GenerateModel();
```

After this, i got the file named "PostgreSQL.Core.generated.cs" with all needed tables, but i can't find any function. No one. Nothing. All functions is located in "public" schema and available for reading by user "postgres".

In sources, in file "LinqToDB.Templates\README.md" i can't find an options to enable or disable wrappers generation for stored procedues and other routines. 

I found the issue https://github.com/linq2db/linq2db/issues/792 with glorious advice "...when you create LINQ to DB Connection, uncheck "Include Stored Procedures and Functions" option.". I downloaded and explored sources of LinqPad, found delightful mapping of this option to property "IncludeRoutines" and more to come - mappting of that property to next - "ExcludeRoutines"! But i can't find a link between this "option" and any of options of t4 generator.

So, most of all DB projects is legacy. If one want to use linq2db with them, he must be able to EASY get all DB schema into his code and play with it. Without all these code digging like mine experience.

**Comment by MaceWindu** [comment]
Right now schema provider for postgresql doesn't support functions. Will work on it
