### ISSUE TITLE
Failed to generate Model for MsAccess Provider

### ISSUE THREAD

**Issue by FrantzUml** [linq2db/linq2db#1164]
First with an 'accdb' database, there's an error 'database format'.

Retrograding the 'accdb' to an 'mdb' file format (access 2000), there's an another error at :
- DataModel.ttinclude
- Line 103 : var db = sp.GetSchema(dataConnection, GetSchemaOptions);
- Error = Exécution de la transformation : System.InvalidOperationException: La séquence ne contient aucun élément.
   à System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   à LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   à Microsoft.VisualStudio.TextTemplatingBA95FE6E378FC051EB5424991BA86F9697C09BFC61F1F5EA302D4727C696B5D7C7E3D16F890A5DE6EE92186DECC05C1CA43DC009A87504E336B89221DFF8728D.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) dans D:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:ligne 103
   à Microsoft.VisualStudio.TextTemplatingBA95FE6E378FC051EB5424991BA86F9697C09BFC61F1F5EA302D4727C696B5D7C7E3D16F890A5DE6EE92186DECC05C1CA43DC009A87504E336B89221DFF8728D.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) dans D:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:ligne 413
   à Microsoft.VisualStudio.TextTemplatingBA95FE6E378FC051EB5424991BA86F9697C09BFC61F1F5EA302D4727C696B5D7C7E3D16F890A5DE6EE92186DECC05C1CA43DC009A87504E336B89221DFF8728D.GeneratedTextTransformation.LoadAccessMetadata(String path, String database) dans D:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.Access.ttinclude:ligne 24
   à Microsoft.VisualStudio.TextTemplatingBA95FE6E378FC051EB5424991BA86F9697C09BFC61F1F5EA302D4727C696B5D7C7E3D16F890A5DE6EE92186DECC05C1CA43DC009A87504E336B89221DFF8728D.GeneratedTextTransformation.TransformText() dans D:\Users\xx\Documents\Programmation\csharp\EssaiModel\EssaiModel\ModelLayer\FLData.tt:ligne 34	Fichiers divers	D:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude	103

Any idea on this issue ?

Thanks

**Comment by MaceWindu** [comment]
it would be nice if you can provide db file (without data) for debugging or identify which foreign key gives linq2db problem.

**Comment by FrantzUml** [comment]
Hello,

For the 'accdb' access database, I've changed the connection string (in app.config and in LinqToDB.Access.ttinclude) like this : 
LinqToDB.Data.DataConnection GetAccessConnection(string path, string database)
{
	return GetAccessConnection(string.Format(
		"Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Persist Security Info=True;OLE DB Services=-13",
		System.IO.Path.Combine(path, database)));
}
and using NuGet Package of Linq2DB version 2.0.0, I've got error :
System.Data.OleDb.OleDbException (0x80004005): Format de base de données ('C:\Developpement\Essai.accdb') non reconnu.
   à System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   à System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   à System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   à System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   à System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   à System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   à System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   à System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   à System.Data.OleDb.OleDbConnection.Open()
   à LinqToDB.Data.DataConnection.get_Connection()
   à LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   à Microsoft.VisualStudio.TextTemplating537036BFE774790B3BCA10B10253BA2ABC7ED0A520973486FAAC8515A97339AF0E51637E6657CEA302A6ABD605816F34551B646D4656122BE09631A7F59EC284.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) dans C:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:ligne 103
   à Microsoft.VisualStudio.TextTemplating537036BFE774790B3BCA10B10253BA2ABC7ED0A520973486FAAC8515A97339AF0E51637E6657CEA302A6ABD605816F34551B646D4656122BE09631A7F59EC284.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) dans C:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:ligne 413
   à Microsoft.VisualStudio.TextTemplating537036BFE774790B3BCA10B10253BA2ABC7ED0A520973486FAAC8515A97339AF0E51637E6657CEA302A6ABD605816F34551B646D4656122BE09631A7F59EC284.GeneratedTextTransformation.LoadAccessMetadata(String path, String database) dans C:\Users\xx\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.Access.ttinclude:ligne 24
   à Microsoft.VisualStudio.TextTemplating537036BFE774790B3BCA10B10253BA2ABC7ED0A520973486FAAC8515A97339AF0E51637E6657CEA302A6ABD605816F34551B646D4656122BE09631A7F59EC284.GeneratedTextTransformation.TransformText() dans C:\Users\xx\Documents\Programmation\csharp\EssaiModel\EssaiModel\ModelLayer\FLData.tt:ligne 35		C:\Users\Franck\Documents\Programmation\csharp\EssaiModel\packages\linq2db.Access.2.0.0\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude	103	

The DB Engine for 2016 Access is 32 bit, so I've compiled in 'Any CPU', in '32 bits" but always the same error.

With donwgrading the database to 'mdb' format, it does not seem corrupted, I send you a copy without data.

Thanks you

**Comment by FrantzUml** [comment]
Sorry,

Herre the database without data :
[Essai1 - Copie.zip](https://github.com/linq2db/linq2db/files/2053694/Essai1.-.Copie.zip)

**Comment by MaceWindu** [comment]
Ok, I've create fix for issue with mdb: https://github.com/linq2db/linq2db/pull/1167
I will merge it soon and then it will appear on myget a bit later.

Regarding accdb issue - it is some issue with ACE provider itself. You can try to remove this part "Persist Security Info=True;OLE DB Services=-13" from conenction string to leave only provider and database file parameters

**Comment by MaceWindu** [comment]
Regarding ACCDB file issue. I was reading this topic https://stackoverflow.com/questions/13884080/corrupted-access-accdb-file-unrecognized-database-format
and looks like it could be various reasons: from corrupted database file to wrong ACE provider version - you should try it yourself

**Comment by MaceWindu** [comment]
Fix was merged and will be available soon on myget
