### ISSUE TITLE
Generated association variable names changed...

### ISSUE THREAD

**Issue by ezsoftware** [linq2db/linq2db#1165]
I added a new column to our database and tried to generate the model, and it didn't generate everything the same way as it did before (for the other developer).

For example, the other developer has this association generated

		/// <summary>
		/// FK_Features_Fabricator
		/// </summary>
		[Association(ThisKey="Fabricator_id", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Features_Fabricator")]
		public CustomerBase FeaturesFabricator { get; set; }

While for me, it generates like this:

		/// <summary>
		/// FK_Features_Fabricator
		/// </summary>
		[Association(ThisKey="Fabricator_id", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Features_Fabricator")]
		public CustomerBase CustomerBase{ get; set; }

This is causing issues with code written based on one system, and then the code is generated by another.

I haven't been able to find any reason for why this is happening, is there any way I can get my system to generate the associations the same way as the other developers?

using linq2db 1.10.2

Thanks

**Comment by integral-llc** [comment]
As an addition to the  above comment.
See the picture, before the association would be derived from the FK itself `FK_Features_Fabricator` -> `FeaturesFabricator`, now for some reason became `Fabricator_`. 
That's a big breaking change guys, the whole project got stuck now because of this.

![image](https://user-images.githubusercontent.com/1841073/40680616-969924d2-633b-11e8-8576-25d659af1252.png)

**Comment by MaceWindu** [comment]
I'm not sure that we need to support pre-2.0 name generation logic out of box.
I would recommend to add following snippet to your tt file with old name generation logic as a fix (adjust it if it doesn't reproduce old behavior correctly):
```cs
GetSchemaOptions.GetAssociationMemberName = key =>
{
	var name = key.MemberName;
	var thisTable = key.ThisColumns[0].Table;

	if (key.BackReference != null && key.ThisColumns.Count == 1 && key.ThisColumns[0].MemberName.ToLower().EndsWith("id"))
	{
		name = key.ThisColumns[0].MemberName;
		name = name.Substring(0, name.Length - "id".Length);

		if (thisTable.ForeignKeys.Select(_ => _.MemberName).Concat(
			thisTable.Columns.Select(_ => _.MemberName)).Concat(
			new[] { thisTable.TypeName }).All(_ => _ != name))
		{
			name = key.MemberName;
		}
	}

	if (name == key.MemberName)
	{
		if (name.StartsWith("FK_"))
			name = name.Substring(3);

		if (name.EndsWith("_BackReference"))
			name = name.Substring(0, name.Length - "_BackReference".Length);

		name = string.Join("", name
			.Split('_')
			.Where(_ =>
				_.Length > 0 && _ != thisTable.TableName &&
				(thisTable.SchemaName == null || thisTable.IsDefaultSchema || _ != thisTable.SchemaName))
			.ToArray());

		var digitEnd = 0;
		for (var i = name.Length - 1; i >= 0; i--)
		{
			if (char.IsDigit(name[i]))
				digitEnd++;
			else
				break;
		}

		if (digitEnd > 0)
			name = name.Substring(0, name.Length - digitEnd);
	}

	if (string.IsNullOrEmpty(name))
		name = key.OtherTable.TableName;

	return name;
};
```

@it, @sdanyliv  what do you think?

**Comment by MaceWindu** [comment]
looks like we need to fix it on our side

**Comment by MaceWindu** [comment]
Don't think we will address it. please use provided workaround
