### ISSUE TITLE
Implement Merge into updatable query or CTE

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#1166]
The current merge API accepts only `ITable<TTarget>` as a merge target.  In Microsoft SQL Server at least it is valid to have any updatable query or CTE as the target of a merge statement.

Specifically this is useful when updating certain types of history tables or slowly-changing dimensions (Type 2 specifically) in data warehouse environments.  In the case of Type2 SCDs the merge target is the subset of rows that are currently active.  All of the terms of the merge act on the selected subset of the data rows.

For example, a partial update of a Type2 SCD:

	MERGE INTO (SELECT * FROM myTargetTable WHERE IsCurrent = 1) t
	USING mySourceTable s
	ON s.ID = t.ID

	-- Close changed records
	WHEN MATCHED AND s.SomeIntField <> t.SomeIntField THEN
		UPDATE SET EndTime = GETDATE(), IsCurrent = 0

	-- Close deleted records
	WHEN NOT MATCHED BY SOURCE THEN
		UPDATE SET EndTime = GETDATE(), IsCurrent = 0

	-- Append new records
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (ID, StartTime, EndTime, IsCurrent, SomeIntField)
		VALUES (s.ID, GETDATE(), '31-Dec-2999', 1, s.SomeIntField)
	;

If the merge is run against all of the rows in the table it will have unintended consequences.

I acknowledge that this may be out of scope, and Data Warehouse updates should almost always be done with stored procedures, but it seems like a desirable feature to implement.

**Comment by MaceWindu** [comment]
Interesting, didn't know it is possible. I would say it is not out-of-scope, but it will take some time to implement as we have other things on our radar ATM.

**Comment by Corey-M** [comment]
@MaceWindu I've been doing some data warehouse stuff recently - all stored procedures of course - and was toying with the idea of doing the same sort of thing in C#.  Looking over the new Merge API it struck me as odd that the target was `ITable<T>` instead of `IQueryable<T>` when the SQL Server MERGE statement supports queries as targets.

The downside is that you can't easily validate whether the target is writable when you're building the SQL statement.  You have to trust that the coder knows what they are doing.

This isn't a high priority, just a matter of completeness.  I think in general once you get to this level of complexity it's safer and cleaner to use stored procedures.

**Comment by Corey-M** [comment]
Correction, you can't inline your updatable query as I had it above.  It has to be either an updatable view or a CTE.  The [`MERGE` docs][1] explicitly mention merging to a view but omit mention of a CTE as a valid target.  I suspect that CTEs are treated similarly to views in most cases - anything you can do to a view (apart from the obvious things like dropping or altering them) you can do with CTEs.

So to get the above I could do this instead:

    WITH cteTarget AS (SELECT * FROM myTargetTable WHERE IsCurrent = 1)
    MERGE INTO cteTarget t
    ....

Not sure if it will make it simpler to implement, but CTE support in Linq2DB 

[1]: https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql
