### ISSUE TITLE
Modification the query expression tree

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#1176]
Is there a way to dynamically modify query expressions?

I.e. I need to convert all query expressions with the usage of Contains to the solution from issue #973 
I can make an ExpressionVisiter, that does this, but I don't know where can I intercept the final expression.

Can you help, please?

**Comment by sdanyliv** [comment]
Somewhere in initialization part of your application. Invoke this:
```cs
Expressions.MapMember(
    (IEnumerable<int> source, int value) => source.Contains(value), 
    (source, value) => source.In(value)
);
```

**Comment by arwyl** [comment]
Wow, nice, thank you!
