### ISSUE TITLE
LinqToDB.Sql.Between handles struct `null` values incorrectly / counter-intuitively

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#1180]
In my view the current implementation for nullable structs handles null values incorrectly (or at least counter-intuitively). null values should be completely ignored instead of actually compared. For example, `query.Where(x => x.Number.Between<int>(1, null))` should be evaluated as `Number >= 1` not as `Number between 1 and NULL` which can never evaluate to `true`.

A query like `query.Where(x => x.Number.Between<int>(null, null))` should be ignored altogether.

Current implementation:
https://github.com/linq2db/linq2db/blob/b4998d6bf39ebbd55cb385335d0fcb9b45d82e35/Source/Sql/Sql.cs#L101

**Comment by sdanyliv** [comment]
You have to do that yourself. `Between` is not an option here - it’s syntax sugar that requested for not nullable situations.
Something like this, which more correct and gives better performance and clear SQL:
```cs
if (start != null)
   query = query.Where(e => e.Value >= start);

if (end != null)
   query = query.Where(e => e.Value <= end);
```

**Comment by JechoJekov** [comment]
@sdanyliv Yes - I agree. My point is that the `Between` method does accept nullable values which is misleading since the result is unexpected.

**Comment by sdanyliv** [comment]
@JechoJekov, unfortunatly we have to accept this limitation, otherwise Expression caching will no work.
`Sql.Between(x.Number, varStart, varEnd)` will produce SQL with parameters which are dynamic and we can not optimize this part without knowledge of real values. After second run query reused and just parameters changed.

**Comment by JechoJekov** [comment]
@sdanyliv I see. OK, thanks for explaining. Will close this issue now.

You have a great product BTW - I love it! :-) Thank you for all your hard work :-)

**Comment by sdanyliv** [comment]
Thanks for good words ;)
