### ISSUE TITLE
2.0.0 is released but nuspec still has 2.0.0-rc

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#1183]
```
<id>linq2db</id>
<version>2.0.0-rc</version>
<title>LINQ to DB</title>
```

> Release 2.0.0
> MaceWindu released this 24 days ago

**Comment by MaceWindu** [comment]
This is only in repository. When published to nuget/myget, deployment script patches version. Maybe we should just put something like `WILL_BE_UPDATED_ON_DEPLOY` placeholder to not bother with it?

**Comment by hardhub** [comment]
But if you locally build source code using Build.cmd then it uses nuspec values for such packages.

**Comment by MaceWindu** [comment]
makes sense. Should be updated to 2.1.0
