### ISSUE TITLE
ExecuteReaderAsync should use CommandBehavior

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#1185]
The question is well explained here:

https://stackoverflow.com/questions/28543293/entity-framework-async-operation-takes-ten-times-as-long-to-complete/

Linq2db is affected as well. So it has terrible performance with byte[] columns (varbinary(Max)).

CommandBehavior.SequentialAccess increase speed maybe in ten times.

**Comment by hardhub** [comment]
Maybe it will be good to add overloaded method to 'public static class AsyncExtensions'.
So developer can decide which CommandBehaviour should be used.

**Comment by sdanyliv** [comment]
Yes we have to fix that place. 
Also, i think, we can handle this situation in queries automatically because we know from which tables we selecting data.

**Comment by MaceWindu** [comment]
We will fix direct use of CommandBehavior for next release so people could override GetCommandBehavior method, but SequentialAccess support in linq2db needs more research and testing, so probably it will not be a part of release.

**Comment by hardhub** [comment]
Regarding command behaviour.

For now I am using the following simple fix in real-world project (with fixed Linq2db source code):

```C#
public override CommandBehavior GetCommandBehavior(CommandBehavior commandBehavior)
        {
            return base.GetCommandBehavior(commandBehavior) | CommandBehavior.SequentialAccess;
        }
```

Using long time on production I can say it does not look like problematic.  
But it fixes dramatic performance decrease during async fetch of byte array.
