### ISSUE TITLE
DataProvider.Oracle wrong sql generated

### ISSUE THREAD

**Issue by Gonzo47110815** [linq2db/linq2db#1186]
Hello guys!
I'm currently having some trouble with linq2db.
I use Devexpress xtragrid with Linqdatasource.
When the grid data is filtered by string property, linq2DB generates sql like this

```sql
SELECT
	Count(*) as cnt
FROM
	TestClasst1
WHERE
	Lower(t1.StringProperty) LIKE '%windows%'
```

this is wrong because you never get rows, which starts or ends with 'windows'.
The correct statement should be:

```sql
SELECT
	Count(*) as cnt
FROM
	TestClasst1
WHERE
instr( Lower( t1.StringProperty) , 'windows')  > 0

```
you can reproduce the sql statement like this:
  `var data = db.GetTable<TestClass>().Where(x =>    x.StringProperty.ToLower().Contains("windows"));
`

### Environment details
linq2db version: *2.0.0*  
Database Server: *E.g. PostgreSQL 9.6.3*  
Database Provider:  Oracle.ManagedDataAccess 3.2.3*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.5.2*

**Comment by jogibear9988** [comment]
if you look at https://docs.oracle.com/cd/B13789_01/server.101/b10759/conditions016.htm the % matches zero or more characters

**Comment by Gonzo47110815** [comment]
Hi,

ops, I tested it and you are right with this. I compare only the results from xtraGrid using XPObjects and Linq2Db. It seems that XPObjects (over XAF) the search is not casesensitiv.
Is there a change to change the behaviour when using linq2db?
I have no chance to change the linq query, it is build from the xtraGrid.

best regards

**Comment by sdanyliv** [comment]
@Gonzo47110815, which query you have prepared for xtraGrid grid?

**Comment by Gonzo47110815** [comment]
Hi sdanyliv,

the query is created by the gridview, when the user filters data by autofilterrow.
I only found this at devexpress:
DevExpress.Data.Helpers.ServerModeCore.DefaultForceCaseInsensitiveForAnySource = true;
which makes all searches caseinsensitive. But I'm not happy with this workaround.

**Comment by sdanyliv** [comment]
If you are familiar with Expression tree, you can implement `IExpressionPreprocessor` Interface in your DataConnection class and correct tree.
But in your case it is better when xtraGrid will expose settings how to compare strings.
