### ISSUE TITLE
RetryPolicy for ServiceModelDataContext

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1187]
Hello,

is there also a RetryPolicy for the ServiceModelDataContext class?

**Comment by sdanyliv** [comment]
Why just do not specify RetryPolicy on the server side DataConnection?
I never played with linq2db WFC Services this should be right way.

**Comment by Franki1986** [comment]
I am setting the retry policy in my server side constructor. I did not know that this would be called also by the service. I will try and report.

**Comment by MaceWindu** [comment]
No report - no fix :D
