### ISSUE TITLE
Global Expression method

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1188]
Hello,

Is there any way to create mapping with an ExpressionMethodAttribute and call a method that is not defined in the class itself? Say that I couod call a global defined method in multiple classes for mapping.
In my case I would like to map a property to a column if it exists, if my database version is older and the column does not exists in this version, I would overwrite thr mapping for this property to an ExpressionMethod that receives the default value.

```
// column exists 
[Column("Test")]
Public string TestProperty{ get; set}

// column does not exist
[ExpressionMethod("DefaultStringValueMethod"), IsColumn= true]
Public string TestProperty {get; set;}
```

**Comment by sdanyliv** [comment]
@Franki1986, so [this method](https://github.com/linq2db/linq2db/issues/1040#issuecomment-373310627) do not work for you?

**Comment by Franki1986** [comment]
This works, but so I have to write every time a new query. If I could overcome this directly in mapping it would be easier. This is no feauture request I know that this is not an every day use case, but if there is the possibilty I would use it.
Any way to call global methods?

**Comment by sdanyliv** [comment]
I do not see possiblity. Expression method expects appropriate type for entity, but you can always create dynamic method generator that of course should be marked as expression method.
Everything that you have mentioned you can do by our T4 scripts. Add attribute, add method to the entity wih body. Everything.

**Comment by Franki1986** [comment]
Ok, there is no problem until there is a way for a solution. Thanks for your investigation!

**Comment by Franki1986** [comment]
Closed with this solution [DateTime-Nullable](https://github.com/linq2db/linq2db/issues/1189)
