### ISSUE TITLE
Fluent mapping and ExpressionMethod

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1190]
Is there a way to create fluent mapping with ExpressionMethods?

At the moment I found only this : [Fluent mapping attributes](https://github.com/linq2db/linq2db/issues/961)

**Comment by sdanyliv** [comment]
If no - PR is appreciated. 
Looking on your hard work, and feels that my solution with method that returns correct projection is best way. Even better projection can be dynamically generated by expressions. Everyting in one place even with super calculated columns.

**Comment by Franki1986** [comment]
Ok,
for first thing, I use the given HasAttribute method :-)

```
[Table("CUSTOMER", IsColumnAttributeRequired = true)]
public partial class Customer
{
    [Column("ID"), PrimaryKey, NotNull] public int Id { get; set; } // integer

    [Column("NAME"), NotNull] public string Name { get; set; } // varchar(20)
    
    // set this with fluent mapping
    //[ExpressionMethod(nameof(DefaultDateTime), IsColumn = true)]
    public DateTime? ToDelete{ get; set; }

    static Expression<Func<Customer, DateTime>> DefaultDateTime()
    {
       return p => Sql.AsSql(DateTime.Now); 
    }
}

```
```
var mapping = MappingSchema.Default.GetFluentMappingBuilder();         
         mapping.Entity<Customer>().Property(k => k.ToDelete).IsNotColumn().HasAttribute(new ExpressionMethodAttribute("DefaultDateTime"){IsColumn = true});

```


Strange thing here is that I have to set IsNotColumn, although it is set on class that and the property is not marked with column.

**Comment by MaceWindu** [comment]
Closing, please reopen if you found missing support in fluent mapper
