### ISSUE TITLE
Correct way to manipulate table names while generating model from T4?

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#1192]
I tried to manipulate table names while generating from T4 template. Table names on server look like `T_BATCH`, `T_ANOMALIES` ... and so on. All start with "`T_`" which I want to remove. 

Example:
```
T_BATCH > Batch
T_ANOMALIES > Anomalies
```

I tried to insert a (kind of?) stupid hack in `DataModel.ttinclude` (`.ToValidNameDefault`):

```
if (name.ToUpper().StartsWith("T"))
{
     name = name.Subtring(1);
}
```

But this changed anything in model generation. can someone help me to implement the wish correctly?

Thank you in advance.

linq2db version: *2.0.0*  
Database Server: *SQL Server 2012*   
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
It is easy. You don not have to change our tt files. Just your copy.
How T4 generation works:
1. `LoadDataModel` we load tables, stored procs etc. into our classes and give them names.
2. T4 calls `GenerateModel` - generating from these classes source code.

So you have option - create between steps 1 and 2 additional code that changes class names.
```cs
// Replaces all table names
foreach (var t in Tables.Values)
	if (t.TableName.ToUpper().StartsWith("T_"))
        {
            t.TypeName = t.TableName.Substring(2);
        }
```
But here you have to apply CamelCase by yourself.

[Customizing generation process](https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#customizing-generation-process)

**Comment by sdanyliv** [comment]
Closing for now, will reopen if needed.

**Comment by jdistlr** [comment]
Thank you. Works like a charm!
