### ISSUE TITLE
Instance update not working with dynamic columns

### ISSUE THREAD

**Issue by boris-turk** [linq2db/linq2db#1193]
Hi,

the new dynamic column implementation (described in #964) is great and most of the functionality works like a charm. There is only one feature which still needs to be fixed in my opinion. Consider this test:

		[Test, DataContextSource]
		public void UpdateInstanceWithDynamicColumns(string context)
		{
			using (var db = GetDataContext(context, ConfigureDynamicMyClass()))
			{
				var firstName = Guid.NewGuid().ToString();

				try
				{
					db.GetTable<MyClass>()
						.Value(c => Sql.Property<string>(c, "FirstName"), () => firstName)
						.Value(c => Sql.Property<string>(c, "LastName"), () => "")
						.Value(c => Sql.Property<Gender>(c, "Gender"), () => Gender.Male)
						.Insert();

					MyClass instance = db.GetTable<MyClass>()
						.Single(c => Sql.Property<string>(c, "FirstName") == firstName);

					instance.ExtendedProperties["LastName"] = "Limonadovy";

					db.Update(instance);
				}
				finally
				{
					db.GetTable<MyClass>().Delete(c => Sql.Property<string>(c, "FirstName") == firstName);
				}
			}
		}

Here we simply insert an instance of MyClass into DB, retrieve that instance from DB, modify it a little bit and try to update it with the db.Update(instance) statement, but it fails with an exception. Is it possible to fix that? Thank you in advance,

Boris Turk

**Comment by sdanyliv** [comment]
@boris-turk, possible bug or as designed. I need time to investigate and i do not see whole picture (classes, mapping).
But why not update here using Set/Update?
```cs
db.GetTable<MyClass>()
	.Set(c => Sql.Property<string>(c, "FirstName"), firstName)
        .Update();
```
And simple question why do you need such kind of dynamic processing?

**Comment by boris-turk** [comment]
Hi @sdanyliv ,

thanks for your quick response. We are working on a legacy system which uses some kind of "primitive" ORM implementation and we would like to switch to a modern one. This is only one of the tasks which we have to carry out and we are a little bit under time pressure - as usual :) So our thinking was: let's try to replace the old ORM approach with the new one with as little breaking changes as possible.

Unfortunately this legacy code uses the "instance" update version in most of the cases, which means that if we replace that code with linq2db calls, we need to make sure that the whole record gets updated (no way to rewrite those calls into GetTable/Set/Update approach, the one that you suggest).

But today I discovered the #433 issue where you use reflection to build up an UpdateAll method at runtime. It seems to me that I should be able to use it for my specific case (with some minor adjustments).

I am closing this ticket for now. If there will be major problems with this new approach, then I will contact you again. Thank you very much for your time!

Boris

**Comment by sdanyliv** [comment]
@boris-turk, there is modern version: https://github.com/linq2db/linq2db/issues/1172#issuecomment-394308169

**Comment by boris-turk** [comment]
Thanks a lot @sdanyliv - this looks even more promising. Will have a closer look tomorrow.
