### ISSUE TITLE
Can’t copy and rename CopyMe.MySql.tt.txt file

### ISSUE THREAD

**Issue by panuckov-nick** [linq2db/linq2db#1194]
Can’t copy and rename CopyMe.MySql.tt.txt file because it's a not real, but linked file.

As a workaround it's possible to add to the project original file that is located in package folder, but this solution is not obvious.

### Steps to reproduce
Install Linq2DB 2.0.0 package via Nuget and try rename CopyMe.MySql.tt.txt file

### Environment details
linq2db version: 2.0.0  
Database Server: MariaDB MySQL
Framework version: .NET Core 2.0
Visual Studio 2017
.Net Core SDK 2.1

![screenshot_11](https://user-images.githubusercontent.com/15320216/41597766-085dc0c2-73d7-11e8-8bc5-04605e910dd3.png)

**Comment by ili** [comment]
Hello @panuckov-nick 

This is due to new nuget content system - now all content files are added as links. We should update documentation on it...

For .Net Core you should:
1. create new `tt` file (`Model.tt` for ex)
1. copy content from `CopyMe.MySql.tt.txt` & paste it into your `Model.tt`

**Comment by sdanyliv** [comment]
Reopening for tracking documentation update.

**Comment by MaceWindu** [comment]
We already have this workflow documented at https://linq2db.github.io/articles/get-started/full-dotnet/existing-db.html#generate-model-from-database

I will update instructions in corresponding *.tt.txt files
