### ISSUE TITLE
LoadWith and Views

### ISSUE THREAD

**Issue by lrhmx** [linq2db/linq2db#1200]
Is it possible to use LoadWith with entities created from views? Sure, I can use joins but I want to know if there is a way to load like associations.

**Comment by sdanyliv** [comment]
Views are like tables, so yes, just define in partial entity implementation additional association. But i’m warning you, we will not load list of details only one to one relationships.

**Comment by sdanyliv** [comment]
Closing for now, will reopen if needed.
