### ISSUE TITLE
MONO  and SQLite

### ISSUE THREAD

**Issue by JTrotta** [linq2db/linq2db#1207]
I used for a log time with no problem, **linq2db 1.9 + mono 5.12.0.233 + Mono.Data.Sqlite.dll**.
The last updates to linq2db 2.0.0 and 2.1.0 does not work on mono anymore.
I got this error:"Could not load type 'System.Data.SQLite.SQLiteDataReader' from assembly 'System.Data.SQLite, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' "
But System.Data.SQLite did not ever work on Mono, only Mono.Data.Sqlite has been working since version 1.9.
How can I use  **linq2db 2.1.0 + Mono5.12.0.233**, now?

### Environment details
linq2db version: *2.1.0*
Database Provider: *SQLite*
Operating system: *MONO  5.12.0.233*
Framework version: *.NET Framework 4.7.1*

**Comment by sdanyliv** [comment]
@JTrotta, I've found that we have removed direct Mono support in 2.0.0. 
Could you please confirm if your project can use netstadard2.0 libraries. If yes, we can return extra code that works with `Mono.Data.Sqlite.dll`

**Comment by JTrotta** [comment]
@sdanyliv, in the meanwhile  I have found a solution using System.Data.SQLite.dll 1.0.108.0 + libSQLite.Interop.dll .
But I'd like to what is the best practice (or what you suggest) to use linq2db 2.x with Mono.
Right now I cannot move the netstandard 2.0, but I will do.
Thanks

**Comment by sdanyliv** [comment]
@jogibear9988, can you handle this issue? Also question, does your Mono projects with SQLite works as expected after 2.0.0 release?

**Comment by JTrotta** [comment]
@jogibear9988 please can you tell me how do you use System.Data.Sqlite without the interop file?

**Comment by JTrotta** [comment]
@jogibear9988  may you help me? Such combination of sol (system.data.salute + Interop) you use?

**Comment by jogibear9988** [comment]
Sorry for the delayed answer! How can I help you? What is not working with system.data.sqlite?

Additional Info: In next Version 1.0.109 system.data.sqlite also supports netcore, so we also could use it in such scenarios

**Comment by JTrotta** [comment]
I use Mono, latest version, where can I find the Interop working for MONO?

**Comment by jogibear9988** [comment]
you have to compile it yourself! i‘ll send you a snippet how, when I find it!
where do you want to use it? linux? x86 or arm?

**Comment by JTrotta** [comment]
Thank you.
JJ
