### ISSUE TITLE
Natural Sorting via LINQ

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1212]
Is it possible to implement natural sorting for string Columns? Maybe we need different SQL for each provider?

**Comment by sdanyliv** [comment]
@jogibear9988, better to show samples and documentation links.

**Comment by Franki1986** [comment]
I think this is an often use case scenario! Should we think about an OrderBy with option parameters?
Firebird e.g. has also a possibilty to set Null first or Null last.
Also what to do for fallback. Extract the first part of numbers and split the rest and then order by the rest?

**Comment by gkathire** [comment]
For Sql server, alpha numeric sorting is achieved by custom sqls like the one described in https://www.codeproject.com/Articles/842541/How-Do-I-Use-SQL-Server-to-Sort-Alphanumeric-Value 

My question is how do you convert the custom query like one below to linq2db ? 

SELECT Section
FROM dbo.Section
ORDER BY LEFT(Section,PATINDEX('%[0-9]%',Section)-1), -- alphabetical sort
         CONVERT(INT,SUBSTRING(Section,PATINDEX('%[0-9]%',Section),LEN(Section))) -- numerical sort

I understand OrderBy can have custom expressions, can anyone let me know how to use it in this context ?

**Comment by sdanyliv** [comment]
@gkathire, it is easy if you define your custom sql extension as defined [here SqlExpression](http://blog.linq2db.com/#Sql.Expression)

**Comment by jogibear9988** [comment]
If I have strings like this:

    1
    100
    1000    
    20
    
it would work if I first sort by Length, and then by value. But it will not work If I have strings like this

    0001
    100
    1000
    20

**Comment by sdanyliv** [comment]
@jogibear9988, better to show real values if you need our assitance.

**Comment by sdanyliv** [comment]
Closing issue as answered. For each situation it is needed custom approach.
If you feel that linq2db can not create appropriate query it will be fixed ASAP.
