### ISSUE TITLE
Wrong Sql for .HasValue check

### ISSUE THREAD

**Issue by Trigun27** [linq2db/linq2db#1213]
Hello, find some strange sql. 
I have class _TestClass_ with several properties  and have a select linq statement. 

```
class TestCalss()
{
    public double? SpaceParking { get; set; } // float
    public double? SpaceParkingBuff { get; set; } // float
}
```

For SpaceParkingBuff generats wrong IIF. It's
**IIF ([obj].[SpaceParking] = 1)**
but should be 
**[obj].[SpaceParking] is not null**

```
var query = from cte in cteBase
........
select new TestClass()
{
SpaceParking = obj.SpaceParking != null
? (double?)obj.SpaceParking.Value
: null, 

SpaceParkingBuff = obj.SpaceParking.HasValue
? (double?)obj.SpaceParking.Value
: null,
}
```

generated sql

```
SELECT
	IIF([obj].[SpaceParking] IS NOT NULL, [obj].[SpaceParking], NULL) as [c1],
	IIF([obj].[SpaceParking] = 1, [obj].[SpaceParking], NULL) as [c2],

```
### Environment details
linq2db version: *2.1.0*
Database Server: *MS SQL*
Database Provider: *MS SQL 2012*
Operating system: * Windows 10*
Framework version: *.NET Core 2.1*

**Comment by sdanyliv** [comment]
Fixed in #1215
