### ISSUE TITLE
InsertOrUpdate Not working correctly with identity columns

### ISSUE THREAD

**Issue by Terricide** [linq2db/linq2db#1216]
I'm running linq2db 2.1 and I am trying to use the insertorreplace command it is failing complaining about the identity column. Like it is trying to insert it even though I didn't set it. I can see that it defaults to 0. If I use Insert it works fine. 

### Environment details
linq2db version: 2.1.0
Database Server: Sql Server
Database Provider: *E.g. Npgsql 3.2.3*
Operating system: *E.g. Windows 10*
Framework version: *.NET Framework 4.7.1*

**Comment by sdanyliv** [comment]
@Terricide, please provide us with DataModel and simple sample of InsertOrReplace usage.
Thanks.

**Comment by sdanyliv** [comment]
Closing for now. We need more information. Will reopen if needed.
