### ISSUE TITLE
Informix support in linq2db

### ISSUE THREAD

**Issue by bert1973** [linq2db/linq2db#122]
Hi,

I get an exception using a connection for informix 11.50:
Error   1   Running transformation: System.ArgumentException: SQL_INFX_ATTR_CALL_FROM_DOTNET - no error information available

On the internet I read it would be a problem with a non-up to date odbc driver (http://www-01.ibm.com/support/docview.wss?uid=swg21609618).

This could be, however isn't it better to support Informix by using the IBM.Data.DB2.dll from the IBM data packet driver? This is the prefered way now by IBM, as the IBM Informix .NET Provider is no longer being enhanced for new .NET APIs.

When I use IBM.Data.DB2.dll, I get another error:
Error   2   Running transformation: IBM.Data.DB2.DB2Exception (0x80004005): ERROR [42000] [IBM][IDS/UNIX32] The specified table (sysibm.sysdummy1) is not in the database. (-111 ISAM error:  no record found.)
This message is true for informix. However is use of sysdummy1 needed? And if so, what if the connection would determine:
DB2 -> use sysdummy1
Informix -> use systables where tabid=1

Kind regards,
Bert

**Comment by emmanuelpereira** [comment]
@bert1973 I'm too interested. How do I get this changes you did?

**Comment by bert1973** [comment]
Hello Emmanuel,
That's a long time ago I did that code changes, as I don't work with Informix db's anymore.
I searched my disk, but can't find the changes anymore, I guess I did them at work with my previous employer.
I'm sorry, even if I read my own comments in the post on GitHub, it's not directly sheading light on what I did.

Are you receiving certain problems?
Kind regards,Bert

**Comment by emmanuelpereira** [comment]
2y ago wow 😲 ! thanks for replying!
I've been facing some problems with old versions of ifx, but Just in some cases like T4 POCO generation in linq2db, so I saw your comment and tried to solve it in my fork of this repo.
I found a problem in nullable decimal (ifx) and fixed it.
I'm working in changes principally for informix.
My T4 generation Works like a charm now 🙂

Even so, thanks for searching 😊

**Comment by sdanyliv** [comment]
@emmanuelpereira, could you please confirm that problem still exists in current linq2db sources. Thanks.

**Comment by emmanuelpereira** [comment]
@sdanyliv the problem seems solved right now.. Updating sources and rebuilding the project worked for me

Thanks.

**Comment by sdanyliv** [comment]
@bert1973, clossing for now. Will reopen if needed.
