### ISSUE TITLE
Method GetProcedures is not overidden in PostgreSQLSchemaProvider class and thus returns null

### ISSUE THREAD

**Issue by Shimon91** [linq2db/linq2db#1220]
Hi,

The method GetProcedures is not overidden in the PostgreSQLSchemaProvider class.

Therefore, it fallbacks to the virtual method's implementation back in SchemaProviderBase which returns null.

Thus, The Procedures property in the LinqToDB.SchemaProvider.DatabaseSchema class is always an empty list and thus the procedures are not actualy generated by the DataModel.ttinclude (the code section of "var procedures = db.Procedures.Select(p => new { ... });" returns an empty list.

Steps to reproduce
Create a simple subclass of DataConnection, e.g MyDataConnection:

        public partial class MyDataConnection : LinqToDB.Data.DataConnection
        {
		public ITable<City>    Cities    { get { return this.GetTable<City>(); } }

		public MyDataConnection()
		{
			InitDataContext();
		}

		public MyDataConnection(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
        }

        [Table(Schema="public", Name="City")]
        public partial class City
        {
            [PrimaryKey, NotNull] public Guid   CityId    { get; set; } // uuid
            [Column,     NotNull] public string CityName  { get; set; } // text
            [Column,     NotNull] public Guid   CountryId { get; set; } // uuid

            #region Associations

		/// <summary>
		/// FK_User_City_CityId_BackReference
		/// </summary>
		[Association(ThisKey="CityId", OtherKey="CityId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<User> UserCityIds { get; set; }

		#endregion
        }

Configure the connection-string as appears in the README guide, let's call it connstr.

Then in a Console Application in the Main method 

        using (var db = new MyDataConnection("connstr"))
        {
            var procs = db.DataProvider.GetSchemaProvider().GetSchema(db).Procedures;
        }

The procs variable will be an empy list.

Environment details:
linq2db version: 2.1.0
Database Server: PostgreSQL 10.4
Database Provider: Npgsql 3.2.5
Operating system: Windows 10
Framework version: .Net Core 2.0

Thanks :)

**Comment by sdanyliv** [comment]
@Shimon91, this is known issue and we are working on this https://github.com/linq2db/linq2db/pull/1184.
I hope next release will support PostgreSQL’s stored procs.

**Comment by Shimon91** [comment]
Thank you @sdanyliv , I'm trying to fix it localy on my env temporarily, by inheriting from the  PostgreSQLSchemaProvider  class and overriding the GetProcedures method. Could you just write the sql query to use (something similar to the one from GetTables) so I could generate the procs in my project in order to avoid double-working later?

Thank you

**Comment by sdanyliv** [comment]
@Shimon91, why not just copy [this code](https://github.com/linq2db/linq2db/blob/postgresql_procedures/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSchemaProvider.cs#L349) ?

**Comment by sdanyliv** [comment]
BTW, better to get sources from PR, compile them. And replace linq2db.dll just for generation procedures.

**Comment by MaceWindu** [comment]
@Shimon91, I glad to see that there is demand for this feature. I really hope I will manage to finish it in a week and hope you will be able to give your feedback on prerelease version after PR merged.

As @sdanyliv  said, you can take code from my PR and try to use it. It has GetProcedures implemented and I just need to fix T4 templates code to support some pg-specific functions functionality. If you don't have such functions it could already work for you. If not - don't hesistate to provide more details on what doesn't work.

**Comment by Shimon91** [comment]
@sdanyliv & @MaceWindu - Thank you both, I didn't know that that branch existed lol :)

BUT, there are some problems with just changing the linq2db.dll in the .nuget\packages\linq2db.postgresql\2.1.0\tools folder.

Reproduce Steps:

Create a new netstandard library project.

Install the latest LinqToDB.PostgreSQL nuget package

Get a simple pg DB with a few simple tables and a simple Function.

Follow the docs to generate the POCOs for the tables (the Function POCO shouldn't be created as it's not supported as mentioned above). Let's assume that now you've got a "MyModels" folder with MyModels.tt file its corresponding auto-generated file.

Now clone the branch you gave me above, bulid the solution, and copy the linq2db.dll from the linq2db\linq2db-postgresql_procedures\Source\LinqToDB\bin\Debug\netstandard2.0 folder to the 
.nuget\packages\linq2db.postgresql\2.1.0\tools folder.

Now, there should be 3 files in the .nuget\packages\linq2db.postgresql\2.1.0\tools folder: 

1. Npgsql.dll from 6/21/2018 9:12 AM
2. System.Threading.Tasks.Extensions from 6/21/2018 9:12 AM
3. linq2db.dll from the datetime you've built the solution earlier.

Now go to the solution of your new netstandard library project you've created and save again the MyModels.tt.

I'm getting here 9 errors:

![image](https://user-images.githubusercontent.com/36296393/42502382-89fbef6a-843e-11e8-8113-2e2736698eac.png)

I've googled that "Must add ref netstandard" stuff but just got into more complex problems after trying to add the netstandard.dll ref like 

<#@ assembly Name="C:\Program Files\dotnet\sdk\2.1.200\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll" #>
as suggested in some posts:

![image](https://user-images.githubusercontent.com/36296393/42503888-8dd7eac2-8442-11e8-847d-90933ea845aa.png)


Your help will be highly appreciated :)

**Comment by sdanyliv** [comment]
@Shimon91, try to create 4.6 project. Not sure why you can not replace dll.

**Comment by Shimon91** [comment]
The strange thing is that my proj is netstandard 2.0 and it's telling me that I must add a ref to netstandard.
I guess that it's about referencing the assembly via the template itself as those types are reconized just fine in the *.cs files in the rest of the project and the problems are just with the T4 templates.

If someone encounters it and finds a solution until our dear guys here release the new version with the PostgreSQL Functions support - I'll be glad.

Thanks in advance.

**Comment by Shimon91** [comment]
Ok, got it working, but the C# method isn't generated so well.

For the following function in pg:

	DROP FUNCTION public."GetUsers"(text);
	
	CREATE OR REPLACE FUNCTION public."GetUsers"(
		"@FirstName" text)
		RETURNS TABLE("UserId" uuid, "LastName" text, "CityName" text, "CountryName" text) 
		LANGUAGE 'sql'
	
		COST 100
		VOLATILE 
		ROWS 1000
	AS $BODY$
	
	SELECT 	u."UserId", 
			u."LastName", 
			ci."CityName", 
			co."CountryName"
	FROM public."City" ci
	INNER JOIN public."User" u ON (u."CityId"=ci."CityId")
	INNER JOIN public."Country" co ON (ci."CountryId"=co."CountryId")
	WHERE u."FirstName"="@FirstName"
	
	$BODY$;
	
	ALTER FUNCTION public."GetUsers"(text)
		OWNER TO shimont;

The corresponding generated method in C# is:

            #region GetUsers

		[Sql.TableFunction(Schema="public", Name="GetUsers")]
		public ITable<GetUsersResult> GetUsers(string @FirstName, out Guid? UserId, out string LastName, out string CityName, out string CountryName)
		{
			return this.GetTable<GetUsersResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@FirstName,
				UserId,
				LastName,
				CityName,
				CountryName);
		}

		public partial class GetUsersResult
		{
			public Guid?  UserId      { get; set; }
			public string LastName    { get; set; }
			public string CityName    { get; set; }
			public string CountryName { get; set; }
		}

		#endregion

Of course the compiler shouts that "The out parameter '[ParamName]' must be assigned to before control leaves the current method".

After I remove the out parameters like this:

            [Sql.TableFunction(Schema="public", Name="GetUsers")]
		public ITable<GetUsersResult> GetUsers(string @FirstName)
		{
            return this.GetTable<GetUsersResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(), @FirstName);
		}

And call it with:

        public void Foo(string firstName)
        {
            using (var db = new BrainsspaceDB())
            {
                var users = db.GetUsers(firstName).ToList();
            }
        }

- it works fine.

Can you please fix that?
I guess it's something in the LinqToDb.ttinclude file.

Thanks! :)

@sdanyliv 
@MaceWindu

**Comment by sdanyliv** [comment]
@Shimon91, i hope @MaceWindu will fix that soon.

Simple advice: for speed and mantainance purposes - better to rewtire fuction using Linq2db. I can not remember when i have created stored procs, almost everything can be rewritten using linq queries.

**Comment by MaceWindu** [comment]
@Shimon91 you can try updated code from my PR - now it should work

**Comment by Shimon91** [comment]
Works like a charm! :)

Thanks a lot.

By the way, I'm just reminding that at least for me to make it work with your proj, I add the project to the solution as an existing project, add it as a reference to the necessary project, install the latest version from nuget of the LinqToDB.PostgreSQL package, and then go to the the .nuget/packages/linq2db.postgresql/2.1.0/contentFiles/any/any/LinqToDB.Templates folder and copy the templataes to there, o.w when I run the .tt file in my project it uses the old templates and not yours, and if I delete the LinqToDB.Templates folder installed by the NPM and copy it manually from your project to mine, I get some strange errors claiming it could not resolve the template files.

Anyway - thank you a lot :)

**Comment by MaceWindu** [comment]
feature merged into master and will be released in a week
