### ISSUE TITLE
.Skip().Take() vs .Take().Skip are not the same

### ISSUE THREAD

**Issue by MichielDG** [linq2db/linq2db#1227]
There is a bug in Linq2db  when you first use Take and than Skip. 
When I use 'Skip(50).Take(25)' it's correctly translated to 'BETWEEN 51 AND 75' but when I use 'Take(25).Skip(50)' it's not correctly translated to sql to 'BETWEEN 51 AND 25'
The problem is illustrated with an example below.
### **Correct situation:**
Linq2db query
```c#
var items = dataConnection.GetSqlContext().GetTable<DBContactPerson>().Skip(50).Take(25);
```
**Result:**
```sql
SELECT *
FROM
(
	SELECT
		t.*,
		ROW_NUMBER() OVER
		(
			ORDER BY
				t.[Name]
		) as rn
	FROM
	(
		SELECT
			[t1].[Name],
			[t1].[CustomerId],
			[t1].[ExternalId],
			[t1].[ExternalSourceId],
			[t1].[Id],
			[t1].[ChangedOn],
			[t1].[ChangedBy],
			[t1].[CreatedOn],
			[t1].[CreatedBy]
		FROM
			[dbo].[ContactPerson] [t1]
	) t
) t2
WHERE
	t2.rn BETWEEN 51 AND 75
```
### **Wrong situation:**
Linq2db query
```c#
var items = dataConnection.GetSqlContext().GetTable<DBContactPerson>().Take(25).Skip(50);
```
**Result:**
```sql
SELECT *
FROM
(
	SELECT
		t.*,
		ROW_NUMBER() OVER
		(
			ORDER BY
				t.[Name]
		) as rn
	FROM
	(
		SELECT
			[t1].[Name],
			[t1].[CustomerId],
			[t1].[ExternalId],
			[t1].[ExternalSourceId],
			[t1].[Id],
			[t1].[ChangedOn],
			[t1].[ChangedBy],
			[t1].[CreatedOn],
			[t1].[CreatedBy]
		FROM
			[dbo].[ContactPerson] [t1]
	) t
) t2
WHERE
	t2.rn BETWEEN 51 AND 25
```

### Environment details
linq2db version: 2.1.0
Database Server: SqlServer 2008
Operating system: Windows 10
Framework version: .NET Standard 2.0

**Comment by sdanyliv** [comment]
@MichielDG, it is normal behavior. You are getting 25 records, but skipping 50 from 25. `Skip` should be placed before `Take`. You can experiment with linq to objects - not records will be returned.

**Comment by MichielDG** [comment]
I understand it. A more clear example can be find on stackoverflow [https://stackoverflow.com/a/30349156](https://stackoverflow.com/a/30349156 )
