### ISSUE TITLE
Simplified partial insert / partial update syntax - feature request

### ISSUE THREAD

**Issue by dotnetchris** [linq2db/linq2db#124]
Take the examples

``` c#
using (var db = new DbNorthwind())
{
  var statement = db.Product
                    .Value(p => p.Name, product.Name)
                    .Value(p => p.UnitPrice, 10.2m);

  if (storeAdded) statement.Value(p => p.Added, () => Sql.CurrentTimestamp);

  statement.Insert();

  db.Product
    .Where(p => p.ProductID == product.ProductID)
    .Set(p => p.Name, product.Name)
    .Set(p => p.UnitPrice, product.UnitPrice)
    .Update();
}
```

That is alot of duplicated effort. I think a much better solution would be to support a slightly modified syntax such as

``` c#
using (var db = new DbNorthwind())
{
  var statement = db.Product
                    .Value(p => p.Name)
                    .Value(p => p.UnitPrice, 10.2m);

  if (storeAdded) statement.Value(p => p.Added, () => Sql.CurrentTimestamp);

  statement.Insert(product);
}

  db.Product
    .Where(p => p.ProductID == product.ProductID)
    .Set(p => p.Name)
    .Set(p => p.UnitPrice)
    .Update(product);
```

Bonus points if you support duck typing and that in these examples the object you pass into Insert/Update does not neccessarily need to be a Product and just needs to be able to satisfy the lambda expressions. Ie that you could use `Update(new { Name="Foo", UnitPrice = 5 })` or `Update(myPartialProductViewModel)`

**Comment by sdanyliv** [comment]
@dotnetchris, i don't think we have enought time to implement this, but! You always can write your own extension to do such things. And your pull request will be appreciated!
It is similar to: https://github.com/linq2db/linq2db/issues/433#issuecomment-246669331

Close for now, will reopen if needed.

**Comment by ili** [comment]
For me the request is not clear, it is possible to do (for insert too):
To update needed fields:
```cs
db.GetTable<TestParent>()
	.Where(t => t.ID < 0 && t.ID > 0)
	.Update(t => new TestParent
	{
		ID = t.ID - 1
	});

```
or to update all fields:
```cs
var p =  db.GetTable<TestParent>().First(_ => _.ID == 1);

db.Update(p);
```
