### ISSUE TITLE
[Request for help] Mapping DateTime columns to System.DateTime in utc

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#1241]
l2db 1.10.2.

We have a MS SQL db with a lot of datetime2 fields:
```sql
CREATE TABLE [User] (
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(200) NOT NULL,
	...
	[CreatedOn] DATETIME2(7) NOT NULL,
);
```
All datetime values are in UTC. We cannot migrate to the datetimeoffset right now.

The l2db T4 schema generator emits dto classes with DateTime columns:
```cs
	public partial class User
	{
		[PrimaryKey,               NotNull    ] public Guid          Id                         { get; set; } // uniqueidentifier
		[Column,                   NotNull    ] public string        Name                       { get; set; } // nvarchar(200)
		...
		[Column,                   NotNull    ] public DateTime      CreatedDate                { get; set; } // datetime2(7)
	}
```

linq2db .Select() fills the DateTime fields values with Kind = `Unspecified`.
The issue is, DateTime ignores it's kind on comparison ( as a proof: https://stackoverflow.com/questions/17661734/comparing-datetimes-with-unspecified-and-utc-kinds)

So the issue is: how force usage of utc for all DateTime columns for all tables in emitted Db class?

[There's advice](https://rsdn.org/forum/prj.rfd/5893618.all) (in Russian) to setup mapping for default schema or set mapping on each db instance. Both options will not work for us as we have a large codebase with multiple DBs and some DBs uses local timezone.

### Environment details

linq2db version: *1.10.2*
Database Server: *MS SQL 2017*
Database Provider: *Syetem.Data.Sql*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.7.2*

**Comment by MaceWindu** [comment]
It is not clear on what level you want it to be setup. If it is not on global or db level as you say in your last sentence, then how you identify what area should be affected by this conversion?

**Comment by ig-sinicyn** [comment]
As example. We have DataModels.tt:
```
DataContextName = "MyDb";  ...

// emits 
public partial class  MyDb : LinqToDB.Data.DataConnection { ... }
```

and OtherDataModels.tt:
```
DataContextName = "OtherDb";  ...

// emits 
public partial class OtherDb: LinqToDB.Data.DataConnection { ... }
```

I want to apply schema mappings for all instances of MyDb, but not to instances of OtherDb.

**Comment by sdanyliv** [comment]
`DataConnection` class has constructor parameter `MappingSchema`
Also you can add mapping schema to `DataConnection` later `AddMappingSchema(ms)`

So:

1. You can disable constructor generation `GenerateConstructors = false` in **tt** file.
Create constructor of your **partial** class 'MyDb ' in other file and pass particular Mapping Schema.

 2. You can generate constructor or other members itself. Our template design allows this.

**Comment by ig-sinicyn** [comment]
@sdanyliv thanks, your suggestion worked:)
