### ISSUE TITLE
Incorrect sql script if table/column name set with quotes in oracle

### ISSUE THREAD

**Issue by AlexeyDeev** [linq2db/linq2db#1243]
Hi.
Seems some problem with oracle sql generation - sql script is invalid if table/column name set with quotes.

Steps.

Some table in Oracle db. Table name and column name sets inside quotation-marks aka case sensitive names.

Script for creating table.

_Sql_

```
CREATE TABLE {some_schema}."TestTable" (
  "FirstField"  NVARCHAR2(50),
  "SecondField" NVARCHAR2(50)
)
```

In way to get easy quoting names creats some custom attrs:

```
 public sealed class TableNameAttribute : TableAttribute
    {
        public TableNameAttribute(string tableName)
        {
            Name = Config.IfQuote? '"' + tableName + '"' : tableName;
        }
    }
```
	
and 
	
```
	 public class ColumnNameAttribute : ColumnAttribute
    {
        public ColumnNameAttribute(string columnName)
        {
            Name = Config.IfQuote? '"' + columnName + '"' : columnName;
        }
    }
```
	

> **Config.IfQuote**   

Just global const (true, false).	

_And next c# model like this_

```
[TableName("JustTable")]
    public class SimpleTable
    {
        [ColumnName("FirstField")]
        public string FirstField { get; set; }
        [ColumnName("SecondField")]
        public string SecondField {get; set; }
    }
```

Simple database context:

```
 public class OracleContext : DataConnection
    {
        public OracleContext() : base("OracleConnection") { }
        public ITable<SimpleTable> Simples => GetTable<SimpleTable>();
    }
```
	

> **OracleConnection**

  Connection from app.config. Its direct connection via Oracle.ManagedDataAccess.

First try.

Set IfQuote to false. It's mean that table and column names without quotes.
 
Starts this code:
```
using (var dbContext = new OracleContext())
            {
                var querry = dbContext.Simples.SqlText;
                var data = dbContext.Simples.ToList();
            }
```
			
In querry variable sqlText:

> SELECT
> 	t1.FirstField,
> 	t1.SecondField
> FROM
> 	JustTable t1

	
This incorrect. When try get data gets **OracleException ORA-00942**.
	
Second try.

Set IfQuote to true. It's mean that table and column names with quotes 

Starts this code:
```
using (var dbContext = new OracleContext())
            {
                var querry = dbContext.Simples.SqlText;
                var data = dbContext.Simples.ToList();
            }
```
In querry variable sqlText:	

> SELECT
> 	t1.""FirstField"" as FirstField,
> 	t1.""SecondField"" as SecondField
> FROM
> 	""JustTable"" t1

This incorrect. Double quoting.

### Environment details
linq2db version: *2.1.0*
Database Server: *Oracle Database 11g*
Database Provider: *Oracle.ManagedDataAccess.Client*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.5*

**Comment by MaceWindu** [comment]
Linq2Db handles identifiers quotation, but we have a bug in check wether we need to quote it or not - we allow lowercase letters in non-quoted identifiers.

It is easy to fix, but will cause regression for users, that used lowercase letters in their mappings.
