### ISSUE TITLE
Update nuget publishing API  key

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1248]
Right now we cannot publish `linq2db.Sybase.DataAction` automatically and need to do it manually.

**Comment by MaceWindu** [comment]
Also make sure linq2db.t4models also included as we plan to publish 2.x version for it

**Comment by MaceWindu** [comment]
Ok, final list of packages that should be added to API key:
- linq2db.Sybase.DataAction
- linq2db.t4models
- linq2db.SQLite.MS

**Comment by ili** [comment]
For now I no not have access to our AppVeyor account. Guys from AppVeyor has changed something in security. So for now only @igor-tkachev can change API keys.

**Comment by ili** [comment]
done!
