### ISSUE TITLE
Add linq2db.core package to LinqToDB organization and obsolete it

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1254]
This package should be added to our nuget organization and description modified to tell users that this package is obsoleted and they should migrate to linq2db package

**Comment by MaceWindu** [comment]
Also I see several other linq2db packages, still not added to LinqToDB organization:
- https://www.nuget.org/packages/linq2db.Identity/
- https://www.nuget.org/packages/IdentityServer4.LinqToDB/
- https://www.nuget.org/packages/IdentityServer4.Contrib.Linq2db/

they also should be moved and maybe updated if needed

**Comment by ili** [comment]
Obsolete packages are unlisted. Ownership fixed :)
