### ISSUE TITLE
DataConnection Closed

### ISSUE THREAD

**Issue by liubutiantang** [linq2db/linq2db#1258]
The DataConnection does not use using. If the sql is executed, the underlying connection needs to be closed?

**Comment by sdanyliv** [comment]
Not sure that understand your question. Check this article 
https://linq2db.github.io/articles/general/Managing-data-connection.htm
You do not have to close anything, just dispose DataConnection.

**Comment by liubutiantang** [comment]
![image](https://user-images.githubusercontent.com/15134226/43442318-35f9e122-94d0-11e8-8685-3c6695727bc6.png) 
At this point, the connection should not be open.

**Comment by sdanyliv** [comment]
You do not have to use EF integration in that way. And there is standard rule for C# development - if something implements IDisposable - dispose it.
We are trying to reuse transaction and DBconnection of the current DBContext. So your code is superfluous and below sample should be enough.
```cs
erpDbContext.Persons.
   .Where(...)
   .Set(...j
   .Update();
```

**Comment by sdanyliv** [comment]
And yes we have difference with EF Core, we do not close DBConnection after each query and keeps connection opened upon DataConnection is disposed.
If you feel that this is a problem, we can tune our DataConnection class to work in the same way.

**Comment by sdanyliv** [comment]
Also we have function `CreateLinqToDbContext()` - it returns instance that closes DbConnection after each call.

**Comment by liubutiantang** [comment]
![image](https://user-images.githubusercontent.com/15134226/43444359-1ef55dd4-94d6-11e8-8c34-f5729df95a03.png)
If we use this, how to deal with dbContextConnection.OnTraceConnection, is it possible to use DataConnection.OnTrace global configuration?

**Comment by liubutiantang** [comment]
DbContext is often used with DI. If you keep open within a request, it should has a big impact on the program.

**Comment by sdanyliv** [comment]
Why do you need that either, we injects into EF Core logging and linq2db logs should be also visisble in EF Core logs.

**Comment by sdanyliv** [comment]
Use `CreateLinqToDbContext()` - it closes connection after each call.

**Comment by liubutiantang** [comment]
![image](https://user-images.githubusercontent.com/15134226/43445071-f6a00526-94d7-11e8-9a90-0f04265b2db9.png)
Is this a post-plan or an implementation?

**Comment by liubutiantang** [comment]
![image](https://user-images.githubusercontent.com/15134226/43445249-82fd4664-94d8-11e8-8f4f-32cf59ba450b.png)
We may add some necessary comments before sql sends to the database

**Comment by sdanyliv** [comment]
Show me the sample and i will check what to do with that. Also do you use EF Core analog that add comments?

**Comment by liubutiantang** [comment]
![image](https://user-images.githubusercontent.com/15134226/43445927-1f174bf2-94da-11e8-867b-f36c0516a0d1.png)
like this

**Comment by sdanyliv** [comment]
What is it? Why do you need such code?
Do you know that EF Core closes connection after each call, for sure if there is no transaction?
Many DI containers disposes EF Context automatically after releasing scope.

**Comment by liubutiantang** [comment]
![image](https://user-images.githubusercontent.com/15134226/43448586-f36c1436-94e0-11e8-9d79-9b2125bc70bb.png)
can like dapper,close connection after each call。

**Comment by sdanyliv** [comment]
Our integration with EF Core usually close connection after each call because it uses CretateLinqToDbContext function which is implemented from start. And yes we thinking about releasing connection because it is valuable resource. And you can test it - if it is not, we have bug.

Sometimes people complicates things too much. And why do you use screenshots instead of markdown?

**Comment by sdanyliv** [comment]
Closing as answered.
