### ISSUE TITLE
What kind of code reformat tool does the source code use?

### ISSUE THREAD

**Issue by lake2** [linq2db/linq2db#1271]
What kind of code reformat tool does the source code use?
I'm modifying the source code of linq2db, and I notice that the code format style is different from the original VS style. How can I keep the code format style when I reformat the source code?
Thanks.

**Comment by sdanyliv** [comment]
It's hard, we know. 
But we disable automatic Visual Studio formatting features and make formatting itself.

**Comment by MaceWindu** [comment]
We don't have such tool right now, so don't use reformat.

We have basic options in .editorconfig like tabs settings and plan to add more formatting options there later to help with it.

For vertical alignment formatting you can use https://marketplace.visualstudio.com/items?itemName=cpmcgrath.Codealignment addon (http://www.codealignment.com/)

**Comment by lake2** [comment]
Ok, I know how to do. 
Thanks.
