### ISSUE TITLE
ITable<T> extension methods should return new ITable instance instead of modified instance, passed to them

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1274]
We have some extension methods (need to identify all such methods), that we can apply to ITable<T> instance. User will expect that calling such method on table object will not modify initial object, but return new modified copy.

E.g. of unexpected behavior:
```c#
var table = db.GetTable<SomeTable>();

// here With will add hint to table instance instead of returning new instance
table.With(hint).Select().ToList();

// here we will generate query with table having hint from select query!
table.Set(r => r.Field, someValue).Update();
```

### Environment details
linq2db version: *2.2.0*

**Comment by jogibear9988** [comment]
How expensive is the "GetTable" Call? The question is, if we implement it like you said, we always create 2 Table<T> instances, even if the one without the "with" is not needed!

**Comment by sdanyliv** [comment]
@jogibear9988, it's almost nothing, just generation of Expression Tree.
