### ISSUE TITLE
Char mapping

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#1279]
```c#
	[TestFixture]
	public class CharValueTests : TestBase
	{
		class Table1
		{
			[PrimaryKey(1)]
			[Identity] public int Id { get; set; }

			public Char CharFld { get; set; }
		}

		[Test, DataContextSource(false)]
		public void Test(string context)
		{
			using (var db = new TestDataConnection())
			{
				db.DropTable<Table1>(throwExceptionIfNotExists: false);
				db.CreateTable<Table1>();

				var val = 'P';

				db.Insert(new Table1 { CharFld = val });

				var result = db.GetTable<Table1>().First().CharFld;

				Assert.AreEqual(val, result);

				db.DropTable<Table1>(throwExceptionIfNotExists: false);
			}
		}
	}
```

When run for SQLite.MS result is 56 ('8') not 80 ('P').  I've tested other values and it looks like the return value is the first digit of the value of the char rather than the char itself e.g. for 'z' 122 the result is '1', for char.MinValue 0 '\0' the result is 48 '0'

SQLite.Classic works fine so it would suggest that this is something that the underlying DataConnection is returning differently.

I'm getting the same problem with the DB2 iSeries provider (which is what prompted me to do further investigation) so this not confined to SQLite.MS.

### Environment details
linq2db version: 2.2.0
Database Server: N/A
Database Provider: SQLite.MS, DB2 iSeries and possibly others
Operating system: Windows 10
Framework version: .NET Framework 4.6.2

**Comment by MaceWindu** [comment]
@RoyC-Retail-Assist It was sqlite.ms provider issue which is fixed. For iSeries you need to check if it has similar behavior and decide how it fix it.

**Comment by RoyC-Retail-Assist** [comment]
@MaceWindu thank you.  I'll apply the same fix to the iSeries provider and work from there.
