### ISSUE TITLE
linq2db as DTO layer

### ISSUE THREAD

**Issue by CroveanOS** [linq2db/linq2db#1283]
Hello.
We've been using Linq2db in a project for a while and we got to a stage where we understood that working directly with generated classes is not enough. Is it worth creating a BO and DTO separately, using linq2db?

If i would like to introduce a field UserCreated in my Users table, which would automatically use Insert date,
how could i achieve that using Linq2db without an extra layer, where i would manually write my Insert function?

If then i introduce an extra layer, then in order to use linq for my queries (lets say i have 
```csharp 
var admins = db.Users.Where(usr => usr.IsAdmin).ToList();
```
I would have to reproduce the exact same query on my BO class, something like this
```csharp
var admins = Users.All().Where(usr => usr.IsAdmin);
```
which makes me load the whole list, thus generate two separated queries, which is not nice.

What is the best approach to this structure?

Thank you!

**Comment by sdanyliv** [comment]
How about this simple mapping?
```cs
IQueryable<DTOUser> GetUsers(IDataContext db)
{
    return db.GetTable<User>()
      .Select(u => new DTOUser{
         UserId = u.USerId,
         ...
         UserCreated = u.InsertDate
      });
}
```
Then you can update such objects:
```cs
GetUsers(db).Where(u => u.UserId == 1)
   .Set(u => u.Name, u.Name)
    ....
   .Update();
```
If you want to update this object dynamically you have to use this sample https://github.com/linq2db/linq2db/issues/1234#issuecomment-406864607

**Comment by CroveanOS** [comment]
It works nice, but it is not generic. I assume there's no way to have it generic, i'd have to implement the Get method for each DTO, right?

What i tried is 
```csharp
return db.GetTable<User>().Where(predicate).Select(x => Mapper.Map<DTOUser>(x)).ToList()
```

which would still generate the query with all the properties of User class, because the mapping goes after the select is done.

**Comment by sdanyliv** [comment]
We need Expression Tree but not just object to object remapping,
You have to write mapper only in the following way:
```cs
IQueryable<DTOUser> Map(this IQueryable<User> query)
{
   return query.Select(u => new DTOUser{
         UserId = u.USerId,
         ...
         UserCreated = u.InsertDate
      }
}
```
Or you can return Expresssion Tree for remapping:
```cs
Expression<Func<User, DTOUser>> Map()
{
    return u => new DTOUser{
         UserId = u.USerId,
         ...
         UserCreated = u.InsertDate
      }
}
```
And use in query
```cs
db.Users.Select(Map()).ToArray()
```

**Comment by CroveanOS** [comment]
Okay, i think it is pretty clear what has to be done now. Thank you!

**Comment by sdanyliv** [comment]
Ineresting that i’m thinking about universal implementation for such needs. And i have proposed interfaces for implementing this
https://github.com/linq2db/linq2db/issues/230#issuecomment-412290451
Thinking about implementation of some independed  `DTOEntityServices` with registration of IEntityMapping.
Almost everything can be done without changing linq2db code.
