### ISSUE TITLE
ProcessQuery method in LinqToDB.Data.DataConnection class is not called for cached query

### ISSUE THREAD

**Issue by alifshits** [linq2db/linq2db#129]
My purpose is to have method or event which occurs every time when any query is going to run against the database. 
I overrided ProcessQuery method in LinqToDB.Data.DataConnection class.
But I mentioned that sometimes ProcessQuery is not called. After small research I found that cached queries are not going through GetCommand -> ProcessQuery chain.

``` c#
...
// ProcessQuery called
var res1= _repository.Query().Where(x => x.SomeField == someValue).Select(x => x.ID).ToArray();
...
// some code
...
// same query as before, it presents in cache, so ProcessQuery is not called
var res2 = _repository.Query().Where(x => x.SomeField == someValue).Select(x => x.ID).ToArray();
```

I understand benefits of caching queries, but still need to handle every query which is going to run.
Probably linq2db needs other method or event for this purpose. And ProcessQuery method should only be used by user for some custom query preprocessing.

Is there any solution for this case?

Thank you.

**Comment by Vitegor** [comment]
@igor-tkachev,  I have the same problem, there is workaround ?

**Comment by MaceWindu** [comment]
What are you trying to do?

**Comment by MaceWindu** [comment]
Also it should be better to open new issue, as commenting in closed issues usually goes unnoticed
