### ISSUE TITLE
Invalid Method name 'bool' with Postgres t4model generation

### ISSUE THREAD

**Issue by Kempe** [linq2db/linq2db#1295]
Hi,
just 2 small problems when generating schema with the t4 postgres model:
I'm using linq2db v2.2 and linq2db.PostgreSQL v2.2

### 1.
The gererated SQLFunctions class uses the BitArray class, but the using statement 'System.Collections' is missing!

### 2.
the t4 model generator for Postgres generates the following code in the SQLFunctions class when setting 
`NormalizeNames = true;`
```cs
[Sql.Function(Name=".bool", ServerSideOnly=true)]
public static bool? **Bool**(int? par451) // this is fine
{
	throw new InvalidOperationException();
}
```
but if
`NormalizeNames = false;`
it generates a method name 'bool' -> reserved keyword !
```cs
[Sql.Function(Name=".bool", ServerSideOnly=true)]
public static bool? **bool**(int? par451) // this is wrong
{
	throw new InvalidOperationException();
}
```
Can you please have a look? 

Thank you!

Cheers Micha

**Comment by Kempe** [comment]
Sorry, but the same happens with 'char' : 
[Sql.Function(Name=".char", ServerSideOnly=true)]
public static object char(string par960)
{
	throw new InvalidOperationException();
}

**Comment by sdanyliv** [comment]
Yeah there are problems here. But we have workarounds before it is fixed.
1. Add the following code to your TT file:
```cs
Model.Usings.Add("System.Collections"); 
```
2. Before generating model, correct procedure name:
```cs
Procedures[".char"].Name = "Char";
```

**Comment by Kempe** [comment]
Hi sdanyliv, thanks you for help! Your suggest to add 'System.Collections' works fine. But I got an key-not-found exception when renaming the procedure. Is it correct to set 'Procedures[".char"].Name = "Char";' before calling GenerateModel(); ???

Here is my tt file: 

NormalizeNames			 = false; 	
LoadPostgreSQLMetadata("connection_string");

Model.Usings.Add("System.Collections"); 
Procedures["char"].Name = "Char";

GenerateModel();

**Comment by sdanyliv** [comment]
@Kempe, sorry i have no idea which name is correct and how it is stored in Procedures Dictionary, try to analyse yourself.
