### ISSUE TITLE
Support Multiple Sql.Like in Where clause

### ISSUE THREAD

**Issue by BergenSoft** [linq2db/linq2db#1302]
The following code failed, because the expression cannot be converted to sql.

```c#
var likeList = new List<string>()
{
	"abc%xyz",
	"def%",
	"%uvw"
};

var result = new DataContext().GetTable<Table1>().Where(t => likeList.Any(l =>Sql.Like(t.Column1, l))).ToList();
```

```
Exception message:
Sequence 'value(My.ClassNamespace+<>c__DisplayClass31).likeLlist' cannot be converted to SQL.
```

The expected SQL should be something like this:
```SQL
SELECT * FROM Table1 t WHERE t.Column1 LIKE 'abc%def' OR t.Column1 LIKE 'def%' OR t.Column1 LIKE '%uvw';
```

Is there a change to get it work in future?

**Comment by sdanyliv** [comment]
@BergenSoft, it is not a linq2db bug but you just need to write appropriate extension. 
I have created sample last week - https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/8#issuecomment-417217962
Use it accordingly:
```cs
var likeList = new List<string>()
{
	"abc%xyz",
	"def%",
	"%uvw"
};

var result = new DataContext().GetTable<Table1>()
	.WhereOr(likeList, (t, l) => likeList.Any(l => Sql.Like(t.Column1, l)))
	.ToList();
```

**Comment by sdanyliv** [comment]
Yes, I've corrected just after posting, my fault.
So closing for now as answered.
