### ISSUE TITLE
Wrong conversion of byte[] identifiers for MySQL

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#1303]
For MS SQL Server provider I will get correct values in WHERE clause.  
But in MySQL it looks like just ToString() called by mistake.  

```sql
--  MySql
SELECT
	`t1`.`Id`,
	`t1`.`Name`,
	`t1`.`Surname`
FROM
	`Account` `t1`
WHERE
	`t1`.`Id` IN (System.Byte[], System.Byte[], System.Byte[], System.Byte[])

```

It should be like this:

```sql
SELECT *
FROM Account
WHERE Id  IN (0x0164576A362F652476256346B2626501, 0x64743E66556712i71894244624623402, 0xD1923467267FDA742326E63234263423)
```

### Environment details
MySql 8.0
Linq2db: from master (2.4.0)

**Comment by sdanyliv** [comment]
@hardhub, can you prepare PR with fix? Seems that this not so difficult task.

**Comment by hardhub** [comment]
I guess such lines should be added in MySqlMappingSchema:

SetValueToSqlConverter(typeof(byte[]),         (sb,dt,v) => ConvertBinaryToSql        (sb, (byte[])v));
SetValueToSqlConverter(typeof(Binary),         (sb,dt,v) => ConvertBinaryToSql        (sb, ((Binary)v).ToArray()));

I will check and update it if all is correct.

**Comment by sdanyliv** [comment]
@hardhub, thanks for fix. Also could you provide simple test that reproduces problem?
`CreateaLocalTable`, insert record, retrieve record, compare binary values. There are many similar tests in code.

**Comment by hardhub** [comment]
> @hardhub, thanks for fix. Also could you provide simple test that reproduces problem?
CreateaLocalTable, insert record, retrieve record, compare binary values. There are many similar tests in code.

I think I cannot do that because I do not know what are requirements for tests in Linq2Db repository.  
I need to invest some time in understanding of source code and existing tests.  
Unfortunately that is not something doable in nearest future.  
If anybody can create test for this specific issue it will help me a lot in the future.

**Comment by sdanyliv** [comment]
@hardhub, tests are needed and usually they have more code than fix :)
It's easy. Follow these steps:

## Initial - only once
1. Make copy of file `\linq2db\Tests\DataProviders.json`  -> `\linq2db\Tests\UserDataProviders.json` - this file mentioned in git ignore so it will not boring you when switching between branches.
2. Change `NET45`  section in copied file. Just add 'MySql' or 'MySql57', others remove.
3. Search for `LocalConnectionStrings` section and correct 'MySql' or 'MySql57' connection string to use your server.

## For every new test
1. Open Playground solution: linq2db.playground.sln
2. Make copy of class TestTemplate - it will be your unit test. It starts with creating temporary table that will be used in your test, modify it accordingly.
3. Write test (you can found a lot of samples in our PRs) and run it using ReSharper or by Visual Studio.

**Comment by MaceWindu** [comment]
closed by https://github.com/linq2db/linq2db/pull/1304
