### ISSUE TITLE
Add Order field for ColumnAttribute to allow greater control for code-first

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#1305]
I propose that we modify `LinqToDB.Mapping.ColumnAttribute` to add an `Order` property to allow specification of column order for code-first scenarios.

I've been working on building a versioned record system for one of my projects.  I have a dozen tables that all start with the same fields:

    RecordID INT PRIMARY KEY,
    EffectiveStart DATETIME NOT NULL,
    EffectiveEnd DATETIME NULL,
    Key UNIQUEIDENTIFIER NOT NULL

In C# I have something like this:

    public abstract class VersionedRecord
    {
        // SQLite ROWID proxy
        [Column(IsPrimaryKey = true, SkipOnInsert = true)]
        public int RecordID { get; set; }

        [Column]
        public DateTime EffectiveStart { get; set; }

        [Column]
        public DateTime? EffectiveEnd { get; set; }

        [Column]
        public Guid Key { get; set; }
    }

    [Table("Accounts")]
    public class Account : VersionedRecord
    {
        [Column, NotNull]
        public string Code { get; set; }

        [Column, NotNull]
        public string Name { get; set; }
    }

When I create the table using `context.CreateTable<Account>();` the fields from the most-derived class are declared first.  In the case above the SQL statement looks like this:

	--  SQLite.Classic SQLite
	CREATE TABLE [Accounts]
	(
		[Name]           NVarChar(255)     NULL,
		[Code]           NVarChar(255)     NULL,
		[RecordID]       INTEGER       NOT NULL,
		[EffectiveStart] DateTime2     NOT NULL,
		[EffectiveEnd]   DateTime2         NULL,
		[Key]            Guid          NOT NULL,
	
		CONSTRAINT [PK_Accounts] PRIMARY KEY ([RecordID])
	)

(If I were creating the table myself I'd put the `Name` and `Code` fields after the `Key` field.)

What I would like is a way to specify the ordering of the columns independent of their position in the type(s) where they are defined.

In [`System.ComponentModel.DataAnnotations.Schema.ColumnAttribute`][1] there is an `Order` property which lets you define the order of columns.

Adding the `Order` property to `LinqToDB.Mapping.ColumnAttribute` would allow the manual specification of column ordering.  Columns with unset order values would come after the columns whose order is set.  Columns with conflicting order would be sorted as per current ordering.

### Environment details
linq2db version: *2.3.0*
Database Server: *N/A*
Database Provider: *All*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.6*

[1]: https://docs.microsoft.com/en-au/dotnet/api/system.componentmodel.dataannotations.schema.columnattribute?view=netframework-4.7.2

**Comment by MaceWindu** [comment]
Closed by #1308
