### ISSUE TITLE
{String data right truncation} in informix

### ISSUE THREAD

**Issue by s1495k043** [linq2db/linq2db#1306]
When call InsertOrReplace throw exception {String data right truncation},but data length is smaller than schema define.
still have window xp so still use net40.

Exception message:
```
{"ERROR [22001] [Informix .NET provider]String data right truncation."} 
IBM.Data.Informix.IfxException
Stack trace:
   於 IBM.Data.Informix.IfxConnection.HandleError(IntPtr hHandle, SQL_HANDLE hType, RETCODE retcode)
   於 IBM.Data.Informix.IfxCommand.ExecuteReaderObject(CommandBehavior behavior, String method)
   於 IBM.Data.Informix.IfxCommand.ExecuteNonQuery()
   於 LinqToDB.Data.DataConnection.ExecuteNonQuery()
   於 LinqToDB.Linq.QueryRunner.NonQueryQuery2(Query query, IDataContext dataContext, Expression expr, Object[] parameters)
   於 LinqToDB.Linq.QueryRunner.<>c__DisplayClass40.<SetNonQueryQuery2>b__3f(IDataContext db, Expression expr, Object[] ps)
   於 LinqToDB.Linq.QueryRunner.InsertOrReplace`1.Query(IDataContext dataContext, T obj)
   於 StockItems.InvItem.Save(String opNo) 於 D:\StockItems\Model\InvItem.cs: 行 153
```

### Steps to reproduce

schema
```sql
CREATE TABLE test (
    pmkey serial ,
    content varchar(255)
); 
```

```c#
using(var db = new DB())
{
    var test = new Test(){
         Content = "中文字中文字中文字" //at most 27 byte
    };
     db.InsertOrReplace(test); //throw exception
}
```

### Environment details
linq2db version: 1.10.0.0
Database Server:  Informix 11.7
Database Provider: IBM.Data.Informix 3.0.0.2 FC8 (x64)
Operating system:  Windows 10*
Framework version: .NET Framework 4.0*

**Comment by sdanyliv** [comment]
@s1495k043, looks like it is your problem: https://www-01.ibm.com/support/docview.wss?uid=swg1IT08509

**Comment by MaceWindu** [comment]
Looks like @sdanyliv is right, FC8 was released in 2013 and IBM fixed in 2015. Please reopen if it is still an issue with newer provider

**Comment by s1495k043** [comment]
I upgrade my csdk to 4.10 xC6 64bit.
It still not work.
![default](https://user-images.githubusercontent.com/7563962/45065193-664da300-b0ea-11e8-9a92-dc08a752c06b.png)
