### ISSUE TITLE
{"ERROR [22001] [Informix .NET provider]String data right truncation."} when InsertOrReplace

### ISSUE THREAD

**Issue by s1495k043** [linq2db/linq2db#1307]
When call InsertOrReplace throw exception {String data right truncation},but data length is smaller than schema define.
It's work fine when the content is English string,and fail if the content contains Chinese char.
db locale is en_us.utf8, have try IBM.Data.Informix 3.4 and 4.1. 

Exception message:
```
{"ERROR [22001] [Informix .NET provider]String data right truncation."} 
IBM.Data.Informix.IfxException
Stack trace:
   於 IBM.Data.Informix.IfxConnection.HandleError(IntPtr hHandle, SQL_HANDLE hType, RETCODE retcode)
   於 IBM.Data.Informix.IfxCommand.ExecuteReaderObject(CommandBehavior behavior, String method)
   於 IBM.Data.Informix.IfxCommand.ExecuteNonQuery()
   於 LinqToDB.Data.DataConnection.ExecuteNonQuery()
   於 LinqToDB.Linq.QueryRunner.NonQueryQuery2(Query query, IDataContext dataContext, Expression expr, Object[] parameters)
   於 LinqToDB.Linq.QueryRunner.<>c__DisplayClass40.<SetNonQueryQuery2>b__3f(IDataContext db, Expression expr, Object[] ps)
   於 LinqToDB.Linq.QueryRunner.InsertOrReplace`1.Query(IDataContext dataContext, T obj)
   於 StockItems.InvItem.Save(String opNo) 於 D:\StockItems\Model\InvItem.cs: 行 153
```

### Steps to reproduce

schema
```sql
CREATE TABLE test (
    pmkey serial ,
    content varchar(255)
); 
```

```c#
using(var db = new DB())
{
    var test = new Test(){
         Content = "中文字中文字中文字" //at most 27 byte
    };
     db.InsertOrReplace(test); //throw exception
     db.Update(test); //not work either
     db.Insert(test); //not work either
}
```

### Environment details
linq2db version: 1.10.0.0
Database Server:  Informix 11.7
Database Provider: IBM.Data.Informix 3.0.0.2 FC8 (x64) => fail , IBM.Data.Informix 4.0.410.6 xC6 (x64) => fail either
Operating system:  Windows 10*
Framework version: .NET Framework 4.0*

**Comment by sdanyliv** [comment]
@s1495k043, there is no special magic from our side when putting data to Informix DataConnection.
Create simple test which inserts data without linq2db just using `InformixDataConnection`.
Also IBM very confusing in their issues system and versioning. Please insure that you have CSDK 4.10.xC6

**Comment by s1495k043** [comment]
I dont know why,but the code below is work.
```c#
db.Test.Value(x => x.Content, "中文中文中文").Insert();
```

**Comment by sdanyliv** [comment]
@s1495k043, i propose to test your code using linq2db sources before we start investigation. IBM libraries still far away from perfection and problem can be not reproducible in our environment.
Just add linq2db.csprog to your solution and debug what happened. 

UPD. Difference in two samples that in first case we may use Parameter.
Try before insert
```cs
db.InlineParameters = true
```

**Comment by s1495k043** [comment]
@sdanyliv
It's work when set InlineParameters  true.
But another problem is that when I set InlineParameters  true ,the `SetParameter` method in DataProvider doesnt invoke.

#Exception
```
{"ERROR [22008] [Informix .NET provider][Informix]Extra characters at the end of a datetime or interval."}
```
#Because
```
...
UPDATE informix.sto_items
Set
 ...
 informix.sto_items.op_time = '2018-09-05 12:25:09.688', 
--this should be '2018-09-05 12:25:09' and i dont need millsecond
...
```

#My solution
```c#
        public override void SetParameter(IDbDataParameter parameter, string name, DataType dataType, object value)
        {
            if (value is DateTime)
            {
                value = ((DateTime)value).AddTicks(-(((DateTime)value).Ticks % TimeSpan.TicksPerSecond));
            }
            base.SetParameter(parameter, name, dataType, value);
        }
```

**Comment by sdanyliv** [comment]
1. Test on pure ADO.NET variant with parameter to ensure that this is Informix bug.
2. Is there are any documentation about milliseconds in this case? For sure SetParameter is not called here because we inlined parameters.
Check this function and how it is registered
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Informix/InformixMappingSchema.cs#L60

**Comment by s1495k043** [comment]
1.Yes ,Im sure that is a informix bug.
2.the OpTime value is from `DateTime.Now()` , and the column schem in db is ``year to second``

**Comment by s1495k043** [comment]
Driver will throw exception regardless of any version in x64 in case 1, and working fine in x86.
I think I should change driver to DB2 and upgrade xp still in use .

**Comment by MaceWindu** [comment]
>is there any way to detect which datetime column is used?

we take column data type information from mappings, so ColumnAttribute should provide information which kind of date type is used. Because we don't have such type in DataType enumeration, it should be specified using DbType property.

E.g.
```cs
[ColumnAttribute("op_time", DataType.DateTime, DbType="datetime year to second")]
public DateTime OpTime {get;set;}
```
and then you need to set converter for this pair of DataType/DbType, as right now we don't set it (must be fixed).

**Comment by MaceWindu** [comment]
@s1495k043 I've done some tests (see https://github.com/linq2db/linq2db/commit/f374ff278a46607533428a8738e0ea38e48c82e7) and have following observations:
- datetime values inlining works properly in linq2db 2.x for any quantifier, so you just need to migrate to 2.x version or add 2.x version's mapping to your mapping schema as @sdanyliv  suggested
- inserting of sample string from your issue works for me for both literal and parameter forms with following locale settings: DB_LOCALE=en_us.utf8;CLIENT_LOCALE=en_us.utf8 on both database and client sides. I would say that probably you have some locale misconfiguration in database or/and connection string
