### ISSUE TITLE
Repetitive problems in t4-based model generation

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#1312]
I have noticed this observation many times before. Currently, this behavior has occurred after I updated from version 2.2.0 to 2.3.0 via NuGet (linq2db, linq2db.SqlServer, linq2db.t4models).

After the successful update, the models could no longer be generated via T4. Hundreds of errors (see attachment). Sometimes I can bring the T4 functionality back to life by downgrading and upgrading a couple of times. 

At the moment I am without T4 functionality.

Are there any reasonable hints or "best practices" in such scenarios?

![linq2db_t4models_errorlist](https://user-images.githubusercontent.com/1959022/45170061-4b208780-b1ff-11e8-93ed-76cdaf94fd77.png)

### Environment details
linq2db version: *2.3.0*
Database Server: Microsoft SQL Server 2012
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
@jdistlr, for now i have no idea.
Try to remove package `linq2db.SqlServer` and install again.

**Comment by jdistlr** [comment]
Thank you for your answer. Unfortunately it did not help.

Downgrading to linq2db.t4models 1.10.0 worked. For the moment. :)

**Comment by sdanyliv** [comment]
It's strange two days ago i have created new project from scratch without any problems.
Please create new project and try to generate T4 templates. If it fails, post this project here.

**Comment by jdistlr** [comment]
This happens mainly in projects that have already existed and linq2db sideways added to it. Can the conflict be related to managing the project via SVN?

**Comment by jdistlr** [comment]
This issue is still alive. With version 2.4.0 the same defect happens all over. Only switching back to 1.10.0 give me a functional code-generation. This happens on a new generated project.

Steps to reproduce:
1. Filling up correct credentials to database
2. Rename the CopyMe.SqlServer.tt.txt to CopyMe.SqlServer.tt
3. Run custom tool
... while leaving all the t4-generation files in folder LinqToDB.Templates.

After rollback to 1.10.0 and unload/reload the Solution, everything is fine. :-(

**Comment by sdanyliv** [comment]
@jdistlr, i assume that this can be problem with VS tooling. Which version of Visual Studio do you use?

**Comment by jdistlr** [comment]
I'm on VS2015 Professional Update 3. It's a naked WinForms project with nothing installed except linq2db.

**Comment by sdanyliv** [comment]
Looks like it is root of problem. We have stopped developing with VS 2015 more than year ago. And possible used some environment variables that are not supported.

As a workaround I suggest to create project with linq2db 1.10.1 just for generating model.
In your current projects uninstall linq2db.SqlServer, and just install latest linq2db package.
Add refrence to project with generated model, or just add generated model as link in appropriate project.

**Comment by MaceWindu** [comment]
Did you tried to remove lines 3-4 and uncomment lines 5-6 in your tt file:
```
<#@ template language="C#" debug="True" hostSpecific="True"                           #>
<#@ output extension=".generated.cs"                                                  #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude"     #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"     #>
```

they are here to support old tooling, so maybe it will help.

**Comment by sdanyliv** [comment]
Looks like it is already answered. Closing.
