### ISSUE TITLE
Dapper benchmark comparison

### ISSUE THREAD

**Issue by ifle** [linq2db/linq2db#1314]
Hi,

Dapper has benchmark comparison between ORM. I've created PR for Linq2DB too.
You can review it and contribute improvements 
https://github.com/StackExchange/Dapper/pull/1125

**Comment by sdanyliv** [comment]
@ifle, thanks for that ;)
I saw it before. Tests looks so synthetic - just retrieve one record.
We have our performance tests: https://github.com/linq2db/PerformanceTest/tree/master/Result

**Comment by CoskunSunali** [comment]
Dear @sdanyliv, out of curiosity, how in the world can linq2db be faster than handwritten code given that they generate the same SQL query let's say?

What is more, I came across to a post there the author states the following, what is your two cents on it?

https://weblogs.asp.net/fbouma/net-micro-orm-fetch-benchmark-results-and-the-fine-details

> The reason Linq to DB is faster than the rest is that it skips testing for NULL for fields which can’t be NULL. It does this by examining the schema returned by the DbDataReader. This is risky however. It doesn’t always match with reality.

**Comment by sdanyliv** [comment]
Yes testing for NULL could be key of that. 
We are trying to do not check for nulls if DataReader's schema returns that for specific field NULL are not possible. But this approach works only in 90+% cases. So we also generate additional mapping which check for nulls everything. This mapping automatically used when we experienced problem with optimal mapping.

**Comment by CoskunSunali** [comment]
OK so you basically handle what the author says you don't, this way or that way, the other 10% of cases should not and will not be a problem for us. Is that right?

**Comment by sdanyliv** [comment]
Yes, we keep in mind that sometimes Database Providers return incorrect information, so we have special code that handles this case. It's simple, if we have exception in optimized mapper - we automatically replace mapper with 'slow' version.

**Comment by CoskunSunali** [comment]
Can you imagine being able to catch that flow without wrapping your code inside a try-catch block (hence a small performance lose) to make it even faster? 

Thanks for your replies and the details you have given. Great job!
