### ISSUE TITLE
Using Sql.TableExpression on a class that is not a DataConnection

### ISSUE THREAD

**Issue by CoskunSunali** [linq2db/linq2db#1317]
I am trying to use the `Sql.TableExpressionAttribute` on a class that inherits neither from `DataConnection` nor `ITable<>`.

The reason I am trying to do so is because I want the connection class to be only a connection class and custom logic to be implemented in another class.

I tried two approaches but both of them failed. I will write explain both separately.

Approach 1: Custom data connection class, not inheriting from `DataConnection`, has a method that has the custom table expression attribute. The `DataConnection` instance is a private field. 

Approach 2: Custom table class, not implementing `ITable<>`, has a method that has the custom table expression attribute. The custom table class has the backing `ITable<>` as a private field. The custom table class itself implements `IQueryable<>`.

The following is a piece of (rather ugly, please do not pay attention to the coding style or to the code quality) sample that combines both of the approaches.

Executing the following lines of code should demonstrate you both of the exceptions:

```cs
var sample = new Sample();

sample.TestGetCustomTableFromCustomConnection();
sample.TestGetCustomTableUsingCustomTableClass();
```

The sample:

```cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using LinqToDB.Data;
using LinqToDB.Mapping;
using LinqToDB.SqlQuery;

namespace LinqToDB.Sample
{
    public class Sample
    {
        private readonly CustomConnection _customConnection;

        public Sample()
        {
            _customConnection = new CustomConnection();

            _customConnection.CreateTable<Entity>();
        }

        public void TestGetCustomTableFromCustomConnection()
        {
            var tableAsQueryable = _customConnection.GetCustomTable<Entity>();

            var result = tableAsQueryable.ToList();
        }

        public void TestGetCustomTableUsingCustomTableClass()
        {
            var tableAsQueryable = new CustomTable<Entity>(_customConnection);

            var result = tableAsQueryable.ToList();
        }

        public class CustomConnection
        {
            private readonly DataConnection _dataConnection;

            public CustomConnection()
            {
                _dataConnection = new DataConnection(
                    "SqlServer",
                    "Server=(local);Database=TestDatabase;User Id=TestUser;Password=P@ssw0rd;MultipleActiveResultSets=True;Enlist=False;");
            }

            public void CreateTable<T>()
                where T : class
            {
                try
                {
                    _dataConnection.CreateTable<T>();
                }
                catch (Exception)
                {
                }
            }

            public IQueryable<T> GetCustomTable<T>()
                where T : class
            {
                return GetCustomTableAsQueryable1<T>();
            }

            /// <summary>
            /// This method is internal because it is only used by the CustomTable<T> class. Just for testing purposes.
            /// </summary>
            internal ITable<T> GetTable<T>(object instance, MethodInfo methodInfo, params object[] parameters)
                where T : class
            {
                return _dataConnection.GetTable<T>(instance, methodInfo, parameters);
            }

            [CustomTableExpression]
            private ITable<T> GetCustomTableAsQueryable1<T>()
                where T : class
            {
                var methodInfo = typeof(CustomConnection)
                    .GetMethod(nameof(GetCustomTableAsQueryable1))
                    .MakeGenericMethod(typeof(T));

                return _dataConnection.GetTable<T>(this, methodInfo);
            }
        }

        public class CustomTable<T> : IQueryable<T>
            where T : class
        {
            private readonly CustomConnection _connection;
            private readonly IQueryable<T> _queryable;

            public CustomTable(CustomConnection connection)
            {
                _connection = connection;
                _queryable = GetCustomTableAsQueryable2();
            }

            [CustomTableExpression]
            private ITable<T> GetCustomTableAsQueryable2()
            {
                var methodInfo = typeof(CustomTable<T>)
                    .GetMethod(nameof(GetCustomTableAsQueryable2), BindingFlags.Instance | BindingFlags.NonPublic);

                return _connection.GetTable<T>(this, methodInfo);
            }

            public Type ElementType => _queryable.ElementType;

            public Expression Expression => _queryable.Expression;

            public IQueryProvider Provider => _queryable.Provider;

            public IEnumerator<T> GetEnumerator() => _queryable.GetEnumerator();

            IEnumerator IEnumerable.GetEnumerator() => _queryable.GetEnumerator();
        }

        public class CustomTableExpressionAttribute : Sql.TableExpressionAttribute
        {
            public CustomTableExpressionAttribute()
                : base("")
            {
            }

            public override void SetTable(MappingSchema mappingSchema, SqlTable table, MemberInfo member, IEnumerable<Expression> arguments, IEnumerable<ISqlExpression> sqlArgs)
            {
                base.SetTable(mappingSchema, table, member, arguments, sqlArgs);
            }
        }

        public class Entity
        {
            [PrimaryKey]
            public int Id { get; set; }

            [Column(DataType = DataType.NVarChar)]
            public string Data { get; set; }
        }
    }
}
```

I would appreciate any of your assistance.

**Comment by sdanyliv** [comment]
@CoskunSunali, sorry for long delay. Vacations and a lot of main work.
I see many problems here. Looks like linq parser will not handle such queries. Better to start explaining why do you need such approach and maybe i‘ll find more elegant solution.

**Comment by CoskunSunali** [comment]
@sdanyliv No worries at all, life continues outside GitHub too! :)

Which part would you like me to explain you the "reasons" as to why the object oriented design is as the given example? I will try to explain shortly but please don't hesitate to ask if you have specific questions.

The `CustomConnection` doesn't inherit from `DataConnection`  because I am trying to abstract away the underlying ORM. The same goes for the `CustomTable<T>`. `CustomTable<T>` is basically just an `IQueryable<T>` and the underlying queryable is `ITable<T>`.

So the custom table expression here is all about `JSON` columns. SQL server's `json_value` function is only meant to return scalar values and has a return type of NVARCHAR(4000) which might very easily truncate a long JSON data. In order to avoid that issue, one has to extract the data from that column using the `WITH` syntax - which is not included in the above example for the sake of simplicity.

And I think from object oriented design perspective, JSON related code or table expression has nothing to do with my `CustomConnection` class. I thought there might be two approaches here:

1. Implement `CustomTable<T>` which basically overwrites its own GetTable method and sends the `MethodInfo` to your `GetTable`.
2. Okay, don't have a `CustomTable<T>` and put the things within `CustomConnection` which I _don't_ prefer anyway.

The method that demonstrates the 1st approach is `GetCustomTableAsQueryable2`. That method invokes the `GetTable` method directly on _your_ data connection. So I am not really sure why it still needs to complain about _my_ data connection not being a `DataConnection` instance. I am already giving it a _real_ `DataConnection`.

The method that demonstrates the 2nd approach is `GetCustomTableAsQueryable1`. That method also invokes the `GetTable` method directly on _your_ data connection. 

All in all, I am trying to solve the `json_value` functions problem with being able to return anything larger than a `scalar` value.

Please let me know if you have any specific questions I might have skipped to explain.

**Comment by sdanyliv** [comment]
Okey, but better to show linq query sample that you are trying to achieve. Also it is better to show which sql do you expect. It will speedup my overloaded mind.

**Comment by CoskunSunali** [comment]
It is here at https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-2017#example-3---join-rows-with-json-data-stored-in-table-cells-using-cross-apply

```sql
SELECT SalesOrderID, OrderDate, value AS Reason  
FROM Sales.SalesOrderHeader  
     CROSS APPLY OPENJSON (SalesReasons) WITH (value nvarchar(100) '$')
```

And since my developers can query inner properties like `$.XXX.YYY` instead of the `$` directly, I will for sure handle that. Just not the scope of this issue. However, multiple paths can be queried within the same linq query. Not just one. So it can be value1, value2, ...valueN.

I have not written a particular linq query since the above methods failed even with just `GetTable<T>().ToList()`. You remember helping me with the `JsonColumn` attribute? That is going to be integrated into this one.

**Comment by CoskunSunali** [comment]
Thanks for the reply and sorry for the late response.

I see. Do you suggest me going back to the not-so-good-but-old EAV design to handle attributes of not-known-at-design-time but only-known-at-runtime kind of objects?

What is your experience with linq2db along with EAV design, does it perform well given that necessary indexes are created?

Can I also use the `property bag` (you call them dynamic properties?) with linq2db and EAV?

I really don't want to give up on going forward with linq2db as I can see the attention you are paying to it, especially you @sdanyliv. Very much looking forward to v3 (I guess there is no approximate ETA or roadmap for that, right?)

**Comment by sdanyliv** [comment]
@CoskunSunali, to version 3.0 about 2-3 months.
Will find time to look at your problem closer since it is real case that needs to be handled without writing raw SQL.

**Comment by CoskunSunali** [comment]
Lovely! `2-3 months` is rather appreciated comparing to `we don't have an ETA yet` :)

Would you like me to change the title of this issue and what to if yes, so that it can be found easier by others looking for a similar design problem?

By the way, I guess what I am trying to do is already clear but all in all, the only final result I am trying to have is:

1. Don't want developers to be have to create a new table object (a class that has `Table` attribute) for every single type of object they want to store
2. I want to handle most of the custom logic within a class called `Content<T>` where `T` is the type of the object they want to store within the table (consider it like a document table). `Content<T>` has basic properties like `Id` on its own and also exposes a property of type `T` where the name is something like `Value`.
3. Application bootstrapper will take care of the custom conversion of `T` from database and into database (you helped with that earlier in another issue, thanks!) by registering the necessary converters during initialization.
4. `T` classes don't have to define linq2db mapping attributes. If EAV is the way to go, things will be setup based on the property types using reflection (custom logic, not expecting linq2db to understand it out of the box) and stored in several columns like IntValue, LongValue, StringValue, DateTimeValue, etc. If EAV is not suggested and you can pay attention to MSSQL JSON columns, I would just say WOW.

I am aware that most of these better fit into a NoSQL database. However, given the complexity of today's applications, it started to be really common to use a relational database and NoSQL database together. Since it means maintaining two separate infrastructures, we finally started seeing relational databases supporting non-relational data, as in document stores or NoSQL databases. You know MSSQL, MySQL, PostgreSQL, Oracle, all now support JSON storage this way or that way with their pros and cons.

I am also aware that the `one table for all` approach might not be the best idea at all times but it has its uses and is really useful sometimes. None of the above statements mean that we will be using a single table by the way. AspNet Identity tables and plenty other tables will get their own database tables. It is just some generic content table with JSON or EAV design that we would like to have in our internal framework where the ORM or ORM-ish framework is abstracted away.

Let me know if you have any business questions like what would we like, how would we like, why would we like, you know, just to brainstorm together.

Your replies, comments and concerns are really appreciated.

**Comment by CoskunSunali** [comment]
@sdanyliv I know you are quite busy these days, as you explicitly mentioned earlier. So my intention is not pushing you but I would really like to hear your thoughts about my last comment. If you could be so kind to share your opinions if and when you have time, I would really appreciate.

**Comment by sdanyliv** [comment]
@CoskunSunali, there are a lot of work for version 3.0 but we can implement features that do not break library interface early. Let's follow your steps.

>1. Don't want developers to be have to create a new table object (a class that has Table attribute) for every single type of object they want to store

You can register IMetadataReader in mapping schema and configure mapping according to your needs.
Simple sample, how he play with EF Core metadata: 
https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs#L19

> 2. I want to handle most of the custom logic within a class called `Content<T>` where `T` is the type of the object they want to store within the table (consider it like a document table). `Content<T>` has basic properties like `Id` on its own and also exposes a property of type `T` where the name is something like `Value`.

Sorry we had discussions about this early, but switching contexts cleared my memory :)

I see your problem and currently trying to invent solution. I will create PR and you can monitor progress.
I hope my work will be introduced in separate library. If i found limitations in linq2db we will fix them.

**Comment by sdanyliv** [comment]
@CoskunSunali, great sample. That's what i'm need for prototyping.
Almost everything fits to linq2db. But needs appropriate wrapping.

**Comment by CoskunSunali** [comment]
@sdanyliv Happy that I could help! And I am looking forward to working with you on your PR, even if you don't need my coding skills, I will just comment.

What is missing from the above samples is partial update. I am a bit against using proxy objects because 1) performance 2) they usually leak list objects and that requires plenty of workaround code. But at the same time, I don't see any other solution if I want to dynamically handle partial updates, e.g. track changed columns.

Will you decide JSON vs EAV on the go? What do you feel like you will use?

Finally, really looking forward for the PR. One line of code is worth a thousand words for both of us :)

Hats off for you, great support and assistance. Thanks a million times for your time and attention.

**Comment by sdanyliv** [comment]
@CoskunSunali, thinking about partial update also.

**Comment by CoskunSunali** [comment]
Just ping me whenever you feel like. I am going to spend time on this one, testing, commenting, brain storming, whatever. Leaving you in peace so that you can work instead of spending time to reply here :)

Cheers.

**Comment by sdanyliv** [comment]
@CoskunSunali, how do you plan in your structure set name of the table?

**Comment by CoskunSunali** [comment]
I am afraid I don't understand what you mean by `structure set name`. Would you mind elaborating a bit so I can answer?

**Comment by sdanyliv** [comment]
@CoskunSunali, try this `CustomMetadataReader`.
Check that you can select, update, detele data. For sure JSON is not supported yet.
```cs
		public class CustomMetadataReader : IMetadataReader
		{
			public T[] GetAttributes<T>(Type type, bool inherit = true) where T : Attribute
			{
				if (typeof(Content<>).IsSameOrParentOf(type))
				{
					var valueType = type.GetGenericArguments()[0];

					if (typeof(T) == typeof(TableAttribute))
					{
						return new T[] { (T) (Attribute) new TableAttribute(valueType.Name) };
					}
				}

				return Array.Empty<T>();
			}

			public T[] GetAttributes<T>(Type type, MemberInfo memberInfo, bool inherit = true) where T : Attribute
			{
				if (typeof(Content<>).IsSameOrParentOf(type))
				{
					var valueType = type.GetGenericArguments()[0];

					if (typeof(T) == typeof(ColumnAttribute) && memberInfo is PropertyInfo prop)
					{
						var isPrimaryKey = prop.Name == "Id";
						return new T[] { (T) (Attribute) new ColumnAttribute { IsPrimaryKey = isPrimaryKey } };
					}
				}

				return Array.Empty<T>();
			}

			public MemberInfo[] GetDynamicColumns(Type type)
			{
				return Array.Empty<MemberInfo>();
			}
		}
```
You have to add this reader to MappingSchema:
```cs
			var dataReader = new CustomMetadataReader();
			MappingSchema.Default.AddMetadataReader(dataReader);
```

**Comment by CoskunSunali** [comment]
So you mean if I implement what you just shared, that would support all of the features of the sample we discussed above? Really? That short?

**Comment by sdanyliv** [comment]
It will start mapping your classes to real database. It is a part of my solution but it covers almost everything instead of JSON objects.

**Comment by CoskunSunali** [comment]
Alright, I will integrate it into my solution using the above sample we discussed and see how it goes.

Basically, I should go with entity-attribute-value schema in this case, right?

**Comment by sdanyliv** [comment]
> Basically, I should go with entity-attribute-value schema in this case, right?

Each entitity is a table, each property is a column.

**Comment by sdanyliv** [comment]
I'm confused.  
What is a table for your entities? How do you plan to store `Content<Car>`?

**Comment by CoskunSunali** [comment]
A common table (using JSON for the `Data` column) or EAV schema for storing all properties of `T` of `Content<T>`.

So I am trying to avoid being have to create a table-per-class (even if it is generic like `Content<T>`) because my classes can be plenty of different classes and some of them are `designed` using a visual interface, so they don't even exist in C# world in terms of strongly typed classes, hence the JSON or EAV is needed.

**Comment by sdanyliv** [comment]
I have the following test:
```cs
		[Test, Combinatorial]
		public void SampleSelectTest([DataSources(false)] string context)
		{
			var dataReader = new CustomMetadataReader();
			MappingSchema.Default.AddMetadataReader(dataReader);
			var mappingSchema = new MappingSchema();

			using (var db = GetDataContext(context, mappingSchema))
			using (var table = db.CreateLocalTable<Content<Person>>())
			{
				var result = table.ToArray();
			}
		}
```
I have the following SQL
```sql
CREATE TABLE [Person]
(
	[Id]   INTEGER   NOT NULL,
	[Data] Undefined     NULL,

	CONSTRAINT [PK_Person] PRIMARY KEY ([Id])
)

SELECT
	[t1].[Id],
	[t1].[Data] as [Data1]
FROM
	[Person] [t1]
```

**Comment by sdanyliv** [comment]
Ok, i got it again. Simultaneously working on two projects.
But, if we just correct `TableAttribute` creation - we got one table.

**Comment by CoskunSunali** [comment]
Right, maybe we misunderstood each other.

All I am trying to do is to avoid the need for separate tables as in `db.CreateLocalTable<Content<Person>>`

```
Ok, i got it again. Simultaneously working on two projects.
But, if we just correct TableAttribute creation - we got one table.
```
:) No worries at all, I am already glad you are doing so much to assist people here and I appreciate `every single byte of your assistance`.

**Comment by CoskunSunali** [comment]
@sdanyliv Is there anything I can assist you with regards to this issue? Or anything you want me to try to implement by myself?

**Comment by sdanyliv** [comment]
@CoskunSunali, sorry. I have no time today. Will find several hours on weekend.

**Comment by CoskunSunali** [comment]
No worries! Just let me know for anything I can do. I don't want to waste your time in case something is misunderstood.

By the way, please remember the `Content<T>` class which is the only `virtual` table we are aiming to create (apart from the entity, attribute and value tables). I am saying virtual because it is a combination of multiple tables hence the EAV schema. Considering that everything cannot be strongly typed at all times, especially if the EAV's attributes can be managed using a web GUI by end users, they might not be a part of the backing class (`T`).

Do you think it is too much to also have a `Content` class that the `Content<T>` inherits from and the `Content` class to have a property bag and a method like `GetValue<T>(string attributeName)` which returns the attribute of type `T` (string, bool, DateTime, etc).

No rush with replies since you don't have the time. I understand. Cheers.

**Comment by sdanyliv** [comment]
@CoskunSunali, samples really helps in investigation. Also show schematically which SQL do you expect - that’s how my mind understands problem.

**Comment by CoskunSunali** [comment]
@sdanyliv I am sorry for not getting back earlier. I decided this should be solved at the business layer rather than the data layer.

Feel free to close the issue in case you don't keep it open for your own ideas.

Thank you!

**Comment by MaceWindu** [comment]
Closing for now
