### ISSUE TITLE
Operation could destabilize the runtime

### ISSUE THREAD

**Issue by boris-turk** [linq2db/linq2db#1319]
Hi everybody,

I noticed a strange error related to dynamic columns feature. Below there is a unit test which fails with a weird error "Operation could destabilize the runtime". I couldn't reproduce the error with the standard test classes in Linq2Db code base, don't know why exactly. But my test case is pretty straight forward, the only special thing is the usage of Sql.Prperty mechanism (dynamic column).

If I omit the dynamic property, then the union statement executes correctly. Does anyone have an idea why I am getting this weird error and whether it could be fixed (hopefully in an easy way)? Thank you in advance,

Boris Turk

	public class SomeClass
	{
		public string Description { get; set; }

		[DynamicColumnsStore]
		public IDictionary<string, object> ExtendedProperties { get; set; }
	}

	[TestFixture]
	public class UnionTests
	{
		[Test]
		public void Test()
		{
			DataConnection.DefaultDataProvider = ProviderName.SqlServer2014;
			DataConnection.AddConfiguration("database", GetConnectionString());
			DataConnection.DefaultConfiguration = "database";

			using (var dataContext = new DataContext())
			{
				var builder = dataContext.MappingSchema
					.GetFluentMappingBuilder()
					.Entity<SomeClass>();

				builder.Property(x => x.Description).HasColumnName("F066_04");
				// if I comment this line, then everything works as expected
				builder.Property(x => Sql.Property<string>(x, "F066_05"));

				var result =
					dataContext.GetTable<SomeClass>().TableName("M998_T066")
						.Union(dataContext.GetTable<SomeClass>().TableName("M998_T066"))
						.ToList();
			}
		}

		private string GetConnectionString()
		{
			var connectionBuilder = new SqlConnectionStringBuilder
			{
				InitialCatalog = "V60",
				ConnectTimeout = 3600,
				IntegratedSecurity = true,
				["server"] = "."
			};

			return connectionBuilder.ToString();
		}
	}

**Comment by MaceWindu** [comment]
Fixed by #1326
