### ISSUE TITLE
Timestamp column type

### ISSUE THREAD

**Issue by CroveanOS** [linq2db/linq2db#1322]
Hello.

In previous versions, ~ v2.0, the column of type 'Timestamp' used to generate a property of type DateTime. Currently, in version 2.3 the generated property is of type object. Is this an intentional change?

Database: PostgreSQL

Thanks!

**Comment by MaceWindu** [comment]
object is definitely not intentional and must be fixed

**Comment by ExzaSolutions** [comment]
Hi When will this be fixed?

**Comment by MaceWindu** [comment]
Whoops, forgot to close it with 2.4.0 release
