### ISSUE TITLE
DefaultConfiguration is not null

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1323]
Changed from Version 1.9.0 to 1.10.0

Hello,

I don't know if this is a bug or not, but the DefaultConfiguration changed from null to 'LocalSqlServer'.
I haven't seen anything in the release notes to this.
Is this a wanted change? Because it sounds so arbitrarily to take 'LocalSqlServer'.

**Comment by MaceWindu** [comment]
Code, responsible for it wasn't changed since v1.7.5, so I will assume it is environment changes. Please reopen if you think we have issue here
