### ISSUE TITLE
[Question, Suggestion] Case-sensitive string comparison

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#1337]
I can't seem to find this, but is there any built-in support for case-sensitive string comparison in linq2db?
I know I can use custom functions like `Sql.Function` to manually build SQL, but I would like to have it like:

`q.Name.StartsWith( "Test", false, CultureInfo.InvariantCulture )`
or
`q.Name.StartsWith( "Test", StringComparison.InvariantCulture )`
or
`q.Name.Equals( "foo", StringComparison.InvariantCulture )`
or
`string.Compare( q.Name, "foo", false )`

...or any other variant of string comparison.

Is this supported and if not do you have a plan to implement this?

**Comment by sdanyliv** [comment]
@stsrki, you can introduce mapping 
```cs
Expressions.MapMember(
   (string v1, string v2, bool c) => string.Compare(v1, v2, c), 
   (v1, v2, c) => SqlFuncs.SomeMyCompareFunc(v1, v2, c)
);
```
Using this technique you can map any standard method to to functions with specific attributes.

**Comment by sdanyliv** [comment]
Closing for now, looks like it is already answered.
