### ISSUE TITLE
[Question] How to determine whether there is a current transaction

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#1341]
Is there any way to find out if the Connection already has an active Transaction?

I am writing a method that needs to be atomic but it could also be a part of another method that has already created a transaction.  I therefore need to check whether there is already a transaction in progress and only start a new one in the method if there isn't.

### Environment details
linq2db version: 2.3.0
Database Server: any
Database Provider: any
Operating system: Windows 10
Framework version: .NET Framework 4.6.2

**Comment by sdanyliv** [comment]
@RoyC-Retail-Assist, how about `TrasactionScope` usage?
Also you can use `Transaction.Current`

**Comment by RoyC-Retail-Assist** [comment]
Can we use TransactionScope with a DataContext?  If so, do you have an example I can try?

**Comment by sdanyliv** [comment]
https://github.com/linq2db/linq2db#transactions

@RoyC-Retail-Assist, linq2db is lightweight ORM, almost all that you know about DbConnection should work.

**Comment by RoyC-Retail-Assist** [comment]
Thanks.  I new there would be a simple answer even though I couldn't see it.

**Comment by sdanyliv** [comment]
https://msdn.microsoft.com/en-us/library/ms973865.aspx
Example 6. Indirect scope nesting
