### ISSUE TITLE
Update System.Data.SqlClient to version 4.5+

### ISSUE THREAD

**Issue by lexCerveza** [linq2db/linq2db#1342]
Hi to all.

Current linq2db 2.4.0 version has dependency on System.Data.SqlClient version 4.4.2.
Please, update it to 4.5+ version because this version does not support TransactionScope in dotnet core 2.0+ projects

Link to github issue which describes this problem
https://github.com/dotnet/corefx/issues/24282

**Comment by sdanyliv** [comment]
@lexCerveza, we will update in next release. But you can do that also in your projects without waiting. Just add nuget package `System.Data.SqlClient` manually and linq2db should use newest one.

**Comment by lexCerveza** [comment]
@sdanyliv thanks a lot

**Comment by MaceWindu** [comment]
Looks like they dropped net45 support, so I will bump version only for net core targets
