### ISSUE TITLE
Updating DataConnection.CommandTimeout doesn't update DataConnection.Command.CommandTimeout

### ISSUE THREAD

**Issue by JamesAtPropertyMe** [linq2db/linq2db#1354]
During the lifetime of a `DataConnection`, if I set `DataConnection.CommandTimeout` and run a query, which lazy loads a `DataConnection.Command`, the `_commandTimeout` will be passed to `DataConnection.Command`. However, if I update `DataConnection.CommandTimeout` again, the `DataConnection.Command.CommandTimeout` isn't updated. This caused some inconsistency in the expected behaviour of the db access. The stack track of the timeout exception is very vague and took me some time to find out this problem. Suggest to change `DataConnection.cs`'s `CommandTimeout` property setting code to be something like:

```
public  int   CommandTimeout
{
	get { return _commandTimeout ?? 0; }
	set
	{
		_commandTimeout = value;
		if (_command.HasValue)
		{
			_command.CommandTimeout = value;
		}
	}
}
```

**Comment by MaceWindu** [comment]
Fixed by #1356
