### ISSUE TITLE
Inferring columns based on interface mappings

### ISSUE THREAD

**Issue by benliebert** [linq2db/linq2db#1365]
This is a follow on from #1099 which I wrote last year concerning queries which were created using interface entities.

## Overview - my goal
We build bespoke web applications, many of which need a shopping cart.  As such, we have abstracted the common functionality into a different assembly.  This common functionality includes data queries such as `GetCart()`, `GetCartItems()` etc.  

Because we do not know the precise database layout of each individual client app that will use this library, our data queries operate over _interfaces_ - not _classes_.  For example, we have an interface:

``` c#
public interface ICartItem {
    int CartItemID {get;set;}
    string Name {get;set;}
}
```

Our data interface (nothing to do with L2DB yet) is:

```c#
public interface ICartRepository : IRepository
{
	IQueryable<ICartItem> CartItem { get; }
}
```

And our query is:

```c#
public List<TCartItem> GetCartItem(int cartItemID)
{
    using (var cxt = Dependency.Resolve<ICartRepository>()) {
        return cxt.CartItem.FirstOrDefault(x => x.CartItemID == cartItemID);
    }
}
```

So far, so good.  Now we get to the actual client implementation:

```c#
public class OrderItem : ICartItem{
    public int CartItemID {get;set;} // ICartItem
    // Other properties...
}
```

If the `CartItemID` property is the same as a mapped database name...

```c#
fluent.Entity<OrderItem>().Property(x => x.CartItemID).HasColumnName("CartItemID");
```

...everything works fine.

But this is not usually the case.  Rather, the client database should be at liberty to create _their own database structure_, which we then map to our common interface like this:

```c#
public class OrderItem : ICartItem{
    public int OrderItemID {get;set;}
    public int CartItemID {get { return this.OrderItemID; } set { this.OrderItemID = value; } // ICartItem
    // Other properties...
}
```
and
```c#
fluent.Entity<OrderItem>().Property(x => x.OrderItemID).HasColumnName("OrderItemID");
```

In this case, when we try the above query, (`cxt.CartItem.FirstOrDefault(x => x.CartItemID == cartItemID)`), I get an error indicating that `CartItemID` does not belong to the table.

Okay, well not ideal, but I kind of understand why L2DB wouldn't support this.  So, as an interim, I try to map the column to the OrderItemID column:
```c#
fluent.Entity<OrderItem>().Property(x => x.CartItemID).HasColumnName("OrderItemID");
```

Unfortunately, this throws a different error because now _two_ columns are being mapped to the same column name.

Can anybody think of a way I can keep my dream alive?

## System specs
Windows 10
L2DB v 2.4.0
ASP.Net v4.6.1

Thanks guys - much appreciated (great product by the way)

**Comment by igor-tkachev** [comment]
@benliebert, try the ColumnAlias attribute. 

```c#
fluent.Entity<OrderItem>()
    .Property(x => x.CartItemID)
        .HasAttribute(new ColumnAliasAttribue("OrderItemID"));
```

**Comment by benliebert** [comment]
Thanks @igor-tkachev .  Thanks firstly for the quick response.  The solution sounded promising but hasn't initially worked.  Here is my updated code:

```c#
fluent.Entity<OrderItem>().HasPrimaryKey(x => x.OrderItemID).HasIdentity(x => x.OrderItemID);
fluent.Entity<OrderItem>().Property(x => x.OrderItemID).HasColumnName("OrderItemID");
fluent.Entity<OrderItem>().Property(x => x.OrderID).HasColumnName("OrderID");
// etc etc

// Now your update
fluent.Entity<OrderItem>().Property(x => x.CartItemID).HasAttribute(new ColumnAliasAttribute("OrderItemID"));
```

This results in this error:
> System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CartItemID'.

Given that it is a SQL error, I expected that the system was still generating SQL.  So, I added the `IsNotColumn()`:

```c#
fluent.Entity<OrderItem>().Property(x => x.CartItemID).IsNotColumn().HasAttribute(new ColumnAliasAttribute("OrderItemID"));
```
Unfortunately this led me back to my original error:
> LinqToDB.Linq.LinqException: Expression 'x.CartItemID' (x.CartItemID) is not a table

I'm going to try to find some docs on the `ColumnAlias` attribute because it sounds promising, perhaps it is simply a question of code order.  I'll report back on my findings, but if you can advise in the meantime, it would be hugely appreciated.

**Comment by benliebert** [comment]
I do note that the docs indicate there are issues:

![image](https://user-images.githubusercontent.com/2273767/47524553-6488aa80-d8f7-11e8-9728-c8cd82c6fa35.png)

**Comment by igor-tkachev** [comment]
It might be a problem with the fluent mapping. I will look into it.

**Comment by sdanyliv** [comment]
@benliebert, if your provide small console application with reproducing error it will be helpful and it will be quickly fixed.
New release is coming next week and you have chance to be on this train.

**Comment by benliebert** [comment]
Thanks @sdanyliv - it would be amazing to sneak this into the release.  I've repro'd at https://github.com/benliebert/L2DBInterfaceMappingExample and included instructions in the ReadMe.  It's a really simple repro so hopefully easy enough to follow.  I used the same entity names as described above, to keep things simple.  Thanks very much.

**Comment by benliebert** [comment]
@sdanyliv I see 2.5.1 was released yesterday, but it doesn't appear this ticket was in it.  Is there a timeframe for the 2.X milestone?

**Comment by sdanyliv** [comment]
@benliebert, sorry i have missed you message. I thought i’m monitoring all notifications. Will take care about that.

**Comment by benliebert** [comment]
Thanks @sdanyliv.  Out of interest, do you have an idea of when it might be available in a release?  I only ask because I've put a client project on hold in the hope that the fix becomes available soon.  But if it will be a few weeks, that is fine - I can hack a workaround.

**Comment by sdanyliv** [comment]
I have to analyse your sources. But i think two week is enought. Even it is not released yet you can use MyGet packages.

**Comment by sdanyliv** [comment]
@benliebert, you can use sample from `FluentMappingAliasTests` unit test in PR  #1389

**Comment by benliebert** [comment]
@sdanyliv I have forked and merged your PR and it works perfectly.  Thank you very much, I have been delighted with the support and responsiveness of this free product.
