### ISSUE TITLE
Is it possible to query a not mapped table with the same schema that a mapped table?

### ISSUE THREAD

**Issue by desarrollo03TR** [linq2db/linq2db#1369]
I have some tables with exactly the same structure, but different table name, example:

    TableXXX2016
    TableXXX2017
    TableXXX2018
    ...
   
I need to query that tables using the table name... is it possible?

**Comment by sdanyliv** [comment]
Yes it is possible
```cs
db.GetTable<TableXXX2016>().TableName(“OtherName”)
```

**Comment by desarrollo03TR** [comment]
Nice! Thanks.
