### ISSUE TITLE
Cannot provide dynamic types into Query parameters

### ISSUE THREAD

**Issue by glacorSoul** [linq2db/linq2db#1370]
I am calling `QueryToListAsync` with a handmade query and some `DataParameter(s)`. My issue is that the value of my `DataParameter` is `dynamic`. More specifically, I am deserializing some `JSON` into a dynamic type, however `linq2db` doesn't seem to support this scenario.

### Steps to reproduce
```
	type  [<CLIMutable>] SearchCriteria = {
        Operator: string;
        Property: string;
        Value: obj //this value is deserialized with JIL
    }
	
	type [<CLIMutable>] SearchModel = {
        Page: int;
        Limit: int;
        Filter: SearchCriteria[]
    }    
	
    [Table("Sessions")]
    public class SessionDb {
        [PrimaryKey, NotNull]
        public string Id { get; set; }
        [Column(DbType = "json", DataType = DataType.Json), Nullable]
        public string Data { get; set; }
        [Column, Nullable]
        public string LastModifiedBy { get; set; }
        [Column, Nullable]
        public DateTime LastModifiedAt { get; set; }
        [Column, Nullable]
        public string Service { get; set; }
    }
	
	public class SessionContext : DataConnection
    {
        public ITable<SessionDb> Session => GetTable<SessionDb>();
    }
	
	let listSessions (searchOptions: SearchModel) = async{
	
		use context = new SessionContext()
		let obj = 
		  searchOptions.Filter
		  //p.Value is a type provided by JIL and is not a primitive not a databasase compatible typer like int bool, string, DateTime...
		  |> Seq.map(fun p -> DataParameter(p.Property, p.Value)) 
		  |> Seq.toArray
		return Async.AwaitTask(context.QueryToListAsync<SessionDb>(query, obj))
	}

```
### Environment details
linq2db version: *2.4.0*
Database Server: MySql 8.0.12
Database Provider: MySql
Operating system: Windows 10
Framework version: .Net Core 2.1 (f# 4.5.2)

**Comment by sdanyliv** [comment]
@brunoss, it is hard to understand F# for the people who never write single line of code this language.

At first sign you have to convert `p.Value` to appropriate type yourself. linq2db do not provides special conversions for the types which don't know.
Why do not write function that create DataParameter with functionality that you have mentioned in source comment?

**Comment by brunoss** [comment]
@sdanyliv I wasn't sure of what my options were. I also wanted to report the issue in case you want to do something about it.

**Comment by brunoss** [comment]
@sdanyliv When I tried to use an explicit type for my parameter it also didn't work. In my specific case the type was `Int32` I believe the reason why it didn't work was because my value was not an integer and could not be converted by regular means.

**Comment by sdanyliv** [comment]
Maybe i have missed something. In this case i will write the following function and use in your `map`:
```cs
public static DataParameter CreateDynamicParameter(string name, object value)
{
	if (value == null)
            return new DataParameter (name, null);

	var str = value.ToString(); 
	if (int.TryParse(str out var i))
		return new DataParameter(name, i, DataType.Int32);
	else if (DateTime.TryParse(str out var d))
		return new DataParameter(name, d, DataType.DateTime);
	else if (bool.TryParse(str, out var b))
		return new DataParameter(name, b, DataType.Boolean);
	else
		return new DataParameter(name, str, DataType.NVarChar);
}
```

**Comment by MaceWindu** [comment]
Looks like external issue with missing type conversions
