### ISSUE TITLE
Documentation: how to do group by

### ISSUE THREAD

**Issue by hahn-kev** [linq2db/linq2db#1379]
Currently there's no documentation on how to do group by.  I know the following works
```C#
from product in db.Product
from category in db.Category.InnerJoin(c => c.ID = product.CategoryID )
group product by new {product.CategoryID, category} into _
select new {
    categoryCost = product.Sum(p => p.UnitPrice),
    _.Key.CategoryID,
    _.Key.category.Name
}
```

I'd love to get this documented for others, and learn other ways that linq2db supports group by.

**Comment by sdanyliv** [comment]
It is standard in .NET world, usually it is explained in deprecated library LinqToSql.
I sugest to find how it is documented in EFCore and adopt to our needs.

BTW, they did a trick: 
https://docs.microsoft.com/en-us/ef/core/querying/basic

**Comment by MaceWindu** [comment]
Please check this https://github.com/linq2db/linq2db/issues/1608 :smile:
