### ISSUE TITLE
linq2db provider for Postgre SQL 10

### ISSUE THREAD

**Issue by 80LevelElf** [linq2db/linq2db#1386]
I want to use linq2db with Postgre SQL 10, but I can't see any Postgre SQL provider of this version.

I found out providers for such versions:

	public enum PostgreSQLVersion
	{
	  v92,
	  v93,
	  v95,
	}

Also, I have run example app with the latest versions of linq2db library, looked at the `_dataProviders` internal variable of the DataConnection object and ... there are no applicable providers for Postgre SQL of 10 version.

How is this possible? We already have Postgre SQL of 11 version and linq2db have providers only for 9 version? Looks like I have missed something.

**Comment by sdanyliv** [comment]
@80LevelElf, basically we introduce such versions because of important difference in SQL dialect. Latest provider 9.5 should work in your case.
