### ISSUE TITLE
Type "hstore" does not exist.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1391]
Hi guys.

I want to execute a query on a PostgreSQL database, but I have an error that the type "hstore" does not exist.

My code and Query are:
```
string query = "ALTER TABLE audit.logged_actions ADD \"row_data\" hstore";
using(var db = new MyDb())
{
    db.Execute(query);
}
```

How can this be solved?

### Environment details
linq2db version: 2.5.1
Database Server: PostgreSQL 10.3
Database Provider: Npgsql 4.0.3
Operating system: Windows 10 x64 Pro
Framework version: .NET Framework 4.7.2

**Comment by sdanyliv** [comment]
@YXMagnuMXY, it is not linq2db issue. Looks like you have to install extension (once per database)
```sql
CREATE EXTENSION hstore;
```
http://www.postgresqltutorial.com/postgresql-hstore/

**Comment by YXMagnuMXY** [comment]
Thank you for help!
