### ISSUE TITLE
Error at "NOT"

### ISSUE THREAD

**Issue by matrix2019** [linq2db/linq2db#1394]
Hello Linq2db team! 👍 

I have created a c# project using SQL Express.
Everything works fine with db.CreateTable<XY>();

now I have changed the DataProvider to PostgreSQLDataProvider.
When I call the db.CreateTable<XY>();
I got an exception 42601: Syntaxfehler bei »NOT«

Maybe my DBConnection class has some errors? I do not use T4.
Here is my dataconnection class
```cs
public class DBConnection : LinqToDB.Data.DataConnection
{
   
	public DBConnection(DatabaseType typ, string constr) : base(GetDataProvider(typ),constr)
	{

	}

	static IDataProvider GetDataProvider(DatabaseType typ)
	{

		LinqToDB.Common.Configuration.AvoidSpecificDataProviderAPI = true;

		switch (typ)
		{
			case DatabaseType.Access:
				return new AccessDataProvider();
			case DatabaseType.MSSQL2005:
				return new SqlServerDataProvider("", SqlServerVersion.v2005);
			case DatabaseType.MSSQL2008:
				return new SqlServerDataProvider("", SqlServerVersion.v2008);
			case DatabaseType.MSSQL2012:
				return new SqlServerDataProvider("", SqlServerVersion.v2012);
			case DatabaseType.PostgreSQL:
				return new LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider();
			case DatabaseType.SQLite:
				return new SQLiteDataProvider();
		}
		throw new Exception("Database is not supported!");
	}

}
```
I use dotnet 4.5, LINQ2DB 2.5.1.0 and  NPGSQL 3.2.5.0

help please :-)

best regards

**Comment by matrix2019** [comment]
sorry I forgot

my code with the exception

DBConnection db = new DBConnection(Global.DBType, Global.Dbconstr);

                    var schema = db.DataProvider.GetSchemaProvider();
                    var dbSchema = schema.GetSchema(db);

                    if (!dbSchema.Tables.Any(t => t.TableName == "Auftrag"))
                    {
                        //no required table-create it
                        db.CreateTable<Auftrag>();

=> Exception at db.CreateTable<Auftrag>();

**Comment by sdanyliv** [comment]
@matrix2019, please post class definition for `Auftrag`.
Also post SQL that was generated. Thanks.

**Comment by matrix2019** [comment]
Hi sdanyliv

Auftrag class
  [Table(Name = "Auftrag")]
    public class Auftrag
    {
        [Browsable(false)]
        [PrimaryKey, Identity]
        public int ID { get; set; }

        [DisplayName("Nr.")]
        [Column(Name = "IDAccess"), NotNull]
        public Int64 ID_Access { get; set; }

        [Column(Name = "ShowOnMap")]
        [DisplayName("Karte")]
        public bool AnzeigenAufKarte { get; set; }

        [Column(Name = "Aufragstyp")]
        [DisplayName("Typ")]
        public EAuftragsType AuftragsType { get; set; }

        [Column(Name = "Status")]
        public AuftragsStatusType Status { get; set; }



        [Column(Name = "KD-Nr"), NotNull]
        public int KundenNr { get; set; }

        [Column(Name = "Name")]
        public string Name { get; set; }

        [Column(Name = "Strasse")]
        public string Strasse { get; set; }

        [DisplayName("Plz")]
        [Column(Name = "PLZ")]
        public string PLZ { get; set; }

        [Column(Name = "Ort")]
        public string Ort { get; set; }

        [Column(Name = "Datum")]
        public DateTime Anzeigedatum { get; set; }

        [Column(Name = "Latitude")]
        [Browsable(false)]
        public double Latitude { get; set; }

        [Column(Name = "Longitude")]
        [Browsable(false)]
        public double Longitude { get; set; }

        [Browsable(false)]
        [Column(Name = "FahrzeugID")]
        public long FahrzeugID { get; set; }

        [Column(Name = "FZKZ")]
        [DisplayName("Fahrzeug")]
        public string FahrzeugKZ { get; set; }

    }

two enums
 public enum EAuftragsType
    {
        [MapValue("1")]
        E,
        [MapValue("1")]
        A
    }

  public enum AuftragsStatusType
    {
        [MapValue("0")]
        Neu,
        [MapValue("1")]
        Erledigt
    }

maybe it helps

**Comment by sdanyliv** [comment]
Thanks, will find time to fix that.
Also we appreciate PRs, it should be not so difficult to find porblem in SqlBuilder ;)

**Comment by sdanyliv** [comment]
@matrix2019, problem here that we do not throw appropriate message in your case.
You have to define DataType for your enum columns:
```cs
	[Column(Name = "Aufragstyp", DataType = DataType.VarChar)]
	[DisplayName("Typ")]
	public EAuftragsType AuftragsType { get; set; }

	[Column(Name = "Status", DataType = DataType.VarChar)]
	public AuftragsStatusType Status { get; set; }
```

**Comment by sdanyliv** [comment]
BTW, strange that this works for other providers, will take a look.

**Comment by matrix2019** [comment]
Hi @sdanyliv,

ok, it works! :-) but why is it DataType.VarChar ?
Maybe numeric value would ne better for indices?

**Comment by sdanyliv** [comment]
Sure. So you have to set appropriate type. Also string columns needs length.

**Comment by matrix2019** [comment]
I don't understand what you mean?

**Comment by sdanyliv** [comment]
If you just define
```cs
	[Column(Name = "Strasse")]
	public string Strasse { get; set; }
```
We don't know size of string and use default value according to Data Provider. Better to define it by yourself
```cs
	[Column(Name = "Strasse", Length = 100)]
	public string Strasse { get; set; }
```

**Comment by matrix2019** [comment]
ah, ok. that's right!
Thank you so much, sdanyliv!!! :-)
