### ISSUE TITLE
Reduce db roundtrips

### ISSUE THREAD

**Issue by loudadyassine** [linq2db/linq2db#1402]
Hi,

Is it possible to reduce db roundtrips by sending requests by batch ( Like NHibernate Future<T>() ) ?

For the paging example, it's ok to have two requests, but could we send them togheter in one batch and parse the results one time ? : 

```
public static List<Product> Search(string searchFor, int currentPage, int pageSize, out int totalRecords)
{
  using (var db = new DbNorthwind())
  {
    var products = from p in db.Product 
                   select p;

    if (searchFor != null)
    {
      products = from p in products 
                 where p.Name.Contains(searchFor) 
                 select p;
    }

    totalRecords = products.Count();

    return products.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();
  }
}
```

Thank you,

Yassine

**Comment by Franki1986** [comment]
I am not sure but using transactions should work...

**Comment by sdanyliv** [comment]
Hi, @loudadyassine, not yet. But we had thoughts about that. Not as it is done in NHibernate but in our way.

But, I've spend 20 minutes for writing to you simple class which should help in your situation if database supports Window functions.
```cs
public static class QueryPaginator
{
	private class Envelope<T>
	{
		public long TotalCount { get; set; }
		public T Data { get; set; }
	}

	public static List<T> Paginate<T>(IQueryable<T> query, int page, int pageSize, out long totalRecords)
	{
		var withCount = from q in query
			select new Envelope<T>
			{
				TotalCount = Sql.Ext.Count().Over().ToValue(),
				Data = q
			};

		var items = withCount.Skip((page - 1) * pageSize).Take(pageSize).AsEnumerable();

		var result = new List<T>();
		totalRecords = 0;

		using (var enumerator = items.GetEnumerator())
		{
			if (enumerator.MoveNext())
				totalRecords = enumerator.Current.TotalCount;

			do
			{
				result.Add(enumerator.Current.Data);
			} while (enumerator.MoveNext());
		}

		return result;
	}
}
```
and usage 
```cs
var items = QueryPaginator.Paginate(products, currentPage, pageSize, out totalRecords);
```

**Comment by loudadyassine** [comment]
Thank you @sdanyliv , I'll study your example it's interesting. So as for today we have to manage each case individualy. Can we have this in a future release or it's complicated ? The performance benefit can be huge for small requests.

**Comment by sdanyliv** [comment]
@loudadyassine, I've updated sample to be more effective. 
Proposed solution is fastest way for pagination with `TotalCount`.

And yes, `Future` is complicated part and needs rethinking many concepts and API.

**Comment by loudadyassine** [comment]
Ok, thank you @sdanyliv , I looked for that information everywhere. By the way, this library is an excellent piece of code art, keep the good job. Thanks.

**Comment by sdanyliv** [comment]
@loudadyassine, if you think that `Future` is missing important part in our library, please create separate issue, with samples from real world.

**Comment by loudadyassine** [comment]
@sdanyliv Ok I'll do it in the next 24h, I'll present the case of my app which would benefit greatly from this feature.

**Comment by jogibear9988** [comment]
> Hi, @loudadyassine, not yet. But we had thoughts about that. Not as it is done in NHibernate but in our way.
> 
> But, I've spent 20 minutes for writing for you simple class which should help in your situation if database supports Window functions.
> 
> ```cs
> public static class QueryPaginator
> {
> 	private class Envelope<T>
> 	{
> 		public int TotalCount { get; set; }
> 		public T Data { get; set; }
> 	}
> 
> 	public static List<T> Paginate<T>(IQueryable<T> query, int page, int pageSize, out int totalRecords)
> 	{
> 		var withCount = from q in query
> 			select new Envelope<T>
> 			{
> 				TotalCount = (int)Sql.Ext.Count().Over().ToValue(),
> 				Data = q
> 			};
> 
> 		var items = withCount.Skip((page - 1) * pageSize).Take(pageSize).AsEnumerable();
> 
> 		using (var enumerator = items.GetEnumerator())
> 		{
> 			List<T> result;
> 			if (!enumerator.MoveNext())
> 			{
> 				totalRecords = 0;
> 				result = new List<T>();
> 			}
> 			else
> 			{
> 				totalRecords = enumerator.Current.TotalCount;
> 				result = new List<T>(pageSize);
> 				do
> 				{
> 					result.Add(enumerator.Current.Data);
> 				} while (enumerator.MoveNext());
> 			}
> 
> 			return result;
> 		}
> 
> 	}
> }
> ```
> 
> And usage:
> 
> ```cs
> var items = QueryPaginator.Paginate(products, currentPage, pageSize, out totalRecords);
> ```

Is it also Possible to Get 2 Counts like this? We have in our System 2 Counts, one without extra filters and one of the filtered entities this query would return

**Comment by sdanyliv** [comment]
Show me your query or link to issue. I remember you have created such one.

**Comment by Franki1986** [comment]
https://github.com/linq2db/linq2db/issues/687#issue-231834533

**Comment by sdanyliv** [comment]
Try to set
```cs
FilteredCount = Sql.Ext.Count().Over().ToValue()
```
when combining Dto

**Comment by Powerz** [comment]
> Hi, @loudadyassine, not yet. But we had thoughts about that. Not as it is done in NHibernate but in our way.
> 
> But, I've spent 20 minutes for writing for you simple class which should help in your situation if database supports Window functions.

This is awesome, thank you 👍
