### ISSUE TITLE
Column order in an inherited class break query

### ISSUE THREAD

**Issue by erikfroseth** [linq2db/linq2db#1403]
When I have an inherited class with fields containing the "Order" attribute to set column order, querying the table/model fails. If I either remove the inheritance or remove the "Order" attribute, it works just fine.

The following exception is raised:
`LinqToDB.LinqToDBException: 'Mapping of column event_description value failed, see inner exception for details'`

Tested on version 2.5.2, 2.5.1 and 2.5.0. Version 2.4.0 seems to work just fine

Reproducible case:
1) Install latest linq2db and System.Data.SQLite.Core from nuget

File ModelBase.cs:
```
public abstract class ModelBase {}
```

File MyClass.cs:
```
  [Table("MyClass")]
  public class MyClass : ModelBase
  {
    [Column("event_id", Order = 1), PrimaryKey, NotNull, Identity]
    public int EventId { get; set; }

    [Column("event_description", Order = 2), NotNull]
    public string EventDescription { get; set; }
  }
```

File Database.cs:
```
  public class Database : LinqToDB.Data.DataConnection
  {
    public Database() : base("sqlite") { }

    public ITable<MyClass> MyClass => GetTable<MyClass>();
  }
```

File App.config:
```
  <connectionStrings>
    <add name="sqlite"
      connectionString = "Data Source=:memory:;New=True;"
      providerName     = "SQLite" />
  </connectionStrings>
```

Code that fails:
```
  using (var db = new Database())
  {
    db.CreateTable<MyClass>();
    db.Insert(new MyClass()
    {
      EventId = 1,
      EventDescription = "New event"
    });
    var events = db.MyClass.First();
  }
```

**Comment by sdanyliv** [comment]
@jogibear9988, can you handle this?

**Comment by jogibear9988** [comment]
Sorry, haven‘t seen this
