### ISSUE TITLE
Get response from Commit of transaction.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1406]
Hi guys!

Situation:
We have to import a list of Customers from Excel to DB. For this case, we use beginTransaction, the insert method and the commitTransaction(or rollback if something goes wrong). After the commitment we should refresh the UI with all the list of the inserted Customers, and we are getting all of them from DB.

In case that we should insert 10000 of the customers, after the commit, first time when the list refreshes, loads a part of Customers, second refresh returns more, and after the third or fourth refresh we have all the customers in the UI. I know that this is because of the fact that the commit is happening on the server, and we can't get the response when commitment is done, and all the customers are inserted.

Is there a way to get a response when all the data is Inserted(updated, deleted)?

PS: This situation is imaginary...Sorry for my English.

### Environment details
linq2db version: LATEST
Database Server: PostgreSQL 10.3
Database Provider:  NPGSQL for the latest linq2db
Operating system: Windows 10 x64 Pro
Framework version: .Net Framework 4.7.2

**Comment by sdanyliv** [comment]
@YXMagnuMXY, 
You have to use `db.BulkCopy(items)`. It will insert 10000 records in 10 seconds, maybe faster.
It also has callback function for notifying.

**Comment by YXMagnuMXY** [comment]
You want to say that in a transaction, to use BulkCopy?
In the same transaction can be many inserts, updates and deletes of different types and tables...This can happen when you work with many databases, and you try to do some logic of synchronization. You said before that BulkCopy should not be used in transactions...
Doesn't make sense, in 10 seconds I can refresh the UI 3 times to get all data. Is the same thing.

Can we get a response after the commitment is done?

**Comment by YXMagnuMXY** [comment]
```
transaction.Commit();
// in this line of code you know that transaction commited to the server - refresh UI.
```
This will say to provider to commit all data, but will not insert instantly, and because of this - I can't refresh the UI because some data is not inserted yet! Only after 10 seconds, I should refresh the UI.
The answer for this question was - There is no such event. I really do not see any needs for such event.

Thank you.

**Comment by sdanyliv** [comment]
Oh i see, it's Database Engine related question. And each engine has it's own ways to do that.
I suggest you to create some helper class which start task that monitors count of records in one or several tables.

**Comment by sdanyliv** [comment]
It is universal solution. Handling notifications from database is real pain.

**Comment by YXMagnuMXY** [comment]
It already hurts ))
