### ISSUE TITLE
Timespan is mapped as NpgsqlTypes.NpgsqlDbType.Time instead of NpgsqlTypes.NpgsqlDbType.Interval

### ISSUE THREAD

**Issue by pawepaw** [linq2db/linq2db#1429]
Hi,

I've got problem with updating interval values if they are above 24h. They are defined as timespan in my code but for some reason in Linq2db they are mapped as NpgsqlTypes.NpgsqlDbType.Time instead of NpgsqlTypes.NpgsqlDbType.Interval. 

It fails with error: ```22008: time out of range``` for any value below 24h it's fine.

I suspect there is something wrong with mapping because when i try to update with pure Npgsql and i provide timespan as parameter it works fine and value is mapped as 'NpgsqlTypes.NpgsqlDbType.Interval'

I've tried to specify dbType with column attribute as 'interval' but it doesn't work as well.

**Comment by MaceWindu** [comment]
Yep, TimeSpan mapped to DbType.Time in linq2db which mapped to NpgsqlDbType.Time by npgsql.

As workaround you can:
- use NpgsqlTimeSpan instead of TimeSpan in your mapping
- configure TimeSpan to DataParameter mapping:
```cs
db.MappingSchema.SetConverter<TimeSpan, DataParameter>(x =>
    new DataParameter()
    {
        Value = new NpgsqlTimeSpan(x)
    });
db.MappingSchema.SetConverter<TimeSpan?, DataParameter>(x =>
    x != null ? new DataParameter()
    {
        Value = new NpgsqlTimeSpan(x.Value)
    } : null);
```

dbType used only for CreateTable API right now, so it will not affect behavior of other APIs.

**Comment by MaceWindu** [comment]
Don't close it as it is something we need to improve in future

**Comment by MaceWindu** [comment]
#1942 introduce new DataType.Interval enum field to instruct linq2db to map column to interval type

**Comment by AlexanderBlackman** [comment]
I'm getting the same error using Sqlite
> LinqToDB.Common.LinqToDBConvertException: Mapping of column 'Length' value failed, see inner exception for details
 ---> System.FormatException: String '3.00:00:00' was not recognized as a valid DateTime.

**Comment by MaceWindu** [comment]
You have `System.DateTime` type in your error message, not TimeSpan

**Comment by AlexanderBlackman** [comment]
Yes,  but the column was marked datetime, and in my dummy entry generator,  I used TimeSpan.FromHours(48) and TimeSpan.FromDays(2)  to assign to it,
 
>[Column]
>public TimeSpan Length { get; set; }

**Comment by MaceWindu** [comment]
That's not a good place to discuss it. Create new issue and provide code to demonstrate error.
