### ISSUE TITLE
Support for NodaTime types

### ISSUE THREAD

**Issue by pawepaw** [linq2db/linq2db#1432]
How to add custom mappings to support noda time types i.e map timestamp to LocalDateTime when reading from postgresql?

**Comment by MaceWindu** [comment]
You need to set converters from types, returned from npgsql to NodaTime types. Something like this:
```cs
mappingSchema.SetConverter<NpgsqlTimeStamp, LocalDateTime>(timeStamp => new LocalDateTime(???));
```

You can check this test for oracle, which does something similar: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/DataProvider/OracleTests.cs#L2090 (CustomMappingNonstandardTypeTest)

**Comment by pawepaw** [comment]
what about built in npgsql noda time support? If i register map it still doesn't work https://www.npgsql.org/doc/types/nodatime.html

**Comment by sdanyliv** [comment]
@pawepaw, show me your mapping.

**Comment by kt215** [comment]
This works for me with **linq2db** using **Postgresql 11** and referencing **Npgsql.NodaTime 4.0.5**, no converters necessary.

Remember to call `NpgsqlConnection.GlobalTypeMapper.UseNodaTime();` in `Startup.cs`
