### ISSUE TITLE
SQL Server 'NEXT VALUE FOR <SEQUENCE>' support

### ISSUE THREAD

**Issue by iouris** [linq2db/linq2db#1434]
Hi Guys,

I cant seem to find a way of getting next value for a sequence when generating an ID for a new record in the Merge operation, for SQL Server (12 and higher) ie

````
var command =
    dbContext.GetTable<Apple>()
    .Merge()
    .Using(models)
    .On((a, b) => a.Code == b.Code)
    .InsertWhenNotMatched(model => new Apple
    {
        Id = ? //need following SQL generated: NEXT VALUE FOR MySequence 
        Code = model.Code
    });
````
As per https://docs.microsoft.com/en-us/sql/t-sql/functions/next-value-for-transact-sql?view=sql-server-2017

Is there anything already available, or a workaround? Please note that the Id column is not an identity column.

Thank you!

**Comment by iouris** [comment]
found the solution:
````
    public static class LinqToDBExtensions
    {
        [Sql.Expression("next value for [{0}]", ServerSideOnly = true)]
        public static long GetNextSequenceValue(string sequenceName) => throw new NotSupportedException();
    }
````

then

````
var command =
    dbContext.GetTable<Apple>()
    .Merge()
    .Using(models)
    .On((a, b) => a.Code == b.Code)
    .InsertWhenNotMatched(model => new Apple
    {
        Id = LinqToDBExtensions.GetNextSequenceValue('MySequence')
        Code = model.Code
    });
````

SQL Server however doesnt support 'NEXT VALUE FOR' in merge operations.

**Comment by sdanyliv** [comment]
Great that you have found it by yourself :)
There is blog post that we have to convert to documentation 
http://blog.linq2db.com/
