### ISSUE TITLE
T4 template creating same Table / Associations as EF

### ISSUE THREAD

**Issue by advapiIT** [linq2db/linq2db#1446]
Hello,
I was wondering if it's possible to have the same Table / Associations naming as EF does, it would be easier to find the relations instead of the naming it's automatically created.
Is it possible?
Thanks

**Comment by sdanyliv** [comment]
@advapiIT, before loading metadata write the following code in your T4 file:
```cs
	GetSchemaOptions.GetAssociationMemberName = key => 
	{
		var name = key.OtherTable.TypeName;
		return name;
	};
```
