### ISSUE TITLE
T4 templates. Stored procedure is ignored if "table type" parameter present

### ISSUE THREAD

**Issue by shnipov** [linq2db/linq2db#1451]
I have stored procedure in MS SQL 2016 with user-defined table type parameter.
It looks like this:
``` sql
CREATE TYPE MyTableType AS TABLE
(
	MyTableId INT
)

CREATE PROC MyStoredProc (
	@Ids MyTableType READONLY
)
AS 
BEGIN
    SELECT 1 AS Result
END
```
This proc is ignored by t4 generator because of this condition:
https://github.com/linq2db/linq2db/blob/cdf43a43ce404b8746078c7aa51e3246c2fa94e8/Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs#L258

I've managed to call procedure with this code:
``` csharp
var dataTable = new DataTable();
dataTable.Columns.Add("MyTableId", typeof(int));
dataTable.Rows.Add(1);
List<object> res = this.QueryProc<object>("MyStoredProc", new DataParameter("@Ids", dataTable)).ToList();
```

Is there any chance to support this scenerio in t4 templates?

### Environment details
linq2db version: *2.5.4*
Database Server: *Sql Server 2016*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.7.2*

**Comment by MaceWindu** [comment]
Related issues: #1034, #332
