### ISSUE TITLE
Mapping Stored Procedure output to a class with complex properties

### ISSUE THREAD

**Issue by nzandy** [linq2db/linq2db#1456]
Say I have a class:

```cs
public class ClassA {
    public int Num1 {get; set;}
    public string String1 {get; set;}
    public ClassB LinkedClass {get; set;}
}
```

and another class:

```cs
public class ClassB {
    public int Num2 {get; set;}
}
```

And I have a stored procedure called GetClassA.sql that returns:
```cs
int Num1
string String1
int Num2.
```
Is there anyway I can call

```cs
return db.ExecuteProc<ClassA>("GetClassA")
```

and have the result be parsed into the ClassA object with the results correctly mapped to the nested object?

Or does the object we are parsing to need to be a "flat" object with no nesting of other objects?

Thanks,
Andy.

**Comment by MaceWindu** [comment]
To map columns to complex objects, you need to use MemberName in column mapping: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/ColumnAttribute.cs#L126

**Comment by nzandy** [comment]
Thanks for quick reply @MaceWindu . I understand how this works when I am mapping the relationships between entities and letting linq2db create the queries with joins etc.

Is this also applicable when I am directly calling a stored procedure from linq2db?

**Comment by MaceWindu** [comment]
There is no difference in this area for table, procedure or raw sql query: linq2db receive data reader with column names and map them to properties, configured using mappings.
