### ISSUE TITLE
Custom AssociationAttribute

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#1457]
Current AssociationAttribute allows to automatically build queries with joins, and that's great, but is there a way to implement custom AssociationAttribute or something else to allow to build a query with cross apply of table function?

So that the final SQL query will be like this:

```sql
DECLARE @p1 Int -- Int32
SET     @p1 = 1
DECLARE @p2 Int -- Int32
SET     @p2 = 2

SELECT 
	[t2].[Id],
	-- some other fields from t2
	[t1].[Field1],
        [t1].[Field2]
FROM
	[dbo].[SomeTable] [t2] WITH (NOLOCK)
		CROSS APPLY [dbo].[fn_someFunction]([t2].[Id], @p2) [t1]
```

and the class would be something like this:

```cs
[Table("SomeTable")]
public class SomeEntity
{
    public int Id { get; set; }
    // some other fields
    [CustomCrossApplyAssociation(/*parameters*/)]
    public SomeOtherEntity { get; set; }
}
```

I know that this can be achieved with Sql.TableFunction attribute for ITable<T> in data connection and building query like 

```cs
int someParameter = 123;
var res = db.GetTable<SomeEntity>()
               .SelectMany(x => db.FunctionCall(x.Id, someParameter)
                                             .Where(/*maybe some other needed predicates*/))
               .Select((x, y) => new 
{
   // all needed x fields
   // all needed y fields
}).ToList();
```

But that means I have to know all needed fields for select at this moment. And it would be so great to just have IQueryable<SomeEntityClass> and map it to any dto you want with automapper without any need to add joins or cross applies manually..

**Comment by sdanyliv** [comment]
@arwyl, tried to prepare sample for you using `ExpressionMethodAttribute` and new `FromSql` feature and found some weakneses that fixed this PR #1460.

You will be able to create extension method which produce CROSS APPLY automatically. Release is planned on this Thursday.

**Comment by arwyl** [comment]
@sdanyliv wow, I didn't really hope, that it can be possible=) Can you show me this example? I know, it will not work until release, but I just want to look at it

**Comment by sdanyliv** [comment]
I have created extension methods:
```cs
[Table("SomeTable")]
public class SomeEntity
{
   [Column]
   public int Id { get; set; }

   // some other fields
}

[Table("SomeOtherEntity")]
public class SomeOtherEntity
{
   [Column]
   public int Id { get; set; }

   // some other fields
}

public static class AssocaitionExtensions
{
   [ExpressionMethod(nameof(OtherEntitiesImpl))]
   public static IQueryable<SomeOtherEntity> OtherEntities(this SomeEntity entity, IDataContext db, int param)
   {
      return OtherEntitiesImpl().Compile()(entity, db, param);
   }

   private static Expression<Func<SomeEntity, IDataContext, int, IQueryable<SomeOtherEntity>>> OtherEntitiesImpl()
   {
      return (e, db, param) => db.FromSql<SomeOtherEntity>($"fn_someFunction({e.Id}, {param})");
   }
}
```
The following test query 
```cs
var query = 
   from e in db.GetTable<SomeEntity>()
   from o in e.OtherEntities(db, 2)
   select new
   {
      e,
      o
   };
```
Produces SQL
```sql
SELECT
	[e].[Id],
	[o].[Id]
FROM
	[SomeTable] [e]
		CROSS APPLY fn_someFunction([e].[Id], 2) [o]
```

**Comment by sdanyliv** [comment]
I see, sometimes i'm missing main goal. Will check how it can be done.

**Comment by arwyl** [comment]
thanks a lot!

**Comment by sdanyliv** [comment]
For clarification. How about such syntax? Trying to figure out how to do implement in best way.
```cs
[Table("SomeTable")]
public class SomeEntity
{
   [Column]
   public int Id { get; set; }

   // some other fields

   [Association(ExpressionQueryMethod = nameof(OtherImpl))]
   public SomeOtherEntity Other { get; set; }

   public static Expression<Func<SomeEntity, IDataContext, IQueryable<SomeOtherEntity>>> OtherImpl()
   {
      return (e, db) => db.FromSql<SomeOtherEntity>($"fn_someFunction({e.Id}, 2)");
   }
}
```

**Comment by arwyl** [comment]
that's perfectly fine (if the cross apply will be generated)

**Comment by sdanyliv** [comment]
> if the cross apply will be generated

I promise you ))

**Comment by arwyl** [comment]
> > if the cross apply will be generated
> 
> I promise you ))

awesome!

**Comment by arwyl** [comment]
@sdanyliv I'm trying to use the new feature, but keep getting error "Message: LinqToDB.LinqToDBException : Invalid association query. It is not possible to inline query. Can not find owner table."

```
public class SomeEntity
		{
			public int Id { get; set; }

			[Association(QueryExpressionMethod = nameof(OtherImpl), CanBeNull = true)]
			public TaskSignaturesUsersEntity Other { get; set; }

			private static Expression<Func<SomeTask1, IDataContext, IQueryable<TaskSignaturesUsersEntity>>> OtherImpl()
			{
				return (e, db) => db.FromSql<SomeOtherEntity>($"dbo.fn_SomeFunction({e.Id})").Take(1);
			}
		}
```

what am I doing wrong?

**Comment by arwyl** [comment]
it seems, that the table for SomeEntity must be in Table attribute (and not in db.GetTable().TableName() - my mistake

**Comment by MaceWindu** [comment]
@arwyl can you open new issue with example of failing query? I think we should fix it

**Comment by arwyl** [comment]
@sdanyliv  but nevertheless the query is generated using OUTER APPLY, not Cross APPLY..

**Comment by arwyl** [comment]
@MaceWindu will do

**Comment by arwyl** [comment]
@MaceWindu created #1523

**Comment by sdanyliv** [comment]
> @sdanyliv  but nevertheless the query is generated using OUTER APPLY, not Cross APPLY..

It is based on how association configured. If it CanBeNull - we generate outer apply,

**Comment by arwyl** [comment]
@sdanyliv my bad, didn't notice. Checked that - everything works great, thanks!
