### ISSUE TITLE
Exception translating GroupBy statement

### ISSUE THREAD

**Issue by TCGV** [linq2db/linq2db#146]
I just updated linq2db from version 1.0.5 to version 1.0.6 and got this exception while running some tests:

```GenericArguments[0], 'System.Linq.IGrouping`2[System.Int64,MeSeems.Business.Surveys.DataModel.AppUserSurvey]', on 'System.Nullable`1[T]' violates the constraint of type parameter 'T'.```

The constraint being violated appears to be the following:

`class GetValueOrDefaultExpressionInfo<T1> : IExpressionInfo, ISetInfo
			where T1 : struct`

And it occurs when the following code is executed using my custom **class** as the generic type T:

`var gtype    = typeof(GetValueOrDefaultExpressionInfo<>).MakeGenericType(typeof(T));`

Decided to post it here since the same GroupBy query works just fine in version 1.0.5.

Regards,
Thomas

**Comment by igor-tkachev** [comment]
Can I get example of your query?

**Comment by TCGV** [comment]
Hi,

We had a few code changes in the module where the exception was occurring, and now the tests of both 1.0.6 and 1.0.7 versions are not failing anymore.

Unfortunately I haven't taken note of my project's commit that contains the query that throws the exception.

I will schedule our Linq2Db produtction version update (from 1.0.5 to 1.0.7) for the next week, and will let you know if the exception shows up again.

Thanks!

**Comment by TCGV** [comment]
I just closed the issue since I was not able to reproduce it again.
