### ISSUE TITLE
Is it possible to use Complex Types

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#1463]
Hello.

I am wondering if it is possible to have complex types as it done in EF and EF Core. I.e. I want to have custom type `Height` as property of some POCO, which should be mapped to fields `Feet` and `Inches` in the table.

It seems that documentation is not covering this situation at all. I found some pieces of examples for one to one mapping (custom type to single field and back), but not for group of fields to be mapped to single property of custom type.

Is it doable?

**Comment by sdanyliv** [comment]
@Usaga, it is possible only in read only way. Since linq2db is not entites service framework we suggest to create linq queries which transform to DTO.

**Comment by Usaga** [comment]
I see. linq2db designed to work with "pure" persistance models, without any mimicry into DDD as "big" ORM's do.

This feature would be very useful. But your answer suits me. 

Thank you!

**Comment by Usaga** [comment]
In case someone looking for this like I did, I found an answer:

`C#
    class Height
    {
        public int? Feet { get; set; }
        public int? Inches { get; set; }
    }

    [Table("MasterName")]
    [Column("Feet", "Height.Feet")]
    [Column("Inches", "Height.Inches")]
    class MasterName
    {
        [Column("Id"), PrimaryKey, Identity]
        public int Id { get; set; }
        public Height Height { get; set; }
    }
`

This works for **both read and write**, just as I looking for. It also is possible to place attributes at Height, but only one property of Heigh might be mapped in this case, so entire class sould be annotated to use all properties of Height.
