### ISSUE TITLE
Table hints in association joins

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#1464]
Is there a way to add table hints to join expressions generated by association attribute? 
In particular I need all joins to have WITH(NOLOCK) hint

**Comment by sdanyliv** [comment]
Nope. I hope after implemntation #1457 you can set any hints that are needed.

**Comment by arwyl** [comment]
Good, thanks!

**Comment by arwyl** [comment]
@sdanyliv is there a possibility to implement something like IDataConnection.TableHints to globally add table hints to all tables (via associations, GetTable, etc)? Because even  with QueryExpressionMethod being very useful, it's very difficult to add NOLOCK to all tables in a query. Especially if there are nested associations. 
And if one needs to apply NOLOCK (or other hints) not for every query, then he has to implement two versions for every association, and that's not very good

**Comment by arwyl** [comment]
and also specifying Schema globally for dataconnection would be nice

**Comment by sdanyliv** [comment]
I'm thinking about API.
```cs
var query = from e in db.Entities
  from e2 in db.Entities
  select new {e, e2};

var query = query.WithTableHints("NOLOCK");
var materialized = query.ToArray();
```
And for every table hint will be applied.

**Comment by arwyl** [comment]
if this api will be for IQueryable<T> (not for ITable<T>) then it would be perfect

**Comment by arwyl** [comment]
@sdanyliv done
