### ISSUE TITLE
MS SQL Temproray tables in procedures. How to build

### ISSUE THREAD

**Issue by Trigun27** [linq2db/linq2db#1468]
Good day.
1) For mssql, can i use temporary tables in procedures and with what valid names?
I ran tt template and saw that procedure loaded with error. Error shows some problem with temprory table: _"Invalid object name '#Data' "_

2) Is it possible to locally build the library and add dll to my project?
I want to try debug the app when it loads metadata.

Thank you

### Environment details
linq2db version: *2.6.0*
Database Server: *MS SQL Server 16*
Operating system: *E.g. Windows 10*
Framework version: *.NET Core 2.1*

**Comment by sdanyliv** [comment]
@Trigun27, just add `Linq2db.csproj` to your solution and add reference. It always works.
But it requires VS 2017.

**Comment by sdanyliv** [comment]
With stored proc. Looks like stored proc uses temporary table which does not exists. When `SqlProvider` return stored procedures it usually executes them in special mode. So it can be problem.

**Comment by Trigun27** [comment]
> With stored proc. Looks like stored proc uses temporary table which does not exists. When `SqlProvider` return stored procedures it usually executes them in special mode. So it can be problem.

hmm. As usually i created temp tables inside the procedures and then droped it. May be this special mode can't create them?

**Comment by sdanyliv** [comment]
Sorry, I have no idea. But sometimes we noticed this behavior. Maybe debugging helps you to locate problematic stored proc.

**Comment by sdanyliv** [comment]
Try to call yourself 
```cs
DataConnection dc  = ...

dc.DataProvider.GetSchema(dc)
```

**Comment by Trigun27** [comment]
The problem was in use the temporary tables in proc.

As understood, linq2db exec procedure with the condition _CommandBehavior.SchemaOnly_. this corresponds to the instructions SET FMTONLY ON in sql.

> Because FMTONLY ON doesn't execute statements, so any statement that relies on the (non-existent) temp table will fail to parse

Therefore linq2db cannot get the resulting table schema.

Found two ways to work around the problem.
1) make a table variable inside the procedure
2) make a new type of Memory-Optimized Table.

**Comment by MaceWindu** [comment]
Adding T4 label to look at it later. Need to think how we can load schema for such procedures.
