### ISSUE TITLE
Store dynamic columns outside of current entity

### ISSUE THREAD

**Issue by apollo82** [linq2db/linq2db#1477]
Hello,
is it possible to store the dynamic columns to another dictionary <string, object> that doesn't exist in the entity itself? Our problem is that we have to use a given datastructure but have tables, that differ for each tenant. So we cannot extend the model class with a dictionary and the attribute [DynamicColumnsStore]. Or would it be possible to throw an event when a column ist encountered, that doesnt exist in the given type?

For example:

```cs
namespace OracleTest
{
    public class Customer
    {
        public string Guid { get; set; }
        public string Name { get; set; }
    }

    class Test1
    {

        public  Dictionary<string, object> MetaData { get; set; }
        public string ConnectionString { get; set; }

        public  List<Customer> GetCustomer(string name)
        {
            using (var db = new DataConnection(ProviderName.OracleManaged, ConnectionString))
            {
                Dictionary<string, string> metaDataDict = new Dictionary<string, string>();

                MappingSchema ms = MappingSchema.Default;
                var mb = db.MappingSchema.GetFluentMappingBuilder();
                mb.HasAttribute<Customer>(new TableAttribute("Customer"));
                mb.HasAttribute<Customer>(new ColumnAttribute("name", "name"));
                mb.HasAttribute<Customer>(new ColumnAttribute("guid", "guid"));
                mb.Entity<Customer>().Property(x => Sql.Property<string>(x, "AdditionalColumn"));

                var query = db.GetTable<Customer>().Where(p => p.Name == name);

                db.OnDynamicColumnEvent += OnDynamicColumnHandler;

                return query.ToList(); ;
            }

        }

        private  void OnDynamicColumnHandler(string columnName, object value)
        {
            MetaData.Add(columnName, value);
        }
    }
}
```
Thank you very much.

**Comment by apollo82** [comment]
The model layer of our application was created by another division of our company and is also used in different database contexts, like MongoDB. We want to keep our layers loosely coupled, thats why i cannot extend those classes, let alone add references to new packages.

I just wanted to ask if it would be possible to store the dynamic columns seperately from the entity, maybe as a second dedicated property to give to the MappingBuilder or the DataConnection.

Or can I maybe get the dynamic values by defining a custom converter?

Thank you.

**Comment by sdanyliv** [comment]
We can pass dynamic columns to event `OnEntityCreated`. But you have to realize that we can not store them, only read. If you need storing we have to invent other approach.

**Comment by apollo82** [comment]
That would be a good idea and already help very much. 

For insert and update, maybe it would be possible to pass a delegate, respectively a Func<string, T> that can be called when an unkown column is encountered, that fetches the columnValue T (to be inserted or updated in DB) for a given string columnName?

Thank you very much.

**Comment by MaceWindu** [comment]
@apollo82 please check #1695 - will it cover your schenario?
