### ISSUE TITLE
Stored procedure extension method can be generated in a nested class and fail to compile

### ISSUE THREAD

**Issue by MozgC** [linq2db/linq2db#1479]
Let's say we have stored procedure in a non-dbo schema, for example [Data].[MyStoredProc].

Currently linq2db's datamodel generation T4 templates will generate an extension method in a nested class. It will look something like this:

```c#
public partial class MySqlServer: LinqToDB.Data.DataConnection
{
  ...
  public static partial class DataSchema
  {
    public static partial class MySqlServerStoredProcedures
    {
      // this will not compile because extension methods are not allowed in nested class
      public static int MyStoredProc(this DataConnection dataConnections, ...)
      {
        ...
      }
    }
  }
}
```

### Environment details
linq2db version: *2.1.0*
Database Server: SqlServer 2012 & 2016

**Comment by MaceWindu** [comment]
Confirmed. In v2.2 we fixed it only for functions.

**Comment by MozgC** [comment]
Thanks MaceWindu!
