### ISSUE TITLE
Boolean not updating after passing it to the update statement

### ISSUE THREAD

**Issue by Jyasan** [linq2db/linq2db#1485]
Hi,

I'm trying to update some values in my class "Member" by passing my object to the update statement like below. Some values are of type int, string, bool,... All values are updating correctly, but not the bool value.
There is no error during the commit and I checked the values before update. They are all correct.
Any idea what's going wrong here? Am I missing something?

```
Member m = new Member();
m.Id = 1;
m.IsActive = false;
...

db.BeginTransaction();
db.Update(m);
db.CommitTransaction();
```

Kind regards

### Environment details
linq2db version: *2.6.1*
Database Provider: *MS Access*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.6.1*

**Comment by MaceWindu** [comment]
It's hard to say without mapping, but I will gues that your Id column configured to be non-updatable by:
- using Identity attribute
- using ColumnAttribute.SkipOnUpdate=true
- using ColumnAttribute.IsIdentity=true
- using ColumnAttribute.IsColumn=false
- some other mapping options possible :)

**Comment by Jyasan** [comment]
After looking throught the generated code, I do see that those colums have the Identity attribute and thus will be ignored for insert and update operation.

```
[PrimaryKey, Identity   ] public int       Id                    { get; set; } // Long
[            Identity   ] public bool      IsActive              { get; set; } // Bit
```

After some online searching I noticed that following DOES work for insert and update.

```
db.Members
   .Where(p => p.Id == 1)
   .Set(p => p.IsActive, true)
   .Update();
```

But this doesn't. Any idea to make this work? And thus by passing only the object?

```
db.BeginTransaction();
db.Update(m);
db.CommitTransaction();
```

**Comment by MaceWindu** [comment]
Ok, now it is clear.
First of all, you just need to remove Identity attribute from boolean field, as it is supported only for numeric fields by linq2db.

Difference between those two updates is that in first case you explicitly tell linq2db what fields you want to update and it will try to do it, even if it is not updateable field.
In second update there is no way to tell what fields should be updated, so this information is iferred from mapping schema. And in your case mapping schema tells that IsActive field is non-updateable, because it has Identity attribute.

**Comment by Jyasan** [comment]
Ok, I understand the problem now, but I do not know where to remove the Identity attribute.
If I remove it in the generated code, it just reappears after running the generation again.

**Comment by Jyasan** [comment]
The code looks promising as the Identity attribute is gone now.
It does add some extra "skips" and therefor does not result in the expected outcome.

`[Column(SkipOnInsert=true, SkipOnUpdate=true), NotNull    ] public bool      IsActive              { get; set; } // Bit`

Adding this two lines in the T4 template removes those skips,

```
column.SkipOnInsert = false;
column.SkipOnUpdate = false;
```

and thus results in the expected output.

`[Column,     NotNull    ] public bool      IsActive              { get; set; } // Bit`

**Comment by MaceWindu** [comment]
Thanks, you are right here

**Comment by Jyasan** [comment]
Thanks for the advice & support !
