### ISSUE TITLE
Xamarin form Can't connect to sqlite  

### ISSUE THREAD

**Issue by sutineee** [linq2db/linq2db#1487]
When connect always got this exception

> {System.TypeInitializationException: The type initializer for 'LinqToDB.Data.DataConnection' threw an exception. 
---> System.TypeLoadException: Could not load type of field 'LinqToDB.DataProvider.SqlServer.SqlServerTools:_commandBuilder' 
(0) due to: Could not resolve type with token 010000fe from typeref (expected class 'System.Data.SqlClient.SqlCommandBuilder' 
in assembly '
 Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') 
assembly:System.Data.SqlClient, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Data.SqlClient.SqlCommandBuilder member:(null)

This is my code 
`IDataProvider dataProvider = new LinqToDB.DataProvider.SQLite.SQLiteDataProvider();`

                ConnectionStringSettings connectionString = new ConnectionStringSettings
                {
                    Name = "Database",
                    ProviderName = "SQLite",
                    ConnectionString = "Data Source=" + path 
                };

                using (var db = new DataConnection(dataProvider, connectionString.ConnectionString))
                {
                    var td = db.Query<ITEM>("SELECT * FROM ITEMS");
                }

And this is linq2db version
![capture](https://user-images.githubusercontent.com/42196652/50420891-61188d80-086c-11e9-8911-ad73075f95bb.PNG)

**Comment by MaceWindu** [comment]
Ouch. Sorrry about that. Can you rollback to lin2db v2.5.4 while it is not fixed?

**Comment by sutineee** [comment]
I'm rollback to v2.5.4 and it works now.
Thank you so much.

**Comment by sutineee** [comment]
@MaceWindu  
I'm rollback lin2db to v2.5.4 it work fine on android but ios i got this exception.

> Could not load type 'Microsoft.Data.Sqlite.SqliteDataReader' from assembly 'Microsoft.Data.Sqlite, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

Please advise

**Comment by sutineee** [comment]
I fix  issue by adding this `Microsoft.Data.Sqlite.SqliteDataReader sqliteDataReader;`
It works now Thank you so much.

**Comment by sdanyliv** [comment]
Reopening to keep issue tracking.

**Comment by MaceWindu** [comment]
And when you try to debug it, exception reports assembly version, not even included in nuget...

![image](https://user-images.githubusercontent.com/1099238/50598685-d0653180-0eab-11e9-8af4-876d11d51240.png)

**Comment by MaceWindu** [comment]
For some reason it uses system.data.sqlclient 4.4.0 instead of v4.5.1+ that we need.

I don't have any idea why and not really interested in debugging this xamarin circus, so I will just try to find out why it even tries to access sqlclient code, when we need sqlite.

**Comment by zabolotnev** [comment]
Please reopen the issue. Fix works only with net standard 1.6.
With net standard 2.0 project target the error comes back.

**Comment by MaceWindu** [comment]
Not sure I understand. netstandard 1.6 never had this issue, and fix was applied to netstandard 2.0 only. Could you provide more details like exception, version and used provider?

**Comment by zabolotnev** [comment]
Steps to reproduce:
1) In VS 2017 create Xamarin XAML App (Xamarin.Forms). It creates a solution with two projects: android and netstandard 2.0
2) In netstandard project install "linq2db.SQLite.MS"
3) Open properties of android project -> Android Options ->
 - turn off "Use Shared Runtime"
 - set "Linking = Sdk assemblies only"
(this settings are for production build)
4) Start an application.
Result: 
Mono.Linker.MarkException: Error processing method: 'System.Func`2<System.String,System.String> LinqToDB.DataProvider.SqlServer.SqlServerTools::TryToUseCommandBuilder()' in assembly: 'linq2db.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Data.SqlClient.SqlCommandBuilder

If I downgrade linq2db version to 2.5.4 - it works.
