### ISSUE TITLE
query: would like to change the code in linqToDB.ttinclude

### ISSUE THREAD

**Issue by David-Mawer** [linq2db/linq2db#1489]
Hi there,

OK - so I've got a question about changing the LingToDB.ttinclude file (on my local installation): -
(SQL Server back-end)
In my system there are several stored procedures that return a few rows.
I would like the generated code the return a List instead of an an Enumerable...
e.g.
the t4 script currently generates this: -

		public static IEnumerable<ppkg_SectionFieldAddResult> ppkg_SectionFieldAdd(this DataConnection dataConnection, string @p_SectionCode, int? @p_VersionNo, string @p_FieldCode, int? @p_FieldType, int? @p_MandatoryInd, string @p_FieldDescrip, int? @p_IsDescripCol, string @p_LookupTableCode, string @p_FieldNote, string @p_DefaultValue, bool? @p_IsClaimField)
		{
			var ms = dataConnection.MappingSchema;

			return dataConnection.QueryProc(dataReader =>
				new ppkg_SectionFieldAddResult
				{
					Column1 = Converter.ChangeTypeTo<string>(dataReader.GetValue(0), ms),
				},
				"[ppkg_SectionFieldAdd]",
				new DataParameter("@p_SectionCode",     @p_SectionCode,     DataType.VarChar),
				new DataParameter("@p_VersionNo",       @p_VersionNo,       DataType.Int32),
				new DataParameter("@p_FieldCode",       @p_FieldCode,       DataType.VarChar),
				new DataParameter("@p_FieldType",       @p_FieldType,       DataType.Int32),
				new DataParameter("@p_MandatoryInd",    @p_MandatoryInd,    DataType.Int32),
				new DataParameter("@p_FieldDescrip",    @p_FieldDescrip,    DataType.VarChar),
				new DataParameter("@p_IsDescripCol",    @p_IsDescripCol,    DataType.Int32),
				new DataParameter("@p_LookupTableCode", @p_LookupTableCode, DataType.VarChar),
				new DataParameter("@p_FieldNote",       @p_FieldNote,       DataType.VarChar),
				new DataParameter("@p_DefaultValue",    @p_DefaultValue,    DataType.VarChar),
				new DataParameter("@p_IsClaimField",    @p_IsClaimField,    DataType.Boolean));
		}

I would like to generate this: -

		public static List<ppkg_SectionFieldAddResult> ppkg_SectionFieldAdd(this DataConnection dataConnection, string @p_SectionCode, int? @p_VersionNo, string @p_FieldCode, int? @p_FieldType, int? @p_MandatoryInd, string @p_FieldDescrip, int? @p_IsDescripCol, string @p_LookupTableCode, string @p_FieldNote, string @p_DefaultValue, bool? @p_IsClaimField)
		{
			var ms = dataConnection.MappingSchema;

			return dataConnection.QueryProc(dataReader =>
				new ppkg_SectionFieldAddResult
				{
					Column1 = Converter.ChangeTypeTo<string>(dataReader.GetValue(0), ms),
				},
				"[ppkg_SectionFieldAdd]",
				new DataParameter("@p_SectionCode",     @p_SectionCode,     DataType.VarChar),
				new DataParameter("@p_VersionNo",       @p_VersionNo,       DataType.Int32),
				new DataParameter("@p_FieldCode",       @p_FieldCode,       DataType.VarChar),
				new DataParameter("@p_FieldType",       @p_FieldType,       DataType.Int32),
				new DataParameter("@p_MandatoryInd",    @p_MandatoryInd,    DataType.Int32),
				new DataParameter("@p_FieldDescrip",    @p_FieldDescrip,    DataType.VarChar),
				new DataParameter("@p_IsDescripCol",    @p_IsDescripCol,    DataType.Int32),
				new DataParameter("@p_LookupTableCode", @p_LookupTableCode, DataType.VarChar),
				new DataParameter("@p_FieldNote",       @p_FieldNote,       DataType.VarChar),
				new DataParameter("@p_DefaultValue",    @p_DefaultValue,    DataType.VarChar),
				new DataParameter("@p_IsClaimField",    @p_IsClaimField,    DataType.Boolean)).ToList();
		}

So the difference is not big: -
The important thing is that I want to add "ToList()" to the QueryProc call that's returned in the procedure.

The effect is significant - it means a call to a stored procedure will always free up the connection for other uses.
This is important to me because I'm migrating from a different ORM to Linq2DB - I'm trying to avoid finding hundreds of calls to stored procedures, and adding "ToList()" at the end of each one.

So - here's what I tried to do to change the generated code.
in LinqToDB.ttinclude line 883 I saw that there's already code to add the "ToList" if the procedure has an output parameter.

	str += i + 1 == inOrOutputParameters.Count ? (_outputParameters.Count > 0 &&_ p.ResultTable != null ? ").ToList();" : ");") : ",";

so I change it to add the "ToList()" even if there were no output parameters

	str += i + 1 == inOrOutputParameters.Count ? (p.ResultTable != null ? ").ToList();" : ");") : ",";

When I re-generated the models for the project - the output of the t4 process was unchanged.

So - just to check - I comment out that row entirely, and saved all the files in the project.

The idea was that the output should change for all parameters.
Even though this would generate un-usable code, at least I would know that I'm editing the correct template. 

When I re-generate the models - then I saw no difference in the output.

So - in my mind - I'm clearly doing something wrong here (when I try to edit linqToDB.ttinclude).

Please could you let me know how I should go about changing the generated output?

Sincerely,
David :-)

### Environment details
linq2db version: *2.6.1*
Database Server: *SQL Server 2012*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.6.1*

**Comment by MaceWindu** [comment]
First of all I would say that this is not the best idea to edit those files, so I will use this issue as feature request for future releases.

If you don't see changes, it means you edit wrong file (copy of original file). Not sure how it is possible, but I would suspect it related to type of project you use: legacy project or sdk project. Nuget works with content files in different ways for those projects:
- for legacy project it copies content files to project directly
- for SDK project it references content files from nuget cache

BTW, if you edit content files for SDK project - they are edited in nuget cache and I observed issues with updating those nugets later (probably it will require nuget cache purge).

Only idea I have right now is that you have legacy project and edit local copy of this file, but for some reason, visual studio use file from nuget cache for generation.

**Comment by David-Mawer** [comment]
Thanks @MaceWindu - you're right about the legacy project with the local copy being ignored...

also - I see your point that editing the scripts can mess with future upgrades...

...so - I'll do the ".ToList()" for all my stored procedure calls that need it, then I can clean this all up later if / when the feature gets implemented.

**Comment by David-Mawer** [comment]
Awesome - thanks @MaceWindu :-)
