### ISSUE TITLE
First "database-call" via linq2db is significant slow

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#1494]
Hello community,

sorry for this (maybe) stupid question, but:

Whenever the first database call via linq2db takes place, a great deal of non-response goes by. I do not know the internals of linq2db, but I suspect that then assemblies will be created or materialized.

Is there a way to speed up this first phase? A kind of warmup?

Best
Johannes

**Comment by sdanyliv** [comment]
@jdistlr, better to profile your application and find gaps. We do not experience such problems and it can vary from provider to provider.

**Comment by MaceWindu** [comment]
I can add that I observe longer startup time in our tests for some unmanaged providers, which is not surprising, as they all just hacks to support .net with low effort

**Comment by MaceWindu** [comment]
Closing, as we are not aware of anything in linq2db, that could cause delays, so it should be provider initialization.
I would recommend to explicitly open connection by accesssing Connection property as warmup operation. Feel free to reopen if this is not the case.
