### ISSUE TITLE
Make association 1 to many by fluent api

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [linq2db/linq2db#1498]
I have this model

    public class Topic
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Text { get; set; }

        [Association(ThisKey="Id", OtherKey="TopicId")]  // Need to remove and go to fluent syntax definition
        public virtual ICollection<Message> Messages { get; set; }
    }

    public class Message
    {
        public int Id { get; set; }

        public int TopicId { get; set; }

        [Association(ThisKey="TopicId", OtherKey="Id")]
        public virtual Topic Topic { get; set; }

        public string Text { get; set; }
    }

And this query

    db.Topics.Where(x => x.Id == 6).Select(x =>
           new
           {
              Topic = x,
              MessagesIds = x.Messages.Select(t => t.Id).ToList()
           }).FirstOrDefault();

All works fine, but I am searching the way how to make 1 to many assotiation by fluent api.

If I remove attribute

    [Association(ThisKey="Id", OtherKey="TopicId")]  // This removed
    public virtual ICollection<Message> Messages { get; set; }

And do such way

    mp.Entity<Topic>().Association(x => x.Messages, (x, y) => x.Id == y.TopicId);

Query fails with this

> ArgumentNullException: Value cannot be null. Parameter name: body
> System.Linq.Expressions.Expression.Lambda(Expression body, string
> name, bool tailCall, IEnumerable<ParameterExpression> parameters)
> System.Linq.Expressions.Expression.Lambda(Expression body,
> ParameterExpression[] parameters)
> LinqToDB.Linq.Builder.ExpressionBuilder+<>c__DisplayClass94_0.<GetMultipleQueryExpression>b__1(Expression
> e) LinqToDB.Expressions.Extensions.Transform(Expression expr,
> Func<Expression, Expression> func)
> LinqToDB.Expressions.Extensions.Transform<T>(ICollection<T> source,
> Func<Expression, Expression> func)
> LinqToDB.Expressions.Extensions.TransformX(MethodCallExpression e,
> Func<Expression, Expression> func)
> LinqToDB.Expressions.Extensions.Transform(Expression expr,
> Func<Expression, Expression> func)

Maybe I write assotiation wrong? How is propper way to write 1 to many assotiation in fluent syntax?
My StackOverflow [question](https://stackoverflow.com/questions/53967568/how-to-make-association-1-to-many-by-fluent-api).

And I tried both with virtual and without on `ICollection<Message> Messages`.

**linq2db version 2.6.1 
Provider  MySql
Asp.NET Core 2.2**

**Comment by sdanyliv** [comment]
@Dmitrij-Polyanin, will check. Thanks for reporting.

**Comment by MaceWindu** [comment]
reproduced...

**Comment by MaceWindu** [comment]
Update: currently you should continue to use attributes with keys for this association, as there is no workaround for fluent mapping. Will be fixed soon
