### ISSUE TITLE
How to call QueryProc Asynchronously

### ISSUE THREAD

**Issue by Raj4git** [linq2db/linq2db#1501]
Hi 

I wanted to call queryproc method asynchronously. Is there any plan to add that functionality.
I tried to use ExecuteProcAsync but it couldn't mapped record to the complex type. But code works very well with Query Proc.

Thanks
Raj

**Comment by sdanyliv** [comment]
@Raj4git, will check what we can do here.
Can you try `FromSql` function instead?

**Comment by sdanyliv** [comment]
Also there are many overloads of `QueryToListAsync`

**Comment by Raj4git** [comment]
@sdanyliv 

Thanks for the response. FromSql isn't async. Have tried with QueryToListAsync
but it failed with the stored procedure [dbo].[getdata] is expecting parameter @statusid which is not passed

     var parms = new DataParameter[]
            {
                new DataParameter("@statusId", parameters.StatusId) { DbType = DataType.Int16.ToString() },
}

var results = await
                 this.QueryToListAsync<returnobject>("[dbo].[getdata]",
                            cancellationToken, parms);

**Comment by sdanyliv** [comment]
FromSql returns IQueryable:
```cs
FromSql($“[dbo].[getdata] {new DataParameter("@statusId", parameters.StatusId) { DataType = DataType.Int16}”)
    .ToArrayAsync();
```

**Comment by Raj4git** [comment]
@sdanyliv 

Thanks for your help. It got worked with QueryToListAsync.

**Comment by Raj4git** [comment]
closing as per prev comments

**Comment by DDSGooch** [comment]
@Raj4git how did you get it working? I've got the same issue when I try to use QueryToListAsync about it expecting a parameter which I'm passing.

Obviously ideally there would be a QueryProcAsync - I hope that gets implemented soon :)

**Comment by Raj4git** [comment]
Hello

I had to create dataparameter array and pass it to queytolistasync to get
it work.

E.g var Params = new dataparameter []
{
New dataparameter
}

Await this.querytolistasync(command, cancellation token, Params)

**Comment by DDSGooch** [comment]
@Raj4git, many thanks for getting back to me so promptly. Unfortunately I can't get that to work, as I still get the same error. However, I can get it to work with QueryProcMultipleAsync, which isn't ideal but is OK as a workaround for the moment. It's just a shame there isn't a QueryProcAsync, as I'm pretty sure that would work.

Thanks again :)

**Comment by steveadoo32** [comment]
Is there still no QueryProcAsync? I can't get an enumerable<T> from a stored procedure and I'm not sure what I am supposed to do. FromSql and QueryProcMultipleAsync don't work :(.

Just using the sync version for now.

**Comment by sdanyliv** [comment]
PR is welcome. I think it will be good contribution if someone still misses this API.
