### ISSUE TITLE
LinqException when another In-Extension is in place

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#1507]
Previously, the following use of the In Extension was always no problem:
`.Where(x => !x.IsSuspect && (x.StateId == null || x.StateId.In(5, 8)) && x.ComponentTypeId.In(1, 2, 4))`

Now I have an additional In-Extension method for local business-logic usages:
```
public static bool In<T>(this T value, params T[] list)
{
    return list.Contains(value);
}
```

Since then I always get a LinqException when generating the SQL statements from the Linq.Statement (first example).

Message:
`{"'x.StateId.In(new [] {Convert(5), Convert(8)})' cannot be converted to SQL."}`

Can I "mask" my Extension, as non-usage for the SqlBuilder?

**Comment by sdanyliv** [comment]
@jdistlr, try initialize somewhere:
```cs
	Expressions.MapMember((int v, int[] items) => In(v, items),
		(v, items) => LinqToDB.Tools.SqlExtensions.In(v, items));
```

**Comment by MaceWindu** [comment]
It is not SqlBuilder but C# compiler creates expression with reference to _your_ In method instead of correct one. If solution from @sdanyliv will not work, you will need to configure your usings to tell compiler which In should be used.
