### ISSUE TITLE
how can i receive the output parameter's value ?

### ISSUE THREAD

**Issue by zhaxg** [linq2db/linq2db#151]
LinqToDB.Data 
DataConnectionExtensions 
ExecuteReader

**Comment by feeleen** [comment]
@MaceWindu 
It seems that in latest versions member ```db.Command``` is not available anymore from ```DataConnection```, so what is the proper way to get out parameters or access the command?

**Comment by MaceWindu** [comment]
You can use [OnNextCommandInitialized](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#configuration) to save command instance for inspection after execution.

**Comment by feeleen** [comment]
> You can use [OnNextCommandInitialized](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#configuration) to save command instance for inspection after execution.

@MaceWindu 

I made a test and couldn't get parameters, this code returns 0, I expected it to be 1

```using (var conn = new CustomDataConnection("test"))
{
	DbCommand? myCommand = null;
	
	conn.OnNextCommandInitialized((args, command) =>
	{
		myCommand = command;
		return command;
	});

	var parVal = 2;

	var res = conn.GetTable<Foo>()
		.Where(x=> x.Id == parVal)
		.ToList();

	Console.WriteLine(myCommand?.Parameters.Count);
}
```

Am I doing it wrong?

**Comment by MaceWindu** [comment]
I see two options:
- command doesn't use parameters (e.g. parameters not supported or disabled for context)
- command is disposed after query and provider could clean parameters collection on disposal (depends on behavior of database provider you use)

What are you trying to achieve? If you want to have an access to input parameters, you should extract required parameters data in `OnNextCommandInitialized` delegate.

**Comment by jods4** [comment]
It would help to see what you're trying to achieve. There's no output parameter in that simple SELECT you've shown.

Generally speaking it's not a good idea to peek at linq2db parameters as they may not always match your expectations.
For various reasons there can be more parameters, or less, in a different order, with different names than you would expect.

Also I can't think of a "normal" LINQ situations where linq2db is going to create an OUTPUT parameter for you. Again, having a specific use-case would help answer.

If you're executing a stored procedure (table-valued or not), then it's easy to access return values and output parameters (through `DataParameter` instances), plenty of examples in those tests: https://github.com/linq2db/linq2db/blob/6bb5d8baaff795e44a38af7dc63019b38a346652/Tests/Linq/Data/ProcedureTests.cs

If you execute SQL directly, you can also have full control over `DataParameters`, see this test for example: 
https://github.com/linq2db/linq2db/blob/6bb5d8baaff795e44a38af7dc63019b38a346652/Tests/Linq/Linq/FromSqlTests.cs#L133

**Comment by feeleen** [comment]
> There's no output parameter in that simple SELECT you've shown.

In my sample with ```OnNextCommandInitialized``` I just tried to see if there's any available common parameters, not out parameters.
It's just a simple test to see how it work, but unfortunately command parameters are empty

**Comment by feeleen** [comment]
I migrate some old legacy code from 3.6.0 to 5.3.2, there was usage of ```db.Comand``` 

Finally I rewrote that piece of code in another way and get it to work, 
but anyway it's strange that Command.Parameters collection is empty in case of ```OnNextCommandInitialized```

**Comment by feeleen** [comment]
> What are you trying to achieve? If you want to have an access to input parameters, you should extract required parameters data in `OnNextCommandInitialized` delegate.

Ok, seems that is the only option

**Comment by feeleen** [comment]
@MaceWindu 

> You can use [OnNextCommandInitialized](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#configuration) to save command instance for inspection after execution.

```using (var conn = new CustomDataConnection("test"))
{
	DbParameterCollection? param = null;
	conn.OnNextCommandInitialized((args, command) =>
	{
		param = command.Parameters;
		Console.WriteLine(param?.Count);
		return command;
	});

	var parVal = 2;

	var res = conn.GetTable<Foo>()
		.Where(x=> x.Id == parVal)
		.ToList();

	Console.WriteLine(param?.Count);
}
```

Result is 
1
0

so there is no chance to get command's parameters after query completes :(

**Comment by MaceWindu** [comment]
You need to save parameters (not parameter collection) in `OnNextCommandInitialized` like it's done in referenced example as after query execution command is disposed and command disposal clears parameters collection
