### ISSUE TITLE
MySql Authentication method not supported 

### ISSUE THREAD

**Issue by crucialize** [linq2db/linq2db#1511]
It seems that linq2db doesn't support the new authentication method in mysql 8.0.

```
Exception message: Authentication method 'caching_sha2_password' not supported by any of the available plugins.
```

I've tested:
Platform: .net core and .net framework.   .Net framework works fine, while .net core 2.0, 2.1 both have the problem.
Mysql Server: Mysql8.0.13 on my PC, and Mysql 8.0.12 in docker on my cloud server(ubuntu 16.04)

### Steps to reproduce
Just connect to a mysql 8.0 server, and do something like:

```c#
using (var db = new TestDB())
			{
				db.Students.Any();
			}
```

### Environment details
linq2db version: *2.6.2*
Database Server: *Mysql8.0.12 Mysql8.0.13*
Database Provider: *I don't know where to find*
Operating system: Windows 10
Framework version: .net core 2.0, 2.1

**Comment by crucialize** [comment]
Well, my problem was solved by installing nuget package 'Mysql.Data'.

**Comment by MaceWindu** [comment]
Right, you need to install/update Mysql.Data v8.0.11+ to work with MySQL 8.
Also in next (v2.7) release we will add MySqlConnector support (you can try it with linq2db 2.7 preview from myget)
