### ISSUE TITLE
How to create DataContext from string ProviderName?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [linq2db/linq2db#1513]
I am trying to make my `DataBaseFactory`
And `GetContext` method, must return `DataContext`.

But how to create `DataContext`, from `connectionString` and `string` `providerName`?
I want to configure `providerName` and `connectionString` from settings file. So i have string of `providerName`.

But there is no `DataContext` constructor geting `providerName`?

**Comment by sdanyliv** [comment]
You are looking for this one?
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L103

**Comment by Dmitrij-Polyanin** [comment]
This is DataConnection. I need DataContext.

**Comment by sdanyliv** [comment]
Maybe this one can help you to pass appropriate data provider to DataContext.
https://github.com/linq2db/linq2db/blob/835f8cd4c18a913dfece871dcdd4102b34aa3146/Source/LinqToDB/Data/DataConnection.cs#L712

Usually we do not use DataContext and possibly missed usability points.
