### ISSUE TITLE
Is there easy way to set ConnectionString and ProviderName by json file in Asp.Net Core 2.2?

### ISSUE THREAD

**Issue by DmitrijOkeanij** [linq2db/linq2db#1514]
Is there any way to set `ConnectionString` and `ProviderName` from Json config and easy bind it to DataBaseConnection, Factory, Context and so on?

**Comment by MaceWindu** [comment]
Standard way is to implement settings provider interface [ILinqToDBSettings](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Configuration/ILinqToDBSettings.cs) and assign provider instance to `DataConnection.DefaultSettings` on startup.

We don't have any built-in provider for .net core right now, only app.config-based [LinqToDBSection](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Configuration/LinqToDBSection.cs), which is not available for .net core.

We have issue for this (#1051) but nobody took it yet (PRs welcome)

**Comment by MaceWindu** [comment]
I will add this issue to next release milestone to track .net core configuration issues. We ignored them for too long.

**Comment by Dmitrij-Polyanin** [comment]
Thanks!

**Comment by hahn-kev** [comment]
@MaceWindu I'd like to try and pick this up. Should I try and model it after how EF is setup in Asp.net core?

**Comment by MaceWindu** [comment]
Having EF-like setup will definitely be a good start.

**Comment by MaceWindu** [comment]
@hahn-kev, I've sent you invite to our slack chat. Feel free to join

**Comment by yuanxiongwei** [comment]
need

**Comment by yuanxiongwei** [comment]
Whether it can be implemented first
