### ISSUE TITLE
T4 Schema name should be escaped

### ISSUE THREAD

**Issue by j-dc** [linq2db/linq2db#1516]
I have an informix database on a linux system.
Users can log in with their windows domain name.

Schema's in informix are based upon the users login.
So I have a schema with this name:  "ABC\userName"

The T4 generates invalid code:
[Table(Schema="ABC\userName", Name="theTable")]
	public partial class TheTable

This could easily be fixed by generating this code: 
[Table(Schema=@"ABC\userName", Name="theTable")]

### Environment details
linq2db version: *2.6.2*
Database Server: *Informix 11.70*
Framework version: *.NET Framework 4.6.2*

**Comment by MaceWindu** [comment]
We already have code for it in https://github.com/linq2db/linq2db/pull/1393
Looks like string literals code should be extracted to 2.x release
