### ISSUE TITLE
oracle refcursor parameter bug

### ISSUE THREAD

**Issue by zhaxg** [linq2db/linq2db#152]
dataparameter.binary ->  oracledbtype.refcursor ???
please test it,  thank you !

i modified it as this :
                _setVarBinary = GetSetParameter(connectionType, "OracleParameter", "OracleDbType", "OracleDbType", "RefCursor");//Blob-> RefCursor  by zhaxg

LinqToDB.DataProvider.Oracle.OracleDataProvider  OnConnectionTypeCreated

**Comment by igor-tkachev** [comment]
How can I reproduce this bug?

**Comment by sdanyliv** [comment]
Fixed in #555
