### ISSUE TITLE
Documentation typo: "intert"

### ISSUE THREAD

**Issue by Arithmomaniac** [linq2db/linq2db#1525]
https://github.com/linq2db/linq2db/blob/b182372bc62367a134670212d0ae92df3c2f9b30/Source/LinqToDB/Data/DataConnectionExtensions.cs#L1425
https://github.com/linq2db/linq2db/blob/b182372bc62367a134670212d0ae92df3c2f9b30/Source/LinqToDB/Data/DataConnectionExtensions.cs#L1447

**Comment by sdanyliv** [comment]
@Arithmomaniac, i can’t handle what do you mean.

**Comment by Arithmomaniac** [comment]
The third word in each comment is "intert" instead of "insert".

**Comment by sdanyliv** [comment]
Oh, i see, thanks. Fixed.
