### ISSUE TITLE
Sap Hana support

### ISSUE THREAD

**Issue by fraillt** [linq2db/linq2db#154]
Hi,

First I would like to thank Igor Tkachev for wonderful project, and i would like to contribute to it as well.
I would like to offer to merge my branch in master, for Sap Hana support.
I was working on my branch for 5 months now, and we're fully using this library for two big projects now, and I would like to share my work, hopefully there will be more users in the future, because there is no other alternatives for those that use Hana.
I have merged linq2db and t4models projects with master branches recently.
If you`re interested in this, and need any assistance regarding Hana, i would gladly help you as much as I can.

Sincerely yours,

**Comment by fraillt** [comment]
Hi,
I can't give you access to Hana server... and in order to install Hana db you need to be SAP partner.
But as there is amazon web services that supports Hana, not sure if it has trial version, but you can find more here http://aws.amazon.com/sap/saphana/

Hope that helps

**Comment by igor-tkachev** [comment]
I have merged your pull request. I still can not test it. Please test it and let me know if there are any problems.

**Comment by jogibear9988** [comment]
There seems to be a free SAP Hana Database: http://saphanatutorial.com/sap-hana-cloud-platform-free-hana-cloud-trial-account/

**Comment by igor-tkachev** [comment]
Yes, please.

**Comment by igor-tkachev** [comment]
Still, how can get dev version of SapHana. I have registered on SAP site, but it's really complicated and  confusing to get the access.

**Comment by fraillt** [comment]
I haven't tried to register because my company is SAP partners, but have you tried [this] (http://scn.sap.com/docs/DOC-55588). 
Unfortunately I can't give you access to our SAP Hana server(s)...
