### ISSUE TITLE
Way of mapping special double conditions (NaN, Inf, ... ) to null?

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#1542]
Everytime I insert doubles (Model) to nullable floats (SQL Server Column) via BulkCopy, I get an exception from BulkCopy (OLE DB provider 'STREAM' for linked server '(null)' returned invalid data for column '[!BulkInsert].valueDouble'). I tracked this issue down to the special conditions of double (NaN, Inf ... ).

Is there a way, linq2db can map this double-conditions to null?

**Comment by MaceWindu** [comment]
Taking into account that we use mapping schema during bulk copy value retrieval, it should be possible to do by setting value converter in your mapping schema. Something like this:
```cs
mappingSchema.SetConvertExpression<double, DataParameter>(d => new DataParameter() {DataType = DataType.Double, Value = double.IsNaN(d) || double.IsInfinity(d) ? null : d });
```
