### ISSUE TITLE
no Update Method on db

### ISSUE THREAD

**Issue by fopsdev** [linq2db/linq2db#1548]
![image](https://user-images.githubusercontent.com/5448300/51439184-d08c6c00-1cb6-11e9-9c01-e2ea5b38785f.png)

### Steps to reproduce
Install .net core 2.2 sdk
Create a fresh asp.net wepapi project
Install linqtodb (nuget)

### Environment details
linq2db version: *2.6.2*
Database Server: *SqlServer 2016*
Database Provider: *SqlServer*
Operating system: *Windows 10*
Framework version: *.NET Core 2.2*

**Comment by sdanyliv** [comment]
Do you have appropriate using?
```cs
using LinqToDB;
```

**Comment by MaceWindu** [comment]
I will add usings to readme

**Comment by fopsdev** [comment]
Oh, yeah. Using was missing :)
Good idea to add it to the readme
