### ISSUE TITLE
[T4 template] empty lines added into output from BeforeGenerateModel()

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#1550]
The code in [GenerateModel()](https://github.com/linq2db/linq2db/blob/4b1c5ab13b7e78de575cec58c43309b135627816/Source/LinqToDB.Templates/T4Model.ttinclude#L17-L20) trims output after `BeforeGenerateModel()` call

As a result, if there's any output in `BeforeGenerateModel` the output file contains emtpy lines taken from `<#include ...>`. Example:
```cs







<output here>
//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
```
**Proposed solution:** 
Perform the `if ... GenerationEnvironment.Length = 0;` check before `BeforeGenerateModel` call.

### Environment details
linq2db version: *2.6.1*
Database Server: *MS SQL 2017*
Database Provider: *System.Data.Sql*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.7.2*

**Comment by MaceWindu** [comment]
I think better to put output from BeforeGenerateModel  after header
