### ISSUE TITLE
Linq2Db and string.join()

### ISSUE THREAD

**Issue by 80LevelElf** [linq2db/linq2db#1559]
I am using Linq2db in my big query with subqueries.
At the one place inside it, I want to use string.Join():

    ...
    FullPath = string.Join(" -> ", GetPathQuery(db, c.Id).Select(pi => pi.Name))
    ...
    
But I have received an exception:

> LinqException: 'Join(" -> ", value(RI.DAL.Categories.AdminCategoryPreviewDAL).GetPathQuery(value(RI.DAL.Categories.AdminCategoryPreviewDAL+<>c__DisplayClass4_0).db, c.Id).Select(pi => pi.Name))' cannot be converted to SQL.

I use Postgre SQL and it has the `concat_ws` function which is perfect for me. So I try to use it:

    [Sql.Expression("concat_ws({1}, {0})")]
    public static string JoinAsString(this IQueryable<string> query, string separator)
    {
        return string.Join(separator, query);
    }
    
    ...
    FullPath = GetPathQuery(db, c.Id).Select(pi => pi.Name).JoinAsString(" -> ")
    ...

But I was failed with the same exception.
So how to make it work?

**Environment details**
linq2db version: 2.6.3
Database Server: PostgreSQL 10
Database Provider: standard provider "PostgreSQL.9.5"
Operating system: Windows 10
Framework version: .Net core 2.1

**Comment by 80LevelElf** [comment]
Even in case of the GetPathQuery method will be out of the main query I will have a problem with string joining:

```
var pathQuery = GetPathQuery(db);

...
FullPath = string.Join(" -> ", pathQuery.Where(c1 => c1.RootCategoryId == c.Id).Select(c1 => c1.Name));
...
```

Also, the [solution with Aggregate ](https://stackoverflow.com/questions/54391465/linq2db-and-string-join/54391510?noredirect=1#comment95595087_54391510) is not working too:
```
...
FullPath = pathQuery.Where(c1 => c1.RootCategoryId == c.Id).Select(c1 => c1.Name)
                        .Aggregate(string.Empty, (results, nextString) => results + " -> " + nextString)
...
```

**Comment by igor-tkachev** [comment]
I think we need to add support for string.Join. Sql Server 2017 got the similar function STRING_AGG as well.

**Comment by 80LevelElf** [comment]
Could you advise some temporary possible solution at this moment, please?

**Comment by sdanyliv** [comment]
Will check tomorrow, strange why it is not working. 
BTW for `JoinAsString` try to set `IsAggregate = true` in `Sql.Expression` attribute.

And final aggregates should have injecting function in Expression Tree, like here:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.Analytic.cs#L420

**Comment by igor-tkachev** [comment]
BTW, this is aggregate function, so you should use set IsAggregate =flag to  true when you define your Sql.Function.

**Comment by igor-tkachev** [comment]
A little bit late :)

**Comment by 80LevelElf** [comment]
@sdanyliv thanks!
I have already used the method 'StringAggregate' from your PR and it's work!

**Comment by dejanberic** [comment]
@80LevelElf Can you please elaborate how did you end up creating string.Join functionality using 2.6.4 version of Linq2DB?

**Comment by dejanberic** [comment]
I ended up using this extension method since I am using 2.6.4 version of linq2db and SQL Server 2017.

`[Sql.Extension("STRING_AGG({source}, {separator}){_}{aggregation_ordering?}", IsAggregate = true, ChainPrecedence = 10)]
        public static string AggregateString(
            [ExprParameter] this IEnumerable<string> source,
            [ExprParameter] string separator)
        {
            return string.Join(separator, source);
        }`
