### ISSUE TITLE
Incorrect cross apply for QueryExpressionMethod

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#1560]
Entities
```cs
	public class SomeTableType
	{
		public int Value { get; set; }
	}

	[Table("FewNumberEntity")]
	public class FewNumberEntity
	{
		[Column]
		public int Id { get; set; }
		[Column]
		public int UserId { get; set; }
	}

	[Table("LargeNumberEntity")]
	public class LargeNumberEntity
	{
		[Column]
		public int Id { get; set; }

		[Association(QueryExpressionMethod = nameof(GetSomeValue), CanBeNull = false)]
		public SomeTableType SomeValue { get; set; }

		private static Expression<Func<LargeNumberEntity, IDataContext, IQueryable<SomeTableType>>> GetSomeValue()
		{
			return (t, db) => db.FromSql<SomeTableType>($@"SELECT 
	COUNT(*) as [Value] 
FROM 
	[dbo].[SomeTable] [st] WITH(NOLOCK) 
WHERE 
	[st].[LargeNumberEntityId]={t.Id}");
		}
	}
```

Usage
```cs
[Test]
public void Test()
{
	using (var db = GetDataConnection())
	{
		var tasksQuery = db.GetTable<LargeNumberEntity>();

		var filtered = db.GetTable<FewNumberEntity>().Where(x => x.UserId == 123);

		var final = filtered.InnerJoin(tasksQuery, (x, y) => x.Id == y.Id, (x, y) => y);

		var q = final.Select(x => new
		{
			x.Id,
			x.SomeValue.Value
		});

		Console.WriteLine(q.ToString());
	}
}
```

SQL:
```sql
SELECT
	[y].[Id],
	[a_SomeValue].[Value]
FROM
	[FewNumberEntity] [x]
		INNER JOIN [LargeNumberEntity] [y]
			CROSS APPLY (
				SELECT 

					COUNT(*) as [Value] 

				FROM 

					[dbo].[SomeTable] [st] WITH(NOLOCK) 

				WHERE 

					[st].[LargeNumberEntityId]=[y].[Id]
			) [a_SomeValue]
		ON [x].[Id] = [y].[Id]
WHERE
	[x].[UserId] = 123
```

As we can see, there is join Table cross apply () on ...
and if there are many records in Table, all of them are cross applied

why is the query built this way and not like this:
join Table on ...
cross apply ()
?

this way few records from FewNumberEntity will be joined to LargeNumberEntity and the result (also few records) will be cross applied

### Environment details
linq2db version: *2.6.4*
Operating system: *E.g. Windows 10*
Framework version: *.NET Framework 4.7.2*

**Comment by arwyl** [comment]
and one more question: why are there extra empty lines in cross apply? Maybe my formatting is wrong in a way?

**Comment by arwyl** [comment]
also same query building can be repeated (in my case) if there is cross applying some fromSql with permissions to final query
so that's not only QueryExpressionMethod problems

**Comment by sdanyliv** [comment]
Will check thanks. I think i know where is problem and how to fix that.

**Comment by arwyl** [comment]
and normal Associations (with join) work fine
if the code is changed to 
```
[Table]
		public class SomeTableType
		{
			[Column]
			public int Value { get; set; }
			[Column]
			public int Id { get; set; }
		}
...
[Association(ThisKey = "Id", OtherKey = "Id")]
			public SomeTableType SomeValue { get; set; }
```

the resulting query is correct
```
SELECT
	[y].[Id],
	[a_SomeValue].[Value]
FROM
	[FewNumberEntity] [x]
		INNER JOIN [LargeNumberEntity] [y] ON [x].[Id] = [y].[Id]
		LEFT JOIN [SomeTableType] [a_SomeValue] ON [y].[Id] = [a_SomeValue].[Id]
WHERE
	[x].[UserId] = 2118
```

**Comment by arwyl** [comment]
@sdanyliv thanks a lot!

**Comment by sdanyliv** [comment]
@arwyl, looking at your query again. I can not find problem here. Looks like generated query is correct in this situation. 

You have `JOIN` to `LargeNumberEntity` and then want to get its value `SomeValue` which can be obtained only by `CROSS APPLY`.

**Comment by arwyl** [comment]
@sdanyliv I don't mind cross apply, I'm talking about it's positioning

This is current result
```sql
SELECT
	[y].[Id],
	[a_SomeValue].[Value]
FROM
	[FewNumberEntity] [x]
		INNER JOIN [LargeNumberEntity] [y]
			CROSS APPLY (
				SELECT 

					COUNT(*) as [Value] 

				FROM 

					[dbo].[SomeTable] [st] WITH(NOLOCK) 

				WHERE 

					[st].[LargeNumberEntityId]=[y].[Id]
			) [a_SomeValue]
		ON [x].[Id] = [y].[Id]
WHERE
	[x].[UserId] = 123
```

its execution time is about 13 seconds in my case

this is how I think it should be:

```sql
SELECT
	[y].[Id],
	[a_SomeValue].[Value]
FROM
	[FewNumberEntity] [x]
		INNER JOIN [LargeNumberEntity] [y] ON [x].[Id] = [y].[Id]
		CROSS APPLY (
			SELECT 

				COUNT(*) as [Value] 

			FROM 

				[dbo].[SomeTable] [st] WITH(NOLOCK) 

			WHERE 

				[st].[LargeNumberEntityId]=[y].[Id]
		) [a_SomeValue]		
WHERE
	[x].[UserId] = 123
```

Its execution time is 0 seconds in my case..

**Comment by sdanyliv** [comment]
@arwyl, oh i see. Moment.

**Comment by arwyl** [comment]
I may be mistaken, but I think, that in the first case sql executes it like 
"take few records. Now take a lot of records and cross apply to them some calculations. Now join the to sets together and return result"

and in the second case it's working like "take few records, then join them to a lot of records, but with primary key condition it's fast, now add some calculations to resulting few records and return result"

**Comment by sdanyliv** [comment]
@arwyl, fixed. Wait for upcoming bug-fix release in several days.
