### ISSUE TITLE
Modular site architect with linq2db

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [linq2db/linq2db#1565]
I am thinking about modular system for my site.

I have controller action with such code

```
return Json(db.SomeTable.Select( x=>
    new {
        // some props
        Id = x.Id
        // ...
    }
  ) );
```

And I want to make modules extend function with some additional data results

```
return Json(db.SomeTable.Select( x=>
    new {
       // some props
       Id = x.Id
       // ...
       DataFromModules = /* Some Modules Extensions methods */
   }
  ) );
```

But is it possible, and if is how?

**Comment by sdanyliv** [comment]
It's not clear for me from this part.
`DataFromModules = /* Some Modules Extensions methods */`

Try to write some API samples.

**Comment by Dmitrij-Polyanin** [comment]
```
abstract class MyModule {
   public virtual object GetAdditionalData(Entity entity) {
      // Some code
   } 
}
```

In Controller Action
```
MyModule[] modules = someArray;

return Json(db.SomeTable.Select( x=>
    new {
       // some props
       Id = x.Id
       // ...
       DataFromModules = /* Some code that returns array based on all GetAdditionalData from all modules, but I don't know syntax how can it may be done  */
   }
  ) );
```

Idia is to place in result all additional data from all modules as array of objects `DataFromModules`.

**Comment by Dmitrij-Polyanin** [comment]
There is Main Core module and its code.
And some additional Get code from modules.

I am searching a way to combine it in one db request. To get main Core module data and all others modules.

I am not sure that this is possible, but interesting is or not.

If not I will get  additional data by separate requests with `foreach(modulesArray)` and inject it in Json result.

**Comment by sdanyliv** [comment]
It will be a pain even for me. 
In which scenarios do you plan to use such technique? How many such queries?

**Comment by Dmitrij-Polyanin** [comment]
Ok. Clear. Its not a problem. I will do with separate requests.

Making site engine with modular system. Likes, favorites and many more will be modules.
For example to get Forum Thread, and in additional Likes for the thread posts.

On real site it can be 0-4 modules on each main request.

**Comment by sdanyliv** [comment]
If you ensure that it will be requests one-to-one in plugins, it may be possible. I mean that plugins just add LEFT JOIN to other tables for data.
Not easy. Better to write solution without this and then you will find regularity.

**Comment by sdanyliv** [comment]
Closing for now.
