### ISSUE TITLE
[Question] How to use UTC time on the server

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#1577]
There is a need to use server-side timestamps for distributed locking and consistency. Difference in the clocks of the machines accessing the database is not tolerable so the best approach is to use the clock of the database machine.

I am aware that there are `Sql.GetDate()` and `Sql.CurrentTimestamp`, however, these properties return the local server time. Is there a way to access the UTC server time (e.g. `getutcdate()` on SQL Server) ?

### Environment details
linq2db version: *2.6.3*
Database Server: *SQL Server 2014*
Operating system: *Windows 10*
Framework version: *.NET Core 2.2*

**Comment by JechoJekov** [comment]
I ended up creating a small class:

```C#
    /// <summary>
    /// Extended Linq2DB functions.
    /// </summary>
    public static class SqlExt
    {
        /// <summary>
        /// Returns the current UTC date/time.
        /// </summary>
        /// <returns></returns>
        [Sql.Function(ProviderName.SqlServer, "GetUtcDate", ServerSideOnly = true, CanBeNull = false)]
        public static DateTime CurrentTimestampUtc => throw new LinqException($"'{nameof(CurrentTimestampUtc)}' is server side only property.");
    }
```

Would be nice to have this in the built-in `Sql` class though. I can make it compatible with other providers if this would help.

**Comment by sdanyliv** [comment]
@JechoJekov, yes prepare please PR with these functions for other providers. 
Create `Sql.DateTime.cs` and and add partial implementation of static `Sql` class.
Thanks!
