### ISSUE TITLE
Optimize sql plans caching with varbinary size

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#1578]
Same issue as #989 _Optimize sql plans caching with varchar\nvarchar size_ but for `varbinary(max)`.

### Environment details
linq2db version: *2.6.3*
Database Server: *SQL Server 2014*
Database Provider: *SQL Server 2012*
Operating system: *Windows 10*
Framework version: *.NET Core 2.2*

**Comment by sdanyliv** [comment]
@JechoJekov, any samples? We have already fixed issue that you have mentioned.

**Comment by sdanyliv** [comment]
Closing for now. Expecting more information.
