### ISSUE TITLE
Question. Postgres. Default nextval

### ISSUE THREAD

**Issue by lobster2012-user** [linq2db/linq2db#1579]
Hi!

1. Why is the default value not used for a column with identity type? (checking...)
2. Why is `currval` being called, although you can use the `returning id`?

### Environment details
Database Provider: *Npgsql*

**Comment by MaceWindu** [comment]
I would say - probably because it was implemented like that from start and nobody asked before.

Need to check pgsql documentation, but I suspect default value will not work when:
- it is not configured in database
- user want to use values from other sequence

**Comment by lobster2012-user** [comment]
@MaceWindu 
We can use `default` instead of `nextval` (Which is the default). 
If user wants to use another sequence, then he can override the SequenceNameAttr


In the current implementation, the default sequence with a non-standard name will not be used. Replacing the above would partially solve this problem.
There will be a problem with the generation of the database from the generated model, for this you will still have to extract the sequence name with the schema.

**Comment by MaceWindu** [comment]
makes sense
