### ISSUE TITLE
Performance Issue with current Version (GetEntityDescriptor)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1585]
We use linq2db with our own MappingSchema wich we use when we create a DataConnection as a Paremeter.

It seems that the GetEntityDescriptor call always creates a new EntityDescriptor, wich takes most of our time. Descriptors should be cached in MappingSchemaInfo, but maybe that is also always recreated?

See Our perf. Profile:

![image](https://user-images.githubusercontent.com/364896/52217763-6ae4d600-2899-11e9-89f2-16a49d5a3d0a.png)
![image](https://user-images.githubusercontent.com/364896/52217783-73d5a780-2899-11e9-9bb4-1dc6a3d748dd.png)

**Comment by sdanyliv** [comment]
@jogibear9988, it is regression? If you create MappingSchema each time, it for sure will recreate EntityDescriptor.

**Comment by jogibear9988** [comment]
I do not create the Mapping Schema each time. Mine (the one I hand over to DataConnection) is fix, but the combined one linq2db creates not

**Comment by sdanyliv** [comment]
@jogibear9988, it is hard to understand what happened. Just debug and tell for us about findings.

**Comment by jogibear9988** [comment]
I've created a test...

**Comment by jogibear9988** [comment]
Maybe this is relevant: https://github.com/linq2db/linq2db/issues/615#issuecomment-290966550

**Comment by jogibear9988** [comment]
So maybe we did the cache of the entity descriptors at the wrong place...

**Comment by jogibear9988** [comment]
@sdanyliv is it my error? or should my test work?

**Comment by sdanyliv** [comment]
@jogibear9988, I don't know. I'm really busy for now with fixing other issues. It should be easy for you to understand what happened here. 
One comment, our tests has to be written in model way way. There is `SQLiteDataSources` attribute for tests, `GetDataConnection` for retrieving connection, `CreateLocalTable` for creating temporary table.

**Comment by jogibear9988** [comment]
I think test does not need a database at all. I wanted to know, what is our prefered behavior?
We support external mapping schemas, and dataconnection is a short lived object, so our cacheing is wrong? or am I wrong? Or is getentitydescriptor not expensive?

**Comment by sdanyliv** [comment]
@jogibear9988, i can fix that but i need merging this PR before starting implementation.

**Comment by sdanyliv** [comment]
I have already prepared fix using MemoryCache. Please review.
