### ISSUE TITLE
Table named "Relationships"

### ISSUE THREAD

**Issue by darestov** [linq2db/linq2db#1586]
Hello,

I created my database (MS Sql)  with a table named "Relationship". After running T4 templates, the generated code failed to compile:

![image](https://user-images.githubusercontent.com/5158873/52227566-edcd5700-28c0-11e9-9592-4e35f54ed515.png)
In this case, the name of the enum `LinqToDB.Mapping.Relationship` conflicts with the generated class `Relationship`. I found these lines in the `linqtodb.ttinclude` file and changed them to use full name of the enum:

```c#
switch (key.AssociationType)
{
	case AssociationType.OneToOne  : aa.Parameters.Add("Relationship=LinqToDB.Mapping.Relationship.OneToOne");  break;
	case AssociationType.OneToMany : aa.Parameters.Add("Relationship=LinqToDB.Mapping.Relationship.OneToMany"); break;
	case AssociationType.ManyToOne : aa.Parameters.Add("Relationship=LinqToDB.Mapping.Relationship.ManyToOne"); break

}

```

However, it did not affect the generated code, it was still the same, with errors. 
Can anyone please suggest a workaround (**besides renaming my table**), or maybe a patch is needed? As a generic rule, generated code should always use fully qualified names.

Thanks.

**P.S.:** Ok I got it, I just referenced *.tt files from my project instead of from `/packages` directory, and the generation went alright. But still, can the generation be fixed to use full names?

### Environment details
linq2db version: *2.6.4*

**Comment by sdanyliv** [comment]
@darestov, you can find your table in T4 and rename mapped class.
Before generating model. Place something like this:
```cs
Tables["Relationship"].Name = "RealtionshipTable";
```
