### ISSUE TITLE
MappingSchema.EntityDescriptorCreatedCallback should be static

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1592]
Right now MappingSchema.EntityDescriptorCreatedCallback is defined per-MappingSchema instance, which makes it non-trivial to configure, because user should attach callback to current data connection mapping schema instance.

Attaching it to DefaultSchema will not work, because it is not used directly - we copy schemas from it to actual mapping schema, used by connection in MappingSchema constructor.

There are several ways to fix it:
- make callback application-wide static, so it will be called always and then users could inspect mapping schema parameter, if he wants to perform action only for specific schemas
- derive callbacks when we aggregate mapping schemas. Not a big fan of it - in case of multiple schemas having callbacks we need to call all of them
- move callback to DataConnection

I would prefer first approach.

Also see: https://github.com/linq2db/linq2db/issues/1074#issuecomment-460057547

### Environment details
linq2db version: *2.6.4*

**Comment by sdanyliv** [comment]
I think first one is good until we implement new configuration mechanism.
@jogibear9988, how do you think, as i remember it was your PR with such callback?

**Comment by jogibear9988** [comment]
I really don‘t like static.
Cause we use linq2db for different libs in our code wich can access different customer databases. And so a complete different part of the application (wich is maybe developed by someone different), gets callbacks wich it shouldn‘t see

**Comment by jogibear9988** [comment]
I think as a first fix it should work, but we should think about a configuration without static

**Comment by jogibear9988** [comment]
Maybe we could call the callback for each child mappingschema? i can take a look

**Comment by sdanyliv** [comment]
> but we should think about a configuration without static

I'm already working on this. But it needs time.

**Comment by MaceWindu** [comment]
I've already asked @GonzoSpire to work on it

**Comment by jogibear9988** [comment]
If we create a static one we shouldn't change the current Behavior, we should introduce a new static one.
If we don't it will be a breaking change

**Comment by sdanyliv** [comment]
For do not break change, we have to process items hierarchcally by schemas. Then we have to deprecate this method after implementing some kind of schema interceptor.

I can not miss feeling that we have implemented something in wrong way.
