### ISSUE TITLE
Pack.bat does not work

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#1595]
It is not possible to compile and create nuget packages from command line.

`
Attempting to build package from 'linq2db.MySql.nuspec'.
The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'authors, version' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nusp
ec.xsd'. This validation error occurred in a 'metadata' element.
`

#### Steps to reproduce
Just run _Pack.bat_ file.

**Comment by sdanyliv** [comment]
Yes, they need additional tweaking which has been done by powershell scripts.
Check this usage
https://github.com/linq2db/linq2db/blob/master/appveyor.yml#L66

**Comment by hardhub** [comment]
But it is not clear what to do with that yml file.  
I do not have Appveyor CI.
Should Pack.bat run PowerShell script as well?
If yes - then why it is not added to Pack.bat? Bug?

**Comment by sdanyliv** [comment]
Looks like we have missed that. 
@MaceWindu removed duplicate information from packages because it is hard to track so many packages and provided on-the-fly updating with needed properties.

**Comment by hardhub** [comment]
OK

Now it is clear, so it is possible to make some workarounds.

**Comment by MaceWindu** [comment]
For local builds you need to use `PackLocal.cmd` and revert nuspec changes before next run

**Comment by hardhub** [comment]
I tried, but result was the same. I think it is because PS was not able to run script.

Probably something like this needed: `powershell -ExecutionPolicy ByPass -File script.ps1`

I am now on different branch so cannot check what exactly happens.

**Comment by MaceWindu** [comment]
What we can do here to improve situation:
- add notes about pack/packlocal files and their difference to contributing.md
- add notes how to fix or fix cmd file if possible for powershell run issue
- restore nuspec templates after packlocal.cmd finished, so it could be run again without reverting changes to them
