### ISSUE TITLE
Can't connect to other DB

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1600]
Hi guys.

I have a problem with connecting to another DB, that means, I'm already connected in my application to a DB, and when I do LogOut, I have the list of DBs. When I put the username, password and selecting another DB from a list, I do a Initialisation of new DB. But when I call 
```
using(var db = new MyDb()){}
```
the "db" variable has the old connection string...from first login.

Example of code:
```
CoreDB.Init(DBConnection dbConnection) //called to set the DB settings.
   {
        _dbConnection = dbConnection;
        DataConnection.DefaultSettings = new DBSettings();
   }  // Initiating new DB Settings.

private class DBSettings : ILinqToDBSettings
        {
            public IEnumerable<IConnectionStringSettings> ConnectionStrings
            {
                get
                {
                    var list = new List<IConnectionStringSettings>
                    {
                        new ConnectionStringSettings
                        {
                            Name = "PostgreSQL",
                            ProviderName = "PostgreSQL",
                            ConnectionString =
                                $"Server={_dbConnection.Host};" +
                                $"Port={_dbConnection.Port};" +
                                $"Database={_dbConnection.Database};" +
                                $"User Id={_dbConnection.Username};" +
                                $"Password={_dbConnection.Password.Decrypt()};" +
                                $"Pooling=true;" +
                                $"MinPoolSize=10;" +
                                $"MaxPoolSize=100;" +
                                $"Timeout=600;" +
                                $"CommandTimeout=600"
                                //
                        }
                    };
                    return list;
                }
            }
            public IEnumerable<IDataProviderSettings> DataProviders { get; }
            public string DefaultConfiguration => "PostgreSQL";
            public string DefaultDataProvider => "PostgreSQL";
        }
```
First time of calling ```using(var db = new MyDb())``` is saving first settings.
So when I logout from application and choose another DB, and doing again CoreDB.Init(dbConnection) with new connection data, it "saves" it, but next call of ```using(var db = new MyDb())``` has just the old ConnectionString.

Am I doing something wrong?

### Environment details
linq2db version: *2.6.3*
Database Server: *E.g. PostgreSQL 10.3*
Database Provider: *E.g. Npgsql 4.0.4*
Operating system: *E.g. Windows 10 x64*
Framework version: *.NET Framework 4.7.2*

**Comment by sdanyliv** [comment]
@YXMagnuMXY,  `ILinqToDBSettings` statically initialized only once.
I suggest to create DataConnection using other constructor:
```cs
		/// <summary>
		/// Creates database connection object that uses specified database provider and connection string.
		/// </summary>
		/// <param name="dataProvider">Database provider implementation to use with this connection.</param>
		/// <param name="connectionString">Database connection string to use for connection with database.</param>
		public DataConnection(
			[JetBrains.Annotations.NotNull] IDataProvider dataProvider,
			[JetBrains.Annotations.NotNull] string connectionString)
		{
```
Provider can be crated once:  `new PostgreSQLDataProvider(...)`

And yes, we are working on simplifying this.

**Comment by YXMagnuMXY** [comment]
Why my code from above was working in previous versions of linq2db, and is not working in the indicated?
Can you give me an example of creating new DataConnection?

**Comment by sdanyliv** [comment]
It is simple.
```cs
var db = new DataConnection(new PostgreSQLDataProvider(PostgreSQLVersion.v95), "connectionstring");
```
`PostgreSQLVersion.v95` tells to use latest version of Postgres SQL syntax.
Also you can modify your `MyDb` connection to call base constructor with these parameters.

**Comment by YXMagnuMXY** [comment]
But why in older versions my code were working?
This is not a good solution, because we use the method showed by you to connect to second DB, and do operations between two DB's. I mean, the app is connected at the same time to two DB's using your last example.

But, the main DB was set from the code that we provide, when we do Login.
Maybe there is another option of doing this instead of completely exiting the application and starting it again?

**Comment by MaceWindu** [comment]
Don't see any recent changes that could change settings behavior.
@YXMagnuMXY, why just don't use `DataConnection.SetConnectionString()` method to update connection string instead of replacing whole settings instance?

**Comment by YXMagnuMXY** [comment]
I tried, and this didn't help. I will try one more time, maybe I did something wrong. Thank you for suggestion.

**Comment by MaceWindu** [comment]
Well, then you definitely do something wrong. I use this method a lot in our application for similar reason - our application could connect to one of dozens database instances based on user's choise and we never had issue with it.

**Comment by MaceWindu** [comment]
BTW, what is base class for `MyDb` and it's constructor?

**Comment by YXMagnuMXY** [comment]
The base class is DataConnection
and I have 3 constructors:
```
                public MyDb()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MyDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}
        public MyDb(LinqToDB.DataProvider.IDataProvider dataProvider, string connectionString)
            : base(dataProvider, connectionString)
        {
            InitDataContext();
        }
```

**Comment by YXMagnuMXY** [comment]
Hey, with ```DataConnection.SetConnectionString``` is working. I don't know what I did wrong before with this method, but now is working ))
My code is:
```
DataConnection.SetConnectionString(DataConnection.DefaultSettings.DefaultConfiguration, DataConnection.DefaultSettings.ConnectionStrings.FirstOrDefault().ConnectionString);
```
for ```DataConnection.DefaultSettings.ConnectionStrings``` I have only one connection string always.

**Comment by MaceWindu** [comment]
I will close it. Reopen if you think we have issue here.
