### ISSUE TITLE
Azure AD Support (SqlConnection.AccessToken)

### ISSUE THREAD

**Issue by mrfrankbell** [linq2db/linq2db#1604]
Please could you add support for using [Azure AD authentication](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication#7-connect-by-using-azure-ad-identities) by allowing the setting of the SqlConnection.AccessToken property **before** the connection is opened.

The easiest way may be to just have a protected virtual method like BeforeOpen() which is called before the connection is first opened. One could then just override that method to request and set the access token.
https://github.com/linq2db/linq2db/blob/1c234c067cb607a70e7b0bd9a34ea7dac25d2344/Source/LinqToDB/Data/DataConnection.cs#L968

**Comment by MaceWindu** [comment]
I think you can try to use DataConnection constructor with connectionFactory parameter as workaround for now.

**Comment by mrfrankbell** [comment]
Does the trick, thanks!

**Comment by MaceWindu** [comment]
#3939 adds new option to do it without custom connection factory
