### ISSUE TITLE
Implement `IndexColumns` schema table population for MySql on our side

### ISSUE THREAD

**Issue by nitz** [linq2db/linq2db#1606]
I'm able to use linq2db to connect to my database successfully in the create connection dialog using the test button.  However, when I go to actually expand the tree view to start using the connect, It throws a SqlNullValueException, with the message "Data is Null. This method or property cannot be called on Null Values". I've attached the MessageBox with the full call stack below.

Connection string: `Server=<redacted>.amazonaws.com;Database=<redacted>;Uid=<redacted>;Pwd=<redacted>;`

I do have rows with null values in them.

Full error MessageBox:

![image](https://user-images.githubusercontent.com/602691/52789514-044a7f80-3032-11e9-80d2-a4891ed322ed.png)

([via](https://forum.linqpad.net/discussion/comment/4152/#Comment_4152))

**Comment by MaceWindu** [comment]
moved to main repo as it is `linq2db` issue

**Comment by nitz** [comment]
Makes sense! I unfortunately can't provide the database, itself, but if there's other information I can provide, let me know!

**Comment by MaceWindu** [comment]
Error is on this line: https://github.com/mysql/mysql-connector-net/blob/8.0/MySQL.Data/src/SchemaProvider.cs#L363

and `show index` [documentation](https://dev.mysql.com/doc/refman/8.0/en/show-index.html) clearly says:
```
 Collation

How the column is sorted in the index. This can have values A (ascending), D (descending), or NULL (not sorted). 
```

people really need to read their own documentation...

**Comment by MaceWindu** [comment]
Actually Oracle was informed about it 5 years ago: https://bugs.mysql.com/bug.php?id=75301
:man_facepalming:

**Comment by MaceWindu** [comment]
Actually there are some chances it will be fixed in MySql.Data too. Somebody tried to send PR (not the easiest task for that repo) https://github.com/mysql/mysql-connector-net/pull/30
