### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1608]
### Developer

We always open to new linq2db developers, so if you want to try yourself as linq2db team member, check those items, which you can start with:
- issues, labeled with [good first issue](https://github.com/linq2db/linq2db/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) tag
- issues, labeled with [needs tests](https://github.com/linq2db/linq2db/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+needs-tests%22) tag - those are issues, for which we need a test to verify defect
- azure pipelines/docker test infrastructure improvements

Don't be afraid to try it, as we always open to help and provide directions.

---
### Technical Writer

`LINQ To DB` team is looking for new members to help us improve our documentation, which is our most painfull area.

In which areas you can help:
- proofreading of existing documentation (english native speaker is a +)
- writing missing and improving existing xml-documentation
- writing articles on linq2db features
- writing tutorials
- updating existing documentation to reflect changes in new releases
- maintain documentation build and publishing processes

From our side we can offer help with understanding existing functionality to make it easier to document using our Slack chat.

Please post below if you are interested and we will send you invite.

**Comment by to11mtm** [comment]
I'm interested!

I don't know whether I can handle documenting everything in question, but I would certainly be willing to chip in!

**Comment by MaceWindu** [comment]
@to11mtm great, sent you slack invite :smile:

**Comment by pebezo** [comment]
Sign me up. I could help with proofreading and writing, but I wouldn't have too much time to dig through the code to figure out how things work.

**Comment by MaceWindu** [comment]
invite sent!

**Comment by FabioNascimento** [comment]
Hello,

I haven`t native english but I would like to help. Invite me.

**Comment by MaceWindu** [comment]
@FabioNascimento, nice, sent you invite!

**Comment by FabioNascimento** [comment]
Tks !!

**Comment by MaceWindu** [comment]
We are moving our documentation to https://github.com/linq2db/docs repository. Please check it if you want to provide us any help with documentation
