### ISSUE TITLE
Any() hides connectivity error

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#161]
I have a table with 1 record that I query with request like that:
return db.Parameters.Any(p => /_some condition_/);

It works without any problems usually. When SQL Server becames unavailable due network problems or server restart, all other queries throw corresponding exceptions (SqlException or some other exceptions), but this one sometimes throws "InvalidOperationException: Sequence contains no elements" from Query<T>.RunQuery method, line:
return Array<TE>.Empty.First();

(maybe it's not related to Any and I observe it for this query only because it executed a lot).

Looks like original error is catched silently somewhere in ExecuteReader or Read methods. I've inspected linq2db catch clauses and didn't found any that could do that. It looks like problem lays inside SqlClient.

You cannot fix SqlClient (and it's not clear if it's SqlClient's fault), but I think it's possible to replace current exception from "return Array<TE>.Empty.First();" line to something more specific.

**Comment by ryanbnl** [comment]
If you can re-create, enable reference-source in Visual Studio then turn on break-on-all exceptions for the CLR-exceptions. Then run your test-case with the VS debugger attached; the debugger'll break when any CLR-exception is hit, even if it's handled :)

**Comment by MaceWindu** [comment]
Hi Ryan, nice to hear from you :)
Well, main problem is that I cannot reproduce it artifically, but get it from time to time from running applcation. It's not a problem at all in our case - just annoing error email. Maybe later I will look into this issue again.

You know, you just gave me idea why I was unable to reproduce it - we receive this error from applications that use sql server on other machine, but I tried to reproduce it locally. So it could be some sockets error improperly handled by provider, because for local connections it use shared memory instead of tcp by default.

**Comment by ryanbnl** [comment]
Hehehe, it's always nice to see a familiar face :) Oh, that could be. We couldn't repo either, the error just pops up occasionally :)

**Comment by sdanyliv** [comment]
@MaceWindu, closing for now. Will reopen when additional reproduce scenarious appear.

**Comment by MaceWindu** [comment]
Yep, no problem. We still get it from time to time, but I have no idea how to reproduce it as it appears rarely and only when there is a network connectivity issues.

**Comment by MaceWindu** [comment]
As we started to get this error in huge numbers last several monthes on one of our servers, I will post some details for anyone who will find this issue.

First of all exception above generated from `impossible` place, because `SqlDataReader.Read` returns false for query that always return 1 record (`SELECT COUNT...`).

I'm 99.9% sure this happens due to this bug: https://stackoverflow.com/questions/14229310/how-to-address-sqlconnection-being-closed-from-inside-executereader when data reader hides connectivity error

**Comment by MaceWindu** [comment]
Looks like it is finally fixed https://github.com/dotnet/SqlClient/issues/291
