### ISSUE TITLE
LinqToDB not work well with DatetimeOffiset properties

### ISSUE THREAD

**Issue by emiliogg84** [linq2db/linq2db#1613]
When execute a query that uses a 'GroupBy' expression base on a property of type DatetimeOffset the result format is not the same as when you do a simple query with a DatetimeOffset property involve.

### Steps to reproduce
Execute a query that uses a group by base on a datetimeoffset property and execute a simple query to view the differences.

### Environment details
linq2db version: 2.6.4
Database Server: SqlServer 2016
Database Provider:  EntityFramework Core
Operating system: Windows 10
Framework version: .Net Core 2.2.0

**Comment by MaceWindu** [comment]
Could you provide more details? I don't see how queries could produce different results on unique data (ignoring sort order)
```
SELECT
    [t1].[dt]
FROM
    [Issue1613] [t1]
GROUP BY
    [t1].[dt]

SELECT
    [t1].[dt]
FROM
    [Issue1613] [t1]
```

**Comment by MaceWindu** [comment]
Also it is not clear what you mean by `EF Core` database provider.

**Comment by emiliogg84** [comment]
I double check the problem and detect that the issue is in OData 4 for ASP.NET Core, when the query pass through EF Core serialization of the datatimeoffset is in different format than when is with Odata and LinqToDB.
