### ISSUE TITLE
TransactionScope not working with PostgreSQL database

### ISSUE THREAD

**Issue by djacksonnz** [linq2db/linq2db#1620]
Sorry if this issue already exists, but I could not see it in the issues list anywhere.

C# TransactionScope() doesnt work with PostgresSQL database, it is working fine with BeginTransaction() in the standard linq2db DataConnection.

I have another project using a MSSQL server and the same version of linq2db (of course with a different provider) and the TransactionScope() works as intended there as described in the documentation https://github.com/linq2db/linq2db#transactions

### Steps to reproduce
Working code example:
Code rolls back the insert successfully
```c#
using (var db = new SsDb())
{
   db.BeginTransaction();

   db.Insert(sessionToken);

   db.RollbackTransaction();
}
```
Issue code example:
Insert is done even though the transaction is not completed with transaction.Complete()
```c#
using (var transaction = new TransactionScope())
{
    using (var db = new SsDb())
    {
        db.Insert(sessionToken);
    }                   
}
```

### Environment details
linq2db version: 2.6.4
Database Server: PostgreSQL 11.1 (In Docker container Debian 11.1)
Database Provider: Npgsql 3.2.5
Operating system: Windows 10/Docker
Framework version: Dotnet Core 2.2

**Comment by lobster2012-user** [comment]
@djacksonnz 
[npgsql, set enlist=true in cs](https://github.com/npgsql/npgsql/blob/master/doc/performance.md)

**Comment by djacksonnz** [comment]
Thanks @lobster2012-user updating the npgsql version to the latest fixes my issue and TransactionScope is now working as expected.
