### ISSUE TITLE
ValueToSqlConverter for enums affects simple integers

### ISSUE THREAD

**Issue by glebkozh** [linq2db/linq2db#1622]
Hi!
When i define custom value to sql converters for an enum, this enum is treated like its underlying value type (e.g., int) and primitive values of that underlying type are affected. For instance, I define some custom expression which compares some column value with custom enum value: 

```c#
[Table]
public class Entity
{
    [Identity, PrimaryKey]
    public int Id { get; set; }
    [Column]
    public string SomeText { get; set; }
}

public enum SomeEnum
{
    Value1, Value2
}

[Sql.Expression("{0} = {1}", InlineParameters = true, ServerSideOnly = true, IsPredicate = true)]
public static bool SomeComparison(string column, SomeEnum value) => throw new InvalidOperationException();
```
Here I set custom mapping for that enum into SQL: 
```c#
 _db.MappingSchema.SetValueToSqlConverter(typeof(SomeEnum),
                (sb, dt, v) =>
                {
                    sb.Append("'").Append(((SomeEnum)v).ToString()).Append("_suffix'");
                });
```
And finally I try to execute two queries:

```c#
var res = _db.GetTable<Entity>().Where(e => SomeComparison(e.SomeText, SomeEnum.Value1)).ToArray();
var res2 = _db.GetTable<Entity>().Where(e => e.Id == 1).ToArray();
```

The first one is executed as expected:
```sql
SELECT
	[e].[Id],
	[e].[SomeText]
FROM
	[Entity] [e]
WHERE
	[e].[SomeText] = 'Value1_suffix'
```
But, unfortunalely, converter tries to map int to its corresponding enum value and affects the second query too:
```sql
SELECT
	[e].[Id],
	[e].[SomeText]
FROM
	[Entity] [e]
WHERE
	[e].[Id] = 'Value2_suffix'
```

I've made workaround and defined container struct for enum and defined mapping  for that container: 
```c#
public struct SomeEnumContainerStruct
{
    public SomeEnum SomeEnum { get; set; }
}

[Sql.Expression("{0} = {1}", InlineParameters = true, ServerSideOnly = true, IsPredicate = true)]
public static bool SomeComparison(string column, SomeEnumContainerStruct value) => throw new InvalidOperationException();

_db.MappingSchema.SetValueToSqlConverter(typeof(SomeEnumContainerStruct),
                (sb, dt, v) =>
                {
                    sb.Append("'").Append(((SomeEnumContainerStruct)v).SomeEnum.ToString()).Append("_suffix'");
                });
```
This works as expected. By the way, container class (not struct) does not work (converter just does not fire). Is this by design?

Thanks!
### Environment details
linq2db version: _2.6.4_
Database Server: _Sql Server 13.0.1601.5_
Database Provider: _Sql.Data.SqlClient 4.6.27110.4_
Operating system: _Windows 10 Pro 10.0.17134_
Framework version: _.NET Core 2.2.102_

**Comment by MaceWindu** [comment]
While it is definitely doesn't work as expected and should be fixed I would recommend to use built-in enum mapping support using `MapValueAttribute` applied to enum instead of `SetValueToSqlConverter`

**Comment by MaceWindu** [comment]
http://blog.linq2db.com/2015/05/using-mapvalueattribute-to-control.html

**Comment by glebkozh** [comment]
Thanks, @MaceWindu! However, I simplified initial problem a bit: actually, I need mapping where strings representing enum values are not escaped with quotes in sql. It seems that your soultion won't work in this case. Fortunately, the above-mentioned trick with custom struct worked perfectly for me.

**Comment by MaceWindu** [comment]
Looks like you need sql.expression extension. Check this file for similar example:
https://github.com/linq2db/linq2db/pull/1649/commits/acd6cd621432ac31c5353ae15cdd3e345b3681fe#diff-dab7b27a9affaf31a33145244bf2cb36R58

ModifierBuilder  is a custom enum to sql builder for sq.expression extension below (Match/MatchRelevance)

**Comment by glebkozh** [comment]
@MaceWindu, nice example, thank you!
