### ISSUE TITLE
Default "Where" condition.(not a bug)

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1627]
Hi, my friends!

I don't know the best option to work with in the next situation:

I have a class generated from a table, for example "USERS", that has a flag - IsDeleted for one of the rows with the boolean value to true. This user is "deleted", and should not be used further.

Is not a problem to do one time ```db.Users.Where(x=>!x.IsDeleted)```, but if I'm using the same table in many places, each time I should put the condition where, ```x.IsDeleted = false```.

Is there any method that would let me write only ```db.Users.ToList()``` and will load the list of users that does not have the flag "IsDeleted" to true?

I know that this is the place of creating issues only, but please help.
If this is not implemented, you can use this to create maybe new feature.

Thanks in advance!

### Environment details
linq2db version: *2.6.3*
Database Server: *E.g. PostgreSQL 10.3*
Database Provider: *E.g. Npgsql 3.2.3*
Operating system: *E.g. Windows 10 x64*
Framework version: *.NET Framework 4.7.2*

**Comment by to11mtm** [comment]
You can handle this a couple of different ways.

If you are using T4 Templates, you may add an additional Partial class to the generated project:

```
//This should be in the same Project/Namespace as your T4 generated Model
namespace PostreSQLDataContext
{
    //This should be the same Class Name as your T4 Generated Model
    public partial class MyGeneratedDataConnection : LinqToDB.Data.DataConnection
    {
        public IQueryable<Users> MyActiveUsers { get { return this.Users.Where(x=>!x.IsDeleted); } }
    }
}
```

You may then use it as `db.MyActiveUsers.ToList()`, or even as `db.MyActiveUsers` in Queries:

```
var myOrdersForActiveUsers = db.Orders.Where(o=> db.MyActiveUsers.Select(activeUser=>activeUser.ID).Contains(o.UserId)).ToList();
```

If you are not using T4 Templates, you may follow the same pattern, instead adding the method to your existing class. (Or, you may still keep it as a partial if you'd like.)

**Comment by YXMagnuMXY** [comment]
Thank you. I will try this.

**Comment by YXMagnuMXY** [comment]
Yes, this works. In fact I had this partial class created already - "
public partial class MyGeneratedDataConnection : LinqToDB.Data.DataConnection", so I've just added the IQuaryable that I need.
Thank you for help!

**Comment by MaceWindu** [comment]
Closing as answered
