### ISSUE TITLE
Support CSharp 8.0 nullable reference types

### ISSUE THREAD

**Issue by ijsgaus** [linq2db/linq2db#1632]
Support CSharp 8.0 nullable reference types in templates by specify option in model

**Comment by MaceWindu** [comment]
FYI https://github.com/dotnet/corefx/blob/master/Documentation/api-guidelines/nullability.md

**Comment by quan01994** [comment]
How to configure `string` mapping to `string?` in T4

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB.Templates/README.md

```cs
EnableNullableReferenceTypes = true;
// this option will be removed in 3.0
AddNullablePragma = true;
```
