### ISSUE TITLE
T4, Type (class) name, sheme prefix with underscore

### ISSUE THREAD

**Issue by Trigun27** [linq2db/linq2db#1633]
Hi, i have problem:

update nuget from 2.2 to the latest. 
The type name is generated in a new way for schemes other than "dbo".
Was:
```csharp
public ITable<AccessContext> AccessContext
```

Now
```csharp
public ITable<access_AccessContext> AccessContext
```
is it possible to set my own Class name?

thank you

**Comment by MaceWindu** [comment]
You can disable this feature using
```
PrefixTableMappingWithSchema  = false;
```

https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#configuring-generation-process


or rename mappings using code similar to properties rename here
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#example-of-generation-process-customization

**Comment by Trigun27** [comment]
Everything is ok, thank you.
