### ISSUE TITLE
Generating SQL from expressions

### ISSUE THREAD

**Issue by CorneVermeulen** [linq2db/linq2db#1634]
Hi all,

I would like to know if there is currently a way to generate SQL from an expression for a different dataprovider than the current context.

Here is a rough example to illustrate what I am aiming to do:

```c#
DataConnection.AddOrSetConfiguration("SQLite", "Data Source=:memory:;Version=3;New=True;", "SQLite");
using (_0DB dataContext = new _0DB("SQLite"))
{	
	Expression expression = dateContext.test.Take(1).Expression;
	var test = dateContext.test.Execute(expression);
	if(test == null)
	{
		query = LinqToDB.GetQueryForDataProvider(expression, new LinqToDB.DataProvider.SqlServer.SqlServerDataProvider(LinqToDB.DataProvider.SqlServer.SqlServerVersion.v2012));
	}
}

if(query != null)
{
	using (sqlDB dataContext = new sqlDB())
	{	
		var test = dataContext.Execute<Test>(query)
	}
}
````

What I am trying to do is use two databases in the same project, first the in memory db should be checked, if it yields no results the sql server db should be checked. I would like to achieve this with the same query to avoid query changes not pulling through to both database checks.

For now I have managed this with some source change, but I recon there might already exist a way to do this that I am just not seeing.

**Comment by sdanyliv** [comment]
It is possible, we have did similar trick with EF Core extension. 
I’ll prepare sample. I think `IQueryable<T> ChangeConnection(this IQueryable<T>, IDataContext newConnection)` will be enough?

**Comment by CorneVermeulen** [comment]
@sdanyliv Thank you for your response! Changing the DataContext on the Queryable would definitely do the trick!

**Comment by sdanyliv** [comment]
@CorneVermeulen, try this one:
```cs
public static IQueryable<T> ChangeConnection<T>(this IQueryable<T> query, IDataContext dc)
{
	var newExpression = query.Expression;
	
	return Internals.CreateExpressionQueryInstance<T>(dc, newExpression);
}
```

**Comment by CorneVermeulen** [comment]
@sdanyliv Thank you so much, that works brilliantly! You are an absolute legend!
