### ISSUE TITLE
DataExtensions for IEnumerable Types

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#164]
In BlToolkit you've had DataHelpers also for IEnumerable Types! Why is this not supported in Linq2Db?
If I do a foreach from outside will it have the same Perf. than BlToolkit, or did BlToolkit put all into one SQL?

**Comment by igor-tkachev** [comment]
What helpers you are talking about?

**Comment by jogibear9988** [comment]
I was wrong...

There were no extensions, but it was possible:

Insert a List of T:
https://github.com/igor-tkachev/bltoolkit/blob/ed697fcc455e8aea0bbbd1553a1b0aa65551465f/Source/DataAccess/SqlQueryT.cs#L167-178

Delete a List of T:
https://github.com/igor-tkachev/bltoolkit/blob/ed697fcc455e8aea0bbbd1553a1b0aa65551465f/Source/DataAccess/SqlQueryT.cs#L328-340

**Comment by igor-tkachev** [comment]
We have BulkCopy methods Instead of InsertBatch.
For Delete see test above.
For Update, at least for MS SQL, you can use Merge method.
