### ISSUE TITLE
Mapping different tables to one class

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1642]
Hi guys,

I have multiple tables that at the end should be loaded in a single general class.
Is there any way to do this so that filtering also works?
I know I could map each table to an own class and than assign the general class in the select statement. But if I would like to filter with a where condition by the general class this wont work.

Provider is Firebird
Linq2db version 2.6.3

**Comment by sdanyliv** [comment]
@Franki1986, better to show samples. How you combine class and how filter.

**Comment by Franki1986** [comment]
Say I would like to have a general card object that has this structure:

        public class GeneralCard{
		public int Id {get;set;}
		public int CardNumber{get;set;}
		public string Name {get;set;}
		public bool IsBlocked{get;set;}
	    }

Now I have two tables with different columns but atually the same meanings:
Table Internal_Card: 
	columns: ID, Number, Name, Blocked
	
Table External_Card:
	columns: External_ID, Card_Number, Name, Is_Blocked

I would like to filter for examlple all cards with card number 1224.
In reality these tables are four and more complex but this should ahow what I want to do.

	var result = GeneralCard().Where(c => c.CardNumber = 1234);

**Comment by sdanyliv** [comment]
@Franki1986, how about defining common interface between different entites? 
Sorry but your sample is still unclear for me and I can not see why linq2db cannot solve this.

**Comment by Franki1986** [comment]
With an Interface this is possible by creating a derived class for each table.
But I was wondering if there is the possibility to create something like this:

```
[Table("INTERNAL_CARD"), MappingName("InternalCard")]
[Table("INTERNAL_CARD"), MappingName("ExternalCard")]
public class GeneralCard{
	[Column("ID"), MappingName("InternalCard")]
	[Column("EXTERNAL_ID"), MappingName("ExternalCard")]
	public int Id{get;set;}
	[Column("Name"), MappingName("InternalCard")]
	[Column("Name"), MappingName("ExternalCard")]
	public string Name{get;set;}
	[Column("NUMBER"), MappingName("InternalCard")]
	[Column("CARD_NUMBER"), MappingName("ExternalCard")]
	public int CardNumber{get;set;}
}


var result = db.GetTable<GeneralCard>("InternalCard").Where(c => c.CardNumber == 1234);
var result = db.GetTable<GeneralCard>("ExternalCard").Where(c => c.CardNumber == 1234);
```

**Comment by sdanyliv** [comment]
This functionality availaible from library’s first day.
```cs
db.GetTable<GeneralCard>().TableName("InternalCard").Where(c => c.CardNumber == 1234)
```

**Comment by Franki1986** [comment]
awesom!!!! I had this in my mind that it will work anyhow but I hadn't found this.
Thanks for helping!!!

**Comment by Franki1986** [comment]
Sorry for asking another time, but how to overcome the different column names?

**Comment by sdanyliv** [comment]
Sorry, no way. Mapping schema stick together with type. Not to table name.

**Comment by Franki1986** [comment]
Ok, then I will use the way with the Interface. I was not sure if this could be handled anyhow.. Thanks!

**Comment by sdanyliv** [comment]
Check this test
https://github.com/linq2db/linq2db/blob/ca111076f81338d361a4ed4d3acb1d8db7c6e12d/Tests/Linq/Mapping/FluentMappingAliasTests.cs#L54

**Comment by Franki1986** [comment]
This helps, but I have a question to that, what is the difference between the base class DataConnection and DataContext. Because I can only change the MappingSchema if my class inherits from DataContext.

**Comment by Franki1986** [comment]
This helps, but is it also possible to create a MappingSchema for the current instance of my DataConnection class? If I work with DataContext this will work, but what about DataConnection?

```
public class MyContext: DataConnection{
    // the global default MappingSchema is used
}
  
```
```
var ms = CreateCustomMappingSchema();
using(var db = new MyContext(ms)){
    Only in this using the created MappingSchema is used
}

```

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L44 ?

**Comment by Franki1986** [comment]
Thanks for the support!
I have tested this and it works like desired!

```
public partial class MyDbContext : LinqToDB.Data.DataConnection
   {
      public MyDbContext() { }

      public MyDbContext(MappingSchema ms)
      {
         if (ms != null && this.MappingSchema != ms)
         {
            this.AddMappingSchema(ms);
         }
      }
      
      public static MappingSchema CreateMappingForTable(string tableName)
      {
         var schema = new MappingSchema();
         var fluent = schema.GetFluentMappingBuilder();

         switch (tableName)
         {
            case "INTERNAL_CARD":
               fluent.Entity<Card>().IsColumnRequired()
                     .HasTableName(tableName)
                     .IsColumnRequired()
                     .Property(e => e.Id).IsColumn().HasColumnName("ID")
                     .Property(e => e.CardNumber).IsColumn().HasColumnName("NUMBER");
               break;
            case "EXTERNAL_CARD":
               fluent.Entity<Card>().IsColumnRequired()
                     .HasTableName(tableName)
                     .IsColumnRequired()
                     .Property(e => e.Id).IsColumn().HasColumnName("EXTERNAL_ID")
                     .Property(e => e.CardNumber).IsColumn().HasColumnName("CARD_NUMBER");
               break;
            default: return LinqToDB.Mapping.MappingSchema.Default;
         }
         return fluent.MappingSchema;
      }

   }

   public class Card
   {
      public int Id { get; set; }
      public string CardNumber { get; set; }
   }

   [Table("CUSTOMER")]
   public class Customer
   {
      [Column("ID")]
      public Int32 Id { get; set; }
      [Column("NAME")]
      public string Name { get; set; }
   }
```


```
            List<Card> res;
            List<Customer> k;
            using (var db = new MyDbContext(MyDbContext.CreateMappingForTable("INTERNAL_CARD")))
            {
               k = db.GetTable<Customer>().Where(c => c.Id < 500).ToList();
               res = db.GetTable<Card>().Where(c => c.CardNumber == "12345").ToList();
               
            }

            using (var db = new MyDbContext(MyDbContext.CreateMappingForTable("EXTERNAL_CARD")))
            {
               k = db.GetTable<Customer>().Where(c => c.Id < 500).ToList();
               res = db.GetTable<Card>().Where(c => c.CardNumber == "12345").ToList();
            }
            using (var db = new MyDbContext())
            {
              k = db.GetTable<Customer>().Where(c => c.Id < 500).ToList();
            }
```
