### ISSUE TITLE
Error while inserting object

### ISSUE THREAD

**Issue by shishmak** [linq2db/linq2db#1648]
when I insert object like here:

```
var d = new billing_Device
                {
                    Devid = Guid.NewGuid(),
                    Sernum = "Test01",
                    Devtypeid = 1
                };

                db.Devices.Insert(() => d);
```
I catch Exception: **LinqToDB.Linq.LinqException: "'value(TestLinq2Db.Program+<>c__DisplayClass4_0).d' cannot be converted to SQL."**

but when I do like this:
```
db.Devices.Insert(() => new billing_Device
                {
                    Devid = Guid.NewGuid(),
                    Sernum = "Test01",
                    Devtypeid = 1
                });
```
evrything is good

### Environment details
linq2db version: 2.6.2.0
Database Server: E.g. PostgreSQL 9.6.9
Database Provider: E.g. Npgsql 3.2.5.0
Operating system: E.g. Windows 10
Framework version: .NET Framework 4.5.0

**Comment by shishmak** [comment]
and another question: when I insert an object through Insert (() => new DBObj {...}) I need to fill in all NotNull properties, even those for which the default value is specified. Is this the normal behavior of the method or should the field values be initialized?

for example:
public class DBObj {
  public DateTime dt {get;set;} = DateTime.Now
}

**Comment by MaceWindu** [comment]
This is expected behavior.

`ITable.Insert(() => new record() {...field setters...})` method works with contructor expressions and allow you to select which fields should be inserted by specifying field initializers explicitly.

`db.Insert(recordObject)` accepts record object and insert all fields, configured as insertable in mapping.

**Comment by MaceWindu** [comment]
closing as answered
