### ISSUE TITLE
Convert based on property custom Attrtibute

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1652]
Hello,

from time to time I have integer fields in my database that saves values in currency in the smallest unit. Better said, Euros in cent. Now I would like to map these to full Euros without changing the mapped property.

```
public class Amount{
    [Column("FEE")]
    public double Fee {get;set}
}

```

The table has a column FEE with integer values that I want to convert to double when loading and back to integers when insert-/updating.
I now I can overwrite the default behavior from loading values  like this:

```
this.MappingSchema.SetConverter<int, double>(i =>
         {
            return i / 100.0;
         });
```

but I would like to be able to create something like this:

```
public class Amount{
    [Column("FEE", DbType = "IntToDouble")]
    public double Fee {get;set}
}

```
and convert like I said. So in my application I can work with doubles, and don't care about the saved data.

**Comment by sdanyliv** [comment]
@Franki1986, check  `SetConverter` overloads, you can specify exact type for destination mapping:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/MappingSchema.cs#L539

**Comment by Franki1986** [comment]
Yes, but how about setting this only for specific mappings? I don't want to always override double -int mapping, only for those which I mark in my mapping, maybe even something like a custom Attribute.

public class Amount{
    [Column("FEE",), IsDoubleToInt]
    public double Fee {get;set}
}

**Comment by sdanyliv** [comment]
Ok, let's imagine you have written the following query:
```cs
var boundary = 100;
var query a in db.GetTable<Amount>()
  where (a.Fee + 10) > boundary
  select a;
```
How do you suggest to calculate boundary parameter type? What I'm trying to explain, that there will be problem in querying such objects. Here we need more logic. And I'm not ready to propose that.

It is also problem in EF Core - they allow any convertation, but they do not provide query mechanism for such properties (but may be something has been changed in this area).

**Comment by Franki1986** [comment]
Hmmmm... In my case it was only a data visualization, but thinking about that makes it more complicated. I think until I have a better idea I will use an expression method, for now that works, but I am not sure how to work with such a scenario like you mentioned..

**Comment by Franki1986** [comment]
Closed for now, because of the complexer query problem
