### ISSUE TITLE
About t4Models  PrefixTableMappingWithSchema Not effective

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db#1656]
PrefixTableMappingWithSchema whether it is true or false,
The generated classes are not prefixed.
````
<#@ template language="C#" debug="True" hostSpecific="True"                           #>
<#@ output extension=".generated.cs"                                                  #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude"     #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"     #>
<#
//  See more at https://github.com/linq2db/t4models

	NamespaceName = "Hyw.Data";
	DataContextName ="HywCrmDbContext";
	PrefixTableMappingWithSchema = true;
	LoadSqlServerMetadata("192.168.1.52", "HYW.CRM", "sa", "siia_db2315");

	GenerateModel();
#>
````

linq2db.sqlserver 2.6.4

**Comment by MaceWindu** [comment]
Prefix is not applied to default schema. If you want to include it for default schema too, you can do it by adding following code before `GenerateModel()` call:
```cs
foreach (var table in Tables.Values)
		table.IsDefaultSchema = false;
```

**Comment by quan01994** [comment]
i edit this .
i want to know what is the use of IsDefaultSchema
![image](https://user-images.githubusercontent.com/20533465/54669089-716a9c80-4b2b-11e9-849b-421bfd1e722a.png)

**Comment by MaceWindu** [comment]
default schema is schema, used by server when you don't specify schema for database object explicitly.

`select * from from table` == `select * from from default_schema.table`

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/ownership-and-user-schema-separation-in-sql-server#the-dbo-schema
