### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by romanreal89** [linq2db/linq2db#1668]
Hello

I have the method         

public virtual int Delete(T item) => m_db.Delete(item); 

And call it in controller

arcReportRepository.Delete(guid);

And after that I have the error:
Время ожидания выполнения истекло. Время ожидания истекло до завершения операции, или сервер не отвечает.
The statement has been terminated.
StackTrace:
   в System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   в System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   в System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   в System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   в System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   в System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   в System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   в LinqToDB.Data.DataConnection.ExecuteNonQuery() в C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:строка 1040
   в LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryImpl(DataConnection dataConnection, PreparedQuery preparedQuery) в C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:строка 287
   в LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery() в C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:строка 325
   в LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters) в C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:строка 759
   в LinqToDB.Linq.QueryRunner.<>c__DisplayClass28_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps) в C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:строка 752
   в LinqToDB.Linq.QueryRunner.Delete`1.Query(IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName) в C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.Delete.cs:строка 66
   в LinqToDB.DataExtensions.Delete[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName) в C:\projects\linq2db\Source\LinqToDB\DataExtensions.cs:строка 462
   в Vero.Navicon.ProcessCube.Data.Repositories.Repository`3.Delete(P id) в E:\Projects\Git Vero.Navicon.ProcessCube\Vero.Navicon.ProcessCube.Data\Repositories\Repository.cs:строка 36
   в Vero.Navicon.ProcessCube.Web.Controllers.SalesoutReportController.DeleteArcFactsByReport(Guid guid) в E:\Projects\Git Vero.Navicon.ProcessCube\Vero.Navicon.ProcessCube.Web\Controllers\SalesoutReportController.cs:строка 64

How I can change timeout for command?
By default CommandTimeout for my DataConnection (m_db) is 0 (infinity), but it doesn't work.

**Comment by MaceWindu** [comment]
Actually by default timeout is not applied to command if you didn't assign value to it explicitly. In this case it use default timeout value, which is 30 seconds for SqlCommand: https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout?view=netframework-4.7.2

Not sure why we return 0 in CommandTimeout property getter for this case, as it is really confusing.

**Comment by MaceWindu** [comment]
See this https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L1068 and this https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L1094,
so you actually need to explicitly set `dataConnection.CommandTimeout = 0;` (and call DisploseCommand, if DataConnection instance already used before https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L1106)

**Comment by MaceWindu** [comment]
Looks like we need to make this property nullable, which is a API-breaking change and should be postponed till v3

**Comment by romanreal89** [comment]
I tried next variants, but still have the same error
        public virtual int Update(T item) {
            m_db.CommandTimeout = 0;
            m_db.DisposeCommand();
            return m_db.Update(item);
        }
and
        public virtual int Update(T item) {
            m_db.DisposeCommand();
            m_db.CommandTimeout = 0;
            return m_db.Update(item);
        }

**Comment by sdanyliv** [comment]
@romanreal89, it can be problem when many DataConnections are opened.
Please verify that you manage connections properly.
https://github.com/linq2db/linq2db/wiki/Managing-data-connection

**Comment by MaceWindu** [comment]
Also can you check with debugger what timeout value is set for command when you have this error, because I don't see how it cannot work on our side. I tried following test as quick check and it passed:

```cs
[Test]
		public void CommandTimeoutTest([IncludeDataSources(ProviderName.SqlServer2014)] string context)
		{
			using (var db = new TestDataConnection(context))
			{
				var start = DateTimeOffset.Now;
				db.QueryHints.Add("WAITFOR DELAY '00:01';");

				try
				{
					db.Person.ToList();
				}
				catch { }
				finally
				{
					var time = DateTimeOffset.Now - start;
					Assert.True(time >= TimeSpan.FromSeconds(30));
					Assert.True(time < TimeSpan.FromSeconds(32));
				}

				start = DateTimeOffset.Now;
				try
				{
					db.CommandTimeout = 10;
					db.Person.ToList();
				}
				catch { }
				finally
				{
					var time = DateTimeOffset.Now - start;
					Assert.True(time >= TimeSpan.FromSeconds(10));
					Assert.True(time < TimeSpan.FromSeconds(12));
				}

				start = DateTimeOffset.Now;
				try
				{
					db.CommandTimeout = 0;
					db.Person.ToList();
				}
				catch { }
				finally
				{
					var time = DateTimeOffset.Now - start;
					Assert.True(time >= TimeSpan.FromSeconds(60));
					Assert.True(time < TimeSpan.FromSeconds(62));
				}
			}
		}
```

**Comment by romanreal89** [comment]
Sorry, I confused you. Last my comment was my mistake.
You first solution works for me! 
Thank you very much!
