### ISSUE TITLE
Exception on InsertWithIdentity, is asking for pluralised name of sequence.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1671]
Dear developers,

I have a problem with new created tables.
I added as a default value the nextval of the sequence created by me.
When trying the method InsertWithIdentity, it gives an error - 
```Error message: relation "plc.data_types_id_seq" does not exist```.
The point is that the sequence name is "plc.data_type_id_seq", without an "s" after the word "type". why is asking for the sequence that does not exist?
And this is not the only table that has the same error.
With the regular Insert is working without any problem. That means, the InsertWithIdentity looks in the sequence for the next ID that will be given to the inserted row and returns that number? I understand that this can be maybe a little bit faster to insert, but in my opinion is better to check if is inserted, and what Id it has. Don't you think so?

By the way, how to fix this error?

### Environment details
linq2db version: *2.6.4*
Database Server: *PostgreSQL 10.3*
Database Provider: *Npgsql 4.5.2*
Operating system: *Windows 10 x64*
Framework version: *.NET Core 2.2*

**Comment by MaceWindu** [comment]
If sequence name is not set explicitly by SequenceNameAttribute, name is [inferred](https://github.com/linq2db/linq2db/commit/41a00e5a06e10d05fdcbf2dc5b43a07661f7211f#diff-9e564a72a782e8d8ec64c49bdd015c6cL49) from table and field name.

BTW, it will change in new release to not use sequence name as you can see from provided link changes

**Comment by YXMagnuMXY** [comment]
Ok, but you know that the sequence can be named how you want, should not be limited to table and column name, right?
So in the next release, the InsertWithIdentity will change the approach of getting the ID of the inserted row without using sequence?

**Comment by MaceWindu** [comment]
>> Ok, but you know that the sequence can be named how you want, should not be limited to table and column name, right?

that's why we have SequenceName attribute, using which you can set name for sequence if it doesn't match default naming strategy for pgsql

>> So in the next release, the InsertWithIdentity will change the approach of getting the ID of the inserted row without using sequence?

yes, starting from v2.7 we will switch to use `RETURNING` clasue instead of separate query to fetch sequence value. See https://github.com/linq2db/linq2db/pull/1581

**Comment by YXMagnuMXY** [comment]
Thank you for your fast response. Now I have a clear vision how to fix now the problem, and what will be the solution in the future.
You're the best ;)

**Comment by MaceWindu** [comment]
Closing as answered
