### ISSUE TITLE
Fluent mapping generation tool

### ISSUE THREAD

**Issue by zdomokos** [linq2db/linq2db#1672]
Hi! 
I added linq2db fluent mapping generation to the nHibernateMappingTool https://github.com/zdomokos/NHibernateMappingGenerator_Patched.

**Comment by MaceWindu** [comment]
Can you post it to https://github.com/linq2db/linq2db/issues/945?

**Comment by MaceWindu** [comment]
Thanks, I will close this to keep issue list clean
