### ISSUE TITLE
AsUpdatable() generates syntax error in UPDATE statement

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#1676]
I try to build update query from several parts checking each part for null - simple and typical situation like in UPDATE section of your README.md file. Below query raises exception due to wrong UPDATE syntax.

```
DataConnection: Error
Exception: System.Data.OleDb.OleDbException
Message  : Syntax error in UPDATE statement.
```

### Steps to reproduce
```c#
var u = db.Batches.
    Where(x => x.Id == 1).
    AsUpdatable();

u.Set(x => x.ReferenceId, 1);
u.Update();
```
Section just after AsUpdatable() generates the following SQL in Visual Studio SqlText:
```
SELECT
	[x].[OtherUnimportantField],
	[x].[ReferenceId],
	[x].[Id]
FROM
	[T_Batch] [x]
WHERE
	[x].[Id] = 1
```
Section just after Set() doesn't change anything in SQL.

### ExpressionTest
[ExpressionTest.0.cs.txt](https://github.com/linq2db/linq2db/files/3053962/ExpressionTest.0.cs.txt)

### This works
```c#
var v = db.Batches.
    Where(x => x.Id == 1).
    Set(x => x.ReferenceId, 1);

v.Update();
```

### Environment details
linq2db version: *2.6.4*
Database Server: *Ms Access*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.5*

**Comment by MaceWindu** [comment]
You forgot to save your set expression:
```cs
/*u = */u.Set(x => x.ReferenceId, 1);
```

I just hope C# will get explicit results discard check at some point...
