### ISSUE TITLE
LINQ over WCF on .Net standard 2.0?

### ISSUE THREAD

**Issue by rualmar** [linq2db/linq2db#1678]
We have an app working with LinqToDB on Server and executing queries on Windows WPF clients using LINQ Over WCF with LinqToDB.ServiceModel.ServiceModelDataContext. We're evaluating the cost of doing some helper app for android using Xamarin.Forms, which relies on .NET Standard 2.0. 

I've installed the last LinqToDB NuGet on my model package targeting .net Standard 2.0 and I can't find the namespace LinqToDb.ServiceModel. Does it have any similar feature to use with our current LinqToDB.ServiceModel.LinqService?

### Environment details
linq2db version: 2.6.4
Database Server: Sql Server
Database Provider: Sql Server
Operating system: Android (Xamarin.Forms)
Framework version: .NET Standard 2.0

**Comment by MaceWindu** [comment]
Right now we don't expose it for netstandard2.0 build as .net core lacks server support. Will check if we can expose client part.

**Comment by rualmar** [comment]
Thank you! It would be really great to keep our app ecosystem consistent over different platforms. I'll try to make some tests myself and will tell if I reach any good results.

**Comment by MaceWindu** [comment]
.net core support added by #3410 (using grpc). If you need WCF support with .net core - create new feature request and specify which WCF implmentation framework needed
