### ISSUE TITLE
how to get IAsyncEnumerable from raw sql query?

### ISSUE THREAD

**Issue by andrewlawis** [linq2db/linq2db#1679]
Is it possible to get IAsyncEnumerable from raw sql query?

**Comment by sdanyliv** [comment]
Sorry, not yet. We have to switch to C# 8.0 elegantly to support previous frameworks.

**Comment by Shane32** [comment]
Now that linq2db 3.0.0 only supports .Net Standard 2.1, should the `LinqToDB.Async.IAsyncEnumerable` and `LinqToDB.Async.IAsyncEnumerator` classes be replaced with their .Net Standard 2.1 counterparts?  I could probably write a PR for this.

**Comment by MaceWindu** [comment]
actually we don't target netstandard2.1 right now (as we don't use it's features), but if you are willing to work on IAsyncEnumerable, we will add it to target platforms

**Comment by Shane32** [comment]
@MaceWindu How would you imagine this working with the existing IAsyncEnumerable interfaces?  The signatures are notably different, particularly in the way that the CancellationTokens work, so it doesn't seem immediately obvious.  Microsoft does provide a `Microsoft.Bcl.AsyncInterfaces` nuget package to provide backwards compatibility to .Net Standard 2.0, but right now 3.0 also targets .Net Framework 4.5.  Here's a few options:
1. Implement the new interfaces when targeting .Net Standard 2.1 only, and optionally mark the existing interfaces as deprecated.
2. Import the Microsoft.Bcl.AsyncInterface nuget package for .Net Standard 2.0, and implement the new interfaces when targeting .Net Standard 2.0+.  Optionally mark the existing interfaces as deprecated.
3. Implement the new interfaces when targeting .Net Standard 2.1 only, and remove the existing interfaces (or make as private if necessary).
4. Import the Microsoft.Bcl.AsyncInterface nuget package for .Net Standard 2.0, and implement the new interfaces when targeting .Net Standard 2.0+.  Remove the existing interfaces (or make as private if necessary).

**Comment by MaceWindu** [comment]
I would prefer to bring our interfaces to resemble oficial `IAsyncEnumerable` for net45/net46, use `Microsoft.Bcl.AsyncInterfaces` for other targets without IAsyncEnumerable  and use IAsyncEnumerable out of box for netstandard2.1

As it is breaking change, we should do it in 3.0 release, but we don't have much time left, so I would say we should do following:
- small breaking PR which changes our interface definition, hide it for non-net45/net46 targets and adds `Microsoft.Bcl.AsyncInterfaces` to nestandard2.0/netcoreapp2.1 targets. This PR should go into 3.0
- working on better IAsyncEnumerable support accross libary without haste for some 3.x release

**Comment by Shane32** [comment]
See PR #2303

**Comment by MaceWindu** [comment]
Implemented
