### ISSUE TITLE
Check if we need to change sql generation for mysql with ONLY_FULL_GROUP_BY sql mode

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1694]
With ONLY_FULL_GROUP_BY sql mode option set some of our mysql tests start to fail.
We should check if it is expected behavior or we can adjust SQL generation so it will work with this option enabled

**Comment by exileDev** [comment]
Can I still hope you fix this behavior soon? For some queries quite hard to leave compatibility with the MySQL engine.

**Comment by MaceWindu** [comment]
Well, you are first person that upvoted this issue. Will assign it to next release for now.
