### ISSUE TITLE
How to use TransactionScope across multiple repositories?

### ISSUE THREAD

**Issue by nzandy** [linq2db/linq2db#1698]
We have legacy code using SimpleData as an ORM that we are looking to replace with Linq2Db (all our newer code is already using this).

The pattern we are currently using is a Service class that injects one or more repository classes for data access. 

I am wanting to make use of the built in TransactionScope class in the .NET framework with Linq2Db, however the only examples I can see are only using a single repository class.

Not sure if this is the right place to be asking for advice - but does anyone have any experience or code examples for achieving this?

Currently each  Linq2Db backed repository has its own implementation of DataConnection class, and within each repository method we instantiate a new instance of the relevant DataConnection to perform the query.

We have multiple DataConnection classes so that we can create one for each BoundedContext, rather than just having a single DataConnection class that references multiple bounded contexts.

Is it possible to share a transaction across multiple instances of DataConnection? Or do the repositories need to use the same DataConnection to be able to do this?

**Comment by sdanyliv** [comment]
@nzandy, I don' think it is good idea to share transaction via `TransactionScope` and it has to be supported by DataProvider. If it is supported, you can use it just now.

What you can do also:
1. Share `DataConnection` via DI (dependency injection), so every repository will have the same DataConnection instance per request/scope
2. Create `DataConnection` using appropriate constructor(s) - there are lot of them where you can share `IDbConnection` or `IDbTransaction` https://github.com/linq2db/linq2db/blob/6b20d8288e6eec1927eade8b309631676a7450f1/Source/LinqToDB/Data/DataConnection.cs#L221

Usually i don't like repository pattern. And you just got one from the future problems.

**Comment by nzandy** [comment]
> @nzandy, I don' think it is good idea to share transaction via `TransactionScope` and it has to be supported by DataProvider. If it is supported, you can use it just now.

sorry can you elaborate more on this? Why exactly is it not a good idea to share a transaction via TransactionScope?

> Usually i don't like repository pattern. And you just got one from the future problems.

Also this, can you you clarify what you mean by not liking the repository pattern?

Cheers.

**Comment by sdanyliv** [comment]
> sorry can you elaborate more on this? Why exactly is it not a good idea to share a transaction via TransactionScope?

Sorry, not a big expert in this area. Linq2db do not hide `TransactionScope` usage and you have try it [yourself](https://docs.microsoft.com/ru-ru/dotnet/api/system.transactions.transactionscope?view=netframework-4.8).

> Also this, can you you clarify what you mean by not liking the repository pattern?

Repository pattern adds additional complexity instead of helping writing code. Especially if you need to join data from two or more repositories. Linq2db is great DB Abstraction and i do not see benefits in creating additional abstraction. Repository pattern is good for languages which do not have LINQ - but we have :)

I prefer static methods (it can be extension methods for DataConnection):
```cs
// like repository, but just encapsulates LINQ queries
public static class UsersData
{
    public static IQueryable<User> GetAvailaibleUsers(IDataContext dc)
    {
          return dc.GetTable<User>().Where(u => u.IsActive);
    }
}

// another "repository"
public static class OrdersData
{
    public static IQueryable<Order> GetAllowedOrders(IDataContext dc, string userName)
    {
          // row level security
          var query = from o in db.GetOrder<Order>()
                      from uo in db.GetTable<UserOrder>().InnerJoin(uo => uo.OrderId == o.OrderId && uo.UserName == userName)
                      select o;
    }
}

// final service, or controller
public class OrderService
{
    // hypothetical implementation, just shows how two "repositories" work together 
    public async Task<OrderDto[]> GetOrders(string currentUser)
    {
         using (var db = new DataConnection())
         {
               var query = from u in UsersData.GetAvailaibleUsers(db)
                           from o in OrdersData.GetAllowedOrders(db, currentUser).InnerJoin(o => o.ProvidedBy == u.UserId)
                           select new OrderDto
                            {
                                 Order = o,
                                 User = u
                           }
               return await query.ToArrayAsync();
         }
    }

   public async Task DeleteOrder(string currentUser, string orderId)
   {
         using (var db = new DataConnection())
         {
              // here we combine row level security with delete operation, 
              // so we can be always sure that not allowed order can not be deleted.
              var affected = await OrdersData.GetAllowedOrders(currentUser)
                     .Where(o => o.OrderId == orderId)
                     .DeleteAsync();
              if (affected == 0)
                 throw new Exception("Order not found");
         }
   }
}
```
My point is - write working effective code now and then (after weeks) you will find places that can be unified. For example, proposed helper methods can help in writing report queries - you will never make mistake and do not show inappropriate data for user.

**Comment by to11mtm** [comment]
@nzandy I can chime in as to why you should be careful about using TransactionScope nowadays.

 - NetCore versions before 2.1 have spotty `TransactionScope` support from providers. I believe SQLClient's behavior is to throw an error, other providers may just fail silently however. 
 - NetCore versions released to date do NOT support DTC.
 - Cross DB transactions (i.e. MSSQL + Oracle) will probably get promoted to DTC if supported
 - SQL Server connections using `SQLClient` that are using the SAME database can be under a different TransactionScope.
 - SQL Server will promote to DTC if you are using multiple databases (even on the same server)
 

 Oh, as a random aside: 
  
- SQLite will deadlock if you write to the same table twice, using different connections, under the same `TransactionScope`

I'm somewhat curious what in the design requires transactionally writing to multiple databases. If these are different tables in the same schema, but are functionally different parts of the domain, that MIGHT make sense.

@sdanyliv's example is actually pretty close to how I write my code from an abstract standpoint. I don't necessarily use statics that way however.

I tend to think of things in the concept of repositories for Business Domains versus Model Domains. Writing Linq2Db code in that fashion (and using statics and/or extension methods in a way as shown above) can be a good bit cleaner and leans closer to CQRS designs.
