### ISSUE TITLE
Sybase DateTime 1 Jan 1900 converted to 1 Jan 0001 on read?

### ISSUE THREAD

**Issue by pnewton** [linq2db/linq2db#1707]
If one is reading the DateTime `1 Jan 1900`, the sybase provider overrides this with `1 Jan 0001`:
https://github.com/linq2db/linq2db/blob/5db980311525135d0105491daaab2f85d187adea/Source/LinqToDB/DataProvider/Sybase/SybaseDataProvider.cs#L61-L62

Is there any reason for this?  The minimum datetime for Sybase ASE is 1 Jan 1753. What if one wants to represent 1 Jan 1900 in the database?

http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36271.1550/html/blocks/X58954.htm

linq2db version: *2.7.0*
Database Server: *Sybase ASE 15.7*
Database Provider: *Sybase*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.6.2*

**Comment by MaceWindu** [comment]
I suspect this is related to how Sybase provider works with time intervals, by representing them using DateTime 1/1/1900, but still it looks too aggressive, probably we should review this code.

**Comment by MaceWindu** [comment]
issue confirmed
