### ISSUE TITLE
New feature request: producing sql without running a query

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#1708]
Today I was [twitting](https://twitter.com/giuliohome_2017/status/1124260758555123712) with @Zaid-Ajaj (about his Fable.SqlClient which is node-mssql binding) and, once more, aside from the specific context originating the question, I've seen that having the option to produce the sql query as text *without actually running it on the DB* would be a nice feature.

I see that here we have an `InitCommand` where we set `LastQuery = Command.CommandText;` so maybe it shouldn't be too difficult to run the "initialization" only.

Is that something you could put in the roadmap and/or for which you would accept any dev contributions?
Thank you.

**Comment by MaceWindu** [comment]
AFAIC, you can get approximate sql for linq queries using ToString() call.
To get actual sql from CommandText you can try to set your custom execute handler using this feature https://github.com/linq2db/linq2db/pull/1699. In that case I would recommend to throw and catch exception from Execute extensions, to avoid linq2db failures when execute returns unexpected results. Again, this will not work if query requires multiple commands executed, as it will fail on first one

**Comment by giuliohome** [comment]
Wonderful!
You are right! 
Thank you for the immediate and great support, as usual.
