### ISSUE TITLE
Association using a query expression throws a cast exception when using an IQueryable property.

### ISSUE THREAD

**Issue by SaltyDH** [linq2db/linq2db#1711]
I'm attempting to add additional query constraints to an association via a query expression. Additionally, when using this association in a query, I would like to perform a .Any() linq query upon this association.

The following configuration works:
```
Mapping:
builder
	.Entity<Entity>()
	.HasTableName("Entity")
	.HasPrimaryKey(x => Sql.Property<long>(x, "Id"))
	.Association(x => Sql.Property<IQueryable<Relationship>>(x, "relationship"),
		e => e.Id, r => r.EntityId);
```

```
Query:
var result1 = entity
	.Where(t => Sql.Property<IQueryable<Relationship>>(t, "relationship").Any())
	.ToList();

SQL:
SELECT
	[t].[Id],
	[t].[Deleted],
	....
FROM
	[Entity] [t]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[Relationship] [c_1]
		WHERE
			[t].[Id] = [c_1].[EntityId]
	)
```

The following configuration fails with an exception when using the same query from above:
```
builder
	.Entity<Entity>()
	.HasTableName("Entity")
	.HasPrimaryKey(x => Sql.Property<long>(x, "Id"))
	.Association(x => Sql.Property<IQueryable<Relationship>>(x, "relationship"),
		(e, db) => db.GetTable<Relationship>()
		    .Where(r => r.Deleted == false && r.EntityId == e.Id));
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.ArgumentException: 'Expression of type 'Linq2DBTest.Relationship' cannot be used for parameter of type 'System.Linq.IQueryable`1[Linq2DBTest.Relationship]' of method 'Boolean Any[Relationship](System.Linq.IQueryable`1[Linq2DBTest.Relationship])'
Parameter name: arg0'
```

### Environment details
linq2db version: *2.7.0*
Database Server: *E.g. SQL Server 2017*
Database Provider: *E.g. SqlClient*
Operating system: *E.g. Windows 10*
Framework version: *.NET Core 2.2*

**Comment by SaltyDH** [comment]
The below association definition works at the expense of access to the current IDataContext.

.Association(x => Sql.Property<IQueryable<Relationship>>(x, "relationship"),
  (e, m) => m.Deleted == false && m.EntityId == e.Id);

**Comment by sdanyliv** [comment]
@SaltyDH, we never used IQueryable associations in that way especially by dynamic properties. I have to check that and possible additional work is needed here. It is a cost when implementing feature and people invents another ways of its usage )
Let me access to my computer on Monday and i’ll check possibilities.

Your second sample uses different algorithm for generating associations. Queryable associations are more complicated to parse and inject into query AST.

**Comment by SaltyDH** [comment]
@sdanyliv Thanks! I really appreciate the feedback.

I definitely recognise the complexities in these usages, I took a deep dive into these code flows to see how they are put together its well structured, just a lot going on for the different possibilities! If the above solution is the recommended way of doing this, that's probably good enough. The reason I was interested in the IDataContext is so that I have access to things like FromSql or GetCte from within these mapping expressions. It sounds like these are usages I should probably avoid if possible.

:) Thanks again!
