### ISSUE TITLE
Mapping datetime2 to Local DateTime for just a given column

### ISSUE THREAD

**Issue by damnlogin** [linq2db/linq2db#1719]
Hello

I am using `MappingSchema.SetConvertExpression` method to convert all DB stored datetime fields to `DateTime` properties with `DateTimeKind.Utc` as in utc I save them, but for just few tables (exernally owned) I need to convert `DateTime` fields to `DateTimeKind.Local`. As SetConvertExpression gives me no information of the entity type or column name being converted - I can not use this method for the purpose. Is there any way to assign column level converter either using attribute or fluent builder?

Thanks in advance

**Comment by sdanyliv** [comment]
@damnlogin, i have several ideas:

- You can switch MappingSchema for every connection
- You can set convert expression based on db type name (it can be defined for column)

**Comment by MaceWindu** [comment]
per-column converters for both attribute-based and fluent mappings will be available in next release https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273
