### ISSUE TITLE
SQLite: custom functions fail with shift operators (>> and <<) 

### ISSUE THREAD

**Issue by hoangcuongvn** [linq2db/linq2db#1723]
I see in SQLite, custom functions fail if they have shift operators (both >> and <<) . E.g both functions Test1, Test2 below will fail. The exception message is something like `"(x.MyField >> 16) cannot be converted to SQL"`.

```
public static class HelperFunctions
{
	[ExpressionMethod("Test1Impl")]
	public static long Test1(long value)
	{
		throw new InvalidOperationException();
	}

	private static Expression<Func<long, long>> Test1Impl()
	{
		return (value) => (value >> 16);
	}

	[ExpressionMethod("Test2Impl")]
	public static long Test2(long value)
	{
		throw new InvalidOperationException();
	}

	private static Expression<Func<long, long>> Test2Impl()
	{
		return (value) => (value << 16);
	}
}

```

**Comment by sdanyliv** [comment]
@hoangcuongvn, at first you have to teach our SQL Builder how to translate shift operation.
```cs
public static class SqLite
{
     [SqlExpression(“{0} << {1}”, Precedence.Primary)]
     public static long Shl(long v, int s) => v << s;

     [SqlExpression(“{0} >> {1}”, Precedence.Primary)]
     public static long Shr(long v, int s) => v >> s; 
}
```
Then you have to remap expression to these functions. Somewhere in program initialization.
```cs
Expressions.MapMember((long v, int s) => v << s, (v, s) => SqLite.Shl(v, s));
Expressions.MapMember((long v, int s) => v >> s, (v, s) => SqLite.Shr(v, s));
```
For now linq2db will know how to translate shift operations.

Note that i’m typing on iPad from my memory ;)

**Comment by hoangcuongvn** [comment]
It seems something is wrong. The SqlExpressionAttribute does not exist. I tried Sql.ExpressionAttribute but the Expressions.MapMember fails. The exception is `"Unable to cast object of type 'System.Linq.Expressions.SimpleBinaryExpression' to type 'System.Linq.Expressions.NewExpression'."`.

**Comment by hoangcuongvn** [comment]
I found it `[Sql.Expression("{0} >> {1}", ServerSideOnly = true)]`

**Comment by sdanyliv** [comment]
@hoangcuongvn, so it works?

**Comment by hoangcuongvn** [comment]
Yes, it works.  I use SqLite.Shr and SqLite.Shl functions in place of shift operators.

**Comment by sdanyliv** [comment]
Leaving this issue opened to track MapMember enhancement.

**Comment by sdanyliv** [comment]
Added function `Expressions.MapBinary(...)` for defining such mapings.
