### ISSUE TITLE
Error "Too many clients already", a lot of IDLE connection in DB.

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1724]
Dear friends.

We are working on an API, and occur a problem related to PostgreSQL error - "Too many clients already".
This happens when trying to load data from the database. 
If we look at ```pg_state_activity``` , we can see that there are a bunch of connections on IDLE.

```
Exception message: Too many clients already
```
![image](https://user-images.githubusercontent.com/33696606/57917078-a467ad00-789c-11e9-8f71-8e187c1c6355.png)
We are using dependency injection for the Context.

Before, we worked on a project for a desktop application, and never had a problem like that. But there we used ```using(var db = new DbContext){}``` for getting data, without a need to dispose the connection, and no need to use Async methods at all.

Did this happen to somebody else before?
What we are doing wrong?
We tried almost everything and no luck...
Help ;(

### Environment details
linq2db version: 2.7.0
Database Server: PostgreSQL 10.3
Database Provider: Npgsql ? (is not installed with Linq2DB at all, but is working.)
Operating system: Windows 10 x64
Framework version: .NET Core 2.2

**Comment by sdanyliv** [comment]
@YXMagnuMXY, ensure that you have properly defined your DI container to dispose DataConnection after request.
Also read this article https://linq2db.github.io/articles/general/Managing-data-connection.html

**Comment by YXMagnuMXY** [comment]
For sure we are doing something wrong...
Thank you @sdanyliv . We'll follow your suggestion, because logic, somewhere the DataConnection is not disposing.
Have a good day!
