### ISSUE TITLE
error with lag function

### ISSUE THREAD

**Issue by dconner2006** [linq2db/linq2db#1732]
I am getting incorrect syntax near respect when using lag function.

```cs
var posi =
                    from p in db.GetTable<Position_c>()
                    where p.Msg_Dt == yesterday
                    select new vehicle_positions
                    {
                        Hral_veh_id = p.Hral_Veh_Id,
                        prev_veh_id = Sql.Ext.Lag(p.Hral_Veh_Id, Sql.Nulls.Respect, 1, null).Over().OrderBy(p.Msg_Dt).ThenBy(p.Hral_Veh_Id).ThenBy(p.Msg_Tm).ToValue(),

                    };
```

**Comment by MaceWindu** [comment]
This error generated only for databases, which doesn't support `RESPECT NULLS` token. So basically now it works only for Oracle and Informix.
Taking into account that `RESPECT NULLS` is default behavior for LAG function, we just shouldn't generate it.
