### ISSUE TITLE
Fix GenerateTestString

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1737]
There are a few issues with Generate Test String wich could made it easier to create a Test

- [x] Attributes wich are not needed should not be included
- [x] Constructors of DTO throw NotImplementedExcpetion
- [x] Enums are created as Structs derived from Enum, no Values are included
- [ ] Arrays of objects are treated as separate class
- [ ] Constructors are created wich are not needed, classes used only in the constructors are not created
- [x] Mapping is missing if Attributes are not used
- [ ] All classes should be defined inside of test namespace (so we get no conflicts) (remove original ns?)
- [ ] Captures should be emited

**Comment by jogibear9988** [comment]
A good idea would be to convert query of test #1736 to a test again.
(cause I created it like this)

**Comment by sdanyliv** [comment]
@jogibear9988, i hope you have time to improve that. 
Also, check this one https://github.com/agileobjects/ReadableExpressions
Maybe we can dynamically load library and reuse this implementation.

**Comment by jogibear9988** [comment]
I‘m looking to work on this

**Comment by jogibear9988** [comment]
https://github.com/linq2db/linq2db/pull/1752
