### ISSUE TITLE
AccessProvider - 'Data type mismatch in criteria expression' on Insert decimal value

### ISSUE THREAD

**Issue by sergpy** [linq2db/linq2db#174]
My Code is: 
       var p = new Models.Products
            {
                Price = 12.33m,
            };
       var id = conn.InsertWithIdentity(p);   // error!!

```
public class Products
{
    [PrimaryKey, Identity]
    [Column("ProductID")]
    public int ID { get; set; }

    public decimal Price;
}  
```

I fix it in  AccessDataProvider.cs, SetParameterType():
    case DataType.Decimal    :
    case DataType.VarNumeric : 
          ((OleDbParameter)parameter).OleDbType = OleDbType.Currency; return;

**Comment by ili** [comment]
It should work now
