### ISSUE TITLE
Update list of reserved words for Firebird

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1741]
See https://stackoverflow.com/questions/56374260/linq2db-not-able-to-create-table-for-inherit-class

right now we use list of reserved words from FB 2.5 (I assume). We need to add new reserved words from later versions.
E.g. list for 3.0 is here https://firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-reswords.html#rnfb30-reswords-new
but also newer versions should be checked

**Comment by Aceto1** [comment]
Hey, mind if I give it a shot?

**Comment by MaceWindu** [comment]
You are welcome!

**Comment by Aceto1** [comment]
The Firebird reserved words list is incomplete as it is even for Firebird 2.5. I noticed that some of the mising keywords seem to be in the common ReservedWords.txt file though. But it turnes out that the common list never gets checked should a provider specific one exist. 
Is that intended? Should I add the reserved words that are missing to the firebird specific file or change the checking method to include common reserved words?

**Comment by MaceWindu** [comment]
Just add missing words to firebird-specific file

**Comment by MaceWindu** [comment]
BTW, can you organize list of FB words by version and add header line to each section like
`# version 2.5 <url_to_list_here>`? This will require list load logic update to ignore lines starting from #

**Comment by Aceto1** [comment]
Sure thing!

**Comment by MaceWindu** [comment]
We want to release 2.7.2 bugfix release today. Will you be able to submit PR today or we should move this issue to next release?

**Comment by Aceto1** [comment]
I can probably get one ready in like an hour. I just got home.

**Comment by MaceWindu** [comment]
Yep!
