### ISSUE TITLE
Error Table 'public.table' not found

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1753]
Dear devs,

I faced an issue on generation of classes from a database.
Before, we were generating classes when tables were placed in different schemas without any error.
Now we moved all the tables to the "public" schema, and on generation we have an error.
I haven't find any help in your documentation about that.
The error is:

```
Exception message: #error Table 'public.logged_actions' not found.
```

And as comment, in existing tables part we have
```
/*
	Existing tables:

	logged_actions
	...
        (40 more tables)
 */
```

The same table, found in "public" schema but gives an error.
I know it should be simple to resolve, but I haven't found in documentation how.

Can you help please?

### Environment details
linq2db version: 2.7.0
Database Server: Postgres
Database Provider: PostgreSQL 10.3
Operating system: Windows 10 x64 Pro
.NET Framework: .Net Core 2.2

**Comment by MaceWindu** [comment]
If you just need to get rid of #error directives - set [GenerateProcedureErrors](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB.Templates/README.md) to false in your tt file.

for some reason schema retrieval for one of your functions fail with this error - if it is not a broken function - it will help us to fix it if you can provide more details how this function use aforementioned table

**Comment by YXMagnuMXY** [comment]
This is a code of the trigger function - "if_modified_func" that is store in "public" schema.
```
DECLARE
    audit_row public.logged_actions;
    include_values boolean;
    log_diffs boolean;
    h_old public.hstore;
    h_new public.hstore;
    excluded_cols text[] = ARRAY[]::text[];
BEGIN
    IF TG_WHEN <> 'AFTER' THEN
        RAISE EXCEPTION 'if_modified_func() may only run as an AFTER trigger';
    END IF;


    audit_row = ROW(
        nextval('logged_actions_event_id_seq'), -- event_id
        TG_TABLE_SCHEMA::text,                        -- schema_name
        TG_TABLE_NAME::text,                          -- table_name
        0,                                            -- record_id
        current_timestamp,                            -- action_tstamp_tx
        clock_timestamp(),                            -- action_tstamp_clk
        inet_client_addr(),                           -- client_addr
        inet_client_port(),                           -- client_port
        current_query(),                              -- top-level query or queries (if multistatement) from client
        substring(TG_OP,1,1),                         -- action
        NULL, NULL                                    -- row_data, changed_fields
        );


    IF NOT TG_ARGV[0]::boolean IS DISTINCT FROM 'f'::boolean THEN
        audit_row.client_query = NULL;
    END IF;

    IF TG_ARGV[1] IS NOT NULL THEN
        excluded_cols = TG_ARGV[1]::text[];
    END IF;

    IF (TG_OP = 'UPDATE' AND TG_LEVEL = 'ROW') THEN
        audit_row.row_data = hstore(OLD.*) - excluded_cols;
        audit_row.changed_fields =  (hstore(NEW.*) - audit_row.row_data) - excluded_cols;
        IF audit_row.changed_fields = hstore('') THEN
            -- All changed fields are ignored. Skip this update.
            RETURN NULL;
        END IF;
        audit_row.record_id = NEW.id;
    ELSIF (TG_OP = 'INSERT' AND TG_LEVEL = 'ROW') THEN
        audit_row.row_data = hstore(NEW.*) - excluded_cols;
        audit_row.record_id = NEW.id;
    ELSIF (TG_OP = 'DELETE' AND TG_LEVEL = 'ROW') THEN
        audit_row.row_data = hstore(OLD.*) - excluded_cols;
        audit_row.record_id = OLD.id;
    ELSE
        RAISE EXCEPTION '[if_modified_func] - Trigger func added as trigger for unhandled case: %, %',TG_OP, TG_LEVEL;
        RETURN NULL;
    END IF;
    INSERT INTO logged_actions VALUES (audit_row.*);
    RETURN NULL;
END;
```
Each table has a trigger, that runs on Insert, on Update and Delete this function.
In Declare section, if I delete the word ```public.``` in front of logged_actions or hstore, it gives error.
Is this what you asked?

PS: I tried GenerateProccedureErrors = false, on generation, but no luck.

In database is the problem I think...
In PGAdmin I found now this error:
```
ERROR:  relation "logged_actions_id_seq" does not exist
LINE 2:         nextval('logged_actions_id_seq'), -- id
                        ^
QUERY:  SELECT ROW(
        nextval('logged_actions_id_seq'), -- id
        TG_TABLE_SCHEMA::text,                        -- schema_name
        TG_TABLE_NAME::text,                          -- table_name
        0,                                            -- record_id
        current_timestamp,                            -- action_tstamp_tx
        clock_timestamp(),                            -- action_tstamp_clk
        inet_client_addr(),                           -- client_addr
        inet_client_port(),                           -- client_port
        current_query(),                              -- top-level query or queries (if multistatement) from client
        substring(TG_OP,1,1),                         -- action
        NULL, NULL                                    -- row_data, changed_fields
        )
CONTEXT:  PL/pgSQL function public.if_modified_func() line 14 at assignment
```
The error is that I should put in front the schema..."public"..
I mean - public.logged_actions_id_seq................
Very strange.

**Comment by YXMagnuMXY** [comment]
I moved the table "logged_actions" to a new schema - "audit"
So now I have only two schemas - public(40 tables) and audit(1 table).
Now, I put ```GetSchemaOptions.ExcludedSchemas = new[] { "audit"};``` and I got the same error to first table from the public schema.

**Comment by YXMagnuMXY** [comment]
I found the error...
After:
```LoadPostgreSQLMetadata("x", "x", "x", "x", "x");```
we've put a foreach loop, to give "IIdentifiable" as BaseClass for each class generated.
```foreach (var table in Tables.Values)
		GetTable(table.Schema + "." + table.TableName).BaseClass = "IIdentifiable";
```
I changed it to
 ```foreach (var table in Tables.Values)
		GetTable(table.TableName).BaseClass = "IIdentifiable";``` and no works.

**Comment by MaceWindu** [comment]
right, was just looking at code and had suspition that somewhere we passed wrong table name to GetTable - with default schema prefix

**Comment by YXMagnuMXY** [comment]
Sorry for disturbing, but I was trying to fix this from morning till now ))

**Comment by sdanyliv** [comment]
@YXMagnuMXY, why do you call `GetTable`? This code should work:
```cs
foreach (var table in Tables.Values)
  table.BaseClass = "IIdentifiable";
```

**Comment by YXMagnuMXY** [comment]
Yeah, and is working.
I found this in an example...somewhere, don't remember where. But your part of code is logical ))
Thank you.

**Comment by sdanyliv** [comment]
If you are trying to customize generation, you have to read this doc: [useful-members-and-data-structures](https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#useful-members-and-data-structures)
