### ISSUE TITLE
Set ConfigureAwait to false

### ISSUE THREAD

**Issue by DMokhnatkin** [linq2db/linq2db#1754]
Hello, have you come to a conclusion about using ConfigureAwait(false)?
We have the same problem as #1366.
We are trying to migrate to async database access, but some old parts of our system execute it synchronously. Sometimes it leads to deadlocks.

As an example: we are forced to call such methods synchronously in Html.RenderPartial(), because in hasn't async implementation in MVC5. And it leads to deadlock.

**Comment by MaceWindu** [comment]
Yes, we need to do it (probably as an option). I was thinking about this change couple of days ago.

**Comment by DMokhnatkin** [comment]
@MaceWindu, thanks.

**Comment by sdanyliv** [comment]
@MaceWindu, it can not be an option, we have to put ConfigureAwait(false) for every await in library.
@andrewvk, can you explain why we do not do that?

**Comment by MaceWindu** [comment]
@sdanyliv  I meant something like ConfigureAwait(Configuration.ConfigureAwaitValue), but probably you are right and we just need to pass false

**Comment by andrewvk** [comment]
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by MaceWindu** [comment]
also see https://github.com/aspnet/EntityFrameworkCore/issues/12270#issuecomment-396779527

I think it should be hidden behind option and disabled by default

**Comment by sdanyliv** [comment]
My vote for implementing this. Refactoring synchronous code to async version usually has several steps and it is bad to fight with deadlocks on early stage.
