### ISSUE TITLE
Wrong SQL Stamatement with nullable value

### ISSUE THREAD

**Issue by advapiIT** [linq2db/linq2db#1755]
Describe your issue.

I've faced this issue when I've a linq2db statement and checking for the null value.
Consider this sample
```cs
 var categorieSP = (from c in mainContext.CondizioniCategorie
                            .LoadWith(x => x.RsmPolizzaOpzionis).LoadWith(x =>
                                x.RsmPolizzaOpzionis.FirstOrDefault().RsmOpzioniCompagnia)
                            .LoadWith(x => x.Categorie)
                            .LoadWith(x => x.GruppoRamo)
                            .LoadWith(x => x.Parametri)
                            .LoadWith(x => x.TipoRischio)
                        where c.IdPolizza == idPolizza
                              && (attiva.HasValue || attiva.Value && c.DataAnnullamento == null ||!attiva.Value && c.DataAnnullamento != null)
                        select c);
```
This generates the following SQL Statement

```sql
....
	[c_1].[ID_POLIZZA] = @idPolizza AND ((**NULL IS NOT NULL** OR 1 = 0 AND [c_1].[DATA_ANNULLAMENTO] IS NULL) OR 1 = 1 AND [c_1].[DATA_ANNULLAMENTO] IS NOT NULL)
```
while if I use
```cs
var categorieSP = (from c in mainContext.CondizioniCategorie
                            .LoadWith(x => x.RsmPolizzaOpzionis).LoadWith(x =>
                                x.RsmPolizzaOpzionis.FirstOrDefault().RsmOpzioniCompagnia)
                            .LoadWith(x => x.Categorie)
                            .LoadWith(x => x.GruppoRamo)
                            .LoadWith(x => x.Parametri)
                            .LoadWith(x => x.TipoRischio)
                        where c.IdPolizza == idPolizza
                              && (attiva== null || attiva.Value && c.DataAnnullamento == null ||!attiva.Value && c.DataAnnullamento != null)
                        select c);
```
it generates the following
where statement
```sql
[c_1].[ID_POLIZZA] = @idPolizza AND ((**1 = 1** OR 1 = 0 AND [c_1].[DATA_ANNULLAMENTO] IS NULL) OR 1 = 1 AND [c_1].[DATA_ANNULLAMENTO] IS NOT NULL)
```
In my particular case, it cuts off some data I need to show, but I don't understand why it generate NULL IS NOT NULL

**Comment by sdanyliv** [comment]
Thanks for reporting, will check. For now i consider to rewrite query in the following way:
```cs
 var categorieSP = from c in mainContext.CondizioniCategorie
                            .LoadWith(x => x.RsmPolizzaOpzionis).LoadWith(x =>
                                x.RsmPolizzaOpzionis.FirstOrDefault().RsmOpzioniCompagnia)
                            .LoadWith(x => x.Categorie)
                            .LoadWith(x => x.GruppoRamo)
                            .LoadWith(x => x.Parametri)
                            .LoadWith(x => x.TipoRischio)
                        select c;
if (attiva.HasValue)
   categorieSP  = categorieSP.Where(c => c.DataAnnullamento == null);
else
   categorieSP  = categorieSP.Where(c => c.DataAnnullamento != null);
```

**Comment by detoxhby** [comment]
@sdanyliv is this related to #1750 ? (I cannot upgrade if regression still appears in cases like this; although the currently stable version results in overall correct conditions as far as we were able to check by smoke tests)

**Comment by sdanyliv** [comment]
It is another case which we have to cover. But not tested yet maybe it is already solved.

**Comment by MaceWindu** [comment]
```cs
&& (attiva.HasValue || attiva.Value && c.DataAnnullamento == null ||!attiva.Value && c.DataAnnullamento != null)
```
this actually doesn't make sense. Did you mean `!attiva.HasValue`?

**Comment by MaceWindu** [comment]
I've created tests for your issue and (taking into account missing HasValue negation) current master branch (future 2.8) generate proper SQL for both approaches: `!HasValue` and `== null`

`== null` appoach generates very clean SQL, so I would assume it is already fixed:
```SQL
-- attiva = false
WHERE [c_1].[ParentID] = @id AND [c_1].[Value1] IS NOT NULL
-- attiva = true
WHERE [c_1].[ParentID] = @id AND [c_1].[Value1] IS NULL
-- attiva is null
WHERE [c_1].[ParentID] = @id
```

for !HasValue, generated SQL is still no good, so we will fix it:
```SQL
-- for any attiva value
WHERE [c_1].[ParentID] = @id AND ((@flag IS NULL OR 1 = @Value0 AND [c_1].[Value1] IS NULL) OR 1 <> @Value0 AND [c_1].[Value1] IS NOT NULL)
```

**Comment by advapiIT** [comment]
Excuse me, is there a current version that's safe to use? or when the 2.8 will be avaiable?
The "hack" u suggested me doesn't cover all the cases so I've got some regressions on my code behavior

**Comment by MaceWindu** [comment]
2.8.0 scheduled for release for tomorrow #1826

**Comment by MaceWindu** [comment]
if you need it today, you can fetch it from here https://ci.appveyor.com/project/igor-tkachev/linq2db/builds/26204489/artifacts
if there will no regressions found, it will be same as release version

**Comment by advapiIT** [comment]
awesome, for now I update to this version, thanks

**Comment by MaceWindu** [comment]
nuget still labeled as 2.7.4, but it is built from 2.8 sources

**Comment by advapiIT** [comment]
Excuse me, I can directly set it as nuget source? right, I've to reference
them manually?

Thanks

**Comment by MaceWindu** [comment]
You can:
- unpack it (nuget is just renamed zip) and reference assembly directly
or 
- drop it in folder on your pc and setup custom nuget source in visual studio to target this folder

**Comment by advapiIT** [comment]
Thanks
