### ISSUE TITLE
Analytic Functions, Sum and GroupBy

### ISSUE THREAD

**Issue by Brains** [linq2db/linq2db#1763]
## Task
I have a table with events, each one occured at some timepoint. I need to:
1. Group events per `User` and `Process`
2. Calculate `intervals` between adjacent events for each group
3. Filter out all `intervals` greater than `5` minutes
4. Sum remained events so each `User * Process` group contains a scalar value
5. Plot onto the chart where `Y` axis for `Users`, `X` for `Processes`, bubbles radius for total `Sum` (overall duration excluding `Idle` intervals `> 5 mins` )

![image](https://user-images.githubusercontent.com/5301844/59554122-34396d80-8fa7-11e9-828f-fdcc71a82724.png)

## Code
The only working approach is below. Commented parts are described next. 
Sorry for ugly names in DB, not my work, suffer from it too.

```cs
using LinqToDB;
using LinqToDB.DataProvider.SqlServer;
using System;
using System.Linq;

namespace Tests
{
    public class Process_IndexedEvents
    {
        public int eventIndex;
        public int processID;
        public string eventUser;
        public DateTime eventTime;
    }

    class Program
    {
        const string ConnectionString =
            @"Server=DESKTOP\SQLEXPRESS; Database=Automata; Integrated Security=true;";

        static void Main()
        {
            using (var db = SqlServerTools.CreateDataConnection(ConnectionString))
            {
                // LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true
                // LinqToDB.Common.Configuration.Linq.PreloadGroups = true

                var query =
                    from o in from x in db.GetTable<Process_IndexedEvents>()
                              select new
                              {
                                  User = x.eventUser,
                                  Proc = x.processID,
                                  Diff = x.eventTime - 
                                         Sql.Ext
                                            .Lag(x.eventTime, Sql.Nulls.None)
                                            .Over()
                                            .PartitionBy(x.eventUser, x.processID)
                                            .OrderBy(x.eventTime)
                                            .ToValue()
                              }
                              //into y
                              //where 0 < y.Diff.TotalMinutes && y.Diff.TotalMinutes <= 5
                              //select y
                    group o by new {o.User, o.Proc}
                    into g
                    select g;

                query.Take(10)
                     .ToList()
                     .Select(x => new
                     {
                         x.Key,
                         Count = x.Count(),
                         Sum   = x.Where(y => 0 < y.Diff.TotalMinutes 
                                               && y.Diff.TotalMinutes <= 5)
                                  .Sum(y => y.Diff.TotalMinutes)
                     })
                     .ToList()
                     .ForEach(Console.WriteLine);
            }
        }
    }
}
```
## Sum
Attempt to calculate final `Sum` from step `4` not locally but on `SQL` side:
```cs
query.Take(10)
  // .ToList()
     .Select(x => new
```
fails with:
```cs
Unhandled Exception: System.ArgumentException: Property 'System.TimeSpan Diff' is not defined for type 'System.Linq.IGrouping`2[<>f__AnonymousType1`2[System.String,System.Int32], <>f__AnonymousType0`3[System.String,System.Int32,System.TimeSpan]]'

   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at LinqToDB.Expressions.Extensions.TransformX(MemberExpression e, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1259
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 995
   at LinqToDB.Expressions.Extensions.TransformX(MemberExpression e, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1259
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 995
   at LinqToDB.Linq.Builder.SelectContext.GetExpression(Expression expression, Expression levelExpression, Expression memberExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 1062
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 935
   
   ...
```
Sum inside query:
```cs
group o by new {o.User, o.Proc}
into g
select new
{
	g.Key,
	// Count = g.Count(),
	Sum = g // .Where(y => 0 < y.Diff.TotalMinutes && y.Diff.TotalMinutes <= 5)
		   .Sum(y => y.Diff.TotalMinutes)
};
```
fails with:
```cs
Unhandled Exception: System.Data.SqlClient.SqlException: Column 'Process_IndexedEvents.eventTime' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.

Windowed functions cannot be used in the context of another windowed function or aggregate.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   
   ...
```

## Filter
Attempt to filter intervals from step `3` not locally but on `SQL` side:
```cs
into y
where 0 < y.Diff.TotalMinutes && y.Diff.TotalMinutes <= 5
select y
```
fails with
```cs
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass45_0.<ConvertToIndexInternal>b__7(Int32 n, IBuildContext ctx, Expression ex, Int32 l, Expression _) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 576
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 994
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 572
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 433
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SubQueryContext.cs:line 39

...
```

## SQL Script
This `sql` query I used as source for `C#` code works perfectly inside `SSMS`
Replicated in `C#` even derived table
```sql
SELECT
  User_Groups    AS [Dept],
  eventUser      AS [User],
  Process_Name   AS [Proc],
  SUM(i) / 60.0  AS [Sum]
FROM (
  SELECT
    eventUser,
    processID,
    DATEDIFF (
      minute,
      LAG(eventTime) OVER(PARTITION BY eventUser, processID ORDER BY eventTime),
      eventTime) AS i
  FROM Process_IndexedEvents) AS o
INNER JOIN Users ON eventUser = [User]
INNER JOIN Processes AS p ON o.processID = p.ProcessID
WHERE 0 < i AND i <= 5
GROUP BY
  User_Groups,
  eventUser,
  Process_Name
```

## Other
**Settings**
Settings adjustment didn't help
```cs
LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true
LinqToDB.Common.Configuration.Linq.PreloadGroups = true
```
**Analytic Functions**
The same problems occur with rest `Analytic` functions

**F#**
Situation is the same, whether using `fluent syntax` or `F# query { }` syntax

## Environment details
linq2db version: **2.7.4**
Database Server: **MS SQL Express**
Database Provider: **MS SQL Server**
Operating system: **Windows 10**
.NET Framework: **4.5.2**

**Comment by Brains** [comment]
## Other random exceptions which occurred during testing
```cs
Unhandled Exception: LinqToDB.Linq.LinqException: 'x.processID' cannot be converted to SQL.

   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1089
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 705
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass121_0.<ConvertToSql>b__1(Expression _) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 984
   at LinqToDB.Sql.ExtensionAttribute.ConvertHelper.Convert(Expression exp) in C:\projects\linq2db\Source\LinqToDB\Sql\Sql.ExtensionAttribute.cs:line 691
   at LinqToDB.Sql.ExtensionAttribute.BuildExtensionParam(IDataContext dataContext, SelectQuery query, MemberInfo member, Expression[] arguments, ConvertHelper convertHelper) in C:\projects\linq2db\Source\LinqToDB\Sql\Sql.ExtensionAttribute.cs:line 634
   at LinqToDB.Sql.ExtensionAttribute.BuildFunctionsChain(IDataContext dataContext, SelectQuery query, Expression expr, ConvertHelper convertHelper) in C:\projects\linq2db\Source\LinqToDB\Sql\Sql.ExtensionAttribute.cs:line 539

   ...
```

```cs
Unhandled Exception: System.Data.SqlClient.SqlException: Cannot perform an aggregate function on an expression containing an aggregate or a subquery.

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()

   ...

   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 450
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__10`1.MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 344
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.Program.Main() in C:\Projects\Dashboard.WPF\Tests\Program.cs:line 47
```

**Comment by Brains** [comment]
Ideally would be to perform everything on `SQL Server` side without local processing

Also would like to `GroupBy (x.eventUser, x.processID)` as first step to not use `.PartitionBy (x.eventUser, x.processID)` then. As I hope this should reduce groping operations from `2` to `1`.
Something like this:
```cs
                db.GetTable<Process_IndexedEvents>()
                  .GroupBy(x => new {x.eventUser, x.processID})
                  .Select(xs => new
                  {
                      xs.Key,
                      Intervals =
                          xs.Select(x => new
                            {
                                User = x.eventUser,
                                Proc = x.processID,
                                Diff = x.eventTime -
                                       Sql.Ext
                                          .Lag(x.eventTime, Sql.Nulls.None)
                                          .Over()
                                          .PartitionBy(x.eventUser, x.processID)
                                          .OrderBy(x.eventTime)
                                          .ToValue()
                            })
                            .Where(y => 0 < y.Diff.TotalMinutes && y.Diff.TotalMinutes <= 5)
                  })
                  .Select(x => new
                  {
                      x.Key,
                      Count = x.Intervals.Count(),
                      Sum = x.Intervals.Sum(y => y.Diff.TotalHours)
                  })
                  .ToList()
                  .ForEach(Console.WriteLine);
```

**Comment by Brains** [comment]
Explored https://github.com/linq2db/linq2db/issues/679, https://github.com/linq2db/linq2db/pull/775, https://github.com/linq2db/linq2db/issues/73, https://github.com/linq2db/linq2db/issues/699, https://github.com/linq2db/linq2db/issues/781. 
Unfortunately didn't find any workaround (maybe just searched badly?)

**Comment by sdanyliv** [comment]
@Brains, let me check.

**Comment by Brains** [comment]
Sure, please, if you can. Because I've tried everything I could, no more ideas.
Thank you for the quick response.

**Comment by sdanyliv** [comment]
5 minutes, rewriting your query

**Comment by sdanyliv** [comment]
There is your query (not tested for business correctnes):
```cs
var query =
	from x in db.GetTable<Process_IndexedEvents>()
	select new
	{
		User = x.eventUser,
		Proc = x.processID,
		Diff = Sql.DateDiff(Sql.DateParts.Minute,
			Sql.Ext
				.Lag(x.eventTime, Sql.Nulls.None)
				.Over()
				.PartitionBy(x.eventUser, x.processID)
				.OrderBy(x.eventTime)
				.ToValue(), x.eventTime),
	};

query = query.Where(q => q.Diff > 0 && q.Diff <= 5);

var finalQuery = from q in query
	from u in db.GetTable<Users>().InnerJoin(u => u.UserId == q.User)
	from p in db.GetTable<Processes>().InnerJoin(p => p.ProcessId == q.Proc)
	group q by new { q.User, u.UserGroups, p.ProcessName }
	into g
	select new
	{
		g.Key.User,
		g.Key.ProcessName,
		g.Key.UserGroups,
		Sum = g.Sum(e => e.Diff) / 60
	};


finalQuery
	.Take(10)
	.ToList()
	.ForEach(Console.WriteLine);
```
Generated SQL:
```sql
SELECT TOP (10)
	[q].[User_1],
	[p].[ProcessName],
	[u].[UserGroups],
	Sum([q].[Diff])
FROM
	(
		SELECT
			DateDiff(minute, LAG([x].[eventTime]) OVER(PARTITION BY [x].[eventUser], [x].[processID] ORDER BY [x].[eventTime]), [x].[eventTime]) as [Diff],
			[x].[eventUser] as [User_1],
			[x].[processID] as [Proc]
		FROM
			[Process_IndexedEvents] [x]
	) [q]
		INNER JOIN [Users] [u] ON ([u].[UserId] IS NULL AND [q].[User_1] IS NULL OR [u].[UserId] = [q].[User_1])
		INNER JOIN [Processes] [p] ON [p].[ProcessId] = [q].[Proc]
WHERE
	[q].[Diff] > 0 AND [q].[Diff] <= 5
GROUP BY
	[q].[User_1],
	[u].[UserGroups],
	[p].[ProcessName]
```
Simple tip: if you rewriting SQL, separate it by parts, starting from subqueries.

**Comment by Brains** [comment]
Awesome, works like a charm.
Thank you very much. 
Didn't expect such quick resolution. For most other open-source libraries I would need to explore source code before got an advice (if ever). 

> Simple tip: if you rewriting SQL, separate it by parts, starting from subqueries.

Thanks. 
However with your awesome library it seems I will not need to use plain `SQL` at all, love this idea.

## Exploration
But I can't sleep until find out the root cause. Can you help me by elaborating your solution a little bit? Actually, it's not urgent of course, ok to do it later. 

So I explored your solution. 

Replaced `Sql.DateDiff` because the same errors appeared even when called `LAG` for pure `int` column, like `processID` (sorry, totally forgot to wrote about that in my previous messages, maybe tired). Your solution still worked.

Then removed
```cs
query = query.Where(q => q.Diff > 0 && q.Diff <= 5);
```
failed with
```cs
Unhandled Exception: System.Data.SqlClient.SqlException: 
Column 'Process_IndexedEvents.eventTime' is invalid in the 
select list because it is not contained in either an 
aggregate function or the GROUP BY clause.

Windowed functions cannot be used in the context of 
another windowed function or aggregate.
```
Ok, probably that, it's warm.

Moved `where` clause into second `query`, still worked.

Removed `joins`, still worked.

Current state
```cs
var query =
    from x in db.GetTable<Process_IndexedEvents>()
    select new
    {
        User = x.eventUser,
        Proc = x.processID,
        Diff = (x.eventTime - Sql.Ext
                                 .Lag(x.eventTime, Sql.Nulls.None)
                                 .Over()
                                 .PartitionBy(x.eventUser, x.processID)
                                 .OrderBy(x.eventTime)
                                 .ToValue()).TotalMinutes,
    };

var finalQuery = from q in query
                 where q.Diff > 0 && q.Diff <= 5
                 group q by new {q.User,q.Proc}
                 into g
                 select new
                 {
                     g.Key.User,
                     g.Key.Proc,
                     Sum = g.Sum(e => e.Diff) / 60.0
                 };
```
So can you explain what is the magic of `where` clause? I thought that root cause was related to `Windowed functions cannot be used in the context of another windowed function or aggregate`. I need to know, otherwise will return with a new query after few days.

**Comment by Brains** [comment]
I thought that due to being newbie in `SQL` did something really stupid, so tried to find it out the whole day today. However, your solution looks pretty similar. But some little subtle difference is hidden there. Probably about `Analytic Functions`, or `GroupBy` or else?

Thanks again for your help.

**Comment by sdanyliv** [comment]
Yes we know about this problem. Will find time to fix that. Currently my mind is focused on Eager Loading implementation.
We have to force subqueries creation when analytic functions are in projection. Where clause  is one of the way to do that.

And yes linq2db is focused in SQL creation (i hope any), and if you can not generate some SQL - come here and we will find the way.

**Comment by Brains** [comment]
> Yes we know about this problem

Ok, thanks. I thought that was completely my mistake. Always good to discover I am not so bad.

> We have to force subqueries creation when analytic functions are in projection. Where clause is one of the way to do that.

Will keep in mind about analytic functions. 
Even if there is no `where` clause by design, I can always insert something returns `true`.

> And yes linq2db is focused in SQL creation (i hope any), and if you can not generate some SQL - come here and we will find the way.

Thank you. 
You have a good guide already: [How to teach LINQ to DB convert custom .NET methods and objects to SQL](http://blog.linq2db.com/2016/06/how-to-teach-linq-to-db-convert-custom.html). Will try to employ  it too. 
In today case I got different errors all the time, definitely the problem was not in a single function. So I asked here, wise decision. 
##
Before, I was going to close the issue, since my particular problem was solved. However, if it is internal issue, maybe leave it open. I am taking no action, you decide what to do.
##
Thanks again for the great help.

**Comment by Brains** [comment]
I think this is related, so won't open a new issue:

**`Sql.Nulls.Ignore`**
```cs
Sql.Ext.Lag(x.eventTime, Sql.Nulls.Ignore)
```
fails with
```cs
Unhandled Exception: System.Data.SqlClient.SqlException: Incorrect syntax near 'IGNORE'.
```

**`Sql.Nulls.Respect`**
```cs
Sql.Ext.Lag(x.eventTime, Sql.Nulls.Respect)
```
fails with
```cs
Unhandled Exception: System.Data.SqlClient.SqlException: Incorrect syntax near 'RESPECT'.
```
Not a problem for me, just noted.

**Comment by sdanyliv** [comment]
I’m leaving it open. Just to track subqueries problem. 
We have to teach our optimizer to do not use analytic functions and custom aggregates in where clause and possible in other SQL clauses.

Other issues that you have spotted is just non-informative error messages.

You are trying to use extended LAG function syntax. Which maybe only supported by ORACLE. We do not prevent extended syntax call and always generate SQL. See note below https://linq2db.github.io/articles/sql/Window-Functions-%28Analytic-Functions%29.html#resulting-sql

**Comment by Brains** [comment]
> Other issues that you have spotted is just non-informative error messages.

Yes, it's true. 
I've formatted exception messages before put into the ticket, but the original ones looked like that in `Console` window (it's faster to examine than in debugger, less clicks needed):
```
Unhandled Exception: System.Data.SqlClient.SqlException: Column 'Process_IndexedEvents.eventTime' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
Windowed functions cannot be used in the context of another windowed function or aggregate.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.
```
important line
```
Windowed functions cannot be used in the context of another windowed function or aggregate.
```
is hard to distinguish 

> You are trying to use extended LAG function syntax. Which maybe only supported by ORACLE. We do not prevent extended syntax call and always generate SQL. See note below 

Ok, I see. Thanks
I saw that important note, even few times, it was the reason to implement the query in pure `SQL`, for exclude such problems. However, it's quite hard to get used the idea of different `SQL`  implementations which support not all features, like to have `C#` implementation without lambdas, `async \ await` or else.

**Comment by sdanyliv** [comment]
> I saw that important note, even few times, it was the reason to implement the query in pure SQL, for exclude such problems. However, it's quite hard to get used the idea of different SQL implementations which support not all features, like to have C# implementation without lambdas, async \ await or else.

For Window functions we have to do that, they are partially implemented in other databases, but we don’t want to limit other providers. Usually people who use Window functions know about their limitations. For other functionality we are trying to emulate, if it is possible.
Main idea, to do not write raw SQL - it can not be reused or is hard to modify. You queries are checked by C# compiler, they are type safe, they can be combined, can be reused for Delete, Update, Insert into another table.

**Comment by Brains** [comment]
> For Window functions we have to do that, they are partially implemented in other databases, but we don’t want to limit other providers.

Yes, sure, I totally understand, no questions. I would do exactly in the same way as you.

> Usually people who use Window functions know about their limitations. For other functionality we are trying to emulate, if it is possible.

True, I have just a brief look on `SQL` and its functions, still newbie. It's the only reason why the idea of different SQL implementation is strange for me. Of course, I am not saying that something is wrong in your library design, in no way. 

> Main idea, to do not write raw SQL - it can not be reused or is hard to modify. You queries are checked by C# compiler, they are type safe, they can be combined, can be reused for Delete, Update, Insert into another table.

It works as intended. 
I am really happy to find your awesome library, no need to use raw `SQL` at all. I learned it a little bit, but don't like the language already, `SQL` is pretty weird for me (`select` is always first but executed almost last, different behavior of standard clauses depending on context and other stuff).

**Comment by sdanyliv** [comment]
> SQL is pretty weird for me (select is always first but executed almost last, different behavior of standard clauses depending on context and other stuff).

It is a history that we have to admit :) But if you want to write high performance Database applications, SQL knowledge is must. Our library do not hide SQL from the users, as other ORM frameworks do, but gives more powerful way to manipulate with queries.

**Comment by Brains** [comment]
Yes, true, I have noticed that.
Thank you for the library.

**Comment by sdanyliv** [comment]
Let me share some examples, how you can use our library in advanced mode
High performance pagination using Window Functions
https://github.com/linq2db/linq2db/issues/1402#issuecomment-438961009

And my thoughts, why you don't have use Repository Pattern (especially with our library) if you want to write performance critical applications and do not want to spend time in tweaking additional abstraction:
https://github.com/linq2db/linq2db/issues/1698#issuecomment-486174854
I saw several projects which development was critically slow down because of that. And, damn it, they use this anti-pattern again. I saw one quote about repository pattern: "you bought 8000$ sofa and covered it by envelope" - very good explanation of this pattern.

**Comment by Brains** [comment]
Thank you a lot.

> High performance pagination using Window Functions

Yes, I need to implement some sort of pagination, but as a viewer by `date` period, that is all events per `Day, Week, Month`. The simplest `where` clause from `date` to `date` should work. But can it be improved by using `Window Functions`, not likely?

> And my thoughts, why you don't have use Repository Pattern 

Agree here. `LinqToDB` is already a great abstraction (especially with powerful `associations`), no reasons to introduce another one.

> And, damn it, they use this anti-pattern again.

Probably because they used to do so before, habits. Also it's recommended everywhere very often, including for testing purposes. 

> you bought 8000$ sofa and covered it by envelope

I would also cover by envelope, to not dirty it or screw up the surface, like with phone.

**Comment by sdanyliv** [comment]
> Yes, I need to implement some sort of pagination, but as a viewer by date period, that is all events per Day, Week, Month. The simplest where clause from date to date should work. But can it be improved by using Window Functions, not likely?

It is something different. For example, you have query:
```cs
var query = db.GetTable<Something>().Where(s => s.Date > someDate);
```
But you need to know how many records are affected by this query and return only needed page:
```cs
var itemsInPage = QueryPaginator.Paginate(query, currentPage, pageSize, out totalRecords);
```
Then you can inform UI that not everything is returned and how many records are left.

**Comment by Brains** [comment]
Nice. 
Thanks again.

**Comment by MaceWindu** [comment]
Guys, it is hard to track tasks when multiple issues discussed in single topic :smile: 

I've moved one issue to https://github.com/linq2db/linq2db/issues/1799

Other issues as I can see caused by use of columns, not included in group/window. SQL is not C# and doesn't work like that.

If you still think there is more than one issue - please open separate issue for each.
