### ISSUE TITLE
MSSQL's STRING_AGG do not allow mixing types NVarchar and VarChar in expression and separator.

### ISSUE THREAD

**Issue by sdanyliv** [linq2db/linq2db#1765]
Original issue is here: 
http://rsdn.org/forum/prj.rfd/7473620.1

Also we have to check other servers for limitation.

**Comment by epetrukhin** [comment]
Issue title slightly wrong. Documentation states that if the input expression is type VARCHAR, the separator cannot be type NVARCHAR (https://docs.microsoft.com/en-us/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-2017#remarks). So, separator can be of type NVARCHAR, but only if expression is NVARCHAR too.
