### ISSUE TITLE
Insert with identity of multiple objects

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1766]
I need to insert multiple objects wich get an ID from the Database.
Is there a way to do this in a more perfromat way instead of multiple times calling insertwithidentity.
I also only need the Id of the last one, so I could calculate the before ones

**Comment by sdanyliv** [comment]
I assume it is Sqlite. So just bulk copy in transaction and `SELECT last_insert_rowid()`

**Comment by jogibear9988** [comment]
No it's not only sqlite.

We use mssql, sqlite,...
Is there no independent way?

**Comment by sdanyliv** [comment]
How do you plan to insert many records? BulkCopy for sure. Not we do not have universal mechanism. Each database have it's own features.

**Comment by jogibear9988** [comment]
Kay, thx
