### ISSUE TITLE
APM (application performance monitors) & linq2db

### ISSUE THREAD

**Issue by MightyDesertFox** [linq2db/linq2db#1770]
Anyone using linq2db and an APM?

I'm trying to integrate my application using linq2db to Raygun and I'm failing miserably. 

Thought?

**Comment by sdanyliv** [comment]
Just checked what they are documented. I can not find any problems with that https://raygun.com/languages/dotnet
Just install package and send statistics. To turn on linq2db tracing, correct this code snippet which enables console logging, to send statistic using Raygun client class:
```cs
LinqToDB.Data.DataConnection.TurnTraceSwitchOn();
LinqToDB.Data.DataConnection.WriteTraceLine =
      (message, displayName) => { Console.WriteLine($"{message} {displayName}"); };
```

**Comment by MightyDesertFox** [comment]
Hi @sdanyliv 

Thanks for the help. I'm able to see everything in Raygun already, but NO query data. 

In fact, even without the code you provided, I was able to see Oracle (the DB i'm using) connections opening and all, but no query information.

**Comment by sdanyliv** [comment]
If you do not use client package, that means that they instrument running application, which can be problematic when they can not find entry point for IDbConnection in particular library. Maybe .Net Core version is a problem.

It’s just my thoughts.

**Comment by MightyDesertFox** [comment]
Would you recommend something? Im quite new into this instrumentation process (also linq2db)...

**Comment by sdanyliv** [comment]
Why just not install Raygun client package? It should work now.

I don’t know how they instrument running application but it is complicated thing. It is how profilers work. And looks like they have failed here. Better to contact with their support, since it is paid service.

**Comment by sdanyliv** [comment]
@MightyDesertFox, I have checked it again. Looks like Raygun automatically collects only performance tracing information. For collecting queries, you have to install their package and do it manually.
There are several ways to track queries and you have to choose correct one.

**Comment by sdanyliv** [comment]
Closing as answered. Reopen if you need more details.
