### ISSUE TITLE
mysql: ordery by rand(), how to implement？thanks

### ISSUE THREAD

**Issue by brucexhe** [linq2db/linq2db#1790]
mysql: ordery by rand(), how to implement? Thanks

i try orderby(f=>Guid.NewGuid())  like SqlServer, BUT not work.

thanks.

**Comment by sdanyliv** [comment]
Try this one:
```cs
query = query.OrderBy(f => Sql.NewGuid());
```

**Comment by MaceWindu** [comment]
or define rand function and use in your query
```cs
[Sql.Function("RAND", ServerSideOnly=true, CanBeNull = false)]
public static double Rand()
{
    return new Random(DateTimeOffset.UtcNow.Ticks).NextDouble();
}
```

**Comment by brucexhe** [comment]
> or define rand function and use in your query
> 
> ```cs
> [Sql.Function("RAND", ServerSideOnly=true, CanBeNull = false)]
> public static double Rand()
> {
>     return new Random(DateTimeOffset.UtcNow.Ticks).NextDouble();
> }
> ```

Thanks , it works fine!

**Comment by brucexhe** [comment]
> Try this one:
> 
> ```cs
> query = query.OrderBy(f => Sql.NewGuid());
> ```

It doesnot work, but thanks anymore

**Comment by sdanyliv** [comment]
Closing as answered.
