### ISSUE TITLE
Yandex Clickhouse support

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1796]
Any news about clickhouse?

_Originally posted by @thyn in https://github.com/linq2db/linq2db/issues/1014#issuecomment-508747735_

@thyn, right now we are busy with preparing 2.8 and 3.0 releases which already have a lot of features planned, so we will not start working on new providers before 3.0 release probably.

It will help, if someone will send us PR, so we can give it higher priority.

As I understand, for ADO.NET provider this project should be used: https://github.com/killwort/ClickHouse-Net

~Also there is another provider https://github.com/ilyabreev/ClickHouse.Net, but I don't see much activity in that repo~ not ado.net provider

**Comment by thyn** [comment]
I didn't find any optimal version. ClickHouse-Net is the only one that works.

But, for bulk insert it requires such interface. 

`
class MyPersistableObject:IEnumerable{
	public string MyStringField;
	public DateTime MyDateField;
	public int MyIntField;

	//Количество и порядок return должны соответствовать количеству и порядку полей в SQL INSERT
	public IEnumerator GetEnumerator(){
		yield return MyDateField;
		yield return MyDateField;
		yield return MyStringField;
		yield return (ushort)MyIntField;
	}
}

`

I've found i's strange and i'm using small wrapper over their http interface.

**Comment by sdanyliv** [comment]
This library looks promising https://github.com/DarkWanderer/ClickHouse.Client
Others are mistake.

**Comment by ili** [comment]
Playing with ClickHouse now

**Comment by MaceWindu** [comment]
@ili  воу-воу-воу, палегше!

**Comment by MaceWindu** [comment]
Guys, I'm currently working on ClickHouse provider (PR: https://github.com/linq2db/linq2db/pull/3627. I expect it being ready in August).

ClickHouse (as most of other DBs) has a lot of non-standard sql extensions. I want to hear from you which of those you use so I can prioritize their implementation.

As an example of such extension I would expect people to use `[GLOBAL]` and `[OUTER|SEMI|ANTI|ANY|ASOF]` join "hints" (https://clickhouse.com/docs/en/sql-reference/statements/select/join)
