### ISSUE TITLE
Oracle : Which way to force TO_DATE or TO_TIMESTAMP parameter type

### ISSUE THREAD

**Issue by CITnDev** [linq2db/linq2db#180]
Hello,

I read that the UpdateBuilder has the field attribute information, no way to find a similar thing in the WhereBuilder or through the MappingSchema.

I have to use TO_DATE on specific cases and TO_TIMESTAMP on other cases with a mapped CLR DateTime type. I worked on using the DataType property of the ColumnAttribute to change to parameter type, but I haven't found how to do that.

Thanks.

**Comment by igor-tkachev** [comment]
I modified DateTime to SQL conversion, but I am not sure it solves your problem. So, I added a test to demonstrate how you can customize this conversion:

https://github.com/linq2db/linq2db/commit/e874da316340bd2698936180723717b7c34bb101#diff-860df4080298fa715e0c2ed38dbc8b51R567

**Comment by CITnDev** [comment]
I will check and I'll give you a feedback.
Thank you.

**Comment by CITnDev** [comment]
I've just test your code, but the DataType is always Undefined.
I'll work on a workaround and I will postpone something that, I hope, can help you.

**Comment by CITnDev** [comment]
Hello,

Sorry, your test runs well :) I forgot to remove the comment "DataType=DataType.DateTime,       Length=7" in the Column attribute.

But what I've tried to do is  :
db.GetTable<ALLTYPE>().Where(e => e.DATETIMEDATATYPE == DateTime.Now && e.DATETIME2DATATYPE == DateTime.Now).Any();

In this case the execution enters in the anonymous method as in your case but the DataType is Undefined.

I'm running tests with lvaleriu who seems to have a similar need.
