### ISSUE TITLE
StoredProcedures as extensions apply to all data connections

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#1805]
I'm adding a collection of stored procedures to my database and calling them from code.  While messing around with the initial C# code I used the wrong database as target for invoking a stored procedure on and the compiler allowed it.  The code will not execute but will compile happily even though the source database does not and never will have that particular stored procedure.

Examining the code it looks like stored procedures are hard-coded to always target `DataConnection` instead of targeting my data context.  This means I don't get any compile-time feedback on which stored procedures are available for a particular database in a multi-database project, nor any compile-time warnings when I target the wrong database.

I'm old.  I need all the help I can get from the compiler.

Changes seem to be required [here][1] to replace the hard-coded `DataConnection` with the name of the context, plus adding a new configuration variable (`GenerateProceduresOnContext` or similar) which will control what target is used.

Can send a pull request later, but don't ask me to write tests it unless you're willing to be very patient while I learn how T4 tests work :smile: 

### Steps to reproduce

Use T4 templates on any database with stored procedures.  Observe that the target type is too broad. 

### Environment details
linq2db version: 2.7.4
Database Server: Any
Database Provider: Any
Operating system: Any
.NET Framework: Any

[1]: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB.Templates/LinqToDB.ttinclude#L772-L775

**Comment by MaceWindu** [comment]
Never liked those extensions :) Will add option soon.

PS: nobody knows how to test T4. I use my own secret technic, called "manual testing". Elders say there is sacred technic, called "automated testing". But when you ask them - "how can I automate installation of nuget into VS and run template there?" they answer "Sorry Mario, your princess is in another castle".

**Comment by MaceWindu** [comment]
please check #1807

**Comment by Corey-M** [comment]
@MaceWindu Looks good.  Sorry, got caught up with work so I didn't get around to it.  I'd have done a similar thing but with less coverage in the testing.

On an unrelated note, part of the work distraction was overseeing an intern writing some code that I have been putting off.  After watching him struggle with EF for 3 hours trying to get a view to work, I showed him how to do it with Linq2DB in about 5 minutes.  Converts to the cause are worth as much as pull requests, right? 😁
