### ISSUE TITLE
HiLo Algorithm

### ISSUE THREAD

**Issue by loudadyassine** [linq2db/linq2db#1809]
Is it possible to configure HiLo Id generator algorithm in linq2db ? It's very important for batching insertion requests at the end of the work unit.

**Comment by sdanyliv** [comment]
Could you please explain how we can help here? Small sample what is expected. I'm personally do not see problems why it should be difficult to do by yourself.

**Comment by MaceWindu** [comment]
linq2db doesn't generate ids for you. They could be generated by:
- db (e.g. identity columns, triggers)
- by user in code

There is no unit-of-work pattern implementation in linq2db, so if you have one implemented over linq2db - you should implement generators by yourself there.

**Comment by loudadyassine** [comment]
I see, I'll have to generate Ids in my user code before calling linq2db, I could then batch insertion for inter-dependent entities.

Thank you for your help!
