### ISSUE TITLE
How T4 generates multiple files

### ISSUE THREAD

**Issue by Seanxwy** [linq2db/linq2db#1825]

**Comment by igor-tkachev** [comment]
Look at this example https://github.com/linq2db/linq2db/blob/master/Tests/T4.Model/MultipleFiles.tt

**Comment by yuanxiongwei** [comment]
This example is not a data-independent model file directly from the database

**Comment by igor-tkachev** [comment]
So, you need to generate a data model from database but every table should be in a separate file. Right?

**Comment by yuanxiongwei** [comment]
@igor-tkachev Yeah, that's it

**Comment by Drapondur** [comment]
> So, you need to generate a data model from database but every table should be in a separate file. Right?

This is, although not too tough, not an entirely simple task, at least as far as I can see.
I came up with the following solution provided in the attached file "MultiFileSupport.ttinclude".
I made this for linq2db 2.9.5.

Put the file in your project directory (not the LinqToDB.Templates directory).

Then in your .tt-file:
```
<#@ template language="C#" debug="True" hostSpecific="True"                           #>
<#@ output extension=".generated.cs"                                                  #>

<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)MultipleFiles.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude"     #>

<#//@ include file="$(ProjectDir)LinqToDB.Templates\MultipleFiles.ttinclude" #>
<#//@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" #>
<#//@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"     #>

<#@ include file="$(ProjectDir)MultiFileSupport.ttinclude"     #>

//The usual stuff here like
//	LoadSqlServerMetadata("MyServer", "MyDatabase", "User", "Password");
//etc. up to

GenerateModel();

//and now
SyncProject();
[MultiFileSupport.zip](https://github.com/linq2db/linq2db/files/4168145/MultiFileSupport.zip)



```

**Comment by ademchenko** [comment]
@Drapondur , works awesome. Thanks a lot!

**Comment by Drapondur** [comment]
Thanks ademchenko. Yes it seems to work although for the case that files do not get deleted properly. 
After having dropped a table the generated file for the table was still there.
I believe that is the case for SDK style projects only. I haven't used it for the old project style yet.
However, I added a workaround I uploaded to here: [MultiFileSupport.zip](https://github.com/linq2db/linq2db/files/4281577/MultiFileSupport.zip)
A new variable named _ClearMultiFileDir_ (bool) is introduced which is false per default.
If set to true all files with the extension defined in _MultiFileExtension_ will be deleted from the target directory before new files are generated.
**Important:** If you use the file I uploaded to this post you must replace _SyncProject()_ at the end of your tt-file with _FinalizeMultiFiles()_

```
<#@ template language="C#" debug="True" hostSpecific="True"                           #>
<#@ output extension=".generated.cs"                                                  #>

<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)MultipleFiles.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude"     #>

<#//@ include file="$(ProjectDir)LinqToDB.Templates\MultipleFiles.ttinclude" #>
<#//@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" #>
<#//@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"     #>

<#@ include file="$(ProjectDir)MultiFileSupport.ttinclude"     #>

//The usual stuff here like
//	LoadSqlServerMetadata("MyServer", "MyDatabase", "User", "Password");
//etc. up to

GenerateModel();

//and now
FinalizeMultiFiles(); 
```
Have fun!

**Comment by emiletu** [comment]
> FinalizeMultiFiles

I can't run with the latest one. Can you help me?
