### ISSUE TITLE
Disable escaping chars with like

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1828]
DB-Provider: Firebird 2.1
LinqToDB-Version: 2.7.4

Hello,

I have the following query:

` var result= db.GetTable<Person>.Where(p => p.Kfz.StartsWith("TEST_")).ToList();`

This produces the following select:

`SELECT p.NAME, p.ID, p.FIRST_NAME WHERE p.NAME LIKE 'TEST~_%' ESCAPE '~'`

Can I disable using the ESCAPE?
The problem is that this does not work! The above select statement returns nothing the same statement without ESCAPE returns the right result:

`SELECT p.NAME, p.ID, p.FIRST_NAME WHERE p.NAME LIKE 'TEST_%'`

**Comment by MaceWindu** [comment]
You sure? I've tested with following query and it works for me:
```sql
SELECT * FROM rdb$relations
WHERE "RDB$RELATION_NAME" LIKE 'RDB$SECURITY~_%' ESCAPE '~'
```

also don't see how it is not correct according to FB's LIKE documentation

**Comment by MaceWindu** [comment]
Maybe you need not StartWith by LIKE with pattern-matching symbols support? Then you need to use `Sql.Like` methods for it

**Comment by Franki1986** [comment]
I will have a try with LIKE. I will report if it won't work. Thanks for help!

**Comment by MaceWindu** [comment]
PRobably you will hit same issue with it, check this #776 for workaround
