### ISSUE TITLE
Examples of spatial types and linq2db

### ISSUE THREAD

**Issue by Shavingsoap** [linq2db/linq2db#1836]
I've spend quite some time trying to figure out how to use linq2db in combination with sql server spatial types. I'm in the need of an example how to achieve this. I've just upgraded from an old version of linq2db (1.0.6)

POCO:
```
[Table(Name = "[MyTable]")] 
public class MyTable
{
       // other properties

        [Column(Name ="HomeLocation"), Nullable]
        public SqlGeography HomeLocation { get; set; }
}
```
Fetching data:

```
using (var db = new MyDatabase())
{
      var query = from o in db.MyClasses
      select o;
      return query.ToList();
}
```
Generated query seems allright!

```
-- MyDatabaseContext SqlServer.2012
SELECT
	-- other properties are ok
	[o].[HomeLocation]
FROM
	[MyTable] [o]
```

Exception is thrown: 
`Can't create 'MyDatabase.sys.geography' type or '' specific type for HomeLocation.`

**Comment by MaceWindu** [comment]
This is actually good question, because you are a second person for last 10 days with same issue (see https://stackoverflow.com/questions/57012534/cant-cast-sqlgeography-when-withdrawing-data-from-db). As we didn't get any response from SO guy, maybe you will help us to find out what we miss here.

Problem is that is does work for us (see new test for your case https://github.com/linq2db/linq2db/commit/bf3126bddfcf08b9b902cfb1afe040a1886b11b6)

**Comment by MaceWindu** [comment]
Actually I can see some issues for this test with 3rd-party types assembly for .net core 2 environment. Will look into it

**Comment by MaceWindu** [comment]
Also if it is not .net core project, check if those test notes apply to you: https://github.com/linq2db/linq2db/tree/master/Tests/Linq/SqlServerTypes

**Comment by MaceWindu** [comment]
I've enabled missing spatial types functionality for netcoreapp2.0 [here](https://github.com/linq2db/linq2db/pull/1843), but it doesn't sound like related to your issue

**Comment by Shavingsoap** [comment]
Could you please elaborate _how_ I can help you with debugging this?

**Comment by MaceWindu** [comment]
Because I cannot find anything about this error, I think we can start with:
- which target framework you use: netfx 4.x or .net core
- if netfx - do you have CLR types installed or not
- if netcore - do you have dotMorten's implementation referenced
- did you tried to load types explicitly by calling `SqlServerTools.ResolveSqlTypes(Microsoft.SqlServer.Types
 assembly)`
- which version and edition of sql server you use

**Comment by MaceWindu** [comment]
Also can you:
- provide full stack trace for error
-  try to execute query from management studio (or any other tool)
- sql client version used

It will help to understand where this error comes from:
- from server - then it is some server/db configuration issue
- from sql client - then we should look into missing client configuration options

**Comment by MaceWindu** [comment]
oh, my bad, it is actually error, thrown by linq2db itself. maybe I will be able to find out why it fails. Still if you can provide details/test results for questions above - it can help

**Comment by MaceWindu** [comment]
So...
SqlDataReader returns null from GetFieldType for spatial type. Will try to look into it's code to see why it is possible.

Can you check which version of Microsoft.SqlServer.Types you have and define explicit binding redirect to this version in your app.config like here: https://github.com/aspnet/EntityFramework6/issues/244#issuecomment-309126812

**Comment by MaceWindu** [comment]
Yep, I think this is the reason - we have redirect configured for our test project to v14 and in debugger I see that reader column metadata references v11 assembly, so without redirects it will not work

**Comment by Shavingsoap** [comment]
- still on .NET Framework 4.52.
- no addtional CLR types installed
- I'm loading the Microsoft.SqlServer.Types like this:
```
SqlProviderServices.SqlServerTypesAssemblyName = typeof(SqlGeography).Assembly.FullName;
SqlServerTypes.Utilities.LoadNativeAssemblies(AppDomain.CurrentDomain.BaseDirectory);
```
- version of sql server 
`Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) `
- Version of Microsoft.SqlServer.Types:
`<package id="Microsoft.SqlServer.Types" version="14.0.1016.290" targetFramework="net452" />`

**Comment by Shavingsoap** [comment]
Let me check the redirect section...

**Comment by MaceWindu** [comment]
Marking as documentation issue as even if it is not a reason, we still need to put notes about redirects to xml-doc for related APIs and to FAQ.

**Comment by Shavingsoap** [comment]
Adding the redirect fixed this issue for me! Thank you @MaceWindu !!

**Comment by MaceWindu** [comment]
Glad to hear. I will reopen it as we still need to update documentation on our side

**Comment by MaceWindu** [comment]
also we should document .net core fix https://stackoverflow.com/a/57373622/1641529

**Comment by MaceWindu** [comment]
Resolved by https://linq2db.github.io/articles/FAQ.html#how-can-i-use-sql-server-spatial-types
Also #1843 will add xml-doc comments with that link
