### ISSUE TITLE
Select property by name & set a converter using Fluent Mapping

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#1837]
How can I use FluentMappingBuilder or EntityMappingBuilder to select a property by name (and optionally by type) and set a converter to like Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder does.

```
builder.Property("propertyName").HasConversion(personalDataConverter);
builder.Property(typeof(string), "propertyName").HasConversion(personalDataConverter);
builder.Property<string>("propertyName").HasConversion(personalDataConverter);
```

**Comment by sdanyliv** [comment]
@tb-mtg, how about PR for that?

**Comment by sdanyliv** [comment]
BTW, check please how it works in this case:
```cs
builder.Property(e => Sql.Property<string>("propertyName"))
```

**Comment by tb-mtg** [comment]
That Sql.Property method requires and entity object, as shown below: 
`
public static T Property<T>(object entity, [SqlQueryDependent] string propertyName); `

How do I pass that in a fluent mapping situation like below:

`entityMappingBuilder.Property(e => Sql.Property<string>(?entityObject?, "propertyName");`

Can I somehow get entityObject from the entityMappingBuilder?

**Comment by sdanyliv** [comment]
Oops my fault
```cs
builder.Property(e => Sql.Property<string>(e, "propertyName"))
```

**Comment by tb-mtg** [comment]
Yes that should work for selecting the property. 

Now just need to know how to set a convert for this property.

**Comment by sdanyliv** [comment]
Convert for particular property is not supported. Looks like we have to improve this area.

**Comment by jogibear9988** [comment]
@sdanyliv I thought we would not allow Converters for special propertys
https://github.com/igor-tkachev/bltoolkit/issues/243#issuecomment-21253805

**Comment by tb-mtg** [comment]
@jogibear9988  Should I introduce a custom struct and use SetConverter like below?
```
public struct PersonalDataString{}

mappingSchema.SetConverter<string, PersonalDataString>(v => ProtectPersonalDataString(v));
mappingSchema.SetConverter<PersonalDataString, string>(v => UnprotectPersonalDataString(v));
```

**Comment by sdanyliv** [comment]
@tb-mtg, i would also suggest just read and update data differently.
```cs
from p in db.Person
select new Person
{
    ....
   PersonalData = UnprotectPersonalDataString(p.PersonalData)
}
```
And update
```cs
db.Person
    .Where(p => p.PersonId)
    .Set(p => p.PersonalData, ProtectPersonalDataString(p.PersonalData))
    .Update();
```

**Comment by MaceWindu** [comment]
per-column converters for both attribute-based and fluent mappings will be available in next release https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273

I think it covers remaining items from this issue
