### ISSUE TITLE
EXISTS quieries break in i series provider in 2.8

### ISSUE THREAD

**Issue by nsarris** [linq2db/linq2db#1848]
As @RoyC-Retail-Assist has no access to an IBM i series any more we are cooperating with him to maintain the i series provider. Upgrading to 2.8 has caused EXISTS queries to break.

We narrowed the problem down to linq2db ConvertInternal in QueryVisitor.cs line 1483.

The problem is that "Exists" is an SqlFunction wrapped inside a "FuncLikePredicate" construct. The framework unwraps it and passes on the inner SqlFunction to the optimizer expecting to get an SqlFunction in return. As the i series doesn't have an exists function, the i series provider returns an SqlSearchCondition. The framework tries to cast it to an SqlFunction and breaks with an invalid cast exception. 

 The way I see it, the casting is done in order to check if the returned SqlFunction after convertion is a different instance, in order to replace the FuncLikePredicate wrapper with a new instance that contains the new function instance. So I believe that a simple type check and returning the returned instance if it is not an SqlFunction is a proper fix. Although this piece of code hasn't changed for 2.8 so I'm not sure if this has any other implications. 

The patch woulb be:  (QueryVisitor.cs line 1483)

```
case QueryElementType.FuncLikePredicate:
{
	var p = (SqlPredicate.FuncLike)element;
	var f = ConvertInternal(p.Function, action); //removed the cast to sql function


	if (f != null && !ReferenceEquals(p.Function, f)) //if the reference has changed
	{
		newElement = f is SqlFunction sqlFunction ? //if the converted element is an sqlFunction
			new SqlPredicate.FuncLike(sqlFunction) : //return a new wrapper with the new sqlFunction instance
			f; //return the result of the converter
	}
}
```
If this is the proper solution I'd be happy to provide a PR, otherwise please advise how we could tackle this.

**Comment by sdanyliv** [comment]
@nsarris, looking into.

**Comment by sdanyliv** [comment]
@nsarris, your changes looks good. I have created PR. Release planned for tomorrow.

**Comment by MaceWindu** [comment]
Fixed by #1849 
A bit later today (in about 1 hour) I will create new PR for tomorrows release - it would be nice if you will be able to fetch linq2db nuget from appveyor artifacts from that pr and test it.

**Comment by MaceWindu** [comment]
nugets are here : https://ci.appveyor.com/project/igor-tkachev/linq2db/builds/26530547/artifacts

**Comment by nsarris** [comment]
We applied this patch on yesterdays master and tested it and it worked fine. If you still want to test the latest nuget we'll run it tomorrow and let you know
