### ISSUE TITLE
linq2db Configuration.ContinueOnCapturedContext

### ISSUE THREAD

**Issue by thyn** [linq2db/linq2db#1859]
I 'm wondering why you are using Configuration.ContinueOnCapturedContext = true. it's used in ConfigureAwait. We have a lot of issues with awaiting cached tasks. It locks our iis.

**Comment by thyn** [comment]
May be it's possible to make changes at readme to recommend using ContinueOnCapturedContext = false.

**Comment by MaceWindu** [comment]
well, I'm a bit lost here as it shouldn't change existing behavior because
`await task` should have same behavior as `await task.ConfigureAwait(true)`

**Comment by thyn** [comment]
May be you should remind about it at readme. It's really big problem. We've lost a day to found problem.

**Comment by MaceWindu** [comment]
First of all I need to understand why it is a problem, because this change shouldn't change linq2db behavior at all

**Comment by thyn** [comment]
We are caching Task with result from db. Requests are attached to context and they never ends. After some time iis starts sending 503 
Message "The serverRuntime@appConcurrentRequestLimit setting is being exceeded."

https://msdn.microsoft.com/en-us/magazine/jj991977.aspx?f=255&MSPPError=-2147217396

Microsoft recomendations for example.

**Comment by thyn** [comment]
It's not about change. We are started caching now.

**Comment by MaceWindu** [comment]
Ahh, now it makes sense. I though we broke something with this change. Will make notes to readme in this case

**Comment by MaceWindu** [comment]
Answering your question in first message: we use it because it is default behavior for await and we don't want to break users who rely on it. This new option was added for cases like yours to override this behavior

**Comment by MaceWindu** [comment]
Added to FAQ, will be up soon
