### ISSUE TITLE
Is it possible to add Sybase SQL Anywhere?

### ISSUE THREAD

**Issue by zestime** [linq2db/linq2db#186]
Hi, everyone.
First of all, this project is awesome. It's really helpful. I appreciate this.

My legacy system use Sybase SQL Anywhere 12. 
And there are no proper ORM.
I believe linq2db is the best for this.
I really want to make it, Can I do that?

**Comment by fraillt** [comment]
Hello,
Was also in the same situation with SAP Hana.
Just make your own branch and work on it, after you're done, just make a Pull request.
igor-tkachev will make it happen :)

**Comment by sdanyliv** [comment]
@zestime, yes it is possible. You can find many custom DataProviders here as start for implementation here https://github.com/linq2db/linq2db/tree/master/Source/DataProvider
