### ISSUE TITLE
SqlServerVersion in SqlServerDataProvider creates version dependency

### ISSUE THREAD

**Issue by tauqirghani** [linq2db/linq2db#1871]
Describe your issue.

If you have a question, first try to check our [documentation](https://linq2db.github.io/), especially [FAQ](https://linq2db.github.io/articles/FAQ.html) and search in [issues](https://github.com/linq2db/linq2db/issues) - maybe your question already answered there.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
<code with error and mapping classes>
```

### Environment details
linq2db version: *?*
Database Server: *?*
Database Provider: *?*
Operating system: *?*
.NET Framework: *?*

**Comment by MaceWindu** [comment]
Looks like you forgot to fill in issue
