### ISSUE TITLE
Cannot group on fields selected with '*' - exception on group by followed by delete

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#1873]
I try to delete all NcsReferences that exist in NcsReference table but don't exist in Ncs table. I have in my static repository the following method:
```
public static IQueryable<NcsReference> GetUnused(DbQms db)
{
    var q1 = from r in db.NcsReferences
             from n in db.Ncs.LeftJoin(x => x.Creation_ReferenceId == r.ReferenceId)
             group r by r into rGroup
             where rGroup.Count() == 0
             select rGroup.Key;

    return q1;
}
```
### Class
NcsReferences class has only two properties
```
[Table(Name = "tblNcsReference")]
public class NcsReference : PropertyChangedNotifier
{
    [Column, PrimaryKey, Identity]
    public int ReferenceId { get; set; }

    [Column, NotNull]
    public string ReferenceName { get; set; }
}
```
### Try 1 - ToArray()
When GetUnused() method is executed like so:
```
var unusedNcsReferences = await NcsReferenceRepository.GetUnused(db).ToArrayAsync();
```
It generates proper SQL query (good grouping and selecting)
```
SELECT
	[r].[ReferenceName],
	[r].[ReferenceId]
FROM
	[tblNcsReference] [r]
		LEFT JOIN [tblNcs] [x] ON ([x].[Creation_ReferenceId] = [r].[ReferenceId])
GROUP BY
	[r].[ReferenceId],
	[r].[ReferenceName]
HAVING
	Count(*) = 0
```
### Try 2 - Delete()
But when I want to delete received objects by applying:
```
await NcsReferenceRepository.GetUnused(db).DeleteAsync();
```
I receive:
### Exception
`System.Data.OleDb.OleDbException (0x80040E21): Cannot group on fields selected with '*'.`

Generated SQL query is wrong.
```
DELETE FROM
	[tblNcsReference]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[tblNcsReference] [r]
				LEFT JOIN [tblNcs] [x] ON ([x].[Creation_ReferenceId] = [r].[ReferenceId])
		WHERE
			[tblNcsReference].[ReferenceId] = [r].[ReferenceId]
		GROUP BY
			[r].[ReferenceId]
		HAVING
			Count(*) = 0
	)
```
### Optimizer?
By the way. Roslynator analyzer suggests to optimize LINQ method call from `where rGroup.Count() == 0` to `where !rGroup.Any()` but this change produces unoptimal SQL query (also not working for the same reason):
```
DELETE FROM
	[tblNcsReference]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[tblNcsReference] [r_1]
				LEFT JOIN [tblNcs] [x_1] ON ([x_1].[Creation_ReferenceId] = [r_1].[ReferenceId])
		WHERE
			[tblNcsReference].[ReferenceId] = [r_1].[ReferenceId]
		GROUP BY
			[r_1].[ReferenceId]
		HAVING
			NOT EXISTS(
				SELECT
					*
				FROM
					[tblNcsReference] [r_2]
						LEFT JOIN [tblNcs] [x_2] ON ([x_2].[Creation_ReferenceId] = [r_2].[ReferenceId])
				WHERE
					[r_1].[ReferenceId] = [r_2].[ReferenceId]
			)
	)
```

### Environment details
linq2db version: 2.9.0
Database Server: Ms Access
Database Provider: Microsoft.ACE.OLEDB.12.0
Operating system: Windows 10
.NET Framework: 4.5

**Comment by sdanyliv** [comment]
For bug confirmation i have to understand your query. 
Where count() == 0 should never happen. Maybe you need something else?

**Comment by yarecky1** [comment]
As mentioned at the very begin I try to find production references in NcsReferences table that don't exist in main Ncs table. In my database I have long list of production references and only some of them have ever been used by user during creation of Ncs objects. So, some references exist in Ncs table multiple times, some exist only once and many don't exist.

So, my idea was to calculate how many times each of reference from NcsReference table exist in Ncs table by left joining to Ncs table. Then I could receive temporary combined object consist of NcsReference and Quantity (of occurrence) in Ncs table. Then I could filter down this list to these only where Quantity == 0. Some day I may need to find NcsReferences that were used exactly once (for example) so left-joining, grouping to Count() and filtering by specific quantity of occurrence (using SQL Having keyword) will be necessary. 

I found temporary workaround by:
1. fetching distinct list of ReferenceId from Ncs table
2. finding these NcsReference objects that ReferenceId is not on the list. 

This works however only for specific situation where quantity of occurrence = 0.
```
public static IQueryable<NcsReference> GetUnused(DbQms db)
{
    var q1 = (from n in db.Ncs
              select n.Creation_ReferenceId).Distinct();

    var q2 = from r in db.NcsReferences
             where !q1.Contains(r.ReferenceId)
             select r;

    return q2;
}
```

**Comment by yarecky1** [comment]
Ok, I think I screwed up a little bit with counting occurrences...
I corrected to this below.
1. I fetch all referenceIds and quantities from main Ncs table
2. I left join it to NcsReferences
```
var q1 = from n in db.Ncs
         group n by n.Creation_ReferenceId into nn
         select new {referenceId = nn.Key, quantity = nn.Count() };

var q2 = from r in db.NcsReferences
         from n in q1.LeftJoin(x => x.referenceId == r.ReferenceId)
         select new NcsReferenceExtended()
         {
             ReferenceId = r.ReferenceId,
             ReferenceName = r.ReferenceName,
             Quantity = n != null ? n.quantity : 0
         };

return q2;
```
Good SQL query with references that have zero occurrences:
```
SELECT
	[r].[ReferenceId],
	[r].[ReferenceName],
	[x].[referenceId],          <= Why?
	[x].[quantity]
FROM
	[tblNcsReference] [r]
		LEFT JOIN (
			SELECT
				[t1].[Creation_ReferenceId] as [referenceId],
				Count(*) as [quantity]
			FROM
				[tblNcs] [t1]
			GROUP BY
				[t1].[Creation_ReferenceId]
		) [x] ON ([x].[referenceId] = [r].[ReferenceId])
```
Is it normal to have `[x].[referenceId]` in SQL query above? Is it physically fetched from database? In linq I ask for 3 fields, SQL query gives me 4 fields.

**Comment by MaceWindu** [comment]
Nope, it is not normal. Еhis extra column looks like a bug

**Comment by sdanyliv** [comment]
Yes it is normal. We need this field for processing projection. Especially this part.
```cs
Quantity = n != null ? n.quantity : 0
```
It is virtually converted to
```cs
Quantity = Sql.ToNullable(n.referenceId) != null ? n.quantity : 0
```

**Comment by yarecky1** [comment]
Thank you. True, of course:
```
Quantity = Sql.ToNullable(n.quantity) ?? 0
```
Should I close the original issue (`Cannot group on fields selected with '*'`)? Maybe, now, it is irrelevant concerning my original demand but exception still exist and can happen to anybody in different queries. What do you think?

**Comment by yarecky1** [comment]
@MaceWindu, @sdanyliv This additional column `[x].[referenceId]` - will you solve this bug? It is increasing amount of data fetched from database on tables with several columns.

**Comment by yarecky1** [comment]
Ok. I'm still learning you library. It's not very obvious to use
```
Quantity = Sql.ToNullable(n.quantity) ?? 0
```
This is not allowed `An expression tree lambda may not contain a null propagating operator.`
```
Quantity = n?.quantity ?? 0
```

SQL query for `Quantity = Sql.ToNullable(n.quantity) ?? 0` looks like this (OK)
```
SELECT
	[r].[ReferenceId],
	[r].[ReferenceName],
	Iif([x].[quantity] IS NULL, 0, [x].[quantity])
FROM
	[tblNcsReference] [r]
		LEFT JOIN (
			SELECT
				[t1].[Creation_ReferenceId] as [referenceId],
				Count(*) as [quantity]
			FROM
				[tblNcs] [t1]
			GROUP BY
				[t1].[Creation_ReferenceId]
		) [x] ON ([x].[referenceId] = [r].[ReferenceId])
```
So, one thing is closed. One remaining topic: `Cannot group on fields selected with '*'`

**Comment by sdanyliv** [comment]
Sql.ToNullable(...) was introduced for such situations. There is limitation in LINQ and C# - it will not create on the fly class which has all properties nullable. So we have to force compiler to treat integer property as nullable - common situation during LEFT JOIN.

According groping issue, i have to check when i become near computer. But possible it is Access limitation.

**Comment by sdanyliv** [comment]
BTW, your query should looks like this one:
```cs
public static IQueryable<NcsReference> GetUnused(DbQms db)
{
    var q1 = from r in db.NcsReferences
             from n in db.Ncs.LeftJoin(x => x.Creation_ReferenceId == r.ReferenceId)
             where n == null
             select r;
    return q1;
}
```
Sorry i’m on vacation and can not get idea from first sign. It is usual query how to find not connected entities.

**Comment by yarecky1** [comment]
Your query works and it's simpler indeed as a Linq but take a look what SQL query it produces. It's confusing - see second condition in WHERE: `[tblNcsReference].[ReferenceId] = [r].[ReferenceId]` means `1 = 1` because `[tblNcsReference] is [r]` so it's redundant. I'm quite surprised that your library produces such a SQL query for such simple (?) Linq query.
```
DELETE FROM
	[tblNcsReference]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[tblNcsReference] [r]
				LEFT JOIN [tblNcs] [x] ON ([x].[Creation_ReferenceId] = [r].[ReferenceId])
		WHERE
			[x].[NcsId] IS NULL AND [tblNcsReference].[ReferenceId] = [r].[ReferenceId]
	)
```
My query, uglier as Linq, prettier as SQL.
```
DELETE FROM
	[tblNcsReference] [r]
WHERE
	NOT EXISTS(
		SELECT
			*
		FROM
			[tblNcs] [n]
		WHERE
			[n].[Creation_ReferenceId] = [r].[ReferenceId]
	)
```
I have to maintain legacy project in Ms Access and cannot check it but which SQL query is faster?

**Comment by sdanyliv** [comment]
We can not do this either. Access has a very limited DML operations, so we transformed original select query in what you have seen. If it is a problem, we can discuss how to create general algorithm for better DELETE FROM.

**Comment by sdanyliv** [comment]
Closing as answered, will reopen if needed.
