### ISSUE TITLE
Possibility to map bitmask to integer list and filter it

### ISSUE THREAD

**Issue by frankiDotNet** [linq2db/linq2db#1876]
Hi,

is it possible to map a bitmask to an integer list and make filter operations to it?

```
    [PERSON]
    public class Person{
        [ExpressionMethod(nameof(MaskToList), IsColumn = true)]
        public List<int> PermissionList{ get; set;}
    
        public static Expression<Func<Person, List<int>>> MaskToList(){
              return p => new List<int>(){p.Permissions & 1, p.Permissions & 2, p.Permissions & 4};
        }
        [PERMISSIONS]
        public int Permissions{ get; set;}
    }


using(var db = new TestDb())
{
    var result = db.GetTable<Person>().PermissionList.Contains(2).ToList();
}

```

This does not work with the given code!

DB-Provider: Firebird 2.1
LingToDb: 2.7.4
```

**Comment by MaceWindu** [comment]
It is definitely possible to map field to custom type and define custom operations, but I'm afraid with list and contains it will conflict with already existing default mappings. Still you can try.

To define mapping for well-known members, like Contains or for custom operators you can use Expression.MapMember/MapBinary: https://github.com/linq2db/linq2db/issues/1723

But as it probably will conflict with default mapping for Contains, I recommed to define your own extension method, e.g. `ContainsFlags` and map it to SQL.

To define custom type mapping check my answer here https://stackoverflow.com/a/53961787

PS: Don't close this issue if it is answered, as I will use it to track that we have this stuff documented finally.

**Comment by Franki1986** [comment]
Thanks for your help! Unfortunately I am using [DevExtreme.AspNet](https://github.com/DevExpress/DevExtreme.AspNet.Data) framework that only uses the default conatains method, so this helps only partially. But good point.

**Comment by sdanyliv** [comment]
I can not understand how do you plan to use it with DeveExpress. I saw their DataAccess library and i know what to expect from it. How do you plan to feed grid with this data?

**Comment by Franki1986** [comment]
Yes, sadly I followed the code on github and saw that the contains method is only used for string operations, unfortunately the filter operations are not customizable as desired. The idea is nice that the filter is directly translated into a linq expression, but it is restricted to the most use cases.
In fact a long time ago I did start an issue for binary operation filters, but it seems there is no need for this... [](url)..

**Comment by sdanyliv** [comment]
You can create boolean properties for each permission.  In this case DevExpress can easily filter such recordset.
```cs
[Sql.Function(ServerSideOnly = true)]
public static int BIN_AND(int value1, int value2)
{
    throw new NotImplemenedException();
}

public class Person
{
     ...
     public int Permissions{ get; set;}

     [ExpressionMethod(nameof(CanReadImpl), IsColumn = true)]
     public bool CanRead { get; }

     [ExpressionMethod(nameof(CanWriteImpl), IsColumn = true)]
     public bool CanWrite { get; }

     public Expression<Person, bool> CanReadImpl()
        => p => BIN_AND(p.Permissions, 1) != 0;

     public Expression<Person, bool> CanWriteImpl()
        => p => BIN_AND(p.Permissions, 2) != 0;
}

using(var db = new TestDb())
{
     var result = db.GetTable<Person>().Where(p => p.CanRead).ToList();
}

```
Not tested for syntax, but it should work.

**Comment by GeenCo86** [comment]
Thaks for this! Is it possible to encapsulate the boolean properties into an own class ?

public class Permissons{
     public bool CanRead { get; }
}

using(var db = new TestDb())
{
     var result = db.GetTable<Person>().Where(p => p.Permissons.CanRead).ToList();
}

**Comment by Franki1986** [comment]
Thanks for this!
Is it possible to encapsulate the boolean Permission values into an own class?


```
[Sql.Function(ServerSideOnly = true)]
public static int BIN_AND(int value1, int value2)
{
    throw new NotImplemenedException();
}

public class Person
{
     ...
     public int Permissions{ get; set;}
     public CustomPermissions Permission{ get; set;}

}
public class CustomPermissions {
     public bool CanRead { get; }
     public bool CanWrite { get; }
}

using(var db = new TestDb())
{
     var result = db.GetTable<Person>().Where(p => p.Permission.CanRead).ToList();
}
```

**Comment by sdanyliv** [comment]
Not sure that this is doable.

**Comment by Franki1986** [comment]
I know that this should not be part of this issue, but the DevExtreme team did extend there functionalities for custom filters:

[Custom filters](https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/210#issuecomment-527442129)

@sdanyliv and @MaceWindu  thanks for your help again!!!!

**Comment by sdanyliv** [comment]
@Franki1986, everything is possible, if you can transform expression tree. I can, but i have not enough time for that.
Implement `IExpressionPreprocessor` in your DataConnection class, and you can transform any expression in any parseable expression.
