### ISSUE TITLE
Review DataContext connection management for possible connection leak issues

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#1877]
See https://stackoverflow.com/a/57783825/1641529
Looking at code I suspect we will leak connection for KeepConnectionAlive=true configuration. We shouldn't allow query execution after context disposal if keep-alive set or reset it to false on dispose

**Comment by MaceWindu** [comment]
Maybe we even should shutdown context completely like we do with DataConnection on dispose to make it follow disposable semantics. With old behavior behind flag.

**Comment by sdanyliv** [comment]
I think we have to do not allow using `DataContext` after disposing

**Comment by testerbig** [comment]
So what would be the best way to use linq2db datacontext/connection in 3-tier app?

for example, i have some interface
`IQueryable<T> GetDataRecords<T>() where T : class`

And I want to implement server side like this:
```
public IQueryable<T> GetDataRecords<T>() where T : class
{
      return MyDataContext.GetTable<T>().AsQueryable();
}
```

I suppose my client side like this:
```
var expr = stub.GetDataRecords<Employee>();
var result = expr.Where(x => x.EmployeeID < 5).ToList(); // here is real query to DB, but I'll get an object disposed exception?
```

**Comment by sdanyliv** [comment]
Few questions:
1. Why `DataContext` but not `DataConnection`?
2. How `MyDataContext` is instantiated and when it is disposed?

`DataContext` do not need disposing, it closes connection after each database call. It has advantage - no disposing, but also disadvantage - Open/Close on each query (if `KeepConnectionAlive` is not set).
if `KeepConnectionAlive` is set, after usage, you have to set `KeepConnectionAlive = false` to prevent connection leak.

What i suggest from the start: pass `IDataContext` as an additional parameter and then you can use any instantiation mechanism.
```cs
IQueryable<T> GetDataRecords<T>(IDataContext dc) where T : class 

public IQueryable<T> GetDataRecords<T>(IDataContext dc) where T : class
{
      return dc.GetTable<T>();
}
```

**Comment by testerbig** [comment]
I just started to build my 3-tier prototype with linq2db, 
I tried to use "using"

```c#
public IQueryable<T> GetDataRecords<T>() where T : class
{
      using (MyDataContext dc = new DataContext(Connection))
      {
            return dc.GetTable<T>();
      }
}
```

but got object dispose exception, when using xxx.Where(..) filter on the client side to query database.

I really can't figure out how to do it right (I've read https://github.com/linq2db/linq2db/wiki/Managing-data-connection, but couldn't find the answer) 

when i got rid of using(.. ) inside a server method and define one static MyDataContext with static SqlConnection - all is working.. but i'm not sure this is a right way to do things, and i worry if it will stop working after changes ment by this ticket.

your suggestion with  `GetDataRecords<T>(IDataContext dc)` is good for 2-tier, but when i use 3-tier, client side should know nothing about server's connection to database?..

**Comment by sdanyliv** [comment]
@testerbig, you are developing ASP.NET application? Do you use Dependency Injection?

**Comment by testerbig** [comment]
No i'm developing standard windows .net console client and console server..

**Comment by sdanyliv** [comment]
So, basic and simple usage is:
```cs
// somewere in application start
DataConnection.AddConfiguration("MyConnection", connectionString);
DataConnection.DefaultConfiguration = "MyConnection";
DataConnection.DefaultDataProvider = ProviderName.SqlServer;

// and usage 
using (var db = new DataConnection())
{
    return db.GetTable<SomeTable>().ToArray();
}
```
If you are trying to implement Repository pattern - create `DataContext` instance and do not dispose it.

If you want to reuse queries - work with algorithms but not generic repositories:
```cs
public static class OrderQueries
{
    public IQueryable<Order> GetOrders(this IDataContext dc) 
    {
        return dc.GetTable<Order>().Where(o => !o.IsDeleted);
    }

    public IQueryable<Order> GetAvailaibleOrders(this IDataContext dc, string userName)
    {
         return dc.GetOrders().Where(o => o.VisibleToUser == userName);
    }
}

// and usage 
using (var db = new DataConnection())
{
     db.GetAvailaibleOrders("some_user")
        .Set(o => o.Amount, o => o.Amount + 1) // just increase value
        .Update();
}
```

**Comment by testerbig** [comment]
@sdanyliv  your example intended to use in 2-tier application.. in 3 tier, on a client, I want to get IQueryable from server, and then materialize results with some filters, but do not want to allow client to deal with DataContext or DataConnection. 

Perhaps I need to make some session management on my app server and keep DataContext (with connection) alive as long as client session alive. When client session expires i'll dispose DataContext and connection for this client session

**Comment by sdanyliv** [comment]
Oh, you are second one who asked about remote DataContext during last two years.
Have you seen this example?
https://github.com/linq2db/examples/tree/master/LinqOverWCF

**Comment by testerbig** [comment]
Thanks, i'll check this out, but wcf is almost dead technology i think.. )

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/ServiceModel

We provide WCF and SOAP web-service transports, but you can implement your own one.

**Comment by sdanyliv** [comment]
So, if you need that over TCP, gRPC, REST or other protocol, you can create another Remote DataContext. Everything in the sources.
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/ServiceModelDataContext.cs

**Comment by testerbig** [comment]
Ok, thanks, i'll dig it

**Comment by MaceWindu** [comment]
remote context didn't have much attention lately, but there are plans to improve this area in 3.0 version by improving .net core support and probably adding more transports, so if you have specific transport in mind - let us know.

**Comment by MaceWindu** [comment]
Disposal guards added by #1278
