### ISSUE TITLE
Feature: Oracle fetch sizes

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#1883]
It would be nice to have an API to specify some provider-specific parameters on commands.

Specifically, I am interested in setting `OracleCommand.InitialLOBFetchSize` to optimize fetching blobs.

I'm not sure what the API would best look like, but I feel it's similar to hints.
Maybe it could be some provider-specific well-known hints that don't turn into an actual hint in SQL text but rather set specific properties?

**Comment by to11mtm** [comment]
It may not be Ideal but for now you could possibly try this extension method, or integrate similar into a DataConectionFactory (if that's your thing):

```
public static DataConnection WithLobFetchSize(this DataConnection conn)
{
   var cmd = conn.Command as OracleCommand;
   if (cmd!= null) //If you do SQLite Integration tests you'll want a null check
   {
     cmd.InitialLOBFetchSize = 8192;
   }
   return conn;
}
```

**Comment by to11mtm** [comment]
As a more generic option...

```
public static class DataConnectionExtensions
{
	public static DataConnection WithCommandHints<TCommandType>(this DataConnection dc, Action<TCommandType> commandHints) where TCommandType : System.Data.Common.DbCommand
	{
		var cmd = dc.Command as TCommandType;
		if (cmd != null)
		{
			commandHints(cmd);
		}
		return dc;
	}
}

//use:
	using (var conn = myConnFactory())
	{
		//Could have this be in your factory too...
		conn.WithCommandHints((FbCommand c) =>
		{
			c.FetchSize = 8192;
		});
		//query goes here... 
	}
```

**Comment by jods4** [comment]
Thanks for the tip! I'll try next week.

Just to understand fully: accessing `Command` will create one command that will be used for the next command? Is the command also reused for further queries?

**Comment by to11mtm** [comment]
That is correct, but note: Setting the `CommandTimeout` property on a `DataConnection` to a value less than 0 will cause the Command to be cleared.

**Comment by sdanyliv** [comment]
There is also another way:
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/DataProvider/OracleTests.cs#L2341

**Comment by MaceWindu** [comment]
Closing as we now have `OnNextCommandInitialized` interceptor API for some time
