### ISSUE TITLE
InsertOrUpdate with identity auto increment primary column?

### ISSUE THREAD

**Issue by hnviradiya** [linq2db/linq2db#1884]
### Steps to reproduce
Details I have mentioned on stackoverflow.
https://stackoverflow.com/q/57834149/9263418

### Environment details
linq2db version: 2.9.0
Database Server: SQL Server
Database Provider: SQL Server
Operating system: Windows 10
.NET Framework: .Net Core 2.2

**Comment by sdanyliv** [comment]
@hnviradiya, linq2db do not support InsertOrUpdate on Identity columns with retrieving just generated identity value.  But without - you can do that:
```cs
using (var db = new DataConnection())
{
	db.GetTable<TestTable3>().InsertOrUpdate(() => new TestTable3
		{
			Name = "Crazy Frog"
		},
		e => new TestTable3
		{
			Name = "Crazy Frog"
		},
		() => new TestTable3
		{
			ID = 5
		});
}
```
If you need just inserted value i suggest to do the following:
```cs
using (var db = new DataConnection())
using (var tran = db.BeginTransaction())
{
    var affected = db.GetTable<TestTable3>()
       .Where(t => t.ID == 5)
       .Set(t => t.Name, "Crazy Frog")
       .Update();

   if (affected == 0)
   {
       var identity = db.GetTable<TestTable3>().
          Value(t => t.Name,  "Crazy Frog")
          InsertWithInt32Identity();
   }

   tran.Commit();
}
```

**Comment by hnviradiya** [comment]
Awesome. I couldn't get this anywhere. I don't need identity value. thanks.

**Comment by sdanyliv** [comment]
Just tip. There are many overloads for CRUD functions, examine them via intellisence.
