### ISSUE TITLE
[Question] type of output DataParameter.Value

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#1888]
I'm not sure if this is the expected behavior and/or how I should be doing the following.

I'm calling into an Oracle stored procedure that has Output parameters.

Here's an example:
```csharp
var p1 = new DataParameter { Name = "p1", Direction = ParameterDirection.Output, DataType = DataType.Int32 };
var p2 = new DataParameter { Name = "p2", Direction = ParameterDirection.Output, DataType = DataType.VarChar, Size = 400 };

db.ExecProc("package.proc_with_output", p1, p2);

var value1 = (int)p1.Value; // yes
var value2 = (string)p2.Value; // no, Value is OracleString
```

The `DataParameter` values are properly populated with what the procedure actually returned.

But the catch is that `p1.Value` is a C# type (`Int32`) rather than provider-specific (`OracleNumber`).
On the other hand, `p2.Value` is _not_ a C# type (`String`) but rather _is_ provider-specific `OracleString`.

Is that expected? Is there an easy way to get C# values (`null` or `string`) from an  output/return value `DataParameter`?

This would be convenient to use and also useful, as linq2db hides provider-specific implementation and dialect by offering a db-neutral API (i.e. you can switch providers).

For comparison, with Dapper you can do:
```csharp
var parameters = new DynamicParameters(); // etc. 
// after execution:
var value2 = parameters.Get<string>("p2");
```

**Comment by MaceWindu** [comment]
Fixed by #1961 for oracle, for other providers will be covered by #2103
