### ISSUE TITLE
linq2db ASP MVC .net core postgres example request

### ISSUE THREAD

**Issue by AppyCat** [linq2db/linq2db#1890]
Hi, I'm a Ruby developer new to using ASP MVC .net core for a project. Its flowing smooth out the gate but for performance reasons and elegant syntax I would like to use Linq2db.

Unfortunately getting the persistence layer wired up is slowing me down. Would it be possible for you to put up an example of an ASP MVC .net core app with linq2db.

An example of a query call to one table with an object that can be fed to the view file to loop through and output the results would be enough to be off to the races. 

Its my first experience writing POCOS to map objects to table columns but pretty straight forward.

I appreciate any help or assistance on this front.

**Comment by sdanyliv** [comment]
Hi. I know that in Ruby you use ActiveRecord. linq2db is quite different, it is SQL builder on steroids with a lot of CRUD operations. It do not have Change Tracker, so it can be complicated for novices to use.

I have not a lot of time to create sample project but can share ideas how effectively use linq2db.
Check these comments https://github.com/linq2db/linq2db/issues/1698#issuecomment-486174854
It shows how to manipulate with linq2db effectively. Everything is query and you can combine them, delete, insert into another table, ect.

If you have concrete questions, go on. At first, create empty ASP.NET MVC Core project and install `linq2db.PostgreSQL` package.

**Comment by AppyCat** [comment]
Thank you for your tips, linq2db reminds me of the Sequel gem in Ruby, closer to the metal. I've been writing reg SQL for years, where I need help are:

1. Best way and place to define a DB connection globally.
2. How to call a query with an object to send to the view., in a controller i.e. return View(result);

I made an empty asp.net mvc project named **linqy** with a db called **foo** with 1 table **contacts** earlier today and installed the linq2db and linq2db.PostgresQL package. 

In the linq2db docs I saw 3 files:

1. ILinqToDBSettings.cs - I put that in the Models folder. Db connection within that is:

Name = "PostgreSQL",
ProviderName = "PostgreSQL",
ConnectionString = @"Host=127.0.0.1;Username=laptop;Password=;Database=foo;Port=5432;Trusted_Connection=True;Enlist=False;"

2. DB table POCO is in Models/Contact.cs
3. DataConnection.cs - I put in app root

Not sure whether to put this in the controller method or in separate class file and invoke in controller methods as needed.

public static List<Product> All()
{
  using (var db = new DbNorthwind())
  {
    var query = from p in db.Product
                where p.ProductID > 25
                orderby p.Name descending
                select p;
    return query.ToList();
  }
}

DBSettings.cs in app root is:

using System;
using System.Collections.Generic;
using LinqToDB.Configuration;

namespace linqy
{
	public class ConnectionStringSettings : IConnectionStringSettings
	{
		public string ConnectionString { get; set; }
		public string Name { get; set; }
		public string ProviderName { get; set; }
		public bool IsGlobal => false;
	}

	public class PostgreSQLDbSettings : ILinqToDBSettings
	{
		public IEnumerable<IDataProviderSettings> DataProviders
		{
			get { yield break; }
		}

		public string DefaultConfiguration => "PostgreSQL";
		public string DefaultDataProvider => "PostgreSQL";

		public string ConnectionString { get; set; }

		public PostgreSQLDbSettings(string connectionString)
		{
			ConnectionString = connectionString;
		}

		public IEnumerable<IConnectionStringSettings> ConnectionStrings
		{
			get
			{
				yield return
						new ConnectionStringSettings
						{
							Name = "Foo",
							ProviderName = "PostgreSQL",
							ConnectionString = ConnectionString
						};
			}
		}
	}
}

**Comment by sdanyliv** [comment]
Put somewhere in Startup.cs
```cs
DataConnection.DefaultSettings = new PostgreSQLDbSettings();
```
Change 
```cs
public string DefaultConfiguration => "PostgreSQL";
```
to
```cs 
public string DefaultConfiguration => "Foo";
```

**Comment by AppyCat** [comment]
Thank you, I made a fresh project **linqy2** with the changes you suggested. I've put it up on a repo, could you take a look at the code and see if its put together correctly?  The repo link is:

[https://github.com/AppyCat/linqy2](url)


The build is successful however I get an error message upon run as follows:

`LinqToDBException: Configuration 'Foo()' is not defined.

    LinqToDB.Data.DataConnection.GetConfigurationInfo(string configurationString)
    LinqToDB.Data.DataConnection..ctor(string configurationString)
    linqy2.Models.Foo..ctor() in DataConnection.cs

    		public Foo() : base("Foo()") { }

linqy2.Controllers.HomeController.Index() in HomeController.cs

    			var db = new Foo();

lambda_method(Closure , object , object[] )
`

**Comment by sdanyliv** [comment]
Not checked yet, but if you have defined DefaultConfiguration - you do not need configuration name.
Also use `"Foo"` but not `"Foo()"`

**Comment by sdanyliv** [comment]
Moment, I'll correct your solution.

**Comment by sdanyliv** [comment]
Corrected solution. Just define proper connection string.
[linqy2-master.zip](https://github.com/linq2db/linq2db/files/3612570/linqy2-master.zip)

**Comment by AppyCat** [comment]
Thank you so much for your help, much appreciated :)

It looks like its connecting fine, here's my connection string:

PostgreSQLDbSettings("Server=localhost;Port=5432;Database=Foo;User Id=postgres;Password=postgres;Pooling=true;MinPoolSize=10;MaxPoolSize=100;Protocol=3;providerName=PostgreSQL");

That is working smooth, I'm off to the races. Only remaining glitch is when I run the app I get the following error, it seems the Pggsql driver doesn't like the name param.


`Unhandled Exception: System.ArgumentException: Keyword not supported: protocol
Parameter name: keyword
   at Npgsql.NpgsqlConnectionStringBuilder.GetProperty(String keyword)
   at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection.GetPoolAndSettings()
   at lambda_method(Closure , String )
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString)
   at LinqToDB.Data.DataConnection.EnsureConnection()
   at LinqToDB.Data.DataConnection.CreateCommand()
   at LinqToDB.Data.DataConnection.get_Command()
   at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters, Boolean withParameters)
   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints, Boolean withParameters)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at linqy2.Startup..ctor(IConfiguration configuration) in /Users/laptop/Projects/linqy2-master/linqy2/Startup.cs:line 20
--- End of stack trace from previous location where exception was thrown ---`

**Comment by sdanyliv** [comment]
Looks like you have to remove this one `providerName=PostgreSQL`

**Comment by AppyCat** [comment]
Thank you, I saw on another post 

[https://github.com/linq2db/linq2db/issues/345](url)

it needs removal of both these params:

Protocol=3
providerName=PostgreSQL

Now it runs perfectly. Thank you for all your help :)

Are there any other libraries you would recommend for enhancing dev workflow? Perhaps for migration scripts or generating POCOS from table metadata where it has 100 plus columns.

**Comment by JudeaDumont** [comment]
> Corrected solution. Just define proper connection string.
> [linqy2-master.zip](https://github.com/linq2db/linq2db/files/3612570/linqy2-master.zip)

Recreating this implementation solved my problem. An example should be made of this and included in the readme under a postgresql section so as to not cause other developers the hours of frustration I experienced.
