### ISSUE TITLE
Possibility to default add an alias to ExpressionMethod as Column

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1892]
LinqToDb: 2.7.4

Hi,

is it anyhow possible to add an alias to an ExpressionMethod per default?
I mean if I do something like this:

```
[Table("PERSON")]
public class Person
{
	[Column("FIRST_NAME")
	public string Name { get; set; }

	[ExpressionMethod(nameof(AgeExpr), IsColumn = true)]
	public int Age{ get; set; }

	public static Expression<Func<Person, int>> AgeExpr()
	{
		return p => Sql.AsSql(5);
	}
}
```

The select string would be:

`select c_1.FIRST_NAME, 5 FROM PERSON;`

Maybe something autogenerated or the member name of the ExpressionMethod owner:

`select c_1.FIRST_NAME, 5 as  Age FROM PERSON;`

**Comment by sdanyliv** [comment]
Try to set this option:
```cs
Configuration.Sql.GenerateFinalAliases = true;
```

**Comment by Franki1986** [comment]
unfortunately this is not working.. I get the same result.

`select c_1.FIRST_NAME, 5 FROM PERSON;`

**Comment by sdanyliv** [comment]
Will check, i think we can handle such situation automatically.

**Comment by Franki1986** [comment]
Ok, strange thing is I did not find an occurence of 'GenerateFinalAliases' in code..

**Comment by sdanyliv** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Configuration.cs#L352

**Comment by Franki1986** [comment]
Yes .. this, but did not find where this is checked to build the final sql

**Comment by sdanyliv** [comment]
Looks like its usage was accidentally removed. It was introduced for such situations. Anyway i have to check how it will work for `IsColumn` `ExpressionMethod`

**Comment by Franki1986** [comment]
Thanks!
