### ISSUE TITLE
Can the new Microsoft.Data.SqlClient driver be used with linq2db Sqlserver package

### ISSUE THREAD

**Issue by tauqirghani** [linq2db/linq2db#1895]
Microsoft has released Microsoft.Data.SqlClient that lets .Net Core application to connect to SQL Server and Azure SQL using Active Directory based authentication. Moving forward the new development will be in this package. Is this part of the roadmap for

**Comment by sdanyliv** [comment]
Yes, we definitely have plans to support this provider.

**Comment by MaceWindu** [comment]
fixed by #1929
