### ISSUE TITLE
[Request, T4 template] Support for ParameterDirection.ReturnValue

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#1897]
Current version of l2db template [has no support](https://github.com/linq2db/linq2db/blob/30e0cbf0dd7b3a3dad38855e21d672e5f3bd00b9/Source/LinqToDB.Templates/LinqToDB.ttinclude#L887-L896) for return parameters. 
Can you add an option like
```cs
Procedures["SomeProc"].UsesReturn = true;
```
?

**Use case:** we have a legacy MS SQL db with a lot of SPs that use `RETURN someValue;`. 

We've workarounded it with c# helper methods that wrap `QueryProc()` calls but having such feature will be a real time-saver:)

### Environment details
linq2db version: *2.9.0*
Database Server: *MS SQL 2017*
Database Provider: *System.Data.Sql*
Operating system: *Windows 10*
Framework version: *.NET Core 3*

**Comment by sdanyliv** [comment]
@MaceWindu, it looks like a bug. Please clarify. We have have to process at leas IsResult parameteter.
@ig-sinicyn, can you post sample of such procedure?

**Comment by ig-sinicyn** [comment]
@sdanyliv it's not a bug, really. [As example](https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/return-data-from-a-stored-procedure?view=sql-server-2017#returning-data-using-a-return-code).
```sql
CREATE PROCEDURE dbo.GetRandomNumber
AS
BEGIN
	RETURN 4 -- chosen by fair dice roll.
                 -- guaranteed to be random.
END;
```

 SP may use output parameter(s), result set(s) or result code. It's up to developer to specify which one should be treated as return value in generated code.
