### ISSUE TITLE
Oracle "LONG" column value not selected in join

### ISSUE THREAD

**Issue by DonKonfetti** [linq2db/linq2db#1899]
Hi!

I've got a query that yields a wrong result for a value from an Oracle LONG column under certain conditions:

```c#
var query = from k in _db.F2cfgtree
    join v in _db.F2cfgvalues on k.IdF2cfgtree equals v.IdF2cfgtree
    where k.IdF2mandant.Equals(_mandantId) && k.Hkey == keyType && (k.Name ?? "<null>").Equals(keyValue) && k.Key.ToUpper().Equals(key.ToUpper()) && v.Name.ToUpper().Equals(name.ToUpper())
    select v.ValueL;
var values = await query.Take(2).ToArrayAsync();
```

This always yields an empty string although the actual VALUE_L column contains the string "LOOONG". Above query is generating the following SQL statement:

```SQL
SELECT
	v.VALUE_L
FROM
	F2cfgtree k_1
		INNER JOIN F2cfgvalues v ON k_1.ID_F2CFGTREE = v.ID_F2CFGTREE
WHERE
	ROWNUM <= 2 AND k_1.ID_F2MANDANT = 0 AND
	k_1.HKEY = 1 AND
	Nvl(k_1.NAME, '<null>') = '<null>' AND
	Upper(k_1.KEY) = Upper('AAA\BBB\CCC') AND
	Upper(v.NAME) = Upper('Text-Long');
```

This query, executed with SQL Developer, yields the correct result for VALUE_L.

The VALUE_L column mapping looks like this:

```c#
[Column("VALUE_L",        DbType="LONG",          DataType=DataType.Text,     Length=0),    Nullable]
public string ValueL { get; set; } // LONG
```

When I select all rows of the F2cfgvalues table with the following query, the correct VALUE_L values are being returned for all rows.

```c#
var query = from r in _db.F2cfgvalues select r;
var allRows = await query.ToArrayAsync();
```

So, the issue only appears with my first query. Any idea what I am doing wrong?

### Mapping

Full mapping of all involved tables is this:

```c#
[NormalizedIdColumn("IdF2cfgtree")]
[Table("F2cfgtree")]
public partial class F2cfgtree : VasDbTableWithRidVid, IHasInsertUpdateInfo
{
    [Column("ID_F2CFGTREE", DbType="NUMBER (12,0)", DataType=DataType.Decimal, Length=22, Precision=12, Scale=0, SkipOnUpdate=true), PrimaryKey, NotNull]
    public long IdF2cfgtree { get; set; } // NUMBER (12,0)
    [Column("USERNAMEINS",  DbType="VARCHAR2(8)",   DataType=DataType.VarChar, Length=8, SkipOnUpdate=true),    Nullable]
    public string Usernameins { get; set; } // VARCHAR2(8)
    [Column("USERNAME",     DbType="VARCHAR2(8)",   DataType=DataType.VarChar, Length=8),    Nullable]
    public string Username { get; set; } // VARCHAR2(8)
    [Column("ID_F2MANDANT", DbType="NUMBER (12,0)", DataType=DataType.Decimal, Length=22, Precision=12, Scale=0), NotNull]
    public long IdF2mandant { get; set; } // NUMBER (12,0)
    [Column("HKEY",         DbType="NUMBER (2,0)",  DataType=DataType.Decimal, Length=22, Precision=2, Scale=0),    Nullable]
    public sbyte? Hkey { get; set; } // NUMBER (2,0)
    [Column("NAME",         DbType="VARCHAR2(32)",  DataType=DataType.VarChar, Length=32),    Nullable]
    public string Name { get; set; } // VARCHAR2(32)
    [Column("KEY",          DbType="VARCHAR2(200)", DataType=DataType.VarChar, Length=200),    Nullable]
    public string Key { get; set; } // VARCHAR2(200)
}

[NormalizedIdColumn("IdF2cfgvalues")]
[Table("F2cfgvalues")]
public partial class F2cfgvalues : VasDbTableWithRidVid, IHasInsertUpdateInfo
{
    [Column("ID_F2CFGVALUES", DbType="NUMBER (12,0)", DataType=DataType.Decimal,  Length=22, Precision=12, Scale=0, SkipOnUpdate=true), PrimaryKey, NotNull]
    public long IdF2cfgvalues { get; set; } // NUMBER (12,0)
    [Column("USERNAMEINS",    DbType="VARCHAR2(8)",   DataType=DataType.VarChar,  Length=8, SkipOnUpdate=true),    Nullable]
    public string Usernameins { get; set; } // VARCHAR2(8)
    [Column("USERNAME",       DbType="VARCHAR2(8)",   DataType=DataType.VarChar,  Length=8),    Nullable]
    public string Username { get; set; } // VARCHAR2(8)
    [Column("ID_F2CFGTREE",   DbType="NUMBER (12,0)", DataType=DataType.Decimal,  Length=22, Precision=12, Scale=0),    Nullable]
    public long? IdF2cfgtree { get; set; } // NUMBER (12,0)
    [Column("NAME",           DbType="VARCHAR2(60)",  DataType=DataType.VarChar,  Length=60),    Nullable]
    public string Name { get; set; } // VARCHAR2(60)
    [Column("VALUE_S",        DbType="VARCHAR2(254)", DataType=DataType.VarChar,  Length=254),    Nullable]
    public string ValueS { get; set; } // VARCHAR2(254)
    [Column("VALUE_N",        DbType="FLOAT(126)",    DataType=DataType.Decimal,  Length=22, Precision=126),    Nullable]
    public decimal? ValueN { get; set; } // FLOAT(126)
    [Column("VALUE_DT",       DbType="DATE",          DataType=DataType.DateTime, Length=7),    Nullable]
    public DateTime? ValueDt { get; set; } // DATE
    [Column("VALUE_L",        DbType="LONG",          DataType=DataType.Text,     Length=0),    Nullable]
    public string ValueL { get; set; } // LONG
    [Column("FLAGS",          DbType="NUMBER (12,0)", DataType=DataType.Decimal,  Length=22, Precision=12, Scale=0),    Nullable]
    public long? Flags { get; set; } // NUMBER (12,0)
    [Column("EXTRA",          DbType="NUMBER (1,0)",  DataType=DataType.Decimal,  Length=22, Precision=1, Scale=0),    Nullable]
    public sbyte? Extra { get; set; } // NUMBER (1,0)
}

```
### Environment details
linq2db version: 2.9.0
Database Server: Oracle 12.1.0
Database Provider: Oracle.ManagedDataAccess.Core 2.19.31
Operating system: Windows 10
.NET Framework: .NET Core 2.2

**Comment by MaceWindu** [comment]
We have tested it and looks like it is an issue in `Oracle.ManagedDataAccess.Core` provider. It returns empty `string`\`OracleString` from reader for any supported Get*() method.

You should report it here I assume : https://community.oracle.com/community/groundbreakers/database/developer-tools/windows_and_.net/odp.net

**Comment by DonKonfetti** [comment]
> We have tested it and looks like it is an issue in `Oracle.ManagedDataAccess.Core` provider. It returns empty `string`/`OracleString` from reader for any supported Get*() method.

Thank you!

Can you also confirm the observation mentioned in my first post that you get the correct LONG column value as long as you're doing a simple select query?

**Comment by MaceWindu** [comment]
Yes, when I add additional column to select - it works

**Comment by DonKonfetti** [comment]
Well, maybe then it's connected to the InitialLONGFetchSize property value of the OracleCommand class (see [InitialLONGFetchSize](https://docs.oracle.com/cd/E85694_01/ODPNT/CommandInitialLONGFetchSize.htm) and [Obtaining LONG and LONG RAW Data](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/odpnt/featData.html#GUID-20DB5E62-F366-47D4-85A1-17BB55DFDA8B)).

Is there a way to add custom initialization for OracleCommand class instances created by Linq2DB?

**Comment by MaceWindu** [comment]
Will check, but want to note that it works fine with `Oracle.ManagedDataAccess` provider (without `.Core`)

**Comment by MaceWindu** [comment]
You were right, it is due `InitialLONGFetchSize` defaults. Check this workaround [here])https://github.com/linq2db/linq2db/pull/1903/files#diff-2749a1be7dcd7ebad0de4f56d94dd666R769) how to set this option on command. I used dynamic in tests, but you can just cast to OracleCommand.

I will leave this issue open - we should decide if we want to change this behavior for managed provider or expose some options to configure it.

**Comment by DonKonfetti** [comment]
I've checked that workaround and it works for me, too. Again, thanks for your effort. :)

May I vote for a callback, event or similar mechanism that gives the application an opportunity to apply custom settings to the IDbCommand or IDbCommandProcessor instance? Maybe an optional factory for IDbCommand could also do the job.

**Comment by sdanyliv** [comment]
Also, you can override `ExecuteReader` in your `DataConnection` class, like here:
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/DataProvider/OracleTests.cs#L2341

**Comment by MaceWindu** [comment]
#1931
