### ISSUE TITLE
error installing linq2db for Sqlite

### ISSUE THREAD

**Issue by arunabhayani** [linq2db/linq2db#190]
hi. I try to install Linq2db for SQlite. getting error like:

Install failed. Rolling back...
Install-Package : Could not install package 'linq2db 1.0.7.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework.
 For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  linq2db.SQLite
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

any solution?

**Comment by sergey-miryanov** [comment]
Set .Net Framework version 4.0+

**Comment by igor-tkachev** [comment]
.NET FW 3.5 is not supported. If you can't migrate your code to 4.0, use bltoolkit.

**Comment by NN---** [comment]
@igor-tkachev Too many programmers stuck with 3.5 because Windows 7 comes with 3.5 out of the box.
It would be good to have some limited functionality but work with 3.5.
