### ISSUE TITLE
Filter dynamic column with ExpressionMethod throws Exception

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1900]
LinQToDb: 2.7.4
Firebird: 2.1

Hi,

is it possible to use dynamic columns with ExpressionMethods?
I have the following:

```
[Table("PERSON")]
public class Person{
    [COLUMN("AGE")]
    public int Age {get; set;}
    [COLUMN("NAME")]
    public string Name {get; set;}

    [ExpressionMethod(nameOf(GetTypeExpr), IsColumn = true)]
    public int Type {get; set;}

    public static Expression<Func<Person, int>> GetTypeExpr(){
        return p => (Sql.Property<int>(p, "OPTIONS")& 0xF);
    }
}
```

The table looks like this:

Tablename PERSON,
Columns: AGE (int), NAME (int), OPTIONS (string)
      

The real context looks complexer...

This works:

```
using(var db = new MyDb()){
    var result = db.GetTable<Person>().ToList();
}

```
result has all Types set with the right values.
But if I put in a Where filter, it throws an ArgumentOutOfRangeException (TableContext.cs line 335)

```
using(var db = new MyDb()){
    var result = db.GetTable<Person>().Where(p => p.Type == 4).ToList();
}
```

**Comment by sdanyliv** [comment]
Before i start investigation. Check issue using latest version.

**Comment by Franki1986** [comment]
Same thing with version 2.9, only the line number increased to 336 in the exception

**Comment by sdanyliv** [comment]
Please post stack trace.

**Comment by Franki1986** [comment]
bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei LinqToDB.Linq.Builder.TableBuilder.TableContext.<>c__DisplayClass42_0.<BuildDefaultConstructor>b__2(<>f__AnonymousType85`2 idx) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:Zeile 336.
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildDefaultConstructor(EntityDescriptor entityDescriptor, Type objectType, Int32[] index) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:Zeile 332.
   bei LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Int32[] index) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:Zeile 233.
   bei LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:Zeile 650.
   bei LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:Zeile 165.
   bei LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:Zeile 279.
   bei LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:Zeile 232.
   bei LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:Zeile 84.
   bei LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:Zeile 179.
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei IacCentralDataBaseMapping.Program.Main(String[] args) in C:\Users\ICA\Documents\Visual Studio 2017\Projects\IacCentralDataBaseMapping\IacCentralDataBaseMapping\Program.cs:Zeile 544.

**Comment by Franki1986** [comment]
Does it help? Or do you need more information?

**Comment by sdanyliv** [comment]
Yes, i have reproduced issue. Will be fixed soon.

**Comment by Franki1986** [comment]
Is there any way to fix it with a workaround?
 So that I can make a call to a column that is not mapped?

**Comment by sdanyliv** [comment]
I think `Sql.Property` cause problem. But i have to investigate.

**Comment by Franki1986** [comment]
Ok, but is there any other way to get this to work without mapping the OPTIONS column?
Something like 
```
public static Expression<Func<Person, int>> GetTypeExpr(){
        return p => Sql.AsExpression("BIN_AND(OPTIONS, 1)")
    }
```

**Comment by sdanyliv** [comment]
`Sql.Expr<int>("BIN_AND(OPTIONS, 1)")`

**Comment by Franki1986** [comment]
Thanks!
