### ISSUE TITLE
How to convert datatype ‘Memo’

### ISSUE THREAD

**Issue by jasonyush** [linq2db/linq2db#1902]
The field type of the access database is Memo。
How do I define an entity class field type when using ling2db

**Comment by MaceWindu** [comment]
We don't test this type in our tests, but memo is just a text with bigger max length (64k), so I would expect it to work.

**Comment by jasonyush** [comment]
> We don't test this type in our tests, but memo is just a text with bigger max length (64k), so I would expect it to work.

thank you it works。
Another question, do you have the orm performance test comparison report?

**Comment by MaceWindu** [comment]
We don't have separate reliable perfomance tests yet (in plans) but we have linq2db included at least into two major orm benchmarks:
- https://github.com/FransBouma/RawDataAccessBencher/tree/master/Results
- https://github.com/StackExchange/Dapper#performance
