### ISSUE TITLE
INNER JOIN nested inside a LEFT JOIN => Join Expression not supported exception

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#1906]
### Problem
I try return from static method a complete object
```
private static IQueryable<CtqResultModel> GetFull(this DbQms db)
{
    return db.CtqResults.
        LoadWith(f => f.Definition.Set.Sector).
        AsQueryable();
}
```
Result belongs to 1 Definition. Definition belongs to 0 or 1 Set. Set belongs to 1 Sector.

Produced query:
```
SELECT
*
FROM
(([tblCTQResult] [r]
    INNER JOIN [tblCTQDefinition] [db_Definition] ON ([r].[DefinitionId] = [db_Definition].[DefinitionId]))
    LEFT JOIN [tblCTQSet] [db_Set] ON ([db_Definition].[SetId] = [db_Set].[SetId]))
	INNER JOIN [tblSector] [db_Sector] ON ([db_Set].[SectorId] = [db_Sector].[Id])
```
gives
`System.Data.OleDb.OleDbException: 'JOIN expression not supported.'`

I found two sources where this problem is mentioned:
1. Due to [limitation in MS Access](https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/bb208854(v=office.12)?redirectedfrom=MSDN) a LEFT JOIN or a RIGHT JOIN may be nested inside an INNER JOIN, but an INNER JOIN may not be nested inside a LEFT JOIN or a RIGHT JOIN.
2. Here I found [proposition](https://stackoverflow.com/a/28685893) to convert the second join to a left join.

How to solve this issue? Do you know any workaround?

### Steps to reproduce
```
public class CtqResultModel
{
    [Column, PrimaryKey, Identity]
    public int ResultId { get; set; }
    
    [Column, NotNull]
    public int DefinitionId { get; set; }
    
    [Association(ThisKey = nameof(DefinitionId), OtherKey = nameof(CtqDefinitionModel.DefinitionId), CanBeNull = false)]
    public CtqDefinitionModel Definition { get; set; }
}

public class CtqDefinitionModel
{
    [Column, PrimaryKey, Identity]
    public int DefinitionId { get; set; }
    
    [Column, NotNull]
    public int SetId { get; set; }
    
    [Association(ThisKey = nameof(SetId), OtherKey = nameof(CtqSetModel.SetId), CanBeNull = true)]
    public CtqSetModel Set { get; set; }
}

public class CtqSetModel
{
    [Column, PrimaryKey, Identity]
    public int SetId { get; set; }
    
    [Column, NotNull]
    public int SectorId { get; set; }
    
    [Association(ThisKey = nameof(SectorId), OtherKey = nameof(FtqSectorModel.Id), CanBeNull = false)]
    public FtqSectorModel Sector { get; set; }
}

public class FtqSectorModel
{
    [Column, PrimaryKey, Identity]
    public int Id { get; set; }
}
```
### Environment details
linq2db version: 2.9.0
Database Server: MS Access
Database Provider: OleDb
Operating system: Windows10
.NET Framework: 4.5

**Comment by sdanyliv** [comment]
Set CanBeNull = true to Definition association.

**Comment by yarecky1** [comment]
In Defintion class, association to Set class is already set to CanBeNull = true.

But as proposed at SO, I changed in Set class association to Sector class from CanBeNull = false to true. And it works now of course. Query produces two LEFT JOINS. 
```
SELECT
*
FROM
(([tblCTQResult] [r]
    INNER JOIN [tblCTQDefinition] [db_Definition] ON ([r].[DefinitionId] = [db_Definition].[DefinitionId]))
    LEFT JOIN [tblCTQSet] [db_Set] ON ([db_Definition].[SetId] = [db_Set].[SetId]))
	LEFT JOIN [tblSector] [db_Sector] ON ([db_Set].[SectorId] = [db_Sector].[Id])
```
But is it safe? This association is untrue looking at what's in database. What if behind Sector class were other nested classes? All associations should be converted to CanBeNull = true. What about performance of few nested LEFT JOINS? I found many articles which are very inconclusive in term what is faster and why (INNER JOIN or LEFT JOIN). Some say that LEFT JOIN can be slower because it must do the job of INNER JOIN + null-extend the results if necessary. Some others say that LEFT JOIN can be faster because it's faster to join tables to already prepared and filtered data.

I will close the issue if needed.

**Comment by sdanyliv** [comment]
Will check what we can do here. We definitely can move joins and reduce nesting automatically.
