### ISSUE TITLE
Need ProviderName for MS Access

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#1914]
Hello 

I try to use Linq2DB for MsAccess. I try it with MSSql, it works fine.

Now I Try to set the cionnectionstring for MSAccess (see below) I get an exception
"DataProvider is not provided for configuration"

Could you help me ? Thanks Andreas
```cs
new ConnectionStringSettings
{
   Name = "Access",
   ProviderName = "Access",
   ConnectionString = @"Data Source=c:\Test\AtgCor32.mdb;Locale Identifier=1033;Jet OLEDB:Engine Type=5;Persist Security Info=True"
};
```

**Comment by MaceWindu** [comment]
Your provider name is correct (you can look for default provider names in ProviderName  class https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ProviderName.cs)

Could it be that you try to use it from .net core application? Currently Access provider available only for netfx builds.

**Comment by MaceWindu** [comment]
I will add it to 3.0 milestone, we should review .net core support for existing providers

**Comment by AndreasWaning** [comment]
Yes I use -NET Core 3.0:
What do you think, when is a Access Provider for .NET Core available  ?

**Comment by MaceWindu** [comment]
we plan to release 3.0 preview in 2-3 weeks. I'm planning to enable several netfx-only providers for .net core with that release:
- access
- sqlce
- sap hana

**Comment by AndreasWaning** [comment]
Thank you.

Is your SQLite provider working with .NET core 3.0 ?

**Comment by MaceWindu** [comment]
Sure

**Comment by MaceWindu** [comment]
#1920
