### ISSUE TITLE
Implementing custom IDataContext and the public APIs being sufficient

### ISSUE THREAD

**Issue by davidglassborow** [linq2db/linq2db#1915]
Related to #1912, I'm trying to use linq2db where I can provide the actual data myself through other means, similar to [LINQ over WCF](http://blog.linq2db.com/2016/03/linq-over-wcf.html)

The [Public API ](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/IDataContext.cs#L17) has [IDataContext.GetQueryRunner](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/IDataContext.cs#L104) that returns a [IQueryRunner](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/IQueryRunner.cs#L9) which looks like it should do the job of what I need.

I looked at the source code for the [RemoteDataContextBase](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/RemoteDataContextBase.QueryRunner.cs#L13) which is the base class for the WCF / ServiceModel functionality, and implements IQueryRunner, to see how to use this interface.

Looking at how it's implemented, and trying to replicate the logic of getting the SQL / Parameters so I can then handle getting the data myself, I found a couple of issues around the APIs not being sufficient / relying on internal access.

The perfect example is in [QueryRunner.ExecuteNonQuery()](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/RemoteDataContextBase.QueryRunner.cs#L126) where it accesses an [Internal only API](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Query.cs#L29) to get the details of the exact query to run, implemented as [IQueryContext](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/IQueryContext.cs).

I've managed to bypass this restriction using Reflection, but wouldn't want to do this in production obviously:
```csharp
// Work around because Query.Queries, a List<QueryInfo>, is internal
private IQueryContext queryContext()
{
    var fields = query.GetType().GetFields(BindingFlags.Instance | BindingFlags.NonPublic);
    var l = fields.Single(a => a.Name == "Queries").GetValue(query);
    var casted = l as System.Collections.IList;
    return casted[QueryNumber] as IQueryContext;	
}
```

I also had problems where the parameters didn't appear to being set, and were always null.

---

I'm assuming that it should be possible to implement IDataContext without changing the Linq2db source code, is that correct ?

I had a look for some tests for the WCF/ServiceModel code, and although I found [this](https://github.com/linq2db/linq2db/blob/master/Tests/Model/TestServiceModelDataContext.cs#L9), I can't see where it was used (I'm struggling to see how the tests work to be honest)

I guess the only way I can suggest to see the issues, is try and develop a version of WCF or similar, just using the public APIs for a separate assembly with no privileged access.

**Comment by sdanyliv** [comment]
> I'm assuming that it should be possible to implement IDataContext without changing the Linq2db source code, is that correct ?

Not exactly. You can add or open additional API if it is needed, but it will be reviewed very carefully.
It is possible situation if it is needed additional abstraction.

I suggest to create unit tests using our Playground solution, with features which fits your needs and create Pull Request. It will be iterative process and together we may create working solution.

**Comment by davidglassborow** [comment]
Ok, did u see my comment about the WCF tests ?  If you can help, can we start with getting it tested ?

**Comment by sdanyliv** [comment]
Currently almost all our tests uses LinqService as additional test for linq2db. Check GetDataContext method in TestBase class. I propose for you to redirect this to your implementation, then we will invent together how to work with different remote contexts.

**Comment by davidglassborow** [comment]
I've raised a PR, but because test classes have internal access, my code compiles ok.  If i try to do this code in a normal project, it fails.  Don't know how to show you the issue by doing it inside tests that have privileged access.

**Comment by davidglassborow** [comment]
I've added a test project, ApiTest, that shows the issue by being unable to compile

**Comment by davidglassborow** [comment]
Closing, I used the DataConnection.ExecuteReader overrides in the end, and a custom provider that  implemented `IsCompatibleConnection` and `DataReaderType` to support custom types I used under the hood.
