### ISSUE TITLE
Access LIKE wildcards not supported?

### ISSUE THREAD

**Issue by Falthazar** [linq2db/linq2db#1925]
Access supports different wildcard characters with LIKE:
https://support.office.com/en-us/f1/topic/examples-of-wildcard-characters-939e153f-bd30-47e4-a763-61897c87b3f4

Specifically looking for the digit wildcard '#'.

I tried these two:
```C#
Projects.Select(p => p.ProjectManagerLookup).Where(p => Sql.Like(p, "#%"))
//and
Projects.Select(p => p.ProjectManagerLookup).Where(p => p.StartsWith("#"))
```
Which produces this SQL:
```SQL
SELECT
	[p].[Project Manager Lookup]
FROM
	[Projects] [p]
WHERE
	[p].[Project Manager Lookup] LIKE '#%'
```

but finds no results. However, if I copy the generated SQL and paste it into an Access query, it'll run and find the results.

`Regex.IsMatch` gives the "Cannot be converted to SQL" error, understandably.

#### Environment details
linq2db version: 2.9.1 with LINQPad 5.4
Database Provider: Access

**Comment by to11mtm** [comment]
Have you tried something like:

```
public static class SqlHelpers
{
    [Sql.Expression("{0} ALIKE {1}",ServerSideOnly=true)]
    public static bool ALike(string expr, string pattern)
    {
    	return false; //Ideally should mimic behavior if possible.
    }
}

//use
Projects.Select(p => p.ProjectManagerLookup).Where(p => SqlHelpers.ALike(p, "#%"))
```
I haven't tried this myself (will attempt this weekend if possible) but JET/OLEDB can sometimes change the semantics allowed in Access [as exampled here](https://stackoverflow.com/questions/5166907/why-does-a-like-query-in-access-not-return-any-records).

As an alternative, the pattern `[0-9]` may also provide the same functionality and be just a little bit more portable (I believe SQL server supports that syntax as well, possibly others.)

**Comment by to11mtm** [comment]
So it looks like `[0-9]` is the correct pattern to use, However it looks like we may have a bug in SQL Generation.

In the meantime, you should be able to put this method in a helper class to use in place of `Sql.Like`. With this method you should be able to use `[0-9]` to find a digit in your `LIKE` clause. 

```
		[Sql.Expression("{0} LIKE {1}", ServerSideOnly = true, IsPredicate = true)]
		public static bool AccessLike(string col, string expr)
		{
			return Sql.Like(col, expr);
		}
```

I will make a branch with my repro of issue.
