### ISSUE TITLE
SQLite: A very strange issue with Sql.Property

### ISSUE THREAD

**Issue by hoangcuongvn** [linq2db/linq2db#1928]
I found a very strange issue when using custom functions (that use Sql.Property) in a WHERE linq.

I have a table like below
```
class MyTable
{
	public long? Field1 { get; set; }
	public long? Field2 { get; set; }
	public long? Field3 { get; set; }
	public long? Field4 { get; set; }
	public long? Field5 { get; set; }
}

```
I create a helper class that uses Sql.Property:
```
static class Helper
{
	[ExpressionMethod(nameof(GetFieldImpl))]
	public static long? GetField(this MyTable entity, long i)
	{
		throw new InvalidOperationException();
	}

	private static Expression<Func<MyTable, long, long?>> GetFieldImpl()
	{
		return (entity, i) => Sql.Property<long?>(entity, $"Field{i}");
	}
}

``` 
The code below only works when i = 1. If i > 1, then the test value is wrong.
```
for (var i = 1; i <= 5; i++)
{
	var test = db
		.GetTable<MyTable>()
		.Where(x => x.GetField(i) == i)
		.Count();
}

```

I created a sample in the attached file to reproduce this issue.
[TEST.zip](https://github.com/linq2db/linq2db/files/3720394/TEST.zip)

**Comment by sdanyliv** [comment]
@hoangcuongvn, it might be an issue with query caching. Try this one.
```cs
public static long? GetField(this MyTable entity, [SqlQueryDependent] long i)
```

**Comment by hoangcuongvn** [comment]
I have tried using SqlQueryDependent but the issue still remains.

**Comment by sdanyliv** [comment]
Will check. This attribute was introduced for such situations and looks like it needs review.

**Comment by sdanyliv** [comment]
As a workaround try this one
```cs
using (NoLinqCache.Scope())
for (var i = 1; i <= 5; i++)
{
	var test = db
		.GetTable<MyTable>()
		.Where(x => x.GetField(i) == i)
		.Count();
}
```

**Comment by hoangcuongvn** [comment]
Yes, `NoLinqCache.Scope` works!

I put `using (NoLinqCache.Scope())` on top of the method and the test value is now correct.

**Comment by sdanyliv** [comment]
Will fix that in next release. Thanks for reporting.
