### ISSUE TITLE
Nested objects aren't inserted

### ISSUE THREAD

**Issue by Scratch-net** [linq2db/linq2db#193]
Hi and thanks for the great library.

Is this supported? 

```
public class User
{
    [PrimaryKey, Identity]
    public int Id { get; set; }
    public string Username { get; set; }
    [Association(ThisKey = "Id", OtherKey = "UserId", CanBeNull = false)]
    public IEnumerable<Role> Roles { get; set; }
}

public class Role
{
    [PrimaryKey, Identity]
    public int Id { get; set; }
    public string Value { get; set; }
    public int UserId { get; set; }
}
```

.....
        var usr = new User() { Username = "Test"};
        var role = new Role() { Value = "TestRole" };
        usr.Roles = new List<Role>() { role };
...
        db.Insert(usr);

insert throws no exceptions and does not insert roles that I've assigned. Is it possible at all?

**Comment by sdanyliv** [comment]
@Scratch-net, linq2db do not supports inserting a graph of objects.

**Comment by sanjuroo** [comment]
Is this still not supported? If not, how are this type of inserts typically solved using linq2db? save parent first, then bulkcopy children? thanks.

**Comment by viceroypenguin** [comment]
Correct. Complex object graph inserts are done in other ORMs by multiple insert statements. Since l2db does not do any object tracking, l2db will not automate these inserts.

Proper process is to effect each set of inserts yourself, by doing the parent and then each of the children (or bulk insert the children).

**Comment by TsakiDev** [comment]
The way I tackle this issue in my projects, is by creating a service class layer for every type of object or at least most of them and then those service layers interact with a generic repository class. There are other/better ways but I think it suits me best.
