### ISSUE TITLE
Use Linq2Db to get table schema and all data

### ISSUE THREAD

**Issue by advapiIT** [linq2db/linq2db#1933]
Hello,
This is not a real issue and I don't know if it's the right place to write.
I need to get the schema (and later all the data) since I need to serialize them via HTTP and push them. 
Is there a way I can execure the Query<T> when I've no DataContext mapped? (I mean using the T4 template generator)

Thanks

**Comment by ili** [comment]
Hello! 
Thats realy easy, you can use (SchemaProvider)(https://linq2db.github.io/api/LinqToDB.SchemaProvider.html):

```cs
using (var db = new DataConnection())
{
	var schemaProvider = db.DataProvider.GetSchemaProvider();

	var schema = schemaProvider.GetSchema(db, TestUtils.GetDefaultSchemaOptions(context));
}
```

**Comment by ili** [comment]
> Is there a way I can execure the Query when I've no DataContext mapped? (I mean using the T4 template generator)

Not really clear... You do not need using T4 templates, they just help to jenerate your POCOS, but you always can do:

```cs
new DataContext().GetTable<MyPoco>().ToArray();
```

**Comment by advapiIT** [comment]
Thanks, and if I don't have a POCO, can I return a generic?

**Comment by ili** [comment]
What do you mean under "generic"? If you do not have POCO how to know table name and fields...

In general you can invoke generic method using reflection and supply POCO type...

**Comment by sdanyliv** [comment]
It is not possible to return raw query result via RemoteContext. I suggest to create additional WCF service and return this data via your RPC call.

**Comment by advapiIT** [comment]
Even serializing them?
