### ISSUE TITLE
Single-column temp tables are not supported

### ISSUE THREAD

**Issue by Bobsson** [linq2db/linq2db#1934]
I'm trying to create a temporary table to hold the results of one query so that a later query can join against it.  However, I only need the ID column from the first query - none of the other data.  However, I can't find a way to do this successfully.

```
using (var db = new MyDB())
    using (var temp = db.CreateTempTable<int>("#ids"))
```
fails to generate valid SQL: It produces 
```
CREATE TABLE [#ids]
(
)
```

If I make a `struct` or `class` `IntTable` with one field (an `int` named `Value`), I get a `NotImplementedException` (see ExpressionTest.struct.cs and ExpressionTest.class.cs in [ExpressionTest.zip](https://github.com/linq2db/linq2db/files/3736709/ExpressionTest.zip), if that output would be helpful).  This may be expected behavior because my `IntTable` should implement a specific interface, but if that's the case, then I shouldn't be able to specify anything that doesn't implement that interface.

### Environment details
linq2db version: 2.9.1
Database Server: SQL Server 14.0.3048.4
Database Provider: SqlServerSchemaProvider
Operating system: Windows 10
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
Temp table can be created only from class. So, help linq2db to do that.
```cs
public class IdHolder<T>
{
     [Column] public T ID { get; set; }
}
```
```cs
using (var db = new MyDB())
    using (var temp = db.CreateTempTable<IdHolder<int>>("#ids"))
```
Sorry i can not check your project right now. We use temporary tables in our tests very intensive so it should be not a problem at all.

**Comment by sdanyliv** [comment]
Use the following query to inset data:
```cs
using (var db = new MyDB())
using (var temp = db.CreateTempTable<IdHolder<int>>("#ids"))
{
     var query = from t in db.GetTable<Table1>();
    
     query.Insert(temp, t => new IdHolder<int> { ID = t.Id });
}
```

**Comment by sdanyliv** [comment]
@MaceWindu, we have to set to `CreateTempTable<T>()` generic function limitation to use classes.

**Comment by MaceWindu** [comment]
add this to 2.9.3?

**Comment by MaceWindu** [comment]
Not planned currently
