### ISSUE TITLE
Oracle.Managed alias is same as table name.

### ISSUE THREAD

**Issue by johnhwright** [linq2db/linq2db#1939]
It's possible to choose what alias is chosen for a table? Currently when updating with a join it's aliasing the name with the exact table name which doesn't work as expected in oracle.

```
UPDATE
  OWNER.TableName
SET
  OWNER.TableName.Column1 = 'Y'
WHERE
  EXISTS(
    SELECT
        *
    FROM
        OWNER.TableName tablename
        INNER JOIN joinedTable...
    WHERE
        joinedTable.Column1 = 123 AND
        tablename.PK1 = OWNER.TableName.PK1 AND
        tablename.PK2 = OWNER.TableName.PK2
  )
```

This will match **ALL** records in the in the table since the alias `tablename` is equivalent to the actual table name. When generating the alias value it should never use the actual table name.

I can currently get around it by querying the same table and join it with the original set I'm trying to update it will move the name to tablename2 which will allow it to work but it seems like it shouldn't be necessary.

### Environment details
linq2db version: 2.9.2
Database Server: Oracle 12c
Database Provider: linq2db.Oracle.Managed 2.9.2
Operating system: Windows 10
.NET Framework: 4.7.1

**Comment by sdanyliv** [comment]
Could you please check this query in 3.0 preview 1 version? It contain a lot of fixes in this area.
Also generated SQL gives me almost nothing without LINQ queries.

**Comment by sdanyliv** [comment]
BTW, I’ve got your point. Looks like a bug and i have to check, but i also needed your LINQ Query.

**Comment by sdanyliv** [comment]
I have reproduced issue. Fix prepared.

**Comment by MaceWindu** [comment]
#1941
