### ISSUE TITLE
tt-script generate wrong DataType for Oracle LONG

### ISSUE THREAD

**Issue by ldi0pathic** [linq2db/linq2db#1940]
Same problem as in #1927 

**How To Fix IT:** 

The tt-script generates the following model:

```c#
[Column("DATA",            DbType="LONG",          DataType=DataType.Text,    Length=0),    Nullable]
public string Data { get; set; } // LONG
```
when i use following settings in my tt-script:
 ```c#
 GenerateDataTypes   = true;		
 GenerateLengthProperty   = true;		
 GeneratePrecisionProperty   = true;		
 GenerateScaleProperty   = true;		
 GenerateDbTypes   = true;		
```
when i change the DataType im model manuell to 

> DataType=DataType.Long

 the insert work without problems

### Environment details
linq2db version: 2.9.2
Database Server: Oracle 12.1.0
Database Provider: Oracle.ManagedDataAccess.Core 2.19.31
Operating system: Windows 10
.NET Framework: .NET Core 2.2

**Comment by MaceWindu** [comment]
For workaround you can add extra code to tt file to enumerate columns and update DataType property based on DbType value.

**Comment by MaceWindu** [comment]
Something like this should help:
```cs
foreach (var t in Tables.Values)
	foreach (var c in t.Columns.Values)
		if (c.DbType == "LONG")
			c.DataType=DataType.Long;
```

**Comment by Soffel** [comment]
```c#
foreach (var t in Tables.Values)
	foreach (var c in t.Columns.Values)
		if (c.ColumnType== "LONG")
			c.DataType = "DataType.Long";
```
works for me
