### ISSUE TITLE
Wrong query for enum comparison

### ISSUE THREAD

**Issue by sss13579** [linq2db/linq2db#1946]
If comparison of enum field and enum constant is in linq query then sql query is wrong

### Steps to reproduce

model
```c#
public enum UserVersion
{
		FirstRelease = 0,
		SecondRelease = 1
}

public class User
{
		[PrimaryKey]
		[Identity]
		public int Id { get; set; }

		[Column]
		public UserVersion? Version { get; set; }
}

```
code:
```c#
var maxVersion = UserVersion.SecondRelease;
using (var context = _dataContextFactory.CreateContext())
{
var ids = await context.Users.Where(u => u.Version < maxVersion)
						.Select(u => u.Id).ToArrayAsync();
}
```

will generate query:

```sql
SELECT
	[u].[Id]
FROM
	[Users] [u]
WHERE
	@maxVersion < [u].[Version]
```

### Environment details
linq2db version: 2.9.1
Database Server: Microsoft SQL Server Enterprise (64-bit) 14.0.1000.169
Database Provider: ms sql
Operating system: Windows 10
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
I can not reproduce this. What i have:
```sql
-- SqlServer.2017 (asynchronously)
DECLARE @maxVersion Int -- Int32
SET     @maxVersion = 1

SELECT
	[u].[Id]
FROM
	[User] [u]
WHERE
	[u].[Version] < @maxVersion
```
Maybe you use some Expression Tree transformations?

**Comment by sss13579** [comment]
[test.zip](https://github.com/linq2db/linq2db/files/3755649/test.zip)

Please check this solution. Suddenly my initial code become generate properly script. But this solution i run on 2 PC and got described error. Deattached db in archive also.
