### ISSUE TITLE
Mapping for Composite Entity

### ISSUE THREAD

**Issue by mattmcnabb** [linq2db/linq2db#1950]
I previously asked a [related question over on StackOverflow](https://stackoverflow.com/questions/53937514/linq2db-one-poco-from-multiple-tables), and the answer provided there got me a long way down the path, but I may need further clarification. Consider the following classes:

```csharp
[Table(Name = "UserTable1")]
public class UserTable1
{
	[Column, NotNull, PrimaryKey] public string Username {get; set;}
	[Column, NotNull] public int Company {get; set;}
	[Column, NotNull] public string Property3 [get; set;}
	[Column, NotNull] public string Property4 [get; set;}
}

[Table(Name = "UserTable2")]
public class UserTable2
{
	[Column, NotNull, PrimaryKey] public string Username {get; set;}
	[Column, NotNull] public int Company {get; set;}
	[Column, NotNull] public string Property5 [get; set;}
	[Column, NotNull] public string Property6 [get; set;}
}

public class User
{
	public string Username {get; set;}
	public int Company {get; set;}
	public string Property3 [get; set;}
	public string Property4 [get; set;}
	public string Property5 [get; set;}
	public string Property6 [get; set;}
}
```

Our domain model for the user entity is a composite of the data from UserTable1 and UserTable2, where the Username and Company fields match. The additional properties are unique to each table. I know that I can use a join to compose the entity like this:

```csharp
using (context)
{
	return from u1 in context.GetTable<UserTable1>()
		   join u2 in context.GetTable<UserTable2>() on u1.Username equals u2.Username
		   where u1.Company == Company
		   select new User()
		   {
			   Username = u1.Username,
			   Company = u1.Company,
			   Property3 = u1.Property3,
			   Property4 = u1.Property4,
			   Property5 = u2.Property5,
			   Property6 = u2.Property6
		   };
}
```

However, this approach is getting very cumbersome when it comes to insert, update, and delete methods. Can this be done solely with Mapping using either mapping attributes or the Fluent Mapping builder? What I'm imagining is something like this:

```csharp
using (context)
{
    User u = new User()
    {
	Username = "Matt",
	Company = 1,
	Property3 = "Value3",
	Property4 = "Value4",
	Property5 = "Value5",
        Property6 = "Value6"
    };
   
   u.Insert();
}
```

In this case the mapping would already be configured to write these values out to the two tables supporting the composite model, since the User table doesn't actually exist in the database.

Thanks!

### Environment details
linq2db version: 2.9.0
Database Server: IBM iSeries
Database Provider: DB2iSeries
Operating system: Windows 10
.NET Framework: 4.6.1

**Comment by sdanyliv** [comment]
MappingSchema will not help here. I think you have to create your custom method which splits your DTO to two inserts, updates, deletes. It can be done via reflection

**Comment by mattmcnabb** [comment]
@sdanyliv Thanks, that's what I was afraid of!

**Comment by sdanyliv** [comment]
Anyway, not complex task ;) For me

**Comment by sdanyliv** [comment]
Sorry about that but library is focused on optimal SQL generation but you asked for Entity management, which is not strong part of linq2db.

**Comment by mattmcnabb** [comment]
> Anyway, not complex task ;) For me

Well, unfortunately we're not all you 🤣

I'm neither a database expert, nor a .NET expert - I'm just trying to move a project forward and simplify the data access layer so we can focus on the business logic.

> Sorry about that but library is focused on optimal SQL generation but you asked for Entity management, which is not strong part of linq2db.

No worries - it's good to understand that. I started out with an attempt to build a repository pattern approach and mostly this has worked fine up to now, but as I work toward full CRUD operations it's become unwieldy. I think I'll need to take a less abstract approach moving forward, but that's fine.

Thanks!
