### ISSUE TITLE
Incorrect sql type is generated in CreateTable

### ISSUE THREAD

**Issue by antrv** [linq2db/linq2db#1960]
Hi,

I'd like to use 'decimal(x, y)' column type for C# decimals for SQL server and 'text' column type for SQLite, because SQLite converts all inserted values to doubles, and precision is lost.

The column is declared as `[Column(Precision = 28, Scale = 4)] public decimal Money { get; set; }`.

I use convert expression for SQLite mapping schema:
```cs
SQLiteMappingSchema.MicrosoftMappingSchema s = new SQLiteMappingSchema.MicrosoftMappingSchema();
s.SetDataType(typeof(decimal), new SqlDataType(DataType.Text, typeof(string)));
s.SetConvertExpression((string s) => decimal.Parse(s, CultureInfo.InvariantCulture));
s.SetConvertExpression((decimal d) => d.ToString(CultureInfo.InvariantCulture));
```

`CreateTable` generated the following type for the column: `[Money]   Text(2147483647)(28,4)  NOT NULL`. SQLite doesn't allow such column specification.

How can I remove length or/and precision/scale?
Thanks.

### Environment details
linq2db version: 2.9.3
Database Server: -
Database Provider: SQLite MS provider
Operating system: Win 10 x64
.NET Framework: .NET Core 3.0

**Comment by antrv** [comment]
I also want to save DateTime as integers in SQLite database.

I tried:
`            
SQLiteMappingSchema.MicrosoftMappingSchema s = new SQLiteMappingSchema.MicrosoftMappingSchema();
s.SetDataType(typeof(DateTime), new SqlDataType(DataType.Int64, typeof(long)));
            s.SetConvertExpression((long l) => new DateTime(l, DateTimeKind.Utc));
            s.SetConvertExpression((DateTime t) => t.Ticks);
            s.SetConvertExpression((DateTime t) => t.Ticks.ToString(CultureInfo.InvariantCulture));
            s.SetValueToSqlConverter(typeof(DateTime),
                (sb, dt, v) => sb.Append(((DateTime) v).Ticks.ToString(CultureInfo.InvariantCulture)));
`
but this only make the type of column to be 'BigInt'.
DateTime values are still inserted as strings like this '2019-11-02 19:48:22.5151161'.

How can I insert DateTime values to db as integers?

**Comment by MaceWindu** [comment]
As workaround for create table issue: specify database type using ColumnAttribute.DbType:
```cs
[Column(DbType="your_type_here")] public decimal Money { get; set; }.
```

**Comment by MaceWindu** [comment]
For DateTime as BigInt - you probably need to set DataParameter converstion (`ms.SetConvertExpression<TwoValues,DataParameter>(...)`)

Also it is not clear that you set your mapping schema to data connection. BTW, you shouldn't use SQLiteMappingSchema.MicrosoftMappingSchema directly - use MappingSchema class.

**Comment by MaceWindu** [comment]
I've checked it and looks like there is no actual issue here - your column definition has precision and scale configured and it takes precedence over mapping schema setting for type.
you should configure precision/scale only for sql server mappings. Check some samples [here](https://github.com/linq2db/linq2db/pull/2011/files#diff-c2bedcb0e802d1def4bb81ed0688efe9R18-R27)
