### ISSUE TITLE
Define LinqToDB mapping attributes in another partial class

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1972]
Hi,

till now I am using table and column attributes to generate the mappings.
I would like to split the specific LinqToDb mapping to another partial class, so that I have one clean class in a file and another with the specific attributes.
My idea was to split it like this:

File Data.Person.cs:

```
public partial class Person{
    public string Name {get; set;}
    public int Age {get; set;}
}
```
 
File Data.LinqToDB.Person.cs:

```
using Metadata = System.ComponentModel.DataAnnotations;

[Table("PERSONS")]
[Metadata.MetadataType(typeof(Person_DB))]
public partial class Person{
}
public class Person_DB{
    [Column("NAME")]
    public string Name {get; set;}
    [Column("AGE")]
    public int Age {get; set;}
}

```
In this way I could cleanly split mapping and my data class. Is it somehow possible that this could work? First try din't work.

**Comment by MaceWindu** [comment]
Don't think we can redirect mappings to another type, but you can apply column mappings to class directly and specify MemberName:
```cs
// main file
public partial class Person{
    public string Name {get; set;}
    public int Age {get; set;}
}

// mappings file
[Table("PERSONS")]
[Column("NAME", nameof(Name))]
[Column("AGE", nameof(Age))]
public partial class Person{
}
```
