### ISSUE TITLE
[Bug] RetryingDbConnection.BeginTransaction() does not pass isolation level arg

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#1973]
L2db's DataConnection uses RetryingDbConnection if retry policy applied.

BeginTransaction() method in this class [does not pass](https://github.com/linq2db/linq2db/blob/5e26fa1693208b92b0791dff445ab7b42e79fb1b/Source/LinqToDB/Data/RetryPolicy/RetryingDbConnection.cs#L28-L31) isolation level arg to the wrapped connection:
```cs
		protected override DbTransaction BeginDbTransaction(IsolationLevel isolationLevel)
		{
			return _dbConnection.BeginTransaction();
		}
```
As a result calls like `db.BeginTransaction(System.Data.IsolationLevel.RepeatableRead)` use default isolation level. I'm pretty sure this is unintended behavior as async overload, BeginTransactionAsync, does pass the isolation level arg.

P.S. Also, it looks like the 'Clone()' method has incorrect implementation:
```cs
		public object Clone()
		{
			if (_connection is ICloneable cloneable)
				return cloneable.Clone();
			return _dataConnection.DataProvider.CreateConnection(_dataConnection.ConnectionString);
		}
```
Shouldn't it return clone of the current RetryingDbConnection instance?

### Environment details
linq2db version: *2.9.0*  
Database Server: *MS Sql 2016*  
Database Provider: *SqlServerDataProvider("mssql", SqlServerVersion.v2012);*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7.2*

**Comment by MaceWindu** [comment]
srsly...
