### ISSUE TITLE
Association CanBeNull changed behaviour after update to 2.9.1

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1974]
Current working version:  2.9.3 and 3.0
version testet that brings a change: 2.9.1

After version 2.9.1 an Association with CanBeNull does not return null for associated Property:

```
public class Person{
    public int ID {get; set;}   
    public string Name {get; set;}
    [Association(QueryExpressionMethod = nameof(ArticleExpr), CanBeNull = true, Relationship = Relationship.OneToOne)]
    public Artivle Bought {get; set}

public static Expression<Func<Person, IDataContext, IQueryable<Article>>> ArticleExpr()
      {
         return (p, db) => db.GetTable<Article>().Where(a => a.PersonId == c.Id);
      }
}

public class Article{
    public string ID {get; set;}  
    public int PersonId {get; set;}  
    public double Price {get; set;}  
}
```

**Comment by Franki1986** [comment]
Changed the title, because 'broken' is my interpretation..

**Comment by Franki1986** [comment]
Any way to work around this? 
I have many situations where this does not work anymore, because the result is not null.

**Comment by sdanyliv** [comment]
How to reproduce? No linq queries provided.

**Comment by Franki1986** [comment]
public class Person{
    public int ID {get; set;}   
    public string Name {get; set;}
    [Association(QueryExpressionMethod = nameof(ArticleExpr), CanBeNull = true, Relationship = Relationship.OneToOne)]
    public Article Bought {get; set}

```
public static Expression<Func<Person, IDataContext, IQueryable<Article>>> ArticleExpr()
      {
         return (p, db) => db.GetTable<Article>().Where(a => a.PersonId == c.Id);
      }
}

public class Article{
    public string ID {get; set;}  
    public int PersonId {get; set;}  
    public double Price {get; set;}  
}
```


using(var db = new MydataContext()){
    db.GetTable<Person>().LoadWith(p => p.Bought).ToList();
}

if no Article is found (property Bought) in previous versions it was null, now it is initialized with default property values.

**Comment by sdanyliv** [comment]
Ok, got it.
