### ISSUE TITLE
Problem with Association and Derived Class (and also without)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1979]
Describe your issue.

My Query in My Pull reqest does not work.

```
Exception message:
LinqToDB.LinqToDBException : Second parameter of expression predicate should be 'Tagging'
```

if I change the 

			public List<TaggingIssue> Tagging { get; set; }

to

			public List<Tagging> Tagging { get; set; }

I get the following exception:
    System.InvalidCastException : Das Objekt des Typs "System.Linq.Expressions.MethodCallExpressionN" kann nicht in Typ "System.Linq.Expressions.MemberExpression" umgewandelt werden.

### Steps to reproduce
Look at my Pull Request

**Comment by jogibear9988** [comment]
see https://github.com/linq2db/linq2db/pull/1980

**Comment by jogibear9988** [comment]
Is my mapping for the Association wrong?

**Comment by jogibear9988** [comment]
@sdanyliv could you help me with this?

**Comment by MaceWindu** [comment]
Association expressions had incorrect type. Also it is possible that changes in rc0 regarding associations also helped
