### ISSUE TITLE
Null Refe while iterrating Group By Joined from Table wich also could be null

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1989]
I've a query wich looks like this:
```cs
        var query = from i in da.Issues
                    join t in (da.Taggings.Where(x => x.TaggableType == "Issue")) on i.Id equals t.TaggableId into tj
                    from t in tj.DefaultIfEmpty()
                    join tg in da.Tags on t.TagId equals tg.Id into tgj
                    from tg in tgj.DefaultIfEmpty()
                    join u in da.Users on i.AssignedToId equals u.Id into uj
                    from u in uj.DefaultIfEmpty()
                    where
                    i.Status.IsClosed == false &&
                        (i.StartDate >= startdate && i.StartDate <= enddate) || (i.DueDate <= enddate && i.DueDate >= startdate) &&
                        tg.Name == "Visu"
                    select new { Issue = i, User = u };
```
then I do this:
```cs
       var grouped = query.GroupBy(x => x.User).ToList();
```
If I now iterate over the group:
```cs
       foreach (var entry in group)
```
I get a null ref exception in the foreach...

I know that the user could be empty.

**Comment by sdanyliv** [comment]
Two years ago you had the similar issues with Grouping. Yes it needs refactoring and we find time to do that. BUT, again it is NOT valid SQL.
Even worse, this Enumerable implementation will also fail with NRE but earlier.
```cs
var grouped = query.AsEnumerable().GroupBy(x => x.User).ToList()
```

**Comment by jogibear9988** [comment]
oh my brain is sometimes a disaster...

you're right, don't know how to write this as a query...

maybe we should fail earlier then?

**Comment by sdanyliv** [comment]
So why you group by Null User? Why not filter out them?
Just remove `from u in uj.DefaultIfEmpty()`
And then 
```cs
var grouped = query.AsEnumerable().GroupBy(x => x.User).ToList();
```

**Comment by jogibear9988** [comment]
I also need the Issues wich are not assigned to a user

**Comment by sdanyliv** [comment]
```cs
var defaultUser = new User();
var grouped = query.AsEnumerable().GroupBy(x => x.User == null ? defaultUser).ToList();
```

**Comment by jogibear9988** [comment]
I did it like this, but I can group by user without the null check...

**Comment by jogibear9988** [comment]
And shouldn't we throw with the upper query that is not possible to create it as sql?

**Comment by sdanyliv** [comment]
> Don't we have a Materialization cache per query, so we can check if a row has the same Primary Key for a object and return the same instance?

No, we don't. It will be improved in future.

> And shouldn't we throw with the upper query that is not possible to create it as sql?

We have such configuration option `Configuration.Linq.GuardGrouping`
