### ISSUE TITLE
How use sqlite on mono/osx?

### ISSUE THREAD

**Issue by mamcx** [linq2db/linq2db#199]
I have tried to use this with sqlite on osx, running last version of xamarin.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="linq2db" version="1.0.7.1" targetFramework="net40" />
  <package id="linq2db.SQLite" version="1.0.7" targetFramework="net40" />
  <package id="linq2db.t4models" version="1.0.7.1" targetFramework="net40" />
</packages>
```

When run the code it say:

System.DllNotFoundException: SQLite.Interop.dll
  at at (wrapper managed-to-native) System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none 

I try adding Mono.data.sqlite, System.Data.SQLite.Core and and buch of other sqlite nugets packages, but none work.

**Comment by jogibear9988** [comment]
I think this can be closed. Linq2db works on mono on my system
