### ISSUE TITLE
Postgres - Exception Database do not support CROSS/OUTER APPLY

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#1992]
I create a quer and get this exception:

Database do not support CROSS/OUTER APPLY join required by the query.

Do I need to configure that my postgres Version supports it?

**Comment by sdanyliv** [comment]
I think, it should work via LATERAL JOIN. LINQ query here is appreciated.

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs#L38

you need to set pgsql9.5 sql mode for provider (don't think you use something old like 9.2)

**Comment by MaceWindu** [comment]
Probably we need to review defaults for 3.0 here. 9.5 is already pretty ancient version to be default

**Comment by jogibear9988** [comment]
@MaceWindu 
did not find wich setting to use.

thanks... ;-)
