### ISSUE TITLE
Merge(): Precision is lost when converting DateTime objects (created from datetime2 in SQL Server) to SQL

### ISSUE THREAD

**Issue by MozgC** [linq2db/linq2db#200]
When I used the Merge() method on SqlServer 2012 recently I got a duplicate unique key exception. So I looked at the SQL generated and saw that DateTime2 values were truncated to 3 digits in the fractional seconds part (and that DateTime2 column was a part of the unique key).
So, let's say we have the following datetime value:

``` c#
var dt  = DateTime.Parse("2010-12-14T05:00:07.4250141Z");
```

Merge() method will produce an SQL query containing '2010-12-14T00:00:07.425' for the datetime value in question, so the precision is lost and 2 different datetime2 values may be converted to the same truncated value.

**Comment by MaceWindu** [comment]
Maybe reassign it to me as it is related to merge operation?

**Comment by sdanyliv** [comment]
It is more related to the mapping. @ili should work with this issue also. You have to cooperate with him.

**Comment by MaceWindu** [comment]
Ok, maybe you are right. From description it looks like datetime type used instead of datetime2 specified in mapping and should be easy to fix.

**Comment by sdanyliv** [comment]
What i've found - datetime2 is not handled correctly in whole library. It is more global work.
