### ISSUE TITLE
Wrong version of System.Threading.Tasks.Extensions.dll in linq2db.PostgreSQL 2.9.4

### ISSUE THREAD

**Issue by FunctorPrototype** [linq2db/linq2db#2001]
Generating models using T4 templates throws exception due version of System.Threading.Tasks.Extensions.dll. T4 requres version 4.1.0.0 but [2.9.4 linq2db.PostgreSQL](https://www.nuget.org/packages/linq2db.PostgreSQL/2.9.4) contains version 4.2.0.0 in tools folder

```
Exception message: Running transformation: System.IO.FileNotFoundException: Could not load file or assembly "System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" or one of its dependencies. The system cannot find the file specified
Stack trace: File name: 'System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   in Npgsql.NpgsqlConnection.Open(Boolean async, CancellationToken cancellationToken)
   in Npgsql.NpgsqlConnection.Open()
   in LinqToDB.Async.AsyncDbConnection.Open()
   in LinqToDB.Data.DataConnection.EnsureConnection()
   in LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   in Microsoft.VisualStudio.TextTemplating4B543A34388238D1D3DCB1B010C8938059517179F9614D5C27B1D1D118E5DD8F580ECF64D0EA61C90FCB445DA4CA08F59F800E289475CF8F27CF6C6731B38020.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) в ...\.nuget\packages\linq2db.postgresql\2.9.4\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:line 105
   in Microsoft.VisualStudio.TextTemplating4B543A34388238D1D3DCB1B010C8938059517179F9614D5C27B1D1D118E5DD8F580ECF64D0EA61C90FCB445DA4CA08F59F800E289475CF8F27CF6C6731B38020.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in ...\.nuget\packages\linq2db.postgresql\2.9.4\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:line 419
   in Microsoft.VisualStudio.TextTemplating4B543A34388238D1D3DCB1B010C8938059517179F9614D5C27B1D1D118E5DD8F580ECF64D0EA61C90FCB445DA4CA08F59F800E289475CF8F27CF6C6731B38020.GeneratedTextTransformation.LoadPostgreSQLMetadata(String connectionString) in ...\.nuget\packages\linq2db.postgresql\2.9.4\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 141
   in Microsoft.VisualStudio.TextTemplating4B543A34388238D1D3DCB1B010C8938059517179F9614D5C27B1D1D118E5DD8F580ECF64D0EA61C90FCB445DA4CA08F59F800E289475CF8F27CF6C6731B38020.GeneratedTextTransformation.TransformText() in ...\source\repos\CodegenerationForMonitoring\CodegenerationForMonitoring\Models\Monitoring.tt:line 42
```

### Steps to reproduce
Generate classes from postgres database using T4 templates. Manually replacing System.Threading.Tasks.Extensions.dll from [System.Threading.Tasks.Extensions 4.3](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/4.3.0) in tools directory solves problem

### Environment details
linq2db version: *2.9.4*
Database Server: *postgres:11.4*
Database Provider: *docker container*
Operating system: *windows 10 pro*
.NET Framework: *core 3.1*

**Comment by MaceWindu** [comment]
Note: issue exists because we take tools assemblies from tests build outputs and this assembly is one of 3rd party assemblies, referenced by multiple providers by different version number. Which means we need to package different dependencies for different t4 nugets.

Anyway, tools packaging changes needed as part of #Developer support in near future...

**Comment by MaceWindu** [comment]
That's strange. I can confirm that we use newer version of  `System.Threading.Tasks.Extensions` but it doesn't give me any errors and npgsql itself declares that it wants v4.1.0+, which 4.2.0 satisfies.

Which version of visual studio you use to run templates? Or you run it using something else?

**Comment by MaceWindu** [comment]
Anyway, I will downgrade it for now and in v3 we will rework it anyway when we will add #develop support

**Comment by FunctorPrototype** [comment]
> That's strange. I can confirm that we use newer version of `System.Threading.Tasks.Extensions` but it doesn't give me any errors and npgsql itself declares that it wants v4.1.0+, which 4.2.0 satisfies.
> 
> Which version of visual studio you use to run templates? Or you run it using something else?

VS 2019 (Version 16.4.0)
