### ISSUE TITLE
T4 Templates unable to resolve LinqToDBT4OracleTemplatesDirectory

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2002]
I'm creating a .NET Core 3.1 Console Application in Visual Studio 2019.
I have added the nuget package linq2db.Oracle.Managed (2.9.4).
I have copied LinqToDB.Templates\CopyMe.Oracle.tt.txt to .\DataModels\CopyMe.Oracle.tt.
Running TextTemplatingFilePreprocessor with .\DataModels\CopyMe.Oracle.tt doesn't work:

`error : Failed to resolve include text for file: C:\...\$(LinqToDBT4OracleTemplatesDirectory)LinqToDB.Oracle.Tools.ttinclude`

It seams that linq2db.Oracle.Managed.props is not compiled or included in the project.

### Environment details
linq2db version: 2.9.4
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (2.18.3)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by filippobottega** [comment]
Solved in linq2db.Oracle.Managed (3.0.0-preview.1).

Thank you

**Comment by MaceWindu** [comment]
I'll reopen it, as we should make sure 2.x branch still works

**Comment by MaceWindu** [comment]
I cannot reproduce it, but from error message I can see that props file from nuget build folder wasn't used for some reason: `LinqToDBT4OracleTemplatesDirectory` msbuild property wasn't replaced with value from props file.

To me it looks like CPS/nuget issue which is very hard to report without stable reproducable case.

If you can reproduce it, I would recommend to fill issue against https://github.com/dotnet/project-system

**Comment by MaceWindu** [comment]
as a hint - check generated props file obj\ folder, it should contain something like
```
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)linq2db.oracle.managed\2.9.4\build\linq2db.Oracle.Managed.props" Condition="Exists('$(NuGetPackageRoot)linq2db.oracle.managed\2.9.4\build\linq2db.Oracle.Managed.props')" />
  </ImportGroup>
```

**Comment by MaceWindu** [comment]
Also check that custom tool for tt file is set to `TextTemplatingFileGenerator `, not `TextTemplatingFilePreprocessor `

**Comment by MaceWindu** [comment]
Ok, we identified that it is caused by incorrect custom tool used - when you create new t4 file in visual studio, you should select `Text Template`, not `Runtime Text Template`.  I will check if we can detect it and generate proper error message to user.

**Comment by MaceWindu** [comment]
For some yet unknown reason, changing custom tool doesn't fix SDK project (old netfx projects handle it properly) - probably `TextTemplatingFilePreprocessor` changes something in project properties so it cannot recover after it :smile:
