### ISSUE TITLE
ToValidNameDefault error

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2003]
The ToValidNameDefault function in DataModel.ttinclude file has an error.
`if (NormalizeNames && mayRemoveUnderscore && name.Contains("_"))`
has to be changed in:
`if (NormalizeNames && mayRemoveUnderscore)`
because column names without underscores are not converted to lower case if NormalizeNames is true.

### Environment details
linq2db version: 3.0.0-preview.1
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (3.0.0-preview.1)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by MaceWindu** [comment]
I've added fix, but it is disabled by default to not break existing code for other users https://github.com/linq2db/linq2db/pull/2015/files#diff-ab3d85524e051f745d4fd17003da6397R262
