### ISSUE TITLE
Linq StartsWith() translate to "like" in sql query (Firebird)

### ISSUE THREAD

**Issue by konstsch** [linq2db/linq2db#2005]
Linq StartsWith() translate to "like" in sql query(Firebird)
for example:
`from c in db.GetTable<MAN>() where c.Name.StartsWith(txt) select c.Name`
linq2db translate it to:
`select name from man where name like "txt" escape "~"`
but I think should be:
`select name from man where name **starting with** "txt"`

**Comment by Franki1986** [comment]
I am not sure if this should be changed. 'like' is standard sql. Although internally the query for like '%Hello' is converted to starting with.

**Comment by konstsch** [comment]
if I use StartWith() or Contains()
I get iterated over all the records in the table,
but should get a search by index.

**Comment by Franki1986** [comment]
Are you sure? If I use Like '%' I also get a plan with the right index. 
This is from the [docs](https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-commons-predicates.html):

_About LIKE and the Optimizer
Actually, the LIKE predicate does not use an index. However, if the predicate takes the form of LIKE 'string%' , it will be converted to the STARTING WITH predicate, which will use an index._

But I can understand your point, the firebird advice is to directly use a starting with...

**Comment by Franki1986** [comment]
You could try and make a pr.

I think overriding this: [BasicSqlBuilder](https://github.com/linq2db/linq2db/blob/492a44f09f39ad86dea78419e3f3f589e8b4843f/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L2141)

here [FirebirdSqlBuilder](https://github.com/linq2db/linq2db/blob/edde2b04f79db022d43f07127baa0108f28f71d8/Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs)

should work.

**Comment by sdanyliv** [comment]
Do not create additional PRs, i think it should be a part of #1996

**Comment by konstsch** [comment]
I read all the links, but still did not understand how to get a query with StartWith or let it to use the index...

**Comment by Franki1986** [comment]
Look at the blog. There is an example for the between method.

**Comment by sdanyliv** [comment]
@konstsch, you can write simple workaround:
```cs
public static class FB
{
    [Sql.Expression("STARTS WITH {0}", PreferServerSide = true, IsPredicate = true)]
    public static bool StartsWith(string text)
    {
        return text.StartsWith(text);
    }
}
```
```cs
from c in db.GetTable<MAN>() where FB.StartsWith(c.Name) select c.Name
```

**Comment by konstsch** [comment]
Should this work? I get: 	`WHERE p1 = 1`

**Comment by MaceWindu** [comment]
should be
```cs
public static class FB
{
    [Sql.Expression("{0} STARTING WITH {1}", PreferServerSide = true, IsPredicate = true)]
    public static bool StartsWith(string text, string template)
    {
        return text.StartsWith(template);
    }
}
```

**Comment by konstsch** [comment]
YES. it works! Thanks!

**Comment by sdanyliv** [comment]
@MaceWindu, thanks, my fault.
