### ISSUE TITLE
Issues with transactions

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2006]
In the readme.md we have the following example for transactions:

	using (var db = new DbNorthwind())
	{
	  db.BeginTransaction();
	  
	  // ... select / insert / update / delete ...

	  if (somethingIsNotRight)
	  {
		db.RollbackTransaction();
	  }
	  else
	  {
		db.CommitTransaction();
	  }
	}

a friend of mine had a problem with disposed transactions...

for me it looks like, that this code is not any more correct. cause BeginTransaction now returns a "DataConnectionTransaction" wich is not used and this will in it's own Dispose, dispose the transaction...

**Comment by jogibear9988** [comment]
@sdanyliv @MaceWindu 
can someone of you say if I'm correct? Is the example wrong?

**Comment by MaceWindu** [comment]
I would say, example is not wrong, but a bit confusing.
`DataConnectionTransaction` methods just call DataConnection methods, so it is not required to call them on transaction object

**Comment by jogibear9988** [comment]
cause as I see the DataConnection has no Reference to the DataConnectionTransaction only the other way around...

**Comment by MaceWindu** [comment]
GC calls only finalizer, and we don't have it defined for DataConnectionTransaction

**Comment by jogibear9988** [comment]
@MaceWindu 
never knew that... so it seems to be correct...
