### ISSUE TITLE
JSONB update

### ISSUE THREAD

**Issue by pavelvondrasek** [linq2db/linq2db#2007]
Hi,

I'm using Postgres driver with jsonb and is possible to call jsonb_set in update command? I would like to update only one json property not all json values.

Does exist some workaround to do that or I should use npgsql to call plain SQL update manually?

Thanks for you reply!

**Comment by MaceWindu** [comment]
We don't have already exisings bindings for this function [yet](https://github.com/linq2db/linq2db/issues/1791), so you need to add it to your code. Something like that:
```cs
[Sql.Function(Name="pg_catalog.jsonb_set", ServerSideOnly=true)]
		public static string? JsonbSet(string? jsonb_in, object? path, string? replacement, bool? create_if_missing)
		{
			throw new InvalidOperationException();
		}
```
and then just use in update statement:
```cs
db.MyTable
    .Where(some_filter)
    .Set(_ => _.JsonbField, _ => JsonbSet(_.JsonbField,  path, replacement, false))
    .Update();
```

**Comment by pavelvondrasek** [comment]
Thank you! It works very well. :-) 

Wish you Merry Christmas!!! 

I love Linq2db every time I use it more and more. I moved from EF Core and now I'm very happy!
