### ISSUE TITLE
MySQL CreateTable DataType varchar to char issue

### ISSUE THREAD

**Issue by Tommybearrr** [linq2db/linq2db#2020]
When creating a table with my the MySQL Provider and a column data type of varchar, it converts the column type to char.

Method CreateTable<T>();

e.g. Columns in POCO:
 [Column(Order = 2, DataType = LinqToDB.DataType.VarChar, Length = 512)]
        public string Name { get; set; }
        [Column(Order = 3, DataType = LinqToDB.DataType.VarChar, Length = 64)]
        public string Value { get; set; }

are scripted as:
  `Name` char(255) DEFAULT NULL,
  `Value` char(64) DEFAULT NULL,

this does not seem correct behavior.
I tried all DataTypes and non produce varchar(512) in the database.

Currently using version 2.94.

**Comment by MaceWindu** [comment]
workaround: you can specify type using DbType property

**Comment by Tommybearrr** [comment]
Thank you Master Windu, workaround works but will be an issue later if I want to use the same POCO with a different provider, so I hope we get a fix.
Thanx again.
