### ISSUE TITLE
Postgres RETURNING

### ISSUE THREAD

**Issue by pavelvondrasek** [linq2db/linq2db#2021]
Hi,

I'm reading book about Postgres and I would like to use RETURNING *. I found it isn't possible for now in Linq2db.

Is any simple way how can I implement in my project? Can you give me advice how to do it?

Thank you!
Pavel

**Comment by sdanyliv** [comment]
Returning for which commands? We already started implementing such functionality for MSSQL Server, but it needs a lot of our efforts to make it complete.

**Comment by pavelvondrasek** [comment]
I think most useful is for insert/update :)

**Comment by sdanyliv** [comment]
Unfortunately, we do not have a lot of time to do that in nearest several months. There are a lot of features that need to be finished.

**Comment by pavelvondrasek** [comment]
Ok, I understand :) 

I'm reading your PR with output command for insert and I don't know that I'm able to do that for Postgres. I think it's hard for me because I don't know Linq2db codebase :(

**Comment by sdanyliv** [comment]
You have to extend SqlBuilder, because AST for returning (output) already in place. Also I've started method `BuildReturningSubclause` in PostgreSQLSqlBuilder.cs

**Comment by pavelvondrasek** [comment]
It is in dev-dml-output branch? :)

**Comment by sdanyliv** [comment]
Yes.

**Comment by MaceWindu** [comment]
I'm gonna close it as we already have #979 to track pqsql support
