### ISSUE TITLE
Exception when specific Sql.AssociationAlias is set

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#2022]
Hi,

Usually most of us set `LinqToDB.Common.Configuration.Sql.AssociationAlias` to `null` or just `"{0}"`, whatever. That works fine producing query with association for example `[Table].[Field]`.

However when `AssociationAlias` is set for example to `"db].[{0}";` we receive exception because produced query is `[db].[Table].[Field]`.

I know... Nobody will set such a fancy association alias as this :) So you can close this issue if you think it is irrelevant bug.

**Comment by MaceWindu** [comment]
We need to check wether we accept raw SQL there. If not, we should pass alias through name `Convert` api

**Comment by MaceWindu** [comment]
Confirmed as bug. `ConvertType.NameToQueryTableAlias` conversion should perform required escaping. Remove it from next release as low impact issue.

**Comment by MaceWindu** [comment]
Fixed in `6.0.0-preview.1`
