### ISSUE TITLE
Happy new year!

### ISSUE THREAD

**Issue by DimitrOkeanij** [linq2db/linq2db#2024]
Thanks for this awesome framework and for your great job on it!
Happy new year 🎄☃️❄️ !

**Comment by MaceWindu** [comment]
Thanks! :santa:

**Comment by sdanyliv** [comment]
It is not possible right now, but i have ideas how to do that https://github.com/linq2db/linq2db/issues/1404#issuecomment-558098581
Not easy but will find time to implement.

**Comment by sdanyliv** [comment]
It is not possible right now, but i have ideas how to do that https://github.com/linq2db/linq2db/issues/1404#issuecomment-558098581
Not easy but will find time to implement.
