### ISSUE TITLE
Max records for Merge Api

### ISSUE THREAD

**Issue by frankiDotNet** [linq2db/linq2db#2027]
Hello,

I am using Firebird with the Merge Api. Unfortunately Firebird has it's size problems with big union queries. Is there a way to create a Merge extension that gets the size of maximum records for an operation?

```
db.GetTable<T>()
    .Merge()
    .Using(yourList, 100) // here you pass the maximum count of records for a round trip
    .OnTargetKey()
    .UpdateWhenMatched()
    .InsertWhenNotMatched()
    .Merge();
```

**Comment by MaceWindu** [comment]
I have mixed feelings about it. From one side I'm not a big fan of it, as it is something, that could be implemented in helper method. From other side it's kinda useful for client-side list sources and we have similar option for bulk copy.

**Comment by Franki1986** [comment]
Because it is kind of a helper funtion, for me it is not vital, it would only be nice to have... Leave it open so next time you have a working process in the Merge Api you can think abot...

**Comment by viceroypenguin** [comment]
Having a max count of records produces incorrect behavior when `.DeleteWhenNotMatchedBySource()` is used - there is no way to create a merge statement that works correctly in this case. As such, I would recommend this only be implemented by consumers who have better awareness of semantics of the data they are trying to merge. 

@frankiDotNet - I'd recommend that we go ahead and close this, if you agree?

**Comment by frankiDotNet** [comment]
For me it's ok
