### ISSUE TITLE
Truncate strings that are too long for db column

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2028]
LinqToDb-Version: 2.9.4
Firebird: 2.1

Hello,

I would like to truncate strings that are too long to fit into a db column.
So every string that does not fit into a column, should be truncated.

I started with 'SetValueToSqlConverter':

```
var fbMappingSchema = (FirebirdMappingSchema)MappingSchema;
         fbMappingSchema.SetValueToSqlConverter(typeof(string), (sb, dt, v) => ConvertStringToSql(sb, dt, (string) v));

private static void ConvertStringToSql(StringBuilder stringBuilder, SqlDataType dt, string value)
{
    //...
}
```

The problem is that SqlDataType does not have the length of the VARCHAR field, that is written.

Any chance to get the information about the length? Or any chance to get the current acting class and Property or Table and Column?

**Comment by MaceWindu** [comment]
Don't think it is possible to get this information here, but I agree that we probably should add it (alongside with precision and scale to SqlDataType).
Note that you also need to add converter to DatParameter to conver parameter values.

**Comment by Franki1986** [comment]
Is it possible to silently truncate strings that are too long?

**Comment by Franki1986** [comment]
I am not sure, but I think this is the default way Ado.Net provider does ..

**Comment by Franki1986** [comment]
Sorry if I am asking another time, but I cannot find a workaround.

**Comment by sdanyliv** [comment]
> I am not sure, but I think this is the default way Ado.Net provider does ..

Nope, because linq2db use standard Ado.Net provider.

> Sorry if I am asking another time, but I cannot find a workaround.

It depends on how you are trying to update/insert record.

**Comment by Franki1986** [comment]
I update the records over the Set method or over DataContext.Update method.

I saw that there is an on entityDescriptor created callback. If I could Set the length property of the columndescriptors there, this could already, but the most of columndescriptor properties are readonly.

**Comment by sdanyliv** [comment]
Ok, I know two ways to do that.

1. You can implement `IExpressionPreprocessor` in your DataConnection class and correct parameters in ExpressionTree for `Set` methods.
2. You can override `ProcessQuery` as shown here
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Samples/ConcurrencyCheckTests.cs#L47

**Comment by Franki1986** [comment]
Will try tomorow morning and report the workaround here

**Comment by sdanyliv** [comment]
Looks like it will work only for `Set` methods. Update via objects may fail. I suggest to write your own extensions which handle such situations.

**Comment by Franki1986** [comment]
What about making the length property of the columndescriptor to write enabled? So it could be set in the entitydescriptor callback?

**Comment by sdanyliv** [comment]
It is a bad idea, this information should be immutable.

**Comment by Franki1986** [comment]
At the end I will use the FluentMappingBuilder to update the schema.

- initialy load the database schema.

- Create fluent mapping

- Update the type schema

```
public  partial class MyDbContext: LinqToDB.Data.DataConnection
{
    private static DatabaseSchema _schema;

    public static void Initmapping()
    {
		 if (_schema == null)
		 {
			 using (var con = LinqToDB.DataProvider.Firebird.FirebirdTools.CreateDataConnection(connectionString))
			{
				var sp = con.DataProvider.GetSchemaProvider();
				var schema = sp.GetSchema(con,
				new GetSchemaOptions() {GetTables = true, GetForeignKeys = false, GetProcedures = false});
				return schema;
			}
		}
		// Create fluent mapping ...
		var ms = new MappingSchema().GetFluentMappingBuilder();
		
		fluent.Entity<Customer>().HasTableName("CUSTOMER").IsColumnRequired()
            .Property(x => x.Id).HasColumnName("ID").IsPrimaryKey()
            .Property(x => x.Name).HasColumnName("CUSTOMER_NAME");
			
		// Update the properties with the database schema info		
		fluent.UpdateSchema<Customer>(_schema);
	}
}
public static class LinqToDbExtensions
{
  public static void UpdateSchema<T>(this FluentMappingBuilder fluent, DatabaseSchema schema)
  {
	 var ed = fluent.MappingSchema.GetEntityDescriptor(typeof(T));
	 var tableSchema = schema.Tables.FirstOrDefault(t1 => t1.TableName == ed.TableName);
	 if (tableSchema != null && ed != null)
	 {
		foreach (var cd in ed.Columns)
		{
		   var columnSchema = tableSchema.Columns.FirstOrDefault(c => c.ColumnName == cd.ColumnName);
		   if (columnSchema != null)
		   {
			  var entity = fluent.Entity<T>();
			  var param = Expression.Parameter(typeof(T), "p");
			  Expression body = param;
			  body = Expression.PropertyOrField(body, cd.MemberName);
			  var convert = Expression.Convert(body, typeof(object));
			  var selector = (Expression<Func<T, object>>)Expression.Lambda(convert, param);
		   
			  var propBuilder = entity.Property(selector).HasDataType(columnSchema.DataType);
			  if (cd.MemberType == typeof(string))
			  {
				 var l = Convert.ToInt32(columnSchema.Length ?? 0);
				 propBuilder.HasLength(l);
			  }
		   }
		}
	 }
  }
}
```

**Comment by Franki1986** [comment]
I am sure there is a simpler way with your MemberAcessor helper...

**Comment by MaceWindu** [comment]
FYI, in v3 (preview2) we added missing type information and preview3 will add missing precision/scale info

**Comment by MaceWindu** [comment]
per-column converters for both attribute-based and fluent mappings will be available in next release https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273

With this you should be able to apply trimming logic for each column separately. I will close issue for now. Feel free to reopen if it is not something you are looking for

**Comment by sgashua** [comment]
@Franki1986 sorry to use your thread. I can't find way to get value for audit before do insert/update/delete. Where do you get value in ChangeUpdateOrInsertValue(descriptor, item)? I see my item.Expression.Value is null.
