### ISSUE TITLE
MERGE with TVP example

### ISSUE THREAD

**Issue by richbryant** [linq2db/linq2db#2030]
Is there an example anywhere of a MERGE against a table using a table valued parameter from linq2db?

This is currently our primary motivation for not switching to linq2db and it would be nice if it could be resolved.

Thanks.

**Comment by MaceWindu** [comment]
It's a good question... I would say it should work if you combine query-sourced merge with query against TVP. Let me test it quickly

**Comment by MaceWindu** [comment]
I hope we are talking about SQL Server TVP, as we don't support oracle yet

**Comment by richbryant** [comment]
Oh yes, SQL Server is the database target.

**Comment by MaceWindu** [comment]
It works. I've added new TVP test here https://github.com/linq2db/linq2db/commit/1d1124dd89ce3988c7446a14a90ff27ec814517a

Main idea is to create source query using FromSql + DataParameter:
`FromSql($"{new DataParameter(...)}")`. More details in [release notes](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#table-valued-parameters-support-332-1034-1451-1459) for TVP support

Produced sql for query in test:
```sql
MERGE INTO [TestMergeTVPTable] [Target]
USING
(
	SELECT
		[_].[Id],
		[_].[Name]
	FROM
		@p1 [_]
	WHERE
		[_].[Id] IS NOT NULL
) [Source]
ON ([Target].[Id] = [Source].[Id])

WHEN NOT MATCHED THEN
INSERT	
	(
		[Id],
		[Name]
	)
	VALUES
	(
		[Source].[Id],
		[Source].[Name]
	)
;
```

**Comment by richbryant** [comment]
thanks!
