### ISSUE TITLE
Is there a template for creating a new linq2db db provider?

### ISSUE THREAD

**Issue by richbryant** [linq2db/linq2db#2035]
I'm doing a lot of work with client-side Blazor at the moment and have requirements to store relational data on the client side.  Lucky for me (and everyone) [Sqlite is available compiled to wasm](https://github.com/kripken/sql.js).  This supplies a set of javascript hooks to perform the usual database operations and is extensible to some degree.

However, in order to make it easy for the rest of the team to maintain, I'd like to do the db handling in C# and _obviously_ this leads me to linq2sql, because I'll always leap at the chance to use it.

So, is there an interface i must implement or a template to follow in creating a provider to linq2db (which would package up all the js and keep it away from those who don't want it) ?

Where should I look for that?

**Comment by sdanyliv** [comment]
You can copy `SQLiteDataProvider.cs` code and make your own.
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/DataProvider/SQLite
