### ISSUE TITLE
How to map sql table or values to DDD value objects with constructor parameters

### ISSUE THREAD

**Issue by ftaran** [linq2db/linq2db#2043]
I would like to be able to map my database tables to pure DDD objects that are persistent ignorant, looking at the docs there seems to be a way to achieve this using custom MappingSchemas but there isnt any demonstrable examples for mapping to immutable Value Objects that require constructor parameters as shown below.

```c#
public class Email{
  public Email(string address){
}
}
```
Can anyone provide an example for achieving the top scenario?

**Comment by sdanyliv** [comment]
@ftaran, not verbose help, but you can look here:
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/UserTests/Issue533Tests.cs#L41
