### ISSUE TITLE
Getting DataConnection

### ISSUE THREAD

**Issue by niklas-stake** [linq2db/linq2db#2047]
We're considering replacing System.Data.Linq with LinqToDB - but have stumbled on an issue as follows.

At the core of our fairly large implementation is the DataContext (LinqToDB.DataContext). At times we need to apply a non-standard CommandTimeout. To set this, we need to access the CommandTimeout property of LinqToDB.Data.Dataconnection. The CommandTimeout property is public, but the GetDataConnection() in LinqToDB.DataContext is internal. 

It would be beneficial to have the GetDataConnection method be public instead, - unless there's another way to access/set the CommandTimout having the DataContext as starting point.

Cheers!

**Comment by sdanyliv** [comment]
Few aiming questions:
- You are on the start of converting?
- Why do you use DataContext instead of DataConnection? If it is auto-closing clonnection after each request, we can add additional property to do that.

**Comment by niklas-stake** [comment]
We have made evaluations among different options to get away from System.Data.Linq and the best bet seem to be LinqToDB. We're right now in the test-implementation phase, so I'd say we've left the start phase...

The entire design of the data layer is built on the DataContext-approach. Moving to DataConnection would be possible but a far bigger task. Our implementation is rather performance-focused. Reusing connections, not closing them too early/often etc. 

To facilitate migration from System.Data.Linq (which I assume is a significant 'opportunity' for you) the CommandTimeout property is available on the DataContext (https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.datacontext?view=netframework-4.8). Would be really nice to have the same possibility w LinqToDB

**Comment by sdanyliv** [comment]
You have to use DataConnection instead of DataContext, it is created only for autoclosing connection and for Remote server calls. Only data connection has bulk operations, transactions control and other database related functionality. It is naming difference between two ORMs.
Please read this article also: https://linq2db.github.io/articles/general/Managing-data-connection.html

**Comment by niklas-stake** [comment]
I'm with you on that one - but would prefer if tweaking CommandTimeout would be possible also coming from the DataContext angle

**Comment by sdanyliv** [comment]
I do not see problems in opening `DataContext.GetDataConnection` method.
@MaceWindu, @igor-tkachev, do you have any objections?

**Comment by MaceWindu** [comment]
Could be can of worms. We already duplicate some properties on DataContext and map them to data connection in `GetDataConnection`. Probably it will be better to keep it hidded and just add timeout property to DataContext itself..

**Comment by niklas-stake** [comment]
For what it's worth - I'd be perfectly happy with adding the CommandTimeout prop on DataContext - that would solve our need :)

**Comment by jogibear9988** [comment]
For me it's not clear.

When should I use DataContext and when DataConnection in Linq2DB

**Comment by MaceWindu** [comment]
For me too :rofl:  I always use `DataConnection` in my code

**Comment by jogibear9988** [comment]
I also... I did not even recognize DataContext was here, since i read this issue.

@sdanyliv 
can you give a explanation whats the case of "DataContext"?
