### ISSUE TITLE
how to insert or update without null properties

### ISSUE THREAD

**Issue by yuzd** [linq2db/linq2db#2050]
how to insert or update object without null properties?

for example:

```c#

public class Person
{
    public string Name{get;set;}
      public string School{get;set;} 
} 

// in my db schame, School default value is "test"
var person = new Person {
 Name = "yuzd",
 School = null
};

Db.Insert(person); 

```

i do not want to  set School value .

any ideas to skip null property value  on insert or update ??

**Comment by Franki1986** [comment]
Use [SkipValuesOnUpdateAttribute](https://linq2db.github.io/api/LinqToDB.Mapping.SkipValuesOnUpdateAttribute.html?q=Skip)  or [SkipValusOnInsertAttribute](https://linq2db.github.io/api/LinqToDB.Mapping.SkipValuesOnInsertAttribute.html?q=Skip)

**Comment by yuzd** [comment]
@Franki1986 thanks,but i want to do in case by case . 
if i use SkipValuesOnUpdateAttribute or SkipValusOnInsertAttribute,
i can not do it if School is not null.

can i set SkipValuesOnUpdateAttribute or SkipValusOnInsertAttribute in runtime?

for example:

```c#
public class Person
{
    public string Name{get;set;}
      public string School{get;set;} 
} 

// in my db schame, School default value is "test"
var person = new Person {
 Name = "yuzd",
 School = null
};

Db.Insert(person); //i want ignore null

var person2 = new Person {
 Name = "yuzd",
 School = "goodschool" //  School have value ,so i  do not want to ignore
};
Db.Insert(person); 
```

**Comment by Franki1986** [comment]
I am not sure if I understand you right, but the attributes accepts also values, so if you pass null as parameter value to SkipValuesOnInsertAttribute, only null values are skipped.
For more flexibility you can also inherit from SkipBaseAttribute. 
Look at the test folder, there are a few examples. Sorry for not giving you one, but at the moment I am not at the pc

**Comment by yuzd** [comment]
@Franki1986 thank you comment, its good for me!

**Comment by koujiangheng** [comment]
How to insert a row into a table User

```
using(var db = new database())
User newUser = new User { Email = _recv["email"], Password = _recv["passenc"] };
```
there are no insert function in db or db.User

**Comment by MaceWindu** [comment]
You miss
```cs
using LinqToDB;
```

**Comment by koujiangheng** [comment]
> You miss
> 
> ```cs
> using LinqToDB;
> ```

you are definitely right!

**Comment by sdanyliv** [comment]
@koujiangheng, maybe better to use the following method. It will insert only needed fields.
```cs
db.GetTable<User>().Insert(() => 
  new User { Email = _recv["email"], Password = _recv["passenc"] }
);
```

**Comment by koujiangheng** [comment]
> @koujiangheng, maybe better to use the following method. It will insert only needed fields.
> 
> ```cs
> db.GetTable<User>().Insert(() => 
>   new User { Email = _recv["email"], Password = _recv["passenc"] }
> );
> ```

thank you

**Comment by koujiangheng** [comment]
I have a quetstion, if i have 3 table: Users,Profiles,Namespace,  where Users.userid = Profiles.userid , Profiles.profileid = Namespace.profileid. If i want to insert a row record (like Users.email, Profiles.nick, Namespace.productid, etc.) to database in 3 table, what should i do ?

**Comment by sdanyliv** [comment]
Currently no way to do that in single query, but there are plans to implement that: https://github.com/linq2db/linq2db/issues/1404#issuecomment-558098581
For now you have to start transaction and insert three records.
```cs
using (var tran = db.BeginTransaction())
{
    var userId.   = db.GetTable<User>().InserWithInt32Identity(....);
    var profileId = db.GetTable<Profile>().InserWithInt32Identity(..userId..);
    db.GetTable<Namespace>().Insert(..profileId..);
    tran.Commit();
}
```

**Comment by koujiangheng** [comment]
> Currently no way to do that in single query, but there are plans to implement that: [#1404 (comment)](https://github.com/linq2db/linq2db/issues/1404#issuecomment-558098581)
> For now you have to start transaction and insert three records.
> 
> ```cs
> using (var tran = db.BeginTransaction())
> {
>     var userId.   = db.GetTable<User>().InserWithInt32Identity(....);
>     var profileId = db.GetTable<Profile>().InserWithInt32Identity(..userId..);
>     db.GetTable<Namespace>().Insert(..profileId..);
>     tran.Commit();
> }
> ```
I need update not only u.userid but also u.email u.password, p.nick, p.firstname

**Comment by sdanyliv** [comment]
I think it’s obvious
```cs
using (var tran = db.BeginTransaction())
{
    var userId.   = db.GetTable<User>().InserWithInt32Identity(() => new User {Еmail =..});
    var profileId = db.GetTable<Profile>().InserWithInt32Identity(() = new Profile {UserId = userId, ...);
    db.GetTable<Namespace>().Insert(() => new Namespace { ProfileId = profileId, ...);
    tran.Commit();
}
```
Take a look at small video which shows almost all CRUD operations.
https://youtu.be/m--oX73EGeQ

**Comment by koujiangheng** [comment]
> I think it’s obvious
> 
> ```cs
> using (var tran = db.BeginTransaction())
> {
>     var userId.   = db.GetTable<User>().InserWithInt32Identity(() => new User {Еmail =..});
>     var profileId = db.GetTable<Profile>().InserWithInt32Identity(() = new Profile {UserId = userId, ...);
>     db.GetTable<Namespace>().Insert(() => new Namespace { ProfileId = profileId, ...);
>     tran.Commit();
> }
> ```
> 
> Take a look at small video which shows almost all CRUD operations.
> https://youtu.be/m--oX73EGeQ

thank you

**Comment by huahaitao** [comment]
> 使用[SkipValuesOnUpdateAttribute](https://linq2db.github.io/api/LinqToDB.Mapping.SkipValuesOnUpdateAttribute.html?q=Skip) 或[SkipValusOnInsertAttribute](https://linq2db.github.io/api/LinqToDB.Mapping.SkipValuesOnInsertAttribute.html?q=Skip)

HI, I am a beginner of linq2db. I used EF core before. I used to set fields to not null and give it a default value , 0 for bit , sysutcdatetime() for datetime2(7) etc.
It can work well in EF, but does not work in linq2db. If I insert a entity without set value to the field which has default value in db. It will insert a NULL if it's nullable ,or insert a C# default value if it's not null. eg. 0001-01-01 00:00:00.0000000

how can i make the database default value work in linq2db ? thanks!

btw. I manully update the generated.cs file like this:
[Column,     Nullable, SkipValuesOnInsert(null)] public DateTime?  CreatedOnUtc        { get; set; }
it works when the field is nullable. 
When the db schema changes , It will be erased when I regenerate XXX.generated.cs.
How can linq2db recognize the fields that have default value and generate "SkipValuesOnInsert(null)" automatically? thanks!

**Comment by sdanyliv** [comment]
You can do that by applying attribute In T4 model before `GenerateModel()` call. Something like this:
```cs
foreach (var t in Tables.Values)
{
   foreach (var c in t.Columns.Values)
   {
       c.Attributes.Add(new Attribute("SkipValuesOnInsert", "null"));
   }
}
```

**Comment by yuzd** [comment]
I have a question for [SkipValuesOnInsert or  SkipValuesOnUpdate]
for example:


```csharp
	[Table("product")]
	public partial class Product
	{
		/// <summary>
		/// 产品ID
		/// </summary>
		[Column("productId"),   PrimaryKey, Identity] public long   ProductId   { get; set; } // bigint(20)
		/// <summary>
		/// 产品名称
		/// </summary>
		[Column("productName"), Nullable            ] public string ProductName { get; set; } // varchar(50)
		/// <summary>
		/// 产品描述
		/// </summary>
		[Column("productDesc"), Nullable  ,SkipValuesOnInsert(null), SkipValuesOnUpdate(null)] public string ProductDesc { get; set; } // varchar(50)
	}

```

```csharp
 static void Main(string[] args)
        {
            DataConnection.DefaultSettings = new MySettings();

            DataConnection.TurnTraceSwitchOn();

            DataConnection.OnTrace = OnTrace;

            using (var db = new TestormDB("TestormDB"))
            {
                Product p1 = new Product
                {
                    ProductName = "p1",
                    ProductDesc = null
                };

                p1.ProductId = db.InsertWithInt64Identity(p1);

//sql
-- TestormDB MySqlConnector MySql
DECLARE @ProductName VarChar(2) -- String
SET     @ProductName = 'p1'

INSERT INTO `product`
(
	`productName`
)
VALUES
(
	@ProductName
)

// what should I do when I want to update ProductDesc  to null.
                p1.ProductDesc = null;
                
                db.Update(p1); 

//sql
-- TestormDB MySqlConnector MySql
DECLARE @ProductName VarChar(2) -- String
SET     @ProductName = 'p1'
DECLARE @ProductId Int64
SET     @ProductId = 6

UPDATE
	`product` `t1`
SET
	`t1`.`productName` = @ProductName
WHERE
	`t1`.`productId` = @ProductId

//  so set ProductDesc to  null  i have to do this, but  it is not good way if have a lot of fields 
                db.Products.Where(r => r.ProductId.Equals(p1.ProductId)).Set(r => r.ProductDesc, (string)null).Update();

//sql

-- TestormDB MySqlConnector MySql
DECLARE @ProductId Int64
SET     @ProductId = 7

UPDATE
	`product` `r`
SET
	`r`.`productDesc` = NULL
WHERE
	`r`.`productId` = @ProductId
            }

            Console.WriteLine("Hello World!");
        }
```

**Comment by huahaitao** [comment]
thanks!
I use the follows instead.
        GetColumn("Customer", "Deleted").SkipOnInsert = true;
	GetColumn("Customer", "CreatedOnUtc").SkipOnInsert = true;
otherwise ,I will make these fields Nullable if I use SkipValuesOnInsert.

Another question is I tried to insert an entity , like this:
       var customer = db.Customers.Where(c => c.Id == 1).FirstOrDefault();
       DataModels.Task task = new DataModels.Task();
       task.Creator = customer;
       task.TypeId = 1;
       await db.InsertAsync(task);
I run the code ,then I found that the CreatorId field is null (it supposed to be 1) . When I get the record then ,I found that the task.Type is null also (it supposed to be the TaskType object with id=1).
What should I do with the foreignKey property in linq2db. 
Thanks!

**Comment by sdanyliv** [comment]
What can I say, it is typical mistake when people start using linq2db.

linq2db do not have change tracker. So working with linq2db in EF way is a mistake.
You have to insert everything by hands, like in SQL and assign IDs, not objects. Associations are introduced only for easy SQL generation via LINQ, assigning to them do NOTHING.
```cs
       DataModels.Task task = new DataModels.Task();
       task.CustomerId = c.Id;
       task.TypeId = 1;
       await db.InsertAsync(task);
```
Or
```cs
      await db.Tasks.InsertAsync(() => new Task { CustomerId = c.Id, TypeId = 1 });
```
> //  so set ProductDesc to  null  i have to do this, but  it is not good way if have a lot of fields 
                db.Products.Where(r => r.ProductId.Equals(p1.ProductId)).Set(r => r.ProductDesc, (string)null).Update();

If you know which fields needs to be updated, update only them.
```cs
var productsToUpdate = db.Products.Where(r => r.ProductId == p1.ProductId).AsUpdatable();
if (IsDescriptionUpdated)
   productsToUpdate  = productsToUpdate.Set(r => r.ProductDesc, p1.Description);
if (IsOtherFieldUpdated)
   productsToUpdate  = productsToUpdate.Set(r => r.OtherField, p1.OtherField);

var affectedRecordsCount = productsToUpdate.Update();
if (affectedRecordsCount == 0)
   throw new Exception("Product not found.")
```
Looks complex, but it can be generated automatically.

Answering future questions. Why not change tacker: 

- because change tracker for updating record needs selecting record from database. It is additional roundtrip to database.
- because there is no fast way to change several fields for 1000 records - you have to load them and then you will have 1000 updates. 
- because you can not use MySql functions in update process, like this
```cs
productsToUpdate  = productsToUpdate.Set(r => r.ModificationDate, r => Sql.CurrentTimestamp);
productsToUpdate  = productsToUpdate.Set(r => r.UpdateCount, r => r.UpdateCount + 1);
```

linq2db helps in writing effective type safe SQL. If you expect complex objects manipulations, saving graph of objects - it is not what library offer.
