### ISSUE TITLE
help me , migrate from bltoolkit to linq2db 

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2055]
hi

my project worked by bltoolkit like

`   [SqlQuery(@"UPDATE Tbl.Art SET LikeScore=ISNULL(LikeScore,0)+1 WHERE ArticleId=@ArticleId")]
        public abstract void ArticleLike(int articleId);`

I don't know  in linq2db how ?

**Comment by MaceWindu** [comment]
Don't see a reason to use raw SQL here. This should work:
```cs
db.Arts
    .Where(r => r.ArticleId == articleId)
    .Set(r => r.LikeScore, r => (r.LikeScore ?? 0) + 1)
    .Update();
```

**Comment by MajidSafari** [comment]
i want use raw SQL

**Comment by MaceWindu** [comment]
you can use [FromSql](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#raw-sql-support-in-linq-queries-1388)

**Comment by MajidSafari** [comment]
i want to create Data Access Layer  by linq2db that can  insert update delete  execute in  this layer 
like

`     public static int Insert(T entity)
        {
            return Query.Insert(entity);
        }
`

how i can  do this ?

**Comment by MajidSafari** [comment]
tanx for response @MaceWindu

**Comment by sdanyliv** [comment]
@MajidSafari, this is repository pattern. You can find a tons of realizations in github even for linq2db. 
I personally don’t like this pattern.
Do you have any reason to use Raw SQL? Linq2db created for simplifying SQL generation and it is a strongest part of the library.
