### ISSUE TITLE
Sending SQL queries through custom connector.

### ISSUE THREAD

**Issue by SergeyA** [linq2db/linq2db#2060]
В новом проекте появилось ограничение - все запросы к БД должны выполняться через специальный компонент "MySuperDbConnection". В компоненте реализован набор методов ExecuteScalar(DbCommand), ExecuteReader(DbCommand) и пр. Целевая БД - postgres. 

Можно ли как то попросить linq2db выполнять все запросы через этот компонент?

Цель - использовать всю мощь linq2db для формирования статически типизованных запросов, а выполнять их через свою библиотеку.

**Comment by MaceWindu** [comment]
You should loot at `DataConnection` constructors that accept `IDbConnection`/`Func<IDbConnection>`. There you need to pass your `MySuperDbConnection` or adapter to `MySuperDbConnection`.

Also disable use of npgsql-specific API: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Configuration.cs

**Comment by MaceWindu** [comment]
Note that because execute methods belong to DbCommand, you will need to implement own `DbCommand` and return it from custom connection.

**Comment by sdanyliv** [comment]
@SergeyA, also we have global interceptor. Maybe it can help

You can inject here:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DbCommandProcessor/DbCommandProcessorExtensions.cs#L22

Implement IDbCommandProcessor and assign this static property.

**Comment by filippobottega** [comment]
@SergeyA please use English if possible when publishing an issue. Thank you!
