### ISSUE TITLE
SQL Error: lack of space between the CTE's name and 'AS' keyword

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2061]
I have created a CTE and I need to get the row count letting the server to calculate the result.

There is an error on emitted SQL:

``` SQL
-- Wip Oracle.Managed Oracle
WITH AllowedNcCodeAS -- Should be AllowedNcCode AS 
(
        SELECT DISTINCT
                ncCode.HANDLE as NcCodeBo,
                ncCode.NC_CODE as NcCode,
                ncCode.DESCRIPTION as NcCodeDescription
        FROM
                WIPUSER.NC_CODE ncCode
                        INNER JOIN WIPUSER.NC_GROUP_MEMBER ncGroupMember ON ncCode.HANDLE = ncGroupMember.NC_CODE_OR_GROUP_GBO
        WHERE
                ((ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_AUTO' OR ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_MAN') OR ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_ALL')
)
SELECT
        COUNT(*) as Count_1
FROM
        AllowedNcCode item
```

I'm using the CTE as:

``` C#
            var countQuery = wipCte.AllowedNcCode().Select(item => new { Count = Sql.Ext.Count().ToValue() });
            var sqlText = ((IExpressionQuery)countQuery).SqlText;
```

Code project:
[LinqToDb.Sample3.zip](https://github.com/linq2db/linq2db/files/4118189/LinqToDb.Sample3.zip)

### Environment details
linq2db version: 3.0.0-preview.1
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (3.0.0-preview.1)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by sdanyliv** [comment]
@filippobottega, why not use standard Count? And which error do you have?

var countQuery = wipCte.AllowedNcCode().Count();

**Comment by sdanyliv** [comment]
Also SQL can be retrieved easily with
```cs
var sqlText = wipCte.ToString();
```

**Comment by filippobottega** [comment]
@sdanyliv Thank you!

With:
``` C#
var count = wipCte.AllowedNcCode().Count();
```

I get:

``` SQL
WITH GetAllowedNcCode (NcCodeBo, NcCode, NcCodeDescription)
AS
(
	SELECT DISTINCT
		ncCode.HANDLE as NcCodeBo,
		ncCode.NC_CODE as NcCode,
		ncCode.DESCRIPTION as NcCodeDescription
	FROM
		WIPUSER.NC_CODE ncCode
			INNER JOIN WIPUSER.NC_GROUP_MEMBER ncGroupMember ON ncCode.HANDLE = ncGroupMember.NC_CODE_OR_GROUP_GBO
	WHERE
		((ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_AUTO' OR ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_MAN') OR ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_ALL')
)
SELECT
	Count(*) as cnt
FROM
	GetAllowedNcCode t1
```

> why not use standard Count? And which error do you have?

I was not sure if Count() where executed on the server or on the client.
Using LastQuery I have checked it.

> Also SQL can be retrieved easily with...
Thank you, it's more easy...

Anyway I think to have found a little bug to fix ;)

**Comment by sdanyliv** [comment]
Yes, another case :) I have to figure out how to fix that.

**Comment by sdanyliv** [comment]
@filippobottega, for testing purposes turn queries logging on 
```
DataConnection.TurnTraceSwitchOn();
DataConnection.WriteTraceLine = (s, s1) => Debug.WriteLine(s, s1);
```
And you can read queries in Output. Or redirect to console.

**Comment by filippobottega** [comment]
@sdanyliv Thanks you!

**Comment by MaceWindu** [comment]
BTW, @filippobottega.
You use v3 preview and we still have unfinished work for next preview. Will it be possible for you to use azure build after fix merged to v3 branch? Otherwise we will need to release next preview without all planned changes (also fine, but would preferer to have more solid previews :smile: ).

**Comment by filippobottega** [comment]
@MaceWindu Don't worry, I'll wait for next preview. Feel free to finish the work.

**Comment by filippobottega** [comment]
Hi @MaceWindu , I need to get a new build to use linq2db. I'm using version v3 preview as you say.
I don't understand where is "azure build". How can I upgrade my linq2db version?

**Comment by MaceWindu** [comment]
For v3 we switched from MyGet feed to Azure Artifacts for preview versions: https://dev.azure.com/linq2db/linq2db/_packaging?_a=feed&feed=linq2db%40Local

Clicking to `Connect to feed` button will get you nuget feed to use with Visual studio
