### ISSUE TITLE
Exception when debugging query in VS2017

### ISSUE THREAD

**Issue by RoyChase** [linq2db/linq2db#2064]
This looks to be the same issue as #1795 but that wasn't really resolved.

If, using VS2019 targeting .Net Framwork I put a breakpoint on an IQueryable then stepping over it gives a TypeInitializationException.  The same code running in VS2017 works fine.

If targeting .Net Core it works fine.

Without the breakpoint it works fine in all cases.

I have created the simplest demo code that I can https://github.com/RoyChase/DebugIssue.git which contains a .Net Framework console app and a .Net Core console app.

I agree that it look sot be something that MS has done with VS2019 but I'm hoping that you might be able to trace the issue deeper into the Linq2DB source code to be able to isolate it further and perhaps even make a fix.  Maybe System.Diagnostics.Debugger.NotifyOfCrossThreadDependency may be of use?

### Environment details
linq2db version: 2.9.5
Database Server:  Any
Database Provider: Any
Operating system: Windows 10
.NET Framework: 4.7.1

**Comment by sdanyliv** [comment]
Which VS 2019 version do you use?

**Comment by MaceWindu** [comment]
Yep, for @sdanyliv it fails in same place with same error as in referenced exception. For me it works fine, so basically there is something that changes debugger behavior, but we cannot identify what.

So we will change code, that triggers exception as workaround.

**Comment by MaceWindu** [comment]
Closed by #2066

**Comment by RoyChase** [comment]
Thanks for your, as usual, brilliant response.
