### ISSUE TITLE
Cannot access when i use conn.ChangePassword("string") method.

### ISSUE THREAD

**Issue by sarfaraz78615** [linq2db/linq2db#2069]
Unable to use change the password in .NetCoreApp, It is accessible through the .Net Framework only.

```
Exception message: CS1061	'SQLiteConnection' does not contain a definition for 'ChangePassword' and no accessible extension method 'ChangePassword' accepting a first argument of type 'SQLiteConnection' could be found (are you missing a using directive or an assembly reference?)	SQLiteSecurity.Core (netcoreapp3.1)
Stack trace: No Trace
```

### Here is the c# code
```c#
using (var cn = new SQLiteConnection(con))
{
      cn.Open();
      cn.ChangePassword(newpwd);
}
```

I Know #1113 is similar but its not in .netcoreapp

**Comment by sdanyliv** [comment]
I'm not sure that this is linq2db related issue. Ensure which SQLite provider installed.
Anyway, SQLite is hosted here https://github.com/dotnet/efcore

**Comment by MaceWindu** [comment]
ChangePassword method implemented only by .net framework version of System.Data.Sqlite. You need to use PRAGMAs directly
