### ISSUE TITLE
Support for array columns

### ISSUE THREAD

**Issue by dioptryk** [linq2db/linq2db#207]
Hi,

We started using linq2db in our new project and we're really happy with it, everything seems to be working as advertised :) There is one problem though. We have PostgreSQL 9.3 as our DB and we're using array columns in a few tables. It seems support for this is only partial, as DataType is Undefined in linq2db. When defining the model (we use T4 templates) property is generated as an "object"; it is castable to array though, so we can read the values all right. However, the main problem is SELECT WHERE. No matter what we do, it's impossible to search by values in such a column (using Constains, let clause etc.). Usually there is an Exception about not being able to convert LINQ to SQL or NullPointer in linq2db in some internal function requiring Expression Context. I can provide more info if necessary.

My question is, would it be possible to add such support? Even for a few specific types like int or varchar arrays. The truth is I'm considering adding it myself, but perhaps it's in the works already? We really like the idea of array columns because they simplify the model a lot, and wouldn't want to change our schema.

**Comment by igor-tkachev** [comment]
What SQL should be generated?

**Comment by dioptryk** [comment]
Thank you very much for responding.

I think it should work like this: assume we have a table "border_offices" with column "customs_procedures" of type "character varying(2)[]". Then, when using generated model:

LINQ:
=====
var result = from o in DB.border_offices where o.customs_procedures.Contains("5");

should generate SQL like this:
========================
SELECT * FROM border_offices WHERE '5' = ANY (customs_procedures);

Now it throws an exception about not being able to convert "Contains" to SQL.

PostgreSQL array docs:
http://www.postgresql.org/docs/9.3/static/arrays.html

I should probably add that inserting into such columns also works out of the box. Only "WHERE" is a problem.

**Comment by igor-tkachev** [comment]
It can be done, but, of course, it requires some work to do. Any help will be appreciated. For example,  you can add some tests and provide expected result.

**Comment by dioptryk** [comment]
Hi,

Description of some recent issue I read contained the solution to my problem :) I wasn't aware that something like Sql.ExpressionAttribute existed. After I saw it in action I had an implementation ready in a few seconds. For future reference:

>[LinqToDB.Sql.Expression(LinqToDB.ProviderName.PostgreSQL, "{0} = ANY({1})")]
>public bool DbContains<T>(T val, T[] col) where T : IComparable<T>
>{
>    return col.Contains(val);
>}

It works perfectly now and the solution is completely generic. Thanks again for fantastic library!
