### ISSUE TITLE
GroupBy with aggregate fails when using .net core ODATA api library

### ISSUE THREAD

**Issue by djkunkel** [linq2db/linq2db#2070]
I'm still seeing what I think is this issue (https://github.com/linq2db/linq2db/issues/1225) with using Microsoft's ODATA library for .net core. I'm using linq2db 2.9.6.

The test case created (Issue1225Tests.cs) succeeds, but when attempting to do an aggregate in an actual controller with EnableQuery it fails. 

Investigating further, it seems to be trying to call the getter for Value on the wrong parameter in GetParameter in ExpressionBuilder.SqlBuilder.cs. It needs to be calling it on the AggregationWrapper, but is instead trying to call it on the GroupByWrapper which does not have a Value property.

Here is a minimal project demonstrating the issue:
https://github.com/djkunkel/linq2db-aggregate-odata-sample

PeopleController.cs is the one that uses LinqToDb and an example table and data is present in the LinqToDb folder in the project.

OData queries:
/odata/People('Bob')  -- works
/odata/People?$apply=groupby((Title)) -- works
/odata/People?$apply=groupby((Title),aggregate(YearsExperience with sum as TotalExperience))  -- fails

Failure exception:
System.ArgumentException: Property 'System.Object Value' is not defined for type 'Microsoft.AspNet.OData.Query.Expressions.GroupByWrapper' (Parameter 'property')

Thank you for this wonderful project.

**Comment by sdanyliv** [comment]
Thanks for reporting and reproducible case. Will fix that ASAP.

**Comment by djkunkel** [comment]
Hello! I have build the repo at master and added to my example project and the example queries I submitted work now just fine! THANK YOU!

However, attempting to do an $orderby with the aggregate column fails with Linq2db, but succeeds with an in memory collector or with Entity Framework.

Exception:
Message='Convert(new LastInChain() {Name = "TotalExperience", Value = Convert(Convert($it, IEnumerable`1).Select($it => Convert($it.GroupByContainer.Value, Int32)).Sum(), Object)}, AggregationPropertyContainer).Value' cannot be converted to SQL.

Failing ODATA request:
/odata/People?$apply=groupby((Title),aggregate(YearsExperience with sum as TotalExperience))&$orderby=TotalExperience

Example project updated to use Linq2db as a submodule:
https://github.com/djkunkel/linq2db-aggregate-odata-sample

Thank you again for any direction you can give me, or if I should open a new ticket.

**Comment by sdanyliv** [comment]
@djkunkel, please open new issue. And try to cover as much as possible cases. Looks like OData library creates unexpected conversions which we do not handle.
It will be easy to fix, but i have no time to discover them all.
Thanks!

**Comment by sdanyliv** [comment]
Just Odata query is enough, i have created test based on your entitiy which accepts Odata query string.

**Comment by djkunkel** [comment]
Great. I will work through some of our samples and see if I can identify any other cases, then I will open a new ticket.
