### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#2071]
Hello,
 Could you tell me, when Version 3.0 is released ? I want to use Access in my .Net Core project.

Do you have a link to download V3.0 preview ?
Thanks Andreas

**Comment by MaceWindu** [comment]
Preview (with .net core access support) already available from nuget https://www.nuget.org/packages/linq2db/3.0.0-preview.1

Final release of 3.0 expected in about 2 months. In couple of week we hope to release preview2 with more functionality and then probably another preview with smaller changes/fixes.

**Comment by AndreasWaning** [comment]
Thank you
