### ISSUE TITLE
ExpressionQueryImpl<TElement>.ToString() doesn't update SQL text when parameter's values changes

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2073]
Hello,
  when we build queries with linq2db we get an `ExpressionQueryImpl<TElement>` object that implements `IQueryable<T>` interface.
  For example: 

``` C#
...
DataConnection.DefaultSettings = new MySettings();
Configuration.Sql.GenerateFinalAliases = true;

using var db = new WipDB("Wip");
var wipCte = new WipCte(db);

var ncCodeBo = "NCCodeBO:8110,SETUP_OSCILLOSCO";

var result = from item in wipCte.AllowedNcCode() where item.NcCodeBo == ncCodeBo select item;
var sql = result.ToString();
Console.WriteLine(sql);
..
```
Output:
``` SQL
-- Wip Oracle.Managed Oracle
DECLARE @ncCodeBo_1 Varchar2(30) -- String
SET     @ncCodeBo_1 = 'NCCodeBO:8110,SETUP_OSCILLOSCO'

WITH AllowedNcCode (Handle, NcCodeColumn, Description)
AS
(
        SELECT DISTINCT
                ncCode.HANDLE as NcCodeBo,
                ncCode.NC_CODE as NcCode,
                ncCode.DESCRIPTION as NcCodeDescription
        FROM
                WIPUSER.NC_CODE ncCode
                        INNER JOIN WIPUSER.NC_GROUP_MEMBER ncGroupMember ON ncCode.HANDLE = ncGroupMember.NC_CODE_OR_GROUP_GBO
        WHERE
                ((ncGroupMember.NC_GROUP_BO IS NOT NULL AND ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_AUTO' OR ncGroupMember.NC_GROUP_BO IS NOT NULL AND ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_MAN') OR ncGroupMember.NC_GROUP_BO IS NOT NULL AND ncGroupMember.NC_GROUP_BO = 'NCGroupBO:' || ncCode.SITE || ',CATAN_ALL')
)
SELECT
        item.Handle,
        item.NcCodeColumn,
        item.Description
FROM
        AllowedNcCode item
WHERE
        item.Handle = :ncCodeBo_1
```

  If I change ncCodeBo and I print the SQL, I get the previous one because the SQL query is built when I assign the query to the variable result:
``` C#
ncCodeBo = "NCCodeBO:8110,SETUP_OSCILLOSCO2";
sql = result.ToString();
Console.WriteLine(sql);
```
``` SQL
-- Wip Oracle.Managed Oracle
DECLARE @ncCodeBo_1 Varchar2(30) -- String
SET     @ncCodeBo_1 = 'NCCodeBO:8110,SETUP_OSCILLOSCO' -- It should change to "NCCodeBO:8110,SETUP_OSCILLOSCO2"

WITH AllowedNcCode (Handle, NcCodeColumn, Description)
AS
...
```

  My question is: is there a way to get an `ExpressionQueryImpl<TElement>` with a method to call to set only the changing part of the query? For example the parameter ncCodeBo?

  If the query is really huge, rebuilding the query only to change few parameters  is time consuming.

  Thank you!

**Comment by sdanyliv** [comment]
Does it reproducible if you just run queries?

**Comment by filippobottega** [comment]
Argh!!! You are right! The real query changes!
But the db.LastQuery doesn't show the parameter's definitions and I was not aware about the real value of the parameter.
Is there a way to refresh to ToString() value of the ExpressionQueryImpl object? Or to get the last used parameters?

Thank you in advance.

**Comment by sdanyliv** [comment]
Try Query.ClearCaches()

**Comment by filippobottega** [comment]
I have tried Query.ClearCaches() but it doesn't work, the ToString() value is not changed.
The problem is that I need to log all queries for debugging reasons and I'm using SqlText to take the actual query.
db.LastQuery doesn't have the parameter's definition.
Do you know if there is another way to get the complete real SQL query?

**Comment by filippobottega** [comment]
Hello,
  I have found db.Command.Parameters. I'll use these collection to trace the real parameter values.

  If you want you can close this issue for me.

  Thank you for your support!

**Comment by filippobottega** [comment]
Sorry,
  I have another problem: sometime I need to trace the SQL text but I don't call the db, for this reason I don't have a valid LastQuery and Command.Parameters values...

  Yes, I need a sort of ToString() that returns the actual parameter's.

**Comment by sdanyliv** [comment]
> The problem is that I need to log all queries for debugging reasons and I'm using SqlText to take the actual query.

You are missed my message how to log all queries:
```cs
DataConnection.TurnTraceSwitchOn();
DataConnection.WriteTraceLine = (message, category) => YourLogger.Write($"[{category}] {message}");
```

**Comment by filippobottega** [comment]
Hello @sdanyliv ,
I don't need to log all queries, and sometime I need the SQL query without running the query.
I have created this workaround that works very well:
``` C#
DataConnection.DefaultSettings = new MySettings();
DataConnection.DefaultSettings = new MySettings();
Configuration.Sql.GenerateFinalAliases = true;

using var db = new WipDB("Wip");
var wipCte = new WipCte(db);

var ncCodeBo = "NCCodeBO:8110,SETUP_OSCILLOSCO";

var queryBuilder = (Func<IQueryable<AllowedNcCodeOutput>>) (() =>  from item in wipCte.AllowedNcCode() where item.NcCodeBo == ncCodeBo select item);
var result = queryBuilder.Invoke();
var sql = result.ToString(); // Very slow...
Console.WriteLine(sql);

ncCodeBo = "NCCodeBO:8110,SETUP_OSCILLOSCO2";
result = queryBuilder.Invoke();
sql = result.ToString(); // Very fast!
Console.WriteLine(sql);
```
I have discovered that only the first call to `result.ToString()` is slow but the second call is fast and gives me the right result.
You should probably update the documentation to explain the ToString() behavior and to show how to update the  ToString() result if parameters change.

**Comment by sdanyliv** [comment]
It is a bug in ToString(), we have to repopulate parameters for this call. Will fix that.
First query is slow because we parse Expression Tree and provide optimizations. Second query just reuse parsed AST and generated SQL.
