### ISSUE TITLE
 несколько временный таблиц

### ISSUE THREAD

**Issue by sd-mobile** [linq2db/linq2db#208]
При попытке использовать несколько временных таблиц падает с ошибкой
{"Операция является недопустимой из-за текущего состояния объекта."}

   в LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject) в i:\linq2db\Source\Linq\Builder\TableBuilder.cs:строка 486
   в LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level) в i:\linq2db\Source\Linq\Builder\TableBuilder.cs:строка 463
   в LinqToDB.Linq.Builder.SelectContext.<BuildExpression>b__6(IBuildContext ctx, Expression ex, Int32 l) в i:\linq2db\Source\Linq\Builder\SelectContext.cs:строка 122
   в LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) в i:\linq2db\Source\Linq\Builder\SelectContext.cs:строка 881
   в LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level) в i:\linq2db\Source\Linq\Builder\SelectContext.cs:строка 119
   в LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass57.<BuildExpression>b__55(Expression expr) в i:\linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:строка 81
   в LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) в i:\linq2db\Source\Expressions\Extensions.cs:строка 1072
   в LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression) в i:\linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:строка 23
   в LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level) в i:\linq2db\Source\Linq\Builder\SelectContext.cs:строка 94
   в LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) в i:\linq2db\Source\Linq\Builder\SelectContext.cs:строка 64
   в LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() в i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:строка 160
   в LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) в i:\linq2db\Source\Linq\Query.cs:строка 164
   в LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) в i:\linq2db\Source\Linq\ExpressionQuery.cs:строка 77
   в LinqToDB.Linq.ExpressionQuery`1.Execute(IDataContextInfo dataContextInfo, Expression expression) в i:\linq2db\Source\Linq\ExpressionQuery.cs:строка 69
   в LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() в i:\linq2db\Source\Linq\ExpressionQuery.cs:строка 149
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в WSReport.Web.Services.PivotDataService.GetDetailedWellInfo(DataConnection wsCtx, Log logger, Int32 lcid, IQueryable`1 wellsQuery, DateTime yesterday, Dictionary`2 result) в c:\Users\Дмитрий\Source\Workspaces\WSReport\Main\Src\WsReport.Web\Services\PivotDataService.cs:строка 1150

**Comment by igor-tkachev** [comment]
Пример кода?

**Comment by sdanyliv** [comment]
We can reopen issue when additional information appear.
