### ISSUE TITLE
Custom type mapping

### ISSUE THREAD

**Issue by brunolau** [linq2db/linq2db#2082]
I inherited code where I'm having some values stored as JSON in DB column. I'd like to achieve a very simple mapping that serializes / deserializes JSON from the nvarchar column [no other advanced functions such as JSON_VALUE and other needed atm]

In EF Core I can do something like this

```
entity.Property(e => e.NameLocalized)
      .HasColumnName("NameLocalized_JSON")
      .HasConversion(v => JsonConvert.SerializeObject(v), v => JsonConvert.DeserializeObject<LocalizedString>(v));
```

What I'd need to achieve is to custom map the type [ideally], or each property of the type [less ideal, but still doable]. I've tried playing with mappingSchema.SetConverter<LocalizedString, string>, but the debugger never stopped inside my method body. Might be important to notice I'm using Linq2Db in combination with EF Core via linq2db.EntityFrameworkCore package

### Steps to reproduce
For example this simple scenario, which throws [understandably] "cannot be converted to SQL error

```c#
class Program
    {
        private class LocalizedString
        {
            public string English { get; set; }
            public string German { get; set; }
            public string Slovak { get; set; }

        }

        static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                var query = db.Tickets.ToLinq2Db().Where(p => p.Id < 10).Select(p => new
                {
                    Id = p.Id,
                    NameLocalized = p.NameLocalized
                }).ToList();
            }
        }
   }
```

### Environment details
linq2db version: 3.0.0 preview1
Database Server: Azure SQL
Database Provider: SQL Server provider
Operating system: Windows
.NET Framework: .NET Core 3.1

**Comment by sdanyliv** [comment]
Hi, there is a "little" problem, linq2db does not have member by member type mapping. But you can register global conversion.

```cs
// converting from string, because usually JSON is stored as string, but it depends on DataProvider
MappingSchema.Default
   .SetConverter<string, LocalizedString>(v => JsonConvert.DeserializeObject<LocalizedString>(v));

// here we told linq2db how to pass converted value as DataParameter.
MappingSchema.Default
   .SetConverter<LocalizedString, DataParameter>(v => new DataParameter("", JsonConvert.SerializeObject(v), DataType.NVarchar));
```
Sorry away from computer and writing these samples from memory. I think it is obvious to correct mistakes.

**Comment by brunolau** [comment]
I guess I might have hit an issue, or not-supported scenario. If the entity class inherits from a base class, the custom converters don't seem to kick in.

As this might be a linq2db.EntityFrameworkCore issue, I've opened an issue and submitted a repro console project in
linq2db/linq2db.EntityFrameworkCore#28

**Comment by sdanyliv** [comment]
Already fixed in linq2db.EntityFrameworkCore 2.0.3
