### ISSUE TITLE
Oracle "Cross outer apply / lateral" join

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2083]
We got this error from linq2db with oracle:

Database do not support CROSS/OUTER APPLY join required by the query.
   bei LinqToDB.SqlQuery.SelectQueryOptimizer.OptimizeApply(HashSet`1 parentTableSources, SqlTableSource tableSource, SqlJoinedTable joinTable, Boolean isApplySupported, Boolean optimizeColumns) in C:\projects\linq2db\Source\LinqToDB\SqlQuery\SelectQueryOptimizer.cs:Zeile 1022.

but we use orcale 12.c and it seems to be supported now:
https://oracle-base.com/articles/12c/lateral-inline-views-cross-apply-and-outer-apply-joins-12cr1

**Comment by jogibear9988** [comment]
@sdanyliv @MaceWindu 
can someone of you tell me if it's an error in our code or a oracle problem?

**Comment by MaceWindu** [comment]
Right now our oracle support is on v11 level. To support v12/v18 somebody needs to add new dialects support to existing provider.

**Comment by MaceWindu** [comment]
So, basically what is needed:
- add additional dialect versions to provider in postgres or sqlserver way
- test servers configuration for azure, as we need to be able to test it somehow
- implement new dialect features one by one

**Comment by jogibear9988** [comment]
@MaceWindu 
In the Postgres way, how can I change the default version wich is used, if I want that linq2db selects the dataprovider itself?

**Comment by jogibear9988** [comment]
Would it be okay to implement a static property on DataProvider "DefaultVersion"?

**Comment by MaceWindu** [comment]
I think it would be better to implement it in the way sqlserver provider use https://github.com/linq2db/linq2db/blob/199e01c0734b0e3317d71b052356f53d326d2fe6/Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs#L144 :

- if we can detect version from provider/connection name - we use this version
- otherwise if autodetection enabled - ask database for version
- otherwise use some version by default. e.g. if we include v12 support in v3, we can default to v12, otherwise it will be better to use v11 to not introduce behavior change

**Comment by MaceWindu** [comment]
actually same logic used for postgresql provider

**Comment by MaceWindu** [comment]
right now we don't have any DefaultVersion property, but it's actually good idea, but it should be in *Tools class probably

**Comment by jogibear9988** [comment]
I'll look...

At first I'll test if the outer/cross apply works.
then I'll work on the Version support.

But I'll have no Idea about how to setup azzure for the tests

**Comment by MaceWindu** [comment]
Let's move to slack. I can try to setup oracle 12c image

**Comment by jogibear9988** [comment]
#2087

**Comment by jogibear9988** [comment]
will be fixed in 3.0

**Comment by MaceWindu** [comment]
Implemented by #2087
