### ISSUE TITLE
Do you propose to migrate from bltoolkit to linq2db?

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2084]
I have a project by bltoolkit . Do you propose to migrate to linq2db ???

**Comment by MaceWindu** [comment]
It's up to you. If bltoolkit covers your needs you can still use it. But take into account that it is in low-priority support mode, so if you will hit issue with it - it will hardly be fixed soon.

**Comment by MajidSafari** [comment]
thank you ,

i think performance linq2db better than bltoolkit , its ture ?

**Comment by MaceWindu** [comment]
At least in our tests linq2db performs better in most of cases https://github.com/linq2db/PerformanceTest/tree/master/Result

**Comment by MajidSafari** [comment]
tanx @MaceWindu
