### ISSUE TITLE
how use multiple database

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2086]
hi

how use linq2db in multi database

```
using (var db = new DataConnection())
{
     using (var db2 = new DataConnection2())
     {
          db.tbl1 join  db2.tb2 
     }
}
```

is it true ?

**Comment by MaceWindu** [comment]
If your databases are on the same server (or on linked servers), you don't need two connections - you just need to annotate your taable mappings with database name (and server name for linked server connections).

Using multiple connections in single query will not work. Even with distributed transactions.

**Comment by MaceWindu** [comment]
Also you can specify database/server name right in query if annotating model is not suitable:
```cs
using (var db = new DataConnection())
{
          db.tbl1.DatabaseName("db1") join  db2.tb2.DatabaseName("db2")
}
```

**Comment by MajidSafari** [comment]
ok , but i want use T4 for data model  how marge 2 data model

**Comment by MaceWindu** [comment]
Well, don't think we support generation of single context class for multiple databases, so for one of them you will need to use db.GetTable<TableFromSecondDatabase>() syntax directly. You can also enable generation of database name in T4 using corresponding option.

**Comment by sdanyliv** [comment]
Use `GetTable` and you can reuse entities from different contexts.
```cs
var table1 = db.GetTable<TableFromDataModel1>().DatabaseName("DB1");
var table2 = db.GetTable<TableFromDataModel2>().DatabaseName("DB1");
```

**Comment by shameleo** [comment]
Since all generated classes are `partial`, you can simply generate multiple contexts with the same name, and they will be "merged"
**Your "primary" database (tt):**
```
DataContextName = "Db";
...
LoadSqlServerMetadata(your_first_db);
...
GenerateModel();
```
**Another databases**
```
DataContextName = "Db";
GenerateDatabaseName = true;
GenerateConstructors = false;
...
LoadSqlServerMetadata(your_another_db);
...
GenerateModel();
```

If you'll get conflcting table names you can overwrite whatever you want:
```
// class name
GetTable("Person").TypeName  = "MyName";

// data context property
SetTable("Person", "MyName", "MyNames");

// associations
GetSchemaOptions.GetAssociationMemberName = foreignKeySchema => 
{
    return "associationName";
};
```
This worked nice for me
