### ISSUE TITLE
Add extention method for queryproc to simplify parameter specification

### ISSUE THREAD

**Issue by feeleen** [linq2db/linq2db#2089]
Somebody already guessed this in some issue's comments, but it's still not implemented..

I want to query stored proc's using anonymous type as a parameter storage:

Db.QueryProc<MyType>("myStoredProc", new {TypeID = 55, CloseDate = DateTime.Now.Date});

It's a pain working with dataparameter[]

**Comment by sdanyliv** [comment]
@feeleen, looks like everything is ready for this. We just need additional overloads.

For this one
https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L529

Create overload like this
https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L700

There are other QueryProc extensions that also needs overloading

https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L103

https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L664

https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L621

https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L575

Feel free to create PR.

**Comment by feeleen** [comment]
I have this extension in my project 

public static List<T> QueryProcedure<T>(this DataConnection db, string proc, object values)
        {
            List<DataParameter> parameters = new List<DataParameter>();
            foreach (var prop in values.GetType().GetProperties())
            {
                var name = prop.Name;
                var value = prop.GetValue(values);
                parameters.Add(new DataParameter(name, value));
            }
            var result = db.QueryProc<T>(proc, parameters.ToArray());
            return result.ToList();
        }

**Comment by sdanyliv** [comment]
We do not need that, linq2db already processes such objects.

This function already accepts anonymous objects. We just need to create overloads in the same way.
https://github.com/linq2db/linq2db/blob/8cd544b91d3ffd791d6906b82109949aa7ba4b61/Source/LinqToDB/Data/DataConnectionExtensions.cs#L700

**Comment by feeleen** [comment]
@sdanyliv #2090
