### ISSUE TITLE
hi how add Serializable in model ?

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2094]
hi
how config T4 for Serializable in model like
```
	[Serializable]
	[Table(Database="db1", Schema="dbo", Name="City")]
	public partial class City
	{
		[PrimaryKey, NotNull    ] public int    CityCode  { get; set; } 
         }
```

**Comment by MaceWindu** [comment]
Check this https://github.com/linq2db/linq2db/issues/1864#issuecomment-521947316
you need to enumerate Tables dictionary and add serializable attribute to each table

**Comment by MajidSafari** [comment]
like this ? 	
	var tableAttrs = new List<string>();

		 tableAttrs.Add("[Serializable]");

			 foreach (var t in Tables.ToList()){

				t.Attributes.Add(new Attribute("Table", tableAttrs.ToArray()) );
			 }

**Comment by MajidSafari** [comment]
@MaceWindu  tanx

```
	foreach (var t in Tables.Values){

	t.Attributes.Add(new Attribute("Serializable()") );
	}
```
