### ISSUE TITLE
Is there a way to fill associations when query stored procedure?

### ISSUE THREAD

**Issue by feeleen** [linq2db/linq2db#2095]
Is there a way to automatically fill associations when I query stored procedure (queryProc ) ?
I need this because don't want to give a select permissions on some tables.. 
Maybe we could have some column names convention like [person.title] and [person.id] for a "person" association?

**Comment by sdanyliv** [comment]
Please read documentation for MemberName in ColumnAttribute
https://github.com/linq2db/linq2db/blob/5e26fa1693208b92b0791dff445ab7b42e79fb1b/Source/LinqToDB/Mapping/ColumnAttribute.cs#L102

If it does not work with QueryProc, use db.FromSql
