### ISSUE TITLE
I could not properly execute the stored procedure with the return value

### ISSUE THREAD

**Issue by Yuyg77** [linq2db/linq2db#2106]
I could not properly execute the stored procedure with the return value

SQL:
![2](https://user-images.githubusercontent.com/26400716/75539373-189ec600-5a55-11ea-8f51-87e33fcf98cb.jpg)

Code：
![D444943E-24A4-4c55-8C11-3442590CA0BE](https://user-images.githubusercontent.com/26400716/75539381-1b99b680-5a55-11ea-9681-3bf970acb2fa.png)

Error：
![3](https://user-images.githubusercontent.com/26400716/75539407-23f1f180-5a55-11ea-80a0-0255ae4af58f.png)

**Comment by MaceWindu** [comment]
Your code and exception doesn't match. `ExecuteProc` doesn't use `DataReader`

**Comment by MaceWindu** [comment]
I'm closing it for now, as we have [tests](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/DataProvider/MySqlTests.cs#L1115-L1137) for this functionality and doesn't observe any issues. Also your exception stack trace doesn't match your code, so I would suspect you call wrong API.

If you still think there is an issue here, reopen it with more details.
