### ISSUE TITLE
IQueryable , select in select

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2111]
hi when i use IQueryable

now i want 

`CommentSelectPendding().Where(r => (r.UserKind == 4)).tolist();;`

T Sql has   select to select ,

```
select  *from (
select* from tbl where ....

    orderby  r.CommentId
)
```
where  UserKind = 4

```
   private IQueryable<tblComment> CommentSelectPendding()
        {
            return (from r in new db.GetTable<tblComment>()
                     where r.AcceptStatus.Equals((byte)Enums.CommnetAcceptStatus.Pendding) && r.InsertDate < DateTime.Now.AddSeconds(-35)
                     orderby  r.CommentId
                     select  r);
```

**Comment by sdanyliv** [comment]
@MajidSafari, i really can not handle which problem do you have. It is usual queries.

**Comment by sdanyliv** [comment]
What is it?
from r in **new** db.GetTable<tblComment>()

**Comment by MajidSafari** [comment]
db is dbcontext ...

**Comment by sdanyliv** [comment]
Which query you need, an which linq queries do you use?
I’m pointed you to `new` operator which is not needed here.

**Comment by MajidSafari** [comment]
i want
```

select take (2) * from tbl
where id >2
order by id

```

now  linq2db  genarete

select * from(
select take (2) * from tbl
where id >2
order by id

)
where id=2

**Comment by sdanyliv** [comment]
Please post real linq2db queries, not samples. And remove NEW keyword from place that i have mentioned before.

**Comment by MajidSafari** [comment]
tanx  i changed my code and fix

**Comment by sdanyliv** [comment]
And simple suggestion, do not use current DateTime, but `Sql.CurrentTimestamp.AddSeconds(-35)`
In this case you do not have to worry about client-server time resynchronization.

**Comment by MajidSafari** [comment]
tanx for suggestion , it's best  .... 👍
