### ISSUE TITLE
Add support for provider-specific BulkCopy for MySqlConnector 0.62.0+

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#2113]
MySqlConnector added bulk copy api recently, should by quick task to support it if we will not hit any issues
https://mysqlconnector.net/overview/version-history/

**Comment by MaceWindu** [comment]
actually, we probably should wait for https://github.com/mysql-net/MySqlConnector/issues/773 implemented, as it is not very useful for us without mappings

**Comment by bgrainger** [comment]
I added basic column mapping support in 0.65.0; let me know if it's viable for you, or if you need something more.

**Comment by MaceWindu** [comment]
Thanks! Will try it next week

**Comment by MaceWindu** [comment]
@bgrainger everything works fine, except issue with binary data https://github.com/mysql-net/MySqlConnector/issues/816

Feedback:
- API require table and column names not escaped (other providers except Sybase ASE accept escaped names). Potentially could be a problem with FQN table names like `database.table_with_dot.in_name`
- `BatchSize` property not available, so we implemented batching on our side, because on big batches server returns error resulting in `MySqlException : Failed to read the result set.` (in our test case error occurs on 30k records and works with 25k records, but it could be data size limit, not record number limit)

**Comment by bgrainger** [comment]
> API require table and column names not escaped

Are you suggesting it should optionally permit escaped names, or just pass the names straight through and require them to be escaped if they contain special characters? (The latter would be unambiguous, and more similar to `MySqlBulkLoader`.)

> Potentially could be a problem with FQN table names like database.table_with_dot.in_name

`MySqlBulkCopy` (which is `LOAD DATA`) can only load a single database table, so this is unlikely to come up in practice.

> big batches server returns error resulting in MySqlException : Failed to read the result set.

This sounds like https://github.com/mysql-net/MySqlConnector/issues/780 but I haven't been able to reproduce it. Any steps to repro that you can add to that case would be greatly appreciated!

**Comment by MaceWindu** [comment]
> Are you suggesting it should optionally permit escaped names

I don't think it is really important (at least if anybody will ever hit issue wiht it, he can workaround it easily). I wanted to say that accepting escaped name is more proper when API exposes single property for table name, as table name for most of databases could be composite (including mysql) with each part escaped separately. Still it is not clear from LOAD DATA documentation if tbl_name could contain database name or only table name (testing required).

> Any steps to repro that you can add to that case would be greatly appreciated!

We insert records into this table: https://github.com/linq2db/linq2db/blob/master/Data/Create%20Scripts/MySql.sql#L176 (all columns except ID)
This is test data used:
https://github.com/linq2db/linq2db/pull/2215/files#diff-2b6f64493f759acbb9a91425a33017a5R313

Target server is 5.7.17.0 (pretty old, so could be just server issue)

**Comment by MaceWindu** [comment]
> Are you suggesting it should optionally permit escaped names, or just pass the names straight through and require them to be escaped if they contain special characters? 

I mean that it should be second option to comply with other implementations of BulkCopy API (except ASE as I mentioned)

**Comment by bgrainger** [comment]
> I wanted to say that accepting escaped name is more proper when API exposes single property for table name, as table name for most of databases could be composite (including mysql) with each part escaped separately. 

Ah, yes, I see your point. This was an oversight in MySqlConnector's implementation (and one I should probably revert).
