### ISSUE TITLE
linq Sybase.Data.AseClient.AseException: 'The command has timed out.

### ISSUE THREAD

**Issue by fcabralj** [linq2db/linq2db#2115]
Ding the following I'm the error in the title, could you help me identifying why? The table has 200 million rows.

```
using (LinqDB dbLinq = new LinqDB(dbSource))
{
                dbLinq.CommandTimeout = UniversalVariables.linqTimeOut; // actually here is 3600

                var lstFilters = dbLinq.Table
                                 .GroupBy(g => g.Date.Year);

                lstFilters.AsParallel().ForAll(group =>
                {

                    foreach (var item in group) // here I get timeout
                    {
                    }
                }
}
```

**Comment by MaceWindu** [comment]
Well, basically here you have created a lot of queries and connections to database:
- one for main query to select years
- one for each parallel thread to select records with this year

So my guess itt timeouts due to high load or due to lack of connections in connection pool.

**Comment by MaceWindu** [comment]
Another reason (I would suspect this is one for this case) is that you hit max limit of open connections possiblleon database side

**Comment by sdanyliv** [comment]
Linq2db DataConnection is not Thread Safe. But you have lazy loading in each group. Correct your code to the following.
```cs
    var lstFilters = dbLinq.Table
          .AsEnumerable()
          .GroupBy(g => g.Date.Year);
```
