### ISSUE TITLE
How do I view MiniProfile results

### ISSUE THREAD

**Issue by Yuyg77** [linq2db/linq2db#2117]
![微信截图_20200302112442](https://user-images.githubusercontent.com/26400716/75642995-73fcce00-5c78-11ea-92e0-bdc2625dcd8b.png)
I have configured the MIniProfile, but how do I view the relevant monitoring data

**Comment by to11mtm** [comment]
I would suggest looking at the [MiniProfiler docs](https://miniprofiler.com/dotnet/) to do so. They have Instructions for both ASP.NET and Console scenarios (Both Framework and Core)

**Comment by MaceWindu** [comment]
This is linq2db repository, for MiniProfiler you should check link, posted above
