### ISSUE TITLE
i need return DataTable

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2119]
hi 

how can use DataTable to call store for store procedure
not like #1645 

```
	public static IEnumerable<DataTable> spReportpAGEvISITcOUNT(this db dataConnection)
		{
			return dataConnection.QueryProc<DataTable>("spName");
		}
```

**Comment by sdanyliv** [comment]
It ieasy, if you need IQueryable, you do not have to use QueryProc.
```cs
return dataConnection.FromSql(“spName”);
```

**Comment by MajidSafari** [comment]
i don't need IQueryable

**Comment by MajidSafari** [comment]
just i need return System.Data.DataTable

**Comment by sdanyliv** [comment]
Everything can be found in StackOverflow and analyzing linq2db extension methods:
```cs
var dataTable = new DataTable();
using (var reader = dataConnection.ExecuteReader("spName", CommandType.StoredProcedure))
{
	dataTable.Load(reader.Reader);
}
```

**Comment by MajidSafari** [comment]
Hi @sdanyliv 

sorry for  a lot question 

and tanxxxxxxxxxxxxxxxx

**Comment by gpgpublickey** [comment]
Hi guys @sdanyliv  is this suitable for TVP output returned values? Would you mind to show an example about how to retrieve data from an executed stored procedure returning an TVP output parameter ?
