### ISSUE TITLE
database connection is not disposed in case of delayed execution

### ISSUE THREAD

**Issue by DukeBG** [linq2db/linq2db#212]
Because the inner DataReader is using delayed execution (yield return), in some cases the session would not be created yet when the Dispose() of the DataConnection fires and thus not released afterwards.

Sample program:
http://pastebin.com/nJAi8DQQ

**Comment by igor-tkachev** [comment]
Your sample is not correct. You have to finish working with DataReader before leaving the DataConnection scope. If you want to create an iterator, your code should look like the following:

```c#
public IEnumerable<A> AwesomeSelect()
{
    using (var db = new CustomDataConnection())
    {
        foreach (var item in db.Query<A>("select 'test' as b, 'test2' as c from dual"))
            yield return res;
    }
}
```
