### ISSUE TITLE
How to update with key?

### ISSUE THREAD

**Issue by ahdung** [linq2db/linq2db#2125]
```c#
var users = db.Users.Where(x => x.Name.StartsWith("a"));
var upd = users.Set(u => u.Name, u => u.Name + "_2"); //sql: ...where name like 'a%'
```
I hope sql is `where id in (xxx) //id is PK`, how?

**Comment by sdanyliv** [comment]
You forgot to call `Update` method.
```cs
var users = db.Users.Where(x => x.Name.StartsWith("a"));
var upd = users.Set(u => u.Name, u => u.Name + "_2");
upd.Update():
```

**Comment by ahdung** [comment]
@sdanyliv I didn't forgot, it's just didn't write it out. let me re-describe:
```c#
var users = db.Users.Where(x => x.Name.StartsWith("a"));
var upd = users.Set(u => u.Name, u => u.Name + "_2"); //sql: ...where name like 'a%'

; //breaking point: when run to this, i saw upd's sql is '... like 'a%''

upd.Update();
```

**Comment by sdanyliv** [comment]
Sorry, it is not clear for us, what exactly you need. Try to describe your question again, linq2db has a lot of CRUD operations and we can not figure out which one you need.

**Comment by ahdung** [comment]
`User` has PK, so I hope update `User` by its PK, not the condition of `Where`.

**Comment by sdanyliv** [comment]
It is what are you looking?
```cs
db.Update(user)
```

**Comment by ahdung** [comment]
I'll try it later, thank you.

**Comment by sdanyliv** [comment]
Let me clarify linq2db usage for you. It is not change tracker based ORM, so updating whole entities can be not effective from db indexes side. It can be compared with EF Core in detail.
Usually for updating entity in EF Core you have to select WHOLE entity from database and then update several properties:
```cs
var entity = ctx.Where(e => e.Id == dto.Id).FirstOrDefault();
if (entity == null)
   throw new Exception("Entity not found");
entity.Property1 = dto.Property1;
entity.Property2 = dto.Property2;
ctx.SaveChanges();
```
This approach is nice and can be used in many complex DDD scenarios. But it also has disadvantages:

1. Before updating record you have to select this record from database: +1 roundtrip to database
2. You select whole entity from database: +N not needed fields

It is good for small tables, but not for complex with millions records.

linq2db propose to control from your side which fields needs to be updated:
```cs
var entityUpdate = db.Where(e => e.Id == dto.Id).AsUpdatatable();
if (dto.HasChanged("Property1"))
  entityUpdate = entityUpdate.Set(entity => entity.Property1, dto.Property1);
if (dto.HasChanged("Property2"))
  entityUpdate = entityUpdate.Set(entity => entity.Property2, dto.Property2);
if (entityUpdate.Update() <= 0);
   throw new Exception("Entity not found");
```
What we have here: only one roundtrip to database and NONE records selected for update.

If you have already poisoned by Repository pattern, it can be difficult for you to gain needed performance from linq2db. It manipulates by queries not an entities - it is main difference.

You can define methods which return needed query filtered by permission, whatever and reuse them in other CRUD operations:
```cs
public static IQueryable<User> GetAvailaibleUser(this IDataContext dc, int? userId, int currentUser)
{
   var query = dc.GetTable<User>()
     .Where(u => u.AssignedTo == currentUserId);
   if (userId.HasValue) // if we need all available users - just do not pass this value
     query = query.Where(u => u.UserId == userId)
   return query;
}
```
And reuse this method in our update:
```cs
var entityUpdate = db.GetAvailaibleUser(dto.Id, currentUserId).AsUpdatatable();
if (dto.HasChanged("Property1"))
  entityUpdate = entityUpdate.Set(entity => entity.Property1, dto.Property1);
if (dto.HasChanged("Property2"))
  entityUpdate = entityUpdate.Set(entity => entity.Property2, dto.Property2);
if (entityUpdate.Update() <= 0);
   throw new Exception("Entity not found");
```
Or delete these entities:
```cs
if (db.GetAvailaibleUser(dto.Id, currentUserId).Delete() <= 0) 
  throw new Exception("Entity(es) not found");
```

**Comment by ahdung** [comment]
Thanks for the explanation, but I still don't understand, `User` has `PrimaryKeyAttribute`, linq2db know that, why not use it for `Set`? well, I'm not care WHY, please tell me, if I get the users through other conditions, how to update they by `ID`? I haven't tried `db.Update(users)`, because it seems will update all columns, that's not what i want.
```c# 
[Table]
public class User
{
    [PrimaryKey]
    public int ID { get; set; }

    [Column]
    public string Name { get; set; }
}

**Comment by sdanyliv** [comment]
Answer is simple, because we do not have object or data about primary key.
Show me API that you expect and i can help you to implement it.

**Comment by ahdung** [comment]
```c#
users.Set(xxx)
    .ByKey() // if no parameter, use entity's PK, if no PK, throw ex
 // .ByKey(u => u.Name) // use keySelector
    .Update();
```
the sql will be `where id in (xxx)` or `where name in (xxx)`.

**Comment by sdanyliv** [comment]
I assume you are trying to mimic something like this
```cs
db.GetTable<User>()
   .Where(u => users.Contains(u.UserId)
   .Set(xxx)
   .Update()
```

**Comment by ahdung** [comment]
@sdanyliv But I want get users use other conditions. e.g.
