### ISSUE TITLE
insert List

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#2126]
hi , i want insert list items like this sample , but  i can't

can you help me ?

sorry 

```
   var range = Enumerable.Range(course.StartPos.To<int>(), course.QuestionCount.To<int>());
                            var detailEntityList = range
                                .Select(id => new DataModel.tblQuizMiniDetail
                                {
                                    QuizId = entity.Rid,
                                    Answer = null,
                                    Counter = Userid.To<int>(),
                                    DateInsert = DateTime.Now,
                                    QuestionNo = id
                                }).ToList();

                            db.Insert(detailEntityList);
```

**Comment by MaceWindu** [comment]
For batch inserts you should use `BulkCopy` method

**Comment by MajidSafari** [comment]
oh , i think, better BulkCopy and Insert get unify  ,

**Comment by MajidSafari** [comment]
hi @MaceWindu BulkCopy  for update ?

sorry ,i was  think  linq2db like  bltoolkit for list update and list insert  .

**Comment by MaceWindu** [comment]
`Insert` method is used only with SQL INSERT statement to INSERT single record from client or multiple records from other query using INSERT FROM.
`BulkCopy` is for importing of multiple records from client and could use various import methods based on provided options and support from database and provider.

For bulk updates you need to use UPDATE FROM temporary table/query statement or `Merge` if your database supports them.
