### ISSUE TITLE
DefaultConfiguration not initial to the first connectionString in mono(exception Configuration string is not provided )

### ISSUE THREAD

**Issue by luopeizhen** [linq2db/linq2db#213]
when using mono, I found that function InitConnectionStrings  will not found out the  first connectionString because ElementInformation.Source always to be null.
than in function DataConnection will throw exception Configuration string is not provided if no configurationString.

**Comment by MirandaBrazil** [comment]
You can use DataConnection(string configurationString); to pass the configuration instead of using .config file

**Comment by igor-tkachev** [comment]
How can I reproduce it?

**Comment by RodionNikolaev** [comment]
У меня такая ошибка была под Mono для PostgreSQL.
1.Создал под Windows консольный проект.
2.Сгенерировал, как описано классы из БД.
3 Добавил connectionString в app.config.
4. Вызвал  var db = new TestDB(), где TestDB - DataConnection;
5 Под Windows строка подтянулась из app.config
6. Под Mono, указанная ошибка.
7. Пересобрал проект с  var db = new TestDB("configuration"), где configuration - name из connectionStrings в app.config
8. Работает в обоих случаях

**Comment by ili** [comment]
Not really clear how can we fix it =(
If any suggestions or test to reproduce the situation
