### ISSUE TITLE
Problem with T4 of setting "IncludeDefaultSchema = false" for PostgreSQL provider.

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2133]
Problem with T4 of setting "**IncludeDefaultSchema = false;**" for PostgreSQL provider.

I need to generate POCO classes without "Schema" attribute (generated SQL-s should not contain schema prefixes).
As for Oracle it is works. After setting "IncludeDefaultSchema = false;", I got this:

> 	**[Table("TEST_TABLE")]**
> 	public partial class TestTable
> 	{
> 		/// <summary>
> 		/// Option Id
> 		/// </summary>
> 		[Column("OPTN_ID"),      PrimaryKey,  NotNull] public long      OptnId     { get; set; } // NUMBER (10,0)

...

So for Oracle, SQL generates correctly, without schema prefixes.

For Postgre it does not work:

> 	[Table(**Schema="test_schema"**, Name="TEST_TABLE")]
> 	public partial class TestTable
> 	{
> 		[Column("OPTN_ID"),      PrimaryKey,  NotNull] public long      OptnId     { get; set; } // bigint
> 

Schema attribute still presents and SQL-s generates with Schema prefix.
I want to avoid Schema prefix in SQLs, my Postgre USER/ROLE created such way (with SET search_path TO):
ALTER ROLE test_user IN DATABASE postgres **SET search_path TO test_schema**;

Please, fix the generation POCO classes for PostgreSQL provider.
Or specify what I do wrong.

**Comment by MaceWindu** [comment]
Right now we don't check actual default schema for current connection user and use "public" as default. Probably we should change this logic or/and provide more customization what is "default" schema

**Comment by AndrePScope** [comment]
> Right now we don't check actual default schema for current connection user and use "public" as default. Probably we should change this logic or/and provide more customization what is "default" schema

At first, many thanks for your very quick answer!

But I am not sure that we talking about additional customization. 
I need to avoid Schema attribute in the class of entity (so in SQLs).
This works for the Oracle T4 template. 
The Oracle T4 template generates the class without Schema attribute (when I set **"IncludeDefaultSchema = false"**). As it says in your doc.

But the PostgreSQL template does not work the same.
I would say, this looks like a bug...

**Comment by MaceWindu** [comment]
Well, problem is that T4 templates are quite old and we often cannot just say that something is a bug and replace some "incorrect" logic with correct. Because it will be breaking change for users that already have generated mappings with old behavior. We need to introduce some fallback support for such situations.

As I said for postgresql current implementation just treat "public" as defauld schema, so if your default schema is not public, current templates will treat it as custom schema and generate SchemaName.
For Oracle we do it in more proper way.

**Comment by MaceWindu** [comment]
I think proper fix here will be:
- fix default schema detection for postgresql
- introduce additional option to specify default schema name explicitly

**Comment by MaceWindu** [comment]
BTW, as workaround you can add additional code to your T4 file between model load and generation to inspect model and remove schema from attributes. Check this as starting point https://linq2db.github.io/articles/T4.html#example-of-generation-process-customization

**Comment by AndrePScope** [comment]
Ok, thank you for an explanation. now I see the problem...
I also think, that to treat "public" schema always as "default" maybe not quite good. )

And thank you for the advice of workaround. I will try to resolve this issue via this way.

**Comment by AndrePScope** [comment]
I have to say again many thanks for your suggestion about the workaround.

As for now, this works well for me:

	PrefixTableMappingWithSchema         = false;
	GetSchemaOptions.IncludedSchemas     = new string[] {"test_schema"} ;
	LoadPostgreSQLMetadata("localhost", "5432", "postgres", "test_schema", "test_password");

	// fix: avoid default schema in attribute
	foreach (var t in Tables.Values)
		t.Schema = null;

	GenerateModel();

**Comment by MaceWindu** [comment]
I've looked into it and now I see why it's probably wasn't implemented in first place. `search_path` could contain multiple schemas. Also proper fix will require changes to all data providers.

For now I will move this task to v3 release. It's quite big and we already have workaround for now.

**Comment by MaceWindu** [comment]
In next release we add `GetSchemaOptions.DefaultSchema` setting that will allow you to set name of schema that should be treated as default [see](https://github.com/linq2db/linq2db/pull/2308)

I will close this issue for now. If it doesn't cover your cases, we can reopen it
