### ISSUE TITLE
Access BulkCopy RowByRowCopy without transcation

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#2134]
[Here](https://github.com/linq2db/linq2db/tree/5e26fa1693208b92b0791dff445ab7b42e79fb1b#bulk-copy) you mention about not using transaction whenever we can. But from [here](https://linq2db.github.io/articles/sql/Bulk-Copy.html#insert-methods-and-support-by-providers) and [here](https://github.com/linq2db/linq2db/blob/5e26fa1693208b92b0791dff445ab7b42e79fb1b/Source/LinqToDB/DataProvider/BasicBulkCopy.cs#L48) we can conclude that simple insert on large set of data on MsAccess database (or any others using only RowByRow method) can cause partial insert if transaction is not use.

Could you clarify it?

**Comment by MaceWindu** [comment]
Well, agree that it is quite controversial statement. In general I don't see issue with using transactions here except cases when provider-specific BulkCopy used for providers that doesn't support explicit transactions for BulkCopy. This is not the case for Access, as it use conventional insterts.
Probably we need to review this document
