### ISSUE TITLE
Auto convert a mapped value in fluent builder

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2138]
Hi,

I am saving money values  as integer in my db (two decimal values: double * 100). Now I would like to auto convert while mapping this with the Fluent builder.

Is there something that I can use in generic way for this? Maybe by defining a SQLFunction ?

```
fluent.Entity<Receipt>().HasTableName("RECEIPT").IsColumnRequired()
.Property(x => x.Id).HasColumnName("ID").IsPrimaryKey().HasSkipOnInsert()
            .Property(x => x.Amount).HasColumnName("AMOUNT");
```

Amount is a double in my class but an Integer in my db.

Is HasCreateFormat() the right method or is there something else to gnerate the double frrom (intValue/100.0)?

**Comment by Franki1986** [comment]
https://github.com/linq2db/linq2db/issues/1837

**Comment by Franki1986** [comment]
@sdanyliv : Is there some kind of workaround without the need of creating an expressionMethod for each property

**Comment by sdanyliv** [comment]
I think no way.

**Comment by Franki1986** [comment]
Ok, thanks for response

**Comment by Franki1986** [comment]
What is the Expression in the ExpressionMethodAttribute for? Can I override the desired Expression here. In the docs it says it is a substituition expression.
So is it possible to create an ExpressionMethodAttribute, that acceses the Member it self?

**Comment by Franki1986** [comment]
@sdanyliv  sorry for asking another time, but how to convert the columns in an ExpressionMethod without previous mapping declaration?
I mean I cannot convert a column without having it mapped earlyer

**Comment by sdanyliv** [comment]
Sorry, I have no time now to analyze code.

**Comment by Franki1986** [comment]
ok

**Comment by MaceWindu** [comment]
per-column converters for both attribute-based and fluent mappings will be available in next release https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273
