### ISSUE TITLE
postgres - ERROR: invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2139]
seems like this sql is generated:

DECLARE @FormatId Uuid -- Guid
SET     @FormatId = 'b441bdb8-d973-4835-985a-21c7a90d4371'
DECLARE @Data0 Text(166) -- String
SET     @Data0 = 'AK75MFC1SR010100' || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0) || chr(0)
DECLARE @ConnectionName Text(8) -- String
SET     @ConnectionName = 'MDYNAMIC'
DECLARE @TelegramDirection Integer -- Int32
SET     @TelegramDirection = 0
DECLARE @CreatedTimeStamp Timestamp -- DateTime
SET     @CreatedTimeStamp = '2020-03-21 23:00:36.826'::timestamp

INSERT INTO VISU_PLCProtocol
(
	FormatId,
	Data,
	ConnectionName,
	TelegramDirection,
	DateTime
)
VALUES
(
	:FormatId,
	:Data0,
	:ConnectionName,
	:TelegramDirection,
	:CreatedTimeStamp
)

**Comment by jogibear9988** [comment]
Do I need to fix this on my side? Or is there a setting?

The chr(0) is in the string, why is that not legal?

**Comment by jogibear9988** [comment]
Kay, found this:

https://stackoverflow.com/questions/1347646/postgres-error-on-insert-error-invalid-byte-sequence-for-encoding-utf8-0x0/45810272

How could we solve this? Maybe we need a setting for columns how chr(0) values should be threaded in postgres?

**Comment by jogibear9988** [comment]
https://stackoverflow.com/questions/35879323/postgres-insert-strings-with-null-between-the-characters

maybe we should encode it as 0xC0 0x80

**Comment by jogibear9988** [comment]
@MaceWindu @sdanyliv suggestions?

**Comment by jogibear9988** [comment]
I can work on this maybe...

**Comment by sdanyliv** [comment]
I can not understand problem. What you shown is debug output of generated SQL and parameters - it is not real SQL. Binary data is sent via parameters.
Better to post test code.

**Comment by jogibear9988** [comment]
The Problem is, I have a varchar column in postgres, but my string contains chr(0) characters. Wich is not supported by postgres.

**Comment by MaceWindu** [comment]
We cannot go with 0xC0 0x80, as MUTF-8 is just a java-specific abomination, and doesn't look related to postgresql.
I'm not sure what to do to it. From one side we can provide some data normalization, but to me it looks like something, that should be done by user - he shouldn't try to insert unsupported data and expect it to work.

**Comment by jogibear9988** [comment]
problem is, we use same code in mssql, sqlite and postgres
on with 2 datbases it works, with postgres not.
Maybe we could introduce a setting on PostgresProvide (Fix invalid string characters or smth. similar...)

**Comment by MaceWindu** [comment]
Not a big fan of it. We can introduce options to handle null-chars. Something like
```cs
string NullReplacement;
NullHandling NullHandlingMode;

enum NullHandling
{
Ignore = 0, // current mode with do nothing
Remove, // inspect values and parameters and remove \0
Replace // replace null in values/ parameters and restore in results
}
```
But it  adds a lot of complexity (especially Replace mode) for something that is actually user's responsibility

**Comment by jogibear9988** [comment]
maybe only for some columns? and only for some providers? would this be possible?
