### ISSUE TITLE
LoadWith makes queries for each entity

### ISSUE THREAD

**Issue by mrb1n** [linq2db/linq2db#214]
``` c#
class Directory
{
    public long Id { get; set;}
    public string Path { get; set;}
    public IEnumerable<File> Files { get; set;}
}

class File
{
    public long Id { get; set;}
    public long DirectoryId { get; set; }
    public string Name { get; set; }
    public Directory Directory { get; set; }
}

db.Directory.LoadWith(d => d.files)
```

Fails with exception "Multiple queries are not allowed. Set the 'LinqToDB.Common.Configuration.Linq.AllowMultipleQuery' flag to 'true' to allow multiple queries."

If set AllowMultipleQuery to true, it generates query for each directory entry,

May be it could be done with one query?

**Comment by igor-tkachev** [comment]
I am working on it.

**Comment by dsys** [comment]
Thank you for your reply!
I like linq2db but sometimes that feature is really needed. 
Could you estimate when it will be ready?

**Comment by igor-tkachev** [comment]
I am really working n it :)

**Comment by KrolikROJER** [comment]
Igor, will it be possible to load additional dependencies? For example,
var dirs = db.Directory.LoadWith(d => d.Files.Select(f => f.Properties)).ToArray();
class File
{
    public long Id { get; set;}
    public long DirectoryId { get; set; }
    public string Name { get; set; }
    public Directory Directory { get; set; }
    public IEnumerable<PropertyAlign> Properties { get; set;}
}
and will be:
foreach (var dir in dirs)
     foreach(var file in dir.Files)
            foreach(var prop in file.Properties)
                  {
                            ....
                  }

**Comment by igor-tkachev** [comment]
```c#
db.Directory.LoadWith(d => d.Files[0].Properties);
```

**Comment by KrolikROJER** [comment]
Super!!!! 
This feature is working or still in development?

**Comment by igor-tkachev** [comment]
It works.

**Comment by tvilkov** [comment]
Hello, Igor. Should it work for PostgreSql too?

**Comment by igor-tkachev** [comment]
It should.

**Comment by ronnyek** [comment]
Is there a particular version required for this functionality? I just tried with a release that was not that old and it told me I had to allow multiple queries as well. Also looked like for a one to many, it was executing child query per id

**Comment by ronnyek** [comment]
sorry I misunderstood, In testing I found that if I had a User->Friends, I'd get one query for users matching the criteria, and one for all the friends for all the users. That's what I was looking for! thanks!

**Comment by iheb719** [comment]
Is the feature still in development or is abandoned ? Making a query for each entity is really a performance issue for me.

**Comment by ili** [comment]
This would be the point for v2

**Comment by jogibear9988** [comment]
do you?, or igor work on v2 atm?

**Comment by ili** [comment]
Igor.

**Comment by ronnyek** [comment]
Man having this actually be optimized is a huge requirement... seems like v2 is... not progressing well at this point (not trying to sound ungreatful, linq2db is close to what I'd see if I picture my ideal ORM) I'm unclear as to whether this actually does what it is supposed to do...  It does seem to make a ton of queries for each child

**Comment by jogibear9988** [comment]
should we reopen this issue to track it's support in 2.0?

**Comment by ronnyek** [comment]
I know this issue is marked as closed... but did it actually get resolved? Eg, to get at most 2 queries for a relation between two entities?

**Comment by jogibear9988** [comment]
i reopen it, but I do not think someone has the time to work on it. It is not an easy task.

**Comment by sdanyliv** [comment]
I think we have to create separate issue with feature request for Eager loading.

**Comment by CrazyAlex25** [comment]
Can i use LoadWith with tree structure?
Example: 
```csharp
[Table]
public class TestClass
{
	[Column, PrimaryKey, Identity]  public int Id { get; set; }
	[Column, Nullable]  public int? ParentId { get; set; }


	[Association(ThisKey = "ParentId", OtherKey = "Id", CanBeNull = true, Relationship = Relationship.ManyToOne)]
	public TestClass Parent { get; set; }

	[Association(ThisKey = "Id", OtherKey = "ParentId", CanBeNull = true, Relationship = Relationship.OneToMany, IsBackReference = true)]
	public IEnumerable<TestClass> Childs { get; set; }
}
```

**Comment by MaceWindu** [comment]
Fixed by new eager load implementation #1756

**Comment by JamesBarea** [comment]
I don't believe this is fixed in the linked issue as I am experiencing it still on the latest version (4.4.0).
Can this be re-opened to keep the issue tracking to this thread please?

**Comment by MaceWindu** [comment]
PLease open new issue with query and model
