### ISSUE TITLE
How do you create a CTE with an IList<> passed as a parameter? 

### ISSUE THREAD

**Issue by crackerjacked** [linq2db/linq2db#2145]
My function currently takes an IList<> as a parameter. I need to be able to convert it to a CTE that is joined on in a SQL statement. 

When I try to convert it to an IQueryable object and convert it to a CTE like so:

```
var myQueryable = myList.asQueryable<T>();
var myCTE = myQueryable.AsCte();
```

But myCTE object doesn't reflect having any values from the list.

```
var myQueryableType = myQueryable .GetType(); 
```
This shows that the type is System.Linq.EnumerableQuery as well.

The myCTE object also has the message: "There is no method 'AsCte' on type 'LinqToDB.LinqExtensions' that matches the specified arguments".

**Comment by sdanyliv** [comment]
Sorry, it is not possible yet. I will handle this feature.
Which SQL do you expect? It will help me to design API.

**Comment by crackerjacked** [comment]
Currently expecting Postgres Sql but it should be flexible in case it changes in the future! Thank you!

**Comment by sdanyliv** [comment]
Show me expected SQL. It will work on all databases.

**Comment by crackerjacked** [comment]
Oh that's what you meant! Okay this is what I'm trying to do:

```
WITH "CTE_1"
(
	"column1", 
	"column2", 
	"column3", 
	"column4"
)
AS
(
	SELECT
		t1.column1,
		t1.column2,
		t1.column3,
		t1.column4
	FROM
		(
			select 1468 as column1, 115 as column2, 56 as column3
			union select 1468, 116, 56 union select 1467, 115, 56 union select 1467, 116, 56 
		) t1
)
SELECT
	t2."column1",
	t2."column2",
	t2."column3",
	t2."column4"
FROM
	"CTE_1" t2
```
The union select is from iterating through the IList<> object.

**Comment by sdanyliv** [comment]
Yes, I thought about this also. But `UNION ALL`, not `UNION`. I'll do my best to implementing this.

Anyway you can mimic this query now, just sample:
```cs

var itemsQuery = db.SelectQuery(() => new Some{ Column1 = 1, Column2 = 10...})
   .Concat(db.SelectQuery(() => new Some{ Column1 = 2, Column2 = 20...}))
   .Concat(db.SelectQuery(() => new Some{ Column1 = 3, Column2 = 30...}))

var result = itemsQuery.AsCte().ToArray();

```

**Comment by crackerjacked** [comment]
Hmmm , I tried to replicate this but it's only creating an array of one object.
I tried to loop through the list to concat like so:

```

// param: IList<Object> myList

IQueryable<Object> itemsQuery = null;
if (myList != null && myList.Count() > 0)
{
	itemsQuery = connection.SelectQuery(() => new Object
	{
		column1 = myList[0].column1,
		column2 = myList[0].column2,
		column3 = myList[0].column3,
		column4 = myList[0].column4
	});

	for (int i = 1; i < myList.Count; i++)
	{
		try
		{
			itemsQuery.Concat(connection.SelectQuery(() => new Object
			{
				column1 = myList[i].column1,
				column2 = myList[i].column2,
				column3 = myList[i].column3,
				column4 = myList[i].column4
			}));
		} catch (Exception e)
		{
			var error = e;

		}
	}
}

if (itemsQuery != null)
{
	var result = itemsQuery.AsCte();
	var resultarray = result.ToArray(); // only has one object from the first SelectQuery()
}
```

**Comment by sdanyliv** [comment]
You forgot to assign:
```cs
itemsQuery = temsQuery.Concat(...)
```

**Comment by crackerjacked** [comment]
Thanks. It's able to iterate and build the sql statement but before it calls .AsCte() it has a System.ArgumentOutOfRangeException. I'm not sure what causes this since it exits the for loop after iterating over the last item in the list

**Comment by sdanyliv** [comment]
It is because of invalid closure. This one works.
```cs
IQueryable<SampleClass> itemsQuery = null;

for (int i = 0; i < items.Length; i++)
{
	var item = items[i];
	var current = db.SelectQuery(() => new SampleClass
	{
		Id = item.Id,
		Value = item.Value,
	});

	itemsQuery = itemsQuery == null ? current : itemsQuery.Concat(current);
}
var result = itemsQuery.AsCte().ToArray();
```

**Comment by crackerjacked** [comment]
Thanks, that one did work :)

**Comment by sdanyliv** [comment]
Actually not, problem with parameters. I'm working on fix and maybe tomorrow it will be released.

**Comment by viceroypenguin** [comment]
@sdanyliv - if you are looking for API suggestion around this, I would ask for the following (at least on the Microsoft SQL Server provider):
```
IList<SomeObject> data;
IQueryable<SomeObject> query = data.AsTable();
```

would use the [table value constructor](https://docs.microsoft.com/en-us/sql/t-sql/queries/table-value-constructor-transact-sql?view=sql-server-ver15) syntax to generate an inline table:
```
(values 
   (123, 45, 678),
   (901, 23, 456)) t1(Column1, Column2, Column3)
```

`t1` can now be joined to any other table, which makes it useful for loading quick data for insert, update, or my favorite, merge.

**Comment by sdanyliv** [comment]
Actually we already have such method, but it works only with scalar types.
```cs
query = data.AsQueryable(db);
```
What is needed is a time for implementation.

**Comment by viceroypenguin** [comment]
If you point me in the right direction, I'd be happy to implement using the `(values (colA, colB))t1(colA, colB)` syntax. That appears to be part of ISO standard and implemented by Oracle and others now.

**Comment by sdanyliv** [comment]
There are only four IQueryable sources  supported in library
- GetTable
- FromSql
- SelectQuery
- AsCte

Any of them are complicated. I appreciate your interest but it can be really challenging task from the start. For example implementing CTE took about month of my free time to understand how to do that correctly.
It is not an just create SQL AST which generates VALUES, but it is also good knowledge in our LINQ parser.

I'll give you small example which problems needs to be solved:
We have array
```cs
var data = new [] {
  new Some 
   { 
    Column1 = ..,
    Column2 = ..,
    ...
    ColumnN = ..,
   },
   ...
},
```
Let's write query
```cs
var query = 
   from d in data.AsQueryable(db)
   join t1 in db.OtherTable1 on d.Colum1 equals t1.Id
   join t2 in db.OtherTable2 on d.Colum2 equals t2.Id
   select new { t1, t2 }
```
In this query, we have used only two fields from `data` array. So only two fields should be used in SQL generation.
Another trick with reusing values from other table:
```cs
var query = 
   from m in db.Master
   from d in new Some[] {
     new Some{Column1 = m.Id, Column2 = 1},
     new Some{Column1 = m.Id2, Column2 = m.Value}
     new Some{Column1 = 1, Column2 = 2}
   }
   join t1 in db.OtherTable1 on d.Colum1 equals t1.Id
   join t2 in db.OtherTable2 on d.Colum2 equals t2.Id
   select new { t1, t2 }
```
Also If database do not support VALUES, we have to mimic it by UNION ALL
A lot of nuances here. Really. That's why i'm trying to prioritize this task implementation.

If you still interested, i can start pointing you in right direction.

**Comment by viceroypenguin** [comment]
Ah, yes. The inline syntax would be trickier to implement. I only recently started using that syntax in direct SQL; it's powerful, but not easy to grok.

I may start by implementing the simpler version (constant-only) first, leaving the second to throw an exception for now, if that's acceptable to you. I can update the exception to be more explicit on why the outer-apply version is not implemented yet.

I can see the foundation in ArrayBuilder.cs and ExpressionBuilder.SqlBuilder.cs, with an `InnerJoinClassArray()` test in ArrayTableTests.cs. Anything else I should be aware of before digging in?

**Comment by sdanyliv** [comment]
`ArrayBuilder` it is what needed to rewrite, 
`SqlMergeSourceTable` - it is sample what we need for SQL AST. It is source table for Merge operations. `MergeSourceQueryContext` - we have to create appropriate context like this. Also sample is `CteTableContext` and possibly you have to inherit from `TableContext`. It is not a good abstraction but not found time to extract this class more clearly.
`ConvertToSql` is one most important in these contexts - if system called this method for some field - this field needs to be counted in final SQL.

**Comment by viceroypenguin** [comment]
Ok, I'll start taking a look! Thanks!

**Comment by sdanyliv** [comment]
Don't give up, if you want to improve this library :)
It is powerful because of such LINQ features.

**Comment by sdanyliv** [comment]
One important thing. `QueryVisitor` and `ConvertVisitor` should take in account about new SQL AST element and should be written correctly, otherwise it may fail in many unexpected situations.

**Comment by viceroypenguin** [comment]
Yeah, I'm going to write a series of new tests for sure. Need to test that the constant array works for insert, update, delete, merge, and regular select. I'll put in `[ActiveIssue]` tests for all of the same for the outer apply version, knowing those won't work in v1.

Thanks for the add'l places to look for changes though.
