### ISSUE TITLE
Possible memory leaks when using structured parameters or FromSql()

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#2151]
Hi everyone!

I had a need to implement lot of queries with filtering by thousands of ids provided from outside. 
So I had to use structured parameters.
But then I've noticed the growth of memory usage (and a significant growth).
Maybe I did something wrong, maybe there is some caching of parameter values..
Adding 

```
DataConnection.ClearObjectReaderCache();
Query.ClearCaches();
```

helps, but not a lot - the memory usage still grows, but a bit slower.

Key moments:

structured parameters mapping

```
var builder = new MappingSchema().GetFluentMappingBuilder();

builder.MappingSchema.SetConverter<List<IntTableType>, DataParameter>(x => new DataParameter
{
	DataType = DataType.Structured,
	DbType = $"dbo.{nameof(IntTableType)}",
	Value = Helpers.GetDataTable(x)
});
```

structured parameters usage in query:

```
using (var db = GetConnection())
{
	var pars = GetRandomParams(1000);
	var parsQuery = db.FromSql<IntTableType>($"{pars}");

	var query = from u in db.GetTable<User>()
				join p in parsQuery on u.Id equals p.Value
				select u;

	await query.ToListAsync().ConfigureAwait(false);
}
```

I hope you can help me somehow..

I've implemented the situation in a small console project:
https://www.dropbox.com/sh/s773pflz71ga3zc/AACM66BzJo2TdVCGQL4fysF6a?dl=0

### Environment details
linq2db version: 2.9.7
Database Server: Ms SQL
Operating system: Windows
.NET Framework: 4.7.2
.NET Core: 2.2

**Comment by sdanyliv** [comment]
@arwyl, finally I have found time to look at. You have missed `MappingSchema.ClearCache();`
linq2db uses `MemoryCache` for storing needed data. Data has retain period which is controlled by global setting `Configuration.Linq.CacheSlidingExpiration`. By default if items are not used for one hour, it will be removed from cache.
Set it, for example, to `Configuration.Linq.CacheSlidingExpiration = TimeSpan.FromSeconds(10)`

If you feel that we need to extend this configuration, PR is welcome.

**Comment by sdanyliv** [comment]
Anyway, consider to do not create new MappingSchema for each context creation. It makes cache growing quickly.

**Comment by arwyl** [comment]
I'll certainly try to make only one MappingSchema object and add MappingSchema.ClearCache();
but is that correct, that parameter values are added to cache? It doesn't make sense to me..

**Comment by sdanyliv** [comment]
Not just parameters but whole queries are cached with parameters.
We have plans to review parameters logic, possible it will reduce memory usage.

**Comment by arwyl** [comment]
can you tell me if the same queries with different parameters are cached separately or not?

**Comment by sdanyliv** [comment]
> UPD 2: oh.. maybe you mean, that different mapping schemas use their own cache and every one of them caches the same queries.. I'll definitely investigate that

Yes new mapping schema will start creating new EntityDescriptors in cache. It is bad for performance and memory usage.

**Comment by sdanyliv** [comment]
> can you tell me if the same queries with different parameters are cached separately or not?

We cache query (SQL). When we decided that we hit cache - we reuse SQL and just replace parameters. It is know bottleneck in current implementation, we have to do **lock** here on particular SQL.

But again, if you create new MappingSchema for each connection - you will miss that cache always.

**Comment by arwyl** [comment]
thanks a lot for your answers! I'll try to experiment with that
that'll be a hell of a weekend =)

**Comment by sdanyliv** [comment]
Just tested. If in your project initialize mapping schema only once - no memory leak.

**Comment by arwyl** [comment]
thanks for that!
but I also have a case where I need to create mapping for dynamically typed entities. So I have to create a mapping schema on the run based on users permissions and stuff. To clear all the cache after that is really "overheaded". Maybe there'll be a PR for removing only the EntityDescriptor for current mapping schema from me

**Comment by sdanyliv** [comment]
Or just create your MappingSchema cache, if you expect cache hit for sure.

**Comment by arwyl** [comment]
I really need a Mapping schema for one to three queries. And after that there is no need for that for several hours..
There's a weird case where all users operates with one entity, but that entity is dynamic, its' navigation properties should join on different tables and such. That's really messy =)

**Comment by arwyl** [comment]
Checked that - everything is fine with only one MappingSchema
Thanks a lot!
