### ISSUE TITLE
Documentaion question for custom types mapping #1954

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2154]
Hi,

I saw the implementation of #1954 and I am not sure how it works..
I have to create  a constructor with e.g. the class itself as parameter.
Then I can call this copy constructor in my select query .
The content of the copy constructor itself is not called, there is only a Mapping to properties over LinqToDb, somehow Automapper does?
If I already defined a copy constructor, this is not used?

**Comment by sdanyliv** [comment]
Copy constructor will not work. Properties are mapped only if they are present as parameters in constructor. Name of parameter should be equal to property name (no case).

**Comment by Franki1986** [comment]
Thanks for the response. The functionality is quite well, but it is hard to find in the documentaion. Maybe the release notes could be updated for users that aren not so familiar with linqtodb.
