### ISSUE TITLE
Issue with Postgres in 3.0 Preview 2 - Method not found in target type: Npgsql.NpgsqlBinaryImporter.Cancel()

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2155]
If updated my program to the preview nuget, and got now this error:

LinqToDB.LinqToDBException: 'Method not found in target type: Npgsql.NpgsqlBinaryImporter.Cancel()'

![image](https://user-images.githubusercontent.com/364896/77932453-d8c63b00-72ad-11ea-8985-34e56c9925ea.png)

**Comment by MaceWindu** [comment]
Looks like you have thrown exceptions enabled in debugger. This is expected exception and it is catched inside of linq2db.
Will see if we can avoid throwing it.

**Comment by jogibear9988** [comment]
sorry... didn't look further... cause it was not thrown in 2.x Version...

**Comment by jogibear9988** [comment]
Should I close, or leave it?

**Comment by MaceWindu** [comment]
Leave it open, I will try to implement  optional methods support  without exceptions

**Comment by MaceWindu** [comment]
Better to fix it to not end like [AngleSharp](https://github.com/AngleSharp/AngleSharp/issues/842), where it was bombarded with reports from people failing to understand that they see catched exception :smile:
