### ISSUE TITLE
Complex Query, SQL generated seams okay, but IsExpression in AllAnyBuilder throws NotImplementedException

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2156]
I've a complex query, I will create a Test reproducing this, but it will take a little bit of time.

I've the following linq:

        var query = from i in da.Issues
                    join t in (da.Taggings.Where(x => x.TaggableType == "Issue")) on i.Id equals t.TaggableId into tj
                    from t in tj.DefaultIfEmpty()
                    join tg in da.Tags on t.TagId equals tg.Id into tgj
                    from tg in tgj.DefaultIfEmpty()
                    join u in da.Users on i.AssignedToId equals u.Id into uj
                    from u in uj.DefaultIfEmpty()
                    join p in da.Projects on i.ProjectId equals p.Id
                    join iSs in da.IssueStatuses on i.StatusId equals iSs.Id
                    join e in da.EmailAddresses on u.Id equals e.UserId into ej
                    from e in ej.Take(1).DefaultIfEmpty()
                    where
                        i.Status.IsClosed == false
                        && ((i.StartDate >= startdate && i.StartDate <= enddate) || (i.DueDate <= enddate && i.DueDate >= startdate))
                    select new { Issue = i, User = u, Project = p, Status = iSs, Email = e, IsHoliday = tgj.Any(x => x.Name == holidayName) };

            var grouped = query
                .Distinct()
                .OrderBy(x => x.User)
                .ThenBy(x => x.Issue.StartDate != null ? x.Issue.StartDate : x.Issue.DueDate.Value.AddHours(-1 * x.Issue.EstimatedHours))
                .ToList()
                .GroupBy(x => (x.User, x.Email))
                .ToList();

the query fails here:

			public override IsExpressionResult IsExpression(Expression? expression, int level, RequestFor requestFlag)
			{
				if (expression == null)
				{
					switch (requestFlag)
					{
						case RequestFor.Expression :
						case RequestFor.Field      : return IsExpressionResult.False;
					}
				}

				throw new NotImplementedException();
			}

The query works when I remove the 

           IsHoliday = tgj.Any(x => x.Name == holidayName)

the generated SQL looks good:

	--  PostgreSQL.9.5 PostgreSQL
	DECLARE @holidayName Text(6) -- String
	SET     @holidayName = 'Urlaub'
	DECLARE @take Integer -- Int32
	SET     @take = 1
	DECLARE @startdate Timestamp -- DateTime
	SET     @startdate = '2020-03-01'::date
	DECLARE @enddate Timestamp -- DateTime
	SET     @enddate = '2020-04-30'::date

	SELECT
		t4.id,
		t4.tracker_id,
		t4.description,
		t4.start_date,
		t4.closed_on,
		t4.estimated_hours,
		t4.done_ratio,
		t4.assigned_to_id,
		t4.project_id,
		t4.subject,
		t4.due_date,
		t4.category_id,
		t4.status_id,
		t4.priority_id,
		t4.fixed_version_id,
		t4.author_id,
		t4.lock_version,
		t4.created_on,
		t4.updated_on,
		t4.parent_id,
		t4.root_id,
		t4.lft,
		t4.rgt,
		t4.is_private,
		t2.u,
		t2.lastname,
		t2.firstname,
		t2.login,
		t2.hashed_password,
		t2.admin_1,
		t2.status,
		t2.last_login_on,
		t2.language_1,
		t2.auth_source_id,
		t2.created_on,
		t2.updated_on,
		t2.type_1,
		t2.identity_url,
		t2.mail_notification,
		t2.salt,
		t2.must_change_passwd,
		t2.passwd_changed_on,
		p.id,
		p.name,
		p.description,
		p.homepage,
		p.is_public,
		p.parent_id,
		p.created_on,
		p.updated_on,
		p.identifier,
		p.status,
		p.lft,
		p.rgt,
		p.inherit_members,
		p.default_version_id,
		p.default_assigned_to_id,
		"iSs".id,
		"iSs".name,
		"iSs".is_closed,
		"iSs"."position",
		"iSs".default_done_ratio,
		t3.id,
		t3.e,
		t3.address,
		t3.is_default,
		t3.notify_1,
		t3.created_on,
		t3.updated_on,
		t4.c1
	FROM
		(
			SELECT
				i.assigned_to_id,
				i.project_id,
				i.status_id,
				"a_Status".is_closed,
				i.start_date,
				i.due_date,
				i.id,
				i.tracker_id,
				i.description,
				i.closed_on,
				i.estimated_hours,
				i.done_ratio,
				i.subject,
				i.category_id,
				i.priority_id,
				i.fixed_version_id,
				i.author_id,
				i.lock_version,
				i.created_on,
				i.updated_on,
				i.parent_id,
				i.root_id,
				i.lft,
				i.rgt,
				i.is_private,
				EXISTS(
					SELECT
						*
					FROM
						tags tg
					WHERE
						tg.id = t1.tag_id AND tg.name = :holidayName
				) as c1
			FROM
				issues i
					LEFT JOIN issue_statuses "a_Status" ON i.status_id = "a_Status".id
					LEFT JOIN (
						SELECT
							x_1.taggable_id as t,
							x_1.tag_id
						FROM
							taggings x_1
						WHERE
							x_1.taggable_type = 'Issue'
					) t1 ON i.id = t1.t
		) t4
			LEFT JOIN (
				SELECT
					x_2.id as u,
					x_2.lastname,
					x_2.firstname,
					x_2.login,
					x_2.hashed_password,
					x_2."admin" as admin_1,
					x_2.status,
					x_2.last_login_on,
					x_2."language" as language_1,
					x_2.auth_source_id,
					x_2.created_on,
					x_2.updated_on,
					x_2.type as type_1,
					x_2.identity_url,
					x_2.mail_notification,
					x_2.salt,
					x_2.must_change_passwd,
					x_2.passwd_changed_on
				FROM
					users x_2
				WHERE
					x_2.type = 'User'
			) t2 ON t4.assigned_to_id = t2.u
			INNER JOIN projects p ON t4.project_id = p.id
			INNER JOIN issue_statuses "iSs" ON t4.status_id = "iSs".id
			LEFT JOIN LATERAL (
				SELECT
					ej.user_id as e,
					ej.id,
					ej.address,
					ej.is_default,
					ej."notify" as notify_1,
					ej.created_on,
					ej.updated_on
				FROM
					email_addresses ej
				WHERE
					t2.u = ej.user_id
				LIMIT :take
			) t3 ON 1=1
	WHERE
		True <> t4.is_closed AND (t4.start_date >= :startdate AND t4.start_date <= :enddate OR t4.due_date <= :enddate AND t4.due_date >= :startdate)

**Comment by jogibear9988** [comment]
I'll look to create a Unit Test...

Or is my query  not possible?

**Comment by sdanyliv** [comment]
I think it is not possible. You can not reuse GroupJoin result in such way.

**Comment by jogibear9988** [comment]
Fixed it now like this:

        var query = from i in da.Issues
                    join t in (da.Taggings.Where(x => x.TaggableType == "Issue")) on i.Id equals t.TaggableId into tj
                    from t in tj.DefaultIfEmpty()
                    join tg in da.Tags on t.TagId equals tg.Id into tgj
                    from tg in tgj.DefaultIfEmpty()
                    join u in da.Users on i.AssignedToId equals u.Id into uj
                    from u in uj.DefaultIfEmpty()
                    join p in da.Projects on i.ProjectId equals p.Id
                    join iSs in da.IssueStatuses on i.StatusId equals iSs.Id
                    join e in da.EmailAddresses on u.Id equals e.UserId into ej
                    from e in ej.Take(1).DefaultIfEmpty()
                    from h in tgj.Where(x => x.Name == holidayName).Take(1).DefaultIfEmpty()
                    where
                        i.Status.IsClosed == false
                        && ((i.StartDate >= startdate && i.StartDate <= enddate) || (i.DueDate <= enddate && i.DueDate >= startdate))
                    select new { Issue = i, User = u, Project = p, Status = iSs, Email = e, IsHoliday = h != null };

**Comment by jogibear9988** [comment]
Okay, result was not correct, I had to do the join again and not reuse the already joined table.
Is this correct or a linq2db problem?

so it works:

        var query = from i in da.Issues
                    join t in (da.Taggings.Where(x => x.TaggableType == "Issue")) on i.Id equals t.TaggableId into tj
                    from t in tj.DefaultIfEmpty()
                    join tg in da.Tags on t.TagId equals tg.Id into tgj
                    from tg in tgj.DefaultIfEmpty()
                    join u in da.Users on i.AssignedToId equals u.Id into uj
                    from u in uj.DefaultIfEmpty()
                    join p in da.Projects on i.ProjectId equals p.Id
                    join iSs in da.IssueStatuses on i.StatusId equals iSs.Id
                    join e in da.EmailAddresses on u.Id equals e.UserId into ej
                    from e in ej.Take(1).DefaultIfEmpty()
                    join t2 in (da.Taggings.Where(x => x.TaggableType == "Issue")) on i.Id equals t2.TaggableId into tj2
                    from t2 in tj2.DefaultIfEmpty()
                    join tg2 in da.Tags on t.TagId equals tg2.Id into tgj2
                    from h in tgj2.Where(x => x.Name == holidayName).Take(1).DefaultIfEmpty()
                    where
                        i.Status.IsClosed == false
                        && ((i.StartDate >= startdate && i.StartDate <= enddate) || (i.DueDate <= enddate && i.DueDate >= startdate))
                    select new { Issue = i, User = u, Project = p, Status = iSs, Email = e, IsHoliday = h != null };

**Comment by sdanyliv** [comment]
It more likely not implemented feature because of complexity. Good point here, It stopped you on writing non effective SQL in that case.

**Comment by jogibear9988** [comment]
so should I close? or is it smth. we would implement?

**Comment by sdanyliv** [comment]
Will look later, maybe it is possible. But not now.

**Comment by MaceWindu** [comment]
Actually fixed in 3.7.0 for providers with lateral join support (even for more providers in v6)
