### ISSUE TITLE
Can DelegateDecompiler be used for computed columns?

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#2157]
Can an excellent library called [DelegateDecompiler](https://github.com/hazzik/DelegateDecompiler) be be introduced (or its methodology) into Linq2Db used to assist with computed columns.
```
[Computed] public string FullName
  => $"{(string.IsNullOrWhiteSpace(KnownAs) ? FName : KnownAs)} {SName}";
```
Which is much easier than the current method of:
```
[ExpressionMethod(nameof(GetFullName), IsColumn = true)]
public string FullName { get; set; }

private static Expression<Func<T_Employees, string>> GetFullName()
  => e => $"{(string.IsNullOrWhiteSpace(e.KnownAs) ? e.FName : e.KnownAs)} {e.SName}";
```
At the moment I can get it to work by assigning the **Computed** attribute on relevant properties/methods, but I then have to call .Decompile() before each and every call of .FirstOrDefault() or .ToList() where these properties/methods are used.

Is there anyway to intercept the IQueryable before being built by Linq2Db in the DataConnection or DataContext or SqlBuilder class just just before ToList() or FirstOrDefault() so that I can add the .Decompile() in one place?

**Comment by sdanyliv** [comment]
Implement `IExpressionPreprocessor` In your `lDataConnection` class.
