### ISSUE TITLE
Create Sql.Format function or translate ToString(string format) to correct function

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db#2158]
Hi,

I have this query

```
var source = from n in _context.N
                         select new N()
                         {
                            ...
                            Time = n.Date == null ? "00:00:00" : n.Date.Value.ToString("HH:mm:ss")
                            ...
                         }
```
After that I use that source for further processing.
Time is [NotMapped].

Currenty, this query throws this exception

```
Exception message:
''ToNotNull(n.Datum).ToString("HH:mm:ss")' cannot be converted to SQL.'
```
I know I can create custom 'FORMAT' function
https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-ver15
One way would be to use it like Sql.Format(...), but it would be more convenient to just correctly translate number.ToString(string format) or datetime.ToString(string format) to this sql function.

In the mean time, is there a way to execute this n.Date.Value.ToString("HH:mm:ss") on client side only?

### Environment details
linq2db version: 3.0.0.preview2
Database Server: Sql Server 2016
Database Provider: Microsoft
Operating system: Windows 10
.NET Framework: 3.1.3

**Comment by sdanyliv** [comment]
You can create your `Sql.Format` function. And somewhere in initialization call this:
```cs
Expressions.MapMember(
   (string s, string f) => s.ToString(f), 
   (s, f) => Sql.Format(s, f)
);
```
If you need advanced processing in your `Format` function, take a look here as an example how we process custom DateTime functions:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.DateTime.cs#L892

**Comment by Marka83** [comment]
Excellent. Thank you.
