### ISSUE TITLE
Big Random Select: bad performance

### ISSUE THREAD

**Issue by TheDerevtso** [linq2db/linq2db#2165]
Hello!

I have a need to use a lot of SELECT queries for random records in the postgreSQL database.

I am currently using BLToolkit, although it is very old.

I need to make sure that when migrating to linq2db I will not get critical performance drops.

I created a test project with a simple 'user_tbl' table with three no-meaning fields (id, name, login_count), with randomly generated data (50,000 entries, generating on program start). Now I'm trying to create a sufficiently effective query to fetch half of the records (25,000). IDs are selected separately for the purity of the experiment.

I made a speed comparison between the "clean" npgsgl, bltoolkit, linq2db. 

Here are my attempts to create similar  code with linq2db.

```csharp
...
private static List<User> Linq2db_SelectUser_Linq(
    DBHelper.InnerDbConnection innerConnection, 
    List<User> usersList, Select_TestParameters parameters)
        {
            List<User> selectedUsersList = new List<User>();

            if (parameters.OneByOne)
            {
                var db = (LinqToDB.Data.DataConnection)innerConnection.Connection;

                foreach (var user in usersList)
                {
                    var q =
                        from c in db.GetTable<User>()
                        where c.Id == user.Id
                        select c;

                    selectedUsersList.AddRange(q);
                }


                // code from npgsql test
                //using (var db = PostgreSQLTools.CreateDataConnection(ConnectionString))
                //{

                //}
                //using (var cmd = new NpgsqlCommand())
                //{
                //    cmd.Connection = (NpgsqlConnection)(innerConnection.Connection);
                //    foreach (var user in usersList)
                //    {
                //        selectUser = new User();
                //        cmd.CommandText = String.Format(
                //        "SELECT * FROM public.user_tbl WHERE id = {0};",
                //        user.Id
                //        );

                //        using (var reader = cmd.ExecuteReader())
                //        {
                //            if (reader.Read())
                //            {
                //                selectUser.Id = reader.GetInt64(0);
                //                selectUser.Name = reader.GetString(1);
                //                selectUser.Login_count = reader.GetInt32(2);
                //            }
                //        }
                //        selectedUsersList.Add(selectUser);
                //    }
                //}

            }
            else // BATCH select
            {
                var db = (LinqToDB.Data.DataConnection)innerConnection.Connection;

                {
                    var usrArr = usersList.Select(u => u.Id).ToArray();
                    var q = from u in db.GetTable<User>()
                            where usrArr.Contains(u.Id)
                            select u;

                    selectedUsersList.AddRange(q);

                    var lst = db.LastQuery;
                }

                // similar code for npgsql
                //using (var cmd = new NpgsqlCommand())
                //{
                //    StringBuilder concatCommand = new StringBuilder(
                //        "SELECT * FROM public.user_tbl WHERE id IN ( ");

                //    //StringBuilder sb = new StringBuilder();

                //    foreach (var usr in usersList)
                //    {
                //        concatCommand.Append(usr.Id.ToString()).Append(',');
                //    }

                //    concatCommand.Remove(concatCommand.Length - 1, 1);
                //    //string ids = String.Join<long>(",", usersList.Select(user => user.Id));

                //    concatCommand.Append(" );");

                //    cmd.CommandText = concatCommand.ToString();
                //    cmd.Connection = (NpgsqlConnection)(innerConnection.Connection);


                //    using (var reader = cmd.ExecuteReader())
                //    {
                //        while (reader.Read())
                //        {
                //            User selectUser;
                //            selectUser = new User();

                //            selectUser.Id = reader.GetInt64(0);
                //            selectUser.Name = reader.GetString(1);
                //            selectUser.Login_count = reader.GetInt32(2);

                //            selectedUsersList.Add(selectUser);
                //        }
                //    }

                //}
            }

            return selectedUsersList;
        }

        private static List<User> Linq2db_SelectUser_FromSql(
    DBHelper.InnerDbConnection innerConnection, List<User> usersList, 
    Select_TestParameters parameters)
        {
            List<User> selectedUsersList = new List<User>();

            if (parameters.OneByOne)
            {
                var db = (LinqToDB.Data.DataConnection)innerConnection.Connection;

                foreach (var user in usersList)
                {
                    StringBuilder queryBuilder = 
new StringBuilder("SELECT id, name, login_count FROM public.user_tbl WHERE id = ");
                    queryBuilder.Append(user.Id.ToString());
                    var query = db.Query<User>(queryBuilder.ToString());

                    selectedUsersList.AddRange(query);
                }

                Console.WriteLine("LastQuery: =============\n{0}\n========", db.LastQuery);
            }
            else //BATCH
            {
                var db = (LinqToDB.Data.DataConnection)innerConnection.Connection;
                {
                    var usrArr = usersList.Select(u => u.Id).ToArray();

                    StringBuilder concatCommand = new StringBuilder(
                            "SELECT * FROM public.user_tbl WHERE id IN ( ");

                    foreach (var usr in usersList)
                    {
                        concatCommand.Append(usr.Id.ToString()).Append(',');
                    }

                    concatCommand.Remove(concatCommand.Length - 1, 1);

                    concatCommand.Append(" )");


                    //var query = db.FromSql<User>(concatCommand.ToString());
                    //var query = db.Execute<List<User>>(concatCommand.ToString());
                    //var query = db.Execute<User[]>(concatCommand.ToString());
                    var query = db.Query<User>(concatCommand.ToString());

                    selectedUsersList.AddRange(query);

                    var lst = db.LastQuery;
                }
            }

            return selectedUsersList;
        }


...
```
Program response:

![image](https://user-images.githubusercontent.com/25724721/78459266-8081a580-76c0-11ea-8873-5d16cec4a134.png)

There is a very serious difference in performance even from bltoolkit. How can I optimize the code to get performance similar to at least bltoolkit?

### Environment details
linq2db version: compiled 'master' branch at 2020-04-04
Database Server: PostgreSQL 10
Database Provider: PostgreSQLDataProvider
Operating system: Windows 10x64 1903
.NET Framework: 4.5.2 (project compile at this)

**Comment by sdanyliv** [comment]
Any chance to get source code of this benchmark?

**Comment by TheDerevtso** [comment]
> 
> 
> Any chance to get source code of this benchmark?

Yes, of course.

That's my little messy 'playground' (part of it, actually) without any 'global' logic and there is no  'code purity', but it's working for me.
[https://github.com/TheDerevtso/TestORMPerformance](https://github.com/TheDerevtso/TestORMPerformance)

**Comment by MaceWindu** [comment]
I've checked your benchmarks and there are couple of major issues with them:
- there is no warmup stage, so different startup times affect results
- from-sql test logs last LastQuery, resulting in extra work adding a lot of time

After initial cleanup I got following results which are quite similar to each other:

![image](https://user-images.githubusercontent.com/1099238/80378151-8708d480-889c-11ea-9655-f913df45bfe3.png)


Anyway, I will see what we can improve here to make it even faster.

**Comment by MaceWindu** [comment]
Also don't see any perf.regressions on that case in lastest 3.0 master

![image](https://user-images.githubusercontent.com/1099238/80378639-3e055000-889d-11ea-8d2c-b6e94dcd9a4c.png)

**Comment by TheDerevtso** [comment]
Ok, thanks for response.
I've cleared sections using db.Lastquery function.
There is added tests with linq precompiling and query parameter using.

But I don't understand how can I add some "warmup stage". Can you explain that, please? Probably there is lack of linq2db documentation (and my ignorance of course).

![image](https://user-images.githubusercontent.com/25724721/80525232-928df580-8999-11ea-97a8-c9d9188e5554.png)

**Comment by MaceWindu** [comment]
For warmup I just run each test twice. first without logging and second with log.
Warmup needed, because each approach needs different amount of initialization work for first run like jitting, loading libraries, caching queries.

There is no need in special documentation for benchmarking linq2db as there is nothing specific in it. You can check https://benchmarkdotnet.org/ for de-facto standard in .net benchmarking

**Comment by MaceWindu** [comment]
Also make sure you use release build of linq2db, as debug version contains extra logic to help with debugging

**Comment by TheDerevtso** [comment]
Yes, I've used Release build for minimization of Debug-specific overhead.

About benchmarking: I've not meant to we need "documentation for benchmarks", of course. 

My "pseudobenchmark" is a just sort of rude imitation of our production infrastructure. Anyway, thanks for the https://benchmarkdotnet.org/ - I'll try to use that in my next experiments, I've really appreciate for this.

I've trying run these tests tvice in one process but I can't get so significant speed up except test with a big linq func (batch select).

I've curtainly "did it wrong" but what exactly I can do for not so "dissimilar" and more robust results?

![image](https://user-images.githubusercontent.com/25724721/80605001-24017400-8a3b-11ea-949b-e3a09e8c6514.png)

**Comment by MaceWindu** [comment]
That's really strange numbers. Could you update your project with lastest changes to I can check?

**Comment by TheDerevtso** [comment]
Already. BTW, I've use HDD 5400 bmp (not SSD) and default PostgreSQL server settings.

**Comment by MaceWindu** [comment]
Environment settings (HDD/server settings) shouldn't be important here as they are the same for all tests anyways.

I can confirm your results... which is really strange.

Note that to get proper results, code-under-test should contain only logic, related to evaluated functionality. If some extra logic used, it should at least be the same as much as possible to not affect results. I've made following changes to mitigate those issues:
- Removed all ToArray calls from linq2db tests. They are not needed and just add extra unrelated times to tested functionality
- moved compiled query to static field, otherwise you will compile it again on second run, making warm-up less effective
- removed creation of unused array usrArr from  Linq2db_SelectUser_Query, Linq2db_SelectUser_FromSql, Linq2db_SelectUser_FromSql_Params
- updated query generation logic for IN list to use string.join in linq2db and npgsql tests as it is done for bltoolkit (actually moved it to separate method and reused)
- npgsql tests don't use string builder (except IN batch generation), so I also used string.Format for other tests as StringBuilder is overkill here.
- also I moved Stopwatch start/stop to before/after test method call, but it doesn't really matter much

With those changes I'm getting following numbers (similar picture with recent master):
![image](https://user-images.githubusercontent.com/1099238/80614588-ebfc3000-8a3e-11ea-9122-05cd075e37b6.png)

which is strangely bad for FromSql and Query methods. I will look into it.

**Comment by MaceWindu** [comment]
Checked with profiler and can confirm that it's linq2db issue for those 3 long tests. Will be fixed for next release

**Comment by TheDerevtso** [comment]
Upd: 
Using DataParameters with OneByOne-Query gives much more good results than "only text" Query even without warming up. But not for `FromSQL`. 

```csharp
var query = 
    db.Query<User>("SELECT id, name, login_count FROM public.user_tbl WHERE id = @usr", 
    new DataParameter("@usr", user.Id));
```

PS: StringBuilder not so bad: String.Format method internally using just StringBuilder.AppendFormatHelper (which internally parse Format string and using StringBuilder as a "glue") and nothing more.

**Comment by MaceWindu** [comment]
Yes, performance degradation you see is caused by lack of caching on linq2db side, which is possibly caused by use of different sql for each query. I will see if we can ignore sql and cache only based on result type for those cases.

**Comment by MaceWindu** [comment]
But anyway, for production use you should use parameters. And not use FromSql for raw sql execution, as it is primary intended for use in other queries and raw sql injection

**Comment by MaceWindu** [comment]
Status update.

We identified and fixed two caching issues with `FromSql`, where query wasn't cached, so in next release it will work faster if  `DataParameter` used for parameters.

Remaining long-running cases will not be fixed, because we cannot reuse query when sql changed. This will require us to write SQL parser for all supported databases with is out-of-scope. And writing queries like that anyways is not not a good idea security- and performance-wise.

**Comment by MaceWindu** [comment]
Results for properly parametrised queries
![image](https://user-images.githubusercontent.com/1099238/80865336-01fd3100-8c89-11ea-9f4b-f13be19fb160.png)

**Comment by MaceWindu** [comment]
#2197

**Comment by TheDerevtso** [comment]
Thank you very much! I really appreciate for this.
