### ISSUE TITLE
Unexpected behavior for the FirstOrDefault method

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2167]
I got "null" in FirstOrDefault when the SQL command does not find the result.

DB: **PostgreSQL**
The structure of table:
```sql
create table products
(
    id                bigserial     not null  constraint pk_product  primary key,
    code  varchar(10)
);

insert into products (code) values ('test');
```

C# code:

![image](https://user-images.githubusercontent.com/30083441/78583582-b0a38280-783f-11ea-9058-53ecd8e1ee6e.png)

Is it Ok? Or what I have to do to get an empty Entity class?

**Comment by sdanyliv** [comment]
Yes :) 
`FirstOrDefault` means: return first or default value. Default value for class is `null`.

Better to write your own extension which calls FirstOrDefault and returns default not null value.

**Comment by AndrePScope** [comment]
OK 
Thanks, @sdanyliv
