### ISSUE TITLE
DataConnection.OnEntityCreated not called with LoadWith

### ISSUE THREAD

**Issue by Drapondur** [linq2db/linq2db#2169]
When LoadWith is used, DataConnection.OnEntityCreated is not called for the entities of the subquery. 
The reason seems to be that the DataConnection is cloned for subqueries but DataConnection.Clone does not pass the OnEntityCreated delegate to the clone.

I solved this for myself in 2.9.7 by changing DataConnection.Clone from
```
		public object Clone()
		{
			var connection = _connection?.TryClone() ?? _connectionFactory?.Invoke();

			// https://github.com/linq2db/linq2db/issues/1486
			// when there is no ConnectionString and provider doesn't support connection cloning
			// try to get ConnectionString from _connection
			// will not work for providers that remove security information from connection string
			var connectionString = ConnectionString ?? (connection == null ? _connection?.ConnectionString : null);

			return new DataConnection(ConfigurationString, DataProvider, connectionString, connection, MappingSchema);
		}
```
to

		public object Clone()
		{
			var connection = _connection?.TryClone() ?? _connectionFactory?.Invoke();

			// https://github.com/linq2db/linq2db/issues/1486
			// when there is no ConnectionString and provider doesn't support connection cloning
			// try to get ConnectionString from _connection
			// will not work for providers that remove security information from connection string
			var connectionString = ConnectionString ?? (connection == null ? _connection?.ConnectionString : null);

			var result = new DataConnection(ConfigurationString, DataProvider, connectionString, connection, MappingSchema);
			result.OnEntityCreated = this.OnEntityCreated;
			return result;
		}

Could this be fixed for the next relase or are there any side-effects I am not aware of here?

### Environment details
linq2db version: 2.9.7
Database Server: Sql Server 2012
Database Provider: 
Operating system: Windows 10
.NET Framework: I guess all

**Comment by sdanyliv** [comment]
Could you please check version `3.0-preview2`?
It has completely rewritten LoadWith functionality.

**Comment by MaceWindu** [comment]
Cloning itself is a huge side-effect :). In v3 we fixed LoadWith to not use cloning, so it should be fixed there. Still I will keep this issue open, as we still have cloning functionality used for couple of other features.

**Comment by MaceWindu** [comment]
Linking another cloning-related issue #962, to not forget to finally fix it too

**Comment by MaceWindu** [comment]
Well, in general I need to check that other DataConnection options also compatible with Cloning
