### ISSUE TITLE
Oracle connection KeepAlive

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#2171]
Code you add KeepAlive support for oracle in DataConnection Class?

**Comment by sdanyliv** [comment]
We can, but not with current options system. I suggest to handle two events in `DataConnection`

`OnConnectionOpened` and `OnConnectionOpenedAsync`
or `OnBeforeConnectionOpen` and `OnBeforeConnectionOpenAsync`

and configure `OracleConnection` by yourself.

**Comment by sarabu07** [comment]
Thanks for the update.
