### ISSUE TITLE
Linq2db entity framework update query for dynamic table and column

### ISSUE THREAD

**Issue by hnviradiya** [linq2db/linq2db#2172]
Describe your issue.

### Steps to reproduce
I am trying to create query using dynamic tables and dynamic columns.
So that I can pass any table and column name from string.
Now problem is I have to mention EntityType (I have asked [question on stackoverflow](https://stackoverflow.com/questions/61081571/linq2db-entity-framework-update-query-for-dynamic-table-and-column/61096238#61096238) as well as also tried to hire some developer who knows linq2db).

Isn't it possible to escape entitytype and directly we can execute query?

e.g. c#

Current support. 
```
public void update<TEntity>(string entity, string attribute, object value, string whereAttribute, string whereAttributeValue)
    where TEntity : class
{
    projectContext.GetTable<TEntity>()
        .TableName(entity)
        .Where(t => Sql.Property<TEntity>(t, whereAttribute).Equals(whereAttributeValue))
        .Set(t => Sql.Property<TEntity>(t, attribute), value)
        .Update();
}
```
Needed support.

```
public void update(string entity, string attribute, object value, string whereAttribute, string whereAttributeValue)
{
    projectContext.GetTable()
        .TableName(entity)
        .Where(t => Sql.Property(whereAttribute).Equals(whereAttributeValue))
        .Set(t => Sql.Property(attribute), value)
        .Update();
}
```

```

### Environment details
linq2db version: 2.9.7
Database Server: SQL server 2019
Operating system: Windows 10
.NET Framework: .Net core 3.1

**Comment by sdanyliv** [comment]
Maybe you have some schema of your dynamic entities with property types?

**Comment by hnviradiya** [comment]
I am trying to update different types of tables. So I am sending string of table name. So far what I can do is get entity based on following answer (using reflection) to get entity. Someone suggested that reflection is a bad practice to use. 

So isn't it possible without types? Which can simply execute row sql based on linq with provided entity name in string format, without depending on models or schema?

https://stackoverflow.com/a/12455419/9263418

**Comment by sdanyliv** [comment]
Anyway, if this code works - it is easy to transform it via reflection to your variant.
```cs
public void update<TEntity>(string entity, string attribute, object value, string whereAttribute, string whereAttributeValue)
    where TEntity : class
{
    projectContext.GetTable<TEntity>()
        .TableName(entity)
        .Where(t => Sql.Property<string>(t, whereAttribute) == whereAttributeValue)
        .Set(t => Sql.Property<string>(t, attribute), value)
        .Update();
}
```

**Comment by MaceWindu** [comment]
Check also this https://github.com/linq2db/linq2db/issues/1591#issuecomment-462048375
