### ISSUE TITLE
How to change Table Schema at runtime?

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2173]
Hello,
  I need to deploy my application to a production environment.
  I'm connecting to an Oracle instance.
  My concern is about the fact that the schema name of development db is different from production one. 
  In Oracle the schema name corresponds to the user id and in this case the user of development is different from the production one..
  The schema name is assigned to classes, by T4 template, using the Table attribute and at runtime is not possible to change the attributes values.

  Do you know a way to change the schema name at runtime? Is it possible to avoid to specify the schema name in the Table attribute and let linq2db to use the user id specified in the connection string?

  Thank you!

**Comment by sdanyliv** [comment]
There are three ways:

1. Disable schema name generation in T4 before call the `GenerateModel()`
```cs
foreach (var table in Tables.Values)
{
    table.Shema = null;
}
```
2. Using extension method `db.GetTable<Some>().SchemaName(“OtherSchema”)`
3. Configure for connection appropriate `MappingSchema`

**Comment by filippobottega** [comment]
@sdanyliv thank you very much for your first suggestion.
Disabling schema name generation solved my issue.
In my use case I don't need to specify schema name with suggestions 2 and 3.

Best regards,
  Filippo.

**Comment by filippobottega** [comment]
Hi @sdanyliv,
  I have found the right way to do it in the tt file from [T4 article](https://linq2db.github.io/articles/T4.html):

```
	/* Table mappings configuration */
	// Enables generation of TableAttribute.Schema property for default schema
	IncludeDefaultSchema          = false;
```
