### ISSUE TITLE
Query about a dotnet core MVC template

### ISSUE THREAD

**Issue by David-Mawer** [linq2db/linq2db#2181]
Hi there,

So I love Linq2DB.

So much so, that I pretty much look for any way to use this tool instead of the default EntityFramework that's used for things like Microsoft Indentity, and MVC apps, and pretty much any template that comes with visual studio.

Since there may be other people with this kind of passion for Linq2DB, I've created a default .NET Core 3.1 MVC application that works with Linq2DB.

I'm not sure if my style of coding OK for my template to be used as a reference for others who are looking for a basic MVC template.

Could you please let me know if this is of any value to the team?

Sincere thanks,
David :-)

Repository = https://github.com/David-Mawer/LINQ2DB-MVC-Core-3

### Environment details
linq2db version: *3.0.0-preview.2*
Database Server: *Microsoft SQL Server*
Database Provider: *SqlServer*
Operating system: *Windows - but hopefully also works on Linux*
.NET Framework: *.Net Core 3.1*

**Comment by MaceWindu** [comment]
Thanks! Sounds great! I will check it later and include in our readme. We really miss stuff like that for beginners.

**Comment by David-Mawer** [comment]
I'm glad that the template helped...

...but I'm also interested in using the Angular / API code pattern some times...

...so here's a starter template for that solition: -

https://github.com/David-Mawer/LINQ2DB-AngularWebApp-Core-3

(similar to the MVC solution - I took what Visual  Studio creates for you, and converted it to use Linq2DB).

:-)

**Comment by MaceWindu** [comment]
I've added links to templates to readme
