### ISSUE TITLE
Insert json SqlClinet

### ISSUE THREAD

**Issue by pavelvondrasek** [linq2db/linq2db#2187]
Hi,

now I'm working on application which is running on Linq2db SqlClient.

I've problem with JSON. How can I insert JToken value? 

It fails with this message:
No mapping exists from object type Newtonsoft.Json.Linq.JValue to a known managed provider native type.

I found how to do that with Npgsql but not with SqlClient :(

```cs
                    await _db.Blocks // Title with {name} - node.name
                        .Value(b => b.Type, BlockType.Title)
                        .Value(b => b.RevisionId, revisionId)
                        .Value(b => b.Value, @"{""text"": ""{name}""}")
                        .InsertWithInt32IdentityAsync();
```

Thanks!

**Comment by sdanyliv** [comment]
Without information about model and column type it may be not correct.
You can register mapping globally or per connection:
```cs
MappingSchema.Default.SetConverter<JToken, DataParameter>(json => new DataParameter
	{ Value = json.ToString() });

MappingSchema.Default.SetConverter<string, JToken>(str => JToken.Parse(str));
```

**Comment by pavelvondrasek** [comment]
Hi Svyatoslav, 

it works great! Sorry for delay in communication I'm a bit busy because of deadline :)

I was confused because solution for npgsql is different (you need setup npgsql json.net plugin) and didn't know that for SqlClient SetConverter is possible solution :)

Thank you for response. Linq2db community support is absolutely awesome ❤️

**Comment by sdanyliv** [comment]
Great, closing for now.
