### ISSUE TITLE
Type Initializer Error Thrown by linq2db InformixDataProvider when run in Web Application but not Console

### ISSUE THREAD

**Issue by robnardo** [linq2db/linq2db#219]
I am trying to use the linq2db library (thanks by the way!) to retrieve records from an Informix database. I followed the steps from the documentation and was able to successfully get records from an ASP.NET console applicaiton using the Visual Studio debugger. 

However, I then tried to follow the same with a fresh and standalone ASP.NET MVC5 application and I am getting the error "The type initializer for 'IBM.Data.Informix.IfxDecimal' threw an exception." also running using Visual Studio debugger. 

I did some digging by downloading the source code and adding some break points and found that Line 125 and line 133 of the file LinqToDB.DataProvider.Informix.InformixDataProvider file are involved in causing the error. But that is as far as I got. So running in the context of a web application throws an error, but running in a console application is fine.

Below is line 125 of LinqToDB.DataProvider.Informix.InformixDataProvider

```cs
MappingSchema.AddScalarType(_ifxDecimal,  GetNullValue(_ifxDecimal),  true, DataType.Decimal);
```

below is the GetNullValue method in that class (lines 130 to 134 of same file), error gets thrown on _return getValue.Compile()()_

```cs
static object GetNullValue(Type type)
{
    var getValue = Expression.Lambda<Func<object>>(Expression.Convert(Expression.Field(null, type, "Null"), typeof(object)));
    return getValue.Compile()();
}
```

**Additional Info..** In the documentation titled Informix Client Software Development Kit (Version 4.10) in Table 2-1. Best-fit types for retrieving Informix data types it shows that there are three DECIMAL Informix types, each map to three different suggested .NET types

i found some time to continue my digging and thinking this may have something to do with Thread Culture ?? I also found that when drilling down through the error above the expression 
 ```
((System.Exception)(((IBM.Data.Informix.IfxException)(((System.Exception)(typeIn‌​itializationException))._innerException)).Message))._message
```
 gives "Object reference not set to an instance of an object."

This is a copy of what is in a stackoverflow item on this here: http://stackoverflow.com/questions/30171835/type-initializer-error-thrown-by-linq2db-informixdataprovider-when-run-in-web-ap

**Comment by igor-tkachev** [comment]
Can create a test project, so I will be able to reproduce the issue?

**Comment by MaceWindu** [comment]
@robnardo do you still have this problem? We tried to reproduce it without success, so we are closing it for now. If you can provide more details like stack trace, version of Informix client, etc it will help a lot

**Comment by sdanyliv** [comment]
New details, same issue here #856

**Comment by MaceWindu** [comment]
closing in favor of #856 with more details
