### ISSUE TITLE
Could not load type System.Data.SqlClient.SqlCommandBuilder

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db#2191]
Hi,

I have to switch connection string based on user token, so instead of implementing ILinqToDBSettings I tried to provide service factory and manually set provider and connections string like this:

```
public AuthorizationDbContext(string connectionString)
            : base("SqlServer", connectionString)
        { }
```

But it throws me exception:
`System.TypeLoadException: 'Could not load type 'System.Data.SqlClient.SqlCommandBuilder' from assembly 'System.Data.SqlClient, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'`

Also, doesn't 3.0 use new SqlClient from Microsoft.Data.SqlClient namespace?

P.S. 
I'm migrating from EF, so I referenced linq2db.entityframeworkcore, if that makes any difference.
When I use Linq2Db from DbContext everything works fine.

### Environment details
linq2db version: 3.0.0.preview2
Database Server: Sql Server 2016
Database Provider: SqlServer
Operating system: Windows 10
.NET Framework: 3.1.3

**Comment by MaceWindu** [comment]
Both providers supported, so it is recommended to explicitly specify which one to use to not depend on detection logic. With your configuration linq2db has only "SqlServer" string to work with, so it returns default provider, which is `System.Data.SqlClient`.
You can:
- change default provider: `SqlServerTools.Provider = SqlServerProvider.MicrosoftDataSqlClient`
- use more specific connection name: `Microsoft.Data.SqlClient`

**Comment by Marka83** [comment]
Thank you. I'll try it tommorow.

**Comment by Marka83** [comment]
Everything works as expected now.
