### ISSUE TITLE
Does the expression tree get cached if you make multiple calls

### ISSUE THREAD

**Issue by ekalchev** [linq2db/linq2db#2192]
I want to know if expression trees are compiled on each call. For example

```
int id = 0;
while(true)
{
id++;
var items = context.Table.Where(i => i.id = id).ToList();
}
```
If yes - is there a way to avoid expression tree compilation for each call if using the same expression tree multiple times?

**Comment by sdanyliv** [comment]
It should be cached for such queries. No additional compilation should be performed.
Do you have any issues with this?

**Comment by ekalchev** [comment]
No, I am just looking for best performance when using expression trees.

**Comment by ekalchev** [comment]
Can you tell me class name that is responsible for caching so I can be sure my queries are cached?

**Comment by sdanyliv** [comment]
Everything is hidden in library. But if you debug current sources, you can check this property
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Query.cs#L274
