### ISSUE TITLE
MySql FREETEXT support

### ISSUE THREAD

**Issue by SilverioMiranda** [linq2db/linq2db#220]
Hi again :)

If i add FULLTEXT to column like this : `ALTER TABLE `cliente` ADD FULLTEXT(`Logradouro`);`
The tool throw this exception :
![image](https://cloud.githubusercontent.com/assets/1939153/7782299/7306b2d4-00e5-11e5-8aa2-1d9fc0d9b71a.png)

I have no idea how to fix it :(

**Comment by igor-tkachev** [comment]
Can you provide and example?

**Comment by MirandaBrazil** [comment]
```
CREATE TABLE IF NOT EXISTS `teste` (
  `ID` int(10) unsigned NOT NULL,
  `Texto` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `teste`
  ADD PRIMARY KEY (`ID`), ADD FULLTEXT KEY `Texto` (`Texto`);
-- AUTO_INCREMENT for table `teste`
ALTER TABLE `teste`
  MODIFY `ID` int(10) unsigned NOT NULL AUTO_INCREMENT;
```

This table will throw that exception when i run the mysql tt file
