### ISSUE TITLE
TraceInfo.RecordsAffected

### ISSUE THREAD

**Issue by sd-mobile** [linq2db/linq2db#2202]
Why TraceInfo.RecordsAffected has 0 value when I try delete, update or insert rows into table?
How I can get actual value while tracing?

### Environment details
linq2db version: 2.9.4
Database Server: SqlServer 2017
Database Provider: SqlServer
Operating system: Windows 10 Pro
.NET Framework: 4.6.1

**Comment by MaceWindu** [comment]
You should look at `TraceInfoStep.AfterExecute` event for `RecordsAffected` value, not `TraceInfoStep.Completed`.
