### ISSUE TITLE
[Oracle] UPDATE FROM: implement correlated update support

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#2204]
Hi!

I think Oracle has more good candidate for such thing:
```sql
UPDATE
  [UpdatedEntities]
SET
  ( [Value1], [Value2], [Value3] ) = 
  (
    SELECT
      ([UpdatedEntities].[Value1] * [t].[Value1]) * @int1,
      ([UpdatedEntities].[Value2] * [t].[Value2]) * @int2,
      ([UpdatedEntities].[Value3] * [t].[Value3]) * @int3
    FROM
      [NewEntities] [t] 
    WHERE
      [t].[id] <> @someId AND [UpdatedEntities].[id] = [t].[id]
  )
WHERE
  EXISTS(
    SELECT
      *
    FROM
       [NewEntities] [t6] 
    WHERE
      [t6].[id] <> @someId AND [UpdatedEntities].[id] = [t6].[id]
  )
  ```

_Originally posted by @AndrePScope in https://github.com/linq2db/linq2db/pull/1278#issuecomment-620851672_

**Comment by jods4** [comment]
That would be a great improvement!

Currently a subquery in Oracle UPDATE is copied for every column you extract from it, so if you want to update 10 columns, that's 10 times the (potentially big) subquery.

Using the syntax in this issue, it would be reduced to just two copy of the subquery: one for the SET and one for the WHERE, which is probably what you'd write manually.

**Comment by viceroypenguin** [comment]
(Caveat: not familiar w/ Oracle; both examples come from MS SQL) Why would one of the following not be better?
```sql
merge into UpdatedEntities ue
using (
    SELECT
      ([UpdatedEntities].[Value1] * [t].[Value1]) * @int1,
      ([UpdatedEntities].[Value2] * [t].[Value2]) * @int2,
      ([UpdatedEntities].[Value3] * [t].[Value3]) * @int3
    FROM
      [NewEntities] [t] 
    WHERE
      [t].[id] <> @someId) t
on ue.[id] = [t].[id]
when matched then update
  set Value1 = t.Value1,
      Value2 = t.Value2,
      Value3 = t.Value3;
```

or
```sql
UPDATE
  [ue]
SET Value1 = ue.Value1 * t.Value1 * @int1,
    Value2 = ue.Value2 * t.Value2 * @int2,
    Value3 = ue.Value3 * t.Value3 * @int3
FROM
  [UpdatedEntities] [ue]
    inner join [NewEntities] [t]
      on ue.id = t.id and t.id <> @someId;
```

Both of these would only query NewEntities once instead of twice even.

**Comment by sdanyliv** [comment]
@viceroypenguin. Oracle is the rule-breaker, WITH statements in such case will not work. Oracle sticks WITH statement with SELECT, not whole query.

**Comment by jods4** [comment]
@viceroypenguin UPDATE FROM is 100% what I'd use in Sql Server but it is sadly not available in Oracle, hence the ugly trick. 
Maybe MERGE might work, I'd need to think about it and try it. MERGE is a weird statement that can have weird perf and weird locking semantics though, so that's something to be aware of when replacing the default code generator.

**Comment by jods4** [comment]
@sdanyliv tangentially related: is there a syntax to write a "tuple" (not sure what's the right word) update in Oracle manually?

I.e. can you write this with linq2db?
```sql
update X set (a, b) = (1, 2)
-- or with a subselect
update X set (a, b) = (select 1, 2 from dual)
```
