### ISSUE TITLE
FromSql with orderby

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db#2205]
Use class from Issue #2199:

`var test = _context.FromSql<Country>("select Code,Name from Country order by Name");`

This query doesn't work because you generate following query:

```
SELECT
	[t1].[Code],
	[t1].[Name]
FROM
	(
		select Code,Name from Country order by Name
	) [t1]
```
Now you have order by within subquery which isn't allowed.
This can be fixed by removing order by from 'FromSql' and apply it afterwards, but you should handle this case.
Why don't you just use straight query as specified in 'FromSql'?

### Environment details
linq2db version: 3.0.0.preview2
Database Server: SqlServer 2016
Database Provider: MicrosoftDataSqlClient
Operating system: Windows 10
.NET Framework: .Net Core 3.1.3

**Comment by MaceWindu** [comment]
Main goal of `FromSql` API is to provide ability to perform query composition using ad-hoc sql. For that we need to know column aliases.

If you just want to execute raw sql query, you should use `Execute(sql)` methods

**Comment by Marka83** [comment]
Ok, but I still don't understand why you need to generate column aliases?
I specify class to map my query into and my query must have the same column names as specified in model. Generating one level of indirection won't change anything. 
Is instead i write 'select Code from Country' (without name) this query will fail.

I agree that order by shouldn't be in there, but I don't know why you generate column aliases?

I believe you used same approach for joins:
https://github.com/linq2db/linq2db/issues/2195#issuecomment-620570523

where you unnecessarily generate columns for joined tables and almost double query size.

I'm not questioning your judgement. I just want to understand reasoning behind it.

**Comment by sdanyliv** [comment]
Do not mix these two issues, they have different root.
We generate columns, because LINQ mapper uses indexes of the columns, not their names.
So in your case we have to put it into subquery. Sure we can write simple parser and retrieve column indexes, but it was not a primary goal for FromSql implementation.

**Comment by sdanyliv** [comment]
Also what to do if you just put star instead of column names. What to do with parsing other SQL dialects?

**Comment by sdanyliv** [comment]
Also your query has no aliases, and we can not correctly inject into big generated SQL. That’s why it is in our controlled subquery.

**Comment by Marka83** [comment]
Ok, I understand.
One more suggestion. When you do join, it's mostly done by primary key which cannot have nullable columns, so generating 

`[e].[CountryCode] IS NULL AND [t1].[Code] IS NULL OR [e].[CountryCode] = [t1].[Code]`

isn't necessary in 99% of cases.
If someone needs this it can specify ANSI_NULLS 
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-nulls-transact-sql?view=sql-server-ver15
or use isnull operator.

I'm not trying to be ungrateful. I like your product and we are just switching from EF.
I just won't to make suggestions which, at least it's my opinion, can make your product even better.

**Comment by sdanyliv** [comment]
Turn that off:
```cs
Configuration.Linq.CompareNullsAsValues = false;
```

**Comment by Marka83** [comment]
Ahhhh, excellent :D
You really have configuration for everything.

**Comment by sdanyliv** [comment]
Anyway your classes has Nullable PK columns, that's why we generate such comparison expressions.

**Comment by Marka83** [comment]
Ok. It makes sense. I'll set CompareNullsAsValues=false;
