### ISSUE TITLE
CommandText for IUpdatable/ISelectInsertable/IValueInsertable

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#2207]
* [IUpdatable<T>](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/IUpdatable.cs)
* [ISelectInsertable<T, TTarget>](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/ISelectInsertable.cs)
* [IValueInsertable<T>](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/IValueInsertable.cs)

For each of the above, is there a way to get the command text for before they are executed & without modifying the database?

I know I can get the text of the last command from a DataConnection by using LastQuery after the command has been executed, but I need it before. 

`IQueryable<T>.ToString()` seems to work for select commands. 

The following works using transactions with rollback calls, but this it far from ideal and obvious wouldn't be used production code:
```
public static class DataConnectionExtensions {

    public static string LastQueryUpdatable = string.Empty;
    public static string LastQuerySelectInsertable = string.Empty;
    public static string LastQueryValueInsertable = string.Empty;

    public static string LastQuery<T>(this DataConnection dataConnection, IUpdatable<T> updatable) {
      var sql = $"Cannot get {nameof(LastQuery)} for {updatable}";
      using(var t = dataConnection.BeginTransaction()) {
        updatable.Update();
        sql = dataConnection.LastQuery;
        t.Rollback();
      }
      LastQueryUpdatable = sql;
      return sql;
    }

    public static string LastQuery<T, TTarget>(this DataConnection dataConnection, ISelectInsertable<T, TTarget> selectInsertable) {
      var sql = $"Cannot get {nameof(LastQuery)} for {selectInsertable}";
      using(var t = dataConnection.BeginTransaction()) {
        selectInsertable.Insert();
        sql = dataConnection.LastQuery;
        t.Rollback();
      }
      LastQuerySelectInsertable = sql;
      return sql;
    }

    public static string LastQuery<T>(this DataConnection dataConnection, IValueInsertable<T> valueInsertable) {
      var sql = $"Cannot get {nameof(LastQuery)} for {valueInsertable}";
      using(var t = dataConnection.BeginTransaction()) {
        valueInsertable.Insert();
        sql = dataConnection.LastQuery;
        t.Rollback();
      }
      LastQueryValueInsertable = sql;
      return sql;
    }

}
```

**Comment by sdanyliv** [comment]
Could you please try `LinqToDB.Linq.Internals.GetDataContext(..)` it has a lot of overloads to get context from query.

**Comment by to11mtm** [comment]
I've not dug further but the issue I ran into doing similar is that the query expression is hidden from the interface definitions for each, for example the public `IUpdatable<T>` interface doesn't have an `IQueryable<T>` on it, but rather the declaration is on `Updatable<T>` private class.

The solution I found, works but uses internal bits of API:

```
//Also make overloads for IValueinsetable, ISelectInsertable
public static string GetSql<T>(IUpdatable<T> updatable)
{
	return (updatable.GetType().GetField("Query").GetValue(updatable) as IExpressionQuery).SqlText;
}
```

**Comment by tb-mtg** [comment]
@ sdanyliv 
Most of [LinqToDB.Linq.Internals](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Internals.cs) code is only available in version 3, I am using the current release version 2.9.8.

[LinqToDB.Linq.Internals](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Internals.cs) also makes reference to the following classes:
* [LinqExtensions.Updatable](https://github.com/linq2db/linq2db/blob/55c44feca711ba8c3f3b208a57a727f5268cd178/Source/LinqToDB/LinqExtensions.cs#L617)
* [LinqExtensions.SelectInsertable](https://github.com/linq2db/linq2db/blob/55c44feca711ba8c3f3b208a57a727f5268cd178/Source/LinqToDB/LinqExtensions.cs#L1780)
* [LinqExtensions.ValueInsertable](https://github.com/linq2db/linq2db/blob/55c44feca711ba8c3f3b208a57a727f5268cd178/Source/LinqToDB/LinqExtensions.cs#L1133)

Could these be changed from internal to public?

**Comment by tb-mtg** [comment]
@to11mtm I've created the following with your help:

Helper Extension:
```
public static IExpressionQuery GetIExpressionQuery<T>(this Type type, T obj) => (IExpressionQuery)type.GetField("Query").GetValue(obj);
```
ISelectInsertable Extensions
```
    public static IExpressionQuery GetIExpressionQuery<T, TT>(this ISelectInsertable<T, TT> insertable) => typeof(ISelectInsertable<T, TT>).GetIExpressionQuery(insertable);
    public static IDataContext GetDataContext<T, TT>(this ISelectInsertable<T, TT> insertable) => insertable.GetIExpressionQuery().DataContext;
    public static Expression GetExpression<T, TT>(this ISelectInsertable<T, TT> insertable) => insertable.GetIExpressionQuery().Expression;
    public static string GetSqlText<T, TT>(this ISelectInsertable<T, TT> insertable) => insertable.GetIExpressionQuery().SqlText;
```
IUpdatable Extensions
```
    public static IExpressionQuery GetIExpressionQuery<T>(this IUpdatable<T> updatable) => typeof(IUpdatable<T>).GetIExpressionQuery(updatable);
    public static IDataContext GetDataContext<T>(this IUpdatable<T> updatable) => updatable.GetIExpressionQuery().DataContext;
    public static Expression GetExpression<T>(this IUpdatable<T> updatable) => updatable.GetIExpressionQuery().Expression;
    public static string GetSqlText<T>(this IUpdatable<T> updatable) => updatable.GetIExpressionQuery().SqlText;
```
IValueInsertable Extensions
```
    public static IExpressionQuery GetIExpressionQuery<T>(this IValueInsertable<T> insertable) => typeof(IValueInsertable<T>).GetIExpressionQuery(insertable);
    public static IDataContext GetDataContext<T>(this IValueInsertable<T> insertable) => insertable.GetIExpressionQuery().DataContext;
    public static Expression GetExpression<T>(this IValueInsertable<T> insertable) => insertable.GetIExpressionQuery().Expression;
    public static string GetSqlText<T>(this IValueInsertable<T> insertable) => insertable.GetIExpressionQuery().SqlText;
```

**Comment by sdanyliv** [comment]
Please describe me why do you need SQL for these commands before execute? Maybe i'll add needed API.

**Comment by tb-mtg** [comment]
When trying to run an insert or update command fails I'd like to know what CommandText had been generated that caused the exception.  

Also sometimes would like to see the generated ComandText to see if it could be optimized better.

**Comment by to11mtm** [comment]
Just adding for another use case...

Sometimes I have to make SQL for certain Insert or update statements that are not executed via code (i.e. for Rollout/rollback type scripts.) Getting these strings lets me use Linq2Db in Linqpad to generate the SQL for these scripts.

**Comment by sdanyliv** [comment]
Good point, maybe it is good to add additional API for script generation, for example with inlined parameters. 
I'm also doing such SQL generation, but usually copy SQL from debugger.
