### ISSUE TITLE
DB2 iSeries Support

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#221]
Great project!  

Currently the DB2 data provider supports LUW and zOS versions.

Is there any chance of supporting the IBM i Access for Windows .NET provider (<b>IBM.Data.DB2.iSeries.dll</b>) in the future?

**Comment by igor-tkachev** [comment]
How can I download dev version of the server?

**Comment by tb-mtg** [comment]
There is a nuget package for the IBM iSeries ADO.NET<https://www.nuget.org/packages/IBM.Data.DB2.iSeries/7.1.0> (7.1.0) library which lets you reference: iDB2Command, iDB2CommandBuilder, iDB2Connection, iDB2DataAdapter, etc.

I use DB2 iSeries at work, I’m not sure there is a “dev version of the server”. Perhaps the next few links:


·         http://www-01.ibm.com/software/data/db2/linux-unix-windows/downloads.html



·         http://www.ibm.com/support/docview.wss?rs=4020&uid=swg21385217

I am going to try out the express community edition from home to see if it supports DB2 iSeries.

Other pages may be helpful for using “IBM i Access for Windows”

Connect to IBM DB2 only using .dll reference<https://www.ibm.com/developerworks/community/forums/html/topic?id=77777777-0000-0000-0000-000014491597>

Where to get the iSeries ADO.NET data provider<http://dotnetfluke.blogspot.com.au/2008/01/where-to-get-iseries-adonet-data.html>

**Comment by amccorma** [comment]
I wrote the iSeries DB2 provider if anyone interested.  the DB2 provider included was not correct for IBM iSeries.

**Comment by tb-mtg** [comment]
Yes I am interested. 

I have managed to create a very basic DataProvider for iSeries DB2 (formerly AS400). It is not fully tested for all features yet, but it is working so far.

However as I am new to Github, I am not familiar with pull requests so I am not sure how or where to post my code.

**Comment by amccorma** [comment]
I attached my code.  maybe we can compare your solution and mine to see if we can merge it for a pull request.  

https://drive.google.com/file/d/0B9e5M9PgHNOOLS1QWm1GYW9QSVE/view?usp=sharing

just replace the DB2 folder under DataProvider.

created:
iDB2SqlBuilder.cs
iDB2SchemaProvider.cs
modified:  iDB2SchemaProvider.cs

Sample code:
I created a new enum type for iSeries.  There were a few types that I could not map like XML.  I used String, but there are other types that could map to it.  

public Repository() : base(new LinqToDB.DataProvider.DB2.DB2DataProvider("", LinqToDB.DataProvider.DB2.DB2Version.iSeries), 
            new IBM.Data.DB2.iSeries.iDB2Connection(System.Configuration.ConfigurationManager.AppSettings["IBMConnectionString"]))
        { }

**Comment by tb-mtg** [comment]
This is my first attempt & I was not sure how to do a pull request, so hopefully the link below works, 

https://gist.github.com/tb-mtg/5aaf36df5cddda3dc6d8

I modified the following files:

* Data\DataConnection.cs
* Data\DataConnection.Extensions.cs
* Data\DataConnection.Linq.cs
* DataProvider\DataProviderBase.cs
* Linq\Expressions.cs
* Sql\Sql.cs
* ProviderName.cs

I created  the following files:

* DataProvider\AS400\AS400BulkCopy.cs
* DataProvider\AS400\AS400DataProvider.cs
* DataProvider\AS400\AS400Factory.cs
* DataProvider\AS400\AS400IdentifierQuoteMode.cs
* DataProvider\AS400\AS400MappingSchema.cs
* DataProvider\AS400\AS400Merge.cs
* DataProvider\AS400\AS400SchemaProvider.cs
* DataProvider\AS400\AS400SqlBuilder.cs
* DataProvider\AS400\AS400SqlOptimizer.cs
* DataProvider\AS400\AS400Tools.cs
* DataProvider\AS400\AS400TypeCreators.cs
* DataProvider\AS400\AS400Types.cs

**Comment by Coreinsanity** [comment]
Hey, thanks for this.

I'm not all that familiar with pull requests either, honestly. I'm looking into what all you changed and seeing how it works, and I can look into helping you create a pull request as well if you're still interesting. 

I'm pretty sure to create one you have to fork the repo on git, then make your changes, push them to your repo, and then in the github UI somewhere there's a pull request you can issue back to this repo. But I've never done  it, so I'm not 100% sure.

**Comment by Coreinsanity** [comment]
Alright, so, after inspecting the files for a while I found all the spots you changed. Wasn't as hard as I thought it'd be. It looks like I've got it working based on the master branch. Going to test it a bit more.

**Comment by tb-mtg** [comment]
pull request https://github.com/linq2db/linq2db/pull/462 has been created for this

**Comment by ili** [comment]
@tb-mtg can we close it? BTW, where can i find provider you'v implemented?

**Comment by sdanyliv** [comment]
https://github.com/LinqToDB4iSeries/Linq2DB4iSeries
