### ISSUE TITLE
Use strng.Equals in Linq2Db

### ISSUE THREAD

**Issue by JTrotta** [linq2db/linq2db#2210]
Are you sure you can do this with linq2db ?:
`where ur.Slug.Equals(slug, StringComparison.InvariantCultureIgnoreCase)`

UrlRecordService.cs row 1239

```c#
                return _staticCacheManager.Get(key, () =>
                {
                    //load all records (we know they are cached)
                    var source = GetAllUrlRecords();
                    var urlRecords = from ur in source
                        where ur.Slug.Equals(slug, StringComparison.InvariantCultureIgnoreCase)
                        //first, try to find an active record
                        orderby ur.IsActive descending, ur.Id
                        select ur;
                    var urlRecordForCaching = urlRecords.FirstOrDefault();

                    return urlRecordForCaching;
                });
```
I suppose It should be mapped to a new Expression

### Environment details
linq2db version: *last*

**Comment by MaceWindu** [comment]
Wrong repo? UrlRecordService.cs is nopCommerce file

**Comment by MaceWindu** [comment]
BTW, two-parameters string.Equals is not mapped to sql by default (if nopCommerce don't define own mapping), but we have string.Compare mappings

**Comment by JTrotta** [comment]
Sorry, it was for nop...
