### ISSUE TITLE
[Firebird] Can I use firebird's list function?

### ISSUE THREAD

**Issue by konstsch** [linq2db/linq2db#2212]
Can I use firebird's list function?

```
id | text
---------
1  | a
2  | b
3  | c
```

> select list(text, "-") from table

result: a-b-c

**Comment by sdanyliv** [comment]
Yes, we already implemented such functionality along with other providers.
```cs
var value = table.Select(t => t.Text).StringAggregate("-").ToValue();
```
```cs
var query = from t in table
	group t by new {t.Id} into g
	select new
	{
		Values = g.StringAggregate("-", e => e.Text).ToValue(),
	};
```
Full list of examples in our tests.
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/StringFunctionsTests.cs

**Comment by konstsch** [comment]
Thanks! I see it in v2.7.0 and more
