### ISSUE TITLE
Error using linq2db in linqpad6

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2216]
I got this exception using postgres with linqpad6.
For me it seems like an error in linq2db?

![image](https://user-images.githubusercontent.com/364896/81507094-2f865200-92fb-11ea-93a6-14724e105b66.png)

**Comment by jogibear9988** [comment]
Now I switched to linq2db 3 and get this error:

![image](https://user-images.githubusercontent.com/364896/81729518-63dd4800-948c-11ea-8139-0ab972234b1a.png)

problem is, I get the exception in this line of code:
https://github.com/linq2db/linq2db.LINQPad/blob/17b6cb5dcd3730a2dde973cf34c4d7f9ef6fc20b/Source/ProviderHelper.cs#L227

But this line is called 4 times when I attach debugger to linqpad. 3 times it works...

I've no idea anymore atm.

maybe @MaceWindu or @sdanyliv you could help me?

**Comment by jogibear9988** [comment]
Also I break on all exceptions, the exception is still rais at the line 227.
I don't get what could cause this exception at this point.

**Comment by sdanyliv** [comment]
I have no time now to switch. Looks like wrong library dynamically loaded.

**Comment by jogibear9988** [comment]
Thought also about this. I thought maybe a wrong linq2db dll is loaded, but when the excpetion happed, and I looked in the Visual Studio wich I had attached to the process, the dll wich were loaded under "Modules" seem to be the right ones... 
At the Moment I have no Idea any more what could be wrong.
I also used DN-SPY to dig deeper into it, but without luck atm.

**Comment by sdanyliv** [comment]
Probably wrong provider dll is loaded, for example .NET Framework version instead of .NET Standard

**Comment by jogibear9988** [comment]
Thought about this...
But I linked directly to my compiled Version of linq2db in NetStandard2 Folder.
When I got the error I look in VS wihc linq2db dll is loaded under modules. (it's a shadow copy)
Then I looked, and it's the same dll (same size, same date as in the NetStandard Folder of linq2db)
And TestConnection works, wich also uses the DLL...

**Comment by jogibear9988** [comment]
I now updated all Nuget's and switched to linq2db preview Nuget package.
Now I'm back to my previous error....
But don't know what caused the other one...
But I used linq2db master before...

so now error is again:

![image](https://user-images.githubusercontent.com/364896/81771177-94e86780-94e2-11ea-815e-a579f9ad704c.png)

**Comment by jogibear9988** [comment]
@sdanyliv 
Are we missing a cast here: https://github.com/linq2db/linq2db/blob/094548f327c4e44152d1eb43ab2e3e395a28819f/Source/LinqToDB/DataProvider/DynamicDataProviderBase.cs#L44
to IDBConnection?

**Comment by jogibear9988** [comment]
So it looks like this:

		private static Expression<Func<string, IDbConnection>> CreateConnectionExpression(Type connectionType)
		{
			var p = Expression.Parameter(typeof(string));
			var l = Expression.Lambda<Func<string, IDbConnection>>(
				Expression.Convert(Expression.New(connectionType.GetConstructor(new[] { typeof(string) }), p), typeof(IDbConnection)),
				p);
			return l;
		}

**Comment by jogibear9988** [comment]
But I could not test....
If I compile again the linq2db dll myself I get the other error...
