### ISSUE TITLE
[Question] PostgreSQL version support?

### ISSUE THREAD

**Issue by KrisPetkov** [linq2db/linq2db#2217]
I have a quick question in regards to the PostgreSQL support. I saw in the [official documentation](https://linq2db.github.io/articles/general/databases.html) that the latest support PostgreSQL version is 9.5. Do you have any plans to support newer versions in a foreseeable future? Currently we are using PostgreSQL v12.2  (stable release) for our ASP.NET Core project. We are searching for an ORM to use but we cannot use linq2db if it only support such an old version (almost 5 years already).

Thank you in advance!

### Environment details
Database Provider: *PostgreSQL v12.2*
Operating system: *Linux*
.NET Framework: *.NET Core 3.1*

**Comment by MaceWindu** [comment]
`PostgreSQL.9.5` is a name of provider, wich targets postgresql 9.5+.

We usually add new provider version only when alternative sql syntax introduced for some SQL feature, to generate different sql for new version.

**Comment by KrisPetkov** [comment]
@MaceWindu Thank you for the quick answer! 
So it does mean that we can give it a try as it is a supported version. 

**One last question:** any recommended tutorials for using the linq2db, except the official documentation here, as I am comming from the EF world?

Thank you again!

P.S. I'm closing the issue

**Comment by MaceWindu** [comment]
Don't think we have any actual tutorials. Documentation is not our strong side :smiley:

**Comment by sdanyliv** [comment]
@KrisPetkov, not released yet, but on the way:
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.AspNet
It will only work with latest master sources. Nuget feed: https://dev.azure.com/linq2db/linq2db/_packaging?_a=feed&feed=linq2db%40Local

Also take a look at template projects:
https://github.com/linq2db/linq2db#related-linq2db-and-3rd-party-projects

**Comment by KrisPetkov** [comment]
Hi @sdanyliv 

Thank you for the provided information!
One quick question for the first link that you have send - this will be some kind of a wrapper to add a DI option for the linq2db or there will be and something more related to the Asp.Net Core?
And is there any ETA for release? 
I'm asking because I'm still investigating what will be the effort to replace the EF with linq2db because we are using a clean architecture and repository pattern and I'm trying to figure out if there is going to have some major drawbacks. For now it seems that the time consuming part will be to implement some kind of a migration which will be able to replace the EF migrations because the project is still in an active development and to be able to rapid develop it we are using the code first approach and the auto migrations are really handy at that stage of the project.

**Comment by sdanyliv** [comment]
- Yes it is a DI extensions for Asp.Net.
- linq2db supports only Database First approach, usually migrations are done via FluentMigrator
- I see your comments in nopCommerce, they better know how migrate big project.
