### ISSUE TITLE
[Firebird] I try to get 0 or default using FirstOrDefault

### ISSUE THREAD

**Issue by konstsch** [linq2db/linq2db#2219]
I try to get p2 = 0, but I get null
Before I used v1 of linq2db and I get 0:
```
qf = from p1 in db.BIKEs
let p2 = (from o in db.BIKE_PHOTO where p1.ID == o.BIKE_ID select o.ID).FirstOrDefault()
select new BIKE_PH { BRAND = p1.BRAND, PHOTO_ID = p2 };
```

Then I try this one:
`let p2 = (from o in db.BIKE_PHOTO where p1.ID == o.BIKE_ID select o.ID).FirstOrDefault(a => a == 0)`
But I get p2 = null too...

**Comment by sdanyliv** [comment]
BIKE_PH.PHOTO_ID is int?

Please post your model classes used in this query.
Anyway, I suggest to write query in the following way:
```cs
qf = from p1 in db.BIKEs
let p2 = (from o in db.BIKE_PHOTO where p1.ID == o.BIKE_ID select o.ID).FirstOrDefault()
select new BIKE_PH { BRAND = p1.BRAND, PHOTO_ID = Sql.ToNullable(p2) ?? 0 };
```

**Comment by sdanyliv** [comment]
Closing as answered.
