### ISSUE TITLE
SaveChanges

### ISSUE THREAD

**Issue by KrolikROJER** [linq2db/linq2db#222]
Igor, have any functional like ObjectContext (DbContext).SaveChanges (EF)?
We would like to replace the EF + WCF DataServiсe on Link2DB + WCF DataServiсe, but most are written using a strategy of accumulation changes and commit at the end with same merge.

**Comment by igor-tkachev** [comment]
No, linq2db does not support UnitOfWork approach. You can use CRUD operations instead
http://blog.linq2db.com/2015/05/linq-crud-operations.html

**Comment by jorgearana** [comment]
it is incredible a connector to a DB without save changes. And what is the use of this connect then?

**Comment by pebezo** [comment]
Of course you can save your changes, you just do it a bit differently. There some examples of how on the repo's homepage (readme.md).

The unit of work approach, while convenient in some cases, ends up with slower code. If you look at ORM benchmarks L2DB beats all other ORMs and even most micro-ORMs. This could not be possible with UoW. One common approach is to wrap all your changes in a transaction and write them out as you go. If you absolutely need unit of work, then EF is still there for you. However, in my opinion, with UoW you gain little and give up a lot (performance, clarity).
