### ISSUE TITLE
Cannot initialize connection string if linq2db exists on separate solution project

### ISSUE THREAD

**Issue by panayis** [linq2db/linq2db#2221]
Hi,
   I cannot initialize connection string if linq2db exists on a separate project than the Mvc. This is a Asp .net core website. But, If linq2db exists inside MVC project, then it works fine. Please note that I followed the recommendation for .net core on how to retrieve default connection string from stratup.cs.
Thank you.

[stackoverflow question](https://stackoverflow.com/questions/61858983/linq2db-the-connectionstring-property-has-not-been-initialized)

### Environment details
linq2db version: 2.9.8
Database Server: *SqlServer Express 2016*
Database Provider: *?*
Operating system: *Windows10*
.NET Framework: *.Net Core 3.1*

**Comment by sdanyliv** [comment]
Please show stack trace.

**Comment by panayis** [comment]
StackTrace	"   at System.Data.SqlClient.SqlConnection.PermissionDemand()\r\n   at System.Data.SqlClient.SqlConnectionFactory.PermissionDemand(DbConnection outerConnection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at LinqToDB.Async.AsyncDbConnection.Open()\r\n   at LinqToDB.Data.DataConnection.EnsureConnection()\r\n   at LinqToDB.Data.DataConnection.get_Connection()\r\n   at LinqToDB.Data.DataConnection.CreateCommand()\r\n   at LinqToDB.Data.DataConnection.get_Command()\r\n   at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters, Boolean withParameters)\r\n   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints, Boolean withParameters)\r\n   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()\r\n   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__10`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at CPT.Cms.CmsFrontAppService.GetCmsMenus() in D:\\Dev.WorkSpace\\CPT\\src\\CPT.Application\\Cms\\CmsFrontAppService.cs:line 32\r\n   at Castle.Proxies.CmsFrontAppServiceProxy.GetCmsMenus_callback()\r\n   at Castle.Proxies.Invocations.ICmsFrontAppService_GetCmsMenus.InvokeMethodOnTarget()\r\n   at Castle.DynamicProxy.AbstractInvocation.Proceed()\r\n   at Abp.Domain.Uow.UnitOfWorkInterceptor.InterceptSynchronous(IInvocation invocation)\r\n   at Castle.DynamicProxy.AsyncDeterminationInterceptor.Intercept(IInvocation invocation)\r\n   at Castle.DynamicProxy.AbstractInvocation.Proceed()\r\n   at Abp.Auditing.AuditingInterceptor.InterceptSynchronous(IInvocation invocation)"	string

**Comment by panayis** [comment]
**ConnectionStrings I used:**
  "ConnectionStrings": {
    "Default": "Server=RYZEN\\SQLEXPRESS2016; Database=CPTdb; User=sa; Password=Pr_97616230; Trusted_Connection=True;"
  },
  "ConnectionStrings": {
    "Default": "Server=RYZEN\\SQLEXPRESS2016; Database=CPTDb; Trusted_Connection=True;"
  },

**Linq2DbSettings.cs**
using LinqToDB.Configuration;
using System.Collections.Generic;
using System.Linq;

namespace CPT.Web
{
    public class ConnectionStringSettings : IConnectionStringSettings
    {
        public string ConnectionString { get; set; }
        public string Name { get; set; }
        public string ProviderName { get; set; }
        public bool IsGlobal => false;
    }

    public class Linq2DbSettings : ILinqToDBSettings
    {
        public IEnumerable<IDataProviderSettings> DataProviders => Enumerable.Empty<IDataProviderSettings>();

        private string ConnectionString;
        public string DefaultConfiguration => "SqlServer";
        public string DefaultDataProvider => "SqlServer";
        public Linq2DbSettings(string connectionString)
        {
            this.ConnectionString = connectionString;
        }
        public IEnumerable<IConnectionStringSettings> ConnectionStrings
        {
            get
            {
                yield return
                    new ConnectionStringSettings
                    {
                        Name = "Default",
                        ProviderName = "SqlServer",
                        ConnectionString = ConnectionString
                    };
            }
        }
    }
}

**Comment by panayis** [comment]
It would come easy if you have an example solution Asp.Net Core solution that is using Linq2Db as separate project..

**Comment by sdanyliv** [comment]
Yes please, attach sample project. It is strange.
Also please try 3.0-preview2 version.

**Comment by panayis** [comment]
I did a new asp.net core 3.1 project and another separate project where Linq2Db is used and it is working fine with no problem. Now, the problem with my big project is that the CPT.Web.Mvc project is using the CPT.Application project which is using the CPT.Linq2Db project. So, you see that between the Mvc and Linq project an intermediate project exists. This is why the connectionstring fails to initialize. An ideas how to achieve this? The CPT.Application is an Application Service project which is using Linq2db (and other projects).


![Untitled](https://user-images.githubusercontent.com/5340451/82247240-be741980-994e-11ea-8f38-a9273d50d99a.png)

**Comment by sdanyliv** [comment]
I can only give small troubleshooting suggestion. Set breakpoint on Linq2DbSettings constructor, and analyze when it is created and check ConnectionString parameter.

**Comment by panayis** [comment]
Will do that. Thank you very much indeed!
