### ISSUE TITLE
About UTC and LocalTime Convertion

### ISSUE THREAD

**Issue by huahaiao** [linq2db/linq2db#2229]
hi,there.

I develop my project based on nopCommerce . I have just upgrade it to nop 4.3.
It use linq2db .
I met a error ,on this line:
```cs
return _customerRepository.Table
   .Where(c => c.RegisteredInStoreId == storeId 
       && (DateTime.Now.Date - c.CreatedOnUtc.ToLocalTime().Date) == TimeSpan.FromDays(1))
   .Count();
```
the error is caused by  ToLocalTime() . It's not supported by linq2db.
So How can I fix this problem ? thanks a lot!

**Comment by sdanyliv** [comment]
Which database do you use?

**Comment by sdanyliv** [comment]
Anyway, try this variant:
```cs
return _customerRepository.Table
   .Where(c => c.RegisteredInStoreId == storeId 
       && Sql.DateDiff(DateParts.Day, c.CreatedOnUtc, Sql.CurrentTimestampUtc) == 1)
   .Count();
```

**Comment by huahaiao** [comment]
sql server .
thanks! I will try now.

**Comment by sdanyliv** [comment]
@huahaiao, this approach solves your problem?

**Comment by huahaiao** [comment]
Yes! Thanks a lot!
You are such an extraordinary genius, a good man who is willing to help others!

**Comment by sdanyliv** [comment]
Great, closing than.
If you need some function from SQL Server. Check this folder first, possibly there is already implemented varient. Also it is great example how to extend linq2db.
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/Sql

**Comment by huahaiao** [comment]
I met another problem .that is  In nopCommerce4.3  ,it use linq2db without t2 templates.
so I can't solve the databae default value . 
before, I write like this:

` builder.Property(b => b.CreatedOnUtc).IsRequired().HasDefaultValue();`
It will activate the database defaultvalue: sysutcdatetime()  for the field CreatedOnUtc When I insert an object without set a value to CreatedOnUtc property.

But now , When I insert the object ,   It write a '0001-01-01 00:00:00.0000000' value .
It means the database defaultvalue becomes useless...
btw.
If the project use t4, I know SkipValuesOnInsert will work. But nopCommerce did not use T4

**Comment by huahaiao** [comment]
I met another problem .that is In nopCommerce4.3 ,it use linq2db without T4 templates.
so I can't solve the databae default value .
before, I write like this:

builder.Property(b => b.CreatedOnUtc).IsRequired().HasDefaultValue();
It will activate the database defaultvalue: sysutcdatetime() for the field CreatedOnUtc When I insert an object without set a value to CreatedOnUtc property.

But now , When I insert the object , It write a '0001-01-01 00:00:00.0000000' value .
It means the database defaultvalue becomes useless...
btw.
If the project use T4, I know SkipValuesOnInsert will work. But nopCommerce did not use T4

**Comment by sdanyliv** [comment]
builder.Property(b => b.CreatedOnUtc).HasAttribute(...)
Put SkipOnInsert attribute. Don’t remember name.

**Comment by huahaiao** [comment]
I have no idea how to write in nowaday mapping .
It looks like this:
` public partial class SvApproveBuilder : NopEntityBuilder<SvApprove>
    {
        #region Methods
        public override void MapEntity(CreateTableExpressionBuilder table)
        {
            table
                .WithColumn(nameof(SvApprove.SvId)).AsInt32().ForeignKey<sv>(onDelete: Rule.None)
                .WithColumn(nameof(SvApprove.CustomerId)).AsInt32().ForeignKey<Customer>(onDelete: Rule.None);
         }
        #endregion
    }`
 Where  should I write SkipOnInsert attribute?

I see a method named WithDefaultValue. Can that works? 
maybe like this:
   `table.WithColumn(nameof(SvApprove.CreatedOnUtc).AsDateTime().WithDefaultValue();`

**Comment by sdanyliv** [comment]
Looks like it is not linq2db mapping, but FluentMigrator configuration.
It is two different libraries.
FluentMigrator - responsible for migrations
linq2db - working with data

**Comment by huahaiao** [comment]
I am so sorry for my lack of knowing about these technique.
The use of linq2db in nopCommerce is a little complicated for me. I must study harder ...

**Comment by sdanyliv** [comment]
Looks like nopCommerce uses other mapping technique. How do you access to database from nopCommerce? Via which interface?

**Comment by huahaiao** [comment]
_storeRepository.Update(store);  _storeRepository is a IRepository<Store>
In Nop.Data.EntityRepository<TEntity>, define CRUD Methods, coding like this:
_dataProvider.UpdateEntity(entity);
_dataProvider.DeleteEntity(entity);
_dataProvider.GetTable<TEntity>()
_dataProvider.InsertEntity(entity);
_dataProvider is a INopDataProvider.

then It might call ( I don't know how, BaseDataProvider seems no relation with INopDataProvider):
public abstract class BaseDataProvider
{
        //...
       public TEntity InsertEntity<TEntity>(TEntity entity) where TEntity : BaseEntity
        {
            using var dataContext = CreateDataConnection();
            entity.Id = dataContext.InsertWithInt32Identity(entity);
            return entity;
        }
       //   ...
}

When I press Ctrl+F12 to trace code on " _dataProvider.InsertEntity(entity); ", It will enter the BaseDataProvider. It's quite confusing..

**Comment by sdanyliv** [comment]
Try the following trick, somewhere in initialization
```cs
var ms = Singleton<MappingSchema>.Instance;
var builder = ms.GetFluentMappingBuilder();

builder.Entity<YourEntity>()
   .HasSkipValuesOnInsert(e => e.CreatedOnUtc, default(DateTime));
```

**Comment by huahaiao** [comment]
I strongly suggest that some code should be automatically generated by reading database schema . 
An ORM framework should do this. That is the original purpose of database constraint of default value.

**Comment by sdanyliv** [comment]
It should be done by nopCommerce. They have implemented `FluentMigratorMetadataReader` which has to be improved to handle more cases.
linq2db has about ten different ways how to insert record. Inserting via objects usually needs precise configuration.
