### ISSUE TITLE
What is the meaning of Mapper.QueryRunner field?

### ISSUE THREAD

**Issue by feeleen** [linq2db/linq2db#2244]
Mapper class:

```cs
class Mapper<T>
{
    ...
    public IQueryRunner? QueryRunner;
    ...
}
```

And at the same time QueryRunner always passed to Mapper.Map(..) method as a parameter:
```cs
public T Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
{
    ...
    var qr = QueryRunner;  <--- why not just do qr = queryRunner ?
    ...
}
```
I cant understand this piece of code above..

and there are many peaces of code like this:

```cs

			try
			{
				mapper.QueryRunner = runner;  <--

				using (var dr = runner.ExecuteReader())
				{
					while (dr.Read())
					{
						var value = mapper.Map(dataContext, runner, dr); <--
						runner.RowsCount++;
						yield return value;
					}
				}
			}
			finally
			{
				mapper.QueryRunner = null;  <--
			}

```

Here QueryRunner is always the same runner that passed to Map method

can you clarify the purpose of separate QueryRunner field existance and it's assignment outside of Map method inside try-finally?..

**Comment by MaceWindu** [comment]
Looks like it is legacy code, not refactored during #758 implementation.
