### ISSUE TITLE
Using Npgsql 3.3 or later in Linq2db

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2247]
Hi!

The current Linq2db version is 2.9.8 and built with Npgsql 3.2.5.
The current version of Npgsql is 4.1.3.1. 

**Is it possible to upgrade Npgsql in Linq2db to version 3.3 or later?**
The problem is that Npgsql 3.2 does not work with TransactionScope. 
https://github.com/linq2db/linq2db/issues/1620

As I understand laters versions of Npgsql (from 3.3) already support TransactionScope...

Thank you!

**Comment by sdanyliv** [comment]
Just install latest version of Npgsql from Nuget into your project and linq2db should use that version automatically.

**Comment by AndrePScope** [comment]
Thank you!
