### ISSUE TITLE
Regression in 3.0.0-rc0 - Distinct causes incorrect query translation

### ISSUE THREAD

**Issue by brunolau** [linq2db/linq2db#2252]
Might be related to #2251, but the outcome is different, so posting as a separate issue

Putting .Distinct() to the query and selecting Id column respectively results in incorrect LINQ to SQL translation.

I'm attaching a sample repro that reproduces the problem 
[CrashRepro.zip](https://github.com/linq2db/linq2db/files/4717784/CrashRepro.zip)

Sample program contained in the repro (just to indicate the issue without opening the ZIP file)
```cs
var db = new StrippedDownContext();
LinqToDBForEFTools.Initialize();

var eventId = 8921;
var eventQuery = db.ACL_Entry.Where(p => p.TicketNumber.Ticket.EventId == eventId);
var tnQuery = eventQuery.Select(p => p.TicketNumber).Distinct(); //Without distinct everything seems fine

var idQuery = tnQuery.ToLinqToDB().Select(p => p.Id);
var result = idQuery.ToList();

var sqlText = idQuery.ToString();
```
This outputs following incorrect query...
```sql
--SqlServer.2012
DECLARE @eventId_1 Int-- Int32
SET     @eventId_1 = 8921

SELECT
    [t1].[EventId]
FROM
    (
        SELECT DISTINCT
[a_TicketNumber].[Id],
[a_TicketNumber].[TicketID],
[a_TicketNumber].[LookupId],
[a_Ticket].[EventId]
        FROM
[ACL_Entry][p]
    INNER JOIN[TicketNumber][a_TicketNumber] ON[p].[TicketNumberId] = [a_TicketNumber].[Id]
    INNER JOIN[Ticket][a_Ticket] ON[a_TicketNumber].[TicketID] = [a_Ticket].[Id]
        WHERE
[a_Ticket].[EventId] = @eventId_1
```

**Comment by sdanyliv** [comment]
Will check, looks like `[a_Ticket].[EventId]` in select is not needed. It is problem of this query?

**Comment by brunolau** [comment]
Hi, unfortunately no. The problem is it selects [a_Ticket].[EventId] while it should select [a_TicketNumber].[Id], therefore it queries wrong results

**Comment by sdanyliv** [comment]
Ok, will fix that today. Thanks for reporting.

**Comment by brunolau** [comment]
Thanks. Would there be possibility to release as RC1 and not wait until stable 3.0.0 once fixed?

**Comment by sdanyliv** [comment]
Once i have merged Fix PR into master, CI automatically build Nugets and put them [here](https://dev.azure.com/linq2db/linq2db/_packaging?_a=feed&feed=linq2db%40Local) 
Put attached NuGet.config into your solution folder and you will be able use these packages,
[NuGet.zip](https://github.com/linq2db/linq2db/files/4718296/NuGet.zip)
Just install into your project new version of `linq2db` (select linq2db feed) and `linq2db.EntityFrameworkCore` should use newer package.

**Comment by sdanyliv** [comment]
Anyway if there is no additional problems we will release 3.0 on this or next week.

**Comment by sdanyliv** [comment]
@brunolau, changes already in master. So, you can try how it works.

**Comment by brunolau** [comment]
@sdanyliv All unit tests in my solution are now passing, I also haven't encountered any other issues while testing yet...so far, so good, seems like it's all tuned up

**Comment by sdanyliv** [comment]
@brunolau, what i'm interesting how ChangeTracker support works. I have implemented this ability but not created heavy tests.

**Comment by brunolau** [comment]
Is it the standard ChangeTracker of EF Core [when wired via L2DB EF Core package], or does L2DB have a native ChangeTracker now ?

**Comment by sdanyliv** [comment]
It is standard EF Core ChangeTracker. Latest version of linq2db.EntityFrameworkCore, registers objects in EF Core ChangeTracker, so they can be modified via standard SaveChanges mechanism.

**Comment by brunolau** [comment]
OK, will try and let you know

**Comment by sdanyliv** [comment]
I’m worrying about massive Include queries and how relations between entities are registered. Anyway `Include/ThenInclude` should be fast as a beast.
