### ISSUE TITLE
SkipValuesOnUpdate/Insert at class level

### ISSUE THREAD

**Issue by Quentinb** [linq2db/linq2db#2254]
Would it be possible to apply the SkipValuesOnUpdate and SkipValuesOnUpdate attribute at class level? Currently it is only effective at member level, but when applying a path-based Column attribute on a complex member, SkipValuesOnUpdate cannot be applied.

For example, if I supply only the customer name and not surname, I want to skip the surname field being updated to a null in the below model:
```cs
[Table("tbl_customer")]
[Column("customer_name", "Customer.Name"), SkipValuesOnUpdate(null) <-- cannot be applied 
[Column("customer_surname", "Customer.Surname"), SkipValuesOnUpdate(null) <-- cannot be applied here]
public class SomeModel
{
   ...
   [NotColumn, SkipValuesOnUpdate(null) <-- has no effect here]
   public CustomerModel Customer { get; set; }
}
```
this is based off the example here -> https://github.com/linq2db/linq2db/blob/master/Tests/Model/ComplexPerson.cs

**Comment by sdanyliv** [comment]
What can I say. PR is welcome. We have no time to prioritize this request now.
`SkipValuesOnUpdate` is contributor's feature which do not cover all possible situations.

**Comment by feeleen** [comment]
@Quentinb 
Have you tried new "column filter" feature in Update method to update only changed class members?.. (to use this feature, you should also implement some change tracking for your classes, for example https://github.com/feeleen/POCOChangeTracker. 
Or just hardcode column filter parameter when updating your class)

**Comment by Quentinb** [comment]
@sdanyliv happy to do a PR :)
@feeleen looks interesting, thanks, will check it out.

**Comment by Quentinb** [comment]
I've spent some time on getting this to work and going through the code and have managed to get it to work without needing to change any code in Linq2DB itself.

The quick fix is to apply the `SkipValuesOnUpdate` on the actual sub-class members. i.e:

```cs
[Table("tbl_customer")]
[Column("customer_name"     , "Customer.Name")]
[Column("customer_surname", "Customer.Surname")]
public class SomeModel
{
   [NotColumn]
   public CustomerModel Customer { get; set; }
}

public CustomerModel
{
   [SkipValuesOnUpdate(null)]
   public string Name { get; set; }

   [SkipValuesOnUpdate(null)]
   public string Surname { get; set; }
}
```

**Comment by sdanyliv** [comment]
Great, it is much better than extending API.
