### ISSUE TITLE
SQL Server's MS_Description is ignored on stored procedures and functions

### ISSUE THREAD

**Issue by antonKrouglov** [linq2db/linq2db#2256]
Linq2db seems to ignore descriptions attached to stored procedures, functions and their parameters. I would expect it to generate /// comments. On the contrary MS_description extended properties are respected on at least table columns.

Is it technically possible to extend SqlServerSchemaProvider.cs and LinqToDB.SqlServer.ttinclude in such as way that MS_description will be put into /// comments?

**Comment by sdanyliv** [comment]
Technically yes ;)
Would you like to do that yourself and create PR? It will be appreciated and you will have this feature faster.

**Comment by antonKrouglov** [comment]
I will try to do it. I would also like to write an option to represent stored procedures as C# classes. That is more flexible easy to use in cases when SP has lots of parameters.
