### ISSUE TITLE
Oracle: Need to dispose command parameters but also their values when disposing command

### ISSUE THREAD

**Issue by SergeyA** [linq2db/linq2db#226]
https://community.oracle.com/thread/2279050
https://fromthefiefdom.wordpress.com/2011/08/26/what-to-dispose-in-oracle-odpnet/

Недавно столкнулись с крешами пула asp.net, источник которых находится где то глубоко внутри oracle odp.net. Исследования показали, что с таким поведением столкнулись не только мы. По ссылкам выше приводятся слова службы поддержки Oracle о том, что нужно диспозить не только команду, но и все ее параметры и их значения. Люди пишут, что причина падений в этом.

fix:
file: C:\Projects\linq2db\Source\Data\DataConnection.cs:551

    public void DisposeCommand()
    {
        if (_command != null)
        {
            foreach (var param in _command.Parameters)
            {
                DisposeParameter(param);
            }

            _command.Dispose();
            _command = null;
        }
    }

    private void DisposeParameter(object param)
    {
        if (param == null)
            return;

        // возможно стоит обернуть в try/catch
        var dbParam = param as System.Data.Common.DbParameter;
        if (dbParam != null && dbParam.Value != null && dbParam.Value is IDisposable)
            ((IDisposable)dbParam.Value).Dispose();

        if (dbParam is IDisposable)
            ((IDisposable)dbParam).Dispose();
    }

tags: w3wp exception 0xc0000374 odp.net

**Comment by jogibear9988** [comment]
why should I dispose the Value? it can still be used in other parts of the program!

**Comment by SergeyA** [comment]
Ok, I think that disposing only parameters will be enough. But it must be done, do you agree?

**Comment by jogibear9988** [comment]
If the Oracle Dokumentation says so, I think it's ok, but the value not!
