### ISSUE TITLE
*Not really an issue

### ISSUE THREAD

**Issue by os1r1s110** [linq2db/linq2db#2261]
This it not really an issue, it's a continuation of a discussion [here](https://github.com/dotnet/efcore/issues/21134)

### Steps to reproduce
Here is the goal of the query I'm trying to generate and why I was initially using CTE.

When test results are updated for a given equipment, I need to reprocess them with previous results on the same equipment to compute rates of changes between results (also need to check if there are more recent results for the same equipment as their respective rates of change will also be affected by changing the "current" results).

Here is the query I'm using (put in context with the table below)
```C#
var queryResult = await _dbContext.TestResults.FromSqlRaw($@"
    WITH equipmentResults AS
    (
        SELECT ROW_NUMBER() OVER (Order BY EquipmentId, TestDate) AS rn
        , *
        FROM dbo.TestResults
        WHERE EquipmentId IN (1,2)                            
    ),
    relatedRowNumbers AS 
    (
        SELECT
        rn AS currentResultRN,
        rn+1 AS nextResultRN
        from equipmentResults
        WHERE Id IN (4,10)
    )
    SELECT * from equipmentResults
    WHERE rn IN (select currentResultRN from relatedRowNumbers) OR rn IN (select nextResultRN from relatedRowNumbers)")
.ToListAsync();
```

To accomplish this I do the following:

First create a list of all the equipment for which results have been updated since last rate compute task has run. This list is used as a parameter to the 1st CTE, which returns me a list containing all the test results of all the specified equipment (in the example equipment with id 1 and 2).

Once I have this list, I then need to find the specific rows for which results have been updated, and then go on to find their adjacent rows (results are also sorted by date in 1st CTE). This is what the 2nd CTE is used for (attributing row numbers (here the window function could be beneficial I guess)

Here is an example result table after running 1st CTE, in which I identified the rows that I need to retrieve in the final result (and for which I used the 2nd CTE and final SELECT clause). So at the end, EF would need to return rows with rn in (3,4,5,9,10,11) or ResultsRowId in (3,4,5,54,108,109) if not using second CTE

Rn | EquipmentId | ResultsRowId | Date Updated | Note
-- | -- | -- | -- | --
1 | 1 | 1 | 2020-06-05 |  
2 | 1 | 2 | 2020-06-06 |  
3 | 1 | 3 | 2020-06-07 | Previous relative to 1st
4 | 1 | 4 | 2020-06-08 | 1st results row updated
5 | 1 | 5 | 2020-06-09 | Next (relative to 1st)
6 | 2 | 28 | 2020-06-10 |  
7 | 2 | 29 | 2020-06-11 |  
8 | 2 | 31 | 2020-06-12 |  
9 | 2 | 54 | 2020-06-13 | Previous
10 | 2 | 108 | 2020-06-14 | 2nd results row updated
11 | 2 | 109 | 2020-06-15 | Next
12 | 2 | 111 | 2020-06-16 |  
13 | 2 | 112 | 2020-06-17 |  

### Environment details
linq2db version: None yet :)
Database Server: SQL Server
Database Provider: MS SQL Server
Operating system: Windows 10
.NET Framework: .net core 3.1

**Comment by sdanyliv** [comment]
@os1r1s110, from start post here Equipment class and which property you need to test in your algorithm.
Forget about CTE, just explain what we have to calculate.

**Comment by os1r1s110** [comment]
Okay so here is a simpler repro I just made for the needs of this question, I included both the Equipment table at its simplest form, and an example of the results table replicates the real one (having json fields containing the results of each test)
```C#
public class Equipment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string Manufacturer { get; set; }

        /// <summary>
        /// Represents all the test results sets related to this equipment
        /// </summary>
        public List<TestResults> TestResults { get; set; } = new List<TestResults>();
    }

public class TestResults
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public Equipment Equipment { get; set; }

        [JsonField]
        public SingleTestResultsTemplate Test1Results { get; set; }
        [JsonField]
        public SingleTestResultsTemplate Test2Results { get; set; }
        [JsonField]
        public SingleTestResultsTemplate Test3Results { get; set; }

        public DateTime? TestDate { get; set; }

        /// <summary>
        /// Even though different tests are performed on the equipment, all of them share some properties together, which are defined by the SingleTestResultsTemplate class
        /// </summary>
        public class SingleTestResultsTemplate
        {
            public double? Result { get; set; }
            public double? RateOfChange { get; set; }
            public double? Increment { get; set; }
            /// <summary>
            /// This represents the last set of results used to compute the rates of change and increments/decrements for this specific result
            /// </summary>
            public int? LastComparedWith { get; set; }
        }
    }
```

**Comment by sdanyliv** [comment]
TestResults is a table?

**Comment by os1r1s110** [comment]
Yes it is, here is a detailed example of what's expected at the end.

Let's say the results table would contain these entries:
![image](https://user-images.githubusercontent.com/1885400/83948569-1a162200-a7ec-11ea-9672-ecee0547845c.png)

In this table, each row represents a point in time where tests were performed on the specified equipment. Now let's suppose we just edited results for rows with id 71 and 75, I would then need to go in the db and find their "relative past and next test results sets" so that I can then compute the rates of changes for each of the specific `TestResults` variable

**Comment by sdanyliv** [comment]
If understand correctly, you need Previous Test result id, and Next test result, based on particular test id, for example 71 - it is 70 and 76. That's correct?

**Comment by os1r1s110** [comment]
Yes that is correct, and I need these "groups" of ids for each of the edited test results sets. So in the example above, both sets with id 71 and 75 would have been updated and I would need to retrieve all highlighted rows to be able to compute the rates of change/increments/decrements between the results of the different sets. (that would be split it 2 groups of 2-3 items as one of them doesn't have a more recent test results set)

**Comment by sdanyliv** [comment]
This query is written using linq2db. And it returns needed values. Then you can join to this query using ids from this query:
```cs
var adjacent = 
   from tr in _context.TestResults
   where tr.Id == 71 // or contains
{
    PrevId = Sql.ToNullable(Sql.Ext.Lag(e => e.Id).Over().PartitionBy(e.EquipmentId).OrderBy(e.TestDate)).ToValue(),
    CurrentId = e.Id,
    NextId = Sql.ToNullable(Sql.Ext.Lead(e => e.Id).Over().PartitionBy(e.EquipmentId).OrderBy(e.TestDate)).ToValue(),
}
```

**Comment by os1r1s110** [comment]
hmmm... doesn't compile

**Comment by sdanyliv** [comment]
Missed few parameters, updated

**Comment by os1r1s110** [comment]
![image](https://user-images.githubusercontent.com/1885400/83949041-8c3c3600-a7ef-11ea-9c87-be4968fd87d2.png)

**Comment by sdanyliv** [comment]
Updated

**Comment by os1r1s110** [comment]
![image](https://user-images.githubusercontent.com/1885400/83949116-08cf1480-a7f0-11ea-9bbc-fd7c300ef28f.png)
I'm currently trying to figure out what this error is about

**Comment by sdanyliv** [comment]
Missed closing parentheses.

**Comment by os1r1s110** [comment]
No you did not miss them, they were just placed after the `OrderBy` instead of the `ToValue()` call and there was a small typo (`e.Id` instead of `tr.Id` on line 2 within the `where` clause)
Final query:
```C#
var adjacent =
    from tr in _dbContext.TestResults
    where tr.Id == 71
    select new
    {
        PrevId = Sql.ToNullable(Sql.Ext.Lag(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
        CurrentId = tr.Id,
        NextId = Sql.ToNullable(Sql.Ext.Lead(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
    };
```

I will test it right away :)

**Comment by os1r1s110** [comment]
When running this, I obtain an error `LinqException: 'Lag' is server-side method.`

**Comment by sdanyliv** [comment]
How do you run this?

**Comment by sdanyliv** [comment]
Let me check. In 5 minutes.

**Comment by os1r1s110** [comment]
I have created a small repro project, I will share it won't be long just let me a couple minutes to publish on github (it's not clean as I'm using the index razor page to execute this code by laziness ahah, but it works to test :) )

**Comment by sdanyliv** [comment]
My fault. You have to call `ToLinqToDB()` before entities materialization.
```cs
adjacent = adjacent.ToLinqToDB();
foreach (var item in adjacent)
{
     var value = item.CurrentId;
}
```

**Comment by os1r1s110** [comment]
oh I didn't know that lol, I will test it in a couple minutes, quick lunch first :)

Thanks for your help no matter what ahah!

**Comment by sdanyliv** [comment]
`ToLinqToDB()` is the core of our extension usage. It replaces EF Core's LINQ translator completely.
It is called automatically if you use our extensions, like `AsCte` but if it is the pure query, at least once in query it should called.

This also should work:
```cs
var adjacent =
               from tr in _dbContext.TestResults.ToLinqToDB()
               where listOfUpdatedEntriesId.Contains(tr.Id)
               select new
               {
                   PrevId = Sql.ToNullable(Sql.Ext.Lag(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
                   CurrentId = tr.Id,
                   NextId = Sql.ToNullable(Sql.Ext.Lead(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
               };
```

**Comment by os1r1s110** [comment]
What's the namespace for the `ToLinqToDB`? compiler doesn't find it

**Comment by sdanyliv** [comment]
namespace is `LinqToDB.EntityFrameworkCore`

**Comment by os1r1s110** [comment]
Hmmm. gives wrong results
--> 
![image](https://user-images.githubusercontent.com/1885400/83950720-e4c50080-a7fa-11ea-8ef8-6694923f4f93.png)

**Comment by sdanyliv** [comment]
I see, try this one:
```cs
var adjacent =
               from tr in _dbContext.TestResults.
               select new
               {
                   PrevId = Sql.ToNullable(Sql.Ext.Lag(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
                   CurrentId = tr.Id,
                   NextId = Sql.ToNullable(Sql.Ext.Lead(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
               };

var filtered = adjacent.Where(tr => listOfUpdatedEntriesId.Contains(tr.Id))
var filtered = filtered.ToLinqToDB().ToArray();
```

**Comment by os1r1s110** [comment]
Would expect it to be:`
1. Prev = 70, Current = 71, Next=76
2. Prev = 72, Current = 75, Next = null

**Comment by sdanyliv** [comment]
If it works, try to limit `adjacent` recordset to avoid full table scan, for example by TestDates or known EquipmentId.

**Comment by sdanyliv** [comment]
Updated

**Comment by os1r1s110** [comment]
Still not quite there yet....
![image](https://user-images.githubusercontent.com/1885400/83951155-8a796f00-a7fd-11ea-8d8e-4e739943ae85.png)

**Comment by sdanyliv** [comment]
Show me generated SQL. 
```cs
var sql = filtered2.ToString();
```

**Comment by os1r1s110** [comment]
```SQL
SELECT
	LAG([tr].[Id]) OVER(PARTITION BY [tr].[EquipmentId] ORDER BY [tr].[TestDate]),
	[tr].[Id],
	LEAD([tr].[Id]) OVER(PARTITION BY [tr].[EquipmentId] ORDER BY [tr].[TestDate])
FROM
	[TestResults] [tr]
WHERE
	[tr].[Id] IN (71, 75)

```

**Comment by sdanyliv** [comment]
Add `AsSubquery()`
```cs
var adjacent =
               from tr in _dbContext.TestResults.
               select new
               {
                   PrevId = Sql.ToNullable(Sql.Ext.Lag(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
                   CurrentId = tr.Id,
                   NextId = Sql.ToNullable(Sql.Ext.Lead(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
               };

var filtered = adjacent.AsSubquery().Where(tr => listOfUpdatedEntriesId.Contains(tr.CurrentId));
var filtered = filtered.ToLinqToDB().ToArray();
```

**Comment by os1r1s110** [comment]
The last one worked (with some minor typo corrections). 

As for 

> If it works, try to limit adjacent recordset to avoid full table scan, for example by TestDates or known EquipmentId
How would I go about it? I would specify a `Where` after the partition by?

**Comment by sdanyliv** [comment]
Exactly or just `where` LINQ syntax

**Comment by os1r1s110** [comment]
Ok, so once I get all these groups of ids, then I can query the `TestResults` table to actually fetch the information from these rows and perform the calculations (with change tracking as this query can be done via EF), correct? So essenitally I would just need to aggregate all the ids together in a single list to query the db (and take only distinct ids as they could overlap eachother in some cases)

**Comment by sdanyliv** [comment]
Something like that. You have query which returns what you need use it for continuous calculations or queries.
About ChangeTracker. This particular query has nothing with change tracker.

**Comment by os1r1s110** [comment]
Yes i know, I just noticed on the docs of linq2db that it does not include any change tracking, so I just said that if I want it, I can use a second query performed via EF Core, with the results from this one, which will provide change tracking as normal.

Thanks for your help, it's been incredibly useful! I will certainly take a closer look to the `LAG` and `LEAD` functions

**Comment by sdanyliv** [comment]
Latest version of `linq2db.EntityFrameworkCore` registers entities in ChangeTracker. But they should be fine grained EF entities ;)

Anyway I have an idea how to automatically collect needed EquipmentId
```cs
var targetEqIds = _dbContext.TestResults
     .Where(tr => listOfUpdatedEntriesId.Contains(tr.CurrentId))
     .Select(tr => tr.EquipmentId)
     .Distinct();

var adjacent =
    from tr in _dbContext.TestResults
    join e in targetEqIds on tr.EquipmentId equals e.EquipmentId
    select new
    {
        PrevId = Sql.ToNullable(Sql.Ext.Lag(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
        CurrentId = tr.Id,
        NextId = Sql.ToNullable(Sql.Ext.Lead(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
    };

var filtered = adjacent.AsSubQuery().Where(tr => listOfUpdatedEntriesId.Contains(tr.CurrentId));
var filtered2 = filtered.ToLinqToDB().ToArray();
```

**Comment by os1r1s110** [comment]
^Yup what you have proposed is exactly what I was doing previously (when using CTE, see other thread) that is fetching the equipment ids in a first query, and then using that to fetch the test results. 

That's a good way to do it I think, is your solution doing it in a single roundtrip to db though?  (if so, it would be even better that what I was doing)

**Comment by sdanyliv** [comment]
It is fastest solution, believe me. We have used full power of Database engine. Just ensure that table `TestResults` has non unique index on `EquipmentId`.

**Comment by os1r1s110** [comment]
It has effectively (not in the small repro I provided but in my real db there are multiple indexes, one of which is on the EquipmentId).

Now I only have to group all these ids in a single list and I'll be ready to go ahah! Thanks again for your help, it was really appreciated!

**Comment by sdanyliv** [comment]
You are welcome. Read something about window functions, they do a lot of interesting things.

Closing then. You know what to do when EF fails to do it's job.

**Comment by sdanyliv** [comment]
@os1r1s110, keep in mind that, if something can be done via single SQL query, even update/delete, modify single JSON field - it can be expressed by linq2db's LINQ extensions.

**Comment by os1r1s110** [comment]
yeah that's pretty sweet! I will also have to spend some time learning more about SQL ins and outs to create better queries when the situation is more complex than simple select statements ahah :) 

I will try to see if I can convert the queries above to directly return the rows instead of only their ids (though I'm not entirely sure  I want to do it like this as I'll lose change tracking)

**Comment by sdanyliv** [comment]
It is easy:

```cs
var targetEqIds = _dbContext.TestResults
     .Where(tr => listOfUpdatedEntriesId.Contains(tr.Id))
     .Select(tr => tr.EquipmentId)
     .Distinct();

var adjacent =
    from tr in _dbContext.TestResults
    join e in targetEqIds on tr.EquipmentId equals e
    select new
    {
        PrevId = Sql.ToNullable(Sql.Ext.Lag(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
        CurrentId = tr.Id,
        NextId = Sql.ToNullable(Sql.Ext.Lead(tr.Id, Sql.Nulls.None).Over().PartitionBy(tr.EquipmentId).OrderBy(tr.TestDate).ToValue()),
    };

var filtered = adjacent.AsSubQuery().Where(tr => listOfUpdatedEntriesId.Contains(tr.CurrentId));

var entitiesQuery = 
   from ids in filtered
   from tr in _context.TestResults.InnerJoin(tr => tr.Id == ids.PrevId || tr.Id == ids.CurrentId || tr.Id == tr.NextId)
   select tr;

// here TestsResult entities should automatically added to ChangeTracker
var entities = entitiesQuery.ToLinqToDB().ToArray();
```

**Comment by os1r1s110** [comment]
The query seems to work but I get a conversion error (probably due to the JSON fields)

"Cannot convert value '{"Result":1306.943548520535,"RateOfChange":null,"Increment":null,"LastComparedWith":null}' to type 'WebApplication1.Models.TestResults+SingleTestResultsTemplate"

**Comment by sdanyliv** [comment]
Oh, yes, we have limitations. Currently we do not support entity property value conversion.
But it's easy to solve.
ONCE per application.
```cs
MappingSchema.Default.SetConverter<string, SingleTestResultsTemplate>(str => 
   // do Newtonsfoft deserialization here
)
```

**Comment by os1r1s110** [comment]
So that's done at app initialization?

**Comment by sdanyliv** [comment]
Yes, good place. I'll find time to support properties convertors, but it is not simple task.

**Comment by os1r1s110** [comment]
Well I must say it seems like a great package already hehe :)

**Comment by sdanyliv** [comment]
We know, that's why we improve library day by day. It helps in creating a much complex queries. Yesterday I have generated SQL in 15 screen pages. I can not imagine how much time I had to spend to do similar task via text editor.
