### ISSUE TITLE
How to deserialize a json column

### ISSUE THREAD

**Issue by rgustavsson** [linq2db/linq2db#2263]
Appologies if I've missed the docs but I've looked at the FAQ and had a glance at historic issues and questions about deserializing data from JSON columns but I simply haven't been able to find any good examples of how to work with such fields. Unit tests point to simples inserts but I'm wondering how to work with deserializing,

I'd like to store a list of objects as JSON in a datatype == json column.
And so if my class (corresponds to a row) looks like this:
```
public class MyRow {
   public string Name { get; set; }
   [Column(DataType = LinqToDB.DataType.Json)]
   public List<TranslationModel> MyJsonObject { get; set; }
}
```
how would I deserialize the "MyJsonObject" property?
I can insert the above to the database via db.Insert (and db.Update) but when I want to fetch and deserialize from the database I get the error message:

```
InvalidCastException: Invalid cast from 'System.String' to 'System.Collections.Generic.List`1[[Common.Models.Translation.TranslationModel, Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'.
```

I think I need to make use of a converter but I don't know if I need one, two or three, or how they would look like.

### Environment details
linq2db version: linq2db.PostgreSQL 2.9.7
Database Server: Postgresql (pgAdmin 4.16
.NET Framework: .NET CORE 3.1

**Comment by sdanyliv** [comment]
Somewhere in Startup:
```cs
MappingSchema.Default.SetConverter<string, List<Model>>(
  str => JsonConvertrer.Deserialize<List<Model>>(str));

MappingSchema.Default.SetConverter<List<Model>, DataParameter>(
  list => new DataParameter("", JsonConvertrer.Serialize(list)));
```

**Comment by rgustavsson** [comment]
@sdanyliv Many thanks, works like a charm! 👍 👯

**Comment by itmay** [comment]
Should I do similiar with JsonDocument from System.Text.Json? I'm using Npgsql. It has built-in support for JsonDocument (https://github.com/npgsql/npgsql/pull/2589). How should I map JsonDocument in Linq2Db?

**Comment by sdanyliv** [comment]
With latest version linq2db, we have introduced value converters
https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273

Which type do you have in model?

**Comment by itmay** [comment]
I saw it. It nice feature.

I would like to use JsonDocument or JsonElement as type of property in my model.

**Comment by sdanyliv** [comment]
Please create separate issue for that.
