### ISSUE TITLE
Subquery on left join

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db#2267]
Hi, 
Using same tables as in this issue:
https://github.com/linq2db/linq2db/issues/2199

```
var man1 = from e in _context.GetTable<Manufacturer>()
                               join c in _context.GetTable<Country>() on e.CountryCode equals c.Code into ce
                               from co in ce.DefaultIfEmpty()
                               where e.ManufacturerId == 1
                               select new Manufacturer { ManufacturerId=e.ManufacturerId, CountryCode=e.CountryCode,Name=e.Name,CountryEntity=co};
```

This expression generates this query:

```
SELECT
	[e].[ManufacturerId],
	[e].[CountryCode],
	[e].[Name],
	[t1].[co],
	[t1].[Name],
	[t1].[is_empty]
FROM
	[Manufacturer] [e]
		LEFT JOIN (
			SELECT
				[ce].[Code] as [co],
				1 as [is_empty],
				[ce].[Name]
			FROM
				[Country] [ce]
		) [t1] ON [e].[CountryCode] = [t1].[co]
WHERE
	[e].[ManufacturerId] = 1

```

This same query, when used with inner join generates better query:

```
SELECT
	[e].[ManufacturerId],
	[e].[CountryCode],
	[e].[Name],
	[c_1].[Code],
	[c_1].[Name]
FROM
	[Manufacturer] [e]
		INNER JOIN [Country] [c_1] ON [e].[CountryCode] = [c_1].[Code]
WHERE
	[e].[ManufacturerId] = 1
```
We already talked about this and you said it might be fixed with latest pr, but it wasn't.

Almost all of our queries are with left joins. 
Some queries have 20 joins where most of the table have over 20 columns.
In that case, generated query is more than double in size than compared with the one generated by EF.

For one of our bigger queries, Linq2Db version is 30KB and EF is 15KB.
I could send you and example, but even from this example, it's evident what is the problem.

Because of this, there is a much bigger payload to transfer to SqlServer, but it is also slower to parse for the first time. So, although Linq2Db is subsequently faster than EF, first execution is much slower. 

We discused about this in case 
https://github.com/linq2db/linq2db/issues/2205

I'm willing to try to implement this if you could point me in right direction, but from my perspective, there shouldn't be any difference between left and inner join generation of subquery.

### Environment details
linq2db version: 3.0.0.rc0
Database Server: SqlServer 2016
Database Provider: MicrosoftDataSqlClient
Operating system: Windows 10
.NET Framework: .Net Core 3.1.5

**Comment by sdanyliv** [comment]
`Country` table has PK defined?

**Comment by sdanyliv** [comment]
Country table has not nullable columns?

**Comment by Marka83** [comment]
This was just an example. I suppose Name is nullable because I didn't specify it is required.

**Comment by Marka83** [comment]
But in our code, we use almost all properties as nullable.
But that shouldn't be a reason to generated this kind of query.

**Comment by Marka83** [comment]
This "[is_empty]" looks suspicious to me.
Why do you generated it?
It is a constant that you use in final projection.

**Comment by sdanyliv** [comment]
That't is a problem. When you do LEFT JOIN we need information that record was successfully found when generating projection. If your table has no at least one NOT Nullable column - we add constant `1` to ensure that join was successful.

**Comment by sdanyliv** [comment]
It is works for 99% of queries. But in your schema Primary Key is a nullable colun. Why? As i know SqlServer do not allow nullable Primary Key,

**Comment by Marka83** [comment]
Well, I have pk columns. They can't be null. 
It doesn't matter if property in class is nullable (we do it for some other purposes)
It can't be null on database side.

**Comment by sdanyliv** [comment]
linq2db should know that at least one column is not nullable. I think you have to correct your metadata reader and queries will be optimized better.

**Comment by Marka83** [comment]
Is it ok to just specify it is required field?

**Comment by Marka83** [comment]
I'll try to map it in my custom MetadataReader.
I can't be 100% sure, but I think that in EF, by specifying [Key] attribute, it's automatically implied that property is not null.

**Comment by sdanyliv** [comment]
linq2db does not support `Required` attribute. 
Paste here your Metedata Reader and i'll give you advise,

**Comment by Marka83** [comment]
I already fixed it.
I set this:
"CanBeNull = !required && !key"

One more unrelated thing: How can I pregenerate metadata about entities at the start of application?

**Comment by sdanyliv** [comment]
> How can I pregenerate metadata about entities at the start of application?

If you have Metadata Reader. Just create single instance of MappingSchema whith this metadata reader and reuse it in every DataConnection. Entity information will be cached automatically when used first time.
```cs
  var new DataConnection(mappingSchema);
// or
  var dc = new DataConnection();
  dc.AddMappingSchema(mappingSchema);
```

**Comment by Marka83** [comment]
Thanx, I'll try it.

**Comment by sdanyliv** [comment]
So, we have found root of your problems? Issue can be closed?

**Comment by Marka83** [comment]
Yes. You can close it.
I just had to modify Metadata reader a little.
Thank you for your help.

**Comment by sdanyliv** [comment]
@Marka83, i have significantly improved query generation speed for the next version. And it is not a limit we can do better, will find time to refactor slow parts,

**Comment by Marka83** [comment]
It's always nice to have free performance upgrade :D

**Comment by Marka83** [comment]
Also, we migrated whole application and I must say I'm really pleased who it performs even at this moment.

**Comment by sdanyliv** [comment]
This improvement is valuable for really big queries, staring from 10 joins. Anyway it is general optimization and may speedup everything.

Glad to hear that your application works better with linq2db. Working hard to make library fast and valuable.
