### ISSUE TITLE
PostgreSQL Identity field must be defined

### ISSUE THREAD

**Issue by KrisPetkov** [linq2db/linq2db#2268]
I have a mapping table (named User_UserRole_Mapping) with two fields User_Id(PK) and UserRole_Id(PK)
For insertion I'm using **InsertWithInt32Identity** method.
If I try to insert new object of type my mapping table (UserUserRoleMapping) I'm getting the following error: **SqlException: Identity field must be defined for 'User_UserRole_Mapping'**.

This error happens when I'm using PostgreSQL as a database, but if I'm using MS SQL everything works as it suppose to work.
I have found the reason for this error and it can be seen here: https://github.com/linq2db/linq2db/blob/7528b9edc33d3e545443c5bc5c4aca4ab966af3a/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs#L45

Is it possible this check to be changed so it can work as it works in MS SQL?

This is how MS SQL handles this situation: https://github.com/linq2db/linq2db/blob/7528b9edc33d3e545443c5bc5c4aca4ab966af3a/Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs#L167

### Environment details
linq2db version: 2.9.8
Database Server: PostgreSQL v12.2
Operating system: Windows 10
.NET Framework: .NET Core 3.1.

**Comment by sdanyliv** [comment]
What is the problem to mark one field as [Identity] ?

**Comment by KrisPetkov** [comment]
Well, it will be a workaround and I don't know if it is OK, to have a column that is not actually identity to be marked as such.

If I have the following situation:
| User_Id  | UserRole_Id |
| ------------- | ------------- |
| 1  | 1  |

And User_Id is marked as Identity will I be able to insert a new row (1, 2) and have the following data at the end:

| User_Id  | UserRole_Id |
| ------------- | ------------- |
| 1  | 1  |
| 1  | 2  |

**Comment by sdanyliv** [comment]
[Identity] in linq2db do the following thing:
- Do not include column in Insert
- Used to identify which columns is Identity column. Especially for Postgres, we need to know which field is GENERATED by DATABASE when you are trying to cal `InsertWithIdentity` to return this value back to the client.

SqlServer
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15

Postgres
https://www.postgresqltutorial.com/postgresql-identity-column/

linq2db do not guarantee anything for uniqueness, it just generate proper SQL.

**Comment by KrisPetkov** [comment]
Ok, but if linq2db does NOT include the marked as [Identity] column than what is the point? I want to insert value x but if it is omitted then will not be inserted.

**Comment by sdanyliv** [comment]
I think you d not need `InsertWithIdentity` function call. Just `Insert` and do not mark columns that are not Database Generated as [Identity].

**Comment by KrisPetkov** [comment]
Yes, I tried this way and it works, but my problem is that I'm using one function for everything (InsertWithIdentity) and I was wondering if there is some workaround or if this check is 100% accurate. 
Otherwise I will have to make additional changes to my logic and to know when to use InsertWithIdentity method and when to not use it.

**Comment by sdanyliv** [comment]
```cs
var ed = db.MappingSchema.GetEntityDescriptor(obj.GetType());
var hasIdentity = ed.Columns.Any(c => c.IsIdentity);
if (hasIdentity)
    return db.InsertWithInt32Identity(obj);
else
{
    db.Insert(obj);
    return -1;
}
```

**Comment by KrisPetkov** [comment]
@sdanyliv great, thank you for the example and the provided information!
I will close the issue.
