### ISSUE TITLE
Add find property at column attribute

### ISSUE THREAD

**Issue by ferbenor** [linq2db/linq2db#227]
hello Mr Igor, i think the possibility of append something like find property for column attribute with the finaly of implement one function that allow execute where expression with the values contents in the sets columns, for example:

```c#
[Column(Storage="_id", IsFind = true, FindOrder = 0), PrimaryKey, NotNull]
public short id // smallint
{
	get { return _id; }
	set { _id = value; }
}

[Column(Storage="_active", IsFind = true, FindOrder = 1), PrimaryKey, NotNull]
public short active // boolean
{
	get { return _active; }
	set { _active = value; }
}
```
----
"ExecWhere(params object[])"
var list = db.table.BuildWhere(1, true).ToList();

Tanks.

**Comment by igor-tkachev** [comment]
1. It make sence only if you generate ExecWhere method.
2. The FindOrder field does not have to be a field of the Column attribute. You can  create new attribute.
3. linq2db T4 template generate Find method for each table using PK info. Is this what your need?

**Comment by ferbenor** [comment]
Thank you for you response, i thought any form to generate the where expression to get all the list, based on the attribute IsFind, but the examples of the wiki in Creating-Generic-CRUD-Class section could be of help to make this.

The Idea is not especify the expression such as "x => x.field == value && x.fiel1.Contains(value)" directly, but i can auto generate the expression with the definition of the mapping, however i could be overwrite the find method for this case.
