### ISSUE TITLE
DataConnection.OnEntityCreated not called

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2274]
Hi,
  I'm trying to use OnEntityCreated event.
  This is my C# code:

``` C#
        private static void Main()
        {
            DataConnection.DefaultSettings = new MySettings();
            Configuration.Sql.GenerateFinalAliases = true;

            using var db = new WipDB("Wip");
            db.OnEntityCreated += (e) => Console.WriteLine(e.Entity.GetType().Name);

            var result = from ncCode in db.NcCode
                         join ncGroupMember in db.NcGroupMember
                         on ncCode.Handle equals ncGroupMember.NcCodeOrGroupGbo
                         where
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_AUTO" ||
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_MAN" ||
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_ALL"
                         select new AllowedNcCodeOutput { NcCodeBo = ncCode.Handle, NcCode = ncCode.NcCodeColumn, NcCodeDescription = ncCode.Description };

            var sql = result.ToString();
            Console.WriteLine(sql);
            var resultItems = result.ToList();
        }
```

  The issue is that `Console.WriteLine(e.Entity.GetType().Name` is never called even if result.ToList() contains more than 7000 items.
  I'm expecting that OnEntityCreated will be raised for each entity of type AllowedNcCodeOutput that is created by the query. Am I wrong?

  Thank you!

### Environment details
inq2db version: 3.0.0-rc.2303
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (3.0.0-rc.2303)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by sdanyliv** [comment]
It should not depend on entity count in any cases. Instead of console output, just count elements.

**Comment by filippobottega** [comment]
**Update:**

If I change the code like this:

``` C#
...
            var result = from ncCode in db.NcCode
                         join ncGroupMember in db.NcGroupMember
                         on ncCode.Handle equals ncGroupMember.NcCodeOrGroupGbo
                         where
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_AUTO" ||
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_MAN" ||
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_ALL"
                         select ncCode;
...
```
  it works.
  Does OnEntityCreated work only on entities defined as ITable on WipDB?

**Comment by filippobottega** [comment]
Update2:
This code doesn't work:
``` C#
...
            var result = from ncCode in db.NcCode
                         join ncGroupMember in db.NcGroupMember
                         on ncCode.Handle equals ncGroupMember.NcCodeOrGroupGbo
                         where
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_AUTO" ||
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_MAN" ||
                             ncGroupMember.NcGroupBo == "NCGroupBO:" + ncCode.Site + ",CATAN_ALL"
                         select new NcCode { Handle =  ncCode.Handle };
...
```
  It seems that if I create a new instance in the Select clause, the OnEntityCreated is not called.

**Comment by sdanyliv** [comment]
Yes it should work only if you select full instance.

**Comment by MaceWindu** [comment]
So? Bug or by-design?

**Comment by sdanyliv** [comment]
It is by design. This event were introduced for Entities tracking purposes. If you select projection, object is useless in this case.

**Comment by MaceWindu** [comment]
ok, then we should add notes xml-docs

**Comment by filippobottega** [comment]
Thank you for your response.
I need to track all entities creation because I need to implement an in memory deduplication algorithm.
My queries results contains a lot of duplicated strings and I need to intercept the entity creation to change entities and substitute string properties values. This to reduce memory footprint.
If OnEntityCreated is not intended to track all objects created by linq2db, do you know where linq2db creates query result objects?

**Comment by sdanyliv** [comment]
It is only one place how to track entities and currently it works only if entity is not projected.

I think it is bad idea to intercept entities creation in such way.
If I implement such task, i will create new extension:
```cs
public static List<T> ToListWithCheck(this IQueryable<T> source)
{
    var result = source.ToList();
    /// run validator
}
```

**Comment by filippobottega** [comment]
Thank you for let me find a different way to solve my issue: IQueryable inherits IEnumerable and I can change the entities one by one using yield keyword. I want to avoid to allocate all entities in a list using ToList().
The only drawback is that I need to change every query instead to implement a single event.
Please feel free to close this issue if you want.

Thank you

**Comment by sdanyliv** [comment]
Yes, You give me better idea:
```cs
public static IEnumerable<T> AsChecked<T>(this IEnumerable<T> source)
{
    foreach (var item in source) 
    {
        /// run validator
       yield return item;
    }
}
```
