### ISSUE TITLE
Oracle: .Contains with more than 1000 elements results in a split

### ISSUE THREAD

**Issue by inosyryev** [linq2db/linq2db#228]
I have the following code:

```cs
var aCodesToIgnore = LoadACodesToIgnore(directoryPath);
var query =
    from item in repository.TBL_L_TEXT_BLOC
    join term in repository.TBL_TEXT_BLOC on item.FK_TEXT_BLOC equals term.PK_TEXT_BLOC
    join product in repository.TBL_PROD on term.FK_PROD equals product.PK_PROD
    where product.ORA7_PROD_CODE == "FD100"
    where !aCodesToIgnore.Contains(term.OBJE_CODE)
    select new { item.PK_L_TEXT_BLOC, item.FK_TEXT_BLOC, item.FK_LANG_COUN_DATA, item.OBJE_TEXT, term.OBJE_CODE };
```

In this example the list aCodesToIgnore may have more than 1000 items. In this case the following SQL is generated:

```sql
--  Oracle
SELECT
    item.PK_L_TEXT_BLOC,
    item.FK_TEXT_BLOC,
    item.FK_LANG_COUN_DATA,
    item.OBJE_TEXT,
    term.OBJE_CODE
FROM
    SVG_COMP_TEST.TBL_L_TEXT_BLOC item
        INNER JOIN SVG_COMP_TEST.TBL_TEXT_BLOC term ON item.FK_TEXT_BLOC = term.PK_TEXT_BLOC
        INNER JOIN SVG_COMP_TEST.TBL_PROD product ON term.FK_PROD = product.PK_PROD
WHERE
    product.ORA7_PROD_CODE = 'FD100' AND (
        term.OBJE_CODE NOT IN ('A10', 'A10000', 'A10066', ... 'A24081', 'A24155', 'A24204')
        OR term.OBJE_CODE NOT IN ('A24209', 'A24213', 'A24214', ... 'A9946', 'A9972', 'A9980'))
```

I replaced most of strings with "..." to make this SQL shorter.

I don't understand a reason to split the list into 2 parts (btw, it is interesting that the split happens right after 1000th item), but even if it is required then "OR" is definitely an error. Replace it with "AND" and it should work correctly.

This type of error is very dangerous (what I found in a hard way on a production server) because everything works just fine with the number of items less 1000, so it easily passes unit tests.

**Comment by sergey-miryanov** [comment]
@inosyryev Maybe this can help you
https://github.com/linq2db/linq2db/blob/master/Source/DataProvider/Oracle/OracleDataProvider.cs#L29

**Comment by inosyryev** [comment]
@sergey-miryanov Maybe it is a way, but for now I just changed the query to "query.ToList().Where(term => !aCodesToIgnore.Contains(term.OBJE_CODE))". Obviously it will load much more data from the server, but for this query it should not be critical. So, I just traded speed for stability.

I just hope that the bug will be fixed, because it is not a way to remember all these little glitches.
