### ISSUE TITLE
How to set use only Oracle.ManagedDataAccess.Core for linq2db.oracle.managed ?

### ISSUE THREAD

**Issue by B7R5** [linq2db/linq2db#2285]
Describe your issue.

How to set use only Oracle.ManagedDataAccess.Core for linq2db.oracle.managed ?
I'm use linq2db.oracle.managed from .netstandard library, but unit test library targeted to .net48.
In build have warning:

Обнаружен конфликт между "Reference:C:\Users\User\.nuget\packages\oracle.manageddataaccess\12.2.1100\lib\net40\Oracle.ManagedDataAccess.dll" и "Reference:C:\Users\User\.nuget\packages\oracle.manageddataaccess.core\2.19.60\lib\netstandard2.0\Oracle.ManagedDataAccess.dll". Используется "Reference:C:\Users\User\.nuget\packages\oracle.manageddataaccess\12.2.1100\lib\net40\Oracle.ManagedDataAccess.dll", так как значение AssemblyVersion "4.122.1.0" больше "2.0.19.1".

```
Exception message:
System.IO.FileLoadException : Не удалось загрузить файл или сборку "Oracle.ManagedDataAccess, Version=2.0.19.1, Culture=neutral, PublicKeyToken=89b483f429c47342" либо одну из их зависимостей. Найденное определение манифеста сборки не соответствует ссылке на сборку. (Исключение из HRESULT: 0x80131040)

### Environment details
linq2db version: linq2db.2.9.8 
Database Server: Oracle 11g
Database Provider: linq2db.Oracle.Managed.2.9.8, Oracle.ManagedDataAccess.Core.2.19.60
Operating system: Windows
.NET Framework: .netstandart, .net48

**Comment by MaceWindu** [comment]
If you don't use t4 templates, you can reference linq2db and provider nugets directly instead of using linq2db.oracle.managed

**Comment by B7R5** [comment]
Thank you very much. 
I moved the templates and generated classes to a separate assembly and manually copied the context into the main assembly. It works.
