### ISSUE TITLE
Bit (bool) fields and result ms sql query with <> 

### ISSUE THREAD

**Issue by Nelo-cool** [linq2db/linq2db#2288]
Hello guys!
I have trouble with boolean fields and simple ! operator (or == false). In my C# code: _db.TableName.Any(x=>!x.BoooleanField) or _db.TableName.Any(x=>x.BoooleanField == false)
I expected to see it on the way out this : ... WHERE TableName.BooleanField **== 0**, but i see this: WHERE TableName.BooleanField **<>** 1. As a result my index in MS SQL does not work. 
Help me guys, please 8)

linq2db version: *2.9.8*
Database Server: *MS SQL 2016*
Database Provider: *SqlServer*
Operating system: *Windows 2016, Windows 10*
.NET Framework: *4.8*

**Comment by sdanyliv** [comment]
It is a pain, we know, and we have plans to refactor this part.
Try this trick
```cs
_db.TableName.Any(x => Sql.ConvertTo<int>.From(x.BoooleanField) == 0)
```

**Comment by Nelo-cool** [comment]
Okay, but I can do all that, of course, Convert to int, or convert my DAL to int and another. But in SQL query i will see convert operator and as a result my index in MS SQL does not work again:) Any additional functions = break index in most cases. In this story only convert DAL and SQL Table together to Number (int, long and...) type save my country:) thank you for your future work!

**Comment by sdanyliv** [comment]
There are a lot of workarounds which can avoid convert
```cs
[Sql.Expression("{0}", Precedence = Precedence.Additive)]
static int ToInt(this bool boolValue)
{
    return boolValue ? 1 : 0;
}
```
