### ISSUE TITLE
calls subquery sql for each row, if use where/select

### ISSUE THREAD

**Issue by sergpy** [linq2db/linq2db#229]
I have a simple model

```
[Table("customers")]
public class Customer
{
    [PrimaryKey, Identity, Column("idd")]
    public int OID;

    [Column("farch")]
    public bool IsArchive { get; set; }

    [Column("personId")]  
    public int PersonID { get; set; }

}

[Table("persons")]
public class Person 
{
    [PrimaryKey, Identity]
    public int Id;

    [Column(Length=500)]
    public string Name;

    [Association(ThisKey = "Id", OtherKey = "PersonID", CanBeNull = true)]
    public List<Customer> Customers;
}
```

When I try to call

```
        var db = new Models.MyDb();
        var query =
            from r in db.GetTable<Person>().LoadWith(x=>x.Customers)
            where r.Name.Length>1  // as filter sample
            select new
            {
                id = r.Id,
                customers = r.Customers.Where(x=>!x.IsArchive).Select(x => new { x.OID, x.IsArchive, }),
            };

        var res = "";
        foreach (var row in query)
        {
            foreach (var cust in row.customers)
            {
                res += "," + cust.OID;
            }
        }
```

... and the next SQL is called for each row in query  ((

```
 SELECT
[t1].[idd],
[t1].[farch]
 FROM
[customers] [t1]
 WHERE
[t1].[personId] = @p1 AND NOT ([t1].[farch] = 1)
```

I show this simple sample as ilustration, but I use WebApi Odata Controller in real app to serialize query into json, so I got 100+. subqueries for each main query

The problem - I don't know full [where] condition, because it can be changed by OData WebApi parser, so I can't use separate subquery and cache results/
Now this is the main reason to set aside your library and use monster EF ORM

**Comment by MirandaBrazil** [comment]
This is a design issue, not linq2db

Person object have multiple customers, right?

In sql the result will be :

SELECT * FROM persons;
and in loop you will select person customers like :
SELECT * FROM customers WHERE PersonID = id


If you dont want that loop you can use a join like this :

SELECT persons.Id,persons.Name,customers.OID,customers.IsArchive FROM persons JOIN customers ON (customers.PersonID = persons.Id)

Linq equivalent

from r in db.GetTable<Person>() JOIN c IN db.GetTable<Customer>() ON c.PersonID equals r.PersonID
            where r.Name.Length>1 && c.IsArchive.Equals(false)  // as filter sample
            select new
            {
                id = r.Id,
               OID = c.OID,
               IsArchive = c.IsArchive
            };

**Comment by sdanyliv** [comment]
@sergpy, currently optimization of such queries is not supported. It needs additional efforts. We will back to this problem later. Closing for now.
