### ISSUE TITLE
Issue with Cached Queries / Custom Columns

### ISSUE THREAD

**Issue by DuaneTDAC** [linq2db/linq2db#2298]
I have 2, SQLite databases.  1 has no custom fields, the 2nd has the same structure except it has a custom field added to the ContactCustom table, a sub table of the main entity, Contact.  --   Contact -> ContactCustom (linked by CONTACTID columns).

**If I use the following code, I cannot switch databases without an error.**
 ```cs
           mapSchema = MappingSchema.Default;
            mapBuilder = Database.MappingSchema.GetFluentMappingBuilder();
            if (CustomContactFields.Count > 0)
            {
                mapBuilder.HasAttribute<Models.ContactCustom>(new TableAttribute("ContactCustom"));
                mapBuilder.HasAttribute<Models.ContactCustom>(new ColumnAttribute("CONTACTID", "CONTACTID"));
                foreach (Entity.Models.Field field in CustomContactFields)
                    SetProperty<Models.ContactCustom>(field.ALIASNAME, field.DATATYPE);
            }
```
Note:  **SetProperty** does:    mapBuilder.Entity<T>().Property(x => Sql.Property<string>(x, columnName));

When opening the database without the custom field, I receive this message:

Exception message:
```
System.Data.SQLite.SQLiteException
  HResult=0x800007BF
  Message=SQL logic error
no such column: z.CUSTOM1_CHAR50
  Source=System.Data.SQLite
  StackTrace:
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 1579
```
So clearly, the original column name was cached from the first database with the custom column.
-------------------------------------------------------------------------------
After reading through other issues with custom columns, I switched the first few lines to this:
            MappingSchema.ClearCache();
            mapSchema = new MappingSchema(Guid.NewGuid().ToString());
            mapBuilder = mapSchema.GetFluentMappingBuilder();

The issue with switching databases went away, but now I cannot retrieve or save data to the custom column.  The custom table doesn't appear to have any custom fields, just the one static CONTACTID.

"Error updating contact: LinqToDB.Linq.LinqException: There are no fields to update in the type 'ContactCustom'. No PK is defined or all fields are keys.
at LinqToDB.Linq.QueryRunner.Update`1.CreateQuery(IDataContext dataContext, EntityDescriptor descriptor, T obj, String tableName, String databaseName, String schemaName, Type type)

### Environment details
linq2db version: 2.9.7.x
Database Provider: SQLite
Operating system: Windows 10 Pro
.NET Framework: 4.61

I've tried several different ways of clearing the cache, setting the mapSchema and mapBuilder, to no success.  Am I missing something or is this an issue?

Thanks,

Duane

**Comment by sdanyliv** [comment]
If you use `MappingSchema.Default` you has to be aware that you are changing mapping schema for whole application.
Do it in the following way:
```cs
var mapSchema = new MappingSchema();
var mapBuilder = mapSchema.GetFluentMappingBuilder();
...
using (var db = new DataConnection(mapSchema))
{
    ...
}
```

**Comment by sdanyliv** [comment]
Show me you model. And how you are trying to work with this entity.
Maybe we can find solution with dynamic columns.

**Comment by DuaneTDAC** [comment]
I'm on holiday for a week.  I'll report back when I return,

**Comment by MaceWindu** [comment]
Closing. No additional details provided and initial code with use of `MappingSchema.Default` expected to have such issue
