### ISSUE TITLE
Invalid cast exception for cases where group join result is projected to another type in select phase

### ISSUE THREAD

**Issue by detoxhby** [linq2db/linq2db#2307]
(related to #1756)

Invalid cast exception for cases where the group join result is projected to another type in select phase.

```
Exception message:
LinqToDB.Common.LinqToDBConvertException : Cannot convert value '1' to type 'AttendanceSheetRow' (System.InvalidCastException)

Stack trace:
  ConvertBuilder.ConvertDefault(Object value, Type conversionType) line 27
 lambda_method(Closure , IDataReader )
 ColumnReader.GetValue(IDataReader dataReader) line 207
 lambda_method(Closure , IQueryRunner , IDataReader )
 Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader) line 88
 <ExecuteQuery>d__13`1.MoveNext() line 574
 List`1.ctor(IEnumerable`1 collection)
 Enumerable.ToList[TSource](IEnumerable`1 source)
 <>c__DisplayClass39_0`2.<RegisterPreambles>b__0(IDataContext dc, Expression expr, Object[] ps) line 1413
 <>c__DisplayClass185_0`1.<RegisterPreamble>b__0(IDataContext dc, Expression e, Object[] ps) line 3379
 Query.InitPreambles(IDataContext dc, Expression rootExpression, Object[] ps) line 209
 IQueryProvider.Execute[TResult](Expression expression) line 214
```

### Steps to reproduce

```c#
from sheet in ...
// sheet.Id is int
join row in Context.AttendanceSheetRows on sheet.Id equals row.AttendanceSheetId into rows
...
select new X
{
   // 'rows' element type is 'AttendanceSheetRow'
   Rows = rows.Select(x => new AttendanceSheetRowListModel(x)).ToList(),
}
```

### Environment details
linq2db version: v3.0.0-rc.1
Database Server: SQL Server 2017
Database Provider: SqlClient
Operating system: Windows 10 1909
.NET Framework: 4.8

**Comment by MaceWindu** [comment]
@detoxhby I cannot reproduce issue, probably something missing from test case (https://github.com/linq2db/linq2db/pull/2319/files). Can you check test and add more details to query/mappings?

**Comment by MaceWindu** [comment]
Or maybe you can test against latest version from artifacts https://dev.azure.com/linq2db/linq2db/_packaging?_a=package&feed=linq2db&package=linq2db&protocolType=NuGet&version=3.0.0-rc.2512&view=versions - maybe it was already fixed?

I've tried my test on rc1 and it passes, so something it missing.

**Comment by detoxhby** [comment]
Checked with new version, same results.
Posted the changes on MR to align the query with the original.
