### ISSUE TITLE
DB2/zOs ITable<T>.With("UR") issue

### ISSUE THREAD

**Issue by anilcansutaner** [linq2db/linq2db#2315]
Hello ,

I'm trying to select data with uncommitted read in db2/zOs. When i try to use  `ITable<T>.With("UR")` extension method, the library creates sql like 

select * from sometable WITH **UR**  where 1=1

However 
For db2/zOS it should be 

select * from sometable where 1=1 **WITH UR** 

Is there anyway to move with option to the end of the query?

Regards

**Comment by MaceWindu** [comment]
you can append/prepend arbitrary text to your next query (or to all queries using `QueryHints`):

```cs
// append to end
db.NextQueryHints.Add("WITH UR");
// prepend to start
db.NextQueryHints.Add("**WITH UR");
db.your_query;
```
