### ISSUE TITLE
DataConnection GetConfigurationInfo Error

### ISSUE THREAD

**Issue by zharonar** [linq2db/linq2db#2322]
Hi everybody,

I am having this error while I try to make a connection via SQL server provider.

**Error message**: 

`LinqToDB.LinqToDBException: 'Configuration server=(servername);database=(databasename);user id=(userid);password=(userpassword) is not defined.'`

Connection string is correct, since it's the same one for generating the T4 models, which worked.

If you could point me at any direction that would be great. I tried to find any solution online, but no relevant help, so I had to come here.

Thanks.

**Comment by MaceWindu** [comment]
Looks like you are passing connection string in configuration name field/parameter

**Comment by zharonar** [comment]
> Looks like you are passing connection string in configuration name field/parameter

I got confused by the fact that ctor said "configurationString".

It works, thanks for help!
