### ISSUE TITLE
Multiple Take calls results in only the last call being respected

### ISSUE THREAD

**Issue by stuartag** [linq2db/linq2db#2325]
I've had an issue with LINQ to DB as a provider to OData WebApi with SqlServer provider. I have a page size of 200 set in OData but for a particular case I want to specify a $top=5 parameter.

OData effectively performs the $top as a Take(5) followed by the page limit as Take(201). It appears LINQ to DB only respects the last call to Take rather than giving the most restrictive result.

### Steps to reproduce
This can be recreated without OData simply by calling Take twice.

```c#
using (var db = new DataModel.NorthwindDB())
{
    var q =
            (from c in db.Customers
            select c)
               .Take(10)
               .Take(20);

    foreach (var c in q)
        Console.WriteLine(c.ContactName);
}
```

### Expected result
10 results are returned as Take(10) is more restrictive than Take(20)
### Actual result
20 results are returned as Take(20) is overwriting Take(10)

### Environment details
linq2db version: 2.9.8 and 3.0.0-rc.2
Database Server: SQL Server 2017
Database Provider: SqlServer (v2017)
Operating system: Windows Server 2016
.NET Framework:  Core 3.1

**Comment by sdanyliv** [comment]
It is by design of LINQ itself.
Check this result:
```cs
var result = Enumerable.Range(1, 100).Take(10).Take(20).ToArray()
```
Translation of this query is simple: give me 10 records and then give me 20 records from 10 records.

**Comment by stuartag** [comment]
Your example is correct, 10 records are returned, but LINQ to DB is returning 20.

**Comment by sdanyliv** [comment]
So, then it is a bug, thanks for reporting.

**Comment by sdanyliv** [comment]
If you are looking for a quick workaround try the following query:
```cs
db.Customers
      .Take(10)
      .AsSubquery()
      .Take(20);
```
