### ISSUE TITLE
LastOrDefaultAsync are not provided

### ISSUE THREAD

**Issue by KANekT** [linq2db/linq2db#2326]
LastOrDefaultAsync planned for support ?

### Environment details
linq2db version: 2.9
Database Server: MSSQL
Database Provider: *?*
Operating system: *?*
.NET Framework: net core 2.2

**Comment by MaceWindu** [comment]
We don't plan to support `LastOrDefault` : https://github.com/linq2db/linq2db/issues/1904#issuecomment-535890247

**Comment by sdanyliv** [comment]
Just thinking... We can do that if OrderBy is specified for the query. Otherwise we can throw exception.
