### ISSUE TITLE
Генерация оберток к хранимкам

### ISSUE THREAD

**Issue by ilogman** [linq2db/linq2db#233]
При указании в tt шаблоне названия БД содержашей точки (ms sql), например:
LoadSqlServerMetadata(@"DSDB1\SQL2008", "dev.zakupki.sc", "developer", "developer");

Для генерации оберток для хранимок делаются запросы в БД вида:
exec [dev].[zakupki].[sc].[dbo].[GetDataLots] @from='2015-06-23 13:03:12.010',@to='2015-06-23 13:03:12.010'
Сответственно падают из-за превышения числа префиксов и ни одной обертки для хранимки не генерируется.

**Comment by ili** [comment]
fixed
