### ISSUE TITLE
Is there a basic support for a generic ODBC driver?

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#2335]
I have a 64bit **odbc** driver on Windows for a particular DB that is not listed in the explicitly supported ones, but I need extremely basic sql queries: really like a simple select from a certain table with a where condition on a string field or little more.
Is there a simple way to use linq2db with such a driver?
Of course it is already setup as odbc 64bit dsn on my Windows laptop and the classical C# `System.Data.Odbc` with `OdbcCommand `etc works without any issues. I'd simply like to present the code through a light orm wrapper to make it as much generic as possible and with a more friendly NET-idiomatic look...

### Environment details
linq2db version: *latest*
Database: *64 bit ODBC driver*
Operating system: *Windows 64bit*
.NET Framework: *latest version*

**Comment by MaceWindu** [comment]
Nope. We have ODBC providers for Access and SAP HANA, but there is no "generic" provider.

**Comment by giuliohome** [comment]
Ok, is there a commit or a page where I can see what it means to develop my specific odbc provider (with the **minimum** viable features) or can you help me with another comment to understand the expected time effort or a drafted list of to-do actions?
Feel free to close this issue and thanks a lot for your immediate reply, as usual.

**Comment by sdanyliv** [comment]
Which database do you want to connect? Choose right SQL Dialect.
I think working provider can be developed in one day. Then tweaking for a week.

**Comment by MaceWindu** [comment]
you can look at existing implementations for access or sap hana:
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/DataProvider/Access : AccessODBCDataProvider.cs
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/DataProvider/SapHana : SapHanaOdbcDataProvider.cs

As minimal case you will need for starts:
- YourDbODBCDataProvider - you can take access/hana provider and comment out most of code/methods for now to use base implementation first and then see what you need to configure for your db
- YourDbSqlBuilder - just inherit from BasicSqlBuilder, override CreateSqlBuilder method
- YourDbSqlOptimizer - inherit from BasicSqlOptimizer
- YourDbSchemaProvider - you don't need it probably so just throw exception from  GetSchemaProvider
- YourDbMappingSchema - inherit from MappingSchema

**Comment by giuliohome** [comment]
Thank you!

**Comment by giuliohome** [comment]
It's an odbc to bigdata, but, aside from that, I'd love to have the output
of the one day development based on a bare minimum "universal" odbc
"dialect" (i.e. capable vor doing just select x, y from mytable where w=?
and z=? at least when x, y, w and z are string fields) already released and
labeled as "generic minimal odbc", and then test it against my scenario,
eventually tweaking for a week on a specific test branch if anything else
is needed besides that bare odbc level (I can imagine that reading or
writing a field of type BigInt falls into this tweaking, doesn't it?).
What about the connection string to open the connection for example? I
assume that passing it to the actual driver is included in the bare minimum
odbc without any tweaking, right? I guess that, if I pass a pure
"dsn=mydsn" connection string, linq2db will call the configured windows
64bit dsn, that will in turn open the connection, or is there something
else more specific to do that I am missing?
