### ISSUE TITLE
SQL-Text of ILoadWithQueryable

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2336]
Hi,

is it anyhow possible to get the generated SQL string from the new ILoadWithQueryable like it is done with ITable?

**Comment by Franki1986** [comment]
What is here the method AsSubQuery() for? In my case it creates a IQueryable with the desired result, but is this only  always the case?

**Comment by sdanyliv** [comment]
We will add support of query generation for `ILoadWithQueryable` in next release.
`AsSubquery` is intorduced to do not allow optimizer remove subquery from result SQL. It is especially important for Window Functions.

**Comment by Franki1986** [comment]
Any work around here to get it? I have updated my production  code to LinqToDb version 3.

**Comment by MaceWindu** [comment]
What SQL you expect to get?

**Comment by Franki1986** [comment]
In my case I have one class that has an association to another per Left join.
Now I would like to get the resulting sql incl. the left join.

**Comment by MaceWindu** [comment]
ok, this case will work with proposed fix #2337 (release will be probably tomorrow, still need to fix couple of issues)
For multi-query cases it will return sql only for main query

**Comment by Franki1986** [comment]
Thanks!
