### ISSUE TITLE
DataContext vs DataConnection

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#2339]
Hello!

I used to EF's behaviour where connections open for each query and close right after query executed. So, I found `DataContext` more convenient than `DataConnection`. But it seem luck many useful methods existed in `DataConnection`. I found method `DataContext.CreateDataConnection()` that seem to give me ability to forward ALL methods from `DataConnection` to `DataContext` as extensions.

Am I right? Does it have some catches with transactions or other not so obvious things?

**Comment by sdanyliv** [comment]
`DataConnection` is more comparable to `DbContext`. Prefer use this class. 
But yes, EF closes connection on each request, it is really critical? If yes, we can add option `AutoClose` or something like that in next version.

**Comment by Usaga** [comment]
Yes, this is very convenient. This allows us to use `TransactionScope` which attaches to connection only when connection is created (in case of `DataConnection`, when first query executed). So, we can't use `TransactionScope` with repositories injected into constructors, because we can't be sure if connection already been opened by other requests. The only way of using transaction is to "drag out" `DataConnection.BeginTransaction()` through all abstractions (something like `IRepository.BeginSession`), which is not seem to be right.

In case of EF, which opens connections per query, we have ability to use `TransactionScope` knowing nothing about fact of using database in repositories\services.

So, in my opinion, `DataContext` is more convenient to use.

**Comment by sdanyliv** [comment]
A little bit confusing here. What is the problem with TransactionScope and DataConnection? EF do not close connection if it is in transaction scope, I hope.

**Comment by Usaga** [comment]
Problem is if connection is already opened, `TransactionScope` will not attach to it. This is not a problem in EF, if connection is "retained" by other transaction as new transaction will be attached to outer as nested. No contradiction her.

But when we get service or repository, that uses DataConnection, and we want to wrap all requests to those service\repo with `TransactionScope`, we can't be sure this works because there might be preceding requests, which are not even part of current business process.

I mean, if single DataConnection is shared across all services (shared by IoC for current scope\session), we can't know if connection already opened or not.

EF's behaviour allowed us to just use `TransactionScope` and do not bother with such a things. With `DataConnection` we must introduce some way to explicitly require transaction from `DataConnection`, which is less convenient compared to `DataContext` or EF, as it might be hidden somewhere under layer of abstractions.

I see, that DataContext gives me such behaviour, which is nice. But it lucks some functionality. Can I use `DataContext.CreateDataConnection()` to compensate this?

**Comment by sdanyliv** [comment]
Better GetDataConnection, but both are hidden.

**Comment by Usaga** [comment]
I found solution. It is simple and elegant.

`DataConnection` implements `IDataContext` which has `CloseAfterUse` property. I didn't found it earlier because it implemented implicitly, so you have to cast `DataConnection` to `IDataContext` to get access to it.

Setting this property to `true` changes behaviour of `DataConnection` to exactly what I expect to see.

Thanks a lot!
