### ISSUE TITLE
Проблема колонок в Merge

### ISSUE THREAD

**Issue by ilogman** [linq2db/linq2db#234]
При использовании Bulk можно убирать колонки посредством SkipOnInsert, с мержем же такой финт не работает, судя по коду пытаются скопироваться все не идентити колонки. Хотелось бы иметь возможность так же как и в bulk убирать колонки, который физически не могут быть вставлены. По хорошему же иметь полноценный синтаксис, как и в InsertOrUpdate.

**Comment by MaceWindu** [comment]
@ilogman, this will be fixed  the way you wanted with next release by #686
