### ISSUE TITLE
LinqToDb produces a query that wraps Int64 DateTime.Ticks value in SQLite DateTime() function?

### ISSUE THREAD

**Issue by Edward-Alchikha** [linq2db/linq2db#2346]
Hello, I've changed my code recently to store any DateTime values as Int64 values by setting up my DataConnection like this:

```
            var connection = new DataConnection(ProviderName.SQLiteMS, connectionString)
            {
                InlineParameters = true
            };

            connection.MappingSchema.SetDataType(typeof(DateTime), DataType.Int64);
            connection.MappingSchema.SetConvertExpression(
                (long ticks) => new DateTime(ticks, DateTimeKind.Unspecified)
            );
            connection.MappingSchema.SetConvertExpression(
                (DateTime dt) => dt.Ticks
            );
            connection.MappingSchema.SetValueToSqlConverter(
                typeof(DateTime),
                (sb, dType, v) => sb.Append(((DateTime) v).Ticks.ToString(CultureInfo.InvariantCulture))
            );
```

and that works fine for me so long as I don't apply a WHERE to any queries I do. When I do apply a WHERE, this is an example of a query produced:

```
SELECT
        [x].[DateTime],
        [x].[Value]
FROM
        [fae5697f79034df99e0ad32292446f5a_testOut] [x]
WHERE
        DateTime([x].[DateTime]) > DateTime(637304378093620000) AND
        DateTime([x].[DateTime]) < DateTime(637304382196380000)
```

The WHERE condition is created using Linq.Expressions (small but hopefully sufficient cut of code):

```
var left = Expression.Property(x, p);
var right = Expression.Constant(dt, typeof(DateTime));
var e = Expression.GreaterThan(left, right);
var whereCondition = Expression.Lambda<Func<T, bool>>(e, x);

...
queryable = queryable.Where(whereCondition);
...
```

Sorry for not providing more code or any mapping classes. All the mapping classes I'm using are generated dynamically at run time with IL.Emit so I don't have any more code to give that wouldn't make things more confusing. If necessary I can try making a solution that reproduces the problem, but I'm hoping that I'm just missing something like an extra setting on the DataConnection that I wasn't able to find and you can see the problem easily.

linq2db v2.9.8
linq2db.SQLite.MS
Ubuntu 18.04
.NET Core 3.1

**Comment by sdanyliv** [comment]
At first. Do not change MappingSchema of connection. Create new one.
```cs
var ms = new MappingSchema();
ms.SetConverter<long, DateTime>(ticks => new DateTime(ticks, DateTimeKind.Unspecified));
ms.SetConverter<DateTime, DataParameter>(d => new DataParameter(“”, d.Ticks));

using var connection = new DataConnection(ms);
```

**Comment by Edward-Alchikha** [comment]
> At first. Do not change MappingSchema of connection. Create new one.
> 
> ```cs
> var ms = new MappingSchema();
> ms.SetConverter<long, DateTime>(ticks => new DateTime(ticks, DateTimeKind.Unspecified));
> ms.SetConverter<DateTime, DataParameter>(d => new DataParameter(“”, d.Ticks));
> 
> using var connection = new DataConnection(ms);
> ```

Unfortunately, when I change my method to:

```
        private DataConnection MakeConnection()
        {
            var ms = new MappingSchema();
            
            ms.SetConverter<long, DateTime>(ticks => new DateTime(ticks, DateTimeKind.Unspecified));
            ms.SetConverter<DateTime, DataParameter>(d => new DataParameter("", d.Ticks));

            // set InlineParameters to true so that we don't get any "@Variable Name" occurring in queries
            // since this will fail if a column name has spaces in it (possible when using Reflection.Emit)
            var connection = new DataConnection(ProviderName.SQLiteMS, connectionString, ms)
            {
                InlineParameters = true
            };

            return connection;
        }
```

it doesn't seem to help. It behaves in the same way: writes work and store correctly in the database, and reads work properly so long as it's just a simple SELECT with no WHERE. Although, it seems to stop respecting the InlineParameters = true when done like this:

```
DECLARE @p1  -- DateTime
SET     @p1 = 637304378093620000
DECLARE @p2  -- DateTime
SET     @p2 = 637304382196380000

SELECT
        [x].[DateTime],
        [x].[Value]
FROM
        [fae5697f79034df99e0ad32292446f5a_testOut] [x]
WHERE
        DateTime([x].[DateTime]) > @p1 AND DateTime([x].[DateTime]) < @p2
```

**Comment by sdanyliv** [comment]
Could you please check latest version. Maybe it will not change inlining but who knows, i need to check on my workstation.

**Comment by Edward-Alchikha** [comment]
> Could you please check latest version. Maybe it will not change inlining but who knows, i need to check on my workstation.

I updated to 3.0.1 and it looks like it still ignores InlineParameters = true, though it has changed:

```
DECLARE @DateTime_1  -- DateTime
SET     @DateTime_1 = 637304378093620000
DECLARE @DateTime_2  -- DateTime
SET     @DateTime_2 = 637304382196380000

SELECT
        [x].[DateTime],
        [x].[Value]
FROM
        [fae5697f79034df99e0ad32292446f5a_testOut] [x]
WHERE
        DateTime([x].[DateTime]) > @DateTime_1 AND DateTime([x].[DateTime]) < @DateTime_2
```

**Comment by sdanyliv** [comment]
@Edward-Alchikha, can you live for several days with parameters? I'll fix inlining.

**Comment by Edward-Alchikha** [comment]
> @Edward-Alchikha, can you live for several days with parameters? I'll fix inlining.

Yea, the inlining problem doesn't bother me since I can just use my original code that properly inlines since neither set of code works for not calling the SQLite DateTime() function on my Int64 DateTime.Ticks values anyways.

I can manage without the DateTime.Ticks fix for now as well, since that's on an experimental branch, but it would be nice to have that working since it improves the size of the database files and the performance (in the case of a simple insert or read with no WHERE)

**Comment by sdanyliv** [comment]
Looking into DateTime conversion and inlining problem. Looks like there are legacy conversions.
