### ISSUE TITLE
Не закрывается соединение с БД

### ISSUE THREAD

**Issue by flamencist** [linq2db/linq2db#235]
В следующем примере кода не закрывается соединение с БД
```csharp
        [Test]
        public void Try_Find()
        {
            IEnumerable<Log> query;
            using(var db = new DataConnection(_connectionName))
            {

                query = db.GetTable<Log>()
                 .Select(el => el);
            }

            var result = query.ToList();
        }
```

При актулизации ```var result = query.ToList()``` открывается соединение, выполняется запрос, приходят верные данные, но не закрывается соединение.
Как я думаю, это особенность linq2db, и решением является использование привидения к ```ToList``` в ```using```, или не использование совсем ```using```.

**Comment by igor-tkachev** [comment]
You should use ToList inside using.
