### ISSUE TITLE
COLLATE NOCASE

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2353]
Linq2Db: 3.0.0-rc.1

Is there any possibility to use COLLATE NOCASE for SQLite in Linq2Db

- globally for the database or, 
- for the column (Linq2Db configuration) or
- in the query (Linq2Db query)

I use Linq2Db in-memory in combination with SQLite

**Comment by sdanyliv** [comment]
Please post expected SQL and LINQ expression, we do not know all SQL Dialects and database features.

**Comment by HypeillingerChillinger** [comment]
Ok, I use SQLite in memory

SQLite is case-insensitve by default as far as I understood. In order to have case-sensitiveness on a column you need to add COLLATE NOCASE on creation of the column or add it to the query.

The query could be:
```sql
SELECT * FROM ... WHERE name = 'someone' COLLATE NOCASE
```

or add it to the column on creation:
```sql
create table Test
(
  Text_Value  text collate nocase
);
```

The Linq Query could be:
```c#
context.MyClass.Where(x => x.StringProperty == "Hello")
```

https://stackoverflow.com/questions/973541/how-to-set-sqlite3-to-be-case-insensitive-when-string-comparing

**Comment by sdanyliv** [comment]
You have to create helper function:
```cs
[Sql.Expression("{0} = {1} COLLATE NOCASE", IsPredicate = true, ServerSideOnly = true, Precedence = Precedence.Comparison)]
public static bool CompareNoCase(string value1, string value2) 
   => throw new NotImplementedExcption();
```
And use in LINQ query
```cs
context.MyClass.Where(x => CompareNoCase(x.StringProperty, "Hello"));
```
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/Sql#sql-extensions

**Comment by HypeillingerChillinger** [comment]
Ok, thank you. Since I use more database servers than SQLite can I say
if(SQLite) then use it

I build the query with expressions

**Comment by sdanyliv** [comment]
There are a lot of ways to do that
```cs
[Sql.Expression(ProviderName.SQLite, "{0} = {1} COLLATE NOCASE", IsPredicate = true, ServerSideOnly = true, Precedence = Precedence.Comparison)]
[Sql.ExpressionMethod(ProviderName.SqlServer, nameof(CompareNoCaseImpl))]
[Sql.ExpressionMethod(nameof(CompareNoCaseLowerImpl))] // for others
public static bool CompareNoCase(string value1, string value2) 
   => throw new NotImplementedExcption();

// fallback to default implementation
static Expression<Func<string, string, bool>> CompareNoCaseImpl()
   => (value1, value2) => value1 == value2;

// or with changing case
static Expression<Func<string, string, bool>> CompareNoCaseLowerImpl()
   => (value1, value2) => value1.ToLower() == value2.ToLower();
```

**Comment by HypeillingerChillinger** [comment]
That works, thanks.

**Comment by alexey-leonovich** [comment]
@sdanyliv @MaceWindu If I need to create a column with NOCASE collation
```
CREATE TABLE User
(
  Id  TEXT COLLATE NOCASE 
);
```
is there a better aproach that this one?
```
public class User
{
    [Column(DbType = "TEXT", CreateFormat = "{0} {1} {2} {3} COLLATE NOCASE")] public Guid? Id { get; set; }
}
```
I found [this comment](https://github.com/linq2db/linq2db/pull/2731#issuecomment-772450529) but I don't understand what _SQLITE: standard "{str} COLLATE {collation}"_ means. Should I use some attribute?
