### ISSUE TITLE
Override Merge API in 3.x version

### ISSUE THREAD

**Issue by ghost** [linq2db/linq2db#2355]
Previously it was possible to override MySQL provider behaviour in case of calling merge API.

```c#
public override int Merge<T>(DataConnection connection,
                                     Expression<Func<T, bool>> deleting, bool delete,
                                     IEnumerable<T> source, string table, string database, string schema)
```

How to do it in 3.0?
I need to implement workaround for MySQL, because lin2db fails on merge call (which used for bulk update opetation).

https://github.com/linq2db/linq2db/issues/1596
https://github.com/linq2db/linq2db/issues/1596

It is crucial for my existing code base to override it. Some fallback for example per-row processing.

**Comment by MaceWindu** [comment]
Well, merge API currently supports only providers with real MERGE, mysql/pgsql UPSERT support only planned.

Quickly looked, probably you can try to implement custom sql builder. As MySqlSqlBuilder is not public, you will need to copy it's code and inherit from it to override BuildMergeStatement method.

**Comment by MaceWindu** [comment]
From your initial message I see that you already subclassed provider. You need to override this method to return custom sql builder
https://github.com/linq2db/linq2db/blob/422f6df9c17d3e3f28bdfa85783c38575568531b/Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs#L59

**Comment by sdanyliv** [comment]
Better create PR and share it with others ;)

**Comment by hardhub** [comment]
> Better create PR and share it with others ;)

Yes in case of full implementation it makes sense and I will share of course.  
Though for the moment I want to repeat workaround of version 2.x first.

**Comment by MaceWindu** [comment]
Not planned. Merge API is for MERGE statement. We don't plan to emulate it
