### ISSUE TITLE
Setting of DateTimeKind does not work

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2356]
We have this code in our backend:

     mappingSchema.SetConvertExpression<DateTime, DateTime>(dt => DateTime.SpecifyKind(dt, DateTimeKind.Utc));

but it does not seem to work.

Don't know if it happend with update to v3 or before. Using Postgres Database

**Comment by jogibear9988** [comment]
Postgres database Type is "Timestamp without Timezone"

**Comment by jogibear9988** [comment]
Problem is, I can not set a breakpoint inside of the expression, to see if it is called...

**Comment by jogibear9988** [comment]
Fore sure I can not... It creates a expression tree... I'm dumb...

**Comment by MaceWindu** [comment]
if you want to debug it - move conversion to function.

**Comment by jogibear9988** [comment]
SetConvertExpression only allows a expression. Don't know if SetConverter is the same...

**Comment by jogibear9988** [comment]
@MaceWindu do you have any Idea why the datetimekind could be unset?

**Comment by MaceWindu** [comment]
Yes, but you can call function in expression
```cs
mappingSchema.SetConvertExpression<DateTime, DateTime>(dt => SetKind(dt));

static DateTime SetKind(DateTime dt) => DateTime.SpecifyKind(dt, DateTimeKind.Utc);
```

**Comment by MaceWindu** [comment]
I've checked I don't see any obvious code that could mess with kind on our side. Could be npgsql behavior

**Comment by MaceWindu** [comment]
Anyway, having test will have to identify if it is expected behavior or bug

**Comment by sdanyliv** [comment]
Try this:
```cs
mappingSchema.SetConverter<DateTime, DataParameter>(dt => new DataParameter("", DateTime.SpecifyKind(dt, DateTimeKind.Utc), DataType.DateTime));
```

**Comment by jogibear9988** [comment]
Creating a test at the moment. Also thought about what you wrote @sdanyliv 

But it worked before without extra converter (at least I thought it worked)

**Comment by sdanyliv** [comment]
Will check, possible regression.

**Comment by jogibear9988** [comment]
https://github.com/linq2db/linq2db/pull/2357

**Comment by jogibear9988** [comment]
does not work....
on insert converter is called. on reading not...

**Comment by sdanyliv** [comment]
> on insert converter is called.

What does it mean? Sample included in test?

**Comment by jogibear9988** [comment]
When I insert a Row to the database, and you set a breakpoint here:

https://github.com/linq2db/linq2db/pull/2357/files#diff-d62ecbf49af017ba92a814743333166dR20

it is raised, on the read not.

**Comment by jogibear9988** [comment]
@sdanyliv more infos required? is my test okay?

**Comment by sdanyliv** [comment]
Not yet, I'll check it right now.

**Comment by sdanyliv** [comment]
What I  do not see here that SetKind is called when we remove this line
```cs
ms.SetConvertExpression<DateTime, DataParameter>(dt => new DataParameter() { Value = SetKind(dt), DataType = DataType.DateTime });
			
```

**Comment by jogibear9988** [comment]
Yes, but it should be, or not?

**Comment by jogibear9988** [comment]
I think some releases ago it was enough only to specify 

     mappingSchema.SetConvertExpression<DateTime, DateTime>(dt => DateTime.SpecifyKind(dt, DateTimeKind.Utc));

but I don't know any more if it was used on insert or on read.

I want it to be used in both. I want always UTC is written and read from DB.

**Comment by jogibear9988** [comment]
We saw now that our Unitests worked before Version 3.0

So the converter with

     mappingSchema.SetConvertExpression<DateTime, DateTime>(dt => DateTime.SpecifyKind(dt, DateTimeKind.Utc));

was enough

**Comment by jogibear9988** [comment]
@sdanyliv is there something I could do about this, or should I roll back to 2.x ?

**Comment by sdanyliv** [comment]
Use workaround before we fix that.

**Comment by jogibear9988** [comment]
What is workaround? 

also with

       mappingSchema.SetConverter<DateTime, DataParameter>(dt => new DataParameter("", DateTime.SpecifyKind(dt, DateTimeKind.Utc), DataType.DateTime));

it does not work

**Comment by sdanyliv** [comment]
Oh man. You have debugger we do not have enough time. Which column type do you have?
Try this variant
```cs
mappingSchema.SetConverter<DateTime, DataParameter>(dt => new DataParameter("", DateTime.SpecifyKind(dt, DateTimeKind.Utc), DataType.DateTimeOffset));
```

**Comment by MaceWindu** [comment]
@sdanyliv sounds like we have misunderstanding here. @jogibear9988 has issue with converter not applied on mapping from db. I suspect at some point we started ignore converter in mapper when source and target types are same

**Comment by jogibear9988** [comment]
@MaceWindu 
yes, that's what i ment. 
Sorry I do not want to make extra work for you.  I help where I could to find the issue.

But yes, with DataParameter, the converter is called when writing to the database.

But with Version 2.x the converter wich I posted wa sused during reading

**Comment by jogibear9988** [comment]
sorry, I closed, I thought the pull req. was already merged
