### ISSUE TITLE
JetBrains Rider reports 1437 errors in ttinclude files with brand new project

### ISSUE THREAD

**Issue by pingvinen** [linq2db/linq2db#2358]
Hi

I am currently checking out linq2db, but I ran into an issue very early on.

I am on Linux and I use JetBrains Rider 2020.1.

Doing the following, leaves me with a project that - according to Rider - has 1437 errors in 12 files. Luckily I can still compile the project, but it is very annoying to see all these errors all the time.

As far as I know, these files are for generating models based one existing databases, which is not a use-case that I have, so I tried removing the files from Rider, which it does not allow for some reason.

Anyway, I did the following:

```
$ dotnet new console --name=something
$ cd something
$ dotnet add package linq2db
$ dotnet add package linq2db.PostgreSQL
```

Typical errors are (these are from `DataAnnotations.ttinclude`):
  - Cannot resolve symbol `Class` 
  - Cannot resolve symbol `BeforeGenerateModel`

Can anyone tell me if I am just missing something obvious? If it is actually a bug in Rider, I will gladly take it up with them :)

### Environment details
linq2db version: *3.0.1*
Database Server: *Postgres 12.3*
Database Provider: *linq2db.PostgreSQL 3.0.1*
Operating system: *LInux (ubuntu 18.04)*
.NET Framework: *Core 3.1*

**Comment by viceroypenguin** [comment]
You do not actually have to include the `linq2db.PostgreSQL` package if you do not need it. That package is strictly for the purpose of the t4 model generation. If you simply need `linq2db` on PostgreSQL, linq2db will dynamically load the npgsql package automatically if you have included a reference in your package and specify in the connection that you are using PostgreSQL.

**Comment by MaceWindu** [comment]
I think you should contact JetBrains, as it should work. They even released some fixes in 2020.1 for our templates https://youtrack.jetbrains.com/issue/RIDER-33469

**Comment by MaceWindu** [comment]
Also check this for exceptions configuration https://youtrack.jetbrains.com/issue/RIDER-36962

**Comment by MaceWindu** [comment]
and this https://youtrack.jetbrains.com/issue/RIDER-35758

**Comment by pingvinen** [comment]
Thank you for the very quick answers :)

It worked. For other newbies hitting this issue (and who do not need the models-from-existing-db functionality), the following seems to work:

```
$ dotnet new console --name=something
$ cd something
$ dotnet add package linq2db
$ dotnet add package Npgsql
```
