### ISSUE TITLE
Wrong Query with Linq2db in Postgres (but also Sqlite)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2359]
Linq See Pull Request. (#2360)

SQL in SQLite is: 

	SELECT
		Substr([tag].[Name], CharIndex('.', [tag].[Name], CharIndex('.', [tag].[Name], 6) + 1) + 1, Length([tag].[Name]) - CharIndex('.', [tag].[Name], CharIndex('.', [tag].[Name], 6) + 1)),
		Substr([tag].[Name], 5, CharIndex('.', [tag].[Name], 6) - 5),
		[tag].[Name],
		(
			SELECT
				[x].[TagValue]
			FROM
				[Issue2358TagArchive] [x]
			WHERE
				[x].[TagId] = [tag].[Id] AND DateTime([x].[ModifiedTimeStamp]) < DateTime(@now)
			ORDER BY
				[x].[ModifiedTimeStamp]
			LIMIT @take
		),
		(
			SELECT
				[x_1].[TagValue]
			FROM
				[Issue2358TagArchive] [x_1]
			WHERE
				[x_1].[TagId] = [tag].[Id] AND DateTime([x_1].[ModifiedTimeStamp]) < DateTime(@today)
			ORDER BY
				[x_1].[ModifiedTimeStamp]
			LIMIT @take_1
		)
	FROM
		[Issue2358Tag] [tag]
	WHERE
		[tag].[Name] LIKE '%.ServiceData.General.OperatingTimeInAutomaticMode'

I thought difference should be build on database side?

**Comment by jogibear9988** [comment]
I thought query should look like this:

	SELECT
		Substr([tag].[Name], CharIndex('.', [tag].[Name], CharIndex('.', [tag].[Name], 6) + 1) + 1, Length([tag].[Name]) - CharIndex('.', [tag].[Name], CharIndex('.', [tag].[Name], 6) + 1)),
		Substr([tag].[Name], 5, CharIndex('.', [tag].[Name], 6) - 5),
		[tag].[Name],
		(
			SELECT
				[x].[TagValue]
			FROM
				[Issue2358TagArchive] [x]
			WHERE
				[x].[TagId] = [tag].[Id] AND DateTime([x].[ModifiedTimeStamp]) < DateTime(@now)
			ORDER BY
				[x].[ModifiedTimeStamp]
			LIMIT @take
		) -
		(
			SELECT
				[x_1].[TagValue]
			FROM
				[Issue2358TagArchive] [x_1]
			WHERE
				[x_1].[TagId] = [tag].[Id] AND DateTime([x_1].[ModifiedTimeStamp]) < DateTime(@today)
			ORDER BY
				[x_1].[ModifiedTimeStamp]
			LIMIT @take_1
		) AS Value
	FROM
		[Issue2358Tag] [tag]
	WHERE
		[tag].[Name] LIKE '%.ServiceData.General.OperatingTimeInAutomaticMode'

**Comment by sdanyliv** [comment]
It is by design.
You always have Sql.AsSql

**Comment by jogibear9988** [comment]
but the result should be 10000 and not 0

**Comment by jogibear9988** [comment]
or is my linq wrong?

**Comment by jogibear9988** [comment]
ahhhh, think my orderby is wrong, need desc

**Comment by jogibear9988** [comment]
OrderBy was Wrong :-(

But I thought the query is wrong cause the difference was no tbuild in database
