### ISSUE TITLE
Rebind parameters of generic methods

### ISSUE THREAD

**Issue by N00mBus2000** [linq2db/linq2db#2361]
### Steps to reproduce
```c#
            var param = new DataParameter("param", "before", DataType.VarChar) {Direction = ParameterDirection.Output};
            var resultSet = await db.ExecuteProcAsync<Foo>("Bar", param); // set after
            var value = param.Value; // before (expect: after)
            //var value = Converter.ChangeTypeTo<string>(((IDataParameter)db.Command.Parameters[param.Name]).Value); // why is life soooo hard? ;(
```

### Environment details
What you want.

**Comment by sdanyliv** [comment]
1. Does it reproducible in sync version?
2. Which database do you use?
3. linq2db version?

**Comment by N00mBus2000** [comment]
1) Yes, it does.
2) SqlServer v2017
3) I checked 2.8 and 3.0.1

namespace LinqToDB.Data
CommandInfo
`
                public T Execute<T>()
		{
			var hasParameters = Parameters?.Length > 0;

			DataConnection.InitCommand(CommandType, CommandText, Parameters, null, hasParameters);

			if (hasParameters)
				SetParameters(DataConnection, Parameters);
                        ...
		}
`
`
		public int Execute()
		{
			var hasParameters = Parameters?.Length > 0;

			DataConnection.InitCommand(CommandType, CommandText, Parameters, null, hasParameters);

			if (hasParameters)
				SetParameters(DataConnection, Parameters);

                        ...

			if (hasParameters)
				RebindParameters(DataConnection, Parameters);

			return commandResult;
		}
`

**Comment by sdanyliv** [comment]
So what? Which line makes error? `RebindParameters` has error?

**Comment by sdanyliv** [comment]
One nuance with SQLServer, to get output parameter you have to open and enumerate reader to the end and close DataReader. Probably your stored proc have returned more than one record.

**Comment by N00mBus2000** [comment]
Full text:
```c#
		public async Task<T> ExecuteAsync<T>(CancellationToken cancellationToken)
		{
			await DataConnection.EnsureConnectionAsync(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);

			var hasParameters = Parameters?.Length > 0;

			DataConnection.InitCommand(CommandType, CommandText, Parameters, null, hasParameters);

			if (hasParameters)
				SetParameters(DataConnection, Parameters);

			using (var rd = await DataConnection.ExecuteReaderAsync(GetCommandBehavior(), cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext))
			{
				if (await rd.ReadAsync(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext))
				{
					var additionalKey = GetCommandAdditionalKey(rd);
					try
					{
						return GetObjectReader<T>(DataConnection, rd, CommandText, additionalKey)(rd);
					}
					catch (InvalidCastException)
					{
						return GetObjectReader2<T>(DataConnection, rd, CommandText, additionalKey)(rd);
					}
				}
			}

			return default;
		}
```

You close reader inside a method. But don't rebind parameters. Maaaayyyybeee you did not fix this in https://github.com/linq2db/linq2db/pull/1231.

**Comment by sdanyliv** [comment]
Probably, do you want to create PR for this?

**Comment by N00mBus2000** [comment]
Ok. Today or tomorrow.

**Comment by MaceWindu** [comment]
Current version rebinds parameters only for `int ExecuteProc()` API. Working on support for other APIs here #2412
