### ISSUE TITLE
how can auto assign foreignkey?

### ISSUE THREAD

**Issue by ckhker** [linq2db/linq2db#237]
public class User
{
    [PrimaryKey, Identity]
   [Column,        Nullable] 
    public string Id { get; set; }

   [Column,        Nullable] 
    public string Name { get; set; }
[Column,        Nullable] 
   public int AddressId{get;set;}
[Association(ThisKey="AddressId", OtherKey="AddressId", CanBeNull=false]
   public Address UserAdr{get;set;}
}
public class Address 
{
    [PrimaryKey, Identity]
   [Column,        Nullable] 
    public string Address Id { get; set; }

   [Column,        Nullable] 
    public string Name { get; set; }
[Column,        Nullable] 
   public int AddressText{get;set;}
}

when i use
var q =from c in db.User
                    where c.id==1
                    select c;
why UserAdr always null?
var q =from c in db.User
                    where c.id==1
                    select c.UserAdr ;
it have value.
but i want when i select User, UserAdr have a value,how can i do?

**Comment by igor-kalashnikov** [comment]
You can use LoadWith method:
```
var q = from c in db.User.LoadWith(u => u.UserAdr)
where c.id == 1
select c;
```

**Comment by sdanyliv** [comment]
It seems that it is already answered.
