### ISSUE TITLE
Since Update to 3.0 DataType in Mapping is needed....

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2372]
Since we've updated to v3.0 we need to specify the Datatype at some places, were it worked before without specification.

At one place we have a CustomObject, wich uses a special converter to string. At another place we used a enum wich was stored in a string column.

For me it this is no problem, and I understand that we need to know the column type for the insert to work correctly. But why did it work in 2.x before without specification of the type? (this is the thing I don't understand) 

Here a screenshot of the stacktrace we've got (the bltoolkit exception is a wrapper of the exception from linq2db of our datalayer, we need to rename some time in the future...)
![image](https://user-images.githubusercontent.com/364896/88554085-59136780-d026-11ea-849f-ba39ae8b3af1.png)

**Comment by jogibear9988** [comment]
The exception was from the enum we store as string.

Adding .HasDataType(DataType.NVarChar) fixed the problem

**Comment by jogibear9988** [comment]
This was the converter we used for the enum (in 2.x and 3.x)

            mappingSchema.SetConverter<NumbersType, string>((obj) =>
            {
                return obj.ToString();
            });
            mappingSchema.SetConverter<NumbersType, DataParameter>((obj) =>
            {
                return new DataParameter { Value = obj.ToString() };
            });
            mappingSchema.SetConverter<string, NumbersType>((txt) =>
            {
                return (NumbersType)Enum.Parse(typeof(NumbersType), txt, true);
            });

**Comment by sdanyliv** [comment]
@jogibear9988, can you try to comment out this part:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/ColumnDescriptor.cs#L442-L443

**Comment by jogibear9988** [comment]
okay, I will try.
But is it intended? Should it work without (or not)

**Comment by sdanyliv** [comment]
Possible, so you can help me to understand what happened. 
If you have specified DataParameter's type and it do not work - it will be a definitely bug

**Comment by jogibear9988** [comment]
I'll test now...
we also found some other issues in our nightly Tests after 3.0 update.
Will create issues form them also

**Comment by jogibear9988** [comment]
Does not change anything.
If type is enum, Datatype is already set here:
https://github.com/linq2db/linq2db/blob/8f242d79af6d1dece13b800f642590f63c650d7a/Source/LinqToDB/Mapping/ColumnDescriptor.cs#L160

this code does not exist in V2.x

**Comment by sdanyliv** [comment]
Who set datatype?

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/88652703-79e1c880-d0cb-11ea-9f46-09d6975823bc.png)

 this is the call stack where enum type is set

**Comment by jogibear9988** [comment]
The following test works in linq2db 2.x

https://github.com/linq2db/linq2db/pull/2381

**Comment by jogibear9988** [comment]
At least with sqlite

**Comment by jogibear9988** [comment]
For me it's okay if we need to specify type, but in 2.x we did not need to

**Comment by jogibear9988** [comment]
If I step over line 187

https://github.com/linq2db/linq2db/blob/8f242d79af6d1dece13b800f642590f63c650d7a/Source/LinqToDB/Mapping/ColumnDescriptor.cs#L187

it works.

**Comment by sdanyliv** [comment]
I’ll check. No free time now. For the next release it will be fixed.

**Comment by jogibear9988** [comment]
No problem. As it works when I add the Datatype.
Only critical issue for me now is #2378 as I don't know how it will affect some of our complex queries

**Comment by MaceWindu** [comment]
#2381
