### ISSUE TITLE
Guidance on limiting features while integrating this into an existing project

### ISSUE THREAD

**Issue by cutig3r** [linq2db/linq2db#2373]
I've got an existing project that I'm looking to transition from ado.net calls to use linq2db.
The database has ~250 tables with custom business logic for saving residing on the database.
In order integrate this slowly into the project, I'd need the ability to do the following:
1. Only allow selects using the mapped classes
2. Disallow bulk copy (currently no way to intercept that), and disable all other query types (most are handled by overriding the process query method)
3. Prevent calls where the developer can enter sql as a string (e.g. DataConnection.FromSql, ITable&lt;T&gt;.Query(), etc)

Is there a way that I can achieve this?  
I've tried decorating the DataConnection and returning IQueryables, but the data/schema modification extension methods for IQueryable are still applicable (also I had issues getting the Queryables to execute on the db, they were throwing an InvalidOperationException)
Currently I have a class decorating the DataConnection which returns ITables, but ITable&lt;T&gt; leaks the DataConnection and makes it unnecessary.

**Comment by viceroypenguin** [comment]
None of these are strictly feasible, as the only way to limit compile-time access to certain methods in any library is to ship a secondary version of that library without those methods. 

In L2DB, there are currently no parameters or configurations that will disable run-time usage of any of these methods. 

That said, a cheap way to block the bulk copy and FromSql methods would be to define duplicate extension methods that mirror them and make sure that they are in a namespace that is always included. Then any attempt to use those methods normally would introduce a compile-time error. 

I don't see any way to prevent 1. currently, though the others might know of something I don't.

**Comment by cutig3r** [comment]
Thanks for the quick response.  Off the top of your head, do you think something like castle's dynamicproxy would work with linq2db?

**Comment by viceroypenguin** [comment]
If you're looking to proxy `LinqExtensions.cs` (which is where most of the extension methods (BulkCopy, Insert, Update, etc.) live), that should work fine, as far as I know. L2DB translates the calls internally into an expression tree, so as long as the L2DB code gets called, there shouldn't be any issues. 

Where you _might_ find issues is if you use anything like the windowed aggregate support or anything else that gets called inside of an expression (the select part, etc.). I don't know how or if Castle affects the generated expression tree there, but that would be where any issues would crop up. Even then, any issues should be avoidable in the general case.

**Comment by sdanyliv** [comment]
@cutig3r, everything can be hidden if you disallow to use LinqToDB namespace. There are a ways to do that but it needs expression tree preprocessing (which is availaible). Anyway, you can setup CI restrictions via FxCop or Roslyn analysers.

**Comment by cutig3r** [comment]
Thank you both for the input.  I ended up using a hybrid approach, where I decorated the datacontext with another class, and also created a [custom roslyn analyzer](https://gist.github.com/cutig3r/e8b504beb0c8ecf12e06939b6ab56357).

**Comment by viceroypenguin** [comment]
The analyzer is impressive. Thanks for sharing! Glad you were able to get something working!
