### ISSUE TITLE
Just a little praise for you guys

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#2374]
I'm a longtime user of Linq2DB and before that I was using BLToolkit, One thing that I always wanted was to be able to get model `OneToMany` associations in one go without going to the database multiple times.

I was away from doing back-end for a while so I didn't realized you guys have fixed this limitations. With just doing `query.LoadWith( x => x.ProductLicenses ).ThenLoad( x => x.Product )` it just works. Magic!

Guys, you are the best. I cannot thank you enough times for all the work you're doing. Thank you!!!

**Comment by sdanyliv** [comment]
I'm glad to hear that. Spell was very complicated ;)

**Comment by yarecky1** [comment]
Let's read this conversations once more:
@stsrki - Magic!
@sdanyliv - Spell was very complicated ;)
Ha ha. Nice. 👍

**Comment by stsrki** [comment]
@yarecky1 You have no idea from just how much boilerplate code this feature saves. In one of my previous projects I had to do a lot of manual queries to make it work. And there was always many room for errors. 

PS. You guys accept donations?

**Comment by yarecky1** [comment]
When I started using this library I tested some of its features including one-to-many LoadWith. I quickly stopped because of multiple round trips to database. I quickly started using two queries and joining them in memory using Dictionary or Lookup. Personally I don't use LoadWith and query entire objects; I prefer selective and effective query with absolutely minimum properties involved.

**Comment by stsrki** [comment]
That was exact thing that I did, but you must admit, in cases you when need to get entire object it's a lot easier with `.LoadWith()`.

**Comment by sdanyliv** [comment]
Look at this my nightmare for a half of the year https://github.com/linq2db/linq2db/pull/1756
With the breaks to rethink/rewrite code again. 
There are a lot of ideas how to improve speed of Eager Loading with CTE... well I need time to rest.

> PS. You guys accept donations?

Never tried that but GitHub suggested such option several months ago.

**Comment by yarecky1** [comment]
@stsrki True. It's saves a lot of code typing. I have to maintain legacy code with MsAccess database using and quickly realized that in shared environment I can't allow for querying heavy entities with children and grandchildren objects. Maybe in future I will find the reason to use again LoadWith.

**Comment by stsrki** [comment]
@sdanyliv Just scrolling through that PR takes time. I guess it was real pain to finish it.
