### ISSUE TITLE
Linq2db 3.x - Problems with group by in Postgres

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2375]
After Update to 3.x we get the following exception:

System.InvalidCastException: 'Can't write CLR type MCC.WMS.ServiceInterfaces.Enums.InventoryResourceStatus with handler type Int32Handler'

but only when we use postgres, with mssql and sqlite it works.

or select is very complex:

            var list = from inventory in s.Query<InventoryResourceDTO>()
                    join lc in s.Query<WmsLoadCarrierDTO>() on inventory.ResourceID equals lc.Id
                       join material in s.Query<MaterialDTO>() on inventory.MaterialID equals material.Id
                join infeeds in s.Query<InfeedAdviceDTO>() on inventory.InfeedAdviceID equals infeeds.Id into infeedList
                from infeed in infeedList.DefaultIfEmpty()
                where inventory.Status < InventoryResourceStatus.Finished
                      //&& !material.DontMerge
                      && inventory.ModifiedTimeStamp < DateTime.UtcNow - TimeSpan.FromHours(1)
                      && inventory.ProductionDate == null
                      && inventory.Unit != "m" && inventory.Unit != "M"
                      && (infeed == null || (infeed.Status >= InfeedAdviceStatus.Finished &&
                                             infeed.ModifiedTimeStamp < DateTime.UtcNow - TimeSpan.FromHours(1)))
                       group inventory by new
                {
                    inventory.Status,
                    inventory.MaterialID,
                    inventory.ResourceID,
                    inventory.ExpiryDate,
                    inventory.BatchNumber,
                    inventory.Unit,
                    inventory.QuantityPerBundle,
                    inventory.BundleUnit,
                    inventory.ProductStatus,
                    inventory.ReasonForRestriction,
                    inventory.RestrictionLabel,
                    inventory.RestrictionText,
                    inventory.ToHostStatus,
                    inventory.CustomField1,
                    inventory.CustomField2,
                    inventory.CustomField3,
                    inventory.CustomField4,
                    inventory.CustomField5,
                    inventory.CustomField6,
                    inventory.CustomField7,
                    inventory.CustomField8,
                    inventory.CustomField9,
                    inventory.CustomDate1,
                    inventory.CustomDate2,
                    inventory.CustomDate3,
                    inventory.CustomDate4,
                    inventory.CustomDate5,
                    inventory.CustomDate6,
                    inventory.CustomDate7,
                    inventory.CustomDate8,
                    inventory.CustomDate9,
                    inventory.CustomLong1,
                    inventory.CustomLong2,
                    inventory.CustomLong3,
                    inventory.CustomLong4,
                    inventory.CustomLong5,
                    inventory.CustomLong6,
                    inventory.CustomLong7,
                    inventory.CustomLong8,
                    inventory.CustomLong9,
                    lc.ResourceLabel
                       }
                into grp
                where grp.Count() > 1
                select grp;

            var groups = new List<KeyValuePair<string,IEnumerable<InventoryResourceDTO>>>();

            foreach (var group in list)
            {
                groups.Add(new KeyValuePair<string, IEnumerable<InventoryResourceDTO>>(group.Key.ResourceLabel, group.OrderBy(x => x.ModifiedTimeStamp).ToList()));
            }

error occures in this line:
        groups.Add(new KeyValuePair<string, IEnumerable<InventoryResourceDTO>>(group.Key.ResourceLabel, group.OrderBy(x => x.ModifiedTimeStamp).ToList()));
    

stacktrace looks like this:

![image](https://user-images.githubusercontent.com/364896/88664202-021c9980-d0dd-11ea-8f15-a6d4ad342943.png)

**Comment by jogibear9988** [comment]
I'll look if I could create a reproducible scenario, but need to look how.

**Comment by sdanyliv** [comment]
This query also needs client side grouping.

**Comment by jogibear9988** [comment]
That meens? Why did it work before?

**Comment by sdanyliv** [comment]
Changed way how we handle such queries (EagerLoading). Fixing that is not current priority, since it is usually bad queries as in your sample.

**Comment by jogibear9988** [comment]
It means before the Update they were executed on Client Side or on Server Side?
How could we fix (haveing the same performance).
The switch to EagerLoading we could do later.

**Comment by sdanyliv** [comment]
Before it was very ineffective and intorduces N+1 queries. 
Rewrite your query
```cs
var query = from inventory in s.Query<InventoryResourceDTO>()
                join lc in s.Query<WmsLoadCarrierDTO>() on inventory.ResourceID equals lc.Id
                   join material in s.Query<MaterialDTO>() on inventory.MaterialID equals material.Id
            join infeeds in s.Query<InfeedAdviceDTO>() on inventory.InfeedAdviceID equals infeeds.Id into infeedList
            from infeed in infeedList.DefaultIfEmpty()
            where inventory.Status < InventoryResourceStatus.Finished
                  //&& !material.DontMerge
                  && inventory.ModifiedTimeStamp < DateTime.UtcNow - TimeSpan.FromHours(1)
                  && inventory.ProductionDate == null
                  && inventory.Unit != "m" && inventory.Unit != "M"
                  && (infeed == null || (infeed.Status >= InfeedAdviceStatus.Finished &&
                                         infeed.ModifiedTimeStamp < DateTime.UtcNow - TimeSpan.FromHours(1)))
            select new 
           {
                 inventory,
                 lc.ResourceLabel
           };

var materialized  = query.ToList();
var list = from q in materialized
group q.inventory by new
{
                q.inventory.Status,
                q.inventory.MaterialID,
                q.inventory.ResourceID,
                q.inventory.ExpiryDate,
                q.inventory.BatchNumber,
                q.inventory.Unit,
                q.inventory.QuantityPerBundle,
                q.inventory.BundleUnit,
                q.inventory.ProductStatus,
                q.inventory.ReasonForRestriction,
                q.inventory.RestrictionLabel,
                q.inventory.RestrictionText,
                q.inventory.ToHostStatus,
                q.inventory.CustomField1,
                q.inventory.CustomField2,
                q.inventory.CustomField3,
                q.inventory.CustomField4,
                q.inventory.CustomField5,
                q.inventory.CustomField6,
                q.inventory.CustomField7,
                q.inventory.CustomField8,
                q.inventory.CustomField9,
                q.inventory.CustomDate1,
                q.inventory.CustomDate2,
                q.inventory.CustomDate3,
                q.inventory.CustomDate4,
                q.inventory.CustomDate5,
                q.inventory.CustomDate6,
                q.inventory.CustomDate7,
                q.inventory.CustomDate8,
                q.inventory.CustomDate9,
                q.inventory.CustomLong1,
                q.inventory.CustomLong2,
                q.inventory.CustomLong3,
                q.inventory.CustomLong4,
                q.inventory.CustomLong5,
                q.inventory.CustomLong6,
                q.inventory.CustomLong7,
                q.inventory.CustomLong8,
                q.inventory.CustomLong9,
                q.ResourceLabel
}
into grp
            where grp.Count() > 1
            select grp;
```

**Comment by sdanyliv** [comment]
Anyway create small reproducible case. Not a ton of classes and complex query please.

**Comment by jogibear9988** [comment]
Yes, I will do... But takes time

**Comment by jogibear9988** [comment]
I've now created the same code as a test in linq2db...

But here it works...

https://github.com/linq2db/linq2db/pull/2379

don't know whats different on our solution...

**Comment by jogibear9988** [comment]
Could it be cause no data is inside of the tables?

**Comment by sdanyliv** [comment]
If exception in mapper. Data is important.

**Comment by jogibear9988** [comment]
Okay, look to fill the test with data.

Maybe someone can help me quickly.

I added data to the test, but when inserting, I get this error:

LinqToDB.Linq.LinqException: ''value(Tests.UserTests.Issue2375Tests+<>c__DisplayClass6_0).res' cannot be converted to SQL.'

in this line: https://github.com/linq2db/linq2db/pull/2379/files#diff-4e28bf75a18e743b8075ad90c263a365R141

**Comment by sdanyliv** [comment]
```cs
db.Insert(res);
```

**Comment by jogibear9988** [comment]
@sdanyliv I've now created a test wich shows the issue. Work's in sqlite but fails in postgres during mapping.

System.InvalidCastException : Can't write CLR type Tests.UserTests.Issue2375Tests+InventoryResourceStatus with handler type Int32Handler

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/88849936-e7384b00-d1ea-11ea-8466-d1df13373058.png)
