### ISSUE TITLE
Linq2db update to 3.x - Postgres Bulk Insert throws error

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2376]
We get now following exception:

08P01: insufficient data left in message

It seems in Postgres we need to use WriteNull instead of Write:

https://stackoverflow.com/questions/37431054/08p01-insufficient-data-left-in-message-for-nullable-datetime

We used following code:

                        var ret = 
                        DataConnection.BulkCopy(new BulkCopyOptions
                        {
                            CheckConstraints = true,
                            BulkCopyType = BulkCopyType.ProviderSpecific,
                            MaxBatchSize = 5000,
                            UseInternalTransaction = false,
                            NotifyAfter = 2000,
                            BulkCopyTimeout = 0,
                            RowsCopiedCallback = i =>
                            {
                                if (insertObjects.Count > 1000)
                                    TraceSystem.Instance.Info("DB", "Large insert of " + typeof(TX).Name + " - inserted " + i.RowsCopied + " of " + insertObjects.Count);
                            }
                        }, insertObjects);

**Comment by jogibear9988** [comment]
WriteNull is not enough.... I've implemented it but it does still not work

**Comment by jogibear9988** [comment]
Anyone a Idea how I can debug why it does not work?

**Comment by MaceWindu** [comment]
\0 character in string data? https://stackoverflow.com/a/47436417

**Comment by MaceWindu** [comment]
To debug, remove columns to detect failing column, and then identify failing record

**Comment by jogibear9988** [comment]
I've found the failing column. It's a nullable int.
If it is null it works, If it is not null it fails.
I look to create a test.

**Comment by MaceWindu** [comment]
which type database column use?

**Comment by jogibear9988** [comment]
bigint

**Comment by jogibear9988** [comment]
maybe bigit does not work wenn c# type is int?

**Comment by MaceWindu** [comment]
Sounds like valid error for me in this case. int is 4 bytes and bigint is 8 bytes.
So server expects 4 more bytes from client.
Maybe if you can add type hint to column mapping it will work, but it is not good idea to use int here as for me.

**Comment by viceroypenguin** [comment]
I know w/ SQL Server, Bulk Copy does not allow for automatic type conversions (including int -> bigint). All types have to be exactly what they are in the column. May be true in PostgreSQL too? Try changing type in model to bigint/long instead?

**Comment by MaceWindu** [comment]
In general npgsql bulk copy is very picky regarding types (compared to regular sql), so you shouldn't expect it to work if db types doesn't match client type.

**Comment by jogibear9988** [comment]
I tested now, Problem is bigint type.

**Comment by MaceWindu** [comment]
@viceroypenguin yep, I wrote about it long time ago here https://linq2db.github.io/articles/sql/Bulk-Copy.html#postgresql-provider-specific-bulk-copy

**Comment by jogibear9988** [comment]
But I thought we also used Bulk Insert with v2.x and there it worked?
Was something changed in BulkCopy for Postgres?

**Comment by viceroypenguin** [comment]
@MaceWindu everything you wrote in there is true for SQL Server too, FYI

**Comment by MaceWindu** [comment]
We have no changes to this functionality in 3.0 so if it is really worked, probably something changed in inference of `NpgsqlDbType` for column. That's why I suggested to add some kind to type hint to mapping to check. E.g. DbType = "bigint"

**Comment by MaceWindu** [comment]
Anyway, if type inferrence regressed, we need to know exact mapping for failing column to reporduce it and identify why it worked before and wether it's bug or not

**Comment by jogibear9988** [comment]
I'll look that I could debug why it worked before.

**Comment by jogibear9988** [comment]
So I think it did work, cause we did not fill the values.
So I close it.
