### ISSUE TITLE
LinqToDB.Data.DataConnection ExecuteMethodCall

### ISSUE THREAD

**Issue by toSilence** [linq2db/linq2db#238]
Hi,

i'm trying to implement this library into an existing project to use linq with sqlite.
I recognised that the method 'ExecuteMethodCall' is missing (from the DataConnection class) which is available in .net framework context. We use this method for executing a stored procedure.
Now my question is this functionality missing or perhaps is the method name different because i couldn't find it.

Any help appreciate.

Thx in advance

**Comment by igor-tkachev** [comment]
THere are the ExecuteProc/QueryProc methods.
