### ISSUE TITLE
Is possible to Reload object by PK?

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2384]
Hi Linq2Db!

Is it possible to do the reload of the object by PK?
Something like this db.Reload(obj);

Indeed, methods ```db.Update(obj), db.Delete(obj), db.InsertOrReplace(obj)``` automatically generates SQL with filter by PK.
I need this for SQL select (automatically filter by PK).

I cannot use "Find" method extension, because I need to reload object in common code and the type of object is unknown.

Could you provide me, what the best way for implementing this (workaround)?
Thank you in advance!

**Comment by sdanyliv** [comment]
Do you still need solution?

**Comment by AndrePScope** [comment]
Thank you, @sdanyliv!
I made some workaround, but it looks really not good. 

I closed the issue because do not want to waste your time and because workaround created (even this workaround is not good).

But yes! I am still very interested in your suggestion.

**Comment by sdanyliv** [comment]
Enjoy, probably we have include such function in Tools.
```cs
	public static class DataContextExtensions
	{
		private static MemoryCache _cache = new MemoryCache(new MemoryCacheOptions());

		public static void Reload<T>(this IDataContext dc, T obj)
			where T : class
		{
			Reload(dc, obj, dc.GetTable<T>());
		}

		public static void Reload<T>(this IDataContext dc, T obj, ITable<T> table)
		{
			var key = Tuple.Create(typeof(T), dc.MappingSchema.ConfigurationID);
			var loadFunc = _cache.GetOrCreate(key, ce => CreateReloadFunc<T>(dc.MappingSchema));
			loadFunc?.Invoke(dc, obj, table);
		}

		static Action<IDataContext, T, ITable<T>>? CreateReloadFunc<T>(MappingSchema ms)
		{
			var entityDescriptor = ms.GetEntityDescriptor(typeof(T));
			var pks = new List<ColumnDescriptor>();
			var toLoad = new List<ColumnDescriptor>();
			foreach (var column in entityDescriptor.Columns)
			{
				if (column.IsPrimaryKey)
					pks.Add(column);
				else if (column.MemberAccessor.HasSetter)
					toLoad.Add(column);
			}

			if (pks.Count == 0)
				throw new Exception($"Type '{typeof(T).Name}' has no primary key defined.");
			if (toLoad.Count == 0)
				return null;

			var queryParam = Expression.Parameter(typeof(T), "q");
			var destParam = Expression.Parameter(typeof(T), "dest");


			Expression predicate = null!;
			foreach (var pk in pks)
			{
				var equal = Expression.Equal(Expression.MakeMemberAccess(queryParam, pk.MemberInfo),
					Expression.MakeMemberAccess(destParam, pk.MemberInfo));
				if (predicate == null)
					predicate = equal;
				else
				{
					predicate = Expression.AndAlso(predicate, equal);
				}
			}

			predicate = Expression.Lambda(predicate, queryParam);

			var dcParam = Expression.Parameter(typeof(IDataContext));
			var tableParam = Expression.Parameter(typeof(ITable<T>));

			var query = Expression.Call(Methods.Queryable.Where.MakeGenericMethod(typeof(T)), tableParam, predicate);
			query = Expression.Call(Methods.Queryable.AsEnumerable.MakeGenericMethod(typeof(T)), query);
			query = Expression.Call(Methods.Enumerable.First.MakeGenericMethod(typeof(T)), query);

			var generator = new ExpressionGenerator();
			var loaded = generator.AssignToVariable(query, "loaded");

			var initExpressions = toLoad.Select(c =>
				Expression.Assign(Expression.MakeMemberAccess(destParam, c.MemberInfo),
					Expression.MakeMemberAccess(loaded, c.MemberInfo)));

			foreach (var initExpression in initExpressions)
			{
				generator.AddExpression(initExpression);
			}


			var lambda =
				Expression.Lambda<Action<IDataContext, T, ITable<T>>>(generator.Build(), dcParam, destParam,
					tableParam);

			return lambda.Compile();
		}
	}

```

**Comment by AndrePScope** [comment]
Hi @sdanyliv !
Many-many thanks for your help and the solution!!!

**Your code works well!**
I would ask some clarifying questions...

The first question. My linq2db version (3.0.1) does not know dc.MappingSchema.ConfigurationID.

![image](https://user-images.githubusercontent.com/30083441/89103211-b6d5f400-d418-11ea-97c3-66e9b7aa28e6.png)
(I corrected this how I guess, but maybe you know how it will better...)

The second, when the select does not return the object, I got exception "Sequence contains no elements". 
Probably this is Ok. Maybe the result of method Reload (true/false) also looks ok...

So, I can adapt this code. I just want to say many-many thanks! :) 
As for me, to have Reload in base functionality will be super!

**Comment by sdanyliv** [comment]
You can use FirstOrDefault. Yes ConfigurationID is hidden, if you have problem with finding better alternative I can look at.
I think you've got an idea and can correct expression ;)
Usually I recommend this extension to analyze what is generated: [ReadableExpressions](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers)
