### ISSUE TITLE
Add more `IAsyncEnumerable<T>` support

### ISSUE THREAD

**Issue by viceroypenguin** [linq2db/linq2db#2386]
Placeholder for need to add support for `IAsyncEnumerable<T>` support.

**Comment by MaceWindu** [comment]
@viceroypenguin could you be more specific with it? :smile:

**Comment by viceroypenguin** [comment]
@MaceWindu - was further discussed [here](https://github.com/linq2db/linq2db/wiki/Async-API-Style-Guidelines-%5BIN-PROGRESS%5D) and then dropped.  At some point, we should clarify interests and formalize tasks into this issue.

**Comment by MaceWindu** [comment]
Better to open specific issue/feature requests or PR as it currently doesn't contain any details.
