### ISSUE TITLE
Problem with Merge operation when using interfaces

### ISSUE THREAD

**Issue by BetterThanNothing** [linq2db/linq2db#2388]
Hello there!

This code on previous version worked fine (I've tested 3.0.0 preview.2):

```cs
public ITable<IReviewIndex> ReviewIndexes => GetTable<ReviewIndex>();
...

await db.ReviewIndexes
    .Merge()
    .Using(items)
    .On(x => new { x.Index, x.Date }, x => new { x.Index, x.Date })
    .UpdateWhenMatched()
    .InsertWhenNotMatched()
    .MergeAsync();
```
Now with version 3.0.0 and later it failed with wrong mapping error System.ArgumentException Property 'System.Decimal Value' is not defined for type 'Finam.Interfaces.Data.Entities.Comon.IReviewIndex' (Parameter 'property')

Mappings declared in ReviewIndex class which implements IReviewIndex interface. Other operations (select, insert, delete etc) work as expected.

### Environment details
linq2db version: 3.0.1
Database Server: MS SQL Server
Database Provider: MSSQL
Operating system: Windows 10
.NET Framework: .NET Core 3.0

**Comment by sdanyliv** [comment]
For fix problem we need reproducible case. Post your model, interface and mapping.

**Comment by BetterThanNothing** [comment]
IReviewIndex.cs
`
public interface IReviewIndex
{
	DateTime Date { get; set; }
	int Index { get; set; }
	decimal Value { get; set; }
	bool Ctime { get; set; }
	DateTime? DateMsk { get; set; }
	double? Change { get; set; }
	short? Decp { get; set; }
}
`

ReviewIndex.cs
`
[Table(Schema = "dbo", Name = "ReviewIndexes")]
public class ReviewIndex: IReviewIndex
{
	[Column(Name = "date", IsPrimaryKey = true)]
	public DateTime Date { get; set; }

	[Column(Name = "idx", IsPrimaryKey = true)]
	public int Index { get; set; }

	[Column("value")]
	public decimal Value { get; set; } 
		
	[Column("ctime")]
	public bool Ctime { get; set; }
	
	[Column("date_ta_msk")]
	public DateTime? DateMsk { get; set; }

	[Column("chg")]
	public double? Change { get; set; }

	[Column]
	public short? Decp { get; set; }
}
`

Method call
`
public async Task ImportIndex(IEnumerable<IReviewIndex> items)
{
	using (var db = new DbTest())
	{
		await db.ReviewIndexes
			.Merge()
			.Using(items)
			.On(x => new { x.Index, x.Date }, x => new { x.Index, x.Date })
			.UpdateWhenMatched()
			.InsertWhenNotMatched()
			.MergeAsync();
	}
}
`
