### ISSUE TITLE
Hana Linq Query failed - cant load Sap.Data.Hana.dll

### ISSUE THREAD

**Issue by rabbers** [linq2db/linq2db#239]
Started looking at HANA for a project and downloaded Linq2db. Set up a query string, managed to create a small test Context, opened a connection all fine.

When trying to execute a LINQ query, I get a crash suggesting that 'Sap.Data.Hana' could not be found.

Although my Provider IS 'Sap.Data.Hana' and the Connection class can open a connection, my assembly is actually called 'Sap.Data.Hana.v4.5', straight from the Hana client install.

I guess that something is trying to instantiate a type by looking for the assembly name - either the object type needs to be grabbed from the connection or the assembly name similarly grabbed from the connection or providers table or something.

Apologies, my code is not available to me right now, I'm just hoping that somebody just knows what it is. I may be able to post example later when I pick up my laptop.

**Comment by rabbers** [comment]
There's still an issue here, but I've had a chance to look into it and found out a workaround.

Effectively, the AssemblyName is worked out in SapHanaTools constructor. It's done by searching the Assembly codebase folder for "Sap.Data.Hana.dll" and then "Sap.Data.Hana.v4.5.dll".

The answer to my problem, and therefore the workaround for this issue is to set 'copy local' to true in the 'Sap.Data.Hana.v4.5' reference properties, which ensures that the dll is copied to the project output folder. If the Sap.Data.Hana.dll file is distributed with the application then there should be no problem.

There should still be a way of loading the same assembly used in the connection though. I'm not sure how to do that though.

Mark

**Comment by fraillt** [comment]
Hello,
Am, glad to see that someone is finally using Sap.Hana provider at last.

Regarding your problem since linq2db library supports many databases, you can't simply build library using native DBConnections to all databases at compile time.
So the most elegant solution is to explicitly load DataProvider at runtime.

There are some performance problems with Ado.Net Sap.Hana drivers though (as of 1.0.90v) it seems that Ado.Net drivers create proxy connection on server itself, so as a "bonus" all state changes must go to server, and it is quite a big issue when server is not the same machine as application, which is definitely the case :)

For this reason I created SapHanaOdbcDataProvider, it works much better, except that you cannot use native BulkCopy functionality with it.

You can create base DataConnection that use Odbc drivers [like this](https://gist.github.com/fraillt/0a9fdfc50e83a86fe145)

**Comment by FabioNascimento** [comment]
Hello,

I`m using HANA provider too and I have the same issue. When I use SapHanaOdbcDataProvider linq2db throw the same erro... 

I`m using the other way to create Connection, https://github.com/schambers/fluentmigrator/blob/master/src/FluentMigrator.Runner/Processors/Hana/HanaProcessorFactory.cs#L11

I this way I don't need to add references of hana in my project.

**Comment by FabioNascimento** [comment]
I changed to ODBC and working better, cause the lib bind to my app maybe diferente in client of prodution invite and de HANA client throw exception...

Here instruction to make connection string to HanaOdbcProvider .. 
http://help.sap.com/saphelp_hanaplatform/helpdata/en/66/a4169b84b2466892e1af9781049836/content.htm

**Comment by ili** [comment]
Is it still actual?

**Comment by fraillt** [comment]
I'm afraid, but I no longer have access to SapHana servers and cannot maintain this, but if thing has changed, then you must explicitly copy sap hana dll by making "copy local" in reference properties.
The magic happens in SapHanaTools.cs  file, it will search application runtime directory for files like 
Sap.Data.Hana.dll or Sap.Data.Hana.v4.5.dll, if sap hana has new version and file name has changed, either fix SapHanaTools and contribute :)

**Comment by ili** [comment]
@fraillt thanks

So I'm closing issue for now

**Comment by FabioNascimento** [comment]
The problem still happing with me.  

After I copied the assembly to directory occurred other problem the version of Assembly should be the same of client of HANA. Then I changed de code that got Assembly of the GAC and everthing work fine for me.

I will be provide a merge request to this.

**Comment by FabioNascimento** [comment]
Link of Express Version of HANA : https://www.sap.com/developer/topics/sap-hana-express.html

**Comment by sdanyliv** [comment]
@FabioNascimento, great i'll try to setup our DBHost virtual machine to handle SAP Hana unit tests.

**Comment by FabioNascimento** [comment]
I think it can closed because in the 1.9.0 doesn't happen anymore.

**Comment by MaceWindu** [comment]
Closing, ask for reopen if you still get it on latest bits
