### ISSUE TITLE
Asp.Net Core 3.1 LinqToDB.Identity UserManager CreateAsync Error

### ISSUE THREAD

**Issue by dogaanismail** [linq2db/linq2db#2400]
I have implemented LinqToDB.Identity into my project. I have been trying to create a user by using .Net Identity UserManager, but I am getting an error. I have also implemented LinqToDB.Identity optimizations, such as AddLinqToDBStores and IdentityConnectionFactory.

As I have mentioned about it, I am getting an error like this when I try to create an user.

{"Method not found: 'Int32 LinqToDB.DataExtensions.Insert(LinqToDB.IDataContext, System.__Canon, System.String, System.String, System.String)'."}

Here is an image that shows the error.

https://i.stack.imgur.com/8oZ98.png

Here is my AddLinqToDBStores options and configurations.

    `    public static void AddDevPlatformAuthentication(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddIdentity<AppUser, LinqToDB.Identity.IdentityRole<int>>(options =>
            {
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 4;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
                options.Password.RequireLowercase = false;

                options.User.RequireUniqueEmail = true;

                //TODO
                //options.User.RequireUniqueEmail = true; 
                //options.SignIn.RequireConfirmedEmail = true;
                //options.Lockout.MaxFailedAccessAttempts = 5;
                //options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(3);

            }).AddLinqToDBStores<int, AppUserClaim, AppUserRole, AppUserLogin, AppUserToken, AppRoleClaim>(new
            IdentityConnectionFactory(new SqlServerDataProvider(ProviderName.SqlServer, SqlServerVersion.v2017), "SqlServerIdentity", DataSettingsManager.LoadSettings().ConnectionString))
                .AddDefaultTokenProviders();

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie();

            // Uncomment the following lines to enable logging in with third party login providers

            JwtTokenDefinitions.LoadFromConfiguration(configuration);
            services.ConfigureJwtAuthentication();
            services.ConfigureJwtAuthorization();
        }`

Here is my IdentityConnectionFactory class that has inherited from IConnectionFactory interface.

    `public class IdentityConnectionFactory : IConnectionFactory
     {
        private static readonly Dictionary<string, HashSet<string>> _tables = new Dictionary<string, HashSet<string>>();
        private readonly string _configuration;
        private readonly string _connectionString;
        private readonly string _key;
        private readonly IDataProvider _provider;

    public IdentityConnectionFactory(IDataProvider provider, string configuration, string connectionString)
    {
        _provider = provider;
        Configuration.Linq.AllowMultipleQuery = true;
        //DataConnection.AddConfiguration(configuration, connectionString, provider);
        _configuration = configuration;
        _connectionString = connectionString;
        _key = _configuration + "$$" + _connectionString;
    }
    public IDataContext GetContext()
    {
        return new DataContext(_provider, _connectionString);
    }

    public DataConnection GetConnection()
    {
        var db = new DataConnection(_provider, _connectionString);
        db.AddMappingSchema(AdditionalSchema);

        return db;
    }

    protected MappingSchema AdditionalSchema
    {
        get
        {
            if (!(Singleton<MappingSchema>.Instance is null))
                return Singleton<MappingSchema>.Instance;

            Singleton<MappingSchema>.Instance =
                new MappingSchema(_provider.Name) { MetadataReader = new FluentMigratorMetadataReader() };

            return Singleton<MappingSchema>.Instance;
        }
    }`

Here is my Register api that can be used to create an user by using UserManager.

    `  public async Task<JsonResult> Register([FromBody] RegisterApiRequest model)
        {
            try
            {
                if (model.RePassword != model.Password)
                {
                    return BadResponse(ResultModel.Error("Repassword must match password"));
                }

                AppUser userEntity = new AppUser
                {
                    UserName = model.UserName,
                    Email = model.Email,
                    CreatedDate = DateTime.Now,
                    DetailId = 1
                };

                IdentityResult result = await _userManager.CreateAsync(userEntity, model.Password);
                if (!result.Succeeded)
                {
                    Result.Status = false;
                    Result.Message = string.Join(",", result.Errors.Select(x => x.Description));
                    return BadResponse(Result);
                }
                return OkResponse(Result);
            }
            catch (Exception ex)
            {
                Result.Status = false;
                Result.Message = ex.ToString();
                return BadResponse(Result);
            }
        }`

There are so many code blocks that I can not paste here. I would be very happy if someone could help.

If you would like to see the project, you can check here;

https://github.com/dogaanismail/DevPlatform

I have asked this question on Stackoverflow. Here is the link.

https://stackoverflow.com/questions/63326498/asp-net-core-3-1-linqtodb-identity-usermanager-createasync-error

Any help would be appreciated!

### Environment details
linq2db version: *v3.0.1*
Database Server: *Microsoft Sql Server*
Database Provider: *SqlServerDataProvider*
Operating system: *Windows 10*
.NET Framework: *.Net Core 3.1*

**Comment by sdanyliv** [comment]
Could you provide full exception stack trace?

**Comment by dogaanismail** [comment]
Hello,

Here you are, sir. @sdanyliv 

"System.MissingMethodException: Method not found: 'Int32 LinqToDB.DataExtensions.Insert(LinqToDB.IDataContext, System.__Canon, System.String, System.String, System.String)'.\r\n   at LinqToDB.Identity.Extensions.TryInsertAndSetIdentity[T](IDataContext db, T obj)\r\n   at LinqToDB.Identity.UserStore`7.<>c__DisplayClass48_0.<CreateAsync>b__0()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at LinqToDB.Identity.UserStore`7.CreateAsync(DataConnection db, TUser user, CancellationToken cancellationToken)\r\n   at LinqToDB.Identity.UserStore`7.CreateAsync(TUser user, CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user)\r\n   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)\r\n   at DevPlatform.Api.Controllers.AccountController.Register(RegisterApiRequest model) in D:\\Projects\\DevPlatform\\DevPlatform.Api\\Controllers\\AccountController.cs:line 56"

**Comment by sdanyliv** [comment]
Looking at `TryInsertAndSetIdentity` and can not find anything criminal here
https://github.com/linq2db/LinqToDB.Identity/blob/master/src/LinqToDB.Identity/Extensions.cs#L19

Clone linq2db sources and add LinqToDB.csproj to to you solution. Then correct reference to this project. Then you will be able to debug linq2db with your solution.

**Comment by dogaanismail** [comment]
Hello sir,

First of all, thank you for your help. I would like to say that I do not try to find anything that is criminal. I just need some help to improve my  LinqToDB and LinqToDB.Identity skills. 

I did your instructions and I am able to debug LinqToDB.Identity. There is a different error message now. 

In TryInsertAndSetIdentity function;

Microsoft.Data.SqlClient.SqlException: 'Cannot insert explicit value for identity column in table 'AppUser' when IDENTITY_INSERT is set to OFF.'

"Cannot insert explicit value for identity column in table 'AppUser' when IDENTITY_INSERT is set to OFF."

This exception was originally thrown at this call stack:
    [External Code]
    DevPlatform.LinqToDB.Identity.Extensions.TryInsertAndSetIdentity<T>(LinqToDB.IDataContext, T) in Extensions.cs
    DevPlatform.LinqToDB.Identity.UserStore<TKey, TUser, TRole, TUserClaim, TUserRole, TUserLogin, TUserToken>.CreateAsync.AnonymousMethod__0() in UserStore.cs
    [External Code]

      ` using DevPlatform.Core.Entities;
        using DevPlatform.LinqToDB.Identity;
        using System;
        using System.ComponentModel.DataAnnotations;
        using System.ComponentModel.DataAnnotations.Schema;

       namespace DevPlatform.Core.Domain.Identity
        {
        public class AppUser : IdentityUser<int>, IEntity
      {
         [Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
         [Key]
        public override int Id { get => base.Id; set => base.Id = value; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }

        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
        public int? StatusId { get; set; }

        [Required]
        [ForeignKey("UserDetail")]
        public int DetailId { get; set; }

        public virtual AppUserDetail UserDetail { get; set; }
    }
}`



StackTrace

"   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(IDbCommand cmd)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery()\r\n   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()\r\n   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass33_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.Insert`1.Query(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName)\r\n   at DevPlatform.LinqToDB.Identity.Extensions.TryInsertAndSetIdentity[T](IDataContext db, T obj) in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\Extensions.cs:line 25\r\n   at DevPlatform.LinqToDB.Identity.UserStore`7.<>c__DisplayClass48_0.<CreateAsync>b__0() in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\UserStore.cs:line 1024\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)"
  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(IDbCommand cmd)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery()\r\n   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()\r\n   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass33_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.Insert`1.Query(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName)\r\n   at DevPlatform.LinqToDB.Identity.Extensions.TryInsertAndSetIdentity[T](IDataContext db, T obj) in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\Extensions.cs:line 25\r\n   at DevPlatform.LinqToDB.Identity.UserStore`7.<>c__DisplayClass48_0.<CreateAsync>b__0() in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\UserStore.cs:line 1024\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)" | string


  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(IDbCommand cmd)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery()\r\n   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()\r\n   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass33_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.Insert`1.Query(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName)\r\n   at DevPlatform.LinqToDB.Identity.Extensions.TryInsertAndSetIdentity[T](IDataContext db, T obj) in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\Extensions.cs:line 25\r\n   at DevPlatform.LinqToDB.Identity.UserStore`7.<>c__DisplayClass48_0.<CreateAsync>b__0() in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\UserStore.cs:line 1024\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)" | string



  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(IDbCommand cmd)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)\r\n   at LinqToDB.Data.DataConnection.ExecuteNonQuery()\r\n   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()\r\n   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass33_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)\r\n   at LinqToDB.Linq.QueryRunner.Insert`1.Query(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName)\r\n   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName)\r\n   at DevPlatform.LinqToDB.Identity.Extensions.TryInsertAndSetIdentity[T](IDataContext db, T obj) in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\Extensions.cs:line 25\r\n   at DevPlatform.LinqToDB.Identity.UserStore`7.<>c__DisplayClass48_0.<CreateAsync>b__0() in D:\\Projects\\DevPlatform\\DevPlatform.LinqToDB.Identity\\UserStore.cs:line 1024\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)" | string

**Comment by sdanyliv** [comment]
I see some mix of EF and linq2db.
DatabaseGenerated(DatabaseGeneratedOption.Identity) is not linq2db attribute.
Try to use [Identity] attribute instead.
Sorry it's to late here and I'm just giving ideas without trying them.
Method not found exception means that some reflection code is used in exception path, that's why I've mentioned that I have not found anything "criminal" in code.

**Comment by dogaanismail** [comment]
The problem has been solved thanks to you! Thank you very much. 

Best Regards

**Comment by sdanyliv** [comment]
Can we close issue?

**Comment by dogaanismail** [comment]
Sure, you can close the issue. Thanks a lot for your help.

Best Regards
