### ISSUE TITLE
Query cache not respecting linq settings?

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2401]
could it be an issue that the query chache does not respect the linq settings in 

      Configuration.Linq

specially I tried the setting:

     Configuration.Linq.DoNotClearOrderBys

**Comment by jogibear9988** [comment]
I'll look to create a test.
Or is this desired behavior?

**Comment by sdanyliv** [comment]
It is bad to change global configuration on the fly. But if you want you can create PR with similar fix
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Query.cs#L474-L482

**Comment by jogibear9988** [comment]
I only do it in a Test. :-)
I‘ll take a look

**Comment by MaceWindu** [comment]
Should be fixed by #3530
