### ISSUE TITLE
CTE for groups

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2402]
I have the following entities (1-to-many => 1 Car can have multiple tyres)

```c#
public class Car 
{
      public int Id {get;set;}
      public int Value {get;set;}
      public ICollection<Tyre> Tyres {get;set;}
}

public class Tyre 
{
       public int Id {get;set;}
       public int Size {get;set;}
       ...
}
```

The class for the query result is:

```c#
public class CarInfo 
{
     public int Value {get;set;}
     public IEnumerable<Tyre> Tyres {get;set;}
}
``` 

I receive a condition data structure for filtering according to CarInfo. For example I convert
Pseudo:  (property = "Value", isEqual, 2)    OR ( "Value", isEqual, 5)
to expressions which works very fine. The result is put into a Where and it works.

Result:   
```c#
var lambda = getLambda(...);
myQuery.Where(lambda); // works
```

Now I want to query like: "Give me all CarInfo including the tyres with Size 1 AND Size 2" without restructuring the condition data structure I receive. For that I receive Pseudo (property="Tyres.Size", isEqual, 1) AND (property="Tyres.Size", isEqual, 2)

I do not put the data structure for the conditions in here because it is not necessary for understanding.

Now the question:
Can I search within the car groups by using AND in Linq2Db?

**Comment by sdanyliv** [comment]
Pseudo code does not help at all. I assume you need eager loading
```cs
var carQuery = db.GetTable<Car>();
carQuery = carQuery.Where(lambda);

var resultQuery = carQuery.Select(c => new CarInfo 
{ 
   Value = c.Value, 
   Tyres = c.Tyres.Where(t => t.Size.In(1, 2)).ToArray()
});
```

**Comment by HypeillingerChillinger** [comment]
Well, I'm thinking of CTE but I am not sure how. I'm searching for a possibility to not adjust the created lambda in the where method.

I use the following model and query 

```c#
public class MyModel
{
       public Car Car {get;set;}
       public Tyre Tyre {get;set;}
}

var query = (from car in context.Cars
from tyre in context.Tyres.Where(x => x.CarId == car.Id) select new MyModel{car, tyre});

//For the OR version there is no problem: 
from filtered in query.Where(x => x.Tyre.Size == 1 || x.Tyre.Size == 2).Select(x => x.Car.Id).Distinct()
from cars in query.Where(x => x.Car.Id == filtered)
select cars);
// followed by grouping with projection it is working fine

// but how can I do the AND by putting my lambda in a where method?
// works of course not out of the box with denormalized CarInfo

```

**Comment by sdanyliv** [comment]
Still unclear. Possible you need way of injecting lambda in query?
```cs
var lambda = getLambda(...);

from filtered in query.Where(x => (x.Tyre.Size == 1 || x.Tyre.Size == 2) && lambda.Compile()(x))
   .Select(x => x.Car.Id).Distinct()
from cars in query.Where(x => x.Car.Id == filtered)
select cars);
```

**Comment by HypeillingerChillinger** [comment]
I guess it is more a pivot problem may be. The result of
```c#
.Where(x => x.Tyre.Size == 1 && x.Tyre.Size == 2)
```
is of course always false since I am looking at one row but I'd like to do that where over the group
Car 1 Tyre 1 (Size 1)
Car 1 Tyre 2 (Size 2)
Car 1 Tyre 3 (Size 3)

Result with where above should be: All three rows

**Comment by sdanyliv** [comment]
Let's start from SQL which you expect. It it is PIVOT, it is not supported yet. If not - we can create linq query dynamically.

**Comment by HypeillingerChillinger** [comment]
Actually I am not sure. Can we use a pseudo pivot with CTE? I am not an expert in SQL - I have no suggestion.

**Comment by jogibear9988** [comment]
why closed?
