### ISSUE TITLE
OracleProvider: add Materialized Views to OracleSchemaProvider.GetTables 

### ISSUE THREAD

**Issue by lytico** [linq2db/linq2db#2404]
OracleProvider does't add Materialized Views to Tables

### Steps to reproduce
OracleSchemaProvider.GetTables 
gives back only Tables and Views, but not Materialized Views

see also: https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_1105.htm#REFRN20139

### Environment details
linq2db version: all
Database Server: Oracle
Database Provider: Oracle
Operating system: all
.NET Framework: all

### Pull-Request

if you are interested, i'll add a Pull Request

**Comment by sdanyliv** [comment]
> if you are interested, i'll add a Pull Request

Always appreciated

**Comment by sdanyliv** [comment]
If you can do that until 20th august it will be available in the next release.

**Comment by lytico** [comment]
ok, i managed it before:

https://github.com/linq2db/linq2db/pull/2410
