### ISSUE TITLE
Nullable column with non-nullable reference value

### ISSUE THREAD

**Issue by Jevonius** [linq2db/linq2db#2409]
Hi,

A small request for advice rather than an issue - I'm not sure if what I want to do is possible, but if I can find a way to make it work it will allow me to avoid a large refactor I don't want to do [yet]. I did some searching but couldn't find anything obvious.

Say I have a hypothetical database table:
```sql
CREATE TABLE [dbo].[MyEntity] (
    [Id]             INT   NOT NULL IDENTITY,
    [EntityTypeId]   INT   NOT NULL,
    [ForeignKeyId]   INT   NULL
    CONSTRAINT [FK_MyEntity_ForeignKey] FOREIGN KEY ([ForeignKeyId]) REFERENCES [dbo].[OtherThing] ([Id])
);
```

And an object:
```c#
public class MyEntity {
    public int Id {get;set;}
    public EntityType EntityTypeId {get;set;}
    public int ForeignKeyId {get;set;}
}
```

Note that ForeignKeyId is nullable in the database (the change I wish to make) but not in the class.

Is there a way to use Fluent Mapping, and default values, such that if `ForeignKeyId == default`, `NULL` is inserted into the column rather than 0 (which would be rejected because of the foreign key)?

I am trying to introduce a new EntityType that doesn't require the ForeignKeyId value (among various other columns), without changing the MyEntity class definition to `public int? ForeignKeyId {get;set;}` as this has implications in a lot of other areas I otherwise don't need to touch for the new type to work.

Thanks for any pointers!

**Comment by MaceWindu** [comment]
Looks like you need to apply value converter to your column https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273

**Comment by Jevonius** [comment]
Thanks for the reply - I'd forgotten about those! I think I can make it work with them, although if there was a variant of `HasConversion` that provided the whole object it would have been cleaner (in my case, I only want it to be nullable for one value of EntityType) - can see why this isn't possible though, the provider->model part gets complex.

My alternative is to have a second variant of `MyEntity` 'internal' to my my data access that had the value as nullable and switch to it when saving. The conversion method is simpler/cleaner though, even if the behaviour is slightly different.

**Comment by sdanyliv** [comment]
Check `HasSkipValuesOnInsert` and `HasSkipValuesOnUpdate`

**Comment by Jevonius** [comment]
Going to close this issue - the `HasConversion` functionality would have done the job nicely (I tested it and got it working). I ended up going with the second internal `MyEntity` variant as this had the added bonus of allowing me to ensure all other values were cleared to known default values when saving the saving (albeit with another class to maintain/keep in sync with the 'standard' one.

Thanks for the pointers (and linq2db in the first place!)
