### ISSUE TITLE
Lazy<DbContext> does not work on two consecutive queries?

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#2417]
This is not related to linq2db itself but probably it's due to my misunderstanding how `Lazy<T>` works.

I have `public class Manager : IDisposable`. Inside class I have private property `private Lazy<DbContext> Context => new Lazy<DbContext>();`. All methods in this class uses `Context.Value` to access database to insert, update or select entities. It works but...

### Option 1 (not working)
In one of my methods I have two consecutive queries (insert single entity and select all entities). I've discovered that `temp` field doesn't receive recently inserted object. There is no `sector` object inside `temp` list.
```
await Context.Value.InsertAsync(sector).ConfigureAwait(false);
var temp = await Context.Value.GetAllSectors().ToListAsync().ConfigureAwait(false);
```

### Option 2 (working)
So I added 500 ms delay between inserting and selecting like below and this helped. `sector` is inside `temp`. What's interesting that 400 ms is NOT enough. The good time is somewhere between 400 and 500 ms... 
```
await Context.Value.InsertAsync(sector).ConfigureAwait(false);
await Task.Delay(500).ConfigureAwait(false);
var temp = await Context.Value.GetAllSectors().ToListAsync().ConfigureAwait(false);
```

### Option 3 (working)
Then I checked another approach by asking for identity. Between inserting and selecting `SELECT @@IDENTITY` is executed. This also helped. `Id` from `IDENTITY` is correct.
```
await Context.Value.InsertWithInt32IdentityAsync(sector).ConfigureAwait(false);
var temp = await Context.Value.GetAllSectors().ToListAsync().ConfigureAwait(false);
```

### Option 4 (working)
Then I created connection in typical way using `using` statement and `select` - of course - returns inserted entity.
```
using (var db = new DbContext())
{
    await db.InsertAsync(sector).ConfigureAwait(false);
    var temp = await db.GetAllSectors().ToListAsync().ConfigureAwait(false);
}
```
### For not working option 1:
I used `Stopwatch` to check times after inserting (before selecting) and after selecting:
* before insert = 0
* after insert, before select = 0.062 s
* after select = 0.085 s

Information from `WriteTraceLine`
Insert:
* Query Execution Time (AfterExecute) (async): 0.010. Records Affected: 1.
* Total Execution Time (Completed) (async): 0.035. Rows Count: 0.

Select:
* Query Execution Time (AfterExecute) (async): 0.002
* Total Execution Time (Completed) (async): 0.016. Rows Count: 67.

### For working option 3 (with IDENTITY):
* before insert = 0
* after insert and identity, before select = 0.078 s
* after select = 0.124 s

Insert:
* Query Execution Time (AfterExecute) (async): 0.009. Records Affected: 1.
No Total Execution Time (Completed) (async)

IDENTITY
* Query Execution Time (AfterExecute) (async): 0.002
* Total Execution Time (Completed) (async): 0.045. Rows Count: 0.

Select
* Query Execution Time (AfterExecute) (async): 0.002
* Total Execution Time (Completed) (async): 0.041. Rows Count: 68. `<- here we have it - 68 instead of 67 above.`

### Question
I didn't find explanation for this behaviour [in Microsoft resource for Lazy<T> class](https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=netframework-4.7.2). Do you know why although I `await` before each query `Lazy<DbContext>().Value` doesn't respect it (?) and executes `select` query?

### Environment details
linq2db version: 3.0.1, database: Ms Access via OleDb.

### Update
In normal using time1 and time2 have similar times like above 60-ish ms and 80-ish ms, `id` is correct and `temp` contains object.
```
var timer = new Stopwatch();
using (var db = new DbContext())
{
    timer.Start();
    var time0 = timer.ElapsedMilliseconds;
    var id = await db.InsertWithInt32IdentityAsync(sector).ConfigureAwait(false);
    var time1 = timer.ElapsedMilliseconds;
    var temp = await db.GetAllSectors().ToListAsync().ConfigureAwait(false);
    var time2 = timer.ElapsedMilliseconds;
}
```

**Comment by Shane32** [comment]
For the purposes of testing only, can you try a couple different scenarios:

1. Use `Lazy<T>` constructor with initialization method and explicit thread safety mode: (see https://docs.microsoft.com/en-us/dotnet/api/system.threading.lazythreadsafetymode?view=netcore-3.1 )
```csharp
private Lazy<DbContext> Context => new Lazy<DbContext>(() => new DbContext(), LazyThreadSafetyMode.ExecutionAndPublication);
```

2. Try caching the `Lazy.Value` response:
```csharp
var dbContext = Context.Value;
await dbContext.InsertAsync(sector).ConfigureAwait(false);
var temp = await dbContext.GetAllSectors().ToListAsync().ConfigureAwait(false);
```

3. Try using non-async methods:
```csharp
Context.Value.Insert(sector);
var temp = Context.Value.GetAllSectors().ToList();
```

4. Try making `Lazy<T>` static
```csharp
private static Lazy<DbContext> Context => new Lazy<DbContext>();
```

**Comment by Shane32** [comment]
Nevermind I know why.  The `Lazy` object is getting created every time `Context` is called.  You wrote this:

```csharp
private Lazy<DbContext> Context => new Lazy<DbContext>();
```

which is identical to the following code:

```csharp
private Lazy<DbContext> Context {
    get {
        return new Lazy<DbContext>();
    }
}
```

Now it is apparent the problem, and also the fix - use a field rather than a property:

```csharp
private readonly Lazy<DbContext> Context = new Lazy<DbContext>();
```

Now the field is initialized only once when the class is created.  You will have no more problems.

**Comment by sdanyliv** [comment]
Eagle Eye ;) Important part was shown as single line comment.

**Comment by Shane32** [comment]
If it is required that `Context` is a property, you can of course initialize a private field to `new Lazy<DbContext>()` and then have the property return the stored value of the private field.  For example:

```csharp
private readonly Lazy<DbContext> _context = new Lazy<DbContext>();
private Lazy<DbContext> Context => _context;
```

One last thought: if you do not need to worry about multithreaded access to `Context`, you can write this code, which gives you lazy initialization without thread safety:
```csharp
private Lazy<DbContext> _context;
private Lazy<DbContext> Context => _context ??= new DbContext();
```

**Comment by yarecky1** [comment]
Ok guys, thanks a lot! 👍 

I will use `private readonly Lazy<DbContext> _context = new Lazy<DbContext>();`
without `private Lazy<DbContext> Context => _context;`.

Private field is enough, property is not necessary, no multithreaded access. In `Manager` class I have some methods that don't use database; that's why I needed lazy instantiation to use context whenever needed. Methods in this class do small part of the whole job and comply SRP. Sometimes I need only insert operation, sometimes insert followed by select, sometimes something else.

BTW: this was very interesting case and difficult to catch at first view.
Thank you once more!
