### ISSUE TITLE
Get SQL text after exception has happened

### ISSUE THREAD

**Issue by scratch-net** [linq2db/linq2db#242]
is it possible? Or at least log every SQL text that is generated when doing statements like merge\update\etc?

**Comment by scratch-net** [comment]
Ok, I've found "LastQuery" which can be used but it's a pain to insert blablabla.Add (context.LastQuery) after each statement. Could you please add a simple OnQuery delegate that could be used for gathering queries ?

**Comment by scratch-net** [comment]
Created #243

**Comment by Maximusya** [comment]
Does #33 try to do similar thing? Via `TraceSwitch` functionality

**Comment by scratch-net** [comment]
@Maximusya I don't see it merged

**Comment by scratch-net** [comment]
Oops, sorry. My bad

**Comment by scratch-net** [comment]
I looked into trace code and found it to be static while I want queries for the specific instance of DataConnection. Is it possible?
