### ISSUE TITLE
t4 transformations does not work when nuget packages are stored in different folder

### ISSUE THREAD

**Issue by bonza** [linq2db/linq2db#244]
We've got an error running CopyMe.SqlServer.tt transformation:
Compiling transformation: Metadata file 'C:\work\DbTool\src\packages\linq2db.t4models.1.0.7.1\tools\linq2db.dll' could not be found C:\work\DbTool\src\DbTool.Data\Models\CopyMe.SqlServer.tt   

The problem occurs because our nuget packages folder location is differs from default. 
We store all our dependencies in folder called "libs", so we configured nuget.exe to download packages within this folder too.

As I see, the path to the linq2db.dll is hardcoded on first line of "LinqToDB.SqlServer.SqlTypes.Tools.ttinclude" file, but I have no idea how to fix it in general way

**Comment by ili** [comment]
You have to change paths in assembly directives in ttinclude files.
But for future it would be better to copy assemblies to local folders automatically. We'll do it later

**Comment by ili** [comment]
It should be fixed with 1.8.0 T4 packages (also .Net Core support implemented)
