### ISSUE TITLE
SAP Hana connection fro dotnetcore

### ISSUE THREAD

**Issue by djhonb** [linq2db/linq2db#2443]
How can I connect to SAP HANA from dotnet core
I can see its supported, not sure how.
Any Samples.

**Comment by MaceWindu** [comment]
You need to install SAP HANA ODBC provider locally and use "SapHana.Odbc" provider name (ProviderName.SapHanaOdbc) for your connection configuration.

**Comment by djhonb** [comment]
@MaceWindu Thanks a lot
Is there any sample snippets available for me anywhere..?
I searched but no luck.
Thanks a lot

**Comment by MaceWindu** [comment]
What exactly you miss?

E.g. for connection strings they will look like that (my test connection strings):
```
// x64 process
"Driver={HDBODBC};SERVERNODE=server_address:39015;databaseName=HXE;CS=TESTHANAODBC;UID=user_here;PWD=password_here;"

// x86 process
"Driver={HDBODBC32};SERVERNODE=server_address:39015;databaseName=HXE;CS=TESTHANAODBC;UID=user_here;PWD=password_here;"
```

Connection setup is same as for other providers, you just need to specify different provider. E.g. for sqlserver sample from readme:
```cs
// instead of 
builder.UseSqlServer(connectionString);
// you should use (we don't have UseSapHanaOdbc helper, so you should use UseConnectionString)
buider.UseConnectionString(LinqToDB.ProviderName.SapHanaOdbc, connectionString);
```
similar approach used for other configuration methods
