### ISSUE TITLE
Error: Count fields of associated table is quoted (LoadWith)

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2445]
LinqToDb-Version: 3.1.0
DB: Firebird 2.1

Hi,

I have a complex data structure and I try to reconstruct the situation with simple structures.
I have a class that has a association to another class and it is one to one association.

```
public class Card{
    public int Id { get; set;}
    public string CardName { get; set;}
    [Association(QueryExpression = nameof(Card_Owner), CanBeNull = true)]
    public Client Owner {get; set; }
    public int OwnerId {get; set; }

    public static Expression<Func<Card, IDataContext, IQueryable<Client>>> Card_Owner()
    {
       return (c, db) => db.GetTable<Client>().Where(cl=> cl.Id == c.OwnerId);
    }
}

public class Client{
    public int Id { get; set;}
    public string Name {get; set; }
    [ExpressionMethod(nameof(Client_CountOfTCards), IsColumn = true)]
    public int CountOfTCards {get; set; }

    public static Expression<Func<Client, IDataContext, int>> Client_CountOfTCards ()
    {
         return (cl, db) => cu.GetTable<Card>().Where(t =>t.OwnerId == cl.Id).Count();
     }
}
```

so when I call it in usual way it looks good:

```
using(var db = new MyDb()){
    var cards = db.GetTable<Card>().ToList();
    var clients = db.GetTable<Client>().ToList();
)
```

but when I call it with LoadWith extension:

```
using(var db = new MyDb()){
    var cardsWithClients = db.GetTable<Card>().LoadWith(x => x.Owner).ToList();
)
```

Then the resulting sql get quoted aliases for the count of cards:

-- CarParkConnection Firebird
```
SELECT FIRST 10
	t1.ID,
	t1.CARDNAME,
	t1.OWNERID,
	a_Owner.ID,
	a_Owner.NAME,
	a_Owner."cnt",
FROM
	CARD t1		
		LEFT JOIN (
			SELECT
				cu.ID,
				cu.NAME,
				(
					SELECT
						Count(*)
					FROM
						KARTE card
					WHERE
						(card.OWNERID IS NULL AND cu.ID IS NULL OR card.OWNERID = cu.ID) AND
						(card.OWNERID IS NULL AND cu.ID IS NULL OR card.OWNERID = cu.ID)
				) as "cnt"
			FROM
				KUNDE cu
		) a_Owner ON (a_Owner.ID IS NULL AND t1.OWNERID IS NULL OR a_Owner.ID = t1.OWNERID)
```

This does not work with Firebird, I am not sure for other database systems...

**Comment by MaceWindu** [comment]
Why it doesn't work? you use dialect1 db?

**Comment by MaceWindu** [comment]
Also which quotation mode you use?

**Comment by Franki1986** [comment]
Yes dialect 1.. Ahhhh there was something 😄 .. 
`FirebirdConfiguration.IdentifierQuoteMode = FirebirdIdentifierQuoteMode.None;`

Now it works!!
But why it works in normal query and does not with 'LoadWith'

**Comment by MaceWindu** [comment]
This is a change is 3.1.0 - in Auto quotation mode (default mode) we now quote lowercase identifiers. And I'm actually puzzled why it quoted only load-with aliases. So I'm going to fix it.

Anyway, for dialect1 you should use `None`  as you already figured.

**Comment by Franki1986** [comment]
Thanks for the help!
