### ISSUE TITLE
Association with CanBeNull = false produces LeftJoin when using QueryExpressionMethod

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2450]
LinqToDb-Version: 3.1.0
DB: Firebird 2.1

Hi,

I want to generate an inner join by using the association attribute and a QueryExpressionMethod.

Let's say I have this structure:

```
public class Card{
    public int Id { get; set;}
    public string CardName { get; set;}
    [Association(QueryExpression = nameof(Card_Owner), CanBeNull = false)]
    public Client Owner {get; set; }
    public int OwnerId {get; set; }

    public static Expression<Func<Card, IDataContext, IQueryable<Client>>> Card_Owner()
    {
       return (c, db) => db.GetTable<Client>().Where(cl=> cl.Id == c.OwnerId);
    }
}

public class Client{
    public int Id { get; set;}
    public string Name {get; set; }
}
```

So if I call it :

```
using(var db = new MyDb()){
    var cards = db.GetTable<Card>().LoadWith(x => x.Client).ToList();
)
```

The resulting SQL produces a left join.

if I change the Association Attribute to : 

```
public class Card{
    public int Id { get; set;}
    public string CardName { get; set;}
    [Association(ThisKey = "OwnerId", OtherKey = "Id", CanBeNull = false)]
    public Client Owner {get; set; }
    public int OwnerId {get; set; }
}
```

it produces an inner join. Although both have the CanBeNull set to false!

**Comment by sdanyliv** [comment]
It is a problem?
We just trying to avoid master records filtering because of custom expression in details. I this case we always produce Left join.

**Comment by Franki1986** [comment]
I see a performace difference at my database. Is it possible to workaround this without creating a query with Inner Join?

**Comment by sdanyliv** [comment]
No way right now. It is hardcoded condition which do not bring any slowdown on modern databses.

**Comment by Franki1986** [comment]
'on modern databases'... yes I would also like to change, but that is the eco system I am forced to use :sob:
Thanks for the fast reply, maybe there should be an info at the documentation that this behaves in different ways...

**Comment by travbeamo** [comment]
I known this is closed but just noticed similar problem.

> No way right now. It is hardcoded condition which do not bring any slowdown on modern databases.

I also am not using a modern database (IBM DB2 iSeries V5R4) as we cannot upgrade at this stage. We need to generate inner joins as left joins do perform worse.

We cannot use the AssociationAttribute with thisKey/otheKey properties for 2 reasons:
* the domain/entity class library cannot have reference any 3rd party packages
* the underlying database tables severely lacks normalization and uses composite keys along with filters all over the place. 

It is a nightmare. 

The only viable option is to define associations using the FluentMappingBuilder in the DataConnection with predicate and the canBeNull = false.

Below are some tests classes and DataConnection as below:
```
  public class AM112U {
    [Column] public int Idd { get; set; }
    [Column] public string? NormalizedName { get; set; }
    [Column] public string? NormalizedEmailAddress { get; set; }
    [Column] public int? ImpAM112Id { get; set; }
    [Column] public DateTime? EndDate{ get; set; }
    public int AM114Idd { get; set; }
    public AM114U AM114U { get; set; }
  }

  public class AM114U {
    [Column] public int Idd { get; set; }
    [Column] public string? NormalizedName { get; set; }
    [Column] public DateTime? EndDate { get; set; }
    public List<AM112U> AM112UList { get; set; }
  }

  public class zTestDataConnection : DataConnection {
    public zTestDataConnection(TestAppSettings appSettings) : base(GetLinqToDbConnectionOptions(appSettings)) {
      var fmb = MappingSchema.GetFluentMappingBuilder();
      fmb.Entity<AM112U>()
        .Association(x => x.AM114U, (x, y) => x.AM114Idd == y.Idd && y.Idd > 0 && y.EndDate != null , false);
      fmb.Entity<AM114U>()
        .Association(x => x.AM112UList, (x, y) => x.Idd == y.AM114Idd && x.Idd > 0 && x.EndDate != null, false);
    }

    public static LinqToDbConnectionOptions GetLinqToDbConnectionOptions(TestAppSettings appSettings) {
      var builder = new LinqToDbConnectionOptionsBuilder();
      var connString = appSettings.ConnectionStrings.DB2i_Odbc_V1;
      var dataProvider = new DB2iSeriesDataProvider(DB2iSeriesProviderType.Odbc);
      builder.UseConnectionString(dataProvider, connString);
      return new LinqToDbConnectionOptions(builder);
    }
  }

```

Example Usage

```
var testName = "TEST";
var testListQuery = (from x in db.GetTable<AM112U>()
                     where x.AM114U.NormalizedName == testName
                     select new {
                       Id = x.Idd,
                       Name = x.NormalizedName ?? string.Empty,
                       EmailAddress = x.NormalizedEmailAddress,
                     });
```

testListQuery.ToString() generates SQL:

```
DECLARE @? NVarChar(4) -- String
SET     @? = 'TEST'

SELECT x.Idd,
	Coalesce(x.NormalizedName, ''),
	x.NormalizedEmailAddress
FROM	AM112U x
		LEFT JOIN AM114U T41 ON x.AM114Idd = T41.Idd AND T41.Idd > 0
WHERE
	T41.NormalizedName = CAST(? AS NCLOB)
```

Documentation states that if canBeNull = false it will use **INNER** Join but a **LEFT** join is always generated.

**Comment by sdanyliv** [comment]
Yes, in this case we ignore CanBeNull attribute. Will check what we can do here.

**Comment by travbeamo** [comment]
@sdanyliv Yes, understood.

**Comment by travbeamo** [comment]
It might not be such an issue if the entities models correctly use Nullable Reference Types for association properties.

If the helper methods & code refactoring proposed in issue https://github.com/linq2db/linq2db/issues/2592 are accepted in to Linq2DB, then the canBeNull attribute could possibly be removed altogether.

Then the correct joins would be used purely based on the if the association properties in the entities model are nullable:
* If association property is nullable =  LEFT join is used
* If association property is not nullable =  INNER join is used
