### ISSUE TITLE
Table Default Filter

### ISSUE THREAD

**Issue by caliskanersin** [linq2db/linq2db#2458]
Hi,

My tables have a instance columns and it has default value and it's value can be change to accordin to env. I want to a default filter for that column. However I do not want write every linq query where filter for that column. Is there any way for that in linq2db?

**Comment by sdanyliv** [comment]
This one? https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#query-filters

**Comment by caliskanersin** [comment]
yes it is ok for me thank you.
