### ISSUE TITLE
Table alias in UPDATE SET

### ISSUE THREAD

**Issue by FlipSs** [linq2db/linq2db#2463]
Hello, 

Today I tried to implement the feature I asked you in #2140 and it does not work in SQL Server 2017.
It does not work, because Microsoft does not support table aliases when using .Write method (why???), i.e. a query like `Set [x].[Items].WRITE(@toSaveItem, NULL, 0)` throws an error, but `Set [Items].WRITE(@toSaveItem, NULL, 0) ` works fine.

Is table alias needed in `SET` query (it already indicated in `UPDATE`)?
Can it be optional for DataProvider or removed entirely?

### Environment details
linq2db version: 3.1.1
Database Server: Sql Server
.NET Framework: .Net Core 3.1, net472

**Comment by sdanyliv** [comment]
There are a lot of useful extensions for that:
```cs
connection.SomeTable
      .AsUpdatable()
      .Set(x => $”{Sql.FieldExpr(x.Items)}.WRITE({item}, {offset}, {length})”)
      .Update();
```

**Comment by FlipSs** [comment]
Thanks
