### ISSUE TITLE
Allocations when using custom Mapping schemas with DataConnection

### ISSUE THREAD

**Issue by to11mtm** [linq2db/linq2db#2466]
I've noticed that if a MappingSchema is passed into DataConnection, we new up another MappingSchema (to integrate the DataProvider's Mapping Schema).

In one of my codebases, using `Clone` on an existing DataConnection showed a marked improvement in benchmark results (as, among other things, it avoided re-creating the merged Schema).

`Clone` works for the moment but I'm not sure if it's robust for all scenarios one may encouter.

 - Is there a way to avoid this? I think if you passed in a shared `DataProvider` that would work but I don't know if those are considered thread-safe.

 - Would it make sense to add an overload for DataConnection to accept a 'pre-built' mapping schema:

```
public class BuiltMappingSchema
	{
              public BuiltMappingSchema(string providerName, string connectionString,
			MappingSchema schemaToBuild):this(DataConnection.GetDataProvider(providerName, connectionString), schemaToBuild)
              public BuiltMappingSchema(IDataProvider provider, MappingSchema schemaToBuild)
            //make the mapping schema and put it somewhere
         }
```

  - I don't think? caching is an option with current setup of MappingSchema...

**Comment by sdanyliv** [comment]
I have plans to look at this functionality closer, but I do not think it is good idea to create such overload.
Will check what we can do here.

**Comment by to11mtm** [comment]
I had an idea about this that would be less hacky.

If User Provides either Provider or Provider Name with Mapping Schema, we could create specific property in `LinqToDbConnectionOptionsBuilder` and create `BuiltMappingSchema` property appropriately; constructor for `DataConnection` can then utilize to avoid current pitfalls of custom mapping schemas.

If this is OK option I can do.

**Comment by sdanyliv** [comment]
I have Idea:
Add to `DataConnection` static MemoryCache _combinedSchemas;
Schematically:
```cs
		public DataConnection AddMappingSchema(MappingSchema mappingSchema)
		{ 
                       var key = new { MappingSchema.ConfigurationID, mappingSchema.ConfigurationID };
                       MappingSchema  = _combinedSchemas.GetOrAdd(key, 
                  	     o => 
				{
					o.SlidingExpiration = Common.Configuration.Linq.CacheSlidingExpiration;
					return new MappingSchema(mappingSchema, MappingSchema);
				});
			_id  = null;

			return this;
		}
```

**Comment by to11mtm** [comment]
I can do this part for the moment. I'll get a PR in.
