### ISSUE TITLE
Enum text search

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2468]
Is there a way to search for the enum value text even if the database column holds a number?

```c#
public enum MyEnum
{
    Blue = 0,
    Red = 1
}

context.TableWithMyEnum.Where(x => x.MyEnum.ToString().Contains("Blu").ToList();

```

**Comment by jogibear9988** [comment]
i think you need to use expressionvisitor sne transform the expression before.
you can use enum.getnames and then create or filter conditions.
@sdanyliv or is this something we will support in linq2db?
and @sdanyliv 
do we have a callback where the expression could be visited?

**Comment by sdanyliv** [comment]
@HypeillingerChillinger, try the following (writing that without compiling, so it may contain some mistakes):
```cs
static class MyExtensions
{
    [ExpressionMethod(nameof(MyEnumToStringImpl)]
    public static string MyEnumToString(MyEnum v)
    {
         return v.ToString();
    }

    static Expression<Func<MyEnum, string>> MyEnumToStringImpl()
       => v => v == MyEnum.Blue ? "Blue" : "Red";
}
```
Somewhere in initialization:
```
Expressions.MapMember((MyEnum v) => v.ToString(), v => MyExtensions.MyEnumToString(v));
```

@jogibear9988, 
> do we have a callback where the expression could be visited?

there is `IExpressionPreprocessor` interface which can be applied to `DataConnection`.

**Comment by jogibear9988** [comment]
@sdanyliv 
As I understand, he already has a database, and the enums are not stored as strings, so he wanted to know who to do it in this scenario

**Comment by jogibear9988** [comment]
My Thoughts were silly...
I thought we could rewirte the expression so we create from 

     x.MyEnum.ToString().Contains("Blu")

the correct equals expression:

        x.MyEnum == 3 || ....

but this will then only work when you use a constant for the string. so it is not a good idea

**Comment by jogibear9988** [comment]
@sdanyliv 

It does not work.
We get the Exception "''MyEnumToString(x.Status)' cannot be converted to SQL.'"

![image](https://user-images.githubusercontent.com/364896/92086374-63194a80-edca-11ea-94f6-f9e0e56eb69a.png)

And one more question,

        Expressions.MapMember((MyEnum v) => v.ToString(), v => MyExtensions.MyEnumToString(v));

is this global? Shouldn't this be a Method of the MappingSchema?

**Comment by sdanyliv** [comment]
Looks like a bug, we have to convert ToString to MyEnumToString and then extract ExpressionMethod body.

> is this global? Shouldn't this be a Method of the MappingSchema?

Its obvious, it is static - yes it is global. Thought about moving to MappingSchema, but not now.

**Comment by jogibear9988** [comment]
when we have fixed, will this also work??

			var par = Expression.Parameter(typeof(object), "enum");
			var casted = Expression.Convert(par, typeof(int));
			var values = Enum.GetValues(typeof(MyEnum));
			Expression retE=Expression.Constant(null, typeof(string));
			foreach (var v in values)
			{
				var eq = Expression.Equal(Expression.Constant((int)v), casted);
				retE = Expression.Condition(eq, Expression.Constant(v.ToString()), retE);
			}
			var lambda = Expression.Lambda<Func<object,string>>(retE, par);
			Expressions.MapMember((MyEnum v) => v.ToString(), lambda);

**Comment by sdanyliv** [comment]
@jogibear9988, create test and I'll fix it right now for today's release.

**Comment by jogibear9988** [comment]
@sdanyliv I've created a test.

Maybe you can look if we also could support My Method:

      MapEnumToString<MyEnum>();

**Comment by jogibear9988** [comment]
@sdanyliv 
Should we add  MapEnumToString(Type type) as extension to linq2db?

**Comment by sdanyliv** [comment]
Not yet. It is new API and we need to investigate proper place for that.
