### ISSUE TITLE
LinqToDB Relationship returns null

### ISSUE THREAD

**Issue by dogaanismail** [linq2db/linq2db#2472]
I have been trying to get an entity that is called AppUser with its detail. I have used 2 different methods to get User and its relationship.

I have used **a linq join query** and **an include extension method**, but the relationship that is called UserDetail returns null **for both of them.**

Please check this screenshot.
https://i.stack.imgur.com/hsqq3.png

        `public AppUserDetailDto GetUserDetailByUserName(string userName)
    {
        //TODO: Code needs to be refactored
        if (string.IsNullOrEmpty(userName))
            throw new ArgumentNullException(nameof(userName));

        var appuser = from user in _appUserRepository.Table
                      join userdetail in _appUserDetailRepository.Table on user.DetailId equals 
                      userdetail.Id
                      where user.userName == userName
                      select user;

        var deger = _appUserRepository.Find(x => x.UserName == userName, x => x.Include(t => t.UserDetail)).FirstOrDefault();

        var user2 = _userManager.Users.FirstOrDefault(x => x.UserName == userName);
        _userManager.Users.Include(u => u.UserDetail);

        var detail = user2.UserDetail;

        return null;
    }`

Here is my AppUser class.

    ` public class AppUser : BaseEntity, IAppUser
      {
        [Required, Identity]
        [Key]
        public new int Id { get; set; }

        [Required]
        [ForeignKey("UserDetail")]
        public int DetailId { get; set; }

        public virtual AppUserDetail UserDetail { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string PasswordHash { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public int AccessFailedCount { get; set; }
        public bool LockoutEnabled { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public string ConcurrencyStamp { get; set; }
    }`

The query runs properly on Sql Server side.

https://i.stack.imgur.com/yTdKQ.png

There are so many code blocks that I can not paste here. I would be very happy if someone could help.

If you would like to see the project, you can check here;

https://github.com/dogaanismail/DevPlatform

I have asked this question on Stackoverflow. Here is the link.

https://stackoverflow.com/questions/63760119/linqtodb-relationship-returns-null

Any help would be appreciated!

### Environment details
linq2db version: *v3.0.1*
Database Server: *Microsoft Sql Server*
Database Provider: *SqlServerDataProvider*
Operating system: *Windows 10*
.NET Framework: *.Net Core 3.1*

**Comment by sdanyliv** [comment]
Linq2db does not have `Include` extension. Instead of that it has `LoadWith`

Update linq2db to latest version and try the following query and let me know about results
```cs
var deger = _appUserRepository.Table
    .LoadWith(t => t.UserDetail).FirstOrDefault(x => x.UserName == userName);
```

**Comment by dogaanismail** [comment]
Thank you, sir. I will try to the following query tomorrow. In addition to your answer, how can I use linq queries because I could not get the relationship entity by using a linq query, too.

For instance;

`var appuser = from user in _appUserRepository.Table
                  join userdetail in _appUserDetailRepository.Table on user.DetailId equals 
                  userdetail.Id
                  where user.userName == userName
                  select user;`

**Comment by sdanyliv** [comment]
If you have defined associations for related entities (AssociationAttribute), everything should work.
```cs
var appuser = from user in _appUserRepository.Table.LoadWith(u => u.Details)
   where user.userName == userName
   select user;
```
Check this answer https://stackoverflow.com/questions/63150864/linq2db-effective-way-to-query-hierarchy-of-objects

**Comment by sdanyliv** [comment]
@dogaanismail, can we close issue?

**Comment by dogaanismail** [comment]
@sdanyliv yes, we can close the issue, but **I would like to ask one more question**, sir. 

I have successfully organized my AppUser and AppUserDetail by using AssociationAttribute.

`[LinqToDBAssociation.Association(ThisKey = nameof(DetailId), OtherKey = nameof(AppUserDetail.Id), CanBeNull = true, Relationship = Relationship.OneToOne)]
        public virtual AppUserDetail UserDetail { get; set; }`

My question is that how can I define and organize AppUser and Post related entities ?

For instance each AppUser has many posts. I could not solve this.

`[LinqToDBAssociation.Association(ThisKey = nameof(Id), OtherKey = nameof(Post.CreatedBy), CanBeNull = true)]
        public virtual IEnumerable<Post> UserPosts { get; set; }`

My AppUser class is like this.

    `  public class AppUser : BaseEntity, IAppUser
    {
        [Required, Identity]
        [Key]
        public new int Id { get; set; }

        [Required]
        [ForeignKey("UserDetail")]
        public int DetailId { get; set; }

        [LinqToDBAssociation.Association(ThisKey = nameof(DetailId), OtherKey = nameof(AppUserDetail.Id), CanBeNull = true, 
        Relationship = Relationship.OneToOne)]
        public virtual AppUserDetail UserDetail { get; set; }

        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string PasswordHash { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public int AccessFailedCount { get; set; }
        public bool LockoutEnabled { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public string ConcurrencyStamp { get; set; }

        **[LinqToDBAssociation.Association(ThisKey = nameof(Id), OtherKey = nameof(Post.CreatedBy), CanBeNull = true)]
        public virtual IEnumerable<Post> UserPosts { get; set; }**
    }`



My Post class is like this.

      `  public class Post : BaseEntity
    {
        public Post()
        {
            PostImages = new HashSet<PostImage>();
            PostComments = new HashSet<PostComment>();
            PostVideos = new HashSet<PostVideo>();
        }
        public string Text { get; set; }
        public int? PostType { get; set; }

        public virtual ICollection<PostComment> PostComments { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
        public virtual ICollection<PostVideo> PostVideos { get; set; }
    }`

Finally, I would like to get UserPost by using LoadWith extension method.

` var appUser = _appUserRepository.Table.LoadWith(t => t.UserDetail).LoadWith(p => p.UserPosts).FirstOrDefault(x => x.UserName == userName);`

**Comment by sdanyliv** [comment]
I can not handle your problem. Seems everything is ok.

**Comment by dogaanismail** [comment]
I understand. We can close the issue
