### ISSUE TITLE
SqlDataType.SystemType returns wrong value

### ISSUE THREAD

**Issue by exileDev** [linq2db/linq2db#2476]
`SystemType` is a read-only auto property and always returns the type of System.Type class =)

https://github.com/linq2db/linq2db/blob/389fc22da2b5bf00bccb1e1d46076e16224db4f6/Source/LinqToDB/SqlQuery/SqlDataType.cs#L430

### Steps to reproduce

Getting `SystemType` of `SqlDataType.GetDataType(DataType type)` fails a simply test:

```c#
Assert.AreEqual(typeof(bool), SqlDataType.GetDataType(DataType.Boolean).SystemType);
```

### Environment details
linq2db version: 3.1.2
Database Server: Any
Database Provider: Any
Operating system: Any
.NET Framework: Any

**Comment by sdanyliv** [comment]
I agree, something wrong here, but use Type property instead:
```cs
Assert.AreEqual(typeof(bool), SqlDataType.GetDataType(DataType.Boolean).Type.SystemType);
```
