### ISSUE TITLE
Bug: invalid removal of unused aggregation

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2478]
We have found a case where linq2db simplifies a query too aggressively and produces an incorrect result.

Our high-level use case is that we produce a paginated list.
To do this we construct a complex query, which is then executed twice: 
- `.Count()` to have the total number of rows
- `.Skip().Take().ToList()` to fetch one page of data

During the `.Count()` execution, no field is selected, which leads to massive simplifications made by linq2db.
From a perf perspective this is very nice, unfortunately we found out one bad simplification that produces incorrect results.

The main query performs CROSS APPLY with an aggregation as a sub-query.

The C# code goes something like this (much simplified, this example could be a simple inner join/group by but in reality we several cross apply):
```csharp
from p in db.GetTable<Parent>()
from c in (from t in db.GetTable<Child>()
           where c.ParentId == p.Id
           group t by 1 into g
           select new { Count = g.Count() })
select new { p.Id, c.Count }
```
This generates the following SQL (correct):
```sql
select p.id, c.count
from Parent p
cross apply (
  select count(*) 
  from Child c
  where c.parentId = p.id
) c
```

But when this request goes through `.Count()`, `c.Count` is not selected anymore and linq2db simplifies everything down to:
```sql
select count(*)
from Parent p
inner join (
  select c.parentId 
  from Child c 
  group by c.parentId
) c on c.parentId = p.id
```

But removing `count(*)`, even though it was unused, is incorrect.

In SQL, a query that has no group by and returns aggregations _always_ returns a single row. If no row matches, then a single result with `count(*)` being 0 is returned.

Linq2db removed the unused `count(*)` and put a `group by` in its place, but the behaviour is different. 
If there is no matching row, then the sub-select returns nothing and the `inner join` fails and discards the row.

-> Linq2db needs to recognize sub-queries that return aggregates without group by.
It needs knowledge that such queries always return _exactly_ one row.
This actually means that a correct and more efficient optimization is to completely remove such sub-query if its results are not used.

### Environment details
linq2db version: 3.1.2
Database Server: Oracle 12c
Database Provider: Oracle Managed Provider
Operating system: Windows
.NET Framework: .net 4.7.2

**Comment by sdanyliv** [comment]
I need LINQ query which produces incorrect result.
If i understand correctly
```cs
var query = from p in db.GetTable<Parent>()
from c in (from t in db.GetTable<Child>()
           where c.ParentId == p.Id
           group t by 1 into g
           select new { Count = g.Count() })
select new { p.Id, c.Count }

var cnt = query.Count(); // here you have incorrect result?
```

**Comment by sdanyliv** [comment]
I'll check what happened here. But i suggest to simplify query 
```cs
var query = from p in db.GetTable<Parent>()
select new 
{
   p.Id,
   Count = db.GetTable<Child>().Where(c => c.ParentId == p.Id).Count() 
}
```

**Comment by jods4** [comment]
Yes, you understood correctly.

As for your suggestion: it's a much simplified, minimal repro.
My real case contains multiple independent cross apply, and they return multiple (many) aggregated stats.
CROSS APPLY let us perform all aggregations in one sub-query, we don't want to create one identical sub-query per aggregation (as I said we have _many_ of them).

**Comment by sdanyliv** [comment]
Looks like we have to transfer this to left join. 
Anyway, you do not need group by 1 for such queries.
There are defined functions for that: Sql.Ext.Count() and other aggregation analogs.

**Comment by jods4** [comment]
Left join would work. 
In this specific case you could go as far as dropping the subquery completely (that would clearly be awesome): its results aren't used and it's guaranteed to have exactly 1 row.

> Anyway, you do not need group by 1 for such queries.
There are defined functions for that: Sql.Ext.Count() and other aggregation analogs.

I looked for that but `group by 1` was the best I could find with Google. Could you point me to a doc or give more details/an example? Our subqueries also contain `Count` and `Sum` based on (possibly null) expressions.

**Comment by jods4** [comment]
Note that the LEFT JOIN conversion works in this instance with the empty GROUP BY.
Another CROSS JOIN that contains a GROUP BY must still be converted to an INNER JOIN.

**Comment by sdanyliv** [comment]
> I looked for that but group by 1 was the best I could find with Google. Could you point me to a doc or give more details/an example? Our subqueries also contain Count and Sum based on (possibly null) expressions.

Check these tests, it should be `Sql.Ext.Count().ToValue()`:

https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/AnalyticTests.cs#L32-L60

There are a lot of overloads along with Window Functions

**Comment by sdanyliv** [comment]
@jods4, decided to generate at least one aggregation for such case. I've checked query execution plan - it is very well.
So fixed query is:
```sql
SELECT
	Count(*)
FROM
	[Parent] [p]
		CROSS APPLY (
			SELECT
				Count(*) as [c1]
			FROM
				[Child] [t]
			WHERE
				[t].[ParentID] = [p].[ParentID]
		) [t1]
```

**Comment by jods4** [comment]
Great, that would work.
Out of curiosity, why didn't you remove the whole CROSS APPLY? Was it tricky to do with the existing code?

As aggregations go, I wonder if a dummy such as MIN(1) would be better (it's a constant).

**Comment by sdanyliv** [comment]
> Out of curiosity, why didn't you remove the whole CROSS APPLY? Was it tricky to do with the existing code?

It is really tricky, we have to check a lot of cases here. For example what to do if we change condition:
```sql
[t].[ParentID] <> [p].[ParentID]
```

> As aggregations go, I wonder if a dummy such as MIN(1) would be better (it's a constant).

I've checked execution plan and even Count is optimized out by SQL Server.

P.S.
Tried the same query with EF Core - it fails in any cases.

**Comment by jods4** [comment]
> It is really tricky, we have to check a lot of cases here. For example what to do if we change condition:

I'm not sure what you mean with this different condition. It would still work the same, wouldn't it? 
A query that aggregates without group by always return a single result.

```sql
select max(1)
from SomeTable
where 1 = 0;
-- still returns 1 row with value NULL
```

If that result is not used, you can remove the query as it would never change cardinality.

> Tried the same query with EF Core - it fails in any cases.

Of course, that's why we use linq2db here 😃 
There's so much more you can do that you can't do in EF + the SQL queries are much nicer, EF is totally unreadable.

**Comment by sdanyliv** [comment]
> I'm not sure what you mean with this different condition. It would still work the same, wouldn't it?
A query that aggregates without group by always return a single result.

Oh, it needs more investigation from my side. If you help me to create set of tests, probably I'll figure out corner cases and remove this join.
But create new issue for tracking that.

Anyway, if you have missed that: https://github.com/linq2db/linq2db/issues/1402#issuecomment-438961009
You can do pagination and Count in one roundtrip.

**Comment by jods4** [comment]
Yup thanks for the tip. 
I was aware of the COUNT(*) OVER () technique but haven't used it for a long while as EF doesn't support windowing functions.

It's the kind of thing that's worthy of benchmarks, though. Do you have any?

I don't have much faith in Oracle (sadly can't always use SQL Server here) and for very complex queries with inner loops I'm wary of the optimizer being able to count the whole thing without performing the computations past the paged data.

It's a good reminder, though. I'll do a few experiments, thanks.

**Comment by jods4** [comment]
Thanks for fixing this bug.
If you want to implement further optimizations, I opened #2490.
