### ISSUE TITLE
Insert DateTime into SQL2005

### ISSUE THREAD

**Issue by b0bi79** [linq2db/linq2db#248]
Подскажите, как указать версию SQL, что бы фрэймфорк исользовал типы SQL2005. Сейчас пытаюсь сделать инсерт командой InsertWithIdentity, получаю ошибку: The version of SQL Server in use does not support datatype 'datetime2'.
Для колонок DateTime ставлю атрибут [Column("DataSert", DataType = DataType.DateTime)], не помогает.

**Comment by igor-tkachev** [comment]
1. <add name="SqlServer.2005" connectionString="..." providerName="System.Data.SqlClient" />
2. <add name="XYZ" version="2005" connectionString="..." providerName="System.Data.SqlClient" />

**Comment by b0bi79** [comment]
А можно словами? я цифрами плохо понимаю :)

**Comment by igor-tkachev** [comment]
Убрал скобки.
