### ISSUE TITLE
Visual Studio 20015 is not supported

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#249]
Hello 
I used Linq to Access in our VS2013 Project. It works fine.
But now, with VS2015 it doesn´t worked anymore.

Will LinqToDb Support VS2015 in the future ?
Or must I search a new product ?
Could you send me a short msg to a.waning@gmx.de 
Thanks Andreas

**Comment by igor-tkachev** [comment]
What exactly wrong? I use VS 2015 as well and everything works just fine.

**Comment by AndreasWaning** [comment]
hi,

thank you for your answer.

I will make some hardcopies.



mit freundlichen Grüßen aus Vreden
Andreas Waning

Waning Software
Middelwegg 2
48691 Vreden

Telefon 02564 829 314
Fax 02564 97504
Mobil 0151 551 589 01

Mail : info@waning-software.de
Web: www.waning-software.de

**Comment by AndreasWaning** [comment]
Did you try Visual Studia 2015 and Linq To Access 

When I try to click on T4 Template Degug




I get a few Error Messages.





mit freundlichen Grüßen aus Vreden
Andreas Waning

Waning Software
Middelwegg 2
48691 Vreden

Telefon 02564 829 314
Fax 02564 97504
Mobil 0151 551 589 01

Mail : info@waning-software.de
Web: www.waning-software.de

**Comment by AndreasWaning** [comment]
in VS2013 I do the same and that works fine.

mit freundlichen Grüßen aus Vreden
Andreas Waning

Waning Software
Middelwegg 2
48691 Vreden

Telefon 02564 829 314
Fax 02564 97504
Mobil 0151 551 589 01

Mail : info@waning-software.de
Web: www.waning-software.de

**Comment by AndreasWaning** [comment]
Hello Igor,

You do right,  VS2015 is ok. I made anything wrong.

I have one additional question.

I do not like the Connection String in Config File.

I can pass a configuration string to  the constructor.


Do you have a sample configuration string  for Access and MS Sql  for me ?
(I have no idea what I must set in the configuration string)


Thanks,
Andreas



string strConnection = @"Provider=Microsoft.Jet.OLEDB.4.0;Data Source=c:\test\AtgSpsText32.mdb;Locale Identifier=1033;Jet OLEDB:Engine Type=5;Persist Security Info=True";
using (var db = new DataModels.AtgSpsText32DB(strConnection))
{
    var q =
        from c in db.S7KranV6_Fehler_Texts
        select c;
    foreach (var c in q)
        Console.WriteLine(c.TextEnglish);
}



<connectionStrings>
  <add name="MyDatabase" providerName="Access" connectionString="Provider=Microsoft.Jet.OLEDB.4.0;Data Source=c:/Test/atgspstext32.mdb;Locale Identifier=1033;Jet OLEDB:Engine Type=5;Persist Security Info=True"/>
</connectionStrings>



mit freundlichen Grüßen aus Vreden
Andreas Waning

Waning Software
Middelwegg 2
48691 Vreden

**Comment by AndreasWaning** [comment]
Hello Igor,

forget me first question today.


Is there a way to pass a connection string to Linq2DB, so that I do not need the Config File ???

Thanks Andreas




mit freundlichen Grüßen aus Vreden
Andreas Waning

Waning Software
Middelwegg 2
48691 Vreden

Telefon 02564 829 314
Fax 02564 97504
Mobil 0151 551 589 01

**Comment by igor-tkachev** [comment]
Please install the latest nuget and try again. Let me know if you still have any issues.
