### ISSUE TITLE
Out-of-order SQL Execution in SelectQuery()

### ISSUE THREAD

**Issue by to11mtm** [linq2db/linq2db#2494]
Describe your issue.

### Steps to reproduce

Using SQLite and SQL Server I see odd behavior with `SelectQuery` below. The SQL Executed in order is:
  - Record is inserted into the table
  - Select statement is written.

Ideal behavior: It would be great if there was a way to represent it like this or similar if possible (maybe there's a better way to write this I can't think of, but the order of SQL here still seems worth reporting even if fix is still multiple round trips. 

Failing that, it probably would be better/safer to re-order the operations so that behavior is closer to what would be expected (Select statement runs first, then insert)

#### Ideal Query
```sql
   insert into TEST
   ([Value])
   values('hi')
   WHERE COUNT(SELECT * FROM TEST) = 0;
```     

#### Generated SQL
```sql
--  SqlServer.2012
DECLARE @Value_1 NVarChar(4000) -- String
SET     @Value_1 = N'hi'

INSERT INTO [Test]
(
	[Value]
)
VALUES
(
	@Value_1
)

-- Execution time: 00:00:00.0234765. Records affected: 1.

-- Execution time: 00:00:00.0609296. Records affected: 0.

--  SqlServer.2012
DECLARE @p1 Int -- Int32
SET     @p1 = 1

SELECT
	IIF(EXISTS(
		SELECT
			*
		FROM
			[Test] [t1]
	), @p1, 0)

-- Execution time: 00:00:00.0014808

-- Execution time: 00:00:00.1369867. Records affected: 1.

```

#### Sample Table/Query
```c#
//Sample Table
public class Test
{
	public string Value {get;set;}
}

//Query in question, conn is just a normal DataConnection:
        using (var conn = myConnFactory())
	{
		//conn.CreateTable<Test>();
		conn.SelectQuery(() => 
		   conn.GetTable<Test>().Any() //Tried adding .AsSubQuery() here, no luck
		     ? conn.Insert(new Test() { Value = "hi"},null,null,null,null) //Tried variations of insert here as well
			 : 0).Dump();
	}

```

### Environment details
linq2db version: *3.1.3*
Database Server: *SQLite Classic, SQL Server*
Database Provider: *SQLite Classic, SQL Server*
Operating system: *Windows 10*
.NET Framework: *Core 3.1*

**Comment by MaceWindu** [comment]
I wouldn't call order strange, it's more like query itself strange 😄 . In any case lazy evaluation here fixed in `6.0.0-preview.1`
