### ISSUE TITLE
Query returns empty result when filter by Guid column (MySql)

### ISSUE THREAD

**Issue by klym1** [linq2db/linq2db#2498]
Assuming there's a table definition:

```csharp
[Table(Name = "test")]
public class TestEntity
{
    [PrimaryKey, Identity]
    public Guid Id { get; set; }
        
    [Column]
    public string Name { get; set; }
}
```

I want to search for an entity with an id:

```csharp
var id = Guid.Parse("0003057D9ED04FE186A0F76485759090");

var query = db.Table
     .Where(c => c.Id == id)
     .Select(it => it.Name);
            
var res = query.ToList();
```

I'm using custom converter for Guid type:

```csharp
var m = new MySqlMappingSchema();
m.SetValueToSqlConverter(typeof(Guid), (sb, dt, v) => ConvertBinaryToSql(sb, FlipEndian(((Guid)v).ToByteArray()))); 
// FlipEndian just swaps the bytes
```

Following sql is generated:

```sql
--  MySqlConnector MySql
DECLARE @id Guid
SET     @id = 0x0003057D9ED04FE186A0F76485759090

SELECT
	`c_1`.`Name`
FROM
	`test` `c_1`
WHERE
	`c_1`.`Id` = @id
```

The query executes without errors, but the result is empty (an entity with the id IS in the database, for sure). 
Looks like 'Guid' type in variable declaration causes the problem. Is there any workaround?

UPD
_____

The 'Declare' syntax worries me, there should be no '@' before a variable name. 

This code successfully executes in my IDE (DataGrip) and correctly returns the result:

```sql
--  MySqlConnector MySql
DECLARE id binary(16);
SET     @id = 0x0003057D9ED04FE186A0F76485759090;

SELECT
	`c_1`.`Name`
FROM
	`test` `c_1`
WHERE
	`c_1`.`Id` = @id;
```

### Environment details
linq2db version: *3.1.3*
Database Server: MySql
Database Provider: MySqlConnector 1.0.1
Operating system: Windows 10
.NET Framework: .Net Core 3.0

**Comment by MaceWindu** [comment]
Declare part of SQL log is for debug only and not a part of query (and could use non-db format for parameter values).
By default linq2db use string for Guid values for mysql provider, so as you figured out you need to specify custom formatter.
You set `ValueToSqlConverter` which is used for SQL literal generation, but your query use parameters, so you need to specify Guid to `DataParameter` conversion.
Something like this:
```cs
m.SetConvertExpression<Guid, DataParameter>(v => new DataParameter(null, FlipEndian(v.ToByteArray()), DataType.Binary), false);
```

**Comment by klym1** [comment]
Yes, that's it. Now it works, thanks!
