### ISSUE TITLE
How can I pass a Connectionstring + Provider to DataContext and DataConnection

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#250]
Hello,
I don´t want to use the Connection String in App.Config.

Is there a way to pass ConnectionString and Provider to the DataContext an DataConnection.

Is the a sample available ?
Thanks Andreas

**Comment by igor-tkachev** [comment]
Use one of the following constructors and methods:

```c#
public DataConnection(IDataProvider dataProvider, string connectionString)
public DataConnection(string providerName, string connectionString)

public static DataConnection LinqToDB.DataProvider.SqlServer.SqlServerTools.CreateDataConnection(string connectionString)
```

**Comment by ferbenor** [comment]
One question, is possible enabled storage in association attribute?

2015-08-12 20:48 GMT-05:00 Igor Tkachev <notifications@github.com>:

> Use one of the following constructors and methods:
>
> public DataConnection(IDataProvider dataProvider, string connectionString)public DataConnection(string providerName, string connectionString)
> public static DataConnection LinqToDB.DataProvider.SqlServer.SqlServerTools.CreateDataConnection(string connectionString)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linq2db/linq2db/issues/250#issuecomment-130504611>.
>



-- 
Att.
Fernando
