### ISSUE TITLE
T4 Error - Cannot load assembly Npgsql

### ISSUE THREAD

**Issue by Michael-Kempe** [linq2db/linq2db#2500]
After updating linq2db nuget packages to v3.1.3 I see an "System.InvalidOperationException: Cannot load Npgsql" when transforming T4 Templates. 

It would be nice if someone could give me some advice to resolve this...

Kind regards.

```
Exception message:
Running transformation: System.InvalidOperationException: Cannot load Npgsql
Stack trace:
Running transformation: System.InvalidOperationException: Cannot load assembly Npgsql
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.<>c.<.cctor>b__19_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.GetDataProvider(PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(String connectionString, PostgreSQLVersion version)
   at Microsoft.VisualStudio.TextTemplating22B79C917F41A76637B9515469CA25B69FB3F3D9BEDD3387198F0FA91CC5F6326E6317E03498F1E6D673F80B33B55F545F3683EEB59FD8185145C47E14BB2E46.GeneratedTextTransformation.GetPostgreSQLConnection(String connectionString) in F:\Packages\linq2db.PostgreSQL.3.1.3\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 130
   at Microsoft.VisualStudio.TextTemplating22B79C917F41A76637B9515469CA25B69FB3F3D9BEDD3387198F0FA91CC5F6326E6317E03498F1E6D673F80B33B55F545F3683EEB59FD8185145C47E14BB2E46.GeneratedTextTransformation.LoadPostgreSQLMetadata(String connectionString) in F:\Packages\linq2db.PostgreSQL.3.1.3\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 140
   at Microsoft.VisualStudio.TextTemplating22B79C917F41A76637B9515469CA25B69FB3F3D9BEDD3387198F0FA91CC5F6326E6317E03498F1E6D673F80B33B55F545F3683EEB59FD8185145C47E14BB2E46.GeneratedTextTransformation.TransformText() in F:\WL\DBv2\WL.DBv2\DBv2\Postgres\Logging.tt:line 26	Miscellaneous Files	F:\Packages\linq2db.PostgreSQL.3.1.3\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude	130	
```

### Environment details
linq2db version: 3.1.3
Database Server: Postgres 9.6
Operating system: Windows 10 - 2004
.NET Framework: 4.7

**Comment by MaceWindu** [comment]
do you have this file?
F:\Packages\linq2db.PostgreSQL.3.1.3\build\tools\Npgsql.dll

**Comment by Michael-Kempe** [comment]
No, but this file should be located here : F:\Packages\linq2db.PostgreSQL.3.1.3\tools\Npgsql.dll , right? Then yes!

**Comment by MaceWindu** [comment]
yep, sorry, without `build`

**Comment by MaceWindu** [comment]
could you run template in debug and check exception reason in exception object? I suspect it is not due missing provider assembly.

**Comment by Michael-Kempe** [comment]
Yes. File exists. The exception happens in 
LinqToDB.PostgresSQL.ttinclude:

LinqToDB.Data.DataConnection GetPostgreSQLConnection(string connectionString)
{
	return LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(connectionString);
}
![image](https://user-images.githubusercontent.com/46563088/93876036-6a9b8780-fcd6-11ea-9313-ff5cdda55309.png)

**Comment by Michael-Kempe** [comment]
Just a short note: all our nuget-packages are located in a different path. This path is NOT part of the Solution. But this has worked flawlessly before.

**Comment by MaceWindu** [comment]
That's correct location. T4 templates use files from nuget cache but it is not clear why assembly load fails. You can try to enable break on handled exceptions - maybe there is more specific exception here

**Comment by Michael-Kempe** [comment]
Sorry. No more details. But I can see that npgsql.dll has been loaded:
...
'T4VSHostProcess.exe' (CLR v4.0.30319: transformDomaina65b7055-d9b1-429f-b9a6-cada02a9b513): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.TextTemplating.Interfaces.10.0.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'T4VSHostProcess.exe' (CLR v4.0.30319: transformDomaina65b7055-d9b1-429f-b9a6-cada02a9b513): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'T4VSHostProcess.exe' (CLR v4.0.30319: transformDomaina65b7055-d9b1-429f-b9a6-cada02a9b513): **Loaded 'F:\Packages\linq2db.PostgreSQL.3.1.3\tools\Npgsql.dll'**. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'T4VSHostProcess.exe' (CLR v4.0.30319: transformDomaina65b7055-d9b1-429f-b9a6-cada02a9b513): Loaded 'F:\Packages\linq2db.PostgreSQL.3.1.3\tools\System.Threading.Tasks.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'T4VSHostProcess.exe' (CLR v4.0.30319: transformDomaina65b7055-d9b1-429f-b9a6-cada02a9b513): Loaded 'F:\Packages\linq2db.Access.3.1.3\tools\linq2db.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'T4VSHostProcess.exe' (CLR v4.0.30319: transformDomaina65b7055-d9b1-429f-b9a6-cada02a9b513): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
...

**Comment by MaceWindu** [comment]
Which version you used before update?

**Comment by Michael-Kempe** [comment]
Updated from v3.1.2. And only the linq2db.* packages have been updated. I'm going to build a dummy project. I check to see if the problem occurs there.

**Comment by MaceWindu** [comment]
You can also try to execute following code while in debugger (this is code, which actually fails) and see if it will give you some details:
```cs
Assembly.Load("Npgsql")
```

**Comment by Michael-Kempe** [comment]
Changed the script to:
LinqToDB.Data.DataConnection GetPostgreSQLConnection(string connectionString)
{
	System.Reflection.Assembly.Load("Npgsql");
	return LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(connectionString);
}
This gives me System.IO.FileNotFoundException!

**Comment by MaceWindu** [comment]
this doesn't make sense... could you check that assembly is not locked? (copy it to another place and back)

**Comment by Michael-Kempe** [comment]
I can rename the file.

**Comment by Michael-Kempe** [comment]
Changed the script to:
LinqToDB.Data.DataConnection GetPostgreSQLConnection(string connectionString)
{
	System.Reflection.Assembly.LoadFile(@"F:\Packages\linq2db.PostgreSQL.3.1.3\tools\Npgsql.dll");
	return LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(connectionString);
}
LoadFile(...) works, but CreateDataConnection() returns the error 'Cannot load assembly Npgsql' error.

**Comment by MaceWindu** [comment]
assembly is loaded by  `LinqToDB.PostgreSQL.Tools.ttinclude` file.
If you change path there to full path - will it work?
```
<#@ assembly name="$(LinqToDBT4PostgreSQLToolsDirectory)Npgsql.dll" #>
```
if yes, than it could be that LinqToDBT4PostgreSQLToolsDirectory msbuild property is broken for some reason

**Comment by Michael-Kempe** [comment]
I've replaced it on three locations:
1. In my "Project\LinqToDB.Templates\LinqToDB.PostgreSQL.Tools.ttinclude"
2. F:\Packages\linq2db.PostgreSQL.3.1.3\content\LinqToDB.Templates\LinqToDB.PostgreSQL.Tools.ttinclude
3. F:\Packages\linq2db.PostgreSQL.3.1.3\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.Tools.ttinclude
The line is now:
<#@ assembly name="F:\Packages\linq2db.PostgreSQL.3.1.3\tools\Npgsql.dll" #>
Still the same error. 
Also replacing the path with double backslash returns the same error.

Drives me crazy. I tried everything I could think of...

**Comment by sdanyliv** [comment]
Try clean way:
1. Uninstall linq2db.PostgreSQL and install again
2. If it is still fail. Uninstall linq2db.PostgreSQL, purge NuGet cache and install again
![image](https://user-images.githubusercontent.com/783759/93891662-523a6580-fcf4-11ea-97e8-601bbd482998.png)

**Comment by Michael-Kempe** [comment]
Already did this... :-(

**Comment by MaceWindu** [comment]
out of ideas...
Try to check fusion logs https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

**Comment by Michael-Kempe** [comment]
Ok. I keep looking for a solution. If I have one, I'll let you know. 
Many thanks for your effort!

**Comment by Michael-Kempe** [comment]
After checking with fuslogvw.exe I see the problem: The npgsql.dll file is searched in the wrong directory : \linq2db.Access.3.1.3\tools\ instead of \linq2db.PostgreSQL.3.1.3\tools\ .

Here's the log file:
*** Assembly Binder Log Entry  (24.09.2020 @ 11:19:45) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Npgsql
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: Npgsql | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = devenv.exe
Calling assembly : linq2db, Version=3.0.1.0, Culture=neutral, PublicKeyToken=e41013125f9e410a.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\m.kempe\AppData\Local\Microsoft\VisualStudio\16.0_ed543632\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PublicAssemblies/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PublicAssemblies/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Platform/Debugger/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Platform/Debugger/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/x86/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/x86/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/Npgsql/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PublicAssemblies/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PublicAssemblies/Npgsql/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/Npgsql/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow/Npgsql/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Platform/Debugger/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Platform/Debugger/Npgsql/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/Npgsql/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/x86/Npgsql.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/PrivateAssemblies/DataCollectors/x86/Npgsql/Npgsql.EXE.
**LOG: Attempting download of new URL file:///F:/Packages/linq2db.Access.3.0.1/tools/Npgsql.DLL.
LOG: Attempting download of new URL file:///F:/Packages/linq2db.Access.3.0.1/tools/Npgsql/Npgsql.DLL.
LOG: Attempting download of new URL file:///F:/Packages/linq2db.Access.3.0.1/tools/Npgsql.EXE.
LOG: Attempting download of new URL file:///F:/Packages/linq2db.Access.3.0.1/tools/Npgsql/Npgsql.EXE.**
LOG: All probing URLs attempted and failed.

Any ideas, why this happens now? I got 3 different databases in my project: Access, Postgres and SQLite.

**Comment by MaceWindu** [comment]
My bad. Was sure it is not the case here. This is same as #2485

**Comment by Michael-Kempe** [comment]
OK. However, the problem has only recently appeared.

**Comment by MaceWindu** [comment]
I suspect it appeared only now because installation order changed and now postgresql package is not the last one istalled. Because access doesn't require additional provider libraries (from other side sqlite still needs them)
