### ISSUE TITLE
By-convention registrations

### ISSUE THREAD

**Issue by klym1** [linq2db/linq2db#2501]
So, basically I'm looking for a way to automatically register properties in my DTOs as columns (column name matches property name) 
I'm trying to migrate an existing project based on Dapper, and I don't want to manually add [Column] attribute to several hundreds of properties.  

So far, I've found the following ways to deal with mappings:

1) FluentMappingBuilder (there's no non-generic version, but looks like this is the only viable option)
2) MappingSchema.EntityDescriptorCreatedCallback (doesn't allow adding new columns, unfortunately)
3) MappingSchema.GetEntityDescriptor() allows adding new columns but it seems it doesn't have any effect at all.

Are there any other options?

### Environment details
linq2db version: *3.1.3*
Database Server: MySql
Database Provider: MySqlConnector 1.0.1
Operating system: Windows 10
.NET Framework: .Net Core 3.0

**Comment by MaceWindu** [comment]
E.g. you can create your own metadata provider (check https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Metadata/AttributeReader.cs for example) where you create `ColumnAttribute` for property with any naming convention you like (PRs are appreciated).

**Comment by MaceWindu** [comment]
In one of my projects I read metadata from database
```cs
TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, bool inherit)
        {
            if (typeof(TableAttribute) == typeof(TAttribute))
            {
                 // here you can create custom TableAttribute for your DTO
            }

            return Array.Empty<TAttribute>();
        }


TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, MemberInfo memberInfo, bool inherit)
        {
            if (typeof(ColumnAttribute) == typeof(TAttribute))
            {
               // here you create ColumnAttribute instance and set column name using your convention
               // if memberInfo is your property
            }

            return Array.Empty<TAttribute>();
        }
```

Registration:
```cs
 LinqToDB.Mapping.MappingSchema.Default.AddMetadataReader(new ByConventionMetadataProvider() { /*convention settings*/ });
```

**Comment by klym1** [comment]
Yes, that works. Thanks for the fast reply.

This solution indeed works, but it looks kinda 'hacky' (pardon me). I think adding a new 'registration mechanism' with 'by convention' approach would be very valuable. It will enable easier transition for the users who migrate their projects from some other libraries (like myself) and help to grow the community faster. Also, this will help the old projects with linq2db too, as most of the time, the projects do have some naming conventions for their columns/properties, and not having to type [Column] would be greatly appreciated.

**Comment by MaceWindu** [comment]
Not sure I understand why it is hacky. `IMetadataReader` is a standard linq2db mechanism to provide model metadata from different sources (inlcuding not only attributes, but also fluent mapping, xml files, etc.).
Probably you were confused that it returns attributes (linq2db consume attributes to build internal data model).

**Comment by klym1** [comment]
It's hacky because of a leaky abstraction: marking a property by an attribute to specify it as a column - is an implementation detail and it's quite low-level. There must be some higher-level entity for that, an abstraction that hides this detail.
Think it the other way - IMetadataReader returns an attribute which is really not there (not on the class type/property type)! 
Given the name - IMetadataReader - it should return not Attributes but some abstractions over it.

**Comment by MaceWindu** [comment]
Got your point.  I don't know why we use attributes here (probably initial implementation used attributes and metadata readers were added later). Don't see real benefits for now to change it and introduce additional model hierarchy, but maybe we will revisit it at some point.

**Comment by Jure-BB** [comment]
Here's a MetadataReader for convention based naming and an example of snake case naming convention, that converts from pascal case (eg. `ColumnName`) to snake case (`column_name`) using Humanizer library.

It can be registered with:
`LinqToDB.Mapping.MappingSchema.Default.AddMetadataReader(new SnakeCaseNamingConventionMetadataReader());`

...or by passing custom convention function to CustomNamingConventionMetadataReader: 
`LinqToDB.Mapping.MappingSchema.Default.AddMetadataReader(new CustomNamingConventionMetadataReader(name => name.Underscore()));` (This example functions the same as SnakeCaseNamingConventionMetadataReader.)


```
using System;
using System.Reflection;
using Humanizer;
using LinqToDB.Common;
using LinqToDB.Mapping;
using LinqToDB.Metadata;

namespace Linq2DbNamingConventions
{
    public class SnakeCaseNamingConventionMetadataReader : CustomNamingConventionMetadataReader
    {
        public SnakeCaseNamingConventionMetadataReader()
            : base(name => name.Underscore())
        {
        }
    }

    public class CustomNamingConventionMetadataReader : IMetadataReader
    {
        private readonly Func<string, string> _namingConvention;
        private readonly AttributeReader _reader = new();

        public CustomNamingConventionMetadataReader(Func<string, string> namingConvention)
        {
            _namingConvention = namingConvention;
        }

        public T[] GetAttributes<T>(Type type, bool inherit = true)
            where T : Attribute
        {
            if (typeof(T) == typeof(TableAttribute))
            {
                var tableAttributes = _reader.GetAttributes<TableAttribute>(type, inherit);
                var tableAttributes2 =
                    _reader.GetAttributes<System.ComponentModel.DataAnnotations.Schema.TableAttribute>(
                        type, inherit);

                // Don't use convention if TableAttribute is already defined
                if (tableAttributes.Length + tableAttributes2.Length == 0)
                {
                    var attribute = new TableAttribute()
                    {
                        // get type name and apply naming convention
                        Name = _namingConvention(type.Name),
                    };
                    return new[] {(attribute as T)!};
                }
            }

            return Array<T>.Empty;
        }

        public T[] GetAttributes<T>(Type type, MemberInfo memberInfo, bool inherit = true)
            where T : Attribute
        {
            if (typeof(T) == typeof(ColumnAttribute))
            {
                var columnAttributes = _reader.GetAttributes<ColumnAttribute>(
                    type, memberInfo, inherit);
                var columnAttributes2 =
                    _reader.GetAttributes<System.ComponentModel.DataAnnotations.Schema.ColumnAttribute>(
                        type, memberInfo, inherit);

                // Don't use convention if ColumnAttribute is already defined
                if (columnAttributes.Length + columnAttributes2.Length == 0)
                {
                    var attribute = new ColumnAttribute()
                    {
                        // get property name and apply naming convention
                        Name = _namingConvention(memberInfo.Name),
                    };
                    return new[] {(attribute as T)!};
                }
            }

            return Array<T>.Empty;
        }

        /// <inheritdoc cref="IMetadataReader.GetDynamicColumns"/>
        public MemberInfo[] GetDynamicColumns(Type type)
            => Array<MemberInfo>.Empty;
    }
}
```

@MaceWindu does this implementation of metadata reader look ok? I'm new to Linq2db.

**Comment by MaceWindu** [comment]
Looks fine to me

**Comment by wseegersatdealx** [comment]
A more up to date version specifically for SnakeCase.

```
public class SnakeCaseNamingConventionMetadataReader : IMetadataReader
{
    private readonly Func<string, string> _namingConvention = name => name.Underscore();
    private readonly AttributeReader _reader = new();

    public MappingAttribute[] GetAttributes(Type type)
    {
        var attributes = _reader.GetAttributes(type);

        if (attributes.Any(x => x is TableAttribute))
        {
            return attributes;
        }

        return attributes.Concat([
            new TableAttribute()
            {
                // get type name and apply naming convention
                Name = _namingConvention(type.Name),
            }
        ]).ToArray();
    }

    public MappingAttribute[] GetAttributes(Type type, MemberInfo memberInfo)
    {
        var attributes = _reader.GetAttributes(type);

        if (attributes.Any(x => x is ColumnAttribute))
        {
            return attributes;
        }

        return attributes.Concat([
            new ColumnAttribute()
            {
                // get type name and apply naming convention
                Name = _namingConvention(memberInfo.Name),
            }
        ]).ToArray();
    }

    public MemberInfo[] GetDynamicColumns(Type type) => [];

    public string GetObjectID()
    {
        return nameof(SnakeCaseNamingConventionMetadataReader);
    }
}
```

**Comment by MaceWindu** [comment]
Closing as answered
