### ISSUE TITLE
Templates do not work with JetBrains Rider C# IDE (non-windows)

### ISSUE THREAD

**Issue by JakeSays** [linq2db/linq2db#2515]
The postgresql package installs a bunch of TT templates that are not compatible with Rider as they take a dependency on Visual Studio assemblies.

linq2db version: 3.1.3
Database Server: postgresql 13
Database Provider: npgsql 5.0.0-alpha1
Operating system: ubuntu 20.04
.NET Framework: netcoreapp3.1

**Comment by MaceWindu** [comment]
Currently we officially support T4 generation only for full VS, but JetBrains implemented VS-like T4 support in Rider for some time already.
I see here https://github.com/JetBrains/ForTea/issues/12 several reports that T4 support in Rider regressed recently, so I would recomment to add more info there.

BTW, we are going to implement new platform-independent scaffolding mechanisms without T4 in near future.

**Comment by JakeSays** [comment]
@MaceWindu In the interim can you please implement a way to disable template support? I don't actually use templates when doing development, and it is a real annoyance to have them in my project.

**Comment by MaceWindu** [comment]
In that case you should intall `linq2db` package directly (+provider nuget). `linq2db.<DB_NAME>` packages only needed if you want to use T4 templates

**Comment by JakeSays** [comment]
Ohhh! Lol that makes things simple enough! Thanks!

Also I am not sure what you have in mind for your templating solution, but I would suggest using .csx scripts. Most of the T4 templates are basically just c#, so it makes sense to use actual c# to do it. I use .csx files for that kind of thing all the time. Roslyn's scripting apis are run on both the full framework and net core, so they would work in both VS and Rider.

**Comment by dabide** [comment]
@MaceWindu Is any work being done on this currently? I'm considering taking a look at if the templates can be modified to work with this tool, making them cross platform and command line friendly: https://github.com/mono/t4

**Comment by MaceWindu** [comment]
Nope, we plan to implement dotnet tool instead for this.
Main problems with T4 for non-windows platform are:
- mono implementation doesn't have preprocessor to resolve MSBUILD properties. Which is needed to locate tools binaries, used for generation (linq2db + providers), e.g. [$(LinqToDBT4SharedTools)](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB.Templates/LinqToDB.Tools.ttinclude#L2)
- templates (and tools) expect .net framework runtime, so if we wan't to run T4 template under linux/mac, we should include .net core versions of linq2db/providers in tools folder

**Comment by dabide** [comment]
I see. Is there any timeline for this?

**Comment by MaceWindu** [comment]
Well... I need to finish firebird provider refactoring first (#2693) then I plan to work on it. I would expect to start working on it in February

**Comment by MaceWindu** [comment]
FYI https://github.com/linq2db/linq2db/pull/3098#issuecomment-1022184862
