### ISSUE TITLE
Linq2db DbContext memory issue.

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#2519]
We have an repository class where we are getting memory leak, so wanted to double check are we disposing DbContext class 
correctly.

we are using singleton for OracleRetryFailure class and ILogger interface in DI container.

```csharp
    public sealed class OracleRetryFailure
    {
        private readonly ILogger _logger;

        private readonly HashSet<int> _retryCodeHash = new HashSet<int>();

        private const int RetryMaxCount = 6;

        public OracleRetryFailure(ILogger logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _ = _retryCodeHash.Add(12570);
            _ = _retryCodeHash.Add(12571);
            _ = _retryCodeHash.Add(56600);
            _ = _retryCodeHash.Add(-1000);
            _ = _retryCodeHash.Add(-6403);
            _ = _retryCodeHash.Add(12545);
            _ = _retryCodeHash.Add(-1012);
        }

        public async Task<List<T>> QueryToListAsync<T>(string query, object parameters)
        {
            int count = 0;
            DBConnectionService connectionService = null;
            while (count < RetryMaxCount)
            {
                try
                {
                    connectionService = new DBConnectionService();
                    return await connectionService.QueryToListAsync<T>(query, parameters);
                }
                catch (OracleException oex)
                {
                    if (_retryCodeHash.Contains(oex.Number))
                    {
                        count++;
                        if (connectionService?.Connection != null)
                        {   
                            OracleConnection.ClearPool((OracleConnection)connectionService.Connection);
                        }
                    }
                    else
                    {
                        throw;
                    }
                }
                finally
                {
                    if (connectionService != null)
                    {
                        await connectionService.DisposeAsync();
                    }
                }
            }
            return default;
        }
    }

public class DBConnectionService : DataConnection
{
        public DBConnectionService() : base("Oracle") { }

        public ITable<TableA> TableA => GetTable<TableA>();
}
```

### Environment details
linq2db version: *2.9.8*
Database Server: *Linux*
Database Provider: *Oracle*
Operating system: *Alpine OS web api*
.NET Core: *3.1*

**Comment by viceroypenguin** [comment]
There a significant memory and performance enhancements between 2.9 and 3.0, and we are no longer actively supporting 2.9.

Can you please try w/ v3.1.3 and see if you are still getting the issue?

**Comment by sarabu07** [comment]
@viceroypenguin We found an issue with v3 https://github.com/linq2db/linq2db/issues/2504 so still using v2.9.8

**Comment by sarabu07** [comment]
@viceroypenguin I found the database connection is not disposed and please see below the before and after changes how we made the connection object to dispose.

Before change:
if (connectionService != null)
{
       await connectionService.DisposeAsync();
}

After change:

if (connectionService != null)
 {
        await connectionService.DisposeAsync();

         if (connectionService?.Connection != null)
        {
                  await ((OracleConnection)connectionService?.Connection).DisposeAsync();
        }
       connectionService = default;
}

**Comment by viceroypenguin** [comment]
Thanks for the info. I'll do some research on it. The code looks like it should be disposing the connection, at least in current versions of L2DB.

**Comment by viceroypenguin** [comment]
Now that 3.1.4 has been released, are you able to upgrade and see if you are still experiencing the memory issues?

**Comment by sdanyliv** [comment]
@sarabu07, issue still exists?

**Comment by sarabu07** [comment]
@sdanyliv The issue is still occurring. I see 'OracleInternal.Common.ZoneValue' object called multiple times
<img width="1401" alt="Screenshot 2020-10-28 at 3 32 27 AM" src="https://user-images.githubusercontent.com/19915610/97488121-d0d59300-1983-11eb-8de5-1f1a66eb5fc6.png">

**Comment by sdanyliv** [comment]
It would be better if you prepare small runnable application with problem reproducing. But I don't think that it is linq2db bug, but who knows.

**Comment by viceroypenguin** [comment]
@sarabu07  - closing for now due to lack of activity. If you identify this as an l2db bug, please reopen or create a new issue.
