### ISSUE TITLE
How to choose a dialect of Oracle 11g?

### ISSUE THREAD

**Issue by B7R5** [linq2db/linq2db#2520]
Describe your issue.

How to choose a dialect of Oracle 11g?
After migration from 2.9.8 to 3.1.3 'Take ()' expression does not work for Oracle 11g with provider name "Oracle".
When I changed the provider name to "Oracle.Managed" the version was selected correctly.

### Environment details
linq2db version: 3.1.3
Database Server: Oracle 11g2
Database Provider: "Oracle", "Oracle.Managed"
Operating system: Windows Server 2012 R2 (Oracle), Windows 10 (Client)
.NET Framework: 4.8

**Comment by MaceWindu** [comment]
Starting from v3 default dialect is v12 (https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#oracle-12-dialect-support)

Way to enable v11 dialect depends on your configuration approach:
- add 11 to connection string name https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/OracleTools.cs#L100
- if you create provider in code, you can specify version using `OracleVersion` enum https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/OracleTools.cs#L173

**Comment by B7R5** [comment]
I made a constructor with an outer transaction. It seems to work.
`
public EraRepairsOracleContext(IScopeConnectionSource connectionSource) : 
        base(
            DataConnection.GetDataProvider(
                  "Oracle.Managed", "Oracle.Managed.11", connectionSource.Connection.ConnectionString), 
            connectionSource.Transaction)
        {
            InitDataContext();
            InitMappingSchema();
        }
`
