### ISSUE TITLE
Flag AllowMultipleQuery and new eager load feature 

### ISSUE THREAD

**Issue by yurriiy** [linq2db/linq2db#2521]
Hi, guys!
Since the new feature works fine and doesn't generate unnecessary requests, it might be worth dropping the binding to flag AllowMultipleQuery?

Thanks for the work you've done!

**Comment by sdanyliv** [comment]
I think we can ignore it for Eager Load

**Comment by MaceWindu** [comment]
In that case we return to question - why we need this option at all? connection cloning in group by guarded by separate setting.
