### ISSUE TITLE
Change default escaping options for Oracle provider

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#2526]
Could you try and set
```cs
OracleTools.DontEscapeLowercaseIdentifiers = false;
```
option?
I wonder why we have it set to true by default.

_Originally posted by @MaceWindu in https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/67#issuecomment-704788338_

**Comment by edsdck** [comment]
hey, could you assign me on this one?

**Comment by MaceWindu** [comment]
Sure :+1:
