### ISSUE TITLE
Auditing MERGE operation client-side?

### ISSUE THREAD

**Issue by davidjamesb** [linq2db/linq2db#2529]
I'm implementing functionality to merge data in a staging Azure SQL database into a live Azure SQL database. The databases are connected using external data source/tables.

Upon a data merge, I need to return the changes (inserted, updated, deleted) that were performed for auditing purposes. 

Is it possible to execute a C# method on the client-side for each change (or batch of changes), such that it can be passed down to logging/event services for processing? E.g. add each change to an in-memory list.

Otherwise, I guess I would have to OUTPUT a table from the merge API containing an ACTION column to represent what change took place. Are there any examples/tests for such a case?

I ideally want to do as much as possible in code without resorting to stored procedures if possible. Trying to avoid triggers at this stage.

Thanks.

**Comment by MaceWindu** [comment]
OUTPUT support for MERGE is not implemented yet (#869), maybe @viceroypenguin have it on his implementation list

**Comment by DJBMASTER** [comment]
> OUTPUT support for MERGE is not implemented yet (#869), maybe @viceroypenguin have it on his implementation list

Yes I have seen this issue, but my question was more regarding whether it is possible to have a client-side callback for example, when InsertWhenNotMatched(source => {myLocalMethod(source}) such that I can capture the changes on the C# side, for further processing?

Furthermore, if I can not do this, can you recommend the best approach to take using as much Linq2db as possible to achieve my goal of getting merge changes (whilst waiting for the future MERGE OUTPUT support)?

Otherwise, can you point me to example/tests of returning a table from a store proc call in linq2db.

Thanks.

**Comment by MaceWindu** [comment]
> my question was more regarding whether it is possible to have a client-side callback 

this is not possible, database selects operation based on data/conditions and only way to tell what operation occured is to process OUTPUT clause.

> if I can not do this, can you recommend the best approach to take using as much Linq2db as possible to achieve my goal of getting merge changes

These is one very ugly hack which probably will work -  you can append/prepend raw SQL to any query using NextQueryHints context collection. You can try to add OUTPUT clause to your query with INSERT to some temp/log table and then query that table after merge.

For stored procedure with table results check tests [here](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Data/ProcedureTests.cs): `QueryProc/Async` for single-resultset and `QueryProcMultiple/Async` for multiple resultsets

**Comment by viceroypenguin** [comment]
@davidjamesb With #3241 merged, you can receive the `$ACTION` provided from the server in the output dataset. From there, you can process each record according to what was done on the server.
