### ISSUE TITLE
regression bug 3.1.1 => 3.1.2 (3.1.3 or 3.1.4) in the populating data from one column to two properties in the class.

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2530]
The regression bug was found in the populating data from one column in DB table to two properties in the class.
This bug occurs in 3.1.2 (and 3.1.3, and 3.1.4 (today build)), 
but not in 3.1.1 or less

### Steps to reproduce

**SQL test structure** and inserting one row for the test:

```sql
create table test_mapping_column_2_prop
(
    id                bigserial     not null  constraint pk_test_map primary key,
    test_number       bigint     not null
);

insert into test_mapping_column_2_prop (test_number) values (777);
```

**Class on C#** (**_two properties to the one column_**):
```c#
[Table("test_mapping_column_2_prop")]
public partial class TestMappingColumn2PropInfo 
{
	[Column("id"),          PrimaryKey, Identity] public long Id         { get; set; } // bigint
	[Column("test_number"), NotNull             ] public long TestNumber { get; set; } // bigint

	[Column("test_number"), NotNull] public long TestNumberLast { get; set; } // bigint
}
```
**The test C# code:**
```c#
var testInfo = db.TestMappingColumn2Props.FirstOrDefault();
```
**The output in the moment of selecting:**

```
DataConnection: ====================================
08.10.2020 04:33:27.199  BeforeExecute
-- PostgreSQL PostgreSQL.9.5 PostgreSQL
DECLARE @take Integer -- Int32
SET     @take = 1

SELECT
	t1.id,
	t1.test_number,
	t1.test_number
FROM
	test_mapping_column_2_prop t1
LIMIT :take

DataConnection: ====================================
08.10.2020 04:33:27.204  Query Execution Time (AfterExecute): 00:00:00.0050989

DataConnection: ====================================
08.10.2020 04:33:27.213  Total Execution Time (Completed): 00:00:00.0146411. Rows Count: 1.
```

**The screenshots with the debug breakpoints shown the problem.**

**Version 3.1.1** works well

![image](https://user-images.githubusercontent.com/30083441/95467454-240c8500-0986-11eb-9a26-2dee6d4a70c2.png)

**Version 3.1.2** works wrong

![image](https://user-images.githubusercontent.com/30083441/95467542-41415380-0986-11eb-8f6a-a3e38b354b05.png)

Version 3.1.3 and 3.1.4(today build) work the same wrong as Version 3.1.2...

### Environment details
linq2db version: *3.1.2*
Database Server: *PostgreSQL 12.1*
Database Provider: *Npgsql 4.1.4*
Operating system: *Windows 10*
.NET Framework: *.Net Core 3.1*

**Comment by MaceWindu** [comment]
Could you provide more details why do you have two mappings for single column?

**Comment by AndrePScope** [comment]
This is needed for the implementation of optimistic locking on DB.
The table has the column that determines the version of the row.

After the reading data, when we need to update a row, one property should be changed for the new value of version (Entity_Tag), the second should stay such as in DB, for the check on DB side (Last_Entity_Tag).

Moreover, we mark the second one property to the PK attribute, so Linq2Db adds an SQL filter automatic for all updates. This is very useful.

I described this approach in more detail in the ticket
https://github.com/linq2db/linq2db/issues/553
Here:
https://github.com/linq2db/linq2db/issues/553#issuecomment-607278884

**Comment by AndrePScope** [comment]
I see you planned to release this fix in the 3.2.0.
Thank you!!! 

Will wait for this version.

**Comment by MaceWindu** [comment]
3.2.0 or if we will have another minor release - we will add it here

**Comment by AndrePScope** [comment]
Super! Thank you very much!!!
