### ISSUE TITLE
StringAggregate alternative on SqlServer2012

### ISSUE THREAD

**Issue by Feroks** [linq2db/linq2db#2531]
I am struggling to replicate following SQL in C#:
```sql
SELECT STUFF((
    SELECT
        ', ' + myTable.stringField
    FROM
        myTable
    ORDER BY
        1
    FOR XML PATH('')), 1, 2, '')
```
I know that SqlServer2017 has `.StringAggregate()`, but my server version is lower. I have tried following:
- Use `Aggregate`. Requires multiple queries to run.
- Use `string.Join`. Requires multiple queries to run.
- Use `Stuff` extension and append `ORDER BY 1 FOR XML PATH('')` by using custom extension. Select part is wrapped in brackets and I get invalid SQL as result.

Is there any existing API that I can use?

### Environment details
linq2db version: 3.1.2
Database Server: SqlServer
Database Provider: SqlServer2012
Operating system: Windows
.NET Framework: 4.6.2

**Comment by sdanyliv** [comment]
This one can be executed via 
```cs
var str = db.Select(() => Sql.Expr<string>(@"SELECT STUFF((
    SELECT
        ', ' + myTable.stringField
    FROM
        myTable
    ORDER BY
        1
    FOR XML PATH('')), 1, 2, '')"));
```
You can use `Sql.Expr` to define a projection column.

But it will not help in grouping query and needs to be rewritten every time because you have to use grouping key in WHERE clause.

```cs
var query = from m in db.MyTable
   group m by new { m.GroupingKey } into g
   select new 
   { 
       g.Key.GroupingKey,
       Aggregated = Sql.Expr<string>($@"SELECT STUFF((
    SELECT
        ', ' + myTable.stringField
    FROM
        myTable
    WHERE
       myTable.GroupingKey = {g.Key.GroupingKey}
    ORDER BY
        1
    FOR XML PATH('')), 1, 2, '')")
   }
```

So, examples above are workarounds and you cannot create common function without changing linq2db sources.

**Comment by Feroks** [comment]
I thought about `Sql.Expr` as well, but hoped it could be avoided. Problem is that I am trying to execute this sql for calculated field and it requires some additional logic. Here is a full sample:
```csharp
private static Expression<Func<TblFirma, IDataContext, string?>> AllStringFields()
{
    return (entity, db) => Sql.Expr<string?>(
        $@"STUFF((
            SELECT
                ', ' + myTable.stringField
            FROM
                myTable
            WHERE
                myTable.Id = {Sql.Property<int>(entity, nameof(Id))}
                AND
                {db.GetForDate()} BETWEEN myTable.DateFrom AND myTable.DateTo
            ORDER BY
                1
            FOR XML PATH('')), 1, 2, '')");
}
```
As you can see I filter by Id and also by Date that I access via extension from `IDataContext`.
I need to use string interpolation to resolve `entity.Id` correctly, but this makes `GetForDate()` to be resolved only once, which makes sense.
I have tried to use `{0}` instead and pass `DataParameter`, but then I get an error that `dctx` can not be resolved.
The only workaround I have in mind right now is:
- Hardcode `@datForDate` in the expression.
- Subscribe to DataContext `OnTrace` event.
- Add `@datForDate` SqlParameter to command.

**Comment by Feroks** [comment]
My suggested workaround works. Hopefully, I will not run into some edge cases.
@sdanyliv thank you for the response. I think you can close this issue.
