### ISSUE TITLE
QueryCache - LoadWith() doesn't return data the second time the query is executed after updating to version 3.1.4

### ISSUE THREAD

**Issue by TsakiDev** [linq2db/linq2db#2532]
Hello, after updating to version 3.1.4 doesn't return data the second time the query is executed with a different `Id`

```cs

//Adding ClearCaches fixes the issue
//LinqToDB.Linq.Query.ClearCaches();

LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
IQueryable.LoadWith(o => o.ListOfObjects.First().SecondListOfObjects)
    .LoadWith(o => o.ListOfObjects.First().OneObject)
    .LoadWith(d => d.ListOfObjects.First().ThirdListOfObjects.First().SecondObject)
    .FirstOrDefault(o => o.Id == Id);
LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = false;
```

**Comment by sdanyliv** [comment]
1. From which version you have updated?
2. It is reproducible without `LoadWith`?
3. Could you please also try?
```cs
IQueryable
     .LoadWith(o => o.ListOfObjects)
         .ThenLoad(l => l.SecondListOfObjects)
     .LoadWith(o => o.ListOfObjects)
         .ThenLoad(l => l.OneObject)
    .LoadWith(o => o.ListOfObjects)
         .ThenLoad(l => l.ThirdListOfObjects)
            .ThenLoad(l => l.SecondObject)
    .FirstOrDefault(o => o.Id == Id);
```

**Comment by TsakiDev** [comment]
> 1. From which version you have updated?
> 2. It is reproducible without `LoadWith`?
> 3. Could you please also try?
> 
> ```cs
> IQueryable
>      .LoadWith(o => o.ListOfObjects)
>          .ThenLoad(l => l.SecondListOfObjects)
>      .LoadWith(o => o.ListOfObjects)
>          .ThenLoad(l => l.OneObject)
>     .LoadWith(o => o.ListOfObjects)
>          .ThenLoad(l => l.ThirdListOfObjects)
>             .ThenLoad(l => l.SecondObject)
>     .FirstOrDefault(o => o.Id == Id);
> ```

1. From version 3.1.3
2. I'm not sure on how to do it?! But from what I tried no...?!
3. It has the same effect unfortunately

**Comment by sdanyliv** [comment]
Ok, I know root of the problem, will fix that for the next release.

**Comment by TsakiDev** [comment]
Thank you very much!!!
