### ISSUE TITLE
Another LINQPad crash when connecting to Access 2003 mdb database

### ISSUE THREAD

**Issue by smithnigelw** [linq2db/linq2db#2534]
![image](https://user-images.githubusercontent.com/630841/66592998-12837800-eb8e-11e9-9f8d-d7593357dc6a.png)
I'm trying to use the 'LINQ to DB' driver for the first time. My connection string is:
`Provider=Microsoft.ACE.OLEDB.16.0;Data Source=<<Path to mdb>>;User Id=Admin;Password=;`
I'm using this same connection string with 'OleDbConnection()' from a c# console app without any problem. 
The 'Test' button says the connection is successful.
The database has over 30 tables. 
Maybe 'LINQ to DB' is objecting to just one, or more, of the queries in this database, but as it has over 200, the question is 'which one?'.
I've Googled the error "Operation is not valid due to the current state of the object" but I don't understand whats going wrong. Maybe something to do with 'System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()' ?

**Comment by MaceWindu** [comment]
Moving it here. We should throw more detailed exception from `GetSystemType` or return null.
