### ISSUE TITLE
MS SQL Server Free Text Search Contains function doesn't seem to be working

### ISSUE THREAD

**Issue by rserj** [linq2db/linq2db#2537]
I'm trying to use CONTAINS (Transact-SQL) function like this

`db.UserEmail.Where(email => Sql.Ext.SqlServer().Contains(email, "admin@gmail.com", "Email")); `

It generates incorrect TSQL

```
--   SqlServer.2012
SELECT
	[email_1].[Id],
	[email_1].[UserId],
	[email_1].[Email]
         ....
FROM
	[dbo].[UserEmail] [email_1]
WHERE
	CONTAINS((N'Email'), N'admin@gmail.com')
```
CONTAINS function expects the Column itself as a first argument rather than string N'Email'

Am I missing something?
Thanks in advance

### Environment details
linq2db version: 2.98
Database Server: MS SQL Server 2019
.NET Framework: 4.8

**Comment by sdanyliv** [comment]
Not a familiar with these extensions but looks like you have used them in wrong way

```cs
db.UserEmail.Where(email => Sql.Ext.SqlServer().Contains("admin@gmail.com", email.Email));
```

**Comment by MaceWindu** [comment]
Check documentation and test examples for this API here https://github.com/linq2db/linq2db/wiki/Archived-Release-Notes#full-text-search-support-1649-2

Anyway, I think we should add some validation to prevent non-column values for columns parameter to prevent it.

**Comment by rserj** [comment]
@MaceWindu thanks for your reply with examples, I quickly looked through the link and all I could find is a prototype
```
// CONTAINS((columns), ..)
Sql.Ext.SqlServer().Contains(table, search, param[] columns);
```
which I'm basically using above that didn't work for me.
I think it will be great having documentation with real examples and it might be beneficiary having some overrides so I would rather specify column names as an expression `tbl => tbl.Email` rather than just a string

**Comment by sdanyliv** [comment]
What is the problem with strings? In my sample i have used expression, not a string. We changed order of parameters because how `params` works in C# and to do not create too many overloads.

**Comment by rserj** [comment]
@sdanyliv thanks for your reply, I do not have anything against strings, you are right we can always use nameof() for column names to make it more maintainable.
Just would like to make sure that we are on the same page.
Here is the Contains extension prototype I'm using

```
/// <summary>
    /// Applies full-text search condition using CONTAINS predicate against specified full-text columns.
    /// Example: "CONTAINS((col1, col2), N'search')".
    /// </summary>
    /// <typeparam name="TEntity">Queried table mapping class.</typeparam>
    /// <param name="ext">Extension point.</param>
    /// <param name="entity">Table to perform full-text search against.</param>
    /// <param name="search">Full-text search condition.</param>
    /// <param name="columns">Full-text columns that should be queried.</param>
    /// <returns>Returns <c>true</c> if full-text search found matching records.</returns>
    [LinqToDB.Sql.ExtensionAttribute("CONTAINS(({columns, \', \'}), {search})", IsPredicate = true, ServerSideOnly = true)]
    public static bool Contains<TEntity>(
      this ISqlServerExtensions ext,
      TEntity entity,
      [ExprParameter] string search,
      [ExprParameter] params object[] columns)
      where TEntity : class;
```

Usage itself:
```
db.UserEMail
        .Select(eml=>eml.EMail)
        .Where(email => Sql.Ext.SqlServer()
              .Contains(
                    email, // entity - Table to perform full-text search against
                    "admin@gmail.com", // search- Full-text search condition
                    nameof(UserEMail.EMail) // columns param - Full-text columns that should be queried
        ));
```

The result:
![image](https://user-images.githubusercontent.com/13991195/95801726-21749d00-0cb0-11eb-9b1e-426f31e48562.png)

**Comment by sdanyliv** [comment]
It’s because you have used string, which is wrong. I have already answered, but i can write correct query again. First parameter is search string, then column expression.
```cs
db.UserEMail
        .Where(email => Sql.Ext.SqlServer()
              .Contains(
                    "admin@gmail.com", // search- Full-text search condition
                    email.Email // not a string, but expression
               )
        ));

```

**Comment by rserj** [comment]
@sdanyliv thanks for your reply.
You must get me wrong, when I mean expression I mean 
`Expression<Func<TTable, bool>>`
Anyway, I tried your example from the beginning, it didn't work.
I think you just simply misplaced arguments, when you change the order it works!
```
var emails = db.UserEMail
                    .Where(email => Sql.Ext.SqlServer()
                        .Contains(
                            email.EMail,
                            "admin@gmail.com"
                        )
                    );
```
I think we should definitely document/improve this part by making it more explicitly.
I'll close this ticket for now, you can always reopen it for improvements.
Thank you all for your suggestions.

**Comment by sdanyliv** [comment]
Reopening to check.

**Comment by MaceWindu** [comment]
```cs
var emails = db.UserEMail
                    .Where(email => Sql.Ext.SqlServer()
                        .Contains(
                            email.EMail,
                            "admin@gmail.com"
                        )
                    );
```
this cannot work, as first parameter is search query, not column. Proper call should be
```cs
var emails = db.UserEMail
                    .Where(email => Sql.Ext.SqlServer()
                        .Contains(
                            "admin@gmail.com",
                            email.EMail
                        )
                    );
```

MEthod: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SqlServer/SqlServerExtensions.cs#L629
Test: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/FullTextTests.SqlServer.cs#L1856

**Comment by rserj** [comment]
It works, please see the image of how parameters get mapped
![image](https://user-images.githubusercontent.com/13991195/95894071-714d7580-0d3d-11eb-879f-b8d37fc8bfaa.png)
```
 email.EMail // - Mapped to Entity
 "admin@gmail.com" // Mapped to search
```
since there is no actual invocation and the first argument gets mapped to MemberExpression, linq2db could figure it out and extract the Email property as a column.
I remind you I'm on linq2db version: 2.98, it might be different in new versions

**Comment by MaceWindu** [comment]
> I remind you I'm on linq2db version: 2.98, it might be different in new versions
now it's clear. This was changed in 3.0 https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#full-text-api-changes
