### ISSUE TITLE
MS SQL Server Contains function doesn't seem to be working

### ISSUE THREAD

**Issue by rserj** [linq2db/linq2db#2538]
I'm trying to use CONTAINS (Transact-SQL) function like this

`db.UserEmail.Where(email => Sql.Ext.SqlServer().Contains(email, "admin@gmail.com", "Email")); `

It generates incorrect TSQL

```
--   SqlServer.2012
SELECT
	[email_1].[Id],
	[email_1].[UserId],
	[email_1].[Email]
         ....
FROM
	[dbo].[UserEmail] [email_1]
WHERE
	CONTAINS((N'Email'), N'admin@gmail.com')
```
CONTAINS function expects the Column itself as a first argument rather than string N'Email'

Am I missing something?
Thanks in advance

### Environment details
linq2db version: 2.98
Database Server: MS SQL Server 2019
.NET Framework: 4.8

**Comment by sdanyliv** [comment]
Duplicate #2537
