### ISSUE TITLE
Converters are not used (linq2db V 3.1.4)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2547]
We are using lots of custom converters.

They seem not to be used on inserts any more. following 2 fail:

            mappingSchema.SetConverter<StreamType, string>((obj) =>
            {
                return obj.ToString();
            });
            mappingSchema.SetConverter<StreamType, DataParameter>((obj) =>
            {
                return new DataParameter { Value = obj.ToString() };
            });
            mappingSchema.SetConverter<string, StreamType>((txt) =>
            {
                return (StreamType)Enum.Parse(typeof(StreamType), txt, true);
            });

            mappingSchema.SetConverter<TimeSpan, long>((obj) =>
            {
                return obj.Ticks;
            });
            mappingSchema.SetConverter<TimeSpan, DataParameter>((obj) =>
            {
                return new DataParameter { Value = obj.Ticks };
            });
            mappingSchema.SetConverter<long, TimeSpan>((val) =>
            {
                return TimeSpan.FromTicks(val);
            });

I look to create a test

**Comment by jogibear9988** [comment]
Maybe someone already has an idea?

**Comment by jogibear9988** [comment]
We tested now, it worked in Version 3.1.3

**Comment by sdanyliv** [comment]
@jogibear9988, please prepare small tests. Release tomorrow.

**Comment by jogibear9988** [comment]
Don't know atm why my test did not reproduce the error:

This is the error on our System with a postgres DB
System.InvalidCastException: 'Can't write CLR type System.Int64 with handler type IntervalHandler'

![image](https://user-images.githubusercontent.com/364896/96046678-25511c80-0e74-11eb-8c02-22e4b0c89f57.png)

The SQLServer error is on another Computer, I will post that later

**Comment by jogibear9988** [comment]
Okay, Postgres could be fixed by this:

 .Property(e => e.BufferTimeSpan).HasDataType(LinqToDB.DataType.Int64).IsNullable(false)
                .Property(e => e.PostEventTimeSpan).HasDataType(LinqToDB.DataType.Int64).IsNullable(false);

but it was not needed (i think befor version 3).

for the sqlserver error in need to look tomorrow

**Comment by sdanyliv** [comment]
> Don't know atm why my test did not reproduce the error:

Because test do nothing. And test created for SQLite

**Comment by sdanyliv** [comment]
I've checked this test.
1. Column defined as TimeSpan - which creates Timespan column in table
2. You have defined TimeSpan -> DataParameter conversion, which returns long
3. long != TimeSpan - you have error.

Will close the issue if you do not provide valuable test.

**Comment by jogibear9988** [comment]
will look for later

**Comment by jogibear9988** [comment]
@sdanyliv But I updated the test yesterday to use DataType.VarChar and DataType.Int64.
Does it still use Timespan to create the column?

I copied a test, so the sqlite was not intended

**Comment by jogibear9988** [comment]
@sdanyliv hopefully now the test fails.
problem is, we don't had "varchar" type for string enum in mapping. but it worked in linq2db v 3.1.3

**Comment by jogibear9988** [comment]
I could not create test wich reproduces the issue in a test.
Don't know why I need the type now, but I don't need it in linq2db unittests...

I'll close for now
