### ISSUE TITLE
Map custom attributes to linq2db attributes in another project

### ISSUE THREAD

**Issue by travbeamo** [linq2db/linq2db#2550]
We have a solution with projects:
* **ExampleData.Models.csproj** 
  * cannot have any 3rd party nuget references (not even linq2db). 
  * has database model classes 
  * can use the _Table_ and _Column_ attributes available in System.ComponentModel.DataAnnotations.Schema for mapping.
  * has custom a **StringValueAttribute** (similar to linq2db [MapValueAttriubte](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/MapValueAttribute.cs)) for enum string values

* **ExampleData.Services.csproj** 
  * references **ExampleData.Models.csproj** 
  * can have any 3rd party nuget references (includes linq2db). 
  * has linq2db [DataConnections](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs) 

How can custom attributes in defined **ExampleData.Models.csproj** be mapped to use specific linq2db attributes in **ExampleData.Services.csproj** ?

For example how can enums  that use **StringValueAttribute** in **ExampleData.Models** be converted to use the [MapValueAttriubte](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/MapValueAttribute.cs) in **ExampleData.Services.csproj** in our [DataConnections](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs)?

**Comment by MaceWindu** [comment]
You need to create and register custom metadata provider, which will convert your attributes to linq2db mapping attributes.
Check those links:
- https://github.com/linq2db/linq2db/issues/2501#issuecomment-696707189 - how to create and register custom metadata provider (including table, column and enum mappings)
-for `System.ComponentModel.DataAnnotations.Schema` attributes (`TableAttribute` and `ColumnAttribute`) we already provide [provider](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Metadata/SystemComponentModelDataAnnotationsSchemaAttributeReader.cs) and it is already registered by default

**Comment by sdanyliv** [comment]
You can supply your DataConnection with MappingSchema that contains metadata reader or specify it for whole application . 
```
 LinqToDB.Mapping.MappingSchema.Default.AddMetadataReader(new MyMetadataReader());
```
For example https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Metadata/SystemComponentModelDataAnnotationsSchemaAttributeReader.cs
Or what we did for EF Core https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs

**Comment by travbeamo** [comment]
Some example classes:

**ExampleData.Models.csproj**

```
[AttributeUsage(AttributeTargets.All, AllowMultiple = false)]
public class StringValueAttribute : Attribute {
    public StringValueAttribute(string value) {
      Value = value;
    }
    public string Value { get; set; }
}

public enum Status {
    [StringValue("T")] Terminated,
    [StringValue("A")] Active
}

[System.ComponentModel.DataAnnotations.Schema.Table("T_Employee")]
  public class Employee{
    [System.ComponentModel.DataAnnotations.Schema.Column] public int Id { get; set; }
    [System.ComponentModel.DataAnnotations.Schema.Column] public string FirstName{ get; set; }
    [System.ComponentModel.DataAnnotations.Schema.Column] public string LastName { get; set; }
    [System.ComponentModel.DataAnnotations.Schema.Column("StatusCode")] public Status Status { get; set; }
}
```
