### ISSUE TITLE
Linq Expressions : where statement is translated as subquery

### ISSUE THREAD

**Issue by arispar** [linq2db/linq2db#2554]
We have POCO classes like that 

```
class ClassA
{
        [Identity]
        [PrimaryKey]
        public int ID { get; set; }

        [NotNull]
        [Column(Name = "ClassBID")]
        public int ClassBID { get; set; }

        [Association(
            ThisKey = "ClassBID",
            OtherKey = "ID")]
        public ClassB ClassB { get; set; }
        
        [Association(
            ThisKey = "ID",
            OtherKey = "ClassAID"]
        public ICollection<ClassC> Collection { get; set; }
}

class ClassB
{
        [Identity]
        [PrimaryKey]
        public int ID { get; set; }

        [Nullable]
        public string description { get; set; }
}

class ClassC
{
       [NotNull]
       int ClassAID
       
       [NotNull]
       int TypeID
}

```
A **ClassA** instance can have only one **ClassB** instance and many **ClassC** instances as shown in POCOs above.

We have a very complex query that handles the most popular request in our system concerning our main entity (ClassA in our example) with many **JOINS** to other tables and _conditional_ statements at **WHERE** clause.

We successfully rewrote a query that returns the same data using Linq Expressions with ClassA as our starting point e.g  
`(classA => classA.SomeProperty == someValue);` or `(classA => classA.SomeEmbeddedObject.SomeProperty == someValue);`

Please note that without Linq Expressions it would be hard to make such conditional where statements work together.

Finally we noticed that the actual query that is executed in database has some subqueries when Expressions like this are in the where statement.

Linq Expression:
`(classA =>classA.Collection.Any(classC => classC.TypeID == someValue));`

QueryProduced:

```
SELECT
	[classA]
FROM
	[ClassA] [classA]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[ClassC] [classC]
		WHERE
			[classA].[ID] = [classC].[ClassAID] AND [classC].[TypeID] = @value
	);

```

Are we doing something wrong, or is this the expected behaviour?

We would expect something like this:

```
SELECT
	[classA]
FROM
	[ClassA] [classA]
JOIN
        [ClassC] [classC] on [classA].[ID] = [classC].[ClassAID]
WHERE
	[classC].[TypeID] = @value
```

If this is the expected behaviour is there a way to turn the subquery into a join using Linq Expressions as this is not the optimal approach?

**Comment by viceroypenguin** [comment]
Try this query instead:
```csharp
(classA => classA.SelectMany(a => a.Collection.Where(c => c.TypeID ==someValue), (a, c) => a))
```

The `.Any()` will always turn into a boolean expression in SQL because it is a boolean result. Hence the `WHERE EXISTS`. You have to specify that you want to select data from C in a join manner in order to get a JOIN, even if you don't want the actual data from C.

**Comment by arispar** [comment]
Thank you for your fast response.

This works as expected.

**Comment by sdanyliv** [comment]
I would just only suggest to use LINQ Query syntax, which I prefer, and which is closer to the SQL and, I hope, this question would never appear.
```cs
var query = 
    from classA in db.GetTable<ClassA>()
    from classC in classA.Collection       // this is JOIN based on association
    where classC.TypeID == someValue
    select classA
```
