### ISSUE TITLE
Java equivalent

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#2555]
Hi,

I have to develop some java apllication in future for new projects. Since linqtodb is my new idol in orm frameworks I would like to go a similar way in java ( I know you would say there is no similar framework 😂) but anyone who has best practice in java, what would you recommend to use to go to have nearly the same way of doing?

**Comment by sdanyliv** [comment]
IMHO, JOOQ is closer than any other. But without LINQ it looks like a cripple.
