### ISSUE TITLE
Cached queries memory leak in expressions

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#256]
This is very similar to #119 I've reported some time ago.
Query.Expression catches parameters through ConstantExpression._value.
Is it possible to clear them too? E.g. replacing with ConstantExpression with default value for parameter type?

Currently I'm "fixing" it using memory profiler to find such queries and rewrite them, but its not very productive and in some cases leads to less-performant code :(

**Comment by MaceWindu** [comment]
Example:
```csharp
var data = db.Table1
    .Where(_ => db.Table2.Select(_ => _.Id).Contains(_.Id))
    .Select(_ => new SomeObject(bigObject, _.Field1, _.Field2))
    .ToList();
```
here expression will prevent from GC at least db and bigObject parameters with all their references.

To avoid it I could write something like that:
```csharp
var data = db.Table2
    .SelectMany(_ => _.Table1s)
    .ToList() // ugh..
    .Select(_ => new SomeObject(bigObject, _.Field1, _.Field2))
    .ToList();
```
but two ToList operations means unwanted performance degradation for me.

**Comment by igor-tkachev** [comment]
You should use AsEnumerable instead of the first ToList.

**Comment by MaceWindu** [comment]
Yep, you are right. Completely forgot about AsEnumerable.

I hope this issue could be fixed, because without knowning how it works, you don't expect such behavior. Also to fix it on application side you need to use memory profiler, because leaks could be tricky. E.g. it could be a reference to closure object with a lot of fields, not related to query directly.

BTW, is it possible to extend fix for #119 with cleanup of SqlParameter.Value and apply it also to ObjectOperation<T>.Insert queries (and maybe some other queries, not covered by #119)?
I'm asking for it because string/binary parameters could be huge.

**Comment by ili** [comment]
@MaceWindu getting back to this issue, in your sample expression would be root for `db` and `bigObject`, or i do have some misunderstood?

**Comment by MaceWindu** [comment]
If it could wait I would like to postpone it for a couple of months (if nowbody has plans to take this issue now).

This is a more generic issue - right now query expressions cache contains not only query expression itself but also through ConstantExpression or SqlParameter (if I remember correctly) could store references to local objects. Right now we have a big issue with queries catching references to closure objects that include not only fields used in query but sometimes very big objects that are not directly used by query.
I solved it for now using hacks to linq2db code, but it is not ready for PR. Unfortunatelly right now I'm busy with finishing implementation of our company's next major release but I expect to have more time starting from May and I've already planned to work on this issue and on better Merge API as I don't wan't to support my hacks forever :)

For this issue I have following plan:
1. create tests with different types of queries that use reference-typed parameter, e.g. byte[].
test should save reference to this object as a Week Reference, trigger GC and see if it survived GC or not
2. try to fix it

**Comment by ili** [comment]
That's great! ))

**Comment by MaceWindu** [comment]
Looks like removing values from expressions is not an option. I will add setting to disable query caching but for this I will need to test how cache behave in multithreaded environment. At least I know that in single-threaded mode it is effective.

**Comment by jhudler** [comment]
+1 here. If the query cache could be easily cleaned, it would be already very helpful. The issue now is that every anonymous typed query descending from `Linq.Query<T>` should have its own static cache, which makes cleaning it a bit awkward thing to do (iterate over all concrete descendant types and cleaning it dynamically thru reflection).

**Comment by jogibear9988** [comment]
> Looks like removing values from expressions is not an option. 
Why ?

**Comment by jogibear9988** [comment]
Is this cache often used? Can I adjust the cache size from user Code?

**Comment by MaceWindu** [comment]
> Why ?
Because values are used for query text generation and removal leads to invalid queries. Also expression comparison takes into account values and removal of them will result in false cache miss. Maybe we will find a way to fix it, but it will take some time.

> Is this cache often used? Can I adjust the cache size from user Code?
Cache used almost for all linq queries and size is hardcoded as 100 last unique queries per result type.

I need this issue addressed before september for my project, so it will be definitely resolved soon in some way

**Comment by giuliohome** [comment]
I'm still having a cache issue, the result of a query (more or less what you can see [here](https://github.com/linq2db/linq2db/issues/1455)...) is wrongly affected if another one is executed before .
Is there a way to force a cleanse of the cache at each new connection?
Please this is urgent, can you advice? Thank you!

**Comment by sdanyliv** [comment]
Query.ClearCaches?

**Comment by giuliohome** [comment]
I'm not able to compile it...

**Comment by giuliohome** [comment]
Sorry, yes compiled, let me try if it does the trick...

**Comment by giuliohome** [comment]
YES! THANK YOU!!!

**Comment by sdanyliv** [comment]
@giuliohome, we have ported MemoryCache from Microsoft’s implementation and need for statistic some information. It is ok when cached items are removed automatically when they are not used for a hour? Or you get memory problems earlier?

**Comment by giuliohome** [comment]
The problem I described above was much earlier. I was running a query1 with some parameters and immediately after a different query2 with diverse parameters2 but the results of the second query were wrong like still affected by the parameters1. The solution was issuing `Query.ClearCaches` . Thanks again for your prompt answer.

**Comment by sdanyliv** [comment]
@giuliohome, it sounds like a bug. Can you provide us with reproducing sample?

**Comment by giuliohome** [comment]
Unfortunately at the moment I'm recovered in the hospital. Hopefully nothing too serious but I won't be able to access my laptop till January, I don't know when but I will do.. Thanks anyway for the workaround which did the trick. in the meantime.
