### ISSUE TITLE
Question: Convert custom DateTime object to DateTime on insert

### ISSUE THREAD

**Issue by thedoomx** [linq2db/linq2db#2560]
Hello,

I am using t4 model generation and all of the DateTime properties have been converted to NodaTime.LocalDateTime.

When I am getting the data from the DB I am using this convertor **successfully**:
```
LinqToDB.Mapping.MappingSchema.Default.SetConverter<DateTime, NodaTime.LocalDateTime>(timeStamp =>
			new NodaTime.LocalDateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
			timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond));
```

The issue is when I try to **submit** data:

 ```
UserSession session = new UserSession
            {
                CreatedOn = NodaTime.LocalDateTime.FromDateTime(DateTime.Now),
            };

 using (var db = new DBContext())
            {
                    await db.InsertAsync(session);
            }
```

The error is:
```
ArgumentException: No mapping exists from object type NodaTime.LocalDateTime to a known managed provider native type.
System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, object value, bool inferLen, bool streamAllowed)
System.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
System.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
lambda_method(Closure , IDbDataParameter )
LinqToDB.DataProvider.SqlServer.SqlServerDataProvider.SetParameter(DataConnection dataConnection, IDbDataParameter parameter, string name, DbDataType dataType, object value)
LinqToDB.Data.DataConnection+QueryRunner.AddParameter(DataConnection dataConnection, ICollection<IDbDataParameter> parms, string name, SqlParameter parm)
LinqToDB.Data.DataConnection+QueryRunner.GetParameters(DataConnection dataConnection, PreparedQuery pq)
LinqToDB.Data.DataConnection+QueryRunner.SetQuery(DataConnection dataConnection, IQueryContext queryContext, int startIndent)
LinqToDB.Data.DataConnection+QueryRunner.SetQuery()
LinqToDB.Linq.QueryRunnerBase.SetCommand(bool clearQueryHints)
LinqToDB.Data.DataConnection+QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, object[] ps, object[] preambles, CancellationToken cancellationToken)
LinqToDB.Linq.QueryRunner+Insert<T>.QueryAsync(IDataContext dataContext, T obj, InsertColumnFilter<T> columnFilter, string tableName, string serverName, string databaseName, string schemaName, CancellationToken token)
```

And the convertors that I have tried are:
```
LinqToDB.Mapping.MappingSchema.Default.SetDataType(typeof(LocalDateTime), LinqToDB.DataType.DateTime);
LinqToDB.Mapping.MappingSchema.Default.SetDataType(typeof(LocalDateTime), LinqToDB.SqlQuery.SqlDataType.DateTime);

LinqToDB.Mapping.MappingSchema.Default.SetConverter<NodaTime.LocalDateTime, DataParameter>(timeStamp =>
new DataParameter
{
	Value = new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond),
        //Value = DateTime.Now,
	DataType = LinqToDB.DataType.DateTime
});

LinqToDB.Mapping.MappingSchema.Default.SetConverter<NodaTime.LocalDateTime, DateTime>(timeStamp =>
new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond));

LinqToDB.Mapping.MappingSchema.Default.SetValueToSqlConverter
	(typeof(NodaTime.LocalDateTime), (sb, dt, v) =>
	{
		var d = (NodaTime.LocalDateTime)v;
		var d1 = new DateTime(d.Year, d.Month, d.Day, d.Hour,
		d.Minute, d.Second, d.Millisecond);

		sb.Append("'").Append(d1.ToString()).Append("'");
		//sb.Append("'").Append(d1).Append("'");
	}
	);

LinqToDB.Mapping.MappingSchema.Default.SetConverter<NodaTime.LocalDateTime, DataParameter>(timeStamp =>
new DataParameter
{
	Value = new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond).ToString(),
	DataType = LinqToDB.DataType.NVarChar
});

```

Could you please give some directions of what am I missing here?

I have tried on Linq2DB.SqlServer versions 3.1.2 and 3.1.5

Thank you.

**Comment by sdanyliv** [comment]
@thedoomx, please check this PR https://github.com/linq2db/linq2db/pull/2570
Insert works.

**Comment by thedoomx** [comment]
@sdanyliv Thanks for the sample, but unfortunately i am still getting the same error.
I have tried setting up the mapping schema convertors in both startup and within the using of the DB context - same result.

Maybe I will regress from generating the models with the custom datetime object.

**Comment by sdanyliv** [comment]
I have changed little bit your mapping in PR. So carefully copy.

**Comment by thedoomx** [comment]
@sdanyliv I saw the changes, it is exactly what I have copied.
```
LinqToDB.Mapping.MappingSchema.Default.SetDataType(typeof(LocalDateTime), new SqlDataType(new DbDataType(typeof(DateTime), DataType.DateTime)));

LinqToDB.Mapping.MappingSchema.Default.SetConverter<LocalDateTime, DataParameter>(timeStamp =>
new DataParameter
	{
		Value = new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
			timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond),
		DataType = DataType.DateTime
	});

LinqToDB.Mapping.MappingSchema.Default.SetConverter<LocalDateTime, DateTime>(timeStamp =>
	new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
		timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond));

LinqToDB.Mapping.MappingSchema.Default.SetValueToSqlConverter(typeof(LocalDateTime), (sb, dt, v) =>
       {
        var d = (LocalDateTime)v;
	var d1 = new DateTime(d.Year, d.Month, d.Day, d.Hour,
	d.Minute, d.Second, d.Millisecond);

	sb.Append("'").Append(d1.ToString()).Append("'");
	});


LinqToDB.Mapping.MappingSchema.Default.SetConverter<DateTime, NodaTime.LocalDateTime>(timeStamp =>
new NodaTime.LocalDateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond)); //needed for get
```

It is very weird because the last converter works when I try to get data from the DB.

I am running the app on .net core 3.1, 
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
My versions of NodaTime 3.0.2 and Linq2Db.SqlServer 3.1.5

**Comment by sdanyliv** [comment]
Could you please try do not change default mapping schema and pass new MappingSchema into DataConnection constructor?

**Comment by thedoomx** [comment]
@sdanyliv I have tried the following:

```
using (var db = new DataConnection(ms))
	{
		var query = db.GetTable<UserSession>();
		var dummy = query.FirstOrDefault();
		db.Insert<UserSession>(session);
	}
```

Same result - the Get operation does not throw an error, the Insert does. 
For the sake of testing I tried commenting out the DateTime to NodaTime convertor and the Get operation fails as expected.

**Comment by MaceWindu** [comment]
Could you post your `UserSession` mapping (only class and CreatedOn  property should be enough)

**Comment by thedoomx** [comment]
Hi, @MaceWindu 

This is the way that I am generating the models:
```
foreach (var t in Tables.Values)
{
		foreach(var column in t.Columns.Values) 
                {
				if(column.Type == "DateTime?")
				{
					column.Type = "NodaTime.LocalDateTime?";
				}
				else if(column.Type == "DateTime") {
					column.Type = "NodaTime.LocalDateTime";
				}
		}
}
```

And this is the generated class:
```
[Table(Schema="dbo", Name="tblUserSession")]
	public partial class UserSession
	{
		[PrimaryKey, Identity   ] public int                     UserSessionId    { get; set; } // int
		[Column,     NotNull    ] public int                     UserId           { get; set; } // int
		[Column,        Nullable] public string                  ClientSessionId  { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string                  ClientDeviceName { get; set; } // nvarchar(100)
		[Column,        Nullable] public string                  ClientIpAddress  { get; set; } // nvarchar(100)
		[Column,     NotNull    ] public NodaTime.LocalDateTime  SignedInOn       { get; set; } // datetime
		[Column,        Nullable] public NodaTime.LocalDateTime? SignedOutOn      { get; set; } // datetime
		[Column,        Nullable] public NodaTime.LocalDateTime? HeartbeatOn      { get; set; } // datetime
		[Column,        Nullable] public bool?                   ForceSignOut     { get; set; } // bit
		[Column,        Nullable] public bool?                   ForceExit        { get; set; } // bit
		[Column,     NotNull    ] public bool                    Expired          { get; set; } // bit
		[Column,        Nullable] public string                  Message          { get; set; } // nvarchar(max)
		[Column,        Nullable] public int?                    MessageSentBy    { get; set; } // int
		[Column,     NotNull    ] public int                     CreatedBy        { get; set; } // int
		[Column,     NotNull    ] public NodaTime.LocalDateTime  CreatedOn        { get; set; } // datetime
		[Column,     NotNull    ] public int                     UpdatedBy        { get; set; } // int
		[Column,     NotNull    ] public NodaTime.LocalDateTime  UpdatedOn        { get; set; } // datetime
		[Column,        Nullable] public NodaTime.LocalDateTime? ExpiresOn        { get; set; } // datetime
	}
```

I have not changed the generated stored procedures signature to expect NodaTime, so it expects DateTime parameter.
When I use a stored procedure the functionality works as expected. Similar to the below example:

```
public static int UserSave(this DBContext dataConnection, DateTime? @DriversLicenseExpiresOn)
{
   var ret = dataConnection.ExecuteProc("[dbo].[procUserSave]",
   new DataParameter("@DriversLicenseExpiresOn", @DriversLicenseExpiresOn, DataType.DateTime));
}
```

Is there I chance that I have messed up in the generation code, perhaps something else should be added?

**Comment by carloscs** [comment]
I've been testing Linq2db [mappings, optimistic locking,...] and this is working for me. 

Hmm, just noticed that haven't maps for nullable Datetime columns as my db hasn't any of those. Another todo :)

Setup:

    LocalDateTimeToDatetimeConverter.RegisterConverters(schema);


Code:

    public static class LocalDateTimeToDatetimeConverter {

        public static void RegisterConverters(MappingSchema schema) {
            schema.SetConverter<LocalDateTime?, DataParameter>(ldt => new DataParameter { Value = ldt?.ToDateTimeUnspecified() });
            schema.SetConverter<LocalDateTime, DataParameter>(ldt => new DataParameter { Value = ldt.ToDateTimeUnspecified() });

            schema.SetConverter<LocalDateTime?, DateTime?>(ldt => ldt?.ToDateTimeUnspecified());
            schema.SetConverter<LocalDateTime?, DateTime>(ldt => ldt.LocalDateTimeToDateTime());
            schema.SetConverter<LocalDateTime, DateTime?>(ldt => ldt.ToDateTimeUnspecified());
            schema.SetConverter<LocalDateTime, DateTime>(ldt => ldt.ToDateTimeUnspecified());

            schema.SetConverter<DateTime?, LocalDateTime?>(dt => dt == null ? (LocalDateTime?) null : LocalDateTime.FromDateTime(dt.Value));
            schema.SetConverter<DateTime?, LocalDateTime>(dt => dt.DateTimeToLocalDateTime());
            schema.SetConverter<DateTime, LocalDateTime?>(dt => LocalDateTime.FromDateTime(dt));
            schema.SetConverter<DateTime, LocalDateTime>(LocalDateTime.FromDateTime);

            schema.SetValueToSqlConverter(typeof(LocalDateTime?), ConverterToSql);
        }


        static DateTime LocalDateTimeToDateTime(this LocalDateTime? dateTime) {
            if (dateTime == null) {
                throw new InvalidOperationException("Can't convert null to LocalDateTime.");
            }
            return dateTime.Value.ToDateTimeUnspecified();
        }


        static LocalDateTime DateTimeToLocalDateTime(this DateTime? dateTime) {
            if (dateTime == null) {
                throw new InvalidOperationException("Can't convert null to LocalDateTime.");
            }
            return LocalDateTime.FromDateTime(dateTime.Value);
        }


        static void ConverterToSql(StringBuilder sb, SqlDataType tp, object v) {
            if (v == null) {
                sb.Append("NULL");
            }
            else {
                // todo: format date
                sb.Append($"TO_DATE('{v}', '%Y-%m-%d %H:%M:%S.%F5')");
            }
        }
}

**Comment by thedoomx** [comment]
Hi @carloscs 

The provided solution worked perfectly for me.

Thank you!
