### ISSUE TITLE
Problem with Oracle and Strings in CLOB

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2561]
I've a Orcale String stored in a CLOB Field, cause it could bigger then 2000 characters.

When I tried to run a query like this:

                var a = "a";
                var b = "b";
                var c = "aaa";
                var q = s.Query<ScriptDTO>().Where(x => x.Archive == 0 && x.ScriptType == VISU.Services.VisuServiceInterfaces.Enum.ScriptType.CSharpScript && x.SubType == a && x.ServiceName == b && x.Script == c).FirstOrDefault();

where the "Script" Field in ScriptDTO is CLOB in Database, I got this error:

```
Exception message:

	Message: 
		Oracle.ManagedDataAccess.Client.OracleException : ORA-00932: Inkonsistente Datentypen: - erwartet, NCLOB erhalten
	  Stack Trace: 
		OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
		OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
		OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
		OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
		OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
		DbCommand.ExecuteReader(CommandBehavior behavior)
		DbCommandProcessorExtensions.ExecuteReaderExt(IDbCommand cmd, CommandBehavior commandBehavior)
		<>c__DisplayClass29_0.<ExecuteDbDataReader>b__0()
		RetryPolicyBase.ExecuteImplementation[TResult](Func`1 operation)
		RetryPolicyBase.Execute[TResult](Func`1 operation)
		RetryingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
		DbCommand.ExecuteReader(CommandBehavior behavior)
		DbCommandProcessorExtensions.ExecuteReaderExt(IDbCommand cmd, CommandBehavior commandBehavior)
		DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
		DataConnection.ExecuteReader(CommandBehavior commandBehavior)
		DataConnection.ExecuteReader()
		QueryRunner.ExecuteReader()
		<ExecuteQuery>d__12`1.MoveNext()
		Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
		<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
		IQueryProvider.Execute[TResult](Expression expression)
		Queryable.FirstOrDefault[TSource](IQueryable`1 source)
		DatabaseReadTests.ReadWriteOracleTest() line 110
	```

**Comment by jogibear9988** [comment]
I tried setting DataType in Mapping but it does not help.
I tried NVarChar and Blob

But if that DataType would be needed, I would need different Types cause it is only "CLOB"when I use Oracle

**Comment by jogibear9988** [comment]
This queries works:

                var l = s.Query<ScriptDTO>().ToList();

and also a insert works.

**Comment by sdanyliv** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs#L242

**Comment by jogibear9988** [comment]
@sdanyliv 
I tried NText in our Code, I still got the same error. Also changed Mapping in the Test

**Comment by jogibear9988** [comment]
@sdanyliv 
and also if use

      .HasDataType(LinqToDB.DataType.NText)

the insert in postgres does not work any more (cause there the field is a string)

**Comment by sdanyliv** [comment]
You have to do different mapping schema configuration in that case. Each database has its now mapping.
```cs
builder.Entity<Some>(ProviderName.PostgreSql)
   .Property(e => e.Prop)
   .HasDataType(...)
```

**Comment by jogibear9988** [comment]
Okay, but oracle does not work with  .HasDataType(LinqToDB.DataType.NText)

**Comment by jogibear9988** [comment]
And also, why does <NText> not work on postgres when dbtype is <Text>

**Comment by sdanyliv** [comment]
I really don't know. You have debugger, enable SourceLink support and debug PostgreSqlDataProvider.

**Comment by jogibear9988** [comment]
@sdanyliv @MaceWindu 
maybe the real problem is, fields of type CLOB (in oracle) or TEXT (in postgres) could not be used in a where condition?

is this possible?

if I look here this seems to be the problem (in oracle):
https://stackoverflow.com/a/18251677 

is there something we should do? throw an error?

**Comment by jogibear9988** [comment]
CLOB could not be used i a where -- close
