### ISSUE TITLE
Oracle - Exception running Query:    ORA-00904: "DATEDIFF": ungültiger Bezeichner

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2564]
I've the following query:

                var from = DateTime.UtcNow.AddDays(-1);
                var to = DateTime.UtcNow;
                var qry = (from m in s.GetTable<MessageEventDTO>()
                            where m.TimestampGone.HasValue &&
                             m.TimestampGenerated >= @from &&
                             m.TimestampGenerated <= to &&
                             m.MessageClassName == "Error"
                            group m by new { m.ExternID1, m.TranslatedMessageGroup, m.TimestampGenerated.Hour } into tgGroup
                            select new 
                            {
                                MessageText = tgGroup.Min(x => x.TranslatedMessage1).Trim(),
                                GroupName = tgGroup.Key.TranslatedMessageGroup,
                                Hour = tgGroup.Key.Hour,
                                Count = tgGroup.Count(),
                                DurationInSeconds = (long)tgGroup.Sum(x => (x.TimestampGone.Value - x.TimestampGenerated).TotalMilliseconds),
                            });
                var data = qry.ToList();

I get the following Exception:

	Message: 
		Oracle.ManagedDataAccess.Client.OracleException : ORA-00904: "DATEDIFF": ungültiger Bezeichner
	  Stack Trace: 
		OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
		OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
		OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
		OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
		OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
		DbCommand.ExecuteReader(CommandBehavior behavior)
		DbCommandProcessorExtensions.ExecuteReaderExt(IDbCommand cmd, CommandBehavior commandBehavior)
		<>c__DisplayClass29_0.<ExecuteDbDataReader>b__0()
		RetryPolicyBase.ExecuteImplementation[TResult](Func`1 operation)
		RetryPolicyBase.Execute[TResult](Func`1 operation)
		RetryingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
		DbCommand.ExecuteReader(CommandBehavior behavior)
		DbCommandProcessorExtensions.ExecuteReaderExt(IDbCommand cmd, CommandBehavior commandBehavior)
		DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
		DataConnection.ExecuteReader(CommandBehavior commandBehavior)
		DataConnection.ExecuteReader()
		QueryRunner.ExecuteReader()
		<ExecuteQuery>d__12`1.MoveNext()
		List`1.ctor(IEnumerable`1 collection)
		Enumerable.ToList[TSource](IEnumerable`1 source)
		DatabaseReadTests.ReadComplexOracleTest() line 151

**Comment by sdanyliv** [comment]
`DateDiff` for oracle is not implemented. That's why you have this error.

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.DateTime.cs#L896-L902

**Comment by sdanyliv** [comment]
This link can be used as a reference how to implement that
https://livesql.oracle.com/apex/livesql/file/content_GNGZD9A6PW1N39K62Q34TCIBY.html

**Comment by sdanyliv** [comment]
After implementation just enable these tests for Oracle
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/DateTimeFunctionsTests.cs

**Comment by jogibear9988** [comment]
@sdanyliv 
don't know what to activate, they already contain oracle

				https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/DateTimeFunctionsTests.cs#L1283

**Comment by viceroypenguin** [comment]
`[DataSources]` is the Exclusive version, `[IncludeDataSources]` is the Inclusive version.

To activate these tests for Oracle, simply remove the Oracle line from the attribute for all of these tests.
