### ISSUE TITLE
[PGSQL] Linq2db inserts incorrect value into postgre date column

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#2571]
linq2db 3.1.5, PG SQL 12.2.

Linq2db inserts incorrect value into postgre date column. As example, value 2020-10-21 inserted as 2020-10-20.

### Steps to reproduce
create script:
```sql
CREATE TABLE test."Samples"
(
    "Id" uuid NOT NULL,
    "Day" date NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Samples" PRIMARY KEY ("Id")
)
```
table definition:
```cs
	[Table(Schema="test", Name="Samples")]
	public partial class Sample
	{
		[PrimaryKey, NotNull] public Guid           Id              { get; set; } // uuid

		[Column,     NotNull] public DateTimeOffset Day             { get; set; } // date

		[Column,     NotNull] public DateTimeOffset UpdatedOn       { get; set; } // timestamp (6) with time zone
	}
```

test code:
```cs
		[Test]
		public async Task DateTimeOffsetTests_Ok()
		{
			await using var db = _dbFactory();

			var now = DateTimeOffset.Now;
			var today = now.TruncateTime();
			var sample = new Sample
			{
				Id = Guid.NewGuid(),
				Day = today,
				UpdatedOn = now
			};

			await db.InsertAsync(sample);

			var sample2 = await db.Samples.FirstAsync(x => x.Id == sample.Id);

			sample2.Day.Should().Be(today);
			sample2.UpdatedOn.Should().BeCloseTo(now, TimeSpan.FromMilliseconds(1));
		}
```

test output:
```
Expected sample2.Day to be <2020-10-21 +3h>, but it was <2020-10-20 +3h>.
```

**expected behavior:**
the test should pass:)

### Environment details
linq2db version: 3.1.5
Database Server: PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1)
Database Provider: PostgreSQLVersion.v95
Operating system: Debian 12.2-2
.NET Framework: 3.1.402

**Comment by sdanyliv** [comment]
Have you tried to enable option `GenerateDataTypes = true` in T4 template?

**Comment by ig-sinicyn** [comment]
Yeah. It emits NpgsqlDate which is not an option for us as we do support multiple db providers (ms sql, pg, oracle).

**Comment by sdanyliv** [comment]
Let's wait for @MaceWindu, he should give you and solution.

**Comment by ig-sinicyn** [comment]
A-ha! It looks like my fault. I've used DateTimeOffset.Now instead of DateTimeOffset.UtcNow (silly mistake).
The only issue now is, the value in PG SQL db is treated as a local time, 2020-10-21 +0h is selected as 2020-10-21 +3h (kind=local).

**Comment by ig-sinicyn** [comment]
Ok, fixed with
```cs
		public static void AddDateTimeConverters(DataConnection db)
		{
			db.MappingSchema.SetConverter<DateTime, DateTime>(obj => obj.FixDateTime());
			db.MappingSchema.SetConverter<DateTime, DateTimeOffset>(obj => obj.FixDateTimeOffset());
			db.MappingSchema.SetConverter<DateTime, DataParameter>(obj => obj.FixDateTimeParameter());

			db.MappingSchema.SetConverter<NpgsqlDate, DateTime>(obj => obj.FixDateTime());
			db.MappingSchema.SetConverter<NpgsqlDate, DateTimeOffset>(obj => obj.FixDateTimeOffset());
		}

		private static DateTime FixDateTime(this DateTime obj)
		{
			if (obj.Kind == DateTimeKind.Local)
				throw new InvalidOperationException($"[BUG] You should not use local time. Observed value: {obj}");

			return obj.UnspecifiedAsUtc();
		}

		private static DateTimeOffset FixDateTimeOffset(this DateTime obj) => obj.UnspecifiedAsUtc().ToOffset();

		private static DataParameter FixDateTimeParameter(this DateTime obj) => DataParameter.Create("", obj.FixDateTime());

		private static DateTime FixDateTime(this NpgsqlDate obj) => ((DateTime)obj).FixDateTime();

		private static DateTimeOffset FixDateTimeOffset(this NpgsqlDate obj) => ((DateTime)obj).FixDateTimeOffset();

		public static DateTime UnspecifiedAsUtc(this DateTime dateTime) =>
			dateTime.Kind == DateTimeKind.Unspecified
				? DateTime.SpecifyKind(dateTime, DateTimeKind.Utc)
				: dateTime;
```
Workaround is ok for me so feel free to close the issue

**Comment by sdanyliv** [comment]
Don’t change MappingSchema of DataConnection, this schema is cached, so you will have mapping collisions.

**Comment by ig-sinicyn** [comment]
Nice catch, didn't know about that 👍 

Would you suggest the proper way to configure mappings for specific DataConnection-derived class?
(we use l2db.T4Templates to generate the code)

**Comment by sdanyliv** [comment]
Prepare MappingSchema and pass it to DataConnection constructor or call AddMappingSchema

**Comment by ig-sinicyn** [comment]
Will try. As far as I can see, each DB provider has its own default mapping schema.
I want to keep cache of  { (providerName, dbConnection.GetType()) => mapping schema }.

Is there a way to get a copy of default schema for specific provider?

**Comment by ig-sinicyn** [comment]
Oh, I've missed the AddMappingSchema() trick. With it, there's no need to cache per-provider schema so the previous question is irrelevant.

**Comment by sdanyliv** [comment]
Actually it is better to cache, for memory and performance reasons.

Can we close an issue?

**Comment by ig-sinicyn** [comment]
Yes, feel free to close)
