### ISSUE TITLE
How can an existing System.Data.IDbConnection instance be used?

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2578]
For unit testing I'd like to use an IDbConnection created by EF (Sqlite in memory). The tables etc. are set up with migrations by Entity Framework.

I want to use the created System.Data.IDbConnection of Entity Framework in Linq2Db's DataConnection. One of the overloaded DataConnection constructors is 
```C# 
public DataConnection(IDataProvider dataProvider, IDbConnection connection); 
```

IDataProvider contains 
```C# 
IDbConnection CreateConnection(string connectionString)
```
which is confusing

same applies to 
```C#
public LinqToDbConnectionOptionsBuilder UseConnection(IDataProvider dataProvider, IDbConnection connection, bool disposeConnection = false);
```

What is the preferred/recommended way to use an existing IDbConnection?

**Comment by sdanyliv** [comment]
Do you want to reinvent wheel? https://github.com/linq2db/linq2db.EntityFrameworkCore

**Comment by HypeillingerChillinger** [comment]
Yes, that looks good.

On that page it says

```C# 
// using DbContext
using (var dc = ctx.CreateLinqToDbConnection())
{
   // linq queries using linq2db extensions
}
```

Which returns an IDbContext (implemented by DataConnection) but how can I convert it into "MyContext" with my MappingSchema?

I need to use it in a context factory that creates a MyLinq2DbContext instance. The factory is injected into some services.

**Comment by HypeillingerChillinger** [comment]
I do not want to use the workaround of using EF with an on-top Linq2Db but a real Linq2Db with full support because there are known limitations (see https://github.com/linq2db/linq2db.EntityFrameworkCore).
I don't care about configure EF AND Linq2Db that is ok for me.

So I'd like to reopen this issue (question) and ask how to initialize a Linq2Db Context with an open System.Data.IDbConnection, an existing MappingSchema and a ProviderName?

**Comment by sdanyliv** [comment]
```cs
var builder = new LinqToDbConnectionOptionsBuilder();
builder
  .UseMappingSchema(ms)
  .UseConnection(con)
  .UseProviderName(provName);

var options = builder.Build();
using var db = new DataConnection(options);
```

**Comment by HypeillingerChillinger** [comment]
That is exactly what I need. Thanks.
