### ISSUE TITLE
Question: Reusable queries as extension methods?

### ISSUE THREAD

**Issue by 4amy** [linq2db/linq2db#2579]
I am looking for an example of how I can write extension methods with parameters that have access to the full db context similar to what's shown on the CTE page. Does anyone have examples of how to do that so I can make calls such as
`db.MyExtensionQuery(1) `
or 
`from m in db.MyExtensionQuery` 
or 
```
from sometable in db.sometables
join myQuery in db.MyExtensionQuery on sometable.id equals myQuery.sometableId
```

I tried writing it like: 
`public static IQueryable<pocoName> MyExtensionQuery(this myDb db, int id)`

**Comment by sdanyliv** [comment]
Something like that?
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLExtensions.cs#L317-L328

**Comment by sdanyliv** [comment]
@4amy, you can create any extension methods over DataConnection or IDataContext or IQueryable, with limitation that parameters that are passed to these extensions will be not fields of other tables.

```cs
public static IQueryable<pocoName> MyExtensionQuery(this myDb db, int id)
{
     return db.Table.Where(e => e.id == id);
}

var query = 
      from t in db.MyExtensionQuery(1)
      select t;
```

But there are cases when you need to reuse extension for more complex usage
```cs
var query = 
      from t1 in mydb.SomeTable
      from t2 in mydb.MyExtensionQuery(t1.Id)
      select t;

var query = 
      from t1 in mydb.SomeTable
      where mydb.MyExtensionQuery(t1.Id),Any()
      select t;
```
This case will be not convertible to the SQL. Here we have to instruct linq2db to correct Expression Tree by `ExpressionMethodAttribute`
```cs
[ExpressionMethod(nameof(MyExtensionQueryImpl))]
public static IQueryable<pocoName> MyExtensionQuery(this myDb db, int id)
{
     return db.Table.Where(e => e.id == id);
}

// Func types should be in the same order as in MyExtensionQuery and last type is result.
private static Expression<Func<myDb, int, IQueryable<pocoName>>> MyExtensionQueryImpl()
{
     return (db, id) => db.Table.Where(e => e.id == id);
}
```

After these manipulations all queries described above become valid.

Also check my answer https://stackoverflow.com/questions/63727166/linq2db-filter-by-nested-property-field for another scenario and this blog post http://blog.linq2db.com/2016/06/how-to-teach-linq-to-db-convert-custom.html.

**Comment by 4amy** [comment]
> with limitation that parameters that are passed to these extensions will be not fields of other tables.

Ah, I think this may have a lot to do with the issues I am running into as the SQL from the extension method was not being included or I would get a 'There is already an open DataReader associated with this Command which must be closed first' exception.

Thanks for the clarification, will give it a shot.

**Comment by sdanyliv** [comment]
If you have problems with `ExpressionMethodAttribute` - let me know. But I think you can handle that, nothing special.

**Comment by 4amy** [comment]
Yes, got it working! Thank you.
