### ISSUE TITLE
GetTable<NotConfiguredClass>() with not configured class should throw an exception

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2584]
A GetTable() with a not configured entity should throw an exception or is that intended?

```C#
            var context = new MyEntityFrameworkContext(options);
            context.Database.EnsureCreated();

            var linq2DbContext = context.CreateLinqToDbContext();


            linq2DbContext.GetTable<Bla>(); // Bla is not configured in EF. GetTable should throw
```

**Comment by sdanyliv** [comment]
`GetTable` is a `linq2db` function. If it do not throw in pure `linq2db`, i do not see reason to do that in EF integration.

**Comment by HypeillingerChillinger** [comment]
Mmmh, ok. I thought it would be handy to not rely on database exceptions but to get the exception directly from Linq2Db.

**Comment by sdanyliv** [comment]
Database is not a just object store, there are temporary tables, system tables, linked server tables. So you want to limit yourself to just defined model? I don't think so.
