### ISSUE TITLE
Multiple Columns with MemberName not woriking

### ISSUE THREAD

**Issue by Daveismus** [linq2db/linq2db#2590]
I have the following setup 
```cs
[Table(Name = "Customer")]
public partial class Customer
{
    [PrimaryKey, Identity]
    [Column(Name = "CustomerId"), NotNull]
    public int CustomerId { get; set; }

    [Column(Name = "Street", MemberName = ".Street"),  Column(Name = "City", MemberName = ".City")]
    public Adress Adress { get; set; }
}

public class Adress
{
    public string  Street { get; set; }
    public string City { get; set; }
}
```
Inside the Customer Adress there is only Street set and not City. 

### Steps to reproduce
Just use multiple MemberNames like shown above.

### Environment details
linq2db version: *3.1.6*
Database Server: *SQLite*
Database Provider: *SQLite*
Operating system: *Windows*
.NET Framework: *4.7.2*

**Comment by MaceWindu** [comment]
Does it work when you move attributes to class?
```cs
[Column(Name = "Street", MemberName = "Adress.Street"),  Column(Name = "City", MemberName = "Adress.City")]
[Table(Name = "Customer")]
public partial class Customer
```

**Comment by Daveismus** [comment]
This Works. Thanks.

**Comment by MaceWindu** [comment]
Reopen, as we need to fix this case too. For some reason we have tests only for attriutes on table class.
