### ISSUE TITLE
Question: How to connect to Sybase db via ODBC?

### ISSUE THREAD

**Issue by VILLAN3LL3** [linq2db/linq2db#2594]
I installed the `linq2db.Sybase`, `AdoNetCore.AseClient` and `linq2db.SpNet` nuget packages in my .net5 project. 

Then In initialized the `AppDataConnection `in my `Startup.cs`:

```
services.AddLinqToDbContext<IAppDataConnection, AppDataConnection>((provider, options) =>
            {
                options.UseConnectionString(LinqToDB.ProviderName.Sybase, Configuration.GetConnectionString("DefaultConnection"));
                options.UseDefaultLogging(provider);
            });
```

But I have to use an ODBC connection string and this seems to be not supported by the AseClient (before adding linq2sql I connected to the db via `System.Data.Odbc` ): "Data Source is not specified".

How can I use linq2db for my sybase db using an ODBC connection? 

### Environment details
linq2db version: 3.1.6
Database Server: Odbc connection
Database Provider: Sybase 17
Operating system: Win 10
.NET Framework: .Net5

**Comment by sdanyliv** [comment]
Linq2db do not support Sybase connection via ODBC, only via ADO.NET provider (which is better). It is a problem? You cannot specify proper connection string or it is a restriction?

**Comment by VILLAN3LL3** [comment]
Unfortunately I have to use the ODBC connection for the database. I only need the connection to manipulate data on the db, not to change the schema.

**Comment by sdanyliv** [comment]
linq2db do not change schema as EF does. This connection is needed only for data manipulation.
Better to start working without ODBC and then, if you want, you can propose PR with ODBC provider. Not too much work here.
As reference source you can use [AccessODBCDataProvider](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Access/AccessODBCDataProvider.cs)

**Comment by MaceWindu** [comment]
Currently there is no plans to support ODBC provider for ASE. We already support native provider and AdoNetCore managed provider. ODBC doesn't add any value here
