### ISSUE TITLE
LoadWith performance regression problem

### ISSUE THREAD

**Issue by rchamorro** [linq2db/linq2db#2596]
There is a performance problem generating queries when they have many LoadWith statements in version 3.x that were not happening in version 2.x.

We have updated a project from linq2db@2.9.8 to linq2db@3.1.6 and some queries that were already working take to long or don't work at all. The problem is not retrieving the results, but generating the sql, because just doing a .ToString() in the query already hangs the program.

The code to make it hang in version 3.x (not in version 2.x) can be something like this:
```c#
var query = db
                .GetTable<CustomInvoice>()
                .LoadWith(i => i.Invoice)
                .LoadWith(i => i.Invoice.Rectifying)
                .LoadWith(i => i.Invoice.RefundBy)
                .LoadWith(i => i.Invoice.PendingState)
                .LoadWith(i => i.Invoice.Lines)
                .LoadWith(i => i.Invoice.Lines.First().ProductUnit)
                .LoadWith(i => i.Invoice.Lines.First().Product)
                .LoadWith(i => i.Invoice.TaxLines)
                .LoadWith(i => i.Invoice.TaxLines.First().Tax)
                .LoadWith(i => i.Contract)
                .LoadWith(i => i.AccessTariff)
                .LoadWith(i => i.ServicePoint)
                .LoadWith(i => i.ServicePoint.Town)
                .LoadWith(i => i.ServicePoint.Town.State.Community)
                .LoadWith(i => i.ServicePoint.StreetType)
                .LoadWith(i => i.InvoiceLines)
                .LoadWith(i => i.TypeAMeasures)
                .LoadWith(i => i.TypeAMeasures.First().Source)
                .LoadWith(i => i.TypeAMeasures.First().PreviousSource)
                .LoadWith(i => i.TypeBMeasures)
                .LoadWith(i => i.PriceList)
                .Where(f => f.Id == 1);

            var _ = query.ToString(); // Does not work with v 3.x

```

### Steps to reproduce

I have created a solution with exactly the same code shared between two projects, one with version 2.9.8 and one with version 3.1.6 so it is easy to spot the problem.

https://github.com/rchamorro/linq2db-loadwith-problem

### Environment details
linq2db version: 3.x 
Database Server: Postgresql
Database Provider:  Postgresql
Operating system: Windows
.NET Framework: netcore31

**Comment by sdanyliv** [comment]
Thanks for reporting. Will check.

**Comment by Trigun27** [comment]
Ye, same problem. upgrade from 2.9 to 3.1.6 and some queries started to work slow
