### ISSUE TITLE
Async API Guidelines Design

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#2603]
It is not like I think it will be redundant, but I agree that we should postpone it for now. You unintentionally rised issue with our async API surface - it is not systematic. Earliest versions of async API provide ToList/ToArray methods, later we started to use Task<IEnumerable> but probably IAsyncEnumerable is correct answer here. Also cancellation token use differ between methods.

We should take timeout to think and decide on async API guidelines. After that we will review/refactor existing API.

_Originally posted by @MaceWindu in https://github.com/linq2db/linq2db/pull/2589#issuecomment-723192894_

**Comment by MaceWindu** [comment]
We need strict guidelines on async API: return types, naming, cancellation token support as now it is vary across codebase, which is not good. And even leads to issues with API discovery (see original issue)

**Comment by MaceWindu** [comment]
List of questions:
- async method naming: *Async suffix
- return task type: ValueTask vs Task
- return type for collections: task-ed collection/enumerable vs iasyncenumerable + tocollection helpers
- cancellation token: position and default parameter vs extra overload

**Comment by MaceWindu** [comment]
Next steps:
- new/missing API designed according to guidelines
- non-conforming api obsoleted if possible and/or replaced in next major release

**Comment by MaceWindu** [comment]
related issue #2386

**Comment by viceroypenguin** [comment]
>return task type: ValueTask vs Task

We should use `Task<>` instead of `ValueTask<>` for our APIs. Per (this document)[https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/], unless we are specifically looking to avoid the allocation on the return, we should stick to the traditional `Task<>`. Given our other allocations (even minimal), I would say this is a minor cost for the benefit of being easier to use, etc.

**Comment by viceroypenguin** [comment]
@MaceWindu @sdanyliv [here](https://github.com/linq2db/linq2db/wiki/Async-API-Style-Guidelines-%5BIN-PROGRESS%5D) is a preliminary guideline. I will go back through the l2db API and update the document w/ our existing apis and what they should be. I'll also create a ticket to adjust existing APIs to this spec.

This is a breaking change, but I think the result is cleaner for handling both async call to traditional enumerable as well as async enumerable.
