### ISSUE TITLE
Bug in Sql.Function Left?

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#2605]
Hi,

Just reading the code and found this:
```c#
[Sql.Function(                      PreferServerSide = true)]
[Sql.Function(PN.SQLite, "LeftStr", PreferServerSide = true)]
public static string? Left(string? str, int? length)
{
    return length == null || str == null || str.Length < length? null: str.Substring(1, length.Value);
}
```
Why startIndex = 1 in `str.Substring(1, length.Value)`?
Shouldn't be there startIndex = 0?
(startIndex = The zero-based starting character position of a substring in this instance.)

**Comment by MaceWindu** [comment]
Yep, looks like a bug.

**Comment by yarecky1** [comment]
I'll make PR.

**Comment by MaceWindu** [comment]
Thanks. Please check if we have test coverage for this function (looks like at least client-side part is missing) and add missing test case.

**Comment by yarecky1** [comment]
@MaceWindu Where is the best place to insert the tests for functions? I've searched the folders and nothing fits.
I'm asking because I see next bug here (index will be less than 0 and will raise exception):
```
public static string? Substring(string? str, int? startIndex, int? length)
{
    return str == null || startIndex == null || length == null ? null : str.Substring(startIndex.Value - 1, length.Value);
}
```

**Comment by MaceWindu** [comment]
Tests for those functions are there https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/StringFunctionTests.cs
and I don't see them testing non-db execution :-/

**Comment by yarecky1** [comment]
Ok, already started and decided to add tests to all non-db string functions.

**Comment by yarecky1** [comment]
Finished.
