### ISSUE TITLE
Force index

### ISSUE THREAD

**Issue by BergenSoft** [linq2db/linq2db#2607]
I have a query where my database is using an index that is not optimal for it.
Is it possible to add a force index statement with linq2db?

**Comment by sdanyliv** [comment]
Not yet. We have epic for such request https://github.com/linq2db/linq2db/issues/2452
I hope we will start soon.

**Comment by viceroypenguin** [comment]
@BergenSoft Which db are you using? If it is one that allows specifying the index as a table hint, you can use the `.With()` call to add a table hint. `table.With("index(IX_IDX)")` would work on MS SQL, for example.

**Comment by BergenSoft** [comment]
Thanks for your responses. `table.With(...)` is not useable for me, because I use MariaDB.
Is it possible to do a workaround until the feature is available?

`var db = new MyDatabase();
var query = db.GetTable<Table>().Where(dbo => dbo.column == "VALUE");
var sql = LinqToDB.Linq.Internals.CreateExpressionQueryInstance<Table>(db, query.Expression).ToString();
sql = sql.Replace("WHERE", "FORCE INDEX(INDEX_NAME) WHERE");
return db.FromSql<Table>(sql);`

But I got the following error:

> MySqlException: Parameter '@column0' must be defined.

I found, that `FromSql` has a second argument for the parameters, but I couldn't find out how to get this from the current expression.
So could you help me where I can get this parameters?

**Comment by viceroypenguin** [comment]
Try this. You can use `"VALUE"` or an actual variable inside the `{}`. l2db will automatically identify any interpolations in the string and convert them to parameters.

```csharp
return db.FromSql<Table>($"select colA, colB from Table where column == {"VALUE"}");
```

**Comment by MaceWindu** [comment]
`ToString` returns debug sql, not intended for execution.
As in mysql hint also applied to table, you can use [`WithTable`](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.cs#L119) extention, which allows you to specify hint format:
```cs
 db.GetTable<Table>().WithTable("{0} {1} FORCE INDEX(INDEX_NAME)")
```

**Comment by BergenSoft** [comment]
Thanks, thanks, thanks.
That's what I was looking for and it works perfectly.
Just the method name is `WithTableExpression`.
Thanks a lot for this fast and good response.
