### ISSUE TITLE
Issue when using linq2db with mono

### ISSUE THREAD

**Issue by Infernno** [linq2db/linq2db#261]
Hey guys.
I have an application that relies on System.Data.SQLite (official managed wrapper for SQLite) and Linq2DB.
Connection string is specified in App.config:

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
    </startup>

  <connectionStrings>
    <add name="Database" connectionString="Data Source=database.db" providerName="System.Data.SQLite" />
  </connectionStrings>
</configuration>
```

Under .NET 4.6 on Windows it runs fine. BUT, on Linux & Windows under Mono it falls with the following exception:

``` CSharp
System.ArgumentNullException: Argument cannot be null.
Parameter name: key
at System.Collections.Concurrent.ConcurrentDictionary`2[System.String,LinqToDB.Data.DataConnection+ConfigurationInfo].TryGetValue (System.String key, LinqToDB.Data.ConfigurationInfo& value) [0x00000] in <filename unknown>:0
at LinqToDB.Data.DataConnection.GetConfigurationInfo (System.String configurationString) [0x00000] in <filename unknown>:0
at LinqToDB.Data.DataConnection.GetDataProvider (System.String configurationString) [0x00000] in <filename unknown>:0
at LinqToDB.DataContext..ctor (System.String configurationString) [0x00000] in <filename unknown>:0
at LinqToDB.DataContext..ctor () [0x00000] in <filename unknown>:0
at ConsoleApplication2.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```

This exception is caused by:

``` CSharp
using(var context = new DataContext())
{
    //
}
```

As i said, the most interesting thing - it falls under mono. Under .NET 4.6 it runs fine, no exceptions.
P.S. Tested with latest Mono **4.0.4 SR 4 (4.0.4.1)**

**Comment by jogibear9988** [comment]
@ili i think its fixed, as i use sytem.data.sqlite on mono

**Comment by Infernno** [comment]
As far as i remember, the problem was that path to the System.Data.SQLite library (bundled with app) was incorrectly determined (slash was missing, so instead of `file:///home/...` path started with `file://home/...`)
Now judging by changes made in [SQLiteTools.cs](https://github.com/linq2db/linq2db/blob/master/Source/DataProvider/SQLite/SQLiteTools.cs) it may work, but honestly i migrated to Entity Framework Core long time ago.

**Comment by jogibear9988** [comment]
if fixed this, can be closed...

one question, is ef core comparable to linq2db in speed and linq generation?

**Comment by sdanyliv** [comment]
EF, still have issues with SQL generation. Sometimes they buggy decided to process queries on client side - million of records on client side!
For me EF stays on beginner level and not ready for enterprise.
Object mapping in linq2db have no concurents in performance, even with Dapper.

**Comment by Infernno** [comment]
> EF, still have issues with SQL generation. Sometimes they buggy decided to process queries on client side - million of records on client side!
For me EF stays on beginner level and not ready for enterprise.
Object mapping in linq2db have no concurents in performance, even with Dapper.

Agree. From my experience, I would even say that EF Core isn't too much different from previous version 
(EF 6).
We're still using EF Core in small internal project (but it's not intended for high loads), it works acceptable though.

**Comment by sdanyliv** [comment]
That is a problem. You start with acceptable performance gaps, but when database becomes larger - you switch to data reader (or dapper). That means rewriting a tons of code.

**Comment by jogibear9988** [comment]
Then use linq2db and staywith it ;-)

**Comment by jogibear9988** [comment]
close this issue?

**Comment by ili** [comment]
I think we should finish work on travis-ci builds before.

**Comment by sdanyliv** [comment]
@ili, close after fixing #504

**Comment by ili** [comment]
should be fixed now
