### ISSUE TITLE
Fatal error encountered during command execution.

### ISSUE THREAD

**Issue by zdhuka** [linq2db/linq2db#2611]
Hi,
I am encountering an exception while performing an insert in a table with 1 text column and having ~80 columns. It sometimes throws exception after 8-12 hours of inactivity but when retrying it works. I have DataConnection tracing enabled and the query that is generated by linq2db run fine in lower environments. 

Not sure what the issue is, do let me know if it is not relevant to linq2db.

```
Exception message:
Stack trace:
Message  : Fatal error encountered during command execution.
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)

Exception: System.IO.IOException
Message  : Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at MySql.Data.MySqlClient.TimedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.SendPacket(MySqlPacket packet)
   at MySql.Data.MySqlClient.NativeDriver.ExecutePacket(MySqlPacket packetToExecute)
   at MySql.Data.MySqlClient.NativeDriver.SendQuery(MySqlPacket queryPacket)
   at MySql.Data.MySqlClient.Driver.SendQuery(MySqlPacket p)
   at MySql.Data.MySqlClient.Statement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)

Exception: System.Net.Sockets.SocketException
Message  : An established connection was aborted by the software in your host machine
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
```

### Steps to reproduce
1. Create console application and use database with following connection string. "ConnectionString": "Server=127.0.0.1;Port=3306;Database=<DB_SCHEMA>;Uid=<DB_USER>;Pwd=<DB_Password>;charset=utf8;Connection Timeout=60;Min Pool Size=1;Max Pool Size=5;Connection Lifetime=600;SslMode=None;
2. Perform some random selects on database to ensure at least 1 physical connection is active.
3. Let it run  inactively for some event to happen after 8-12 hours. 
4. Once event arrives perform may be upto 4 selects on one or more tables and finally 1 insert on table of interest. Make sure the table has 80 columns and contains a text column as well.

```c#
Some scrapped code

public class SomeRepository : ISomeRepository, IDisposable
{

	protected SomeDB db = new SomeDB();
	protected QueryRepo queryRepo;
		
	public async Task<string> CreateSome(Some model){
		
		Some lastSome = await queryRepo.greateLastSome(model);
		//external function call above - queryRepo.greateLastSome(model) where it works like mentioned below
		//using (var db = new SomeDB())
		//{
		//	var SomebefQuery = db.Some.Where(ddi => ddi.Id == model.Id && ddi.WId == model.WId && ddi.Md == model.Md && ddi.Inc == model.Inc && ddi.Azi == model.Azi);
		//	lastSome = await SomebefQuery.FirstOrDefaultAsync();
		//}
		
		Some newSome;
		.	<some long running operation which can take ~1 min>
		.
		.
		.
		
		var newIdentity = await DBCommand.Execute(db, InsertCommandFunc(newSome), null);
		
		return newIdentity; //returns uuid
	}
	
	
	public Func<Task<QueryCommandInfo<Some>>> InsertCommandFunc(Some model)
	{
		return async () =>
		{
			var result = await db.InsertAsync(model);
			return new QueryCommandInfo<Some>
			{
				Id = model.Id,
				Model = model,
				Result = result,
				QueryType = NavQueryType.Insert
			};
		};
	}
}
```

### Environment details
linq2db version: 2.7.0
Database Server: MySQL Server 8.0
Database Provider: linq2db.MySql 2.7.0 / MySql.Data (6.10.6)
Operating system: windows server 2019 standard
.NET Framework: dotnet core 2.1.1

**Comment by MaceWindu** [comment]
From error it doesn't look like related to linq2db. More like issue in MySql.Data (one of many).

BTW, I would recommend you to switch to MySqlConnector provider if possible. MySql.Data provider is really low quality one.

**Comment by MaceWindu** [comment]
Also there is no sense in using async with mysql.data as it doesn't implement async API (all it's async APIs are implemented as sync calls). ( and MySqlConnector supports async properly)

**Comment by MaceWindu** [comment]
Actually, error you get is qute strange:
```
Message  : An established connection was aborted by the software in your host machine
```
Could be firewall/antivirus on your side messing with connections

**Comment by zdhuka** [comment]
We are already looking into adding exceptions to our firewall/antivirus. 
As far as MySql.Data goes, I think it is camming from linq2db.MySQL as shown in screen shot, I will try and switch it to MySqlConnector provider.
![image](https://user-images.githubusercontent.com/3692846/98599846-44d83b00-22a2-11eb-9451-3a719d58970a.png)

Thanks @MaceWindu

**Comment by MaceWindu** [comment]
We have separate nuget for mysqlconnector but if you don't need t4 templates, you can reference provider and linq2db nugets directly (but note that linq2db  2.x doesn't support mysqlconnector 1.0+, as they changed namespaces in 1.0 )

**Comment by zdhuka** [comment]
Ohk. Got it. Thanks again.
