### ISSUE TITLE
"Union" with "order by" throw Exception

### ISSUE THREAD

**Issue by slartus** [linq2db/linq2db#2619]
### 1 Example
>  Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00933: неверное завершение SQL-предложения
   в OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   в OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   в OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   в Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   в Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   в System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)

### 2 Example
> Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00904: "ITEM_1"."ID": invalid identifier
   в OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   в OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   в OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   в Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   в Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   в System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)

### Steps to reproduce
```
create table LINQ2DB_TEST
(
	ID int
		constraint LINQ2DB_TEST_PK
			primary key,
	TEST1 varchar2(20),
	TEST2 int
)
/
```
```c#
public class Db: DataConnection
    {
        public ITable<TestTable> TestTable => this.GetTable<TestTable>();

        public Db(string connectionString):base(ProviderName.OracleManaged, connectionString)
        {
        }       
    }

    [Table("LINQ2DB_TEST")]
    public class TestTable
    {
        [Column("ID"), PrimaryKey, NotNull]
        public long Id { get; set; } 

        [Column("TEST1")]
        public string Test1 { get; set; }

        [Column("TEST2")]
        public long Test2 { get; set; }
    }
```

### 1 Example
```c#
using (var db = new Db(connectionString))
{
    var query = ((from item in db.TestTable select item).OrderBy(i => i.Id)).Union((from item in db.TestTable select item));

    var items = await query.ToListAsync();
}
```

### 2 Example
```c#
using (var db = new Db(connectionString))
{
    var query = (from item in db.TestTable select item).Union((from item in db.TestTable select item)
                        .OrderBy(i => i.Id));

    var items = await query.ToListAsync();
}
```

### Environment details
linq2db version: *3.1.6*
Database Server: *Oracle 19.0.0.0.0*
Database Provider: *?*
Operating system: *?*
.NET Framework: *4.7.2*, *.net core 3.1*

**Comment by sdanyliv** [comment]
Thanks for reporting. Will check.

**Comment by slartus** [comment]
linq2db version: 3.2.3
Database Server: Oracle 19.0.0.0.0
Database Provider: ?
Operating system: ?
.NET Framework: 4.7.2, .net core 3.1


Example 2 is not resolved.
still has exception.

**Comment by MaceWindu** [comment]
Confirmed. Second query in union is not wrapped in subquery when sorted, which makes oracle puzzled:

` ORA-00904: "T3"."ChildID": invalid identifier`

```sql
SELECT
    	t2."ParentID",
    	t2."ChildID"
    FROM
    	(
    		SELECT
    			t1."ParentID",
    			t1."ChildID"
    		FROM
    			"Child" t1
    		ORDER BY
    			t1."ChildID"
    	) t2
    UNION ALL
    SELECT
    	t3."ParentID",
    	t3."ChildID"
    FROM
    	"Child" t3
    ORDER BY
    	t3."ChildID" DESC
```

`ORA-00904: "ITEM_1"."ChildID": invalid identifier`

```sql
SELECT
    	item."ParentID",
    	item."ChildID"
    FROM
    	"Child" item
    UNION
    SELECT
    	item_1."ParentID",
    	item_1."ChildID"
    FROM
    	"Child" item_1
    ORDER BY
    	item_1."ChildID"
```

**Comment by slartus** [comment]
@MaceWindu

linq2db version: 3.4.0
Database Server: Oracle 19.0.0.0.0
Database Provider: ?
Operating system: ?
.NET Framework: 4.7.2, .net core 3.1

Example 1 again throw exception ORA-00933
Example 2 is not resolved.
still has exception.

**Comment by aloksharma1** [comment]
i have the same issue with linq2db 3.5.0

**Comment by lytico** [comment]
it worked with linq2db 3.1
it's a real showstopper for upgrading to recent versions.

**Comment by sdanyliv** [comment]
It is still not working in latest lnq2db 3.7.0. version?

**Comment by lytico** [comment]
no, latest linq2db 3.7.0 throws

```
Npgsql.PostgresException (0x80004005): 42P01: missing FROM-clause entry for table "calculation"

POSITION: 1274
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior) in Linq2Db/Source/LinqToDB/Data/DataConnection.cs:line 1399
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in Linq2Db/Source/LinqToDB/Data/DataConnection.cs:line 1431
   at LinqToDB.Data.DataConnection.ExecuteReader() in Linq2Db/Source/LinqToDB/Data/DataConnection.cs:line 1404
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in Linq2Db/Source/LinqToDB/Data/DataConnection.QueryRunner.cs:line 515
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext() in Linq2Db/Source/LinqToDB/Linq/QueryRunner.cs:line 393
```

the query is like this:
```
 	Expression<Func<Machine, bool>> machineCriteria = machine => true;
        Expression<Func<Plant, bool>> plantCriteria = plant => true;

        var machines = context.Machines
           .Where (machineCriteria)
           .OrderBy (c => c.ServiceCode);

        var plants = context.Plants
           .Where (plantCriteria);

        var plantRelations =
            context.PlantRelations
               .Join (machines,
                    plantRelation => plantRelation.SubjectId, machine => machine.Id,
                    (plantRelation, machine) => plantRelation);

        var plantsRelated = plantRelations
           .Join (context.Plants, plantRelation => plantRelation.PlantId, plant => plant.Id,
                (relation, plant) => plant);

        var plantsUnion = plants.Union (plantsRelated)
           .ToArray ();
```

**Comment by sdanyliv** [comment]
Add generated SQL and model. Anyway Union and OrderBy are two mutual exclusive things here.

**Comment by lytico** [comment]
thanks for the fast reply!

i'll try to refactor the example with models from https://github.com/linq2db/linq2db/blob/master/Tests/Model/Northwind.cs.
so then i could make an PR with Testcase, i guess. just give me some time....

**Comment by lytico** [comment]
pr is here: https://github.com/linq2db/linq2db/pull/3505

[Issue2619Tests.Result.log](https://github.com/linq2db/linq2db/files/8488187/Issue2619Tests.Result.log)
