### ISSUE TITLE
T4 templates error in Rider

### ISSUE THREAD

**Issue by pavelvondrasek** [linq2db/linq2db#2622]
Hi,

I'm using Rider for .NET development and Linq2db templates always show me error how you can seen on the screen:

<img width="870" alt="Screenshot 2020-11-14 at 16 33 32" src="https://user-images.githubusercontent.com/7081340/99150820-76347a80-2697-11eb-8e9a-f3d88db0b2ca.png">

I don't know that error is in Rider T4 implementation or whatever but it's very uncomfortable because I don't know that is error in project or not because it always show in all projects which has linq2db as dependency because template folder is automatically symlinked and I cannot exclude it.

Thanks for your advice and have a nice weekend! :)

**Comment by MaceWindu** [comment]
If you don't use T4 templates, you can remove reference to `linq2db.<dbname>` nuget and reference linq2db and provider nugets directly.
But yeah, this is [rider issue](https://github.com/JetBrains/ForTea/issues/12). We plan to provide t4-less scaffolding in near future.

**Comment by pavelvondrasek** [comment]
Thank you now it's better :) 

I'm closing issue.

**Comment by kirillgla** [comment]
Hello @MaceWindu! Is there any ETA for t4-less scaffolding?

**Comment by MaceWindu** [comment]
I expect it to be done in first quarter next year.
