### ISSUE TITLE
UInt64 and Npgsql

### ISSUE THREAD

**Issue by devhl-labs** [linq2db/linq2db#2624]
When using BulkInsertAsync, I'm seeing this error:

System.InvalidCastException: 'Can't write CLR type System.UInt64 with handler type NumericHandler'

When using BulkCopyAsync I get an index of of range exception. I'm guessing these errors have the same source. I am using Npgsql. EF Core 5.0 is creating rows for my ulong of type Numeric with precision 20, scale 0, and dimensions 0.

**Comment by MaceWindu** [comment]
@devhl-labs you can apply fix manually while it is not released by setting following conversion in linq2db mapping schema:
```cs
ms.SetConvertExpression<ulong? , DataParameter>(value => new DataParameter(null, value == null ? (decimal?)null : (decimal)value, DataType.Decimal), false);
```
@sdanyliv , I'm not familiar with mapping schema access with ef.core integration, could you add more details here?

**Comment by devhl-labs** [comment]
What do I do with the MappingSchema object?

**Comment by MaceWindu** [comment]
@sdanyliv

**Comment by sdanyliv** [comment]
@devhl-labs, you can setup `MappingSchema.Default`.
Or derive from class `LinqToDBForEFToolsImplDefault` and override `CreateMappingSchema`, then assign `LinqToDBForEFTools.Implemenation` property by instance of this class. 

Only in these cases you can change `MappingSchema` behavior.

So based on PR which fixes your issue. This code should be enough until new `linq2db` version released. Just do that only once per application.
```cs
var ms = MappingSchema.Default;
ms.SetConvertExpression<ushort?, DataParameter>(value => new DataParameter(null, value == null ? (int?)null     : (int)value    , DataType.Int32)  , false);
ms.SetConvertExpression<uint?  , DataParameter>(value => new DataParameter(null, value == null ? (long?)null    : (long)value   , DataType.Int64)  , false);
ms.SetConvertExpression<ulong? , DataParameter>(value => new DataParameter(null, value == null ? (decimal?)null : (decimal)value, DataType.Decimal), false);

```
