### ISSUE TITLE
Fill poco association

### ISSUE THREAD

**Issue by guilkuhl** [linq2db/linq2db#263]
Hello,
I have a class object with 5 depths of association, as I want to fill it works well but it's really slow.The filling application is split into several sub query instead of a single, complete can complex objects with a single query?

example:
Table1 - Table 2 

```
From Table1 in db.Table1 
let var = (from table2 in db.table2 Where table1.Id equals table2.Id)  ' (sub query)here a list of sub objects
select Poco.Build(Table1,var)
```

How I can do to improve it? thank you

**Comment by sdanyliv** [comment]
@guilkuhl, you have to deal with LoadWith but i have limitations and may produce many queries.
Check discussions: #536, #527, #342.

Closing for now.

**Comment by jogibear9988** [comment]
@sdanyliv are we planing to support scenarios like this? meaning that we don't create subqueries

**Comment by ili** [comment]
May be in v2.
