### ISSUE TITLE
Red code in T4 templates in JetBrains Rider

### ISSUE THREAD

**Issue by kirillgla** [linq2db/linq2db#2633]
Jetbrains Rider reports errors in the templates after installation.
As the developer of the Rider T4 plugin, I think that this is the intended behaviour.
These templates are red in Rider because they are not self-sufficient: some templates contain references to libraries, while others contain usages of symbols from those libraries. It is absolutely impossible to resolve those symbols before both templates with assembly references and templates with usages of their symbols are included into a user file.
So templates with symbol usages implicitly assume that the user will include templates with definitions or references.
I suggest making that dependency explicit by including templates with references or definitions into the dependent templates.
For example, `Equatable.ttinclude` would include `T4Model.ttinclude` since it uses symbol `BeforeGenerateModel` defined in it.
Duplicate inclusions can be avoided by using attribute `once="true"` in such includes.

**Comment by MaceWindu** [comment]
Thanks for this info!

**Comment by picolino** [comment]
We have a workaround to fix that, but it is not clear honestly. See [this comment](https://github.com/JetBrains/ForTea/issues/12#issuecomment-750813543) in related issue
