### ISSUE TITLE
How to switch different database using different context in shared business layer/repositories?

### ISSUE THREAD

**Issue by sgtagan** [linq2db/linq2db#2641]
I have 3 databases
1) Master DB
2) ProjectA DB
3) ProjectB DB

ProjectA DB and ProjectB DB get master data from Master DB.

So my project solution has 2 projects with shared business layers and repositories. T4 Template created Master + ProjectA (ProjectADB) context and Master + ProjectB (ProjectBDB) context.

Following linq2db wiki, I injected dataconnection and ProjectADB when running ProjectA.

```cs
private readonly ProjectADB _db;
public BaseBusiness(DataConnection db)
{ 
   _db = (ProjectADB)db;
}
```
How to use ProjectBDB in shared BaseBusiness when running ProjectB? I only know one possible way is use one context that includes all Master + ProjectA + ProjectB but it has too many classes.

Is it possible to switch different contexts in shared business layers / repositories?

**Comment by viceroypenguin** [comment]
If it were me, I would update the constructor as follows:
```csharp
private readonly ProjectADB _adb;
private readonly ProjectBDB _bdb;
public BaseBusiness(ProjectADB adb, ProjectBDB bdb)
{
  _adb = adb;
  _bdb = bdb;
}
```

**Comment by sgtagan** [comment]
> If it were me, I would update the constructor as follows:
> 
> ```cs
> private readonly ProjectADB _adb;
> private readonly ProjectBDB _bdb;
> public BaseBusiness(ProjectADB adb, ProjectBDB bdb)
> {
>   _adb = adb;
>   _bdb = bdb;
> }
> ```

will it affect memory/performance leak?

**Comment by viceroypenguin** [comment]
Definitely not a memory leak. Only marginally more memory used than w/ one. The biggest elements inside the library are cached across all connections, so this wouldn't be a significant memory usage increase.

**Comment by sgtagan** [comment]
> Definitely not a memory leak. Only marginally more memory used than w/ one. The biggest elements inside the library are cached across all connections, so this wouldn't be a significant memory usage increase.

Thanks. And one question about shared repository.

```
public ProjectADB _adb;
public ProjectBDB _bdb;
public BaseRepository(ProjectADB adb, ProjectBDB bdb)
{
  _adb = adb;
  _bdb = bdb;
}

public List<T> GetA()
   => _adb.GetTable<T>().ToList();
public List<T> GetB()
   => _bdb.GetTable<T>().ToList();

public void SaveA(T obj)
   => _adb.Insert(obj);
public void SaveB(T obj)
   => _bdb.Insert(obj); 
```

For generic CRUD, I have to do this for both projects? Or any other better method?

**Comment by viceroypenguin** [comment]
I think this would be the best way to do it, if you want to have a common repository base for each type. I think this is your trade-off for not having all three databases in the same `DataConnection`. 

Maybe you could do a custom attribute and decorate each class w/ with that attribute and a flag that tells whether that table belongs to ProjectADB or ProjectBDB. Then in your `List<T> Get()`, you could query that attribute and select which connection to use based on that?

**Comment by sgtagan** [comment]
> I think this would be the best way to do it, if you want to have a common repository base for each type. I think this is your trade-off for not having all three databases in the same `DataConnection`.
> 
> Maybe you could do a custom attribute and decorate each class w/ with that attribute and a flag that tells whether that table belongs to ProjectADB or ProjectBDB. Then in your `List<T> Get()`, you could query that attribute and select which connection to use based on that?

Noted and thanks.

**Comment by viceroypenguin** [comment]
Assuming question answered; closing. Feel free to reopen if you have any further questions.
