### ISSUE TITLE
GetReserveSequenceValuesSql implementation for PostgreSQL

### ISSUE THREAD

**Issue by millworm** [linq2db/linq2db#2645]
Hello! in my code, I tried using RetrieveIdentity for collections, but got the error that GetReserveSequenceValuesSql not implemented for PostgreSQLSqlBuilder . tried below code for implementation. it works
```c#
public override string GetReserveSequenceValuesSql(int count, string sequenceName)
{
  return $"WITH RECURSIVE t(n,id) AS (SELECT 1, nextval('{sequenceName}') UNION ALL SELECT n+1, nextval('{sequenceName}')  FROM t WHERE n < {count}) SELECT id FROM t;";
}
```
is it possible to add this to your code?

**Comment by sdanyliv** [comment]
Thanks for the code, but. How many items this recursive CTE can generate? Maybe it is better join to `GENERATE_SERIES`?

**Comment by millworm** [comment]
yeah, probably GENERATE_SERIES will do better

**Comment by sdanyliv** [comment]
@MaceWindu,
This  query should work, for sure better escaping is needed:
```sql
 return $"select nextval('{sequenceName}') from generate_series(1, {count})";
```
