### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer' from assembly 'Microsoft.EntityFrameworkCore

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2653]
FirstOrDefault throws
linq2db.EntityFrameworkCore.dll: 'Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, 

Do I miss something?

```C#
            LinqToDBForEFTools.Initialize();
            using (var efContext = new AccountingContextEf())
            {
                efContext.Database.OpenConnection();
                efContext.Database.Migrate();
                efContext.Database.CloseConnection();

                efContext.Database.EnsureCreated();
                var linq2DbContext = efContext.CreateLinqToDbContext();
                var first = linq2DbContext.GetTable<User>().FirstOrDefault();
            }
```

### Environment details
linq2db version: 3.1.6
Database Server: SQLite In Memory
.NET Framework: 5.0.0

**Comment by jogibear9988** [comment]
Wich version of https://github.com/linq2db/linq2db.EntityFrameworkCore
Maybe the issue should be moved to there?

**Comment by HypeillingerChillinger** [comment]
I guess Linq to Db is using sth. that is not available in version 5.0.0

**Comment by sdanyliv** [comment]
@HypeillingerChillinger, create small reproducible sample.

**Comment by jogibear9988** [comment]
wich version of linq2db.EntityFrameworkCore do you use?

**Comment by jogibear9988** [comment]
and maybe a stacktrace would also help

**Comment by HypeillingerChillinger** [comment]
<PackageReference Include="linq2db.EntityFrameworkCore" Version="3.7.0" />


Eine Ausnahme vom Typ "System.TypeLoadException" ist in linq2db.EntityFrameworkCore.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.: 'Could not load type 'Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer' from assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'
   bei LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.<>c__DisplayClass41_0.<TransformExpression>g__LocalTransform|0(Expression e)
   bei LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.<>c__DisplayClass41_0.<TransformExpression>b__1(Expression e)
   bei LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   bei LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.TransformExpression(Expression expression, IDataContext dc, DbContext ctx, IModel model)
   bei LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.TransformExpression(Expression expression, IDataContext dc, DbContext ctx, IModel model)
   bei LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsDataConnection.ProcessExpression(Expression expression)
   bei LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   bei LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   bei LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei XXXXX.ServiceTestBase.Test() in

**Comment by sdanyliv** [comment]
I need small sample project. This is non informative.

**Comment by jogibear9988** [comment]
is 3.7 not to old for efCore5?
why don't you use 5.0.2 of https://www.nuget.org/packages/linq2db.EntityFrameworkCore

**Comment by jogibear9988** [comment]
maybe we also need to know wich EF Versiojn you use. .net5 does not mean you use ef5

**Comment by HypeillingerChillinger** [comment]
<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="5.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0" />
    <PackageReference Include="linq2db" Version="3.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />

**Comment by HypeillingerChillinger** [comment]
I will post a complete project this evening

**Comment by HypeillingerChillinger** [comment]
Here we go:
https://github.com/HypeillingerChillinger/EfException/tree/master/Bla

**Comment by jogibear9988** [comment]
again, why don't you switch linq2db.EntityFrameworkCore to version 5.02?

**Comment by jogibear9988** [comment]
as you see here: https://github.com/linq2db/linq2db.EntityFrameworkCore/releases only version 5.0.0 has support for ef core 5

**Comment by HypeillingerChillinger** [comment]
Didn't recognize that. Ok, that is the solution.
