### ISSUE TITLE
Performance problems on huge data model

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#2660]
I've being experimenting with migrating our large web project from EF6 to Linq2Db. This project contains about 1000+ entities.
I've noticed, that some (**not all**) entities suffer from overhead even on simplest queries. Example:

```c#
    [Table(Name = "CaseLogProperty", Schema = "v1")]
    public class CaseLogProperty
    {
        [Column]
        [PrimaryKey]
        [Identity]
        public int Id { get; set; }

        [Column]
        public int CaseLogId { get; set; }

        [Column]
        public int PropertyId { get; set; }

        [Column]
        public int? CaseLogFollowUpId { get; set; }

        [Column]
        public int? CaseLogSupplementId { get; set; }
    }

   // DataContext is simple wrapper around DataConnection
  // and Set<T> is simple wrapper around GetTable<T>

    var q = DataContext.Set<CaseLogProperty>()
                .Where(x => x.CaseLogId == caseLog.Id)
                .ToList();
```

This query takes `180ms` to execute, wich includes `50ms` on proccessing query in `SQL Server`.

And the same query, with the same caseLog.Id, but on test project, without any other entities in model takes around `60ms`:

```c#
            var caseLog = new CaseLog { Id = 1088324 };

            using (var con = new DbContext())
            {
                var mn = con.CaseLogProperties
                    .Where(x => x.CaseLogId == caseLog.Id)
                    .ToList();
            }
```

I looked into `EntityDescriptor` for this entity in both projects and found no difference, just five columns.

What may couse this situation? What could I've done wrong to get this? I thought size of data model makes no difference for Linq2Db.

### Environment details
linq2db version: 3.1.6, built from latest commit
Database Server: SQL Server
Database Provider: SQL Server
Operating system: WIN10
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
So, it would be better to show your simple wrapper. Looks like you have missing query cache.
This query should take some time for translation. Then it should be reused from the cache, just updating parameters.

**Comment by sdanyliv** [comment]
Also try to put breakpoint into EntityDescriptor and check how many times it is called.

**Comment by Usaga** [comment]
Wrapper is simple `DataConnection` implementation:

```c#
    public class DbContext : DataConnection, IDisposable
    {
        public DbContext(string connString) : base(LinqToDB.ProviderName.SqlServer, "server=localhost;database=work_database;integrated security=true")
        {
            (this as IDataContext).CloseAfterUse = true;

            if (!_schemaBuilt)
            {
                lock (_cacheSync)
                {
                    if (!_schemaBuilt)
                    {
                        this.MapReportWriterEntityTypes();
                        this.MapListValueTypes();

                        BuildMappingSchema();

                        _schemaBuilt = true;
                    }
                }
            }
        }

        public ITable<T> Set<T>() where T : class
        {
            return this.GetTable<T>();
        }
```

It once was EF's DbContext implementation. It does no extra work, except it uses relfection to initialize Mapping Schema and stores it in `MappingSchema.Default`. But this process called only once, on first call.

> Also try to put breakpoint into EntityDescriptor and check how many times it is called.
Where should I do that?

**Comment by Usaga** [comment]
I can compile Linq2Db in debug and step through it's code to see what's happening. But it's a lot of code I am not familiar with. Would you give some suggestion where to look at?

**Comment by sdanyliv** [comment]
Breakpoint here should hit only one time per class type
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/EntityDescriptor.cs#L26

This place should be reached only once per query
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.QueryRunner.cs#L164

**Comment by Usaga** [comment]
It seems that most of time being spent on query execution intself. I am not sure why, but this has nothing to do with Linq2Db.

Sorry.

**Comment by sdanyliv** [comment]
Probably you have hit bad execution plan cached by SQL Server. Try this trick, which generate literal instead of parameter.
```cs
var caseLog = new CaseLog { Id = 1088324 };

using (var con = new DbContext())
{
      var mn = con.CaseLogProperties
           .Where(x => x.CaseLogId == Sql.AsSql(caseLog.Id))
           .ToList();
}
```
