### ISSUE TITLE
Using Distinct() on a group produces incorrect SQL

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#2662]
I need to count both the total number of items in a group and the unique values in the grouped fields. Using `.Distinct()` on the group produces a `SELECT DISTINCT` on the entire source table rather than only the fields included in the group.

No exceptions, only incorrect SQL and output.

### Steps to reproduce

Contrived example follows.

````C#
[Table(Name="CountDistinctTest")]
public class TestRow
{
    [Column, PrimaryKey]
    public int ID { get; set; }
    
    [Column]
    public int GroupCol { get; set; }
    
    [Column]
    public int LinkCol { get; set; }

    [Column]
    public Guid? NotUsed { get; set; }
    
    public static TestRow[] MakeTestData()
    {
        return Enumerable.Range(0, 100)
            .Select(i => new TestRow { ID = i, GroupCol = i / 20, LinkCol = i % 5 })
            .ToArray();
    }
}

public static bool Test(DataConnection db)
{
    var table = db.CreateTable<TestRow>();
    db.BulkCopy(TestRow.MakeTestData());
    
    try
    {
        var query = 
            from row in table
            group row.LinkCol by row.GroupCol into grp
            select new { grp.Key, c1 = grp.Count(), c2 = grp.Distinct().Count() };
        
        var result = !query.ToArray().Any(row => row.c1 == row.c2);
        return result;
    }    
    finally
    {
        db.DropTable<TestRow>();
    }
}
````

#### Generated SQL.

Note the extra fields in the sub-select. When joined tables are involved (which they often are) all fields from all joined tables are included.

````SQL
SELECT
    [t2].[GroupCol],
    Count(*),
    (
        SELECT
            Count(*)
        FROM
            (
                SELECT DISTINCT
                    [row_1].[ID],
                    [row_1].[GroupCol],
                    [row_1].[LinkCol],
                    [row_1].[NotUsed]
                FROM
                    [CountDistinctTest] [row_1]
                WHERE
                    [t2].[GroupCol] = [row_1].[GroupCol]
            ) [t1]
    )
FROM
    [CountDistinctTest] [t2]
GROUP BY
    [t2].[GroupCol]
````

#### Expected SQL:

````SQL
SELECT
    [t2].[GroupCol],
    Count(*),
    (
        SELECT
            Count(*)
        FROM
            (
                SELECT DISTINCT
                    [row_1].[GroupCol],
                    [row_1].[LinkCol]
                FROM
                    [CountDistinctTest] [row_1]
                WHERE
                    [t2].[GroupCol] = [row_1].[GroupCol]
            ) [t1]
    )
FROM
    [CountDistinctTest] [t2]
GROUP BY
    [t2].[GroupCol]
````

or optionally (SQL Server, at least as far back as 2012):

````SQL
SELECT GroupCol, COUNT(*), COUNT(DISTINCT LinkCol)
FROM CountDistinctTest
GROUP BY GroupCol
````

#### Query Results:

| Key | c1 | c2 |
| --- | --- | --- |
| 0 | 20 | 20 |
| 1 | 20 | 20 |
| 2 | 20 | 20 |
| 3 | 20 | 20 |
| 4 | 20 | 20 |
| 5 | 20 | 20 |

#### Expected Results:

| Key | c1 | c2 |
| --- | --- | --- |
| 0 | 20 | 5 |
| 1 | 20 | 5 |
| 2 | 20 | 5 |
| 3 | 20 | 5 |
| 4 | 20 | 5 |
| 5 | 20 | 5 |

### Workaround

Currently I have to do my grouping and counting in memory in these cases or use a separate query to get both row and distinct counts:

````C#
var distinctCounts = 
    from row in table.Select(r => new { r.GroupCol, r.LinkCol }).Distinct()
    group 1 by row.GroupCol into grp
    select new { grp.Key, c2 = grp.Count() };
````

### Environment details
linq2db version: 3.1.0
Database Server: SQLite, Microsft SQL Server 2017
Database Provider: SQLite, SqlServer
Operating system: Windows 10
.NET Framework: .Net Core 3.0

**Comment by sdanyliv** [comment]
Use `g.CountExt(Sql.АggregateModifier.Distinct)`

**Comment by jogibear9988** [comment]
@sdanyliv bug can we throw a exception that this is not supported?

**Comment by sdanyliv** [comment]
Not a bug, linq2db generated exactly what was requested. For distinct it is needed to limit fields which has to be used, otherwise all available fields will be selected.

**Comment by jogibear9988** [comment]
Means the linq2objects query will return the same result... Then I'll be sorry.

**Comment by Corey-M** [comment]
@sdanyliv 

I think this is a bug. Using standard L2SQL on the same databases I get an inner `SELECT DISTINCT` that only targets the fields that were grouped, as in the 'Expected SQL' above. 

Same happens with L2Objects when I pull the rows into memory:

````C#
var memQuery = 
	from row in table.ToArray()
	group row.LinkCol by row.GroupCol into grp
	select new { grp.Key, c1 = grp.Count(), c2 = grp.Distinct().Count() };
````

This produces the expected output (`c1 != c2` on all rows), because `.Distinct()` is operating directly on the grouped objects rather than the source records.

That said... `CountExt` is better since it doesn't bother with a sub-select to generate the count.

**Comment by sdanyliv** [comment]
@Corey-M, if you need correct Distinct you have to specify which fields to select. Otherwise all available will be used.
```cs
var query = 
            from row in table
            group row.LinkCol by row.GroupCol into grp
            select new 
            { 
                   grp.Key, 
                   c1 = grp.Count(), 
                   c2 = grp.Select(x => x.LinkCol).Distinct().Count() 
           };
```

**Comment by sdanyliv** [comment]
Probably you are right, will check.
