### ISSUE TITLE
SQL Server  => No PK is defined or all fields are keys 

### ISSUE THREAD

**Issue by DiegoStefanon** [linq2db/linq2db#2664]
SQL Server  2019 => No PK is defined or all fields are keys  

A) Table definition in Linq2Db :
```csharp
	[Table("TestTable")]
	public partial class TestTable
	{
		[PrimaryKey, Identity] public int    ID1         { get; set; } // int
		[Column,     Nullable] public string Txt         { get; set; } // varchar(5)
		[Column,     Nullable] public string NumberTxt   { get; set; } // varchar(4)
		[Column,     Nullable] public int?   IntNullable { get; set; } // int
	}
```
B) ID1 is a **PrimaryKey** and Identity column in Sql server 2019 

C)) sql script for table in T-SQL: 
```sql
CREATE TABLE [dbo].[TestTable](
	[ID1] [int] IDENTITY(1,1) NOT NULL,
	[Txt] [varchar](100) NULL,
	[NumberTxt] [varchar](4) NULL,
	[IntNullable] [int] NULL,
 CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED 
(
	[ID1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
```

ERROR produced by ;

```csharp
var listFromDb = _db.TestTable.ToList();

int counter = 1;
foreach (var item in listFromDb)
{
	item.Txt = $"string_Updated2_{counter}";
	++counter;
}

_db.Update(listFromDb );  //**boom** ->  No PK is defined or all fields are keys
```

I'm doing something wrong ?

Many tks ;-)

**Comment by viceroypenguin** [comment]
Sorry, yes. `.Update()` expects a single item, not a list of items. The way you have written it, you are trying to update a single object of type `List<TestTable>` instead of multiple items of `TestTable`. As written, you should call `.Update()` inside the foreach, as follows:
```csharp
var listFromDb = _db.TestTable.ToList();

int counter = 1;
foreach (var item in listFromDb)
{
   item.Txt = $"string_Updated2_{counter}";
   ++counter;
   _db.Update(item);
}
```

**Comment by BenKmann** [comment]
With the [Merge-Api](https://linq2db.github.io/articles/sql/merge/Merge-API.html) and the TempTable-Feature, you can Insert all Entities in the Temptable and then Merge them in your table, in case the "ListFromDb" is big. Merge-API is very efficient.
Or you use it like in Issue 1252 https://github.com/linq2db/linq2db/issues/1252

**Comment by DiegoStefanon** [comment]
Many tks !! ;-)
