### ISSUE TITLE
Creation of Entities fails with Navigation-Properties and Nullable-Bools

### ISSUE THREAD

**Issue by BenKmann** [linq2db/linq2db#2667]
In SQL-Server we use Columns which are nullable bools (bit, null) mapped as bool?. (Not my Database :))
We don't want to have nullable bools in code, so i tried mapping the (bit, null) column to a not nullable bool property in Linq2DB.
Which works wonderful at first. 
But now i found a very strange case. In my table are 25 (bit, null) columns. 
I queried the database with this query
```c#
var linkedContract = db.LinkedContracts
.LoadWith(linked => linked.Fk2_Reference)
.Where(linked => linked.Fk1 == 160160)
.ToList();
// Returns a List with multiple Entries but in one case the Fk2_Reference Property is NULL (but FK2 has an ID).
```

All Fk1 and Fk2 Columns are filled, but 1 linked.Fk2_Reference is NULL. 
So i thought LoadWith is the problem, but upon further inspection, the query below also fails for exactly the same Case:
```c#
var linkedContract = db.LinkedContracts
.Where(linked => linked.Fk1 == 160160)
.Select(verträge => verträge.Vorvertrag_Reference)
.ToList();
// Returns a List with 1 Entry which is NULL
```
But it works normally, when i query the Entity directly without the Navigation Property.
```c#
var contract = db2.Contracts.Find(160851);
```

So there is a Problem in the "Navigation-Property" here. It fails, as soon as all 25 (bit, null) columns in the db are null. It doesn't even call the constructor of the entity. But I don't get an exception either :(.
When i fill the 20th Column with a Value in the Database and the rest is still null, all Queries work. 
If i fill the 21th, 22nd.. Column, it is not enough and Linq2Db still fails. So if i remove the 20th column, then the 15th Column has to be filled, to get a working query. It is all very strange. 

The Query Linq2Db Generates is always the same and correct. So the Query doesn't seem to be the Problem, but apparently the code to generate an Entity when called like this .Select(verträge => verträge.Vorvertrag_Reference) (Navigation-Property) is different, then with a Query directly to the DataTable. (Because it is a Join probably).

I don't map the Columns in any way. I tried mapping them with
propertybuilder.HasDataType(DataType.Boolean).IsNullable(false);
but this didn't help.

If i change the property to bool? again, linq2db works again.
Is there a place where i should put a breakpoint in Linq2Db to find the error? 
Or do you already have an idea? Very strange that it fails so randomly.

### Environment details
linq2db version: 3.1.6
Database Server: SQL-SERVER

**Comment by sdanyliv** [comment]
@BenKmann,  I need more details. Model, defined mapping.

**Comment by BenKmann** [comment]
@sdanyliv I know i know. I found it was so random, that i have not much hope that we can reproduce it in a unittest. 
That's why i wanted to try to debug it myself, so maybe then i can tell you what is wrong.

In general, is mapping of a nullable bit Column to a not nullable bool property supported?

Model:
Contractclass with like 150 properties, which ALL have no attributes and 25 of them are bool fields.
Fluentmapping just sets their "HasColumnname".
LinkTable just has 2 Foreignkeys both have Contract-Table as the target.

I can try to reproduce it in a unittest. But i don't know how to simulate a nullable bit column in the db, which is mapped to a not nullable bool propertie in the unittests.

**Comment by BenKmann** [comment]
Ok i Implemented it like this, and for some reason it now works.
````c#
propertybuilder.HasDataType(DataType.Boolean).IsNullable(true);
````
My property is still not Nullable, but Setting "IsNullable" to true, definately fixed my queries!

````c#
private bool _ÜberregionalerVertrag;

[NotNull]
public bool ÜberregionalerVertrag
{
	get
	{
		return _ÜberregionalerVertrag;
	}
	set 
	{
		_ÜberregionalerVertrag = value;
	}
}
````

So i am Happy for the moment. Would have wished Linq2Db would throw an exception, if it can't create an entity.

**Comment by sdanyliv** [comment]
@BenKmann, it would be great to show small reproducible sample.

**Comment by BenKmann** [comment]
@sdanyliv it would love to. Can you give me a small example how to set unittest-column to nullabe bit?
The Example would be 25x bool Properties without Mapping and 25 db-Columns of Type (bit,null).
And a normal Foreign-Key. 
If you give me like a 3 row example, how to setup a unittest with a "bit, null" db-column, i will give my best to reproduce it.

````c#
private bool _ÜberregionalerVertrag;

[NotNull]
public bool ÜberregionalerVertrag
{
	get
	{
		return _ÜberregionalerVertrag;
	}
	set 
	{
		_ÜberregionalerVertrag = value;
	}
}
````

**Comment by MaceWindu** [comment]
@BenKmann, I've added tests https://github.com/linq2db/linq2db/pull/2881, but  looks like some details missing, as they pass right now. Feel free to add more details

**Comment by BenKmann** [comment]
@MaceWindu thank you very much for the example code.
Couldn't debug the code, my visual Studio builds succesfull and says test sussesfull (even when it is wrong). 
So i hope this code will reproduce it, i changed you're code a little. I am not exactly sure what you wanted to do with the Raw Classes and the not Raw Classes. I Worked with the Raw classes, because they have the nullable Bools.
The big change i made is, i moved the nullable bool Properties in the "TargetTable" (ContractRaw). Because Linq2Db has problems creating the TargetTable Entity (ContractRaw in this case).

````c#
#region Issue 2667
[Table("LinkedContracts", IsColumnAttributeRequired = false)]
public class LinkedContractsRaw
{
	public int   Id    { get; set; }
	public int   FK1   { get; set; }
	public int   FK2   { get; set; }

	[Association(ThisKey = nameof(FK1), OtherKey = nameof(ContractRaw.Id))]
	public ContractRaw? Ref1 { get; set; }

	[Association(ThisKey = nameof(FK2), OtherKey = nameof(ContractRaw.Id))]
	public ContractRaw? Ref2 { get; set; }

	public static readonly LinkedContractsRaw[] Data = new []
	{
		new LinkedContractsRaw() { Id = 11, FK1 = 1, FK2 = 2},
		new LinkedContractsRaw() { Id = 22, FK1 = 2, FK2 = 1}
	};
}

[Table("Contract", IsColumnAttributeRequired = false)]
public class ContractRaw
{
	public int   Id    { get; set; }
	public bool? Bit01 { get; set; }
	public bool? Bit02 { get; set; }
	public bool? Bit03 { get; set; }
	public bool? Bit04 { get; set; }
	public bool? Bit05 { get; set; }
	public bool? Bit06 { get; set; }
	public bool? Bit07 { get; set; }
	public bool? Bit08 { get; set; }
	public bool? Bit09 { get; set; }
	public bool? Bit10 { get; set; }
	public bool? Bit11 { get; set; }
	public bool? Bit12 { get; set; }
	public bool? Bit13 { get; set; }
	public bool? Bit14 { get; set; }
	public bool? Bit15 { get; set; }
	public bool? Bit16 { get; set; }
	public bool? Bit17 { get; set; }
	public bool? Bit18 { get; set; }
	public bool? Bit19 { get; set; }
	public bool? Bit20 { get; set; }
	public bool? Bit21 { get; set; }
	public bool? Bit22 { get; set; }
	public bool? Bit23 { get; set; }
	public bool? Bit24 { get; set; }
	public bool? Bit25 { get; set; }

	public static readonly ContractRaw[] Data = new []
	{
		new ContractRaw() { Id = 1 },
		new ContractRaw() { Id = 2 }
	};
}

[Table("LinkedContracts", IsColumnAttributeRequired = false)]
public class LinkedContracts
{
	public int Id { get; set; }

	public int FK1 { get; set; }

	public int FK2 { get; set; }
	
	[Association(ThisKey = nameof(FK1), OtherKey = nameof(Contract.Id))]
	public Contract? Ref1 { get; set; }

	[Association(ThisKey = nameof(FK2), OtherKey = nameof(Contract.Id))]
	public Contract? Ref2 { get; set; }

	public static readonly LinkedContracts[] Data = new []
	{
		new LinkedContracts() { Id = 11, FK1 = 1, FK2 = 2},
		new LinkedContracts() { Id = 22, FK1 = 2, FK2 = 1}
	};
}

[Table("Contract", IsColumnAttributeRequired = false)]
public class Contract
{
	public int Id { get; set; }
	public bool Bit01 { get; set; }
	public bool Bit02 { get; set; }
	public bool Bit03 { get; set; }
	public bool Bit04 { get; set; }
	public bool Bit05 { get; set; }
	public bool Bit06 { get; set; }
	public bool Bit07 { get; set; }
	public bool Bit08 { get; set; }
	public bool Bit09 { get; set; }
	public bool Bit10 { get; set; }
	public bool Bit11 { get; set; }
	public bool Bit12 { get; set; }
	public bool Bit13 { get; set; }
	public bool Bit14 { get; set; }
	public bool Bit15 { get; set; }
	public bool Bit16 { get; set; }
	public bool Bit17 { get; set; }
	public bool Bit18 { get; set; }
	public bool Bit19 { get; set; }
	public bool Bit20 { get; set; }
	public bool Bit21 { get; set; }
	public bool Bit22 { get; set; }
	public bool Bit23 { get; set; }
	public bool Bit24 { get; set; }
	public bool Bit25 { get; set; }

	public static readonly Contract[] Data = new []
	{
		new Contract() { Id = 1 },
		new Contract() { Id = 2 }
	};
}

[Test]
public void Issue2667Test1([IncludeDataSources(TestProvName.AllSqlServer)] string context)
{
	using (var db = GetDataContext(context))
	using (db.CreateLocalTable(ContractRaw.Data))
	using (var linkedContracts = db.CreateLocalTable(LinkedContractsRaw.Data))
	{
		var linkedContract = linkedContracts
		                     .LoadWith(linked => linked.Ref2)
		                     .Where(linked => linked.FK1 == 1)
		                     .ToList();

		// Both Asserts never Fail. Assert.IsNull(linkedContract[0].Ref2);
		Assert.IsNotNull(linkedContract[0].Ref2);
	}
}

[Test]
public void Issue2667Test2([IncludeDataSources(TestProvName.AllSqlServer)] string context)
{
	using (var db = GetDataContext(context))
	using (var linkedContracts = db.CreateLocalTable(LinkedContractsRaw.Data))
	using (db.CreateLocalTable(ContractRaw.Data))
	{
		var result = linkedContracts
			.Where(linked => linked.FK1 == 1)
			.Select(verträge => verträge.Ref2)
			.ToList();

		Assert.IsNotEmpty(result);
	}
}
#endregion
````

**Comment by MaceWindu** [comment]
Not sure if it is still actual, but looks like your Contract class Id is defined in code after boolean fields.

`Linq To DB` checks that referenced entity loaded by left join by checking first non-nullable field to contain non-null value and use nullable boolean column for that.

To fix it you can:
- WRONG: move Id property up
- Correct: annotate your boolean properties with `[Nullable]` attribute
