### ISSUE TITLE
Deleting rows

### ISSUE THREAD

**Issue by TwoUnderscorez** [linq2db/linq2db#2668]
Hi,
I'm trying to delete entries from a linq select with an orderby. How could I achieve that? The ideal situation would be to use the `DeleteWithOutputAsync` method on the linq expression. 
Would I need to use the AsCte? How? I keep getting a syntax error from the server when invoking `Delete`.

I'm currently using MySQL 5.7, but I can switch to 8 or to sqlserver 2019 if the problem is the DB not supporting something. 

Thanks!

**Comment by sdanyliv** [comment]
DeleteWirhoOutput is not supported for MySql.
Please post your LINQ query an desired SQL.

**Comment by TwoUnderscorez** [comment]
@sdanyliv I see. Perhaps you should consider throwing a `NotImolementedExcrption` instead of doing nothing. On which DBs `DeleteWithOutputAsync` is supported? 

The LINQ sometimes like this 
```csharp
var q = from record in table 
             where record.some_time <= DateTime.Now && ...
             orderby record.thing1 descending
              orderby record.thing2 ascending 
             orderby record.thing3 descending 
```
What is the best way to delete and return whatever that query selects?
Thanks for helping me!

**Comment by sdanyliv** [comment]
Does this query has any advantages without Skip? 
DeleteWithOutput supported only for SQL Server and it should be documented, its new functionality. We trying to implement things which are requested.

**Comment by sdanyliv** [comment]
Anyway, i need more details. Such functionality can be implemented via temporary tables, which are supported.

**Comment by TwoUnderscorez** [comment]
sdanyliv What more details do you need? I'll glad if you could provide a Delete example.

**Comment by sdanyliv** [comment]
Better to show real linq query and how many items should be deleted.

**Comment by sdanyliv** [comment]
If you do not use `Take`, order by is doing nothing fro delete.
Also every next `order by` replaces previous `order by`

For me it will make sense if you write something like that
```cs
var q = from record in table 
        where record.CreationTime <= DateTime.Now && record.DeliverTime <= DateTime.Now && record.Popped == false
        orderby record.Priority descending, DeliverOn ascending, record.CreatedOn descending
        select record;
var toDelete = q.Take(100);
toDelete.Delete();
```

**Comment by TwoUnderscorez** [comment]
That worked. Thanks!
