### ISSUE TITLE
skip\take problems with oracle in new versions

### ISSUE THREAD

**Issue by treschev** [linq2db/linq2db#2669]
H1!
We have a problems with lin2db library when using skip\take methods (latest versions).
when library builds expression (oracle query) - it increments variable name.

```c#
using LinqToDB;

query =  query.Skip( 100 ); // query - IQueryable<T>
```

transforms to Oracle query:
```
DECLARE @skip_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1 Int32
...
WHERE
			ROWNUM <= :skip_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1
```

and then query catch an exception like 'too long variable name'.

In prev version (<3) library build expression:
```
DECLARE @skip Int32
...
WHERE
			ROWNUM <= :skip
```

### Environment details
linq2db version: *3.0.1* >=
Database Server: *Oracle*
Database Provider: *OracleManagedDataAccess*
Operating system: *Windows*
.NET Framework: *4.7*

what can we do with that problem? Can u fix it?

**Comment by MaceWindu** [comment]
@sdanyliv  I told you :)
E.g. `SkipTake32` test https://github.com/linq2db/linq2db.baselines/blob/master/core21/Oracle.11.Managed/Tests/Linq/TakeSkipTests/Tests.Linq.TakeSkipTests.SkipTake32(Oracle.11.Managed%2CFalse).sql

**Comment by sdanyliv** [comment]
Yeah, I  have found this bug also. Will be fixed on the next release.

**Comment by sdanyliv** [comment]
@treschev, as a workaround try to set the following configuration value:
```cs
Common.Configuration.Linq.ParameterizeTakeSkip = false;
```

**Comment by treschev** [comment]
thx for ur answers!
we`ll try.
