### ISSUE TITLE
Nhibernate-like-interceptors?

### ISSUE THREAD

**Issue by Scratch-net** [linq2db/linq2db#267]
Hi There!

Is there any way to process values before they are put into DB and before they are taken back? 

For example encrypt/decrypt all strings or (my case) convert guids to sqlSortable and back

**Comment by jack128** [comment]
MappingScheme.SetConverter ??

**Comment by scratch-net** [comment]
@jack128 Nice one, but how do I determine in which direction the conversion occurs if it is <string, string> or <Guid, Guid>?

**Comment by scratch-net** [comment]
@igor-tkachev Could you please help?

I have a custom Guid struct type (with different byte order) and would like it to be processed transparently by Linq2db

I've added my type to schema mapping
```
                MappingSchema.Default.SetDataType(typeof(SortableGuid),  DataType.Guid);
                MappingSchema.Default.SetDataType(typeof(SortableGuid?), DataType.Guid);
```

and it seems to be working(insert-select at least). But It does not get wrapped into quotes when I do "Where"
Could you advise a proper way of adding a custom type?

**Comment by igor-tkachev** [comment]
Can I get an example? I do not quite understand what you are trying to do.

**Comment by Scratch-net** [comment]
@igor-tkachev 

An example model

```
public class User
{
    publiс string CreditCardNumber{get;set;}
}
```

And suppose I need CreditCardNumber to be stored encrypted in DB but work with it as it is not encrypted at all.

So, that when I do 
1) .Insert(), CreditCardNumber gets automatically encrypted with my code
2) .Where() automatically searches for encrypted values
3) Select returns objects that contain decrypted values.

Basically, all I need is 2 simple hooks which will be triggered when a field goes to DB(insert, where) and when it goes back (select)

So that I wouldn't have to write the encrypt/decrypt code every time I need to query or insert data

**Comment by sdanyliv** [comment]
@ili, do we have attrubute driven converters?

**Comment by jogibear9988** [comment]
no, see : https://github.com/igor-tkachev/bltoolkit/issues/243#issuecomment-21253805
