### ISSUE TITLE
linq2db.aspnet configuration

### ISSUE THREAD

**Issue by pavelvondrasek** [linq2db/linq2db#2671]
Hi,

I'm trying migrate my configurations to linq2db.aspnet and I use custom mapping schema convertors. Which options are there?

before:
```cs
MappingSchema.Default.SetConverter<string, JArray>(JsonConvert.DeserializeObject<JArray>);
```

```cs
services.AddLinqToDbContext<BrandCloudDb>((provider, options) =>
{
  var schema = new MappingSchema();
  schema.SetConverter<string, JArray>(JsonConvert.DeserializeObject<JArray>);

  options
    .UseSqlServer(Configuration.GetConnectionString("BcConnection"))
    .UseDefaultLogging(provider)
    .UseMappingSchema(schema);
});
```

Is there better solutions or is it right?

Thank you!

**Comment by sdanyliv** [comment]
It is right. Changing Default configuration is not good idea.

**Comment by pavelvondrasek** [comment]
So that you recommend me not use SetConverter and better and serialize/deserialize in application logic?

**Comment by sdanyliv** [comment]
No, I suggest to do not use SetConverter for global MappingSchema.

**Comment by pavelvondrasek** [comment]
What other options do I have? Because I only know SetConverters to update mapping.

**Comment by sdanyliv** [comment]
What is the problem? You have created new MappingSchena, defined converter. This is right way.

**Comment by pavelvondrasek** [comment]
Oh, sorry I'm tired :D I see now I thought that you're talking about second solution but you think `MappingSchema.Default`

**Comment by pavelvondrasek** [comment]
Btw before I found `UseMappingSchema` I tried to configure converters from my data connection but there is not setter for schema, will it possible in future to configure there?

**Comment by sdanyliv** [comment]
`DataConnection` has constructor overload which accepts `MappingSchema`. Also `DataConnection` has `AddMappingSchema` method.

**Comment by pavelvondrasek** [comment]
Ah cool 👍 ❤️ I think its best solution for me 🤔

**Comment by pavelvondrasek** [comment]
Thank you!

**Comment by sdanyliv** [comment]
Don’t forget to cache mapping schema. Otherwise you will slowdown your queries.
