### ISSUE TITLE
Lock contention during "LingToDB.Linq.QueryRunnerBase.SetCommand"

### ISSUE THREAD

**Issue by usenff-cu** [linq2db/linq2db#2677]
Hello linq2db-team,

we are currently investigating drops in our servers response-time when there are multiple (100+) parallel requests.

During our profiling-sessions we found out that most of the time is spent in "lock contention" during execution of "LingToDB.Linq.QueryRunnerBase.SetCommand"
![lockContention](https://user-images.githubusercontent.com/68424631/101358348-029f1b00-389b-11eb-958e-18deb97a7e5e.png)

During this time the database-connection-pool grows but doesn't reach its limit. The database itself is more or less idle. (CPU ~10-15%)

Do you have a hint for us which resources could cause the problem?

Kind regards,
Uwe

### Environment details
linq2db version: 3.0.1
Database Server: mysql 8.0.15
Operating system: Windows 10 Pro (profiling was done in development environment)
.NET Framework: .NET core 3.1

**Comment by sdanyliv** [comment]
Yes, we aware with this problem. And prepared PR for resolving this lock. Next version should have improvement in this area.

**Comment by usenff-cu** [comment]
Thank you for the quick reply. Is there an ETA for the next version? :-)

**Comment by sdanyliv** [comment]
About two weeks. A lot of work here.

**Comment by usenff-cu** [comment]
Ok, then I prepare reviewing this in ~2 weeks. Thank you!
