### ISSUE TITLE
InsertWithIdentity is not working for SEQUENCEs with [PrimaryKey, Identity] attribute on MS SQL Server 2012.

### ISSUE THREAD

**Issue by inickvel** [linq2db/linq2db#268]
May be better replace SCOPE_IDENTITY() with OUTPUT for all types, not only for GUIDs ?
SCOPE_IDENTITY also does not working with SEQUENCEs (MS SQL 2012).

http://www.sqlbadpractices.com/how-not-to-retrieve-identity-value/

**Comment by igor-tkachev** [comment]
Be my guest :)
