### ISSUE TITLE
SQLite sql generation issue?

### ISSUE THREAD

**Issue by Sherif-Ahmed** [linq2db/linq2db#2689]
I have this query
`_dataConnection.GetTable<TEntity>().Single(x => x.MyColumn == "xYz")`
which generates a wrong sql

````
--  SQLite.Classic SQLite
DECLARE @take  -- Int32
SET     @take = 2

SELECT
	[x].[Id],
	[x].[MyColumn]
FROM
	[TableName] [x]
WHERE
	[x].[MyColumn] = 'xYz'
LIMIT @take
````

Exception message:
Sequence contains no elements
Exception thrown: 'System.InvalidOperationException' in System.Linq.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll

### Environment details
linq2db version: 3.1.6
Database Provider: SQLite
Operating system: Windows 10 Pro for Workstations
.NET Framework: .NET Core 3.1

**Comment by MaceWindu** [comment]
Generated SQL is correct, see similar question #2557

You receive error, because there is no record that match `[x].[MyColumn] = 'xYz'` condition in your database. See exceptions section: https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=net-5.0

**Comment by MaceWindu** [comment]
Actually this could be a bug. I don't see where @take parameter is used.

**Comment by Sherif-Ahmed** [comment]
Yes I missed it ... I updated it right now.

There is a row in the database the contains 'xYz' in MyColumn
and .ToList() get all records

**Comment by MaceWindu** [comment]
Then you have more than one row like that. There should be exactly one row, not 0, not 2+, or Single will throw exception by contract

**Comment by Sherif-Ahmed** [comment]
Sorry ... it's my fault ... because of case sensitivity ... 
But is the == operator is case sensetive?

**Comment by MaceWindu** [comment]
String comparison behavior is database-specific and for sqlite it depends on collation:
https://www.sqlite.org/datatype3.html#assigning_collating_sequences_from_sql
```
2. If either operand is a column, then the collating function of that column is used with precedence to the left operand. For the purposes of the previous sentence, a column name preceded by one or more unary "+" operators and/or CAST operators is still considered a column name. 
```
This probably your case : `MyColumn` was created with NOCASE collation

**Comment by Sherif-Ahmed** [comment]
Yes that is the case exactly ... appreciate your time and effort

**Comment by MaceWindu** [comment]
If you need case-sensitive comparison, you can define custom comparison function:
```cs
[Sql.Expression("{0} COLLATE RTRIM = {1}", ServerSideOnly == true)]
public static bool Compare(string left, string right) => left == right;
```
or BINARY instead of RTRIM (sqlite doesn't have a lot of collations: https://www.sqlite.org/datatype3.html#collation)

**Comment by Piedone** [comment]
I stumbled upon this when getting an "Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'near "DECLARE": syntax error'.'" exception with a simple parameterized query (i.e. with a `Where()` using a variable). Every source I find tells that `DECLARE` is not supported by SQLite. Can you help me understand why the query in the opening post would work with SQLite?

**Comment by sdanyliv** [comment]
It is just debug SQL Output. Before real query we render SQL server’s DECLARE syntax. Actually to SQLite will be sent only query and binary parameters.

**Comment by Piedone** [comment]
Thank you for your very quick reply! It seems we're doing something wrong then. We're integrating linq2db into [Orchard Core](https://www.orchardcore.net/) and are [converting the query into an SQL string](https://github.com/Lombiq/Helpful-Libraries/blob/ab041c9e70d54f72b206252b9c9d76bc75ac5cef/Lombiq.HelpfulLibraries.LinqToDb/LinqToDbQueryExecutor.cs#L59) to then run through Orchard's existing DB connection.

I guess we shouldn't generate the SQL (which is actually just a debug output) but rather do something like `GetTable<MyClass>().Where(...).ToListAsync()` on the `LinqToDbConnection` instance?

**Comment by Piedone** [comment]
Yeah it seems so, this works: https://github.com/Lombiq/Helpful-Libraries/blob/eb957f470d313e5e1b735e67ecaf6943976dca5e/Lombiq.HelpfulLibraries.LinqToDb/LinqToDbQueryExecutor.cs#L54
