### ISSUE TITLE
Too aggressive query optimization

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#269]
Query like that:

```cs
db.Table1
    .Where(_ =>
        db.Table2
            .Where(r => r.Table1Id == _.Id)
            .OrderByDescending(r => r.SomeField)
            .Select(r => r.AssociationProperty.TextField)
            .First()
            .Contains(filterText))
```

Generates invalid subquery SQL without logic added by Select and Contains:

```sql
SELECT *
FROM Table1
WHERE
(
        SELECT TOP (1)
            *
        FROM
            Table2
        WHERE
            Table2.fk_id = table1.id
        ORDER BY
            Table2.SomeField DESC
)
```

Such query rejected by database engine (MSSQ) and miss join on association, text field selection and LIKE predicate

If you will need exact test-case to reproduce issue, I could provide it a bit later.

**Comment by MaceWindu** [comment]
Tried to rewrite query to:
```
db.Table1
    .Where(_ =>
        db.Table2
            .Where(r => r.Table1Id == _.Id)
            .OrderByDescending(r => r.SomeField)
            .Select(r => r.AssociationProperty.TextField.Contains(filterText))
            .First() == true)
```
the same problem.
Then to this:
```

db.Table1
    .Where(_ =>
        db.Table2
            .Where(r => r.Table1Id == _.Id)
            .OrderByDescending(r => r.SomeField)
            .Select(r => new { BoolProperty = r.AssociationProperty.TextField.Contains(filterText) })
            .First().BoolProperty == true)
```
This one failed with NotImplementedException from #266

**Comment by MaceWindu** [comment]
Changed query to this one:
```
db.Table1
    .Where(_ =>
        db.Table2
            .Where(r => r.Table1Id == _.Id)
            .OrderByDescending(r => r.SomeField)
            .Select(r => r.AssociationProperty.TextField)
            .Take(1)
            .Any(txt => txt.Contains(filterText))
            )
```
Generated SQL is valid but it does something else.
```
SELECT *
FROM Table1
WHERE
EXISTS(
        SELECT TOP (1)
            *
        FROM
            Table2 INNER JOIN Table2 -- join generated
        WHERE
            Table2.fk_id = table1.id
                AND Table2.TextField LIKE filter -- filter generated too, but in wrong place
        ORDER BY
            Table2.SomeField DESC
)
```
With this query WHERE will be evaluated to true if there is at least one record that pass filter, but it must be true only if *first* record passes filter

**Comment by MaceWindu** [comment]
Great, found working workaround:
```
db.Table1
    .Where(_ =>
        db.AssocTable.Where(a => a.Text.Contains(filterText)
            && a.Id = db.Table2
                .Where(r => r.Table1Id == _.Id)
                .OrderByDescending(r => r.SomeField)
                .Select(r => r.AssociationId) -- or AssociationProperty.Id if we need explicit join
                .First()))
```

**Comment by sdanyliv** [comment]
@MaceWindu, could you please rewrite this sample using TestData data model?

**Comment by MaceWindu** [comment]
Of course.

Test query

```
[DataContextSource]
public void Issue269(string context)
{
	using (var db = new TestDataConnection(context))
	using (db.BeginTransaction())
	{
		var result = db.Patient
			.Where(pat => db.Person
				.Where(per => per.ID == pat.PersonID)
				.OrderByDescending(per => per.FirstName)
				.Select(c => c.Patient.Diagnosis)
				.First()
				.Contains("with"))
			.ToArray();
	}
}
```

Generated SQL (invalid). Similar to one in defect but still different. Maybe because of different relations schema or due to changes in last two years (will try a bit more to reproduce same behavior using different tables).
```
SELECT
	[t1].[PersonID],
	[t1].[Diagnosis]
FROM
	[Patient] [t1]
WHERE
	1 = (
		SELECT TOP (1)
			*
		FROM
			[Person] [t2]
		WHERE
			[t2].[PersonID] = [t1].[PersonID]
		ORDER BY
			[t2].[FirstName] DESC
	)

```

Also commenting `First` call produce interesting results. Contains converted to comparison instead of LIKE:
```
SELECT
	[t1].[PersonID],
	[t1].[Diagnosis]
FROM
	[Patient] [t1]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[Person] [t3]
				LEFT JOIN [Patient] [t2] ON [t3].[PersonID] = [t2].[PersonID]
		WHERE
			[t3].[PersonID] = [t1].[PersonID] AND [t2].[Diagnosis] = N'with'
	)

```

**Comment by Lexey** [comment]
> Contains converted to comparison instead of LIKE:

It is a correct behaviour. Note that you are calling IEnumerableContains instead of String.Contains in this case.

**Comment by MaceWindu** [comment]
Hmm, you are right here

**Comment by MaceWindu** [comment]
Rewriting it like that produce proper SQL. I wonder why I didn't use it then - maybe it wasn't possible in real code...

```
[DataContextSource]
public void Issue269v2(string context)
{
	using (var db = new TestDataConnection(context))
	using (db.BeginTransaction())
	{
		var result = db.Patient
			.Where(pat => db.Person
				.Where(per => per.ID == pat.PersonID)
				.OrderByDescending(per => per.FirstName)
				.Select(c => c.Patient.Diagnosis)
				.Take(1)
				.Where(_ => _.Contains("with")).Any())
			.ToArray();
	}
}
```

**Comment by MaceWindu** [comment]
Short summary: looks like it is still possible to express your intentions (`Issue269v2`), but it is too easy to fail and in some cases you could even not notice it immediately (`Issue269v3`)

**Comment by sdanyliv** [comment]
@MaceWindu, what i learn from this issue: 
if you want good SQL - write linq queries but not linq method chain. It keeps common sense and you can early detect weakness of your query,

**Comment by MaceWindu** [comment]
@sdanyliv there are two problems with this approach:
1. I cannot stand linq syntax :-)
2. Specifics of our project require a lot of code generation where we cannot use linq syntax

**Comment by sdanyliv** [comment]
1. Maybe i have learn SQL before .NET, for me it is more explainable and really keeps you closer to SQL.
2. I'm choosing both techniques, but for SQL I'm trying to use linq queries, especially when group by or join are used.
