### ISSUE TITLE
Question: Are the Nullable/NotNull attributes still needed in C#8 with Nullable Reference Types?

### ISSUE THREAD

**Issue by R2D221** [linq2db/linq2db#2690]
I see that the Nullable and NotNull attributes are needed for marking class types (mainly string) where we previously had no way to know if they were meant to be nullable or not. But now in C#8, you can just set the type as `string?` and the compiler will mark it with a Nullable attribute.

So, my question is, is explicitly setting Nullable/NotNull still required for LinqToDb when using it in C# 8 or 9?

I tried looking in the documentation and the issues, but I couldn't find any relevant info.

**Comment by sdanyliv** [comment]
Nope, currently we do not respect reference types nullability. It needs some design.

**Comment by R2D221** [comment]
Thanks for the info

**Comment by jods4** [comment]
Do you think this will be in v4.0?
Since you worked on adding C# nullability to `Association`, it'd be nice if it was generalized to the complete model.
Features other than `Association` use nullability infos, e.g. `IsDistinctFrom` and all the `==` semantics emulation, they would benefit from this.

**Comment by IceReaper** [comment]
Joining in. We are using Nullable features for all our projects since quite a while. Just started to dig into linq2db as a slim alternative to entity framework core. However it seems a few things are off when it comes to null handling.

First adding Nullable or NotNull attributes to our poco class column properties is something which could be avoided.

Secondly i can get the app to crash when trying to register the following:
```csharp
connection.MappingSchema.SetConvertExpression<string, Version>(value => Version.Parse(value));
connection.MappingSchema.SetConvertExpression<string?, Version?>(value => value == null ? null : Version.Parse(value));
connection.MappingSchema.SetConvertExpression<Version, DataParameter>(value => new(null, value.ToString(), DataType.VarChar));
connection.MappingSchema.SetConvertExpression<Version?, DataParameter>(value => new(null, value == null ? null : value.ToString(), DataType.NVarChar));
```
Using a poco class which has both a nullable and a notnull version property. Additionally i cant imagine it being a good idea to implement both variants?

**Comment by jods4** [comment]
This would be quite nice to have.

I did a bit of research if someone wants to tackle implementation:

The idea is to add one extra rule when deciding if model is nullable:
- If there is an explicit `CanBeNull` property on `[Column]` it would of course be respected, as today.
This can easily be checked today, as `[Column]` already has an `HasCanBeNull()` method.
- New step: check if there are C# nullable annotations. 
This could be determined from compiler generated `[NullableContext]` and `[Nullable]` on type and property, but is a little too involved for my liking.
I rather suggest we rely on a new .NET 6 reflection API: `NullabilityInfoContext`, see https://github.com/dotnet/runtime/pull/54985
Note that the API returns correct nullability for value types such as `int?` vs `int` as well 👍 
Relying on this API means that inferring C# nullability is a .NET 6+ feature, which seems acceptable to me.
- Without `CanBeNull` nor C# nullability infos, references should be assumed nullable, like today.

Bonus point for applying the same logic to `[Association]`

**Comment by CodingOctocat** [comment]
Is default NOTNULL now supported (when <Nullable>enable</Nullable>)? 2024 doesn't seem to be supported in my testing.

**Comment by MaceWindu** [comment]
You need to enable it using `Configuration.UseNullableTypesMetadata = true` option
