### ISSUE TITLE
Don't client-side large objects [Possible 3.x regression]

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2691]
> **This might be a 3.x regression.** 
The code below was developed in 2.x and I'm 90% confident that it did what I want.
We recently noticed a serious perf regression and observed the (new?) behavior described here.

Take a model that maps a DB blob into a .net `byte[]`.
```c#
class File 
{
  public int Id { get; set; }
  public string Name { get; set; }
  public byte[] Data { get; set; }  // blob in DB
}
```

This query attempts to fetch the size of the first 20 records:
```c#
var q = from f in db.Files select new { f.Name, Length = f.Data.Length };
q.Take(20).ToList();
```

The SQL looks like this:
```sql
select Name, Data
from Files
where rownum <= 20
```

My gripe here is that linq2db fetches all of `Data` and chooses to evaluate `Data.Length` on the client-side.

Generally speaking, I love how linq2db evaluates as much as possible client-side. 
It gives access to all .net features that dbs don't have and the results are consistent with other c# code (there's always minor discrepancies in the implementation of "similar" functions). 

In this specific instance, I don't love it as much because `Data` is a heavy, costly object. Just imagine each blob is on average 5Mo. That query moves 100Mo over the network!!
It's especially nasty because it still "works". We noticed the problem after significant perf. degradation.

I would suggest that `byte[].Length` is special-cased to always be server-side evaluated.
I.e. above query should generate:
```sql
select Name, LENGTH(Data)
from Files
where rownum <= 20
```

Side note: I couldn't find a built-in `Sql.Length()` that takes `byte[]`, so working around this requires a bit of knowledge (I created my own length function).

### Environment details
linq2db version: 3.1.4
Database Server: Oracle 12 
Database Provider: Managed
Operating system: Windows 
.NET Framework: Core 2.1

**Comment by MaceWindu** [comment]
I cannot find byte.Length mapping, so I'm pretty sure it is not regression. Anyway, we need to add `Sql.Length` function for `byte[]` (we have it only for `Binary` for some reason) and map `byte[].Length`/`Binary.Length` to it.

**Comment by MaceWindu** [comment]
Actually we have mapping for `Binary.Length`, so only `byte[]` support is missing.

**Comment by jogibear9988** [comment]
@MaceWindu  
It's not so easy to fix....

Adding 


			{ M(() => ((byte[])null!).Length ), N(() => L<byte[],int>((byte[] obj) => Sql.Length(obj)!.Value)) },


to Expressions does not work.

I then get this Exception: (Of cause, I added the Function before to SQL Class)

![image](https://user-images.githubusercontent.com/364896/102274516-53aab100-3f24-11eb-9871-cbf5bac7a11c.png)

I'll look if i can fix :-)

**Comment by jogibear9988** [comment]
Problem is, get MemberInfo now get's a ArrayLength expression, but it has no meber..
I returned the meber "Length" of the array type did not work...
Maybe you @MaceWindu or @sdanyliv can take a quick look to guide me in the prefered direction...

https://github.com/linq2db/linq2db/pull/2699

**Comment by jogibear9988** [comment]
I think I also need to change the place where we search for the MemberExpressions in the dictionary, and create a special case for ArrayLength Expressions?
