### ISSUE TITLE
Memory leak in query cache and LoadWith

### ISSUE THREAD

**Issue by andrewvk** [linq2db/linq2db#2696]
When you call LoadWith with caching enabled, the memory consumption is constantly increasing.
![image](https://user-images.githubusercontent.com/803486/102187802-883b5000-3ec5-11eb-96e1-e68f56318900.png)
![image](https://user-images.githubusercontent.com/803486/102187831-92f5e500-3ec5-11eb-96ce-2649a33f8893.png)
It seems that the same query is pushed into the cache on every call
![image](https://user-images.githubusercontent.com/803486/102190539-38f71e80-3ec9-11eb-9110-753749f626fe.png)

### Environment details
linq2db version: *2.9.8*
Database Server: *PostgreSQL*
Operating system: *Debian 10*
.NET Framework: *Core 3.1*

**Comment by sdanyliv** [comment]
Maybe some query sample?

**Comment by MaceWindu** [comment]
@sdanyliv #2670 removed dictionary from CompiledTable, so it could be fixed already.

**Comment by andrewvk** [comment]
Yet another screenshot
![image](https://user-images.githubusercontent.com/803486/102191063-f41fb780-3ec9-11eb-96ae-23f488a6f274.png)

**Comment by sdanyliv** [comment]
I do not need that nice screenshots, but query which fails.

**Comment by MaceWindu** [comment]
@andrewvk could you inspect CompiledTable dictionary cache keys - could you see why there are so many entries (why cache entries not reused?)

**Comment by andrewvk** [comment]
Probably a problematic request.
![image](https://user-images.githubusercontent.com/803486/102191974-3269a680-3ecb-11eb-8d77-dfe7764c43b0.png)

**Comment by sdanyliv** [comment]
@andrewvk, you have not prepared reproducible steps. 
Your stack trace shows that you have used `CompiledQuery` but sample screenshot not related to that.
I have prepared small tests on my side with both variants. All works as expected.

If you want fix to be ready for upcoming release planned this `Thursday`, be more informative.

Anyway, probably you have created new `MappingSchema` for every `DataConnection` and missed query cache.

**Comment by sdanyliv** [comment]
@andrewvk, any news with that? If guys don't know English, they can create post in RSDN.
Anyway, I think that they have problem with `MappingSchema` which should be cached somehow.

**Comment by MaceWindu** [comment]
We addressed some memory issues here #2971

You can try recent preview https://dev.azure.com/linq2db/linq2db/_packaging?_a=package&feed=linq2db%40Local&package=linq2db&protocolType=NuGet&version=3.3.1-rc.5794
