### ISSUE TITLE
An incorrect query is generated when using a TVP to insert data (`INSERT INTO ... SELECT ... FROM @Table`)

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#2700]
Linq2DB generates incorrect query when a table value parameter is used to insert records in the database.

### Steps to reproduce

```c#
var recordList = new List<DataModel>();

// ...

static void Test()
{
    var parameter = new DataParameter("table", ToDataRecords(recordList), DataType.Structured, "dbo.MemoryOptimizedTableType");
    
    db.FromSql<DataModel>($"{parameter}")
        .Select(item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name,
        })
        .Into(db.DestTable)
        .Insert();
}

// ...

static IEnumerable<SqlDataRecord> ToDataRecords(IEnumerable<DataModel> list)
{
    // ...
}
```

Generated query:

```SQL
INSERT INTO [dbo].[DestTable] DEFAULT VALUES
SELECT
	*
FROM
	@table_1 [item]
```

### Environment details
linq2db version: 3.1.6
Database Server: SQL Server 2019
Database Provider: Microsoft.Data.SqlClient
Operating system: Windows Server 2019
.NET Framework: .NET Core 3.1

**Comment by JechoJekov** [comment]
Tried with CTE but no luck :-)

```
    db.FromSql<DataModel>($"{parameter}")
        .Select(item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name,
        })
        .AsCte()
        .Select(item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name,
        })
        .Into(db.DestTable)
        .Insert();
```

```SQL
WITH [CTE_1] AS
(
	SELECT
		*
	FROM
		@table_1 [item]
)
INSERT INTO [raw].[AdRawData] DEFAULT VALUES
SELECT
	*
FROM
	[CTE_1] [item_1]
```

**Comment by viceroypenguin** [comment]
Slightly different tack that might help you:
```csharp
db.DestTable
  .Merge().Using(ToDataRecords(recordList))
  .On((dst, src) => 1 == 0)
  .InsertWhenNotMatched(src => new DestTable() {...})
  .Merge();
```

**Comment by MaceWindu** [comment]
Must be bug, we don't have TVP tests for insert (except using merge, so merge one should work).

**Comment by MaceWindu** [comment]
Could you try to annotate DataModel class with table/column attributes?

**Comment by JechoJekov** [comment]
@MaceWindu Added `[Table(...)]` attribute and `[Column(...)]` attributes to `DataModel` - the generated SQL is the same.

I am aware about `MERGE`, however, I want to use it with `INSERT`, `UPDATE`, joins, etc. Have not tested joins or `UPDATE` yet.

**Comment by sdanyliv** [comment]
You have to rewrite your query. This syntax requires providing which fields to insert.
```cs
db.FromSql<DataModel>($"{parameter}")
        .Select(item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name,
        })
        .AsCte()
        .Into(db.DestTable)
             .Value(t => t.Id, item => item.Id)
             .Value(t => t.Name, item => iitem.Id)
        .Insert();
```
Also you can use the following syntax
```cs
db.FromSql<DataModel>($"{parameter}")
        .Select(item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name,
        })
        .AsCte()
        .Insert(db.DestTable, item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name,
        });
```

**Comment by sdanyliv** [comment]
@MaceWindu, I think we have to throw informative extension that no `Value` calls were made. 
But maybe we can handle this case automatically.

**Comment by JechoJekov** [comment]
@sdanyliv I had an issue with `.AsCte()` since I have a column which is not stored directly in the DB but is transformed by using `Sql.Expression`. For some reason it was added at the end of the select list which resulted in more columns in the select than in the insert statement:

```C#
[Sql.Expression(
    ProviderName.SqlServer2017,
    "Compress(Cast({0} as varchar(max)))",
    CanBeNull = true,
    IsNullable = Sql.IsNullableType.IfAnyParameterNullable,
    ServerSideOnly = true
    )]
public static byte[] Compress(this string _)
{
    throw new NotSupportedException();
}
```

```C#
db.FromSql<DataModel>($"{parameter}")
        .AsCte()
        .Insert(db.DestTable, item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name.Compress(),
        });
```

```SQL
WITH [CTE_1]
(
	[Id],
	[Name]
)
AS
(
	SELECT
		[t1].[Id],
		[t1].[Name]
	FROM
		@table_1 [t1]
)
INSERT INTO [dbo].[DestTable]
(
	[Id],
	[Name]
)
SELECT
	[t2].[Id],
	Compress(Cast([t2].[Name] as varchar(max))),
	[t2].[Name]
FROM
	[CTE_1] [t2]
```

Without CTE it worked perfectly 👍

```C#
db.FromSql<DataModel>($"{parameter}")
        .Insert(db.DestTable, item => new DestTable()
        {
            Id = item.Id,
            Name = item.Name.Compress(),
        });
```

```SQL
INSERT INTO [dbo].[DestTable]
(
	[Id],
	[Name]
)
SELECT
	[item].[Id],
	Compress(Cast([item].[Name] as varchar(max)))
FROM
	@table_1 [item]
```

**Comment by JechoJekov** [comment]
@sdanyliv @MaceWindu 

There does not seem to be a way to use the same approach to update records if there is a need to have a `WHERE` clause. The

```C#
Task<int> UpdateAsync<TSource, TTarget>(this IQueryable<TSource> source, ITable<TTarget> target, [InstantHandleAttribute] Expression<Func<TSource, TTarget>> setter, CancellationToken token = default);
``` 

method does not accept a predicate expression.

I am aware that `MERGE` can be used, however, `MERGE` have some issues on SQL Server (including performance) so I prefer to avoid it.

**Comment by JechoJekov** [comment]
@sdanyliv  @MaceWindu 

To answer my own question - one way to do this is by using inner join:

```C#
await db.MyTable
    .InnerJoin(db.FromSql<DataModel>($"{parameter}"), (record, param) => record.Id = param.Id, (record, param) => new { Record = record, Param = param })
    .UpdateAsync(
        db.MyTable,
        item => new MyTable()
        {
            Column1 = item.Param.Column1
            // ...
        }
    );
```

**Comment by Corey-M** [comment]
This appears to be the same problem I'm having trying to add an `INTO` clause to a query. The query produces all of the right fields in the right order for the `INTO` clause, but because I don't use `.Value(...)` for each field I get `INSERT INTO [target] DEFAULT VALUES...` as my generated query.

I have 16 fields in this particular query. Adding each of them via `.Value(...)` would be tiresome when I've already constructed the record.

When `.Insert<TSource, TTarget>(...)` is called where `TSource` and `TTarget` are the same... can we just omit the `DEFAULT VALUES` please?
