### ISSUE TITLE
sql query generated using nvarchar instead varchar

### ISSUE THREAD

**Issue by cfuentealba** [linq2db/linq2db#271]
We have sql server database where target table has float and varchar fields as PK, with its indexes...
When we query the table the sql statement generated by linq2db uses nvarchar comparison instead of varchar which causes serious performance issues as it does not use existing indexes.

example:
```sql
select * from dbo.table t
where t.field2_varchar=N'value' and
t.field2_varchar2= N'value2' and
t.field3_float=value 
```
Is there a way to force the query generation to use varchar comparison like this?
```sql
select * from dbo.table t
where t.field2_varchar='value' and
t.field2_varchar2= 'value2' and
t.field3_float=value
```

**Comment by MaceWindu** [comment]
Explicit type specification for such fields should help:
[Column(DataType = DataType.Char)]

**Comment by sdanyliv** [comment]
@cfuentealba, proposed solution helped?
