### ISSUE TITLE
linq2db oracle 

### ISSUE THREAD

**Issue by myabdolmaleki** [linq2db/linq2db#2717]
hi

i hope you are doing great!
i have issue in linq2db and oracle database.

linq2db generates oracle objects in .net based on owned objects like views, tables and ....

i have another user(schema) with insert,update,delete,select access that is **not owner of table** in oracle, but it not generate its model and properties in .net.

**Comment by MaceWindu** [comment]
Yes, by default we generate objects only for current schema. To add other schemas you need tospecify them explicitly using:
```cs
GetSchemaOptions.IncludedSchemas
GetSchemaOptions.IncludedCatalogs
``
options

https://linq2db.github.io/articles/T4.html
