### ISSUE TITLE
Extend InsertOrUpdate method

### ISSUE THREAD

**Issue by VitaliyNec** [linq2db/linq2db#2721]
When I used the "InsertOrUpdate" it is necessary getting the created record id  in some cases.
 Could you add an extended method for getting this data?

### Environment details
linq2db version: 3.2.1
Database Server: PostgreSQL 12.1
Database Provider: Npgsql 4.1.4
Operating system: Windows 10
.NET Framework: .Net 5

**Comment by MaceWindu** [comment]
It's already in our plans (#2558) but will take some time to implement.

**Comment by VitaliyNec** [comment]
I'm waiting this changing. Thank you for your answer.
