### ISSUE TITLE
Oracle: BUG with SequenceNameAttribute.Schema and DontEscapeLowercaseIdentifiers

### ISSUE THREAD

**Issue by AK107** [linq2db/linq2db#2722]
По факту сломалась вставка везде, где используются сиквенсы.

Т.к. Schema в SequenceNameAttribute  для Oracle никогда не работала, то название схемы всегда приходилось вписывать как часть SequenceName, например, "user.sq_product".

В связи с этим Oracle11SqlBuilder.IsValidIdentifier говорит, что идентификатор неверный и далее его весь пытаются заключить в кавычки. От этого запрос получается неверный, вне зависимости от DontEscapeLowercaseIdentifiers.

например для:
[SequenceName("user.sq_product")]
сгенерится
insert into ... values (**"user.sq_product"**.nextval,...)

для:
[SequenceName("sq_product", Schema = "user")]
сгенерится
insert into ... values (sq_product.nextval,...)
т.е. синтаксически верный, но схему не добавили - запрос не работает.

Решение: добавить обработку Schema у SequenceNameAttribute  для Oracle.

з.ы. вообще, конечно, идея сделать DontEscapeLowercaseIdentifiers = false по умолчанию весьма странная, особенно если учесть, что придется выверять написания все таблиц/колонок/сиквенсов/etc по всей БД - а это только схем сотни!

**Comment by MaceWindu** [comment]
Позволю себе не согласиться. Идентификаторы должны быть валидными и мы не должны поощрять обратное. К сожалению ранний linq2db добавил достаточно таких "хаков" и их вырезание иногда болезненным получается. А вот со схемой да, прощелкали...

**Comment by MaceWindu** [comment]
English description for issue:

`SequenceNameAttribute` ignores `Schema` property value when generates sequence name in SQL for Oracle right now. This in combination with 3.2.0 change to sequence name escaping (now identifier escaping logic applied to sequences too) breaks old workaround with placing sequence schema name into sequence name: `[SequenceName("schema.sequence")]`

Fix will respect `Schema` property, so example above should work with following code:
```cs
[SequenceName("sequence", Schema = "schema")]
```

**Comment by AK107** [comment]
> Идентификаторы должны быть валидными и мы не должны поощрять обратное

так они и валидные согласно sql. кавычки нужны для уточнения регистра. зачем принудительно их загонять в такой режим я не понимаю. но я бы и не поднимал сей вопрос, если бы в комментах к этому свойству не  было сказано, что оно вообще будет выпилено в будущем и это поведение станет по-умолчанию.

мой поинт в том, что sql - язык регистронезависимый, зачем принудительно обратное - непонятно.

я еще раз поясню проблему: представьте себе стандарную большую БД с сотней схем и десятками таблиц/сиквенсов/колонок в каждой. потенциально там можно быть в любом месте задано нерадивым программистом имя с регистром. в обычном случае это проблема самого оракула и он прекрасно разрешает эти неоднозначности. иначе - это все найти не представляется возможным. а главное проблемы будут вылезать исключительно в рантайме.

**Comment by MaceWindu** [comment]
Ну у нас подход такой: пользователь задает в мапинге чистое имя и мы в зависимости от базы его эскейпим.

Для пары провайдеров (oracle, firebird из того что сейчас помню) были когда-то добавлены флаги (и их убирать не планируется) на отключение эскейпинга, но это было сделано больше для того чтобы обойти баги в реализации самого эскейпинга. Как и всякие проверки типа если идентификатор содержит кавычку - мы считаем что он заэскейплен и его не трогаем. Я это потиху вычищаю, так как это рассадник багов.

Я не в курсе как там Оракл что разруливает, может и есть какие флаги, но 
```sql
SELECT * FROM "alltypes" at2
```
или
```sql
SELECT * FROM AllTypes at2
```
вместо
```sql
SELECT * FROM "AllTypes" at2
```
Дает ожидаемый `ORA-00942: table or view does not exist`

А регистронезависимость SQL это условно. В том же SQL Server можно себе приключений добавить поменяв collation на регистрозависимый

**Comment by AK107** [comment]
> 
> ```sql
> SELECT * FROM "alltypes" at2
> ```
> 
> или
> 
> ```sql
> SELECT * FROM AllTypes at2
> ```
> 
> вместо
> 
> ```sql
> SELECT * FROM "AllTypes" at2
> ```
> 
> Дает ожидаемый `ORA-00942: table or view does not exist`


если речь про [https://docs.oracle.com/cd/B28359_01/server.111/b28320/statviews_2112.htm](url)
то все наоборот

 ```sql
SELECT * FROM All_Types at2
```
работает как надо (в любом регистрк), а

 ```sql
SELECT * FROM "All_Types" at2 
```
уже дает ORA-00942.

все равно не понял вашу мысль про "чистое имя" и "эскейпим в зависимости от базы". экскейпить нужно только то, что нуждается в этом, а не все подряд :hz:

но, если не планируется выпиливать свойство OracleTools.DontEscapeLowercaseIdentifiers, то уже неплохо.

**Comment by MaceWindu** [comment]
Речь о таблице с именем AllTypes (в таком регистре) из наших тестов.

Чистое имя - реальный идентификатор объекта без ошибок в регистре и дополнительных преобразований типа экранирования. Или другими словами - имя, записанное в метаданных (в тех же schema views).

Для [ALL_TYPES](https://docs.oracle.com/cd/B28359_01/server.111/b28320/statviews_2112.htm) это ALL_TYPES, для нашей таблицы "AllTypes" это AllTypes.

И нам не надо угадывать что имел ввиду пользователь - мы просто применяем экранирование к идентификатору. Т.е. экранирование это наша задача (и через те же `DontEscapeLowercaseIdentifiers` мы это позволяем иногда отключать)

А то что у оракла идентификаторы без экранирования переводятся в upper case не значит что это так для всех:
- postgresql, informix приводит такие имена к нижнему регистру
- sqlite, sybase ase, sql server, sqlce используют имена as-is и регистро-независимый матчинг по умолчанию. Т.е. таблица AllTypes будет записана в метаданных как AllTypes но обращаться к ней можно и как alltypes и как AllTypeS
- в mysql вообще поведение от типа базы и файловой системы зависит
