### ISSUE TITLE
There is already an open DataReader associated with this Command which must be closed first.

### ISSUE THREAD

**Issue by rex-pj** [linq2db/linq2db#2738]
Hi,
I am using ASP.NET 5.0 and Linq2Db 3.2.1 for my API.
I use SQL Server
I am following this guide [https://linq2db.github.io/articles/get-started/asp-dotnet-core/index.html](https://linq2db.github.io/articles/get-started/asp-dotnet-core/index.html)
I also use **services.AddLinqToDbContext** to register my **DataConnection** with the **ServiceLifetime** is **Scoped**.

And I got this error when I send 2 requests in the same time.
"**_There is already an open DataReader associated with this Command which must be closed first._**"

I think change the ServiceLifetime to Transient is not the good practices.
Do you have any ways else or guide doc to solve this issue?
Thank you!

For more detail:
```
fail: LinqToDB.Data.DataConnection[0]
      Error
      Exception: System.InvalidOperationException
      Message  : There is already an open DataReader associated with this Command which must be closed first.
         at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
```

**Comment by sdanyliv** [comment]
> And I got this error when I send 2 requests in the same time.
"There is already an open DataReader associated with this Command which must be closed first."

You cannot sent two request simultaneously using the same `DataConnection`. Create new one or await for previous task completion.

**Comment by MaceWindu** [comment]
> You cannot send two request simultaneously using the same `DataConnection`. Create new one or await for previous task completion.

@rex-pj, FYI, we will allow this scenario soon with #2728, but for sqlserver it will require MARS enabled for connection.

**Comment by rex-pj** [comment]
Hi @sdanyliv,
Thanks for you response, I am using GraphQL to makes requests to my API, in GraphQL we can merge requests into a single request so I got issue by these scenarios.

**Comment by rex-pj** [comment]
Hi @MaceWindu,
I am already enabled MARS by adding MultipleActiveResultSets in my connection string, is it right?
![image](https://user-images.githubusercontent.com/16367896/103150775-c7ad4a80-47a9-11eb-8a3f-52716e212bdc.png)

**Comment by MaceWindu** [comment]
yep, but you need to wait for  #2728 to make it work with linq2db

**Comment by sdanyliv** [comment]
> GraphQL we can merge requests into a single request so I got issue by these scenarios.

How you merge that? And which library do you use?

**Comment by rex-pj** [comment]
Hi @sdanyliv,
GraphQL is query over API schema, not query over database, so it only merges the HTTP requests, not database requests :)
It's the feature of GraphQL, not related to any frameworks.
But more precisely, I use Hot Chocolate for the GraphQL server and Apollo for the Client side.
You can look at some examples queries here:
https://github.com/rex-pj/caminoSocial/blob/feature/update_content/src/clientApp/src/utils/GraphQLQueries/queries.js

**Comment by sdanyliv** [comment]
So, it is strange that two requests have not opened two DataConnections.

**Comment by rex-pj** [comment]
Hi @sdanyliv,
Because I registered my DataConnection with the ServiceLifetime as Scoped, I am not use the "using" pattern because it's hard to do mock test.

I don't know if I change the DataConnection to the DataContext, is it difference?

**Comment by sdanyliv** [comment]
As I know each request creates scope which equals to creating new DataConnection. Probably problem in you controller, for example missed `await`, or you have written something like this:
```cs
var query1 = ...;
var query2 = ...;

var tasks = new List<Task>{ query1.ToListAsync(), query2.ToListAsync() };

await Task.WhenAll(tasks);
```

**Comment by rex-pj** [comment]
Hi @sdanyliv,
Yes, but I used to merge the HTTP requests into a single request by using GraphQL. So only one scope was created.

**Comment by sdanyliv** [comment]
> Yes, but I used to merge the HTTP requests into a single request by using GraphQL. So only one scope was created.

How it can be? This is not .NET library and it cannot create request without omitting full HTTP request path, including create scope.

**Comment by MaceWindu** [comment]
Looked into it again. Not familiar with Hot Chocolate, but from your schema it looks like `ServiceLifetime.Scoped`  scope, used by `AddLinqToDbContext` will not work here as it register context on `HttpRequest` level, but after that Hot Chocolate execute parallel evaludation of queries and this is not something that will work even with MARS enabled: database connection is not thread-safe. You should register db context scoped to `Hot Chocolate`'s sub-query level (not sure how they name it). E.g. check here https://chillicream.com/docs/hotchocolate/integrations/entity-framework/ that context is registered on `Field`(?) level.

![image](https://user-images.githubusercontent.com/1099238/109512740-b253e580-7aa4-11eb-91e9-eef1596333b0.png)

**Comment by juniorjoe567** [comment]
> `ghvhbj`

**Comment by turkerurganci** [comment]
> As I know each request creates scope which equals to creating new DataConnection. Probably problem in you controller, for example missed `await`, or you have written something like this:
> 
> ```cs
> var query1 = ...;
> var query2 = ...;
> 
> var tasks = new List<Task>{ query1.ToListAsync(), query2.ToListAsync() };
> 
> await Task.WhenAll(tasks);
> ```

Can't we use like this?

**Comment by sdanyliv** [comment]
@turkerurganci, no. `DataConnection` is not thread safe.

**Comment by turkerurganci** [comment]
> @turkerurganci, no. `DataConnection` is not thread safe.

I have new dataconnection each time when queryMethod1Async.

But I am getting same error when the code is like below. Can you help me about what is the problem? 

using(var tran = new System.Transactions.TransactionScope())
{
    var tasks = new List<Task>();

    tasks.Add(queryMethod1Async());
    tasks.Add(queryMethod2Async());
    tasks.Add(queryMethod3Async());

    await Task.WhenAll(tasks);

    tran.Complete();
}

I

**Comment by sdanyliv** [comment]
You cannot create tasks and execute them in parallel using the same `DatatConnection`. I cannot help here, create new `DataConnection` for each task.

**Comment by turkerurganci** [comment]
> Show me `queryMethod1Async` and try remove Transaction scope.

queryMethod1Async like below

using (SqlConnection connection = new SqlConnection(connectionString)) 
{    
    int employeeID = findEmployeeID();    
    try    
    {
        connection.Open();
        SqlCommand command = new SqlCommand("UpdateEmployeeTable", connection);
        command.CommandType = CommandType.StoredProcedure;
        command.Parameters.Add(new SqlParameter("@EmployeeID", employeeID));

        command.ExecuteNonQuery();    
    } 
    catch (Exception) 
    { 
        /*Handle error*/ 
    }
}



If I remove transactionscope it is working but I need transactionscope because of my business logic

**Comment by sdanyliv** [comment]
Well, then it is limitation of `SqlConnection`. TransactionScope over different `SqlConnections` should initiate Distributed Trasnasction, not sure that you have proper system configuration for that like Distributed Transaction Cordinator etc.

So, better do not execute parallel tasks for TransactionScope.

**Comment by viceroypenguin** [comment]
@turkerurganci The transaction is inherited by the async-context, which means that running on multiple tasks will not automatically inherit the transaction. Further, using a transaction like that will require using MSDTC, which is a more complicated process. You will have to set up your servers and clients to support MSDTC, which further is only supported on Windows, I believe. Better to not try to parallelize these activities.

**Comment by turkerurganci** [comment]
@sdanyliv , @viceroypenguin 

I set up my server and client to support MSDTC and it worked successfully! 

The parallel execution approach has significantly improved performance; however, I have reservations about leveraging MSDTC due to potential complexities.

If you have any knowledge about the disadvantages of MSDTC, could you share it with me please? What kind of issues might I encounter?

**Comment by viceroypenguin** [comment]
* Lack of general knowledge about MSDTC
* Limited to Windows and MSSQL
* Easy to fail creating a DTC transaction
* Difficulties running multiple DTC transactions simultaneously

**Comment by sdanyliv** [comment]
> The parallel execution approach has significantly improved performance

You can sppedup it by sending all required data to temporary table and then process records by the SQL, even by LOOP.
