### ISSUE TITLE
x64 linq2db.SQLite issue

### ISSUE THREAD

**Issue by CotocVictor** [linq2db/linq2db#2747]
Hi Guys,

I have a .net Framework 4.8 WPF solution.
If I keep Preffered 32 bit works fine once I remove the option or I change the platform to x64 throws below exception.
I tried to load System.Data.SQLite.x64 manually but the result is the same.

Thank you,

Victor
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot load assembly System.Data.SQLite
  Source=linq2db
  StackTrace:
   at LinqToDB.DataProvider.SQLite.SQLiteProviderAdapter.CreateAdapter(String assemblyName, String clientNamespace, String prefix)
   at LinqToDB.DataProvider.SQLite.SQLiteProviderAdapter.GetInstance(String name)
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider..ctor(String name, MappingSchema mappingSchema)
   at LinqToDB.DataProvider.SQLite.SQLiteTools.<>c.<.cctor>b__21_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LinqToDB.Data.DataConnection.ConfigurationInfo.GetDataProvider(IConnectionStringSettings css, String connectionString)
   at LinqToDB.Data.DataConnection.ConfigurationInfo.get_DataProvider()
   at LinqToDB.Data.DataConnection..ctor(LinqToDbConnectionOptions options)
   at LinqToDB.Data.DataConnection..ctor(String configurationString)
   at WpfApp2.RFIDInventorySQLite..ctor() in C:\Users\Victor Cotoc\source\repos\WpfApp2\Class1.cs:line 8
   at WpfApp2.MainWindow..ctor() in C:\Users\Victor Cotoc\source\repos\WpfApp2\MainWindow.xaml.cs:line 27

  This exception was originally thrown at this call stack:
    [External Code]
    WpfApp2.RFIDInventorySQLite.RFIDInventorySQLite() in Class1.cs
    WpfApp2.MainWindow.MainWindow() in MainWindow.xaml.cs
```

**Comment by MaceWindu** [comment]
Could you provide more details on project type and referenced nugets?
I wasn't able to reproduce issue with following project:
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <!--<PlatformTarget>AnyCPU</PlatformTarget>-->
    <!--<PlatformTarget>x86</PlatformTarget>-->
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="3.2.2" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.113.7" />
  </ItemGroup>

</Project>


```

**Comment by CotocVictor** [comment]
Hi Mace,

Thank you for your quick answer !

It is a WPF .net framework 4.8 solution.
Please see below.
`
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{0B6D86AD-F104-4015-8E8D-8ED6C7565347}</ProjectGuid>
    <OutputType>WinExe</OutputType>
    <RootNamespace>WpfApp2</RootNamespace>
    <AssemblyName>WpfApp2</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <WarningLevel>4</WarningLevel>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <TargetFrameworkProfile />
  </PropertyGroup>
...
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
...
<ItemGroup>
    <PackageReference Include="linq2db">
      <Version>3.2.2</Version>
    </PackageReference>
    <PackageReference Include="linq2db.SQLite">
      <Version>3.2.2</Version>
    </PackageReference>
  </ItemGroup>`

**Comment by MaceWindu** [comment]
That's strange. I cannot reproduce it still.

Do you have any other nugets referenced?

You could try to clean nuget cache and see if it helped
![image](https://user-images.githubusercontent.com/1099238/103416295-4cbba980-4b86-11eb-81aa-fda17a9ad60e.png)

**Comment by CotocVictor** [comment]
Hi Mace,

Did you create a WPF Core solution and after that you've changed the TargetFramework to 4.8 correct ?
I did a WPF Core and that works fine x32 or x64.
If I do a WPF Framework works x32 only.

FYI: I'm using VS2019 Professional.
![image](https://user-images.githubusercontent.com/19874775/103416547-893bd500-4b87-11eb-88ea-f8564cef5b75.png)

Thank you,

Regards,

**Comment by MaceWindu** [comment]
No, I've created .net framework solution for second try. both .net framework and core worked for me

**Comment by CotocVictor** [comment]
Hi, 

I have no other nugets referenced into my .Net Framework project.
I don't know the reasons but probably it is something related to my environment.
I will try to use the .Net Core solution.

Thank you very much !

Regards,

Victor

**Comment by jogibear9988** [comment]
didn‘t he miss a ref. to sytem.data.sqlite

**Comment by MaceWindu** [comment]
This could be caused by some incompatibility between sqlite nuget and legacy (.net framework) project, but I'm not sure why it still works for me.

If CSP project works for you, I would recommend to use it in this case.

**Comment by MaceWindu** [comment]
>> didn‘t he miss a ref. to sytem.data.sqlite

`linq2db.sqlite` references `sytem.data.sqlite.core` nuget

**Comment by CotocVictor** [comment]
Hi, I tried to add system.data.sqlite, system.data.sqlite.x64.
The situation is the same.

**Comment by CotocVictor** [comment]
Hi Mace,

I reinstalled VS 2019 and that solved the issue.
I will close now this thread.

Thank you !

Regards,

Victor Cotoc
