### ISSUE TITLE
key.t.table.ForeignKeys.Add

### ISSUE THREAD

**Issue by nbraval** [linq2db/linq2db#2752]
Describe your issue.

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB.Templates/DataModel.ttinclude
line 247 249 
		key.t.table.ForeignKeys.Add(
			key.k.OtherTable.IsDefaultSchema ? key.KeyName : key.k.OtherTable.SchemaName + "." + key.KeyName,
			key.key);

### Steps to reproduce
Postgress database table having same  foreign key name throwing error/failing at above line

### Environment details
linq2db version: 3.2.2
Database Server: Postgress 11.6
Database Provider: Postgress
Operating system: windows
.NET Framework: 3.1

**Comment by MaceWindu** [comment]
Could you clarify what you mean by `same foreign key name` ? same as what?

**Comment by MaceWindu** [comment]
Reproduced. Failure occurs when table referenced by two or more foreign keys with same name.
