### ISSUE TITLE
Error when installing linq2db.SQLite

### ISSUE THREAD

**Issue by mpbill** [linq2db/linq2db#276]
when I try to use NuGet to install linq2db.SQLite i get the following error:
```
Error		Could not find file 'C:\Users\Michael\.nuget\packages\linq2db.t4models\1.0.7.1\content\LinqToDB.Templates\%21ReadMe.LinqToDB.md'.			0
```

this error occurs no matter what version I try to install.

**Comment by igor-tkachev** [comment]
Fixed. Please use the latest nuget.
