### ISSUE TITLE
Linq2db do not supports inserting a graph of objects.

### ISSUE THREAD

**Issue by sanjuroo** [linq2db/linq2db#2761]
Is this still not supported? If not, how are this type of inserts typically solved using linq2db? save parent first, then bulkcopy children? thanks.

@Scratch-net, linq2db do not supports inserting a graph of objects.

_Originally posted by @sdanyliv in https://github.com/linq2db/linq2db/issues/193#issuecomment-282830726_

**Comment by viceroypenguin** [comment]
Addressed in comment in #193.
