### ISSUE TITLE
can't load table columns for DB2

### ISSUE THREAD

**Issue by williamlee1982** [linq2db/linq2db#2763]
seems there is a bug in DB2LUWSchemaProvider class, when loading columns of table, it didn't trim the tailing space of the schema name, causes linq query didn't return any column.

the problem is in the GetColumns method here:
```c#
var tableId     = dataConnection.Connection.Database + "." + rd.GetString(0) + "." + rd.GetString(1);
```
and it should be:
```c#
var tableId     = dataConnection.Connection.Database + "." + rd.ToString(0) + "." + rd.ToString(1);
```

### Environment details
linq2db version: all
Database Server: DB2
Database Provider: DB2.Core
Operating system: Windows
.NET Framework: .net 5.0

**Comment by MaceWindu** [comment]
Hmm, can confirm at least TABSCHEMA containing trailing spaces despite being of VARCHAR type...
