### ISSUE TITLE
Array support for insert and update

### ISSUE THREAD

**Issue by TallSwede** [linq2db/linq2db#277]
I'm using linq2db in one client/server project where the MS SQL Server DB is on cloud and winform app is desktop pc. 
Several scenario involves updating or inserting 1000-10000 rows in tables. 
As turnaround times between server/application makes the processing time long (works really fast with local db). 
I might have missed something really basic, but I can't find a good way to batch together many insert or update operations onto a batch and send them to DB at once. That way, I get rid of turn around times. 
Example what I see would work for me:

```c#
List<Order> orderList = GetOrderListToInsert();
db.Insert(orderList);
orderList = GetOrderListToUpdate();
db.Update(orderList);
```

I have done some work in creating text SQL statements and sending them over to DB and that works with good performance. Drawback is to create all the code for update/insert... 

Please note that I'm a relative new user to linq2db and still learning how to do things. I might not use the linq2db in the correct way. 

Thanks for sharing such a cool project as linq2db!

**Comment by MaceWindu** [comment]
For batch insert you should use BulkCopy method
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/InsertTest.cs#L924

**Comment by MaceWindu** [comment]
For updates there are multiple options available:
- use Merge method https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/MergeTest.cs
- bulk insert into temp table and execute update query to apply changes to main table

**Comment by TallSwede** [comment]
Perfect! Thanks for the support.

**Comment by Gennady77** [comment]
fucking links are not available

**Comment by MaceWindu** [comment]
![image](https://user-images.githubusercontent.com/1099238/100337925-3f842b80-2fd8-11eb-9613-22c11566e651.png)
