### ISSUE TITLE
some our code spends most of the time in the GetQuery method. bad performance, lock

### ISSUE THREAD

**Issue by 10der** [linq2db/linq2db#278]
We have performed some investigation on linq2db's GetQuery and FindQuery methods and found following interesting moment.

GetQuery uses FindQuery with double-checked locking pattern to prevent acquiring locks when compiled expression already found in cache and returned by the first FindQuery call: http://take.ms/irSj2 

But in the FindQuery there is also lock region which uses the same lock object as GetQuery: http://take.ms/QPkVZ

This lock region negates double-checked locking pattern effect in GetQuery, because with it we have following workflow:
-   If expression is not found in cache by first call of FindQuery – lock acquired in the GetQuery: http://take.ms/Dzkpu
-   If expression is found in cache but not at first position – lock acquired in the FindQuery: http://take.ms/4mGJZ
-   If expression is found in cache at first position – the only case when no lock acquired

Code inside lock region in FindQuery method just moves compiled expression found in cache to the first position.  It looks like an attempt to reduce number of expression comparison calls while searching through the cache: http://take.ms/jMVYe

Profiler results (local):
http://take.ms/bHcmh - filtered by the Query<T>.GetQuery. Most of time (62,6% + 25%) – awaiting for locks and only 0,6% taken by expression comparison

Profiler results (local) after removing lock region from FindQuery: http://take.ms/WEOc9:
http://take.ms/WTfcQ - filtered by the Query<T>.GetQuery. Expression comparison is now takes about 50% of the GetQuery time, but time for locking and total execution time is significantly reduced in absolute values

Profiler results is received running same 15-mins load test locally

**Comment by mdissel** [comment]
Can you create a pull requests with the changes so we can test this?

**Comment by 10der** [comment]
Ok, will do, when I have a free time.
now you can play with this code:

\linq2db-master\Source\Linq\Query.cs 
```javascript
		static Query<T> FindQuery(IDataContextInfo dataContextInfo, Expression expr)
		{
			// Query<T> prev = null;
			var      n    = 0;

			for (var query = _first; query != null; query = query.Next)
			{
				if (query.Compare(dataContextInfo.ContextID, dataContextInfo.MappingSchema, expr))
				{
					//if (prev != null)
					//{
					//	lock (_sync)
					//	{
					//		prev.Next  = query.Next;
					//		query.Next = _first;
					//		_first     = query;
					//	}
					//}

					return query;
				}

				if (n++ >= CacheSize)
				{
					query.Next = null;
					return null;
				}

//				prev = query;
			}

			return null;
		}
```

**Comment by 10der** [comment]
https://github.com/linq2db/linq2db/pull/299/files

**Comment by MaceWindu** [comment]
Guys. I want to make tests for query caching as a part of #256 fix and based on results we will decide on solution.
