### ISSUE TITLE
Linq2Db not disposing off sql connections and results in exhausting the pool size

### ISSUE THREAD

**Issue by muradkhateeb78** [linq2db/linq2db#2780]
We are using [this](https://linq2db.github.io/articles/get-started/asp-dotnet-core/index.html) as a reference to configure Linq2Db in our .Net Core application and the following is the code to configure it.

```cs
public static IServiceCollection ConfigureLinqToDb<IDbContext, DbContext>(
      this IServiceCollection services,
      IConfiguration configuration,
      IWebHostEnvironment environment,
      bool enableDetailedLogging = false)
      where IDbContext : class
      where DbContext : class, IDbContext, IDataContext
    {
      ConnectionStringSettings linq2DbConnStringSettings = new ConnectionStringSettings();
      configuration.GetSection("Linq2DbConnectionSettings").Bind((object) linq2DbConnStringSettings);
      if (enableDetailedLogging)
        services.AddLinqToDbContext<DbContext>((Action<IServiceProvider, LinqToDbConnectionOptionsBuilder>) ((provider, options) =>
        {
            options.UseSqlServer(linq2DbConnStringSettings.ConnectionString).UseDefaultLogging(provider);
        }), ServiceLifetime.Scoped);
      else
        services.AddLinqToDbContext<DbContext>((Action<IServiceProvider, LinqToDbConnectionOptionsBuilder>) ((provider, options) =>
        {
            options.UseSqlServer(linq2DbConnStringSettings.ConnectionString);
        }), ServiceLifetime.Scoped);
      services.AddScoped<IDbContext, DbContext>();
      return services;
    }
```
And following are our sample IDatabaseContext and DatabaseContext classes that we are passing to the above extension method which eventually gets registered with the IOC Container. 
```cs
public interface IDatabaseContext
{
     IQueryable<MyClient> Clients { get; }
}
```
```cs
public class DatabaseContext : DataConnection, IDatabaseContext
{
     public DatabaseContext(LinqToDbConnectionOptions<DatabaseContext> options) : base(options) { }
     public virtual IQueryable<MyClient> Clients => GetTable<MyClient>();
}
```

We then inject **IDatabaseContext** wherever we want to use it in our code. Everything seems to be working fine unless the number of concurrent users suddenly increases. Which results in a swift increase in the number of active connections, which makes the connection pool exhausted. At one time for 300 users of our application, there were more than 700 active database connections. Please note that this happens mostly with Identity Server. This exhaustion of the connection pool results in users' requests getting timed out and the application becomes unresponsive.

What could we possibly be doing wrong? What are the suggestions to improve this?

### Environment details
linq2db.AspNet version: *3.2.3*
linq2db.SqlServer version: *3.2.3*
Database Server: *SQL Server*
Database Provider: *Microsoft OLE DB*
Operating system: *Linux*
.NET Core version: *3.1*

**Comment by viceroypenguin** [comment]
My suggestion would be to increase the connection pool size in the connection string, to about 1000, based on what you've written here. Since the connections are properly getting returned to the pool, it's just a surge issue, then I would set up the system to prepare for the surges by having enough backfill.

**Comment by muradkhateeb78** [comment]
Well, we have increased the connection pool size to 1000 and that does not fix it. Application is still getting unresponsive.

**Comment by MaceWindu** [comment]
You can try to switch to `DataContext` from from `DataConnection` . It will release connection to pool between transactions, but if all 1000 requests are stuck in query, it will not help

**Comment by to11mtm** [comment]
My other thought would be to look into a couple of things:

 - Not familiar with IdentityServer but there's a chance that you may want to look into how that's hooked up with Linq2Db and make sure it's not somehow holding onto a scope.
 - Consider trying this in your startup:
```
LinqToDB.Common.Configuration.ContinueOnCapturedContext = false;
```

Are you using Blazor or something else that enforces it's own scoping? That can be it's own... thing...

**Comment by muradkhateeb78** [comment]
We are not using any component that enforces its own scoping. Also, the Identity server does not hold onto the scope, but we will give the above solution a try.

**Comment by MaceWindu** [comment]
Have you tried to use `DataContext`?
If you use `DataConnection`, connection is bound to request till request completion, even if it is not used for most of time. Using data context will allow linq2db to return connection to connection pool between transactions/queries during request lifetime.

**Comment by muradkhateeb78** [comment]
Thanks @MaceWindu. Yes, we would have wanted to use DataContext, but since that is a nonpersistent connection so it may have some impact on the performance, isn't that so?

**Comment by MaceWindu** [comment]
Yep, check this thread for more details https://github.com/dotnet/SqlClient/issues/25

**Comment by muradkhateeb78** [comment]
@MaceWindu Thank you. I will go through this.

**Comment by advapiIT** [comment]
> This issue has been closed for a long time - but I wanted to add that my team at work ran into a similiar issue when we would hit a surge of traffic. It ended up not being the Connection Pool itself - but the thread pool on the application not being able to keep up.
> 
> So if you hit the "Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached." exception and have ruled out that it doesn't appear to be your actual Connection Pool - then check the number of process threads and see if you see related spikes. If you do, you may try to fix it by adding `builder.Services.SetMinThreads(100);` and picking an appropriate number for your service.

Excuse me @trimeloni , but is there an extension method to set `builder.Services.SetMinThreads(100)` I'm not able to find it... can you please help me?
Thanks
