### ISSUE TITLE
is ExecuteProc() ready for postgreSQL?

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#2783]
stored procedure:
```sql
CREATE OR REPLACE PROCEDURE "Schema1"."sp_Test"(
	"Id" integer)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
END
$BODY$;
```
test:
```c#
//int exec = db.Execute("CALL \"Schema1\".\"sp_Test\"(@p0)", new DataParameter("p0", 1)); //work
var input1 = new DataParameter("Id", 1, DataType.Int32) { Direction = ParameterDirection.Input };
int proc = db.ExecuteProc("\"Schema1\".\"sp_Test\"", input1); //not work
```
Error: 42809: Schema1.sp_Test(Id => integer) is a procedure
Hint: To call a procedure, use CALL

does that mean i cannot use ExecuteProc() for postgre?

### Environment details
linq2db version: 3.2.3
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by MaceWindu** [comment]
We didn't tested procedures support yet for pgsql since it was introduced in pgsql 12, so probably you need to use `Execute` for now

**Comment by darshana2000** [comment]
C# postgresSQL calling stored procedure with names parameters. Is this solved by now in Linq2db?

I m still getting an error. Tried few methods and all failed.

Method 1 
var result = dataConnection.Execute("SP_nameinUppaerCase", param1, param2, param3);

Method 2
 
var output23 = dataConnection.ExecuteReader("CALL dbo.\"SP_nameinUppaerCase\"(@updatedby,@updatedcount,@insertedcount)",
                    para);
                    
Method 3 
 string cmdText4 = "Call  dbo.SP_nameinUppaerCase(@updatedby,@updatedcount,@insertedcount)";

**Comment by darshana2000** [comment]
Sample code
 `using (NpgsqlConnection con = new(conn))
                {
                    await con.OpenAsync();
                    //con.ReloadTypes(); 
                    using NpgsqlCommand command = new(cmdText4, con);
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandTimeout = 300;
                    //command.Parameters.AddWithValue("updatedby", DbType.String).Value = "test";
                    //command.Parameters.AddWithValue("updatedcount", DbType.Int64).Value = 0;
                    //command.Parameters.AddWithValue("insertedcount", DbType.Int64).Value = 0;

                    // Add named parameters
                    command.Parameters.Add(new NpgsqlParameter("updatedby", NpgsqlTypes.NpgsqlDbType.Varchar)).Value = "test db";
                    command.Parameters.Add(new NpgsqlParameter("updatedcount", NpgsqlTypes.NpgsqlDbType.Integer)).Value = 0;
                    command.Parameters.Add(new NpgsqlParameter("insertedcount", NpgsqlTypes.NpgsqlDbType.Integer)).Value = 0;
                                          
                    var result =   command.ExecuteNonQuery();
                    using NpgsqlDataReader dr = await command.ExecuteReaderAsync();

                    while (dr.Read())
                    {
                        if (dr.HasRows)
                        {
                            Console.WriteLine(dr.Read().ToString());
                            Console.WriteLine("sample = " + dr.Rows.ToString());
                        }
                    }
                    dr.Close();
                }`

**Comment by MaceWindu** [comment]
Issue is still open

**Comment by darshana2000** [comment]
Thank you for the update. any alternative to solve this issue?

**Comment by MaceWindu** [comment]
Well, I tested how it works with ExecuteProc and actually don't see any issue:

```sql
CREATE PROCEDURE testproc(a integer, inout b integer, out c integer)
LANGUAGE 'plpgsql'
AS $$
begin
b = a + b;
c = a + b;
return;
end;
$$;
```

```cs
using var db = new DataConnection(new DataOptions().UsePostgreSQL(cs, PostgreSQLVersion.v15));
        var a = new DataParameter("a", 1) { Direction = ParameterDirection.Input};
        var b = new DataParameter("b", 2) { Direction = ParameterDirection.InputOutput };
        var c = new DataParameter("c", null) { Direction = ParameterDirection.Output };
        // call testproc(1, 2, null)
        var r = db.ExecuteProc("testproc", a, b, c);
        // b.Value = 3
        // c.Value = 4
```

**Comment by MaceWindu** [comment]
> Just wondering to know any reason to mention postgresSQL version in connection string?

`UsePostgreSQL` currently has overloads conflict due to use of default parameters, so I need to specify parameters manually

**Comment by darshana2000** [comment]
Noted, thank you for prompt response. 

Mention postgresSQL version in connection string impact to all areas of the application. 
Hope it won't damange other areas. Have to test them.

**Comment by MaceWindu** [comment]
Closing it, as I'm not aware of issues with pgsql procedures execution support
