### ISSUE TITLE
Wrong SQL for Oracle v12 (1.0.2) , works in v18

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2785]
We create following query:

			using (var db = GetDataContext(context))
			{
				using (db.CreateLocalTable<TableA>())
				using (db.CreateLocalTable<TableB>())
				{
					var query = from a in db.GetTable<TableA>()
								join b in  db.GetTable<TableB>() on a.Id equals b.Id
								select new { Id=a.Id, Id2=b.Id };

					var res = query.Take(10).ToList();

					var sql=((DataConnection) db).LastQuery;
				}
			}

wich creates following sql:

		DECLARE @take Int32
		SET     @take = 10
		
		SELECT
			a."Id",
			b."Id"
		FROM
			"TableA" a
				INNER JOIN "TableB" b ON a."Id" = b."Id"
		FETCH NEXT :take ROWS ONLY

this works only in oracle v18

If I remove the "Take 10" it also works in V12

I got these Exception:

      DataConnection: Error
    Exception: Oracle.ManagedDataAccess.Client.OracleException
    Message  : ORA-00918: Spalte nicht eindeutig definiert

   "ORA-00918: column ambiguously defined"

**Comment by jogibear9988** [comment]
@MaceWindu 
why feature? it fails to create the correct sql and throws a exception

**Comment by MaceWindu** [comment]
If it works in v18, we probably should introduce v18 dialect and fix this issue for v11/v12 only

**Comment by jogibear9988** [comment]
Yes, but v12 is broken. So it's not a feature :-)  (I think)
Problem also is, how could we force to use a Version (for example V11).
We cannot change the ConnectionStringName, cause it's all over in our software, so it uses automatic version detection, and uses v12 Provider, wich adds 

       FETCH NEXT :take ROWS ONLY

support. So I could not switch to V11.
Maybe we should add a setting to force version?

**Comment by jogibear9988** [comment]
I think we could fix this if we add aliases to the Columns wich have the same name.

**Comment by jogibear9988** [comment]
@MaceWindu Which Version is our Oracle installation?
Cause the test seems not to have failed

**Comment by MaceWindu** [comment]
11 and 12

**Comment by jogibear9988** [comment]
The issue is described here:

https://stackoverflow.com/questions/57787579/oracle-sql-column-ambiguously-defined-with-fetch-first-n-rows-only

**Comment by jogibear9988** [comment]
@MaceWindu 
As it seems to work in V18, it is still not allowed according the doc's
https://docs.oracle.com/database/121/SQLRF/statements_10002.htm#BABHFGAA

so I think it would be enough to fix in V12 and not create an extra provider

**Comment by jogibear9988** [comment]
@sdanyliv can you help me with this? is there a way in the SQLBuilder so we add aliases for same named columns? Or should we fall back from the limit format to the one without special SQL support when Take is used?

**Comment by sdanyliv** [comment]
Try as workaround 
```cs
Configuration.Common.GenerateFinalAliases = true;
```
