### ISSUE TITLE
The transaction isolation level is not reset when the connection is closed

### ISSUE THREAD

**Issue by FlipSs** [linq2db/linq2db#2790]
Hello.

I have been migrating a large project from Entity Framework to linq2db and decided to split migration of one especially large database into 2 parts - after the first deployment one part of it will work with EF and the other with linq2db. After this deployment, I noticed that rare deadlocks are starting to occur in EF queries (that code was not changed). After digging around, I realized that some of EF queries use _RepeatableRead_ isolation level, but we use our default (_ReadCommited_ _Snapshot_) in all queries to this database. The single place where connection with _RepeatableRead_ may occur is that when you use _DefaultMultiQueryIsolationLevel_ setting (after wrapping all non transactional EF queries in _ReadCommited_ transaction deadlocks were stopped).

The problem is: **transaction isolation level is not reset to default when the connection is closed and after reuse it continues to use the last isolation level unless a new one is specified**. I read that until Sql Server 2014 _cp_reset_connection_ does not reset isolation level, but we use Sql Server 2017.

So I have a few questions:
1) When is _DefaultMultiQueryIsolationLevel_ setting used? (I assume that when called _LoadWith_ to load some collection)
2) I almost sure that is not linq2db bug, but anything is possible, so what do you know about that problem?

Thank you in advance.

### Environment details
linq2db version: 3.2.3
Database Server: Sql Server 2017
.NET Framework: net472

**Comment by sdanyliv** [comment]
Yes we change isolation level for Eager Loading. Try to set `DefaultMultiQueryIsolationLevel = IsolationLevel.Snapshot`

**Comment by FlipSs** [comment]
But this does not solve the problem globally, this isolation level is kept forever in that connection until a different one is set.
When I profiled I observed the use of _RepeatableRead_ in random queries, it was SPID bound.
This is how you use that setting:
![image](https://user-images.githubusercontent.com/25420767/105629981-3fc56980-5e57-11eb-9034-4205d18174a6.png)

As I understand the problem if I execute something like this: 

```
using(var connection = new DataConnection(...)) 
using(var transaction = connection.BeginTransaction(SomeIsolationLevel)) {
/// whatever
}
```

And then anywhere something like that (anything without transaction):
```
using(var connection = new DataConnection(...)) 
{
/// whatever
}
```
The second connection can be with the first connection isolation level if it reuses the connection from the first code sample.
And that's pretty scary.

**Comment by FlipSs** [comment]
Here is code sample.
```
public void Test()
{
	var connectionStringBuilder = new SqlConnectionStringBuilder("YourConnectionString")
	{
		MaxPoolSize = 1
	};

	var connectionString = connectionStringBuilder.ToString();

	using (var connection = new DataConnection(connectionString))
	using (connection.BeginTransaction(System.Data.IsolationLevel.ReadUncommitted))
	{
		var user = connection.Users.First();
	}

	using (var connection = new DataConnection(connectionString))
	{
		var user = connection.Users.First();
	}
}

```

In profiler first connection audit login event has `set transaction isolation level read committed` and second has `set transaction isolation level read uncommitted`.

**Comment by MaceWindu** [comment]
That's a hard one. As I understand from this [link](https://stackoverflow.com/a/25666921)  SQL Server 2014 change was reverted.

I'm not sure what we can do here... Taking into account that it is sql client behavior, best solution is to avoid auto-transactions and use them explicitly.

When you say `but we use our default (ReadCommited Snapshot) in all queries to this database`, what do you mean by that - how you specify default isolation level?

**Comment by FlipSs** [comment]
_Allow snapshot isolation_ and _Is read commited snapshot on_ are enabled in database.
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/snapshot-isolation-in-sql-server

And there are no explicit transactions with the specified isolation level in this project, so it always uses the database defaults.

**Comment by FlipSs** [comment]
As a workaround for EF, I wrote an [Interseptor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.dbcommandinterceptor?view=efcore-5.0), which sets the _ReadCommited_ transaction to the command if it doesn't exist. Perhaps something like this could be a solution with the default _ReadCommited_ setting, as on _SqlServer_.

**Comment by jogibear9988** [comment]
https://github.com/dotnet/SqlClient/issues/96

**Comment by jogibear9988** [comment]
whats the best way at the moment to solve this issue? we now discovered it on one customer

**Comment by MaceWindu** [comment]
We decided to not implement any workarounds on our side.

For some time already we have interceptors, so same workaround could be used as for EF.Core.
