### ISSUE TITLE
Cannot load assembly MySqlConnector on T4 generation

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#2791]
After updating from 3.1.6 to 3.2.3 I got strange error when generating T4 template.

`Running transformation: System.InvalidOperationException: Cannot load assembly MySqlConnector`

I have found the following changes in code of T4 template

```C#
LinqToDB.Data.DataConnection GetMySqlConnection(string connectionString)
{
	return LinqToDB.DataProvider.MySql.MySqlTools.CreateDataConnection(connectionString, ProviderName.MySqlConnector);
}
```

`ProviderName.MySqlConnector` was added as second parameter.  

I am using official MySql.Data.dll library:

![image](https://user-images.githubusercontent.com/4306334/105633474-d69b2180-5e69-11eb-922a-b487a8c474d3.png)

It is imported using `<#@ assembly name="Some\Path\To\MySql.Data.dll"                          #>`

So to temporarily workaround the issue I had to edit LinqToDB.MySql.ttinclude.  
I have removed second parameter 
```C#
return LinqToDB.DataProvider.MySql.MySqlTools.CreateDataConnection(connectionString);
```

I do not know the exact reason of such behaviour, but it looks like some bug in T4 template.

**Comment by MaceWindu** [comment]
T4 templates in 3.2.3 switched to use `MySqlConnector` provider to load metadata. If you edited provider location in T4 `assembly` directive, than it is your change is correct one.
