### ISSUE TITLE
Wrong data type for MySQL bit(1) type

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#2792]
```sql
CREATE TABLE `SomeTable` (
  `Id` binary(16) NOT NULL,
  `MyFlag` bit(1) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

MyFlag should be `bool?` but it generates:

`[Column,        Nullable] public bool      MyFlag           { get; set; } // bit(1)`

### Environment details
linq2db version: 3.2.3
Database Server: MariaDB 10.4.17
Database Provider: MySql 8.0.23

**Comment by MaceWindu** [comment]
I cannot reproduce issue. Are you sure your column is nullable?

**Comment by MaceWindu** [comment]
Could it be that you modified loaded model or T4 templates as I don't see how it is possible to get both nullable attribute and non-nullable bool field generated.

**Comment by hardhub** [comment]
> 
> 
> Could it be that you modified loaded model or T4 templates? I don't see how it is possible to get both nullable attribute and non-nullable bool field generated.

Sorry guys I have found the reason. It was workaround for old (< 2.0) version of Linq2db.  
Now all is solved and I removed unnecessary code in hooks. It is related to T4 as you mentioned.  
I replaced all T4 files to fresh ones but did not see _include_ of legacy file with workaround inside).
