### ISSUE TITLE
Global Query Filter

### ISSUE THREAD

**Issue by krstesizgoric** [linq2db/linq2db#2794]
It would be nice if there could be a possibility to add filters for entities globally, similar to [Global Query Filters](https://docs.microsoft.com/en-us/ef/core/querying/filters) in Entity Framework Core. I’m currently working on a project where legacy code is completely written In Linq2Db, so there is no possibility to use EFCore + Linq2Db combination to get Global Query Filter support.

This is already discussed in issue [#1149](https://github.com/linq2db/linq2db/issues/1149) but I would like to add reasons for this functionality.

**First is obvious, soft delete.**

I really don’t like when business logic knows that I’m doing soft delete (if I want to implement soft delete on an existing table I need to do a lot of refactoring).

Let’s say there is a table Author with many Post, and Post can have many Tags. I’m adding ExpressionPredicate to Author to connect to the list of Posts, Post to list of Tags and do on. I’m using [AutoMapper](https://docs.automapper.org/en/stable/Queryable-Extensions.html), so my code looks something like this:

```c#
DbContext.GetTable<Author>()
    .ProjectTo<TModel>(Mapper.ConfigurationProvider)
    .ToList();
```

This way I can use the same business logic for multiple endpoints or actions.

For softdeletable entities I need to add IsDeleted == false. I can do that in code.

```c#
DbContext.GetTable<Author>()
    .Where(x => x.IsDeleted == false)
    .ProjectTo<TModel>(Mapper.ConfigurationProvider)
    .ToList();
```

But for related entities I need to add this to model mapping (horrible idea). 

If I add IsDeleted == false to ExpressionPredicate in the entity I lost access to deleted posts for Author. I need to manually write a new select method for that now. That way I can’t use AutoMapper and I need to write each function manually (horrible idea).

If there was functionality to turn global filters on or off that would be wonderful.

Example:
```c#
public IEnumerable<TModel> GetAll<TModel>() => GetQuery().IgnoreQueryFilters().ToList();

public IEnumerable<TModel> GetNotDeleted<TModel>() => GetQuery().ToList();

private IQueriable GetQuery() => DbContext.GetTable<Author>().ProjectTo<TModel>(Mapper.ConfigurationProvider);
```

**Second, multi tenancy.**

Same as above, I’m getting a list of Authors that have many Posts. But on this system there are 3 roles (admin, moderator, author).
- Admin can access all posts and all authors
- Moderator can access group of authors (with specific tenantId) and only to their posts
- Author can access only to himself/herself and his/her own posts.

I'm creating action that lists all authors. This is basically the same functionality for all 3 roles and should be treated like that. If the frontend sends a request to API it should have the same endpoint. That endpoint should call the same method in service, and that service shouldn’t care which role is requesting this action. Why? Because if I want to add a new role I don’t want to rewrite all this logic. I just want to add new role limits and get everything ready out of the box. 

```c#
var predicat = rolePredicateBuilder.GetPredicat<Author>(roleId, userId);
modelBuilder.Entity<Author>().HasGlobalFilter(x => predicat);
```

I implemented this approach on multiple projects in the past, but Linq2Db does not support this. It would be really nice to have this functionality.

**Comment by sdanyliv** [comment]
Actually linq2db has similar functionality ;) Check for other overloads, which are more powerful than EF has.
```cs
modelBuilder.Entity<Author>().HasQueryFilter(predicat);
```
And opposite `IgnoreFilters()`

**Comment by krstesizgoric** [comment]
I thought I was thorough, I don't know how I missed this. [HasQueryFilter](https://linq2db.github.io/api/LinqToDB.Mapping.EntityMappingBuilder-1.html#LinqToDB_Mapping_EntityMappingBuilder_1_HasQueryFilter_System_Func_System_Linq_IQueryable__0__LinqToDB_IDataContext_System_Linq_IQueryable__0___) is definitely the functionality I was looking for. 

Thanks

**Comment by hzzcmaj7** [comment]
@krstesizgoric  hi krstesizgoric，I have encountered the same problem as you. May I ask if your problem has been resolved? Unfortunately, the last link opened was 404.
Thanks

**Comment by krstesizgoric** [comment]
@hzzcmaj7 this one? [HasQueryFilter](https://linq2db.github.io/api/linq2db/LinqToDB.Mapping.EntityMappingBuilder-1.html#LinqToDB_Mapping_EntityMappingBuilder_1_HasQueryFilter_System_Func_System_Linq_IQueryable__0__LinqToDB_IDataContext_System_Linq_IQueryable__0___)

**Comment by hzzcmaj7** [comment]
@krstesizgoric  yes, this is great, Thanks krstesizgoric!
