### ISSUE TITLE
Too long first query

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#2795]
On first query to database linq2db spend too much time.  
I cannot be sure but it looks that earlier versions worked much faster.  

Preparing for 1st query takes 8+ seconds (simple query just to get 1st row in the table).  
Application mostly do not use CPU during that period (even single core is not loaded fully).

Is it normal? Can it be optimized? What can I improve?

### Environment details
linq2db version: 3.2.3
Database Server: MariaDB 10.4.17
Database Provider: MySql 8.0.23

**Comment by sdanyliv** [comment]
Without sample we cannot help. Similar issue https://github.com/linq2db/linq2db/issues/2762

**Comment by sdanyliv** [comment]
@hardhub, if you have Performance Analyser better to check on your side what is happened. For sure there can be static variables initializations but I don't think so. Probably some problems with ADO provider.
Anyway do you use MySql official provider or MySqlConnector?

**Comment by MaceWindu** [comment]
@sdanyliv  `MySql.Data`

**Comment by MaceWindu** [comment]
We are not aware of such performance issue with linq2db itself, so I would suspect:
- something in your code takes a lot of time
- initiation of first mysql connection take a lot of time due to provider/network/whatever reason

I would recommend:
- profile application to see what's going on
- check if problem persists with `MySqlConnector` provider

**Comment by hardhub** [comment]
I do not have anything specific in my code. Just T4 generated classes and single conversion for DateTime UTC (MappingSchema.Default.SetConvertExpression)

I have switched project to use MySqlConnector. Now first initialization takes **1.5 seconds (!)**

It is much better. I do not know the reason, probably MySql.Data asks network, maybe DNS and it takes so much time.  
1.5 seconds looks much more reasonable.

In any case may I ask you if 1.5 seconds is average time of linq2db initialization or is it still can be improved?  
If it is still too much then I will profile linq2db (not app because it is time of linq2db initialization not app itself).

**Comment by sdanyliv** [comment]
Better to run profiler.

**Comment by MaceWindu** [comment]
We do not perform any initialization work like EF that could introduce any noticable delay.

**Comment by MaceWindu** [comment]
non-actionable with provided inputs
