### ISSUE TITLE
Oracle - Linq2db creates to long alias for Column name in SQL

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2798]
We have a Database where we have a long Column Name:

"OutfeedTransportOrderPosition"

but linq2db adds "_1" in the sql but this fails in oracle cause 30chars is max size

![image](https://user-images.githubusercontent.com/364896/105967767-86e57180-6086-11eb-9139-6d65dad57de8.png)

**Comment by jogibear9988** [comment]
problem is we use Orcale 11, and the longer identifiers are only possible in orcale v12

**Comment by MaceWindu** [comment]
Currently we don't validate length of generated ids. I would prefer it fixed in generic way: max-length property for provider + length check in identifier generation logic

**Comment by jogibear9988** [comment]
At the moment we generate the Parameternames at OptimizationContext.CorrectParamName, is this correct?
How should we access QueryProvider from here? (For Provider specific setting)

**Comment by MaceWindu** [comment]
Probably not gonna pick it up for next release, so I will add implementation notes here:
- we should implement identifier trimming for autogenerated identifiers: alias, parameter name, identity sequence and trigger names
- as trimming logic is not straightforward for some databases it should be possible to override it to avoid blocking issues for users. For that we will adopt interceptors approach from ef.core: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors by introducing ISqlGenerationIterceptor with 4 initial operations (alias, parameter, sequence and trigger name generators)

Identifier limit vary per database not only by length but also by measurement unit. E.g.:
- in characters
- in bytes in specific encoding
- in bytes in database encoding
Also for some of databases documentation is vague and lack all requred information, so it should be covered with tests to detect and test actual limits.

Per-db limits:
- access : 64 characters (https://support.microsoft.com/en-us/topic/access-specifications-0cf3c66f-9cf2-4e32-9568-98c1025bb47c?ui=en-us&rs=en-us&ad=us)
- db2 luw : 128 bytes in database codepage... (https://www.ibm.com/support/knowledgecenter/SSEPGG_10.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0001029.html) + read codepage https://knowledgebase.progress.com/articles/Article/3218
- db2 zos : 128 utf8 bytes, 30 for column (https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/sqlref/src/tpc/db2z_limits.html)
- firebird: 31 bytes(utf8), 63 in v4
- informix: 128 bytes in database code set (https://www.ibm.com/support/knowledgecenter/SSGU8G_14.1.0/com.ibm.sqls.doc/ids_sqs_1660.htm)
- mysql/mariadb: object 64 (63 for NBD table till v8) chars, alias 256 chars (https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html, https://mariadb.com/kb/en/identifier-names/)
- oracle: 30 bytes, 12.2+ : 128 bytes. not sure what is byte here
- pgsql: 63 bytes (encoding?) (https://www.postgresql.org/docs/current/limits.html)
- saphana: 127 chars (identifier), 128 (alias) (https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20a760537519101497e3cfe07b348f3c.html)
- sqlce: ? cannot find documentation on it, must be discovered by tests
- sqlite: no limits (limited by sql statement size(1m by default))
- sqlserver: 128 chars, 116 for local temp tables
- sybase: 255 bytes (e.g. for parameters @ counts as name part) with some identifiers (which?) limited to 30 http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36271.1600/doc/html/san1393050529478.html

**Comment by MaceWindu** [comment]
This was fixed in preview 1
