### ISSUE TITLE
Char DataType for bool in Oracle

### ISSUE THREAD

**Issue by KarlssonBernoulli** [linq2db/linq2db#2801]
The column data type in Oracle for a C# property  of type bool is CHAR (1 byte). Shouldn't it be NUMBER(1,0) ?

```C#
 public class Car
    {
        public long Id {get;set;}
        public bool IsSet {get;set;}
    }

context.CreateTable<Car>();
```

**Comment by jogibear9988** [comment]
see https://github.com/linq2db/linq2db/issues/511

**Comment by jogibear9988** [comment]
https://www.oreilly.com/library/view/oracle-plsql-programming/0596003811/ch12.html#:~:text=A%20Boolean%20is%20a%20%E2%80%9Clogical,Boolean%20values%20(or%20NULL).

**Comment by jogibear9988** [comment]
https://stackoverflow.com/questions/3726758/is-there-any-boolean-type-in-oracle-databases

**Comment by jogibear9988** [comment]
We use Char(1), this is not wrong. 
see https://github.com/linq2db/linq2db/blob/d9832b6e8dd60e4946e26c07f5e4ac241d167f11/Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs#L140

**Comment by MaceWindu** [comment]
Note: i've assigned it to 4.0 not because we plan to switch to `number(1)` for oracle, but because we plan to improve situation around custom type mappings to allow users reconfigure mappings in more easier way than now.
E.g. I need this feature for #2693

**Comment by MaceWindu** [comment]
`Char(1)` is widely accepted boolean surrogate for Oracle, so we will not change it. User could define own mappings using mapping schema if he want to use other underlying type. Note that we plan to add Oracle 23 dialect with native boolean type support in next release
