### ISSUE TITLE
INSERT INTO ... SELECT

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2802]
Is there a way to create a ```INSERT INTO ... SELECT``` statement in Linq2Db for Oracle?

I have a table of type Car

and an ```IQueryable<Car>```

I do not get the point in the tests for ```InsertWithOutputInto```. Is it for ```INSERT INTO ... SELECT``` ?

**Comment by sgashua** [comment]
How about this?
```
var list = context.Cars.Where(your where clause).Select(x => new YourOtherTable()
{
   ID = x.ID,
   ..
   ..
}).AsQueryable();

context.BulkCopy(list);
```

**Comment by HypeillingerChillinger** [comment]
It's near the solution but there is a problem:
With INSERT INTO ... SELECT you can select the properties. With BulkCopy you can't because it is
``` BulkCopy<T>(IEnumerable<T> source) ```
So Linq2Db finds the target table by the used type ```T```. So I cannot use any other type than the type used in ```ITable<TargetType>``` 

The PK is an identity column. It results in a unique constraint exception because I do not set the PK which defaults to 0 (zero)

**Comment by sdanyliv** [comment]
https://stackoverflow.com/a/65670652/10646316

**Comment by HypeillingerChillinger** [comment]
@sdanyliv That is what I was searching for, thanks
