### ISSUE TITLE
Use selective aggregates where possible

### ISSUE THREAD

**Issue by gatapia** [linq2db/linq2db#2804]
[Selective Aggregates](https://modern-sql.com/feature/filter) or its alternative `CASE WHEN <condition> THEN 1 END` should be used to improve performance.

An example of this is as follows.  This code (using [Northwind](https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/northwind-pubs)):

```
using (var db = new NorthwindDB()) {
  var _ = db.Employees.GroupBy(e => e.City).Select(g => new { 
    g.Key, 
    Count=g.Count(), 
    HasBoss = g.Count(e => e.ReportsTo != null), 
    IsBoss = g.Count(e => e.ReportsTo == null)
  }).ToArray();
}
```

Creates the following sql:
```
SELECT [t1].[City],
  Count(*),
  (SELECT Count(*) FROM [dbo].[Employees] [e] WHERE 
    ([t1].[City] = [e].[City] OR [t1].[City] IS NULL AND [e].[City] IS NULL) AND [e].[ReportsTo] IS NOT NULL),
  (SELECT Count(*) FROM [dbo].[Employees] [e_1] WHERE
    ([t1].[City] = [e_1].[City] OR [t1].[City] IS NULL AND [e_1].[City] IS NULL) AND [e_1].[ReportsTo] IS NULL	)
FROM [dbo].[Employees] [t1]
GROUP BY [t1].[City]
```

However the following sql is much more efficient:
```
SELECT [t1].[City],
  Count(*),
  COUNT(CASE WHEN [t1].[ReportsTo] IS NOT NULL THEN 1 END),
  COUNT(CASE WHEN [t1].[ReportsTo] IS NULL THEN 1 END)  
FROM [dbo].[Employees] [t1]
GROUP BY [t1].[City]
```

Or (if supported):
```
SELECT [t1].[City],
  Count(*),
  FILTER(WHERE [t1].[ReportsTo] IS NOT NULL),
  FILTER(WHERE [t1].[ReportsTo] IS NULL)
FROM [dbo].[Employees] [t1]
GROUP BY [t1].[City]
```

The first query does three clustered index scans, the other two only do one. Making them almost 66% faster.

**Comment by gatapia** [comment]
Interestingly, the following code results in a very efficient query:
```
var _ = db.Employees.GroupBy(e => e.City).Select(g => new
      {
        g.Key, 
        Count=g.Count(), 
        HasBoss = g.Sum(e => e.ReportsTo != null ? 1 : 0), 
        IsBoss = g.Sum(e => e.ReportsTo == null ? 1 : 0)
      }).ToArray();
```

SQL:
```
SELECT [t1].[City], Count(*), Sum(IIF([t1].[ReportsTo] IS NOT NULL, 1, 0)), Sum(IIF([t1].[ReportsTo] IS NULL, 1, 0))
FROM [dbo].[Employees] [t1] GROUP BY [t1].[City]
```

So I guess this is already supported, is there anywhere where these optimisation 'hacks' are documented?

**Comment by sdanyliv** [comment]
You have shown known workaround with `Count` and condition. linq2db has it's own solution for that case, also check for overloads for `CountExt`:
```cs
var _ = db.Employees.GroupBy(e => e.City).Select(g => new
      {
        g.Key, 
        Count = g.Count(), 
        HasBoss = g.CountExt(e => e.ReportsTo) > 0, 
        IsBoss = g.CountExt(e => e.ReportsTo == null ? 1 : null) > 0
      }).ToArray();
```
Actually we can handle such case automatically but I cannot find time to implement that.
Anyway there is also Filter support but it works only with Window Functions.

**Comment by sdanyliv** [comment]
Check the same without grouping.
```cs
var _ = db.Employees.Select(e => new
      {
        Employee = e,
        HasBoss = Sql.Ext.Count(e.ReportsTo)).Over().ToValue() > 0, 
        IsBoss = Sql.Ext.Count(e.ReportsTo == null ? 1 : null).Over().ToValue() > 0
     }).ToArray();
```

**Comment by gatapia** [comment]
Tnx for the help, hopefully this ticket can serve as documentation for someone else in the future.  Closing as its not a bug.

PS: The count over solution does not work for me in my real-life DB, this example was just contrived to show the specific sql being generated with .Count(predicate)
