### ISSUE TITLE
Question - TableName by convention

### ISSUE THREAD

**Issue by RoyChase** [linq2db/linq2db#2807]
Is there anywhere that a table name mapping function can be attatched globally so that say a POCO table using Pascal Case could be mapped to a DB table using snake case without needing a TableAttribute or mapping?

e.g. InvoiceHeader -> invoice_header

Another example is a POCO class having a suffix removed 

e.g. InvoiceHeaderTable -> InvoiceHeader

Ideally I'd like to be able to do the same for column names as well.

The idea is to be able to specify the function once as a convention rather than having to add table attributes or mappings for each table in an attempt to keep the mappings to the minimum.  Nirvana would be no mappings required!

**Comment by viceroypenguin** [comment]
Yes, you can update the `ToValidName` variable to point to a custom function that does what you need it to do. https://linq2db.github.io/articles/T4.html#configuring-generation-process

```csharp
// Defines logic to convert type/member name, derived from database object name, to C# identifier.
Func<string, bool, string> ToValidName         = ToValidNameDefault;
```


https://linq2db.github.io/articles/T4.html#configuring-generation-process

**Comment by RoyChase** [comment]
I'm not looking for an equivalent function in Linq2Db itself not the generator.

**Comment by MaceWindu** [comment]
This is possible using custom metadata provider. Please check discussion here: #2501

**Comment by RoyChase** [comment]
Thanks that looks like it should work.  I'll see ifit does what I need tomorrow and close the issue if it does.

👍

**Comment by RoyChase** [comment]
That's worked great. Thanks for your help
