### ISSUE TITLE
Question - How to update existing .Set() param

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#2809]
```c#
var qupdate = db.T_Table1.Where(x => x.RowId == 1 && x.Code == "code1").AsUpdatable();
qupdate = qupdate.Set(x => x.IntValue, 1);
qupdate = qupdate.Set(x => x.IntValue, 2);
moreUpdate(ref qupdate);
qupdate.UpdateAudited();//Npgsql.PostgresException: '42601: multiple assignments to same column "IntValue"'
```

how to update existing set instead add new one?
~~include unset/clear too if supported~~

thanks

### Environment details
linq2db version: 3.2.3
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
I think it needs improvements in that case. We generate update for each `Set` call and do not replace previous.
