### ISSUE TITLE
Inserting datetime2 field ignore milliseconds on version 3.2.3?

### ISSUE THREAD

**Issue by Sherif-Ahmed** [linq2db/linq2db#2811]
After uprading to version 3.2.3 from 3.2.1
datetime2 fields milliseconds truncated while inserting and updating

Environment details
linq2db version: 3.2.3
Database Provider: SqlServer
.NET Framework: .Net Core 5.0.2

**Comment by sdanyliv** [comment]
I would ask for Model, mapping and sample how you do `Insert` and `Update`.

**Comment by MaceWindu** [comment]
Looks like caused by #2727

**Comment by Sherif-Ahmed** [comment]
> I would ask for Model, mapping and sample how you do `Insert` and `Update`.

I'm mapping using IMetadataReader and fluentmigrator
and returning a `ColumnAttribute` like below

```
new ColumnAttribute
{
    Name = column.Name,
    IsIdentity = column.IsIdentity,
    IsPrimaryKey = column.IsPrimaryKey,
    IsColumn = true,
    CanBeNull = column.IsNullable ?? false,
    Length = column.Size ?? 0,
    Precision = column.Precision ?? 0,
    DataType = SqlDataType.GetDataType(columnSystemType).Type.DataType
};
```

**Comment by MaceWindu** [comment]
I see

This is not correct, default precision value for `datetime2` type [is 7](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver15), not 0
```cs
  Precision = column.Precision ?? 0,
```

**Comment by MaceWindu** [comment]
Rechecked our datetime2 code once more. Can confirm that it is caused by incorrect default precision manifested due to recent changes in linq2db to properly handle precision for datetime2.

**Comment by Sherif-Ahmed** [comment]
@MaceWindu yes you are right ... after applying that change ... it works perfectly ... thank you
