### ISSUE TITLE
string.IsNullOrWhitespace cannot be converted to SQL

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2816]
In Linq2Db 3.2.3 
string.IsNullOrWhitespace is not supported

```C#
var carTable = context.GetTable<Car>();
carTable.Where(x => !string.IsNullOrWhitespace(x.Name));
```

**Comment by sdanyliv** [comment]
@HypeillingerChillinger, maybe you want to implement that by yourself? It is easy and I'll point you how to do that.

**Comment by HypeillingerChillinger** [comment]
I have not much time but if we could leave that issue open for a month or two I could do it.
Please give me some hints.
