### ISSUE TITLE
Table variable

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2825]
Is it possible to ```INSERT INTO```  a table variable with Linq2Db and reuse it in the next query?

**Comment by sdanyliv** [comment]
Into temporary table YES. Into variable NO.

**Comment by HypeillingerChillinger** [comment]
Is it possible with Linq2db add an index on a temp table?

**Comment by sdanyliv** [comment]
`IntoTempTable` has action with EntityMappingBuilder where you can define primary key. Only such index is supported.

**Comment by HypeillingerChillinger** [comment]
I think that is worth a feature request. What do you think?

**Comment by sdanyliv** [comment]
It worth. but no time to implement. And probably EntityMappingBuilder should be redesigned.

**Comment by HypeillingerChillinger** [comment]
Shall I create an issue?

**Comment by sdanyliv** [comment]
Why not. For tracking new issue will be good.
