### ISSUE TITLE
Async insert/update

### ISSUE THREAD

**Issue by Cromathaar** [linq2db/linq2db#283]
Hi. I'm wondering how may async inserts and updates be implemented using Linq2db (using SQL Server provider)?

**Comment by xclayl** [comment]
I'm wondering too.  I'd like to do something like this:

`await db.InsertAsync(product);`

**Comment by xclayl** [comment]
As background for this request, Project Orleans is async-only.  Without something like InsertAsync, it rules out db2linq unfortunately.

https://github.com/dotnet/orleans

**Comment by ili** [comment]
why not smth like:
```cs
public static Task<int> InsertAsync<T>(this IDataContext db,  T obj)
{
   var t = new Task<int>(() => db.Insert(obj));
   t.Start
   return t;
}
```

**Comment by xclayl** [comment]
Task.Start doesn't release the thread when ado.net goes over the network to the database. It'll have a negative performance effect on systems that make heavy use of Async/await like Orleans.

**Comment by Reltik** [comment]
+1

**Comment by Reltik** [comment]
BeginTransaction, RollBackTransaction, etc. should have an async method too!

**Comment by ipashqa** [comment]
+1

**Comment by iouris** [comment]
async version of Delete is also of course needed

**Comment by jogibear9988** [comment]
I think then we also need a fuction like ExecuteAsync for our iqueryables like 

     IEnumerable<T> ExecuteAsync(this IQueryable<T> qry)

wich sends query to the server, releases the Thread, when the result arrives returns

**Comment by jogibear9988** [comment]
I've looked at this today.
I think it's a big task, if we want to implement async support (but maybe i'm wrong). Also, for insert, update & delete it's clear what to do. If we also want it for Selects, I think we have to look also, if smth like IAsyncEnumerable<T> should be supported. 
I've not really the time to work on this.

**Comment by hardhub** [comment]
Does it make any sense?
https://github.com/linq2db/linq2db/blob/master/Source/AsyncExtensions.cs

But what is about insert/update/delete?

**Comment by hardhub** [comment]
I see that current ToListAsync does the same thing internally:

```
static Task<T> GetTask<T>(Func<T> func)
		{
			var task = new Task<T>(func);

			task.Start();

			return task;
		}
```

**Comment by hardhub** [comment]
But I think Linq2Db should use internally these methods:
```
    DbConnection.OpenAsync
    DbCommand.ExecuteDbDataReaderAsync
    DbCommand.ExecuteNonQueryAsync
    DbCommand.ExecuteReaderAsync
    DbCommand.ExecuteScalarAsync
    GetFieldValueAsync
    IsDBNullAsync
    DbDataReader.NextResultAsync
    DbDataReader.ReadAsync
    SqlConnection.OpenAsync
    SqlCommand.ExecuteNonQueryAsync
    SqlCommand.ExecuteReaderAsync
    SqlCommand.ExecuteScalarAsync
    SqlCommand.ExecuteXmlReaderAsync
    SqlDataReader.NextResultAsync
    SqlDataReader.ReadAsync
    SqlBulkCopy.WriteToServerAsync
```

**Comment by jogibear9988** [comment]
I've looked into this. It's a big Task...
For me it's also not clear what a GetTableAsync should return.

**Comment by hardhub** [comment]
@jogibear9988 
I do not think we need GetTableAsync. Current GetTable just creates some context/expression objects.

We need only to implement async methods which really perform connection to database.
Something like ToList (internally ExecuteReaderAsync), FirstOrDefault, Insert, Update, including bulk insert BulkCopy (most likely will use WriteToServerAsync) and bulk update which is now possible with Merge method.

**Comment by sdanyliv** [comment]
@jogibear9988, we always have EF sources to check how to implement async version. Bu i agree a lot of work here. I'll take a look after analytic functions.

**Comment by sdanyliv** [comment]
Yes, you can clone EF repository and find many async stuff.

**Comment by ili** [comment]
Async is a big deal. @igor-tkachev said that it is already implemented in v2 branch, but not merge ready. We are looking for a way to merge it

**Comment by hardhub** [comment]
Nice news! Maybe if it is not compatible with v1 it is better to release v2? So we will update code for any breaking changes...

**Comment by jogibear9988** [comment]
In c# 8 we will get async foreach, see: https://www.erikheemskerk.nl/c-sharp-7-2-and-8-0-uncertainty-awesomeness/

**Comment by hardhub** [comment]
@jogibear9988 
How is it related to database queries?

**Comment by sdanyliv** [comment]
@hardhub. this is citation from the article about supporting `IAsyncEnumerable`. It is more related to DBConnection but...
>For a lot of scenarios, like querying a database, your data provider would also have to support this scenario. It will probably be quite some time before third party data providers will start supporting this, if at all.

**Comment by hardhub** [comment]
@sdanyliv 

How do you plan to use it?
I do not see how it can be used for real database work... when you need get some rows, apply some logic (especially on whole result set... for example to detect that nothing is returned).

And do not forget about db context and transaction scope.
I think considering current docs (current implementation) you cannot use anything outside of DbContext.
So if you need to start processing of first row immediately after receiving and of course all of that inside DbContext then what you can do there? Just write to file?

And how much time will be between 2 rows sent over TCP stack to get benefits of async IO?
Most likely both will be in the same network packet.
And how much RDBMS client providers will support it in nearest future?
For now we even cannot get merged 2.0.0 to check how native functions (mentioned above in this thread) are used.. and how it is effective. :)

Even more... I personally do not use DbContext for business transactions.. I am using TransactionScope.
I cannot pass anything further (out of db context) except set of data.

So IAsyncEnumerable is interesting feature but not for database linq provider. Here it is like a toy :)
But for example to enumerate all files from file system (especially network file systems) it can be great (of course it will require support from OS / FS).

If I have misunderstand something let me know ))

**Comment by sdanyliv** [comment]
@hardhub, i'm personally using DbConnection with IoC containers in Web server. In that case DbConnection will be disposed after sending data (after web request). So in async web methods we can return IAsyncEnumerable without worrying about releasing context. Also it can be done at Controller level.

**Comment by hardhub** [comment]
@sdanyliv 
I personally do not like not layered architecture.. But it does not matter for now...
I agree that you can have DbConnection async. It makes sense.. because connection to server is also IO and it is not cheap. And threads can do some other work during this time. But I told only about IAsyncEnumerable because you said in first message "_In c# 8 we will get async foreach_".
It makes me a bit more worried :)

**Comment by sdanyliv** [comment]
@ronnyek, async currently under high development. You can monitor this PR https://github.com/linq2db/linq2db/pull/758
