### ISSUE TITLE
DontEscapeLowercaseIdentifiers will be removed

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2830]
The doc comments on `OracleTools.DontEscapeLowercaseIdentifiers` say:

> This flag is added for backward compatibility and *will be removed later*, so it is recommended to leave it as false and fix mappings to use uppercase letters for non-quoted identifiers.

Please don't.

Yes, Oracle is just a pain and the way they make unquoted names uppercase and quoted names case sensitive is horrible.

I think the pre 3.2 `true` behavior was more beginner-friendly, while the post 3.2 `false` behavior is better suited for some Oracle "situations".

I don't think there's an ideal setting here. I won't debate the default but I would like to ask you to keep that as an option.

Here we're loving linqtodb and we have lots of tables mapped.
Their classes are in PascalCase (`MyLittlePony`) as that's the convention in .net (BTW that's also how we name and use them when hand-writing SQL).
We don't want to have to add `Table` attributes on all of them just to repeat the same name in uppercase (and have to add `IsColumnAttributeRequired = false`, since we don't have attribute on every property either).

We like convention over configuration and would love if you could keep it a viable option in linqtodb.

Thanks!

### Environment details
linq2db version: *3.2.3*
Database Server: *Oracle 12*

**Comment by MaceWindu** [comment]
This comment is outdated and we should update it. We don't plan to remove this flag (and similar flags for some other providers like firebird) for compatibility reasons.
