### ISSUE TITLE
Feature: Oracle INSERT ALL

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2831]
`INSERT ALL` statement: 
https://www.oracletutorial.com/oracle-basics/oracle-insert-all/

This is a weird feature (not sure what the shape of the API would be) and it's rarely useful.

But I happened to need it today so I figured I'd suggest the idea.

It's used internally by linq2db already as one alternative to perform bulk insert in Oracle.

**Comment by jods4** [comment]
I know it's niche, but I kind of need this so I gave it a shot.

My WIP is here.
Feature branch: https://github.com/jods4/linq2db/tree/insert-all
Branch with some testing code for dev: https://github.com/jods4/linq2db/tree/insert-all-tests

If you want to get a feel for the API, look here:
https://github.com/jods4/linq2db/blob/insert-all-tests/Source/TestInsertAll/Program.cs#L49

Before I can create a proper PR, there are 2 points where I'd need your help.

1. I still need to generate SQL for the `WHEN` parts. At first I thought it'd be easy and I could just reuse `SqlWhereClause`.
I'm not so sure anymore, because a `WHERE` references its own query directly and can use table aliases, etc.; and can _not_ use epxressions from its SELECT.
For `WHEN` in `INSERT ALL|FIRST`, it's the opposite: the `WHEN` expression must reference aliases from the `SELECT` output list and can't use anything else (in fact no prefixing is required at all).

2. Similar to, but maybe slightly more complex than (1) I noticed in my testing that the `SqlInsertClause` I re-used don't reference the select fields but tend to reference table from the query directly and repeat expressions.
Ideally here the select query should be left untouched and everything in the `INTO` clauses should be based on aliases from the select output.
The code here is related but I'm not sure it's where it can be fixed: 
https://github.com/jods4/linq2db/blob/insert-all-tests/Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs#L23

3. Parameters are not properly reused. In my test, if I reference the same variable in two different `Into` calls, I get two parameters/aliases: `:param` and `:param_1`.

Can you give me some tips?

**Comment by sdanyliv** [comment]
INSERT ALL in your sample
https://github.com/jods4/linq2db/blob/insert-all-tests/Source/TestInsertAll/Program.cs#L51

Needs source query to perform conditions. You cannot make `When` without knowing to which source it is applied.
So API syntax should be changed:
```cs
q.MultiInsert(sourceQuery)
	.When(
		x => x.N > 10,
		db.GetTable<Dest1>(),
		x => new Dest1 { Name = x.Name, A = x.N }
	)
	.When(
		x => x.N > 100,
		db.GetTable<Dest1>(),
		x => new Dest1 { Name = "This is crazy!", A = x.Computed }
	)
	.Else(
		db.GetTable<Dest2>(),
		x => new Dest2 { X = 1, Y = x.Computed + 2 }
	)
	.InsertFirst();
```

**Comment by jods4** [comment]
@sdanyliv The source query is `q`, it is captured by `MultiInsert` call?
Obviously the `Into` call also reference the source query and they work well (modulo the fact that they don't use the output alias but the source constituents directly).

It's the same kind of API as `INSERT INTO T SELECT`

**Comment by sdanyliv** [comment]
Oh, my fault.

**Comment by sdanyliv** [comment]
1. You can create search condition like here:
https://github.com/linq2db/linq2db/blob/5b0384e10396dec4542b266602b6f343782f5854/Source/LinqToDB/Linq/Builder/MergeBuilder.InsertWhenNotMatched.cs#L71-L76
2. It should be based, nothing has to be touched.
3. Don't worry about parameters right now. Actually from ExpressionTree parsing view - it is two different parameters,

**Comment by jods4** [comment]
1. Great, I should have thought of `MERGE`!

2. No it doesn't work, it must be handled with the same "scoping" as `WHEN`
Currently my code generates this SQL:
```sql
insert all 
  into D (name)
  values (S.name)
select *
from S
```
But Oracle doesn't accept this.
Like `when`, every reference in `values` must be to a `select` output alias. I can't reference source tables like `S` in `values`.

Correct SQL would be:
```sql
insert all 
  into D (name)
  values (name) -- no prefix, this is the select output column
select S.name
from S
```

3. Yeah it works, I'll leave it at that for now. 
It would be nice if we could detect that the same variable was captured and use a single parameter but that's not a hard requirement. (Does MERGE do that? If yes, I could have a look and copy the idea)

**Comment by sdanyliv** [comment]
To remove alias, set to `SqlTableSource.Alias = "$"`

**Comment by sdanyliv** [comment]
> Yeah it works, I'll leave it at that for now.
It would be nice if we could detect that the same variable was captured and use a single parameter but that's not a hard requirement. (Does MERGE do that? If yes, I could have a look and copy the idea)

Parameters not detected by just captured variable reference, but position in expression tree - it is how parameter value is retrieved when we have cache hit to reuse query.

**Comment by jods4** [comment]
> To remove alias, set to SqlTableSource.Alias = "$". But it may affect source query - so we can clone table source in your case or improve SqlBuilder.

Is that right?

Isn't `SqlTableSource` a single table?
The source of `INSERT ALL` is a query.

I gave very basic examples, but a more complex goal is:
```sql
insert all
  into T(a, b, c)
  values (x, y, x + y + z)
select 
  S1.x,
  S2.y,
  S1.x * S2.y as z
from S1, S2
```

So S1, S2 still have aliases in the source query; but `when` and `values` should consume the output aliases `x`, `y` and `z`.

**Comment by sdanyliv** [comment]
Well, it needs debugging. 
https://github.com/linq2db/linq2db/blob/5b0384e10396dec4542b266602b6f343782f5854/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L2815

**Comment by jods4** [comment]
`QueryElementType.MergeSourceTable`
Interesting I'll see what I can do. 
I believe the source of `INSERT ALL` should work the same way as the source of a `MERGE` statement.

Thanks for the pointers.

**Comment by jods4** [comment]
Making good progress, thanks to your tip I've added `WHEN..ELSE` conditions and they work.

I noticed just one problem I'm not sure where it comes from: I tested a condition `.When(x => true, ...)` and instead of being printed as `WHEN 1 = 1` it's completely removed `WHEN    `. Any idea how to prevent that?

So the only big item left is making the context of the source query work correctly (in both WHEN in VALUES). Thanks to your help I figured what needs to be done for this to happen.
I'll try to hijack the `MergeSourceTable` because it's really similar but I may have to create my own.

I'll take a stab at that later this week.

**Comment by sdanyliv** [comment]
>I noticed just one problem I'm not sure where it comes from: I tested a condition .When(x => true, ...) and instead of being printed as WHEN 1 = 1 it's completely removed WHEN . Any idea how to prevent that?

In this case you have to generate 1 = 1 by yourself in SqlBuilder. Empty search condition means `true`.

**Comment by jods4** [comment]
ok, thanks. I saw something like that in the MERGE code I think. Will do.

**Comment by jods4** [comment]
That was harder than I thought... but it looks like everything works fine, eventually! 😌 

Please take a look at #2899
