### ISSUE TITLE
[Firebird] Guid literal generation (ValueToSqlConverter)

### ISSUE THREAD

**Issue by jack128** [linq2db/linq2db#2833]
Current behavior:
```cs
db.InlineParameters = true;
var guid = Guid.NewGuid(); 
db.MyTable.Insert(() => new MyTable { GuidValue = guid });
``` 
will generate
```sql
INSERT INTO MyTable
(
	GuidValue
)
VALUES
(
	'b999f87c-fcc0-4858-b155-264205d8c36a'
)
```
It would be nice to generate native format, something like 

```sql
INSERT INTO MyTable
(
	GuidValue
)
VALUES
(
	X'48DE4C2A3FFF422DABB48357FF84E27F'
)
```
but it's breaking change!
Is it OK to add flag to FirebirdConfiguration ??
```
/// <summary>
/// Specifies how linq2db stored Guids. If true then GUIDs enforced stored as strings
/// </summary>
public static bool IsGuidEncodedAsString { get; set; } = true;
```
IsGuidEncodedAsString = true means old behavior, 

| IsGuidEncodedAsString 	| DataType 	| Result SQL value                       	|
|:---------------------:	|----------	|----------------------------------------	|
| true                  	| any      	| 'b999f87c-fcc0-4858-b155-264205d8c36a' 	|
| false                 	| Guid     	| X'48DE4C2A3FFF422DABB48357FF84E27F'    	|
| false                 	| != Guid  	| 'b999f87c-fcc0-4858-b155-264205d8c36a' 	|

**Comment by MaceWindu** [comment]
I don't want to introduce new flags. We should switch to native format and provide guidelines how to re-configure mapping schema to use old format.
As it is breaking change and user could easly reconfigure mapping schema to use native format I propose to include it into v4 release alongside with big refactoring I'm planning for Firebird provider to support v3 and v4 features: #2693

**Comment by jack128** [comment]
Well, this issue and #2823 are bonded. Fixing one without other is useless, IMHO. Should you close #2826 and make PK to features/firebird_refactoring ?

**Comment by MaceWindu** [comment]
No need to close, I'll just change pr target

**Comment by MaceWindu** [comment]
#2826
