### ISSUE TITLE
[Question] Helper to modify a few field in a select?

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2840]
Sometimes you want to select a class with many fields, and alter just a few of them, e.g. provide a default value if they're null.

You could of course, list all fields in the select statement and change just one or two of them (and that's what you'd have to do in plain SQL) but I was thinking linq2db is in a good position to provide an alternative shorter syntax.

In JS you'd maybe write `{ ...x, name: x.name ?? "<blank>" }` and in C# if you use records you can do `x with { Name = x.Name ?? "<blank>" }`.

Is there some kind of helper function in linq2db that would rewrite a select in such a way?
```csharp
// Returns IEnumerable<Person> with all fields, 
// but Name is tweaked to a slightly different expression.
from x in db.Person
select Sql.AllFieldsWith(x, y => new Person { Name = x.Name ?? "<blank>" })
```

**Comment by sdanyliv** [comment]
Currently no way, but it is possible to open such tweaking possibility.

**Comment by jods4** [comment]
Thanks for the answer.
Feel free to close this or keep it open as a suggestion if you think it's a good idea.

**Comment by MaceWindu** [comment]
Closing due to lack of interest.
