### ISSUE TITLE
Invalid SQL generated for Merge when UpdateWhenMatched() is used with PK-only tables

### ISSUE THREAD

**Issue by johnwright** [linq2db/linq2db#2843]
I have a generic wrapper method for merging like this:

    public static int MergeMany<T>(this ITable<T> table, IEnumerable<T> records)
    {
        return table.Merge()
            .Using(records)
            .OnTargetKey()
            .InsertWhenNotMatched()
            .UpdateWhenMatched()
            .Merge();
    }

This works perfectly for almost all tables that I'm using! The problem is, when using it with a table that has only a single column, that's also the primary key, I see the following exception:

    System.Data.SqlClient.SqlException: 'Incorrect syntax near ';'.'

### Environment details
linq2db version: *linq2db.SqlServer.MS 3.2.3*
Database Server: *Microsoft SQL Server 2019*
Database Provider: *?*
Operating system: *Windows 10*
.NET Framework: *5.0*

**Comment by MaceWindu** [comment]
If I understand it correctly, it generates empty update clause as there is no updateable columns.

I suspect you want to propose to skip update clause generation for such cases?

**Comment by MaceWindu** [comment]
Not a big fan of it but doesn't look it will harm anyone to do it. @viceroypenguin , @sdanyliv  what do you think?

**Comment by sdanyliv** [comment]
I think better to skip Update in this case.

**Comment by johnwright** [comment]
@MaceWindu That's correct, I think the best way would be to treat the update as a no-op when there's nothing to update.

**Comment by viceroypenguin** [comment]
I'm good with this.
