### ISSUE TITLE
TruncateAsync() fails with ORA-02289

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2847]
```TruncateAsync()``` fails with ORA-02289 - sequence does not exist

Does Linq2Db expect a sequence with a special name? 
There is no IDENTITY column set.

### Environment details
linq2db version: 3.2.3
Database Server: Oracle

**Comment by MaceWindu** [comment]
You have column marked as identity, so truncate operation resets associated sequence (don't ask me why, this is some weird legacy stuff....). If sequence name not specified by `SequenceName` attribute, default name inferred as `SIDENTITY_<table_name>`

**Comment by MaceWindu** [comment]
@linq2db, I don't like that there is lack of control over this additional logic around sequences in some operations. Probably we should add more options to control it?

**Comment by HypeillingerChillinger** [comment]
Yes, it is actually a nice feature but it shouldn't be the default.

**Comment by jogibear9988** [comment]
@MaceWindu we should also add a extra function to fluent mapping to set sequence name (at the moment you need to use setAttribute(new SequnceNameAttribute)

**Comment by jogibear9988** [comment]
do we really need more control? Trucate extension method already has resetIdentity parameter, defaulting to true. we could change the default, but everyone who recompiles then with a ne linq2db version will get a changed behavior.

**Comment by jogibear9988** [comment]
maybe we should autodetect sequence name (if possible?)

**Comment by MaceWindu** [comment]
Not sure why we have this open. Truncate already accepts parameter to specify wether we want to reset sequence or not
