### ISSUE TITLE
Feature: Auto Group By

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2851]
Having to list all columns that are not part of aggregates in SQL has always felt a bit redundant to me.
Of course you might want to add _more_ columns or do other fancy stuff, but at a minimum all columns in an aggregate in SELECT must be listed.

It would be handy if linqtodb could optionnally generate the group by for me.

Maybe you could add `Sql.GroupBy.Auto` and allow this?
```csharp
table
  .GroupBy(t => Sql.GroupBy.Auto)
  .Select(t => new
  {
    t.Id, t.FirstName, t.LastName, 
    Count = Sql.Ext.Count().ToValue,
  })

// Generates:
SELECT Id, FirstName, LastName, COUNT(*)
FROM Table
GROUP BY Id, FirstName, LastName
```

Or maybe a new method `GroupByAuto` or something like this?

**Comment by sdanyliv** [comment]
I don't think we will start this gambling. There are a lot of other things to do.

**Comment by MaceWindu** [comment]
Ah, infamous difference in behavior of LINQ `GroupBy` method and SQL `GROUP BY`. One of the biggest sources of confusion :rofl:  (actually :crying_cat_face: )
