### ISSUE TITLE
Broken T4 generator for SqlServer

### ISSUE THREAD

**Issue by ivanovmv90** [linq2db/linq2db#2852]
T4 generator throws errors
`Loading the include file '$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude' returned a null or empty string. The transformation will not be run.`
`Loading the include file '$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude' returned a null or empty string. The transformation will not be run.`

Template file:
```
<#@ template language="C#" debug="True" hostSpecific="True"                           #>
<#@ output extension=".generated.cs"                                                  #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude"     #>
<#
	DataContextName  = "DbContext";
	GenerateLengthProperty = true;
	NamespaceName = "MyNamespace";

	// Enables loading of functions and procedures information
	GetSchemaOptions.GetProcedures = false;

	// Filter tables by prefixes and a white list
	var tables = new string[] 
	   {
	   };
	GetSchemaOptions.LoadTable = (LoadTableData d) => tables.Contains(d.Name);

	// Disable use of System.Char type in generated model for text types
	// with length 1 instead of System.String
	GetSchemaOptions.GenerateChar1AsString = true;

	LoadSqlServerMetadata(".", "MyDatabase"); // Integrated Security

	GenerateModel();
#>
```
Looks like $(LinqToDBT4SqlServerTemplatesDirectory) is null for some reason.
Works fine on 3.2.2

### Environment details
linq2db version: 3.2.3
Database Server: MSSQL 2019
Database Provider: linq2db.SqlServer
Operating system: Windows 10
.NET Framework: netstandard2.1

**Comment by MaceWindu** [comment]
3.2.3 (https://github.com/linq2db/linq2db/pull/2751) changed msbuild properties, used by t4. Looks like I've forgot to mention it in release notes. If you will check `CopyMe.SqlServer.tt.txt` for new version it now has following header:
```
<#@ template language="C#" debug="True" hostSpecific="True" #>
<#@ output extension=".generated.cs"                        #>

<#@ include file="$(LinqToDBT4SqlServerTemplatesPath)LinqToDB.SqlServer.Tools.ttinclude" once="true" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesPath)PluralizationService.ttinclude"     once="true" #>
```

`LinqToDBT4SqlServerTemplatesDirectory` -> `LinqToDBT4SqlServerTemplatesPath`
