### ISSUE TITLE
MetaData for an external Model Class

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#286]
I've described my issue in the msdn forum [here](https://social.msdn.microsoft.com/Forums/office/en-US/1b3a2215-19fd-43ee-86bf-22580e0dd8a5/dataannotations-in-a-derived-or-imported-class).

Basically, I'm trying use the MetadataType this way:

```c#
[Table(Name = "table_class")]
[MetadataType(typeof(ModelClassMetadata))]
public partial class ModelClass
{
	
}
public class ModelClassMetadata {

	[Column(Name = "my_code")]
	public string MyCode {get; set;}

}

//[Table(Name = "table_class")]
public partial class ModelClass
{
	//[Column(Name = "my_code")]
	public string MyCode {get; set;}
}
```
Is that do-able?
Am I supposed to write my custom MetaDataProvider?
Or is there something similar to [Fluent API](https://msdn.microsoft.com/en-us/data/jj591617.aspx) for Linq2DB?

Maybe is there a Fluent Mapping for Linq2DB?
This [issue](https://github.com/linq2db/linq2db/issues/26) I've found is promising... 

Please, advise

**Comment by MaceWindu** [comment]
For fluent mapping you can check those tests: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Mapping/FluentMappingTest.cs

MetadataType is not supported now, but you can use:
- linq2db attributes (Table/Column/MapValue...)
- system.data.linq.mapping.* attributes
- fluent mapping
- xml mapping
- implement custom metadata reader

Looks like that's all options available now

**Comment by giuliohome** [comment]
Thank you!!!
I will study your links and suggestions and  will reopen only if I need more help

**Comment by giuliohome** [comment]
Sorry,
what if a field is inherited from the base class?
How should I change my code above?
Thanks
