### ISSUE TITLE
Null is True in conditions

### ISSUE THREAD

**Issue by ademchenko** [linq2db/linq2db#2862]
Hi, folks. Thanks a lot for that awesome library linq2db. I have a small question.

Let me create a very simplified example of my real case. Suppose I have some table transactions(int id, int chainId, string type).
Now I would like to find all transactions in the chain which are not closed:

```
var someChainId = 12;
var notClosedTranactions = dataConnection.Transactions
.Where(t => t.chainId = someChainId && type = 'typeOpen')
.Where(t => t.Id > dataConnection.Transactions.Where(tr => tr.chainId = someChainId && type == 'typeClose').Max(tr => tr.Id)
```
It might happen that there are no closing transactions at all. In that case the above query will return empty instead of all rows of the chain because the condition Id > dataConnection.Transactions.Where(tr => tr.chainId = someChainId && type == 'typeClose').Max(tr => tr.Id) will not be TRUE.

There is  a solution to get the correct result but it seem to be a little bit awkward in terms of C# language so I'd like to ask if there's more 'C# - natural' way to express that query:

```
var someChainId = 12;
var notClosedTranactions = dataConnection.Transactions
.Where(t => t.chainId = someChainId && type = 'typeOpen')
.Where(t => (bool?)(t.Id > dataConnection.Transactions.Where(tr => tr.chainId = someChainId && type == 'typeClose').Max(tr => tr.Id)) ?? true);

//Seems pretty odd to convert boolean (in terms of C#) expression to bool? and then back to bool :-)
```
Thanks in advance!

### Environment details
Database Server: *PostgreSQL*

**Comment by sdanyliv** [comment]
Try to rewrite your query:
```cs
var someChainId = 12;
var notClosedTranactions = dataConnection.Transactions
    .Where(t => t.chainId = someChainId && type = 'typeOpen')
    .Where(t => !dataConnection.Transactions.Where(tr => tr.chainId = someChainId && type == 'typeClose' && tr.Id > t.Id).Any());
```
