### ISSUE TITLE
How to insert parent entity together with its child entities?

### ISSUE THREAD

**Issue by sgashua** [linq2db/linq2db#2864]
I inserted parent including children. But child tables are empty.

How to insert all together in one insert instead of few inserts?

**Comment by sdanyliv** [comment]
No way. Linq2db has no change tracker. You can insert parent - get identity column, update children with parentid and then `BulkCopy` children.

**Comment by sgashua** [comment]
Ok noted. Thanks. Just hope it can be implemented.
