### ISSUE TITLE
Question: Is there a way with an annotation to map a DateTime to a "HH:mm" format?

### ISSUE THREAD

**Issue by TsakiDev** [linq2db/linq2db#2869]
It works when getting the data from the database but on update or insert it saves it as "yyyy-MM-dd HH:mm".

**Comment by sdanyliv** [comment]
Question is: Is data in database is bad? Or you just noticed this format in logged query?

**Comment by TsakiDev** [comment]
There is need to support a legacy application at least until it's re-written.

**Comment by sdanyliv** [comment]
Have you tried to specify `HasConversion` for such fields?
https://github.com/linq2db/linq2db/blob/83de70f7ee9a7d4e2052cf2acbabc73428c019d1/Tests/Linq/Linq/ValueConversionTests.cs#L149

**Comment by TsakiDev** [comment]
How can I do that?

**Comment by sdanyliv** [comment]
I gave you a link to the sample (test)
