### ISSUE TITLE
Doesn't work Sql.NewGuid()

### ISSUE THREAD

**Issue by Nelo-cool** [linq2db/linq2db#2886]
Hello guys!
What is it? Sql.NewGuid() doesn't working in simple case:

```
await db.Controller
                    .Where(x => !x.Object.Deleted)
                    .Where(x => x.ProjectId == projectId || projectId == null)
                    .OrderBy(x => Sql.NewGuid())
                    .Select(x => x.Id)
                    .FirstAsync();

==> Ignore OrderBy ==>

SELECT TOP (@take)
	[x].[Id]
FROM
	[Controller] [x]
		INNER JOIN [Object] [a_Object] ON [x].[Id] = [a_Object].[Id]
WHERE
	[a_Object].[Deleted] = 0

```
### Environment details
linq2db version: 3.2.3
Database Server: MS SQL
Database Provider:  
Operating system: Win10
.NET Framework: 5

**Comment by sdanyliv** [comment]
Function `Sql.NewGuid()` should be marked as `IsPure = false`. Missed that, otherwise optimization will remove such `OrderBy`.

**Comment by Nelo-cool** [comment]
How do I mark it? Or only you?

**Comment by sdanyliv** [comment]
Here we have to add `IsPure = false`
https://github.com/linq2db/linq2db/blob/cecc6a4808029a331ee38f82e14c1249a878fcb7/Source/LinqToDB/Sql/Sql.cs#L226

**Comment by Nelo-cool** [comment]
I thought so, thank you!
![image](https://user-images.githubusercontent.com/902820/110795816-4e8da180-8288-11eb-8a3a-743a5967cb5b.png)

**Comment by sdanyliv** [comment]
@Nelo-cool, unfortunately we have bug in `SqlFunctionAttribute` which do not respect this flag. Only `SqlExpressionAttribute ` works right now.

**Comment by Nelo-cool** [comment]
@sdanyliv Thanks! Excuse me guys, I thought that I would have time to make the commit myself, but you are faster:) Waiting for released ;) In my case I have many workarounds.
