### ISSUE TITLE
WHERE EXISTS for multi-column VALUES

### ISSUE THREAD

**Issue by coudy** [linq2db/linq2db#2889]
I can't find a way to do a `WHERE EXISTS` for multiple columns based on a C# collection with multiple fields/columns.
I've tried the following but am getting "Sequence ...Ids cannot be converted to SQL."

```
from t in db.Stuff
where Ids.Any(i => i.Id == t.Id && i.Id2 == t.Id2)
select ...
```

`Ids` is a .NET collection and I'm trying to get back all rows that match both fields.

### Environment details
linq2db version: 3.2.3
Database Server: SQL Server 2019
Database Provider: System.Data.SqlClient
Operating system: Windows Server
.NET 5

**Comment by sdanyliv** [comment]
Currently `linq2db` supports only variant with Primary Key.
```cs
var objects = Ids.Select(x => new Stuff { Id = x.Id, Id2 = x.Id2 }).ToList();

from t in db.Stuff
where objects.Contains(t)
select ...
```
But if there are a lot of such Ids - better to do that via temporary table.
```cs
using var temp = db.CreateTemporaryTable(Ids);

from t in db.Stuff
from i in temp.InnerJoin(i => i.Id == t.Id && i.Id2 == t.Id2)
select ...
```
