### ISSUE TITLE
MS Access Long Integer field should be (long c#) and not (int c#)

### ISSUE THREAD

**Issue by purell** [linq2db/linq2db#289]
Hi,

If we set a field [Long Integer] in MS Access the data type convert in the c# model is [int]. It should be [long] instead. MS Access [Long Integer] is 64 bits fields and (c# Int) is 32 bits data type.

This is a bit annoying as I have to store 32 bits number UNSIGNED and MS Access do not support unsigned type. So the only way for me is to store the data as 64 bits integer (Long Integer).

Best regards,

**Comment by purell** [comment]
Anyone have a clue on this mismatch ?

I took a look in the file (DataProviderBase.cs) and (AccessDataProvider.cs) but I don't really understand those type and where they come from.

On MS Access I set my field type as "Long Integer" and I'm expecting having a C# mapping to Long (64 bits) not an Int (32 bits).

**Comment by purell** [comment]
Or maybe it is a limitation of the JET driver ? I do not see any LONG in this lis :(

https://en.wikibooks.org/wiki/JET_Database/Data_types

I hope someone here can confirm me that. Else I will have to use DOUBLE to store LONG INTEGER for primary key. This is a bit annoying.

**Comment by igor-tkachev** [comment]
Access Long data type is a 32-bit integer.

**Comment by purell** [comment]
So how can we get a 64 bits integer type ?

**Comment by igor-tkachev** [comment]
Are you sure that Access supports it? I tried to use INSERT statement to insert a value like 6000111222 into long type column and it did not work.
