### ISSUE TITLE
Mark prop as identity/pk without using an attrib on the property itself

### ISSUE THREAD

**Issue by akempe** [linq2db/linq2db#2896]
Is there a way to indicate the Primary Key and Identity of a table via attributes on class rather than the property itself? I'm trying to migrate to linq2db and need to mark properties as PK/Identity but can't modify the partial class they're defined in. I could possibly use a ColumnAlias attribute, but that feels messy. Is there a better way? I've been digging through the source but as I'm new to this project, having some guidance re. where to look would be helpful. I have to do this for many tables, if that influences my options. thanks!

**Comment by sdanyliv** [comment]
You have to define `MappingSchema` and reuse when creating `DataConnection`
```cs
var ms = new MappingSchema();
var builder = ms.GetFluentMappingBuilder();
builder.Entity<SomeEnity>()
   .Property(e => e.Id)
   .IsPrimaryKey()
...

using var dc = new DataConnection(..., ms);
// or
using var dc = new DataConnection(...);
dc.AddMappingSchema(ms);
```

**Comment by akempe** [comment]
Thanks so much for the details and quick response @sdanyliv . It's a pity that once can't co-locate this info with the models.

Just checking, if I just wanted to indicate the `Identity` column, would there be an alternative to do that with just attributes?

**Comment by sdanyliv** [comment]
It's obvious:
```cs
builder.Entity<SomeEnity>()
   .Property(e => e.Id)
   .IsPrimaryKey()
   .IsIdentity()
```

**Comment by akempe** [comment]
Sorry, maybe my question wasn't clear - your previous example only showed indicating `IsPrimaryKey` for the entity. I wanted to check that there wasn't a way to use only attributes to indicate the `identity` column via something like the `Table` attribute. I wanted to be sure that the PrimaryKey didn't need some special treatment and so you didn't suggest some other option. thanks again. I think I'm going to go with the `ColumnAlias` as it keeps things located together - making it easier to see what's going on.
