### ISSUE TITLE
Feature - query tag (TagWith)

### ISSUE THREAD

**Issue by jlukawska** [linq2db/linq2db#2903]
There is one helpful feature in ef core: TagWith. It adds custom tag as a comment before SELECT query. This feature can be very helpful to identify the heaviest queries in a database, because such tag will be stored together with query text in the database query plan cache.

I haven't found anything similar in linq2db and I think it would be great to implement this here as well.

**Comment by sdanyliv** [comment]
Well, I thought about this. Probably we should start implementation if it is really helpful.

**Comment by jlukawska** [comment]
@sdanyliv , actually I've created PR which implements this feature already: #2902 :)

**Comment by sdanyliv** [comment]
Haha, nice ;)

**Comment by sdanyliv** [comment]
Well, before I start reviewing. `TagWith` will have collision with our EF Core integration, so better to name it `TagQuery`.
Final query, which combined from queries with has such tag, should contain all tags.

**Comment by jlukawska** [comment]
@sdanyliv sure, I'll check and correct it.
