### ISSUE TITLE
IsNotColumn does not work when inherited

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#291]
Look at my code for Fluent Mapping in a derived class

``` c#
public enum GenericItemType
{
    DerivedClass = 0 
}

internal class MyContext : LinqToDB.Data.DataConnection
{
    internal MyContext(string context) : base (context)
    {

        MappingSchema.GetFluentMappingBuilder()

            .Entity<CommonLibrary.BaseClass>().HasTableName("my_table")
            .HasAttribute(new LinqToDB.Mapping.InheritanceMappingAttribute()
               { IsDefault = true , Type = typeof(MyFramework.DerivedClass) ,
                          Code = GenericItemType.DerivedClass 
                          }
                        )
                .Property(t => t.MyCol1).HasColumnName("my_col1")
                .Property(t => t.NotACol).IsNotColumn()


        .Entity<MyFramework.DerivedClass>().HasTableName("my_table")
            .Property(t => t.SomeOtherField).HasColumnName("my_other_col")
```

where

``` c#

public class DerivedClass : BaseClass
    {
        [Column(IsDiscriminator = true)]
        public GenericItemType itemType = GenericItemType.DerivedClass ;

        public string SomeOtherField;
```

where BaseClass has attributes, not properties 

``` c#
public class BaseClass
    {
        public string MyCol1;
        public string NotACol;
```

Setting the attribute .IsNotColumn() does _not_ take effect unfortunately!

**Comment by giuliohome** [comment]
I've seen the example from #162 (fixed with #163)
So *maybe* InheritanceMappingAttribute and IsDiscriminator are not required (but consider my next line about derived attributes) for derived classes (furthermore I understand that IsDiscriminator must be a column?).
The problem however is that the example in #162 does *not* work if we are speaking of deriving class attributes (no getter/ setter) instead of calss properties.

**Comment by giuliohome** [comment]
At the moment I can work around this with a little rework, refactoring the basis class attributes as properties.

**Comment by giuliohome** [comment]
I have to reopen, because there is also another error when using IsDiscriminator.
A simple query without join but with only a where conditions returns: "Incorrect syntax near ')'" 
because the WHERE is generated as 
```sql
WHERE
	(()) AND ...
```
Adding a join does the trick. So InheritanceMappingAttribute and IsDiscriminator are supposed to work. And we have 2 possible issues in this case: IsNotColumn being not considered for attributes and the where condition malformed as explained above

**Comment by ili** [comment]
can you provide minimum failing example?

**Comment by jogibear9988** [comment]
There have been many fixes about inheritance, maybe we can close

**Comment by MaceWindu** [comment]
Closing, as https://github.com/linq2db/linq2db/pull/1599 doesn't show any issues with this functionality for recent version. Probably already fixed

Reopen if it is still an issue
