### ISSUE TITLE
BLOB Length on Oracle

### ISSUE THREAD

**Issue by brd-mikek** [linq2db/linq2db#2913]
Hi guys!

Thank you for excellent work, big fan!

I want to query length of a BLOB without downloading full blob.
If I have .Length in LINQ query, it downloads the whole blob.
If I use Sql.Length() function, it is trying to convert to 8000-long binary which is wrong.
I tried on Oracle and SqLite with the same outcome.
I am on version "2.9.6"

Thanks,
Mike K

P.S. Length may be long, not int!

```
[Table(Name="BLOBTABLE")]
public partial class BLOBTABLE
{
	[Column("ID"), PrimaryKey(1)] public int              ID { get; set; }
	[Column("BLOBDATA"), Nullable] public byte[]          BLOBDATA { get; set; }
}
```

This is attempt with .Lengt:

```
var q = db.BLOBTABLE
	.Select(x => x.BLOBDATA.Length)
	.First();
```

ORACLE:
```
	SELECT
		x.BLOBDATA
	FROM
		BLOBTABLE x
	WHERE
		ROWNUM <= 1
```
		
SQLITE:
```
	SELECT
		[x].[BLOBDATA]
	FROM
		[BLOBTABLE] [x]
	LIMIT 1
```
	
This is attempt with Sql.Length:
	
```
var q = db.BLOBTABLE
	.Select(x => Sql.Length(x.BLOBDATA))
	.First();
```
	
ORACLE:
```
	SELECT
		Length(Cast(x.BLOBDATA as Raw(8000)))
	FROM
		BLOBTABLE x
	WHERE
		ROWNUM <= 1
```
	
SQLITE:
```
	SELECT
		Length(Cast([x].[BLOBDATA] as VarBinary(8000)))
	FROM
		[BLOBTABLE] [x]
	LIMIT 1
```

**Comment by jogibear9988** [comment]
see #2691 and #2699 
will be fixed in next version

**Comment by brd-mikek** [comment]
Any guidance on when next version is planned for release?

**Comment by sdanyliv** [comment]
@brd-mikek, this Thursday.
