### ISSUE TITLE
Interceptors migration

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#2927]
For version 4 we add interceptors support. To get familirar with e.g. check [EF.Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors) implementation.

We plan to remove bunch of existing static options and events and replace them with interceptors. #2728 already introduced initial support with couple of interceptors (also check [release notes](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#interceptors))

Below is the list of additional interceptors we should implement:
- [x] static `DbCommandProcessorExtensions` and `IDbCommandProcessor` interface [here](https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/Data/DbCommandProcessor) should be replaced with corresponding events on `ICommandInterceptor`
- static `RetryPolicy` [factory](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Configuration.cs#L321) replaced with event on `IConnectionInterceptor`
- [x] `IDataContext.OnClosing` [event](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/IDataContext.cs) + `DataConnection.OnClosing/OnClosed` [events](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L1109-L1113) + `DataContext.OnCLosing` [event](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataContext.cs#L384) replaced with events on `IConnectionInterceptor`. Note that removal of event from `IDataContext` could require interceptors support added to remote context
- [x] `IEntityServices` [interface](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/IEntityServices.cs) +  `DataConnection.OnEntityCreated` [delegate](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L1116) and `DataContext.OnEntityCreated` [delegate](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataContext.cs#L387) replaced by event on `IConnectionInterceptor` (or new interceptor like IEntityInterceptor?)

Consider migration:
- [Compilation.SetExpressionCompiler()](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Configuration.cs) replaced with interceptor. Probably no, as it doesn't fit good for interceptor.

@linq2db please provide your comments on proposed changes if any or suggest additional interceptor events

**Comment by MaceWindu** [comment]
Another candidate is [`MappingSchema.EntityDescriptorCreatedCallback`](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/MappingSchema.cs#L1517). Should be done it the way to solve #1592 and #1822

**Comment by sdanyliv** [comment]
@MaceWindu, it should be interceptor inside `MappingSchema`, also we have to be sure that `ConfigurationID` takes in care which interceptors are applied.

**Comment by MaceWindu** [comment]
#2941
