### ISSUE TITLE
BulkCopy with DataContext

### ISSUE THREAD

**Issue by comik** [linq2db/linq2db#2928]
Hey!
First of all, thank you for such a good library.

I'm facing a problem with BulkCopy using DataContext. 
The way I'm trying to run a bulk insert:
```c#
context.DataProvider.BulkCopy(context.GetTable<T>(), new LinqToDB.Data.BulkCopyOptions(), items);
```

And it fails with an exception (see below). 
A short pre-story: I'm using DataContext to prevent connection leaks and for proper transaction handling, thus using DataConnection for bulk inserting is highly undesirable.

```
Exception message: Unable to cast object of type 'LinqToDB.DataContext' to type 'LinqToDB.Data.DataConnection'.
Stack trace: System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'LinqToDB.DataContext' to type 'LinqToDB.Data.DataConnection'.
  Source=linq2db
  StackTrace:
   at LinqToDB.DataProvider.MultipleRowsHelper`1..ctor(ITable`1 table, BulkCopyOptions options)
   at LinqToDB.DataProvider.BasicBulkCopy.MultipleRowsCopy1[T](ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at LinqToDB.DataProvider.BasicBulkCopy.BulkCopy[T](BulkCopyType bulkCopyType, ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
```

### Environment details
linq2db version: *v3.3.0*
Database Server: *MySQL v5.7.31*
Database Provider: *MySQL.Data v8.0.23/linq2db.MySql v3.3.0*
Operating system: *Microsoft/Unix*
.NET Framework: *.NET Core 3.1*

**Comment by sdanyliv** [comment]
@comik, it needs design review. For now I suggest to use this workaround:
```cs
public static DataConnection CreateDataConnection(DataContext dc)
{
	var method = typeof(DataContext).GetMethod("CreateDataConnection", BindingFlags.Instance | BindingFlags.NonPublic);

	return (DataConnection)method.Invoke(dc, Array.Empty<object>());
}
```
```cs
using var dc = CreateDataConnection(context);
dc.BulkCopy(dc.GetTable<T>(), new LinqToDB.Data.BulkCopyOptions(), items);
```

**Comment by comik** [comment]
@sdanyliv Thank you!
It works, though for some reason it doesn't respect a transaction.
This would work as a bandaid, but I believe the full BulkCopy support for DataContext would be wonderful.

Thanks again and have a great day!
