### ISSUE TITLE
Race condition in DataReader Close function

### ISSUE THREAD

**Issue by gkathire** [linq2db/linq2db#2938]
I'm having a weird problem. I call the ToListAsync function to get all the items and then when I call BeginTransactionAsync function; I'm getting the "There is already an open DataReader associated" error. When I put a await Task.Delay(1000), Im not getting any errors. Can anyone else let me know why this is happening ? It just happens in one part of the code and it is not happening in other places. 

Btw I just use the expression expansion functions (ToListAsync etc) and I dont use IQueryable or IEnumerable objects in a loop. I dont have any navigational properties in the poco as well.

### Environment details
linq2db version: 3.0.0 & 3.3.0
Database Server: LocalDB
Database Provider: SqlServerDataProvider - SqlServerVersion.v2008 ( SqlServerProvider.SystemDataSqlClient & SqlServerProvider.MicrosoftDataSqlClient)
Operating system: Windows 10
.NET Framework: .Net Core 5

**Comment by sdanyliv** [comment]
Any samples?  Can you try to reproduce in small application?

**Comment by MaceWindu** [comment]
Race conditions means multi-threading involved, but database connection is not thread-safe. Could it be that you are using it in non-thread-safe way?

**Comment by gkathire** [comment]
@sdanyliv Let me see if I can create a sample for you.

@MaceWindu Currently, I'm using only linq2db's async functions in my asp.net core 5.0 view->service->repo functions. I have my own DBManager class which instantiates the DataConnection internally. My DBManager is instantiated with the Scoped Lifetime (using the DI) and except for the async calls, I dont have any manged thread accessing DBManager object.

Let me provide the DBManager code and demo shortly.

**Comment by gkathire** [comment]
@sdanyliv @MaceWindu  I think the problem is with my code. When I added additional logging, I found that one Async Db is called without await and thats screwing up the subsequent db call. I think the well thought out Connection's OnTrace function help nail this issue.

Thanks a lot.
