### ISSUE TITLE
Likely bug in BasicSqlOptimizer

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2943]
I saw this while reading source code:
https://github.com/linq2db/linq2db/tree/42afc3ae9cbdf311ef6dfb4af5152c3914b33263/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#L2882-L2886

That condition cannot be true, can it?
`projectionItems` being the union of `columnItems` + something else, it cannot have less items than `columnItems` alone.

**Comment by jods4** [comment]
Other possible bug:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/JoinOptimizer.cs#L675-L680

The `if` inside this loop is always true, because `fields` is just a `Select` of `v`, so `fields.Length == v.Count` has to be true.
I wonder if that condition can be removed, or if you intended to exclude the fields where `GetUnderlayingField` returns `null`.

**Comment by MaceWindu** [comment]
First issue confirmed (on bigger scale), looking into second report

**Comment by MaceWindu** [comment]
Second issue looks like remnant of refactoring where it contained filter, I will remove it
https://github.com/linq2db/linq2db/pull/1360/files#diff-ae2c4ae9cc1e40a623f8dd877821ce631229d070fd892ef591b1979de689d5cfL675

**Comment by MaceWindu** [comment]
OK, second report is even more tricky. We currently don't even have test that calls into `GetKeysInternal` method. So first we should create test or remove this code if it is not needed...
