### ISSUE TITLE
3.3 Regression in SelectQuery?

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2963]
Assume that `MySequence` is a property decored with  `Sql.Expression("MY_SEQUENCE.nextval", ServerSideOnly = true)`, so basically a placeholder for a sequence nextval.

The following query used to work in 3.2 (Oracle provider):
```csharp
db.SelectQuery(() => db.MySequence).AsEnumerable().Single()
```
It's meant to fetch the next sequence value and generates:
```sql
SELECT MY_SEQUENCE.nextval FROM DUAL
```
Note that the `AsEnumerable()` is just there to prevent LinqToDb from appending a `FETCH NEXT 1 ROW ONLY`, which would be an unsupported Oracle combination with `nextval`, and shouldn't matter.

With 3.3 it crashes during query generation.
It throws `ArgumentException` _Value does not fall within the expected range_ when trying to set the value of a DbParameter named `"db"` to the value `db` (i.e. the `DataConnection` itself).

**Comment by jods4** [comment]
More cases: method, property, extension methods all fail the same way.
Static method does work.

**Comment by jods4** [comment]
Work-around: Adding an explicitly empty `argIndices` works.
`Sql.Expression("SQ_QXT_FILE.nextval", argIndices: new int[0], ServerSideOnly = true)`

**Comment by sdanyliv** [comment]
Yes, it is correct workaround. Preparing fix.
