### ISSUE TITLE
Issue with Where Clause on Joined Tables with Dynamic Columns

### ISSUE THREAD

**Issue by dylanblack** [linq2db/linq2db#2969]
I'm having an issue trying to apply a Where clause to a table with a dynamic column when I've joined 2 tables together and selected the results of both tables.

The issue appears to be that an ArgumentException is thrown when trying to access a dynamic field on one of the selected tables within the Where clause, due to accessing it via a property on the selected results (see example below where I am joining 2 tables, selecting the combined result, and then attempting to apply a Where clause to a column on one of the tables).

My table classes inherit from a common AbstractModelBase class that define an Id property.

My question is can this library support Where clauses on dynamic columns where more than one table has been selected, and if so, how do I go about getting this to work?

Thanks!

```c#
var query = entityTable
        .Join(
            relationshipTable,
            SqlJoinType.Left,
            (x, y) =>
                x.Id == Sql.Property<long>(y, "LeftHandId")
                && y.Deleted == 0 ,
            (x, y) =>
                // Select both tables in results, to apply further filtering
                new {x, y}
        )
    .Where((z) =>                                
                // This works with SQL string, but that's not our preferred solution
                //Sql.Expr<bool>("([y].RightHandId in (1, 2, 3, 4, 5) or [x].Visibility = 2)")
                
                // This throws an exception as it can't be converted to SQL
                //(long)z.x.Fields["Visibility"] == 2
                
                // This throws an argument exception from MemberHelper.cs line 56, though looks like it should work based on docs
                //Sql.Property<long>(Sql.Property<AbstractModelBase>(z, "x"), "Visibility") == 2
                
                // These are converted to SQL that reads 1 = 0
                //Sql.Property<long>(z, "x.Visibility") == 2
                //Sql.Property<long>(z, "[x].Visibility") == 2
                
                // This throws an argument exception from MemberHelper.cs line 56 because it's a MemberAccess node type
                //Sql.Property<long>(z.x, "Visibility") == 2                            
        )
    ;
```

### Environment details
linq2db version: 2.9.0
Database Server: SQL Server
Database Provider: SqlProvider
Operating system: Windows 10
.NET Framework: Core 3.0

**Comment by sdanyliv** [comment]
Better to post models and we figure out what to do.

**Comment by dylanblack** [comment]
I've upgraded our references to v2.9.8, but I'm still getting the same issue.

The models are pretty straightforward - there's a base class with an ID and a set of dynamic fields, and then 2 classes inheriting from that with a number of dynamic fields on each:

```c#
    // This is the base class
    public class AbstractModelBase
    {
        public long Id { get; set; }

        [DynamicColumnsStore] public IDictionary<string, object> Fields { get; set; }
    }

    public class Stakeholder : AbstractModelBase
    {
    }

    public class ProjectRelationship: AbstractModelBase
    {
    }

    // we define the other classes dynamically
    var ms = new MappingSchema();
    
    // Define a Stakeholder class with a Visibility property
    ms.GetFluentMappingBuilder()
        .Entity<Stakeholder>().HasTableName("Stakeholder")
        .HasPrimaryKey(x => Sql.Property<int>(x, "ID"))
        .Property(x => Sql.Property<long>(x, "Visibility"));
    
    // Define a ProjectRelationship class with a LeftHandId and a RightHandId property
    // The LeftHandId can be a reference to the Stakeholder Id
    ms.GetFluentMappingBuilder()
        .Entity<ProjectRelationship>().HasTableName("ProjectRelationship")
        .HasPrimaryKey(x => Sql.Property<int>(x, "ID"))
        .Property(x => Sql.Property<long>(x, "LeftHandId"))
        .Property(x => Sql.Property<long>(x, "RightHandId"));
```

The problem occurs when I try to select both the Stakeholder and ProjectRelationship models from the join and then apply a Where clause, the logic of which needs to be based on properties from both entities.

**Comment by dylanblack** [comment]
After some more investigation, I can actually get this to work as expected in isolation, so I suspect it has something to do with our dynamic generic type system interfering with Linq2Db trying to identify dynamic columns.
