### ISSUE TITLE
Connection seems not released

### ISSUE THREAD

**Issue by DrunkLepus** [linq2db/linq2db#297]
I am using the tool to connect to my access database to request some data for my web application. However, I notice after accessing the DB for maybe couple dozen times, the access database becomes unavailable. I have to manually recycle the application pool to bring it back online.

the way I'm using it is like following code
```
using (var db = AccessTools.CreateDataConnection(connectionString))
            {
                var result = db.GetTable<SysUser>().Where(c => c.State.Equals("Y")).ToList();
                return result;
            }
```
and just access the entity returned.
Please help, thank you!

**Comment by pebezo** [comment]
It looks like you're doing it right. What db are you using and can you share what AccessTools looks like?

**Comment by DrunkLepus** [comment]
Thanks for replying.
It's a Access 2013 database and a ASP.NET and C# Web application talks to the database, in fact the application only reads data and no data writing.
There is also Microsoft Access Database engine 2010 - version 14.0.7015.1000 installed.
Not sure if above answers question of AccessTools since I am not sure what AccessTools is...

Thank you again!
