### ISSUE TITLE
OData contains does not generate the correct sql

### ISSUE THREAD

**Issue by DefinitelyADev** [linq2db/linq2db#2970]
In this example the following query gets generated:

```sql
DECLARE @TypedProperty_1 VarChar(3) -- String
SET     @TypedProperty_1 = '%2%'
      SELECT
        `$it`.`Id`,
        `$it`.`Name`
      FROM
        `test_db`.`Students` `$it`
      WHERE
        CASE
                WHEN `$it`.`Name` IS NULL THEN NULL
                ELSE `$it`.`Name` LIKE @TypedProperty_1 ESCAPE '~'
        END = 1
```

Though it should have generated this query (EF Core generated):

```sql
DECLARE @TypedProperty_1 VarChar(3) -- String
SET     @TypedProperty_1 = '%2%'
      SELECT
        `$it`.`Id`,
        `$it`.`Name`
      FROM
        `test_db`.`Students` `$it`
      WHERE
(@__TypedProperty_0 LIKE '') OR (LOCATE(@__TypedProperty_0, `a`.`Name`) > 0)
```

Additionally, when using the EFCoreTools library, it generates this query:

```sql
DECLARE @TypedProperty_1 VarChar(3) -- String
SET     @TypedProperty_1 = '%2%'

SELECT
        `$it`.`Id`,
        `$it`.`Name`
FROM
    `test_db`.`Students` `$it`
WHERE
    CASE
        WHEN `$it`.`Name` IS NULL
            THEN NULL
        ELSE NULL
    END = 1
```

### Steps to reproduce
[ODataTestProject.zip](https://github.com/linq2db/linq2db/files/6377844/ODataTestProject.zip)
1. Run the sql file inside the zip to seed data.
2. Alter the settings.
3. Run the project.
4. Navigate to: https://localhost:5001/api/values?$filter=contains(Name,'2')

### Environment details
linq2db version: 3.3.0
Database Server: MySql 8.0.21
Database Provider: linq2db.MySql v3.3.0
Operating system: Windows 10
.NET Framework: .NET 5

**Comment by sdanyliv** [comment]
Thanks for reporting. Looks like a bug.

**Comment by sdanyliv** [comment]
Trying to reproduce and looks like your query is not valid. Should be
https://localhost:5001/api/values?$filter=contains(Name,'2')

**Comment by TsakiDev** [comment]
@sdanyliv  Oh yes sorry it was just a typo when creating the issue.

**Comment by gaspropot** [comment]
Was about to open my own issue when I stumbled on this. It would be greatly appreciated if the issue is fixed soon, since my project cannot really release without this fix.

**Comment by DefinitelyADev** [comment]
@sdanyliv Hi, do you have any idea when this will be ready? Because we are close to release and this creates an issue with a very primary component of our solution.

**Comment by Reena-Patel** [comment]
@MaceWindu Can you please consider this and fix it? linq2db is a very good helper for us so if this gets resolved earlier?

**Comment by sdanyliv** [comment]
Will check this case today.

**Comment by sdanyliv** [comment]
Looking into problem. SQL is reproduced. What do you expect finally? Using `LOCATE` or removing weird condition generated by OData?

**Comment by sdanyliv** [comment]
Well, preparing fix. Generated SQL is:
```cs
--  MySql.Official MySql
DECLARE @TypedProperty_1 VarChar(3) -- String
SET     @TypedProperty_1 = '%2%'

SELECT
	`$it`.`Id`,
	`$it`.`Name`
FROM
	`Students` `$it`
WHERE
	`$it`.`Name` LIKE @TypedProperty_1 ESCAPE '~'
```
