### ISSUE TITLE
[PostreSQL] Read/write infinite double precision values

### ISSUE THREAD

**Issue by shadeglare** [linq2db/linq2db#2978]
Can not insert an infinite (plus/minus) value into a double precision column in a postgres table (linq2db 3.3.0).
Seems linq2db don't quote those values according to the postgres documentation.

Output sql with infinite value for an insert query looks like
```sql
insert into some_table 
  (id, value)
values
  (1, Infinite),
  (2, -Infinite);
```

But must be
```sql
insert into some_table 
  (id, value)
values
  (1, '+Infinite'),
  (2, '-Infinite');
```

Npgsql driver supports this feature https://github.com/npgsql/npgsql/pull/339
Is there a solution or workaround for this case in linq2db?

**Comment by MaceWindu** [comment]
You can override default double to sql converter in mapping schema with your implementation:
```cs
// default converter
mappingSchema.SetValueToSqlConverter(typeof(double), (sb, dt, v) => sb.Append(((double)v).ToString("G17", NumberFormatInfo.InvariantInfo)).Append('D'));

// custom converter example
mappingSchema.SetValueToSqlConverter(typeof(double), (sb, dt, v) =>
			{
				var val = (double)v;
				if (double.IsInfinity(val))
					sb.Append('\'');
				sb.Append(((double)v).ToString("G17", NumberFormatInfo.InvariantInfo)).Append('D');
				if (double.IsInfinity(val))
					sb.Append('\'');
			});
```

**Comment by shadeglare** [comment]
@MaceWindu Thanks for the answer. One more question: Is there a way to apply this conversion only on a specific column?

**Comment by MaceWindu** [comment]
You could try with value converter featue, but I'm not sure it will work well here https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273

**Comment by shadeglare** [comment]
@MaceWindu Yes. Seems I can't use ValueConverter for this kind of conversions as the db provider type can be variant (string or number-like value). But your approach with the SetValueToSqlConverter method works like a charm
