### ISSUE TITLE
Generic expression params, expression stopped working in 3.3.0 version.

### ISSUE THREAD

**Issue by goors** [linq2db/linq2db#2981]
Eve since i switched to 3.3.0 my expressions stop working when I have `Expression<Func<T`. Error that i am getting is:

```
First parameter of expression predicate should be 'OwnedDbEntity`1'
```
```c#
public class OwnedDbEntity<T> where T : IOwnedDbEntity
    {
        /// <summary>
        /// Owner.
        /// </summary>
        [Association(ExpressionPredicate = nameof(OwnerPredicate), CanBeNull = true, Relationship = Relationship.ManyToOne, IsBackReference = false)]
        public EntityOwner Owner { get; set; }

        public static Expression<Func<T, EntityOwner, bool>> OwnerPredicate { get; set; } = (T entity, EntityOwner owner) => entity.OwnerId == owner.Id && entity.OwnerType == owner.Type;
        
    }
```

Of course if instead of T i use Correct class it works as expected. 
Is there a way to skip this?
```c#
if (!lambda.Parameters[0].Type.IsSameOrParentOf(parentType))
throw new LinqToDBException($"First parameter of expression predicate should be '{parentType.Name}'");
```
in here https://github.com/linq2db/linq2db/blob/b3b17cd61c40647f38ba813fde91e9c17e2297db/Source/LinqToDB/Mapping/AssociationDescriptor.cs#L251 ?

Logic behind this is that you can have N entities with Owner and OwnerType column that are to FKs because you can not have one FK that is reflecting different tables.

I apologise if i did not fill in more data for this issue/question.

### Environment details
linq2db version: 3.3.0
Database Server: MsSql

**Comment by sdanyliv** [comment]
Why not this expression?
```cs
public static Expression<Func<OwnedDbEntity<T>, EntityOwner, bool>> OwnerPredicate { get; set; } 
     = (entity, owner) => entity.OwnerId == owner.Id && entity.OwnerType == owner.Type;

```

**Comment by goors** [comment]
In that case `entity.OwnerId` and `entity.OwnerType` does not exists.

**Comment by sdanyliv** [comment]
I guess you are storing `T` somewhere in the class? Trying to understand how we can predict that you are worrying about generic parameter. What to do if there two or more generic parameters?

**Comment by goors** [comment]
I resolved this by Copy/Paste same thing to all entities with property `T`. But us is redundant code if you can have one predicate based on generic entity that implements interface. I would really like that this is possible.

**Comment by goors** [comment]
> I guess you are storing `T` somewhere in the class? Trying to understand how we can predict that you are worrying about generic parameter. What to do if there two or more generic parameters?

T is like 15 entities that implements IOwnedDbEntity interface.

**Comment by sdanyliv** [comment]
How about to remove `OwnedDbEntity` and create association as extension to `IOwnedDbEntity`?
Anyway probably I need your interface declaration and and several classes.

**Comment by goors** [comment]
> How about to remove `OwnedDbEntity` and create association as extension to `IOwnedDbEntity`?

I am not sure what do you mean by this. I really don't want to waste to much of your time guys. In 2.x versions of Linq2Db this worked as charm. I was just thinking what was the motivation for you to add such strict check.

**Comment by sdanyliv** [comment]
You are not wasting my time, I like such tasks. In 3.x logic with associations were rewritten completely. Maybe it's too late here but I cannot understand how it worked before. ;)
Post several descendants of `OwnedDbEntity` and sample LINQ query which should work and I'll figure out how to fix.

**Comment by goors** [comment]
Heare are the interfaces.

```
public interface IOwnedDbEntity : IDbEntity
{
  public int OwnerId { get; set; }
  public byte OwnerType { get; set; }
  IEntityOwner Owner { get; }
}
```

```
public interface IEntityOwner
{
  int Id { get; } // int
  Guid PublicId { get; }
  int Type { get; }
  string Name { get; } // nvarchar(101)
  int AgencyId { get; } // int
}
```

Entity example:

```
public partial class Pipeline
{
  [PrimaryKey,                                   Identity   ] public int       Id                 { get; set; } // int
  [Column,                                       NotNull    ] public Guid      PublicId           { get; set; } // uniqueidentifier
  [Column,                                       NotNull    ] public int       OwnerId            { get; set; } // int
  [Column,                                       NotNull    ] public byte      OwnerType          { get; set; } // tinyint
}
```

So as you can see `Pipeline` entity does have` IOwnedDbEntity` interface members so `where T : IOwnedDbEntity` is correct.

For debug query, there is none now since Predicate does not work :)

**Comment by goors** [comment]
So you would say something like 
```
await Db.Pipeline.Select(x => new {
   Owner = x.Owner // and owner is from predicate
}).ToListAsync()
```

**Comment by goors** [comment]
Maybe to forget my problem. As far as i can see you can not now do any predicate now if you don't put in  `T` to be actual entity/class in `public static Expression<Func<T, EntityOwner, bool>>`.

This works  as expected `public static Expression<Func<Pipline, EntityOwner, bool>>` and this `public static Expression<Func<T, EntityOwner, bool>>` does not :)

**Comment by sdanyliv** [comment]
Well, I need to play with code tomorrow. `OwnedDbEntity` is "sealed" class? Thinking a loud: why `IOwnedDbEntity` is not generic to specify exact owner class for join...

**Comment by goors** [comment]
> Well, I need to play with code tomorrow. `OwnedDbEntity` is "sealed" class? Thinking a loud: why `IOwnedDbEntity` is not generic to specify exact owner class for join...

Forgot to mention `public partial class EntityOwner` is also Entity that is actual view of all other entities that have `OwnerId` and `OwnerType`.

I will try to make working example tomorrow so you can test it. Maybe my English sucks and you don't understand because of it :)

**Comment by sdanyliv** [comment]
Good sample makes things easier ;) We proud that linq2db is flexible for user needs and if it is reasonable we add support.
Anyway about association as extension:
```cs
public static class MyExtensions
{
    [Association(ThisKey = "OwnerId,OwnerType", OtherKey = "Id,Type", CanBeNull = true)]
    public static EntityOwner Owner<T>(this T entity)  where T: IOwnedDbEntity
         => throw new NotImplementedException();
}
```
Then this LINQ query should work with any `IOwnedDbEntity` without special class.
```cs
await Db.Pipeline.Select(x => new {
   Owner = x.Owner()
}).ToListAsync()
```
