### ISSUE TITLE
DataExtensions.RetrieveIdentity() returns wrong Identity values

### ISSUE THREAD

**Issue by KostaVlev** [linq2db/linq2db#2983]
[`DataExtensions.RetrieveIdentity()` ](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Tools/DataExtensions.cs#L23)  build internally query to retrieve the last identity column value calling [`GetMaxValueSql()`](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Tools/DataExtensions.cs#L60).

This returns wrong value because the query that is used is ["SELECT Max({columnName}) FROM {tableName}"](https://github.com/linq2db/linq2db/blob/v3.3.0/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L3203) which is not the last identity value. SQL would return the last identity value calling `IDENT_CURRENT('Table_Name')`

The steps to reproduce the issue are:

1. Insert records
2. Go to SQL and delete the records
3. Insert again 

The returned IDs will not match the IDs in  SQL

Note: Turning off the SQL Identity cache does not solve the issue

**Comment by MaceWindu** [comment]
Which database it is? this is db-specific API and implementation could be missing for your db.

**Comment by KostaVlev** [comment]
@MaceWindu Yes, mssql database
