### ISSUE TITLE
MultiInsert doesn't support OUTER APPLY the same way as SELECT does

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#2990]
This happens with fairly tricky queries, I'm gonna create a PR with a test case.

**Comment by sdanyliv** [comment]
@jods4, Do you need workaround?

**Comment by jods4** [comment]
Yes, you're right! That's an easy and perfectly fine workaround for the problem.
It helps, thanks.

**Comment by MaceWindu** [comment]
Fixed in 6.0 preview 1
