### ISSUE TITLE
Complex Query does not work...

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2994]
I've the following query (it does not look like linq2db but this is cause of our wrapping objects)

            using (var s = _commonDl.CreateSession())
            {
                var m = MessageDL.QueryCombinedEvents(s, "de", false);
                var qry = s.Query<MessageEventDTO>().Where(x => m.Any(y => y.MessageEventDTO= = x)).Set(x => x.Destination, "a").Update();
                var sql = s.LastQuery();
            }

it does not work like this. but if I add the property EventID, it does work:

            using (var s = _commonDl.CreateSession())
            {
                var m = MessageDL.QueryCombinedEvents(s, "de", false);
                var qry = s.Query<MessageEventDTO>().Where(x => m.Any(y => y.MessageEventDTO.EventID == x.EventID)).Set(x => x.Destination, "a").Update();
                var sql = s.LastQuery();
            }

then it creates the following SQL:

	UPDATE
		[Common_MessageSystem_Events]
	SET
		[Destination] = @Destination
	WHERE
		EXISTS(
			SELECT
				*
			FROM
				[Common_MessageSystem_Events] [evt]
					INNER JOIN [Common_MessageSystem_Messages] [msg] ON [evt].[MessageId] = [msg].[Id]
					INNER JOIN [Common_MessageSystem_Classes] [mclass] ON [evt].[MessageClassId] = [mclass].[Id]
			WHERE
				[evt].[EventId] = [Common_MessageSystem_Events].[EventId]
		)

but should'nt linq2db create this itself?
the eventid is the primary key, see my mapping:

       .Property(e => e.EventID).HasColumnName("EventId").IsPrimaryKey()

**Comment by sdanyliv** [comment]
Does `MessageEventDTO` has key?

**Comment by jogibear9988** [comment]
What do you mean with key?

it has a this primary key:

        .Property(e => e.EventID).HasColumnName("EventId").IsPrimaryKey()

**Comment by jogibear9988** [comment]
I'll look to create a test

**Comment by jogibear9988** [comment]
this is the test:

		public class Combined
		{
			public Model.Person? p { get; set; }
			public Doctor? d { get; set; }
			public Doctor? g { get; set; }
		}

		[Test]
		public void Issue2994Test([IncludeDataSources(TestProvName.AllSQLite)] string context)
		{
			using (var db = GetDataContext(context))
			{
				var qryFlt = from p in db.Person
							 join d in db.Doctor on p.FirstName equals d.Taxonomy
							 join g in db.Doctor on p.LastName equals g.Taxonomy  // remove this and it also would work
						select new Combined { p = p, d = d };
				var qry = db.Person.Where(x => qryFlt.Any(y => y.p == x)).Set(x => x.LastName, "a").Update();
				//var qry = db.Person.Where(x => qryFlt.Any(y => y.p.ID == x.ID)).Set(x => x.LastName, "a").Update(); // workin
				var sql = ((DataConnection)db).LastQuery;
			}
		}

if you remove the second join it would work

**Comment by sdanyliv** [comment]
So, what should be the key of this entity?

**Comment by sdanyliv** [comment]
Will check if it is possible.
