### ISSUE TITLE
Error when OUTPUT clause exists in T-SQL query

### ISSUE THREAD

**Issue by IgnEriol** [linq2db/linq2db#300]
Hello!

Today i encountered couple of errors like:
The target table 'dbo.XXXYYY' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

Example T-SQL code:
```sql
exec sp_executesql N'INSERT INTO [dbo].[XXXYYY]([Kind],
 [PrimaryAccNum],
 [TaxCode],
 [Name],
 [MDUserName],
 [LastAccessUserId],
 [LastAccessDateTime])
OUTPUT [INSERTED].[Id]
VALUES
(
 @p1,
 @p2,
 @p3,
 @name,
 @mdUsername,
 0,
 ''2015-11-18T12:25:52.200''
)
',N'@p1 int,@p2 nvarchar(6),@p3 nvarchar(9),@name nvarchar(21),@mdUsername nvarchar(4000)',@p1=1,@p2=N'RRRRR',@p3=N'FFFFF',@name=N'YYYY',@mdUsername=NULL
```

**Comment by npochechuev** [comment]
It would be better to USE this MS SQL feature.

In stored procedures I frequently use logic

update t
      set t.value = t.value + @someValue
            ...
 output inserted... deleted...
     into ... --THIS may be not used if I need just return value(s) without additiona SELECT operations              
                --in opened transaction
   from tSomeTable t
 inner
    join ....
 where ... 

or when I insert data.

Actually @@identitny to define inserted value, I always use "output" statement

**Comment by inickvel** [comment]
https://github.com/linq2db/linq2db/issues/305

**Comment by ili** [comment]
It is fixed now :)
