### ISSUE TITLE
How to extend select projection without mapping properties allover again?

### ISSUE THREAD

**Issue by croban** [linq2db/linq2db#3004]
This is more question then an issue.

Is there a better way to select additional fields without mapping all properties again.
e.g.
I have an [Table] class with additional properties without [column] attribute.
Values for those properties are coming from UDF Scalar function..
At the moment I have to map properties all over again e.g.
```
...Select(f=>new Class() {
   f.Prop1 = f.Prop1,
   f.Prop2 = f.Prop2
   .... 
  f.AdditionalProp = UDF.GetSomeValue(f.Id)
}
```

Is there some better way to do this. 
Or is there something line this:

`...Select(f=>f.Build().With(f=>f.AdditionalProp, UDF...)`

I saw this example [here ](https://linq2db.github.io/) but it does not work with [Sql.Expression] attributes.

```
from p in db.Product
from c in db.Category.Where(q => q.CategoryID == p.CategoryID).DefaultIfEmpty()
select Product.Build(p, c);

public static Product Build(Product product, Category category)
{
  if (product != null)
  {
    product.Category = category;
  }
  return product;
}
```

I have also tried to use Tools.MapperBuilder but same result as example above.

br

Linq2Db 3.2.3

**Comment by sdanyliv** [comment]
Does this answer your question? https://stackoverflow.com/questions/63727166/linq2db-filter-by-nested-property-field

**Comment by croban** [comment]
@sdanyliv it helped partially, thx!!! 

I came out with this one so that i don't need to copy all porps e.g.
```c#
f=> new nesto() {
.... all props
}
```

I have not tested all possibilities but the case on bottom works for me.
it could be extended so that e.g. Properties which don't have column attr. but expression attribute could be included.

```c#
public static Expression<Func<T, T>> BuildLambda<T>( Expression<Func<T, T>> setter)
	where T : class
	{
		var createdType = typeof(T);
		var defaults = typeof(Partner).GetPropertiesEx().Where(f => f.CustomAttributes.Any(ca => ca.AttributeType == typeof(ColumnAttribute)));
		var listOfSetters = new List<MemberAssignment>();
		foreach (var def in defaults)
		{
			listOfSetters.Add(Expression.Bind(def, Expression.Property(setter.Parameters.First(), def)));
		}

		var body = setter.Body as MemberInitExpression;
		var bindings = body.Bindings;
		var setters = bindings.Select(f=>(MemberAssignment)f).ToList();
		listOfSetters.AddRange(setters);
		
		var result = Expression.MemberInit(body.NewExpression, listOfSetters);

		return Expression.Lambda<Func<T, T>>(result, true, setter.Parameters);
	}
```

like that i'm possible to do something like this (all default properties are assign and new one are added.

```c#
db.GetTable<Partner>().AsQueryable().Select(Ex.BuildLambda<Partner>(f => new Partner() {
		PostalCodes = PartnerRepository.UDF.PostalCodesAsList(f.Id),
		Tags = PartnerRepository.UDF.TagNamesAsList(f.Id),
		Apps = PartnerRepository.UDF.AppIdsAsList(f.Id)
	}))
```

**Comment by croban** [comment]
found solution that works for me, maybe is there some better "build in" Approche already?
