### ISSUE TITLE
Field bool is not working

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#301]
Hello, I created a Table in Access with the Datatyp AutoValue.
I can read the values correctly, but I can not write to this field.

Is that a know issue ?
Her my code:
               // Find Object
                var data = db.Adresses.FirstOrDefault(t => t.Name == "Waning");
                data.OrderNr    = 47112;
                data.Activ      = true;  // Set true
                DataContext con = new DataContext(Dataconnection.m_DataProvider,Dataconnection.m_ConnectionString);

                int Anzahl = con.Update<DataModels.Adresse>(data);
                //Anzahl is 1

                data = db.Adresses.FirstOrDefault(t => t.Name == "Waning");
                //data.OrderNr is 47112
                //data.Activ is still false

**Comment by igor-tkachev** [comment]
If you mean AutoNumber data type, it's controlled by the database engine and can not be updated.
