### ISSUE TITLE
Support for oracle GetSessionInfo method in OracleConnection

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#3012]
In future could linq2db add support to GetSessionInfo method in OracleConnection class. This would help for tracing sessions in production when oracle session pooling is used.

**Comment by sdanyliv** [comment]
Currently I do not see reason to do that and when it can be helpful. Better provide example of usage.

**Comment by sarabu07** [comment]
The oracle session pooling provides the additional benefits in addition to connection pooling to use the database resources. When we are using oracle session pooling we would want to get session info to be logged so if any database error happens we could rule out it is not because of session pooling. Also is there any way to get oracle connection object from linq2db class so we could get this information in current version?

**Comment by MaceWindu** [comment]
Definitely this is not something we want to support, but you can call any method of connection yourself.
There are multipe options to access connection:
- using connection factory with linq2db or passing connection to it: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L130-L192
- accessing currently used connection https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L1073

In v4 we also will add interceptors https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#interceptors
