### ISSUE TITLE
DeleteWithOutput always returns an empty collection

### ISSUE THREAD

**Issue by Kaoticz** [linq2db/linq2db#3018]
`DeleteWithOutput()` and `DeleteWithOutputAsync()` generate and execute the query correctly, but they always return an empty collection, no matter how many entries are removed from the database table. No exception is thrown.

I'm using them exactly like they are used in [Tests.Linq](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/DeleteWithOutputTests.cs) but I invoke the method directly from the DbContext object. It always returns an empty collection. I'm wondering whether I'm using them correctly or if a certain condition must be met in order for them to work. Some advice would be appreciated.

### Steps to reproduce
- Query any table with one of the two methods above. For example:
```cs
// This deletes a bunch of entries from the table, but returns an Enumerable.Empty<UserEntity>()
var deletedEntities = db.Users
    .Where(x => x.Id > 50)
    .DeleteWithOutput();
```
```cs
// This deletes all entries from the table, but returns an int[0]
var ids = await db.Users
    .DeleteWithOutputAsync(x => x.Id);
```

### Environment details
linq2db version: **3.3.0**
Database Server: **PostgreSQL 13.1**
Database Provider: **Npgsql**
Operating system: **Windows 10**
**.NET 5**

**Comment by viceroypenguin** [comment]
Unfortunately these are only supported on MSSQL for now. It is on my list to expand support to the `RETURNING` operator for PostgreSQL and similar, but that work has not yet been done.

**Comment by Kaoticz** [comment]
Ah, that's unfortunate.
Would you consider adding a `<remarks>` on the documentation about this while the feature is not implemented? To avoid confusion in the future so people don't open more tickets similar to this one.

**Comment by viceroypenguin** [comment]
Added `<remarks>` for now in #2321.

**Comment by MaceWindu** [comment]
#3328 PR with fix
