### ISSUE TITLE
MapValue to Postgres Enum Type

### ISSUE THREAD

**Issue by ThatGeoGuy** [linq2db/linq2db#303]
I have been playing around with LINQ2DB so far, and I'm very much liking it. However, I am having troubles with mapping values as per the blog post listed [here](http://blog.linq2db.com/2015/05/using-mapvalueattribute-to-control.html). In particular, given the following, I find that I end up raising NpgsqlExceptions depending on how I structure the code:

_Database.tt_: More or less the same as default, but I added the following line in between `LoadPostgreSQLMetadata(...)` and `GenerateModel()`

```
Tables["methods"].Columns["methodtype"].Type = "ModelMethodTypes";
```

_Form1.cs_: This is the minimal amount of code needed to reproduce this error:

``` c#
using System;
using System.Windows.Forms;
using DataModel;
using LinqToDB;
using LinqToDB.Mapping;

public enum ModelMethodTypes
{
    [MapValue("TypeA")] TypeA,
    [MapValue("TypeB")] TypeB,
    [MapValue("TypeC")] TypeC,
    [MapValue("TypeD")] TypeD
}


namespace TestLinq2DB
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            DoModelThing(ModelMethodTypes.Capture);
        }

        private static int DoModelThing(ModelMethodTypes methodType)
        {
             using (var db = new TestDB())
            {
                var q = db.methods.Insert(() => new method
                {
                    methodtype = methodType,  // LINE 33 - This is where the problem happens
                    creationdate = DateTimeOffset.Now
                });

                return q;
            }           
        }
    }
}
```

Additionally, the following is the code I use to initialize my Postgres database (`initdb.sql`):

``` sql
CREATE TYPE method_type AS ENUM (
    'TypeA',
    'TypeB',
    'TypeC',
    'TypeD'
);

CREATE TABLE methods (
    id bigserial PRIMARY KEY,
    methodtype method_type NOT NULL,
    creationdate timestamptz NOT NULL
);
```

The problem is that when I call the method like this, an `NpgsqlException` is raised, telling me the following: 

``` text
Npgsql.NpgsqlException occurred
  BaseMessage=column "methodtype" is of type method_type but expression is of type text
  Code=42804
  ErrorCode=-2147467259
  File=src\backend\parser\parse_target.c
  HResult=-2147467259
  Hint=You will need to rewrite or cast the expression.
  InternalPosition=0
  Line=510
  Message=42804: column "methodtype" is of type method_type but expression is of type text
  MessageText=column "methodtype" is of type method_type but expression is of type text
  Position=77
  Routine=transformAssignedExpr
  Severity=ERROR
  Source=Npgsql
  StackTrace:
       at Npgsql.NpgsqlConnector.DoReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage, Boolean isPrependedMessage)
       at Npgsql.NpgsqlConnector.ReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage)
       at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
       at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
       at Npgsql.NpgsqlCommand.ExecuteNonQuery()
       at LinqToDB.Data.DataConnection.ExecuteNonQuery() in i:\linq2db\Source\Data\DataConnection.cs:line 579
  InnerException: 
```

Normally, I would say that this is a problem with Npgsql, but I can't confirm why it would be doing this. I say that in particular because I can swap out my LINE 33 in the `Form1.cs` file with the following:

```
methodtype = ModelMethodTypes.TypeA,
```

and the code works without fail. What could possibly be causing this problem, and what am I doing wrong to map to user-defined types using linq2db? A short-term solution would be to change my database schema to incorporate characters or integer values in place of an enum type, however I would much rather have the ability to map 1:1 my enumeration type in C# to an enum type in PostgreSQL. For that matter, using Npgsql without an ORM, the following can be done: 

```
NpgsqlConnection.RegisterEnumGlobally<ModelMethodTypes>("method_type");
```

which registers the two together globally. In any case,  I figured since this works one way (calling the enum explicitly) but not the other (passing the enum value in as a parameter first), this must be either a bug or I have mis-configured something horribly. I've tried looking at the documentation but beyond the blog post referenced above I cannot find anything that details how `MapValue` works or how I should go about tweaking it.

**Comment by ThatGeoGuy** [comment]
Some information I perhaps forgot to add:

1. I install everything via NuGet in Visual Studio 2015
2. I am using `linq2db.PostgreSQL` version 1.0.7.3
3. This installs `linq2db` and `linq2db.t4models` versions 1.0.7.3 (same as above)
4. Also installs `Npgsql` version 3.0.3

**Comment by ili** [comment]
How to do it with pure ADO .Net (without using linq2db)?

**Comment by CrazyAlex25** [comment]
From [npgsql documentation](http://www.npgsql.org/doc/types/enums_and_composites.html)

> In order to use enum and composite types with Npgsql, you must map your CLR type to the PostgreSQL enum or composite. This must be done in advance, before reading or writing. The easiest way to do this is to call MapEnumGlobally or MapCompositeGlobally before opening any connections; the following will set up a mapping between your CLR SomeEnum type to a PostgreSQL enum called some_enum (more on the name translation later).

```csharp
enum SomeEnum { ... }
NpgsqlConnection.MapEnumGlobally<SomeEnum>();
```
>Similarly, the following will set up a mapping between CLR type SomeType and a PostgreSQL composite called some_type. The CLR type can be a class or struct.
```csharp
class SomeType { ... }
NpgsqlConnection.MapCompositeGlobally<SomeType>();
```
>Note that the PostgreSQL types must have been create in advance (with CREATE TYPE).

>If you don't want to map an enum for all your connections, you can register a mapping for one connection only by calling MapEnum on an NpgsqlConnection instance.

**Comment by kt215** [comment]
This is what I did to get **postgresql** enums to work with **npgsql** and **linq2db**:

```
NpgsqlConnection.GlobalTypeMapper.MapEnum<MyEnum>("myschema.my_enum");
MappingSchema.Default.SetDefaultFromEnumType(typeof(MyEnum), typeof(MyEnum));
```
I have to have both statements for every enum.

I'm using `npgsql 4.0.7` and `linq2db.PostgreSQL 2.7.0`

It would be nice if the MappingSchema statement could be omitted, and instead there was a global setting to pass enums to postgres as-is. By default, linq2db converts enums into integers which causes npgsql errors.

**Comment by ffandreassoroko** [comment]
any updates on that?

**Comment by MaceWindu** [comment]
If nobody willing to work on it, then no - we have enought 3.0-related tasks for next 1-2 monthes...

**Comment by hellznrg** [comment]
@ffandreassoroko I got it to work by telling linq2db to inline parameters.

In your DataConnection class, just use "InlineParameters = true;" in the constructor.

If InlineParameters is false, then the SQL will be generated like this:

```
DECLARE @Name as Text(5);
SET @Name = 'Simon';
DECLARE @Gender as Text(5);
SET @Gender = 'M';
Insert into person (name, gender) values (:name, :gender);
```

With InlineParameters true, it generates:

`Insert into person (name, gender) values ('Simon', 'M');`

Which is the correct Postgres syntax.

**Comment by garkushin** [comment]
for those who are still looking for how to do it, I got it like this.

```
public class DataContext : DbContext 
{
...
        static DataContext()
        {
            var nameTranslator = NpgsqlConnection.GlobalTypeMapper.DefaultNameTranslator;

            NpgsqlConnection.GlobalTypeMapper.MapEnum<PriorityLevel>();

            MappingSchema.Default.SetDefaultFromEnumType(typeof(EdgeType), typeof(string));
            MappingSchema.Default.SetConverter<EdgeType, string>(c => nameTranslator.TranslateMemberName(c.ToString()));
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.HasPostgresEnum<PriorityLevel>();
        }
...
}
```
