### ISSUE TITLE
Interfaces inheritance

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3034]
I'm doing some generic work on several unrelated entities with common code, thanks to interfaces.

linq2db works well enough with interfaces but it seems to ignore members that come from interfaces hierarchies.

For example if you declare this model:
```cs
interface IA
{
  int Id { get; set; }
}

interface IB : IA
{
 string Name { get; set; }
}
```

If you then write Linq that refers to `Id` through `IB`, such as:
```cs
public void ChangeName(int id, string name)
{
  return db.GetTable<IB>().TableName("MyTable")
    .Where(x => x.Id == id)
    .Set(x => x.Name, x => newName)
    .Update();
}
```

It compiles but at runtime linq2db complains that `x.Id` is not a mapped property of `IB`.

**Comment by sdanyliv** [comment]
@jods4, I would like to see full filing test, then we can continue with solution.
