### ISSUE TITLE
Error when filtering on a projected object

### ISSUE THREAD

**Issue by srollinet** [linq2db/linq2db#3038]
Hi,

I found a bug when trying to filter an IQueryable containing a "multi-level" projection

You can reproduce it easily on master, by adding this test in `SQLiteTests`

		[Test]
		public async Task  ProjTest()
		{
			using (var ctx = CreateSQLiteSqlExntitiesContext())
			{
				await ctx.Customers
					.Select(c => new
					{
						c.CustomerId,
						Orders = c.Orders.Select(o => new
						{
							o.OrderId
						}).ToList()
					})
					.FirstOrDefaultAsyncLinqToDB(c => c.CustomerId == "42");
			}
		}

here is the output

> LinqToDB.EntityFrameworkCore.SQLite.Tests.SQLiteTests.FilterProjectionTest
> 
> System.ArgumentException : Expression of type 'System.Linq.IQueryable`1[LinqToDB.Linq.Builder.ExpressionHolder`2[LinqToDB.EntityFrameworkCore.BaseTest...
> 
> System.ArgumentException : Expression of type 'System.Linq.IQueryable`1[LinqToDB.Linq.Builder.ExpressionHolder`2[LinqToDB.EntityFrameworkCore.BaseTests.Models.Northwind.Customer,<>f__AnonymousType3`2[System.String,System.Collections.Generic.List`1[<>f__AnonymousType4`1[System.Int32]]]]]' cannot be used for parameter of type 'System.Linq.IQueryable`1[<>f__AnonymousType3`2[System.String,System.Collections.Generic.List`1[<>f__AnonymousType4`1[System.Int32]]]]' of method '<>f__AnonymousType3`2[System.String,System.Collections.Generic.List`1[<>f__AnonymousType4`1[System.Int32]]] FirstOrDefault[<>f__AnonymousType3`2](System.Linq.IQueryable`1[<>f__AnonymousType3`2[System.String,System.Collections.Generic.List`1[<>f__AnonymousType4`1[System.Int32]]]])' (Parameter 'arg0')
>    at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
>    at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
>    at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
>    at LinqToDB.Expressions.Extensions.TransformX(MethodCallExpression e, Func`2 func)
>    at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
>    at LinqToDB.Linq.Builder.FirstSingleBuilder.Convert(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo, ParameterExpression param)
>    at LinqToDB.Linq.Builder.MethodCallBuilder.Convert(ExpressionBuilder builder, BuildInfo buildInfo, ParameterExpression param)
>    at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertSequence(BuildInfo buildInfo, ParameterExpression param, Boolean throwExceptionIfCantConvert)
>    at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTree(Expression expression)
>    at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters)
>    at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
>    at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
>    at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
>    at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
>    at LinqToDB.EntityFrameworkCore.SQLite.Tests.SQLiteTests.FilterProjectionTest() in /home/sro/projects/repro/linq2db.EntityFrameworkCore/Tests/LinqToDB.EntityFrameworkCore.SQLite.Tests/SQLiteTests.cs:line 61
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

It seems the two conditions to get this exceptions are
- The projection must contain a nested object. If you remove `Orders` everything works as expected
- The where must be after the select

**Comment by sdanyliv** [comment]
@srollinet, thanks for reporting, will check. Issue transferred to main repository.
