### ISSUE TITLE
Protected or Private Construcotors of Entitys supported?

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#307]
Doe linq2db support protected or private constructors of DB Entitys?

**Comment by jogibear9988** [comment]
I think not atm.

Maybe someone can add the "feature" Label

**Comment by ili** [comment]
Is it really needed?

**Comment by ili** [comment]
As for me it is a bad idea to use private constructors... Does for ex EF support it, and how it looks like?

**Comment by sdanyliv** [comment]
We can not support this. Our reader uses Expression Tree, which do not support such reflection tricks.

**Comment by ili** [comment]
Then closing

**Comment by jogibear9988** [comment]
Can I not use a Private Constructor in Expression Trees? When I get the constructor via reflection, and use https://msdn.microsoft.com/en-us/library/bb301982(v=vs.110).aspx

**Comment by jogibear9988** [comment]
We support this already !!! see: https://github.com/linq2db/linq2db/pull/631
