### ISSUE TITLE
Is Association in both directions possible?

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#308]
I've 2 classes for each of them I have a Table in the Database! 1.st Location, 2nd Opening! Now the Opening has in it's Table a LocationId, and the Opening has a Location Property! To this I can Add a Association Property to define the Mapping!
But how can I do (when it's possible) the mapping the other way round? That means the Location has also a Opening Property, but no OpeningId in the Database, because the Opening already has the LocationId! Is this possible?
In NHibernate I do this via:

```
HasOne(x => x.Opening).PropertyRef(x => x.InternalLocation).Cascade.None();
```

**Comment by jogibear9988** [comment]
Doesn't anyone know?
Another Question I have is, do I need the "Id"s needed for the Association as a Property? In NH it's not needed!

**Comment by ili** [comment]
What about sample?

**Comment by sdanyliv** [comment]
@jogibear9988, something strange here. Do we still need that?

**Comment by jogibear9988** [comment]
What do you mean about with „something strange“? I still think it would be cool if we can support!

**Comment by jogibear9988** [comment]
see also: https://github.com/linq2db/linq2db/issues/225

**Comment by jogibear9988** [comment]
Do we have plans for "many to many" associations in V2?

It would be cool if we could support it, in a way, so we do not need to create a class for the ref tabl!

**Comment by MaceWindu** [comment]
Could you clarify what is this issue about?
I'm not aware about any issues with defining both sides of association in both fluent and attribute mappings

Is it about many-to-many associations support without extra mapping class?

**Comment by MaceWindu** [comment]
Closing for now. Please reopen if you have some concrete issue/proposal
