### ISSUE TITLE
Oracle 11 - InsertOrUpdate generates MERGE statement that cannot be handled by DB

### ISSUE THREAD

**Issue by to11mtm** [linq2db/linq2db#3086]
When we try to do InsertOrUpdate, Merge statement is generated that Oracle 11 cannot parse.

Not sure if there's an easy way to fix this in Oracle 11 Optimizer. Will clean up the repro details shortly, main discrepancy one might see is we have custom mapping for column names but I don't think that's related to actual issue.

Exception: 
```
Oracle.ManagedDataAccess.Client.OracleException (0x80004005):
ORA-38104: Columns referenced in the ON Clause cannot be updated: "T1"."PersistenceId"
```

### Steps to reproduce

```c#

//Base Mapping class
public sealed class JournalMetaData
    {
        [Column(IsPrimaryKey = true, CanBeNull = false)]
        public string PersistenceId { get; set; }
        [PrimaryKey]
        public long SequenceNumber { get; set; }
    }

//Failing DB Call:

await db.GetTable<JournalMetaData>()
                                .InsertOrUpdateAsync(() => new JournalMetaData()
                                    {
                                        PersistenceId = persistenceId,
                                        SequenceNumber =
                                            maxMarkedDeletion
                                    },
                                    jmd => new JournalMetaData()
                                    {
                                        PersistenceId = persistenceId,
                                        SequenceNumber = maxMarkedDeletion
                                    },
                                    () => new JournalMetaData()
                                    {
                                        PersistenceId = persistenceId,
                                        SequenceNumber = maxMarkedDeletion
                                    });
```

SQL Generated:

```
--  ODP Oracle11 (asynchronously)
DECLARE @persistenceId Varchar2(3) -- String
SET     @persistenceId = 'p-3'
DECLARE @maxMarkedDeletion Int64
SET     @maxMarkedDeletion = 5

MERGE INTO "journal_metadata" t1
USING (SELECT :persistenceId AS "PersistenceId", :maxMarkedDeletion AS "sequenceNr" FROM SYS.DUAL) s ON
(
	t1."PersistenceId" = s."PersistenceId" AND
	t1."sequenceNr" = s."sequenceNr"
)
WHEN MATCHED THEN
	UPDATE 
	SET
		t1."PersistenceId" = :persistenceId,
		t1."sequenceNr" = :maxMarkedDeletion
WHEN NOT MATCHED THEN
	INSERT
	(
		"PersistenceId",
		"sequenceNr"
	)
	VALUES
	(
		:persistenceId,
		:maxMarkedDeletion
	)
```

### Environment details
linq2db version: *3.4.0*
Database Server: *Oracle 11 XE*
Database Provider: *Oracle.ManagedDataAccess.Core 3.21.1*
Operating system: *Windows 10*
.NET Framework: *Core 3.1*

**Comment by ismaelhamed** [comment]
AFAIK you cannot update a column referenced in the ON clause, hence the ORA-38104. I think if you remove `PersistenceId` from the update in the `InsertOrUpdateAsync` , it will do.

**Comment by MaceWindu** [comment]
Well, I'm aware of this limitation and don't think we should do anything here.

Different databases have various limitations on merge and users just shouldn't use unsupported by db functionality and expect it to work....

**Comment by MaceWindu** [comment]
Whoops, sorry, didn't noticed this is about InsertOrUpdate API, not Merge API.

Maybe we need to fix it in this case...

**Comment by MaceWindu** [comment]
Actually we probably should try to improve it (like we did for  merge here #2843)

**Comment by MaceWindu** [comment]
Look at #3005 - this is probably what you want here

**Comment by sdanyliv** [comment]
@to11mtm, since both fields in table are PK - you do not need to update them:
```cs
await db.GetTable<JournalMetaData>()
	.InsertOrUpdateAsync(() => new JournalMetaData
		{
			PersistenceId = persistenceId,
			SequenceNumber =
				maxMarkedDeletion
		},
		jmd => new JournalMetaData(),
		() => new JournalMetaData
		{
			PersistenceId  = persistenceId,
			SequenceNumber = maxMarkedDeletion
		});
```

**Comment by to11mtm** [comment]
Thanks all, this makes a lot more sense...

Do we still want to investigate overall behavior though? i.e. on oracle 11 should we fall back to a different InsertOrUpdate pattern?

**Comment by sdanyliv** [comment]
I have not time to follow new Oracles's features. Which pattern do you suggest?

**Comment by to11mtm** [comment]
@sdanyliv I think the 'best' fix we could manage is look to see if columns we are updating are included in Match predicate, and if so fallback to `BuildInsertOrUpdateQueryAsUpdateInsert`.

Based on some searches, this may an issue on other newer oracle DBs as well. I know my case had a simpler fix but others may not? 

Tagging @jods4 for thoughts since they seem to be one of the more frequent Oracle users.

**Comment by sdanyliv** [comment]
Issue here that you have explicitly defined Update fields - we aways respect them.

**Comment by MaceWindu** [comment]
InsertOrUpdate API is quite simple one. Implementing workarounds for this limitation of Oracle will be overkill, users could write required queries for this case explicitly
