### ISSUE TITLE
PostgreSQL Test Problem .Any() causing System.StackOverflowException

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#3088]
<details>
<summary>Model</summary>

```C#

	[Table(Schema="Member", Name="Table")]
	public partial class Table
	{
		[PrimaryKey, NotNull    ] public int      Id       { get; set; } // integer
		[Column,     NotNull    ] public DateTime Date     { get; set; } // date
		[Column,     NotNull    ] public TimeSpan Time     { get; set; } // time without time zone
		[Column,        Nullable] public int?     StatusId { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Table_TableStatus
		/// </summary>
		[Association(ThisKey="StatusId", OtherKey="StatusId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table_TableStatus", BackReferenceName="Table")]
		public TableStatus TableStatus { get; set; }

		#endregion
	}

	[Table(Schema="Member", Name="TableStatus")]
	public partial class TableStatus
	{
		[PrimaryKey, NotNull] public int    StatusId   { get; set; } // integer
		[Column,     NotNull] public string StatusName { get; set; } // character varying

		#region Associations

		/// <summary>
		/// FK_Table_TableStatus_BackReference
		/// </summary>
		[Association(ThisKey="StatusId", OtherKey="StatusId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table> Table { get; set; }

		#endregion
	}
```
</details>

Sample test using 0 row data
```c#
            var query = (from t in db.Table
                         let status = t.TableStatus
                         where t.Id == 1
                         select 1);
            query.Count();//worked
            query.ToArray();//worked
            query.Any();//Error: System.StackOverflowException
```

### Environment details
linq2db version: 3.4.0
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
Could you please check latest build?

**Comment by sasukevita** [comment]
> 
> 
> Could you please check latest build?

ok, i have updated to 4.0.0-preview.1 and tried got same exception

**Comment by sdanyliv** [comment]
Not. preview but latest artifacts. Development version nuget [feed](https://pkgs.dev.azure.com/linq2db/linq2db/_packaging/linq2db/nuget/v3/index.json) ([how to use](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources))

**Comment by sasukevita** [comment]
> 
> 
> Not. preview but latest artifacts. Development version nuget [feed](https://pkgs.dev.azure.com/linq2db/linq2db/_packaging/linq2db/nuget/v3/index.json) ([how to use](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources))
> 4 preview is not merged yet with latest fixes.

thanks for info to use dev version
have tried on 3.4.1-rc.6173, its no problem

**Comment by sdanyliv** [comment]
Fixed in https://github.com/linq2db/linq2db/pull/3058
