### ISSUE TITLE
Fantastic performance!!

### ISSUE THREAD

**Issue by pebezo** [linq2db/linq2db#309]
Frans Bouma is working on an ORM benchmark. Until now it wasn't testing LINQ2DB:

https://github.com/FransBouma/RawDataAccessBencher

A few days ago I've added LINQ2DB to the test suite. Here's a preview of the next results:

http://pastebin.com/ZnaNswEE

As you can see LINQ2DB is the fastest ORM! In some cases it's faster than the hardcoded version. Thanks for your hard work!

**Comment by jogibear9988** [comment]
is it possible that you run a test
nhibernate vs. linq2db?

Von meinem iPhone gesendet

**Comment by pebezo** [comment]
I guess Frans didn't run NHibernate for this preview. It's there in the previous runs:

http://pastebin.com/SrDbxUkp

However, it looks like the only configuration for NH is with change tracking, so it's going to be slower (can't really compare). I don't know enough about NH to know if it can query without change tracking (I would imagine it could). Would you consider sending a PR with NH (change tracking off)?

**Comment by pebezo** [comment]
Looks like there's an open issue for this: https://github.com/FransBouma/RawDataAccessBencher/issues/9

**Comment by jogibear9988** [comment]
There is also this https://github.com/sdanyliv/ormbattle
wich is a fork of https://code.google.com/p/ormbattle/
but it's missing actual results for the Frameworks, and I can't run it (I do not have MsSQL & Northwind)
I'm als very interested in Sqlite NHibernate vs. linq2db

**Comment by npochechuev** [comment]
It depends on your test cases...

Try to test child lists for example.
https://github.com/linq2db/linq2db/issues/288

I hope that it will be solved.

**Comment by jogibear9988** [comment]
@ili think this could be closed
