### ISSUE TITLE
ThreadStatic field _suspended is used in async method

### ISSUE THREAD

**Issue by artelk** [linq2db/linq2db#3096]
https://github.com/linq2db/linq2db/blob/89e0f7e34413120b4bffa278f9c4d12e3c885758/Source/LinqToDB/Data/RetryPolicy/RetryPolicyBase.cs#L186

```c#
[ThreadStatic]
static volatile bool _suspended;

protected static bool Suspended
{
	get => _suspended;
	set => _suspended = value;
}

//...
Suspended = true;
var result = await operation(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);
Suspended = false;
```
You cannot assume you will be in the same thread after `await` even if the `ContinueOnCapturedContext` was `true`.
Moreover the thread can be used by some parallel task while the async `operation` is working and that task can also call the `ExecuteAsync` causing unpredictable state of the Suspended property value.

**Comment by MaceWindu** [comment]
We should add BanSymbol analyzer we use in v4 branch and ban use of treadstatic attribute...

**Comment by viceroypenguin** [comment]
`AsyncLocal<>` is the appropriate equivalent, AFAIK

**Comment by MaceWindu** [comment]
I would prefer to get rid of execution context state if possible, but year, `AsyncLocal` could be used if it's copy semantics doesn't break it

**Comment by artelk** [comment]
```c#
public virtual TResult Execute<TResult>(Func<TResult> operation)
{
	if (Suspended)
		return operation();

	OnFirstExecution();

	return ExecuteImplementation(operation);
}

public async Task ExecuteAsync(Func<CancellationToken, Task> operation, CancellationToken cancellationToken = new CancellationToken())
{
	if (Suspended)
	{
		await operation(cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);
		return;
	}

	OnFirstExecution();
	await ExecuteImplementationAsync(async ct => { await operation(ct).ConfigureAwait(Configuration.ContinueOnCapturedContext); return 0; }, cancellationToken).ConfigureAwait(Configuration.ContinueOnCapturedContext);
}

protected virtual void OnFirstExecution()
{
	ExceptionsEncountered.Clear();
}

protected virtual List<Exception> ExceptionsEncountered { get; }
```

And the `ExceptionsEncountered` seems never used outside the class. I suspect that is only needed for debugging.
Maybe the property could be made a local variable in the ExecuteImplementation and ExecuteImplementationAsync methods and they could throw an AggregatedException with exceptions from all attempts instead of the last one. But that information could be lost if it successfully executed on some attempt. We need to know what the author wanted to achieve :). And why it immediately executes the operation when Suspend is true. And the ExceptionsEncountered is a List which is not thread safe...
