### ISSUE TITLE
Translate sql select

### ISSUE THREAD

**Issue by ferbenor** [linq2db/linq2db#310]
How i can translate this sql sentence to linq2db

select pr.*, d.existenciatotal, d.costototal
from productos pr
inner join detallesinventarios d on pr.idempresa = d.idempresa and pr.id = d.idproducto
inner join inventarios i on d.idperiodo = i.idperiodo and d.tipo = i.tipo and d.numero = i.numero and i.esanulado = false
where i.fecharegistro = (select max(fecharegistro) from inventarios it 
   inner join detallesinventarios dt on it.idperiodo = dt.idperiodo and it.tipo = dt.tipo and it.numero = dt.numero
where it.idperiodo = i.idperiodo and dt.idempresa = d.idempresa and dt.idproducto = d.idproducto)

**Comment by ferbenor** [comment]
please mr igor-tkachev you can help me with this.

Thank you.

**Comment by pebezo** [comment]
Is there a particular piece that gives you a hard time?

**Comment by ferbenor** [comment]
Hello, yes, when i try make this sql sentence in linq2db the translate generate one sentence veri big and no same with this. Is for that i want see how should be, thank you for your response.

**Comment by ferbenor** [comment]
the part 
"where i.fecharegistro = (select max(fecharegistro) from inventarios it
inner join detallesinventarios dt on it.idperiodo = dt.idperiodo and it.tipo = dt.tipo and it.numero = dt.numero
where it.idperiodo = i.idperiodo and dt.idempresa = d.idempresa and dt.idproducto = d.idproducto)"

i dont know how to do.

**Comment by pebezo** [comment]
That's more of a LINQ question and less of a LINQ 2 DB. Something like this should work

```
from p in db.Parent
where p.Value == 
(
  from c in db.Child
  join t in db.Toy on c.Id equals t.ChildId
  /* ... and so on ... */
  select c.Value
).Max()
p.Name, p.Age, ... etc ...
```

**Comment by ferbenor** [comment]
i need extract the last record linking 3 tables, products(idbusines(PK), idproduct(PK), description), inventarydetail(idyear(PK), type(PK), number(PK), idbusiness, idproduct, cant, cost,), inventary(idyear(PK), type(PK), number(PK), recorddate (datetime))

if i use this linq sentence:

var f111 = (
                    from i in db.inventarios
                    join d in db.detallesinventarios on new { i.idperiodo, i.tipo, i.numero, i.esanulado } equals new { d.idperiodo, d.tipo, d.numero, esanulado = false }
                    where i.idperiodo == anioPeriodo && i.idsucursalbodega1 == idSucursal && i.idbodega1 == idBodega &&
                    i.fecharegistro ==
                    (from it in db.inventarios
                     join dt in db.detallesinventarios on new { it.idperiodo, it.tipo, it.numero, it.esanulado } equals new { dt.idperiodo, dt.tipo, dt.numero, esanulado = false }
                     where it.idperiodo == i.idperiodo && it.idsucursalbodega1 == i.idsucursalbodega1 && it.idbodega1 == i.idbodega1
                     && dt.idempresa == d.idempresa && dt.idproducto == d.idproducto
                     select it.fecharegistro
                    ).Max()
                    select d
                    ).ToList();

the sql sentence is too big like this:

SELECT
	t1.idperiodo as idperiodo1,
	t1.tipo as tipo1,
	t1.numero as numero1,
	t1.idempresa as idempresa1,
	t1.idproducto as idproducto1,
	t1.registro as registro1,
	t1.cantidad as cantidad1,
	t1.precio as precio1,
	t1.existenciatotal as existenciatotal1,
	t1.costototal as costototal1
FROM
	(
		SELECT
			i.idperiodo as idperiodo2,
			i.idsucursalbodega1,
			i.idbodega1,
			i.fecharegistro,
			(
				SELECT
					Max(it.fecharegistro)
				FROM
					public.inventarios it
						INNER JOIN public.detallesinventarios dt ON it.idperiodo = dt.idperiodo AND it.tipo = dt.tipo AND it.numero = dt.numero AND it.esanulado = False
				WHERE
					it.idperiodo = i.idperiodo AND
					it.idsucursalbodega1 = i.idsucursalbodega1 AND
					it.idbodega1 = i.idbodega1 AND
					dt.idempresa = d.idempresa AND
					dt.idproducto = d.idproducto
			) as c2,
			d.idperiodo,
			d.tipo,
			d.numero,
			d.idempresa,
			d.idproducto,
			d.registro,
			d.cantidad,
			d.precio,
			d.existenciatotal,
			d.costototal
		FROM
			public.inventarios i
				INNER JOIN public.detallesinventarios d ON i.idperiodo = d.idperiodo AND i.tipo = d.tipo AND i.numero = d.numero AND i.esanulado = False
	) t1
WHERE
	t1.idperiodo2 = :anioPeriodo AND
	t1.idsucursalbodega1 = :idSucursal AND
	t1.idbodega1 = :idBodega AND
	t1.fecharegistro = t1.c2


i need one linq expression that returns this sql sentence

select p.idempresa, p.id, p.idmarca, p.descripcion, d.existenciatotal, d.costototal
                from productos p
                inner join detallesinventarios d on p.idempresa = d.idempresa and p.id = d.idproducto
                inner join inventarios i on d.idperiodo = i.idperiodo and d.tipo = i.tipo and d.numero = i.numero and i.esanulado = false
                where i.idperiodo = 1 and i.idsucursalbodega1 = 1 and i.idbodega1 = 1
                  
 and i.fecharegistro = 
                   (select max(fecharegistro) from inventarios it 
                      inner join detallesinventarios dt on it.idperiodo = dt.idperiodo and it.tipo = dt.tipo and it.numero = dt.numero
                      where it.idperiodo = i.idperiodo and it.idsucursalbodega1 = i.idsucursalbodega1 and it.idbodega1 = idbodega1 
                      and dt.idempresa = d.idempresa and dt.idproducto = d.idproducto)

**Comment by pebezo** [comment]
Try using "into" like here http://stackoverflow.com/a/5440545/29821

**Comment by ferbenor** [comment]
Thank you for you response, but not work, if i not put the where clause in de sentence max then work. i think that is good idea use one vist to this case.

**Comment by ferbenor** [comment]
Please how i make with linq, 

where id in (select id from table where idcustom = 1)

**Comment by pebezo** [comment]
Sorry, only now saw you question. Hopefully you found the answer by now. For others:

http://stackoverflow.com/questions/51339/how-can-you-handle-an-in-sub-query-with-linq-to-sql

**Comment by sdanyliv** [comment]
@ferbenor, it is still actual?

**Comment by sdanyliv** [comment]
Closing for now. Will reopen if needed.
