### ISSUE TITLE
Association with byte[] Ids not working

### ISSUE THREAD

**Issue by MGRussell** [linq2db/linq2db#3109]
### Description

Creating an association where the key type is a byte[] seems to result in the associated IEnumerable not being populated. Everything works fine with ints.

## Example

I've attached a complete standalone gist that can demonstrate the issue here: https://gist.github.com/MGRussell/b6620de021c5c5e0f705a5079f8a259f

A gist with a more straight forward set of tests demonstrating the issue is available here:
https://gist.github.com/MGRussell/aa060f31f6eee108c7ea2d9414d61e97

The gist creates Left, Right, and LeftRight entities. The Left type uses an int as the associated key, and everything works fine. The Right uses a byte[] and the association fails. A manual query carrying out the same work as the association works properly.

Here is the output of that program:

> Displaying Database Contents:
Left : [0 : Left 0]
Left : [1 : Left 1]
Left : [2 : Left 2]
Right : [00-00-00-00 : Right 0]
Right : [01-00-00-00 : Right 1]
Right : [02-00-00-00 : Right 2]
LeftRight : [0 <=> 00-00-00-00]
LeftRight : [0 <=> 01-00-00-00]
LeftRight : [0 <=> 02-00-00-00]
LeftRight : [1 <=> 01-00-00-00]
LeftRight : [1 <=> 02-00-00-00]
LeftRight : [2 <=> 02-00-00-00]
Count of associated items for each Lefts (should be 3, 2, 1):
3
2
1
**Count of associated items for each Rights (should be 1, 2, 3):
0
0
0**
Count of associated items for each Rights using manual query (should be 1, 2, 3):
1
2
3

### Environment details
linq2db version: *4.0.0-preview.1*
Database Server: *-*
Database Provider: *System.Data.SQLite*
Operating system: *Win10*
.NET Framework: *6.0*

**Comment by sdanyliv** [comment]
@MaceWindu, looks like we have bad default mapping for `byte[]`. It uses abstract `VarBinary` type but should us `BLOB`

@MGRussell, define for your `byte[]` columns `DataType.Blob`

**Comment by MGRussell** [comment]
I changed the code as follows:

````
    class LeftRight
    {
        [Column(IsPrimaryKey = true, CanBeNull = false, DataType = DataType.Blob)]

    class Right
    {
        [Column(IsPrimaryKey = true, CanBeNull = false, DataType = DataType.Blob)]
````

The type in the db file has definitely been changed to blob, but it seems that the association is still not being populated.

**Comment by MGRussell** [comment]
It seems to only be an issue with associations that are collections. I added 

````
                Console.WriteLine("Loading Rights from LeftRight");
                db.LeftRights.LoadWith(x => x.Right).ForEachAsync(Console.WriteLine).Wait();
````

And the association is correctly populated yielding output of:

````
Loading Rights from LeftRight
LeftRight : [0 <=> 00-00-00-00]
LeftRight : [0 <=> 01-00-00-00]
LeftRight : [0 <=> 02-00-00-00]
LeftRight : [1 <=> 01-00-00-00]
LeftRight : [1 <=> 02-00-00-00]
LeftRight : [2 <=> 02-00-00-00]
````

That works also prior to specifying DataType = DataType.Blob

**Comment by sdanyliv** [comment]
Better throw exceptions what expected. Because it is like quest to understand your sample.

**Comment by MGRussell** [comment]
Yes, it is messy because I wanted to demonstrate a working side (int key) and a nonworking side (byte[] key). One moment. I'll clean it up a bit to make everything more clear.

**Comment by MGRussell** [comment]
OK, I added the new Gist: https://gist.github.com/MGRussell/aa060f31f6eee108c7ea2d9414d61e97

I removed the messier database test and in this case only one type of each item is created, and exceptions are thrown when the result is unexpected.

**Comment by MGRussell** [comment]
Does the above sample clearly demonstrate the issue?

**Comment by sdanyliv** [comment]
Yes, looks like we have to prepare Equals comparator for array. Working on it.

**Comment by MGRussell** [comment]
Okay, thank you for the update (and excellent library).

**Comment by MGRussell** [comment]
Any word here? Seems like this was never assigned/milestoned.

**Comment by sdanyliv** [comment]
Will try to cover that in next release. No free time.
