### ISSUE TITLE
PostgreSQL's range types, T4 & bulk insert.  

### ISSUE THREAD

**Issue by zigzag312** [linq2db/linq2db#3110]
I'm trying tu use PostgreSQL's `int4range` type with linq2db. Models are created using T4 templates. 

When using bulk insert I get an exception: Cannot guess PostgreSQL type for column my_int4range_column. Specify type explicitly in column mapping.

By default T4 generates attributes and type: 
`[Column("my_int4range_column"), Nullable] public object ...`

If I enable GenerateDataTypes in T4 it generates:  
`[Column("my_int4range_column", DataType=LinqToDB.DataType.Undefined), Nullable] public object ...`

Then I tried mapping int4range range type manually by setting column.Type = "NpgsqlRange<int>?". Generated model is now:
`[Column("my_int4range_column", DataType=LinqToDB.DataType.Undefined), Nullable] public NpgsqlRange<int>? ...`

Same exception every time. `LinqToDB.DataType` enum doesn't seem to have type appropriate for ranges.

How do I map range types correctly in T4?

### Environment details
linq2db version: I tried 3.4 & 4.0.0.-preview.2
Database Server: PostgreSQL 13
Database Provider: Npgsql
.NET Framework: .NET 5

**Comment by MaceWindu** [comment]
Try
```cs
GenerateDbTypes = true;
```

**Comment by zigzag312** [comment]
That works perfectly.

Generated attributes are now:
`[Column("my_int4range_column", DbType="int4range", DataType=LinqToDB.DataType.Undefined), Nullable]`
(for reference, if anyone bumps into similar issue in the future)

Since there are multiple properties with type in the name (DataType & DbType), exception message might be more helpful, if it can specify which type property it is referring to. 

 Thank you!
