### ISSUE TITLE
Issues with linq2Postgres and npgsql

### ISSUE THREAD

**Issue by barthr** [linq2db/linq2db#312]
I tried to get linq to postgres running with the template but got this error when i tried to query:

An exception of type 'System.TypeLoadException' occurred in mscorlib.dll but was not handled in user code
Additional information: Could not load type 'NpgsqlTypes.BitString' from assembly 'Npgsql, Version=3.0.3.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.

**Comment by MaceWindu** [comment]
Maybe you use different version of Npgsql? Then you should try to add assembly version redirect to application configuration file. Visual Studio detects such issues and generate warning clicking on which will add required redirects automatically.

**Comment by barthr** [comment]
Yes I've done that thank you! but now the class keeps saying:

Object reference not set to an instance of an object.

**Comment by MaceWindu** [comment]
you need to check stack trace for this error. If it is exception from linq2db then you should post stack trace and your code that triggers that error

**Comment by ronnyek** [comment]
Also I believe I've seen quite a few types that are just setup wrong in the npgsql provider for linq2db. Took a  while but I've managed to get them squared away for my needs. I'm working on getting the npgsql tests return any sort of useful output, and then I'll send a pull request with the fixes

**Comment by Kempe** [comment]
Hi! I have got the same problem. It's because the type NpgsqlTypes.BitString was been removed from npgsql since v3. Would be great to see your request :-)

**Comment by breakingthings** [comment]
Hi, I have made npgsql 3.x work with linq2db here is the pull request https://github.com/linq2db/linq2db/pull/265

**Comment by breakingthings** [comment]
I have mad some work with npgsql 3.x on pull request https://github.com/linq2db/linq2db/pull/265

**Comment by sdanyliv** [comment]
@ili, looks like it is already fixed.

**Comment by ili** [comment]
Yes, it should be fixed already.
