### ISSUE TITLE
SqLite Decimal -> Could not be read after storing, wrong Seperator used.

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3129]
I've a problem with storing a Decimal in sqlite to database and reading it afterwards.
Don't know if this is a linq2db or sqlite error.

When we store a decimal like 8.57 to database, it is stored as "8,57"" (maybe cause our windows is german.
But it could not be read back, cause sqlite needs "8.57" when reading.
If I change the value to 8.57 it works.
But why is sqlite storing the value not as invariantCulture. Is there a setting for this? Is this a linq2db error?

**Comment by jogibear9988** [comment]
Fixed by using "BindInvariantDecimal" Flag in Sqlite ConnectionString

**Comment by MaceWindu** [comment]
I'm pretty sure we are free of such issues now as I use dutch locale for testing. This already helped to discover similar issue at least with Informix provider.

Your fix is correct one - sqlite has buch of options to handle locale-specific behavior.
