### ISSUE TITLE
Byte[] Mapping does not work in Postgres for Bulk Copy

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3130]
I've a Property of type byte[] wich is mapped via HasDataType(DataType.Binary) in Fluent Mapping

When using normal Insert/Delete everything works.

Using BulkCopy, I get this Exception:
Cannot guess PostgreSQL type for column Data. Specify type explicitly in column mapping.

**Comment by MaceWindu** [comment]
Use `DataType.VarBinary` as workaround

**Comment by jogibear9988** [comment]
But can I specify DbType/DataType only for Postgres? 
The other Providers work with this type. Don't know if I'll break them when using another Type?

We use same mapping for All Providers we support (MsSQL, SQlite, Postgres & Oracle)

**Comment by MaceWindu** [comment]
```cs
[Column(Configuration = ProviderName.PostgreSQL, DbType = "bytea")]
[Column]
public byte[] binary {get;set;}
```

**Comment by jogibear9988** [comment]
we use FluentMapping. Is it also possible there?

**Comment by MaceWindu** [comment]
Yes, but you need to use `Entity` method to define configuration-specific changes (only changes, no need to redefine full entity):

```cs
mapper
    .Entity<SomeEntity>() // default mapping
        .Property(...)
        ...
        .Property(...)
    .Entity<SomeEntity>(ProviderName.PostgreSQL) // configuration-specific changes
        .Property(...);


```

**Comment by jogibear9988** [comment]
I've my Mapping now like this:

public ImageDTOMapping(FluentMappingBuilder mb, string tablePrefix)
        {
            mb.Entity<ImageDTO>()
                .HasTableName("Common_Images")
                .Ignore(e => e.MccEntityState)
                .Ignore(e => e.Size)
                .Property(e => e.Id).IsPrimaryKey()
                .Property(e => e.MccImageType).HasDataType(DataType.Int32)
                .Property(e => e.ImageFormat).HasDataType(DataType.Int32)
                .Property(e => e.Data).HasDataType(DataType.Binary);

            mb.Entity<ImageDTO>(ProviderName.PostgreSQL)
             .Property(e => e.Data).HasDbType("bytea");
        }

I still got this exception:

"Exception: (Cannot guess PostgreSQL type for column Data. Specify type explicitly in column mapping.) - SQL: DELETE FROM\r\n\tCommon_Images t1\r\n"}

**Comment by to11mtm** [comment]
@jogibear9988  are you using Async or Sync Bulk copy? Reason I ask is I notice that the Provider specific Copy's [sync version](https://github.com/linq2db/linq2db/blob/881adf49c15cf974a9494e680b9b138873c0d9e3/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs#L95-L102) has different type sniffing semantics than the [async versions](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs#L228-L238) and I'm not sure if that is intentional or not.

**Comment by jogibear9988** [comment]
Don't think it has to do wirh bulk copy, exception was on delete

**Comment by jogibear9988** [comment]
The new exception

**Comment by MaceWindu** [comment]
Could you clarify your issue. Error message you get generated by bulk copy implementation. How is it related to delete?

**Comment by jogibear9988** [comment]
The new error message is by delete:

      Cannot guess PostgreSQL type for column Data. Specify type explicitly in column mapping.

**Comment by MaceWindu** [comment]
btw, looks like `Entity(configuration)` doesn't work, looking into it

**Comment by MaceWindu** [comment]
As workaround you can add additional column attribute with configuration explicitly to property
```cs
.HasAttribute(new ColumnAttribute() { Configuration = ProviderName.PostgreSQL, DataType = DataType.VarBinary })
```
