### ISSUE TITLE
Postgres Insert of UInt32 to Table does not work

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3131]
I've a Property of Type UInt32. wich is Mapped via .HasDataType(LinqToDB.DataType.UInt32)

In Postgres it is of Type BigInt.

When Inserting/Deleting from/to Database I got the following Exception: Can't write CLR type System.UInt32 with handler type Int64Handler

**Comment by MaceWindu** [comment]
You can define missing conversion in mapping schema as workaround. See #3013
or probably use proper DataType for postgresql mapping (`DataType.Int64`)

**Comment by MaceWindu** [comment]
Need repro as I cannot reproduce it (found only issue with ulong to UInt64 mapping).

**Comment by viceroypenguin** [comment]
Closing as outdated with no response. Feel free to reopen if this is still an issue with current versions of l2db.
