### ISSUE TITLE
Ctor with LinqToDbConnectionOptions parameter is invalid

### ISSUE THREAD

**Issue by BergenSoft** [linq2db/linq2db#3138]
When generating the classes for the DB access it creates invalid code when running with specific settings.
Error ocoured with a MySql database, but I think the error is the some also for other databases.

### Steps to reproduce
1. Set `BaseDataContextClass = "LinqToDB.DataContext";` in your Generator.MySql.tt file
2. Save file to generate classes
3. You'll find the following code:
```c#
public partial class MyClassName : LinqToDB.DataContext
{
	// ...
	public MyClassName(LinqToDbConnectionOptions options)
		: base(options) // <-- Error here
	{
		InitDataContext();
		InitMappingSchema();
	}
	// ...
}
```

The parameter options in `base(options)` shows the following error:
CS1503 C# Argument 1: cannot convert from 'LinqToDbConnectionOptions' to 'string?'

### Environment details
linq2db version: 3.4.2
Database Provider: MySQL
Operating system: Windows 10
.NET Framework: 4.5.2

**Comment by MaceWindu** [comment]
LinqToDbConnectionOptions support by DataContext available only since v4.
You can workaround it e.g. by filtering out extra constructors by replacing GetConstructors option.
Something like that should work:
```cs
var original = GetConstructors;
GetConstructors = (p1, p2) => original(p1, p2).Take(2).Skip(2);
```

**Comment by BergenSoft** [comment]
Thanks for the very fast feedback.
It worked but without the `Skip(2)` at the end.

I'm a bit confused regarding your mentioned v4.
Is there a version 4 available? The highest I see is 3.4.2

**Comment by MaceWindu** [comment]
v4 is in preview right now (basically all from v3 + some new features) to allow use of new v4 functionality and still allow us to make breaking changes for upcoming v4 features

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/releases/tag/v4.0.0-preview.3

**Comment by BergenSoft** [comment]
Thank
