### ISSUE TITLE
Association with Expression predicate is always an OUTER JOIN

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3139]
I have created an `Association` that uses a predicate and with `CanBeNull = false`, like so:

```cs
class ENTITY
{
    public string CPARTY_THEKEY { get; set; } = null!;

    [Association(ExpressionPredicate = nameof(CpartyJoin), CanBeNull = false)]
    public QTProd.CPARTY Cparty { get; set; } = null!;

    private static Expression<Func<CONTRAT_CDR_LIEN, CPARTY, bool>> CpartyJoin =>
      (self, cparty) => self.CPARTY_THEKEY.PadRight(6) == cparty.THEKEY;
}
```

When I perform a basic query, such as:
```cs
      return (from c in db.ENTITY
              where c.Id == id
              select new
              {
                c.Id,
                CPARTY_NAME = c.Cparty.NAME,
              })
             .FirstOrDefault()!;
```

The generated SQL uses an OUTER JOIN instead of an INNER JOIN:
```sql
SELECT
	c_1.Id as Id,
	a_Cparty.NAME as CPARTY_NAME
FROM
	ENTITY c_1
		LEFT JOIN QTPROD.CPARTY a_Cparty ON RPad(c_1.CPARTY_THEKEY, 6, ' ') = a_Cparty.THEKEY
WHERE
	c_1.Id= :id
FETCH NEXT :take ROWS ONLY
```

### Environment details
linq2db version: 3.3.0
Database Server: Oracle 12
Database Provider: Managed ODP.NET
Operating system: Win 10
.NET Framework: 5

**Comment by sdanyliv** [comment]
We already have fix for that: https://github.com/linq2db/linq2db/pull/2631

**Comment by MaceWindu** [comment]
@jods4 could you please re-check this issue? It sounds like something fixed [here](https://github.com/linq2db/linq2db/pull/3921)  (first item in list)

**Comment by jods4** [comment]
@MaceWindu Tested it in my project w/ linq2db 5.1.1, looks ok. 👍
I dunno if a test case was added, otherwise example in my OP above could be used.

**Comment by MaceWindu** [comment]
Thanks! PR already adds test for it from another issue
