### ISSUE TITLE
Association one to one not working anymore when updating from 3.3 to 3.4.x

### ISSUE THREAD

**Issue by lucas-garrido** [linq2db/linq2db#3148]
Hello !
I'm using HanaProvider and since i updated to 3.4.*  associations like 
```c#
        [Association(ThisKey = "CustomerId, Mandt", OtherKey = "Id, Mandt")]
        public Customer Customer { get; set; }
```
are not working anymore, 

Error: 
Unhandled expression type: Default

![image](https://user-images.githubusercontent.com/48165310/127860913-e5d9bc18-8c5c-4d84-8e4f-b78f0fbd5802.png)

**Comment by sdanyliv** [comment]
Disable `Configuration.Linq.GenerateExpressionTest = false`. It masks original exception.

**Comment by lucas-garrido** [comment]
well this query works perfectly
![image](https://user-images.githubusercontent.com/48165310/127887642-c733001d-f598-4180-ac50-3c0c21852160.png)

i'm using graphql hotchocolate which is building queries dynamically on request.
So when i run this graphql query which is supposed to do the same thing
![image](https://user-images.githubusercontent.com/48165310/127888337-f6c0e114-070d-4300-95c3-47cd03b03ab4.png)

i have this error
![image](https://user-images.githubusercontent.com/48165310/127888509-33b73721-17d8-4ed3-a2b9-91e23d166916.png)

i suppose its not really related whith linq2db but do you know how i can investigate this ?

**Comment by sdanyliv** [comment]
If you can prepare small reproducible sample, I can help. From this exception I cannot understand what happened. Probably GraphQL library generates non translatable Expression Tree.

**Comment by MaceWindu** [comment]
Default node handling missing in one of visitors. I think I've added it only to one visitor as we had no coverage that hit other visitors and default is not usual expression node you use in your queries...

**Comment by MaceWindu** [comment]
Also we should fix testcase generator, so sample query appreciated (in text form )

**Comment by MaceWindu** [comment]
I'm removing it from next release as we need model and graphql query definition to reproduce issue.

**Comment by MaceWindu** [comment]
Reproduced, basically same issue we had before several times already. When compiler generate `Expression`'s it allows itself to perform various optimizations. In this case it generates `null` constant instead of `DefaultExpression`.

When expression generated by OData library, it generates honest `DefaultExpression` and we fail, because we had no coverage here due to Roslyn being "useful".
