### ISSUE TITLE
Is possible to acces tables without know there name

### ISSUE THREAD

**Issue by hugoaa** [linq2db/linq2db#315]
hello

i've retreive the db shema and loop trught all the tables but how can y use it to access data ?
```cs
using (var db = new commandesDB())
 {
       var sp = db.DataProvider.GetSchemaProvider();
       var shema = sp.GetSchema(db);
       foreach (var tb in schema.Tables)
      {
           var data = db.GetTable<tb>() //doesn't work
       }
}
```
many thanks by advance for your help

**Comment by ili** [comment]
You are doing smth. strange...
Please read [intro](https://github.com/linq2db/linq2db/issues/315) and watch this [video](https://www.youtube.com/watch?v=Qc-5UpMYQO0&feature=youtu.be) 

Also there are useful information in [wiki](https://github.com/linq2db/linq2db/wiki)
