### ISSUE TITLE
Nested subquery does not execute

### ISSUE THREAD

**Issue by Shane32** [linq2db/linq2db#3161]
Executing a outer apply within another outer apply can fail in recent versions of linq2db:

```cs
var ret = db.GetTable<Table1>()
	.Select(t1 => new
	{
		//retrieve Table1.Name1
		Name1 = t1.Name1,
		Value1 = db.GetTable<Table2>()
			.Where(x => x.ParentId2 == t1.Id1)
			.Select(t2 => new
			{
                                //retrieve Table2.Name2 via outer apply
				Name2 = t2.Name2,
				Value2 = db.GetTable<Table3>()
					.Where(x => x.ParentId3 == t2.Id2)
					.Select(t3 => new
					{
                                                //retrieve Table3.Name3 and Table3.Id3 via outer apply
						Name3 = t3.Name3,
						Value3 = t3.Id3
					})
					.FirstOrDefault()
			})
			.FirstOrDefault()
	})
	.ToList();
```

While a single cross apply between Table1 and Table2 works fine, adding the cross apply for Table3 breaks the sample.  For instance, the below code works fine:

```cs
var ret = db.GetTable<Table1>()
	.Select(t1 => new
	{
                //retrieve Table1.Name1
		Name1 = t1.Name1,
		Value1 = db.GetTable<Table2>()
			.Where(x => x.ParentId2 == t1.Id1)
			.Select(t2 => new
			{
                                //retrieve Table2.Name2 and Table2.Id2 via outer apply
				Name2 = t2.Name2,
				Value2 = t2.Id2
			})
			.FirstOrDefault()
	})
	.ToList();
```

The exception is the following:

```
System.Data.SqlClient.SqlException : Only one expression can be specified in the select list
when the subquery is not introduced with EXISTS.
```

The faulty code is producing invalid SQL as follows:

```sql
DECLARE @take Int -- Int32
SET     @take = 1
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT
	[t1_1].[NAME1],
	[t2].[Name2],
	[t2].[Name3],
	[t2].[Value3]
FROM
	[TABLE1] [t1_1]
		OUTER APPLY (
			SELECT TOP (@take)
				[x_1].[NAME2] as [Name2],
				/**** This portion of the SQL statment should not be 
				      present, and the query would work without it *****/
				(
					SELECT TOP (@take_1)
						[x].[NAME3],
						[x].[ID3]
					FROM
						[TABLE3] [x]
					WHERE
						[x].[PARENTID3] = [x_1].[ID2]
				) as [Value2],
				/*************************************************/
				[t1].[Name3],
				[t1].[Value3]
			FROM
				[TABLE2] [x_1]
					OUTER APPLY (
						SELECT TOP (@take_1)
							[x].[NAME3] as [Name3],
							[x].[ID3] as [Value3]
						FROM
							[TABLE3] [x]
						WHERE
							[x].[PARENTID3] = [x_1].[ID2]
					) [t1]
			WHERE
				[x_1].[PARENTID2] = [t1_1].[ID1]
		) [t2]
```

See `Tests/Linq/UserTests/Issue3161Tests.cs` for test marked with `[ActiveIssue]`.  Note that `Issue3160Tests.NestedDictionaryTest3CrossApply` works fine and is set up relatively similar, with a nested outer apply.

### Environment details
linq2db version: 3.3.0 - 4.0 beta
Database Server: SQL Server
Operating system: Windows 10
.NET Framework: .NET 5

**Comment by Shane32** [comment]
I'm now running into this problem in production on 3.4.2, or something very very similar:

> There is already an open DataReader associated with this Connection which must be closed first

Unlike the sample above, downgrading linq2db to 3.3.0 works just fine.  If needed, I could write a test to reproduce the exact scenario and add it to #3162 .  But it's extremely likely that the problem is due to this issue (which already has tests in #3162 ) or #3160 or some combination.

**Comment by sdanyliv** [comment]
Will try to resolve it.

**Comment by Shane32** [comment]
This issue failed on 3.3.0 and possibly prior, so I'm removing the 'regression' and 'eager-load' tags.  Feel free to reapply the labels if they were correct.

**Comment by Shane32** [comment]
See https://github.com/linq2db/linq2db.baselines/pull/729 for other baselines that should improve once this issue is resolved.

**Comment by Shane32** [comment]
@sdanyliv I've cleaned up the notes for this issue and we have a test in the source marked with `[ActiveIssue]`.  You may wish to review this again in case it's something simple.  I have no urgency here.  Thanks!
