### ISSUE TITLE
Incorrect order of columns in window function sort

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3164]
I've found a bug
```c#
.OrderBy(x.ForeignId)
.ThenBy(x.CreatedDate)
```

it translates into 
```sql
LAG([x].[CreatedDate], 1, NULL) OVER(PARTITION BY [x].[ForeignId] ORDER BY  [x].[CreatedDate], [x].[ForeignId])
```

_Originally posted by @mkarnovan in https://github.com/linq2db/linq2db/discussions/3159#discussioncomment-1140384_

**Comment by sdanyliv** [comment]
Already fixed in previous releases.
