### ISSUE TITLE
WHERE on boolean field when there's no boolean dbtype

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3182]
I encountered a bad SQL translation with Oracle.

My Linq query uses some `ExpressionMethod`, but basically it comes down to this:
(`Flag` is a `bool` property)
```cs
from s in db.SomeTable
where db.OtherTable.Single(o => o.Id == tcId).Flag
select s
```

Generated SQL:
```sql
SELECT * /* removed for conciseness */
FROM
	SomeTable T
WHERE
	(((
		SELECT
			ot.Flag
		FROM
			OtherTable ot
		WHERE
			ot.Id = :tcId
	)) OR /* removed for conciseness */)
```

Oracle doesn't have boolean type in SQL. `(select flag)` is not a valid condition.
In DB, `flag` is a number 1/0 and the correct translation would be:
`(select flag from...) = 1`

### Environment details
linq2db version: 3.4.0
Database Server: Oracle 12
Database Provider: Managed ODP.NET
Operating system: Win 10
.NET Framework: 4.7

**Comment by jods4** [comment]
Work-around: using `expr == true` instead of `expr` in LINQ is not "optimized" away and generates the correct query `expr = 1` in SQL.

**Comment by sdanyliv** [comment]
Create test, i’ll fix that quickly,
