### ISSUE TITLE
Sybase float column read as double by DataReader

### ISSUE THREAD

**Issue by alfhv** [linq2db/linq2db#3183]
I have a SyBase DB table with field of type "float", so I have declared a C# backend field of type "float" also.

When I execute ExecuteReader(sqlQuery), in the retourned LinqToDB.Data.DataReader class, the column type of field is "double".
When converting this double value to backend "float" field I have precission loss.

How can I force DataReader to map column to "float" type as defined in DB ?? 

### Environment details
linq2db version: 3.2.3
Database Provider: Sybase ASE
Operating system: Windows+Linux
.NET Framework: dotnet core 3.2

**Comment by MaceWindu** [comment]
1. how is database field declared? Just `float` or `float(x)`?
2. how query selects value? `select float_field` or column value is a result of some operation/function?

**Comment by MaceWindu** [comment]
Also which database provider you use? I suspect `AdoNetCore.AseClient` (a  you use non-windows platform)?

**Comment by alfhv** [comment]
AdoNetCore.AseClient => YES
column is defined just as "float" type
the column is directly in select query, no operation or function applied.

**Comment by MaceWindu** [comment]
Strange... will do some tests. Basically this behavior means database/provider reports double type for column.

If you think your problem is in float<->double conversion, you can register custom reader method in data provider:
```cs
SetProviderField<IDataReader, float, double>((dr, i) => dr.GetFloat(i));
```
As it's protected method, you need to subclass provider or register reader in `ReaderExpressions` directly: https://github.com/linq2db/linq2db/blob/c321b9fb999771d375d109111af226b184f22d8e/Source/LinqToDB/DataProvider/DataProviderBase.cs#L164

**Comment by MaceWindu** [comment]
For me to investigate it later could you provide additional information like:
- server version
- query used (with information about views if views used)

**Comment by alfhv** [comment]
unfortunally I dont have server version, it is the backend DB of proffesional trading system. Query is very simple, just a "select field where..."

where field is of type: "float NOT NULL", thats al I can get when describing the table.

**Comment by MaceWindu** [comment]
You can get version with
```sql
select @@version
```

```
Adaptive Server Enterprise/16.0 SP02 PL05/EBF 26185 SMP/P/X64/Windows Server/ase160sp02pl05x/0/64-bit/FBO/Thu Dec 15 05:07:00 2016
```
I only interested in `16.0 SP02` part

**Comment by MaceWindu** [comment]
Also you can verify size of your column (replace table and colum names with your names)
```sql
select c.name [columnName], t.name [columnType], c.length
from sysobjects o
inner join syscolumns c on c.id = o.id
inner join systypes t on t.usertype = c.usertype
where o.type = 'U' and o.name = 'AllTypes' and c.name in ('floatDataType', 'realDataType')
```

e.g. I have following results for our test table
![image](https://user-images.githubusercontent.com/1099238/130240622-d0a8d2da-972e-4541-8091-0e6bbd6108cb.png)

where you can see that `float` sybase type == .net double type (8-byte number)

**Comment by MaceWindu** [comment]
As side-note: single/double precision data types naming in databases is quite confusing - different databases use different names for those types (float, double, double precision, real, single,...) + could accept precision value as parameter which could change storage type. e.g. float could be single precision number in one db and double precision in anoher...

**Comment by alfhv** [comment]
Adaptive Server Enterprise/16.0 GA PL03/EBF 23024 SMP/P/x86_64/Enterprise Linux/ase160sp00pl02/3572/64-bit/FBO

column is of type: float with length = 8

**Comment by MaceWindu** [comment]
> column is of type: float with length = 8

In that case you should use `double` in your code. In Sybase ASE `float` could be `single`/`double precision` based on precision parameter and it looks like by default it's double precision (cannot find value for default precision in their docs, but at least it is observed behavior..)

**Comment by MaceWindu** [comment]
Actually found it here https://archive.sap.com/documents/docs/DOC-43545:
```
3) When I declare a column or variable to be of type float, there is an optional [precision] specification. What effect does this have?
...
 If you do not specify a precision and use float, the server will default to a double.
```

**Comment by alfhv** [comment]
so, even if the field is declared as float it contains actually a double value ??

it looks consistent as the value I'm receiving is a real double because when converting to float it implies precission loss...

I think it is little bit more clear now...

**Comment by MaceWindu** [comment]
Yes, ASE has:
`real` which is singe
`double precision` which is double
and `float` which is double by default but if you declare it with precision < 16 it is single (e.g. `float(15)`)

**Comment by MaceWindu** [comment]
As I said floating point types naming is a big mess across databases. ASE is not the worst case here IMHO :)
