### ISSUE TITLE
Am I using BulkCopyAsync correctly? Huge memory allocation and speed difference compared to EF Core Insert

### ISSUE THREAD

**Issue by atresnjo** [linq2db/linq2db#3190]
Right now, we're trying to figure out if we should use EF Core or linq2db. So we're doing little tests to compare the performances. I can post a sample project Monday If the screenshots aren't enough. Thanks for the great work! 🚀 

EF Core code
![image](https://user-images.githubusercontent.com/41112852/131164788-1eccc3eb-418e-4be6-9c90-899c59ef94b9.png)

linq2db code
![image](https://user-images.githubusercontent.com/41112852/131164587-71e94896-b392-4e3a-9bac-ca7a2de20567.png)

Benchmark code:
![image](https://user-images.githubusercontent.com/41112852/131165278-424e1e0b-748a-4b7f-8430-f9fbb8800a96.png)

Benchmark result:

![image](https://user-images.githubusercontent.com/41112852/131164295-efa34ae2-723e-4b8d-893e-b2775772f32b.png)

What am I doing wrong?

### Environment details
linq2db version: 4.0.0 - preview.4
Database Provider: PostgreSQL
Operating system: Windows 10
.NET Framework: .NET 5.0

**Comment by MaceWindu** [comment]
That's quite big difference, so test project is appreciated to investigate possible memory issues.
For starters I will recommend to enable native bulk copy (by default for postgresql we use `BulkCopyType.MultipleRows`):
```sql
// change pgsql bulk copy method globally
PostgreSQLTools.DefaultBulkCopyType = BulkCopyType.ProviderSpecific;
// or pass BulkCopyOptions with type set to BulkCopy method
```

**Comment by to11mtm** [comment]
> 
> 
> I'm trying to measure the speed and memory allocations the ORMs require when inserting ~20 objects. We're working in a serverless context and would prefer a solution that's more lightweight than EF Core, but yet offers powerful linq to sql abilities, just like linq2db. 👍

@atresnjo would you be able to do one or more of the following:

 - Upload a sample project somewhere with the code being used or similar
 - Provide more detail on the setup of `TemporaryDbContextFactory`
 - Try MaceWindu's suggestion of Provider specific copy
 - Try adding a `BulkCopyOptios` where `UseParameters` is set to true
   - I don't think this will help memory usage much, but it might. It is most helpful when inserting large binary/string data.


In other tests of bulk insert Linq2Db [has done well enough I'd expect your numbers to be inverted](https://github.com/FransBouma/RawDataAccessBencher/blob/master/Results/20210615_net5.txt#L248-L258).

**Comment by atresnjo** [comment]
@MaceWindu @to11mtm 

Thanks for the help so far. I've applied your suggestions and the difference is still there. 

I've made a [sample project](https://github.com/atresnjo/linq2db_performance_sample) where I've made the models as small as possible, hence the memory usage is reduced in the screenshot. In the sample project, just call CreateDb to create the tables. Hope that's enough. 

![image](https://user-images.githubusercontent.com/41112852/131365048-025105f5-257e-4459-817c-647c2065d7fd.png)

**Comment by sdanyliv** [comment]
Not sure that we can beat EF Core in such case. They generate only one database roundtrip for 21 records, but with linq2db there is 4 requests. For such small amount of records and if Ids are generated on the client (it is important), EF Core works pretty good. But when it become thousands records, performance dramatically slowdown. For example: https://www.michalbialecki.com/2021/01/21/bulk-copy-with-entity-framework-core-5/

**Comment by atresnjo** [comment]
> 
> 
> Not sure that we can beat EF Core in such case. They generate only one database roundtrip for 21 records, but with linq2db there is 4 requests. For such small amount of records and if Ids are generated on the client (it is important), EF Core works pretty good. But when it become thousands records, performance dramatically slowdown. For example: https://www.michalbialecki.com/2021/01/21/bulk-copy-with-entity-framework-core-5/

I think even then linq2db is faster. I've checked my code, and it seems I was making a mistake 🥇  when I was generating the entities using AutoFaker. For linq2db it was generating unnecessary objects which are ignored now. Updated my repository with the changes.

Here are the current results
![image](https://user-images.githubusercontent.com/41112852/131532622-5bb25604-ef8e-472f-bb2b-305d291e7641.png)

I'm going to close this issue for now as it is resolved. I'll comment again if I have any new findings. 👍 

Thanks for the great work! 🚀

**Comment by MaceWindu** [comment]
aww, just 5 seconds before I posted this picture :)
![image](https://user-images.githubusercontent.com/1099238/131533475-09421f68-21ac-4ace-9ac2-d8f1f07c16bd.png)

**Comment by MaceWindu** [comment]
That's results with test data generation removed from benchmarked code

**Comment by to11mtm** [comment]
@atresnjo one more parting comment on this issue:

> - Try adding a BulkCopyOptios where UseParameters is set to true
>   -  I don't think this will help memory usage much, but it might. It is most helpful when inserting large binary/string data.

If you are -not- inserting large binary/string data, `UseParameters` set to `true` can actually have lower performance. The reason for this is that we have pretty good string building code (even on smaller binary data we are light on alloc) and when parameters are used there can be a penalty for validating parameters on server side, marshaling etc.


Note: Most Provider specific copy routines *always* use parameters, but some (like Postgres) aren't used by default because they are a lot more particular about parameter types, whereas the 'generic' bulk copy will create normal Insert statements.
