### ISSUE TITLE
Don't select unnecessary columns

### ISSUE THREAD

**Issue by artelk** [linq2db/linq2db#3192]
```cs
bool b = false;
var q = from t in db.Tbl1
        select new
        {
            t.C1,
            Other = b ? new { t.C2, t.C3, t.C4 } : null
        };
```
The SQL executed is:
```sql
SELECT
        [t].[C1],
        [t].[C2],
        [t].[C3],
        [t].[C4]
FROM
        [Tbl1] [t]
```
The property `Other` in the results is null. But it loads the columns C2, C3 and C4 from the DB.
Desired behavior: don't load columns which aren't needed.

**Comment by Usaga** [comment]
This is bad approach. When you do not need some columns, you just do not select them and use DTO without properties for that columns.

**Comment by sdanyliv** [comment]
This optimisation is not supported. Currently we do not optimise expression tree based on parameters. Will take a look, probably it makes sense to do that for conditional expression.

**Comment by artelk** [comment]
Now it works but it seems it caches the resulting query so if you change the `b` value and execute the query again it won't select C2, C3, C4. This can be a breaking change for some apps.

**Comment by sdanyliv** [comment]
I don't understand. What is breaking change?

**Comment by artelk** [comment]
```cs
var list = q.ToList();
b = !b;
list = q.ToList(); // here it works as if b wasn't changed
```

**Comment by sdanyliv** [comment]
I see, forgot to check this cache variant. Here we cache plan by reference. Thanks for mentioned that.
