### ISSUE TITLE
linq2db call stored procedure

### ISSUE THREAD

**Issue by guyfawkess** [linq2db/linq2db#323]
How can i call stored procedure with linq2db?

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/Data/CommandInfo.cs
CommandInfo.QueryProc
CommandInfo.ExecuteProc
CommandInfo.ExecuteReaderProc
CommandInfo.ExecuteProcAsync
Those methods available on DataConnection using extension methods from here:
https://github.com/linq2db/linq2db/blob/master/Source/Data/DataConnectionExtensions.cs
Example:
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Data/ProcedureTest.cs

**Comment by guyfawkess** [comment]
Thank you!

**Comment by work-des** [comment]
And what if the procedure returns a cursor?
`CREATE OR REPLACE PROCEDURE USER_SETUP.PROC1 (a IN MENU.ID%TYPE, y OUT SYS_REFCURSOR)
as
BEGIN
   OPEN y FOR
    SELECT * FROM MENU WHERE ID < a;
END;`

**Comment by ili** [comment]
@work-des try `QueryProc`
