### ISSUE TITLE
SetLength \ Column.Size seems to be ignore when inserting \ updating

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#3231]
Hello.

I noticed that setting string property length is ignored at insert \ update:

```C#
MappingSchema.GetFluentMappingBuilder()
    .Entity<MasterName>()
        .Property(t => t.Cii)
            .HasLength(2);

// ...

var r2 = con.MasterNames
    .Where(x => x.Id == 55)
    .Set(x => x.Cii, model.Cii)
    .Update();
```

```sql
BeforeExecute
--  SqlServer.2012
DECLARE @Cii NVarChar(4000) -- String has default length
SET     @Cii = N'cii'

UPDATE
        [x]
SET
        [x].[Cii] = @Cii
FROM
        [v1].[MasterName] [x]
WHERE
        [x].[Id] = 55
```

There is no validation on client or query variables length set propely. What this ability for? Is it used for something or is just broken?

**Comment by MaceWindu** [comment]
Type facets like length, precision or scale used for:

- database type name generation (e.g. for table create statement or type cast expression)
- type equality logic
