### ISSUE TITLE
BulkCopy with Identity column in Oracle

### ISSUE THREAD

**Issue by KarlssonBernoulli** [linq2db/linq2db#3239]
I use a table with an Identity column among other columns configured like this:

builder.Property(x => x.Id)
.IsPrimaryKey()
.HasColumnName("ID")
.IsIdentity();

Using 
```await db.BulkCopyAsync(myList);```
results in a unique constraint violation of the ID column. All x.Id properties in ``` myList``` are 0 (default). I assumed that values of IDENTITY columns are created server-side in ```BulkCopy``` but this is obviously not the case. Am I missing sth.?

Using ```myItem.Id = await db.InsertWithInt64IdentityAsync(myItem);``` works with ID created server-side.

I also tried to configure an additional entity without the ID column but same table name as a workaround since I am in a hurry but with no success.

Since I have 30k+ entities in the list I need to use BulkCopy for performance reasons.

### Environment details
linq2db version: 3.3.0
Database Server: Oracle Database 19c  19.0.0.0.0
Database Provider: *?*
Operating system: *?*
.NET Framework: *?*

**Comment by MaceWindu** [comment]
Oracle bulk copy [doesn't implement](https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleBulkCopyOptionsEnumeration.htm#ODPNT7690) identity insert functionality, so if you need to insert with identity, best option is to use `BulkCopyType.MultipleRows`

**Comment by MaceWindu** [comment]
Actually, maybe it will work if identity column excluded from insert operation, but it needs testing. You can try it by using mapping without identity column defined.

**Comment by KarlssonBernoulli** [comment]
@MaceWindu Actually I added an additional configuration with a new entity with excluding the ID column. I named the table as in the original entity but it did not work.

Your other suggestion was to insert with identity and use ```BulkCopyType.MultipleRows```. What do you mean by saying "insert with identity"? Creating them on the client?

**Comment by sdanyliv** [comment]
@KarlssonBernoulli, I have written simple  test with Oracle. Everything works and `BulkCopy` do not insert columns which are identity columns by default. I'm talking about latest library version.

Try to debug project, `linq2db` can be debugged via SourceLink or just add reference to `linq2db` in your solution.

**Comment by KarlssonBernoulli** [comment]
@sdanyliv, so you mean 

1. using BulkCopy with Oracle and an ID defined as IDENTITY column and server-sided ID creation should be working? Or rather
2. @MaceWindu 's suggestion configuring an extra entity excluding the ID column should be working?

1 or 2?

**Comment by sdanyliv** [comment]
First is working for me. By default we do not insert identity columns. I‘ve tried Managed prvider.

**Comment by KarlssonBernoulli** [comment]
Now I upgraded  "linq2db" and "linq2db.Oracle.Managed" to 3.4.5 (both). Still not as expected.

If there is just one item in ```myList``` in ```db.BulkCopy(new BulkCopyOptions { BulkCopyType = BulkCopyType.MultipleRows}, myList); ``` it works and the ID is generated server-sided. If there are two the unique constraint violation exception occurs.

**Comment by sdanyliv** [comment]
Show your Model and MappingSchema configuration.

**Comment by KarlssonBernoulli** [comment]
Model:
`
public class NumericData
{
     public long Id {get;set;}
     public long ParameterId {get;set;}
     public long MetadataId {get;set;}
     public decimal Value {get;set;}
}
`

Mapping Schema:
`
var builder = fluentBuilder.Entity<NumericData>();
builder.HasTableName("NUMERICDATA");

builder.Property(x => x.Id)
.IsPrimaryKey()
.HasColumnName("ID")
.IsIdentity();

builder.Property(x => x.ParameterId).HasColumnName("PARAMETERID");
builder.Property(x => x.MetadataId).HasColumnName("METADATAID");
// leaving out the associations - not relevant here.
`

Then I invoke like this:
`
// works with Take(1)
await db.BulkCopyAsync(new BulkCopyOptions { BulkCopyType = BulkCopyType.MultipleRows}, myList.Take(1).ToList());

// does not work with Take(2) => Exception unique constraint violation (CONSTRAINT_TYPE is 'P' for Primary_Key => I looked up the name in the user_constraints sys table, TABLE_NAME is 'NUMERICDATA')

await db.BulkCopyAsync(new BulkCopyOptions { BulkCopyType = BulkCopyType.MultipleRows}, myList.Take(2).ToList());
`

**Comment by sdanyliv** [comment]
Well, there is my test, which works:
```cs
[TestFixture]
public class TestTemplate : TestBase
{
	public class NumericData
	{
		public long    Id          {get; set;}
		public long    ParameterId {get; set;}
		public long    MetadataId  {get; set;}
		public decimal Value       {get; set;}
	}

	[Test]
	public async Task SampleSelectTest([IncludeDataSources(TestProvName.AllOracleManaged)] string context)
	{
		var ms = new MappingSchema();
		
		var mappingBuilder = ms.GetFluentMappingBuilder();

		var builder = mappingBuilder.Entity<NumericData>();
		builder.HasTableName("NUMERICDATA");

		builder.Property(x => x.Id)
			.IsPrimaryKey()
			.HasColumnName("ID")
			.IsIdentity();

		builder.Property(x => x.ParameterId).HasColumnName("PARAMETERID");
		builder.Property(x => x.MetadataId).HasColumnName("METADATAID");

		using (var db = GetDataContext(context, ms))
		using (var table = db.CreateLocalTable<NumericData>())
		{
			var data = Enumerable.Range(1, 100)
				.Select(x => new NumericData { Id = x, Value = x, ParameterId = x, MetadataId = x });

			await table.BulkCopyAsync(data);
		}
	}
}
```
It generates SQL:
```sql
INSERT ALL
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (1,1,1)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (2,2,2)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (3,3,3)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (4,4,4)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (5,5,5)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (6,6,6)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (7,7,7)
	INTO NUMERICDATA (PARAMETERID, METADATAID, "Value") VALUES (8,8,8)
       ...
SELECT * FROM dual
```
Check which SQL is generated in your case.
Check foreign keys if any, probably they need correct ID for other table.

**Comment by KarlssonBernoulli** [comment]
Does ```cs CreateLocalTable<NumericData>``` create an IDENTITY column for Id?

**Comment by KarlssonBernoulli** [comment]
Ok, Identity is used.

**Comment by KarlssonBernoulli** [comment]
Sorry, I clicked the wrong button.
What about leaving Id = 0 (default)? Does it still work?



.Select(x => new NumericData { Id = x, Value = x, ParameterId = x, MetadataId = x });

**Comment by sdanyliv** [comment]
Yes, SQL is the same. Try to debug our code and check why your `ID` column is used for insert.

**Comment by KarlssonBernoulli** [comment]
I found out what the problem is:

https://stackoverflow.com/questions/56233576/insert-all-causes-unique-constraint-of-primary-key-violated

**Comment by MaceWindu** [comment]
Reopen. We should fix it. Don't see a reason to generate INSERT ALL over INSERT FROM here, especially taking into account such side-effects...

**Comment by MaceWindu** [comment]
I don't think there should be performance difference between `INSERT ALL` vs `INSERT FROM SELECT`, but if it exists - we could generate second form only for entities with identity

**Comment by MaceWindu** [comment]
Hmm, actually it looks like we don't need to change anything. We already support other forms of INSERT for oracle using following setting:
```cs
OracleTools.UseAlternativeBulkCopy = AlternativeBulkCopy.InsertDual;
```

**Comment by MaceWindu** [comment]
This mode also works with identity columns (check docs [here](https://github.com/linq2db/linq2db/pull/3245/files#diff-3b077b7f38a4fbeb26753bbb7379e1b73d7ea25b0151cb7a01e11f8fc404b241R36))
```cs
OracleTools.UseAlternativeBulkCopy = AlternativeBulkCopy.InsertInto;
```

I don't know how oracle provider implements it internally, so it could be more performant than `InsertDual` mode or slower.
