### ISSUE TITLE
Some mechanism to serialize object structure to text field

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#324]
Given, I know in a lot of cases its frowned upon and databases wont index or handle data serialized into xml/json at the database level well...  Postgres supports json very well.

I currently use ormlite(servicestack) and would love to be able to get away from it. By default if you have a poco that is mapped and say one of its properties is Address, which is set to an instance of Address object... ormlite sticks that into a text column called Address,and is the serialized form of address.

Would it be a ton of work to perhaps add a mapping attribute and have the engine serialize that item, so that we're not affecting default behavior,but could utilize if we wanted to?

Would you be open to a pull request if someone was willing to contribute that?

**Comment by ronnyek** [comment]
I actually implemented this, but dont know how well it plays with silverlight etc... Works well for my needs (introduces depdency on json.net)
def42bddf8d7ebb145362af1eead6a8346a5245b for reference. If its remotely close I can pull request it in

**Comment by jogibear9988** [comment]
I think this should worke like I used here: https://github.com/linq2db/linq2db/issues/339
(but it doesn't atm)

**Comment by ronnyek** [comment]
Any chance of this becoming a thing? I attempted to add it myself so i could do a pull request, and I got it mostly working, but dont know about how it;d affect ability to query with linq etc. (Personally I'd probably never be trying to query manually against a property that gets serialized to json object, but... could see how that might be a concern)

**Comment by ronnyek** [comment]
Any updates? Any pointers as far as things I could model this after? I'd just really like to be able to automatically serialize simple objects rather than trying to break them out into their own table with individual fields

**Comment by jogibear9988** [comment]
@ili this works (i use json.net in a project to serialize data into a column). can be closed !

i'll add a example

**Comment by ili** [comment]
I think @ronnyek will close issue after getting an example :)

**Comment by ronnyek** [comment]
yeah I'm interested... I"d love to get away from ormlite... orm lite... if a column is json type, and property is object... it'll generate json. Even if I had to mark up with an attribute (to be more explicit) that would be pretty awesome.

**Comment by ronnyek** [comment]
@jogibear9988 coudl we even see a basic gist? Does it require setting up some manual mapping for a specific type?

**Comment by jogibear9988** [comment]
MappingSchema.Default.SetConverter<List<string>, string>((obj) =>
            {
                if (obj == null)
                    return null;
                return StringSerializer.Serialize(obj);
            });
            MappingSchema.Default.SetConverter<List<string>, DataParameter>((obj) =>
            {
                if (obj == null)
                    return new DataParameter { DataType = DataType.VarChar, Value = DBNull.Value };
                return new DataParameter { Value = StringSerializer.Serialize(obj) };
            });
            MappingSchema.Default.SetConverter<string, List<string>>((txt) =>
            {
                if (string.IsNullOrEmpty(txt))
                    return null;
                return StringSerializer.DeSerialize<List<string>>(txt);
            });

where StringSerializer is our class. but for example you could use json.net and jsonconvert

**Comment by ronnyek** [comment]
@ili if I was able to provide similar functionality via attribtues, so as to not have to write a custom converter for every weird type you'd want to be able to convert... is that worthy of a pull request? Json.Net is capable of dynamically handling json->type conversion.

Also, any input on the handling of expression tree etc? Eg, if my type is List<string> and someone builds a query that does where(x=>x.contains("something")... I dont know how you'd WANT to handle that without building in json stuff as a first class citizen.

**Comment by ili** [comment]
Not sure what case are you talking about, like this:
```cs
[ConvertExpresionPtovider(typof(MyObjectConvertExpressions))]
public MyObject Property;
```

I'm not sure this is really needed - now it can be specified once and globally via mapping schema.

If you are ready to implement this feature it would be good. And as for me for now it is better to fix issues marked as bug :)

**Comment by ronnyek** [comment]
Basically like [JsonNetProperty] and basically have it create necessary registrations... but I'v ebeen able to build a generic method that handles those 3 necessary type registrations and have a list of types to run it against, so I think we're good!

Appreciate the tips!

**Comment by ronnyek** [comment]
Ok, so I got this all built, and it all works in reading data out of the database just fine.... but fails because its trying to setup the write query such that its using "string" as the variable type. Says that doesnt comply with the data type json or jsonb.

DataTypes understandably doesn't have json/jsonb types just yet. Is there anyway without having to subclass postgres provider to say for these properties I'm converting over, use this explicit type (bypassing the mapping etc)?

**Comment by ili** [comment]
Can you provide minimal test?

**Comment by ronnyek** [comment]
I went ahead and built tests, and figured out what it'd take to get those tests to pass. 
Built #586

**Comment by ronnyek** [comment]
I haven't worked out the details, but if its cool, I'd like to also

1. Build an attribute as discussed above
2. Either build a new MetadataReader, or integrate into the LinqMetadataReader
3. Have the above two components end up doing the work required above for setting up a map from this type to that type.

Questions:
1. Is it a problem to add additional dependency on newtonsoft to facilitate broad json conversion? (I added a dependency in the above pull request in the test project so I could generate/parse json.
2. Would it make more sense to decouple by way of MappingSchema.Default.SerializeExpression?

**Comment by CoskunSunali** [comment]
Would love to see this implemented. I would have made a PR myself if allowed (which probably is) and if I had enough experience with linq2db (which I don't sadly).

The attribute approach sounds like a great idea to provide re-usability as well as doing things at runtime instead of design time.

**Comment by sdanyliv** [comment]
@CoskunSunali, i'm implementing now more flexible mechanism for mapping here: https://github.com/linq2db/linq2db/pull/1263 

I'll check if we can support some **universal** mapping attribute for such fields without breaking library design.
Also you have consider that JSON (Newtonsoft for example) is additional dependency and we are trying to avoid this.

**Comment by CoskunSunali** [comment]
@sdanyliv I understand you want to avoid an additional dependency and that is just fine. If we could (maybe we can already?) create our own attributes, then it would only be a decision of the developer what is added as a dependency. I mean, I could easily create JsonSerializedSomethingAttribute and add the dependency there instead of you adding it to the core. If that makes sense.

**Comment by sdanyliv** [comment]
Attribute will not help if you have variable of JSON type and want to use it in linq query. So it’s why defining convertors is better approach.
