### ISSUE TITLE
Supported Linq Scenarios... (some wich in bltoolkit work don't work in linq2db)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#325]
If you look at the "ormbattle" linq tests results:

https://github.com/sdanyliv/ormbattle/blob/master/_Reports/Output.txt

you see that bltoolkit supports some linq scenarios wich do not work in linq2db! Could this be fixed?

**Comment by sdanyliv** [comment]
@jogibear9988, i'll update my repostiry later. Will check if there critical bugs still exist.

**Comment by jogibear9988** [comment]
ahh, ormbattle was your repo... shame on me

**Comment by sdanyliv** [comment]
It's not mine idea and implementation. I did reincarnation an year ago )
