### ISSUE TITLE
Aggregate without group by

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3250]
Issue #679 suggests using a dummy `group by 1` to perform queries that have a global aggregate without a `GROUP BY`, such as:
```sql
select count(*)
from T
```

It does work but it doesn't generate nice queries as the constant is not dropped by Linq2db.
For example, this LINQ code:
```csharp
from s in db.ITEMS
where s.NOT_HANDLED != "ERROR"
   && s.DAT_CRE < DateTime.Now.AddMinutes(-15)
group s by 1 into g
where g.Count() > 0
select new MonitoringError
{
  Message = $"{g.Count()} items have not been processed, e.g. #{g.Min(x => x.ID)}.",
}
```
Generates this SQL, that introduces a sub-select for the constant 1:
```sql
SELECT
        Count(*),
        Min(t1.ID)
FROM
        (
                SELECT
                        1 as Key_1,
                        s.ID
                FROM
                        ITEMS s
                WHERE
                        s.NOT_HANDLED <> 'ERROR' AND s.DAT_CRE < :DAT_CRE
        ) t1
GROUP BY
        t1.Key_1
HAVING
        Count(*) > 0
```
A work-around is to use analytical extensions from `Sql.Ext` without windows. 
This works but if you put one inside a `Where` clause, it's not extracted into a `HAVING` as regular aggregates do. 
You have to do this using the explicit `Having` method, which is not nice to use inside LINQ, being a method call that may require several captured variables.

In this simple example, one can switch from LINQ to method calls and write:
```csharp
db.ITEMS
  .Where(s => s.NOT_HANDLED != "ERROR"
           && s.DAT_CRE < DateTime.Now.AddMinutes(-15))
  .Having(_ => Sql.Ext.Count().ToValue() > 0)
  .Select(s => new MonitoringError
  {
    Message = $"{ Sql.Ext.Count().ToValue() } items have not been processed, e.g. #{ Sql.Ext.Min(s.ID).ToValue() }.",
  })
```
Which generates the very clean SQL:
```sql
SELECT
        COUNT(*),
        MIN(s.ID)
FROM
        ITEMS s
WHERE
        s.NOT_HANDLED <> 'ERROR' AND s.DAT_CRE < :DAT_CRE
HAVING
        COUNT(*) > 0
```

Some ideas that could improve the usability of this:
- Ignore constants in `group by`. 
- When analytical functions are used without a window inside a WHERE, their expression should go inside `HAVING` rather than `WHERE`, like regular aggregates. In fact, it's forbidden to use a true analytical function inside `WHERE` anyway.

**Comment by MaceWindu** [comment]
Fixed in 4.4.0 (note it is currently badly regressed in v6)
