### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3253]
We have encountered a very similar issue however even the latest (```3.4.5```) version doesn't seem to fix this. It has improved but it's not on the same level as before. Our situation is the following, we upgraded from ```2.9.0``` to ```3.1.6``` and noticed that the memory usage of our application was quite a bit higher then before.

So i setup a small console project that executes an update command on an in memory ```SQLite``` database ([link to repo](https://github.com/aarondk-dev/Linq2DbMemory/tree/master)), and added some benchmarking library.
Not only is the memory usages in ```2.9.0``` much better, the performance is also quite a lot better. These are the result when run on my machine:

3.4.5
|                                                         Method |        Mean |       Error |      StdDev |    Gen 0 |   Gen 1 | Allocated |
|--------------------------------------------------------------- |------------:|------------:|------------:|---------:|--------:|----------:|
|                 Small_UpdateStatement_With_Variable_Parameters |  7,148.1 us |   105.17 us |   121.11 us |  93.7500 | 62.5000 |    414 KB |
|                   Small_UpdateStatement_With_Static_Parameters |    183.0 us |     2.94 us |     3.27 us |   5.3711 |       - |     22 KB |
|                  Large_UpdateStatement_With_Variable_Paramters | 25,341.0 us |   483.85 us |   557.20 us | 125.0000 |       - |    922 KB |
|                    Large_UpdateStatement_With_Static_Paramters |    293.6 us |     4.63 us |     4.96 us |   8.7891 |       - |     36 KB |
| Large_UpdateStatement_With_Variable_Paramters_With_ClearCaches | 19,227.3 us | 1,071.55 us | 1,234.00 us |  62.5000 | 31.2500 |    298 KB |

3.1.6
|                                                         Method |        Mean |       Error |      StdDev |    Gen 0 |   Gen 1 | Allocated |
|--------------------------------------------------------------- |------------:|------------:|------------:|---------:|--------:|----------:|
|                 Small_UpdateStatement_With_Variable_Parameters | 11,831.9 us |   176.45 us |   188.80 us | 140.6250 | 62.5000 |    675 KB |
|                   Small_UpdateStatement_With_Static_Parameters |    245.3 us |    31.17 us |    35.90 us |   6.1035 |       - |     25 KB |
|                  Large_UpdateStatement_With_Variable_Paramters | 38,473.9 us | 2,112.70 us | 2,260.57 us | 312.5000 |       - |  1,593 KB |
|                    Large_UpdateStatement_With_Static_Paramters |    326.5 us |     5.19 us |     5.33 us |   9.2773 |       - |     39 KB |
| Large_UpdateStatement_With_Variable_Paramters_With_ClearCaches | 16,906.5 us |   263.30 us |   303.22 us |  93.7500 | 31.2500 |    403 KB |

2.9.0
|                                                         Method |       Mean |    Error |   StdDev |    Gen 0 |   Gen 1 |  Gen 2 | Allocated |
|--------------------------------------------------------------- |-----------:|---------:|---------:|---------:|--------:|-------:|----------:|
|                 Small_UpdateStatement_With_Variable_Parameters | 2,386.7 us | 34.38 us | 39.59 us |  50.7813 | 15.6250 | 3.9063 |    248 KB |
|                   Small_UpdateStatement_With_Static_Parameters |   169.0 us |  6.39 us |  6.83 us |   4.8828 |       - |      - |     21 KB |
|                  Large_UpdateStatement_With_Variable_Paramters | 5,290.6 us | 43.50 us | 46.55 us | 125.0000 |  7.8125 |      - |    567 KB |
|                    Large_UpdateStatement_With_Static_Paramters |   264.9 us |  8.48 us |  9.43 us |   7.8125 |       - |      - |     33 KB |
| Large_UpdateStatement_With_Variable_Paramters_With_ClearCaches | 1,999.7 us | 24.64 us | 26.36 us |  35.1563 | 11.7188 |      - |    151 KB |

The thing is that when the update statement contains the same values in the set (in other words ```set(columnname, value)```), there seems to be no problem. It is only when the value changes that the issue arises.

When analysing the problem with ```dotMemory```, you can see that there are a lot of ```QueryCacheEntry<TESTTABLE>``` objects in memory, while in 2.9.0 this is not the case (I don't think ```QueryCache<T>``` was a thing in ```2.9.0```).
This memory snapshot is after executing ```Large_UpdateStatement_With_Variable_Paramters``` 200 times.

3.1.6
![3 1 6_querycache](https://user-images.githubusercontent.com/92315531/136805352-2a32cb93-aa8e-4447-aa95-b67a7801ed1a.PNG)

Also the sql text of the update is saved in memory a hundred times:
![3 1 6_stringduplicate](https://user-images.githubusercontent.com/92315531/136805417-3d8bd5e0-8a30-4177-af4b-c8df499b7431.PNG)

This seems a bit weird to me.

2.9.0
![2 9 0_querycache](https://user-images.githubusercontent.com/92315531/136806268-3729463a-0ea4-445b-b06d-d8d954135094.PNG)
![2 9 0_stringduplicate](https://user-images.githubusercontent.com/92315531/136806271-a68f4b8e-3362-474a-bbfb-1be33253ac96.PNG)

The weird part to me is how 2.9.0 seems to use less memory and is more performant. It would be ok if 3.1.6 had higher memory usage but the queries were faster. But this isn't the case. Also adding ```Query.ClearCaches``` after the update statement seems to **improve** the performance and the memory usage, this to me indicates that something is wrong.

_Originally posted by @aarondk-dev in https://github.com/linq2db/linq2db/issues/2556#issuecomment-940080728_

**Comment by MaceWindu** [comment]
I've identified issue with Set method making query cache useless (even harmful). Will see what we can do here...

**Comment by MaceWindu** [comment]
Good news. Looks like in next release we will have huge improvement here. I've managed to fix mentioned issue with Set and already got huge perf/memory bust. Still need to check other APIs for similar issues and check if there is more space for fixes.

**Comment by aarondk-dev** [comment]
Thanks a lot for the answers!

I've updated [my repo](https://github.com/aarondk-dev/Linq2DbMemory/tree/master) so that a compiled query is included in the benchmarks. And indeed the performance is very impressive, we're going to try and use this more in our code.

I've tested  #3254 with the benchmark project and the performance difference is very impressive.
|                                                         Method |        Mean |     Error |    StdDev |   Gen 0 |   Gen 1 | Allocated |
|--------------------------------------------------------------- |------------:|----------:|----------:|--------:|--------:|----------:|
|                 Small_UpdateStatement_With_Variable_Parameters |    272.1 us |  11.06 us |  11.83 us |  6.8359 |       - |     28 KB |
|                   Small_UpdateStatement_With_Static_Parameters |    284.7 us |  23.51 us |  27.07 us |  6.8359 |       - |     28 KB |
|                  Large_UpdateStatement_With_Variable_Paramters |    395.0 us |   5.54 us |   5.69 us | 12.2070 |       - |     51 KB |
|                    Large_UpdateStatement_With_Static_Paramters |    432.9 us |  27.75 us |  30.84 us | 12.2070 |       - |     51 KB |
| Large_UpdateStatement_With_Variable_Paramters_With_ClearCaches | 16,691.9 us | 239.28 us | 256.02 us | 62.5000 | 31.2500 |    298 KB |
|         Large_Compiled_UpdateStatement_With_Variable_Paramters |    124.9 us |   0.89 us |   0.91 us |  5.3711 |       - |     23 KB |

Unfortunately we are using a ```db2 database``` so for now we are 'stuck' on version 3.1.6. Maybe we will be able to add these changes to 3.1.6 as well.

**Comment by aarondk-dev** [comment]
>  Still need to check other APIs for similar issues and check if there is more space for fixes.

I was curious and just checked the insert ```.Value``` api, and this one is also affected. The good news is using the lambda expression overload works as well. The PR (as you probably expect) doesn't fix this issue. ([link to updated repo](https://github.com/aarondk-dev/Linq2DbMemory/tree/master/Linq2DbPerformanceRegression))
2.9.0
|                                                                   Method |       Mean |     Error |    StdDev |   Gen 0 |   Gen 1 |  Gen 2 | Allocated |
|------------------------------------------------------------------------- |-----------:|----------:|----------:|--------:|--------:|-------:|----------:|
|                           Small_InsertStatement_With_Variable_Parameters | 2,766.1 us |  94.42 us | 108.73 us | 50.7813 | 15.6250 | 3.9063 |    245 KB |
|                             Small_InsertStatement_With_Static_Parameters |   172.7 us |   5.91 us |   6.80 us |  4.8828 |       - |      - |     20 KB |
|                            Large_InsertStatement_With_Variable_Parameters | 2,399.9 us | 281.18 us | 312.53 us |       - |       - |      - |    256 KB |
|                              Large_InsertStatement_With_Static_Parameters |   403.5 us |  38.68 us |  42.99 us |       - |       - |      - |     48 KB |
|           Large_InsertStatement_With_Variable_Parameters_With_ClearCaches | 2,052.1 us | 176.70 us | 196.40 us |       - |       - |      - |    160 KB |
|                   Large_Compiled_InsertStatement_With_Variable_Parameters |   114.8 us |   5.02 us |   5.15 us |  3.2959 |       - |      - |     14 KB |
| Large__InsertStatement_With_Variable_Parameters_Using_Expression_Overload |   302.8 us |  18.21 us |  18.70 us |  8.7891 |       - |      - |     38 KB |


3.1.6
|                                                                   Method |        Mean |     Error |    StdDev |    Gen 0 |    Gen 1 | Allocated |
|------------------------------------------------------------------------- |------------:|----------:|----------:|---------:|---------:|----------:|
|                           Small_InsertStatement_With_Variable_Parameters | 13,441.1 us | 326.26 us | 375.72 us | 171.8750 | 171.8750 |    726 KB |
|                             Small_InsertStatement_With_Static_Parameters |    202.9 us |   1.34 us |   1.49 us |   6.1035 |        - |     25 KB |
|                            Large_InsertStatement_With_Variable_Parameters | 41,029.5 us | 371.83 us | 413.29 us | 343.7500 |  31.2500 |  1,616 KB |
|                              Large_InsertStatement_With_Static_Parameters |    330.2 us |   2.66 us |   3.06 us |   9.2773 |        - |     40 KB |
|           Large_InsertStatement_With_Variable_Parameters_With_ClearCaches | 19,311.7 us | 242.38 us | 279.12 us |  93.7500 |  31.2500 |    423 KB |
|                   Large_Compiled_InsertStatement_With_Variable_Parameters |    113.9 us |  13.54 us |  15.59 us |   3.7842 |        - |     16 KB |
| Large__InsertStatement_With_Variable_Parameters_Using_Expression_Overload |    363.5 us |   8.10 us |   9.33 us |   9.2773 |        - |     39 KB |


3.4.5
|                                                                   Method |         Mean |      Error |       StdDev |    Gen 0 |    Gen 1 | Allocated |
|------------------------------------------------------------------------- |-------------:|-----------:|-------------:|---------:|---------:|----------:|
|                           Small_InsertStatement_With_Variable_Parameters | 14,676.57 us | 960.232 us | 1,067.296 us | 156.2500 | 156.2500 |    688 KB |
|                             Small_InsertStatement_With_Static_Parameters |    209.06 us |   4.785 us |     5.319 us |   5.8594 |        - |     25 KB |
|                            Large_InsertStatement_With_Variable_Parameters | 44,671.08 us | 735.965 us |   818.023 us | 343.7500 |  31.2500 |  1,616 KB |
|                              Large_InsertStatement_With_Static_Parameters |    336.59 us |   3.474 us |     4.001 us |   9.7656 |        - |     41 KB |
|           Large_InsertStatement_With_Variable_Parameters_With_ClearCaches | 19,035.09 us | 116.229 us |   124.364 us |  93.7500 |  31.2500 |    421 KB |
|                   Large_Compiled_InsertStatement_With_Variable_Parameters |     95.38 us |   3.814 us |     4.393 us |   3.7842 |        - |     16 KB |
| Large__InsertStatement_With_Variable_Parameters_Using_Expression_Overload |    343.33 us |  12.396 us |    14.275 us |   9.2773 |        - |     40 KB |

**Comment by pebezo** [comment]
Unfortunately, at least for our use case, 3.5.0 doesn't seem to fix the issue:

![image](https://user-images.githubusercontent.com/1287097/137397542-1d7a3dbd-da5b-4ac3-be21-10aa49380b86.png)

The Y-axis is from 0 to 100%. It's currently using 95% of the CPU. With version 3.4.5 and a compiled query (only for Update) the CPU was around 25%. It's a pretty big update query (58 columns), so maybe that's why. I'll try to reproduce the problem with @aarondk-dev repro...

**Comment by MaceWindu** [comment]
Please create new issue and provide repro code so we can investigate it
