### ISSUE TITLE
Distributed transaction completed. Either enlist this session in a new transaction or the NULL transaction.

### ISSUE THREAD

**Issue by stomasovic** [linq2db/linq2db#3256]
Hi,

We have recently started moving away from EntityFramework toward some lightweight ORM and linq2db was selected as preferred solution. Linq2db for the time being is used for Querying only (readonly).

One of the issues we encountered was above Exception. It happened while we were using TransactionScope for Insert/Update using EntityFramework, but within transaction some queries were run using linq2db and when using same DataConnection after TransactionScope completed above exception fired. It was resolved by registering OnConnectionOpened event and if ConnectionOpened happened within ambient transaction we UnEnlist that transaction, example code: 
```cs
using AmbientTransaction = System.Transactions.Transaction;
private void OnConnectionOpenedEventHandler(DataConnection dataConnection, System.Data.IDbConnection dbConnection)
{
	if (AmbientTransaction.Current != null)
	{
		AmbientTransaction.Current.TransactionCompleted += this.AmbientTransactionCompleted;
	}
}
private void AmbientTransactionCompleted(object sender, TransactionEventArgs e)
{
	var transactionStatus = e.Transaction.TransactionInformation.Status;

	if (transactionStatus == TransactionStatus.Committed || transactionStatus == TransactionStatus.Aborted)
	{
		var dbConnection = (DbConnection)this.Connection;
			dbConnection.EnlistTransaction(null);
	}
}
```

### Environment details
linq2db version: 3.2.3, but also 3.4.5.
Database Server: SQL Server 2019
Database Provider: SQL
Operating system: W10
.NET Framework: 4.8.2

**Comment by sdanyliv** [comment]
Please make two separate issues for better tracking fix and answers.

**Comment by MaceWindu** [comment]
Not sure what expected here. Linq To DB stays away from transaction scope management and we recommend users to handle it on their side
