### ISSUE TITLE
Is there a way to make the DB2 provider use System.Data.Odbc to connect and execute queries?

### ISSUE THREAD

**Issue by Coreinsanity** [linq2db/linq2db#327]
We currently have an AS/400, and we can connect to it just fine with ODBC and run queries manually using System.Data.Odbc. But, when you want to use IBM.Data.DB2, you end up having to look at licensing - which it looks like we don't have. 

We have the i Navigator, which comes with an IBM.Data.DB2.iSeries, but this won't work with that (It actually looks to have not only a different namespace but different (but at first glance similar) objects.

So, I was essentially wondering if there's a way to either: 
1) Make DB2 use System.Data.Odbc to connect, execute queries, and get results
2) Or, make DB2 provider use IBM.Data.DB2.iSeries

Preferably without writing a new provider.

Thanks

**Comment by tb-mtg** [comment]
I have attempted to create an AS400 / iSeries Data Provider based on IBM.Data.DB2.iSeries. 

See Issue https://github.com/linq2db/linq2db/issues/221 & https://gist.github.com/tb-mtg/5aaf36df5cddda3dc6d8

I've been testing it in house for a while now & it has been working fine. I'm just not sure how to get this code properly included into this project.

**Comment by Coreinsanity** [comment]
Hey, thanks for the info. I'll look into those for sure!

**Comment by Coreinsanity** [comment]
I'm closing this one as the one @tb-mtg references so far matches mine and fixes the issue.
