### ISSUE TITLE
Use COALESCE instead of NVL for nested ??

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3273]
This is not a bug, everything works fine. It's a small SQL codegen improvement.

linq2db uses `nvl` to translate `??`, which is nice because it's shorter than SQL standard `coalesce`.

The trick with `nvl` is that it only accepts 2 parameters, whereas `coalesce` accepts many.

In our codebase, we have a query that computes an error message based on a list of checks, it looks like this:
![image](https://user-images.githubusercontent.com/3832820/137727050-7c7ec386-00b1-4a30-b4cc-522e93636f35.png)

That's 7 `??` chained. 
The resulting SQL is of course 7 nested nvls: `nvl(.., nvl(.., nvl(.., /*4 more*/)))))))`.
It works well enough, I just think it'd be easier to read if it was a single `coalesce(.., .., .., .., .., .., ..)`.

So my suggestion is to convert nested `??` expressions into a single `coalesce` instead of nested `nvl`.
This expression tree: 
![image](https://user-images.githubusercontent.com/3832820/137727612-2d510dc4-e5f5-4bfa-af68-8711e4bbfab8.png)
Could be converted into `coalesce(A, B, C, D, E)` (i.e. a depth-first traversal).

A related Oracle SQL codegen you could have is convert patterns `a == null ? c : d` (and `a != null`) into `nvl2(a, d, c)` (resp. a, c, d).
nvl2 is another Oracle proprietary function that returns the 2nd arg if the first is not null, and the 2rd arg is the first is null.

**Comment by ddas09** [comment]
Thanks @MaceWindu

**Comment by MaceWindu** [comment]
yes, just add test and check how it works without that 'case'. if it doesn't work, you need to write required 
function conversion there

**Comment by jods4** [comment]
No, I think it's better to keep that case. It calls `ConvertCoalesceToBinaryFunc`, who does the job of converting COALESCE into NVL:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#L2536-L2551

What would be required here is to modify this function slightly:
- If there are two parameters (very common), you can keep the conversion to `nvl(a, b)`.
- Otherwise, stick to original expression `coalesce(a, b, c, d)`.

**Comment by jods4** [comment]
The bonus point in this ticket is to optimize expressions 
`case when x is null then a else b` into `nvl2(x, a, b)` and 
`case when x is not null then a else b` into `nvl2(x, b, a)`.

**Comment by MaceWindu** [comment]
@ddas09, just to clarify what is going in that place:

linq2db parses LINQ query and generates generic query AST, which then modified by sql optimizer for specific database provider into form, compatible with database.

In this specific method (`ConvertExpressionImpl`) we convert generated expressions including functions (in our case `coalesce(params)`) to form, supported by specific database.

**Comment by ddas09** [comment]
@jods4, I think I am missing something, please shed some light here. I am not getting why we need to convert the expression two nvl(a, b) in case of two params. coalesce(a, b) will do the same right?

**Comment by ddas09** [comment]
> No, I think it's better to keep that case. It calls `ConvertCoalesceToBinaryFunc`, who does the job of converting COALESCE into NVL: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#L2536-L2551
> 
> What would be required here is to modify this function slightly:
> 
> * If there are two parameters (very common), you can keep the conversion to `nvl(a, b)`.
> * Otherwise, stick to original expression `coalesce(a, b, c, d)`.

So, this is the only restoration needed in this ticket?

**Comment by ddas09** [comment]
@MaceWindu / @jods4, can you please give me the repo access?
![image](https://github.com/linq2db/linq2db/assets/75975903/0934e79c-6672-4623-8c14-dbca858d1c62)

**Comment by ddas09** [comment]
Thanks for the information @jods4, as I am very new to this process, this really helps. I would cover both improvements in my PR.

**Comment by ddas09** [comment]
> @ddas09 the usual Github process is to fork the repo in your account and open a PR from there.
> 
> > So, this is the only restoration needed in this ticket?
> 
> The original ticket had a 2nd improvement listed: rewrite `case when x is not null then a else b` into `nvl2(x, a, b)` rewrite `case when x is null then a else b` into `nvl2(x, b, a)` and.
> 
> But if you've fixed the `nvl(nvl(nvl(..)))` case, you can open a PR for that and it'll be a welcome merge. We can edit the issue description to indicate that half of it is done.
> 
> If you feel like doing both, then that's even more awesome.

And here x, a, and b are the function parameters in the order 1, 2, and 3. Is that correct? @jods4

**Comment by ddas09** [comment]
> rewrite `case when x is not null then a else b` into `nvl2(x, a, b)`
> rewrite `case when x is null then a else b` into `nvl2(x, b, a)`

Here x, a, and b are the function parameters in increasing order? @MaceWindu / @jods4

**Comment by jods4** [comment]
@ddas09 `NVL2(expr1, expr2, expr3)` definition is:
- Evaluates to `expr2` if `expr1` is not null;
- Evaluates to `expr3` if `expr1` is null.

So the transformations I listed above should be correct.

For reference: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/NVL2.html#GUID-414D6E81-9627-4163-8AC2-BD24E57742AE

**Comment by ddas09** [comment]
@jods4, thanks for the explanation. I got it how NVL2 works, but what I am not clear about is where this change would be applicable. Is it for the cases where we have coalesce with three params - x, a, and b?

**Comment by jods4** [comment]
No, `coalesce(x, a, b)` is a different function. It would return `x` when it's not null.

This transformation should match `case when x is [not] null then A [else B] end` expressions.

You'll need to do a bit of research and test, but to put you on track:
- I believe CASE expressions are actually represented by `SqlFunction` with a magic name `CASE` in AST.
- So the right place to "optimize" them is to override `ConvertFunction` from `BaseSqlOptimizer` in `Oracle11SqlOptimizer`. The declaration is here: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#LL2025C41-L2025C41
- Probably best not to touch `SqlFunction` that have `DoNotOptimize` property set.
- The first parameter should be an instance of `SqlPredicate.IsNull` (it has an `IsNot` property, so both cases are handled with a single AST node).
