### ISSUE TITLE
Invalid Oracle SQL for boolean IN clause

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3277]
Assuming column `Boolean` is declare as a `bool`, the following predicate:
```csharp
var list = new List<bool> { true };
var query = db.GetTable<X>().Where(x => list.Contains(x.Boolean));
```
Compiles to the following invalid SQL: 
```sql
WHERE (x.Boolean IS NULL) IN (1)
```
A better translation would be:
```sql
WHERE x.Boolean IN (1)
```

### Environment details
linq2db version: 3.5.0
Database Server: Oracle 19
Database Provider: Oracle.ManagedProvider
Operating system: Win 10
.NET Framework: .net 4.8

**Comment by viceroypenguin** [comment]
Closing as outdated with no response. If this is still an issue, please file a new issue with information from a current version of l2db.
