### ISSUE TITLE
Wrong SQL generated (Skip >Take > Contains)

### ISSUE THREAD

**Issue by TCGV** [linq2db/linq2db#329]
I believe the following C# code:

```cs
    var group = GetTable<User>().OrderBy(x => x.Id).Skip(offset).Take(limit).Select(x => x.Id);
    var result = GetTable<Answers>().Where(a => group.Contains(a.UserId));
```

Should be translated to this SQL query:

```sql
SELECT
    t1."Id",
    t1."UserId",
    t1."QuestionId",
    t1."Text"
FROM
    "Answers" t1
WHERE
    "UserId" IN (
        SELECT
            "Id"
        FROM
            "Users"
        ORDER BY
            "Id"
        LIMIT 10000 OFFSET 0 
    );
```

But instead it is being translated to:

```sql
SELECT
    t1."Id",
    t1."UserId",
    t1."QuestionId",
    t1."Text"
FROM
    "Answers" t1
WHERE
    EXISTS(
        SELECT
            *
        FROM
            "Users" t2
        WHERE
            t2."Id" = t1."UserId"
        ORDER BY
            t2."Id"
        LIMIT 10000 OFFSET 0 
    );
```

I was hoping to select answers for a specif group of users, but the resulting query is returning answers for all users in my database since the `LIMIT` clause is having no effect within the `EXISTS` condition.

And if an `OFFSET` greater than zero is used, then my result set ends up empty.

I'm currently using Linq2DB version 1.0.7.3 along with PostgreSQL.

**Comment by jogibear9988** [comment]
@ili have you any idea about this issue?

**Comment by ili** [comment]
I think we should fix it :)
