### ISSUE TITLE
Is there anyway to intercept a query before it's sent to the db

### ISSUE THREAD

**Issue by garethbudden** [linq2db/linq2db#331]
Hi all,
I guess the title pretty much says it all, I'd like to intercept the query expression and modify it before it's sent to the database.  Is this currently possible?

**Comment by xlievo** [comment]
I would also like to intercept the generated SQL......

**Comment by pebezo** [comment]
MiniProfiler is able to intercept (output) the generate SQL, but I'm not sure about being able to change it. What are you trying to do?

**Comment by sdanyliv** [comment]
@garethbudden, look at this example
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Exceptions/CommonTests.cs

In method **ProcessQuery** is sample transformation.
It's not obvious but if it is really needed - it's possible.

**Comment by sdanyliv** [comment]
@garethbudden, will reopen if help is still needed.
