### ISSUE TITLE
String Substring fails when having column values less then index start

### ISSUE THREAD

**Issue by stomasovic** [linq2db/linq2db#3316]
Hi

When using Substring method on a string property (varchar property on database), it fails when having column length less then substring index start property.

Exception is:
`
System.Data.SqlClient.SqlException: 'Invalid length parameter passed to the LEFT or SUBSTRING function.'
`

Example, if you want to project string column Phone with expression
x => x.Phone.Length > 3 ? x.Phone.Substring(3) : null

It is working fine if Phone length is >= 3 or NULL, but if it is has length less then 3 (empty or 1 or 2) it fails with above exception.

`
Id Phone
1  '1'
2  '15552225525'
`

Instead of producing this SQL:
`
IIF(Len([a].[Phone]) > 3, Substring([a].[Phone], 4, Len([a].[Phone]) - 3), null)
`
it produce 2 columns:
`
Len([x].[Phone]),
Substring([x].[Phone], 4, Len([x].[Phone]) - 3)
`

Code to reproduce issue:
```
using LinqToDB;
using LinqToDB.Mapping;
using System.Linq;

namespace Linq2dbTest
{
    public class SubstringTest
    {
        public void Test()
        {
            var builder = MappingSchema.Default.GetFluentMappingBuilder();

            builder.Entity<Applicant>()
                .HasTableName("Applicants")
                .HasSchemaName("Ats")
                .Property(x => x.Id).HasColumnName("Id").IsPrimaryKey();

            using (var db = new Db())
            {
                var query = db.Applicants
                    .Where(x => new [] {1, 2}.Contains(x.Id));

                var good = query.ToList();
                var bad = query.Select(x => new
                {
                    x.Id,
                    PhonePart = x.Phone.Length > 3 ? x.Phone.Substring(3) : null
                })
                .ToList();
            }
        }

        public class Db : LinqToDB.Data.DataConnection
        {
            public Db() : base(ProviderName.SqlServer2017, "data source=localhost;initial catalog=xxx;integrated security=True;MultipleActiveResultSets=True") { }
            public ITable<Applicant> Applicants => GetTable<Applicant>();
        }

        public class Applicant
        {
            public virtual int Id { get; set; }
            public virtual string Phone { get; set; }
        }
    }
}
```

### Environment details
linq2db version: 3.5.1.
Database Server: Sql Server 2019
Database Provider: SQL
Operating system: W10
.NET Framework: 4.8.2

**Comment by jods4** [comment]
You should be able to work around it by wrapping the expression in `Sql.AsSql(...)`.

From what I see, linq2db wants to evaluate the conditional on the client-side, and evaluates only the sub-expressions on the server-side.

`AsSql()` is a hint to linq2db that you want an expression to be evaluated at server-side, even when client-side is possible.

**Comment by stomasovic** [comment]
Hi jods4,

This really helped. Using Sql.AsSql produced IIF into the query and it is working fine now.

Thank you very much.

**Comment by stomasovic** [comment]
Closing the issue as above comment from @jods4 resolves the issue.
