### ISSUE TITLE
Union with calculated column throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3323]
Copied from https://rsdn.org/forum/prj.rfd/8126584.1

---

Ситуация следующая

```cs
[Table("Parners")]
class Partner
{
    [Column(SkipOnEntityFetch=true)]
    public string Name {...}
    [ExpressionMethod(nameof(...),IsColumn=true)] //здесь выражение основано на Name
    public string Display {...}
}
```

само по себе оно работает, но вот уже вместе с Concat нет:

```cs
var query = DB.Partners.Concat(DB.Partners);
```

при получении данных ругается:

   ` System.ArgumentOutOfRangeException: "Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name"`

**Comment by marcnet80** [comment]
Looks like the issue in multiple places: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlQuery/SqlStatement.cs#L197 and https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#L178 in case when count of SelectQuery.Select.Columns doesn't match count of Select.Columns.
