### ISSUE TITLE
Extension `AsValueInsertable` for IQueryable<T> ?

### ISSUE THREAD

**Issue by MihailsKuzmins** [linq2db/linq2db#3327]
Based on https://stackoverflow.com/questions/69882757/iupdatablet-and-ivalueinsertablet-from-optional-values

IQueryable has an extension `AsUpdatable` which allows building dynamic blocks with `Set()`, but there is no extension which would cast `ITable<T>` to `IValueInsertable<T>`. Would it be possible to add it?

P.S. is it ok that I have created both the stackoverflow question and this issue?

### Environment details
linq2db version: 3.5.1

**Comment by sdanyliv** [comment]
For which purpose do you need that?

**Comment by MihailsKuzmins** [comment]
for the same purpose as `AsUpdatable` with optionals, i.e.
```cs
var optional1 = Optional<int>.None();
var optional2 = Optional<int>.Of(123);

var table = Database.MyTable; // ITable<MyRecord>
if (optional1.HasValue) table = table.Value(x => x.Optional1, optional1.Value);
if (optional2.HasValue) table = table.Value(x => x.Optional2, optional2.Value);

await table.InsertAsync();
```

**Comment by MihailsKuzmins** [comment]
Thank you. Not a perfect solution for my case (generally my extension methods only have `ITable<T>` not the whole `IDataContext`), but it's better than nothing

So if you do not plan to include creation of `IValueInsertable<T>` from `ITable<T>` please feel free to close the issue

**Comment by sdanyliv** [comment]
Well, you can try implement it by yourself. PRs are welcome .

**Comment by MihailsKuzmins** [comment]
I will try to do something, but my VS enters the berserk mode as soon as I try doing something in the solution 😞 

![image](https://user-images.githubusercontent.com/47413092/140995495-b07c7e2f-98bd-4476-9bf5-9a8734f1c5ce.png)

**Comment by sdanyliv** [comment]
Use `linq2db.Playground.slnf` and link only needed tests.

**Comment by MaceWindu** [comment]
merged
