### ISSUE TITLE
Access DB ODBC support?

### ISSUE THREAD

**Issue by Ohmeohmy** [linq2db/linq2db#333]
My web host requires an ODBC connection for MS Access databases.  How do I create a connection string for an ODBC DSN?

**Comment by ili** [comment]
We do not support ODBC.
Why can't you use OleDb?

**Comment by tb-mtg** [comment]
I semi-working version based on the [OleDb](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Access/AccessDataProvider.cs) version by simply replacing the refrences of System.Data.OleDb to System.Data.Odbc.

The only problem I am having is that I think named parameters in OdbcCommands are not supported which is being used in OleDbCommands.

**Comment by tb-mtg** [comment]
This extension method may help (taken from [here](https://gist.github.com/dcolthorp/965749) & [here](https://spin.atomicobject.com/2013/01/21/fake-named-parameters-net-odbc/))

```
  internal static class OdbcConnectionExtensions {
        static readonly Regex NamedParameterPattern = new Regex(@"\?(\w+)");

        public static OdbcCommand CreateCommandWithNamedParameters(this OdbcConnection connection, string sql, IDictionary<string, object> parameters)
        {
            var cmd = connection.CreateCommand();
            var parameterIndex = 0;
            cmd.CommandText = NamedParameterPattern.Replace(sql, (m) => {
                var key = m.Groups[1].Value;
                var value = parameters[key];
                var parameterName = string.Format("{0}_{1}", key, parameterIndex++);

                if ((value as string) != null || (value as IEnumerable) == null) {
                    cmd.Parameters.AddWithValue(parameterName, value ?? DBNull.Value);
                    return "?";
                } else {
                    var enumerable = (IEnumerable<object>)value;
                    var i = 0;
                    foreach (var el in enumerable) {
                        var elementName = string.Format("{0}_{1}", parameterName, i++);
                        cmd.Parameters.AddWithValue(elementName, el ?? DBNull.Value);
                    }
                    return string.Join(",", enumerable.Select(_ => "?"));
                }
            });
            return cmd;
        }
    }
```

**Comment by sdanyliv** [comment]
@tb-mtg, please switch to `release.3.0` branch. In version 3, providers are refactored a lot.

**Comment by MaceWindu** [comment]
@tb-mtg could you provide more details why you prefer to use odbc driver over OleDb Jet or ACE drivers (except that OleDb currently broken in .net core). It is not a big deal to support it, I just want to know if it opens some new use-cases.

**Comment by tb-mtg** [comment]
@MaceWindu  ODBC is required because as you mentioned, OleDb is not supported in .Net Standard or .Net Core.

**Comment by MaceWindu** [comment]
Well, it is supported, but right now has issue, which makes it's unusable due to broken transactions. [Fix](https://github.com/dotnet/runtime/pull/32573) will be released in 3.1.4 next month

**Comment by tb-mtg** [comment]
An alternative to using  CreateCommandWithNamedParameters method i mentioned above to handle positional parameters instead of named parameters is to override part of the AccessSqlBuilder.Convert in a new class. Something like:

```
public class AccessSqlBuilder_Odbc : AccessSqlBuilder {
    ...
    protected override string GetProviderTypeName(IDbDataParameter parameter) => ((OdbcParameter)parameter).OdbcType.ToString();

    public override object Convert(object value, ConvertType convertType) {
      switch (convertType) {
        case ConvertType.NameToQueryParameter:
        case ConvertType.NameToCommandParameter:
        case ConvertType.NameToSprocParameter:
          // Use positional parameters rather than named parameters;
          return "?";
        default:
          return base.Convert(value, convertType);
      }
    }
    ...
  }
```

**Comment by tb-mtg** [comment]
I also had to set SqlProviderFlags.IsParameterOrderDependent = true in AccessDataProvider_Odbc 

```
public class AccessDataProvider_Odbc : DataProviderBase {
    ..
    protected AccessDataProvider_Odbc(string name, MappingSchema mappingSchema) : base(name, mappingSchema) {
      ...
      // Use positional parameters rather than named parameters;
      SqlProviderFlags.IsParameterOrderDependent = true;
      ...
    }
    ...
}
```

**Comment by MaceWindu** [comment]
@tb-mtg , I'm currently finishing work on ODBC provider, probably will upload it in 1-2 days. It works in general but needs some polishing.
But I'm quite disappointed that it is less functional in SQL and SCHEMA area compared to OleDb provider, so I would say it's better to use OleDb when available.

**Comment by tb-mtg** [comment]
@MaceWindu : Cant wait to check out the new ODBC provider.

However, I can't use the OleDb provider as I am using .NET Standard / .Net Core.  

We needed to convert the OleDb [AccessDataProvider](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Access/AccessDataProvider.cs) code into a .NET Standard class library without any references to OLEDB, and build an ODBC Access provider inheriting & overriding that.

I noticed that [SapHanaOdbcDataProvider.cs](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcDataProvider.cs) does similar.

**Comment by MaceWindu** [comment]
@tb-mtg see #2188

Regarding iSeries provider main issue preventing us from including it into linq2db (if it's owners willing to do it) is not dependencies, but that we don't have database to test it. Without testing it is possible to ship code that could be completely broken. We are not SAP to affort such approach :smile:

**Comment by MaceWindu** [comment]
Also as I said, upcoming .net core 3.1.4 release should include OleDb fixes, that will make OleDb provider usable in .net core (windows only)
