### ISSUE TITLE
Division of Sql.DateDiff

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3332]
I'd like to count the number of rows within date range intervals. It works but it seems to be calculated on the client.
```DataConnection.LastQuery``` is not what I expect.

The calculation should start from now to the past in equal date range intervals. I started without the grouping just for testing.

```c#
var interval = new TimeSpan(1,0,0,0).TotalSeconds;
context.Events.Select(x => new {Bla = Sql.DateDiff(Sql.DateParts.Second, x.MyDate, now) / interval}).ToList();
```

LastQuery returns
```sql
SELECT
    (CAST (:now as DATE) - CAST (x.MYDATE as DATE)) * 86400
FROM
   TEVENT x
```

The ```Sql.DateDiff``` is calculated on the server, the division on the client according to LastQuery.

How can I achieve this? Additionally I think I will need the Sql.Floor around the expression in Bla. But step by step.

### Environment details
linq2db version: 3.4.5
Database Server: Oracle
Database Provider: *?*
Operating system: *?*
.NET Framework: *?*

**Comment by sdanyliv** [comment]
Wrap expression by `Sql.AsSql`
```cs
var interval = new TimeSpan(1,0,0,0).TotalSeconds;
context.Events
    .Select(x => new 
    {
        Bla = Sql.AsSql(Sql.DateDiff(Sql.DateParts.Second, x.MyDate, now) / interval)
    })
    .ToList();
```

**Comment by HypeillingerChillinger** [comment]
Works perfectly. Thanks.
