### ISSUE TITLE
[Nuget] Add nuget readme

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3335]
https://devblogs.microsoft.com/nuget/introducing-the-new-nuget-org-package-details-page/

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile

**Comment by Leandro48** [comment]
Hi, I want to help you in these issue. But I need more information about what I need to do here.

**Comment by MaceWindu** [comment]
Well, there are two tasks:
1. technical - add required readme.md files to repository and include them into nuget generation
2. documentation - decide what kind of informaiton we want to put into those readme files

As second part is probably too complex for first-time PR, I propose to implement first part initially.

There are 4 groups of nugets we release on regular basis:
- `linq2db` : main library
- `linq2db.AspNet`: asp.net core helpers
- `linq2db.Tools`: various utility code
- `linq2db.<DB_NAME>`: T4 templates for specific database

Nuget sources located here: https://github.com/linq2db/linq2db/tree/master/NuGet

I propose to do following:
1. add `<nuget_name>.readme.md` empty files for each nuspec file to this folder or for T4 readme to corresponding subfolders
2. add those new files to solution
3. register readme's in nuspec. Example could be found here: https://github.com/linq2db/linq2db.LINQPad/blob/master/Build/linq2db.LINQPad.nuspec - lines 11 and 47 (note that we need to specify target attribute to rename `<nuget_name>.readme.md` to `readme.md` on nuget build)

This should cover technical part of this task and after that we could add actual test to readme files.
