### ISSUE TITLE
Merge operation improvements

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#334]
It would be nice, if Merge operation will allow to specify what columns should be merged. Currently it just copy all updateable columns from source to target.

Also (mentioned already in #234) it would be nice to have set expressions configurable, not just source to target copy.

**Comment by ili** [comment]
PR? :)))

**Comment by MaceWindu** [comment]
see https://github.com/linq2db/linq2db/issues/337#issuecomment-292606854
