### ISSUE TITLE
Support Sql.Like also for queries against objects

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3347]
We have a UI where the user can Filter data in Tables, wich moste of the time are handled via linq2db and directly read from database.

But some tables are read from in memory collections. But the user could create the same queries against, cause we use AsQueryable.

So could we include support for "SqlLike" so it also works against objects.

**Comment by jogibear9988** [comment]
I'll create a pull req for this.

**Comment by jogibear9988** [comment]
Still linq2db could throw if it will be executed on client side. I only want to have it workin when I don't use linq2db

**Comment by sdanyliv** [comment]
Don’t think so. Sql.Like is server side method. If you want client side evaluation. Create new Like on your side.

**Comment by jogibear9988** [comment]
Okay, then I post the Code here, so it don't get lost.
Maybe someone has same problem somtime...


		[Function(ServerSideOnly = true)]
		public static bool Like(string? matchExpression, string? pattern)
		{
			return Regex.IsMatch(matchExpression, Regex.Escape(pattern).Replace("%", ".*").Replace("_", "."));
		}

		[Function(ServerSideOnly = true)]
		public static bool Like(string? matchExpression, string? pattern, char? escapeCharacter)
		{
			if (pattern == null) return true;

			var sb = new StringBuilder();
			for (int i = 0; i < pattern.Length; i++)
			{
				if (pattern[i] == '%')
					sb.Append(".*");
				else if (pattern[i] == '_')
					sb.Append('.');
				else if (escapeCharacter.HasValue && pattern[i] == escapeCharacter.Value)
				{
					if (pattern.Length == i + 1)
						return false;
					if (pattern[i + 1] == '%' || pattern[i + 1] == '_')
					{
						sb.Append(pattern[i + 1]);
						i++;
					}
					else
					{
						sb.Append(Regex.Escape(pattern[i + 1].ToString()));
						i++;
					}
				}
			}
			return Regex.IsMatch(matchExpression, sb.ToString());
		}
