### ISSUE TITLE
Merge without insert

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#335]
Currently merge operation generates:
WHEN MATCHED THEN UPDATE
WHEN NOT MATCHED BY Target THEN INSERT
WHEN NOT MATCHED BY Source THEN DELETE
delete operation could be enabled or disabled. Could you add and option to disable insert operations too?

**Comment by ili** [comment]
PR? :)

**Comment by MaceWindu** [comment]
See see https://github.com/linq2db/linq2db/issues/337#issuecomment-292606854
