### ISSUE TITLE
Bug report from PVS-Studio

### ISSUE THREAD

**Issue by MrKruizer** [linq2db/linq2db#3355]
Hello!

We have found bugs using [PVS-Studio](https://pvs-studio.com/) tool (static code analyzer for C, C++, C#, and Java).

Here is the report: [PVS-Studio checks the code quality in the .NET Foundation projects: LINQ to DB](https://pvs-studio.com/en/blog/posts/csharp/0887/)

**Comment by MaceWindu** [comment]
Thanks!

**Comment by MaceWindu** [comment]
code in GetPublicInstanceValueMembers : just need to remove whole if - it is an intermediate implementation code, that survived cleanup
