### ISSUE TITLE
How to remove summary of property of data context?

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#3361]
Guys how to configure such comments in BeforeGenerateModel?

```C#
/// <summary>
/// VIEW
/// </summary>
internal ITable<MyViewItem>           MyViewItems           { get { return this.GetTable<MyViewItem>(); } }
```

type.Comment.Clear() removes summary only on class definition but not on property of data context.

**Comment by MaceWindu** [comment]
Should disappear if you set `table.Description = null;`

**Comment by hardhub** [comment]
> Should disappear if you set `table.Description = null;` in loaded data model

The following does NOT work:

```C#
BeforeGenerateModel = () => {
        this.GenerateTypesFromMetadata();

        foreach (TypeBase type in this.Model.Types)
        {
            // Table
            if (type is Table)
            {
                Table table = (Table)type;

                // View
                if (table.IsView == true)
                {
                    table.BaseClass = null;
                    table.Description = null; // Does nothing.
                    table.Comment.Clear(); // Clears on table itself.
                }
            }
        }
    };
```

Maybe too old T4 templates? Do you know any fixes last time regarding that?

**Comment by MaceWindu** [comment]
You are trying to clear comments from code model (this could work, but requires cleanup on both class and property), but you need to do it on data model. Check this link https://linq2db.github.io/articles/T4.html#example-of-generation-process-customization

Basically, before call to `GenerateModel()` which will take database model and generate code model, you need to enumerate tables and clear Description on them. Something like that should work:
```cs

foreach (var t in Tables.Values)
    t.Description = null;
```

**Comment by hardhub** [comment]
Not sure I understand...

> this could work, but requires cleanup on both class and property

How to do that? `Model` contains only Namespace, Types, and Parent properties.

**Comment by hardhub** [comment]
It is also empty outside of delegate and filled only after `LoadMySqlMetadata` calling, so it is not possible to control some comments in own ttinclude files.

So some comments can be removed using Model and some not... it a bit inconsistent behaviour.

**Comment by MaceWindu** [comment]
with linq2db.cli it is possible to remove description in schema load interceptors https://github.com/linq2db/linq2db/tree/master/NuGet/CLI#schema-load-interceptors=
