### ISSUE TITLE
PostGIS extension in bulk copy

### ISSUE THREAD

**Issue by SebastianBienert** [linq2db/linq2db#3368]
Do I understand correctly that PostGIS (Spatial and Geographic objects for PostgreSQL) are not supported for BulkCopy with ProviderSpecific type (BINARY COPY)? In the documentation PostGIS data types are not mentioned ([link](https://linq2db.github.io/articles/sql/Bulk-Copy.html#postgresql-provider-specific-bulk-copy)) and in the source code itself ([link](https://github.com/linq2db/linq2db/blob/881adf49c15cf974a9494e680b9b138873c0d9e3/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs#:~:text=private%20void%20ConfigureTypes())) I cannot see handling of NpgsqlDbType.Geometry. When I try to run it in my project I always get following exception for one of PostGIS column with ```geometry(Geometry,4326)``` data type:

```
Exception: (Cannot guess PostgreSQL type for column. Specify type explicitly in column mapping.)
```

**Comment by MaceWindu** [comment]
Yes, currently type detection logic doesn't allow you to specify additional types. We need to extend it to allow registration of missing types or add Geometry to list of known types.

**Comment by MaceWindu** [comment]
Hopefully (not tested for postgis specifically, but in general should work on our side) should work in next release with #3461 merged.

You will need to specify `DbType = "geometry"` in column mapping.
