### ISSUE TITLE
More freedom on merge actions configuration

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#337]
Currently merge supports
WHEN MATCHED THEN UPDATE
WHEN NOT MATCHED BY TARGET THEN INSERT
WHEN NOT MATCHED BY SOURCE THEN DELETE

It will be more usefull, if type of operation could be specified by user.
E.g. in combination with #336 I would like to perform delete of matched records (by primary key and additional field, added as extra predicate).
Another example:
delete by match on composite primary key (no custom predicates required)

**Comment by ili** [comment]
What about PR? :)

**Comment by MaceWindu** [comment]
Not right now, but yes, I have it in plans for summer (design proposal for merge API and then implementation).

**Comment by ili** [comment]
That's really cool.
I do have nothing to add :)
Awaiting for PR's )))
