### ISSUE TITLE
Disable table name quotes for querying through Oracle DBLINK

### ISSUE THREAD

**Issue by yallie** [linq2db/linq2db#3389]
>TL/DR: Is there a way to disable adding double quotes for table names 
like `MY_TABLE@MY_LINK_NAME` when using `System.Data.Linq.Mapping` attributes?

Hello,

I have a large application migrated from BLToolkit to Linq2db.
Everything works great so far except for external tables accessed via Oracle DBLINK.
Tables accessed via DBLINK are named like this: `MY_TABLE@MY_LINK_NAME`:

```sql
SELECT ID, NAME FROM MY_TABLE@MY_LINK_NAME
```

Note that it looks like a table name with special symbols in it, but in fact it isn't.
Database entities are annotated using `System.Data.Linq.Mapping` attributes:

```csharp
[Table(Name = "MY_TABLE@MY_LINK_NAME")]
public class MyTable
{
     [Column(Name = "ID")]
     public long ID { get; set; }
}
```

BLToolkit used to generate table name as is:

```sql
SELECT ID, NAME 
FROM MY_TABLE@MY_LINK_NAME
```

But Linq2db detects a '@' symbol and quotes the table name:

```sql
SELECT ID, NAME 
FROM "MY_TABLE@MY_LINK_NAME"
```

Which is an error because such table doesn't exist in the database.
I don't seem to be able to find a workaround so far.
I found a compatibility option `OracleTools.DontEscapeLowercaseIdentifiers` that affects
table names with lowercase letters, but there is no such an option for the DBLINK `@` character.

### Environment details
linq2db version: 3.0.0.0
Database Server: Oracle
Database Provider: OracleManaged
Operating system: Windows
.NET Framework: 4.6.1

**Comment by MaceWindu** [comment]
For linked server name you should use `Server` mapping property
```cs
[Table(Name = "MY_TABLE", Server="MY_LINK_NAME")]
```

**Comment by yallie** [comment]
Is it Linq2db-specific `Table` attribute?
`System.Data.Linq.Mapping.Table` doesn't seem to have `Server` property.

**Comment by MaceWindu** [comment]
Ah, I see, you use `System.Data.Linq.Mapping`. Yes, this is linq2db-specific property

**Comment by MaceWindu** [comment]
I've checked escaping logic - this is only option available now

**Comment by MaceWindu** [comment]
Technically, you can also replace [SystemDataLinqAttributeReader](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Metadata/SystemDataLinqAttributeReader.cs) with own implementation, which split table name into Name/Server parts

**Comment by yallie** [comment]
Thanks for the suggestion! Will look into it.

**Comment by sdanyliv** [comment]
Answered similar on SO: [How to access an Oracle linked table in Linq2db?](https://stackoverflow.com/a/69451232/10646316)

**Comment by yallie** [comment]
Thanks for the `ServerName` extension method workaround:

```c#
var result = db.GetTable<Sector>().ServerName("STATS")
   .ToList();
```
