### ISSUE TITLE
MappingSchema Converter not used on insert...

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#339]
I've the following Code:

            MappingSchema.Default.SetConverter<SerializableDictionary<string, SerializableDictionary<string, string>>, string>((obj) =>
            {
               if (obj == null)
                    return null;
                return StringSerializer.JsonNetSerialize(obj);
            });
            MappingSchema.Default.SetConverter<string, SerializableDictionary<string, SerializableDictionary<string, string>>>((txt) =>
            {
                if (txt == null)
                    return null;
                return StringSerializer.JsonNetDeSerialize<SerializableDictionary<string, SerializableDictionary<string, string>>>(txt);
            });

And I have the following Property in my Entity:

        [DataMember]
        [Browsable(false)]
        public virtual SerializableDictionary<string, SerializableDictionary<string, string>> ScriptAssignment { get; set; }

when I now Save via:

    DataConnection.Insert(obj)

my Converter is not used on the insert, and "MCC.Utilities.SerializableDictionary`2[System.String,MCC.Utilities.SerializableDictionary`2[System.String,System.String]]" is written to the DB! But when I read, it used the Converter

**Comment by jogibear9988** [comment]
Is this wrong in my Mapping, or as I thought Converters were used? (Or does it not work??)

**Comment by jogibear9988** [comment]
Any news to this?

**Comment by igor-tkachev** [comment]
I added a test to reproduce it. You need to add another Convertion from Distionary to DataParameter as in the test https://github.com/linq2db/linq2db/commit/19c5ac1b14f35d9e4442759eec62eb85082fb7a8#diff-6407e2b74dd2576073c1fbfa98ab09dfR30

**Comment by jogibear9988** [comment]
It does work now! But why do we need to specify 3 Converters? Is this an issue or the desired behavior? If it's an issue, I could work on this...

**Comment by igor-tkachev** [comment]
Actually, we need four converters. Another one is a converter to SQL constant.
The reason why we need a converter to a DataParameter is when we create a parameter, we do not have information about its target type.

**Comment by jogibear9988** [comment]
Is then this COnverter:  MappingSchema.Default.SetConverter<SerializableDictionary<string, SerializableDictionary<string, string>>, string>((obj) used at any time? Would it not be possible that we create the Converter to "DataParamter" automatically during the mapping?

**Comment by igor-tkachev** [comment]
The DataConnection class has its own MappingSchema. You can use it instead of default one.
