### ISSUE TITLE
How can I release the mySql connection after the query is completed? CloseAfterUse has no effect, is it useless?

### ISSUE THREAD

**Issue by xl277541808** [linq2db/linq2db#3390]
我用的版本是：**linq2db.MySql 3.6.0**

我的使用方式是，每次需要访问数据库的时候。都去new 一个访问数据库的实例(**PlatformDB**)。比如这样。
**using (PlatformDB db = new PlatformDB())**
**{**
	**var model = db.Users.Where(item => item.Id == 1).First();**
	**db.Insert(new Data.Model.MySql.KeyValuePair**
	**{**
		**Key = Guid.NewGuid().ToString(),**
		**Value = Guid.NewGuid().ToString()**
	**});**
**}**
其中 **PlatformDB**继承自**DataConnection**，是通过tt文件生成的。
**public partial class PlatformDB : LinqToDB.Data.DataConnection**
我没有使用整个程序共享使用一个**PlatformDB**的方式。而是每次需要访问的时候new一个**PlatformDB**
所以每次新的Http请求过来，访问网站，需要连接数据库的时候。都会new一个。
所以，每个异步线程里面也会去new一个。
看起来，大概就如同这个样子的情况：
**for (int j = 0; j < 100; j++)
{
	Task.Factory.StartNew(() =>
	{
		using (PlatformDB db = new PlatformDB())
		{
			var model = db.Users.Where(item => item.Id == 1).First();
			db.Insert(new Data.Model.MySql.KeyValuePair
			{
				Key = Guid.NewGuid().ToString(),
				Value = Guid.NewGuid().ToString()
			});
		}
	});
}**
因此。它产生了100个到mySql的连接。而且一直没有释放。即使线程执行完成了，也没有释放。 
除非我把整个程序关掉。它才会释放100个线程。

即使，我设置了**CloseAfterUse=true**.
public PlatformDB()
{
	**(this as IDataContext).CloseAfterUse = true;**
	InitDataContext();
	InitMappingSchema();
}
也没有任何效果。依然是100个连接。一直没有释放。

请问，我是哪里没有用对吗？

**Comment by MaceWindu** [comment]
`CloseAfterUse` just controls how we manage connection state - close it after query or leave it open for use with next queries over same context.

It doesn't affect connection pooling functionality, provided by various providers. And I suspect this is what you see here.

I don't know which provider you use - MySqlConnector or MySql.Data, but in general providers have two options to manage pooled connections:
- connection string option to disable connection pooling for current connection
- API to release all pooled connections

For MySql.Data ( https://dev.mysql.com/doc/connector-net/en/connector-net-connections-pooling.html ):
- `Pooling=false` in connection string to disable pooling (https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html)
- release all pooled connections: `MySqlPoolManager.ClearAllPools()`


For MySqlConnector:
- `Pooling=false` in connection string to disable pooling (https://mysqlconnector.net/connection-options/)
- release all pooled connections: `MySqlConnection.ClearAllPools();`

**Comment by xl277541808** [comment]
thank you!
