### ISSUE TITLE
OpenTracing (or DiagnosticSource) support

### ISSUE THREAD

**Issue by forik** [linq2db/linq2db#3405]
Hi, are there any plans to add opentracing or diagnosticsource support to linq2db? Similar to [EfCore](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Instrumentation.EntityFrameworkCore) (this is a wrapper around DiagnosticSource though)

**Comment by MaceWindu** [comment]
At some point - yes. PR is welcome

**Comment by jods4** [comment]
I'm integrating an APM agent (namely Elastic's) into our applications and was looking at how it collects some metrics automatically.
It's using DiagnosticSources when it can, like ASP.NET Core or EF Core events.

For this kind of scenarios/integration it would be nice indeed to add DiagnosticSources to linq2db.

It's not hard to do but the bulk of the work is to define all the diagnostics that we want to emit.
A starting point could be to look at what EF Core has implemented.

If anyone wants to contribute but not do a full PR, I think starting out by listing all the event names and expected payloads in a comment on this issue would be helpful!
