### ISSUE TITLE
Change a network transport: reimplementing LinqService?

### ISSUE THREAD

**Issue by lsoft** [linq2db/linq2db#3409]
I'm looking to https://github.com/linq2db/examples/tree/master/LinqOverWCF/Windows%20Host and trying to replace wcf -> grpc.

I'm at the beginning and need an advise or someone who give me right direction. My trouble now is to understand - I need to take `LinqService` as is and wrap it with grpc stuff and grpc DTO objects I need to create,  or I need to reimplement it.

I tried to reimplement because I want to have all methods (`ExecuteReader`, `ExecuteBatch` etc) as async. So instead of 

```C#
                return DataConnection.QueryRunner.ExecuteNonQuery(db, new QueryContext
                {
                    Statement = query.Statement
                }, new SqlParameterValues());
```

I want to have 

```C#
                return await DataConnection.QueryRunner.ExecuteNonQueryAsync(db, new QueryContext
                {
                    Statement = query.Statement
                }, new SqlParameterValues());
```

etc. Here is a problem: `LinqServiceSerializer`, `DataConnection.QueryRunner` and others is internal. of course I can overcome in with reflection, but I'm not sure it's a right direction.

Any advices will help me a lot.
Thanks!

**Comment by MaceWindu** [comment]
Well, we have a long standing task to refactor it for easier use with other transports...

Easiest way is to use existing client-server base classes.

On client side you need to implement:
 - [ILinqClient](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/ILinqClient.cs) (ignore all those wcf attributes) - grpc client
 - client class inherited from [RemoteDataContextBase](RemoteDataContextBase) with `GetClient` method implementation to return your grpc client. E.g. check exiting implementations [SoapDataContext](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/SoapDataContext.cs) and [ServiceModelDataContext](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/ServiceModelDataContext.cs)

For server implementation (this is where you get issues as I can see due to a lot of stuff being internal) I would recommend you to pass received data to methods of [LinqService](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/ServiceModel/LinqService.cs) class so no reflection needed.

**Comment by MaceWindu** [comment]
BTW, I'm glad to see interest in this feature. We will try to refactor it for v4 release finally

**Comment by lsoft** [comment]
@MaceWindu thanks for your help, I'll try the things you describes.

Let me ask a clarification question: if you are planning to deeply refactor that, I suspect there will no back compat in that scope :) so, may be better for me to clone (or grab through reflection) that internal classes and make async `LinqService` as I want? for both ways I will have to refactor my implementation for v4)) but for now I will benefit of thread reusing because of async.

**Comment by MaceWindu** [comment]
Sure you can, but take into account that `LinqServiceSerializer` modified a lot, so you will need to update it for each release

**Comment by lsoft** [comment]
No, impossible. Because I'm working with net6, I cannot use reflection)) Copy-pasting is not feasible too (a lot of stuff need to be copied and modified).

So the only way to use existing `LinqService` without asyncs. Hope for your refactoring @MaceWindu  :) May I ask is the release date for v4 is known?

**Comment by MaceWindu** [comment]
We don't have date for final release of v4 except `this year`, but we release v4 previews from time to time. Maybe I will find time to include requred changes in nearest preview

**Comment by lsoft** [comment]
> I would recommend you to pass received data to methods of LinqService class so no reflection needed.

hehe, because of net6, there is no `LinqService` along with others (`LinqServiceSerializer` etc) :)

```C#

#if NETFRAMEWORK
...
namespace LinqToDB.ServiceModel
{
...
	public class LinqService : ILinqService
```

So that recomendation feasible in net framework, is there any approaches for net core @MaceWindu  ? Probably copy-pasting a lot of code is the only solution, for now.

**Comment by MaceWindu** [comment]
Yep, for .net core a lot of code is not included currently...

**Comment by lsoft** [comment]
@MaceWindu I tried to copy-paste everything I can. Of course, if I spend few hours, I, probably, succeeds. The problem is not a copy the files, the problem that `ServiceModel`-code depends on **internals** stuff from "core"-code, for example:

```C#
//code from ServiceModel:

//internal contrsuctor
	var query = new SelectQuery(sid); 

//I switched to
	var query = (SelectQuery)Activator.CreateInstance(
		typeof(SelectQuery),
		new object[]
		{
			sid
		}
		)!;
```

or 

```C#
//internal method of SelectQuery type
	query.Init(
		select,
		from,
		where,
		groupBy,
		having,
		orderBy,
		unions?.ToList(),
		null, // we do not serialize unique keys
		null,
		parameterDependent);

//this method can be touched through reflection
```

but... I've stopped. The code is too fragile to be useful.

Please correct me if I wrong, I'm not familiar with `linq2db` enough, but my opinion: remote access in `linq2db` is impossible in net core for now. I can of course fork it and relaxe access identifiers across whole `linq2db`... too ugly! :)

So, I will wait for your refactoring in preview channel. Could I ask you to post a note here once that fix will be available? (if i don't ask too much)

Thank you for fast replies, I REALLY appreciate it!

**Comment by MaceWindu** [comment]
In that case I will prioritize it (basically its more or less #1678) to be included into next preview. Best option I see in this situation is to create custom build of linq2db. In that case you can send PR :)

**Comment by lsoft** [comment]
> Try to implement in different branch (from dev.v4), and open/refactor API which is missed. Then we will review that.

> In that case you can send PR :)

got it. will do.

**Comment by sdanyliv** [comment]
I thought we will replace this with [Remote.Linq](https://github.com/6bee/Remote.Linq) or using [Reaqtor](https://github.com/reaqtive/reaqtor) ExpressionTree serializer.

But for now we can start with refactoring of existing code.

**Comment by lsoft** [comment]
I tried Remote.Linq and developed a nuget for execute few queries per single network request. RemoteLinq is **AWESOME**! But I faced one problem I can't resolve - https://github.com/6bee/Remote.Linq/issues/106

Looks that Chrisof (autor of remote linq) can't help me too. The problem is - I can't (don't know how) to `await` expression at the server-side in the scope of batch execution. Very specific problem, probably unclear for you, sure. But that is the reason I'm here and tried with `linq2db` remote execution :)

**Comment by lsoft** [comment]
@sdanyliv @MaceWindu  so, guys, I'm going forward with refactoring remote access related code. I've reach:

1. Refactor linq2db remote related code to allow it to be easily used in different transports.
2. Refactor both examples (wcf, soap) to use the new version of the remote-related code.
3. Created a grps-dotnet example that generally works.

![изображение](https://user-images.githubusercontent.com/5988558/151330857-2b48130e-60af-4969-9cb0-2b05ae5978dc.png)


Now I've faced with one problem I can't solve without your help. We have the following contract `object?         ExecuteScalar  (string? configuration, string queryData);`. The problem here is `object?` - for grpc I should to create a concrete contract, but that `object` is going from the core of linq2db and I don't know what is inside.

So, here is the question: how to solve it? :) any ideas?

My idea is - why `ExecuteReader` returns `string`, but `ExecuteScalar` returns some `object`?  `ExecuteReader` is much more powerful by its nature that `ExecuteScalar`. Why we can't serialize a result of `ExecuteScalar`  to `string` as we do with the result of `ExecuteReader`? I'm not feeling I will succeeds in this task.

**Comment by sdanyliv** [comment]
Why not, try it. It is really legacy part of the library and needs serious refactoring.

**Comment by lsoft** [comment]
@sdanyliv if so, I need a time to accumulate enough brave :)

**Comment by sdanyliv** [comment]
My idea was replace this logic with `Remote.Linq` via proper interface. And serialize Expression Tree. It can simplify a lot.
Because in current realization we require the same `MappingSchema` on both sides - very bad approach.

**Comment by sdanyliv** [comment]
> @sdanyliv if so, I need a time to accumulate enough brave :)

Well I have accumulated it to rewrite LINQ Translator. Will see... But new one looks cleaner and without compromises.

**Comment by lsoft** [comment]
@sdanyliv can you confirm that `ExecuteScalar` is used only in Insert\Update queries? I have a difficulties to invoke that method.

this

```
            using (var db = new DataModel.NorthwindDB())
            {
                var q =
                    from c in db.Customers
                    select c;

                Console.WriteLine(q.First().ContactName);
            }

```

uses `ExecuteReader` too. what I need to execute at the client to see `ExecuteScalar` invocation? The references going inside a `linq2db` core, too complex for me to understand.

**Comment by sdanyliv** [comment]
Yes, it is used for non query SQL.

**Comment by lsoft** [comment]
Looks like I switched `ExecuteScalar` from `object` to `string`... wow

I think that existing serializer is very inefficient (but I didn't benchmark). Can I switch it to something different (if I decide)? It will break back compat between the host and the client. So, old `linq2db` client will not be able to communicate with newer `linq2db` server.

**Comment by MaceWindu** [comment]
There were never declared compatibility between different versions of server and client as we transfer serialized AST and it changes a lot between versions with each new feature
