### ISSUE TITLE
Computed properties are mapped by default

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#3412]
Hello!

By default, Linq2Db map computed properties to columns, which makes no sence.

```C#
    class Incident
    {
        public int IncidentId { get; set; }

        public string Some => "fdasfds";
    }

    using var ctx = new L2DbContext();

    var r = ctx.GetTable<Incident>()
                .FirstOrDefault();
```

This gives me `System.Data.SqlClient.SqlException: 'Invalid column name 'Some'.'` as Linq2Db tries to read non-existent column:

```sql
--  SqlServer.2012
DECLARE @take Int -- Int32
SET     @take = 1

SELECT TOP (@take)
        [t1].[IncidentId],
        [t1].[Some]
FROM
        [Incident] [t1]
```

It is not big deal for me to explicitly ignore such properties, but it would be nice if Linq2Db will do it automatically. Just check if there is no setter on property.

### Environment details
linq2db version: 3.6.0
Database: SQL Server
Operating system: Windows 10

**Comment by MaceWindu** [comment]
linq2db doesn't analyze property implementation, you should mark property as non-column member:
```cs
class Incident
    {
        public int IncidentId { get; set; }

        [NotColumn] public string Some => "fdasfds";
    }
```

**Comment by Usaga** [comment]
As I expected. Thanks!
