### ISSUE TITLE
Insert into other table with one additional column (without additional class)

### ISSUE THREAD

**Issue by Sp1rit** [linq2db/linq2db#3418]
Given a table "BusinessPartners":
long Id [PK, Identity]
string Name

and another table "BusinessPartners_History"
long Id [PK]
int Instance [PK]
string Name

The history tables are dynamically created (based on an attribute) and are filled every time  the original table is updated.
My question is now, how would i be able to do this without a separate class for the history?

Insert with Value is not an option since i would need to provide every column. Insert with  just another table name doesn't work because i have another column.
I even tried emitting another type at runtime (with base class BusinessPartners, adding the additional column and overwriting Id). The result is always: "MySqlException: Field 'Id' doesn't have a default value"
It seems like it still gets the Identity attribute vom the base class.

Is there a better option i haven't found yet? I couldn't find anything on dynamic tables or something like that.

**Comment by MaceWindu** [comment]
Dynamic column store feature could be used

Insert/Update examples could be seen here:

https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/DynamicColumnsTests.cs

Column store configuration examples:

https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Mapping/DynamicStoreTests.cs
