### ISSUE TITLE
String.Length() Function Mapping Error

### ISSUE THREAD

**Issue by yunxifd** [linq2db/linq2db#343]
[String.Length()](https://msdn.microsoft.com/zh-cn/library/system.string.length%28v=vs.110%29.aspx) return  the number of characters in the current String object.

so in mysql, it should map to `CHAR_LENGTH()`,rather than `LENGTH()`.

**Comment by jogibear9988** [comment]
i think it's wrong! char_length respects unicode characters, so the current mapping is correct! http://www.w3resource.com/mysql/string-functions/mysql-char_length-function.php

**Comment by jogibear9988** [comment]
i think maybe we should map StringInfo.LengthInTextElements to CHAR_LENGTH()

**Comment by sdanyliv** [comment]
@jogibear9988, it is our bug. We have to use CHAR_LENGTH in that case. There are many failing MySql tests, when I've inserted single Unicode value into table Preson.
