### ISSUE TITLE
LINQ Any translated differently from v2

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3432]
### Discussed in https://github.com/linq2db/linq2db/discussions/3429

<div type='discussions-op-text'>

<sup>Originally posted by **hkarask** February 17, 2022</sup>
Hi all,

I'm trying to bump the `linq2sql` version in an older codebase, from `1.10.2` to `2.0.0` and noticed that `LINQ` `Any` gets translated a bit differently:

Given a contrived LINQ statement:

```csharp
var query =
    from task in con.GetTable<Task>()
    from party in con.GetTable<Party>()
        .Where(p => task.AdminPartyId == p.Id ||
                    con.GetTable<PartyAccess>().Any(pa => pa.PartyId == p.Id && pa.Role == Roles.Admin)
        ).DefaultIfEmpty()
...
```

I'm seeing different SQL between versions 1 and 2

### v 1.10.2
```sql
SELECT
 	t.Description,
 	p.Name
 FROM
 	Task t
 		LEFT JOIN Party p ON t.AdminPartyId = p.Id OR EXISTS(
 			SELECT
 				*
 			FROM
 				PartyAccess pa
 			WHERE
 				pa.PartyId = p.Id AND pa.Role = 'Admin'
 		)
```
### v 2.0.0
```sql
SELECT
 	j.Description,
 	t2.Name
 FROM
 	Task t
 		LEFT JOIN (
 			SELECT
 				p.Name,
 				p.Id
 			FROM
 				Party p
 			WHERE
 				(EXISTS(
 					SELECT
 						*
 					FROM
 						PartyAccess pa
 					WHERE
 						pa.PartyId = p.Id AND pa.Role = 'Admin'
 				))
 		) t2 ON t.AdminPartyId = t2.Id
```

There's now a full sub-query instead of join a level filter. This is causing a full table scan for some reason (using MySql 5.6). Is there a way to revert back to the old behaviour?

## 

### Environment details
linq2db version: `1.10.2` & `2.0.0`
Database Server: `MySql 5.6`
Database Provider: `MySql.Data 8.0.25`
.NET Framework: `.NET 4.8`

Thanks!
</div>

**Comment by MaceWindu** [comment]
I'm creating issue for this query as in current v4 master it gives even worse results.

**Comment by MaceWindu** [comment]
I will add test code here temporary

```cs
[Table]
		public class Task
		{
			[Column] public int AdminPartyId { get; set; }
			[Column] public string? Description { get; set; }
		}

		[Table]
		public class Party
		{
			[Column] public int Id { get; set; }
			[Column] public string? Name { get; set; }
		}

		[Table]
		public class PartyAccess
		{
			[Column] public int PartyId { get; set; }
			[Column] public string? Role { get; set; }
		}

		[Test]
		public void Test([DataSources] string context)
		{
			const string Admin = "Admin";

			using (var db = GetDataContext(context))
			using (db.CreateLocalTable<Task>())
			using (db.CreateLocalTable<Party>())
			using (db.CreateLocalTable<PartyAccess>())
			{
				var query =
					from task in db.GetTable<Task>()
					from party in db.GetTable<Party>()
					.Where(p => task.AdminPartyId == p.Id || db.GetTable<PartyAccess>().Any(pa => pa.PartyId == p.Id && pa.Role == Admin)).DefaultIfEmpty()
					select new {  task.Description, party.Name };
				query.ToArray();
				
			}
		}
```

**Comment by hkarask** [comment]
Do you think it's possible to go back to the v1 join behaviour in an upcoming release, at least for MySql?

**Comment by MaceWindu** [comment]
@sdanyliv planned to look at it. It depends on complexity of required fix - right now we want to concentrate on v4 preparation, so if it will require a lot of work - it will be postponed till v4, taking into account that there is a workaround..
