### ISSUE TITLE
Creation of Plugins for Alternative Providers

### ISSUE THREAD

**Issue by to11mtm** [linq2db/linq2db#344]
I'm looking at using Linq2Db for a project involving an Oracle Back-End.

However, our development house uses the Devart Oracle Driver instead of ODP.NET. We'd rather not use the ODP Driver (Bitness issues, non-native code, etc.) unless necessary.

However, it looks like you can't really 'plug in' a provider by making a separate library. This seems primarily due to how the library is currently encapsulated (i.e. AssemblyResolver and other classes are private)

Are there any plans to make the library more extensible in this regard?

**Comment by tb-mtg** [comment]
To assist in creating custom DataProviders, could the following were made public?

**Classes**
- LinqToDB.DataProvider.BasicBulkCopy
- LinqToDB.DataProvider.BasicMerge
- LinqToDB.DataProvider.BulkCopyReader
- LinqToDB.DataProvider.DataTools
- LinqToDB.DataProvider.MultipleRowsHelper
- LinqToDB.Linq.Builder (**all in this namespace**)

**Class constructors**
- LinqToDB.SqlQuery.SqlDataType(DataType dbType, Type type, int? length, int? precision, int? scale)

**Properties**
- LinqToDB.Data.BulkCopyRowsCopied.RowsCopied

**Methods**
- LinqToDB.LinqExtensions.GetContext

**Comment by ili** [comment]
We'll manage it

**Comment by jogibear9988** [comment]
Devart ODP was supported by Bltoolkit, don't we support it in linq2db now?

**Comment by ili** [comment]
No. In general there is Managed Oracle Provider... But i think it is a good idea to make a possibility to write custom providers. We have #462 for ex. but we can't merge it, because we can't test it. I don't know where can we get  AS/400 server :(

**Comment by ili** [comment]
@tb-mtg i'v checked what now is public

Are rest really needed, or we can close an issue?

**Comment by RoyC-Retail-Assist** [comment]
The changes noted _will_ allow a custom provider to be written  ( https://github.com/LinqToDB4iSeries/Linq2DB4iSeries ) so  suggest that any further changes could be requested if any future provider writer needed them.

**Comment by ili** [comment]
So i'm closing the issue :)
