### ISSUE TITLE
IQueryable Parameter value evaluated multiple times

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3450]
Discovered while working on tests and investigating unstable baselines generation. 
E.g. `TestQueryableCallWithParameters` test.

This test use result of `GetChildrenFiltered` method call as query "parameter" and contains complex logic inside. Instead of single call I observe 4 calls to evaluate method value.

Bad baselines example:
https://github.com/linq2db/linq2db.baselines/pull/745/commits/70de0cd52feee3716425d656a7d94373c3193d2a

**Comment by MaceWindu** [comment]
As part of fix, we will need a test that will ensure two things:
- there is only one parameter evaluation per query execution
- parameter value not cached between executions

**Comment by MaceWindu** [comment]
Note on why baselines are unstable:
- on first query execution parameter evaluated 4 times
- on second execution query is cached and parameter evaluated 2 times (one evaluation happens in query cache comparer visittor)

Because evaluation triggers query to database in this specific test, we have 4 or 2 extra queries to database in baselines based on enabled test providers and test execution order.

**Comment by sdanyliv** [comment]
Well, it is how we work with functions which returns `IQueryable`. We expect simple query injection, but function has heavy database request. If we change result type to `IEnumerable`, everything works smoothly.
