### ISSUE TITLE
Oracle Client 19 Issue

### ISSUE THREAD

**Issue by matrix2019** [linq2db/linq2db#3463]
Hello

I've just installed oracle client 19 and updated linq2db to version 3.6.0.0.
Oracle provider is Oracle.ManagedDataAccess 4.122.19.1

When I start my program, I receive this exception

```
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00933: SQL-Befehl wurde nicht korrekt beendet
   bei OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   bei OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   bei Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   bei Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   bei LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   bei LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   bei LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__11`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps, Object[] p
```

Maybe you can help me?

Greetings

**Comment by sdanyliv** [comment]
Well, additional information is needed

- From which linq2db version updated?
- Have you updated also Oracle.ManagedDataAccess?
- LINQ query and SQL which cause such error

**Comment by jods4** [comment]
The localised german error is `ORA-00933: SQL command not properly ended`.

So something is wrong in the generated SQL, @matrix2019 you need to post the C# query and the generated SQL. You can find the SQL in property `LastQuery` of your linq2db context.

**Comment by jorge-ribeiro-evaltec** [comment]
I just had this error in production, during an upgrade (from a version of our product that didn't use linq2db to a version that uses it).

Weird thing is, dozens of other clients had no problem at all.

We solved this particular case by forcing the OracleDataProvider to use version 11 instead of 12 - it seems there is some issue with the database we were connecting to (supposedly it's Oracle 19, but I never got my eyes on it....)

**Comment by matrix2019** [comment]
Hello jods4,

here ist the last statement. under Oracle 12 it works perfect.
```
using (DataConnection con = DBHelper.GetConnection())
                {
                   try
                    {
                        dbjob = con.GetTable<SchedulerJob>().Where(s => s.ID == dbjob.ID).FirstOrDefault();
```

and here is the select statement
```
SELECT
	s.HDR_VERSION,
	s.HDR_H2_TIMESTAMP,
	s.HDR_H2_USERID,
	s.HDR_H1_TIMESTAMP,
	s.HDR_H1_USERID,
	s.HDR_ID,
	s.DIRECTRUN,
	s.IXHAUSDEST,
	s.JOBDEFTYPE,
	s.WERKTAGS,
	s.ISSYSTEMJOB,
	s.ENABLED,
	s.NEXTRUN,
	s.LASTRUN,
	s.WAITFOREXIT,
	s.CRON,
	s.INTERVALLID,
	s.DESCRIPTION,
	s.NAME,
	s.JOBTYPE,
	s.NUMMER
FROM
	IXSQL.SCHEDULERJOB s
WHERE
	s.HDR_ID = :ID
FETCH NEXT :take ROWS ONLY

```
I didn't change the code. Only update to oracle 19. :-/

**Comment by jods4** [comment]
What's your DB instance version?
If it's pre-12c, `FETCH NEXT :take ROWS ONLY` is not supported and might be the problem.

**Comment by matrix2019** [comment]
Connected to Oracle Database 11g Release 11.2.0.4.0 

Uhh, what can I do now? Some customers still have 11g :-/

**Comment by MaceWindu** [comment]
As @jorge-ribeiro-evaltec mentioned - you need to specify dialect version linq2db use to v11 for all or only affected clients

**Comment by sdanyliv** [comment]
Don't worry, you can change behavior globally:
```cs
OracleTools.DefaultVersion = OracleVersion.v11
```
Or using `LinqToDbConnectionOptions`, or via configuration file. It depends on how do you configure your connection.

**Comment by matrix2019** [comment]
I use the code to connect, but the exception is still there.
```
  public static DataConnection GetConnection()
        {

                OracleTools.DefaultVersion = OracleVersion.v11;
                return LinqToDB.DataProvider.Oracle.OracleTools.CreateDataConnection(connectionString);
}
```

**Comment by MaceWindu** [comment]
Try this:
```cs
new DataConnection(OracleTools.GetDataProvider(version:OracleVersion.v11), connectionString);
```

**Comment by matrix2019** [comment]
Hi MaceWindu,

thank's allot, this works. :-D
