### ISSUE TITLE
Customizeable data providers

### ISSUE THREAD

**Issue by mdvtj** [linq2db/linq2db#347]
What makes it hard to tweak existing data providers (to add support for custom logic for id generation or different sequence naming schemes or other small changes that do not justify a new data provider from scratch) is the fact that existing `ISqlBuilder` implementations are declared as **internal**.

This requires workarounds like decorators which are getting really bloated if e.g. just a method like `BasicSqlBuilder.BuildGetIdentity` should be replaced.

**Comment by sdanyliv** [comment]
@ili, it is simplified already to create custom Data Providers?

**Comment by ili** [comment]
We'v done already some job to make it easier to write custom data providers. 
Let's close issue for now, will reopen and work on particular cases
