### ISSUE TITLE
Cannot load assembly IBM.Data.DB2 when run model generator

### ISSUE THREAD

**Issue by s1495k043** [linq2db/linq2db#3470]
When run T4  at LoadDB2Metadata("my connection string");

```
System.InvalidOperationException: Cannot load assembly IBM.Data.DB2
   於 LinqToDB.DataProvider.DB2.DB2ProviderAdapter.GetInstance()
   於 LinqToDB.DataProvider.DB2.DB2DataProvider..ctor(String name, DB2Version version)
```

### Steps to reproduce
Create a new net6 library project.
Install newest linq2db.DB2.Core from nuget.
copy **CopyMe.DB2.tt.txt** and edit connection string
LoadDB2Metadata("my connection string");
run t4 template

### Environment details
linq2db version: 3.6.0
Database Server: Informix12 
Database Provider: NET5.IBM.Data.Db2 or IBM.Data.DB2.Core
Operating system: Win10
.NET Framework: net6
Visual Studio 2022

**Comment by MaceWindu** [comment]
You need to install informix client SDK to use T4 (x64 version of SDK as VS2022 use x64 process to run T4 templates)

**Comment by MaceWindu** [comment]
Also `linq2db.DB2.Core` nuget is for DB2 scaffolding, for informix you should use `linq2db.Informix.Core`

**Comment by s1495k043** [comment]
Create model in develop enviroment and use IBM.Data.DB2.Core provider in production,right?

**Comment by MaceWindu** [comment]
Yes, database provider for T4 used only for model generation.

**Comment by s1495k043** [comment]
ok,thank you very much.

**Comment by MaceWindu** [comment]
In version 4 we will release new tool for model generation not based on T4 which will not require client installation for informix (you will need to specify location of `IBM.Data.DB2.Core`).

If you are interested, you can try preview version attached here https://github.com/linq2db/linq2db/pull/3098#issuecomment-1038157970

**Comment by s1495k043** [comment]
By the way,because IBM.Data.DB2.Core is build on netstandard 2.1. 
IBM release new provider build on net5. 
https://www.nuget.org/packages/Net5.IBM.Data.Db2/

**Comment by MaceWindu** [comment]
OMG... Why? Would be more appreciated if they create single fully managed provider instead..

**Comment by MaceWindu** [comment]
They also released separate version for .net 6... Don't they know that nuget could contain versions for multiple runtimes :fearful:

**Comment by MaceWindu** [comment]
@s1495k043 new providers support will be in next release
