### ISSUE TITLE
Generated not equal query is too complex

### ISSUE THREAD

**Issue by djfoxer** [linq2db/linq2db#3473]
Hi, I have small query with `where` clause in C#:

```c#
table1.StringColumn1 != table2.StringColumn2
```

but linq2db generates much complex `where` clause which is very slow in my particular case:

```sql
([table1].[StringColumn1] <> [table2].[StringColumn2] OR [table1].[StringColumn1] IS NULL AND [table2].[StringColumn2] IS NOT NULL OR [table1].[StringColumn1] IS NOT NULL AND [table2].[StringColumn2] IS NULL)
```
how to force linq2db to generate plain "not equal query" (just:  `table1.StringColumn1 <> table2.StringColumn2`)?

Thank you.

### Environment details
linq2db version: *linq2db 3.5.0*
Database Server: *MS SQL*
Database Provider: *linq2db.EntityFrameworkCore 3.16*
Operating system: *Windows*
.NET Framework: *.NET Core 3.1*

**Comment by MaceWindu** [comment]
```cs
Configuration.Linq.CompareNullsAsValues = false;
```

**Comment by MaceWindu** [comment]
Default is `true` and translates C# null comparison semantics to SQL. `false` will produce as-is SQL

**Comment by djfoxer** [comment]
@MaceWindu Thank for your answer!
