### ISSUE TITLE
Query to Nullable Int(decimal, double...) does not work when raised via Dynamic.Linq.Core

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3475]
I've the following Code:

	    [TestFixture]
	    public class Issue9999Tests : TestBase
	    {
		    internal class Linq2DbDynamicLinqCustomTypeProvider : DefaultDynamicLinqCustomTypeProvider
		    {
			    public override HashSet<Type> GetCustomTypes()
			    {
				    var types = base.GetCustomTypes();
				    types.Add(typeof(Sql));
				    return types;
			    }
		    }
    
		    [Table]
		    public class NumberLikeTestTable
		    {
			    [Column] public int?      IntNProp { get; set; }
		    }
    
		    public class NumberLikeTestObj
		    {
			    public NumberLikeTestTable? Obj { get; set; }
		    }
    
		    [Test]
		    public void NumberLikeTests([IncludeDataSources(TestProvName.AllSQLite)] string context)
		    {
			    ParsingConfig.Default.CustomTypeProvider = new Linq2DbDynamicLinqCustomTypeProvider();
    
			    using (var db = GetDataContext(context))
			    using (db.CreateLocalTable<NumberLikeTestTable>())
			    {
    #pragma warning disable CS8602
				    var query1 = db.GetTable<NumberLikeTestTable>().Select(x => new NumberLikeTestObj() { Obj = x }).Where(x => Sql.Like(x.Obj.IntNProp.ToString(), "1%")).Take(50);
				    var query2 = db.GetTable<NumberLikeTestTable>().Select(x => new NumberLikeTestObj() { Obj = x }).Where("((Sql.Like(it.Obj.IntNProp.ToString(),@0)))", new object[]{ "1%" }).Take(50);
    
				    var res1 = query1.ToList();
				    var res2 = query2.ToList();
    #pragma warning restore CS8602
			    }
		    }
	    }

```
Exception message:
LinqToDB.Linq.LinqException: "'Param_0.Obj.IntNProp.ToString()' cannot be converted to SQL."
```

The Debug View of the Expression:

Workin One (normal Linq):

		.Call System.Linq.Queryable.Take(
			.Call System.Linq.Queryable.Where(
				.Call System.Linq.Queryable.Select(
					.Call LinqToDB.DataExtensions.GetTable(.Constant<Tests.Model.TestDataConnection>(Tests.Model.TestDataConnection)),
					'(.Lambda #Lambda1<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestTable,Tests.UserTests.Issue9999Tests+NumberLikeTestObj]>))
				,
				'(.Lambda #Lambda2<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestObj,System.Boolean]>)),
			50)

		.Lambda #Lambda1<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestTable,Tests.UserTests.Issue9999Tests+NumberLikeTestObj]>(Tests.UserTests.Issue9999Tests+NumberLikeTestTable $x)
		{
			.New Tests.UserTests.Issue9999Tests+NumberLikeTestObj(){
				Obj = $x
			}
		}

		.Lambda #Lambda2<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestObj,System.Boolean]>(Tests.UserTests.Issue9999Tests+NumberLikeTestObj $x)
		{
			.Call LinqToDB.Sql.Like(
				.Call (($x.Obj).IntNProp).ToString(),
				"1%")
		}	

Broken one (created via dynamic linq):

		.Call System.Linq.Queryable.Take(
			.Call System.Linq.Queryable.Where(
				.Call System.Linq.Queryable.Select(
					.Call LinqToDB.DataExtensions.GetTable(.Constant<Tests.Model.TestDataConnection>(Tests.Model.TestDataConnection)),
					'(.Lambda #Lambda1<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestTable,Tests.UserTests.Issue9999Tests+NumberLikeTestObj]>))
				,
				'(.Lambda #Lambda2<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestObj,System.Boolean]>)),
			50)

		.Lambda #Lambda1<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestTable,Tests.UserTests.Issue9999Tests+NumberLikeTestObj]>(Tests.UserTests.Issue9999Tests+NumberLikeTestTable $x)
		{
			.New Tests.UserTests.Issue9999Tests+NumberLikeTestObj(){
				Obj = $x
			}
		}

		.Lambda #Lambda2<System.Func`2[Tests.UserTests.Issue9999Tests+NumberLikeTestObj,System.Boolean]>(Tests.UserTests.Issue9999Tests+NumberLikeTestObj $var1)
		{
			.Call LinqToDB.Sql.Like(
				.Call (($var1.Obj).IntNProp).ToString(),
				"1%")
		}

**Comment by jogibear9988** [comment]
So as I see, the debug view of the expression tree is nearly the same, but only the c# expression works, the one created via dynamic.linq not

**Comment by jogibear9988** [comment]
If I compare the expression trees, they nearly look the same...

![image](https://user-images.githubusercontent.com/364896/159265830-64d5d2e9-5905-4444-8926-2c43bb678425.png)

**Comment by jogibear9988** [comment]
Is this a problem in linq2db?
![image](https://user-images.githubusercontent.com/364896/159266019-72c02383-fbc1-4a30-8639-e318d2d24c61.png)

The Param expresion from the C# compiler has "x" as name, the one from dynamic linq has no name

**Comment by jogibear9988** [comment]
expression from c# compiler:
![image](https://user-images.githubusercontent.com/364896/159266331-0cf672d3-dbd2-4997-af5a-44461252fb72.png)

expression from dynamic linq:
![image](https://user-images.githubusercontent.com/364896/159266414-a0d5d001-b874-4ac1-983e-45cf22ca3b3f.png)

**Comment by igor-tkachev** [comment]
Check the ToString method. It can be either int.ToString() or object.ToString(). Not sure which one is correct.

**Comment by jogibear9988** [comment]
yes, i found that the Dynamic Linq expression uses Nullable.ToString
and the c# compiler object.ToString

**Comment by jogibear9988** [comment]
but should not both work?

**Comment by jogibear9988** [comment]
with this change it would work
