### ISSUE TITLE
How to ignore/skip a column when generating model with t4 template

### ISSUE THREAD

**Issue by dipique** [linq2db/linq2db#3479]
### Describe your issue

I currently use a t4 template to generate my model. I use the built-in functionality to ignore schemas, modify table names, and skip tables.

Recently I had a need to skip a column; is there a way to do this?

### Environment details
linq2db version: 3.3
Database Server: SqlServer
Operating system: Windows 11
.NET Framework: 4.8

**Comment by MaceWindu** [comment]
check this https://github.com/linq2db/linq2db/discussions/3229

**Comment by dipique** [comment]
> check this #3229

Thank you! That is perfect.
