### ISSUE TITLE
Sqlite Aggregate Functions

### ISSUE THREAD

**Issue by kronic** [linq2db/linq2db#348]
linq2db does not function group_concat
https://www.sqlite.org/lang_aggfunc.html

**Comment by sdanyliv** [comment]
Looks like it is related to #353

**Comment by jogibear9988** [comment]
@sdanyliv this is fixed?

**Comment by sdanyliv** [comment]
Yes It is possible for now. Sample how to create custom aggregate is here 
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.Analytic.cs#L718
Closing.
