### ISSUE TITLE
specify the default value of the database column

### ISSUE THREAD

**Issue by CwjXFH** [linq2db/linq2db#3485]
Can linq2db specify the default value of the database column like EFCore?
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>()
        .Property(b => b.Created)
        .HasDefaultValueSql("getdate()");
}
```

**Comment by sdanyliv** [comment]
No, it doesn't. Basically `linq2db` helps in creating temporary tables, but not whole DB. So this feature never considered to implement,

**Comment by MaceWindu** [comment]
Duplicate #2277
