### ISSUE TITLE
Group by generates redundant and apparently inefficient SQL

### ISSUE THREAD

**Issue by shameleo** [linq2db/linq2db#3486]
**[UPDATED] Now I found out why generated SQL is so strange, and can say it's probably my fault and lack of knowledge of how `let` works in LINQ.** Should it be considered an issue? It's up to you.
___
I'd like not to post real-world example, as the issue seems to be consistently reproducible. I'll prepare real case, if it will be nessesary. For now it is pseudo code.

**LINQ query:**
```cs
IQueryable<...> q_t = ...;
var query = (
	from t in q_t
	group t by new { t.ServiceName, t.TariffName } into gr
	select new 
	{
		gr.Key.ServiceName,
		gr.Key.TariffName,
		Sum = gr.Sum(it => it.Bill)
	}
)
```

**Generates SQL, which is expected:**
```sql
SELECT
	[t].[serviceName],
	[t].[tariffName],
	Sum([t].[bill])
FROM
	[t]
	--...
WHERE
	--...
GROUP BY
	[t].[serviceName],
	[t].[tariffName]
```

**However, LINQ query:**
```cs
IQueryable<...> q_t = ...;
var query = (
	from t in q_t
	group t by new { t.ServiceName, t.TariffName } into gr
        let common = gr.Key          // <<======= look here =========
	select new 
	{
		common.ServiceName,
		common.TariffName,
		Sum = gr.Sum(it => it.Bill)
	}
)
```

**Generates  SQL:**

```sql
SELECT
	[t_1].[serviceName],
	[t_1].[tariffName],
	(
		-- duplicated query from below + extra condition in WHERE
		SELECT
			Sum([t].[bill])
		FROM
			[t]
			--...
		WHERE
			([t_1].[serviceName] = [t].[serviceName] AND [t_1].[tariffName] = [t].[tariffName]) AND 
			--...
	)
FROM
	[t_1]
	--...
WHERE
	--...
GROUP BY
	[t_1].[serviceName],
	[t_1].[tariffName]
```

Although both SQL queries produce similar results, they use different execution plans. Besides, the second query is very uncomfortable to read and analyze.

### Environment details
linq2db version: *3.6.0*
Database Server: *SqlServer*
Database Provider: *Microsoft.Data.SqlClient*
Operating system: *Win 10 x64*
.NET Framework: *.NET Core 2.1*

**Comment by MaceWindu** [comment]
Fixed in `6.0.0-preview.1`
