### ISSUE TITLE
MySQL T4 template - No primary key generated

### ISSUE THREAD

**Issue by mikos7** [linq2db/linq2db#350]
I'm using Linq2db version 1.0.7.3, VS2015 and MariaDb. The problem at hand is that no primary key is generated by the template script. I'm using the standard template setup. Haven't noticed any other errors in the generated model. 

Any thoughts?

[sql script](https://dl.dropboxusercontent.com/u/26461879/sql.txt)
[generated model](https://dl.dropboxusercontent.com/u/26461879/model.txt)

**Comment by igor-tkachev** [comment]
I got the following  error when I tried to run the script

```
Can't create table `userdata1`.`coursedescription` (errno: 150 "Foreign key constraint is incorrectly formed") 
```

**Comment by igor-tkachev** [comment]
Just tried to create a data model. Everything works just fine.
Maybe you need to update linq2db dll or your MySql database provider.
