### ISSUE TITLE
mysqlconnector dirver transaction  error

### ISSUE THREAD

**Issue by 273168121** [linq2db/linq2db#3513]
when i use the begintrans  with  mysqlconnector  driver  ,i got the flowing error
The transaction associated with this command is not the connection’s active transaction,
for details https://mysqlconnector.net/troubleshooting/transaction-usage.

and mysql.data driver is normal.

**Comment by MaceWindu** [comment]
Sample code?

**Comment by 273168121** [comment]
i changed abpvnext ef module to linq2db, and the snap code like this 
` if (context.ExistingConnection != null)
            {
                 
                return context.DbConnectionOptionsBuilder.UseConnection(new MySqlDataProvider(ProviderName.MySqlConnector),context.ExistingConnection);
            }
            else
            {
                return context.DbConnectionOptionsBuilder.UseMySql(context.ConnectionString);
            }`

and uow code 
`private TDbContext CreateDbContextWithTransaction(IUnitOfWork unitOfWork)
        {
           var transactionApiKey = $"Linq2db_{DbContextCreationContext.Current.ConnectionString}"; 
            var activeTransaction = unitOfWork.FindTransactionApi(transactionApiKey) as Lin2dbTransactionApi;

            if (activeTransaction == null)
            {
                
                //create DbContext.
                var dbContext = unitOfWork.ServiceProvider.GetRequiredService<TDbContext>();

                var dbtransaction = unitOfWork.Options.IsolationLevel.HasValue
                    ? dbContext.BeginTransaction(unitOfWork.Options.IsolationLevel.Value)
                    : dbContext.BeginTransaction();

                unitOfWork.AddTransactionApi(
                    transactionApiKey,
                    new Lin2dbTransactionApi(
                        dbtransaction, 
                        _cancellationTokenProvider
                    )
                );

                return dbContext;
            } 
            else
            {
                
               
                //different DbContext， if  have the same connection 
                DbContextCreationContext.Current.ExistingConnection = activeTransaction.DbContextTransaction.DataConnection.Connection;
                var dbContext = unitOfWork.ServiceProvider.GetRequiredService<TDbContext>();

                if (DbContextCreationContext.Current.ExistingConnection != dbContext.Connection)
                {
                    dbContext.BeginTransaction();
                }
                 
                 /*dbContext.BeginTransaction();*/
             
                activeTransaction.AttendedDbContexts.Add(dbContext);

                return dbContext;
            }
        }`

**Comment by MaceWindu** [comment]
BTW, I would not recommend to create provider instance manually as:
- it is quite heavy object
- in v4 we remove public constructors from providers to avoid such code

You can use MySqlTools.GetDataProvider method instead to get pre-created instance.
