### ISSUE TITLE
GroupBy problem

### ISSUE THREAD

**Issue by integral-llc** [linq2db/linq2db#352]
Having such a LINQ query
```
var q = from s in dc.Stone
                                from sss in dc.StoneSupplierStone
                                where s.Id == sss.Stone_id
                                && sss.StoneSupplier_id == 6134
                                group s by s.Id into g
                                select new StoneWithCustomName
                                {
                                    StoneId = g.Key,
                                    Name = g.FirstOrDefault().Name
                                };
                q = q.OrderBy(x => x.Name);
```

falls with such an exception

> [InvalidOperationException: Operation is not valid due to the current state of the object.]
> LinqToDB.Linq.Builder.SelectContext.GetMemberExpression(MemberInfo member, Boolean add, Type type) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:1139
> LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:320
> LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:538
> LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:410
> LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SubQueryContext.cs:98
> LinqToDB.Linq.Builder.<>c__DisplayClass23.<ConvertToSql>b__15(IBuildContext ctx, Expression ex, Int32 l) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:276
> LinqToDB.Linq.Builder.SelectContext.ProcessScalar(Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:881
> LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:273
> LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:798
> LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:613
> LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:255
> LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:459
> LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:410
> LinqToDB.Linq.Builder.FirstSingleContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\FirstSingleBuilder.cs:190
> LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:239
> LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:247
> LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:837
> LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:613
> LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:379
> LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:320
> LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in i:\linq2db\Source\Linq\Builder\ExpressionContext.cs:48
> LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:798
> LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:613
> LinqToDB.Linq.Builder.OrderByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\OrderByBuilder.cs:49
> LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:22
> LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:177
> LinqToDB.Linq.Builder.ExpressionBuilder.Build() in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:148
> LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) in i:\linq2db\Source\Linq\Query.cs:165
> LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) in i:\linq2db\Source\Linq\ExpressionQuery.cs:82
> LinqToDB.Linq.ExpressionQuery`1.Execute(IDataContextInfo dataContextInfo, Expression expression) in i:\linq2db\Source\Linq\ExpressionQuery.cs:69
> LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in i:\linq2db\Source\Linq\ExpressionQuery.cs:149
> System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +369
> System.Linq.Enumerable.ToList(IEnumerable`1 source) +58

Any idea how to by pass this?

**Comment by integral-llc** [comment]
Same think can be simulated with Northwind database.

```
var zz = from e in db.Employees
        from et in db.EmployeeTerritories
        where et.EmployeeID == e.EmployeeID
        group e by new {e.EmployeeID}
        into g
        select new
        {
            g.Key.EmployeeID,
            g.FirstOrDefault().FirstName,
        };
//    zz = zz.OrderBy(a => a.FirstName);

    var res = zz.ToList();
```

**Comment by igor-tkachev** [comment]
Unfortunately, this feature is not currently supported. You can rewrite your query in this way:

```c#
    db.Employee.FirstOrDefault(em => em.EmployeeID == g.Key.EmployeeID).FirstName
```

it should work.

**Comment by jogibear9988** [comment]
I think this should be reopened, because it's not yet supported (but I think it should if possible)
