### ISSUE TITLE
How to Register multiple DbContext inside Blazor server app

### ISSUE THREAD

**Issue by iColdoCatalin** [linq2db/linq2db#3527]
I'm trying to register 2 dbcontext inside a blazor server app for dependency injection use but when I do so the app won't start.
Removing one of 2 it works.
Is it possible to add 2 dbcontext with linq2db? If not how can I use 2 differente dbs?
I'm I doing something wrong?
Below is the code used to register the 2 instances.

`builder.Services.AddLinqToDbContext<FIRSTDB>((provider, options) => {
            options
            .UseSqlServer(builder.Configuration.GetConnectionString("FIRSTDB"))
            .UseDefaultLogging(provider);
        });`

`builder.Services.AddLinqToDbContext<SECONDDB>((provider, options) =>
        {
            options
            .UseSqlServer(builder.Configuration.GetConnectionString("SECONDDB"))
            .UseDefaultLogging(provider);
        });`

**Comment by MaceWindu** [comment]
Multiple contexts registration supported and should work if you register and resolve them using different types (`FIRSTDB` != `SECONDDB`).
You should look at thrown exception to see what's wrong with DI configuration in your case.

**Comment by 273168121** [comment]
You can look at ef in abpvnext
