### ISSUE TITLE
Postgres Schema/SearchPath in connection string not used in query

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3528]
Linq2db does not use the Schema given in the connection string.

The connection string includes among others 
```
Database = mydatabase; SearchPath = myschema;
```

For 
```c#
context.CreateTable<MyEntity>() 
```

it throws "3F000: no schema has been selected to create in".

The SQL statement taken from ```context.LastQuery``` starts with ``` CREATE TABLE my_entity ........```

Do I need to set the schema in another way?

### Environment details
linq2db version: 3.7.0
Database Server: Postgres
Database Provider: Linq2db.Npsql 3.7.0
Operating system: *?*
.NET Framework: *?*

**Comment by MaceWindu** [comment]
Connection string parameters are for database/database provider. linq2db knows nothing about them (yes, there are some exceptions like MARS flag for sql server...).

I don't know how exactly `SearchPath` works, maybe it works only for existing objects discovery and doesn't affect default schema for create operations.

Anyway, proper way to specify schema in `linq2db` is to use schema name mapping property, query method on table or parameter. In your case it is:

```cs
context.CreateTable<MyEntity>(schemaName: "myschema")

// or

[Table(Schema="myschema")]
class MyEntity {...}

// or

db.GetTable<MyEntity>().SchemaName("myschema")...
```

**Comment by HypeillingerChillinger** [comment]
I see. Can I set it in fluent mapping?

**Comment by MaceWindu** [comment]
Sure https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Mapping/FluentMappingTests.cs#L231=

**Comment by HypeillingerChillinger** [comment]
Perfekt, thanks a lot.

**Comment by MaceWindu** [comment]
BTW, according to pgsql docs, search_path is for discovery only and could contain multiple schemas https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH
