### ISSUE TITLE
Strange SQL codgen for [Function]

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3538]
Given this custom function:
```csharp
[Function("Nvl2", PreferServerSide = true)]
public static R Nvl2<T, R>(T expression, R ifNotNull, R ifNull)
  => expression == null ? ifNull : ifNotNull;
```

This request (model is plain strings, nothing fancy here):
```csharp
string suffix1 = "_1", suffix2 = "_2";

int count = db.SomeTable.Update(
  mt => mt.Whatever != null,
  mt => new SomeTable
  {
    Whatever = null,
    Name1 = OracleSql.Nvl2(mt.Name1, mt.Name1 + suffix1, null),
    Name2 = OracleSql.Nvl2(mt.Name2, mt.Name2 + suffix2, null),
  });
```

Generates this SQL:
```sql
DECLARE @suffix1 Varchar2(21) -- String
SET     @suffix1 = '_1'
DECLARE @suffix2 Varchar2(22) -- String
SET     @suffix2 = '_2'

UPDATE
  SomeTable
SET
  SomeTable.Whatever = NULL,
  SomeTable.Name1 = Nvl2(SomeTable.Name1, SomeTable.Name1 || :outSuffix, NULL, VarChar2(4000), VarChar2(4000)),
  SomeTable.Name2 = Nvl2(SomeTable.Name2, SomeTable.Name2 || :datalogSuffix, NULL, VarChar2(4000), VarChar2(4000))
WHERE
  SomeTable.Whatever IS NOT NULL
```

Notice the extra `VarChar2(4000)` arguments to `nvl2` that come out of nowhere??

### Environment details
linq2db version: 3.7.0, confirmed with at least 3.5.1
Database Server: Oracle
Database Provider: Managed ODP.NET
Operating system: Win10
.NET Framework: .net 5.0

**Comment by jods4** [comment]
Ok my guess is that Type argument from generic C# functions are somehow included by default.
I worked around / fixed this by adding `ArgIndices = new[] { 0, 1, 2 }` to my `[Function]` attribute.

You can close this issue if this is the expected behavior (it's quite surprising).

**Comment by sdanyliv** [comment]
Yes it is known behavior from version 1.x

**Comment by MaceWindu** [comment]
You can also try `IgnoreGenericParameters` Igor added recently

**Comment by jods4** [comment]
@MaceWindu thanks, that's nice!

Don't you feel for 4.0 we should do a breaking change and make `IgnoreGenericParameters = true` the default behavior?
It's much more intuitive and is what's needed 90% of the time.
Special functions (such as convert-like I suppose) can go back to `IgnoreGenericParameter = false` if they need to.
Functions with explicit `ArgIndices` could also always be in generic parameter mode, which surely will limit the breakage.

**Comment by MaceWindu** [comment]
Sounds good

**Comment by viceroypenguin** [comment]
@jods4  - I like your proposed change as well
