### ISSUE TITLE
Linq2db keeps adding N to varchar in queries even if column of view is varchar slowing down a lot the execution

### ISSUE THREAD

**Issue by iColdoCatalin** [linq2db/linq2db#3546]
I'm having very slow queries cause linq2db keeps adding N in front of varchars in the generated query even if the column on witch the comparison is done is varchar and not nvarchar.
Why is that?
Removing the N the query is much faster.

The code used in the where clause below. 
I use a list of strings and contains to ensure that a column is present in those values.

`where mtListOfStrings.Contains(myColumnName)`

How can I avoid this behaviour?

**Comment by MaceWindu** [comment]
You need to specify DataType.Varchar for `myColumn` mapping

**Comment by iColdoCatalin** [comment]
@MaceWindu  How can I do that? 
The class is automatically generated from T4 template with the column as follows:

`[Column(),                       Nullable] public string    MyColumn    { get; set; } // varchar(50)`

**Comment by MaceWindu** [comment]
https://linq2db.github.io/articles/T4.html

```cs
GenerateDataTypes                   = true;
```

**Comment by iColdoCatalin** [comment]
@MaceWindu thank you a lot!
dindn't know about this behaviour...so now linq2db knows exactly how to construct the query since datatype is specified or else it uses what it thinks its best right?

**Comment by MaceWindu** [comment]
Yes. in C# we have string type only but database usually have several text types and we don't know which one is used

**Comment by iColdoCatalin** [comment]
@MaceWindu thanks again! very clear and fast to respond 👍
