### ISSUE TITLE
linq2db 1.7.4 NpgsqlTypes.NpgsqlDateTime

### ISSUE THREAD

**Issue by salgadonline** [linq2db/linq2db#355]
when type is date time i get the exception cannot load the type NpgsqlTypes.NpgsqlDateTime do assembly Npgsql when i go back to 1.7.3 works fine.

**Comment by igor-tkachev** [comment]
Can you provide an example?

**Comment by salgadonline** [comment]
![2016-04-16 1](https://cloud.githubusercontent.com/assets/4457435/14584537/758ea814-0421-11e6-9597-53674fe35ca6.png)
It just happen in the version 1.7.4

**Comment by salgadonline** [comment]
TKS
