### ISSUE TITLE
Question abou how to query/group

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3552]
I've a question

I've a DTO/Table like this:

      class OpCounter {
            public Guid Id
            public Guid TagId
            public Decimal Value
            public DateTime Modified
      }

Now I'd like to query OpCounter Grouped by TagId so I only get one Result Row per Tag Id (but the Last one), but I also like to return the Sum of the Value Property...

I tried this:

                var qry = (from op in s.Query<OpCounter >().OrderBy(x => x.Modified)
                           group op by op.TagId into ops
                           select new { Value = ops.Sum(x => x.TagValue), OperatingCounter = ops.First() })
                          .ToList();

but this complains it would only work with Configuration.Linq.GuardGrouping = false

**Comment by jogibear9988** [comment]
I tried the DistinctBy from here:

https://stackoverflow.com/questions/69096492/linq-take-distinct/69100842#69100842


        public static IQueryable<T> DistinctBy<T, TKey>(this IQueryable<T> source, Expression<Func<T, TKey>> distinctBy)
        {
            var distinctQuery = source.Select(distinctBy).Distinct();

            var distinctParam = Expression.Parameter(typeof(TKey), "d");
            var entityParam = distinctBy.Parameters[0];

            var mapping = MapMembers(distinctBy.Body, distinctParam).ToList();

            var whereExpr = mapping.Select(t => Expression.Equal(t.Item1, t.Item2))
                .Aggregate(Expression.AndAlso);
            var whereLambda = Expression.Lambda(whereExpr, entityParam);

            var selectManySelector =
                Expression.Lambda(
                    Expression.Convert(
                        Expression.Call(typeof(Queryable), nameof(Queryable.Where), new[] { typeof(T) },
                            source.Expression,
                            whereLambda),
                        typeof(IEnumerable<T>)
                    ),
                    distinctParam
                );

            var selectManyQuery = Expression.Call(typeof(Queryable), nameof(Queryable.SelectMany),
                new[] { typeof(TKey), typeof(T) }, distinctQuery.Expression, selectManySelector);


            return source.Provider.CreateQuery<T>(selectManyQuery);
        }

and then used it like here:

                var opCounters = IQueryableExtensions.DistinctBy(s.Query<OperatingCounterDTO>().OrderBy(x => x.ModifiedTimeStamp), x => x.TagId);
                var opList = opCounters.ToList();

                var qry = (from op in opCounters
                           select new
                           {
                               Value = s.Query<OperatingCounterDTO>().Where(x => x.TagId == op.TagId).Sum(x => x.TagValue),
                               OperatingCounter = op
                           })
                         .ToList();

but already the distinct into the "opList" does not work...
it looks like this:

      SELECT
	      [x_1].[Id],
	      [x_1].[Username],
	      [x_1].[ChangeType],
	      [x_1].[CreatedTimeStamp],
	      [x_1].[ModifiedTimeStamp],
	      [x_1].[TagValue],
	      [x_1].[TagId]
      FROM
	      (
		      SELECT DISTINCT
			      [x].[TagId]
		      FROM
			      [VISU_OperatingCounters] [x]
	      ) [cp]
		      INNER JOIN [VISU_OperatingCounters] [x_1] ON [cp].[TagId] = [x_1].[TagId]
      ORDER BY
	      [x_1].[ModifiedTimeStamp]

**Comment by viceroypenguin** [comment]
(untested) try this: 

```csharp
s.Query<OpCounter>()
  .GroupBy(x => x.TagId, (k, g) => new { TagId = k, Sum = g.Sum(x => x.TagValue), })
  .Select(x => new 
  { 
    x.TagId, 
    x.Sum, 
    FinalValue = s.Query<OpCounter>()
      .Where(y => y.TagId == x.TagId)
      .OrderByDescending(y => y.ModifiedTimeStamp)
      .FirstOrDefault(),
    });
````

**Comment by jogibear9988** [comment]
@viceroypenguin 

your's does not work...
I'll get a InvalidOperationException

![image](https://user-images.githubusercontent.com/364896/167630217-b2d6e953-7afa-4a7f-9512-5cdda9c6bbb6.png)

**Comment by viceroypenguin** [comment]
(tested)

```csharp
s.Query<OpCounter>()
  .GroupBy(x => x.TagId, (k, g) => new { TagId = k, Sum = g.Sum(x => x.Value), })
  .SelectMany(
	  x => s.Query<OpCounter>()
		  .Where(y => y.TagId == x.TagId)
		  .OrderByDescending(y => y.Modified)
		  .Take(1),
	  (x, y) => new { x, y, })
```

**Comment by sdanyliv** [comment]
Use the following query:
```cs
var queryRN = 
    from op in s.Query<OpCounter>()
    select new 
    { 
        Value = Sql.Ext.Sum(op.TagValue)
            .Overt()
            .PartitionBy(op.TagI)
            .ToValue(), 
        RN = Sql.Ext.RowNumber()
            .Overt()
            .PartitionBy(op.TagI)
            .OrderBy(op.Modified)
            .ToValue()
        OperatingCounter = op
    };

var query = 
    from q in queryRN
    where q.RN == 1
    select new 
    {
        q.Value,
        q.OperatingCounter
    }
```

**Comment by jogibear9988** [comment]
I'll test all 3 solution and analyse wich will have the best performance. I'll post here when I'm done

Thanks for the help

**Comment by jogibear9988** [comment]
I now tried all 3 Queries on a Database Table with 222495 rows, wich result in 44147 rows in the result.

Everyone of the 3 queries takes 2 seconds, so ther is no notable difference in speed with this amaount of rows.

But I will stick to @sdanyliv's solution
