### ISSUE TITLE
Too many connections. 

### ISSUE THREAD

**Issue by ilsnk** [linq2db/linq2db#3559]
I use the standard way to connect to my db, but the connections grow and the old ones don't get released :/
How can I close old unused connections?

I am using ILinqToDBSettings for connect to database

```c#
 public class SQLSettings : ILinqToDBSettings
 {
        public IEnumerable<IDataProviderSettings> DataProviders => Enumerable.Empty<IDataProviderSettings>();
        public string DefaultConfiguration => "SqlServer";
        public string DefaultDataProvider => "SqlServer";
        public string ConnectionString { get; private set; }

        public SQLSettings(string databaseServerIP, string databaseServerPort, string databaseName = "db", string databaseUser = "admin", string databasePass = "admin")
        {
            ConnectionString = $"Server={databaseServerIP};Port={databaseServerPort};database={databaseName};user={databaseUser};password={databasePass};SslMode=None;Convert Zero Datetime=true;";
        }

        public IEnumerable<IConnectionStringSettings> ConnectionStrings
        {
            get
            {
                yield return new ConnectionStringSettings
                {
                    Name = "ViceDB",
                    ProviderName = ProviderName.MySql,
                    ConnectionString = ConnectionString
                };
            }
        }
    }
``` 
i set it up like this

```c#
 DataConnection.DefaultSettings = new SQLSettings();
```
```c#
 public class ViceDB : DataConnection
 {
        public ViceDB() : base("ViceDB") { }
        public ITable<ViceUserDataInfo> UsersData => GetTable<ViceUserDataInfo>();
 }
```

**And when i use this methods, my connection count slowly increase. And i have this exception:**
```
Exception message: Authentication to host 'AWS' for user 'admin' using method 'mysql_native_password' failed with message: Too many connections 
```
```c#
 public async Task<bool> UpdateData(ViceUserDataInfo data)
 {
        using (var db = new ViceDB())
        {
             await db.UpdateAsync(data);
             return true;
         }
 }

 public async Task<ViceUserDataInfo> GetUsersDataByIdAsync(string id)
 {
         ViceUserDataInfo data = default;
         using (var db = new ViceDB())
         {
             data = await db.UsersData.FirstOrDefaultAsync(a => a.Id == id);
         }
         return data;
 }
```

### Environment details
linq2db version: *3.7.0*
Database Server: *MySql amazon*
Database Provider: *MySql*
Operating system: *Linux/MacOs*
.NET Framework: *4.X*

**Comment by MaceWindu** [comment]
`Database Provider: MySql`  well, there is no such provider as `MySql`. It is wether `MySql.Data` or `MySqlConnector`

If you use `MySql.Data` I would recomment to switch to `MySqlConnector`.

In general it looks like issue with connection pool growing over server-side limit. You can try to set lower limit in connection string (or disable it, not recommended). But first I recommed to try `MySqlConnector` if you don't use it - `MySql.Data` contains a lot of bugs.

For connection string pooling options check this message https://github.com/linq2db/linq2db/issues/3390#issuecomment-1002987605

**Comment by ilsnk** [comment]
exactly, I'm using MySql.Data, I'll try using MySqlConnector and write back about the test results

**Comment by MaceWindu** [comment]
I'll close it for now
