### ISSUE TITLE
Association bug - child object is not returned

### ISSUE THREAD

**Issue by Firebie** [linq2db/linq2db#3561]
Association bug - child object is not returned.
Although generated sql is correct and data exists in table - the linq query returns null for the Child.
```No exception```

### Steps to reproduce
```c#
  public static class Test
  {
    public class ChildBase
    {
      [Column] public int Data { get; set; }
    }

    [Table]
    public class Child : ChildBase
    {
      [Column, PrimaryKey] public int ChildId { get; set; }
    }

    [Table]
    public class Parent
    {
      [Column] public int ParentId { get; set; }
      [Column] public int ChildId { get; set; }

      [Association(ThisKey = nameof(ChildId), OtherKey = nameof(Child.ChildId), CanBeNull = true)]
      public Child C1 { get; }
    }

    public static void AssocialtionTest()
    {
      using var dc = new Dc();
      var child = dc.GetTable<Parent>().Where(i => i.ParentId == 1)
        .Select(i => i.C1)
        .FirstOrDefault();
    }
  }
```

### Environment details
linq2db version: latest from git
Database Server: sql 2008
Database Provider: sql 2008
Operating system: win10
.NET Framework: 4.7.2

**Comment by Firebie** [comment]
Changing CanBeNull to false will allow to work.

**Comment by Firebie** [comment]
Looks like fixed in 4.0.1

**Comment by MaceWindu** [comment]
cannot reproduce

**Comment by Firebie** [comment]
Way to reproduce:
```sql
create table Child 
(
  ChildId int,
  Data int,
)


create table Parent
(
  ParentId int,
  ChildId  int,
)

insert into Child values (1, null)
insert into Parent values (1, 1)
```
```c#
  public static class Test
  {
    public class ChildBase
    {
      [Column] public int Data { get; set; }
    }

    [Table]
    public class Child : ChildBase
    {
      [Column, PrimaryKey] public int ChildId { get; set; }
    }

    public class ParentBase
    {
      [Column] public int ChildId { get; set; }
    }

    [Table]
    public class Parent : ParentBase
    {
      [Column] public int ParentId { get; set; }

      [Association(ThisKey = nameof(ChildId), OtherKey = nameof(Child.ChildId), CanBeNull = true)]
      public Child C1 { get; }
    }

    public static void AssocialtionTest()
    {
      using var dc = new Dc();
      var child = dc.GetTable<Parent>().Where(i => i.ParentId == 1)
        .Select(i => i.C1)
        .FirstOrDefault();
    }
  }

```

**Comment by MaceWindu** [comment]
One question - if your fields are nullable, why don't you specify it in mapping using `CanBeNull=true` property?

**Comment by MaceWindu** [comment]
I don't think we should support incorrectly configured mappings

**Comment by Firebie** [comment]
As I understand, in a case that property specified like [Column] public int Data { get; set; } and has in db 'null', the value has to be converted to '0', but in this case the whole 'Child' becomes null.

**Comment by MaceWindu** [comment]
I will check why it happens

**Comment by MaceWindu** [comment]
Checked. To create child entity we check that non-nullable column is not null and in this case it is `Data` column. As it contains null, we consider it missing record.

**Comment by MaceWindu** [comment]
In general, there are a lot of places where linq2db depends on mapping information. If it is not correct - it will result in unexpected behavior.

**Comment by Firebie** [comment]
Than I have another question - as I see in the code - ColumnAttribute.CanBeNull has true by default - is not it?

**Comment by MaceWindu** [comment]
Nope, it is not set by default. Check `HasCanBeNull` method.

If you don't specify `CanBeNull` explicitly then we use following values:
- `true` for reference types and `nullable<t>` types
- `false` for value types
- NRT annotations on reference types not taken into account currently #3606

**Comment by Firebie** [comment]
> Checked. To create child entity we check that non-nullable column is not null and in this case it is `Data` column. As it contains null, we consider it missing record.

But if I will get the record straight, not from association - this will work:
```c#
var child = dc.GetTable<Child>().Where(i => i.Child.Id == 1).FirstOrDefault();
```

**Comment by MaceWindu** [comment]
```cs
// nullable
string Field1
// non-nullable
int Field2
// nullable
int? Field3
```

**Comment by MaceWindu** [comment]
yep, it will work, because it doesn't use child object mapping logic

**Comment by Firebie** [comment]
> Checked. To create child entity we check that non-nullable column is not null and in this case it is `Data` column. As it contains null, we consider it missing record.

Could you please point to the Linq2db code where this is checked?
Thanks

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/DefaultIfEmptyBuilder.cs#L70=

**Comment by Firebie** [comment]
Wait, should not Linq2db check for null only those values, on which association is defined, i.e. in my example that would be 'Child.ChildId'?

**Comment by MaceWindu** [comment]
No, because this code is not specific to associations. It could be used e.g. for sub-queries, so we use more generic approach
