### ISSUE TITLE
How can I use ArrayPool in order to prevent pressure on GC?

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3562]
Files stored in bytea (Postgres) are loaded very frequently from the database. 

Can I manage to advice Linq2Db to write in predefined instances that are built up by using ```ArrayPool``` for ```byte[]``` properties?

I would like to reduce the pressure on GC.

**Comment by MaceWindu** [comment]
Those arrays allocated by `Npgsql`. I have no idea currently wether use of `ArrayPool` configurable on npgsql side, but from their repo I see at least that it is used.

**Comment by HypeillingerChillinger** [comment]
Perfect, thanks
