### ISSUE TITLE
Direct usage of Dataproviders does not work in V4 any more.

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3565]
Code like this:

     public void AddConnectionString(string connectionName, string providerName, string connectionString)
        {
          IDataProvider prov = new SQLiteDataProvider(ProviderName.SQLiteClassic);
          if (providerName == "System.Data.SqlClient")
          {
            prov = new SqlServerDataProvider(connectionName, SqlServerVersion.v2012);
          }
          else if (providerName == "Oracle.DataAccess.Client")
          {
            prov = new OracleDataProvider(connectionName, OracleVersion.v12);
          }
          DataConnection.AddConfiguration(providerName + "." + connectionName, connectionString, prov);
        }

does not work in V4 any more, cause the DataProviders are not public. 

Whats the expected migration Path?

**Comment by MaceWindu** [comment]
See notes here https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#release-400-release-candidate-1

**Comment by jogibear9988** [comment]
Part of the notes:

[BREAKING] We are marking most of database provider classes (e.g. SqlServerDataProvider) as abstract. There are many reasons why you shouldn't create provider instance manually. Proper way to get provider instance is to use <dbname>Tools.GetDataProvider(...) method or DataConnection.GetDataProvider(...) methods. Only situation when you should create provider instance manually is when you sub-class provider to override some of it's methods. And even is such case it is better to register your provider implementation in DataConnection with AddDataProvider method.

**Comment by jogibear9988** [comment]
I'll post how I fixed it, when I'm done

**Comment by jogibear9988** [comment]
https://github.com/linq2db/linq2db/blob/271b60f71fd89b357f2436876a5ce80544476a53/Source/LinqToDB/Data/DataConnection.cs#L809
https://github.com/linq2db/linq2db/blob/271b60f71fd89b357f2436876a5ce80544476a53/Source/LinqToDB/Data/DataConnection.cs#L823
https://github.com/linq2db/linq2db/blob/271b60f71fd89b357f2436876a5ce80544476a53/Source/LinqToDB/Data/DataConnection.cs#L841

how do I get a specific version?

**Comment by MaceWindu** [comment]
By using `GetDataProvider` method from tools class, not from DataConnection

**Comment by jogibear9988** [comment]
Fixed it with using the Get Method from each Tool class.

Thx @MaceWindu
