### ISSUE TITLE
CLI generates wrong file name if the name of the class was overridden

### ISSUE THREAD

**Issue by Powerz** [linq2db/linq2db#3568]
When I change the name of the class in the interceptor, the CLI generates the correct class, but it puts it in a file with the wrong name (see example below).

```c#
public class SuperInterceptor : LinqToDB.Scaffold.ScaffoldInterceptors
{
    public override void PreprocessEntity(ITypeParser typeParser, EntityModel entityModel)
    {
        if (entityModel.Metadata.Name.ToString() == "dbo.SuperTable")
        {
            entityModel.Class.Name = "AwesomeTable";
            
            // The name of the file containing the generated class is going to be SuperTable instead of AwesomeTable
        }
    }
}
```

Expected file name: `AwesomeTable.cs`.
Actual file name: `SuperTable.cs`.

### Environment details
linq2db version: 4.0.0
Database Server: Postgres
Operating system: macOS
.NET Framework: 6.0.101

**Comment by MaceWindu** [comment]
Yep, I'm aware of this issue. Wasn't able to fix it before release, but will see how to fix it
