### ISSUE TITLE
Sql.Collate should accept null strings

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3579]
This is the current definition of `Collate`:
```csharp
public static string Collate(this string expr, [SqlQueryDependent] string collation)
```
Takes a non-null string, returns a non-null string.

It should take and return a nullable `string?` with an annotation to say it returns non-null string if `expr` is non-null.

**Comment by APalpattuwar7** [comment]
Can I work on this?

**Comment by MaceWindu** [comment]
@jods4, could you clarify your intent? Which behavior you expect for `null` as collation?

**Comment by MaceWindu** [comment]
@APalpattuwar7 you are welcome. Do you need directions?

**Comment by viceroypenguin** [comment]
`[return: NotNullIfNotNull("expr")]`

**Comment by MaceWindu** [comment]
Yes, also you need to set `SqlExpression.CanBeNull` property to `expr.CanBeNull` value.

Implementations are here: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.Collate.cs

**Comment by APalpattuwar7** [comment]
@MaceWindu @viceroypenguin @jods4 I have raised a PR for this - https://github.com/linq2db/linq2db/pull/3802
Could you please review and let me know if any changes required or any test case to add here?

**Comment by APalpattuwar7** [comment]
I am trying to build this solution on my mac, but getting below error while loading almost all the projects - 
![Screenshot 2022-10-08 at 4 46 22 PM](https://user-images.githubusercontent.com/24300489/194704823-39a6b6e2-ef45-48c6-99d2-d6648608b965.png)

Can anyone please help me resolve this? I have installed .NET 6 SDK.

**Comment by MaceWindu** [comment]
If this error comes from `linq2db.benchmarks` project (at least it is mentioned at your screen) - just ignore it/unload that project.

Also I see that .net 5 is still used for build. Never used mac, so it is hard for me to say what's wrong. As an option you could try to remove .net 5 sdk - it is eol anyway

**Comment by MaceWindu** [comment]
Also you can just submit pr and it will be built automatically by CI and report build errors if any
