### ISSUE TITLE
Add `MERGE` support to PostgreSQL provider

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3584]
PostgreSQL 15 adds `MERGE` statement support and already available in beta 1.

List of sub-tasks:
- add pgsql 15 to CI (https://hub.docker.com/_/postgres)
- implement merge builder methods in PostgreSQLSqlBuilder
- enable merge tests for postgresql 15

**Comment by ademchenko** [comment]
Could you say how you plan to integrate that method into the existing API? Are you going to change the implementation of InsertOrUpdate in the case of Postgres 15 but leave the previous one (INSERT INTO...ON CONFICT...) for older versions? If yes, do you consider potential differences in the behaviour of that method (i.e. backwards compatibility issues)  in different Postgres versions?

**Comment by MaceWindu** [comment]
Initial plan was to enable Merge API for pgsql.
But we can also add new dialect (v15) and re-implement `InsertOrUpdate` APIs using merge.

Didn't looked into it yet - could you provide more details on differences between merge and insert here?
