### ISSUE TITLE
 add an oracle driver?

### ISSUE THREAD

**Issue by 273168121** [linq2db/linq2db#3585]
Is it possible to add a Devart.Data.Oracle driver？ thx

**Comment by MaceWindu** [comment]
It is possible. But what it adds compared to `Oracle.ManagedDataAccess` provider?

**Comment by MaceWindu** [comment]
Will add support in next release (4.1.0, not 4.0.1). Still don't see how it is better than oracle's provider, but it is quite an easy task and I see a lot of upvotes for it.

**Comment by 273168121** [comment]
> Will add support in next release (4.1.0, not 4.0.1). Still don't see how it is better than oracle's provider, but it is quite an easy task and I see a lot of upvotes for it.

The driver update is faster than the official one, and it is a commercial version,

**Comment by MaceWindu** [comment]
I'm afraid it will be hard to add support of it as:
- express edition doesn't work in .net core, which means we cannot test it on CI
- I have no idea how to configure express edition licensing to test it even in .net framework:
```
Devart.Common.LicenseException: 'Feature is not supported. This error is thrown by Devart .NET Standard assemblies if license key validation fails. Possible reasons: 1. License key is not found, refer to the "Licensing .NET Standard (.NET Core) Projects" article in the product documentation. 2. Your product edition (the key was generated for) doesn't support the feature you are trying to use, refer to the editions matrix. 3. Your key is outdated for using the current product version, renew the license key in the Customer Portal.'
```

**Comment by MaceWindu** [comment]
I will prepare PR with new provider, but it will not be released as part of linq2db due to licensing/testing issues.

We will add official support only if those issues fixed.
Anyone is welcome to maintain it as separate package.

**Comment by 273168121** [comment]
You have to download the installation package from the official website first. After the installation is complete, there will be a one-month trial key locally, located in C:\ProgramData\Devart\dotConnect\License.
download link
https://www.devart.com/dotconnect/oracle/download.html

THX

**Comment by MaceWindu** [comment]
Actually there is another option that will allow us to support it: if somebody will provide win2022-compatible docker image with oracle server - we will be able to automate at least netfx testing
