### ISSUE TITLE
Native OracleBulkCopy reports inconsistent row numbers

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3602]
We did some work using the new managed ODP.NET bulk copy provider and noticed an inconsistency.

When notifying progress, during the bulk operation we receive the number of rows since the last notification (e.g. it was always a constant 1000).

In linq2db code, this comes straight from provider:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs#L93-L99

When the operation completes, we received one last notification with the final _total_ number, which is a notification created by linq2db itself:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs#L122-L128

This is hard to consume because the same event sometimes reports progress and eventually reports the total number of rows.

It looks like the code specifically assumes that the reported number is the total, since it performs 
`if (rc.RowsCopied != rd.Count)`
before raising the final event.

This could be worked around by cumulating the number of rows in the native event instead of assigning:
`rc.RowsCopied += args.RowsCopied;`

Some caution is required, though, as I'm not 100% sure if this isn't an Oracle bug.
I haven't tested Oracle native provider to check if the behaviour would be different.
My understanding of Oracle documentation is that this is unexpected and the total should be reported. 
From https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleRowsCopiedEventArgsClass.htm#ODPNT7714
> *Property Value*
> An Int64 value that returns the number of rows copied.
> *Remarks*
> The value in the `RowsCopied` property is reset by each call to a `WriteToServer` method.

Seems to me we only call `WriteToServer` once...

**Comment by viceroypenguin** [comment]
So the fix will be out in about 2-3 years?... At least you got them to acknowledge it!

**Comment by jods4** [comment]
@viceroypenguin No idea, they rarely commit to a specific release, maybe later this year.
