### ISSUE TITLE
DataConnection property IDbConnection property method gone

### ISSUE THREAD

**Issue by 273168121** [linq2db/linq2db#3607]
There is a property method in version 3.7
public IDbConnection Connection => EnsureConnection().Connection;
I use it in the project, because there is an existing connection, can it be restored in the next version? Or tell me which method?
  Thank you.

**Comment by MaceWindu** [comment]
Could you clarify which propery/method on which class you mean? Also you could check v4 migration notes: https://github.com/linq2db/linq2db/wiki/Version-4-Migration

**Comment by 273168121** [comment]
public class  DataConnection {
          

		readonly Func<IDbConnection>? _connectionFactory;

		/// <summary>
		/// Gets underlying database connection, used by current connection object.
		/// </summary>
		public IDbConnection Connection => EnsureConnection().Connection;
}

 [DataConnection](https://github.com/linq2db/linq2db/blob/v3.7.0/Source/LinqToDB/Data/DataConnection.cs)
1072 lines

**Comment by 273168121** [comment]
sorry ,the return type is changed
