### ISSUE TITLE
Slow Oracle Bulk Insert

### ISSUE THREAD

**Issue by tymokhin** [linq2db/linq2db#361]
When I try to use BulkCopy on Oracle I got a problem with executing and speed. More detail when count of added rows was more than 400 time of executing is increase for 50s. When count of rows was more then 500 I don`t wait of finishing of query executing. The analisys of query shown that during executing prepare query like

``` sql
INSERT ALL
INTO mytable (column1, column2, column_n) VALUES (val1, val2, expr_n)
INTO mytable (column1, column2, column_n) VALUES (val1, val2, expr_n)
...
INTO mytable (column1, column2, column_n) VALUES (val1, val2, expr_n)
SELECT * FROM dual;
```

and when count of rows is increase result string of query is increase also and Oracle can`t execute this query or do it very slow.

For fix this problem in oracle provider I propose to use anothe type of query and type of data transmission.

Oracle allow to user query like

``` sql
INSERT INTO mytable (column1, column2, column_n) VALUES (:p1, :p2, :pn)
```

were p1, p2, ... pn could be an array. this type of query execute very fast. Maybe authors of linq2db use this way for increase speed of insert query in oracle provider. The code of BulkCopy method of Oracle Provider which use this way is shown below and can be used authors of linq2db for increase speed of insert query in oracle provider if they will consider it useful.

``` c#
class BulkOracleDataProvider : OracleDataProvider
    {
        public BulkOracleDataProvider():base() { }
        public BulkOracleDataProvider(string name): base(name) { }
        public override BulkCopyRowsCopied BulkCopy<T>(DataConnection dataConnection, BulkCopyOptions options, IEnumerable<T> source)
        {
            if (options.BulkCopyType == BulkCopyType.RowByRow) return base.BulkCopy<T>(dataConnection, options, source);
            BulkCopyRowsCopied res = new BulkCopyRowsCopied();
            using (OracleCommand cmd = new OracleCommand())
            {
                cmd.Connection = dataConnection.Connection as OracleConnection;
                cmd.ArrayBindCount = source.AsQueryable().Count();
                if (cmd.ArrayBindCount == 0)
                {
                    res.Abort = true;
                    return res;
                }

                cmd.CommandType = CommandType.Text;

               TableAttribute attr = typeof(T).GetCustomAttribute<TableAttribute>();
                if (attr == null)
                {
                    res.Abort = true;
                    return res;
                }

                cmd.CommandText = "INSERT INTO " + attr.Name + " (";


                IEnumerable<PropertyInfo> props = typeof(T).GetProperties().Where(a => a.GetCustomAttribute(typeof(ColumnAttribute)) != null);
                if (props.AsQueryable().Count() == 0)
                {
                    res.Abort = true;
                    return res;
                }

                List<string> param = new List<string>();
                foreach (PropertyInfo prop in props)
                {
                    ColumnAttribute pInfo = prop.GetCustomAttributes(typeof(ColumnAttribute), false).Cast<ColumnAttribute>().First();
                    if (pInfo == null)
                    {
                        res.Abort = true;
                        return res;
                    }

                    param.Add(pInfo.Name);
                    cmd.Parameters.Add(new OracleParameter()
                    {
                        Direction = ParameterDirection.Input,
                        ParameterName = ":" + pInfo.Name,
                        OracleDbType = GetOracleDbType(prop.PropertyType),
                        //OracleDbType = (OracleDbType)Enum.Parse(typeof(OracleDbType), pInfo.DbType),
                        Value = source.Select(o => prop.GetValue(o, null)).ToArray()
                    });
                }

                cmd.CommandText += String.Join(", ", param.ToArray()) + ") VALUES(:" + String.Join(", :", param.ToArray()) + ")";

                cmd.ExecuteNonQuery();
            }
            return res;
        }
```

**Comment by igor-tkachev** [comment]
Use this code

```c#
LinqToDB.DataProvider.Oracle.OracleTools.DefaultBulkCopyType = BulkCopyType.ProviderSpecific;
```

**Comment by tymokhin** [comment]
I try to use LinqToDB.DataProvider.Oracle.OracleTools.DefaultBulkCopyType = BulkCopyType.ProviderSpecific;

Unfortunately this way genetare sql query like

INSERT ALL
INTO mytable (column1, column2, column_n) VALUES (val1, val2, expr_n)
INTO mytable (column1, column2, column_n) VALUES (val1, val2, expr_n)
...
INTO mytable (column1, column2, column_n) VALUES (val1, val2, expr_n)
SELECT * FROM dual;

It`s to slow and don`t work with more than 300 records. My way allow to add all 55000 records in one query and do in very fast ( about 2s) Time of insert is little more whan delete time (1,6s)

**Comment by igor-tkachev** [comment]
I tried to implement your scenario, but got the following error:

```
ORA-03111: Break received on communication channel
```

To reproduce it, set OracleTools.UseAlternativeBulkCopy to true.

**Comment by tymokhin** [comment]
I can`t reproduce this error because don`t have property 
OracleTools.UseAlternativeBulkCopy
and can`t set it to true

I use Oracle client v12.1.0 and ODP.net v112.3.20. Clent I installed separately using Oracle distributive. ODP.NET - from nuget repository

**Comment by sdanyliv** [comment]
@ili, close please. We can reopen if needed.
UseAlternativeBulkCopy property exists.

**Comment by ili** [comment]
I think we should make test before closing with inserting huge data.

**Comment by tymokhin** [comment]
Unfirtunatly now I don`t have enough time for checking UseAlternativeBulkCopy
I make my alternative bulk copy which I describe above. When I back to this topic I reopen it and wrote my results.
