### ISSUE TITLE
LastQuery shows 1.1000000000000001 instead of expected 1.1

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3622]
For a ```double?``` property the value in the following query in LastQuery is 1.1000000000000001 instead of 1.1 (unexpected).

```c#
            var res = context.TestEntities
                .Where(x => x.DoubleNullableTest == 1.1)
                .Select(x => x.DoubleNullableTest)
                .ToList();
```

``` 
"SELECT\n\t[x].[DoubleNullableTest]\nFROM\n\t[TestEntity] [x]\nWHERE\n\t[x].[DoubleNullableTest] = 1.1000000000000001\n"
```

### Environment details
linq2db version: 4.1.0
Database Server: SQLite In Memory
Database Provider: *?*
Operating system: *?*
.NET Framework: *?*

**Comment by MaceWindu** [comment]
We use roundtrip format for floating point numbers. In your case  1.1000000000000001 and 1.1 represnt same double value

**Comment by MaceWindu** [comment]
Extra notes:
- sqlite actually use bad floating point parser, which could break roundtripping (I've reported an issue couple of years ago but it was dismissed)
- usually it is not a good idea to use equality operators without some epsilon for floats
