### ISSUE TITLE
Multiple concurrent async calls in Blazor project not working

### ISSUE THREAD

**Issue by iColdoCatalin** [linq2db/linq2db#3623]
I have a Blazor Server project that tries to load from the same page 2 different components.
Each of them are making a call to the db to get some data but failing due to pending async operation already in progress.
Both have await and their parent methods are async Task<T>.

This is how I register the db instance, where DBService is a class where the dbcontext is injected and the used:
```cs
builder.Services.AddLinqToDbContext<MYDB>((provider, options) =>
        {
            options
            .UseSqlServer(builder.Configuration.GetConnectionString("MYCONNSTRING"))
            .UseDefaultLogging(provider);
        });
builder.Services.AddScoped<IDbService, DbService>();
```
Can multiple calls to db from blazor components be done at same time?

I have already seen that event EF has same issues with Blazor projects. (https://stackoverflow.com/questions/66464018/how-do-i-make-data-calls-from-different-blazor-components-simultaneously)

Is any solution to this issue for linq2db?

Here is the exception thrown:

```
System.InvalidOperationException: The command execution cannot proceed due to a pending asynchronous operation already in progress.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at InfrastructureLibrary.DataAccess.DbService.GetKpiOee() in D:\MyApp\InfrastructureLibrary\DataAccess\DbService.cs:line 275
   at MyApp.Components.IndicatorKpiOee.OnInitializedAsync() in
```

**Comment by sdanyliv** [comment]
Could you please create small reproducible sample?

**Comment by iColdoCatalin** [comment]
@sdanyliv I not sure how to di it since it connects to local dbs.
I can explain more on what I do to make you understand the issue better.

I have an Index page where I've added 3 blazor components.
Each of them in the OnInitializedAsync do some calls to the db.
Each of the call to the db has the await.
Each of the call is made through a service injected on each component.
The service DBService has the dbcontext injected.
When loading the page the error occurs if all 3 components do calls to the db. If I comment and leave only one then it works but similtaneosly for all 3 doesn't work.

Code from Index.razor
```
<IndicatorCommessePerStato />
<SectionsWithCount />
<IndicatorKpiOee />
```

Code of one of the components (all 3 do almost the same thing one call to the db and renders html with the result):
```
@inject IDbService dbService

@if (totaliCommessePerStato is not null)
{
    <p>here I put the result</p>
}
else
{
    <p>not loaded</p>
}

@code {
    private Dictionary<int, int>? totaliCommessePerStato;

    protected async override Task OnInitializedAsync()
    {
        totaliCommessePerStato = await dbService.GetTotaleCommessePerStato();
    }
}
```

**Comment by viceroypenguin** [comment]
If you change `builder.Services.AddScoped<IDbService, DbService>();` to `builder.Services.AddTransient<IDbService, DbService>();`, that should help. 

With Scoped registration, the same `DbService` is shared by all three, since they are instantiated in the same scope, and so they try to issue simultaneous db calls from multiple async tasks. With Transient registration, each will receive it's own `DbService` no matter what.

**Comment by iColdoCatalin** [comment]
@viceroypenguin I just tryied with AddTransient but same issue.
It seems a Blazor related issue and for now I'm trying the solution suggested by Daniel Hoffman on the link that I provided from stackoverflow using a semaphore.
It seems to work but it is a pain now to use this workaround everywhere it uses more that 1 component that does simultaniosly calls to the db since Blazor is a "components" style framework.

**Comment by iColdoCatalin** [comment]
@viceroypenguin sorry but I'm not so expert on DI but 
I tryied to you your code and I get on error on sp.GetRequiredService<DbService>() on converting delegate type.
Changed it to 
`builder.Services.AddTransient<Func<IDbService>>(sp => sp.GetRequiredService<Func<DbService>>());`
and getting a runtime error on DbService as "type not registered".

What I'm doing wrong?

**Comment by viceroypenguin** [comment]
```csharp
builder.Services.AddLinqToDbContext<MYDB>((provider, options) =>
        {
            options
            .UseSqlServer(builder.Configuration.GetConnectionString("MYCONNSTRING"))
            .UseDefaultLogging(provider);
        });
builder.Services.AddTransient<IDbService, DbService>();
builder.Services.AddTransient<Func<IDbService>>(sp => () => sp.GetRequiredService<IDbService>());
```

You still need to add the `IDbService` as a service; and the `GetRequiredService()` should be for an `IDbService`.  What I missed above is an extra layer of lambda - that's my fault. Try the above now?

**Comment by viceroypenguin** [comment]
One more thing to try, sorry. I forgot to have you update the `.AddLinqToDbContext<>()` call. If you add a second parameter, `lifetime: ServiceLifetime.Transient`, that should address the issue. 

```csharp
builder.Services.AddLinqToDbContext<MYDB>((provider, options) =>
        {
            options
            .UseSqlServer(builder.Configuration.GetConnectionString("MYCONNSTRING"))
            .UseDefaultLogging(provider);
        }, lifetime: ServiceLifetime.Transient);
```

**Comment by iColdoCatalin** [comment]
Wow. All working now.
Thank you a lot @viceroypenguin 
Using the factory method should I do dispose of the service or something on the component?
Adding it as Transient does have any performance issues?

**Comment by iColdoCatalin** [comment]
Ok, understood.
Thank you again @viceroypenguin 
You've been very helpfull and patient.
Have a nice day!
