### ISSUE TITLE
LinqToDB.Templates is not created

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#3625]
Hello,

when I add Linq2db and Linq2DB.SqlServer to my project, the **LinqToDB.Template**s folder is not created to my project.

What do I wrong ?

Thanks Andreas

**Comment by viceroypenguin** [comment]
Which IDE are you using? Visual Studio, VS Code, Rider?

**Comment by AndreasWaning** [comment]
Sorry, I made a mistake. It is Visual Studio 2022 WinForm Project: .NET4.8

**Comment by viceroypenguin** [comment]
By default, a winforms project will use the old style csproj/nuget packages, which does not support creating the LinqToDB.Templates folder. 

Depending on how old the project is, there are two recommendations:
1. Create a new .net 6 winforms app, but change the `<TargetFramework>` tag to reference net48
2. Update the existing .csproj file to use the new SDK style csproj format.

**Comment by AndreasWaning** [comment]
The Problem is, in .NET6 it works fine.
If I try .NET4.8 it adds only the dlls but he will not create the Template Folder !

**Comment by AndreasWaning** [comment]
wait I will try

**Comment by AndreasWaning** [comment]
OK, that works
