### ISSUE TITLE
[SQL Server] MergeWithOutputAsync possible to add Output for [Source]?

### ISSUE THREAD

**Issue by MihailsKuzmins** [linq2db/linq2db#3643]
Currently in MergeWithOutputAsync it is only possible to output:
- action: "inserted" or "updated"
- result [INSERTED]
- result [DELEETED]

In the SQL Server it is also possible to output [Source], so I am wondering would it be possible to add something like this?
![image](https://user-images.githubusercontent.com/47413092/177000723-bf4d6976-b17e-4e4c-8d24-d2c729042a19.png)

So it could look something like this. Required change is only for `MergeWithOutputAsync`.
```c#
await using var tempTable = await toughComDatabase.CreateTempTableAsync(input, cancellationToken: ct)
	.ConfigureAwait(false);

connection.Source
	.Merge()
	.Using(tempTable)
	.On(static (x, y) => x.Name == y.Name)
	.InsertWhenNotMatched(static x => new Record
	{
		Name = x.Name,
		Prop1 = x.Prop1,
		Prop2 = x.Prop2
	})
	.UpdateWhenMatched(static (_, y) => new Record
	{
		Prop1 = y.Prop1,
		Prop2 = y.Prop2
	})
	.MergeWithOutputAsync((action, deleted, inserted, source) =>
	{
		inserted.PK,
		source.GroupId
	});
```
And the generated SQL might look like this
```sql
MERGE INTO [tblTarget] [Target]
USING (
	SELECT
		[t1].[GroupId],
		[t1].[Name],
		[t1].[Prop1],
		[t1].[Prop2]
	FROM
		[tempdb]..[#tmpSource] [t1]
) [Source]
(
	[GroupId],
	[Name],
	[Prop1],
	[Prop2]
)
ON ([Target].[Name] = [Source].[Name])

WHEN NOT MATCHED THEN
INSERT
(
	[Name],
	[Prop1],
	[Prop2]
)
VALUES
(
	[Source].[Name],
	[Source].[Prop1],
	[Source].[Prop2]
)

WHEN MATCHED THEN
UPDATE
SET
	[Target].[Prop1] = [Source].[Prop1],
	[Target].[Prop2Keys] = [Source].[Prop2]
OUTPUT
	[INSERTED].[IdentityPK],
	[Source].[GroupId]
;
```

If it is possible to consider this feature, let me know if some details are needed.

### Environment details
linq2db version: 4.1.0
Database Server: SQL Server
Database Provider: Microsoft.Data.SqlClient
Operating system: Windows
.NET Framework: .NET 6

**Comment by jangarach** [comment]
The idea seems very interesting. Would like to see this functionality.
