### ISSUE TITLE
BulkUpdate

### ISSUE THREAD

**Issue by ilsnk** [linq2db/linq2db#3654]
When the bulk update appears, unfortunately I feel uncomfortable with the bulk data update. ( 
I tried using this, when bulk inserting it skips some data, and dont save them 
https://github.com/linq2db/linq2db/issues/1259#issuecomment-409235996

**Comment by ilsnk** [comment]
> Explain what you are trying to update in bulk. How many records? Which database?

Im use MySql, 600-2000 records every 10seconds. Its just player data, look like

```  c#
using (var db = new ViceDB())
{
       _ = await db.BeginTransactionAsync();
       _ = await db.BulkUpdateAsync(arrayData, db.UsersData);
       _ = await db.BulkUpdateAsync(arrayItems, db.UserItems);
       await db.CommitTransactionAsync();
}

```

**Comment by sdanyliv** [comment]
```
DataConnection.TurnTraceSwitchOn();
DataConnection.WriteTraceLine = (s1,s2) =>
	{
		Debug.WriteLine(s1);
	};
```

**Comment by sdanyliv** [comment]
Try without transaction. Instead of posting images post UPDATE SQL, find it.

**Comment by ilsnk** [comment]
I am also from Ukraine, I sent you a linkedin request, if it's not difficult for you, I can call you
like this sql?
```
UPDATE
	`Items` `outer_1`
		INNER JOIN `temp_Items` `inner_1` ON `outer_1`.`Id` = `inner_1`.`Id`
SET
	`outer_1`.`Cars` = `inner_1`.`Cars`,
	`outer_1`.`Planes` = `inner_1`.`Planes`,
	`outer_1`.`Boats` = `inner_1`.`Boats`,
	`outer_1`.`Guns` = `inner_1`.`Guns`,
	`outer_1`.`Clothes` = `inner_1`.`Clothes`,
	`outer_1`.`Other` = `inner_1`.`Other`,
	`outer_1`.`ExtraItem` = `inner_1`.`ExtraItem`
```

**Comment by ilsnk** [comment]
i solved this problem, sorry, bulk update work fine, trouble in my business logic
