### ISSUE TITLE
I use now dotnet linq2db scaffold.

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#3656]
Hello,

I use not the command "dotnet linq2db scaffold ...."

The file created has some differences from the file created with T4.

e.g. the table AktenStatus is now called AktenStatuses
The attribute IDD is now Idd 

Is it possible to change this with a parameter, that it creates the same as before ?
Thanks Andreas

**Comment by MaceWindu** [comment]
T4 used strange naming logic in some places, not always convertible to new tool.
I don't have time now to test it, but you could try to use [t4_pluralized or t4](https://linq2db.github.io/articles/cli-help.txt) casing options. If it doesn't help, you need to use customization logic for specific members https://linq2db.github.io/articles/CLI.html#interceptor-implementation-examples

You you have a list of pairs `(db name + expected name in code)` I could look at it later - maybe it will be possible to improve compatibility.
