### ISSUE TITLE
Condition not include entity will be ignored

### ISSUE THREAD

**Issue by darkflame0** [linq2db/linq2db#3666]
```cs
        db.CreateTable<Test>(tableOptions: TableOptions.CreateIfNotExists);
        int? t = 0;
        await db.GetTable<Test>().Where(a => t == null || a.Id == t).ToListAsync();

        [Table(IsColumnAttributeRequired = false)]
        public class Test
        {
            [Identity]
            [PrimaryKey]
            public int Id { get; set; }
        }
```
wrong sql
```sql
      DECLARE @t_1 Int -- Int32
      SET     @t_1 = 0

      SELECT
        [a].[Id]
      FROM
        [Test] [a]
      WHERE
        [a].[Id] = @t_1
```

**Comment by jods4** [comment]
@darkflame0 what's wrong ?

Linq2db simplifies expressions that can be evaluated client-side, so when `t` is `0` then `t == null` is false and it can be dropped.

If for some reason you don't want something to be evaluated client-side, you can wrap it in `Sql.AsSql(...)`.

**Comment by sdanyliv** [comment]
It is as designed. Predicate optimized and better query is produced.

**Comment by darkflame0** [comment]
I try 
```cs
await db.GetTable<Test>().Where(a => Sql.AsSql(t == null || a.Id == t)).ToListAsync();
```
still generate
```sql
      DECLARE @t_1 Int -- Int32
      SET     @t_1 = 0

      SELECT
        [a].[Id]
      FROM
        [Test] [a]
      WHERE
        [a].[Id] = @t_1
```
but
```cs
await db.GetTable<Test>().Where(a => Sql.AsSql(1 == 0)).ToListAsync();
```
works

```sql
     SELECT
        [a].[Id]
      FROM
        [Test] [a]
      WHERE
        1 = 0
```

**Comment by sdanyliv** [comment]
AsSql should not help here. Optimiser simplifies predicate in any case.

Do you have problem with query?

**Comment by jods4** [comment]
@sdanyliv is it expected that client-side expressions are simplified inside `AsSql`? I didn't expect that.

@darkflame0 your second example is special.
`1 == 0` would evaluate to `false` and since most DB don't have a boolean literal or even type, Linq2DB uses `1 = 0` to represent false in a SQL query :)
If you start with something like `2 == 3` it will probably be translated into `1 == 0` as well.

**Comment by darkflame0** [comment]
@jods4 yes, you are right...
@sdanyliv no, I have no problem now,just want to try,thanks.
