### ISSUE TITLE
Exception convert LINQ to SQL

### ISSUE THREAD

**Issue by FreeNickName** [linq2db/linq2db#371]
I'm using OData protocol over linq2db. OData works with IQueryable from linq2db. This problem occurs when OData layer try to resolve query which contains this pattern: `TraderName lt 'some text'`.
[calltrace](https://drive.google.com/open?id=0B1wQRpLMiHo9LVJmNlQweGNVckE)

It works through the Entity Framework..
[Example SQL generated EF](https://drive.google.com/open?id=0B1wQRpLMiHo9VmFTWHNULVFBTFE)

Version linq2db - 1.0.7.1

**Comment by FreeNickName** [comment]
line 38 in Example SQL generated EF `([Filter1].[Name1] < @p__linq__2)`

**Comment by FreeNickName** [comment]
In version 1.0.7.4 the same problem - [calltrace](https://drive.google.com/open?id=0B1wQRpLMiHo9Qm0tcjZXSDRWeHc)

**Comment by jogibear9988** [comment]
can you post your linq?

**Comment by sdanyliv** [comment]
@ili, close. We can reopen if problem still needs resolving.

**Comment by ili** [comment]
Closing issue.

@FreeNickName that would be great if you can come back to this issue and post minimum sample.

**Comment by FreeNickName** [comment]
Sorry for the waiting, the problem is difficult to repeat, the component that made such a request was updated and now does not do it any more =)

**Comment by sdanyliv** [comment]
@FreeNickName, maybe this library may be helpful for you
https://github.com/voronov-maxim/OdataToEntity
