### ISSUE TITLE
Documentation is deleted

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#3713]
I cannot access any documentation under `api` section.

See this commit: https://github.com/linq2db/linq2db.github.io/commit/089b15b275f2838e94acdd64e1b32f20372da11c

**Comment by MaceWindu** [comment]
Yep, recent msbuild release broke docfx, used for API docs generation https://github.com/dotnet/docfx/issues/8097

Reverted recent docs deploys (they shouldn't happen anyway)
