### ISSUE TITLE
Getting Issue with SAP HANA while Generating POCO Class using T4 Template

### ISSUE THREAD

**Issue by rahuljain257** [linq2db/linq2db#3719]
Hello Team,

Well, I am trying my hands on with this library and facing configuration level issues. The error which I am getting are as follows - "**ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified**"

Screenshot 1 - Config File screenshot
![Untitled](https://user-images.githubusercontent.com/111686671/185789079-3a908be7-173e-4429-b73b-e2d6d9c27b52.png)
  
Screenshot 2 - Error While Executing the TT File
![Untitled](https://user-images.githubusercontent.com/111686671/185789115-fec1ea91-aed6-4209-97b3-8be94982a7bd.png)

Screenshot 3 - Project Details for your reference
![Untitled](https://user-images.githubusercontent.com/111686671/185789172-be334343-56a9-4759-9294-e90a0baf7077.png)

Screenshot 4 - Tried modifyng the LinqToDB.SapHana.ttinclude file but no access 
![Untitled](https://user-images.githubusercontent.com/111686671/185789330-89ef88b1-0c9f-484e-8081-391eb2bda7ad.png)

Screenshot 5 - ODBC32 bit Screenshot
![Untitled](https://user-images.githubusercontent.com/111686671/185789458-270f3cca-1ea8-4cb2-b5ae-e22f71e538a4.png)

Let me know if you require more details from my end. 

Attaching the test project for your reference 
[ConsoleApp1.zip](https://github.com/linq2db/linq2db/files/9388989/ConsoleApp1.zip)

### Environment details

`Linq To DB` version: 4.1.1.0
Database (with version): SAP HANA v2.0
ADO.NET Provider (with version): SAP.Data.hana
Operating system: Windows Server 2019
.NET Version: 4.7

**Comment by MaceWindu** [comment]
You don't need to edit `LinqToDB.SapHana.ttinclude` - you can call  `LoadSapHanaMetadata` overload that takes connection string

Tested it my test instance and it works fine so you probably need to check your ODBC configuration once more:

```cs
LoadSapHanaMetadata("Driver={HDBODBC};SERVERNODE=localhost:39017;CS=TESTDB;UID=SYSTEM;PWD=Passw0rd;");
```

`Get-OdbcDriver | Where-Object {$_.Name -like '*HDB*'} | Select Name, Platform`:

```
Name      Platform
----      --------
HDBODBC32 32-bit
HDBODBC   64-bit
```

**Comment by rahuljain257** [comment]
Hello MaceWindu, 

Thanks for your response... Can we meet over the call ? here is the meeting invite - (https://meet.google.com/muh-vwby-tmc)

**Comment by MaceWindu** [comment]
Well,

1. This is not `linq2db` issue, but issue with ODBC setup/connection string on your machine
2. If your connection string use Driver configuration directly, you don't need DSN and should check installed ODBC drivers and their bitness (VS 2022 T4 requires 64-bit driver `HDBODBC`)
3. If you want to use DSN, your connection string should use DSN name, not driver name
4. Check https://stackoverflow.com/questions/17115632
