### ISSUE TITLE
How to implement Converter DateTime with TimeZone

### ISSUE THREAD

**Issue by b0bi79** [linq2db/linq2db#372]
The model has a field DateTimeOffset and TimeZone. Is it possible to implement a converter that will convert DateTimeOffset to DateTime considering TimeZone?
In BLToolkit I have been implemented MemberMapper as follows:

```cs
    public override object GetValue(object o)
    {
        var dtoffset = (DateTimeOffset) base.GetValue(o);
        var pos = (PosInfo)o;
        return dtoffset > MinDate ? DateTimeHelper.ConvertToUtc(dtoffset, Tz.GetShopTimeZone(pos.shopNum)) : MinDate; 
    }
```

**Comment by ili** [comment]
No, we do not have such possibility.

I think you will need to do it with adding new property to `PosInfo`
```cs
public class PosInfo
{
    public DateTime SomeTime => _dtoffset > MinDate ? DateTimeHelper.ConvertToUtc(_dtoffset, Tz.GetShopTimeZone(shopNum)) : MinDate;
}
```
