### ISSUE TITLE
LINUX+ MONO  + Sqlite

### ISSUE THREAD

**Issue by JTrotta** [linq2db/linq2db#374]
I'm using linq2db on Linux+Mono+Sqlite. It works perfectly. 
However it seems to be too slow (25 seconds!) the first time the application connects to the db and (probably?) maps the tables for the first time. The next CRUD operations are normally fast.
Is there a way to speed up the first connection time, or map the db at design time? 
The hardware I'm using is old ARM 6 mono core.

Thank you
JJ

**Comment by JTrotta** [comment]
No answers?

**Comment by igor-tkachev** [comment]
Can you connect to your SQLite manually? How is it work?

**Comment by jogibear9988** [comment]
have you tried newest version? ili fixed some multithreading issues in mapping. 
why is the first slowdown a problem? you could activate you app logic after linq2db is initialized?

**Comment by jogibear9988** [comment]
wich sqlite do you use? i use system.data.sqlite and not mono one! (you can compile native part of system.data.sqlite easily)

**Comment by JTrotta** [comment]
@jogibear9988 
thank you for tips! Could you please tell me how to compile system.data.sqlite easily?

**Comment by jogibear9988** [comment]
for managed part used system.data.sqlite.core nuget, for native part, download source from https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki

here is a script to build for a garz+fricke panle with a arm core:

    #!/bin/bash
    libname=libSQLite.Interop.dll
    cd SQLite.Interop/src/generic
    source /opt/guf/1.6.1/environment-setup-cortexa9hf-vfp-neon-poky-linux-gnueabi
    arm-poky-linux-gnueabi-gcc  -g -fPIC -shared -o $libname interop.c -I../core -DSQLITE_THREADSAFE=1 -DSQLITE_USE_URI=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_STAT4=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_SOUNDEX=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_API_ARMOR=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DINTEROP_TEST_EXTENSION=1 -DINTEROP_EXTENSION_FUNCTIONS=1 -DINTEROP_VIRTUAL_TABLE=1 -DINTEROP_FTS5_EXTENSION=1 -DINTEROP_PERCENTILE_EXTENSION=1 -DINTEROP_TOTYPE_EXTENSION=1 -DINTEROP_REGEXP_EXTENSION=1 -DINTEROP_JSON1_EXTENSION=1 -lm -lpthread -ldl

**Comment by ili** [comment]
Can anybody give me this compiled linux binaries? :)

**Comment by jogibear9988** [comment]
for wich platform? x86, x64, arm? no problem if you say for wich...

**Comment by ili** [comment]
for Travis :)

**Comment by jogibear9988** [comment]
I look to compile a dll tomorrow

**Comment by jogibear9988** [comment]
Here, the Unmanged DLL for Linux. Copy into to the bin directory from where you run the app.

[libSQLite.Interop.dll.zip](https://github.com/linq2db/linq2db/files/680465/libSQLite.Interop.dll.zip)

**Comment by jogibear9988** [comment]
Can this be closed?

**Comment by ili** [comment]
yes, it moves to #504
