### ISSUE TITLE
How to update a field with a value depending by itself

### ISSUE THREAD

**Issue by fedrok777** [linq2db/linq2db#3758]
I mean,
how can I Translate in linq2db the following SQL syntax

`update myTable set myField1 = myField1 + 1 where myField2 = 'xyz'`

thank you.
;-)

**Comment by MaceWindu** [comment]
1. Use one of `Update` overloads with `Expression<Func<TTable, TTable>>` setter

https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/UpdateTests.cs#L32

```cs
db.Table
    .Update(
        record => record.Field2 = "xyz",
        currentRecord => new Table { Field = currentRecord .Field+ 1 });
```

2. Use `Set` methods to set each field separately:

https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/UpdateTests.cs#L146

```cs
db.Table
    .Where(record => record.Field2 = "xyz")
    .Set(
        currentRecord => currentRecord.FIeld,
        currentValue => currentValue + 1)
    .Update();
```

**Comment by fedrok777** [comment]
Thank you @MaceWindu.
How can I translate the 2nd version in VB.NET?
Sorry I'm not able with C#...

**Comment by fedrok777** [comment]
thank you @MaceWindu

**Comment by fedrok777** [comment]
@MaceWindu thank you very much!
;-)
