### ISSUE TITLE
Scaffold generator generating incorrect attributes for composite FK associations and MSSQL schema-bound functions

### ISSUE THREAD

**Issue by thomas-hori** [linq2db/linq2db#3762]
### Describe your issue

A large number of tests started failing when we attempted to migrate our project from the old T4 template system to the new scaffold generator.  Investigation of the cause revealed two errors in the attributes being generated by the scaffold generator:

1. Associations generated from <var>n</var>-component composite foreign key constraints join on the first component <var>n</var> times (redundantly) and the other components never—furthermore, all components of `OtherKey` *other than the first* get set to the same name (same `nameof` expression, even) as the corresponding components of `ThisKey`, even when the names do not correspond between the tables.  *In other words*, all components of both `ThisKey` and `OtherKey` apart from the first seem to be clobbered by duplicates of the first component of `ThisKey`.
2. We have a schema-bound scalar function which we use from LINQ expressions.  SQL Server appears to require it to be referenced with an explicit schema prefix (`dbo.`), which the scaffold was not including (unlike the old T4 system).  Furthermore, the scaffold attribute was wrapping the name in `[]`, resulting in `[…](…)` syntax in the generated SQL, which was causing a syntax error on the SQL Server side.

### Steps to reproduce

https://github.com/megaslice/LDBMinim

### Environment details

`Linq To DB` version: 4.2.0

Database (with version): SQL Server 2019

ADO.NET Provider (with version): Microsoft.Data.SqlClient 4.1.0

Operating system: Windows 10

.NET Version: 6.0

**Comment by coudy** [comment]
Is there anything happening on this? Should we keep using the T4-based code generator?

**Comment by MaceWindu** [comment]
Will be fixed next release. Currently we busy with other stuff, so PR is welcome

**Comment by alexmehlhorn** [comment]
This is issue is not fixed. When scalar function is within a non-default schema on SQL Server then running from CLI (version 5.2.0.0) generates:

	throw new InvalidOperationException("Scalar function cannot be called outside of query");

**Comment by alexmehlhorn** [comment]
Please see the sample from this exact issue:
[Sql.Function("dbo.ExampleFunction", ServerSideOnly = true)]
		public static int? ExampleFunction(int? k)
		{
			throw new InvalidOperationException("Scalar function cannot be called outside of query");
		}

Code is still being generated exactly like that.

**Comment by MaceWindu** [comment]
@alexmehlhorn tries to say that we don't generate escaped name for scalar function in schema. Which I cannot confirm. Just tested generation and it produce escaped names for both main and addtional schema functions

**Comment by sdanyliv** [comment]
@alexmehlhorn, there is only one way to get value from this function is to use `Select`:
```cs
var result = db.Select(() => MyClass.ExampleFunction(n));
```
