### ISSUE TITLE
[PLSQL] ExecuteProcAsync tries to map BOOLEAN as Int16

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#3763]
When I try to execute a stored procedure passing a boolean output type, linq2db is trying to set that output type declaring it as int16 instead of boolean, triggering **PLS-00306: wrong number or types of arguments in call to 'FOO_SP_NAME'**

How to reproduce:
Create an stored procedure declaring an input varchar parameter, and output BOOLEAN parameter,
then try to execute it using ExecuteProcAsync passing the parameters indicating the boolean output type:
```
var hasSomeBoolValue = new DataParameter("FOO", false)
            {
                Direction = System.Data.ParameterDirection.Output,
                DataType = DataType.Boolean
            };
```

I know BOOLEAN cannot be used as part of sql but i believe should be working correctly for stored procedures

Any clue about how to achieve to call this kind of stored procedures?

**Comment by viceroypenguin** [comment]
@gpgpublickey is there a difference between this request and #3740?

**Comment by gpgpublickey** [comment]
Yes, the https://github.com/linq2db/linq2db/issues/3740 issue is happening because boolean is not compatible for SQL, but in this case I'm trying to run a stored procedure, it's supposed to support BOOLEAN in that level

**Comment by MaceWindu** [comment]
This is related to #3740 actually. Right now we convert booleans to integers in oracle provider. #3754 fix it but it is not proper/complete fix as  it breaks backward compatibility
