### ISSUE TITLE
Backreferences naming

### ISSUE THREAD

**Issue by bert1973** [linq2db/linq2db#377]
The naming of backreferences seems to go wrong for at least my firebird (3.0) db.
The names exist of '1' only:

```
[Table("COUNTRY")]
public partial class COUNTRY
{
  [PrimaryKey, NotNull] public string COUNTRY_CODE { get; set; } // char(2)
  [Column,     NotNull] public string DESCRIPTION  { get; set; } // varchar(30)

  #region Associations

  /// <summary>
  /// FK_COUNTRY_1_BackReference
  /// </summary>
  [Association(ThisKey="COUNTRY_CODE", OtherKey="COUNTRY_CODE", CanBeNull=true, IsBackReference=true)]
  public IEnumerable<ADDRESS> 1 { get; set; }

  #endregion
}


/// <summary>
/// FK_COUNTRY_1
/// </summary>
[Association(ThisKey="COUNTRY_CODE", OtherKey="COUNTRY_CODE", CanBeNull=false, KeyName="FK_COUNTRY_1", BackReferenceName="1")]
public COUNTRY COUNTRY1 { get; set; }
```

instead of:

```
[Table("COUNTRY")]
public partial class COUNTRY
{
  [PrimaryKey, NotNull] public string COUNTRY_CODE { get; set; } // char(2)
  [Column,     NotNull] public string DESCRIPTION  { get; set; } // varchar(30)

  #region Associations

  /// <summary>
  /// FK_COUNTRY_1_BackReference
  /// </summary>
  [Association(ThisKey="COUNTRY_CODE", OtherKey="COUNTRY_CODE", CanBeNull=true, IsBackReference=true)]
  public IEnumerable<ADDRESS> FK_COUNTRY_1_BackReferences { get; set; }

  #endregion
}

/// <summary>
/// FK_COUNTRY_1
/// </summary>
[Association(ThisKey="COUNTRY_CODE", OtherKey="COUNTRY_CODE", CanBeNull=false, KeyName="FK_COUNTRY_1", BackReferenceName="FK_COUNTRY_1_BackReferences")]
public COUNTRY FK_COUNTRY_1 { get; set; }

```

It think that in ...\LinqToDB.Templates\LinqToDB.ttinclude at line 376 the check should be:

`if (GenerateBackReferences && !string.IsNullOrEmpty(key.BackReference.MemberName))`    instead of `key.BackReference.KeyName` ?

Because the key.BackReference.MemberName is used underneath:
`aa.Parameters.Add("BackReferenceName=\"" + key.BackReference.MemberName + "\"");`

Next to that I did a quick fix for myself at Line 145 in ..\LinqToDB.Templates\DataModel.ttinclude:

`MemberName      = k.KeyName, /* k.MemberName, */`

But maybe the real error resides in `MemberName = ToValidName(fk.Name)` Line 157 in SchemaProvider/SchemaProviderBase.cs?

Kind regards,
Bert

**Comment by ili** [comment]
@bert1973 can you provide database schema (script or backup)?

**Comment by bert1973** [comment]
Here's a small part from the script
[ddl.txt](https://github.com/linq2db/linq2db/files/801330/ddl.txt)
