### ISSUE TITLE
Unspecified DateTime Kind F#

### ISSUE THREAD

**Issue by Mrjuanblack** [linq2db/linq2db#3776]
### Describe your issue

I'm encountering an issue when dealing with DateTime objects. Seems like DateTime objects being inserted into the db will always have an `Unspecified Kind`, and I'm using Postgres so that will throw an error.
I'm making sure that I'm using UTC now to prevent that, but the error persists.
To make it work (for now) I'm falling back to EF Core methods, which makes me think that this might be a Linq2Db issue.

```
Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
```

### Steps to reproduce

Model
```fsharp
[<CLIMutable>]
type AppointmentCalendarEvent = {
    [<Key>]
    [<DatabaseGenerated(DatabaseGeneratedOption.Identity)>]
    Id : int
    AdiId : int
    StartTime : System.DateTime
    EndTime : System.DateTime
}
```
Repository method
```fsharp
type Repository(context : AppDbContext) =
    member _.insertAppointment() =
        let event : AppointmentCalendarEvent = {
            Id = 0 // For inserts with auto-generated PK
            AdiId = 0
            StartTime = System.DateTime.UtcNow
            EndTime = System.DateTime.UtcNow
        }

        task {
            try
                let! eventId = context.CreateLinqToDbContext().InsertWithInt32IdentityAsync(event)
                return event |> Result.Ok
            with
            | e ->
                return Result.Error e
        } |> Async.AwaitTask
```
Context
```fsharp
type AppDbContext(options: DbContextOptions<AppDbContext>) =
    inherit DbContext(options)

    [<DefaultValue>] val mutable appointmentCalendarEvent : DbSet<AppointmentCalendarEvent>
    member this.AppointmentCalendarEvent
        with get() = this.appointmentCalendarEvent
        and set v = this.appointmentCalendarEvent <- v

    override _.OnModelCreating builder =
        builder.RegisterOptionTypes() // enables option values for all entities
    
type TestDbContextFactory() =
    member this.CreateDbContext() =
        let options = new DbContextOptionsBuilder<AppDbContext>()
        options.UseNpgsql("connectionStringHere").UseFSharpTypes() |> ignore
        new AppDbContext(options.Options)
```
I'll link the project I created for this issue: https://github.com/Mrjuanblack/testProject

### Environment details

`Linq To DB` version: 4.2.0

Database (with version): Postgres 14.3

**Comment by Mrjuanblack** [comment]
I created another F# project without any EF Core components. It works perfectly, so I guess the error is somewhere between EF Core and Linq2Db communication.

**Comment by su8898** [comment]
Hi @MaceWindu I was wondering if there's any workaround for this issue?

**Comment by Mrjuanblack** [comment]
Found something that could be useful. Creating a `DateTime` object using `DateTime.Now` instead of `DateTime.UtcNow` wont throw an error.

**Comment by Mrjuanblack** [comment]
Using `System.DateTimeOffset.UtcNow.DateTime` seems to be a functional workaround? I'll have to test more to see if there's any drawback using that method.
