### ISSUE TITLE
Table name incorrect

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3781]
If you use fluent configuration

```c#
entityMappingBuilder.HasTableName("MyName")
```

then the name of the table in 

```c#
context.GetTable<Entity>().TableName;
```

is not "MyName"

**Comment by HypeillingerChillinger** [comment]
Works, my mistake. Sorry.

**Comment by sdanyliv** [comment]
@HypeillingerChillinger, use [Discussions](https://github.com/linq2db/linq2db/discussions) tab, do not open issues for every question.
