### ISSUE TITLE
Incomplete Update Query!

### ISSUE THREAD

**Issue by VictorHaine** [linq2db/linq2db#379]
Hi! I'm trying to update some bool fields on mapped objects to an access database, but the last executed query never shows the Boolean fields!

I can do it by using .Set(t => t.Property, user.Property), is this the only way??

Thanks!

**Comment by SergeyA** [comment]
Use Update() to set update expression to DB.
.Set(t => t.Property, user.Property)**.Update()**

**Comment by VictorHaine** [comment]
Another way to get it running is make all "boolean" values integers in the access db, and after the code generation, change the properties type from integer to bool!

This way, the db.Update(entity) works ok!

**Comment by sdanyliv** [comment]
@ili, close please.
