### ISSUE TITLE
[PLSQL] Are Hierarchical queries supported?

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#3790]
I would like to know if this plsql feature is supported by linq2db plsql provider https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries003.htm, and if it is supported how to use it.

Thanks

**Comment by sdanyliv** [comment]
Actually no. It is something that related to just for Oracle. Support needs additional design and efforts. So answer is - it is not implemented and not planned for near future.

**Comment by jods4** [comment]
It should be noted that the SQL-standard way to do hierarchical queries is a recursive CTE (`WITH x as (1 UNION ALL 2 FROM x)`) and this is both works in Oracle and is supported by linq2db.
