### ISSUE TITLE
[PLSQL] SELECT INTO FROM sequence issue

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#3793]
I have a table called THE_TABLE with a sequence configured as next:
`[Column("MY_SEQUENCE", DataType = LinqToDB.DataType.Int32, Length = 10, CanBeNull = false, IsPrimaryKey = true, IsIdentity = true)]`
`[SequenceName("MY_SEQUENCE")]`
`public new int MY_SEQUENCE{ get; set; }`
when I try to do something like:
`await _db.OtherTables.Select(x => new MyTable
                {
                    FOO = x.FOO,
                    BAR = x.BAR,
                    LOREM_IPSUM = x.LOREM_IPSUM
                }).Into(_db.TheTables).InsertAsync(cancellationToken);`
                
this code is being generated and I cannot find a way to setup the sequence number in the select,

```INSERT INTO THE_TABLE
(
        MY_SEQUENCE,
        FOO,
        BAR,
        LOREM_IPSUM
)
SELECT
        o.FOO,
        o.BAR,
        o.LOREM_IPSUM
FROM
        OTHER_TABLE o`

```
Exception message:
Stack trace:
`Exception: Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00947: not enough values`
```

I tried using Sql.Default<int>() but the ORM is omitting it. For instance:
`await _db.OtherTables.Select(x => new MyTable
                {
                    MY_SEQUENCE = Sql.Default<int>(),
                    FOO = x.FOO,
                    BAR = x.BAR,
                    LOREM_IPSUM = x.LOREM_IPSUM
                }).Into(_db.TheTables)
                .InsertAsync(cancellationToken);`
will generate the same code in raw sql as above.

I already tried using **InsertWithInt32IdentityAsync** as well but is not working, when I try to do it it's failing with:
```
Exception: Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00933: SQL command not properly ended
```

Generating this raw sql:


DECLARE @IDENTITY_PARAMETER Decimal
SET     @IDENTITY_PARAMETER = NULL

INSERT INTO THE_TABLE
(
        MY_SEQUENCE,
        FOO,
        BAR,
        LOREM_IPSUM
)
SELECT
        o.FOO,
        o.BAR,
        o.LOREM_IPSUM
FROM
        OTHER_TABLE o`
RETURNING
        MY_SEQUENCE INTO :IDENTITY_PARAMETER

**Comment by sdanyliv** [comment]
Will provide answer tomorrow, if no one has solution right now, Such insert needs defining SQL extension method. We do not do any predictions which SQL to generate for `nextval` if user used `Select`.  It is fully custom query and needs custom approach.

**Comment by gpgpublickey** [comment]
Thanks @sdanyliv  I will test it and let know my results

**Comment by gpgpublickey** [comment]
@sdanyliv seems to be not working, any value or expression assigned for the sequence attribute is being omitted in the raw sql, it's dissapearing

**Comment by gpgpublickey** [comment]
Adding more details, when IsIdentity or SequenceName is being applied to decorate the MY_SEQUENCE attribute the select MY_SEQUENCE is being removed, it has sense in some way, but if will do that it should take care to populate correctly the sequence in the SELECT part of the query I guess.

**Comment by sdanyliv** [comment]
Corrected previous answer.
`SequenceName` and is `Identity` is not used if you use projection. It is like: I want this one and no other. You have to explicitly specify which properties to insert and which values to insert.

**Comment by gpgpublickey** [comment]
Looks like is no way to use identities or sequences in a SELECT INTO FROM query where you depend on sequences to insert rows. right? Hope somebody knows a way to give some hint to the orm to allow specify the sequence in the select statement

**Comment by sdanyliv** [comment]
Wait for tomorrow. It's too late here. Solution should be simple.

**Comment by gpgpublickey** [comment]
Sure, thx for the help

**Comment by sdanyliv** [comment]
Try the following extension:
```cs
await _db.OtherTables
      .Into(_db.TheTables, x => new MyTable {
        MY_SEQUENCE = OracleHelpers.SequenceValue<MyTable, int>(e => e.MY_SEQUENCE), 
        FOO = x.FOO, 
        BAR = x.BAR, 
        LOREM_IPSUM = x.LOREM_IPSUM }
      ))
      .InsertAsync(cancellationToken)
```
And realisation:
```cs
public static class OracleHelpers
{
    class SequenceValueBuilder : Sql.IExtensionCallBuilder
    {
        public void Build(Sql.ISqExtensionBuilder builder)
        {
            var method = (MethodInfo)builder.Member;

            var genericArguments = method.GetGenericArguments();

            var propLambda = (LambdaExpression)((UnaryExpression)builder.Arguments[0]).Operand;

            var mi = MemberHelper.GetMemberInfo(propLambda.Body);
            var sequence = mi.GetCustomAttributes(typeof(SequenceNameAttribute)).FirstOrDefault() as SequenceNameAttribute;

            if (sequence is null)
            {
                throw new InvalidOperationException(
                    $"Type {genericArguments[0]} has no defined 'SequenceNameAttribute'");
            }

            builder.ResultExpression = new SqlExpression(genericArguments[1], sequence.SequenceName + ".nextval");
        }
    }

    [Sql.Extension("Oracle", builderType: typeof(SequenceValueBuilder), ServerSideOnly = true)]
    public static TResult SequenceValue<TEntity, TResult>(Expression<Func<TEntity, TResult>> sequenceProp)
    {
        throw new InvalidOperationException("SequenceValue is server side method.");
    }
}
```

**Comment by gpgpublickey** [comment]
sorry I had been busy this days, I will test it asap to give feedback

**Comment by sdanyliv** [comment]
Closing as there is no response.
