### ISSUE TITLE
Memory leak with SqlCommand instances not unregistering from CancellationToken

### ISSUE THREAD

**Issue by Shane32** [linq2db/linq2db#3817]
I'm using Linq To Db 4.2.0 and have a quite complicated setup that results in what appears to be a memory leak with SqlClient.  In the memory dump below, there appears to be about 400 `SqlConnection` instances and almost as many `SqlCommand` instances.  Those 400 instances are holding references to about 4 million `CancellationTokenRegistration` instances (which is a struct; see `CallbackNode` in the dump below).  Based on the source code of `SqlCommand` it would seem that `CancellationTokenRegistration` is only held as a local variable; nevertheless it is not being released properly, or the `CallbackNode` would wipe itself and remove itself from the double-linked-list of `CallbackNode` instances (aka `CancellationTokenRegistration` instances) referenced by the `CancellationTokenSource` object.

Perhaps what makes my code unique is that the `CancellationTokenSource` is held for a very long time, while the linq2db context is short lived (as it is held by a short-lived DI scope).  Perhaps if the context was long-lived, or if the CTS was short-lived, the issue would not present itself.

Looking further at the `SqlCommand` source, it would seem that there are different code paths based on if `ExecuteReader` or `ExecuteNonQuery` were called.  Also notable, there are no instances of `ExecuteReaderAsyncCallContext` or `ExecuteNonQueryAsyncCallContext` held in memory.

Based on the above, my assumptions/conclusions so far are:
1. SqlConnection is created, cached and reused behind the scenes and at this dump point has 400 instances in memory
2. Each SqlConnection has a single cached instance of SqlCommand, and at this dump point also has 400 instances in memory
3. SqlCommand is used repeatedly, and/or makes many repeated calls to `CancellationToken.Register` (totaling 4 million times)
4. Somewhere, somehow, SQL executions are not unregistering the cancellation token registrations.

(FYI, this capture was after an hour or two; there certainly was not 4 million SQL calls in that time period; but perhaps 4 million packets of SQL data or something.)

I have been unable to replicate the issue in my local test environment (on Windows); issue is occurring on in production (on Linux).  Typically the server crashes a couple times a day, when the memory usage gets up around 5gb.

Anyone have a suggestion how to diagnose this further -- what to look for, where to add diagnostic/logging, what to test, etc?  I've been pulling my hair out for a week now, and would really appreciate any suggestions.

### Photo 1

Here we can see `CallbackNode` (aka `CancellationTokenRegistration`) with almost 5 million references in memory.  Also, the underlined `StateMachineBox` and `TableBroadcaster` is essentially my currently executing code (which is a `BackgroundTask` and has an application lifetime).

![image](https://user-images.githubusercontent.com/6377684/199135722-f7a3394c-eb60-4295-9c8b-f1dec54b6ee9.png)

### Photo 2

Here you can see my code references a CancellationTokenSource, which contains a double-linked list of registrations.  These registrations appear to be almost all references to the static method `SqlCommand.s_cancelIgnoreFailure`, with the `State` property of the registration being a reference to the `SqlCommand` itself.

Ref:
- https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs

![image](https://user-images.githubusercontent.com/6377684/199135989-f29ef5d9-853b-4bb4-a8a1-0cff67753270.png)

### Photo 3

Here we can see the same situation for my other background task; a cancellation token source containing many linked registrations by `SqlCommand`.

![image](https://user-images.githubusercontent.com/6377684/199136167-9cee7706-0b17-457a-a410-24b90854e80e.png)

### Photo 4

Here we can see that there is about 400 instances of `SqlConnection` and `SqlCommand` currently in memory.  Also you can see via 'Paths to Root' that each of the 376 `SqlCommand` instances are only rooted by the cancellation token registration, not by any currently-executing code.

![image](https://user-images.githubusercontent.com/6377684/199141221-c9f5e1e3-1dc5-4b33-8ebe-f33321d9d0e1.png)

### StateMachineBox

This piece of my code executes in this fashion:

```cs
// singleton
private CancellationTokenSource _cts; // signaled when app is shutting down

while (true) {
    await GetSomeDataViaHttpAsync(_cts.Token);
    await DoSomeStuffAsync(_cts.Token);
    await Task.Delay(5000, _cts.Token);
}

Task DoSomeStuffAsync(CancellationToken token)
{
    using var scope = scopeFactory.CreateScope();
    var provider = scope.ServiceProvider;
    var db = provider.GetRequiredService<MyDbContext>();
    // do some stuff
}
```

### TableBroadcaster

This piece of code executes generally in this fashion:

```cs
// singleton
private CancellationTokenSource _cts; // signaled when app is shutting down

async void Broadcast(string txt)
{
    using var scope = scopeFactory.CreateScope();
    var provider = scope.ServiceProvider;
    var listeners = provider.GetRequiredService<IEnumerable<IListener>>();
    foreach (var listener in listeners)
    {
        await listener.DoStuffAsync(txt, _cts.Token);
    }
}
```

### Other notes

The LinqToDb context is a scoped service, and although the two background tasks above are singletons, a scope is created (and disposed of) each time DB access is necessary.  I've also enabled `ValidateScopes` so that it is impossible for any singleton service to pull a scoped service from DI.  I've also checked my async calls to be sure they are awaited.  Although it's a very large codebase, I have as of yet been unable to find anything that is not disposed of properly, or any missing awaits.

Typically access to the database is encompassed within a transaction; I've double checked every call to `BeginTransactionAsync` to be sure the transaction is disposed (via `using`).

In other areas of my codebase I do have a few scattered uses of `CreateTempTable` (and/or bulk upload), and the merge API.  Most everything else is pretty basic calls; `ToListAsync`, `FirstOrDefaultAsync`, and similar, however.

Considering the issue, I would guess that I can "solve" the issue by creating a linked cancellation token at the same time I create a DI service scope, and passing this cancellation token to all linq2db calls.  Disposing of the CTS should unlink itself from the parent/root CTS, and allow all unreleased SqlCommand instances to release themselves via GC collection along with the "child" CTS.  However, it would seem that I am merely masking the bug without fixing it, and it would be better to identify and solve the bug, saving this "fix" as a failsafe.  If this bug exists in the linq2db or Microsoft.Data.SqlClient codebase, it would be better for the community to solve it, so either way I think it's best to investigate further.

Other refs:
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationToken.cs
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenRegistration.cs
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs

### Environment details

`Linq To DB` version: ~4.2.0~ correction: 4.3.0

Database (with version): Azure SQL Server

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.0.1

Operating system: Linux - Azure App Service

.NET Version: 6.0

**Comment by MaceWindu** [comment]
https://github.com/dotnet/SqlClient/issues/1810 ?

**Comment by MaceWindu** [comment]
Try to downgrade to 5.0.0 to see if issue gone

**Comment by MaceWindu** [comment]
btw, good analysis :+1: 
When I've seen `CancellationToken` it immediately remind me that latest sqlclient release mentioned something about it in release notes..

**Comment by Shane32** [comment]
Thanks so much @MaceWindu ; this has to be it!  This was one of the packages I updated the day before the memory leak started occurring.  I was too focused on many of the other changes made then to think about checking the SqlClient changes.  (I even checked every linq2db change between 4.2.0 and 4.3.0 in case it was there.)  I'll downgrade the package this morning and monitor RAM usage, and post my results.

**Comment by Shane32** [comment]
For future reference, this is what my memory usage pattern has been like, where this shows the last 3 days:

Peaks are just before the server crashes (and auto-restarts), or when we published new code.  It doesn't gain as much as night, which is natural, nor as much on the weekend, and this chart contains Sat, Sun, and Mon.

![image](https://user-images.githubusercontent.com/6377684/199233797-01ee410f-19d1-413b-bb48-5d31bd9071d8.png)

("Memory working set" in Azure metrics)

**Comment by Shane32** [comment]
Seems to have solved it.  Thanks again @MaceWindu !  Definitely pays to read the release notes!

![image](https://user-images.githubusercontent.com/6377684/199312094-ad9d1be9-a0d4-41c8-8b36-5471de4a2887.png)

(after red line is after downgrading from SqlClient 5.0.1 to 5.0.0)
