### ISSUE TITLE
PRIMARY KEY  violation

### ISSUE THREAD

**Issue by KlausBenislavskis** [linq2db/linq2db#3818]
### Describe your issue

I have a system that creates a lot of "Save" requests to the database. For the procedure, I use the .InsertOrReplace() method, but I get the PK violation a few times an hour. Why is this so? Shouldn't this method be PK violation safe? Any solutions for this?

```
Stack trace:
System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Orders'. Cannot insert duplicate key in object 'dbo.Orders'. The duplicate key value is (52529786).
The statement has been terminated.
   at Commerce.Orders.Infrastructure.Sql.Repositories.Internal.OrderBaseRepository.Save(Order order, Boolean publishDomainEvents)
   at Commerce.Orders.Infrastructure.Sql.Repositories.OrderRepository.Save(Order order, Boolean publishDomainEvents)
   at Commerce.Orders.Infrastructure.Raven.MigrationRepositories.MigrationOrderRepository.Save(Order order, Boolean publishDomainEvents)
Error Number:2627,State:1,Class:14
```

```c#
            db.InsertOrReplace(convertedOrder);
```

### Environment details

`Linq To DB` version: 4.2.0

Database (with version):  SQL Server 2019

ADO.NET Provider (with version): System.Data.SqlClient 4.8.2

.NET Version: .NET framework 4.8

**Comment by MaceWindu** [comment]
Depends on used isulation level. I assume you use default `read commited` isolation.
For SQL Server `InsertOrReplace` method implemented using MERGE command without any additional lock hints (merge is not atomic).
You can use Merge API directly and apply required locks to it

**Comment by KlausBenislavskis** [comment]
> Depends on used isolation level. I assume you use default `read commited` isolation. For SQL Server `InsertOrReplace` method implemented using MERGE command without any additional lock hints (merge is not atomic). You can use Merge API directly and apply required locks to it

Well I wrap it BeginTransaction() I use it for the lock. I don't know what is  the default isolation level for transaction?

**Comment by MaceWindu** [comment]
Serializable should help. Another option could be something like that:
```cs
db.Table
    .Merge("HOLDLOCK")
    .Using(new[] { record })
    .OnTargetKey()
    .InsertWhenNotMatched()
    .UpdateWhenMatched()
    .Merge();
```

**Comment by KlausBenislavskis** [comment]
> Serializable should help. Another option could be something like that:
> 
> ```cs
> db.Table
>     .Merge("HOLDLOCK")
>     .Using(new[] { record })
>     .OnTargetKey()
>     .InsertWhenNotMatched()
>     .UpdateWhenMatched()
>     .Merge();
> ```

Why does merge API operations cost so much more? InsertOrReplace was done in 1-3 ms and the code you sent does it in 45-60 ms
