### ISSUE TITLE
Select Into Insert question

### ISSUE THREAD

**Issue by panthernet** [linq2db/linq2db#3819]
Hi. I have the following query:
```
            db.Scenarios.Where(a => a.Id == id)
                .Into(db.Scenarios)
                .Value(s => s.Name, name)
                .Value(s => s.Value, s => s.Value)
                .Insert();
```
Is it possible to perform insert of the selected entry modifying only some of it's properties and allowing all the others to be copied automatically? Right now I have to list ALL the properties to copy the entry. Or may be there's a better way to copy an entry in the same table modifying only some props?

Also I want to be able to fetch new entry ID from:
```
            db.Scenarios.Where(a => a.Id == id)
                .Into(db.Scenarios)
                .Value(s => s.Name, name)
                .Value(s => s.Value, s => s.Value)
                .InsertWithInt64Identity();
```
But it throws an exception `ORA-00933: sql command not properly ended`. Is there any work around?

Generated query:
```
DECLARE @Name Varchar2(9) -- String
SET     @Name = 'COPY'
DECLARE @id Int64
SET     @id = 61
DECLARE @IDENTITY_PARAMETER Decimal
SET     @IDENTITY_PARAMETER = NULL

INSERT INTO SCENARIOS
(
	NAME,
	VALUE
)
SELECT
	:Name,
	a.VALUE
FROM
	SCENARIOS a
WHERE
	a.ID = :id
RETURNING 
	ID INTO :IDENTITY_PARAMETER
```

### Environment details

`Linq To DB` version: *3.4.3.0*

Database (with version): *ORACLE 21c*

ADO.NET Provider (with version): *ODP.NET, Managed Driver 4.122.19.1* 

Operating system: *WIN 10*

.NET Version: *4.5.2*

**Comment by croban** [comment]
That should work, it works for me but I'm using mssql server.
Only those fields inside the list will be inserted, other values must have some default values (NULL, or GetDate() etc.) 
In the sql command only thing I can see is that @IDENTITY_PARAMETER is **Decimal** not Int64, but I said, I am not a best friend with "Oracle" ;)
Does this sql query runs inside DB or you are getting also error there?

**Comment by panthernet** [comment]
> That should work, it works for me but I'm using mssql server. Only those fields inside the list will be inserted, other values must have some default values (NULL, or GetDate() etc.) In the sql command only thing I can see is that @IDENTITY_PARAMETER is **Decimal** not Int64, but I said, I am not a best friend with "Oracle" ;) Does this sql query runs inside DB or you are getting also error there?

I guess Oracle stores all numbers as a decimal but I will take a look. Thanks. The generated query also fails in the Oracle console with the same error message. 

Sadly I can't upgrade linq2db version to check if it works in the latest version, the project requirements just won't allow me that.

**Comment by croban** [comment]
Maybe something similar https://github.com/linq2db/linq2db/issues/2831

**Comment by MaceWindu** [comment]
oracle doesn't support `returning/output` clause so it is expected for `InsertWith*Identity` API to generate unsupported sql. If you have an idea how oracle-compatible sql should look here - we could fix it

**Comment by panthernet** [comment]
> oracle doesn't support `returning/output` clause so it is expected for `InsertWith*Identity` API to generate unsupported sql. If you have an idea how oracle-compatible sql should look here - we could fix it

Sad but true. The only workaround I've found so far: https://stackoverflow.com/questions/49195453/alternative-to-returning-with-insert-select



> Maybe something similar #2831

Thanks, this is interesting feature to keep in mind but won't help with the current issue :)

**Comment by MaceWindu** [comment]
not supported by target database. not much could be done here

**Comment by MaceWindu** [comment]
Probably it could be done in oracle 23 using Merge, as they added returning clause to diagram https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/MERGE.html#GUID-5692CCB7-24D9-4C0E-81A7-A22436DC968F

but without any examples or mentioning it in document itself. So it could be not true

**Comment by MaceWindu** [comment]
Ok, looks like documentation bug, ORacle 23 doesn't understand RETURNING in merge
