### ISSUE TITLE
Mapping of TimeSpan and TimeSpan? and SQL generation with DateTime

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3821]
### Describe your issue

I mapp TimeSpan and TimeSpan? like this:

				mappingSchema.SetConverter<TimeSpan?, long?>((obj) => obj.HasValue ? obj.Value.Ticks : (long?)null);
				mappingSchema.SetConverter<TimeSpan?, DataParameter>((obj) => new DataParameter { Value = obj.HasValue ? obj.Value.Ticks : (long?)null });
				mappingSchema.SetConverter<long?, TimeSpan?>((val) => val.HasValue ? TimeSpan.FromTicks(val.Value) : (TimeSpan?)null);

				mappingSchema.SetConverter<TimeSpan, long?>((obj) => obj.Ticks);
				mappingSchema.SetConverter<TimeSpan, DataParameter>((obj) => new DataParameter { Value = obj.Ticks  });
				mappingSchema.SetConverter<long?, TimeSpan>((val) => TimeSpan.FromTicks(val));

Problem now is, I'd like to be able to add it to DateTime in the Database.
What makes me wonder is, it already works in SQLite, don't know how.

In SQL Server I get a overflow exception.

How can I tell Linq2Db how to create the correct SQL. Need it for SQLite, SQLServer, Oracle and Postgres

### Environment details

`Linq To DB` version: latest

**Comment by jogibear9988** [comment]
Or is it better if I store as a DateTime? ?
When I look in Converter.cs, we only support TimeSpan and not TimeSpan?

**Comment by MaceWindu** [comment]
We already have such mapping. You need to use `DataType.Int64` in mappings.

**Comment by jogibear9988** [comment]
Also for TimeSpan?
