### ISSUE TITLE
CreateTable puts columns in reverse order in some cases

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#3827]
### Describe your issue

In some cases, when I use `CreateTable` the columns are created in db in reverse order. I can't figure out why it's like that but it can be reproduced:

**Example:**
```csharp
NpgsqlConnection.GlobalTypeMapper.UseNodaTime();
context.CreateTable<TestDto>();

// this is created in reverse
public sealed class TestDto
{
    public string Adam { get; set; }
    [DataType("timestamptz")]
    public NodaTime.Instant Bobby { get; set; }
}

// this is created correctly
public sealed class TestDto
{
    public string Adam { get; set; }
    public string Bobby { get; set; }
}
```

### Environment details

`Linq To DB` version: *4.3.0*

Database (with version): *PostgreSQL 14*

Operating system: *Ubuntu 22.04*

.NET Version: *7.0*

**Comment by MaceWindu** [comment]
You should use `ColumnAttribute.Order` property https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/ColumnAttribute.cs#L330
