### ISSUE TITLE
Oracle sub query not working

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#383]
My query for oracle database is not generating the subquery;
```cs
from cda in db.GetTable<Contract_Distributor_Agent>()
    join a in db.GetTable<Agent>() on cda.Agent_Id equals a.Agent_Id
    join d in db.GetTable<Distributor>() on cda.Distributor_Id equals d.Distributor_Id
    join dcp in db.GetTable<Distributor_Commercial_Propert>() on d.Distributor_Id equals dcp.Distributor_Id
    join cp in db.GetTable<Commercial_Property>() on dcp.Commercial_Property_Id equals cp.Commercial_Property_Id
    join cd in db.GetTable<Contract_Dates>() on cda.Contract_Id equals cd.Contract_Id
    where cda.Contract_Id == 198827882
         && cda.Distributor_Type_Code == "CC"
         && cda.Distributor_Agent_Type_Prefix == "OFFICE"
         && cda.Represents_Type_Prefix == "REPRESENTS"
         && cd.Type_Code == "ESTCOE"
         && d.Type_Code == "RE"
         && dcp.Distributor_Type_Code == "RE"
    select new 
       {
            a.First_Name,
            a.Last_Name,
            d.Distributor_Name,
            cp.Street_Number,
            cp.Street_Name,
            City_Name = (from c in db.GetTable<Cities>()
                   where c.City_Code == cp.City_Code
                   select new { c.City_Name }),
             cp.State,
             cp.Zip_Code,
             cp.Zip_Plus_4,
             cd.Effective_Date
         };
```

The query generated by linq2db is 
```sql
SELECT
    a.First_Name,
    a.Last_Name,
    d.Distributor_Name,
    cp.Street_Number,
    cp.Street_Name,
    cp.City_Code,
    cp.State as State1,
    cp.Zip_Code,
    cp.Zip_Plus_4,
    cd.Effective_Date
FROM
    Contract_Distributor_Agent cda
        INNER JOIN Agent a ON cda.Agent_Id = a.Agent_Id
        INNER JOIN Distributor d ON cda.Distributor_Id = d.Distributor_Id
        INNER JOIN Distributor_Commercial_Propert dcp ON d.Distributor_Id = dcp.Distributor_Id
        INNER JOIN Commercial_Property cp ON dcp.Commercial_Property_Id = cp.Commercial_Property_Id
        INNER JOIN Contract_Dates cd ON cda.Contract_Id = cd.Contract_Id
WHERE
    cda.Contract_Id = 198827882 AND
    cda.Distributor_Type_Code = 'CC' AND
    cda.Distributor_Agent_Type_Prefix = 'OFFICE' AND
    cda.Represents_Type_Prefix = 'REPRESENTS' AND
    cd.Type_Code = 'ESTCOE' AND
    d.Type_Code = 'RE' AND
    dcp.Distributor_Type_Code = 'RE';
```
City name column is missing from sql

**Comment by sdanyliv** [comment]
Sub queries is not fully supported. You have to left join to the Cities table and grab data from join clause.

**Comment by sarabu07** [comment]
Thanks for your response. I modified the linq as below

from cda in db.GetTable<Contract_Distributor_Agent>()
                                            join a in db.GetTable<Agent>() on cda.Agent_Id equals a.Agent_Id
                                            join d in db.GetTable<Distributor>() on cda.Distributor_Id equals d.Distributor_Id
                                            join dcp in db.GetTable<Distributor_Commercial_Propert>() on d.Distributor_Id equals dcp.Distributor_Id
                                            join cp in db.GetTable<Commercial_Property>() on dcp.Commercial_Property_Id equals cp.Commercial_Property_Id
                                            join cd in db.GetTable<Contract_Dates>() on cda.Contract_Id equals cd.Contract_Id
                                            join ci in db.GetTable<Cities>() on cp.City_Code equals ci.City_Code
                                            into temp
                                            from b in temp.DefaultIfEmpty<Cities>()
                                            where cda.Contract_Id == 198827882
                                                    && cda.Distributor_Type_Code == "CC"
                                                    && cda.Distributor_Agent_Type_Prefix == "OFFICE"
                                                    && cda.Represents_Type_Prefix == "REPRESENTS"
                                                    && cd.Type_Code == "ESTCOE"
                                                    && d.Type_Code == "RE"
                                                    && dcp.Distributor_Type_Code == "RE"
                                            select new 
                                            {
                                                a.First_Name,
                                                a.Last_Name,
                                                d.Distributor_Name,
                                                cp.Street_Direction,
                                                cp.Street_Number,
                                                cp.Street_Name,
                                                b.City_Name,                                              
                                                cp.State,
                                                cp.Zip_Code,
                                                cp.Zip_Plus_4,
                                                cd.Effective_Date
                                            };

and it generated below query:


SELECT
  a.First_Name,
  a.Last_Name,
  d.Distributor_Name,
  cp.Street_Direction,
  cp.Street_Number,
  cp.Street_Name,
  temp.City_Name,
  cp.State as State1,
  cp.Zip_Code,
  cp.Zip_Plus_4,
  cd.Effective_Date
FROM
  Contract_Distributor_Agent cda
    INNER JOIN Agent a ON cda.Agent_Id = a.Agent_Id
    INNER JOIN Distributor d ON cda.Distributor_Id = d.Distributor_Id
    INNER JOIN Distributor_Commercial_Propert dcp ON d.Distributor_Id = dcp.Distributor_Id
    INNER JOIN Commercial_Property cp ON dcp.Commercial_Property_Id = cp.Commercial_Property_Id
    INNER JOIN Contract_Dates cd ON cda.Contract_Id = cd.Contract_Id
    LEFT JOIN Cities temp ON cp.City_Code IS NULL AND temp.City_Code IS NULL OR cp.City_Code = temp.City_Code
WHERE
  cda.Contract_Id = 198827882 AND
  cda.Distributor_Type_Code = 'CC' AND
  cda.Distributor_Agent_Type_Prefix = 'OFFICE' AND
  cda.Represents_Type_Prefix = 'REPRESENTS' AND
  cd.Type_Code = 'ESTCOE' AND
  d.Type_Code = 'RE' AND
  dcp.Distributor_Type_Code = 'RE'

please help me to modify linq to remove condition "cp.City_Code IS NULL AND temp.City_Code IS NULL OR" from sql query

**Comment by ili** [comment]
@sarabu07 this means that in your data model `City_Code` is nullable data type, that's why linq2db generates such condition.

Why do you need to remove it? In general this is right condition.

**Comment by MaceWindu** [comment]
Closing it as it looks like original query was not correct and it works now at least for v3

Expression
```cs
City_Name = (from c in db.GetTable<Cities>()
                   where c.City_Code == cp.City_Code
                   select new { c.City_Name }),
```
has `IQueryable<T>` type, so it is implemented as extra query.
To make it generate sub-query you should select one element. E.g. like this

```cs
City_Name = (from c in db.GetTable<Cities>()
                   where c.City_Code == cp.City_Code
                   select c.City_Name ).Single(), // or SingleOrdefault/FirstOrDefault
```
