### ISSUE TITLE
wrong variable declaration generated using FromSql for Oracle DB..

### ISSUE THREAD

**Issue by storaid** [linq2db/linq2db#3833]
### Describe your issue

it's annoying..
I don't get it!!
```
 using (var context = new EShipDbContext("ESHIPCLONEConnectionString"))
            {
                string active = "Y";
                var sql = @"
                            SELECT
                                    t1.active,
                                    t1.codedesc2,
                                    t1.codedesc1,
                                    t1.codekind,
                                    t1.codevalue
                            FROM
                                    BU_IMS_CODELIST t1
                            WHERE
                                    t1.active = {0}
                            ";
                var q3 = context.FromSql<dynamic>(sql, active);
                System.Console.WriteLine(q3.ToString());
            } // end using 
```
Result:
```
-- ESHIPCLONEConnectionString Oracle.11.Managed Oracle11
DECLARE @p_1 Varchar2(1) -- String
SET     @p_1 = 'Y'

SELECT
        t1
FROM
        (

                                            SELECT
                                                    t1.active,
                                                    t1.codedesc2,
                                                    t1.codedesc1,
                                                    t1.codekind,
                                                    t1.codevalue
                                            FROM
                                                    BU_IMS_CODELIST t1
                                            WHERE
                                                    t1.active = :p_1

        ) t1
```
see that???
@p_1??? this declaration is for SQL Server, not Oracle...
### Environment details

`Linq To DB` version: 4.3.0

Database (with version): Oracle 11

ADO.NET Provider (with version): ODP.NET

Operating system: Windows 10

.NET Version: 4.6.1

**Comment by MaceWindu** [comment]
this is not variable. It's trace data for query parameters for just logging and not intended to have specific db syntax.

**Comment by storaid** [comment]
thx for your reply...
yes, you're right...

just run this:
foreach(var d1 in q3)
                {
                    System.Console.WriteLine("pass");
                } // end foreach
Exception:
Oracle.ManagedDataAccess.Client.OracleException: 'ORA-00904:  Invalid ID

how to resolve this problem???

**Comment by storaid** [comment]
well, probably the problem is "dynamic" type....
looks like strong type is required...
var q3 = context.FromSql<EShipCodeList>(sql, active);
EShipCodeList => strong type
dynamic type is possible I can use it???

**Comment by MaceWindu** [comment]
check this feature https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/DynamicResultTests.cs

**Comment by storaid** [comment]
appreciate your help very much...
thank you!

**Comment by storaid** [comment]
- [ ]
