### ISSUE TITLE
Query Produces Exception in SQLServer - Property ist not defined

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3840]
I try the following Code in SQLServer
(not exctly this code, but smth similar)

	public class Test
	{
		public virtual DateTime? StartDateTime { get; set; }

		public virtual TimeSpan? PreNotification { get; set; }
	}

	[TestFixture]
	public class Issue3999Tests : TestBase
	{
		[Test]
		public void Test3999([IncludeDataSources(TestProvName.AllSqlServer)] string configuration)
		{
			var ms = new MappingSchema();
			var mb = ms.GetFluentMappingBuilder();
			mb.Entity<Test>()
			   .HasTableName("Common_Topology_Locations")
			   .Property(e => e.StartDateTime)
			   .Property(e => e.PreNotification);

			using (var db = GetDataContext(configuration, ms))
			{
				using (db.CreateLocalTable<Test>())
				{
					var qry = from t in db.GetTable<Test>()
							  select new
							  {
								  StartDateTime = t.StartDateTime,
								  PreNotification = t.PreNotification,
								  NotificationDateTime = Sql.DateAdd(Sql.DateParts.Millisecond, -1 * t.PreNotification!.Value.Milliseconds, t.StartDateTime)
							  };
					var lst = qry.ToList();
					var sql = ((DataConnection)db).LastQuery;
				}				
			}
		}
	}

**Comment by jogibear9988** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/364896/203297911-45abf2db-6b4b-4221-bf35-61bcff0267bc.png)

**Comment by MaceWindu** [comment]
Test pass for me

**Comment by MaceWindu** [comment]
Actually reproduced with a bit different setup

**Comment by MaceWindu** [comment]
looks like another case of same .net 7 bug

**Comment by jogibear9988** [comment]
No, we had this issue in our Net6 application. I'll look when my tests work again.

**Comment by MaceWindu** [comment]
7.0.1 released

**Comment by jogibear9988** [comment]
@MaceWindu I updated the test. With Values in database it fails

**Comment by MaceWindu** [comment]
![image](https://user-images.githubusercontent.com/1099238/214533321-b5e12f72-8264-43fb-9cd6-1209b0bed41a.png)
