### ISSUE TITLE
Dictionary not includeable in Postgresql in linq2db

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3847]
See the Test in the Pull request, will not work in linq2db with postgres

**Comment by MaceWindu** [comment]
What exactly doesn't work? I've run test locally and it passed for all enabled databases

**Comment by jogibear9988** [comment]
Mhm, I created invalid SQL in our Database. Of cause I simplified the Test case. So maybe it does not reproduce. I'll look, my problem atm is I cold not run the linq2db tests any more. I'll wait for the Net7 Bugfix release, then I'll test again.

**Comment by MaceWindu** [comment]
status?

**Comment by jogibear9988** [comment]
I'll look tomorrow

**Comment by MaceWindu** [comment]
Closing for now as existing tests work and no other tests provided.
