### ISSUE TITLE
Setting up 2 Database Connections

### ISSUE THREAD

**Issue by Echostorm44** [linq2db/linq2db#3850]
Long time linq2db user first time caller.
I have a project that needs to work with two different SqlServer Databases.  I normalled use the DataConnection.DefaultSettings pattern to setup my connection in the Startup.cs but that doesn't seem to work here.  If I do:

```
MyDB1.DefaultSettings = new MySettings(Configuration.GetConnectionString("MyDB1"));
MyDB2.DefaultSettings = new MySettings(Configuration.GetConnectionString("MyDB2"));
```

The result is that both end up with whatever the last connection string is, in this case MyDB2.
I tried setting them manually, like this:

```
MyDB1.AddOrSetConfiguration("MyDB1", Configuration.GetConnectionString("MyDB1"), "SqlServer");
MyDB2.AddOrSetConfiguration("MyDB2", Configuration.GetConnectionString("MyDB2"), "SqlServer");
```
Same problem here, they both seem to pickup what the last setting was.
Also tried:

```
MyDB1.SetConnectionString("MyDB1", Configuration.GetConnectionString("MyDB1"));
MyDB2.SetConnectionString("MyDB2", Configuration.GetConnectionString("MyDB2"));
```

With the same problem.
I hope someone can point me in the right direction here please.

**Comment by MaceWindu** [comment]
Do you pass configuration name (MyDB1 and MyDB2) to base constructor?

```cs
MyDB1.DefaultSettings = new MySettings(Configuration.GetConnectionString("MyDB1"));
MyDB2.DefaultSettings = new MySettings(Configuration.GetConnectionString("MyDB2"));
```

Here you create two instances of `ILinqToDBSettings` (`MySettings`) and assign them to the same static property `DefaultSettings`. There should be only one `ILinqToDBSettings` instance, which store both connection configurations.

---

```cs
MyDB1.AddOrSetConfiguration("MyDB1", Configuration.GetConnectionString("MyDB1"), "SqlServer");
MyDB2.AddOrSetConfiguration("MyDB2", Configuration.GetConnectionString("MyDB2"), "SqlServer");
```

This should work.
---

```cs
MyDB1.SetConnectionString("MyDB1", Configuration.GetConnectionString("MyDB1"));
MyDB2.SetConnectionString("MyDB2", Configuration.GetConnectionString("MyDB2"));
```

I would expect this will throw exception, as you need to have MyDB1 and MyDB2 configurations already to change connection string for them.

**Comment by Echostorm44** [comment]
Is there a way to do it where you can just create instances of the class without having to specify the configuration?  I can make it work using the AddOrSetConfiguration in startup (as above) and then creating the instances like this:

`using DB1db = new DB1("DB1");`

That being said, I adore this project, every time I'm forced to use EF or Dapper I feel dirty ;)

**Comment by ademchenko** [comment]
Assuming that DB1 is a partial class it's very easy to achieve. You just have to disable the generation of default ctor by the scaffolding tool (dataModel.add-default-ctor: false) and in our partial part add default ctor with  **_this("DB1")_** call.
