### ISSUE TITLE
Different behavior with Npgsql when using transaction and explicit commit

### ISSUE THREAD

**Issue by feeleen** [linq2db/linq2db#3863]
Tested on a latest versions (linq2db 4.3.0 and Npgsql 7.0.0) and found a different behavior when using Npgsql classes and linq2db classes.
Is it a bug or not?

this code throws exception:
```csharp
using (var db = new DataConnection("PostgreSQL", pgConnectionString))
{
    using (var tran = db.BeginTransaction())
    {
        db.Execute("commit;");
        db.Execute("INSERT INTO foo VALUES (1);");
    } // --> here exception thrown ('This NpgsqlTransaction has completed; it is no longer usable.')
}
```

this code doesn't throw:
```csharp
using (var connection = new NpgsqlConnection(pgConnectionString))
{
    connection.Open();
    using (var tran = connection.BeginTransaction())
    {
        var command = new NpgsqlCommand("commit;", connection);
        command.ExecuteNonQuery();

        var command2 = new NpgsqlCommand("INSERT INTO foo VALUES (2);", connection);
        command2.ExecuteNonQuery();
    }
}
```

**Comment by MaceWindu** [comment]
Actually it is more easy. You don't need second query. Difference in those two samples is that in first one you call `NpgsqlTransaction.Dispose` which checks wether transaction completed. In seconds sample we call `NpgsqlTransaction.Rollback` because transaction wasn't commited using `DataConnectionTransaction.Commit`

**Comment by Shane32** [comment]
> @linq2db guys, what do you think about it? should we stop tracking transaction state in our wrappers and just call Dispose? I will create test PR to check how it affects tests...

Makes sense to me.  I guess it depends on the level of support within all the providers.  Regardless, my general rule of thumb for me is that `Dispose` should not throw exceptions, or else `using` can mask inner exceptions and prevent proper disposal of other objects within a finalizer.  So an alternative design would be to discard exceptions within `Dispose`

**Comment by viceroypenguin** [comment]
> @linq2db guys, what do you think about it? should we stop tracking transaction state in our wrappers and just call Dispose? I will create test PR to check how it affects tests...

Makes sense to me too. Providers can use dispose to decide whether to rollback or not.
