### ISSUE TITLE
Is there a way to prevent custom function to add TypeName as the last argument?

### ISSUE THREAD

**Issue by MaxLevs** [linq2db/linq2db#3879]
I've created custom function for PostgreSql

```cs
    [CLSCompliant(false)]
    [Sql.Function("Coalesce", InlineParameters = true, ServerSideOnly = true)]
    public static T Coalesce<T>(T first, T second)
    {
        throw new InvalidOperationException("Coalesce is server-only function");
    }
```

And it generates this sql

```sql
select
	Coalesce(t1.id, t2.id, uuid),
	Coalesce(t1.tc, t2.tc, TimeStamp)
from table1 t1
    full join table2 t2
        on t1.tc = t2.tc and t1.id = t2.id
;
```

As you can see there are `uuid` and `TimeStamp` as third arguments of `Coalesce`. 
Postgre returns `ERROR: column "uuid" does not exist`

How can I fix it? Any ideas?

**Comment by sdanyliv** [comment]
Sure, there is `ArgIndices` property in `Sql.FunctionAttribute`.
Anyway `Coalesce` is generated by `linq2db` automatically when you use `??` operator. What is the reason to implement new one?

**Comment by MaxLevs** [comment]
> Sure, there is `ArgIndices` property in `Sql.FunctionAttribute`. Anyway `Coalesce` is generated by `linq2db` automatically when you use `??` operator. What is the reason to implement new one?

I have 2 tables with columns `tc` and `some_id`. They are join keys and in POCO's have `DateTime` and `Guid` types (struct). I must return this fields after join and only way I found is `Coalesce`.

I know `??` operator converts to `Coalesce` but If I wanna use `??` operator I should use nullable types (`DataTime?`, `Guid?`) but then `FULL JOIN` throws exceptions.
'Cause `from table1 t1 full join table2 t2 on (t1.tc = t2.tc OR t1.tc is NULL AND t2.tc is NULL) AND (t1.some_id = t2.some_id OR t1.some_id is NULL AND t2.some_id is NULL)`.

**Comment by sdanyliv** [comment]
Well, then it is a bug. But you can suppres such condition generation by global setting  `LinqToDB.Common.Compilation.Linq.CompareNullsAsValues = false`

**Comment by MaxLevs** [comment]
> there is `ArgIndices`

I don't exactly understand how 'ArgIndices' argument can help.

I've tried this way but result sql is still the same.

```cs
    [CLSCompliant(false)]
    [Sql.Function("Coalesce", InlineParameters = true, ServerSideOnly = true, ArgIndices=new[]{1, 2})]
    public static T Coalesce<T>(T first, T second)
    {
        throw new InvalidOperationException("Coalesce is server-only function");
    }
```

**Comment by MaxLevs** [comment]
> by global setting

Can I do this for current DataConnection or specific query?

**Comment by sdanyliv** [comment]
Not yet, we plan to do that in v5.0

**Comment by MaxLevs** [comment]
Okay. I found it. There is `IgnoreGenericParameters` property in `Sql.FunctionAttribute`.
It is exactly what I wanted.
