### ISSUE TITLE
Insert interface fails

### ISSUE THREAD

**Issue by JCKodel** [linq2db/linq2db#388]
I have a generic code that returns an interface (the entity class inherits the same interface).
An instance is constructed through Activator.CreateInstance().
db.Insert() fails because it can't find the correct concrete class (it assumes the table name is the name of the interface, minus the initial i)

As a workaround, I'm passing the result of the following code to get the table name:

```
private static ConcurrentDictionary<Type, string> _tableNames = new ConcurrentDictionary<Type, string>();

internal string GetTableName(Type type)
{
    string tableName;

    if(_tableNames.TryGetValue(type, out tableName))
    {
        return tableName;
    }

    var tableAttribute = (TableAttribute)type.GetCustomAttributes(typeof(TableAttribute), true)[0];

    _tableNames[type] = tableAttribute.Name;

    return tableAttribute.Name;
}
```

**Comment by jogibear9988** [comment]
@ili: this seemsnot alinq2db error? seem an usage error, or?

**Comment by ili** [comment]
`TableAttribute` applied to interface should work...
But to he honest we need an example, that causes error

**Comment by sdanyliv** [comment]
@JCKodel, any updates here?

**Comment by MeuCronogramaCapilar** [comment]
Honestly, I don't even remember opening this issue =\
Guess you could close it.

**Comment by sdanyliv** [comment]
Closing for now. Will reopen if needed.
