### ISSUE TITLE
broken update linq2db.AspNet from 4.3.0 to 4.4.0 for net6

### ISSUE THREAD

**Issue by KANekT** [linq2db/linq2db#3883]
### Describe your issue

after update from 4.3.0 to 4.4.0 and restore pckges

```
Error	NU1605	Detected package downgrade: Microsoft.Extensions.DependencyInjection from 7.0.0 to 6.0.1. Reference the package directly from the project to select a different version. 
 Intra.NotificationsService -> Intra.Core.Initializing -> linq2db.AspNet 4.4.0 -> Microsoft.Extensions.DependencyInjection (>= 7.0.0) 
 Intra.NotificationsService -> Microsoft.Extensions.DependencyInjection (>= 6.0.1)	Intra.NotificationsService	D:\DaOffice\core\Intra.NotificationsService\Intra.NotificationsService.csproj	1	

### Environment details

`Linq To DB` version: 4.4.0

Operating system: Windows 10

.NET Version: 6

**Comment by MaceWindu** [comment]
why not update reference to  Microsoft.Extensions.DependencyInjection to 7.0.0?

**Comment by KANekT** [comment]
@MaceWindu 

I don't understand why updating in a minor version should force updating dependent libraries in major versions ;)

я не понимаю почему обновление в минорной версии должно заставлять обновлять зависимимые  библиотеки в мажорных версиях ;)

**Comment by MaceWindu** [comment]
We will take it into account for future releases. For current one we will not fix it as next release is major one anyway...

**Comment by MaceWindu** [comment]
#3953
