### ISSUE TITLE
Oracle bulk copy and batch statements?

### ISSUE THREAD

**Issue by georgiuk** [linq2db/linq2db#3885]
### Describe your issue

Hi, does Oracle bulk copy support transactions?
Also instead of using bulkcopy is there a way I can batch multiple statements (inserts and updates) together to minimize the database roundtrips using linq2db for oracle?

**Comment by MaceWindu** [comment]
> Hi, does Oracle bulk copy support transactions?

yes

> Also instead of using bulkcopy is there a way I can batch multiple statements (inserts and updates) together to minimize the database roundtrips using linq2db for oracle?

Nope, only if you already have SQL script to send to server

**Comment by jods4** [comment]
> Hi, does Oracle bulk copy support transactions?

Native Oracle BulkCopy does _not_ support transactions. This is a limitation of Oracle itself.
It is one reason why the native strategy is not the default, as this can be surprising and unexpected (and BTW, the native Oracle bulk copy is not that performant anyway).
If you need transactional bulk copy, you need to use an alternative linq2db bulk copy strategy (array-parameters are probably best).

> Also instead of using bulkcopy is there a way I can batch multiple statements (inserts and updates) together to minimize the database roundtrips using linq2db for oracle?

There are ways but they're not exposed by linq2db as general-purpose API:
- To perform the same statement on many different parameters, the most efficient way is to use array parameters. 
- You can also batch several statements in one BEGIN/END PL/SQL block.

Both are exposed by linq2db as bulk insert strategies, but not for other statements (e.g. update or delete).

**Comment by georgiuk** [comment]
Thanx a lot for your answers:

> > Hi, does Oracle bulk copy support transactions?
> 
> Native Oracle BulkCopy does _not_ support transactions. This is a limitation of Oracle itself. It is one reason why the native strategy is not the default, as this can be surprising and unexpected (and BTW, the native Oracle bulk copy is not that performant anyway).

This is what I had found in the past searching the docs. But now in Oracle docs they say that local transactions are supported. 
https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/featBulkCopy.html

![image](https://user-images.githubusercontent.com/1830368/208886833-aa6ecbb8-4d2c-4fbe-89ba-6daed163f5b6.png)

Is this true? I haven't tested. But if you have measured the performance maybe I will stick with MultipleRows strategy. I think it is very fast also.

> If you need transactional bulk copy, you need to use an alternative linq2db bulk copy strategy (array-parameters are probably best).

So I use the below settings for bulk copy and the options and surround the bulk copy in an explicit transaction:
```
OracleTools.UseAlternativeBulkCopy = AlternativeBulkCopy.InsertInto; // anything else caused some errors

...

var options = new LinqToDB.Data.BulkCopyOptions()
{
     BulkCopyType = BulkCopyType.MultipleRows,
     UseInternalTransaction = false
};

// start transaction
...
// execute bulk copy/copies with above options
...
// commit transaction
...
```

Is the above the correct way to do it?
Is Linq2Db MultipleRows and RowByRow custom implementations for bulk insert completely independent from the native one?

> > Also instead of using bulkcopy is there a way I can batch multiple statements (inserts and updates) together to minimize the database roundtrips using linq2db for oracle?
> 
> There are ways but they're not exposed by linq2db as general-purpose API:
> 
> * To perform the same statement on many different parameters, the most efficient way is to use array parameters.
> * You can also batch several statements in one BEGIN/END PL/SQL block.
> 
> Both are exposed by linq2db as bulk insert strategies, but not for other statements (e.g. update or delete).

Do you refer to MultipleRows and RowByRow?
I think batching multiple mixed statements (insert, update, delete) would be also useful, even if the API is more primitive and the batch size could be managed by the code. Wouldn't be?

Something else, when I initially tested Linq2Db bulk copy I got some errors about unusable index when i terminated the app abnormally during a bulk copy. Probably I was using the Native/Oracle strategy. Is this possible to happen using MultipleRows and RowbyRow?  You can find some info here. 
https://dba.stackexchange.com/questions/7287/what-specifically-does-oraclebulkcopy-do-and-how-can-i-optimize-its-performance

**Comment by jods4** [comment]
> This is what I had found in the past searching the docs. But now in Oracle docs they say that local transactions are supported.

Interesting! Unfortunately I'm stuck with Oracle 19c for now, so I have not performed bulk copy tests with Oracle 21.
You can test it for yourself: when I open a transaction, perform some bulk inserts, then rollback, on Oracle 19 I get a very specific error message indicating that rollback is not possible.

Let me know if it works on 21c, that would be good news.

> Is the above the correct way to do it?

Yes. There are multiple ways but IMHO most efficient is 
```csharp
OracleTools.UseAlternativeBulkCopy = AlternativeBulkCopy.InsertInto;
OracleTools.DefaultBulkCopyType = BulkCopyType.MultipleRows;     
```
This will use a single `INSERT INTO` statement and bind arrays of values to its parameters (whose size you can tweak).
Using array parameters is an Oracle-specific thing.

> I think batching multiple mixed statements (insert, update, delete) would be also useful, even if the API is more primitive and the batch size could be managed by the code.

Yes, it is an interesting feature but there's nothing like that in linq2db for now.

There is a brand new `DbBatch` api in ADO.NET. I believe Postgre and MySQL already have implemented it, SQL Server is on the way. (Oracle will be late to the party, as always.)
I'd say if linq2db adds support for multiple statements, it'd make sense to leverage this.

> Something else, when I initially tested Linq2Db bulk copy I got some errors about unusable index when i terminated the app abnormally during a bulk copy.

Can't say I'm surprised. Oracle is ridden with bugs and limitations. Given native bulk copy is not transactional, I have no idea what happens to indexes if there's a failure in the middle of the operation.
