### ISSUE TITLE
Not able map joined entities into main model

### ISSUE THREAD

**Issue by Insanenotfromthisworld** [linq2db/linq2db#3890]
### Linq2 DB not mapped child entities on custom dto entities

I not find in documentation how do it, but I want auto map from my sql query with join entities this child entities to list, but have only mapped main entity like in plain sql use.

#### Note: I not use assotions for it becouse in my case I have one generic field for many other entities.

```c#
    public class StoreVm
    {
        public StoreVm()
        {
            Documents = new List<DocumentVm>();
        }
        public long CardId { get; set; }
        public string Title { get; set; }
        public StoreType Type { get; set; }
        public long Id { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public List<DocumentVm> Documents { get; set; }
    }
    
    public class DocumentVm
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    }
    
    var sqlQuery = new StringBuilder($"SELECT \"Store\".\"CardFK\" AS \"CardId\", \"Store\".\"CreatedOn\", \"Store\".\"Title\", \"Store\".\"Type\", \"Store\".\"DeletedOn\", \"Store\".\"Id\",\r\n\t\"Document\".\"Id\", \"Document\".\"Name\", \"Document\".\"Path\" FROM public.\"Store\" JOIN public.\"Document\" ON \"Store\".\"Id\" = \"Document\".\"RecordId\" WHERE \"Document\".\"RecordType\" = 1 AND \"Store\".\"CardFK\" = 35");
    
    var resQuery = DbConnection.FromSql<StoreVm>(sqlQuery.ToString()).ToArray(); //not mapped documents vm
    
    
```

### Environment details

`Linq To DB` version: 4.3.0

Database (with version): PostrgeSQL 14

Operating system: Windows

.NET (Core): 6

**Comment by sdanyliv** [comment]
There is no collection properties mapping for raw SQL. But you do not need associations to make LINQ query which do the same.
```cs
var query =
    from s in DbConnection.GetTable<Store>()
    where s.CardFk == 35
    select new StoreVm
    {
        CardId = s.CardFk,
        Title = s.Title,
        Type = s.Type
        Id = s.Id,
        CreatedOn = s.CreatedOn
        Documents = DbConnection.GetTable<Document>()
            .Where(d => d.RecordId == s.Id)
            .Select(d => new DocumentVm
            {
                Id = d.Id,
                Name = d.Name,
                Path = d.Path
            })
            .ToList()
    };

var result = query.ToArray(); 
```

**Comment by Insanenotfromthisworld** [comment]
> collection properties mapping for raw SQL

@sdanyliv so thanks for LINQ but can you provide collection properties mapping example? Dont find example how do it via properties mapping.

**Comment by sdanyliv** [comment]
I cannot provide _collection properties mapping example_ via Raw SQL, because it is not supported. Only via LINQ as I shown above.

**Comment by Insanenotfromthisworld** [comment]
@sdanyliv So thanks will know.

**Comment by Insanenotfromthisworld** [comment]
@sdanyliv So thanks will know. Does it planned on feature(collection properties mapping)?

**Comment by sdanyliv** [comment]
Actually not planned because `linq2db` is more LINQ oriented, but for sure it can be implemented if we design useful API for that. Check how it works in Dapper https://www.learndapper.com/relationships - my thoughts: LINQ is better.
