### ISSUE TITLE
Linq2Db EF 7 PostgreSQL timestamp behavior

### ISSUE THREAD

**Issue by datguyvladik** [linq2db/linq2db#3895]
### Discussed in https://github.com/linq2db/linq2db/discussions/3888

<div type='discussions-op-text'>

<sup>Originally posted by **datguyvladik** December 19, 2022</sup>
Hello,

On my project we are using EF 7 with Npgsql provider (https://www.npgsql.org/efcore/release-notes/7.0.html) and linq2db.EntityFrameworkCore 7.1.0.
 
Since release 6.0 npgsql driver store DateTime as timestamp with time zone (i know i can turn off this behavior) https://www.npgsql.org/efcore/release-notes/6.0.html?tabs=annotations

But when i try use linq2db like this

` await _context.Contents.Set(x => x.ModifiedAt, DateTime.UtcNow).UpdateAsync()`
 
 I get an error  "Cannot write DateTime with Kind=Unspecified to PostgreSQL type
'timestamp with time zone', only UTC is supported" 

Maybe I'm doing something wrong?</div>

**Comment by MaceWindu** [comment]
Need to look into it, but you can try to set this option

```cs
PostgreSQLTools.NormalizeTimestampData = false;
```

**Comment by nothrow** [comment]
Disabling `NormalizeTimestampData`. The issue is that EF is creating `DateTime` as "timestamp with time zone", whereas linq2db.EF sends DbDataType to `NormalizeTimeSTamp` as `Timestamp` (without TZ), thus normalizing incorrectly removes the kind.
