### ISSUE TITLE
Using IOC container

### ISSUE THREAD

**Issue by gsteinbacher** [linq2db/linq2db#390]
In all your examples you are creating an instance of the DataConnection class with a `using` statement. 

``` csharp
public static List<Product> All()
{
 using (var db = new DbNorthwind())
  {
     var query = from p in db.Product
                where p.ProductID > 25
                orderby p.Name descending
                select p;
      return query.ToList();
  }
}
```

I would like to add the DataConnection as a parameter to the method so that I can use an IOC container to pass in the DataConnection class.

``` csharp
public List<Product> All(DataConnection context)
// or possibly even ... public List<Product> All(IDataContext context)
{
     var query = from p in context.Product
                where p.ProductID > 25
                orderby p.Name descending
                select p;
      return query.ToList();
}
```

Is this possible and, if so, any suggestions on how to do it?  Would the syntax vary based on the IOC container I am using?  I would like to use it with an ASP.Net Core R2 assembly.

**BTW:  I just love Linq2Db.  So simple to use!**

**Comment by JTrotta** [comment]
Yes, I agree with gsteinbacher. What is the best practice to use linq2db with an IOC container (like tinyioc)?

**Comment by alexkuznetsov** [comment]
hi @gsteinbacher, i work with autofac and this is how i do it:
I have a service class:

```csharp
public class SomeServiceImpl : ISomeService
{
	readonly IDbContextFactory _dbFactory;
	
	public SomeServiceImpl(IDbContextFactory db)
	{
		_dbFactory = db;
	}
	
	...
	
	public SomeServiceView[] GetAllList()
	{
		using (var db = _dbFactory.Create())
		{
            return db.GetSomeServiceViews().ToArray();
		}
	}
	
	...
}
```
Autofac module with component registration:
```csharp
public class RegisterApplicationIoC : Module
{
	protected override void Load(ContainerBuilder builder)
	{
	    ...
		builder.RegisterType<DbContextFactory>()
		   .As<IDbContextFactory>()
		   .WithParameter("connectionString", "Name=someDbContext")
		   .InstancePerLifetimeScope();

		builder.RegisterType<SomeServiceImpl>()
			.As<ISomeService>()
			.InstancePerLifetimeScope();
		...
	}
}
```
And, DbContextFactory:

```csharp
public class DbContextFactory : IDbContextFactory
{
	readonly string _connString;

	public DbContextFactory(string connectionString)
	{
		_connString = connectionString;
	}

	public IDbContext Create()
	{
		// DefaultDbContext is DbContext from EntityFramework
		return new DefaultDbContext(_connString);
	}
}
```

All my services resolves from IoC Container, so this works perfectly.

**Comment by jogibear9988** [comment]
@ili :this semms to be answerd, close?

**Comment by ili** [comment]
Yes i think.
One point: `DataConnection` or `DataContext` **should not be injected**, the way is to inject **factory** (as in sample by @alexkuznetsov) 

ADO .Net Connections (`DataConnection` is only wrapper on `IDbConnection`) are not thread safe and should not be cached.
