### ISSUE TITLE
Error in sql generated for Oracle

### ISSUE THREAD

**Issue by tymokhin** [linq2db/linq2db#391]
Hi,
I try to use Linq2DB for Oracle Database, and wrote complex query
like this

 res = (from mes in dc.Measurment
           let l = (from l in dc.Link_Object_Channel
                     where l.Object == obj.ID && l.Channel == channel.ID
                     select l.ID)
            let m = (from p in dc.Pnt
                    where l.Contains(p.ID)
                    group p by p.Measurment into m
                    select m.Key)
           where m.Contains(mes.ID)
            select mes);

It generate SQL like:

--  Oracle.Native Oracle
DECLARE @ID1 Decimal(1,0)
SET     @ID1 = 1
DECLARE @ID2 Decimal(3,0)
SET     @ID2 = 310

SELECT
    t1.ID
FROM
    MEASURMENT t1
WHERE
    EXISTS(
        SELECT
            *
        FROM
            PNT t2
        WHERE
            (EXISTS(
                SELECT
                    *
                FROM
                    LINK_OBJECT_CHANNEL t3
                WHERE
                    t3.OBJECT = :ID1 AND t3.CHANNEL = :ID2 AND t3.ID = t2.ID
            )) AND
            t2.MEASURMENT = t1.ID
        GROUP BY
            t2.MEASURMENT
    )

But Oracle doesn`t support command like 
DECLARE @ID1 Decimal(1,0)
SET     @ID1 = 1

and query executed with error

overwise Oracle support expression like 
VARIABLE ID1 1;

And generated query correctly executed on Oracle if made changes of DECLARE/SET to VARIABLE

How to fix this problem for using Linq2DB?

Thanks, Aleksander

**Comment by tymokhin** [comment]
I fix it. It was my fault.
Query is correct. Without DECLARE and SET.
Its apear only in LastQuery string.

Error was in my class in wich converts query results

Excuse me. :)

**Comment by jogibear9988** [comment]
Can be closed?

**Comment by tymokhin** [comment]
Yes.
