### ISSUE TITLE
[Question] Which version of ODP Oracle provider is linq2db using and help with UDT types?

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#3911]
### Describe your issue
Hi, I would like to know if the oracle provider for managed access supports UDT types. I know that ODP.NET Managed for net core from version 3.21.3 is supporting UDT types. But would like to know if I can use this feature with a command parameter used in linq2db.
Parameters from oracle odp provider has a property called UdtTypeName  to define the udt type. I cannot find it for linq2db.

Could you please help me to understand how use this feature if is available?

Additional question:
Is possible to create a connection with ODP.net oracle provider and then pass that connection to linq2db in order to work under the same session directly with the odp.net provider?

Just looking for some options.

Thanks

**Comment by MaceWindu** [comment]
> Is possible to create a connection with ODP.net oracle provider and then pass that connection to linq2db in order to work under the same session directly with the odp.net provider?

yes, you can pass existing connection or connection factory method to `DataConnection`/`DataContext`

**Comment by gpgpublickey** [comment]
Even if ODP.NET 21.3 version supports UDT types, it doesn't support the PLSQL RECORD type yet so in case of associative arrays (table valued parameters) using PLSQL RECORD (multidimensional array) is not possible to retrieve or send data to a stored procedure, function, etc


Any ideas regarding strategies to cast or convert plsql records to udt custom types?

**Comment by gpgpublickey** [comment]
Just adding here a link related to the ODP.NET issue for request support for the RECORD PLSQL type to be implemented by the ODP.NET team https://github.com/oracle/dotnet-db-samples/issues/275
Additionally I put my discoveries to apply a workaround to this requirement related to associative arrays and record plsql types in input and output parameters

**Comment by gpgpublickey** [comment]
Looks like most of my questions are already solve so closing my issue
