### ISSUE TITLE
Drop .NET Framework 4.5/4.6.1 support

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3937]
bump lowest supported version to currently supported 4.6.2

Cleanup task for v6

**Comment by jods4** [comment]
Happy to see this one, it brings us up to .net standard 2.0! 🍾
Working on recent features like the C# nullables, I felt like 4.5 and 4.6.0 were getting more and more of a hindrance.

**Comment by jods4** [comment]
I didn't mention it in #3919 but now that we can target .net standard 2.0, maybe stuff like ZString is an option?
https://github.com/Cysharp/ZString

As we're doing a whole lot of string building everywhere, it has potential to improve perf.

**Comment by igor-tkachev** [comment]
What's wrong with 4.5?

**Comment by viceroypenguin** [comment]
* only been EOL for 7 years... (4.5.2 was supported until last year, previous versions EOL'd in Jan-16)
* Not supported for build in VS19 or VS22 (have to _find_ and manually dl the SDK)
* Very few dependencies still support pre NS2.0, making it harder to continue db support
* missing lots of useful APIs (AsyncLocal, Attribute APIs, StringComparer.InvariantCulture, ValueTuple(!!), several key nullable APIs, etc.)
* Outdated JIT/GC
