### ISSUE TITLE
Oracle 10g bulk insert failure on a large string

### ISSUE THREAD

**Issue by Lexey** [linq2db/linq2db#394]
I have a column like this in the table class definition:
[Column(DbType = "nclob"), NotNull]
public string DocumentRus { get; set; }

If it is assgned a value with the Length > 4000 then an attemt to bulk insert the object under a transaction will fail with an error message telling that the string is too long (this is a variant of this problem: http://stackoverflow.com/questions/13945710/error-ora-01704-string-literal-too-long). The obvious workaround is to use the normal .Insert method which is significantly slower.
Is there other possible solutions?

BTW, Is it possible to add CLOB/NCLOB types support for string columns without explicit length set (at this moment they are mapped to varchar2(255) which is completely inappropriate).

**Comment by Lexey** [comment]
OracleTools.UseAlternativeBulkCopy = true;
Looks like a way to go. Unfortunately the implementation is broken.

Here is the partial fix:
https://github.com/linq2db/linq2db/pull/400/files
Unfortunately, it does not solve all problems. :(

The whole story:
http://rsdn.ru/forum/prj.rfd/6504869.flat

**Comment by Lexey** [comment]
Looks like that after applying of both https://github.com/linq2db/linq2db/pull/400/files and https://github.com/linq2db/linq2db/pull/403 and cleanup of some explicit column type declarations alternative bulk copy have started working as expected.
So, now I just wonder when it will be available in the release version. :)

**Comment by ili** [comment]
fixed :)
