### ISSUE TITLE
Fix System.Data.Linq.Binary performance

### ISSUE THREAD

**Issue by guillaume86** [linq2db/linq2db#3943]
While benchmarking linq2db on the Northwind sample database vs Linq2SQL (a netcore port with some little fixes), I got disappointing results on some tables, and after investigation, I found the System.Data.Linq.Binary was the issue:

![image](https://user-images.githubusercontent.com/441850/215363568-7a8966e5-0d36-49e6-be32-c4e39457966b.png)

The Binary constructor eagearly computes the hash: 
https://github.com/linq2db/linq2db/blob/17968920816a5e41069f8b4432a9f79ae608017c/Source/LinqToDB/Compatibility/System/Data/Linq/Binary.cs#L28
which is just wasted cycles if you don't end up using it. The class will compute the hash lazily when needed so it can safely be removed from the constructor if I'm not mistaken.

**Comment by MaceWindu** [comment]
Why do you need `Binary` type?

**Comment by guillaume86** [comment]
I'm migrating a codebase from Linq2SQL, I will use the same entities for
both linq2sql and linq2db for a while.

Le lun. 30 janv. 2023 à 11:06, MaceWindu ***@***.***> a
écrit :

**Comment by MaceWindu** [comment]
PR is welcome. Should be easy fix. BTW, it copies `netfx` behavior, but of course we can improve it

**Comment by guillaume86** [comment]
Thanks, will do. Yes I noticed it was original behavior, it was the netcore port I used as a baseline (https://github.com/mindbox-moscow/data-linq/blob/main/Mindbox.Data.Linq/Binary.cs) that had fixed it, probably because they noticed the same thing.
