### ISSUE TITLE
InsertOrUpdate do only inserts new values but missing WHEN MATCHED

### ISSUE THREAD

**Issue by croban** [linq2db/linq2db#3949]
Executing InsertOrUpdateAsync on ITable<T> produce this query where WHEN MATCHED missing

```
MERGE INTO [Something] [t1]
USING (SELECT @Id AS [Id], @Type_1 AS [Type]) [s] ON
(
        [t1].[Id] = [s].[Id] AND
        [t1].[Type] = [s].[Type]
)
WHEN NOT MATCHED THEN
        INSERT
        (
                [Value],
                [Type],
                [Id]
        )
        VALUES
        (
                @Value_1,
                @Type_1,
                @Id
        );
``` 

Version: 4.4.0
Server: MSSQL

**Comment by MaceWindu** [comment]
Could you add more details what query you expected? linq2db needs primary key defined to generate match condition

**Comment by croban** [comment]
Sorry, my fault !!!
I have not set update expression, was NULL

`_dataProvider.Something.InsertOrUpdateAsync( ()=> inserted, null, cts)`
must be 
`_dataProvider.Something.InsertOrUpdateAsync( ()=> inserted, (f) => updated)`
