### ISSUE TITLE
Error in generated sql code

### ISSUE THREAD

**Issue by rechkalov** [linq2db/linq2db#395]
Hi! I've found case when generating wrong query.
This happens when in union clause first select has multiple columns with zero constant values (following selects in union may or may not fill this columns).
If I try to group by this union - only first of this columns will be represented.

Example for Northwind db - I try summarize Freights by countries by shipping method:

``` C#
var first = db.Order.Where(x => x.ShipVia == 1).Select(x => new {x.ShipCountry, Via1 = x.Freight, Via2 = 0M, Via3 = 0M});
var second = db.Order.Where(x => x.ShipVia == 2).Select(x => new {x.ShipCountry, Via1 = 0M, Via2 = x.Freight, Via3 = 0M});
var third = db.Order.Where(x => x.ShipVia == 3).Select(x => new {x.ShipCountry, Via1 = 0M, Via2 = 0M, Via3 = x.Freight});

var allData = first.Union(second).Union(third)
    .GroupBy(x => x.ShipCountry)
    .Select(x => new
    {
        ShipCountry = x.Key,
        Via1 = x.Select(y => y.Via1).Sum(),
        Via2 = x.Select(y => y.Via2).Sum(),
        Via3 = x.Select(y => y.Via3).Sum(),
    });

var data = allData.First();

// ok
Assert.That(data.Via1, Is.EqualTo(first.Where(x => x.ShipCountry == data.ShipCountry).Sum(x => x.Via1)), "first aggregation sum mismatch");

// ok
Assert.That(data.Via2, Is.EqualTo(second.Where(x => x.ShipCountry == data.ShipCountry).Sum(x => x.Via2)), "second aggregation sum mismatch");

// asserts
Assert.That(data.Via3, Is.EqualTo(third.Where(x => x.ShipCountry == data.ShipCountry).Sum(x => x.Via3)), "third aggregation sum mismatch");

```

generates following query:

``` SQL
SELECT TOP (1)
    [t4].[ShipCountry] as [ShipCountry1],
    Sum([t4].[Freight]) as [c1],
    Sum([t4].[c2]) as [c3]
FROM
    (
        SELECT
            [t1].[ShipCountry],
            [t1].[Freight],
            0 as [c2],
            0 as [c4]
        FROM
            [Orders] [t1]
        WHERE
            [t1].[ShipVia] = 1
        UNION
        SELECT
            [t2].[ShipCountry],
            0 as [Freight],
            [t2].[Freight] as [c2],
            0 as [c4]
        FROM
            [Orders] [t2]
        WHERE
            [t2].[ShipVia] = 2
        UNION
        SELECT
            [t3].[ShipCountry],
            0 as [Freight],
            0 as [c2],
            [t3].[Freight] as [c4]
        FROM
            [Orders] [t3]
        WHERE
            [t3].[ShipVia] = 3
    ) [t4]
GROUP BY
    [t4].[ShipCountry]
```

but expected something like

``` SQL
SELECT TOP (1)
    [t4].[ShipCountry] as [ShipCountry1],
    Sum([t4].[Freight]) as [c1],
    Sum([t4].[c2]) as [c3],
    Sum([t4].[c4]) as [c5]
FROM
    ...
```

**Comment by sdanyliv** [comment]
Try write aggrigations in the following way

Via1 = x.Sum(y => y.Via1)

**Comment by rechkalov** [comment]
Tryed, no difference. 

I've checked source code - looks like when there is "union", then linq2db use select context from only first part. And in this case in first part we have two constant zeros. Engine dont differ them (at some moment they are compared and get Equals = true) and use only first. If I use different constans ("0" for Via2 and "1" for Via3) - sql generated corectly (of cource, I can do this only for test purposes). If I use different aggregating function ("Sum" for Via2 and "Min" for Via3) sql generated corectly too.

Finally, I rewrited my query in another way, it has terrible sql representation, but acceptable performance, so problem is not too severe.

**Comment by jogibear9988** [comment]
@ili: maybe we can tag all issues wich generate wrong sql, they are critical for me.

**Comment by sdanyliv** [comment]
@ili, can you check this again, maybe problem already solved?

**Comment by jogibear9988** [comment]
we have a pull req. with a test: https://github.com/linq2db/linq2db/pull/396

**Comment by ili** [comment]
Still fails, fix needed
