### ISSUE TITLE
[V5]Lower dependency versions for microsoft abstraction libs

### ISSUE THREAD

**Issue by nsarris** [linq2db/linq2db#3953]
Linq2db uses DependencyInjection and Logging abstractions from the MS extensions namespace. It is generally not the best practive to aggresively upgrade those packages in library projects as they are pretty much backwards compatible back to v1 and might create conflicts to consumer projects. Linq2db only uses IServiceCollection and ILoggerFactory / ILogger , you can stay to a very early version of abstractions for both or at least stick to v6.

**Comment by MaceWindu** [comment]
linq2db itself don't use them, but it is referenced by `linq2db.aspnet` project.

As this issue was rised second time in last couple of months, I think we can do it in v5.
