### ISSUE TITLE
FluentMappingBuilder 

### ISSUE THREAD

**Issue by 273168121** [linq2db/linq2db#3956]
In the new version, I don't think it is a good solution to put FluentMappingBuilder in the static method. Although the performance problem is improved, if you want to encapsulate the dataconnection, you want to use FluentMappingBuilder to separate the static and the instance. For example, in  AbpVnext  such as  dataconnection  like efcore dbcontext , just rewrite the configuration of entity fields and database table names, then these methods are all in static methods and there is no way to rewrite them
the flowing code is in 5.0 preview1.  

```cs
        public AbpLinq2dbDbContext(DataOptions<TDbContext> options,IAbpLazyServiceProvider lazyServiceProvider) : base(options.Options)
    {
        this.LazyServiceProvider = lazyServiceProvider;
        var mappingSchema = new MappingSchema();
        var fluentMappingBuilder = mappingSchema.GetFluentMappingBuilder(); 
         var entityTypes= DbContextHelper.GetEntityTypes(typeof(TDbContext));

       //Configure basic data columns such as id and createtime for each entity and global filter eg softdelelete flag
        foreach (var entityType in entityTypes)
        {
            ConfigureBasePropertiesMethodInfo
                .MakeGenericMethod(entityType)
                .Invoke(this, new object[] { fluentMappingBuilder });
        }
         
        this.BuildMappingSchema(fluentMappingBuilder); 
        this.AddMappingSchema(mappingSchema); 

    }
//override it and  configure field and tablename here
 protected virtual  void BuildMappingSchema(FluentMappingBuilder fluentMappingBuilder)
        {
         

        }


public class DemoLinq2dbContext: AbpLinq2dbDbContext<DemoLinq2dbContext>
{

    public ITable<TbTest> TbTests => this.GetTable<TbTest>(); 

    protected override void BuildMappingSchema(FluentMappingBuilder mappingBuilder)
    {
       
        mappingBuilder.ConfigureTbTest(); 
    }

    public DemoLinq2dbContext(DataOptions<DemoLinq2dbContext> options, IAbpLazyServiceProvider lazyServiceProvider) : base(options, lazyServiceProvider)
    {
    }
}
```

**Comment by MaceWindu** [comment]
Not sure I understand your problem. 

`GetFluentMappingBuilder` method on context was just a shortcut to
```cs
context.MappingSchema.GetFluentMappingBuilder()
```

And I don't understand why you need to configure same mappings for each instance of context.

**Comment by 273168121** [comment]
> Not sure I understand your problem.
> 
> `GetFluentMappingBuilder` method on context was just a shortcut to
> 
> ```cs
> context.MappingSchema.GetFluentMappingBuilder()
> ```
> 
> And I don't understand why you need to configure same mappings for each instance of context.

Because I have more than one interface eg I’d  creator updator soft delete column if entity implate interface you don’t write colum config  and gloable queryfiter

**Comment by MaceWindu** [comment]
I still don't get what prevents you from continue doing that in v5? It is not something we would recommend, but I don't see how v5 changes could stop you here.

**Comment by sdanyliv** [comment]
According to Release notes. You can do the same:
```cs
public AbpLinq2dbDbContext(DataOptions<TDbContext> options,IAbpLazyServiceProvider lazyServiceProvider) : base(options.Options)
{
    this.LazyServiceProvider = lazyServiceProvider;
    var mappingSchema = new MappingSchema();
    var fluentMappingBuilder = new FluentMappingBuilder(mappingSchema); 
    var entityTypes = DbContextHelper.GetEntityTypes(typeof(TDbContext));

    //Configure basic data columns such as id and createtime for each entity and global filter eg softdelelete flag
    foreach (var entityType in entityTypes)
    {
        ConfigureBasePropertiesMethodInfo
            .MakeGenericMethod(entityType)
            .Invoke(this, new object[] { fluentMappingBuilder });
    }
        
    this.BuildMappingSchema(fluentMappingBuilder); 
    fluentMappingBuilder.Build();
    this.AddMappingSchema(mappingSchema); 
}
```
But note this approach is very ieneffective.

**Comment by 273168121** [comment]
> According to Release notes. You can do the same:
> 
> ```cs
> public AbpLinq2dbDbContext(DataOptions<TDbContext> options,IAbpLazyServiceProvider lazyServiceProvider) : base(options.Options)
> {
>     this.LazyServiceProvider = lazyServiceProvider;
>     var mappingSchema = new MappingSchema();
>     var fluentMappingBuilder = new FluentMappingBuilder(mappingSchema); 
>     var entityTypes = DbContextHelper.GetEntityTypes(typeof(TDbContext));
> 
>     //Configure basic data columns such as id and createtime for each entity and global filter eg softdelelete flag
>     foreach (var entityType in entityTypes)
>     {
>         ConfigureBasePropertiesMethodInfo
>             .MakeGenericMethod(entityType)
>             .Invoke(this, new object[] { fluentMappingBuilder });
>     }
>         
>     this.BuildMappingSchema(fluentMappingBuilder); 
>     fluentMappingBuilder.Build();
>     this.AddMappingSchema(mappingSchema); 
> }
> ```
> 
> But note this approach is very ieneffective.

thx

**Comment by 273168121** [comment]
> I still don't get what prevents you from continue doing that in v5? It is not something we would recommend, but I don't see how v5 changes could stop you here.

i got it wrong  that static method must be used
