### ISSUE TITLE
Columns in SELECT statements are reversed when entity class inherits from a base class

### ISSUE THREAD

**Issue by guillaume86** [linq2db/linq2db#3959]
I'm using the 5.0.0-preview2.

Just noticed something weird, not really a bug but it is annoying when analyzing SQL queries...

When the entity type inherits from another type, the columns are reversed in the SELECTs, here's what I mean:

```c#
    [Table(Name = "BsContact", IsColumnAttributeRequired = false)]
    public class Contact
    {
        [PrimaryKey]
        public int ContactId { get; set; }
        public string ContactCode { get; set; }
        public int? Age { get; set; }
        public DateTime? DateBirth { get; set; }
    }
```
generates this:
```SQL
SELECT
        [t1].[ContactId],
        [t1].[ContactCode],
        [t1].[Age],
        [t1].[DateBirth]
FROM
        [BsContact] [t1]
```

but this mapping:

```c#
    public class BaseType
    {

    }

    [Table(Name = "BsContact", IsColumnAttributeRequired = false)]
    public class Contact : BaseType
    {
        [PrimaryKey]
        public int ContactId { get; set; }
        public string ContactCode { get; set; }
        public int? Age { get; set; }
        public DateTime? DateBirth { get; set; }
    }
```
generates this:
```SQL
SELECT
        [t1].[DateBirth],
        [t1].[Age],
        [t1].[ContactCode],
        [t1].[ContactId]
FROM
        [BsContact] [t1]
```

Not really sure why it works with no base type, but the reverse order seems to originate from this method called by `TypeAccessor<T>`, it returns members in reverse order because it uses `AddFirst` and not `AddLast`. Is there any reason for that?

https://github.com/linq2db/linq2db/blob/0b8f1e08c173f12ab29d8d413e11f3bba3d4a476/Source/LinqToDB/Extensions/ReflectionExtensions.cs#L46

Thanks in advance

**Comment by MaceWindu** [comment]
Code added by #1336

**Comment by MaceWindu** [comment]
I suspect idea was to add base properties before derived properties, but implementation does something else.

@guillaume86 do you see this behavior in preview only?

**Comment by guillaume86** [comment]
@MaceWindu do you see any problem with just replacing AddFirst by AddLast ?

**Comment by jods4** [comment]
With `AddLast`, the hierarchy would look flipped (properties from base class would appear last).
I think this would be very similar to what we have in `members` already so we could simplify that method a bit more if we went this route.

I'd say that if that code is touched, we should review it more thoroughly, right now it looks pretty inefficient and allocatey to me (e.g. using a `LinkedList`, which allocates one node for each item, when we know the maximum collection length ahead of time...)

It would be nice to document (with a comment) why we dedupe members by name with the hashset.
`members` is the list of apparent members on the most derived class, so the only cases that I can think of where this might be useful could be members hidden with `new` (do hidden members even appear in reflection `GetMembers`, I'm not sure would need to check).

**Comment by guillaume86** [comment]
@jods4 thanks for the details.

Ok if I'm touching this I'll add unit tests to ensure ordering remains correct and consistent with or without inheritance and benchmark it against the old version for perf/memory use.

Sorry I'm not very familiar with the code base, what do you mean by "what we have in `members` already" ? 

Yes the deduping is for hidden by `new` members and is required, see: https://github.com/linq2db/linq2db/blob/0b8f1e08c173f12ab29d8d413e11f3bba3d4a476/Tests/Linq/UserTests/Issue1313Tests.cs#L81

**Comment by jods4** [comment]
@guillaume86 
> Yes the deduping is for hidden by new members and is required, see:

Thanks for doing the research! If you modify the code, it'd be nice to leave a comment to explicit that purpose.

> Sorry I'm not very familiar with the code base, what do you mean by "what we have in `members` already" ?

I was referring to the `members` local variable that contains all the public fields/properties of the type we're looking at.
My remark was meant to say that depending on the ordering we eventually land on, we don't need those sorting shenanigans and we only need to filter out members hidden by `new` from `GetMembers`.

About sorting: it might be worth noting what [MSDN says about `GetMembers` ordering](https://learn.microsoft.com/en-us/dotnet/api/system.type.getmembers?view=net-7.0) anyway:
> In .NET 6 and earlier versions, the [GetMembers](https://learn.microsoft.com/en-us/dotnet/api/system.type.getmembers?view=net-7.0) method does not return members in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which members are returned, because that order varies. However, starting with .NET 7, the ordering is deterministic based upon the metadata ordering in the assembly.
