### ISSUE TITLE
Oracle package\function call

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#397]
I'm using DataConnection.ExecuteProc method to call oracle pl\sql package\function and getting error. I can call the package from other app successfully.  We have 4 out params with array datatype in package\function.Please provide me link any help.

**Comment by mdvtj** [comment]
@sarabu07, I guess it would be easier for others to help you if you could provide more information on what you want to call (the exact signature of your package function), what you have tried (the code that is calling `DataConnection.ExecuteProc`) and what the result was (the exception you have received).

**Comment by sarabu07** [comment]
We have a oracle package with following signature

FUNCTION f_get_optional_pricing(
  n_contract_id_in            IN      CONTRACT.CONTRACT_ID%TYPE,
  st_coverage_cust_type_out       OUT   common_func.STRING_TABLE,
   st_coverage_quantity_out       OUT   common_func.STRING_TABLE,
   st_coverage_price_out          OUT   common_func.STRING_TABLE,
   st_coverage_description_out      OUT   common_func.STRING_TABLE,
  s_error_msg_out             OUT   common_func.T_ERROR_MSG  )

I'm trying to call the package with following code and getting error

var contractIdIn = DataParameter.Int32("n_contract_id_in",contractId);
                    var customerType = new DataParameter { Direction = System.Data.ParameterDirection.Output };
                    var quantity = new DataParameter { Direction = System.Data.ParameterDirection.Output };
                    var covPrice = new DataParameter { Direction = System.Data.ParameterDirection.Output };
                    var description = new DataParameter { Direction = System.Data.ParameterDirection.Output };
                    //var 
                    var optional = dbConnection.Execute("test_contract_file_functions.f_get_optional_pricing", contractIdIn, customerType, quantity, covPrice, description);

**Comment by sarabu07** [comment]
@mdvtj Can you please provide me some help?

**Comment by mdvtj** [comment]
Could you please provide the exact error message?

**Comment by sdanyliv** [comment]
@sarabu07, any updates here?

**Comment by ili** [comment]
closing for now, will reopen on feedback
