### ISSUE TITLE
Npqsql 5.0.0-rc.1 - System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3971]
### Describe your issue

For some reason some Xunit integration tests in my project fail with npgsql error (invoked by Linq2Db)
Executing the tests "all tests in file" only -  **no error** occurrs.

It crashes with this query:

![grafik](https://user-images.githubusercontent.com/66479830/218979591-9dba267c-055b-42c4-8c66-ae0f702b109d.png)

![grafik](https://user-images.githubusercontent.com/66479830/218980195-d3b73f7d-be16-4cf4-aab7-70a4ce11c77b.png)

So the query is executed but the result cannot be read.

Unfortunately I cannot provide an reproducible example since the error only occurs if `dotnet test` is used - there are hundreds of tests. All Xunit test classes running against Postgres are decorated with `[Collection("PostgresSequential")]`

```c#
await context.Aggregates
            .Where(x => x.AggregateId == aggregateId)
            .Set(x => x.LastDispatchedVersion, lastDispatchedVersion)
            .UpdateAsync();
```

### Environment details

`Linq To DB` version: 5.0.0-rc.1

Database (with version): Postgres latest

ADO.NET Provider (with version): *?* (e.g. Microsoft.Data.SqlClient 4.1.0)

Operating system: *?*

.NET Version: 6

**Comment by MaceWindu** [comment]
What makes you think it's related to linq2db? BadImageFormatException is hardly something we could cause IMO

**Comment by MaceWindu** [comment]
index exception probably comes from this line https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlDataReader.cs#L815

**Comment by MaceWindu** [comment]
https://github.com/npgsql/npgsql/issues/4778

**Comment by MaceWindu** [comment]
I would recommend to isolate issue into small reproducible case first as there is currently nothing  for us or npgsql team (if it is npgsql issue) to start with.

**Comment by HypeillingerChillinger** [comment]
Yes, sure I tried to isolate it and built up a new project that is similiar to the bigger project. But it is not reproducible in the small test project.

I also observed the issue in a test with transaction as mentioned here https://github.com/npgsql/npgsql/issues/4778#issue-1458160378

I use https://www.nuget.org/packages/dbup-postgresql#dependencies-body-tab
Version="5.0.8"

which uses  <PackageReference Include="Npgsql" Version="7.0.2" />

Is it possible that there is an interference? But as I said it is not reproducible in a small test project only in the big project using `dotnet test`

**Comment by MaceWindu** [comment]
You could try to add debugger launcher on exception (`System.Diagnostics.Debugger.Launch();` call from `try/catch` ) and inspect `NpgsqlDataReader` state around crash point

**Comment by MaceWindu** [comment]
Well, without await it shouldn't work and missing await is the reason of such error in 99.9% cases:
without await you send query to server and then without waiting for response you can try to send another query, which results in broken provider state.

I would recommend to check your code for missing awaits for queries. this could help https://www.nuget.org/packages/Lindhart.Analyser.MissingAwaitWarning/ 
If you still cannot find missing awaits - then try to catch error and attach with debugger to inspect provider state as I mentioned above

**Comment by jods4** [comment]
@HypeillingerChillinger that first example is wrong.
You are disposing the context as soon as `UpdateMeAsync` returns, but at this point `UpdateAsync` is likely to not being complete.
This is bad concurrent code.

**Comment by HypeillingerChillinger** [comment]
I see, thanks.

**Comment by HypeillingerChillinger** [comment]
@jods4 The exception should then be sth. like context already disposed or sth.  not an Npgsql Exception.

**Comment by MaceWindu** [comment]
We cannot do anything as query already passed to npgsql at that point

**Comment by HypeillingerChillinger** [comment]
Ok, the query is already in outer space. Thanks
