### ISSUE TITLE
oracle procedure error

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#398]
we have oracle procedure with following signature

getcoverages(P_CNTRCT_IDInput          IN NUMBER,
                                                  P_PRODUCT_VERSION_IDInput IN NUMBER,
                                                  p_arr                     OUT grpprod_tab)

I use below code to call the oracle procedure
 object[] output1 = null;
var output = dbConnection.ExecuteReader("getcoverages", System.Data.CommandType.StoredProcedure, System.Data.CommandBehavior.Default, new DataParameter("P_CNTRCT_IDInput", contractId),
                                                                                new DataParameter("P_PRODUCT_VERSION_IDInput", productVersionId), 
                                                                                new DataParameter("p_arr", output1) { Direction = System.Data.ParameterDirection.Output });

I'm getting below error
ORA-06550: line 1, column 7:
PLS-00201: identifier 'GETCOVERAGES' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored   

@sergey-miryanov can you check if im missing anything in code?

**Comment by sergey-miryanov** [comment]
@sarabu07 Sorry, I can't help with this.

**Comment by sarabu07** [comment]
not using procedure
