### ISSUE TITLE
Purpose of generic argument in IMetadataReader.GetAttributes<T>

### ISSUE THREAD

**Issue by nsarris** [linq2db/linq2db#3981]
Is there any puprpose in the generic attributte in IMetadataReader.GetAttributes<T> after the attriutes refactoring? Unless I missed something the framework internally only calls IMetadataReader.GetAttributes<MappingAttribute> and I don't see IMetadataReader as part of the public API. Even so it's a minor breaking change, the consumer can simply filter the results with. This would simplify the implementation of provider implementations and remove a lot of type checking.

**Comment by MaceWindu** [comment]
That's actually makes sense... We plan to release final version this week, so we should do it now or leave it as it is now..

**Comment by nsarris** [comment]
I vote for now if you could sqeeze it in.
