### ISSUE TITLE
The InsertWithOutputIntoAsync method does not work correctly

### ISSUE THREAD

**Issue by jangarach** [linq2db/linq2db#3983]
Hi, I wanted to call the InsertWithOutputIntoAsync method with the following request:

```c#
 await source.InsertWithOutputIntoAsync(
    targetTable,
    valueFromTargetTable=> valueFromTargetTable,
    otherTable,
    valueFromTargetTable=> new OtherClass
            {
                Id = valueFromTargetTable.Id, 
                Status = 1
            });
```

But I caught an exception when calling such code:

```
System.InvalidCastException : Unable to cast object of type 'LinqToDB.Linq.Table`1[OtherTable]' to type 'System.Linq.IQueryable`1[TargetTable]'
```

When I started looking at the source code, what I saw was that the method has this code `(IQueryable<TTarget>)outputTable`
link to the source:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.Insert.cs/#L300

Why do you need a type conversion? The semantics of the method allows you to call the code that I have.

**Comment by MaceWindu** [comment]
Should be easy fix. This line use wrong generic argument in cast: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.Insert.cs/#L403

**Comment by MaceWindu** [comment]
Same error for sync version
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.Insert.cs/#L361

**Comment by MaceWindu** [comment]
hmm, that's what you get when doesn't cover all API overloads with tests. COuple more places:

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.Insert.cs/#L717
and
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.Insert.cs/#L764

**Comment by jangarach** [comment]
Thanks for the quick fix, please tell me when the stable version 5.0.0 will be released, and whether we will get the package linq2db.EntityFrameworkCore with these new changes?

**Comment by MaceWindu** [comment]
v5 release scheduled for tomorrow, efcore integration probably by the end of this week/next week

**Comment by jangarach** [comment]
Thanks!
