### ISSUE TITLE
Incorrect SQL generated over 'Contains' in array having null element

### ISSUE THREAD

**Issue by ademchenko** [linq2db/linq2db#3986]
### Describe your issue

Consider the following table 
```sql
create table issue
(
    number        integer,
    number_string text
);
```
with the following data:
```sql
insert into issue(number, number_string)
VALUES (0, null), (1, 'one'), (2, 'two');
```
and with the following class generated:
```c#
[Table("issue", Schema = "public")]
	public partial class Issue
	{
		[Column("number"       )] public int?    Number       { get; set; } // integer
		[Column("number_string")] public string? NumberString { get; set; } // text
	}

```

### Steps to reproduce

Consider the following test:

```c#
        [Test]
        public async Task IssueTest()
        {
            var dataConnection = new LinqToDB.Data.DataConnection();

            var strings = new[] { null, "two" };

            var result = await dataConnection.GetTable<Issue>().Where(i => i.Number == 1 && strings.Contains(i.NumberString)).ToListAsync();

            var lastQuery = dataConnection.LastQuery;

            TestContext.WriteLine(lastQuery);

            Assert.AreEqual(0, result.Count);
        }
```

The condition over the table 'Issue' should obviously lead to a query that returns no rows. But that's not the case, the record (0, null) is actually returned. 
The bug is pretty clear, below is the SQL generated by linq2db and we can see that the necessary brackets are missed there.

```sql
SELECT
	i."number",
	i.number_string
FROM
	"public".issue i
WHERE
	i."number" = 1 AND i.number_string IN ('two') OR i.number_string IS NULL
```

### Environment details

`Linq To DB` version: *4.4.1*

Database (with version): *Postgres 14.1*

**Comment by ademchenko** [comment]
@MaceWindu , this issue is quite serious, is there a way to move it to some service pack of version 4, but not to the version 5.x, which I think is far from the release?

**Comment by MaceWindu** [comment]
5.0 release scheduled for tomorrow and I plan to look at this issue later today

**Comment by jods4** [comment]
It's a part I'm familiar with.
@MaceWindu PR #3990 for a fix.

**Comment by jods4** [comment]
Oh wait, it's not a complete fix, it introduces a different bug. :(

-> I'm gonna write a comment with what remains to be done in the PR.

**Comment by jods4** [comment]
Ok, I thought there was a bug but there is not.
It's not obvious, I'm commenting on all possible cases here: https://github.com/linq2db/linq2db/pull/3990#issuecomment-1440027041
