### ISSUE TITLE
Usage of Linq2db 5-rc with Net4.8

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3987]
I tried to upgrade to linq2db 5 preview, but my code did break.
I used Bulk Copy options, but they are not possible to use in Net4.8, cause I could not switch to a higher language version:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/364896/220527603-5fbb1e47-cc50-44e2-a622-21985adff8b4.png">

**Comment by jogibear9988** [comment]
add 

      <PropertyGroup>
         <LangVersion>9.0</LangVersion>
      </PropertyGroup>

to csproj. it works, but is not possible via visual studio UI

**Comment by MaceWindu** [comment]
Yep, this is known issue, but for all options we introduced fluent api configuration methods, so it is possible to use them for configuration if project policies doesn't allow C# version increase
