### ISSUE TITLE
Changes needed in my code to updte from 4 to 5

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3988]
I need to change the following parts so I could switch from 4 to 5.

Should/are they already documented somewhere?

**Comment by jogibear9988** [comment]
Fluent Mapping Schema:
change

     var builder = newMappingSchema.GetFluentMappingBuilder();

to

     var builder = new FluentMappingBuilder(newMappingSchema);

**Comment by jogibear9988** [comment]
Own Retry policy:

constructor form:

        public DbRetryPolicy(int maxRetryCount, TimeSpan maxRetryDelay)
            : base(maxRetryCount, maxRetryDelay)

to

        public DbRetryPolicy(int maxRetryCount, TimeSpan maxRetryDelay)
            : base(maxRetryCount, maxRetryDelay, Configuration.RetryPolicy.DefaultRandomFactor, Configuration.RetryPolicy.DefaultExponentialBase, Configuration.RetryPolicy.DefaultCoefficient)

**Comment by sdanyliv** [comment]
In release notes.

**Comment by jogibear9988** [comment]
Traceing for errors from:

            DataConnection.OnTrace = (data) => { MyOwnTraceSystem.Instance.Error("Error_DLBase", "Exception occured executing SQL: " + data.SqlText, data.Exception); };

to

       removed the code cause there is no Static "OnTrace" any more.

need to hand over the trace to the constructor of DataConnection. Code will follow.

**Comment by jogibear9988** [comment]
> In release notes.

Okay, will document mine here, maybe we miss some

**Comment by jogibear9988** [comment]
Init only cosntructors error in Net4.8 Projects:

do this change mentioned here : https://github.com/linq2db/linq2db/issues/3987

**Comment by jogibear9988** [comment]
I've a own data provider created for ingres, wich is only used for simple queries, so it's not completely implemented but worked for our usage.

changed code from:

    public class IngresDataProvider : DynamicDataProviderBase<IngresProviderAdapter>
    {
        public IngresDataProvider()
            : this("Ingres", MappingSchemaInstance)
        {
        }

        protected IngresDataProvider(string name, MappingSchema mappingSchema)
            : base(name, mappingSchema, IngresProviderAdapter.GetInstance())
        {
            SqlProviderFlags.AcceptsTakeAsParameter = false;
            SqlProviderFlags.IsSkipSupported = false;
            SqlProviderFlags.IsCountSubQuerySupported = false;
            SqlProviderFlags.IsInsertOrUpdateSupported = false;
            SqlProviderFlags.TakeHintsSupported = TakeHints.Percent;
            SqlProviderFlags.IsCrossJoinSupported = false;
            SqlProviderFlags.IsInnerJoinAsCrossSupported = false;
            SqlProviderFlags.IsDistinctOrderBySupported = false;
            SqlProviderFlags.IsDistinctSetOperationsSupported = false;
            SqlProviderFlags.IsParameterOrderDependent = true;
            SqlProviderFlags.IsUpdateFromSupported = false;
            SqlProviderFlags.DefaultMultiQueryIsolationLevel = IsolationLevel.Unspecified;

            _sqlOptimizer = new IngresSqlOptimzer(SqlProviderFlags);
        }

        public override TableOptions SupportedTableOptions => TableOptions.None;

        public override ISqlBuilder CreateSqlBuilder(MappingSchema mappingSchema)
        {
            return new IngresSqlBuilder(this, mappingSchema, GetSqlOptimizer(), SqlProviderFlags);
        }

        readonly ISqlOptimizer _sqlOptimizer;

        public override ISqlOptimizer GetSqlOptimizer()
        {
            return _sqlOptimizer;
        }

        public override ISchemaProvider GetSchemaProvider()
        {
            return null;
        }

        private static readonly MappingSchema MappingSchemaInstance = new IngresMappingSchema.ODBCMappingSchema();
    }

to 

    not yet done, will post code here

**Comment by MaceWindu** [comment]
I will create separate migration document in wiki to summarize all migration information

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db/wiki/Migration-to-v5
