### ISSUE TITLE
Oracle T4 templates missing packages and certain stored procedures

### ISSUE THREAD

**Issue by sarabu07** [linq2db/linq2db#399]
I tried to generate the metadata infor for my oracle database. The t4 template successfully generated all the tables with few procedures. It failed to generate certain stored procedures and all packages. Let me know if calling packages is supported?

**Comment by ili** [comment]
@sarabu07 can you provide sample database?

**Comment by konbur** [comment]
milestone already 1.9.0 completed, what about this issue?

**Comment by sdanyliv** [comment]
@konbur, i'm not familiar with Oracle. Can you provide more details, database scripts that reproduce problem?

**Comment by MaceWindu** [comment]
Could be metadata permissions issues like  this one https://github.com/dbeaver/dbeaver/issues/2237

**Comment by sdanyliv** [comment]
@MaceWindu, tried to generate T4 template for Oracle, and this [stored proc from WIP PR](https://github.com/linq2db/linq2db/pull/1893/files#diff-43a74f503a3dab20b9fbf68bb9808227R970) is missing:
