### ISSUE TITLE
Question: Postgres Table-Level Locks

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3995]
Is there support for table-level locks in Postgres?
 
see https://www.postgresql.org/docs/current/explicit-locking.html

I searched for `EXCLUSIVE` in the code but couldn't find relevant code for table locks

Sure, one could use `context.ExecuteAsync(...` for it but may be you have something out of the box.

**Comment by MaceWindu** [comment]
Currently we support only hints, specified directly in query. for `LOCK` statement you need to use raw sql

**Comment by HypeillingerChillinger** [comment]
Ok. Thanks for the quick response.
