### ISSUE TITLE
Update with xmin doesn't use in sql query 

### ISSUE THREAD

**Issue by twilightrus** [linq2db/linq2db#4009]
I have this code:

```
var transfer = await connection.Transfers.FirstAsync();

var results = await connection.Transfers
                .Where(x => x.xmin == transfer.xmin && transfer.RecipientAddress == "#account-1")
                .Set(x => x.Amount, 300)
                .UpdateAsync();
```

Resulting query:
```
DECLARE @Amount Numeric -- Decimal
      SET     @Amount = 300

      UPDATE
        "Transfer"
      SET
        "Amount" = :Amount
      WHERE
        1 = 0
```

xmin has value after FirstAsync(), but on update this ignored

**Comment by twilightrus** [comment]
I want to implement optimistic concurrency using xmin. Is there a way to do this out of the box?

**Comment by MaceWindu** [comment]
1. you can mark your xmin column with
```cs
[OptimisticLockProperty(VersionBehavior.Auto)]
```

and use update/delete extensions for optimistic lock https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#optimistic-lock-extensions

2. I need to see your `Transfers` mappings to understand why such filter generated.

**Comment by twilightrus** [comment]
I have more questions:

1. Is it possible to configure Optimistic Concurrency with fluent instead of an attribute?

2. UpdateOptimisticAsync() does not make it possible to set only the required fields for updating and updates everything. Can the fields be set manually?

**Comment by MaceWindu** [comment]
> Is it possible to configure Optimistic Concurrency with fluent instead of an attribute?

use `HasAttribute` fluent api method

**Comment by twilightrus** [comment]
> > Is it possible to configure Optimistic Concurrency with fluent instead of an attribute?
> 
> use `HasAttribute` fluent api method

Okay, what about setting only certain fields on UpdateOptimisticAsync?

**Comment by MaceWindu** [comment]
There is no such API currently. I could add something like `IQueryable<T> OptimisticFilter(this IQueryable<T> source, T record)` so you could combine it with regular `Update` API

**Comment by twilightrus** [comment]
> There is no such API currently. I could add something like `IQueryable<T> OptimisticFilter(this IQueryable<T> source, T record)` so you could combine it with regular `Update` API

It would be nice. Will wait!
Thanks
