### ISSUE TITLE
Dynamic Access to DB

### ISSUE THREAD

**Issue by merthsoft** [linq2db/linq2db#401]
Let's say I've got the name of a table and the columns in strings, and the data in a list. Is there an easy way to insert into a database using linq2db? Having all the same niceness at run-time, so I don't have to write the SQL queries manually.

**Comment by sdanyliv** [comment]
@merthsoft, it's not clear for me. Do you have real object types? Maybe some samples.

**Comment by merthsoft** [comment]
Yeah admittedly that wasn't very clear...
I do not have any real object types. Say something like this.

`string table = "Employees"
List<string> columns = { "ID", "Name", "Age" }
List<object[]> Data = { { "<guid>", "Merthsoft", 28 } , { "<guid>", "SOmeone Else", 57 } }`

and then I want to be able to just do

`using (var db = new DbNorthwind()) {
    foreach (var data in Data) {
        db.Insert(table, columns, data);
    }
}`

**Comment by merthsoft** [comment]
Yeah admittedly that wasn't very clear...
I do not have any real object types. Say something like this.

`string table = "Employees"

List<string> columns = { "ID", "Name", "Age" }

List<object[]> Data = { { "<guid>", "Merthsoft", 28 } , { "<guid>", "SOmeone Else", 57 } }`

and then I want to be able to just do

`using (var db = new DbNorthwind()) {

    foreach (var data in Data) {

        db.Insert(table, columns, data);

    }

}`

**Comment by sdanyliv** [comment]
For sure easiest way is generate queries ))
With linq2db you have to genereate by emitter new classes and Expressions, it is possible, but needs efforts. Without that you need to deal directly with our AST and SqlBuilder class.
If you want to insert many data, it will be better to deal with BulkCopy or Merge functionality.

**Comment by jogibear9988** [comment]
or use https://github.com/StefH/System.Linq.Dynamic.Core

**Comment by ili** [comment]
Closing for now, will reopen if needed
