### ISSUE TITLE
TimeSpan for sql-variant do not support converter

### ISSUE THREAD

**Issue by junsan1** [linq2db/linq2db#4025]
Tried to use custom converter for TimeSpan (standard the same - not working)

```
private class TestEntity
{
	public object Column1 { get; set; }
}

var mappingSchema = db.MappingSchema;

// set up converter to translate TimeSpan into int64.
mappingSchema.SetConverter<TimeSpan, DataParameter>(obj => new() { Value = obj.Ticks });

var table = db.GetTable<TestEntity>(); // in DB column has sql_variant data type

table.BulkCopy(new TestEntity[]
{
	new() { Column1 = TimeSpan.FromMinutes(1) },
	new() { Column1 = TimeSpan.FromHours(1) },
	new() { Column1 = TimeSpan.FromDays(1) }, /* this line not works */
});
```

And the error:

```
Unhandled exception. System.OverflowException: SqlDbType.Time overflow.  Value '1.00:00:00' is out of range.  Must be between 00:00:00.0000000 and 23:59:59.9999999.
   at Microsoft.Data.SqlClient.TdsParser.WriteTime(TimeSpan value, Byte scale, Int32 length, TdsParserStateObject stateObj)
```

`Linq To DB` version: 5.0.0

Database (with version): SQL Server 2019

**Comment by MaceWindu** [comment]
Please provide full runnable sample

**Comment by MaceWindu** [comment]
Didn't checked it, but we already provide mappings for it - specify that column DataType is DataType.Int64

**Comment by junsan1** [comment]
It is not what actually expected. Column must by sql_variant. The column can contain several data types (no TimeSpan only). Is it possible to keep sql_variant and use conversion on fly?

**Comment by junsan1** [comment]
`mappingSchema.SetConverter<object, DataParameter>(obj => new() { Value = obj is TimeSpan ts ? ts.Ticks : obj });`

this code same no works

**Comment by MaceWindu** [comment]
latest release (5.2.0) added some changes to this area, so `object` converter could work

**Comment by junsan1** [comment]
No, same error.

**Comment by MaceWindu** [comment]
Ok... Can confirm that DataParameter mapping currently doesn't work, but you can use column value converter:
```cs
class VariantConverter : ValueConverterFunc<object?, object?>
{
	public VariantConverter() : base(
				model =>
				{
					if (model is TimeSpan ts)
						return ts.Ticks;

					return model;
				},
				provider => provider,
				true)
	{
	}
}

class TestEntity
{
	[ValueConverter(ConverterType = typeof(VariantConverter))]
	public object? Column1 { get; set; }
}
```

**Comment by MaceWindu** [comment]
Fix will be in next release

**Comment by junsan1** [comment]
To make sure. Global convertors not works for all types, not TimeSpan only.
