### ISSUE TITLE
Use new DataConnectionTransaction(dc) is more faster then dc.BeginTransaction() when Using database transactions.

### ISSUE THREAD

**Issue by wxysy** [linq2db/linq2db#4032]
### Describe your issue
Hello:
When I use Linq2DB database transactions, I find that transactions is more faster when creat instance of DataConnectionTransaction by using  new DataConnectionTransaction(dc) directly instead of using dc.BeginTransaction() method.
I hope you can fix this problem.
Exception message:None
Stack trace:None

### Steps to reproduce
The main C# code is as follows.
If you need the full code, please contact me by leave a message below this issue.

```c#
tb_Show.Clear();

//1. Create connection string
string dir = @"..\..\..\..\DataSource";// A more common way is to use System.IO.Directory.GetCurrentDirectory(); // There's no "\" at the end of the string
string filename = @"MyTestDB.accdb";
string dBPath = System.IO.Path.Combine(dir, filename);
string dBPassword = "xy12341234";
var connectionString = DBConnectionString.CreatDBConnectionStringForAccess(dBPath, dBPassword);

//2. Create connection parameter instance
var options = new DataOptions().UseAccessOleDb(connectionString);// Usage 1
//var options = new DataOptions().UseAccess(connectionString);// Usage 2

//3. Create a connection and begin LINQ operations within its scope
using (var dc = new DataConnection(options))
{
    //3.0 Begin using transactions
    // Do not use "var dcT = dc.BeginTransaction();" in the tutorial
    // "var dcT = new DataConnectionTransaction(dc);" runs much faster.
    using (var dcT = new DataConnectionTransaction(dc))// <---- Here is the issue
    {
        //3.1 Begin LINQ operations (update)
        //Updates are mainly performed by "db" operation, but if you want to update all columns in the database, use "dc" operation.
        var db = dc.GetTable<Test>();

        //Similarly, as long as the relationship is set up, cascading updates will be performed automatically without additional processing.
        db.Where(p => p.统一社会信用代码PK == "12420000420139CCCC")                  
            .Set(p => p.CompanyAddress, "New address 10")
            .Update();

        //To handle optimistic locking, the update process is generally: "query first, then update", instead of directly updating like in this example.
        //Linq2Db doesn't have change tracking, so you have to manage it yourself.
        //Option 1: try--catch
        try
        { 
            dcT.Commit(); //Commit 
        }
        catch (Exception)
        { 
            dcT.Rollback(); //Rollback
        }
        //Option 2: if--else
        //bool somethingIsNotRight = false;
        //if (somethingIsNotRight)
        //{ 
        //  tr.Rollback(); 
        //}
        //else
        //{ 
        //  tr.Commit(); 
        //}
    }              
}
progress?.Report("Database transaction completed.");
```

### Environment details

`Linq To DB` version: 5.0.0

Database (with version): Office Access 2019 X64

ADO.NET Provider (with version): System.Data.OleDb 7.0.0

Operating system: Windows 11 professional

.NET Version: 6.0

**Comment by MaceWindu** [comment]
I'm not sure how `more faster` is faster is this case, but difference is that in second case you don't use transaction as there is no `BeginTransaction` call. `DataConnectionTransaction` class doesn't start transaction - it only provides wrapper to manage it's lifetime

**Comment by wxysy** [comment]
> I'm not sure how `more faster` is faster is this case, but difference is that in second case you don't use transaction as there is no `BeginTransaction` call. `DataConnectionTransaction` class doesn't start transaction - it only provides wrapper to manage it's lifetime

Thanks reply.
but I think I did't report this issue correctly.
I tried many times, I find that the slow connection always happens when the program first connected to  MS Access File.
It needs about 15-21 seconds when the first time connection, but only needs 0.001-0.01 seconds the next connection.
Could you fix the issue or tell me how to make the first connection faster?

**Comment by MaceWindu** [comment]
Access could be slow if your database hosted on network drive.

I could suggest to rewrite your sample to use OLE DB classes directly to see if issue persists. I'm 99% sure delay comes from oledb provider as there is nothing in linq2db to create such delays

**Comment by wxysy** [comment]
> Access could be slow if your database hosted on network drive.
> 
> I could suggest to rewrite your sample to use OLE DB classes directly to see if issue persists. I'm 99% sure delay comes from oledb provider as there is nothing in linq2db to create such delays

ok, I'll try it, thank you very much.
