### ISSUE TITLE
Error in generated sql parameter caching

### ISSUE THREAD

**Issue by Centurys** [linq2db/linq2db#404]
We have two tables one is referenced by other (one to many) and we need to select second table conditionally, here is linq code we tried to use:
```cs
 // allUsages is nullable enum
var allUsages = !usage.HasValue;
var see = _db.FirstTable
  .GroupJoin(_db.SecondTable.Where(v =>
    (allUsages || v.Usage == usage.GetValueOrDefault())), c => c.Id, v => v.FirstTableId,
     (c, v) => new FirstTable{ Id = c.Id, Values = v.ToList() })
  .FirstOrDefault();
```
It generates two sql calls to db, and second code is for second table. First try when "allUsages" is false is succesfull, but all the other calls generates same sql parameter value even if "allUsages" changes to true.
Generated sql:
```sql
DECLARE @allUsages Bit -- Boolean
SET     @allUsages = 0
DECLARE @p1 Int -- Int32
SET     @p1 = 0
DECLARE @p2 Int -- Int32
SET     @p2 = 5

SELECT
    [t1].[Id],
    [t1].[FirstTableId],
    [t1].[Usage] as [Usage1]
FROM
    [SecondTable] [t1]
WHERE
    (@allUsages = 1 OR [t1].[Usage] = @p1) AND [t1].[FirstTableId] = @p2
```
I know I could make some workaround and select data differently, but goal for this issue to fix this current bug and make linq2db even better :)

**Comment by MaceWindu** [comment]
Looks like already fixed. At least in v3
