### ISSUE TITLE
linq2db HasConversion doesn't work with Connection.ExecuteAsync

### ISSUE THREAD

**Issue by twilightrus** [linq2db/linq2db#4043]
I have same code:

MappingBuilder:
```
        builder.HasTableName("Sendings");
        builder.Property(x => x.Params).HasDbType("jsonb").HasConversionFunc(JsonConvert.SerializeObject, y =>
        {
            return JsonConvert.DeserializeObject<SendingParams>(y)!;
        });
```

Query:
```
var sending = await Connection.ExecuteAsync<Sending>(@"SELECT * FROM ""Sendings"" WHERE ""Params""::json->>'Comment'='test'", CancellationToken.None);
```

Exception:
```
LinqToDB.Common.LinqToDBConvertException: Cannot convert value '{"Nonce": 12, "Amount": 1000000, "Comment": "test", "GasLimit": 2142, "GasPrice": 1000000000, "ToAddress": "cosmos1xwy7k0ffpf6lzlr6zrl20cj63v3gnqret5epm2", "FromAddress": "cosmos15h0zj4lwftstl
r8gufv59setxuv9y4yt75fczn", "TransferAll": false}: System.String' to type 'Domain.Sendings.SendingParams'
 ---> System.InvalidCastException: Invalid cast from 'System.String' to Domain.Sendings.SendingParams'.

```

Conversion doesn't work. For non raw sql queries conversion works.

**Comment by igor-tkachev** [comment]
Did you call the .Build() method at the end of fluent mapping?

**Comment by twilightrus** [comment]
> Did you call the .Build() method at the end of fluent mapping?

I call the .Build(). Mapping works for standard queries. It's not working ONLY for Connection.ExecuteAsync<T>

**Comment by sdanyliv** [comment]
`ExecuteAsync` not for querying data, but `QueryAsync` does. I have checked code and yes conversion may not be applied in this case. Proper fix needed.

**Comment by twilightrus** [comment]
> `ExecuteAsync` not for querying data, but `QueryAsync` does. I have checked code and yes conversion may not be applied in this case. Proper fix needed.

My bad, ExecuteAsync really not the right way. 
QueryListAsync also doesn't works. 
But this code works fine:

```
var result = await Connection.FromSql<Sending>(@"SELECT * FROM ""Sendings"" WHERE ""Params""::json->>'Comment'='test'").ToListAsync();
```

**Comment by sdanyliv** [comment]
Yes `FromSql` uses different mapping technique, that's why it works.

**Comment by sdanyliv** [comment]
Reopening to track existing issue.
