### ISSUE TITLE
Same type different tables

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#4050]
### Describe your issue

I have a class used as  representation entity for two tables. So each of the tables have the same columns.

Please don't ask me why I do that - historic reasons I can't help it. Not my fault.

The fluent configuration does **not** have a `.HasTableName()`

In order to read the tables I can use 
```c# 
db.GetTable<GeneralCard>().TableName("InternalCard").Where(c => c.CardNumber == 1234)
```
like described here https://github.com/linq2db/linq2db/issues/1642#issuecomment-472732593.

So far so good. 

What can I do if I wanted to insert stuff? Ok, there is a `tableName` in one of the overloads of `InsertAsync()` but I'd like to use properties in the context to accomplish that like this:

```c#
public class BlaContext : DataConnection
{
    public BlaContext(DataOptions dataOptions)
        : base(dataOptions)
    {
    }

    public ITable<BlaBla> BlaBlas => this.GetTable<BlaBla>()
        .TableName("BlaBla1");
}
```

`db.BlaBlas.InsertAsync(...` is not available.
I must use `db.InsertAsync("MyTableName"...);`

`BulkCopyAsync` does not have a `tableName` in the overloads.

How can I manage to insert stuff by using BulkCopy and InsertAsync with `GetTable<BlaBla>().TableName()`?

### Environment details

`Linq To DB` version: 5.0.0

**Comment by sdanyliv** [comment]
So, this code do not work?
```cs
db.BlaBlas.TableName("MyTableName").InsertAsync(...
```

**Comment by HypeillingerChillinger** [comment]
Actually, `ITable` does not have an `InsertAsync` extension method that receives a `BlaBla` instance without table name parameter.

This is what I found but you need to provide the table name which 
I do not want because I already provided it in `.TableName("")`

```c#
await context.InsertAsync(blablaItem, context.BlaBlas.TableName);
```

**Comment by igor-tkachev** [comment]
How do you use fluent mapping? Now you have to call method .Build() after all.

**Comment by HypeillingerChillinger** [comment]
@igor-tkachev : It is not an issue during runtime, but a problem of missing extension methods for ITable for this scenario.

(Yes, I've seen the breaking changes in the recent releases and I use Build() )

**Comment by MaceWindu** [comment]
Not planned. We already have required API on context and `ITable<>` APIs are for LINQ queries.
User could easily define own ITable extension methods to extract context reference from ITable and call existing API:
```cs
table.GetDataConnection().Insert(entity, tableName)
```
