### ISSUE TITLE
LoadWith() One To Many : InvalidOperationException: There is already an open DataReader 

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#4057]
We should look wether we have issue here. It doesn't sound right.

### Discussed in https://github.com/linq2db/linq2db/discussions/4056

<div type='discussions-op-text'>

<sup>Originally posted by **mxmissile** April  5, 2023</sup>
I'm obviously doing something wrong here or I dont understand how `LoadWith()` works. I'm getting

`System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
`
```
Parent? parent; 

await using (var db = new DataContext(options))
{
   parent = await db.GetTable<Parent>()
                .LoadWith(x => x.Children)
                .FirstOrDefaultAsync(x => x.Id == 208243);
} // exception is thrown here

Console.WriteLine(parent.Children.Count()); 
```

And my poco classes:

```
[Table("parents")]
    public class Parent
    {
        [PrimaryKey, Identity, Column("parent_id")]
        public int Id { get; set; }

        [Column] 
        public string Title { get; set; }

        [Association(
            ThisKey = nameof(Id),
            OtherKey = nameof(Child.ParentId))]
        public IEnumerable<Child> Children { get; set; } = null!;
    }

    [Table("children")]
    public class Child
    {
        [PrimaryKey, Identity, Column("child_id")]
        public int Id { get; set; }

        [Column("parent_id")] 
        public int ParentId { get; set; }
    }
```

 How can I eager load `Parent.Children`?

UPDATE: I'm not sure why, but using `DataConnection` instead of `DataContext` solved the issue, I think it has something to do with `Async`.</div>

**Comment by mxmissile** [comment]
`DataContext` without *Async does in fact work: 

```
db.GetTable<Parent>()
                .LoadWith(x => x.Children)
                .FirstOrDefault(x => x.Id == 208243);
```
