### ISSUE TITLE
[HELP] [PLSQL] How to map a raw query to an object

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#4063]
### Describe your issue

Need to create a query based on some joins etc, that will return some columns renamed with aliases (theColumn as otherName).

How can achieve this?
I tried to use QueryToListAsync<T> passing an object that has data annotations to declare the renamed columns, but don't work.
`    public class MyClassDto
    {
        [Column("SomethingElse")]
        public int? MyNumber{ get; set; }
        .....
`

For the example above the raw sql query will return SomethingElse as a column.

Not sure how to properly do this, the source of data are many tables not just one and i need to map columns to the class to deserialize the db response in C#

I'm not sending parameters to the query, all the data is in the query string so i dont need to pass parameters.

The issue I'm getting is:

```
Exception: Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00933: SQL command not properly ended
```

### Environment details

`Linq To DB` version: Lastest

Database (with version): Oracle

Is it possible to provide some examples about how to use the API to accomplish this? Thanks

**Comment by sdanyliv** [comment]
Have you tried `FromSql`?

**Comment by sdanyliv** [comment]
Can you post WHOLE classes and what you have tried with SQL. Question looks like a puzzle for me.

**Comment by sdanyliv** [comment]
Try to use double quotes when specifying column aliases:
```cs
var rawQuery = @$" select some_name as ""first_name"", some_age as ""the_age"", from FooTable ";
```
Then `QueryToListAsync` should work.

Or set Global settings (will be obsolete)
```cs
OracleTools.DontEscapeLowercaseIdentifiers = true;
```

**Comment by gpgpublickey** [comment]
Sorry to re open, @sdanyliv how can I pass data parameters to my query instead of string interpolation to avoid sql injection attacks?

**Comment by sdanyliv** [comment]
Have you tried anything? `linq2db` allows passing parameters by default.

**Comment by gpgpublickey** [comment]
Yes I tried, I solved it using FromSql<T> using the {0}, {1}, {2} string format to pass data parameters because with the other methods i didn't have success using that or other formar like @parameter1 in the raw query

**Comment by gpgpublickey** [comment]
Adding more examples, you can replace {0}, {1}... format by :your_parameter, important to highlight it should be ":" instead "@" in the raw query.

For a data parameter with name "your_parameter" then the raw query should have for instance `"SELECT * FROM FOO WHERE BAR = :your_parameter`
