### ISSUE TITLE
Sync/Async performance difference in SqlClient for huge strings

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#4064]
### Describe your issue

I observed performance issues with `SELECT` on large strings (few million chars) in Sql Server. The string column is just read and not part of `WHERE`. Excluding the string column from the query makes the query very fast.

Here
https://github.com/dotnet/SqlClient/issues/593
they say it was an issue with SqlClient and using sync instead of async should push the performance significantly but I cannot observe the high factor they are mentioning here: https://github.com/dotnet/SqlClient/issues/593#issuecomment-639801525

Am I on the wrong track? I did not measure the performance exactly but it is way slower than in Azure Data Studio for the same query.

**Comment by MaceWindu** [comment]
What is your question actually? That's true that `SqlClient` is unusable in async scenarios if big blobs are read from database and there is nothing we can do. Users should use sync code to read blobs.

Referenced issue hardly will be fixed soon if ever fixed (there are attempts to fix it but this process already takes years and far from end). My only hope - new SQL Server client AKA `Woodstar`, but it's also doesn't look like something comning soon...

**Comment by MaceWindu** [comment]
Just want to add that "big blob" here starts from anything bigger than sql server protocol packet size (around 32kb by default IIRC)

**Comment by HypeillingerChillinger** [comment]
The question is:
Is the poor performance even with sync query a SqlClient issue? Am I doing sth. wrong or do I have to accept it? On Postgres instead it is extremely fast.

My table contains 100.001 strings from 0 up to 3 million chars  
SQL Server: varchar(max), 
Postgres: character varying

```c#

        // SQL Server - sync
        var swSync = Stopwatch.StartNew();
        using var msSqlContext = contextFactory.CreateMsSqlContext();
        var result = msSqlContext.MyTable.ToList();
        Assert.Equal(100_001, result.Count);
        swSync.Stop(); // about 5 minutes
  

        // Postgres - same table, same query, same data, no index at all (copied data to Postgres - huge 
        // string column is of type "character varying")
        var swPostgres = Stopwatch.StartNew();
        using var postgresContext = contextFactory.CreatePostgresContext();
        var resultPostgres = await postgresContext.MyTable.ToListAsync();
        Assert.Equal(100_001, resultPostgres.Count);
        swPostgres.Stop(); // 800ms

```

**Comment by MaceWindu** [comment]
There is no additional heavy work on linq2db side for such queries, so if you see performance issue like that, it should be caused by SqlClient or SQL Server configuration.

E.g. if you have MARS enabled for your connection, it will affect performance badly.

I would recommend to convert your test code to ADO.NET and try to ask at https://github.com/dotnet/SqlClient and checking existing performance issues https://github.com/dotnet/SqlClient/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Achart_with_upwards_trend%3A+Performance%22

**Comment by HypeillingerChillinger** [comment]
MARS is not activated.

Ok, thanks
