### ISSUE TITLE
ClickHouse query hints/extensions 

### ISSUE THREAD

**Issue by jljordaan** [linq2db/linq2db#4066]
### Describe your issue

The Roadmap [mentions](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#additional-features) that feedback is welcomed on which custom query hints/extensions should be implemented for the **ClickHouse** provider.

May I suggest that the [FINAL](https://clickhouse.com/docs/en/sql-reference/statements/select/from#final-modifier) table modifier is supported via a custom `.AsClickHouse().UseFinalTableHint()` table hint extension.

Having this functionality will enable our team to start using linq2db in our production environment to perform queries against our OLAP database.

**Comment by MaceWindu** [comment]
@igor-tkachev FYI

**Comment by igor-tkachev** [comment]
Will they ever stop doing it to us?

**Comment by MaceWindu** [comment]
We don't have hints API for ClickHouse yet. I decided to not implement them from start, as ClickHouse has miriad of SQL extensions and it is not clear which of them are useful and I don't have so many time to waste :)

**Comment by igor-tkachev** [comment]
Is there any ClickHouse hint related documentation?

**Comment by jljordaan** [comment]
Hi @MaceWindu & @igor-tkachev 

The time and effort you guys put into this project is very much appreciated!

I couldn't find an explicit list of the hints supported, but the [SELECT Query Syntax](https://clickhouse.com/docs/en/sql-reference/statements/select) does show what I think might be all the various supported hints.

I do understand that it does not makes sense to implement all the ClickHouse SQL extensions from the get-go. Would it maybe be possible to only support a `.AsClickHouse()` database specific API that could then be extended/implemented by end users to add their own hints etc. as they require? I might be on the wrong track here - so please guide me.
