### ISSUE TITLE
[QUESTION] SqlExpressions, how to pass many parameters and if possible to pass linq properties 

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#4078]
### Describe your issue

Is possible to pass many parameters in a SqlExpression?

```
        [Sql.Extension("ROW_NUMBER() OVER(PARTITION BY {args, ', '} ORDER BY {0}", ServerSideOnly = true)]
        public static int GetRowNumber(string orderBy, [ExprParameter] params object[] args)
        {
            throw new NotSupportedException();
        }
```
I'm trying to accomplish a way to make reusable a sql expression to retrieve a row number based on some columns and pass a column as ordering criteria, any idea about how to accomplish this?
Final generated query should be something like:
```
           ROW_NUMBER() OVER(PARTITION BY foo1.name, foo1.age, foo1.birthdate
            ORDER BY foo1.age)
```

### Environment details

`Linq To DB` version: Last stable version

Database (with version): Oracle

**Comment by sdanyliv** [comment]
What is generated? Looks like a correct extension.

**Comment by gpgpublickey** [comment]
Hi @sdanyliv glad to see you < 3

im calling this in my select statement in my IQueryable instance:
```
from foo1 in _db.someTable
select new
{
RowNo = CommonExpressions.GetRowNumber("foo1.age", "foo1.name", "foo1.age", "foo1.birthdate")
}
```

**Comment by sdanyliv** [comment]
Can you try this one?
```cs
var query =
    from foo1 in _db.someTable
    select new
    {
        RowNo = Sql.Ext.RowNumber().Oover()
            .PartitionBy(foo1.age, foo1.name, foo1.age)
            .OrderBy(foo1.birthdate)
            .ToValue()
    };
```

**Comment by gpgpublickey** [comment]
That worked! you are like Rihanna, you shine bright like a diamond lol thanks! <3 @sdanyliv
