### ISSUE TITLE
Race condition in static connection initialization

### ISSUE THREAD

**Issue by justynbussey** [linq2db/linq2db#408]
The following code in DataConnection.cs allows a race condition to occur.

```
    static void InitConnectionStrings()
    {
        foreach (ConnectionStringSettings css in ConfigurationManager.ConnectionStrings)
        {
            _configurations[css.Name] = new ConfigurationInfo(css);

            if (DefaultConfiguration == null && !IsMachineConfig(css))
            {
                DefaultConfiguration = css.Name;
            }
        }
    }

    static int _isInitialized;

    static void InitConfig()
    {
        if (Interlocked.Exchange(ref _isInitialized, 1) == 0)
            InitConnectionStrings();
    }
```

Interlocked.Exchange is used to ensure that InitConnectionStrings() is called only once, but nothing is done to ensure that InitConnectionStrings() has executed fully before a second thread checks if the static initialization has occurred, finds _isInitialized already at 1 and continues on.  Thus a second thread can (and in my code did) attempt to lookup a connection string in _configurations before the first thread has finished populating _configurations.

**Comment by ili** [comment]
this is fixed
