### ISSUE TITLE
[HELP] IN statement in raw queries

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#4080]
### Describe your issue

I want to insert in my raw query an IN statement in PLSQL, i would like to know if exists an API in linq2db to do this easily passing a list of strings or if I should create a custom one, because at time to pass my custom implementation to a data parameter it is being escaped, is not possible passing it in the data parameter?

**Comment by MaceWindu** [comment]
you can combine raw sql subqueries with linq using `FromSql` API. See examples here https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/FromSqlTests.cs
