### ISSUE TITLE
[HELP] Linq2Db has support for the PLSQL "Table" statement?

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#4081]
Is possible to translate to linq something like:

`SELECT * FROM table(MyPackage.GetATable())  ` ?

Where MyPackage.GetATable() returns a `TYPE MY_TABLE IS TABLE OF MY_REC;`

Any idea about if is possible to integrate this in a linq expression using linq2db?

Maybe using FromSql? I saw that for certain compatible providers that allows to return a IQueryable that can be combined with other IQueryable linq expression. Any thought?

**Comment by MaceWindu** [comment]
- use `FromSql`
- use `Sql.Sql.TableExpressionAttribute` (some examples could be found in tests https://github.com/search?q=repo%3Alinq2db%2Flinq2db+Sql.TableExpression+path%3A%2F%5ETests%5C%2F%2F&type=code )
