### ISSUE TITLE
GroupBy clause is different depending on presence of .AsCte()

### ISSUE THREAD

**Issue by brd-mikek** [linq2db/linq2db#4098]
I have this situation when SQL is not generated correctly around GROUP BY clause.
If I use .AsCte() on subquery, the SQL looks correct.

See program attached to reproduce the problem.
Also, see the screenshot with generated SQL.

![Linq2DbProblem](https://user-images.githubusercontent.com/77951000/235388275-ebf216de-05cf-40b7-a164-4ec1396f54c0.png)

[Linq2DbProblem.zip](https://github.com/linq2db/linq2db/files/11362958/Linq2DbProblem.zip)

**Comment by MaceWindu** [comment]
As another workaround you can use AsSubQuery() instead of Cte()

**Comment by brd-mikek** [comment]
Hi guys!
When are you planning to release this?

**Comment by MaceWindu** [comment]
It was released as part of 5.2.1 release last week
