### ISSUE TITLE
Loading backreference not working

### ISSUE THREAD

**Issue by iColdoCatalin** [linq2db/linq2db#4101]
Not working when trying to load a backreference (IEnumerable<object>).
Normal references work with this version of linq2db but when trying to load a backreference it simply doesn't load anything.
On VS output window the query doesn't have the joins on that backreference.

var q = _myDB.MYTABLE
            .LoadWith(x => x.MYBACKREFERENCECOLLECTION)
            .Where(x => x.Active)
            .OrderBy(x => x.Date);

### Environment details

`Linq To DB` version: 3.6.0

Database (with version): SQLServer 2019

ADO.NET Provider (with version): System.Data.SqlClient 4.8.3

Operating system: Windows

.NET Version: .Net6

**Comment by MaceWindu** [comment]
Could you add mappings?

**Comment by iColdoCatalin** [comment]
/// <summary>
		/// FK__iC_Delive__DVMA___1A17459A_BackReference
		/// </summary>
		[Association(ThisKey="MAId", OtherKey="DvmaMAId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<IcDeliveryMaterial> ICDeliveDVMA1A17459A { get; set; }

Can the issue be related to other OrderBy or Where clauses beeing added after?

**Comment by MaceWindu** [comment]
> Can the issue be related to other OrderBy or Where clauses beeing added after?

Maybe. You can move/comment them to check

**Comment by MaceWindu** [comment]
Just tested it with 3.6.0 and everything works for me. Could you provide similar example where it doesn't work for you?


```cs
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.SQLite;
using LinqToDB.Mapping;
using System.Diagnostics;

internal class Program
{
	static void Main()
	{
		var dbName = "test.sqlite";
		if (File.Exists(dbName))
		{
			File.Delete(dbName);
		}
		using (File.Create(dbName))
		{
		}
		using var db = new DataConnection(SQLiteTools.GetDataProvider(ProviderName.SQLiteClassic), $"Data Source={dbName}");
		DataConnection.TurnTraceSwitchOn(TraceLevel.Verbose);
		db.OnTraceConnection += t => Console.WriteLine(t.SqlText);

		db.CreateTable<MainTable>();
		db.CreateTable<ChildTable>();

		db.Insert(new MainTable() { MAId = 1, Active = true, Date = DateTime.Now });
		db.Insert(new ChildTable() { DvmaMAId = 1 });

		var data = db.GetTable<MainTable>()
			.LoadWith(e => e.ICDeliveDVMA1A17459A)
			.Where(x => x.Active)
			.OrderBy(x => x.Date)
			.ToArray();

		if (data[0].ICDeliveDVMA1A17459A.Count() != 1)
		{
			throw new InvalidOperationException();
		}
	}
}


[Table]
sealed class MainTable
{
	[Column]
	public int MAId { get; set; }
	[Column]
	public bool Active { get; set; }
	[Column]
	public DateTime Date { get; set; }

	[Association(ThisKey = "MAId", OtherKey = "DvmaMAId", CanBeNull = true)]
	public IEnumerable<ChildTable> ICDeliveDVMA1A17459A { get; set; } = null!;
}

[Table]
sealed class ChildTable
{
	[Column]
	public int DvmaMAId { get; set; }
}
```

**Comment by iColdoCatalin** [comment]
Just made a simple test similar to yours and works with same version...
I'm gone try and find the issue into my code then. 
Thanks for helping.
