### ISSUE TITLE
Conditional use of LoadWith

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#4109]
I'm in the middle of refactoring an old .NET Framework app to the latest .NET 7. In the old version of linq2db, we used to load associated tables based on a condition, eg.

```cs
var model = db.Profiles;

if ( fields?.Customer != null )
    model.LoadWith( x => x.Customer );

if ( fields?.User != null )
    model.LoadWith( x => x.User );

if ( fields?.Product != null )
    model.LoadWith( x => x.Product );

if ( fields?.GlobalProfile != null )
    model.LoadWith( x => x.GlobalProfile );

return model;
```

But in the latest 5.x linq2db, this is no longer possible. When the model is returned, all associated sub-models are `null`.

Making them all joined up works, like in the following example.

```cs
var model = db.Profiles
    .LoadWith( x => x.Customer )
    .LoadWith( x => x.User )
    .LoadWith( x => x.Product )
    .LoadWith( x => x.GlobalProfile );

return model;
```

But that defeats the purpose because we cannot load sub-models conditionally, as they are all loaded simultaneously.

---

Is there a new way of loading associated models conditionally that I cannot find in the documentation? Is this feature still possible to do?

**Comment by MaceWindu** [comment]
You don't save results of `LoadWith` call:
```cs
// result lost
model.LoadWith( x => x.GlobalProfile )
// result saved
model = model.LoadWith( x => x.GlobalProfile )
```

**Comment by stsrki** [comment]
@MaceWindu, I appreciate your help. That worked. I had to cast a model to `IQueryable` since `ITable` could not be linked with `LoadWith`.

Here is the updated working code for anyone interested.

```cs
var model = db.Profiles as IQueryable<RepositoryProfile>;

if ( fields?.Customer != null )
    model = model.LoadWith( x => x.Customer );

if ( fields?.User != null )
    model = model.LoadWith( x => x.User );

if ( fields?.Product != null )
    model = model.LoadWith( x => x.Product );

if ( fields?.GlobalProfile != null )
    model = model.LoadWith( x => x.GlobalProfile );

return model;
```
