### ISSUE TITLE
Query.Take(1).SingleOrDefault() bug

### ISSUE THREAD

**Issue by Lexey** [linq2db/linq2db#411]
The above LINQ query effciently results in Take(2).SingleOrDefault() SQL query. And it fails if the resultset has more than 1 rows.
Possible fix:
https://github.com/Lexey/linq2db/commit/003b73545def6db36d646b99eb9140d9c43f91fd

**Comment by ili** [comment]
@Lexey @jogibear9988  please, can you explain the problem in sample?

As I see `SingleOrDefault` should fail if we do have more then one row in resultset, if we do not want fail, we should use `FirstOrDefault`. 
If I'm not mistaken reading the suggested change, it would be smth like (for `db.GetTable<T>().Take(1).SingleOrDefault()`):
before:
```sql
select top 2 from mytable
```
after 
```sql
select top 1 from mytable
```

**Comment by jogibear9988** [comment]
yes,  but he does take one before, then we should not overwrite with 2
his example will also work in linq2objects

**Comment by jogibear9988** [comment]
New fix with test: https://github.com/linq2db/linq2db/pull/477

**Comment by jogibear9988** [comment]
close?
