### ISSUE TITLE
Scaffold tool failing to generate schema

### ISSUE THREAD

**Issue by richinoz** [linq2db/linq2db#4111]
### Describe your issue

When using the scaffold tool (5.1.1 or 5.2.0) - the MemberHelper.MethodOf code is omitting the schema from the context call. 
For example - the following code is produced

public static partial class CommunicationsSchema
	{
		public partial class DataContext
		{
			private readonly IDataContext _dataContext;
                         private static readonly MethodInfo _preferencesGet = MemberHelper.MethodOf<DbCore>(ctx => **ctx.PreferencesGet**(default, default));

			[Sql.TableFunction("Preferences_Get", Schema = "Communications")]
			public IQueryable<PreferencesGetResult> PreferencesGet(int? personId, int? applicationSourceId)
			{
				return this.GetTable<PreferencesGetResult>(this, _preferencesGet, personId, applicationSourceId);
			}

**BUT** the code _preferencesGet field **should** read:

private static readonly MethodInfo _preferencesGet = MemberHelper.MethodOf<DbCore>(ctx => ctx.**Communications**.PreferencesGet(default, default));

I'm using .Net core 6.0

```
Exception message:
Stack trace:
```

### Steps to reproduce

run dotnet linq2db scaffold -i scaffold.json

```c#
{
  "general": {
    "provider": "SqlServer",
    "connection": "Server=localhost\\MSSQLSERVER01;Ietc etc",
    "customize": "bin\\Debug\\net6.0\\Core.DataAccess2.dll",
    "output": "Model",
    "overwrite": true
  },
  "dataModel": {
    "context-name": "DbContext",
    "include-default-schema-name": true,
    "add-associations": false
  },
  "code": {
    "namespace": "myNameSpace",
    "single-file": true
  },
  "schema": {
    "include-schemas": [
      "dbo", "Core", "Calendar", "Team", "Communications",  "Analytics", "Reporting", "Resources", "ContentManagement"
    ],
    "exclude-tables": [
      
    ],
    "exclude-views": [
      
    ],
    "objects": [
      "table",              
      "view",               
      "foreign-key",        
      "stored-procedure",   
      "scalar-function",    
      "table-function",     
      "aggregate-function"
    ]
  }
}
```

### Environment details

`Linq To DB` version: *5.2.0*

Database (with version): *SQL Server 2019*

ADO.NET Provider (with version): *default for linq2db 5.2.0* (e.g. Microsoft.Data.SqlClient 4.1.0)

Operating system: *windows 10*

.NET Version: *.net core 6*

**Comment by richinoz** [comment]
Hi - when will it be available to download?

Thanks

Rich

**Comment by richinoz** [comment]
Hi - I just downloaded and used 5.2.1 and the issue still exists :(

**Comment by MaceWindu** [comment]
Could you:
- check installed version (`dotnet tool list -g`)
- show generated code

**Comment by richinoz** [comment]
It was indeed that I hadn't updated my global tool. It's quite easy to
forget that updating the nuget package does not update the tool.

My apologies and thanks.

Rich Smith
