### ISSUE TITLE
When using linq2db version 5.2.0 functionality breaks with code first models using base classes

### ISSUE THREAD

**Issue by aloksharma1** [linq2db/linq2db#4113]
Hello, 
everything works for 5.1.1 but when i upgrade to 5.2.0 it causes my project to crash, with following error:

`ArgumentException: An item with the same key has already been added. Key: Id`

the reason that i traced out was this:

```
public class BaseViewModel
{
    public virtual int Id { get; set; }
}

public class MyModel : BaseViewModel
{
    public new Guid Id { get; set; }
}
```
so i traced that its treating derived types and base types as different columns, please fix this issue.
when i downgraded to previous version the error went away. 
regards

P.S. I am using dotnet 5

**Comment by aloksharma1** [comment]
> 

this workaround is not possible in the current project as i have a hierarchy of derived classes, this will be too much work to fix that i will wait for the next good release.

**Comment by MaceWindu** [comment]
Could you update your model to include interface? (this issue happens only when model implements interfaces)

**Comment by aloksharma1** [comment]
i am good to update, sorry i am unable to try your suggestion for changing base classes as this is already in production, the project architecture makes it impossible to do breaking changes (its divided in plugins a lot)
