### ISSUE TITLE
[KT] Is possible to override the default behavior of the T4 template mapping properties when  schema is regenerated?

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#4114]
### Describe your issue
Sorry if this repo is not the correct place to make this question. If we have another pls let me know and I can move the issue.

We are trying to solve impedance mismatch problems and we need to map chars and chars? to strings always we regenerate the schema cs file to improve performance and avoid issues.

Is it possible to override this behavior with some config that i'm missing in the tt templates?
Thanks

### Environment details

Database: Oracle db

**Comment by MaceWindu** [comment]
Check https://linq2db.github.io/articles/T4.html#configuring-schema-load-process

`GetSchemaOptions.GenerateChar1AsString = true;`
