### ISSUE TITLE
'DataConnection' does not contain a definition for 'GetTable'

### ISSUE THREAD

**Issue by matrix2019** [linq2db/linq2db#4115]
### Describe your issue

Hello gents,

I'm using linq2db in version 3.6. Now I updated to version 5.2 and I receive some errors.
Maybe someone can advice me to fix it.

On a dataconnection
```
DataConnection con = DBHelper.GetConnection();
con.GetTable<testtable>().First();
```

I receive an 
'DataConnection' does not contain a definition for 'GetTable'  exception.

Is there an new way to receive the data?
Thanks for help

**Comment by MaceWindu** [comment]
`GetTable` was converted to extension method. Probably you miss `using` or `this.` before call if you call it from `DataConnection` descendant

**Comment by matrix2019** [comment]
Hello Mace,

i'm not sure whar you mean
I use
```
using System.Linq;

 DataConnection con = DBHelper.GetConnection();
            using (con)
            {
                SettingsGlobal gset = con.GetTable<SettingsGlobal>().First();
```
Is there something I missed?

best regards.

**Comment by MaceWindu** [comment]
Do you have `using LinqToDB;`?

GetTable is here in new versions:

https://github.com/linq2db/linq2db/blob/af2ce8015cfb2986d94862ce34ff4ce0d5c36c30/Source/LinqToDB/DataExtensions.cs#L36

**Comment by matrix2019** [comment]
Hello Mace,

oh, extension. I missed it. :)
Thank's a lot.
using LinqToDB; was the trick.

Have a nice day :)
