### ISSUE TITLE
new scaffold tool generating different stored proc result for sql server stored proc

### ISSUE THREAD

**Issue by richinoz** [linq2db/linq2db#4130]
### new scaffold tool generating different stored proc result for sql server stored proc

the new scaffold tool 5.2.1 is generating incorrect/different result from older 4.1.1 linq2db tools

```
Exception message:
Stack trace:
```

### Steps to reproduce

The procedure in question is a proc that calls another proc and the result is a recordset

```
CREATE OR ALTER  PROCEDURE Core.ReferenceData_GetByType  
    @tenantId INT,  
    @referenceDataTypeId INT  
AS  
BEGIN  
    EXEC dbo.SetStandardSettings  
  
     EXEC Core.ReferenceData_Get @tenantId = @tenantId,  
                                @referenceDataTypeId = @referenceDataTypeId  

	RETURN 0;
  
END  
```

```c#
public static IEnumerable<ReferenceDataGetByTypeResult> ReferenceDataGetByType(this DbCore dataConnection, int? @tenantId, int? @referenceDataTypeId)
		{
			var parameters = new []
			{
				new DataParameter("@tenantId",            @tenantId,            LinqToDB.DataType.Int32),
				new DataParameter("@referenceDataTypeId", @referenceDataTypeId, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<ReferenceDataGetByTypeResult>("[Core].[ReferenceData_GetByType]", parameters);
		}

		public partial class ReferenceDataGetByTypeResult
		{
			public int    GenderId          { get; set; }
			public string GenderDescription { get; set; }
			public long?  SortOrder         { get; set; }
		}
```

However, the new tool generate this instead
```

public static int ReferenceDataGetByType(this DbCore dataConnection, int? tenantId, int? referenceDataTypeId)
{
	var parameters = new []
	{
		new DataParameter("@tenantId", tenantId, DataType.Int32),
		new DataParameter("@referenceDataTypeId", referenceDataTypeId, DataType.Int32)
	};
	return dataConnection.ExecuteProc("[Core].[ReferenceData_GetByType]", parameters);
}

```

Returning an Integer rather than the recordset

### Environment details

`Linq To DB` version: *5.2.1*

Database (with version): *?* (SQL Server 2019)

Operating system: *Windows 10*

.NET Version: *Net7.0*

**Comment by MaceWindu** [comment]
What options you use? Do you have `schema.load-sproc-schema` option enabled?

**Comment by richinoz** [comment]
Hi - I did indeed need the schema.load-sproc-schema to fix the issue.
Maybe this should be default true, as not returning the results of a Stored Proc seems odd?
Thanks

Rich Smith

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaceWindu** [comment]
It's not safe to have it as default.
Most of databases doesn't provide safe api to get schema information for procedures and providers execute them (usually using transaction with immediate rollback). This works good for most of procedures, but if procedure contains non-transactional code, it could lead to unwanted side-effects.

**Comment by richinoz** [comment]
Ok, thanks for the explanation

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
