### ISSUE TITLE
how use multiple database

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#4134]
Hi ,

I use linq2db.cli for Genarate Model ,

i Have multiple Database , How remove InitDataContext()

???

**Comment by MaceWindu** [comment]
Currently there is no option to remove it. Why do you want to remove it?

**Comment by MajidSafari** [comment]
hi , i have multi database , how scaffold , in one context ?

**Comment by MaceWindu** [comment]
Context generated as partial class so you can run generation separately for each database with following options:
- specify same context class name
- disable context constructors generation and define required constructors manually
