### ISSUE TITLE
Registering Linq2DBContext in Asp.Net core not working as previous versions

### ISSUE THREAD

**Issue by iColdoCatalin** [linq2db/linq2db#4143]
I'm updating an existing Asp.Net core project from linq2db v3.6.0 to v5.2.1 and used the new donet cli tool to scaffold the db.
Now I'm having trouble configuring the service.

Using the same code as before it says that **"Not all code paths return a value in lamba expression"**.

```
builder.Services.AddLinqToDBContext<MyDB>((provider, options) =>
{
    options
    .UseSqlServer(builder.Configuration.GetConnectionString("MyDB")!)
    .UseDefaultLogging(provider);
}, lifetime: ServiceLifetime.Transient);
```

How can I fix this?

### Environment details

`Linq To DB` version: 5.2.1

.NET Version: .Net7

**Comment by iColdoCatalin** [comment]
Just tryied even AddLinqToDB and same error.
https://linq2db.github.io/api/linq2db.aspnet/LinqToDB.AspNet.ServiceConfigurationExtensions.html

**Comment by iColdoCatalin** [comment]
I think I found the solution.
I was missing the return before options since now it is a Func and not an Action.
Can the docs be updated?

```
builder.Services.AddLinqToDBContext<MyDB>((provider, options) =>
{
    return options
    .UseSqlServer(builder.Configuration.GetConnectionString("MyDB")!)
    .UseDefaultLogging(provider);
}, lifetime: ServiceLifetime.Transient);
```

**Comment by MaceWindu** [comment]
Thanks! Will fix.

**Comment by MaceWindu** [comment]
We need to update 3 examples here c:\GitHub\linq2db.docs\submodules\linq2db\Source\LinqToDB.AspNet\ServiceConfigurationExtensions.cs
