### ISSUE TITLE
Concider adding some expression-based CRUD extensions to linq2db.tools

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#4149]
E.g. see https://github.com/linq2db/linq2db/discussions/4148 and related links.

**Comment by luty81** [comment]
I already implemented something similar in a packaged I developed a couple of years ago:

https://github.com/luty81/PowerUp/blob/master/PowerUp.Tests/SQL/CommandBuildingUpdateTests.cs

Does it make sense to adapt it and add to linq2db.tools ?

**Comment by MaceWindu** [comment]
No need for tracking issue here
