### ISSUE TITLE
Ability to specific SqlServerVersion

### ISSUE THREAD

**Issue by Terricide** [linq2db/linq2db#4154]
### Describe your issue

Is it possible to specific the version of the SQL server and avoid Linq2Db having to run

SELECT compatibility_level FROM sys.databases WHERE name = db_name()

I believe it used to be able to be passed in the constructor in an older version of Linq2db.

**Comment by Terricide** [comment]
I think I figured it out I can pass SqlServer2022 instead of SqlServer into the constructor.

**Comment by MaceWindu** [comment]
As you figured out, you can specify version in configuration name or use ProviderName.SqlServerXXX as configuration name.
Another options will be:
- build connection options using `DataOptions` class and `UseSqlServer` configuration extension with dialect parameter (recomended)
- pass `IDataProvider` instance to connection from `SqlServerTools.GetDataProvider` mthod
