### ISSUE TITLE
 Is there a global method for directly printing SQL statements?

### ISSUE THREAD

**Issue by gallop1** [linq2db/linq2db#4162]
Is there a global method for directly printing SQL statements?（有没有直接打印SQL语句的全局方法？）

**Comment by viceroypenguin** [comment]
After each query, you can examine `context.LastQuery` to see the statement; or you can use `TraceSwitchConnection` to enable tracing and `OnTraceConnection` to receive trace information about each action to then log statements.

**Comment by gallop1** [comment]
How to write the TraceSwitchConnection method later? I don't know how to assign values to the db. TraceSwitchConnection and OnTraceConnection methods.(后面的TraceSwitchConnection方法怎么写？我不知道改如何赋值 db.TraceSwitchConnection 和OnTraceConnection 方法。) @viceroypenguin

**Comment by MaceWindu** [comment]
To setup sql logging globally you need to do following:
```cs
// set trace level
DataConnection.TurnTraceSwitchOn();
// or
DataConnection.TraceSwitch = new Tracewitch(...);

// set custom trace listener for
// formatted trace messages:
DataConnection.WriteTraceLine = (mesage, category, level) => { ... };
// or for raw traces:
DataConnection.DefaultOnTraceConnection = trace => { ... };
```

**Comment by feeleen** [comment]
#3878

**Comment by gallop1** [comment]
@MaceWindu  When I use DataMnection TraceSwitch = new Tracewitch(...); When using this method, there are also//or for raw traces:
DataConnection.DefaultOnTraceConnection = trace => { ... }; I can't achieve what I want, you have a problem at this time. I'll post my code. Please help me correct it, thank you.
(当我使用DataConnection.TraceSwitch = new Tracewitch(...);这个方法时候，还有// or for raw traces:
DataConnection.DefaultOnTraceConnection = trace => { ... };并不能实现我的想要，你这个时候有问题。我贴一下我的代码。请帮我更正一下，谢谢。)

TraceSwitch traceSwitch = new TraceSwitch("要在用户界面上显示的名称", "切换描述");
////或者原始跟踪,但是一样会打印两次生成的Sql语句。
DataConnection.DefaultOnTraceConnection = trace =>
{
    Console.WriteLine(trace.SqlText);
};

//必须设置SqlServerVersion的数据库版本号，不然不能正常连接数据库。
DataOptions dataOptions = new DataOptions().UseSqlServer(conString, LinqToDB.DataProvider.SqlServer.SqlServerVersion.v2022);
using (DataConnection db = new DataConnection(dataOptions))
{
    //跟using外的效果一样。但是一样会打印两次生成的Sql语句。
    db.OnTraceConnection = trace =>
    {
        Console.WriteLine(trace.SqlText);
    };

    DataConnection.DefaultOnTraceConnection = db.OnTraceConnection;

    //现在，当你使用linq2db执行查询时，它会在控制台中打印出生成的SQL语句
    Student student = new Student();
    //student.Id = 5;
    student.Name = "理想";

    //设置了自增主键字段需要执行这条语句，不然会报错。不能正常插入Id，需要指定Id的值才行。
    //int rows = db.Execute("SET IDENTITY_INSERT Student ON;");
    //1:新增 
    int insertCount = db.Insert(student);

    //LastQuery这个只是日志记录的Sql，不是可执行的SQL语句，所以没有太大意义，还需要自己转义一次替换成数据库可执行的SQL语句。
    //你想干什么？如果您使用日志sql，则它不是为执行而生成的，而是仅用于日志记录。
    string sql = db.LastQuery;
    //2:批量新增
    //db.Insert(new List<Student>());

    var studentModel = from s in db.GetTable<Student>() select s;

    //ToList调用在我们仍在使用时向数据库发送查询。
    var studentModel2 = db.GetTable<Student>().ToList();

    //打印生成执行的SQL语句：每次查询后，您都可以检查上下文。LastQuery查看语句；
    //包含使用当前连接发送到数据库的最后一个命令的文本。打印执行命令行的SQL语句
    return insertCount;
}

**Comment by MaceWindu** [comment]
If you consume `TraceInfo`, you should check value of `TraceInfoStep` to not log same query on different execution phases
