### ISSUE TITLE
Empty string vs null in new versions

### ISSUE THREAD

**Issue by brd-mikek** [linq2db/linq2db#4163]
We are upgrading from old version and we see that Linq2DB now treats empty string/null differently.

We used to have enums mapped like this.

```
public enum PaymentMethod
{
	[MapValue("")]  <-- note this
	Unknown,
	
	[MapValue("C"]
	Cheque,

	[MapValue("E")]
	EFT
}
```

Given query

```
from db.Table x
where x.PaymentMethod != PaymentMethod.Unknown
select x
```

Old version would produce the following

```
SELECT
...
FROM TABLE x
WHERE x.PAYMENTMETHOD IS NOT NULL
```

New version produces

```
SELECT
...
FROM TABLE x
WHERE x.PAYMENTMETHOD <> ''
```

New query does not work, because from Oracle's point of view no value is empty string, they are all nulls.

What would you recommend to do to make new Linq2DB generate old kind of query?

**Comment by MaceWindu** [comment]
Which version you upgrade from? I'm not sure how this mapping could generate `IS NOT NULL` check.

**Comment by jods4** [comment]
@MaceWindu I'm not sure about the specifics of this bug report, but there is a bit of code in `Oracle11SqlOptimizer` that is supposed to replace equality comparisons to a constant empty string with `is [not] null`.
The fact that the empty string is null is a quirk of Oracle.

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs#L86-L108

**Comment by igor-tkachev** [comment]
Such changes should be always done with using compatibility flags.

**Comment by brd-mikek** [comment]
> changes should be always done with using compatibility

Our old version is 2.9.6

**Comment by brd-mikek** [comment]
> Which version you upgrade from? I'm not sure how this mapping could generate `IS NOT NULL` check.

We are upgrading from 2.9.6

**Comment by brd-mikek** [comment]
> Such changes should be always done with using compatibility flags.

Not sure, Igor, if your comment is addressed to me or to your internal team. If it is to me, please elaborate!

**Comment by brd-mikek** [comment]
> @MaceWindu I'm not sure about the specifics of this bug report, but there is a bit of code in `Oracle11SqlOptimizer` that is supposed to replace equality comparisons to a constant empty string with `is [not] null`. The fact that the empty string is null is a quirk of Oracle.
> 
> https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs#L86-L108

Sound like that would have been correct behavior. Also looks like it is not working for some reason. If you can make it work, I think that would fix my problem.

**Comment by MaceWindu** [comment]
regressed since v3.2.0

**Comment by jods4** [comment]
I added the test cases to #4547.
That branch contains some fixes related to empty string and nulls handling in Oracle, so maybe it'll work.
Then again, enum mappings are special so maybe not, let's see.

**Comment by MaceWindu** [comment]
In next preview it will be almost working:
- you need to mark column nullable explicitly : `Column(CanBeNull = true)`
- or add null mapping to enum. e.g. `[MapValue(null)] Null = Unknown`

Infer of nullability currently doesn't work for `[MapValue("")]` and probably will not be available for some time
