### ISSUE TITLE
Bug related to .AsCte()

### ISSUE THREAD

**Issue by brd-mikek** [linq2db/linq2db#4167]
Hey guys!

See test project attached, it demonstrates the problem.
It happens on Oracle.
Adding .AsCte() makes query fail, while without .AsCte() it works fine.

Thanks,
Mike K

[Linq2DbTest.zip](https://github.com/linq2db/linq2db/files/11751751/Linq2DbTest.zip)

**Comment by MaceWindu** [comment]
Closing, already fixed in 5.2.2 by #4146
