### ISSUE TITLE
Unexpected sql on Insert with servername parameter

### ISSUE THREAD

**Issue by Isakacl** [linq2db/linq2db#4168]
Hi, 
I'm using linq2db 5.2.1 version with Oracle 11g managed driver with .NET Framework 4.6.2.
I have two db oracle linked servers, and executing query statement:
`Linq2DbConnection.GetTable<D_DBMS>().ServerName("CENTSIF").Any(p => p.ID ==isdb.Value);`
produces ok sql referencing exepected table "D_DBMS@CENTSIF":

```
DECLARE @Value_1 Int64
SET     @Value_1 = 6

SELECT
	CASE
		WHEN EXISTS(
			SELECT
				*
			FROM
				D_DBMS@CENTSIF p
			WHERE
				p.ID = :Value_1
		)
			THEN 1
		ELSE 0
	END
FROM SYS.DUAL

```
but when I try to execute insert statement with serverName parameter like this:

```
D_DBMS newDbId = new D_DBMS() { ID = isdb.Value };
Linq2DbConnection.Insert(newDbId,serverName: "CENTSIF");
```
it generates me unexpected sql without name of linked server and table name D_DBMS while I would exepect D_DBMS@CENTSIF:
```
--  Oracle.11.Managed Oracle11
DECLARE @ID Int64
SET     @ID = 6

INSERT INTO D_DBMS
(
	ID
)
VALUES
(
	:ID
)
```

Can you please give me an advice am I doing something wrong or misunderstud the purpuse of servername?
Thank you very much!

**Comment by MaceWindu** [comment]
For now you could try to use other `Insert` APIs or specify server name on `D_DBMS` class using `Table(Server="...")` attribute

**Comment by Isakacl** [comment]
Just for info,

I found in \Source\LinqToDB\Linq\QueryRunner.Insert.cs wrong line:

` if (tableName != null || schemaName != null || databaseName != null || databaseName != null)`

I believe it should be:

`if (tableName != null || schemaName != null || serverName != null || databaseName != null)`.

After that change in QueryRunner.Insert.cs and same thing in QueryRunner.Update.cs, everything works as expected.

**Comment by MaceWindu** [comment]
Ah, cool. Will work on defects later this week. Feel free to send PR for it
