### ISSUE TITLE
Unexpected sql on Update with servername parameter 

### ISSUE THREAD

**Issue by Isakacl** [linq2db/linq2db#4174]
Hi,
I'm using linq2db 5.2.1 version with Oracle 11g managed driver with .NET Framework 4.6.2.

fallowing code:

```
D_EQUIPMENTS dto= new D_EQUIPMENTS();
dto.ID   = 314180; //primary key
dto.ISID = 11;     //updated value
dc.Update(eQUIPMENT, serverName: "CENTSIF");

```

generates fallowing sql:

```
UPDATE
	D_EQUIPMENTS@CENTSIF
SET
	D_EQUIPMENTS@CENTSIF.ISID = :ISID
WHERE
	D_EQUIPMENTS@CENTSIF.ID = :ID
```

which is not valid sql for Oracle db.

Is there any way to force generating of alias for table name?

so it could generate sql like this:

```
UPDATE
	D_EQUIPMENTS@CENTSIF p
SET
	p.ISID = :ISID
WHERE
	p.ID = :ID
```

**Comment by sdanyliv** [comment]
Which mapping has table `D_EQUIPMENTS`? I assume 
```cs
[Table("D_EQUIPMENTS@CENTSI")]
```
but it should be:
```cs
[Table("D_EQUIPMENTS", Server = "CENTSI")]
```

**Comment by Isakacl** [comment]
Mappings are:

```
	public class D_EQUIPMENTS
	{
		[PrimaryKey]
		public long ID { get; set; }

		public long? ISID { get; set; }

	}
```

I must use update command with servername parameter because it is conditional and I have local and remote table

**Comment by sdanyliv** [comment]
Yes, missed your Update with `serverName`. @linq2db/developers could someone look into it?

**Comment by sdanyliv** [comment]
@Isakacl, can you point me to the documentation (I can't find)? I'll fix that but have need to ensure that not missed something as in this case.

**Comment by Isakacl** [comment]
> @Isakacl, can you point me to the documentation (I can't find)? I'll fix that but have need to ensure that not missed something as in this case.


I use Update method on DataConnection class which internaly calls 

```
public static int Update<T>(
			this IDataContext dataContext,
			T                 obj,
			string?           tableName    = default,
			string?           databaseName = default,
			string?           schemaName   = default,
			string?           serverName   = default,
			TableOptions      tableOptions = default)
			where T : notnull)
```

extension method defined in source file Source\LinqToDB\DataExtensions.cs

**Comment by Isakacl** [comment]
In source file: \Source\LinqToDB\Linq\QueryRunner.Update.cs
If I change line 49:

```
if (tableName != null || schemaName != null || serverName != null || databaseName != null)
{
	sqlTable.TableName = new(tableName    ?? sqlTable.TableName.Name,
		Server  : serverName   ?? sqlTable.TableName.Server,
		Database: databaseName ?? sqlTable.TableName.Database,
		Schema  : schemaName   ?? sqlTable.TableName.Schema);
}
```

to:

```
if (tableName != null || schemaName != null || serverName != null || databaseName != null)
{
	sqlTable.TableName = new( tableName    ?? sqlTable.TableName.Name,
		Server  : serverName   ?? sqlTable.TableName.Server,
		Database: databaseName ?? sqlTable.TableName.Database,
		Schema  : schemaName   ?? sqlTable.TableName.Schema);

	//set alias table if using remote table name
	if (!string.IsNullOrEmpty(serverName))
		sqlTable.Alias = sqlTable.TableName.Name;
}
```

and in source file: \Source\LinqToDB\SqlProvider\BasicSqlOptimizer.cs
if I change line 3016:


```
if ((tableSource!.Source is SqlTable || updateStatement.Update.Table != null))
{
	tableSource.Alias = "$F";
}

```
to:

```
if ((tableSource!.Source is SqlTable || updateStatement.Update.Table != null))
{

	//change alias only if alias is not already setted for sqltable source
	if (!(tableSource!.Source is SqlTable) || string.IsNullOrEmpty(((SqlTable)tableSource.Source).Alias))
		tableSource.Alias = "$F";
}
```

then generated update sql for original question in this post  is: 
```
UPDATE
	D_EQUIPMENTS@CENTSIF D_EQUIPMENTS_1
SET
	D_EQUIPMENTS_1.ISID = :ISID
WHERE
	D_EQUIPMENTS_1.ID = :ID
```
as I would expect.

So this is solution for me now, but I don't know am I using this wrong or is this ok implementation in all other cases which maybe I am not currently aware of.

**Comment by jods4** [comment]
The first part of this change doesn't seem right to me. 
Unless there's some post-processing later, forcing an alias naïvely like this will run into errors.
For example, if the request joins the same remote table twice, they would be assigned the same alias, which must be different.

**Comment by sdanyliv** [comment]
Fixing this issue is not easy task, I would expect @MaceWindu will handle that during weekend.

**Comment by MaceWindu** [comment]
Ah Oracle-way... "Let's do everything our way even if it drive everyone crazy"

basically they expect ppl to put server name after column nam like below, but I think it's easier to enable aliases...
```sql
UPDATE
	D_EQUIPMENTS@CENTSIF
SET
	D_EQUIPMENTS.ISID@CENTSIF = :ISID
WHERE
	D_EQUIPMENTS.ID@CENTSIF = :ID
```
