### ISSUE TITLE
NullReferenceException instead of a meaningfull error in PostgreSQL ProviderDetector

### ISSUE THREAD

**Issue by Lexey** [linq2db/linq2db#419]
I have a connection string like <add name="PGSQL" connectionString="<deleted>" providerName="PostgreSQL" /> in the .config file. Then I pass the connection string name to the DataConnection(string) .ctor and get the NRE. Code examination showed that this is due to a swalled exception in the PostgeTools.ProviderDetector followed by return null;
I guess it would be better to do return _postgreSQLDataProvider; from the exception handler in this case.

**Comment by Lexey** [comment]
I do not think that this commit really fixes the problem.

**Comment by ili** [comment]
You are right, wrong number in commit

**Comment by ili** [comment]
@Lexey how can I reproduce this case?

**Comment by Lexey** [comment]
I guess you need to try to use an old version of the PostgeSQL server like 8.2 (I am using GreenPlum which has 8.2 engine).

**Comment by sdanyliv** [comment]
@Lexey, maybe some pull request?

**Comment by jogibear9988** [comment]
i think it's already fixed: https://github.com/linq2db/linq2db/commit/07fd45c10c878124829a5df1e5e74cee64010676

@ili or @sdanyliv : close

**Comment by sdanyliv** [comment]
Closing for now, looks like it is already fixed.
