### ISSUE TITLE
I have to avoid double quates in linq sql text query.

### ISSUE THREAD

**Issue by vishal0909** [linq2db/linq2db#4191]
### Describe your issue
Hello 
I already using with Microsoft SQL server and it is working good.
Now I have to used with same DB and same table with Oracle.
Now I am getting an error column name is not exists. 
Because of They are adding double quetes into coulmn name.

Below is mine Generated query
--  Oracle Oracle11
DECLARE @userName NVarchar2(15) -- String
SET     @userName = 'gerardo@plan.cr'

SELECT
	a.ID,
	a."Posicion",
	a."ID_Foto_Perfil",
	a."Fec_Ultimo_Acceso",
	a."IND_Cedula",
	a."Fec_modificacion",
	a."Modificado_por",
	a."Fec_inclusion",
	a."Incluido_por",
	a."Esta_activo",
	a."Esta_borrado",
	a."Ultima_Empresa_Visitada",
	a."NOM_Apellido",
	a."NOM_Pila",
	a."NOM_Usuario",
	a."Recuento_Errores_Acceso",
	a."TEL_Numero_Confirmado",
	a."TEL_Numero",
	a."Hash_Contrasena",
	a."Invitacion_Pendiente",
	a."Codigo_Seguridad",
	a."Actualizacion_Perfil",
	a."Restablecer_Contrasena",
	a."Correo_Electronico_Confirmado",
	a."Correo_Electronico"
FROM
	DEVFA01.ACUSUARIO a
WHERE
	a."NOM_Usuario" = :userName

How to fixed this issue?

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace: Column name is not exists.
`
`Linq To DB` version: 3.3.0

Database (with version): Oracle 21 C

ADO.NET Provider (with version): System.Data.OracleClient 1.0.8

Operating system: Windows 11

.NET Version: dot net 7.0

**Comment by jods4** [comment]
Linq2db does that to respect your lowercase identifiers: Oracle has case-sensitive schema, the trick is that an unquoted name is always converted to uppercase. A quoted name must match exactly (so be uppercase if that's how you created it).

You can use this settings when initializing linq2db to disable this behavior:
`OracleTools.DontEscapeLowercaseIdentifiers = true;`

**Comment by vishal0909** [comment]
I added `OracleTools.DontEscapeLowercaseIdentifiers = true` but still adding double quotes for columns.
Below is generated query.

```
--  Oracle Oracle12
DECLARE @eventId Int32
SET     @eventId = 1

SELECT
	a.ID,
	a."[Mensaje]",
	a."[SUJETO]"
FROM
	ACPLANTILLA_EMAIL a
WHERE
	a."[ID_EVENTO]" = :eventId


```

Below is code

```
var query = from a in _emailTemplateRepository.Table
                        where a.Event == eventId
                        select new EMailTemplate
                        {
                            ID = a.ID,
                            Message = a.Message,
                            Subject = a.Subject,
                        };
            return await query.FirstOrDefaultAsync();
```

Below is my domain. Is it any key word issues?

```
 /// <summary>
    /// Represents a Email template
    /// </summary>
    [Table("ACPLANTILLA_EMAIL")]
    public class EMailTemplate : BaseEntity
    {
        [Column("[ID_EVENTO]")]
        public int Event { get; set; }
        [Column("[SUJETO]")]
        public string Subject { get; set; }
        [Column("[SUJETO_EN]")]
        public string Subject_EN { get; set; }
        [Column("[Mensaje]")]
        public string Message { get; set; }
        [Column("[MENSAJE_EN]")]
        public string Message_EN { get; set; }
        [Column("[ES_PUBLICO]")]
        public bool IsPublic { get; set; }
        [Column("ESTA_BORRADO")]
        public bool IsDeleted { get; set; }
        [Column("ESTA_ACTIVO")]
        public bool IsActive { get; set; }
        [Column("INCLUIDO_POR")]
        public int CreatedUserID { get; set; }
        [Column("FEC_INCLUSION")]
        public DateTime CreatedDate { get; set; }
        [Column("MODIFICADO_POR")]
        public int ModifiedUserID { get; set; }
        [Column("FEC_MODIFICACION")]
        public DateTime ModifiedDate { get; set; }
    }
```
