### ISSUE TITLE
ThrowKeyNotFoundException with latest MariaDB 10.11.3 on debian 12

### ISSUE THREAD

**Issue by SoftwareMagicIT** [linq2db/linq2db#4207]
### Describe your issue

Linq To DB` version: latest (5.2.2)

Database MariaDB 10.11.3 on Debian 12

Operating system: Windows 11,

.NET Version: .Net Framework 4.8

 in System.ThrowHelper.ThrowKeyNotFoundException()
   in System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   in MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   in MySql.Data.MySqlClient.NativeDriver.<GetColumnDataAsync>d__52.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in MySql.Data.MySqlClient.NativeDriver.<GetColumnsDataAsync>d__51.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.Driver.<GetColumnsAsync>d__89.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.ResultSet.<LoadColumnsAsync>d__63.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.ResultSet.<InitializeAsync>d__13.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.ResultSet.<CreateResultSetAsync>d__11.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.Driver.<NextResultAsync>d__84.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in MySql.Data.MySqlClient.MySqlDataReader.<NextResultAsync>d__97.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in MySql.Data.MySqlClient.MySqlDataReader.<CloseAsync>d__36.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.MySqlCommand.<ResetReaderAsync>d__99.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__107.MoveNext()
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   in LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   in LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
   in LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   in LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__12`1.MoveNext()
   in System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

Before upgrade system, my application working without issue

**Comment by MaceWindu** [comment]
MySql.Data doesn't support mariadb. You should use MySqlConnector provider

**Comment by MaceWindu** [comment]
I suspect you also upgraded MariaDB. Don't remember exact version, but MariaDB versions starting from ~10.8 will not work with MySql.Data

**Comment by SoftwareMagicIT** [comment]
Yes, changed with MysqlConnector issue solved!! Thank you very much!!
