### ISSUE TITLE
Merge CTE support broken when `inserted`/`deleted` columns are inferred

### ISSUE THREAD

**Issue by viceroypenguin** [linq2db/linq2db#4213]
### Describe your issue

When writing a MERGE statement that has a CTE as a destination table, and when no columns are explicitly specified for the destination table (e.g. when only using `Where`), then the columns selected are missing ones needed for the `Output` clause.

(related to #4107)

### Steps to reproduce

(copying from `MergeIntoCteIssue4107()`)
```cs
	var updatedRows = db.Person.Where(x => x.FirstName == "unknown").AsCte()
		.Merge()
			.Using(db.Child)
			.On((dest, src) => dest.ID == src.ChildID)
				.UpdateWhenMatched((dest, temp) => new Model.Person()
				{
					MiddleName = "unpdated"
				})
			.MergeWithOutput((a, d, i) => i.Gender);
```

### Incorrect SQL generated

```sql
WITH [CTE_1] ([ID], [MiddleName])
AS
(
	SELECT
		[x].[PersonID],
		[x].[MiddleName]
	FROM
		[Person] [x]
	WHERE
		[x].[FirstName] = N'unknown'
)
MERGE INTO [CTE_1] [Target]
USING (
	SELECT
		[t1].[ChildID]
	FROM
		[Child] [t1]
) [Source]
(
	[ChildID]
)
ON ([Target].[ID] = [Source].[ChildID])

WHEN MATCHED THEN
UPDATE
SET
	[Target].[MiddleName] = N'unpdated'

OUTPUT
	[INSERTED].[Gender]
```

### Expected CTE clause

```sql
WITH [CTE_1] ([ID], [MiddleName], [Gender])
AS
(
	SELECT
		[x].[PersonID],
		[x].[MiddleName],
		[x].[Gender]
	FROM
		[Person] [x]
	WHERE
		[x].[FirstName] = N'unknown'
)
```

### Workaround

Add self-checks in the `.On(...)` clause. (ex: `dst.Gender == dst.Gender`)

### Environment details

* `Linq To DB` version: 5.2.2
* Database (with version): Azure Managed SQL Instance
* ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.1.1
* Operating system: Windows 11 Professional
* .NET Version: 7.0

**Comment by MaceWindu** [comment]
Fixed in `6.0.0-preview.1`
