### ISSUE TITLE
"e.Field is not a field" while trying to execute Any() method when at POCO object and there is ignore property specified via fluent mapping

### ISSUE THREAD

**Issue by Namankevi4** [linq2db/linq2db#4215]
HI!
I faced with problem while trying to execute Any() on query and POCO object has ignore property specified via fluent mapping. Count() method works fine but Any() crashes with Exception: "e.Field is not a field". In Any() method I don't use ignore properties in scope of condition

Linq To DB` version: *5.1.1*

SQL Server 2022

.NET Version: 4.8.2

**Comment by MaceWindu** [comment]
Please provide more details: mappings, query

**Comment by MaceWindu** [comment]
No details provided, closing
