### ISSUE TITLE
Linq2db reads columns not in order they were selected.

### ISSUE THREAD

**Issue by k0tarak** [linq2db/linq2db#4218]
I use CommandBehavior.SequentialAccess.
Query below cause exception `System.InvalidOperationException: Invalid attempt to read from column ordinal '1'.  With CommandBehavior.SequentialAccess, you may only read from column ordinal '2' or greater.`
```
var result = await DataContext.Tests
  .LeftJoin(DataContext.Tests,
	  (t1, t2) => t1.Id == t2.Id,
	  (t1, t2) => new { T1 = t1, T2 = t2 })
  .InnerJoin(DataContext.Tests,
	  (t12, t3) => t12.T1.Id == t3.Id,
	  (t12, t3) => new { T1 = t12.T1, T2 = t12.T2, T3 = t3 })
  .ToListAsync();
```

DataContex and table definition:
```
Table(Name = "Test")]
public class TestDataObject
{
	[Column("Id"), PrimaryKey, NotNull]
	public int Id { get; protected internal set; }
}

public ITable<TestDataObject> Tests => this.GetTable<TestDataObject>();
```

Table creation\initialization:
```
Create table Test
(
	Id int primary key
)
insert into test (Id) values (1)
```

Result sql query looks like:
```
SELECT
	[t1].[Id],
	[t2].[Id],
	[t3].[Id]
FROM
	[Test] [t1]
		LEFT JOIN [Test] [t2] ON [t1].[Id] = [t2].[Id]
		INNER JOIN [Test] [t3] ON [t2].[Id] = [t3].[Id]
```
I expect that linq2db reads first [t1].[Id] column, second [t2].[Id] column, third [t3].[Id] column.
But in fact, the reading order is different, not compatible with CommandBehavior.SequentialAccess.
I tried to change T1, T2, T3 order in `new { T1 = t12.T1, T2 = t12.T2, T3 = t3 }`, but that doesn't help. 

`Linq To DB` version: *5.2.2*, *4.2.0*

Database (with version): *Microsoft SQL Server 2017 (RTM-CU31-GDR) (KB5021126) - 14.0.3460.9 (X64)*

ADO.NET Provider (with version): *System.Data.SqlClient 4.8.5*

Operating system: *win 10 22H2 19045.3208*

.NET Version: *netstandard2.0*

**Comment by MaceWindu** [comment]
Have you enabled `OptimizeForSequentialAccess` option?
```cs
Configuration.OptimizeForSequentialAccess = true;
```

**Comment by MaceWindu** [comment]
No response from reporter
