### ISSUE TITLE
Information&help: async queries

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#422]
How should I transform the standard query to make it asynchronous ?

```csharp
public static List<Product> All()
{
  using (var db = new DbNorthwind())
  {
    var query = from p in db.Product
                where p.ProductID > 25
                orderby p.Name descending
                select p;
    return query.ToList();
  }
}
```
Am I supposed to look at [AsyncExtensions.cs](https://github.com/linq2db/linq2db/blob/7cb932bcef6c5533e3a04a094b33959caff02d49/Source/AsyncExtensions.cs) or is there something else in the wiki/doc?

**Comment by giuliohome** [comment]
I see that there is `ToListAsync` when using `LinqToDB`

**Comment by ronnyek** [comment]
I think this is something that would have to be specific based on the db provider... since thats where most of the async stuff would be advantageous.. Last I looked, in oracle they basically did their async stuff exactly like this.

**Comment by ronnyek** [comment]
BTW, if I thought that the pull requests would be accepted, I'd be more than happy to start making some of these adjustments and issue a pull request... seems like this project is kind of little spurts of activity, and with primary author intermittently working on 'v2' hard to know where I'd need to begin my work.

**Comment by giuliohome** [comment]
@ronnyek Where did you look at an Oracle async implementation that it is wasting a task as shown above? ^-^

Btw
I guess the point is that the true async implementation is defined here (when supported by db providers):

`#if !NOASYNC`

like in [DataReaderAsync](https://github.com/linq2db/linq2db/blob/master/Source/Data/DataReaderAsync.cs) or [DataConnection.Async](https://github.com/linq2db/linq2db/blob/master/Source/Data/DataConnection.Async.cs).

In that case _there should be no wasted task_ (blocked in backround, waiting for an operation to be completed) - as expected.

As an example of a different ORM, look at [Insight.Database](https://github.com/jonwagner/Insight.Database/blob/04bcf2a2ad4ea08f6c6722b791d646aa467341ac/Insight.Database/Reliable/ReliableCommand.cs#L81-L90) where you see an
`#if NODBASYNC`
followed by a comment
`// fallback to calling execute reader in a blocking task`
