### ISSUE TITLE
Issue with Converting NVarchar Date Strings for Month Comparison in Linq2db

### ISSUE THREAD

**Issue by BenKmann** [linq2db/linq2db#4226]
I am having an issue with a conversion. I have a column of type NVarChar in the database where a date is stored as a string.

To be able to work on it anyway, I have the following code in the PropertyBuilder:

```c#
birthdayPropertyBuilder.HasDataType(DataType.NVarChar)
					   .HasLength(11)
					   .IsNullable(true)
					   .HasConversionFunc(s => s.Value.ToString("MM-dd-yyyy"),					                                         
										  dt => DateTime.TryParseExact(dt, "MM-dd-yyyy", null, DateTimeStyles.None, out var result) ? result : null,
										  false)
					   .HasColumnName(fieldInfo.LogicalName);
```

Reading and writing work wonderfully with this ConversionFunc.

Query
```c#
where adr.Birthday == DateTime.Today
```

```sql
DECLARE @Today NVarChar(11) -- String
SET     @Today = N'07-27-2023'
...
WHERE
	[adr].[BIRTHDAY0] = @Today AND
	...
```

However, if I want to compare in Linq not against a date, but against the month, I run into a problem. The SQL query does not parse the DB column to datetime, which is necessary in order to use it for "Month".

Query
```c#
where adr.Birthday.Value.Month == DateTime.Now.Month
```

```sql
DECLARE @Month Int -- Int32
SET     @Month = 7
...
FROM
	[ADDRESSES] [adr]
WHERE
	DatePart(month, [adr].[BIRTHDAY0]) = @Month AND
	...
```

But adr.[BIRTHDAY0] is a string field in the format "MM-dd-yyyy" (I have no influence on it, it's a third-party system). So Linq2db seems to forget that a conversion is needed here and I get error number 241 "Conversion failed when converting date and/or time from character string".

As a bug fix, I tried to include a method with Sql.Expression, but this also didn't help and my Sql.Expression is not used.

```c#
[Sql.Expression("CAST ( CASE WHEN ISDATE (SUBSTRING({0},7,4) + SUBSTRING({0}, 1, 2) + SUBSTRING({0}, 4, 2)) = 1 " +
                "THEN (SUBSTRING({0},7,4) + SUBSTRING({0}, 1, 2) + SUBSTRING({0}, 4, 2)) " +
                "ELSE NULL " +
                "END AS DateTime)", PreferServerSide = true, CanBeNull = true)]
public static DateTime? CastBirthdayString(string fieldValue)
{
	return DateTime.TryParseExact(fieldValue, "MM-dd-yyyy", null, DateTimeStyles.None, out var result) ? result : null;
}
```

In the SQL query, the DB column is still not parsed to datetime before it's used for Month and the like.

What could I do to make my query 
```c#
where adr.Birthday.Value.Month == DateTime.Now.Month
```
work in Linq2db with a string column? Also tried HasConversion instead of HasConversionFunc, but that did not change the result.

### Environment details

`Linq To DB` version: *5.2.2*

Database (with version): *Sql Server 2019*

.NET Version: *4.7.2*

**Comment by MaceWindu** [comment]
1. Column converter used to convert values between client and database, not for conversions inside SQL.
2. DatePart works fine with `MM-dd-yyyy` strings, so probably in your case database contains value in other format
3. to extract month from column you can use extension like this:
```cs
// where GetMonth(adr.Birthday.Value) == DateTime.Now.Month

[Sql.Expression("CAST(SUBSTRING({0},1,2) AS INT)", PreferServerSide = true, CanBeNull = true)]
public static int? GetMonth(DateTime date) => throw new InvalidOperationException("Server-side API");
```
