### ISSUE TITLE
Generic way to automatically handle returning a list of tuples

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#423]
I'm executing a select of an int and long with a query. Query<Tuple<int,long>> doesnt work, it just returns a tuple with both values set to default type value. 

Is there a better way to return arbitrary values (no actual POCO representing the data) but still get all the type conversion stuff (because we'd specify types to map)?

**Comment by ronnyek** [comment]
I just used Query() with my own function that returns those said tuples... just dont know if thats the best way

**Comment by Lexey** [comment]
Show your query code, please.
