### ISSUE TITLE
Add support for MySqlConnector  on cli scaffold cli utility

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [linq2db/linq2db#4235]
### Describe your issue

Add support for MySqlConnector  on cli scaffold cli utility

### Steps to reproduce

dotnet linq2db scaffold -p MySqlConnector ...

We need to use MySqlConnector  as provider in cli tools because MySql Oracle Provider cant actualy connect to our server due to bugs on oracle implementation.

All work ok on aplication with use UseMySqlConnector() extension method.

**Comment by MaceWindu** [comment]
What kind of support you need? scaffold tool already use `MySqlConnector` internally

**Comment by CastelloBrancoTecnologia** [comment]
scaffold tool already use MySqlConnector internally

not true. we are geting conection erros that dont ocours with MySqlConnector, only with MySql provider

cli scafold utility only has -p Mysql and we need -p MySqlConector it is a diferent provider

seel list

https://linq2db.github.io/articles/general/databases.html

also see MySqlConector project (not oracle)

https://github.com/mysql-net/MySqlConnector

![image](https://github.com/linq2db/linq2db/assets/138352584/708c09ee-4d3d-42e3-9ae9-c2d610860952)

**Comment by viceroypenguin** [comment]
In your own screenshot, the stack trace shows that `MySqlConnector` is being used. Is it possible the paths to the certificates is not correct for the current location of the commandline?

![image](https://github.com/linq2db/linq2db/assets/1992555/b0357d7d-70d2-4cc2-9573-39948231a9e7)

**Comment by CastelloBrancoTecnologia** [comment]
> " Is it possible the paths to the certificates is not correct for the current location of the commandline? "

No, i checked this

Also the conection works when i convert pem to pfx with openssl in same directory and change the conection string to CertificateFile=./Certificados/client-cert-key-ca.pfx;CertificatePassword=blabla

This is the behavior that ocours with oracle provider (bug with pem files in windows and not with pfxs). MySqlConector woth ok with pem in both linux and windows.

**Comment by MaceWindu** [comment]
If I understand you correclty, issue is not in scaffold, but in connection configuration for generated model on your side. Why you use `UseMySql` instead of `UseMySqlConnector`? `UseMySql` tries to guess provider and defaults to MySql.Data if detection fails. Instead you should use `UseMySqlConnector` wich uses only MySqlConnector

**Comment by cesarchefinho** [comment]
I used UseMySql () in application only to test purpose to confirm that the problem in scafold cli is it not using mysqlconector.

UseMySql () has problems and UseMySqlConnector () not.
l
scaffold cli utility has the same problems of UseMySql()

**Comment by MaceWindu** [comment]
scaffold tool don't even reference MySql.Data and stack trace clearly says exception comes from MySqlConnector code.

I see you use relative path to certificates in connection string. Could you replace them with full path as it is probably resolves agains tool location in nuget cache?

**Comment by cesarchefinho** [comment]
@MaceWindu the problem is not relative-path because if i use the same relative path ./Cesrtficados/ and change only the extension of file to pfx and of course option to use pfx insted pem, it work ok on cli scaffod utility (i have both pem and pfx on dir). the problem is that cli utility is making some thing that wont accep pem files and in my application the UseMySelConnector accept the same pems with the same conection string without any problem.

**Comment by MaceWindu** [comment]
Which version of cli too you use?
`dotnet tool list -g`

**Comment by cesarchefinho** [comment]
> Which version of cli too you use? `dotnet tool list -g`

@MaceWindu , i use dotnet 7.0 latest sdk on my workstation

**Comment by MaceWindu** [comment]
You could try preview version from azure feed (check readme) - it uses MySqlConnector 2.2.6
