### ISSUE TITLE
Wrong sequence of "distinct" and "first N"

### ISSUE THREAD

**Issue by Cybeer1111** [linq2db/linq2db#424]
Hello!

This expression is translated to sql query incorrectly:
`from oph in dataContext.GetEntityService<OperatorCallHistoryEntity>().List
orderby oph.StartDate descending
select oph.TransferPhoneNumber)
.Distinct()
.Take(10)`
translated to 
`SELECT DISTINCT FIRST 10
    t1.TRANSFERPHONENUMBER
FROM
    OPERATORCALLHISTORY t1
ORDER BY
    t1.STARTDATE DESC`
expected that "FIRST 10" will be stand before "DISTINCT". 
I am using Firebird provider, it cannot execute this query.

This code modification workarounds issue:
`from oph in dataContext.GetEntityService<OperatorCallHistoryEntity>().List
orderby oph.StartDate descending
select oph.TransferPhoneNumber).Distinct().Select(e => new {Number = e}).Take(10).Select(e => e.Number)`

**UPDATE**
Workaround is not works - generated SQL code missing order by clause.

**Comment by Eykhler** [comment]
Some modifications in the method BuildSelectClause of the class LinqToDB.DataProvider.Firebird.FirebirdSqlBuilder should fix the issue:
`protected override void BuildSelectClause()
{
  if (SelectQuery.From.Tables.Count == 0)
  {
    AppendIndent();
    StringBuilder.Append("SELECT").AppendLine();
    BuildColumns();
    AppendIndent();
    StringBuilder.Append("FROM rdb$database").AppendLine();
  }
  else if (SelectQuery.Select.IsDistinct)
  {
    AppendIndent();
    StringBuilder.Append("SELECT");
    BuildSkipFirst();
    StringBuilder.Append(" DISTINCT");
    StringBuilder.AppendLine();
    BuildColumns();
  }
  else
    base.BuildSelectClause();
}`

**Comment by Eykhler** [comment]
Question to @ili and @sdanyliv, can you apply these modifications to the FirebirdSqlBuilder?

**Comment by ili** [comment]
I'll do it this weekend
