### ISSUE TITLE
[how to] Change the data storage value according to the database's data type

### ISSUE THREAD

**Issue by libu1129** [linq2db/linq2db#4244]
In sqlserver, the datetime type consumes 8 bytes.
I want to change this to int type and save it as UnixTimestamp type to reduce table capacity.
However, when reading or storing data, I want to use the DateTime type.
How do I implement mapping like this?
Also, if the data type is bigint type in sql server, I want to save it in milliseconds, and if it is int type, I want to save it in seconds

### Environment details

`Linq To DB` version: 

Database (with version): sql server 2017

ADO.NET Provider (with version): 

Operating system: windows

.NET Version: .net 8

**Comment by sdanyliv** [comment]
Looking for [HasConversion](https://github.com/linq2db/linq2db/blob/a2a18fe2815814c6cafea704938d03e09df79d86/Tests/Linq/Linq/ValueConversionTests.cs#L147)?

**Comment by libu1129** [comment]
I solved this incompletely by myself.
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/ValueConversionTests.cs
I used the example above



sealed class DateTimeToIntConverter : ValueConverter<DateTime, int>
{
public DateTimeToIntConverter() : base(v => (int)v.convert_to_unix_time_seconds(), p => p.ConvertFromUnixTimestamp(), true)
{

}
}


sealed class DateTimeToLongConverter : ValueConverter<DateTime, long>
{
public DateTimeToLongConverter() : base(v => v.convert_to_unix_time_miliseconds(), p => p.convert_from_unixtime_miliseconds(), true)
{

}
}



[Table("test_tb")]
public class test_tb
{
    [Column(DataType = DataType.Int32)]
    [ValueConverter(ConverterType = typeof(DateTimeToIntConverter))]
    public DateTime second_dtm { get; set; }


    [Column(DataType = DataType.Int64)]
    [ValueConverter(ConverterType = typeof(DateTimeToLongConverter))]
    public DateTime ms_dtm { get; set; }
}

**Comment by viceroypenguin** [comment]
> In sqlserver, the datetime type consumes 8 bytes.
> 
> I want to change this to int type and save it as UnixTimestamp type to reduce table capacity.

I would challenge the presumption here. The int32 Unix Timestamp will not track any timestamp after 2038. Unless you are certain this is a short term application, it is probably unwise to limit yourself to the int32 Unix Timestamp.
