### ISSUE TITLE
After calling Query, the memory can not be released and it still grows.

### ISSUE THREAD

**Issue by storaid** [linq2db/linq2db#4247]
### Describe your issue

The following is my test code:
```
using var connection = new DataConnection(Linq2DbOptions.GetProviderName(providerName), connectionString);
                    if (output != null)
                    {
                        output.Result = connection.Query<ExpandoObject>(sql).ToArray();
                    }// end if
```
This problem wasted a lot of my time.
the above code is simple..
But I don't know how to solve the problem that after calling Query, the occupied memory cannot be released.
Did I have something missing or wrong?????
### Environment details

`Linq To DB` version: 5.2.2

Database (with version): SQL 2016

ADO.NET Provider (with version): Microsoft.Data.SqlClient

Operating system: Windows 10

.NET Version: Core 6

**Comment by igor-tkachev** [comment]
What is exactly the problem?

**Comment by storaid** [comment]
> What is exactly the problem?
```
output.Result = connection.Query<ExpandoObject>(sql).ToArray();
```
After the execution of this code, the memory usage is quickly growing.
no memory usage was decreased I saw
this code is called by WebAPI

**Comment by sdanyliv** [comment]
Probably because we cache mappers. I assume you always different SQL?
Try to reduce time of keeping cached mapper, currently it is one hour. 

Once somewhere on startup: 
```cs
LinqOptions.CacheSlidingExpirationOrDefault = TimeSpan.FromMinutes(1);
```

**Comment by storaid** [comment]
> Probably because we cache mappers. I assume you always different SQL? Try to reduce time of keeping cached mapper, currently it is one hour.
> 
> Once somewhere on startup:
> 
> ```cs
> LinqOptions.CacheSlidingExpirationOrDefault = TimeSpan.FromMinutes(1);
> ```

I assume you always different SQL? 
YES..
it's dynamic SQL from customer assigned...

**Comment by storaid** [comment]
> ```cs
> LinqOptions.CacheSlidingExpirationOrDefault
> ```
```
LinqOptions.CacheSlidingExpirationOrDefault = TimeSpan.FromMinutes(1);
```
How can I set this property???
I don't see it in LinqOptions..

**Comment by sdanyliv** [comment]
```cs
LinqToDB.LinqOptions.CacheSlidingExpirationOrDefault = TimeSpan.FromMinutes(1);
```

**Comment by storaid** [comment]
> Sorry may fault.
> 
> ```cs
> LinqToDB.Common.Configuration.Linq.CacheSlidingExpiration = TimeSpan.FromMinutes(1);
> ```
hello,
it's global option for all data connection????

**Comment by storaid** [comment]
it's not working...:(
Program.cs
```
LinqToDB.Common.Configuration.Linq.CacheSlidingExpiration = TimeSpan.FromSeconds(5);
LinqToDB.Common.Configuration.Linq.DisableQueryCache = true;
builder.Services.AddLinqToDBContext<WKCDbConnection>((provider, options) =>
{
    return options
        .UseSqlServer(configuration.GetConnectionString("WKCConnectionString")!)
        .UseDefaultLogging(provider)
        .UseCacheSlidingExpiration(TimeSpan.FromHours(1))
        .UseDisableQueryCache(false);
});
```
ExpandoDatabaseHandler
```
    using Attributes;
    using System.Dynamic;
    using System.Text;
    using AUO.DataMart.WebAPI.App_Lib.Data.Linq2Db;
    using LinqToDB.Data;
    using AUO.DataMart.WebAPI.App_Lib.Extensions;
    using LinqToDB.Mapping;
    using LinqToDB;

    [HandlerKey("DB")]
    public class ExpandoDatabaseHandler
        : DatabaseHandlerBase
    {
        private readonly DefaultHandlerProviderFactory _handlerProviderFactory;

        public ExpandoDatabaseHandler(DatabaseHandlerContext context, DefaultHandlerProviderFactory handlerProviderFactory)
            : base(context)
        {
            _handlerProviderFactory = handlerProviderFactory;
        }

        public override async Task<IHandlerOutput?> ProcessAsync(IHandlerInput input)
        {
            if (input is DatabaseHandlerInput databaseInput)
            {
                var output = _handlerProviderFactory.CreateOutput<DatabaseHandlerOutput>() as DatabaseHandlerOutput;
                IEnumerable<ExpandoObject> result = Enumerable.Empty<ExpandoObject>();
                string? options = databaseInput.Options;
                string? content = databaseInput.Content;
                string? providerName = "";
                string? connectionString = "";
                if (!string.IsNullOrWhiteSpace(options))
                {
                    byte[] jsonByte = Encoding.UTF8.GetBytes(options);
                    using var ms = new MemoryStream(jsonByte);
                    var connectionSettings = await JsonSerializer.DeserializeAsync<Linq2DbConnectionSettings>(ms);
                    if (connectionSettings != null)
                    {
                        providerName = connectionSettings.ProviderName;
                        connectionString = connectionSettings.ConnectionString;
                    } // end if
                } // end if
                if (!string.IsNullOrWhiteSpace(content) &&
                    !string.IsNullOrWhiteSpace(providerName) &&
                    !string.IsNullOrWhiteSpace(connectionString))
                {
                    string sql = content;
                    var connection = new DataConnection(Linq2DbOptions.GetProviderName(providerName), connectionString);
                    if (output != null)
                    {
                        using (connection)
                        {
                            output.Result = connection.Query<ExpandoObject>(sql).ToArray();
                        } // end using
                    }// end if
                } // end if
                //
                return output;
            } // end if
            return null;
        }
    }
```

**Comment by storaid** [comment]
it's possible to avoid any caching???
because sometimes we have ~1 millions data loading....
I don't wan it that will cause a crazy memory consumption...

**Comment by storaid** [comment]
I am not sure...
I have no memory profiler to check..
but looks like the following code is working...
```
if (!string.IsNullOrWhiteSpace(content) &&
                    !string.IsNullOrWhiteSpace(providerName) &&
                    !string.IsNullOrWhiteSpace(connectionString))
                {
                    string sql = content;
                    using var connection = new DataConnection(
                        Linq2DbOptions.GetProviderName(providerName),
                        connectionString,
                        options =>
                        {
                            return options
                                    .UseCacheSlidingExpiration(TimeSpan.FromSeconds(3))
                                    .UseDisableQueryCache(true);
                        });
                    if (output != null)
                    {
                        output.Result = connection.Query<ExpandoObject>(sql).ToArray();
                    }// end if
                } // end if
```
however, memory usage keeps growing even after freeing 30~40% of memory... :(

**Comment by aloksharma1** [comment]
> I am not sure... I have no memory profiler to check.. but looks like the following code is working...
> 
> ```
> if (!string.IsNullOrWhiteSpace(content) &&
>                     !string.IsNullOrWhiteSpace(providerName) &&
>                     !string.IsNullOrWhiteSpace(connectionString))
>                 {
>                     string sql = content;
>                     using var connection = new DataConnection(
>                         Linq2DbOptions.GetProviderName(providerName),
>                         connectionString,
>                         options =>
>                         {
>                             return options
>                                     .UseCacheSlidingExpiration(TimeSpan.FromSeconds(3))
>                                     .UseDisableQueryCache(true);
>                         });
>                     if (output != null)
>                     {
>                         output.Result = connection.Query<ExpandoObject>(sql).ToArray();
>                     }// end if
>                 } // end if
> ```
> 
> however, memory usage keeps growing even after freeing 30~40% of memory... :(
> 
> sql data:100000 ~ 120000 rows, 140 ~ 170 columns

a suggestion you can use pagination instead of fetching thousand or millions of rows?

**Comment by to11mtm** [comment]
> sql data:100000 ~ 120000 rows

This alone will cause Large Object Heap (LOH) allocations of the returned `List`s/etc.

Anything over ~85,000 bytes will wind up in LOH, and in general LOH collection can be pretty finicky. (mostly because LOH collection tends to be a last resort, and LOH does not get compacted except in containers or with specific flags set, such as `System.GC.HeapHardLimit` in runtimeconfig.json. [This link does a decent job of explaining the LOH and implications of the LOH not being compacted normally.](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap)

on 32 bit systems, this means Arrays/Lists/etc with over ~21,000 entries wind up in LOH. On 64 bit systems it's more like ~10,500 entries.

If I recall correctly (and I could very well be misremembering), system memory usage, i.e. what is reported by OS/etc can stay stuck at a fairly high number when the right (wrong?) conditions get hit with the large object heap.

It's a bit of a rabbit hole due to the way the Allocator/GC works with segments, as well as the interesting behavior of some environments[0]

[0] - fun fact, Hosting in IIS, even with a .NET core app, causes IIS to be *very* hesitant to release segments. In one app I worked on, the sysadmins set an IIS process limit and the app couldn't collect memory fast enough when it got the 'warning', so it would restart instead. Setting the `HeapHardLimit` made the problem go away with no ill side effects.

**Comment by storaid** [comment]
> > sql data:100000 ~ 120000 rows
> 
> This alone will cause Large Object Heap (LOH) allocations of the returned `List`s/etc.
> 
> Anything over ~85,000 bytes will wind up in LOH, and in general LOH collection can be pretty finicky. (mostly because LOH collection tends to be a last resort, and LOH does not get compacted except in containers or with specific flags set, such as `System.GC.HeapHardLimit` in runtimeconfig.json. [This link does a decent job of explaining the LOH and implications of the LOH not being compacted normally.](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap)
> 
> on 32 bit systems, this means Arrays/Lists/etc with over ~21,000 entries wind up in LOH. On 64 bit systems it's more like ~10,500 entries.
> 
> If I recall correctly (and I could very well be misremembering), system memory usage, i.e. what is reported by OS/etc can stay stuck at a fairly high number when the right (wrong?) conditions get hit with the large object heap.
> 
> It's a bit of a rabbit hole due to the way the Allocator/GC works with segments, as well as the interesting behavior of some environments[0]
> 
> [0] - fun fact, Hosting in IIS, even with a .NET core app, causes IIS to be _very_ hesitant to release segments. In one app I worked on, the sysadmins set an IIS process limit and the app couldn't collect memory fast enough when it got the 'warning', so it would restart instead. Setting the `HeapHardLimit` made the problem go away with no ill side effects.

you are right...
the problem is about GC...
I'm trying to implement lazy-loading...
but it's not luck...

**Comment by storaid** [comment]
> Sorry may fault.
> 
> ```cs
> LinqToDB.Common.Configuration.Linq.CacheSlidingExpiration = TimeSpan.FromMinutes(1);
> ```

hello, 
I'm trying to implement lazy-loading...
but it's not luck...
the following simple code:
```
output.Result = _internalConnection.Query<ExpandoObject>(sql).AsQueryable();
                        output.Result.Any();
                        output.Result.Any();
```
1st call: Any => successful
2nd call: Any => throw exception "Object reference not set to an instance of an object."
how can I implement lazy-loading??

**Comment by to11mtm** [comment]
> > Sorry may fault.
> > ```cs
> > LinqToDB.Common.Configuration.Linq.CacheSlidingExpiration = TimeSpan.FromMinutes(1);
> > ```
> 
> hello, I'm trying to implement lazy-loading... but it's not lucky... the following simple code:
> 
> ```
> output.Result = _internalConnection.Query<ExpandoObject>(sql).AsQueryable();
>                         output.Result.Any();
>                         output.Result.Any();
> ```
> 
> 1st call: Any => successful 2nd call: Any => throw exception "Object reference not set to an instance of an object." how can I implement lazy-loading??

Calling `.Result` twice may or may not be supported.

But Lazy loading may or may not solve your problem, it's hard to say without more information.

As far as 'beating the GC'... *IF* you don't need to call items by index, you can use `foreach` on the query result to place the items into some collection type that won't cause the same sorts of GC issues. Note that there may be tradeoffs for such types. Namely, they often do not support retrieving by index. The best option would be an 'Unrolled Linked List', but I don't know of one written for C# that has proper tests around it. (I have a public GIST of one, but I have not written tests around it.)

If you don't need Indexing operations, `LinkedList<T>` is one option, so is `ConcurrentQueue<T>`. You may want to benchmark both; `LinkedList<T>` doesn't involve volatile or CAS type operations, but will allocate a bit more per item and doesn't have some of the locality benefits of `ConcurrentQueue<T>`. 

That said, here's an example of a way to stuff the results of a `Query<T>()` into a ConcurrentQueue, adapting it to other types would be trivial;

```
    public static class DataConnectionLargeSetExtensions
    {
        //Add other overloads as desired for query with args, etc.
        public static IReadOnlyCollection<T> MaterializeLargeSetAsReadOnlyCollection<T>(
            this DataConnection dc, string sql)
        {
            var returnSet = new ConcurrentQueue<T>();
            foreach (var item in dc.Query<T>(sql))
            {
                returnSet.Enqueue(item);
            }

            return returnSet;
        }
    }
```

**Comment by EmaX093** [comment]
I suppouse was bitten by this, upgraded from linq2db 4.4.1 to 5.2.2 and my web app grows from 500mb to 4GB  memory ram usage in 1 hour or so, and keep growing until collapse and throws 502 timeout. Rolling back to 4.4.1 and now works perfectly.

**Comment by to11mtm** [comment]
Anyone running into this issue running .NET Core 3.1 or newer and running into this (especially on IIS), can you try [setting the GC Hard Heap Limit](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-limit) to something that is sensible for your use case? e.x. if your app is normally consuming 500mb but is now ballooning to 4GB, you can try setting the heap limit to 1GB. It may (or may not) fail sooner/later/not-at-all depending on what's going on.

**Comment by MaceWindu** [comment]
I will close it for now.

- in v6 there were some improvements implemented to avoid unnecessary data stuck in cache
- to investigate issues like that we need details from memory profiler or standalone isolated test case ther demonstrate issue
