### ISSUE TITLE
Dynamic column name in a query

### ISSUE THREAD

**Issue by zgandrew** [linq2db/linq2db#425]
Need help with getting a dynamic column name in a such peice of code:

var search_words = search_word.Split(' ').ToList();
IQueryable<cv70_personals_catalog> users_db_ls = db.cv70_personals_catalog;
                
search_words.ForEach(sw=>{
users_db_ls = users_db_ls.Where(x =>    
       x.GetType().GetProperty(field_name).GetValue(x).ToString().Contains(sw));
});

////////////////////
it craches with exception 
LinqToDB.Linq.LinqException: 'x.GetType().GetProperty(value(CarService.Core.SmartSearch+<>c__DisplayClass3).field_name).GetValue(x)' cannot be converted to SQL.

////////
Is there is a way out?

**Comment by jogibear9988** [comment]
Try using dynamic linq:

https://github.com/StefH/System.Linq.Dynamic.Core

you cannot use reflection in iqueryable expressions

Von meinem iPhone gesendet

**Comment by zgandrew** [comment]
Wow great, it is what I need,
Great Tnx!

**Comment by jogibear9988** [comment]
close?

**Comment by zgandrew** [comment]
Yea perfect, here is sollution with using System.Linq.Dynamic;

        public void Search<T>(string field_name, string search_word)
        {
            CleanResults();

            using (var db = dbContext) 
            {
                search_words = search_word.Split(' ').ToList();
                IQueryable users_db_ls = (ITable <T>) db.GetType().GetProperty(typeof(T).Name).GetValue(db, null);

                search_words.ForEach(sw =>
                {
                    users_db_ls = users_db_ls.Where(field_name+".Contains(@0)", sw);
                });

                users_db_ls = users_db_ls.Take(20);

                results_set = users_db_ls.ToDynamicArray().ToList<object>();
            }

            Sort<T>(field_name);
            Print<T>(field_name);
        }
