### ISSUE TITLE
Update nuget version up-to 1.0.7.5

### ISSUE THREAD

**Issue by forcewake** [linq2db/linq2db#427]
Hello.

Could you please push the latest version to the nuget?
Currently the latest version on https://www.nuget.org/packages/linq2db/ 1.0.7.4 
Also it will be cool if will have time to upload latest Oracle package to nuget.

Thanks.

**Comment by sdanyliv** [comment]
@ili, can we close this?

**Comment by ili** [comment]
Certainly
