### ISSUE TITLE
[HOW TO] Return pipelined table from function

### ISSUE THREAD

**Issue by gpgpublickey** [linq2db/linq2db#4272]
Hi guys, I need some help with this:

We have this function inside of a package:
```
FUNCTION foo(p1_arg_type IN VARCHAR2,
                       p1_arg      IN VARCHAR2,
                       p2_arg_type IN VARCHAR2,
                       p2_arg      IN VARCHAR2) RETURN foo_tbl PIPELINED;
```

Is this supported by linq2db? Any example about how I need to call this function using PLSQL to pull the results?

Thanks

**Comment by MaceWindu** [comment]
I've checked what PIPELINED function means and currently don't see any difference from regular table function in terms of mapping. Do you have any issues with regular table function mapping?

@jods4 maybe you know anything about it?

**Comment by gpgpublickey** [comment]
@MaceWindu the way to handle table functions worked, thx
