### ISSUE TITLE
Inserting Dictionary into Table

### ISSUE THREAD

**Issue by mercurial-moon** [linq2db/linq2db#4277]
Is it possible to insert a Dictionary as a row into a Table

sample code
```

IDictionary<string, object> dict = new Dictionary<string, object>(){
{"id" = null}, // <- identity field with same name in table
{"result" = false}
};

db.InsertWithIdentity(dict, "myTable"); // <- Error here: "Identity Field must be defined for "mytable"

```
I tried with `"id" = null` and even without it but same result.

**Comment by pbanerji17** [comment]
Hi @mercurial-moon , 

Are you trying to add through EF ?

In EF, it expects the entities to be strongly typed and with Dictionary its not the case.

But you can insert the Dictionary object by converting it to the JSON/XML format and then adding the format in database table.

Do let me know if you need any help in this?

**Comment by mercurial-moon** [comment]
@pbanerji17 was using linq2db without EF, target db is postgres.
usually i would create a class and tag it with a `[Table("sametable")]` attribute.
However I was looking at a generic method where I don't want to make classes for each target table where I want to insert data into.
So was looking at the dictionary option.

**Comment by MaceWindu** [comment]
Such functionality is not supported.
Closest option is to define helper method, which will generate query like this one using dynamic properties: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/DynamicColumnsTests.cs#L29C17-L33

**Comment by MaceWindu** [comment]
Also, currently we don't have plans to support such API in linq2db directly, but we are open for PRs to linq2db.tools project with such helpers

**Comment by mercurial-moon** [comment]
thanks for the detailed explanation.
