### ISSUE TITLE
EasyLOB, an Archetype for LOB Applications

### ISSUE THREAD

**Issue by EasyLOB** [linq2db/linq2db#430]
Thanks for creating LINQ to DB!
I just published EasyLOB, an Open Source Archetype for building ASP.NET MVC LOB Application, at GitHub:

https://github.com/EasyLOB/EasyLOB/wiki

LINQ to DB is one of the Database APIs EasyLOB uses under a Unit of Work/Repository Pattern:

https://github.com/EasyLOB/EasyLOB/wiki/Archetype

https://github.com/EasyLOB/EasyLOB/wiki/EasyLOB-Standard-Libraries

**Comment by ili** [comment]
You are welcome :)
