### ISSUE TITLE
Caching issue with LambdaExpression.Compile within expression

### ISSUE THREAD

**Issue by Shane32** [linq2db/linq2db#4300]
### Describe your issue

When using `lambdaExpression.Compile()(param)` within a `Where` expression, the query executes fine the first time, but subsequent executions use cached search keywords instead of newly supplied ones.  Examining the SQL sent to the database, it can be seen that the old value is used instead of the new value.

### Steps to reproduce

```c#
using System;
using System.Linq;
using System.Linq.Expressions;

using LinqToDB;
using LinqToDB.Mapping;

using NUnit.Framework;

namespace Tests.UserTests
{
	[TestFixture]
	public class Issue4300Tests : TestBase
	{
		[Table("TABLE1")]
		public class Table1
		{
			[Column("ID1"), PrimaryKey, NotNull] public int Id1 { get; set; }
			[Column("NAME1"), Nullable] public string? Name1 { get; set; }
		}

		[Table("TABLE2")]
		public class Table2
		{
			[Column("ID2"), PrimaryKey, NotNull] public int Id2 { get; set; }
			[Column("TABLE1ID"), NotNull] public int Table1Id { get; set; }
		}

		[Test]
		public void ExpressionCompileTest([IncludeDataSources(TestProvName.AllSqlServer2008Plus)] string context)
		{
			using var db = GetDataContext(context);
			using var tbl1 = db.CreateLocalTable(new[]
			{
				new Table1 { Id1 = 1, Name1 = "Some1" },
				new Table1 { Id1 = 2, Name1 = "Some2" },
			});
			using var tbl2 = db.CreateLocalTable(new[]
			{
				new Table2 { Id2 = 10, Table1Id = 1 },
				new Table2 { Id2 = 20, Table1Id = 2 },
			});

			TestMe("Some1", 10); // works correctly
			TestMe("Some2", 20); // fails with error that 10 was received instead of 20 (unless above line is commented out)
			
			void TestMe(string str, int expectedTable2Id)
			{
				Expression<Func<Table1, bool>> expr = t => t.Name1 == str;
				//var query1 = tbl1.Where(expr).Select(row1 => row1.Id1); //works
				var query1 = tbl1.Where(row1 => expr.Compile()(row1)).Select(row1 => row1.Id1); //doesn't work
				var query2 = tbl2.Where(row2 => query1.Contains(row2.Table1Id)).Select(row2 => row2.Id2);
				var ret = query2.ToList();
				Assert.AreEqual(1, ret.Count);
				Assert.AreEqual(expectedTable2Id, ret[0]);
			}
		}
	}
}
```

### Sample SQL queries generated

Below is the SQL that is generated for `TestMe("Some1", 10)` and incorrectly generated for `TestMe("Some2", 20)`.

```sql
-- SqlServer.2017
DECLARE @str NVarChar(4000) -- String
SET     @str = N'Some1'

SELECT
	[row2].[ID2]
FROM
	[TABLE2] [row2]
WHERE
	[row2].[TABLE1ID] IN (
		SELECT
			[row1].[ID1]
		FROM
			[TABLE1] [row1]
		WHERE
			[row1].[NAME1] = @str
	)
```

### Expected SQL for second execution

```sql
-- SqlServer.2017
DECLARE @str NVarChar(4000) -- String
SET     @str = N'Some2'

SELECT
	[row2].[ID2]
FROM
	[TABLE2] [row2]
WHERE
	[row2].[TABLE1ID] IN (
		SELECT
			[row1].[ID1]
		FROM
			[TABLE1] [row1]
		WHERE
			[row1].[NAME1] = @str
	)
```

### Diagnostic notes

During the first execution, I can see a breakpoint hit at `ExpressionTreeOptimizationContext.cs:687` where the `LambdaExpression.Compile` method is processed.  During the second execution, the breakpoint does not get hit.

If the test is simplified to remove `tbl2`, then the code hits `ExpressionTreeOptimizationContext.cs:257` (instead of line 687) for each execution and the test passes.

### Workarounds

Manipulating the expression tree to remove the call to `lambdaExpression.Compile` fixes the problem.  This can always be done, but using `Compile` can simplify development in certain scenarios.  Note that the above test is simplified to demonstrate the problem, not a practical need for `lambdaExpression.Compile`.

### Environment details

`Linq To DB` version: 5.2.1 and newer (tested on `master` as of 10/10/2023)

Database (with version): Azure SQL Server Managed Instance

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.1.1

Operating system: Windows 10 Pro

.NET Version: .NET 6

**Comment by MaceWindu** [comment]
Not an easy fix with current parser, but we expect for it to work out-of-box with new parser, so I will assign it to v6

**Comment by MaceWindu** [comment]
That was fixed in new parser in preview.1
