### ISSUE TITLE
Chat for questions

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#4307]
### Describe your issue

As I now started to work on #3993, I noticed that the slack channel for linq2db is gone.
Is there another way to ask questions, or are the issues the only one?

For example I wanted to know whats the purpose of "SkipPathThrough" wich removes "Methods.LinqToDB.SqlExt.ToNotNull" wich leads to a Property Access of "Milliseconds" on a Nullable<TimeSpan> in my query wich is not there. If I remove it, the query will be generated (still wrong and not working, but maybe thats another issue)

**Comment by viceroypenguin** [comment]
> As I now started to work on https://github.com/linq2db/linq2db/issues/3993, I noticed that the slack channel for linq2db is gone.

We moved to Discord. Join us: https://discord.gg/PcV6pTXt4s
