### ISSUE TITLE
Invalid SQL generated through UpdateWithOutput() for PostgreSQL and SQLite

### ISSUE THREAD

**Issue by hami89** [linq2db/linq2db#4328]
### Describe your issue

I am trying to use the ```UpdateWithOutputAsync()``` / ```UpdateWithOutput()``` methods to update a table and retrieve information about the changed rows in a table.

For my test I am using a table called test, with two integer columns, named "a" and "b". I inserted two rows.

I repeated the test with SqlServer, PostGgres and SQLite.

I can query and update the rows for all three database kinds, but if I use the ```UpdateWithOutputAsync()``` / ```UpdateWithOutput()```, it generates invalid SQL for PostGres and SQLite. (It works for MS SQL.)

I also tried it with various tables, with similar results.

I would expect these methods to work for all supported database types.

#### PostGres exception:
Exception: Npgsql.PostgresException
Message  : 42P01: missing FROM-clause entry for table "DELETED"

POSITION: 74
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)

#### SQLite exception
Exception: System.Data.SQLite.SQLiteException
Message  : SQL logic error
no such column: DELETED.a
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)

### Steps to reproduce
Create a table with 2 int columns "a", "b" and insert any data

```SQL
CREATE TABLE [grid].[test](
	[a] [int] NULL,
	[b] [int] NULL
);

INSERT INTO [grid].[test] ([a],[b]) VALUES (1,2);
INSERT INTO [grid].[test] ([a],[b]) VALUES (2,6);
```

Map a class to the table in C#.
Query and  simple update works (tested for SqlServer, PostGres and SQLite).
When using the ```UpdateWithOutput()``` method, it works for SqlServer, but it fails for PostGres and SQLite.

Here is the generated SQL for all three of them. SQL2DB generates the DELETED pseudo table based code part for all, but it is not valid in SQLite and PostGres.

#### SqlServer (WORKS) - generated SQL

```SQL
--  SqlServer.2019
DECLARE @i Int -- Int32
SET     @i = 2

UPDATE
        [t1]
SET
        [t1].[b] = Coalesce([t1].[b], 0) + @i
OUTPUT
        [DELETED].[a],
        [DELETED].[b],
        [INSERTED].[a],
        [INSERTED].[b]
FROM
        [grid].[test] [t1]
```

#### PostGres (FAILS) - generated SQL

```SQL
--  PostgreSQL.15 PostgreSQL
DECLARE @i Integer -- Int32
SET     @i = 2

UPDATE
        grid.test
SET
        b = Coalesce(grid.test.b, 0) + :i
RETURNING
        "DELETED".a,
        "DELETED".b,
        grid.test.a,
        grid.test.b
```

#### SQLite (FAILS) - generated SQL

```SQL
--  SQLite.Classic SQLite
DECLARE @i  -- Int32
SET     @i = 2

UPDATE
        [test]
SET
        [b] = Coalesce([test].[b], 0) + @i
RETURNING
        [DELETED].[a],
        [DELETED].[b],
        [test].[a],
        [test].[b]
```

## C# test code

```c#
public class Test
{
    public int a { get; set; }
    public int? b { get; set; }
}

internal class Program
{
    static async Task Main(string[] args)
    {
        var db = new DataConnection( new DataOptions()
               .UsePostgreSQL("***** CONN STRING *****")); // MODIFY THIS TO SWITCH to SqlServre or SQLite
        var fluentMappings = new MappingSchema();

        var builder = new FluentMappingBuilder(fluentMappings);

        builder.Entity<Test>()
                        .HasTableName("test")
                        .HasSchemaName("grid")
                        .HasIdentity(t => t.a)
                        .HasPrimaryKey(t => t.a)
                        .Property(t => t.a).HasColumnName("a")
                        .Property(t => t.b).HasColumnName("b");

        var data = (from test in db.GetTable<Test>() select test).ToList();
        int i = 2;
       db.GetTable<Test>().AsUpdatable().Set(t => t.b, t => (t.b ?? 0) + i).Update() // WORKS
        var output = db.GetTable<Test>().AsUpdatable().Set(t => t.b, t => (t.b ?? 0) + i).UpdateWithOutput().ToList(); // FAILS
        var data2 = (from test in db.GetTable<Test>() select test).ToList();
    }
}
```

### Environment details

`Linq To DB` version: 5.3.2

Database (with version): 
PostGres - PostGres 15.1 / Npgsql 7.0.6 
SQLite - System.Data.Sqlite.Core 1.0.118
SqlServer - MS Sql Server Express 15.0.41 / Microsoft.Data.SqlClient 5.1.1

Operating system: Win 11 64bit

.NET Version: .net 6

**Comment by MaceWindu** [comment]
That's expected. Old data not supported in returning clause for SQLite and PostgreSQL:
- https://www.sqlite.org/lang_returning.html : `For INSERT and UPDATE statements, references to columns in the table being modified refer to the value of that column after the change has been applied.`
- https://www.postgresql.org/docs/current/dml-returning.html : `In an UPDATE, the data available to RETURNING is the new content of the modified row`

**Comment by MaceWindu** [comment]
API documentation includes list of supported databases : https://github.com/linq2db/linq2db/blob/6bb5d8baaff795e44a38af7dc63019b38a346652/Source/LinqToDB/LinqExtensions.Update.cs#L788-L789

**Comment by sd-mobile** [comment]
Видимо, проблема в том, что для Postgres в запрос попадают "DELETED".
Возможно-ли исключить все "DELETED" из секции RETURNING?
