### ISSUE TITLE
Get Where parameters from IQueryable

### ISSUE THREAD

**Issue by zgandrew** [linq2db/linq2db#433]
I'm writing a Update extension with dynamicly input fields and it's need to complete my update query with "where" paramters of IQueryabale source ... what is way out, please! maybe that could be done in a different manner ? thanks!

...
  query = query.UpdateAll(properties_collection);
...

 public static IQueryable UpdateAll(this IQueryable source, object fields_collection)
        {
            var pairs = new List<string>();
            var parameters = new Dictionary<string, object>();

            var safety_fields = GetSafeFields(fields_collection);
            var table = source.GetType().GetGenericArguments()[0].Name;

            foreach(var field in safety_fields)
            {
                var value = fields_collection.GetType().GetProperty(field).GetValue(fields_collection, null);
                var value_safe = value.IsNumericType() ? value.ToString() : value.ToLiteral();
                parameters.Add(field, value_safe);
            }
            
            /////////////////////////////////////////////////////////////

            IDbCommand UpdateCmd = SingletonDatabase.dbContext.CreateCommand();
            StringBuilder builder = new StringBuilder(String.Format("UPDATE {0} SET ", table));

            foreach (KeyValuePair<string, object> parameter in parameters)
            {
                builder.Append(parameter.Key).Append(" = @").Append(parameter.Key).Append(",");

                var dp = UpdateCmd.CreateParameter();
                    dp.ParameterName = "@" + parameter.Key;
                    dp.Value = parameter.Value;
                    UpdateCmd.Parameters.Add(dp);
            }

            builder.Remove(builder.Length - 1, 1);
            builder.Append(" WHERE ");
  
             /////////////////////////
            ?? how to get source where paramters to complete query ??
            ////////////////////////////

            //set the command text and execute the command
            UpdateCmd.CommandText = builder.ToString();

            Console.WriteLine("B:{0}", builder.ToString());
            //UpdateCmd.ExecuteNonQuery();

            return source;
        }

**Comment by jogibear9988** [comment]
Why don't you use "update" linq functions of linq2db?

If you realy want to analyze the iqueryable, try ExpressionVisitor.

**Comment by zgandrew** [comment]
Hi Jochen, thanks for the fast reply, 
I have there a lot of mysql tables, so then a table models with a different couple of fields and want to implement a common interface to update them all via common update function, but I really don't understand how to implement in linq2db via dynamic manner update to get cunstruction like
string[] fields = [values];
for(var field in fields){
db.table.Update(field, [value]);
}
cause in a dynamic linq exits few kinds of Where("string condition") implementation but absent overloaded Update extension, a have stucked in a manual implementation of it. Maybe you have any suggestion for that?

**Comment by zgandrew** [comment]
So, I'm looking smth like that 
            using (var db = SingletonDatabase.dbContext)
            {                    
                foreach(var field in safety_fields)
                {
                    var value = fields_collection.GetType().GetProperty(field).GetValue(fields_collection, null);
                    query = query.Set(field, value);
                }
                query.Update();
            }

Is in linq2db some way to implement it?

**Comment by sdanyliv** [comment]
Yes, but it's a little bit tricky
```cs
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using DataModels;
using LinqToDB;
using LinqToDB.Linq;

namespace DynamicUpdate
{
	internal static class UpdateExtensions
	{
		private static MethodInfo _withIQueryable;
		private static MethodInfo _withIUpdatable;
		private static MethodInfo _updateAllGeneric;

		static UpdateExtensions()
		{
			InitSetMethods();
		}

		public static int UpdateAll(this IQueryable source, IList<KeyValuePair<string, object>> values)
		{
			var method = _updateAllGeneric.MakeGenericMethod(source.ElementType);
			return (int) method.Invoke(null, new object[] {source, values});
		}

		public static int UpdateAllGeneric<T>(this IQueryable<T> source, IList<KeyValuePair<string, object>> values)
		{
			var isFirst = true;

			object current = source;
			foreach (var pair in values)
			{
				var propInfo = typeof(T).GetProperty(pair.Key);
				if (propInfo != null)
				{
					var param = Expression.Parameter(typeof(T));
					var propExpression = Expression.MakeMemberAccess(param, propInfo);
					var lambda = Expression.Lambda(propExpression, param);

					var currentMethod = isFirst ? _withIQueryable : _withIUpdatable;
					isFirst = false;

					var method = currentMethod.MakeGenericMethod(typeof(T), propInfo.PropertyType);
					current = method.Invoke(null, new[] {current, lambda, pair.Value});
				}
			}

			if (!isFirst)
				return ((IUpdatable<T>) current).Update();

			return 0;
		}

		private static void InitSetMethods()
		{
			var methods =
				typeof(LinqExtensions).GetMethods(BindingFlags.Static | BindingFlags.Public)
					.Where(m => m.IsGenericMethodDefinition
					            && (m.Name == "Set")
					            && (m.GetParameters().Last().ParameterType == m.GetGenericArguments().Last())
					)
					.ToArray();

			_withIQueryable = methods.First(m => m.GetParameters()[0].ParameterType.Name == typeof(IQueryable<>).Name);
			_withIUpdatable = methods.First(m => m.GetParameters()[0].ParameterType.Name == typeof(IUpdatable<>).Name);

			_updateAllGeneric = typeof(UpdateExtensions).GetMethod("UpdateAllGeneric", BindingFlags.Static | BindingFlags.Public);
		}
	}

	internal class Program
	{
		private static void Main(string[] args)
		{
			using (var db = new NorthwindDB())
			{
				db.Employees.Where(e => 1 == 2)
					.UpdateAll(new[]
					{
						new KeyValuePair<string, object>("Address", "SomeAdress"),
						new KeyValuePair<string, object>("City", "SomeCity")
					});
			}
		}
	}
}
```

**Comment by zgandrew** [comment]
sdanyliv it's INCREDIBLE, works as sharm !! a lot of thanks for the excelent support!!!

**Comment by zgandrew** [comment]
Praise to GOD for one of the best the support!!!

**Comment by zgandrew** [comment]
sdanyliv! it would be fantastic if you could email me a little comment of your super-code!! if you have a bit of time for that, I whoud very appreciate that. Thanks, you did a great job for me!!

**Comment by sdanyliv** [comment]
You can find me in skype svyatoslav.danyliv, i'm also from Ukraine
