### ISSUE TITLE
LinqToDBConnectionOptions 

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#4331]
Hello,

in which Lib is LinqToDBConnectionOptions defined ?

When linq2db creates the classes I have a constructor 

               public GutachterDbv80Db(LinqToDBConnectionOptions<GutachterDbv80Db> options)
			: base(options)
		{
			InitDataContext();
		}

LinqToDBConnectionOptions ist not defined 

What can I do ?

Thanks Andreas

### Describe your issue

If you have a question, first try to check our [documentation](https://linq2db.github.io/), especially [FAQ](https://linq2db.github.io/articles/FAQ.html) and search in [issues](https://github.com/linq2db/linq2db/issues) and [discussions](https://github.com/linq2db/linq2db/discussions) - maybe your question already answered there.

If you still have questions or want to start general discussion, please create new topic in [discussions](https://github.com/linq2db/linq2db/discussions).

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce

Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
<code with error and mapping classes>
```

### Environment details

`Linq To DB` version: *?*

Database (with version): *?* (e.g. SQL Server 2019)

ADO.NET Provider (with version): *?* (e.g. Microsoft.Data.SqlClient 4.1.0)

Operating system: *?*

.NET Version: *?*

**Comment by MaceWindu** [comment]
You are using pre-v5 scaffold generator. There is no such class anymore in linq2db as it was replaced with DataOptions in 5.0 release

**Comment by AndreasWaning** [comment]
dotnet tool update  --global linq2db.cli --version 5.3.2
Thanks you now it works.
