### ISSUE TITLE
Query does not work after Update from Linq2db 5.2.2 to 5.3.0 (or newer)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#4337]
It's a very complex query, I create a reduced test case here.

It does not work in Sqlite and MsSql

Exception:

        LinqToDB.Linq.LinqException: ''<>h__TransparentIdentifier12.<>h__TransparentIdentifier11.<>h__TransparentIdentifier10.<>h__TransparentIdentifier9.<>h__TransparentIdentifier8.c1.Id' cannot be converted to SQL.'

<img width="1699" alt="image" src="https://github.com/linq2db/linq2db/assets/364896/aec3e87a-d6aa-4062-944c-ac93c8801d89">

**Comment by jogibear9988** [comment]
I'll look to simplyfy the test, and wich commit it introduced

https://github.com/linq2db/linq2db/pull/4339

**Comment by jogibear9988** [comment]
This commit breaks the query: https://github.com/linq2db/linq2db/commit/3cff24499ad2a43547920c4eaa55c245097e32ca

**Comment by jogibear9988** [comment]
If I revert this commit on "master", the query works

**Comment by jogibear9988** [comment]
@MaceWindu could you help here? As your commit breaks my query

**Comment by MaceWindu** [comment]
You could try to debug places like this one https://github.com/linq2db/linq2db/commit/3cff24499ad2a43547920c4eaa55c245097e32ca#diff-15fe95a36578d03748fb60f9240e49c20395c8086bd7b7173b7041f76ac9ad2dR929

I suspect somewhere context parameter now processed when it shouldn't. Linked changeset already contains several fixes to issues like that, but your test adds additional coverage we don't have now.
