### ISSUE TITLE
Joins don't work with Merge

### ISSUE THREAD

**Issue by AntonC9018** [linq2db/linq2db#4338]
The following code fails to produce SQL, with an exception in the builder code.
```cs
await dbContext
    .GetTable<ArticleImage>()
    .Where(ai => ai.Article.Name == "hello")
    .AsCte()
    .Merge()
    .Using(urls.Select(u => new { Url = u, }))
    .On((dst, src) => dst.Url == src.Url)
    .InsertWhenNotMatched(s => new()
    {
        ArticleId = 10,
        Url = s.Value,
    })
    .MergeAsync();
```
```
Unhandled exception. LinqToDB.SqlQuery.SqlException: Table not found for 't6.URL'.
```
It throws the exception at [this line](https://github.com/linq2db/linq2db/blob/6bb5d8baaff795e44a38af7dc63019b38a346652/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L2910).

I need to generate a query with an `in` kind of like this:
```
WITH cte ( ... ) AS (
    SELECT ... FROM ArticleImage
    INNER JOIN Article
    ON ArticleImage.ArticleId = Article.Id
    WHERE Article.SupplierId IN (@myParameter)    
) 
MERGE ...
```

This is a blocker for me currently.
What workaround can I use besides `FromSqlRaw`?

**Comment by MaceWindu** [comment]
Fixed in `6.0.0-preview.1`
