### ISSUE TITLE
One common object for all tables

### ISSUE THREAD

**Issue by mercurial-moon** [linq2db/linq2db#4340]
I see that in `linq2db` we need to define 1 Poco per table, so for instance lets say a `Person` poco for the `Person` table and an `Employee` poco for an `Employee` Table.
and then we do something like

```var employees = db.GetTable<Employee>().ToList();```

to pull in data from the table.

I' like to work with a single poco lets call it `Table`
This poco will have properties like 
```
string tableName
List<string> colNames,
List<List<object>> Rows
```
and then 
when we do 
```db.GetTable<Table>(string tableName)```
it should load the required data into a `Table` object.

Does this kind of mechanism exist in `linq2db`?

**Comment by MaceWindu** [comment]
Look at [DynamicColumnsStore](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Mapping/DynamicStoreTests.cs) examples in tests

**Comment by jogibear9988** [comment]
If you already use the Table name as String, why don't you use a DataReader and fill a dataTable with it?

        var dataReader = cmd.ExecuteReader();
        var dataTable = new DataTable();
        dataTable.Load(dataReader);

**Comment by jods4** [comment]
@mercurial-moon how are you gonna use this with linq2db what benefit do you expect?
If everything is untyped, I don't see a reason why you'd use linq2db.

**Comment by mercurial-moon** [comment]
@jogibear9988 I think i ended up using something similar, I don't quite remember now, it has been a few months and I've moved on from that project since.

@jods4  There was a need to create database tables and columns dynamically and I couldn't make POCO's for them at compile time. It's been some time now since i asked that question and I don't quite remember the full details.
