### ISSUE TITLE
I think the `DataOptions` configuration methods are wrong

### ISSUE THREAD

**Issue by AntonC9018** [linq2db/linq2db#4341]
I've been trying to configure `BulkCopyTimeout` for the last like 2 hours, and I have noticed the helper methods like `UseBulkCopyTimeout` are actually pure, as in they don't affect `options`, but they aren't marked as such. They all call into `WithOptions`, which is pure, but they never reset `Options`. I guess that's fine, as long as they are marked as pure.

I guess there isn't any way to update the options after context creation? Like, it's fine, it just tripped me up considerably.

**Comment by curllog** [comment]
Hi @MaceWindu  i made [this pr](https://github.com/linq2db/linq2db/pull/4379) for this issue, can you please review it? thanks
