### ISSUE TITLE
Migration mechanism

### ISSUE THREAD

**Issue by WizMe-M** [linq2db/linq2db#4356]
### Migration mechanism for pure linq2db

Hi, is there migration-management mechanism or any plans about it?  
In my case I want to change my ORM from EF to linq2db and I want to know if there is support of that thing.

Maybe there are any side libraries integrated wtih linq2db?

**Comment by viceroypenguin** [comment]
If you check out my template [here](https://github.com/viceroypenguin/VsaTemplate), I have implemented a simple migration management system.

1. In the [DbContextInitialization](https://github.com/viceroypenguin/VsaTemplate/blob/master/Services/Database/DbContext.InitializeDatabase.cs), under the Services project, the application will self-migrate on startup based on the Scripts present at compilation. 
2. The Scaffold project creates an executable that can be used as part of the build process (and is done for the build process of the Services project), that will scaffold the Scripts into a reliable ORM model based on the Scripts present at compilation.

**Comment by WizMe-M** [comment]
Thank you, I will take a look!
