### ISSUE TITLE
support for .net core

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#436]
Is there a plan for **linq2db**(or blttolkit) to support new .net core? I'm using bltoolkit and/or linq2db in all of my projects and I really think these are the best ORMs out there. Now I'm planning to switch one of my projects to the .net core and I would like to continue using these tools.

**Comment by sdanyliv** [comment]
You have to follow this issue #304

**Comment by stsrki** [comment]
wow, the process has already started :)
tnx

**Comment by ili** [comment]
For linq2db in process. For BLT I don't think it worth a time, it's better to migrate to linq2db

**Comment by jogibear9988** [comment]
i think this can be closed?

**Comment by stsrki** [comment]
Can you please tell me when will the new version of linq2db(1.0.7.5) be published on NuGet? Right now I'm still using .Net Framework in my Core projects and linq2db is the only thing holding me back to fully support .net core. I know that you don't want to release it too soon but can you please consider it to be published as a **Prerelease** on NuGet?

**Comment by ili** [comment]
Working on it right now :)

**Comment by ili** [comment]
https://www.nuget.org/packages/linq2db.Core/ here we are )

**Comment by lbrevity** [comment]
Hello,
Still bltoolkit not available for asp.net core 2.1?

Is there any body to reply me proper? I googled too much.

Thanks

**Comment by MaceWindu** [comment]
bltoolkit is discontinued for many years and will not support .net core
