### ISSUE TITLE
Migration from BLToolkit: Where is update batch?

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#438]
Where can I find the following method in Linq2db?
Is replacement not implemented?

I want to get bulk update of all fields of all items in collection.

``` SQL
public static int Update<T>(this DbManager dataContext, int maxBatchSize, IEnumerable<T> list)
{
    return new SqlQuery<T>(dataContext).Update(dataContext, maxBatchSize, list);
}
```

**Comment by genusP** [comment]
https://github.com/linq2db/linq2db#bulk-copy

**Comment by maxim-boligatov** [comment]
BulkCopy inserts new value... How can you **update** multiple rows?

**Comment by sdanyliv** [comment]
You can try to Bulk insert into into temp table and then update using Update linq query.

**Comment by maxim-boligatov** [comment]
Table is overkill.
BLToolkit has corresponding method. We need just implement that idea in Linq2db considering new project structure.

BLTookit generates this T-SQL for multiple update command. And it will be much more faster than connect to DB for each update.

```sql
UPDATE
	[Vacancy]
SET
	[Title] = 	    @Title_P0,
	[Comment] = 	@Comment_P0
WHERE
	[ID] = @ID_W0;

UPDATE
	[Vacancy]
SET
	[Title] = 	    @Title_P1,
	[Comment] = 	@Comment_P1
WHERE
	[ID] = @ID_W1;
```

**Comment by sdanyliv** [comment]
And this is what i calls unoptimal way. Temp table is much fater alt all.
But i agree for 10 records it's overkill.

**Comment by maxim-boligatov** [comment]
Temp table internally will do the same. You will still need to join data from temp table.... to assign data from temp to target... so the same index scan will be required in any case. In addition you will have to get all overhead of creation of temp table (as well as limitations).     
So I do not think that in high concurrent environment 1000 transactions per second with 10-100 rows update inside each will be executed slower than 1000 temp tables.

**Comment by ili** [comment]
Update is needed or update from temporary table is enough?

**Comment by hardhub** [comment]
I am sure it is needed... I think many users will come to Linq2Db from BLToolkit. 
I assume mostly all users for last 2-3 years are interesting in Linq2Sql provider only. And finally they will switch their projects to Linq2Db. And this transition will not be so smooth without this feature. BLTookit has corresponding methods for bulk update.

**Comment by sdanyliv** [comment]
We have to look more closer to **Merge** functionality. Looks like it does what we need.

**Comment by hardhub** [comment]
sdanyliv, can you explain? What exactly do you want to implement? What is Merge?

**Comment by sdanyliv** [comment]
Search in code using word Merge. I'm not near computer to point to exact place.

**Comment by hardhub** [comment]
I think you mean this:

```sql
-- Create a temporary table variable to hold the output actions.  
DECLARE @SummaryOfChanges TABLE(Change VARCHAR(20));  
  
MERGE INTO Sales.SalesReason AS Target  
USING (VALUES ('Recommendation','Other'), ('Review', 'Marketing'), ('Internet', 'Promotion'))  
       AS Source (NewName, NewReasonType)  
ON Target.Name = Source.NewName  
WHEN MATCHED THEN  
UPDATE SET ReasonType = Source.NewReasonType  
WHEN NOT MATCHED BY TARGET THEN  
INSERT (Name, ReasonType) VALUES (NewName, NewReasonType)  
OUTPUT $action INTO @SummaryOfChanges;  
  
-- Query the results of the table variable.  
SELECT Change, COUNT(*) AS CountPerChange  
FROM @SummaryOfChanges  
GROUP BY Change; 
```
[MERGE (Transact-SQL)](https://msdn.microsoft.com/en-us/library/bb510625.aspx)

I see some logic in BasicMerge...

I guess it is question of at least 3 points:
1) Minimal version where it is supported is 2008.  (For me it is vital to support 2008R2).
2) Performance of table variables and merge...
3) API provided by Linq2Db to finally get bulk update...

**Comment by sdanyliv** [comment]
Check current linq2db sources. Looks like it is already implemented.

**Comment by MaceWindu** [comment]
Will handle it as a part of merge operation improvements.

BTW, @hardhub - temp table will be much better solution if you need to update thousands of records. In our project we use merge for batch updates and we split batches in 2000 record chunks (still it depends on amount of data in each record), because after some point SQL Server parser (?) starts to consume a lot of time trying to parse merge query.

**Comment by hardhub** [comment]
@MaceWindu I do not think we will ever use batch size more than 1000 rows. But even 100 separate connections is very heavy load for RDBMS. Also we need to consider limit of parameters for sql command.
So to make my previous post a bit clear name it "multiple update" instead of "bulk update".
I wrote some Update methods based on merge... it looks OK.

**Comment by sdanyliv** [comment]
@hardhub, great, closing for now will reopen when needed.

**Comment by hardhub** [comment]
@sdanyliv 

I think I got some troubles... Currently merge adds rows which are as source...
And it is not so good to use it as bulk update solution.
It should be possible to update only that items which are already in db on the moment.

I think SQL server allows to avoid insertion...
Can we simply omit "WHEN NOT MATCHED BY TARGET THEN" and make it possible with options in Merge method of context?

**Comment by MaceWindu** [comment]
Yes, this is a limitation of current Merge API we have and unfortunately it is not possible to disable insert operation without changes to linq2db source code.
This will be fixed in new Merge API I am currently working on amd expect to release preview version in a couple of weeks.

**Comment by hardhub** [comment]
@MaceWindu Can you say what is used for Merge in MySQL provider?

**Comment by MaceWindu** [comment]
See https://github.com/MaceWindu/linq2db/wiki/MERGE-INTO-UPSERT-Implementations-Review#mysqlmariadb

MySQL doesn't support MERGE INTO command. There are upsert extensions for INSERT command, that should allow to emulate some parts of MERGE INTO command, but I didn't planned to support them in new Merge API initially. If you need them I could try to add them to my planning.

Also current API doesn't work for MySQL too for the same reason.

**Comment by hardhub** [comment]
@MaceWindu But how to implement bulk update for MySQL without Merge API? It will be really nice to have at least basic implementation for MySQL as you suggested.

What I am trying to achieve is possibility to:
1) Insert one or multiple rows at once
2) Update one or multiple rows at once
3) Delete one or multiple rows at once

For major database systems or at least these 3:
1) SQL Server
2) MySQL
3) Postgres

I know Postgres also can be some sort of pain because merge is in their TODO list only:
https://wiki.postgresql.org/wiki/Todo

But scenario when you need to update multiple rows is very common...
For example you are editing some fields of contact form where each field is separate row in db.
Also in most cases it can be required to avoid new rows on update. And it is what I want to get...
To understand why I need that it is better to think what single update does... It updates only one row if it exists... Such update looks like this: 'update something when Id = ...' So it will return 0 if nothing is updated but will not create new row.

I think it is not trivial to consider all rdbms but it will be very appreciated to do all possible.
Linq2Db can have fallback code which will be changed to normal implementation in the future when merge will be available in corresponding database system.

**Comment by MaceWindu** [comment]
@hardhub  for now (next week or two) I will work solely only on merge support for RDBMS that supports `MERGE INTO` command. After I will finish with it, I will see what we can do for RDBMS that support `UPSERT` commands to support them in Merge API.

If you are interested, you can try to build linq2db from this branch: https://github.com/MaceWindu/linq2db/tree/merge_improvements

Note that it will work only with SQL Server for now as I want to test all required functionality on one provider and then tune support for others.
