### ISSUE TITLE
BulkInsert DateOnly columns fails

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#4385]
### Describe your issue

We tried to migrate some of our C# properties to `DateOnly`, as support was recently added in #3502 .

C# property is typed as `DateOnly`, Oracle column is `date` (includes time but that's the best fit...), this is the default mapping in linq2db Oracle provider.

Reading data into `DateOnly` properties, sending normal updates with `DateOnly` parameters: work flawlessly! 😃 

But when doing a BulkInsert, the `DateOnly` value is not converted to `DateTime` before being put into `OracleParameter.Value`. As ODP.NET has no support for `DateOnly` values yet, it then tries a generic conversion during query execution that fails.

I guess the path that extracts parameter values in BulkInsert is not going through all the mappings of normal statements.

We observe this with Oracle "INSERT INTO + array parameter values" strategy, not sure if it reproduces with other strategies (multiple INSERT or native BulkCopy).

@vinceroypenguin did you check/test BulkInsert when you did #3502?

### Environment details

`Linq To DB` version: *5.3.2*

Database (with version): *Oracle 19*

ADO.NET Provider (with version): *Oracle.ManagedDataAccess.Core 3.21.130*

Operating system: *Windows 10*

.NET Version: *.net 8*

**Comment by viceroypenguin** [comment]
Nope. I don't have (or care about 😉) Oracle.

**Comment by jods4** [comment]
@viceroypenguin Did you test other Bulk Insert providers? They work? (with or without changes to the provider bulk implementation?)

Thinking about it, now that MSSQL has support for `DateOnly` type, it might just work even when passing through a `DateOnly`... not sure about other providers.

**Comment by jogibear9988** [comment]
If we do a conversion of DateOnly -> to DateTime, we maybe should only do this with a special setting.

So we don't get into the situation like with mapping from Time Datatype to TimeSpan wich we then can not fix for the default.

**Comment by jods4** [comment]
@jogibear9988 is there a public API to redefine type mappings (at the provider level?) or none?
How is this currently handled for bool, which has tons of opiniated conversions (1/0, Y/N, X/null and more)?
I think ideally we should let users override their type mappings with some provider options.

In this specific case, at least for Oracle (haven't looked at other providers):
- There's currently no other type to map to (Oracle doesn't have a "date only" SQL type);
- This already shipped in a previous linq2db release.. I opened this issue because it looks like the mapping is not applied in bulk copy.

BTW I created a PR with test case (still waiting for tests to complete and checkout results): #4397

**Comment by jods4** [comment]
I now have a failing test case in #4397!

Good news is that it looks like BulkCopy works for all RDBMS. The bug only happens for a very specific strategy: Oracle MultipleRows + InsertInto.

This is a very Oracle-specific codepath that makes uses of array-bound queries (simple INSERT INTO but each parameter value is an array of multiple values).

I wanted to fix that but at first glance I don't spot the difference compared to the other codepaths. Values do come from `column.GetProviderValue(..)`. The code is here: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs#L407-L415

Anyone has an idea what I'm missing?

**Comment by MaceWindu** [comment]
I suspect it miss provider.SetParameterValue call. I will check it
