### ISSUE TITLE
Ability to use Linq2db in Onion architecture

### ISSUE THREAD

**Issue by gkathire** [linq2db/linq2db#44]
If possible can you split the main project into two parts ? One with the helper/utility classes and the annotation classes and the other with the DB stuff ? This will help in putting the utility/annotation class assembly in non DAL layer projects and the DB part of Linq2DB in the DAL layer project.

**Comment by jogibear9988** [comment]
I think for Problems like this, we have the fluent mapping?

**Comment by ili** [comment]
It is the way... But if we do have 100 POCOs i think fluent mapping would be heavy thing, also using T4 templates is a pretty feature :)

**Comment by jogibear9988** [comment]
What would be the advantage of having two assemblies?

**Comment by gkathire** [comment]
Most of the time in big projects, we tend to put the interfaces and pocos associated with the tables in a separate project, in that case we dont want the database access code to be included in that project.

**Comment by jogibear9988** [comment]
yes, but youonly don't need to use it. 
i don't see any advantage in splitting up linq2db

**Comment by MaceWindu** [comment]
We don't have any plans to split linq2db into several assemblies, at least in this way.
You can easily achieve something like that with custom annotation classes (or whatever metadata source you like) and your IMetadataReader implementation to work with them. Btw I already use this approach for enums sharing with non-db assemblies in our project. Just two halfpage-size classes: for attribute and reader.

I will close it for now.
