### ISSUE TITLE
Create a Possibility to override how Methods are Mapped to the Database

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#4401]
### Describe your issue

At the Moment, in Expressions.cs 
https://github.com/linq2db/linq2db/blob/c8cf53ec7c4569319c2888904fc3e2c6abe74f75/Source/LinqToDB/Linq/Expressions.cs#L587
there is a Entry fora Object Method, you could use in Linq and wich method is then used from Linq2db.

If this is possible to Map this externaly, You could for example Override how Guid is Converted to a String (https://github.com/linq2db/linq2db/pull/4297/commits/da110d4688f3bf418006188e7dc4d7d4b2a52c96#diff-2a6a9163861fbdc4015c6f32a3373c85469cb401552aea366b2d2c07ede63fb5R585)
or you could enable support for the use of Regex.IsMatch (https://github.com/linq2db/linq2db/pull/4392/files#diff-2a6a9163861fbdc4015c6f32a3373c85469cb401552aea366b2d2c07ede63fb5R1197)
or much more.

I think there should be a publicly available Method, like "Register..." smth. (I've no Idea for a good Name), maybe at best on the MappingSchema.

**Comment by jogibear9988** [comment]
https://github.com/linq2db/linq2db/pull/4392

**Comment by jogibear9988** [comment]
https://github.com/linq2db/linq2db/pull/4297

**Comment by jods4** [comment]
I have ideas regarding this one, but this will not play nice with the parser refactoring.
@sdanyliv do you have an ETA when you're going to merge the new parser with master?

**Comment by igor-tkachev** [comment]
`Expressions.MapMember` is what you are looking for?

```c#
Expressions.MapMember<Person>(p => p.FullName(), (Expression<Func<Person,string>>)(p => p.LastName + ", " + p.FirstName));
```

**Comment by jogibear9988** [comment]
If this works for Guid.ToString() and Regex.IsMatch() and I can Redirect to a method wich has builders, like:
<img width="774" alt="image" src="https://github.com/linq2db/linq2db/assets/364896/9318238b-b318-4866-a670-09ccf674848d">
then yes

**Comment by jogibear9988** [comment]
@igor-tkachev thanks...

with this it works:

				LinqToDB.Linq.Expressions.MapMember<Regex, string, bool>((r, s) => r.IsMatch(s), (Expression<Func<Regex, string, bool>>)((p, p1) => Sql.RegExpIsMatch(p1, p.ToString())));

**Comment by jogibear9988** [comment]
@jods4 have you seen it is already possible?
