### ISSUE TITLE
Query fails after Linq2Db Update (misuse of aggregate: Max())

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#4415]
### Describe your issue

I've the following query in a test:

                     var p = s.Query<LanguageDTO>();
                    var qry = p.GroupBy(x => x.Name).Select(x => x.Max(y => y.LanguageID));
                    var qry2 = p.Where(x => qry.Contains(x.LanguageID));
                    var lst = qry2.ToList();

it did work with linq2db 5.2.2

Now I switched to master, wich breaks the query (or mapping)

```
Exception message: System.Data.SQLite.SQLiteException : SQL logic error misuse of aggregate: Max()
Stack trace:

        SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
        SQLiteCommand.BuildNextCommand()
        SQLiteCommand.GetStatement(Int32 index)
        SQLiteDataReader.NextResult()
        SQLiteDataReader.ctor(SQLiteCommand cmd, CommandBehavior behave)
        SQLiteCommand.ExecuteReader(CommandBehavior behavior)
        SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
        <>c__DisplayClass29_0.<ExecuteDbDataReader>b__0()
        RetryPolicyBase.ExecuteImplementation[TResult](Func`1 operation)
        RetryPolicyBase.Execute[TResult](Func`1 operation)
        RetryingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
        DataConnection.ExecuteReader(CommandBehavior commandBehavior)
        DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
        DataConnection.ExecuteReader()
        QueryRunner.ExecuteReader()
        QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext()
        List`1.ctor(IEnumerable`1 collection)
        Enumerable.ToList[TSource](IEnumerable`1 source)
        DatabaseReadTests.DistinctByTestSqlite() line 199
        RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

```

### Steps to reproduce

I'll create a test Branch & pull request

### Environment details

`Linq To DB` version: *?*

Database (with version): SQLite (System.data.sqlite)

Operating system: Windows 10

.NET Version: 7

**Comment by jogibear9988** [comment]
Following SQL is created:

            SELECT
	            [x].[LanguageID],
	            [x].[Name],
	            [x].[AlternativeLanguageID],
	            [x].[Order],
	            [x].[IsoCode]
            FROM
	            [Common_Language] [x]
            WHERE
	            ([x].[LanguageID] IS NULL AND 1 IN (
		            SELECT
			            1
		            FROM
			            [Common_Language] [t1]
		            WHERE
			            Max([t1].[LanguageID]) IS NULL
		            GROUP BY
			            [t1].[Name]
	            ) OR [x].[LanguageID] IS NOT NULL AND [x].[LanguageID] IN (
		            SELECT
			            Max([t1].[LanguageID])
		            FROM
			            [Common_Language] [t1]
		            GROUP BY
			            [t1].[Name]
	            ))

**Comment by jogibear9988** [comment]
If I map the LanguageID with "IsNotNull" the query looks like this and works:

        SELECT
	        [x].[LanguageID],
	        [x].[Name],
	        [x].[AlternativeLanguageID],
	        [x].[Order],
	        [x].[IsoCode]
        FROM
	        [Common_Language] [x]
        WHERE
	        [x].[LanguageID] IN (
		        SELECT
			        Max([t1].[LanguageID])
		        FROM
			        [Common_Language] [t1]
		        GROUP BY
			        [t1].[Name]
	        )


but it did work with the old Version of linq2db (without the IsNotNull Mapping)!

And also, should the query with a nullable work?

**Comment by jogibear9988** [comment]
Problem is, the aggregate function is in the where clause, but it needs to be in a HAVING clause after the group by like this:

            SELECT
                        [x].[LanguageID],
                        [x].[Name],
                        [x].[AlternativeLanguageID],
                        [x].[Order],
                        [x].[IsoCode]
                    FROM
                        [Common_Language] [x]
                    WHERE
                        ([x].[LanguageID] IS NULL AND 1 IN (
	                        SELECT
		                        1
	                        FROM
		                        [Common_Language] [t1]
	                        GROUP BY
		                        [t1].[Name]
				             HAVING
		                        Max([t1].[LanguageID]) IS NULL
                        ) OR [x].[LanguageID] IS NOT NULL AND [x].[LanguageID] IN (
	                        SELECT
		                        Max([t1].[LanguageID])
	                        FROM
		                        [Common_Language] [t1]
	                        GROUP BY
		                        [t1].[Name]
                        ))

**Comment by MaceWindu** [comment]
`If I map the LanguageID with "IsNotNull" the query looks like this and works`

This new behavior sounds correct. `MAX` aggregate is nullable and if you compare it with nullable column it should generate `A == B OR (A IS NULL AND B IS NULL)` condition.
When you remove nullability from column, condition simplified to `A == B`

**Comment by MaceWindu** [comment]
If you want to avoid null checks and don't want to change mappings, you can use `Sql.NotNull()`  util (or something like that):

```cs
                var qry2 = p.Where(x => qry.Contains(Sql.NotNull(x.LanguageID)));
```

**Comment by MaceWindu** [comment]
BTW, would be nice to have this workaround as additional test in your PR
