### ISSUE TITLE
Debug query output always uses SQL Server syntax for params

### ISSUE THREAD

**Issue by Metadorius** [linq2db/linq2db#4419]
> It is debug information. Historically it shows parameters in SQL Server syntax. 
Under hood `linq2db` uses parameters passed `SqlComand` and do not include declaration section in final SQL.

_Originally posted by @sdanyliv in https://github.com/linq2db/linq2db/discussions/4418#discussioncomment-8396188_

This results in the resulting query not being executable by the target provider (in my case Firebird). The suggested solution kind of works (`db.InlineParameters = true` or the same on query) but from my understanding transforms the actual query, which poses an additional SQL injection security risk

**Comment by sdanyliv** [comment]
It has no risk for SQL Injection. All literals are properly quoted.

**Comment by sdanyliv** [comment]
I do not understand what should be done? Inlined parameters for Debug SQL, which do not change actual executed query?

**Comment by Metadorius** [comment]
I think so. Generally the wish is so that the logged SQL is executable as is/what gets executed by linq2db, so I can copypaste it into SQL console to check. It seems that using something like `DECLARE` is not possible without `isql` for Firebird's case though, because only with `isql` or alike you can do `SET TERM` that is needed, so inlining just in the query is a possible solution too.

**Comment by sdanyliv** [comment]
Do you understand that it will slowdown all parametrised queries when they are logged? It is another SQL generation path with additional CPU and memory usage.

We can think in this direction with additional configuration option.

**Comment by Metadorius** [comment]
Well I am not sure what path would be the best to take here. The main point is that what's the point of a generated SQL if it can't be executed to be verified? Of course, reading it is an option too but executing it is important too.

**Comment by jods4** [comment]
"It can't be executed or verified" is a strong statement.
It may depend slightly on what RDBMS and tool you use but:
- it definitely can be executed as-is, as long as you pass the parameters values (which are also logged).
- you can examine the execution plan without providing parameter values.

Conversely: what is the point of logging a request that is NOT the request actually being executed?
I have debugged countless Oracle bugs and execution plans that were affected by the usage of a parameter vs an inline constant.

**Comment by Metadorius** [comment]
> "It can't be executed or verified"

Correction, I only said that it can't be executed as-is.

> It may depend slightly on what RDBMS

...and that's where the problem lies. As was pointed out in the linked discussion, the SQL flavour that Linq2DB outputs the query in is actually just SQL Server's and it's not compatible with Firebird, so whatever you wrote doesn't apply to the case I am dealing with, hence why this issue.

Apparently [Firebird doesn't natively support named parameters whatsoever](https://stackoverflow.com/questions/14160750/firebird-sql-query-with-at-sign-how-to-run-the-query-in-jdbc-jaybird#:~:text=However%20Firebird%20nor%20Jaybird%20supports%20this%20type%20of%20placeholders%20(they%20only%20support%20%3F%20as%20placeholder%20in%20DSQL).). So to have the query executable it's necessary to replace the parameters with question marks (and output the parameters as comments perhaps?)

**Comment by jods4** [comment]
> Correction, I only said that it can't be executed as-is.

Well, I meant "as-is". In many RDBMS tools you can specify parameters without modifying the query text, but I'm not familiar with Firebird.

> the SQL flavour that Linq2DB outputs the query in is actually just SQL Server's and it's not compatible with Firebird

In the linked issue your quote starts with comment 
```sql
-- SomeConfigName Firebird
```
So linq2db is aware of the provider, and in fact the SQL itself is extremely provider-dependent.
Is it really accurate to say "the query is actually just SQL Server"? because then it would be totally wrong.
I'm guessing the issue is that the _query parameters_ are described in MSSQL format? This is something that is worth looking at and ideally should be fixed if possible.

**Comment by Metadorius** [comment]
The query below is not executable by any Firebird utility, the `DECLARE` and `SET` syntax is simply not valid here, and named input params specification via `@name` is also not natively supported in Firebird. IBExpert uses `:param` and .NET provider uses `@param`, but Firebird itself only supports `?`.

So if we assume that Linq2DB outputs something like the following:

```sql
-- SomeDB Firebird (asynchronously)
DECLARE @SomeParam Integer -- Int32
SET     @SomeParam = 0

SELECT
    SOMETABLE.SOMEVALUE
FROM
    SOMETABLE
WHERE
    SOMETABLE.ID = @SomeParam
```

...we would need to correct it to look like this to be executable in any Firebird SQL interface:

```sql
-- SomeDB Firebird (asynchronously)
-- DECLARE @SomeParam Integer -- Int32
-- SET     @SomeParam = 0

SELECT
    SOMETABLE.SOMEVALUE
FROM
    SOMETABLE
WHERE
    SOMETABLE.ID = ? /* @SomeParam */
```

**Comment by Metadorius** [comment]
> Is it really accurate to say "the query is actually just SQL Server"? because then it would be totally wrong.
> I'm guessing the issue is that the _query parameters_ are described in MSSQL format? This is something that is worth looking at and ideally should be fixed if possible.

Yeah you're right, it's the query params.

Unless we want to support a myriad of different interfaces for Firebird I think the best way is to use Firebird-native `?` for Firebird output and specify the exact param values in comments.

**Comment by to11mtm** [comment]
> > Is it really accurate to say "the query is actually just SQL Server"? because then it would be totally wrong.
> > I'm guessing the issue is that the _query parameters_ are described in MSSQL format? This is something that is worth looking at and ideally should be fixed if possible.
> 
> Yeah you're right, it's the query params.
> 
> Unless we want to support a myriad of different interfaces for Firebird I think the best way is to use Firebird-native `?` for Firebird output, possibly with added param names for human readability, and specify the exact param values in comments.
.
FWIW I believe there are some 'other' DBs that may have this syntax as well, between DB2, Sybase, SAP, Access, ODBC, and JET I feel like there's at least a couple in that list where some versions use that syntax [0]

Currently, It looks like at least part of this is sitting in `BasicSqlBuilder`'s `protected virtual void PrintParameterName(StringBuilder sb, DbParameter parameter)` method, that's where the `@` is hard-wired, so it could be overridden in desired providers.

To have the parameters commented out as shown, probably need to override `BasicSqlBuilder`'s `public virtual StringBuilder PrintParameters(IDataContext dataContext, StringBuilder sb, IEnumerable<DbParameter>? parameters)` method as well.

As far as the query -itself-, that may get trickier, I would need to think about a non hacky way it could be done... the ugly but minimal blast radius option that comes to mind would be some funky find/replace on the main sql string in the builder, but there may be a far easier way with existing APIs that I'm not aware of.

Also, a question: if all of this is done, even if it is provider specific, does it need a config flag to avoid 'surprises' for people expecting the old behavior?

[0] - Except for the weird noodle-bake that some DB Providers are actually converting your args to `?` or `P#` behind the scenes... but I digress

**Comment by MaceWindu** [comment]
Duplicate of #3878
