### ISSUE TITLE
Querying Temp tables is extremely slow

### ISSUE THREAD

**Issue by boomgetchopped** [linq2db/linq2db#4429]
I create and populate the temp table easy enough. The insert runs pretty quickly:
`var tempTable = dc.CreateTempTable<DewarRentalUnbilled>("MyTempTable");`
`query.ToLinqToDB().Insert(tempTable, t => t);`

But when querying from it, the performance is a lot slower compared to running the exact query text in SSMS:
```
from tempdata in tempTable.InnerJoin(dt => (
			...conditions
	 ))
```

Generated Sql:
```
FROM
	[tempdb]..[#MyTempTable] [i]
		INNER JOIN [tempdb]..[#Dates] [dt] ON (([dt].[Start] >= [i].
```

Why would it be so much slower? Is this query somehow running client side?

**Comment by sdanyliv** [comment]
Nothing on the client side here, or you have shown not real query. How many records in the tables?

**Comment by sdanyliv** [comment]
How do you get this performance via Raw SQL? Which SQL do you use?
