### ISSUE TITLE
MySQL - Virtual Column not handled in INSERT, UPDATE

### ISSUE THREAD

**Issue by visual1993** [linq2db/linq2db#443]
Please consider the following table:
```sql
CREATE TABLE `products` (
  `ProductID` int(11) NOT NULL,
  `ProductName` char(255) NOT NULL,
  `data` json NOT NULL,
  `jsonID` int(11) GENERATED ALWAYS AS (json_extract(`data`,'$.jsonID')) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
if I retrieve data from the DB, linq2sql behaviour is normal, but if I InsertOrReplace and item, this exception is fired: "The value specified for generated column 'jsonID' in table 'products' is not allowed"
It happens because the MySQL connector tries to set a value in a column that is virtually generated (alias read-only).
Please add a property attribute such as "ReadOnly" or "Virtual" that we can apply to the C# class to indicate linq2db that the column should not be inserted in the INSERT or UPDATE queries, but only in the SELECT query
Thanks in advance, Luca

C# Class implementation

```cs
[Table(Name = "Products")]
    public class Product
    {
        [PrimaryKey]
        public int ProductID { get; set; }

        [Column(Name = "ProductName"), NotNull]
        public string Name { get; set; }

        [Column(Name = "data")]
        public string data { get; set; }

        [Column(Name = "jsonID")]
        public int jsonID { get; internal set;}
    }
```

**Comment by Eykhler** [comment]
Try to use ColumnAttribute boolean properties: SkipOnInsert and SkipOnUpdate.

**Comment by ili** [comment]
@Eykhler is absolutely right!

**Comment by visual1993** [comment]
the solution proposed by Eykhler is actually not working. Please review the code related to SkipOnUpdate during the SQL statement generation.
I'm attaching the modified code

`[Table(Name = "Products")]
    public class Product
    {
        [PrimaryKey]
        public int ProductID { get; set; }

        [Column(Name = "ProductName"), NotNull]
        public string Name { get; set; }

        [Column(Name = "data")]
        public string data { get; set; }

        [Column(Name = "jsonID")]
        [Column(SkipOnInsert = true)]
        public int jsonID { get; internal set;}
    }`

**Comment by jogibear9988** [comment]
I think only one Column Attribute is allowed (if so, we need to fix). Try setting SkipOnInsert in the ssme attribute where you set the Name!

**Comment by visual1993** [comment]
@jogibear9988 Thank you for the quick answear. I can confirm that the bug exists only if more than one Column Attribute is selected.
@Eykhler The bug should be re-opened to fix the Multiple Column Attribute bug.
This code actually works
```
Column(Name = "jsonID", SkipOnInsert = true, SkipOnUpdate=true)]
public int jsonID { get; internal set;}
```
Thanks for the support

**Comment by sdanyliv** [comment]
@visual1993, it is not a bug, this attribute works for different configurations. But i agree it would be great to throw informative exception that for the same configuration two attributes are defined.
