### ISSUE TITLE
What versions of Sybase ASE are supported?

### ISSUE THREAD

**Issue by wlafrance** [linq2db/linq2db#444]
What versions of ASE are supported?
We are using version:
Adaptive Server Enterprise/**12.5.4**/EBF 16787 ESD#10/P/RS6000/AIX 5.1/ase1254/2159/64-bit/FBO/Mon Nov  2 10:11:59 2009

**Comment by ili** [comment]
```sql
select @@version
```
returns 
`Adaptive Server Enterprise/16.0 SP02 PL01/EBF 25183 SMP/P/X64/Windows Server/ase160sp02pl00/0/64-bit/FBO/Fri Sep 18 10:19:23 2015`

This is one where tests are done.

But I think the most question is on ADO .Net provider for Sybase, linq2db just generate queries and do mapping... Also may be some changes for SQL dialect...
