### ISSUE TITLE
Use custom property Getters in Linq queries

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#4448]
### Describe your issue

we have extension methods like this:
    
        public static class WeberCustomFields
        {
            public static string KanbanRegalnummer(this OutfeedTransportOrderDTO oto) => oto.CustomField1;
    
            public static void SetKanbanRegalnummer(this OutfeedTransportOrderDTO oto, string value) => oto.CustomField1 = value;
    
            public static string Buchungsinformation(this WmsLoadCarrierDTO lc) => lc.CustomField1;
    
            public static void SetBuchungsinformation(this WmsLoadCarrierDTO lc, string value) => lc.CustomField1 = value;
    
        }

cause our classes have additional properties in the database CustomField1, CustomField2, .... for usage in customer modules.

Now we want to use them also in Linq Queries. Is this possible in an easy way with linq2db?

I think I could create a Expression Visitor and Rewrite the expressiontree, but is there an easier way?

**Comment by jods4** [comment]
`[Expression]` or `[ExpressionMethod]` don't do the trick?

**Comment by jogibear9988** [comment]
With this code, the quer works:

    public static class CustomFieldsExtension
    {
        [Sql.Expression("CustomField1", PreferServerSide = true)]
        public static string cf1_MyCustomerProperty(this WmsLoadCarrierDTO lc) => lc.CustomField1;

        public static void cf1_SetMyCustomerProperty(this WmsLoadCarrierDTO lc, string value) => lc.CustomField1 = value;

        [Sql.Expression("CustomDate1", PreferServerSide = true)]
        public static DateTime? cd1_MyCustomerDate(this InfeedAdviceDTO iv) => iv.CustomDate1;

        public static void cd1_SetMyCustomerDate(this InfeedAdviceDTO iv, DateTime? value) => iv.CustomDate1 = value;
    }

but the update in the database does not:

                var table = s.GetTable<WmsLoadCarrierDTO>());
                var u = table.Set(x => x.cf1_MyCustomerProperty(), "test2");
                u.Update();

Should this work? Is it an error that the Expression is not used here?

<img width="975" alt="image" src="https://github.com/linq2db/linq2db/assets/364896/787faf50-9c14-454e-868c-25ac0654c787">

<img width="927" alt="image" src="https://github.com/linq2db/linq2db/assets/364896/51d4e993-4c09-4a01-8b92-c9872530abb6">

**Comment by jods4** [comment]
Oh you want to set them also. I did not expect that to work, as `[Expression]` is an arbitrary string (or arbitrary linq expression) but UPDATE can only set a field, which is a lot more restrictive.

Not sure what you can do if you don't want to declare those as properties on the data class.

Note that the first argument to `.Set(p, v)` is an `Expression`, so if you had an extension method that returns such extension it should work. Not the best but could be a workaround:

```cs
static Expression<Func<WmsLoadCarrierDto, string>> MyCustomerSetter => dto => dto.CustomField1;

db.GetTable<WmsLoadCarrierDto>()
  .Set(MyCustomerSetter(), () => "ACME")
  .Update();
```

**Comment by sdanyliv** [comment]
Better to use `ExpressionMethod` with `Sql.Property`
```cs
public static class CustomFieldsExtension
{
    [ExpressionMethod(nameof(cf1_MyCustomerPropertyImpl)))]
    public static string cf1_MyCustomerProperty(this WmsLoadCarrierDTO lc) => lc.CustomField1;

    static Expression<Func<WmsLoadCarrierDTO, string>> cf1_MyCustomerPropertyImpl()
        => dto => Sql.Property<string>(dto, nameof(WmsLoadCarrierDTO.CustomField1));

    // other are similar
}
```

**Comment by jogibear9988** [comment]
works like a charm.

thanks
