### ISSUE TITLE
Max Pool Size limit Exception

### ISSUE THREAD

**Issue by kdkdkdkd85** [linq2db/linq2db#445]
Hello.
When using linq2db the following error:

```
Timeout. The timeout period elapsed before managed to get a connection from the pool. Perhaps all of the connections in the pool are already in use and will reach maximum size of the pool.
   в System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource'1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   в System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource'1 retry, DbConnectionOptions userOptions)
   в System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource'1 retry)
   в System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource'1 retry)
   в System.Data.SqlClient.SqlConnection.Open()
   в LinqToDB.Data.DataConnection.get_Connection() в i:\linq2db\Source\Data\DataConnection.cs:строка 499
   в LinqToDB.Data.DataConnection.CreateCommand() в i:\linq2db\Source\Data\DataConnection.cs:строка 567
   в LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters) в i:\linq2db\Source\DataProvider\DataProviderBase.cs:строка 90
   в LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteReader(Object query) в i:\linq2db\Source\Data\DataConnection.Linq.cs:строка 261
   в LinqToDB.Linq.Query'1.<RunQuery>d__11.MoveNext() в i:\linq2db\Source\Linq\Query.cs:строка 371
   в LinqToDB.Linq.Query'1.<Map>d__6a.MoveNext() в i:\linq2db\Source\Linq\Query.cs:строка 1177
```

I use linq2db as follows:
1. UnitOfWork pattern:

```
public class Linq2DbUow : IUnitOfWork {
    private readonly ShymkentEduDb _db;
    public Linq2DbUow() {
        _db = new ShymkentEduDb();
        LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
    }
    public void Dispose() {
        _db?.Dispose();
    }
    public IGenericTransaction BeginTransaction() {
        return new Linq2DbTransaction(_db.BeginTransaction());
    }
    public ShymkentEduDb GetDb() {
        return _db;
    }
}
```
1. Autofac constructor injection:

`builder.RegisterType<Linq2DbUow>().AsImplementedInterfaces().InstancePerLifetimeScope();`
1. The connection string looks like this:

`connectionString="Initial Catalog=shymkent_edu;Data Source=.;User ID=**;Password=***"`

Is it correct? Why error occurs when the standard parameters "Max Pool Size = 100" (MSDN info)

**Comment by sdanyliv** [comment]
Set breakpoints to constructor and dispose methods.
Looks like you have issue with IoC container.

**Comment by kdkdkdkd85** [comment]
Thanks for the answer. I have done it.
I set a breakpoint on Application_BeginRequest, constructor and Dispose() method. In debug mode all as it should be (I think):
Application_BeginRequest -> constructor -> Dispose() on each request to my wcf service.
Dispose() method now looks like this:
```
public void Dispose()
{
    _db?.Command.Dispose();
    _db?.Connection.Dispose();
    _db?.Transaction.Dispose();
    _db?.Dispose();
}
```
but it does not help (((.

Аfter the end of the method Dispose(), active connections is not closed (I look with SQL script in Managment Studio)

**Comment by sdanyliv** [comment]
Try to create simple test
```cs
for (var i = 0; i < 1000; ++i)
{
   using(var db = new ShymkentEduDb())
   {
       // some query
   }
}
```
We have to be sure that conections closed in simple test.

Also notice several things:
* Db connection is not multithreaded
* You have to materialize objects ToList or ToArray and do no return IQueryable after disposing db connection. Usually asp.net have mechanism to dispose sub containers and everything should work fine but without real project i can not be sure. Check your IDependencyResolver.

**Comment by ili** [comment]
`DataConnection` should be disposed. Looks like somewhere it is not so..

**Comment by worldofsites** [comment]
Hi guys, we are faced with the same problem on our project, but we fixed it with:
`using (var db = new DataConnection(ProviderName.SqlServer2014, LQxC.SqlConnectionString)) { db.GetTable<T>(true); }`
Method 'GetTable' overriden with parameter 'dispose'.
We set this to true, and now all working good.
Perhaps, by default this property should be true? Why is false?
Maybe this information someone will be useful.

**Comment by ili** [comment]
By default it is `false` not to open connections for many queries, for example if you in this way, connection would be opened and closed only once:
```cs
using (var db = new DataConnection())
{
    db.GetTable<Table1>().ToList()
    db.GetTable<Table2>().ToList()
}
```

Also you can do it in this way, and connection would be opened and closed twice:

```cs 
var db = new DataContext();

db.GetTable<Table1>().ToList()
db.GetTable<Table2>().ToList()
```

**Comment by sdanyliv** [comment]
@worldofsites, which frameworks do you use on backend and show me your typical Web method that uses linq2db (full)

**Comment by worldofsites** [comment]
@ili toList() extension is not the best option for us, because the table has a very large number of records
@sdanyliv we use linq2db to create dynamic queries for displaying as tabular data using custom filters, paging, sorting
method:
```      
public IQueryable<T> GetQueryableSource(int commandTimeout)
{
    using (var db = new DataConnection(ProviderName.SqlServer2014, SqlConnectionString))
    {
        db.CommandTimeout = commandTimeout;
        return db.GetTable<T>(true);
    }
}
```

**Comment by ili** [comment]
@worldofsites don't do like this!

You see, when you are going out of using, `DataConnection` is disposed, but LINQ is lazy, so real query would be called later, when you will enumerate your `IQuerable`. 

So on query your connection would be reopened, but would not be closed (by default). When you pass true  to `GetTable` method, this means "dispose connection after each query", that's why you solved problem with connections. But in general this is an antipattern.

In your case it is better to use `DataContext` rather then `DataConnection`

**Comment by worldofsites** [comment]
@ili Thanks, we will try to implement this `DataContext`

**Comment by sdanyliv** [comment]
@worldofsites, which framework do you use for Web? ASP.NET MVC?

**Comment by worldofsites** [comment]
@sdanyliv ASP.NET MVC

**Comment by sdanyliv** [comment]
@worldofsites, do You use Dependency Injection? If yes, it is easy to setup ASP.NET to accurately dispose DataConnection after each Web request. It means after sending everything to client.

**Comment by sdanyliv** [comment]
@worldofsites, note in similar situation EF will throw "The operation cannot be completed because the DbContext has been disposed."
It is our defect that we left query runnable after disposing DataConnection.
