### ISSUE TITLE
Fluent ....HasTableName(..) works only first time (version 1.0.7.4)

### ISSUE THREAD

**Issue by mr-clx** [linq2db/linq2db#446]
Seems like changing mapping TableName with fluent mapping works only once per process instance.

Example:
I have a set of tables with same data models. 

```
        // Data model class (for different tables):
        public class SomeModel
        {
            [Column("id")]
            public int Id { get; set; }
            [Column("field")]
            public string Field { get; set; }
        }

        // Testing mapping same class with different tables (in different instances of DbConnection!)
        public void Test()
        {
            var confName = "Test";

            // map to table1
            using (var db = new LinqToDB.Data.DataConnection(confName))
            {
                db.MappingSchema.GetFluentMappingBuilder().Entity<ModelBase>().HasTableName("table1");
                var q = db.GetTable<ModelBase>(); // = sql=... from "table1"...
                var t = q.ToArray();  // <--- mapped to "table1" 
            }
            // map to table2
            using (var db = new LinqToDB.Data.DataConnection(confName))
            {
                db.MappingSchema.GetFluentMappingBuilder().Entity<ModelBase>().HasTableName("table2");
                var q = db.GetTable<ModelBase>(); // = sql=... from "table1"... !!
                var t = q.ToArray();  // <--- still mapped to "table1", not "table2"  !!!
            }
        }

```

I am using linq2db version 1.0.7.4
Maybe I've missed something?

**Comment by sdanyliv** [comment]
Why you do not use db.GetTable<ModelName>.TableName('table1').Select... ?

**Comment by mr-clx** [comment]
Thank you for this solution!
It will work for me.

But anyway, why GetFluentMappingBuilder....  does now work as expecting ?

**Comment by sdanyliv** [comment]
Sorry, never tried that ;) 
But remember that there are some method to reset mapping caches. Not sure.

**Comment by mr-clx** [comment]
Ok. It's ok to set table name for queries (... TableName()...)
But how can I set table name for update/insert operations?
i.e.  .... Update(MyObject)

**Comment by springjazzy** [comment]
Still doesn't work with updates/deletes since Query is cached in LinqToDB.Linq.QueryRunner.Update<T> ->_queryChache dictionary. If I map entity to one table, update it, then to another all subsequent updates will be made into first mapped entity.

**Comment by sdanyliv** [comment]
We will cover these Update and Inserts in this issue https://github.com/linq2db/linq2db/issues/1026

**Comment by sdanyliv** [comment]
Also please post pseudo code how do you change mapping schema.
Thanks!

**Comment by springjazzy** [comment]
`public class SyncBuffer
{
	  [Column, PrimaryKey, NotNull]
      public Guid LINK { get; set; }
      
       [Column, NotNull]
       public Guid MessageGUID { get; set; }
}

void Update1(SyncBuffer buffer, string connString)
{
	buffer.MessageGUID = Guid.NewGuid(); 	// Change smth 
  
	string tableName = "TableA"; 			// We're going TO UPDATE TABLEA
	// HACK: Need TO pass UNIQUE dataprovider NAME since it's the key to update query cache
	using (var dc = new DataConnection(new SqlServerDataProvider(tableName, SqlServerVersion.v2012), connectionString))
	//using (var dc = new DataConnection(new SqlServerDataProvider("", SqlServerVersion.v2012), connectionString))
	{
		 dc.MappingSchema.GetFluentMappingBuilder().Entity<SyncBuffer>()
                    .HasTableName(tableName);	
          dc.Update()
	}
}

void Update2(SyncBuffer buffer, string connString)
{
	buffer.MessageGUID = Guid.NewGuid(); 	// Change smth 
  
	string tableName = "TableB"; 			// We're going TO UPDATE TABLEA
	// HACK: Need TO pass UNIQUE dataprovider NAME since it's the key to update query cache. WITHOUT it UPDATE would be directed TO previous TableA
	using (var dc = new DataConnection(new SqlServerDataProvider(tableName, SqlServerVersion.v2012), connectionString))
	//using (var dc = new DataConnection(new SqlServerDataProvider("", SqlServerVersion.v2012), connectionString))
	{
		 dc.MappingSchema.GetFluentMappingBuilder().Entity<SyncBuffer>()
                    .HasTableName(tableName);	
          dc.Update()
	}
}

void Main()
{
	...
	var syncBuffer = GetTableAAsSyncBuffer();
	Update1(syncBuffer, connString);
	...
	var syncBuffer = GetTableBAsSyncBuffer();
	Update2(syncBuffer, connString)
}`

**Comment by sdanyliv** [comment]
I’ll try to find time to look at, but could you please try this variant:
```cs
var schema = new MappingSchema();
using (var dc = new DataConnection(new SqlServerDataProvider(tableName, SqlServerVersion.v2012), connectionString))
{
      schema.GetFluentMappingBuilder().Entity<SyncBuffer>()
         .HasTableName(tableName);	
      dc.AddMappingSchema(schema);
      dc.Update()
}
```

**Comment by springjazzy** [comment]
Checked. It works if tableName is unique for each update. If I use same ProviderName(like empty string) second update is directed into TableA. So nothing is changed - unique provider name does the job.

**Comment by sdanyliv** [comment]
Just checked code. Yes there is problem. Will try to figure out how to fix.

**Comment by springjazzy** [comment]
Awesome. Thanks in advance!
