### ISSUE TITLE
default-schemas  not working

### ISSUE THREAD

**Issue by MoeHamdan** [linq2db/linq2db#4466]
I am trying to generate classes without the schema name in them. According to https://[linq2db.github.io/articles/cli-help.txt](https://linq2db.github.io/articles/cli-help.txt) I should be using --default-schemas. I tried this in cli as parameter and did not work, I also tried it in the json file that I pass a argument to scaffold and that did not work either. The generated classes always have the name of the schema in it.

Kindly advice.

`Linq To DB` version: 5.4.0

Database (with version):SQL Server 2022

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.2.0

Operating system: Windows 11

.NET Version: .NET 8

**Comment by MaceWindu** [comment]
Schema name not included to class name only for default schemas or schemas, generated into separate wrapper class, so there are 3 solutions:

1. use interceptor to rename generated classes
2. generate schema with wrapper (`--schema-as-type false`)
3. use following options set: `--schema-as-type false --include-default-schema-name true --default-schemas myschema,dbo`, where:

 - `--schema-as-type false` : disable wrapper for schema
 - `--default-schemas myschema,dbo` : mark required schemas as default so they will not have schema name prepended to class name
 - `--include-default-schema-name true` generate schema name mapping for default schema objects. Needed if schema is not really default for database user and must be specified in query
