### ISSUE TITLE
How do i make nested LoadWith

### ISSUE THREAD

**Issue by retorres** [linq2db/linq2db#448]
Hello,
I need to call nested dependencies,
Like:
`_context.Visita
                .LoadWith(d => d.TalhaoPlanoOperacionalOperacoes)
                .LoadWith(d => d.TalhaoPlanoOperacionalOperacoes.select(x=>x.TalhaoPlanoOperacionalOperacaoInsumos)).ToList();`

its similar to this issue (https://github.com/linq2db/linq2db/issues/214), that u had said to use:
`db.Directory.LoadWith(d => d.Files[0].Properties);`

but i cannot use like that, because, i cant access a index of IEnumerable.
how can i procede with this?

**Comment by SlowLogicBoy** [comment]
IEnumerable.GetEnumerator().Current doesn't work?

**Comment by retorres** [comment]
Nop. :(
Member 'd.TalhaoPlanoOperacionalOperacoes.GetEnumerator().Current' is not an association.

**Comment by sdanyliv** [comment]
How about to use d.TalhaoPlanoOperacionalOperacoes.First() ?

**Comment by jogibear9988** [comment]
@retorres does it work now? can this be closed?

**Comment by ili** [comment]
Closing
