### ISSUE TITLE
List of improvements for Preview 2

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#4494]
Below I will add list of issues and potential improvements, found in baselines from new parser feature that we should review and fix it it makes sense for next preview(s). Only one test per-issue mentioned as example usually.

- `SelectManyUpdateTests.Test1`: IN predicate optimization `[x].[ParentID] IN (0, 0)`
- `SelectManyUpdateTests.Test2`: False predicate minification `1 = 0 AND a_Children_1.ParentID` = a_Children.ChildID`
- `Issue461Tests.SelectToAnonymousTest2`: review current policy how to populate columns for select to avoid unnecessary transfers `SELECT l.ParentID + 1, l.ParentID`
- `UserTests.Issue4383Tests.Test`: duplicate columns in eager load
- `Issue3402Tests.ColumnOptimization`: avoid optimized `true` filter generation `WHERE 1=1`
- `Issue3148Tests.TestDefaultExpression_22` LEFT JOIN with false condition could be removed `ON 1=0`
- `Issue0082Tests.Test1(SqlCe` unused OUTER APPLY should be removed
- remove parameter casts from insert/update setters for FB, DB2
- `OrmBattleTests.DateTimeTest`: predicate function optimization regression
- `SqlServerTests.TablesInScopeHintTest`:  duplicate predicates in AND optimization
- `AnalyticTests.TestStdDev` and others : duplicate columns
- `AssociationTests.AssociationExpressionNullCount`: unused left join not removed
- `ConcatUnionTests.UnionGroupByTest2` : duplicate columns

**Comment by jods4** [comment]
> `Issue0082Tests.Test1(SqlCe` unused OUTER APPLY should be removed
If someone tackles this one: only if its cardinality is known to be 0 or 1.

**Comment by MaceWindu** [comment]
Already addressed in preview1
