### ISSUE TITLE
StringAggregate with GroupBy on SQL Server

### ISSUE THREAD

**Issue by brianvonkuster** [linq2db/linq2db#4501]
Hi,

I've been running into an issue when trying to use StringAggregate with a GroupBy clause when executing against SQL Server (2017, 2019, 2022).

When I run the equivalent of the following code:

```
public class ProductInfo
{
	public int Id { get; set; }
	public string AggregatedDescription { get; set; }
}

public class Product {
	[Column]
	public int Id { get; set; }
	
	[Column]
	public string Description { get; set; }
}

public class ProductService {
	public ITable<Product> Products => GetTable<Product>();

	public IEnumerable<ProductInfo> GetAggregatedDescriptions() 
	{
		var productsGrouped = Products
			.GroupBy(x => x.Id)
			.Select(g => new ProductInfo {
				Id = g.Key,
				AggregatedDescription = g.StringAggregate(", ", x => x.Description)
			});
			
		return productsGrouped.ToList();
	}
}
```

I get an exception thrown -- 
```
LinqToDB.LinqToDBException: 'You should explicitly specify selected fields for server-side GroupBy() call or add AsEnumerable() call before GroupBy() to perform client-side grouping.
Set Configuration.Linq.GuardGrouping = false to disable this check.
Additionally this guard exception can be disabled by extension GroupBy(...).DisableGuard() or using options.UseGuardGrouping(false) configuration extension.
```

Disabling the guard doesn't seem to help, as Linq2Db throws an exception saying `StringAggregate` is a serverside function. Not sure if this is a potential bug or I'm doing something wrong, I've tried several permutations including `g.StringAggregate(", ", x => x.Description).ToValue()` to no avail.

**Comment by sdanyliv** [comment]
Looks like you have returned tuple `(int Id, string AggregatedDescription)`, but query is written using anonymous class. Where is true?

**Comment by brianvonkuster** [comment]
Whoops, sorry. I was cutting a class out and messed that up. I edited the example to be fully functional now.

I tried `g.StringAggregate(", ", x => x.Description).ToValue()`, however when I do that I get the exception `LinqToDB.Linq.LinqException: ''g.StringAggregate(",", x => x.Description).ToValue()' cannot be converted to SQL.'`

**Comment by MaceWindu** [comment]
This happens when unsupported dialect used and linq2db tries to evalue function on client. You should review your configuration - looks like you use older dialect (e.g. 5.2.2 use SQL Server 2008 dialect as default of auto-detect not set and explicit dialect not specified)
