### ISSUE TITLE
Npgsql.PostgresException: '23505: duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by Snazzie** [linq2db/linq2db#4511]
### Describe your issue

exception thrown when duplicate key exists. I would like it to ignore on duplicate instead.

Exception message:
```
Npgsql.PostgresException: '23505: duplicate key value violates unique constraint "IX_PostgresQueries_QueryId_TargetId"

DETAIL: Key ("QueryId", "TargetId")=(-5316830640525975270, 3) already exists.'
```

### Steps to reproduce

Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
    public async static Task BulkUpsertAsync<TEntity>(this DbContext dbContext, IEnumerable<TEntity> entities) where TEntity: class
    {
       await dbContext.GetTable<TEntity>()
        .Merge("HOLDLOCK")
        .Using(entities)
        .OnTargetKey()
        .InsertWhenNotMatched()
        .MergeAsync();
    }

    [Index(nameof(QueryId), nameof(TargetId), IsUnique = true)]
    public class PostgresQueryModel
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public long Id { get; set; }
        [Required]
        public long QueryId { get; set; }
        [Required]
        public long TargetId { get; set; }
        [Required]
        public string QueryText { get; set; }

    }
```

### Environment details

`Linq To DB` version: *8.1*

Database (with version): *postgres 15* 

Operating system: *win 11*

.NET Version: *8*

**Comment by MaceWindu** [comment]
Such functionality is not supported by SQL MERGE https://www.postgresql.org/docs/current/sql-merge.html

You sould specify custom conditions for ON and/or update/insert clauses to avoid such insterts
