### ISSUE TITLE
Assign extra properties to the object leads to query parsing fail

### ISSUE THREAD

**Issue by Firebie** [linq2db/linq2db#4518]
### Assign extra properties to the object leads to query parsing fail.
```
Exception message:
Constant 'value(xx.xxx+<>c__DisplayClass63_1)' is not replaced.
Stack trace:
```

### Steps to reproduce

```c#
          var extraProperty = new Dictionary<int, int>();

          var test = dc.EntityWithString
            .Select(i => new EntityView { ExtraProperty = extraProperty, String = i.String })
            .Select(i => i.String)
            .Distinct()
            .OrderBy(i => i)
            .ToList();

```

### Environment details

`Linq To DB` version: 6.0.0.0

Database (with version): SQL Server 2017

ADO.NET Provider (with version): Microsoft.Data.SqlClient 3.1.15

Operating system: Windows 10

.NET Version: 4.8

**Comment by sdanyliv** [comment]
Well, it is should be exception only in Debug Mode. We check that we do not cache big closures to save memory. Anyway thanks, will take a look at this.

**Comment by Firebie** [comment]
How can I disable it? I am using debug version of linq2db.

**Comment by sdanyliv** [comment]
Currently only by commenting this line https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Query.cs#L589
