### ISSUE TITLE
Power only accept doubles

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#4528]
## Problem
linq2db implementation of Power only accepts doubles and not decimals, unlike all other Math functions such Log or Round.

`Sql.Power`: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.cs#L1339
`Math.Pow`: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Expressions.cs#L1014

## Consequences
This can lead to subtle inaccuracies when using constants.
For example, consider expression `x * Sql.Power(10, 2)` when field `x` is `8.7345`:

In Oracle, when arguments are double, generated code is `x * Power(10d, 2d)`. Notice the `d` suffix which means the type is a `BINARY_DOUBLE`. Float arithmetic then leads to value `873.449999999999` and by default Oracle/linq2db will truncate this into `NUMBER` type with value `873.4499` not exactly the expected value.

If we had `decimal` overload the SQL would be `x * Power(10, 2)`. Now Oracle performs the computation using `NUMBER` type and the result is exactly `837.45`.

## Suggestion
Add `decimal` overload in the two places linked above.

**Comment by riktimmondal** [comment]
Hi.
Raise a PR https://github.com/linq2db/linq2db/pull/4635.
Please review.
