### ISSUE TITLE
T4 Template for Oracle is very slow. Can generate the model about 5 minutes.

### ISSUE THREAD

**Issue by inickvel** [linq2db/linq2db#453]
Slow downs the method OracleSchemaProvider.GetForeignKeys(DataConnection dataConnection).

**Comment by sdanyliv** [comment]
Not sure but It can be stored procedures. For defining their result type they have to be executed once.

**Comment by inickvel** [comment]
My script fetching foreigh keys about 10 seconds or faster.

**Comment by sdanyliv** [comment]
And? Your database only have foreign keys or **Stored Procedures** also?

**Comment by sdanyliv** [comment]
Try to comment out in DataModel.tt from line 162

```cs	
		var procedures = db.Procedures
		.Select(p => new
		{
			p,
```
to the end of function

**Comment by inickvel** [comment]
Slow downs the method protected override List<ForeingKeyInfo> GetForeignKeys(DataConnection dataConnection) of the OracleSchemaProvider.

**Comment by inickvel** [comment]
GetForeignKeys method has something to do with stored procedures?

**Comment by sdanyliv** [comment]
It is what you have to provide in description of your ticket.
