### ISSUE TITLE
Improve result mapper performance

### ISSUE THREAD

**Issue by DerMagereStudent** [linq2db/linq2db#4545]
### Describe your issue

Is there a way to improve the performance of the ORM mapper of Linq2Db using the `FirebirdDataProvider`. I retrieve 1831 records from a table having 39 columns (all `INTEGER`, `DECIMAL(13,5)` and `2x VARCHAR(100)`). The longest varchar is 37 chars. Approximately 60% of all the values are null. I tried to log what takes so much time:

```c#
var sw = new System.Diagnostics.Stopwatch();
this.db.OnTraceConnection = (traceInfo) =>
{
    switch (traceInfo.TraceInfoStep)
    {
        case TraceInfoStep.BeforeExecute:
            sw.Start();
            break;
        case TraceInfoStep.AfterExecute:
            Console.WriteLine($"DB Request Time: {sw.ElapsedMilliseconds} ms");
            sw.Restart();
            break;
        case TraceInfoStep.Completed:
            Console.WriteLine($"Mapping Time: {sw.ElapsedMilliseconds} ms");
            break;
    }
};
```

Here is the result:

```none
DB Request Time: 49 ms
Mapping Time: 1805 ms

DB Request Time: 43 ms
Mapping Time: 1870 ms

DB Request Time: 47 ms
Mapping Time: 1653 ms

DB Request Time: 40 ms
Mapping Time: 1820 ms
```

Network should also not be the bottleneck. The last check I did resulted in 898.4 Mbit/s

I tried to use compiled queries but this did not improve the query at all:

```none
DB Request Time: 45 ms
Mapping Time: 1953 ms

DB Request Time: 47 ms
Mapping Time: 1804 ms

DB Request Time: 48 ms
Mapping Time: 1832 ms

DB Request Time: 41 ms
Mapping Time: 1881 ms
```

I also tried to increase the fetch-size and packet-size:

```c#
protected override Task<DbDataReader> ExecuteReaderAsync(IDbCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken)
{
    if (command is FbCommand fbCmd)
    {
        fbCmd.FetchSize = 1000; // was 200 by default
    }

    return base.ExecuteReaderAsync(command, commandBehavior, cancellationToken);
}
```

### Query

```c#
var result = await (
    from cd in this.dbCaps.CapsDepts
    join c in this.dbCaps.CAPS on cd.CapId equals c.CapId
    where deptIds.Contains(cd.DeptId)
    select c
).Distinct().ToListAsync();
```

### Environment details

PC specs:

- i7-13700K
- 64GB 4000MHz

`Linq To DB` version: Tried 3.5.1 and 4.4.1

Database (with version): Firebird 3.0.9

ADO.NET Provider (with version): FirebirdSql.Data.FirebirdClient - tried 9.9.1 and 10.3.1

Operating system: Windows 11 23H2

.NET Version: Tried net7 and net8

**Comment by MaceWindu** [comment]
How you determined it is mapper issue? Do you have any profiling results to share?

**Comment by jods4** [comment]
The most likely bottleneck is not mapping records to objects but getting records from DB.

When Execute completes, no result has been fetched from the server yet. The RDBMS is ready to send the first results over the wire and on .NET side you get a DbDataReader.

Then as the DbDataReader is read, the RDBMS needs to find the next results (which is heavily query dependent. It could involve full table scans and take minutes for zero actual result) and send them down the wire.

If you want to isolate the cost of just the mapper, you should benchmark code that uses the mapper vs code that reads exactly the same data (consuming all rows and all columns) straight from the DbDataReader.
The difference between the two should be mostly the object mapper cost.

**Comment by DerMagereStudent** [comment]
Okay then I got `TraceInfoStep.AfterExecute` wrong. I compared the raw execution with the mapper execution using this code:

```c#
var query = (
    from cd in this.dbCaps.CapsDepts
    join c in this.dbCaps.CAPS on cd.CapId equals c.CapId
    where deptIds.Contains(cd.DeptId)
    select c
).Distinct();

var sw = Stopwatch.StartNew();
var cmd = this.dbCaps.CreateCommand();
cmd.CommandText = query.ToString();
using (var reader = cmd.ExecuteReader())
{
    var values = new object[reader.FieldCount];
    while (reader.Read())
    {
        reader.GetValues(values);
    }
}
sw.Stop();
Console.WriteLine($"Raw Time: {sw.ElapsedMilliseconds} ms");

sw.Restart();
var result = await query.ToListAsync();
sw.Stop();
Console.WriteLine($"With Mapping Time: {sw.ElapsedMilliseconds} ms");
```

Here is the result:
```
Raw Time: 1579 ms
With Mapping Time: 1682 ms

Raw Time: 1710 ms
With Mapping Time: 1904 ms

Raw Time: 1701 ms
With Mapping Time: 1885 ms

Raw Time: 1695 ms
With Mapping Time: 1797 ms
```

The problem is I also tested the code on my colleagues computer. Specs:
- i7-11850H
- 64GB 3200MHz

Here is the result:
```
Raw Time: 6819 ms
With Mapping Time: 6954 ms

Raw Time: 6868 ms
With Mapping Time: 6851 ms

Raw Time: 6784 ms
With Mapping Time: 6842 ms

Raw Time: 6729 ms
With Mapping Time: 6950 ms
```

We both access the same database server. The network is also not the bottleneck. So its still a client side problem although not a problem of the mapper. The table size (based on `RDB$RELATION_FIELDS.RDB$FIELD_LENGTH`) is ~4MB, for 2106 records with all values NOT NULL. But as I already mentioned about 60% of the values are null. Handling less than 4MB should not take 7 seconds.

**Comment by MaceWindu** [comment]
Wel, if you get same numbers with raw provider calls and sure it is client related, you should report it to client repository here https://github.com/FirebirdSQL/NETProvider/issues
