### ISSUE TITLE
Enhancement: Add generated SQL and other information to activity span tags

### ISSUE THREAD

**Issue by warappa** [linq2db/linq2db#4561]
### More Details in Tags
It would be great if Activities like "ExecuteQuery", "BuildSql" and/or "CommandExecuteReader" would provide a little more information about the query being generated and executed. Something like
- Generated SQL
- Parameters (maybe configurable because of privacy issues)
- Database name

A template could be the SqlClient OpenTelemetry integration which adds the following fields:
- `db.name` (eg. `Northwind`)
- `db.statement` (eg. `SELECT * FROM Users WHERE Modified > @p0`)
- `db.system` (eg. `mssql`)
- `peer.service` (eg. `(localdb)\MSSQLLocalDB`)

For reference, this is the SqlClient OpenTelemetry implementation:
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/93c7a6980ed1043ad2bc21763192f8e1e981631a/src/OpenTelemetry.Instrumentation.SqlClient/Implementation/SqlClientDiagnosticListener.cs#L126

### Steps to reproduce
1. Follow the steps outlined in [ActivityService (Metrics)](https://github.com/linq2db/linq2db/blob/master/Examples/Metrics/README.md) 
2. Execute and look at the tags provided in the span - no SQL specific tags
3. Add `OpenTelemetry.Instrumentation.SqlClient` and configure it like described here: [Configure SqlClient Integration](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/93c7a6980ed1043ad2bc21763192f8e1e981631a/src/OpenTelemetry.Instrumentation.SqlClient)
4. Run any query against the database
5. Look at the tags inside the span and find the aforementioned tags

### Environment details

`Linq To DB` version: 5.4.1

Database (with version): SQL Server 2019 (15.0.4153)

ADO.NET Provider (with version): e.g. Microsoft.Data.SqlClient 5.2.1

Operating system: Windows 10 22H2 (Build 19045.4529)

.NET Version: .NET 8.0

**Comment by igor-tkachev** [comment]
We can set DataContext as a tag. It contains all the information.

**Comment by warappa** [comment]
As I see it, adding the `DataContext` _itself_ would not be that beneficial as a span tag (and I'm not sure if this is even possible as it must be serializable).

I think looking for callsites of `ActivityService.Start...` and adding _there_ the available information would be necessary (like [here](https://github.com/linq2db/linq2db/blob/0bdc5ed2059f35efada459cd5420d5232607250a/Source/LinqToDB/Data/DataConnection.cs#L1135)). But as I see, the `LinqToDB.Tools.IActivity` interface is just a marker-interface and does not allow passing the context nor exposing the underlying `System.Diagonstics.Activity` (or its functionality).

Anyway, to me the caller of `ActivityService.Start...` should have **a way to provide tags/contextual information**. Or (as one already needs to implement some method to pass to `ActivityService.AddFactory(...)`) why not **extend this API to require(?) a DataContext** so the `IActivity` implementation can extract the necessary information and add it to the started `Activity`?

Like:
```diff
public static class ActivityService
{
-    public static void AddFactory(Func<ActivityID, IActivity?> factory)
+    public static void AddFactory(Func<ActivityID, DataContext, IActivity?> factory)
}
```

But that would be a breaking change...
