### ISSUE TITLE
Contributors guide needed

### ISSUE THREAD

**Issue by inickvel** [linq2db/linq2db#457]

**Comment by sdanyliv** [comment]
As i saw erlier igor uses only tabs for starting lines

**Comment by inickvel** [comment]
Yes, he uses tabs for starting lines, but uses spaces for right alignment sql. Example:
						SELECT
							FKCON.CONSTRAINT_NAME                  as Name,
							FKCON.OWNER || '.' || FKCON.TABLE_NAME as ThisTableID,
							FKCOLS.COLUMN_NAME                     as ThisColumn,
							PKCON.OWNER || '.' || PKCON.TABLE_NAME as OtherTableID,
							PKCOLS.COLUMN_NAME                     as OtherColumn,
							FKCOLS.POSITION                        as Ordinal

**Comment by sdanyliv** [comment]
Another ambigous issue. From subject there is no way to underastand you :)
If you create issue, please decribe your thoughts.
Also pull request without description is like nightmare for reviewers.

**Comment by ili** [comment]
Tabs should be used. Spaces (if any) would be replaced...
In any way we'll need to create contributors guide...

**Comment by inickvel** [comment]
I think we need editor.config also. VS 2017 support it.

**Comment by inickvel** [comment]
Benefits of spaces is that they displayed equally regardless of IDE customization.

**Comment by sdanyliv** [comment]
We do have https://github.com/linq2db/linq2db/blob/master/.editorconfig

**Comment by ili** [comment]
Code style is not the thing to discuss. Whole library is written in one style.

**Comment by MaceWindu** [comment]
Looks like already addressed by https://github.com/linq2db/linq2db/wiki/Contributor-Guide
