### ISSUE TITLE
How to get column Description?

### ISSUE THREAD

**Issue by ckhker** [linq2db/linq2db#459]
when run T4 make model ,How to get column Description?

**Comment by sdanyliv** [comment]
Please describe your request more clearly

**Comment by ckhker** [comment]
i mean, when i use mssql, and i have field description in my sql, and i how to get it when i run CopyMe.SqlServer.tt

like

public class User{
///<summary>
///Auto increment ID
/// </summary>
public int userid{get;set;}
///<summary>
/// this is user Name
/// </summary
public string username{get;set;}
}

i want make model like this
