### ISSUE TITLE
DataConnection :  Dynamic class mapping

### ISSUE THREAD

**Issue by AlthalusDGr8** [linq2db/linq2db#460]
Is there a way to dynamically registering the connection with the tables that belong to it? I like to split my entities into different Dlls according to use case (such as splitting user data and finance data into separate libraries) and I want the DataConnection to scan the assemblies on application start to find the classes with the Table attribute applied.

**Comment by sdanyliv** [comment]
You always can use `dc.GetTable<TableEntity>()`
No registerings are required

**Comment by AlthalusDGr8** [comment]
thanks  works like a charm :)
