### ISSUE TITLE
Select Into/Insert with Identity with OVERRIDING SYSTEM VALUE

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#4601]
Using DB2 data provider, when I execute the following select into insert:

```
var q = from p35 in db.Product.IsCompanyCode("S1").IsItemCode("74249")
        from x35 in db.ProductExtension.Where(x=> x.Code == p35.Code).DefaultIfEmpty()
        where x35.Code == null
        select new { p35.Code };
      
var records = q.Into(db.ProductExtension)
       .Value(x=> x.Id, x=> int.Parse(x.Code))
       .Value(x=> x.Code, x=> x.Code)        
       .Insert();
```

It generates the SQL below:
```
INSERT INTO Product(ID, Code)
SELECT Int(p.Code), p.Code
FROM Product
LEFT JOIN ProductExtension x ON x.Code = p.Code
WHERE x.Code IS NULL 
```

The following exception is thrown 

```
ERROR [HY000] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0798 - Value cannot be specified for GENERATED ALWAYS column ID.
```

**DB2** supports using ***OVERRIDING SYSTEM VALUE*** to override the generated identity value with a custom one.

Is there any way to add ***OVERRIDING SYSTEM VALUE*** (or equivalent for other data providers) to the insert generated SQL statement ?

Fix should not be specific to DB2 data provider, rather a solution that would work with any data provided would be appreciated.

### Environment details

`Linq To DB` version: 5.4.1

Database (with version): DB2, Microsft Access, Sql Server, DB2 iSeries (using [Linq2DB4iSeries](https://github.com/LinqToDB4iSeries/Linq2DB4iSeries))

ADO.NET Providers (with version): 
* Microsoft.Data.SqlClient 4.1.0
* System.Data.Odbc
* System.Data.OleDb
* IBM.DB2.Data.iSeries

Operating system: Win 10

.NET Version: 4.8.1

**Comment by MaceWindu** [comment]
This is actually provider-specific issue. We have mechanisms to define query hints. iSeries provider just need to implement specific table hint API and add sql generation for it.

**Comment by nsarris** [comment]
Hi @MaceWindu , sorry for replying to this after all this time. This could be supported if there was a hook in SqlBuilder before the INSERT statement "VALUES" token and the UPDATE statement "SET" token. Is this possible?
