### ISSUE TITLE
Bug: conversion error from string "1" appears when record containing boolean values is inserted to Firebird database

### ISSUE THREAD

**Issue by ranger-turtle** [linq2db/linq2db#4619]
### Description

I want to insert data to table with boolean type columns using Linq2db, but I get an exception described below:

```
Exception message:
FirebirdSql.Data.FirebirdClient.FbException: 'conversion error from string "1"'

Stack trace:
FirebirdSql.Data.Client.Managed.IResponseExtensions.HandleResponseException(FirebirdSql.Data.Client.Managed.IResponse)
FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponseAsync(System.Threading.CancellationToken)
    System.Threading.Tasks.ValueTask<TResult>.Result.get() in ValueTask.cs
    FirebirdSql.Data.Client.Managed.Version12.GdsStatement.ExecuteAsync(int, FirebirdSql.Data.Common.IDescriptorFiller, System.Threading.CancellationToken)
    FirebirdSql.Data.Client.Managed.Version12.GdsStatement.ExecuteAsync(int, FirebirdSql.Data.Common.IDescriptorFiller, System.Threading.CancellationToken)
    FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommandAsync(System.Data.CommandBehavior, bool, System.Threading.CancellationToken)
    FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQueryAsync(System.Threading.CancellationToken)
```

### Steps to reproduce

1. Clone solution at https://github.com/ranger-turtle/FirebirdBooleanTester;
2. Make sure that Firebird 3 is running;
3. Replace given placeholder to absolute path to LOCAL.FDB in Program.cs file, line 4;
4. Run program.

### Environment details

Linq To DB version: 5.4.1

Database (with version): Firebird 3.0.10

ADO.NET Provider (with version): FirebirdSql.Data.FirebirdClient 10.3.1

Operating system: Microsoft Windows 10

.NET Version: 8

**Comment by MaceWindu** [comment]
Built-in Firebird boolean type support [available](https://github.com/linq2db/linq2db/issues/1024) only starting from version 6. You could try to switch to `6.0-preview.1`.

As workaround for older versions you need to configure required mappings manually:

```cs
// for literals support
mappingSchema.SetValueToSqlConverter(typeof(bool), (sb, type, value) => sb.Append((bool)value ? "true" : "false"));
```

for parameters it is more complex - you need to sub-class provider to disable those lines: https://github.com/linq2db/linq2db/blob/ca363a2f97ae46de94beea4678ecca245ccd3382/Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs#L85-L89

or you can disable parameters by setting `db.InlineParameters = true` property

**Comment by ranger-turtle** [comment]
Thank you for answer.
At least, people will quickly find out what they should do if this error occurs...
Unless they use version 6...
