### ISSUE TITLE
Using Expressions like to LowerInvariant is not supported

### ISSUE THREAD

**Issue by AlthalusDGr8** [linq2db/linq2db#463]
Are there plans to support in the linq syntax stuff like to lower invariant etc?  Am trying to query something of the sort:
var languageListQuery = from l in db.GetTable<Language>()
                                        where (
                                            (l.ThreeLetterCode.ToLowerInvariant() == isoCode.ToLowerInvariant()) || (l.TwoLetterCode.ToLowerInvariant() == isoCode.ToLowerInvariant()))
                                        select l;

**Comment by ili** [comment]
@AlthalusDGr8 what difference in `SQL` should be with common `string.ToLower()`

**Comment by jogibear9988** [comment]
Maybe we should look that ToLowerInvariant works (don't know if it does), and does the same as ToLower

**Comment by ili** [comment]
don't know =((
we can easily make `ToLowerInvariant` the same as `ToLower` and it will produce the same SQL, but i do not think that it is right

**Comment by jogibear9988** [comment]
don't know if SQL supports cultures on tolower?

If so, this would be different on all databases.

If not, I think, to use the same is correct!

(ToUpperInvariant exists also!)

**Comment by AlthalusDGr8** [comment]
I think in SQL terms they don't make any difference. So I guess it can be treated as the ToLower and let the C# handle the character conversion

**Comment by ili** [comment]
@AlthalusDGr8 then it is not clear how should we support it.
If `ToLowerInvariant()` in `linq2objects` and in `linq2db` would return different results it would be not safe

**Comment by ili** [comment]
Good point - you can configure it yourself :) 
I'll prepare an example little bit later

**Comment by ili** [comment]
You can read this post about extensibility http://blog.linq2db.com/2016/06/how-to-teach-linq-to-db-convert-custom.html?m=1

Also this should work:
```cs
Expressions.MapMember(() => "".ToLowerInvariant(), () => ToLower())
```

**Comment by jogibear9988** [comment]
seems also ef is not supporting this. (http://stackoverflow.com/questions/4541959/ef-query-using-contains-and-tolowerinvariant-results-in-no-matches-when-ma)

i will create a test if it works with your example, then we can close!

**Comment by ili** [comment]
Good, thanks :)

**Comment by ili** [comment]
Here is the sample how can you configure linq2db to support needed expressions
```cs
		[Test, DataContextSource]
		public void ToLowerInvariantTest(string context)
		{
			Expressions.MapMember((string s) => s.ToLowerInvariant(), (string s) => s.ToLower());

			using (var db = GetDataContext(context))
			{
				AreEqual(
					   Doctor.Where(p => p.Taxonomy.ToLowerInvariant() == "psychiatry").Select(p => p.Taxonomy.ToLower()),
					db.Doctor.Where(p => p.Taxonomy.ToLowerInvariant() == "psychiatry").Select(p => p.Taxonomy.ToLower()));
			}
		}
```
