### ISSUE TITLE
Support DeleteWhenNotMatchedBySourceAnd for Postgres 17

### ISSUE THREAD

**Issue by alexeynikitin** [linq2db/linq2db#4655]
Current [documentation](https://www.postgresql.org/docs/current/sql-merge.html) for Postgres 17 says that MERGE clause supports WHEN NOT MATCHED BY SOURCE [AND] statement,
but DeleteWhenNotMatchedBySourceAnd throws an exception with Postgres provider.

Is there any plan to support this feature?

**Comment by MaceWindu** [comment]
pg17 support is planned for next release
