### ISSUE TITLE
NodaTime Period BulkCopy not mapping

### ISSUE THREAD

**Issue by sjdaniel10** [linq2db/linq2db#4672]
Hi there,

I have the following code:

```cs
var ms = MappingSchema.Default;
//ms.SetConverter<NodaTime.Period?, TimeSpan>(period => period != null ? TimeSpan.FromSeconds(period.Seconds) : TimeSpan.Zero);
ms.SetConverter<NodaTime.Period, TimeSpan>(period => TimeSpan.FromSeconds(period.Seconds));
ms.SetConverter<NodaTime.Period, DataParameter>(period =>
{
    return new DataParameter
    {
        Value = TimeSpan.FromTicks(period.Ticks),
        DataType = LinqToDB.DataType.Interval
    };
});
var dbOptions = new DataOptions().UseConnection(PostgreSQLTools.GetDataProvider(connectionString: connectionString), connection)
.UseMappingSchema(ms);
var dbConnection = new DataConnection(dbOptions);
await dbConnection.BulkCopyAsync(new BulkCopyOptions { TableName = tableName, KeepIdentity = keepIdentity }, entities);
await dbConnection.CloseAsync();
```

Extra information:
I am passing in a npgsqlConnection which has been built using the following:
```cs
dataSourceBuilder = new NpgsqlDataSourceBuilder(_dbSettings.ReportingDbConnection);
dataSourceBuilder.UseNodaTime();
_reportingDataSource = dataSourceBuilder.Build();
```
and is being passed to as an npgsqlConnection connection, ie:
```cs
reportingDataSource.OpenConnection()
```

I am using:
npgsql 8.0.3 and linqtodb 5.4.1
Postgresql13
dotnet core 8.0

The problem:
I am trying to post a list of typed objects and within those objects contains NodaTime.Period's, I have created a test object explicitly to test, it does not seem like I am able to post Period objects via the BulkCopyAsync method, they end up as null in the database, funny enough, NodaTime.Instants are working fine.

Please advise if you can see anything wrong here, I have gone through the other issues in the issues tabs and found similiar issues which may help - which is how I got the syntax of the above "var dbOptions = new DataOptions().UseConnection(PostgreSQLTools.GetDataProvider(connectionString: connectionString), connection)"

Thanks in Advance

Kind Regards
Steven

**Comment by MaceWindu** [comment]
I've made some tests and don't see why need converters. It works fine with `UseNodaTime()` only.

Only issue I see is that npgsql inserts zero interval for some values:

```cs
// works fine
NodaTime.Period.FromMinutes(-123)
// inserts zero interval (into nullable field)
NodaTime.Period.FromTicks(-3675048768766)
```

I would say it looks like Npgsql bug. Probalby they don't handle big numbers in intervals correctly. I will made some extra tests and submit issue for Npgsql in that case

**Comment by MaceWindu** [comment]
I've filled issue for Npgsql repo https://github.com/npgsql/npgsql/issues/5867
You could try to apply Normalize() call to your Period values and see if it helps
