### ISSUE TITLE
Fluent API -> Map Enum to String

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#468]
How can I in the Fluent API Map a Enum to a String?

                .Property(e => e.Type).HasDataType(DataType.NVarChar);

does not work, because we cannot read the value back again!

**Comment by jogibear9988** [comment]
i've created a patch so I could use:


          MappingSchema.Default.SetConverter<NumbersType, string>((obj) =>
            {
                return obj.ToString();
            });
            MappingSchema.Default.SetConverter<NumbersType, DataParameter>((obj) =>
            {
                return new DataParameter { Value = obj.ToString() };
            });
            MappingSchema.Default.SetConverter<string, NumbersType>((txt) =>
            {
                return (NumbersType)Enum.Parse(typeof(NumbersType), txt, true);
            });


but a mapping only solution would be better

**Comment by ili** [comment]
@jogibear9988 can you please provide failing test sample?

**Comment by jogibear9988** [comment]
I will do so!

But will it be ok, if I add a default way so we can define Enums should be stored as string?

Because atm (with my change) you have to create a converter for each enum!

**Comment by ili** [comment]
@jogibear9988 as for me it is not a good idea to use strings to store enums. For ex now `int` is used by def, so, if we'll change it, we'll be a breaking change.

Or you do mean you can configure `DefaultEnumConverter`?

**Comment by jogibear9988** [comment]
i will not change the default. i'd like a mapping attribute, to change this for one property.

i only want that i do not have to create the 3 converter callbacks each time.
it was possible in bltoolkit to map to a string, so i think it should also be possible in linq2db

**Comment by ili** [comment]
@jogibear9988 i'v added a possibility to set "underlying" types for enums:
```cs
// for particular enum type
MappingScgema.Default.SetDefaultFromEnumType(typeof(MyEnum), typeof(string));

// for all enum types
MappingScgema.Default.SetDefaultFromEnumType(typeof(Enum), typeof(string));
```

**Comment by jogibear9988** [comment]
perfect!

even if it's a bad idea to map enums to strings, we may have existing databases we can't change

**Comment by xKloc** [comment]
Awesome, this works for char too.

```
public enum Status
{
   Aborted = 'A',
   InProgress = 'P',
   Finished = 'F'
}

MappingSchema.Default.SetDefaultFromEnumType(typeof(Status), typeof(char));
```
