### ISSUE TITLE
RetrieveIdentity returns wrong Identities for BulkCopy

### ISSUE THREAD

**Issue by kucukemre** [linq2db/linq2db#4687]
RetrieveIdentity method doesn't work as expected for bulk operations(BulkCopy).

The returned IDs don't match the IDs in SQL.

### Environment details

`Linq To DB` version: 5.4.1
Database (with version): SQL Server 2022
ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.2.0
Operating system: Windows 11
.NET Version: 8.0

**Comment by kucukemre** [comment]
I am using nopCommerce v4.70.5. The BulkInsertEntitiesAsync method in the BaseDataProvider class is as follows:

`public virtual async Task BulkInsertEntitiesAsync<TEntity>(IEnumerable<TEntity> entities) where TEntity : BaseEntity
{
    using var dataContext = CreateDataConnection(LinqToDbDataProvider);
    await dataContext.BulkCopyAsync(new BulkCopyOptions(), entities.RetrieveIdentity(dataContext));
}`

**Comment by MaceWindu** [comment]
You need to set `KeepIdentity = true` for identity columns if you want to use client-side values

```cs
new BulkCopyOptions() { KeepIdentity =true }
```

**Comment by kucukemre** [comment]
I tried this and it works fine now. Thank you.
