### ISSUE TITLE
Rework -> Remove Static Configuration

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#471]
The Static COnfiguration is not good in multithreaded Scenarios, needs to be reworked

This class should be changed

	public static class Configuration
	{
		public static bool IsStructIsScalarType = true;
		public static bool AvoidSpecificDataProviderAPI;

		public static class Linq
		{
			public static bool PreloadGroups;
			public static bool IgnoreEmptyUpdate;
			public static bool AllowMultipleQuery;
			public static bool GenerateExpressionTest;
		}

		public static class LinqService
		{
			public static bool SerializeAssemblyQualifiedName;
			public static bool ThrowUnresolvedTypeException;
		}
	}

**Comment by jogibear9988** [comment]
Maybe we can add a label: "breaking change"
because it will be one!

**Comment by jogibear9988** [comment]
it's okay, if i now work on this?

**Comment by ili** [comment]
That would be cool! Let's discuss your ideas how should we refactor it

**Comment by jogibear9988** [comment]
i think of a configuration property with a instance of a default class of the dataconnection, but i have to look at the source next week.

**Comment by ili** [comment]
My thoughts:
* `IsStructIsScalarType` - goes to the mapping I think it is better to move it to `MappingSchema`.
* `AvoidSpecificDataProviderAPI` - move to `DataProvider`
* `PreloadGroups` used in `GroupByBuilder`, I suppose it to be query specific, think we should make smth. like extension method `WithPreloadGroups<T>(this IQueryable<T> source)`
* `IgnoreEmptyUpdate` - don't know... may be it should not be configurable at all?
* `AllowMultipleQuery` -> `WithMultipleQuery<T>(this IQueryable<T> source)`
* `GenerateExpressionTest` - don't know... 
* `SerializeAssemblyQualifiedName` - as is?...
* `ThrowUnresolvedTypeException` - as is?...

I'll ask Igor to review this thread...

**Comment by igor-tkachev** [comment]
Let's not remove anything. Let's extend existing configuration to support multithreading.

**Comment by jogibear9988** [comment]
the problem with static configuration is, what if i want to use different settings in some program paet. or a external library uses linq2db with different settings?

**Comment by igor-tkachev** [comment]
I do not see any problems. We can always extend existing configuration. For example, Configuration.IsStructIsScalarType can be extended in the following way:

```c#
class MappingSchema
{
    ...
    private bool? _isStructIsScalarType;
    public bool IsStructIsScalarType
    {
        get { return _isStructIsScalarType ?? Configuration.IsStructIsScalarType; }
        set { _isStructIsScalarType = value; }
    }
    ...
}
```

**Comment by ili** [comment]
@igor-tkachev  what about strategy of moving parameters? Comments suggestions?

**Comment by jogibear9988** [comment]
i've started to work on this, but i'm not sure if i'm on the right path. see commit https://github.com/jogibear9988/linq2db/commit/635fd4e88a18ee9dd5adf1cdf9684520eb6f7864

**Comment by ili** [comment]
@jogibear9988 I'v discussed this with Igor more closely. So to implement it in right way complex refactoring would be needed - now we do not have any good way to store per query parameters for parser. This mechanism would be the part of second version, so let's stop work on it for now. 

The thing i would ask you is to finish the thing i'm failed with - please try to finish #504. All stuff is in the linux brunch i'v fixed some issues (most of them were about paths and so on), but there some other i think it is mostly about environment. As i'm not familiar neither with mono nor with linux for me it is a way of blind (you can see there is a number of stupid commits with trying to change something). For now I'v stopped with and removed travis and appveyor mono builds (all pull requests were supposed not passing, and it is not convenient). The good would be to configure and finish mono on forked repository  and then to make the pull request, it would be great if you can do it!

**Comment by jogibear9988** [comment]
I'll look... but can take a few days... ;-)

**Comment by jogibear9988** [comment]
I also think it's not so critical. Before we should fix the linq errors, I think they are more critical

**Comment by ili** [comment]
Great!

**Comment by jogibear9988** [comment]
Are we planing to remove the static Config in V2?
