### ISSUE TITLE
Work on V2 Branch

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#473]
If I start to work on features (like remove of static settings), should that be done in the V2 Branch igor already started?

I think most of his changes were switching to new c#7 features

**Comment by ili** [comment]
Master I suppose. Igor said that he is going to rewrite expression parsing using c#7 features, so I do not think that it would be quick :)

**Comment by jogibear9988** [comment]
Ok, I also close for now. Maybe I look to merge some of the V2 Branch changes when you think it's ok!

Which VS Version do you have to develop linq2db?

**Comment by jogibear9988** [comment]
@igor-tkachev do you still work on this?
