### ISSUE TITLE
Nuget update? Nuget/Myget Pre-Release Packages?

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#474]
Is it planed to upload a new Nuget Package?
Is it planed to create Pre-release Versions for each commit at Nuget (i prefer this) or Myget?

**Comment by ili** [comment]
@jogibear9988 MyGet is available now, i'v posted feed address on main page... 
But i don't know how to see it through web ui without authorization...

**Comment by ili** [comment]
I'v found how to add MyGet feed to gallery :)
Speaking about new package for NuGet I think we should do it soon.

**Comment by jogibear9988** [comment]
Ok, MyGet feed works. Nuget will be published when we think we're stable. I'll close for now.
