### ISSUE TITLE
Connection Strings are not found any more.

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#480]
I've updated to the Myget package, but now the connectionStrings are not loaded any more!

**Comment by jogibear9988** [comment]
If I add

     <configSections>
         <section name="linq2db" type="LinqToDB.Configuration.LinqToDBSection, linq2db" requirePermission="false" />
      </configSections>
      <linq2db defaultConfiguration="SQLite" />

to app.config it works

But before it did work without!

**Comment by ili** [comment]
May be it is because `DefaultConfiguration` is not set... I'll look this little bit later...

**Comment by jogibear9988** [comment]
data connection 279 is null I think
