### ISSUE TITLE
Linq2DB.InsertWithIdentity with PostgreSQL custom 

### ISSUE THREAD

**Issue by JFGauvin** [linq2db/linq2db#481]
Using PostgreSQL, I have a Sequence that creates unique Ids throughout the whole database. Every table has an "id" field which defaults the next value of this sequence.

```
CREATE SEQUENCE generic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

```
Trying to use Linq2DB's method InsertWithIdentity on a table that uses this sequence I get error: {"42P01: relation "public.ctest_id_seq" does not exist"}. Here is the table definition:

```
CREATE TABLE public.ctest
(
    id bigint NOT NULL DEFAULT nextval('generic_id_seq'::regclass) , 
    name citext,
    CONSTRAINT ctest_pk PRIMARY KEY (id)
)
```
The InsertWithIdentity method works well when using a standard id field, typed Serial or BigSerial, like in the definition below:

```
CREATE TABLE public.btest
(
    id bigserial NOT NULL,
    name citext,
    CONSTRAINT btest_pk PRIMARY KEY (id)
)
```
Is there a way to use the InsertWithIdentity with a Sequence number generator?

**Comment by ili** [comment]
Try `[SequenceName(ProviderName.PostgreSQL, "generic_id_seq")]`

**Comment by JFGauvin** [comment]
Where I should Specify the SequenceName ? Can you provide me more details please ?

My current insert line :
nId = db.InsertWithIdentity<T>(data);

**Comment by ili** [comment]
You should specify it on your model like here https://github.com/linq2db/linq2db/blob/0485a5a44d66557e0bbbe15f98c9846c25ed1ea5/Tests/Model/PostgreSQLSpecific.cs#L11

**Comment by ili** [comment]
Closing an issue, will reopen if problem is not solved
