### ISSUE TITLE
Wrong generation of "select 1 from [table]"

### ISSUE THREAD

**Issue by HemidAbbasov** [linq2db/linq2db#483]
Hi.
I want to get sql like:
`SELECT 1
    FROM [table]`
To do this, I'm writing:
    using ( var db = new TestDB() )
    {
        var q = db.Requests.Select(rs => 1);
        var list = q.ToList();
        Console.WriteLine("-------------");
        Console.WriteLine(db.LastQuery);
        Console.WriteLine("-------------");
        foreach (var l in list)
        {
            Console.WriteLine("Value: {0}", l);
        }
    }

And I'm getting this output:

-------------
SELECT
	*
FROM
	[requests] [t1]

-------------
Value: 1
Value: 1
Value: 1
Value: 1

====================
I don't understand, is it REALY "SELECT *" goes to database? If we look at result list, the answer is "NO".

**Comment by ili** [comment]
I think yes, it is the real query, but, reader mapping expression is generated from your select closure, that's why you are getting constants

**Comment by HemidAbbasov** [comment]
Ok. It is understanding. I try many variants. But what is going on when I write this:
using ( var db = new TestDB() )
            {
                var q = db.Requests
                          .Where(r => r.RequestStatusHistory
                                       .Select(statusHistory => new { statusHistory.Id})
                                       .Any())
                          .Select(r => new {r.Id});
                var list = q.ToList();
                Console.WriteLine("-------------");
                Console.WriteLine(db.LastQuery);
                Console.WriteLine("-------------");
                foreach (var l in list)
                {
                    Console.WriteLine("Value: {0}", l);
                }
            }

The result SQL is:
`SELECT
	[t1].[id]
FROM
	[requests] [t1]
WHERE
	EXISTS(
		SELECT
			*
		FROM
			[request_status_history] [t2]
		WHERE
			[t1].[id] = [t2].[request_id]
	)`

Why "SELECT *"? By logic, there should be "SELECT [t2].[id]". But not =((

**Comment by sdanyliv** [comment]
EXISTS does not need column, it's simple optimization. Query seems correct.

**Comment by HemidAbbasov** [comment]
Hm... Look's like there is no need to write "r => r.RequestStatusHistory.Select(statusHistory => new { statusHistory.Id}).Any()". We can write simple "r => r.RequestStatusHistory.Any()".

Thank everybody.
