### ISSUE TITLE
How express `SELECT1 UNION ALL SELECT 2` sub-query in Linq2Db

### ISSUE THREAD

**Issue by NickAb** [linq2db/linq2db#484]
I have a query which uses `IN` clause:
```cs
var query = dataContext.ExecuteObject<Card>()
                .Where(x => x.Version == workingVersion);
                .Where(x => cities.Contains(x.CityId));
```
which is not very effective, because `cities` collection is quite big (and provided by user request). I would like to replace `IN` clause with `INNER JOIN` like that:
```sql
[x1].CityId IN (1, 2, 3, 4)
```
```sql
INNER JOIN (SELECT 1 AS Id UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) [c] ON [c].Id = [x1].[CityId]
```
How can I express such `SELECT` `UNION` in Linq2Db?

**Comment by ili** [comment]
I'v tested `in` closure with few thousands records with Sql Server, works pretty fine, i don't think that this style union would be better in performance then in, have you tested it?

**Comment by sdanyliv** [comment]
@NickAb, you can create temp table using linq2db, bulk copy data to that table and use inner join. 
It sholuld be more effective.

**Comment by NickAb** [comment]
@ili in our case it saved up to 100 ms. Our actual query takes 275±25 ms to run. Replacing `IN` with `INNER JOIN` reduces time to 180±25 ms.

@sdanyliv thanks, I will try that option.

**Comment by ili** [comment]
@NickAb what about temporary table? is it OK?

**Comment by NickAb** [comment]
@ili, on actual query it turned out to be slower than `IN` clause.
Is there any way to generate `SELECT ... UNION ALL` from collection in Linq query by implementing some attribute from Linq2Db?

**Comment by ili** [comment]
@NickAb as far as i know no...

**Comment by ili** [comment]
may be smth like:
```cs
var t = db.GetTable<TableWithOneRecord>();
IQuerable<TableWithOneRecord> q = null;
foreach(var id in ids)
{
    var tempQ = t.Select(_ =>_.Zero + id); // or may be t.Select(_ => id);
    if (q == null) 
        q = tempQ;
    else
        q = q.Concat(tempQ);
}
```
while `TableWithOneRecord` has only one record with `0` value

**Comment by ili** [comment]
Solution needed, or we can close an issue?
