### ISSUE TITLE
Core: SQLite provider is not type safe

### ISSUE THREAD

**Issue by ili** [linq2db/linq2db#492]
Details:
https://github.com/linq2db/linq2db/commit/24bee23a862c2f23c59aec52e3969be0b70184c1

Todo:
* fix (?)
* write bug report to MS

**Comment by ili** [comment]
It is supposed to be a "feature" https://github.com/aspnet/Microsoft.Data.Sqlite/issues/300

So for full compatibility we'll need to create new provider for `Microsoft.Data.Sqlite`

Not sure, it is really worth...

**Comment by MaceWindu** [comment]
outdated?
