### ISSUE TITLE
Better exception message for missing fields

### ISSUE THREAD

**Issue by pinx** [linq2db/linq2db#497]
I have a subclass of my own class. In the subclass, I have overridden fields, and added annotations for the ones that I want to save in my database.
When I (accidentally) refer to fields without annotations, e.g. in `Inserts`, I get a NullReferenceException in TableBuilder.cs, line 668. The table can not be found for the given expression. Would be nice to show the field name, that is causing the error.
```
public SqlInfo[] ConvertToSql(Expression expression, int level, ConvertFlags flags)
...
case ConvertFlags.Field :
  {
    var table = FindTable(expression, level, true);

    if (table.Field != null) // <-- table is null, because FindTable did not return a result
      return new[]
      {
        new SqlInfo(table.Field.ColumnDescriptor.MemberInfo) { Sql = table.Field }
      };
...
  }
```

**Comment by ili** [comment]
@pinx can you please provide simple sample of query?

**Comment by pinx** [comment]
This is a part from my unit tests:
```
Expression<Func<Schedule.Order>> OrderBuilder = () => new Schedule.Order
{
	Index = 1,
	StorageGroupID = "test2",
	Action = "i",
	// ... and some more fields
};

var id = repo.Orders.InsertWithIdentity(OrderBuilder);

Schedule.Order testOrder = (Schedule.Order)OrderBuilder.Compile().DynamicInvoke();
var orderFromDb = (from o in repo.Orders where o.id == (long)id select o).First();
Assert.AreEqual(testOrder, orderFromDb);
```
Not sure if this is the best way. Still getting used to the syntax.

**Comment by ili** [comment]
And this query fails because of `FindTable` returns `null`?

**Comment by pinx** [comment]
My class Order is a subclass. So I have something like:
```
public class Order : OrderBase
...
[Column]
public int SomeField {get; set;}
```
but my OrderBase could have (without annotation)
```
public int BaseField {get; set;}
```
When I mention the `BaseField` in the Insert statement (my OrderBuilder above), I get no compiler warning, but the linq2db fails.
In general, it would have helped me if I had gotten a more descriptive exception. Now I had to clone your repo, compile it in debug mode, add it as a reference to my own project, start the debugger, and inspect the variables in the *linq2db* code. Not a very good user experience.
