### ISSUE TITLE
Дублирования inner join с Association для GroupBy

### ISSUE THREAD

**Issue by AK107** [linq2db/linq2db#498]
Проблема серьезная, т.к. даже при среднем количестве строк в дочерней таблице кладет на лопатки БД.

Дано:
> create table t_first
(
	first_id	integer primary key
);
create table t_second
(
	second_id	integer primary key,
	first_id 	integer not null references t_first
);

    [Table(Name = "t_first")]
    class First
    {
        [PrimaryKey]
        [NotNull, Column("first_id")]
        public int Id { get; set; }

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Second.FirstId), CanBeNull = false)]
        public IEnumerable<Second> Seconds { get; }
    }
    [Table(Name = "t_second")]
    class Second
    {
        [PrimaryKey]
        [NotNull, Column("second_id")]
        public int Id { get; set; }

        [NotNull, Column("first_id")]
        public int FirstId { get; set; }
    }

заполнять таблицы не нужно

>            var context = new DataContext();

            var query = from x in context.GetTable<First>()
                        from y in x.Seconds
                        select x.Id;

            query.ToArray(); 

            var query1 = from x in query
                         group x by x into g
                         select g;

            query1.ToArray(); 

первый запрос отрабатывает как нужно:
> SELECT
        t2.first_id
FROM
        t_first t2
                INNER JOIN t_second t1 ON t2.first_id = t1.first_id

а вот со вторым, где выполняется группировка первого - проблемы - двойной inner join с дочерней таблицей:
>SELECT
        t3.first_id
FROM
        t_first t3
                INNER JOIN t_second t1 ON t3.first_id = t1.first_id
                **INNER JOIN t_second t2 ON t3.first_id = t2.first_id**
GROUP BY
        t3.first_id

**Comment by sdanyliv** [comment]
Why group x by x? Maybe you have to concretize your grouping keys? 
I have no computer to check this right now.

**Comment by AK107** [comment]
Я просто до предела упростил запрос, там может быть абсолютно любое поле, например, некое value из t_first:

>>create table t_first
(
	first_id	integer primary key,
	**value	integer not null**
);

>var query = from x in context.GetTable<First>()
                        from y in x.Seconds
                        select x;
            var query1 = from x in query
                         group x by **x.value** into g
                         select g;

получаем
> SELECT
        t3."value" as value1
FROM
        t_first t3
                INNER JOIN t_second t1 ON t3.first_id = t1.first_id
                **INNER JOIN t_second t2 ON t3.first_id = t2.first_id**
GROUP BY
        t3."value"

ошибка из явного задвоения inner join с parent таблицей.

**Comment by sdanyliv** [comment]
I've got it. As workaround try to replace your first query with
```cs
var query = from x in context.GetTable<First>()
  join y in context.GetTable<Second>() on x.Id equals y.Id
  select new {x, y}
```
It will be more closer to real SQL.

**Comment by AK107** [comment]
Да, я так и делаю :)

**Comment by ili** [comment]
We do have #485 I think it should solve the problem. But to merge it I need little more time, now i'm going to publish release and then will back to it
