### ISSUE TITLE
ODBC

### ISSUE THREAD

**Issue by qelewere** [linq2db/linq2db#499]
I have a ODBC/DSN entry to an ancient Sybase database file. The ODBC connection is working fine, I can run queries against the database using SQLRUN.

What I'd like to do is to use LINQ2DB with this DB through ODBC. (

Is this doable? If yes, how?

**Comment by ili** [comment]
@qelewere in general supporting new database with new connection type is complex task, but Sybase is supported with `Sybase.AdoNet45.AseClient.dll` you can get it from [nuget](https://www.nuget.org/packages/linq2db.Sybase/)

**Comment by ili** [comment]
Can close?
