### ISSUE TITLE
Is any way to use Glimpse debug?

### ISSUE THREAD

**Issue by ckhker** [linq2db/linq2db#500]
Is any way to use Glimpse debug?

**Comment by ili** [comment]
Are there a way to use it with ADO .Net?

**Comment by ili** [comment]
Quick looking [here](http://getglimpse.com/Docs/Manual-ADO-Integration) it looks like it is the same as with [MiniProfiler](https://github.com/linq2db/linq2db#miniprofiler)

**Comment by ckhker** [comment]
thx a lot
