### ISSUE TITLE
Nuget Package Version wrong

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#501]
Nuget has 1.7.5 the Docs talk about 1.0.7.5

**Comment by ili** [comment]
Yes... that was a mistake in appveyor config, pointed too late, so decided to leave for nuget this version mnemonic...

**Comment by jogibear9988** [comment]
I think, then we should change the whole linq2db Version.

Maybe after we reworked the static config, we switch to 2.0.0.0

**Comment by ili** [comment]
I think it would not be enough for v 2

**Comment by jogibear9988** [comment]
and what do we do now about wrong version?

We should change everything to 1.7? because now a switch back to 1.0.7 (or next 1.0.8), will not show that a newer package is there...

**Comment by ili** [comment]
I think we can leave it as is for now. Nuget packages are just have separate version...

**Comment by jogibear9988** [comment]
can you create a new nuget? 1.8? with the new fixes?

**Comment by ili** [comment]
All successful builds (excluding pr) are published to [MyGet](https://www.myget.org/gallery/linq2db) :)

**Comment by jogibear9988** [comment]
yes, but old versions are deleted. (at least last time you deleted it). and so our build was broken!

**Comment by ili** [comment]
Hm... Don't remember why, but I had some reason... Now I'm not going to delete them anymore... May be some optimization needed, may be to publish only night builds, not every
