### ISSUE TITLE
namespace miss

### ISSUE THREAD

**Issue by yumingchao** [linq2db/linq2db#505]
hello everybody,
we want to used linq2db.postgres, but get some error below when run t4 template(CopyMe.PostgreSQL.tt)
![image](https://cloud.githubusercontent.com/assets/24603028/21256133/77db8e58-c3ab-11e6-85bb-0e4062341a44.png)
try .net 3.5/4.5/4.6 in vs2015/vs2013 both failed.
change PC get error again.
project info:
webapplication .net 4.5
vs 2015 update 3, C#
windows 2012 server r2 x64
linq2db version:
![image](https://cloud.githubusercontent.com/assets/24603028/21255920/eb9f01be-c3a9-11e6-812b-8b25c0821d36.png)
npgsql version:
![image](https://cloud.githubusercontent.com/assets/24603028/21255924/f9049b84-c3a9-11e6-9159-687046b67ad1.png)

Thanks

**Comment by ili** [comment]
This morning i'v done a test for  `linq2db.Access` and faced with strange thing - nuget installed old dependent packages. Check this please, if yes - update packages and try again

**Comment by yumingchao** [comment]
thank you very much

**Comment by ili** [comment]
Helped? Can close?

**Comment by yumingchao** [comment]
hi
still fail
1, new webappcation
2, get library from nuget
![image](https://cloud.githubusercontent.com/assets/24603028/21262400/1db820b4-c3cc-11e6-8b06-e9ef3bf2cc63.png)
3, build error
![image](https://cloud.githubusercontent.com/assets/24603028/21262407/27f2eb68-c3cc-11e6-8609-64d9f51e5a29.png)

**Comment by ili** [comment]
I see, it looks like we should update nugets... 
To fix now:
* install linq2db.xxx (as you already done)
* Update packages:
  * linq2db 1.7.5
  * linq2db.t4models 1.0.7.5 
* Add this line on the top of `CopyMe.xxx.tt`:
```
<#@ assembly name="$(SolutionDir)\packages\linq2db.1.7.5\lib\net45\linq2db.dll"        #>
<#@ assembly name="$(SolutionDir)\packages\Npgsql.3.1.9\lib\net45\npgsql.dll"          #>

```

I have no PostgeSql on hand to test, but it helps with Sql Server

**Comment by yumingchao** [comment]
thankyou sir, 
namespace issue has gone.
but other fail opend:   it look like Npgsql error, 
![image](https://cloud.githubusercontent.com/assets/24603028/21263568/898ddae4-c3d2-11e6-8119-16d402bc06c9.png)
my project screenshot
![image](https://cloud.githubusercontent.com/assets/24603028/21263601/bd40a93e-c3d2-11e6-8370-62e200bce21a.png)
web.config 
<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.5"/>
    <httpRuntime targetFramework="4.5"/>
  </system.web>
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701"/>
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
        warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+"/>
    </compilers>
  </system.codedom>
  <connectionStrings>
    <add name="MyDatabase" connectionString="Server=127.0.0.1;Port=54321;Database=nbclic;User Id=postgres;Password=postgres;" providerName="PostgreSQL" />
  </connectionStrings>
</configuration>

**Comment by yumingchao** [comment]
Npgsql version may be too high, right?

**Comment by ili** [comment]
looks like connection stting combilen from parameters is wrong.
try to specify connection string directly using `LoadPostgreSqlMetadata` with one parameter, and comment one with many

**Comment by ili** [comment]
Speaking about `npgsql` version, yes, it can mean if some connection string parameters were deprecated.
[Here](https://github.com/linq2db/t4models/blob/master/Tests/LinqToDB/PostgreSQL.tt) we'v tested with 2.2.6

I'll check it later on weekend

**Comment by yumingchao** [comment]
thank you,sir
i will test it with one parameter later

**Comment by yumingchao** [comment]
have a nice day

**Comment by yumingchao** [comment]
hello
test "LoadPostgreSQLMetadata(string connectionString)", get error below:
![image](https://cloud.githubusercontent.com/assets/24603028/21299884/b2c32e50-c5da-11e6-934f-ee5c3f062f2d.png)
project web.config:
![image](https://cloud.githubusercontent.com/assets/24603028/21299892/be1d56b8-c5da-11e6-8dd8-fa9789f0765a.png)

i wiil test npgsql 2.2.6

**Comment by yumingchao** [comment]
test npgsql 2.2.6, same error info
my postgres version: 8.4
i guess this is linq2db.provider initialzation bug.  
do you think?

**Comment by yumingchao** [comment]
good new!
it can generate Linq Code,
thankyou very much.

**Comment by ili** [comment]
That's great, what was the problem? 
Using direct connection string helped?

**Comment by yumingchao** [comment]
using direct connection can work,
screenshot:
![image](https://cloud.githubusercontent.com/assets/24603028/21334877/80bd0eba-c695-11e6-9e63-904be9527f7f.png)
![image](https://cloud.githubusercontent.com/assets/24603028/21334881/8dd8e6f0-c695-11e6-8b22-6238659968d3.png)

**Comment by yumingchao** [comment]
but not generate postgres function code
![image](https://cloud.githubusercontent.com/assets/24603028/21334945/0e16c878-c696-11e6-9658-49740add55cf.png)

**Comment by yumingchao** [comment]
i will test performance of the linq2db.postgres,
Send a report to you later.

**Comment by ili** [comment]
Good, thanks :)

**Comment by yumingchao** [comment]
we test table.count() method by soap api,
code like this:
public int TestLinq()
{
     using (var db = new LinqDB())
     {
         return db.tablex.Count();
     }
}
Test result:
runtime : 16h
test count :  3044050 , multi thread invoke(10 thread)
Ten minutes before, memory from 60mb to 220mb, then no increase.
handle count: 1000 - 2500, then no increase.
cpu using 0% ~ 2%

**Comment by yumingchao** [comment]
send insert/modify/delete report to you later.
