### ISSUE TITLE
Mapping of dynamic columns

### ISSUE THREAD

**Issue by Sp1rit** [linq2db/linq2db#507]
Hi,

I need to map dynamic columns, that can be added by users at runtime (and start with a prefix), to a collection like a dictionary while selecting the data.

Is there any way to realize something like that in linq2db? Any extension points or built in functionality for that?

For Example:
````
class User {
    int Id;
    string Name;
    Dictionary<string, object> AdditionalFields;
}

**Comment by ili** [comment]
You can emit new type with needed columns

**Comment by ili** [comment]
Another way is to store `Dictionary<string, object> AdditionalFields` like serialized object using 
```cs 

MappingSchema.Default.SetConverter<Dictionary<string, object>, string>(...);
MappingSchema.Default.SetConverter<string, Dictionary<string, object>>(...);
MappingSchema.Default.SetConverter<Dictionary<string, object>, DataParameter>(...);
MappingSchema.Default.SetConverter<DataParameter, Dictionary<string, object>>(...);

```

like [here](https://github.com/linq2db/linq2db/blob/4369a08839b835cf92fe933af63590962ab80bab/Tests/Linq/UserTests/ConverterInsertTests.cs#L55)

**Comment by ili** [comment]
Closing issue
