### ISSUE TITLE
F# option types and treating null as None

### ISSUE THREAD

**Issue by jjj-herobase** [linq2db/linq2db#510]
Hi

First of all, Thanks to everyone who've made and contributed to this awesome project. It is [insert superlative more praising than awesome here]!!

To business:

I've been looking into how to add support for F# option types. I started by looking at PR #194, but it seems outdated and wrongish. 
I eventually found out that simply adding the desired option types as scalar types makes everything work (almost), and an appropriate converter.
Currently I do this:
```
db.MappingSchema.AddScalarType(typeof<string option>,          None, false, LinqToDB.DataType.NVarChar)
db.MappingSchema.AddScalarType(typeof<decimal option>,         Option.None, false, LinqToDB.DataType.Decimal)
db.MappingSchema.AddScalarType(typeof<DateTime option>,        None, false, LinqToDB.DataType.DateTime2)

db.MappingSchema.SetConvertExpression<Option<_>,_>( fun x -> if x.IsSome then x.Value else None );

```

I haven't tested with more complex types, but since this is mainly an alternative to using null in F#, and since databases generally don't support complex types, I don't think it's going to be an issue.

The only remaining problem is that, this check:
```
// Add check null expression.
//
if (dataContext.IsDBNullAllowed(dataReader, idx) ?? true)
{
	ex = Condition(
		Call(dataReaderExpr, _isDBNullInfo, Constant(idx)),
		Constant(mappingSchema.GetDefaultValue(type), type),
		ex);
}
```
In ConvertFromDataReaderExpression.cs:GetColumnReader: (line 111 in my version). 
Checks that the actual db field is nullable and sets the result as null if true. That happens even though I've marked my scalar types as not nullable and even though I've added NotNull attribute to my property.

Is there are way to force the converter to run, or at least use the default value if the scalar type is not nullable? So that I could get a proper none instead of null.

This is not a major thing since F# happily pattern matches null as None.

The mapped type
```
type [<Table(Name = "billing_group_call_type_parameter", IsColumnAttributeRequired = false)>] BillingGroupEndpointTypeParameter = {
    id: int
    agent_line_multiplier: Nullable<decimal>
    [<NotNull>]
    price_per_connect: decimal<euro> option
    [<Column(Name = "call_type_id")>] 
    EndpointType: EndpointType 
}
```

**Comment by ili** [comment]
Hello.

I think we can do something with it :)

**Comment by jjj-herobase** [comment]
I'd be happy to do the work, but I just wanted to check that there isn't already a way to do that I might have missed.

**Comment by ili** [comment]
Can you write pseudo code you are expecting on reading `Option` from `DataReader`? 
for ex
```cs
var value = dataReader.IsNull(0) == null ? Option.None : dataReader.GetValue(0);
```

**Comment by jjj-herobase** [comment]
Well it turns out that linq2db actually works as I had hoped, it's F#'s handling of None that wasn't as expected.
Passing None as the default value for AddScalarType actually ends up passing null instead. It seems that None only really exists at compile-time and so stepping through your code looking at values of option types will lead to confusing results.
I tested this by passing a not-none value to AddScalarType as default value and it worked as expected, correctly replacing null values from the data reader with the default value. In retrospect it seems like an obvious thing to test :)

I'm closing this with the conclusion that adding support for option types is trivially doable without any code changes. Just use AddScalarType.

Thank you for your time.

**Comment by ili** [comment]
It would be great if you can provide some test sample we can include and use as manual :)

**Comment by jjj-herobase** [comment]
As a PR test case or just a snippet written to use Northwind fields? 
I haven't looked at what it would take to run the tests here locally.

**Comment by ili** [comment]
PR would be certainly the best :)

Snippet would be good too :)
