### ISSUE TITLE
Oracle generation uses wrong data type for bool properties

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#511]
I've got an entity that I've mapped up that contains boolean fields. Columns that would normally be represented for the boolean type (bit, int, etc) don't exist in oracle.

I believe oracle generally recommends using char(1) with Y/N. Being that there is no REAL official way to handle this, is there a way to say I'd like to utilize some convention, and schema generation will use something other than 'Bit' (which it uses now) to whatever I specify... and likewise when parsing bools from db, this is the conversion?

Unsure of where to go from here... seems like there is a bug here in that linq2db generates sql with "bit" but not sure of how to fix since there are varying ways people get around it.

**Comment by ronnyek** [comment]
Weird, got latest to attempt a fix, generates a char(1) as expected. I guess this is closable

**Comment by ili** [comment]
Little bit unclear... How had you solved an issue?

**Comment by ronnyek** [comment]
I was running 1.0.73 or something, which after all my testing was trying to create "Bit" field types. I saw where I thought the problem was, and was going to fix it and issue a pull request, but when I got the latest version of the code, it didnt exhibit this behavior. 

In other words, something between 1.0.73 and 1.0.75 fixed the problem =)
