### ISSUE TITLE
Mono.Data.Sqlite

### ISSUE THREAD

**Issue by ili** [linq2db/linq2db#512]
Does anybody have some experience with `Mono.Data.Sqlite`?
I do working now on Travis-Ci linq2db (#504) build and do have a problem with `Mono.Data.Sqlite` on Windows.

When trying to create connection `BadImageFormatException` is raised even for simple console application...

**Comment by jogibear9988** [comment]
we had used mono sqlite in a project (with a arm cpu), but switched now to system.data.sqlite, as we had a bug wich was already solved there, and monos classes seem outdated! but for that you have to compile the native part of the libyourself

**Comment by ili** [comment]
[SQLite.Native](https://www.nuget.org/packages/SQLite.Native/) would not help with binaries?

Can i do smth like:
* reference https://www.nuget.org/packages/System.Data.SQLite.Core/
* reference https://www.nuget.org/packages/SQLite.Native/
* ???
* PROFIT!

**Comment by jogibear9988** [comment]
maybe, but not on our embeded arm system.
