### ISSUE TITLE
Compiling transformation errors

### ISSUE THREAD

**Issue by Kempe** [linq2db/linq2db#514]
Hi! After upgrading to the latest linq2db Version (1.7.5) with (linq2db.t4models and linq2db.PostgreSQ v1.7.5) I'm getting a lot of 'Compiling transformation errors' like shown blelow: 
Compiling transformation: The type or namespace name 'LinqToDB' could not be found (are you missing a using directive or an assembly reference?)
I've also created the simplest possible project, added the nuget packages, copied the CopyMe.PostgresSQL.tt to a separate folder and only changed one line to : 
LoadPostgreSQLMetadata("127.0.01", "5432", "MyDatabase", "sysadmin", "sysadmin");

So I got stuck! What can I do to resolve these errors? 

Thanks in advance.
Cheers

**Comment by ili** [comment]
Please, read #505

**Comment by Kempe** [comment]
Thanks! That solved my problem!!

**Comment by ili** [comment]
Not at all :)
