### ISSUE TITLE
InsertWithIdentity in postgres

### ISSUE THREAD

**Issue by Ravath** [linq2db/linq2db#517]
I am using postgres inheritance, and redefine the serial primary key 'id' each time.
But when using InsertWithIdentity, I have
  "the relation 'Schema.Table_id_seq' doesn't exist"
I believe it should be able to find 'Schema.ParentTable_id_seq' instead?

**Comment by ili** [comment]
You can try to specify sequence name for your POCO like [here](https://github.com/linq2db/linq2db/blob/master/Tests/Model/PostgreSQLSpecific.cs)

**Comment by Ravath** [comment]
It works fine, thx.

**Comment by ili** [comment]
You are welcome :) tell your friends about linq2db :):):)

**Comment by lobster2012-user** [comment]
#1576
