### ISSUE TITLE
How to select columns to load using LoadWith?

### ISSUE THREAD

**Issue by 3f6b7** [linq2db/linq2db#527]
```
class Person
{
	public int Id { get; set; }
	public string Name { get; set; }
	public IEnumerable<Thing> Things { get; set; }
}

class Thing
{
	public int Id { get; set; }
	public int PersonId { get; set; }
	public Person Person { get; set; }
}
```

E.g can I omit Person.Name when using `db.Things.LoadWith(p => p.Person)`?

**Comment by ronnyek** [comment]
From documentation, tests, etc you'd use Association attribute like so 
```
class Person
{
	public int Id { get; set; }
	public string Name { get; set; }
        
        [Association(ThisKey="Id", OtherKey="PersonId"]
	public IEnumerable<Thing> Things { get; set; }
}

class Thing
{
	public int Id { get; set; }
	public int PersonId { get; set; }
	public Person Person { get; set; }
}

then
db.People.LoadWith(x=>x.Things).<some filtering here>
```

You can do 1:1 1:* and *:1, or at least the attribute seems to account for those scenarios, but I'd keep an eye on what you are seeing query wise. I started tinkering with this today and its basically doing a query an individual query for each relation...

10 users, for each of the 10 users go and fetch things for each...

**Comment by ronnyek** [comment]
I'm gonna correct myself, I just looked into this, you'd get one query for top level items one one for the children (total)

**Comment by ili** [comment]
@3f6b7 no there is no such function.

linq2db designed not to do hidden actions or actions you may not expect in some context. 

For ex. when a do select all persons i'm not always want and need to select their things too. EF deals with it using `Lazy Load` but linq2db does not use this pattern.

In general linq2db is type-safe SQL, in SQL you do select only data you specified to select :)

**Comment by sdanyliv** [comment]
Last sentence needs to be duplicated in Readme.md on top of the introduction ;)

Good LoadWith is most requested feature from people who saw EF. It is doable, but needs big effort. 
I think we have to create issue with proposed features and prioritize them, maybe some kind of voting. I have about 5 or mored ideas that may improve linq2db usage and popularity.

**Comment by ili** [comment]
@sdanyliv I'll update readme :)

About heavy weight features such as Lazy Load, Identity tracking,  and so on, i think that it would be better to make separate project, implementing this features with using linq2db as `type-safe SQL` :) 

Only one question, who would do it? :(

But yes, i think you should create such issue where we can discuss it

**Comment by sdanyliv** [comment]
I'm not about Lazy loading and such crappy things of heavy ORMs.
Fore example: window functions support, fluent batch script creation, query rewriting...

**Comment by ili** [comment]
@sdanyliv good :)

Lets move this suggestions to an another issue :)
