### ISSUE TITLE
Changing the concrete type of an association

### ISSUE THREAD

**Issue by maul-esel** [linq2db/linq2db#529]
There should be a way to specify the concrete type for an association when the class uses an interface:

```csharp
[Table("test")]
class MyTable {
  [Column, NotNull]
  public int AssocId { get; set; }

  [Association(ThisKey = nameof(AssocId), OtherKey = nameof(IOtherTable.Id), ConcreteType = typeof(OtherTableImpl))]
  public List<IOtherTable> Others { get; set; }
}
```

I'd be willing to try and take a crack at it if you could point me to where this would need to be implemented.

**Comment by CoskunSunali** [comment]
Is there a way to achieve this out of the box already?

**Comment by MaceWindu** [comment]
Duplicate of #230
