### ISSUE TITLE
Problem with Converter (worked in BlToolkit)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#531]
In Linq2Db, it's not possible to specify a converter for only one column, you only can define a global one, wich then is used everytime you hav that type.

Now we have the following Problem:

We've a converter with converts a List<string> into xml in the Database and back to a List when reading. This works fine. But now we have also another Part in the Code, wich looks if a String Column is in a List of strings. 

        public static string[] GetAllRolesForGroupList(List<string> activeDirectoryGroups)
        {
            using (var s = CommonDL.CreateSession(sessionName: "SecurityDL:GetAllRolesForGroupList"))
            {
                var roles = from r in s.Query<RoleDTO>()
                    join gr in s.Query<GroupToRoleDTO>() on r.Id equals gr.RoleID
                    join g in s.Query<GroupDTO>() on gr.GroupID   equals g.Id
                    where activeDirectoryGroups.Contains(g.Name)
                    select r.Name;

                return roles.Distinct().ToArray(); 
            }
        }

This then generates the following Code:

    SELECT DISTINCT
        t[t1].[Name]
        FROM
        [Common_Security_Groups] [t1]
         WHERE\r\n\t[t1].[Name] IN (N'<ArrayOfString>\r\n  <string>G2</string>\r\n <string>G3</string>\r\n</ArrayOfString>')
 
In this part, the converter should not be used. Can we fix that?

**Comment by jogibear9988** [comment]
That means if we have a List<T> and use for example "Contains", the converter should not be used

**Comment by jogibear9988** [comment]
I've created a Test for the issue: https://github.com/linq2db/linq2db/pull/532

But I'm not sure how we could solve? How do we know when the converter should be used? (and when shouldn't we use it)

**Comment by jogibear9988** [comment]
Is there a way that we can detect in ExpressionBuild.SqlBuilder, BuildParameter() - how we should setup the Parameter when we call CreateParameterAccessor?

**Comment by ili** [comment]
Closed due to #532 merge
