### ISSUE TITLE
One more bug with Custom Converters and DataParameter

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#533]
If I have the followig Code:
```cs
			MappingSchema.Default.SetConverter<List<string>, string>((obj) =>
			{
				if (obj == null)
					return null;
				return string.Join(";", obj);
			});
			MappingSchema.Default.SetConverter<List<string>, DataParameter>((obj) =>
			{
				if (obj == null)
					return new DataParameter() { DataType = DataType.NVarChar };
				return new DataParameter { Value = string.Join(";", obj), DataType = DataType.NVarChar };
			});
			MappingSchema.Default.SetConverter<string, List<string>>((txt) =>
			{
				if (string.IsNullOrEmpty(txt))
					return null;
				return txt.Split(';').ToList();
			});
```
a insert does not work on SqlServer (when the Lists are null), because the  DataType.NVarChar is not used!

I got the following error: Die implizite Konvertierung vom sql_variant-Datentyp in nvarchar ist nicht zulässig. Verwenden Sie die CONVERT-Funktion, um diese Abfrage auszuführen.

Means it can not convert from sql_variant to nvarchar implizitly.

**Comment by jogibear9988** [comment]
It does work if I return string.empty instead of null, but should that be the solution?

**Comment by jogibear9988** [comment]
Also DBNull.Value works also.

**Comment by jogibear9988** [comment]
@ili is this a bug? or it's needed to return dbnull? problem is, DataType of DataParameter is not used!

**Comment by ili** [comment]
@jogibear9988  it is not clear if it is a bug or feature :)

As always some test to reproduce needed... 
May be there is some check that convert expression is not used for `null` values?

**Comment by jogibear9988** [comment]
but i think we should use the type of data parameter

**Comment by ili** [comment]
Yes, i think, but for me use case is not clear :(((

Test please...

**Comment by ili** [comment]
@jogibear9988 what about test reproducing the issue? :)
