### ISSUE TITLE
Generation of IN() statement

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#536]
Is there anyway to generate a IN() statement? Eg, I fetch a list of ID's and then I want to select from another table 
```
where(x=>SelectedIds.Contains(x.id))
```

Orr should this work?

For me LoadWith still executes sub query for a relation n times, which seems avoidable. I could do it with an in statement

**Comment by sdanyliv** [comment]
For performance purposes you have to forget about LoadWith
Contains should work, but if there too many records - it is performance gap

You can work with temp tables in linq2db. It means selecting IDs into temp table an then reuse them in detail SQL. Then you have to assign details to master records by himself. Pity but it's not so obvious how to create best solution for detail records.

There is another approach used by EF7:
It creates SQL for master records. Then creates SQL for details with additional join to master SQL.
SQL server returns 2 recordsets, that merged on client side.

You can mimique this approach in linq2db
```cs
var qm = from m in master
  where m.Date > DateTime.Now
  select s;

var qd = from d in detail
  join m in qm.Select(q => q.JoinKey).Distinct() on d.JoinKey equals m.JoinKey
  select new Detail
  {
     d.JoinKey, // it is needed later for assigning to master records
     // ... other fields
  }

var masterRecords = (from m in qm
  select new 
  { 
     m.JoinKey,
     // ... other fields
     Details = new List<Detail>()
  }).ToList();

var detailRecords = qd.ToList();

var joined = from m in masterRecords
  join d in detailRecords on m.JoinKey equals d.JoinKey
  select new
  {
     Master = m,
     Detail = d
  };

foreach (var j in joined)
{
  j.Master.Details.Add(j.Detail);
}
```

**Comment by ili** [comment]
@ronnyek  `Contains` is supported and converted to `IN(...)` [some references](https://github.com/linq2db/linq2db/search?utf8=%E2%9C%93&q=Contains&type=Code)

Also this should work
```cs
db.Childs.Where(c => db.Parents.Select(p => p.Id).Contains(c.ParentId))
```

`LoadWith` generates multiple queries for statements like:

```cs
public class Parent
{ 
    public IEnumerable<Child> Childs;
}

db.Parent.LoadWith(_ => _.Childs);
```

And if you do really need load several parent entities with their child entities I would suggest you to make two queries.

**Comment by sdanyliv** [comment]
Oops, it's not good idea to write comments from iPad :)
Sure you have to rewrite last join to group by
