### ISSUE TITLE
Agnostic parameter re-write for execute and query

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#537]
I have a few places where I calculate some stats and currently return them in many groups, but not to be mapped to an entity.

Currently I do something like .Query<long>(sql, parameters).

Oracle and probably many of the other database vendors have their own notation for the parameter format. My question is whether or not it makes sense to say across the board @param gets rewritten to :param or whatever sort of transform is required via the data provider.

Also, I noticed that it seems to want to setup the parameter like so:
```
DECLARE @param Type
SET @param = some value
<sql...> where name = @param
```
I'm guessing this is erroneous since this doesnt even come close to working in oracle.

**Comment by ili** [comment]
`SqlBuilder` has `Convert` method to deal with different notations.

I think you should not worry about it, and need only to specify parameter name without any notation. 

To make it clear please provide detailed minimum sample :)

**Comment by ronnyek** [comment]
First of all, let me say I'm sure this isn't the primary target of linq2db (handling manual query and unmapped entities)
lets say I have a table of users and I just want to return a list of username strings where first_name = specified name (we'd also have to make the assumption I don't have user mapped. This isn't real world, users would be some result of a complex query)

so my sql might be:
`SELECT USERNAME FROM USERS WHERE FIRST_NAME=<first name parameter>`

so I build a query by defining sql as the examples recommend
```
var sql = "SELECT USERNAME FROM USERS WHERE FIRST_NAME=@firstName"
.Query<string>(sql, new {firstName="bob"});
```

This query fails against oracle because of how the query is being built as I specified above... its defining local variable and trying to use them in the query (but using improper syntax). More so, even if it was just rendering the sql as SELECT USERNAME FROM USERS WHERE FIRST_NAME=@firstName, and feeding in @firstName parameter, oracle syntax for parameters is like  :userName.

If there is a totally diff, easier way to achieve this, I'm all about that... I just didnt find much in the way of helpers for manual queries for un-mapped objects. (just the usual suspects with Execute, ExecuteProcedure, ExecuteScalar)

As for making a simple test case, I would just add a test for it and send a pull request, except that I worry linq2db wasn't SUPPOSED to work this way.

**Comment by sdanyliv** [comment]
@ronnyek, try to use the following syntax.
```cs
var res = db.Query<Employee>("select * from [dbo].[Employees] where FirstName = @firstName",
  new DataParameter {Name = "@firstName", Value = "Nancy"});
```

**Comment by ronnyek** [comment]
oh man, I wasn't aware I could do that with data parameters, if that works, that's awesome.

**Comment by ili** [comment]
@ronnyek oh now i see... 

linq2db would not make any changes with your raw SQL statement... so @sdanyliv's approach would work only if database supports this syntax, so if Oracle does not support `@parameters` it would fail any way... :(

**Comment by sdanyliv** [comment]
@ili, we can rewrite query in the following way. I have no oracle database, but i think it sholud work.
```cs
var res = db.Query<Employee>("select * from [dbo].[Employees] where FirstName = :firstName",
  new DataParameter {Name = ":firstName", Value = "Nancy"});
```
Maybe without colon in DataParameter name

**Comment by ili** [comment]
@sdanyliv certainly this should work :)

My idea was: if you are targeting few databases raw SQL statements should be managed manually.

**Comment by ili** [comment]
@ronnyek can we close issue?

**Comment by ili** [comment]
Closing for now, will reopen if needed

**Comment by ronnyek** [comment]
you know, I bypassed this by using just straight iqueryable, but ended up running across this again. For whatever reason running as oracle generates this: (According to query tracing) 
this is passing in DataParameter(":id",1379397)

```
DECLARE @:id Int64
SET     @:id = 1379397

select distinct parent_id,
                        (select nuser as Priority from ud_data where ud_cols_id = 292 and parent_id = ud.parent_id) as Priority,
                        (select nuser as Priority from ud_data where ud_cols_id = 293 and parent_id = ud.parent_id) as CalcPriority 
                        from ud_data ud
                        where parent_id= :id;
```

I'm not even sure int64 is a valid oracle type. exception blows up with invalid character.

**Comment by ronnyek** [comment]
The weird thing here is that it appears as if other queries that presumably succeed are tracing out as if it were using a int64 data type as well.

**Comment by ronnyek** [comment]
Ends up it didnt like a semi colon in there... which is fair... is it possible traacing isnt spitting out the same query that its actually executing?
