### ISSUE TITLE
New package?

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#540]
Hi

You pulled in the changes for #509 .  Can you let me know a rough idea of when the next release version will be cut and published on NuGet?

Thanks for the great work.

Roy

**Comment by jogibear9988** [comment]
would be nice if you could look at #532 . maybe we can get it into next release

**Comment by ili** [comment]
@RoyC-Retail-Assist it is available as prerelease on MyGet.
I do plan some more changes for release, but too less time =((

@jogibear9988 i'll try to introduce all open PR in next release... and will try to do it in couple of weeks...
