### ISSUE TITLE
[Feature Idea] Window functions support

### ISSUE THREAD

**Issue by sdanyliv** [linq2db/linq2db#542]
Hi everyone,

Occasionally someone ask how to use window (analytic) functions in linq2db ...
So i propose to look at this issue more closer.
There is list of databases that supports these functions:

Database | Documentation
---------- | -------------------
_General_ | https://en.wikipedia.org/wiki/Select_(SQL)#Window_function
SQLite | http://www.sqlite.org/lang_select.html
SQL Server  | https://msdn.microsoft.com/en-us/library/ms189461.aspx
PostgreSQL | https://www.postgresql.org/docs/9.1/static/tutorial-window.html
Oracle | http://docs.oracle.com/cloud/latest/db112/SQLRF/functions004.htm#SQLRF06174
MariaDB | https://mariadb.com/kb/en/mariadb/window-functions/

**Please vote if you interested in.**

**Comment by sdanyliv** [comment]
Proposed syntax. Already prototyped interfaces that handles type-safety for this solution
```cs
void Test(IQueryable<Entity> selectQuery)
{
  var q = from e in selectQuery
    select new
    {
      e.IntField,
      e.StringField,
      c0 = Sql.Over(e).Rank(),
      c1 = Sql.Over(e).Aggregate(ee => ee.Max(v => v.IntField)),
      v1 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).ThenByDesc(v => v.IntField).Rank(),
      v2 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).RowNumber(),
      v3 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).NTile(4),
      v4 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).Range.UnboundedPreceding.Rank(),
      v5 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).Range.Between.UnboundedPreceding.And.UnboundedFollowing.Rank(),
      v6 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).Range.Between.Value(v=> v.StringField).And.UnboundedFollowing.Rank(),
      v7 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).Range.Between.Value(v=> v.StringField).And.UnboundedFollowing.DenseRank(),
      v8 = Sql.Over(e).PartitionBy(v => v.IntField).OrderBy(v => v.StringField).Range.Between.Value(v=> v.StringField).And.UnboundedFollowing.Aggregate(ee => ee.Sum(v => v.IntField)),
    };

}

```

**Comment by sdanyliv** [comment]
It's no longer feature. I have created pull request #613 and you can try it.
Any comments are appreciated.

**Comment by MaceWindu** [comment]
shipped with https://github.com/linq2db/linq2db/releases/tag/Release.1.8.0
