### ISSUE TITLE
Multiples children on selector

### ISSUE THREAD

**Issue by gapin** [linq2db/linq2db#546]
Hi,
Is it possible to use LoadWith for an entity and select multiple fields on selector in order to automatically load the children's entities?

How can I do this?

**Comment by sdanyliv** [comment]
Please take a look at unit tets. But notice it is not so reach as in EF.
https://github.com/linq2db/linq2db/blob/9e13b8a067d50cbbbf157ec03d72f6c28a46e428/Tests/Linq/Linq/LoadWithTests.cs

**Comment by gapin** [comment]
Thanks sdanyliv,
I have already seen it. But, what I need... is to eager load multiples chidren.

i.e.
Student.Father
Student.Mother

In a single LoadWith operation through the right selector.
Do you know if is it possible?

**Comment by sdanyliv** [comment]
Can you write simple linq expression, that you want to use. I will explain you if it is possible for now.
LoadWith is very limited and can expand to multiply queries to each master record.

**Comment by gapin** [comment]
Suposse something like this (using last sample):
var student = db.GetTable<Student>().LoadWith(x => x.Father && x.Mother).FirstOrDefault();

**Comment by sdanyliv** [comment]
Try to revrite this in the following way.
var student = db.GetTable().LoadWith(x => x.Father).LoadWith(x => x.Mother).FirstOrDefault();

**Comment by ili** [comment]
@gapin sdanyliv is absolutely right. I'v added the test, demonstrating this case.

**Comment by gapin** [comment]
Thanks! 👍
