### ISSUE TITLE
TypeLoadException when querying tables with foreign keys in Postgres

### ISSUE THREAD

**Issue by Kempe** [linq2db/linq2db#551]
I get an exception 'TypeLoadException' in linq2db.dll (Could not load type 'LinqToDB.Mapping.Relationship' from assembly 'linq2db, Version 1.0.7.5, Culture=neutral, PublicKeyTooken=f19f8aed7feff67e'). 
I'm using the latest linq2db from Nuget (v1.7.5).  

Also I'm a little confused about the versioning. Nuget says that the latest linq2db version is v1.7.5 while the linq2db.dll says v1.0.7.5. Is this correct? Can anyone help me?

Perhaps it has something to do with the latest changes here : 'Thread Safety in Mapping #548' ?

Thanks in advance, kind regards!

**Comment by ili** [comment]
Not clear about the exception, can you give full text with stack trace?

About versions, yes we do have this little difference, don't worry )

**Comment by Kempe** [comment]
The exception was gone, after using and referencing a local build of the latest linq2db sources. I can't reproduce the error right now because of further progress. Sorry for trouble....
