### ISSUE TITLE
Concurrency checking

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#553]
I'm looking to write some optimistic concurrency functionality similar to Entity Framework or NHibernate but I need something that I can hook into whenever an Update or Delete is to take place that I can then choose to cancel the update if desired.  Alternatively a method to add in row version columns to the where clause and a check that rows have been modified.

Is there anything currently available in the source code that could be used ( I cannot see anything obvious)?

If not I'd be interested in discussing how this could be added preferably as some extensibility points that could be used to supply providers for alternative strategies.

**Comment by sdanyliv** [comment]
Check my answer here https://github.com/linq2db/linq2db/issues/331#issuecomment-277987587

**Comment by RoyC-Retail-Assist** [comment]
Looks promising.

**Comment by RoyC-Retail-Assist** [comment]
I've had a look at this and, whilst I can add the extra condition I cannot see how to get the original value to compare it with as the row being updated doesn't seem to be available in the ProcessQuery method.

**Comment by ili** [comment]
Yes, on this point you'll receive only SQL AST that would be translated to SQL. So only constants as values would be available, but not parameters. 

Let's discuss how are you seeing such changes.

**Comment by ili** [comment]
For ex my sample of optimistic concurrency:

```cs
public class Entity
{
    public int Id;
    public int Version;
    public string SomeValue;
}

public void Update(IDataContext db, Entity obj)
{
    var r = db.GetTable<Entity>()
        .Where(_ => _.Id == obj.Id && _.Version == obj.Version)
        .Set(_ => _.Version,  _ => _.Version + 1)
        .Set(_ => _.SomeValue, obj.SomeValue)
        .Update();

    if (r == 0) throw new ConcurrencyException(obj);
}
```

To implement that I can modify SQL AST adding `&& _.Version == obj.Version` and `.Set(_ => _.Version,  _ => _.Version + 1)`

So i do not need to know particular values...

P.S. not sure that we can now add new parameter to `SelectQuery` but why not... also point is how to throw exception...

**Comment by RoyC-Retail-Assist** [comment]
I'm trying to avoid the developer having to code the concurrency check if at all possible and I also want to cater for a Version variable that uses the DB specific RowVersion.

Something like (using SQLite for testing):

```

		[Table("TestTable")]
		public class TestTable
		{
			[Column(Name = "ID", IsPrimaryKey = true, IsIdentity = true)]
			public int ID { get; set; }

			[Column(Name = "Description")]
			public string Description { get; set; }

			private DateTime _rowVer;

			[Column(Name = "RowVer", Storage = "_rowVer", SkipOnInsert = true, SkipOnUpdate = true)]
                        [RowVersion]
			public DateTime RowVer { get { return _rowVer; } }
		}

		[TestInitialize]
		public override void TestInitialize()
		{
			var sql = "CREATE TABLE TestTable(";
			sql += "ID INTEGER PRIMARY KEY,";
			sql += "Description NVARCHAR(50),";
			sql += "RowVer DATETIME DEFAULT CURRENT_TIMESTAMP)";

			Connection.Execute(sql);

			Connection.Insert(new TestTable { ID = 1, Description = "Row 1" });
			Connection.Insert(new TestTable { ID = 2, Description = "Row 2" });
		}
		[TestMethod]
		public void CheckUpdateOK()
		{
			var table = Connection.GetTable<TestTable>();

			var row = table.First(t => t.ID == 1);
			row.Description = "Changed desc";
			
			var result = Connection.Update(row);

			Assert.AreEqual(1, result);
		}

		[TestMethod]
		public void CheckUpdateFail()
		{
			var table = Connection.GetTable<TestTable>();

			var row = table.First(t => t.ID == 1);
			var row2 = table.First(t => t.ID == 1);

                        // 1st change of the record will modify the rowver to the current timestamp
			row.Description = "Changed desc";

			var result = Connection.Update(row);

			Assert.AreEqual(1, result);

                       // 2nd change will fail as the database timestamp is different to the one sent with the update
			row2.Description = "Another change";

			result = Connection.Update(row);

			Assert.AreEqual(0, result);
		}


```
Maybe having overrides to allow the incrementing integer field if desired.  The benefit (to me at least) of the DB managed row version column is that other updates done at a DB level will also update the RowVer column. 

Although I am programing for a DB first model I'd also like suitable methods on the CreateTable to be able to handle the "DATETIME DEFAULT CURRENT_TIMESTAMP" but maybe there is something that you can point me to already.

**Comment by sdanyliv** [comment]
I'll try to prepare sample how to handle such situations automatically. Maybe tomorrow. From my point it's doable.

**Comment by RoyC-Retail-Assist** [comment]
Thanks

Roy Chase | Senior Analyst Developer
Retail Assist Ltd | 1-2 Premier Court | Boarden Close | Northampton | NN3 6LF
Tel: +44 (0)1604 224120
Email: Roy.Chase@retail-assist.co.uk<mailto:Roy.Chase@retail-assist.co.uk> | Web: www.retail-assist.co.uk<http://www.retail-assist.co.uk>

**Comment by sdanyliv** [comment]
I have created sample in #557, but changed versioning to integer. DateTime is not so good for concurrency.

**Comment by RoyC-Retail-Assist** [comment]
The sample is great thank you.  

I'd like to be able to intercept the results before they are passed back to the caller so that I can intercept them and raise an exception if the update was not successful.  I'm struggling to find an appropriate point to intercept this.  Any suggestions?

**Comment by ili** [comment]
I'v done some update in @sdanyliv's sample (adding insert and delete test).

One point @sdanyliv is really right about `DateTime` because you can have problems with accuracy in milliseconds.

Also from my side this approach is not the best one. I think it is better to make smth. like EF `DataContext` where can be done Identity Tracking and Concurrency Checking and linq2db would be used as SQL.

**Comment by RoyC-Retail-Assist** [comment]
I understand your comments about using DateTime.  SQLite is particularly poor as DateTime is in whole seconds however I'm particularly interested in using the Timestamp type on DB2 iSeries that has a resolution of microseconds or ROWVERSION on SQL server as these are specifically designed for row versioning at the DB level.  It then means that the versioning is done on the DB regardless of how the row is changed (without adding triggers).

I've also looked at handling the InsertOrUpdate method but hit an issue with :

`var dic = pairs.ToDictionary(p => p.New, p => p.Old);`

It's trying to insert a duplicate key into the dictionary for some reason.

```
 [Test]
 public void CheckInsertOrUpdate()
 {
 	var result = Connection.InsertOrReplace(new TestTable { ID = 3, Description = "Row 3" });
 
 	Assert.AreEqual(1, result);
 	Assert.AreEqual(3, testTable.Count());
 
 	var newval = testTable.Where(t => t.ID == 3).First();
 
 	newval.Description = "Row 3 New description";
 	
 	result = Connection.InsertOrReplace(newval);
 	Assert.AreEqual(1, result);
 	Assert.AreEqual(3, testTable.Count());
 }
```      
The DataContext idea is what I am looking ot provide for my application so needed the relevant hooks into Linq2DB to be able to intercept the query processing both before submission to the DB and after submission.  Whilst this approach will work for adding the required slection criteria I would still need some way of checking that the update failed to raise the necessary exception.

**Comment by ili** [comment]
I'v added `InsertOrReplace` sample & fix for issue with dictionary.
**NB!** query it would be different for MS Sql, because SQLite do not support it in one query and two queries are executed

**Comment by ili** [comment]
In general, if you would need some changes in lib. I think we can discuss them and implement )

**Comment by RoyC-Retail-Assist** [comment]
Great.  I'll work up some ideas in the next day or so.

**Comment by RoyC-Retail-Assist** [comment]
I've create PR #566 with some changes that would allow the concurrency checks and overriding them.  I'm not necessarily expecting it to be pulled :o)

1. Not using PrimaryKey for RowVer.  
	a. Could result in multiple records with same ID field but different RowVer value 
	b. May impact performance of foreign keys if DB isn't smart enough to use the index without specifying the RowVer column.
	c. Doesn't allow the overriding of the concurrency check.  Would mean a call to the DB to get the current value then modifying.

I've coded as per the original suggestion and it working for update and insert but not delete ate the moment (need to be able to pass through the existing RowVer value some how)

2. Added DBManaged parameter to the RowVer attribute to allow the Row Version to be managed by the database (e.g. by a trigger or a specific datatype) or by Linq2DB.  Needs tests writing to prove the DB managed option.

3. Added optional parameter to the UpdateMethods to allow the developer to determine that the "User wins".  See CheckUpdateFailWithOverride test.

4. Added QueryExecuted method to IDataContext to be a central place to check the results. Need checks added that the table being updated has a RowVer column.  

I've concentrated on getting the process working rather than specific implementation as I think it would be good to pull the touch points out into a single interface with a "null" implementation so that plugins could be easily developed for specific uses cases.

This "solution" doesn't cater for the Where().Set().Update() pattern (although it does update the RowVer correctly).  I'm not sure that it could do completely as the Select could result in multiple rows to be updated and I'm struggling to come up with a use case that this would be a problem.

**Comment by MaceWindu** [comment]
Guys, what I want to see here is a proposal for desired API. What functionality and behavior should it provide. Like:
- how it enabled
- behavior on lock failure
- how to implement different lock schemas

By last one I can provide several examples:
- row version field, modified "manually" (e.g. some counter)
- row version field, modified automatically by db (e.g. column of rowversion type in sql server)
- record lock using row version field + lock timeout field to ignore lock if timeout expired

**Comment by MaceWindu** [comment]
E.g. I use rowversion with lock timeout in my project, but it is implemented as 

1. interface for entity with lock support
```cs
public interface ITimeoutOfflineLockObject
    {
        DateTimeOffset? LockTime { get; set; }

        byte[] Version { get; }
    }
```
2. set of extension methods to add/remove/prolong lock, check that lock is still valid, etc.

**Comment by AndrePScope** [comment]
Hi guys

I recently started to use Linq2Db in a new project and also ran into an issue with the implementation of the optimistic lock.

I want to share information about how I solved it. It seems to me, it was quite elegant than presented here.
I have to say overriding the DataConnection methods (ProcessQuery, ExecuteNonQuery, ExecuteScalar) is quite complicated and confusing. 
I would like to propose another solution.

Some inputs ...

1. First of all, I want to note that db.GetTable <Entity> () method ... is not for optimistic locking. When we talk about an optimistic lock, this implies blocking only one entity, which the user is currently editing.
db.GetTable <Entity> () - This is a multiple change or deletion, there may have different filters and as a result, we don’t know what can be deleted/changed and we can’t know the previous version value of those records.
So, we must use the db.Update (obj) / db.Delete (obj) methods

2. I use the Datetime field and I don’t think this using is bad for an optimistic lock. There are no problems with milliseconds. As I already said above - an optimistic lock is about editing one entity and most often by the end-user (not a service or program). So, the user must read the data, open the form, change the data and save.
If he did this everything within one millisecond (or another minimum time value), then there will be a problem. Otherwise, there will be no problem.

Now about the solution itself.
It seems to me, the most elegant solution here is to use "virtual PK" that consists of version field also with ID.
I mean not real PK in the DB, but just with implementation in the code.
This needs because Linq2Db generates correct filtering by PK for the db.Update (obj) / db.Delete (obj) methods.
In fact, this is exactly what you just need !!!
The name of Datatime version field in my project is "**Accessed**"
It remains just to add another one same filed "**LastAccessed**" and mark it as PK.


How does it look in the code?
The Standard generated class (please, pay attention only to **Id**, **Accessed** and **LastAccessed** ):
```c#
	[Table("submission_files")]
	public partial class SubmissionFile : BaseConcurrencyEntity, IAuditEntity
	{
		[Column("id"),                            PrimaryKey,  Identity] public long      Id        { get; set; } // bigint
		[Column("status"),                        NotNull              ] public string    Status    { get; set; } // character varying(20)
		[Column("file_path"),                     NotNull              ] public string    FilePath  { get; set; } // character varying(1000)
		[Column("filename"),                         Nullable          ] public string    Filename  { get; set; } // character varying(500)
		[Column("created",    SkipOnUpdate=true), NotNull              ] public DateTime  Created   { get; set; } // timestamp (6) without time zone
		[Column("created_by", SkipOnUpdate=true), NotNull              ] public string    CreatedBy { get; set; } // character varying(100)
		[Column("updated",    SkipOnInsert=true),    Nullable          ] public DateTime? Updated   { get; set; } // timestamp (6) without time zone
		[Column("updated_by", SkipOnInsert=true),    Nullable          ] public string    UpdatedBy { get; set; } // character varying(100)
		[Column("accessed"),                      NotNull              ] public DateTime  Accessed  { get; set; } // timestamp (6) without time zone
	}
```

Base class:
```
	public class BaseConcurrencyEntity
	{
		[Column("accessed", SkipOnInsert = true), PrimaryKey(100), NotNull] public DateTime LastAccessed { get; set; } // timestamp (6) without time zone
	}
```

As a result, when reading an entity, both **Accessed** and **LastAccessed** fields reads from the database:
```sql
SELECT
	t1.accessed,
	t1.accessed,
	t1.updated_by,
	t1.updated,
	t1.created_by,
	t1.created,
	t1.filename,
	t1.file_path,
	t1.status,
	t1.id
FROM
	submission_files t1
WHERE
    ....
```

Before saving, the value of the Accessed field changes to a new one, LastAccessed remains old, and Linq2Db generates such queries for db.Update (obj) / db.Delete (obj):
```sql
UPDATE
	submission_files
SET
	accessed = :Accessed,
	updated_by = :UpdatedBy,
	updated = :Updated,
	filename = :Filename,
	file_path = :FilePath,
	status = :Status
WHERE
	submission_files.id = :Id AND submission_files.accessed = :LastAccessed
```

```sql
DELETE FROM
	submission_files t1
WHERE
	t1.id = :Id AND t1.accessed = :LastAccessed
```

As a result, if such deleting or updating returned 0 rows - this is the place where an optimistic lock can be caught (in fact, it still needs to additionally check if the entire record has been really deleted).

The wish to authors of Linq2Db, if I wrong somewhere, please correct me.

I will be glad if it comment will help somebody. :)
