### ISSUE TITLE
Oracle: QueryProc<T> совсем не работает

### ISSUE THREAD

**Issue by AK107** [linq2db/linq2db#555]
Не работает в Оракуле сабж. Да собственно никогда в linq2db не работал. Или я ошибаюсь и не умею его готовить? А в BLT работал :)

Я тут создал обсуждение http://rsdn.org/forum/prj.rfd/6690741.1
В последнем ответе изложили свои мысли по поводу сабжа.

Если ошибаюсь и у вас все ок, то прошу ткнуть носом и удалить issue.

Скопипастю и сюда.

Собственно, а как? 

Даже в в unit-тестах linq2db оно для оракула не выполняется, хотя сама хранимка в скриптах имеется.

> linq2db\Tests\Linq\Data\ProcedureTests.cs

        public static IEnumerable<Person> PersonSelectByKey(DataConnection dataConnection, int? @id)
        {
            return dataConnection.QueryProc<Person>("[TestData]..[Person_SelectByKey]",
                new DataParameter("@id", @id));
        }

        [Test, IncludeDataContextSource(ProviderName.SqlServer2008)]
        public void Test(string context)
        {
            using (var db = new DataConnection(context))
            {
                var p1 = PersonSelectByKey(db, 1).First();
                var p2 = db.Query<Person>("SELECT * FROM Person WHERE PersonID = @id", new { id = 1 }).First();

                Assert.AreEqual(p1, p2);
            }
        }

> linq2db\Data\Create Scripts\Oracle.sql

        CREATE OR REPLACE 
        FUNCTION Person_SelectByKey(pID IN NUMBER)
        RETURN SYS_REFCURSOR IS
            retCursor SYS_REFCURSOR;
        BEGIN
        OPEN retCursor FOR
            SELECT
                PersonID, Firstname, Lastname, Middlename, Gender     
            FROM
                Person
            WHERE
                PersonID = pID;
        RETURN
            retCursor;
        END;

Ну вот в таком виде никак не работает. Ругается, что процедура не найдена. Я помню когда-то давно, когда linq2db только начинался, поднимал эту тему, но автор забил...

OracleException ORA-06550: Строка 1, столбец 7:
PLS-00221: 'Person_SelectByKey' не является процедурой или не определена
ORA-06550: Строка 1, столбец 7:
PL/SQL: Statement ignored Int32 VerifyExecution(OracleInternal.ServiceObjects.OracleConnectionImpl, Int32 ByRef, Boolean, Oracle.ManagedDataAccess.Client.OracleException ByRef, Boolean ByRef, Boolean)

Или тест у вас работает для Oracle и все норм, а это я туплю? 

з.ы. просто в BLT оно работало искаропки и работало хорошо и вызывалось элементарно:
> [SprocName("contract.get_contract_balance"), DiscoverParameters]        
public abstract List<Entities.AccountBalance> GetBalance(long contractNo);

в linq2db же вызовы хранимок — это "ад и израиль": возьми и опиши каждый параметр, включая обязательное имя... а оно еще и не работает с курсором 

Я догадываюсь в чем проблема: необходимо явно объявлять параметр-курсор для result set'а. Если это функция, то это будет ParameterDirection.ReturnValue, если это процедура с output параметром, то соответственно ParameterDirection.Output:
> // create parameter object for the cursor
  OracleParameter p_refcursor = new OracleParameter();
  // this is vital to set when using ref cursors
  p_refcursor.OracleDbType = OracleDbType.RefCursor;
  // this is a function return value so we must indicate that fact
  p_refcursor.Direction = ParameterDirection.ReturnValue;

Скорее всего в BLT эту задачу решал DiscoverParametersAttribute.

----------------------------------------------------------------

Возможное решение:

Считаю самым простым решением добавление DataType.Cursor (+ маппинг типа на оракловый OracleDbType.RefCursor), чтобы можно было просто добавлять соответствующий параметр:

> connection.QueryProc<Entity>("MyCursorFunc", new DataParameter("cursor", DataType.Cursor, ParameterDirection.ReturnValue),..);

**Comment by sdanyliv** [comment]
Может поможешь и сделаешь пул рквест?

**Comment by AK107** [comment]
Да я не против хоть что-нибудь сделать с этим, но что вы скажете на это :

> сходу:
правильно ли, что именно для оракула нужно руками будет определять такой курсорный (Output/ReturnValue) параметр каждый раз при вызове хранимки? а может он должен автоматом определяться для любого result set (QueryProc<T>) в самом провайдере конкретно для оракла прозрачно для пользователя? если автоматом, то с каким Direction — это может быть процедура с Output параметром (с такими часто сталкиваюсь)? а если процедура с Output-параметром, то тут уже важен порядок в списке параметров. есть вариант если пользователь руками не задал такой параметр по дефолту добавлять первым как ReturnValue (считаем, что это функция)...

по какому пути пойдем?

**Comment by sdanyliv** [comment]
Смотри, я бы начал с того, что посмотрел бы почему в BLT работает. Как он это разруливает.

**Comment by sdanyliv** [comment]
Попробуй пару увариантов, самый элегантный выиграет. Нам точно также придется все это пробовать.

**Comment by AK107** [comment]
Ну суть там (в BLT) такова, что есть возможность с помощью атрибута DiscoverParameters указать на необходимость выводить параметры, что реализуется, конкретно в оракуле, с помощью OracleCommandBuilder.DeriveParameters. Ну т.е. это запрос к провайдеру вернуть набор параметров и их типов используемых в вызове хранимки. Именно потому оно в BLT и работает,а не потому, что кто-то умный там заюзал хитрую логику и маппинг OracleDbType.RefCursor.

Это все замечательно, но никак не ложится на тот подход, что используется в linq2db.

**Comment by AK107** [comment]
Ну в общем я сделал по-простому: новый тип DataType.Cursor и его маппинг для оракула на OracleDbType.RefCursor.

Соответственно для вызове QueryProc<T> в клиентском коде, для функции нужно добавлять параметр-курсор так:
> new DataParameter { DataType = DataType.Cursor, Direction = ParameterDirection.ReturnValue }

или для процедуры с output параметром-курсором:
> new DataParameter { DataType = DataType.Cursor, Direction = ParameterDirection.Output }


Такое нам подходит?

Прикладываю микро-патч на два файла.

[OracleQueryFix.patch.txt](https://github.com/linq2db/linq2db/files/780437/OracleQueryFix.patch.txt)

**Comment by sdanyliv** [comment]
@ili, такое походит? Нету Oracle для теста и понимания что там происходит. Также надо править T4.

**Comment by ili** [comment]
Да подходит наверное, я ещё не смотрел пристально.

**Comment by sdanyliv** [comment]
@ili, should we change T4 templates according to this issue?

**Comment by ili** [comment]
SchemaProvider should be changed. I'v started this, but have some troubles with getting schema for returned cursor - don't know how to get it :(
