### ISSUE TITLE
SELECT TOP(1) WITH TIES *

### ISSUE THREAD

**Issue by 10der** [linq2db/linq2db#560]
Hi!

Is any chance implement WITH TIES hint for TOP in MS SQL provider?

PS: Hey, Igor. why are all Sql*Builder classes internal?
simple trying to override (for example)
`
protected override string FirstFormat { get { return "TOP {0}"; } }
`
make this job so tough!

PSS: please do not suggest me sort of 
`
SELECT *
FROM
	(
		SELECT
			x,
			(
				SELECT
					Max([x)
				FROM
					(
						SELECT TOP (1)
							x
						FROM
							[dbo].[MyTable] [t1]
 [...]
`

thank you!

**Comment by ili** [comment]
why not? :)

i think yes, we can do it

**Comment by sdanyliv** [comment]
I think it's should be more elegant than just open internal classes.

**Comment by ili** [comment]
Certainly!
We can do smth. like 
```cs
[Flags]
public enum TopHints
{
     Perfcent = 1,
     WithTies = 2
}

public static IQuerable<T> Take(IQuerable<T> source, int rows, TopHints hints)
{
//...
}
```

or some extensible thing like [TableExpression](https://github.com/linq2db/linq2db/blob/master/Tests/Model/ParentChild.cs#L541)

**Comment by sdanyliv** [comment]
Closed?

**Comment by ili** [comment]
wrong button =(((

**Comment by sdanyliv** [comment]
I'l take a look at this issue. Several days for implementation and testing.

**Comment by ili** [comment]
It is not a hard thing to implement if DB supports this hints, but what if not?

**Comment by sdanyliv** [comment]
WITH TILES, also supporteb by Oracle and maybe other databases.
Also i is used in OFFSET clause. Proposed syntax:
Table.Skip(1).Take(2).LimitBy(Percent | Tiles)

**Comment by sdanyliv** [comment]
For sure we can implement mimique of this functionality. But not now, just throw Not Supported exception.

**Comment by sdanyliv** [comment]
In general it is not so hard to implement, but there are SQL optimizations and we have to respect this hint when optimizing queries.

**Comment by ili** [comment]
OK, let's do it :)

**Comment by sdanyliv** [comment]
@ili, please ensure that hint is not "optmized" by subquery optmizator.

**Comment by ili** [comment]
@sdanyliv how can i do it?

**Comment by sdanyliv** [comment]
@ili, subqueries may moved to top query. Just write test with simple subquery THAT has WITH TIES hint.
