### ISSUE TITLE
Nested Properties

### ISSUE THREAD

**Issue by igkutikov** [linq2db/linq2db#565]
having some trouble with nested properties
(no navigation properties and no association)
simply a complex model which does not align 1:1 with the table's columns

having the following model

``` 
    public class Address
    {
        public string City { get; set; }
        public string Street { get; set; }
    }
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Address Address { get; set; }
    }
```

while the db table is as follows:

![image](https://cloud.githubusercontent.com/assets/5197595/23197594/0ab43772-f8ca-11e6-9231-dac35e4fefd1.png)

and following data connection

```
    public class UsersConnection : LinqToDB.Data.DataConnection
    {
        public UsersConnection() 
            : base(new SqlServerDataProvider("UsersConnection", SqlServerVersion.v2012), new SqlConnection(ConfigurationManager.ConnectionStrings["UsersConnection"].ConnectionString))
        {
            EntityMappingBuilder<User> builder = MappingSchema.GetFluentMappingBuilder().Entity<User>().HasTableName("UserTable");
            builder.Property(x => x.Id).HasColumnName("Id");
            builder.Property(x => x.Name).HasColumnName("Name");
            builder.Property(x => x.Address.City).HasColumnName("City");
            builder.Property(x => x.Address.Street).HasColumnName("Street");
        }

        public ITable<User> Users { get { return GetTable<User>(); } }

    }
```

the following query 

```
    using (UsersConnection connection = new UsersConnection())
    {
        IEnumerable<User> resulr = (from p in connection.Users select p).ToArray();
    }
```

returns zero results, and no exception is throw,
if to change the fluent mapping to:

```
EntityMappingBuilder<User> builder = MappingSchema.GetFluentMappingBuilder().Entity<User>().HasTableName("UserTable");
builder.Property(x => x.Id).HasColumnName("Id");
builder.Property(x => x.Name).HasColumnName("Name");
//builder.Property(x => x.Address.City).HasColumnName("City");
//builder.Property(x => x.Address.Street).HasColumnName("Street");
builder.Ignore(x => x.Address.City).Ignore(x => x.Address.Street);
```

(notice the commented mapping), all the expected results received (without these properties off course)

now i tried to initialize that object in the constructor like this:

```
public class User
{
    public User()
    {
         Address = new Address();
    }
    public int Id { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }
}
```
 but no help, meaning no results and no exception.

my guess is that Linq2Db simply does not know how to traverse expressions which have multiple nested 'MemberExpression'

of course i thought about making  some converter or other utilities Linq2Db offers but non of them is actually designed for (could not think of a way how to abuse these utilities in non straightforward way either)

is it possible to add a support for ComplexEntity mappings mechanism?
or any other solution for such scenario?
I must say that dynamic mapping (fluent mapping) is quite a key feature for me, although i noticed there is an open issue that it does not make any influence after it was already done for the first time because of some internal caches

**Comment by jogibear9988** [comment]
I've asked this moths ago, and got the following as answer: https://github.com/linq2db/linq2db/blob/master/Tests/Model/ComplexPerson.cs

But I don't like the extra Properties in this example. I think we should support a scenario like yours, maybe we already do...

**Comment by igkutikov** [comment]
yes surely the extra properties are a solution,
in my real life scenario, the model is provided by the client's API interfaces library, and for extra properties to work i'll need to make lots of wrappers to accomplish it using such method
and that is exactly what I'm trying not to get into to begin with :)

I don't see any other way for now except making a bit of hacking of the mechanism, but still reverse engineering the code
trying to figure out how all this mapping works (only yesterday tried to use this library for the first time)

any ideas?

**Comment by ili** [comment]
In general you do not need extra properties, please see i'v added test for `ComplexPerson1`  above.

The issue for now - Fluent Mapping is not supported for this cases =(

**Comment by jogibear9988** [comment]
but your test with fluent does  not fail

**Comment by ili** [comment]
Yes, without fluent everything works (insert & update tests added)

**Comment by jogibear9988** [comment]
I'll look to fix it

**Comment by jogibear9988** [comment]
It already works if you do the mapping like this:

.Entity<ComplexPerson3>()        .HasTableName ("Person")
				.HasAttribute(new ColumnAttribute("FirstName", "Name.FirstName"))
				.HasAttribute(new ColumnAttribute("MiddleName", "Name.MiddleName"))
				.HasAttribute(new ColumnAttribute("LastName", "Name.LastName"))
				.Property(_ => _.ID)             .HasColumnName("PersonID");

**Comment by jogibear9988** [comment]
I've created a fix, so also mapping in the other way works: https://github.com/linq2db/linq2db/pull/570

**Comment by jogibear9988** [comment]
@ili what do you think about my fix?

**Comment by ili** [comment]
@jogibear9988 please look comments in pull request it should be little bit rewritten

**Comment by jogibear9988** [comment]
close?
