### ISSUE TITLE
Does LINQ2DB support stored procedures?

### ISSUE THREAD

**Issue by pebezo** [linq2db/linq2db#57]
I need to call a MySQL stored procedure. Can I do that with LINQ2DB or do I need to use BLToolkit for this? Any examples on how to do this? Thanks.

**Comment by emmanuelpereira** [comment]
BTW, if you guys need, I made a extension to write this with "less code"

`using System.Collections.Generic;

namespace LinqToDB.Data
{
    static class DataConnectionExtension
    {
        public static IEnumerable<T> QueryProc<T>(this DataConnection db, string proc, object values)
        {
            List<DataParameter> parameters = new List<DataParameter>();
            foreach (var prop in values.GetType().GetProperties())
            {
                var name = prop.Name;
                var value = prop.GetValue(values);
                parameters.Add(new DataParameter(name, value));
            }
            return db.QueryProc<T>(proc, parameters.ToArray());
        }
    }
}
`

So you can call this way:

`            var query = db.QueryProc<YoourReturn>("yout_proc_name", new
            {
                my1StParameterName = "my value 1",
                otherNameYouWant = 123123
            });`

**Comment by jogibear9988** [comment]
i think maybe we should generate a expression tree and compile it for each anonymous type and cache it in a dictionary, so reflection is only needed once. Or maybe we create a second function "queryprocwithcache"
