### ISSUE TITLE
10 Not working Tests from ORM Battle

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#573]
Orm Battle has 16 failing Tests with current Linq2DB (tested against Northwind Sqlite)

Not working Tests:

- AnyParameterizedTest 
- ComplexGroupingTest 
- ~~ComplexTakeSkipTest~~ 
- ComplexTest2 
- ComplexTest4 
- ComplexTest6 
- **~~ConcatTest~~** 
- **~~EntitySetCountTest~~** 
- GroupJoinTest 
- LeftJoinTest
- OrderByDistinctTest 
- **~~OrderByPredicateTest~~** 
- OrderBySelectManyTest 
- ~~SumTest~~
- **TypeCastIsChildConditionalTest**
- **~~WhereNullableParameterTest~~** (is fixed in pull req #574)

The bold Tests work in bltoolkit!

I've removed the source code links, cause i've added the tests to linq2db in #574

**Comment by jogibear9988** [comment]
TypeCastAsTest, TypeCastIsChildTest and TypeCastOfTypeTest do not work, because Inheritance Mapping is Configured with true/false. In Sqlite true is stored as '1' but that seems not to work in inheritance mapping! If I change to use '1' it works. I think we should fix this.

**Comment by jogibear9988** [comment]
@ili should I create extra issues for each bug?

**Comment by ili** [comment]
It would better to create pull requests with fixies :):):)
I don't think new issues are needed

**Comment by jogibear9988** [comment]
I think, I should be able to fix the inheritance issues in sqlite... for the rest... I'm not sure if I'm able to solve...

**Comment by jogibear9988** [comment]
Can I add the tests from ormbattle to linq2db?

**Comment by ili** [comment]
Yes

**Comment by jogibear9988** [comment]
I've added a fix for WhereNullableParameterTest  to my Pull Req.

The rest, I could not fix....

**Comment by jogibear9988** [comment]
sdanyliv: have you any idea about the non working tests? maybe you could help, seems like you now linq2db sql generation very well

**Comment by jogibear9988** [comment]
what I don't understand is why sum test is not workin.

**Comment by jogibear9988** [comment]
I've noe included the tests (all) into Linq2DB. (result: https://ci.appveyor.com/project/igor-tkachev/linq2db-8c54d/build/1.7.7.377/tests) 

Should i now disable the not working ones? I don't think, I'm able to fix them atm.

I'll look that the tests will run against all Database providers, when I've time. Atm, they only use Sqlite

**Comment by jogibear9988** [comment]
At appveyor, we have 24 tests wich are not working! Seems like we are using another (or old) Version of sqlite!

I get the errors: 
    no such function: LeftStr'.
or 
     'no such function: Cos'.

**Comment by jogibear9988** [comment]
The Tests "ConcatTest","EntitySetCountTest","OrderByPredicateTest","TypeCastIsChildConditionalTest" & "WhereNullableParameterTest" work in bltoolkit but not in Linq2DB!

**Comment by jogibear9988** [comment]
"ComplexTakeSkipTest" in Bltoolkit throws following error "Skip for subqueries is not supported by the 'SQLite' provider.". Is it the same problem in linq2db? Then we should throm a similar error!

**Comment by sdanyliv** [comment]
@jogibear9988, will check.

**Comment by jogibear9988** [comment]
I've fixed ConcatTest & EntitySetCountTest by stepping through code...
Maybe @ili or @sdanyliv can check if the fix is ok

**Comment by jogibear9988** [comment]
OrderByPredicateTest seems not to work, cause of Sqlite DateTime changes...

Working Query from bltoolkit:

SELECT
	[o].[OrderID] as [Id]
FROM
	[Orders] [o]
ORDER BY
	CASE
		WHEN [o].[Freight] > 0 AND [o].[ShippedDate] IS NOT NULL
			THEN 1
		WHEN (NOT ([o].[Freight] > 0 AND [o].[ShippedDate] IS NOT NULL))
			THEN 0
		ELSE NULL
	END,
	[o].[OrderID]

not working one from linq2db

SELECT
	[t1].[OrderID]
FROM
	[Orders] [t1]
ORDER BY
	CASE
		WHEN [t1].[Freight] > 0 AND DateTime([t1].[ShippedDate]) <> DateTime(NULL)
			THEN 1
		WHEN (NOT ([t1].[Freight] > 0 AND DateTime(DateTime([t1].[ShippedDate])) <> DateTime(DateTime(NULL))))
			THEN 0
		ELSE NULL
	END,
	[t1].[OrderID]

**Comment by jogibear9988** [comment]
I've fixed the OrderByPredicate Test also, @ili can you check my fix

**Comment by jogibear9988** [comment]
ComplexTakeSkip test is also fixed by this

**Comment by ili** [comment]
I'll take a look today! :)

**Comment by jogibear9988** [comment]
thanks! I've also looked at the other tests, and I think, I'm only able maybe to fix 2 more or so (if I've time!)

**Comment by jogibear9988** [comment]
I've updated my fixes....

**Comment by jogibear9988** [comment]
@sdanyliv have you had a change to look at the not workin tests?

**Comment by sdanyliv** [comment]
@jogibear9988, sorry i'm returning from vacation. I think on monday.

**Comment by jogibear9988** [comment]
@sdanyliv have you've got the chance to look at them?

**Comment by sdanyliv** [comment]
@jogibear9988, doing it right now

**Comment by sdanyliv** [comment]
@jogibear9988, many order by test may fail because data in Northwind.sqlite is corrupted because of wrong encoding. For example Customers.CompanyName - has broken names.

**Comment by sdanyliv** [comment]
Added pull request with comments #603

**Comment by jogibear9988** [comment]
Okay, one less test we need to fix ;-)

**Comment by jogibear9988** [comment]
closeing, as we have the tests in our code, and we will reenable them when they are ficed

**Comment by jogibear9988** [comment]
@sdanyliv should some of the not working tests now be possible in version 3? I'd try to reenable them but had no luck.

**Comment by sdanyliv** [comment]
I don't think that they are needed to be enabled. Strange queries.
