### ISSUE TITLE
(Cannot ?) override column attributes at runtime

### ISSUE THREAD

**Issue by Arithmomaniac** [linq2db/linq2db#580]
If for some reason, you need to change the mapping for a table for one operation only, you can call something like `db.GetTable<ModelBase>().TableName('table1')`. However, there is no obvious way to do something like `db.GetTable<ModelBase>().ColumName(x => x.Id, 'idColumn1')`, let alone override things like `IsPrimaryKey`.

I think an API similar to the one for tables would be nice, but in the meantime, is there any way to do the equivalent now?

**Comment by ili** [comment]
Please look [here](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Mapping/FluentMappingTests.cs)

**Comment by Arithmomaniac** [comment]
Are you suggesting I use `MappingSchema.Default.GetFluentMappingBuilder().Entity<ModelBase>()`? Doesn't that edit the configuration globally? 
Or is there a way to clone and edit `MappingSchema`s, and use them for table creation?

**Comment by ili** [comment]
You are right! And one step before me, i just wanted to say that i would not recommend you to do it.
You can create new mapping schema, and use it for particular data connection (this i would recommend).

Here is the sample:

```cs
var ms = new MappingSchema();
var b   = ms.GetFluentMappingBuilder();
// do some stuff

using(var db = new DataConnection())
{
    db.AddMappingSchema(ms);
    // do some db stuff
}
```

**Comment by Arithmomaniac** [comment]
Will that MappingSchema first scan attributes before applying the changes in the builder?
Can you tell an existing DataContext to use a different schema for a specific query? (e.g. something like `db.WithSchema(ms).GetTable<ModelBase>()`). That would essentially solve my problem.

**Comment by sdanyliv** [comment]
@Arithmomaniac, i don't see any problems here. You can write your own extension method for DataConnection
```cs
public static class DataConnectionExtensions
{
   public static T WithSchema<T>(this T connection, MappingSchema schema)
      where T: DataConnection
   {
       connection.AddMappingSchema(schema);
       return connection;
   }
}

**Comment by ili** [comment]
@Arithmomaniac shortly: yes it would scan other attributes, you can make partial changes.

In general situation is more complex. For building queries and mappers `EntityDesctiptors` are used, `MappingSchema` is responsible for `EntityDescriptor` creation. While creation `EntityDescriptor` different metadata sources are used (fluent is one of them). `EntityDescriptor` is cached per each `MappingScgema` instance. So when we create new mapping schema new descriptors would be created & applied.

About your second question - changing `MappingSchema` per query. No there are no build in API. But it is easy to do - you just need to decorate `DataConnection`.

```cs
public class MappingSchemaDecorator : IDataContext
{
    public MappingSchemaDecorator(IDataContext dc, MappingSchema schema)
    {
         _dc = dc;
         MappingSchema = schema;
    }

    public MappingSchema MappingSchema  { get; private set; }

   public string ContextID => _dc.ContextID;
   
   // other members
}

using (var db = new DataConnection())
{
   var db2 = new MappingSchemaDecorator(db, ms);
   
   db. GetTable<Entity>()...; //query with default MappingSchema
   db2.GetTable<Entity>()...; //query in same connection with another MappingSchema
}

```

**Comment by Arithmomaniac** [comment]
That works. I do think adding `.ColumName(x => x.Id, 'idColumn1')` would be less error-prone, though.
Thanks!

**Comment by ili** [comment]
Not at all :)

**Comment by Arithmomaniac** [comment]
? Why not? It's hard to decorate properly.

**Comment by ili** [comment]
The feature you are talking about is really hard to implement from one side and exotic from another.

From another side making decorator is a 10 minutes job. Please see an [example](https://github.com/linq2db/linq2db/commit/8a9c12370e64ef4a6c361a259cf25865095f4234)

**Comment by Arithmomaniac** [comment]
Thanks!
