### ISSUE TITLE
Only 5 Pages of Bugs left...

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#581]
It's good to see the recent activity on linq2db, I think 2 or 3 month ago, we had 7 pages of bugs. Now we have 5.

;-)  Thanks @igor-tkachev , @ili and @sdanyliv for your great work

**Comment by ili** [comment]
Thank you too! :)

**Comment by sdanyliv** [comment]
Thank you for your help also!

**Comment by jogibear9988** [comment]
6 issues, and we are down to 4 pages of bugs... means that over 50 issues where closed in the last months...
thanks guys...

**Comment by jogibear9988** [comment]
4 pages!!! thank you again!!!

**Comment by ili** [comment]
yap... i just closed old issues... no new features :(

**Comment by sdanyliv** [comment]
Be patient, working hard on it :)

**Comment by ili** [comment]
![omm](http://animalfair.com/wp-content/uploads/2012/04/OMMMM3623735560280_1480720823_33351056_1194226937_n-199x220.jpg)
