### ISSUE TITLE
Use of ReLinq for Expression parsing

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#582]
Why don't we use ReLinq for parsing? It's used by ef and nhibernate.

Is it slower? Or does it not help very much?

https://github.com/re-motion/Relinq

**Comment by sdanyliv** [comment]
Not sure but looks like it forces to use Expression descendant's as AST. It is contradictory for me to concider that is good, but looks like EF code, because of this, is more complicated, especially for creating new Data Providers.

**Comment by ili** [comment]
I don't see any documentation =(

**Comment by jogibear9988** [comment]
Here is a little bit: https://www.re-motion.org/download/re-linq.pdf

**Comment by sdanyliv** [comment]
Looks like Microsoft outsourced creator of this library ;)

**Comment by ili** [comment]
It needs really a lot of time and experiments to say either it is worth to migrate or not.

**Comment by sdanyliv** [comment]
As i said earlier it forces to use Expressions as AST for SQL. In my opinion it's bad idea and may slowdown developmen.

**Comment by jogibear9988** [comment]
then we close, i only wanted to notify, maybe it has ideas we could use

**Comment by sdanyliv** [comment]
Sometimes, when i have time, i'm returning to this libraryi. If i'll find that it will be helpful for our project, we can discuss it againn.

**Comment by sdanyliv** [comment]
It is not relevant for now, but we keep on mind.
