### ISSUE TITLE
Way of handling "computed" properties

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#583]
So I've got places where I calculate fields in sql and want them to be mapped on the way out of the database, but in saving, I dont want to try and insert. Is there a mechanism for a "Computed" column?

**Comment by jack128** [comment]
```
[Column(SkipOnInsert = true, SkipOnUpdate = true)
public int ComputedField { get;set;}
```
?

**Comment by ronnyek** [comment]
OMG if its that easy... so awesome... I'll give that a whirl

**Comment by ronnyek** [comment]
Maybe I'll try and submit a pull request for a rehash on documentation... I feel like linq2db already does a lot, but not so obvious how to do things without digging through unit tests etc.

**Comment by ili** [comment]
Documentation is our pain :(
We should work hard to fill wiki, or may be we should use [readthedocs](https://readthedocs.org/) or something like that... in any way if you can participate in writing documentation it would be super, for ex i'v started [FAQ](https://github.com/linq2db/linq2db/wiki/FAQ) from your question :)

**Comment by ronnyek** [comment]
I'd be more than happy to contribute SOMETHING back =)

**Comment by ronnyek** [comment]
This takes care of columns that actually exist as a part of physical schema... but what about purely computed schema? Should IsColumn=false allow me to map that column (in Execute/Query) should the columns be returned, but not exist as part of the schema?

If I am accessing the data via .GetTable<Type>(), I'd just prefer not to include this column in the list.

**Comment by ili** [comment]
Not sure... just try :)
