### ISSUE TITLE
Symbols Package for Nuget should be created

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#599]
See https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages

**Comment by ili** [comment]
They are https://github.com/linq2db/linq2db/blob/master/NuGet/linq2db.nuspec

**Comment by jogibear9988** [comment]
Should we move the pdb to a symbol package, and remove them from the normal one?

**Comment by jogibear9988** [comment]
Or should I only add a additional symbol package (wich also includes the source?)

**Comment by ili** [comment]
Why don't you like to leave pdb in main package? As for me it is convenient solution. 
I do not see the benefit of symbols package (only package size?)...

**Comment by jogibear9988** [comment]
okay,  but a symbol package including the source, would not be a bad idea, or?

**Comment by ili** [comment]
Oh, i see, sources...
No problem, just do it! :)

**Comment by jogibear9988** [comment]
@ili as for v2.0, if we let create visual studio (or msbuild) create the nuget from the csproj, it will automaticly create 2 packages. one normal, and one with source and pdb for debugging! we then only need to publish both!

**Comment by jogibear9988** [comment]
Could we switch to nuget package creation from csproj, or should I look to generate the source code package manually?

**Comment by MaceWindu** [comment]
Do we still need something like that taking into account that we ship pdb already in our nuget package and starting from next release it will have SourceLink support?
