### ISSUE TITLE
Union and Index was out of range

### ISSUE THREAD

**Issue by Nelo-cool** [linq2db/linq2db#601]
Excuse me, my dear friends.

```cs
var pinnedItems = from news in db.News
                              join page in db.Page on news.Id equals page.Id
                              join url in db.FriendlyUrl on page.Id equals url.PageId
                              join main in db.MainContent on page.Id equals main.Id
                              where url.Type == FriendlyUrlType.General && page.CreationDate <= DateTime.Now
                              select new NewsPageFriendlyUrl()
                              {
                                  News = news,
                                  Page = page,
                                  Url = url,
                              };

var popularItems = from news in db.News
                               join page in db.Page on news.Id equals page.Id
                               join url in db.FriendlyUrl on page.Id equals url.PageId
                               join view in db.View on page.Id equals view.Id
                               where view.Value > db.View.Where(x => x.Value > 5).Average(x => x.Value) &&
                               url.Type == FriendlyUrlType.General && page.CreationDate <= DateTime.Now
                               orderby
                               page.CreationDate.Date descending,
                               view.Value descending
                               select new NewsPageFriendlyUrl()
                               {
                                   News = news,
                                   Page = page,
                                   Url = url,
                               };

return pinnedItems.Union(popularItems);
```
Help me pls:) or show a new way for me.

**Comment by sdanyliv** [comment]
@Nelo-cool, which version of linq2db do you have installed?

**Comment by Nelo-cool** [comment]
Last, from nuget. 1.0.7.6

**Comment by Nelo-cool** [comment]
The first and second queries, by separated, return result.

**Comment by sdanyliv** [comment]
@Nelo-cool, please do the following steps:

```cs
// this turns on generation of unit test for this query
Configuration.Linq.GenerateExpressionTest = true;
...
// previous two queries
...
pinnedItems.Union(popularItems).ToString();
Configuration.Linq.GenerateExpressionTest = false;
```
As result one or several test files should be generated
`C:\Users\[username]\AppData\Local\Temp\linq2db\ExpressionTest.0.cs`
Then attach them to the issue

**Comment by Nelo-cool** [comment]
One second, pls:)

**Comment by Nelo-cool** [comment]
Attached!

[ExpressionTest.0.zip](https://github.com/linq2db/linq2db/files/855290/ExpressionTest.0.zip)

**Comment by Nelo-cool** [comment]
Without nested query ( view.Value > db.View.Where(x => x.Value > 5).Average(x => x.Value)) nothing changes, the same exception.

**Comment by Nelo-cool** [comment]
Attached without the nested query
[ExpressionTest.0.cs.zip](https://github.com/linq2db/linq2db/files/855300/ExpressionTest.0.cs.zip)

**Comment by sdanyliv** [comment]
Good, more simpliest query is prefer!

**Comment by sdanyliv** [comment]
Bad news, `Configuration.Linq.GenerateExpressionTest` is not ready for analyzing issues. We have to fix that.
Can you provide file with your DataModel?

**Comment by Nelo-cool** [comment]
Okey:) One second

**Comment by Nelo-cool** [comment]
Model and query, query in MostPopularNewsQuery.cs
[Model with query.zip](https://github.com/linq2db/linq2db/files/855395/Model.with.query.zip)

**Comment by sdanyliv** [comment]
Thanks, created test based on your model. This query is produced:
```sql
-- SqlServer.2014 SqlServer.2012
DECLARE @end1 DateTime2
SET     @end1 = '2017-03-20T17:20:30.078'
DECLARE @begin1 DateTime2
SET     @begin1 = '2017-03-19'

SELECT
	[news].[Description],
	[news].[Text],
	[news].[Url],
	[news].[Id],
	[page].[Id] as [Id1],
	[page].[Name],
	[page].[Active],
	[page].[Order] as [Order1],
	[page].[CreationDate],
	[page].[ParentId],
	[page].[PageTypeId]
FROM
	[News] [news]
		INNER JOIN [Page] [page] ON [news].[Id] = [page].[Id]
		INNER JOIN [MainContent] [main] ON [page].[Id] = [main].[Id]
UNION
SELECT
	[news1].[Description],
	[news1].[Text],
	[news1].[Url],
	[page1].[Id],
	NULL as [Id1],
	[page1].[Name],
	[page1].[Active],
	[page1].[Order] as [Order1],
	[page1].[CreationDate],
	[page1].[ParentId],
	[page1].[PageTypeId],
	[news1].[Id] as [Id3] -- Looks like it is our problem
FROM
	[News] [news1]
		INNER JOIN [Page] [page1] ON [news1].[Id] = [page1].[Id]
		INNER JOIN [View] [view1] ON [page1].[Id] = [view1].[Id]
WHERE
	[page1].[CreationDate] <= @end1 AND [page1].[CreationDate] >= @begin1
```
Can you confirm that query is failing on SQL Server or on Linq2db side during conversion? Call stack whould be nice.

**Comment by Nelo-cool** [comment]
System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) +64
   LinqToDB.SqlQuery.<>c__DisplayClassf.<SetAliases>b__e(IQueryElement expr) in c:\projects\linq2db\Source\SqlQuery\SelectQuery.cs:3589
   LinqToDB.SqlQuery.QueryVisitor.Visit2(IQueryElement element) in c:\projects\linq2db\Source\SqlQuery\QueryVisitor.cs:669
   LinqToDB.SqlQuery.QueryVisitor.Visit2(IQueryElement element) in c:\projects\linq2db\Source\SqlQuery\QueryVisitor.cs:632
   LinqToDB.SqlQuery.SelectQuery.SetAliases() in c:\projects\linq2db\Source\SqlQuery\SelectQuery.cs:3587
   LinqToDB.SqlQuery.SelectQueryOptimizer.FinalizeAndValidate(Boolean isApplySupported, Boolean optimizeColumns) in c:\projects\linq2db\Source\SqlQuery\SelectQueryOptimizer.cs:48
   LinqToDB.SqlProvider.BasicSqlOptimizer.Finalize(SelectQuery selectQuery) in c:\projects\linq2db\Source\SqlProvider\BasicSqlOptimizer.cs:28
   LinqToDB.Linq.Query`1.FinalizeQuery() in c:\projects\linq2db\Source\Linq\Query.cs:222
   LinqToDB.Linq.Query`1.GetQuery() in c:\projects\linq2db\Source\Linq\Query.cs:1097
   LinqToDB.Linq.Query`1.SetQuery(Expression`1 expression) in c:\projects\linq2db\Source\Linq\Query.cs:1147
   LinqToDB.Linq.Builder.UnionContext.BuildQuery(Query`1 query, ParameterExpression queryParameter) in c:\projects\linq2db\Source\Linq\Builder\ConcatUnionBuilder.cs:191
   LinqToDB.Linq.Builder.ExpressionBuilder.Build() in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:161
   LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) in c:\projects\linq2db\Source\Linq\Query.cs:165
   LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:89
   LinqToDB.Linq.ExpressionQuery`1.get_SqlText() in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:55
   LinqToDB.Linq.ExpressionQueryImpl`1.ToString() in c:\projects\linq2db\Source\Linq\ExpressionQueryImpl.cs:15

**Comment by sdanyliv** [comment]
Ok, several additional types needed
```
NewsCategory
FriendlyUrl
PageType
```

**Comment by Nelo-cool** [comment]
[One entity and enums.zip](https://github.com/linq2db/linq2db/files/855536/One.entity.and.enums.zip)

**Comment by sdanyliv** [comment]
Strange but i have no exception on this stage. Could you please try latest bulit package located in MyGet.
In Package Manager - add Package source https://www.myget.org/F/linq2db/api/v2

**Comment by Nelo-cool** [comment]
Okey, trying... one second:)

**Comment by Nelo-cool** [comment]
You version is 1.7.5. My - 1.7.6 (from nuget). Reinstall all, a few minutes

**Comment by sdanyliv** [comment]
Try 1.7.7 from MyGet

**Comment by Nelo-cool** [comment]
Okey

**Comment by Nelo-cool** [comment]
I can't found this, my screen attach
![my get version](https://cloud.githubusercontent.com/assets/902820/24109124/c35e65fa-0da0-11e7-90f3-db686075ef85.png)
ed.

**Comment by Nelo-cool** [comment]
and 1.7.5 from myget the same exception (after clean and rebuild).

**Comment by sdanyliv** [comment]
![image](https://cloud.githubusercontent.com/assets/783759/24109259/c30c13b6-0d98-11e7-9c3f-63bf1bb1d891.png)
![image](https://cloud.githubusercontent.com/assets/783759/24109294/dff7d852-0d98-11e7-8263-c63288226aed.png)

**Comment by sdanyliv** [comment]
Check box **Include Prerelease** should be checked

**Comment by Nelo-cool** [comment]
Ahaha
![image](https://cloud.githubusercontent.com/assets/902820/24109434/acc3f6a6-0da1-11e7-8783-e457b4c538c8.png)

**Comment by Nelo-cool** [comment]
Hmmm, this is worked.
Result in text:
```
-- GTRK SqlServer.2012
DECLARE @end1 DateTime2
SET     @end1 = '2017-03-20T19:18:48.019'
DECLARE @begin1 DateTime2
SET     @begin1 = '2017-03-17'

SELECT
	[news].[Description],
	[news].[Text],
	[news].[Url],
	[news].[Category],
	[news].[Id],
	[page].[Id] as [Id1],
	[page].[Name],
	[page].[Active],
	[page].[Order] as [Order1],
	[page].[CreationDate],
	[page].[ParentId],
	[page].[PageTypeId],
	[url2].[PageId],
	[url2].[Type] as [Type1],
	[url2].[Url] as [Url1],
	[url2].[Id] as [Id2]
FROM
	[News] [news]
		INNER JOIN [Page] [page] ON [news].[Id] = [page].[Id]
		INNER JOIN [MainContent] [main] ON [page].[Id] = [main].[Id]
		INNER JOIN [FriendlyUrl] [url2] ON [page].[Id] = [url2].[PageId]
WHERE
	[url2].[Type] = 0
UNION
SELECT
	[news1].[Description],
	[news1].[Text],
	[news1].[Url],
	[news1].[Category],
	[url5].[Id],
	NULL as [Id1],
	[page1].[Name],
	[page1].[Active],
	[page1].[Order] as [Order1],
	[page1].[CreationDate],
	[page1].[ParentId],
	[page1].[PageTypeId],
	[url5].[PageId],
	[url5].[Type] as [Type1],
	[url5].[Url] as [Url1],
	NULL as [Id2],
	[news1].[Id] as [Id4],
	[page1].[Id] as [Id5]
FROM
	[News] [news1]
		INNER JOIN [Page] [page1] ON [news1].[Id] = [page1].[Id]
		INNER JOIN [View] [view1] ON [page1].[Id] = [view1].[Id]
		INNER JOIN [FriendlyUrl] [url5] ON [page1].[Id] = [url5].[PageId]
WHERE
	[page1].[CreationDate] <= @end1 AND [page1].[CreationDate] >= @begin1 AND
	[url5].[Type] = 0
```

**Comment by Nelo-cool** [comment]
But throw new excepion:
LinqToDB.Linq.Builder.UnionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\ConcatUnionBuilder.cs:373
   LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\ExpressionContext.cs:48
   LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:822
   LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:618
   LinqToDB.Linq.Builder.ExpressionBuilder.ConvertInPredicate(IBuildContext context, MethodCallExpression expression) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:1971
   LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:1338
   LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:2314
   LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:2290
   LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:45
   LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\WhereBuilder.cs:24

**Comment by Nelo-cool** [comment]
Sql query in text after pinnedItems.Union(popularItems).ToString();
Exception throw after pinnedItems.Union(popularItems),ToList();

**Comment by sdanyliv** [comment]
Ok, i see bug. Just looking onto query, but strange that `query.ToString()` works and `query.ToList()` is not.
Ideally if you provide me with creation script for tables:
`News, Page, MainContent, FriendlyUrl, View`

**Comment by Nelo-cool** [comment]
this is simple.

**Comment by Nelo-cool** [comment]
[Script.zip](https://github.com/linq2db/linq2db/files/855646/Script.zip)

**Comment by sdanyliv** [comment]
I have reasonable exception
```
System.Data.SqlClient.SqlException occurred
  Class=16
  ErrorCode=-2146232060
  HResult=-2146232060
  LineNumber=1
  Message=All queries combined using a UNION, INTERSECT or EXCEPT operator must have an equal number of expressions in their target lists.
  Number=205
  Procedure=""
  Server=BLABLA
  Source=.Net SqlClient Data Provider
  State=1
  StackTrace:
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  InnerException: 
```
But not yours. I'll try to fix current situation and then you have to try again.

**Comment by Nelo-cool** [comment]
Okey, of course, they must have the same number of fields. One second and a can count the fields in my results.

**Comment by Nelo-cool** [comment]
16 and 18. This is a bad)

**Comment by sdanyliv** [comment]
Good news, bug found and fixed. I'll prepare pull request tomorrow.

**Comment by Nelo-cool** [comment]
Oh! Thanks! I'll wait!

**Comment by Nelo-cool** [comment]
Waiting... thanks.

**Comment by sdanyliv** [comment]
@Nelo-cool, check 1.7.7.496 version in MyGet

**Comment by Nelo-cool** [comment]
Okey, one second...

**Comment by Nelo-cool** [comment]
Fine! Perfect working:)

**Comment by sdanyliv** [comment]
Thanks for detailed help in reproducing!
