### ISSUE TITLE
Can't make auto increment primary key. Can't get last auto increment indentity primary key.

### ISSUE THREAD

**Issue by R-N** [linq2db/linq2db#611]
On SQLite3, an integer primary key should auto-increment if it's inserted without any value. However I always get "UNIQUE constraint fail" on Insert. I've tried setting it to a nullable column, same issue.

Then I tried giving it Identity attribute. I can now Insert. It does auto-increment fine from what I see after running my program. However I can't get the last auto-increment primary key after inserting. I've tried both Insert and InsertWithIdentity. What do they return anyway? I've tried disposing it and recreating it before trying to get the last key. Here's my code to do it :
```cs
public int GetLastInsertId(){
	return (int)this.Execute<long>("select last_insert_rowid();"); //this works with SQLite.NET and sqlite-net
}
			
public int GetLastInsertId<T>() where T : CNCTable{
	return this.GetTable<T>().Select<T, int>(o => o.myId).TakeLast(1).Last();
}
```
None of them works. No errors either. Always returns 0. For the second method, I've tried setting a Count() check to see if it actually gets any row, and it turns out it does get a row. 

Thanks.

**Comment by sdanyliv** [comment]
I need the following things:

- script for table
- table model
- code with usage of InsertWithIdentity

**Comment by R-N** [comment]
Ok, since you asked for actual code, I just made a test project and both of those methods actually works (The first one doesnt work after I reopened the database, as expected). So the fault gotta be on my project. Thanks for your response. 

By the way, what is the "Identity" attribute? And I can't find "Unique" field, is it the same?

**Comment by sdanyliv** [comment]
As i know Linq2db do not have information about unique constraints instead of primary keys.
IdentityAttribute just inform MappingBuilder that field IsIdentity.
Ususally you have to set to such fields the following attributes
```cs
[PrimaryKey]
[Column(IsIdentity = true, SkipOnInsert = true)]
```

**Comment by R-N** [comment]
Oh, okay. I can do fine without Unique columns.
Thanks for the explanations :)

**Comment by sdanyliv** [comment]
Closing for now
