### ISSUE TITLE
Oracle: DateTimeOffset вызывается неверный конструктор

### ISSUE THREAD

**Issue by AK107** [linq2db/linq2db#612]
Проблема (баг) в неправильной инициализации ораклового типа OracleTimeStampTZ из DateTimeOffset. 

Вместо

> OracleTimeStampTZ(int year, int month, int day, int hour, int minute, int second, **double millisecond**, string timeZone)

вызывается конструктор 

> OracleTimeStampTZ(int year, int month, int day, int hour, int minute, int second, **int nanosecond,** string timeZone)

т.е. во-первых, вместо наносекунд передаются миллисекунды. а во-вторых, если так и задумывалось инициализироваться с миллисекундами, то их точности недостаточно.

Т.е. там где ожидались наносекунды, передаются миллисекунды.

В коде даже присутствует комментарий:
// value = new OracleTimeStampTZ(dto.Year, dto.Month, dto.Day, dto.Hour, dto.Minute, dto.Second, dto.Millisecond, zone);

такой конструктор есть, но он принимает миллисекунды как double.

Пруф:

> 				_createOracleTimeStampTZ =
> 					Expression.Lambda<Func<DateTimeOffset,string,object>>(
> 						Expression.Convert(
> 							Expression.New(
> 								_oracleTimeStampTZ.GetConstructorEx(new []
> 								{
> 									typeof(int), typeof(int), typeof(int), typeof(int), typeof(int), typeof(int), typeof(int), typeof(string)
> 								}),
> 								Expression.PropertyOrField(dto, "Year"),
> 								Expression.PropertyOrField(dto, "Month"),
> 								Expression.PropertyOrField(dto, "Day"),
> 								Expression.PropertyOrField(dto, "Hour"),
> 								Expression.PropertyOrField(dto, "Minute"),
> 								Expression.PropertyOrField(dto, "Second"),
> 								Expression.PropertyOrField(dto, "Millisecond"),
> 								zone),
> 							typeof(object)),
> 						dto,
> 						zone
> 					).Compile();
> 

Как лучше пофиксить надо подумать, но сразу говорю, что миллисекунд для timestamp будет недостаточно_.

Та же тема и в обратной инициализации (GetOracleTimeStampLTZ):

> 				// static DateTimeOffset GetOracleTimeStampLTZ(OracleDataReader rd, int idx)
> 				// {
> 				//     var tstz = rd.GetOracleTimeStampLTZ(idx).ToOracleTimeStampTZ();
> 				//     return new DateTimeOffset(
> 				//         tstz.Year, tstz.Month,  tstz.Day,
> 				//         tstz.Hour, tstz.Minute, tstz.Second, (int)tstz.Millisecond,
> 				//         TimeSpan.Parse(tstz.TimeZone.TrimStart('+')));
> 				// }

опять миллисекунды.

Суть в том, что при использовании обычного DateTime мы получаем точность существенно больше (такты), чем при DateTimeOffset (миллисекунды).
>

**Comment by AK107** [comment]
Yes, but the presicion is milliseconds.

**Comment by ili** [comment]
@AK107 может просто пулл реквест сделаешь? Мы быстренько сольем и на майгет выложим ;)

**Comment by AK107** [comment]
@ili ок, сегодня-завтра запилю.

**Comment by sdanyliv** [comment]
@AK107, also please prepare unit test for this pull request. Thanks!

**Comment by AK107** [comment]
Ну в общем и целом готов был запилить родную точность DateTime в 100 нс, но выяснилось, что timestamp у оракула по дефолту имеет точность в 6 (расширяется до 9, но руками) знаков после запятой, а с указанной точностью (100 нс) нужно 7. 

Как это реализовано в DateTime: в оракул попадает значение с максимальной точностью (100 нс), но дальше режется до указанной длины (6 по дефолту). Итого тест на сравнение не пройдет с DateTime.Now (если не указать точность колонки как минимум в 7 знаков).

Вопрос: повторять логику DateTime?

**Comment by AK107** [comment]
Запилил патч. Во вложении.
[Issue612.patch.txt](https://github.com/linq2db/linq2db/files/882253/Issue612.patch.txt)

**Comment by sdanyliv** [comment]
Пул реквест плиз сделай, а не патчи

**Comment by AK107** [comment]
Это огромный гемор для меня. Я вообще гитом не пользуюсь в командной разработке. Это займет больше времени, чем сам код %)

**Comment by sdanyliv** [comment]
Пооведу ликбез, сам долго сопротивлялся.
Качаем Github for windows. Ставим. https://desktop.github.com/
Делаем форк репозитория себе. Да хоть на сайте.
Через Github desktop клонируем его себе. Апдейтим свой форк с мастера (все подсказывается)
Делаем бранч, называем его, например, issue_612
Делаем изменения. Комитим с вменяемым текстом. И там же давим на кнопку Create Pull Request - все.
Чтобы апдейтнуть пул реквест - просто закомитить новые изменеия в тот же бранч и нажать Sync, чтобы данные побежали на github

**Comment by sdanyliv** [comment]
Вот и патч почему то не проходит, говорит не тот формат

**Comment by AK107** [comment]
Дайте время, я в процессе создания pull request L)

**Comment by AK107** [comment]
Багфикс не подошел?
