### ISSUE TITLE
Usage of linq2db with differnet MappingSchemas

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#615]
I use linq2db in a Business Apllication.

In this I have different DataConnections, with different mapped DTO's and different Mapping Schemas.

I want to know, how should I use linq2db correctly? In the Parts of the Code where I need DB Access, I create a DataConnection, and dispose when I've finished the DB Access. But what is with the MappingSchema? I think the creation of this is expensive, so I should keep it? How do I Setup a DataConnection with a existing MappingSchema?

**Comment by jogibear9988** [comment]
At the moment I use 
     dataConnection.AddMappingSchema(_mappingSchema)
but it looks like this is also a expensiv call, or am I wrong?

**Comment by ili** [comment]
This all depends on what you really need.
For example, you can configure:
* `MappinfSchema.Default` - this will affect all connections & all data providers
* or you can configure data provider specific mapping schema, for example: `AccessTools.GetDataProvider().MappingSchema` - this will affect all Access connections
* and you can specify per query MappingSchema with `DataConnection.AddMappingSchema()` (here we should make a point: `DataConnection.AddMappingSchema()` uses composition approach, so configuration from default schemas would be used if not overridden in your instance`

Now about performance. MappingSchema caches mapping related data to avoid using reflection. So if it is possible, if you use `DataConnection.AddMappingSchema()` it would be better to use static MappingSchema instance then you would have no performance gap (certainly only after second query, for first query caches would be builded).

**Comment by jogibear9988** [comment]
Means, I have a problem, when I use linq2db with different databases of the same type, for example mssql, because i could not use one static mapping schema (for example they use different converters), but i could not cache dataconnection.
Maybe we need a mappingschema.compile? and a dataconnection constructor accepting a mapping schema?

**Comment by ili** [comment]
Not really clear. May be you can provide sample, demonstrating the problem&

**Comment by jogibear9988** [comment]
I mean, I've a Programm wich needs to connect to different MSSql Databases every few seconds. I use Converters in my mappings wich are incompatible, means i create a mappingschema for each database. To read data, I create a DataConnection, but I have to add the mappingschema every time to the DataConnection, so every time it consts performance, cause I can not say to the DataConnection use this already compiled Mappingschema.

**Comment by sdanyliv** [comment]
@jogibear9988, it means taht you have the same DataModel but different DataConnection descedants?

**Comment by jogibear9988** [comment]
No, I've not the same data Model. I've different! But Converters are Global

**Comment by sdanyliv** [comment]
@jogibear9988, we will return to this issue later after fixing issues that we currently working on.

**Comment by jogibear9988** [comment]
thx!

**Comment by jogibear9988** [comment]
Maybe we only need a constructor with the MappingSchema as Parameter?

**Comment by sdanyliv** [comment]
@ili, can you take a look at this issue. @jogibear9988, for sure better if you can play with code by yourself and, for start, create test that simulates your problem.

**Comment by jogibear9988** [comment]
i'll create a pull req tomorrow. 
The problem with the current solution , when we use multiple static mapping schemas as ili suggested, i need to call addmappingschema of datacontext, so the merge will happen every time you create a new datacontext

**Comment by jogibear9988** [comment]
I've now tested in my real Live application. If I call the merge each time, some of my Query's take 3-4 seconds wich normaly only need 100ms

**Comment by ili** [comment]
@jogibear9988 it would be good if you can profile this situation, so we should know where the problem is.

I'v done little changes in your #630 so the perfect would be if you can test without this changes and with em

**Comment by ili** [comment]
Previous solution used to be bad.
#640 created to fix performance issue
