### ISSUE TITLE
.Net Core appsettings.json connection string

### ISSUE THREAD

**Issue by Quentinb** [linq2db/linq2db#616]
Not sure if it is just me, but I am not able to get the DataConnection to pick up the connection string from the config file in a .Net core WebApi app.

I've tried the normal web.config, appsettings.json, app.config and none of them work. I've tried:
1) Linq2DB-1.7.6
2) Linq2DB Core and
3) linq2db.Core -Version 1.7.7-rc547
in a blank, .Net Core (.Net Framework) WebApi project in VS2015.
```cs
public class DbContext : LinqToDB.Data.DataConnection
{
    public DbContext(string configuration) : base(configuration)
    {
        ..//
    }
}

using (var dtx = new DbContext("DataConnection"))
{
     ..//
}
```

**Comment by jogibear9988** [comment]
Don't know what we use at net core atm.

But if this is resolved https://github.com/dotnet/corefx/issues/4571 I think we should relook at our Code

**Comment by jogibear9988** [comment]
maybe look at this https://github.com/linq2db/linq2db/blob/master/Tests/Tests.NetCore/ConfigurationTest.cs

**Comment by ili** [comment]
`System.Configuration` is not supported by .Net Core, so you can't use either `app.config` or `web.config`

Also I don't see if there are any standard of storing connection strings in `appsettings.json`.

So for .Net Core `ILinqToDBSettings` was introduced, so you can store settings in any place you want, the only you need is to implement  `ILinqToDBSettings`

**Comment by jogibear9988** [comment]
maybe we should look at this again when 2.0 of netcore is released! if smth is implemented!

**Comment by ili** [comment]
I'v looked through current .Net Core state. `System.Configuration` is not supported. 

If it would be supported or other standard way of storing connection strings would be provided we'll implement it :)

**Comment by Quentinb** [comment]
Thanks, got my code working using the info provided in the readme. Tested on UBUNTU connecting to a external SQL server box. Thanks for the great work.

**Comment by jogibear9988** [comment]
http://stackoverflow.com/questions/39083372/how-to-read-connection-string-in-net-core

**Comment by jogibear9988** [comment]
https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings

**Comment by Quentinb** [comment]
I've also seen Shawn Wildermuth using: (Copy/paste)
`"Tokens": {
    "Key": "info redacted",
    "Audience": "http://mycodecamp.io"
}`

placed inside the appsettings.json. then loaded inside a .net core app...

`
public Startup(IHostingEnvironment env)
{
    var builder = new ConfigurationBuilder()
        .SetBasePath(env.ContentRootPath)
        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
        .AddEnvironmentVariables();
    _env = env;
    _config = builder.Build();
}
`

and then accessed in code. (the config is injected via dependency injection into the controller.)

`
issuer: _config["Tokens:Key"],
audience: _config["Tokens:Audience"],
`

**Comment by filippobottega** [comment]
Hello,
  now for .Net Core there is the package [System.Configuration.ConfigurationManager](https://www.nuget.org/packages/System.Configuration.ConfigurationManager/).
  Is it possible to update documentation to explain how to use ConfigurationManager in .Net Core console applications?

  Thank you!
