### ISSUE TITLE
Silverlight support?

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#623]
Is SL support still needed, or could we drop it? Since project.json is now obsolete, csproj does only work with VS2017, wich does not support SL5.

**Comment by ili** [comment]
SL support is needed.

I'm looking forward to migrate to VS2017, and build SL & WindowsStore projects separately (as it is done for now).

It would be needed to check this on appveyor (they have added SL SDK on VS2017 machine)

I think we should also ask them to add Windows 8 SDK... or migrate on Windows10\UWP

**Comment by jogibear9988** [comment]
Okay... 

But I think maybe if we release a V2.0 we could drop SL support.
