### ISSUE TITLE
SQLite: "Contains() == false" does not work

### ISSUE THREAD

**Issue by hoangcuongvn** [linq2db/linq2db#632]
Supposing that MyTable is declared as below
```sql
CREATE TABLE [MyTable] (
  [ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);
```
This code below works fine
```cs
var list = new long[] { 1, 2, 3 };
var q = db.MyTable
  .Where(x => !list.Contains(x.ID))
  .ToList();
```
But this code below fails with an exception **LinqToDB.Linq.LinqException: Sequence 'value( ...)' cannot be converted to SQL**.
```cs
var list = new long[] { 1, 2, 3 };
var q = db.MyTable
  .Where(x => list.Contains(x.ID) == false)
  .ToList();
```
This code below fails too.
```cs
var myval = false; // false or true
var list = new long[] { 1, 2, 3 };
var q = db.MyTable
  .Where(x => list.Contains(x.ID) == myval)
  .ToList();
```

**Comment by sdanyliv** [comment]
@hoangcuongvn, i can' reproduce on current sources. Please send POCO class that represents MyTable, maybe problem is here.

**Comment by hoangcuongvn** [comment]
@sdanyliv the declaration of MyTable is simply like below:
```
public class MyTable
{
	public long ID { get; set; }
}
```
I also created a simple sample to reproduce the issue. You can download it by the link below
https://drive.google.com/open?id=0BysoVKf0mGpPVUtHTEZuN2YzZlU

It is 'interesting' that the code below works fine.
```
var q = db.MyTable
  .Where(x => (!!list.Contains(x.ID)) == myval)
  .ToList();
```

**Comment by sdanyliv** [comment]
@hoangcuongvn, thanks for the test project!
In version 1.7.6 it is reproduced. But in current sources it is already fixed, possibly in this commit
https://github.com/linq2db/linq2db/commit/9317c028d1a1a573a0048b547a048011f6659dfd
I think new release is planned on this or next weekdays.
If you can not wait, you can get pre-release version in MyGet

**Comment by sdanyliv** [comment]
@hoangcuongvn, closed for now. Issue already fixed.
