### ISSUE TITLE
Read all Mapped Entity Objects from a MappingSchema

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#637]
Do we have a API, so I can read all Types wich are Mapped via 

      var mb = mappingSchema.GetFluentMappingBuilder();

            mb.Entity<ActionDTO>().HasTableName....

**Comment by sdanyliv** [comment]
Looks like it is private Dictionary.

**Comment by ili** [comment]
Why do you need such API?

**Comment by jogibear9988** [comment]
I wanted to know wich Types are all mapped to a Database Table, to create a full Backup

**Comment by ili** [comment]
You can't do it for sure. You see, each mapping schema caches remembers EntityDescriptors, but they are created only when needed, so you can't be sure for moment that all types are cached.

Certainly we can do some enumeration of types and descriptors, but I think it is more safe to use reflection to load all needed types

**Comment by jogibear9988** [comment]
Can't we do it for fluent mapped types only? Cause fluent mapped types are hard to find via reflection!

**Comment by jogibear9988** [comment]
And also, can we create a init function, that creates entitydescriptors for all fluent mapped types
