### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#646]
Hello, 
I am sorry, but I cannot find any example gow to log made sql queries, maybe also on error. 
There is something explained with miniprofiler, but I cannot see where to add any configuration e.g. to use nlog.. 
Could you please make a real life example, maybe it is enough with writing to console or to file.

**Comment by sdanyliv** [comment]
```cs
DataConnection.TurnTraceSwitchOn();
DataConnection.WriteTraceLine = (s1,s2) =>
	{
		Debug.WriteLine(s1, s2);
	};
```

**Comment by Franki1986** [comment]
Hello!
Thank you for the answer, that helped !
But I  have noticed that when I create a select by a 'ToList()' the expiration time in the TraceInfo is not the time the select command need to complete. This trace is not fired.

**Comment by sdanyliv** [comment]
@Franki1986, please send sample and what you expected to get Also TraceInfo do not have **expiration time**

**Comment by Franki1986** [comment]
Here a litle example 


```
using (var db = new MyBb("MyData"))
         {
            DataConnection.TurnTraceSwitchOn();
            DataConnection.WriteTraceLine = (s, s1) => { Console.WriteLine(s); };
            var before = DateTime.Now;
            var result = db.PERSONS.ToList();
            var after = DateTime.Now;
            var executionTime = after - before;
            Console.WriteLine("Execution time: {0}", executionTime);
         }
```
I had expected that executionTime is the same like in TraceInfo...

**Comment by Franki1986** [comment]
Sorry my fault! I thought the execution time is the time until the complete process has finished (loading and mapping), but it is the database-fetch time..
