### ISSUE TITLE
Switch Library

### ISSUE THREAD

**Issue by mkchmiel** [linq2db/linq2db#648]
Hello,

How can I switch between collection/libraries? I am dealing with a db that has 11 that have identical table structures and want to be able to switch between them dynamically.

**Comment by arbh89** [comment]
One solution will be to have multiple connectionstrings and initialize DataConnection with connectionstring parameter.

```cs
public class DbNorthwind : LinqToDB.Data.DataConnection
{
  public DbNorthwind(string connectionStringName) : base(connectionStringName) { }

  public ITable<Product> Product { get { return GetTable<Product>(); } }
  public ITable<Category> Category { get { return GetTable<Category>(); } }
  
  // ... other tables ...
}
```

And the use it.

```cs
public static List<Product> All()
{
 var connectionName = "Northwind";
  using (var db = new DbNorthwind(connectionName))
  {
    var query = from p in db.Product
                where p.ProductID > 25
                orderby p.Name descending
                select p;
    return query.ToList();
  }
}
```

**Comment by sdanyliv** [comment]
@mkchmiel, i suppose i understand your question. You can switch between databases on the fly.
```cs
db.GetTable<Entity>.Database("ArchiveDb").Select(...)
```

**Comment by mkchmiel** [comment]
This is wierd, I dont see the option db.GetTable<Entity>().Database("ArchiveDb"). What version of LinqToDB are you using?

**Comment by sdanyliv** [comment]
My fault. You should use **DatabaseName** instead. You can found other extension methods in LinqExtensions class.

**Comment by mkchmiel** [comment]
I can only assume that my database setup is quite particular and may or may not be industry standard. For me .SchemaName() seemed to work. I appreciate everyone's input, thanks.

**Comment by sdanyliv** [comment]
Great. That is why some extensions were introduced. For example, my previous customer had partitioning by tables and based on some id I have to to switch to another table with the same columns. These extensions helped me very much, and i've never seen analogues in other ORMs.
