### ISSUE TITLE
VB - error with anonymous group by multiple fields

### ISSUE THREAD

**Issue by yarecky1** [linq2db/linq2db#649]
Assume 2 simple tables:
```
<Table("activity")>
Public Class Activity
    <Column, Identity, PrimaryKey> Property activityid As Integer
    <Column, NotNull> Property personid As Integer
    <Column, NotNull> Property added As Date

    <Association(ThisKey:=NameOf(personid), OtherKey:=NameOf(Person.personid), CanBeNull:=False)> Public Property Person As Person
End Class

<Table("person")>
Public Class Person
    <Column, Identity, PrimaryKey> Property personid As Integer
    <Column, NotNull> Property personname As String
    <Association(ThisKey:=NameOf(personid), OtherKey:=NameOf(Activity.personid), CanBeNull:=False)> Public Property Activties As List(Of Activity)
End Class
```
With data:
```
activityid; personid; added
1; 1; 2017-05-01
2; 2; 2017-05-01
3; 3; 2017-05-01
4; 1; 2017-05-02
5; 2; 2017-05-03

personid; personname
1; user 1
2; user 2
3; user 3
```
This SQL query works as expected returning 3 Persons by last added in Activities.
```SQL
SELECT P.personid, P.personname, max(A.added) AS lastadded
FROM activity A
INNER JOIN person P ON A.personid = P.personid
GROUP BY P.personid, P.personname
ORDER BY max(A.added) DESC
```
Result:
```
personid; personname; lastadded
2; user 2; 2017-05-03
1; user 1; 2017-05-02
3; user 3; 2017-05-01
```
However below Linq query raises an exception.
```
An unhandled exception of type 'System.ArgumentException' occurred in linq2db.dll.
„Key” is not member of type „System.Collections.Generic.IEnumerable`1[**namespace here**.Activity]”.
```
```VB.NET
Using db = New DbContext() With {.InlineParameters = True}

 Dim q1 = (From p In db.Activites
           Where p.added >= New Date(2017, 1, 1)
           Group By pp = New With {Key p.Person.personid, Key p.Person.personname} Into ppp = Group
           Select New With
            {
             .PersonId = pp.personid,
             .PersonName = pp.personname,
             .LastAdded = ppp.Max(Function(f) f.added)
            }).ToList

 For Each q In q1
  Debug.WriteLine("userid: {0}, username: {1}, lastadded: {2}", q.PersonId, q.PersonName, q.LastAdded)
 Next

End Using
```
This part of Group By also does not work
```VB.NET
Group p By pp = New With {Key p.Person.personid, Key p.Person.personname} Into ppp = Group
```
This one also doesn't.
```VB.NET
 Dim q1 = (From p In db.Activites
           Join p In db.Persons ON ....
```
All above linq queries (and other similar) works as expected on collections in memory.

How to transfer this SQL into Linq to work. Grouping by 2 fields is a common practise, isn't it? Without it, all this Linq2Db is crippled.

See also here [http://stackoverflow.com/q/43744979/5213964](url)

**Comment by sdanyliv** [comment]
@yarecky1, looks like VB has bad Linq queries resolver - it creates unexpected method chain that can not be converted to SQL .

Try to use the following syntax
```vb
 Dim q1 = (From p In db.Activites
           Where p.added >= New Date(2017, 1, 1)
            Group By pp = New With {Key p.Person.personid, Key p.Person.personname} Into LastAdded = Max(p.added)
	    Select pp.personid, pp.personname, LastAdded).ToList
```

**Comment by yarecky1** [comment]
@sdanyliv, absolutely fantastic, it works. How did you know? I've never used query this way. 👍 
I also needed to Count how many times Person is in each group (no matter when Added to Activity)
and this works (Count without argument)
Do you maybe know place in internet when I can see more similar examples with grouping into Max, Sum, Count (other?), multiple Aggregators?
```
Group By pp = New With {Key p.Person.personid, Key p.Person.personname} Into LastAdded = Max(p.added), HowMany = Count
```
Returned query is optimal
```
SELECT
	[t1].[personid],
	[t1].[personname],
	Max([t2].[added]) as [c1],
	Count(*) as [c2]
FROM
	[activity] [t2]
		INNER JOIN [person] [t1] ON [t2].[personid] = [t1].[personid]
WHERE
	[t2].[added] >= #2017-01-01#
GROUP BY
	[t1].[personid],
	[t1].[personname]
```
giving
```
personid; personname; lastadded; howmany
2; user 2; 2017-05-03; 2
1; user 1; 2017-05-02; 2
3; user 3; 2017-05-01; 1
```
Thank you!

**Comment by sdanyliv** [comment]
@yarecky1, I've created test on VB and compiled it. Then i examine assembly by dotPeek and found that method chain that were generated is not acceptable for linq2db. Next step is to read Group By specification from MSDN where I've found simplified syntax.

That's all.

**Comment by sdanyliv** [comment]
Your sample generates this method chain:
```cs
		[Test, DataContextSource]
		public void Test2(string context)
		{
			using (var db = GetDataContext(context))
			{
				db.InlineParameters = true;
				var q1 = db.GetTable<Issue649Tests.Activity>()
				.Where(p => p.added >= new DateTime(2017, 1, 1))
				.GroupBy(p => new
				{
					personid = p.Person.personid,
					personname = p.Person.personname
				}, (pp, activities) => new
				{
					pp = pp,
					ppp = activities
				}).Select(data => new
				{
					PersonId = data.pp.personid,
					PersonName = data.pp.personname,
					LastAdded = data.ppp.Max(f => f.added)
				}).ToString();
				var str = q1.ToString();
			}
		}
```
But second that I've proposed is simplier:
```cs
		[Test, DataContextSource]
		public void TestChain(string context)
		{
			using (var db = GetDataContext(context))
			{
				db.InlineParameters = true;

				var q1 = db.GetTable<Activity>()
				.Where(p => p.added >= new DateTime(2017, 1, 1))
				.GroupBy(p => new
				{
					personid = p.Person.personid,
					personname = p.Person.personname
				}).Select(ppp => new
				{
					personid = ppp.Key.personid,
					personname = ppp.Key.personname,
					LastAdded = ppp.Max(f => f.added)
				}).ToString();

				var str = q1.ToString();
			}
		}
```

**Comment by sdanyliv** [comment]
> Do you maybe know place in internet when I can see more similar examples with grouping into Max, Sum, Count (other?), multiple Aggregators?

Nothing special here it is standard extension functions for IEnumerable. 
For example: http://www.csharp-examples.net/linq-aggregation-methods/

**Comment by yarecky1** [comment]
@sdanyliv, yes, result of what you proposed is clean and maximally optimal. I've never used such a syntax you proposed and looking into web I see that 99% of examples and question from people have syntax like main before. In fact the second example in C# you presented just above is the perfect and cleanest.

I tried this way too
```
Dim query = db.Activites.
Where(Function(f) f.added>= New Date(2017, 1, 1).
GroupBy(Function(f) New With 
{
   Key .personid = f.Person.personid,
   Key .personname = f.Person.personname
}).Select(Function(f) New With
{
   .personid = f.Key.personid,
   .personname = f.Key.personname,
   .LastAdded = f.Max(Function(g) g.added)
}).ToList
```
however I receive new exception
```
An unhandled exception of type 'LinqToDB.Linq.LinqException' occurred in linq2db.dll
Convert(f).Select(g => g.Date).Max()' cannot be converted to SQL
```
Could you see what you would receive?

**Comment by yarecky1** [comment]
@sdanyliv, concerning link you provided to examples - thanks, it's clear - but I'm looking for examples and **explanation** of using syntax ```Group By ... Into ... x = Max, Sum, Count``` etc. I try to understand how it works and how it differs from standard ```Group By ... Into ... x = Group``` and then finally in Select statement to choose ```property = Max, Sum, Count``` etc.

**Comment by sdanyliv** [comment]
@yarecky1, last time I saw VB it was about two decades ago and it was not VB.NET, really strange what it generates. Move forward to left this language for the history :)
https://msdn.microsoft.com/en-us/en-en/library/bb531412.aspx

**Comment by yarecky1** [comment]
@sdanyliv Nice. you farewelled VB.Net two decades ago. I met VB when it was necessary to improve my work in Excel, 15 years ago, then 10 years ago I switched to VB.Net. How I hate VB in Excel now. I plan to switch to C# since long time ago but due to many reasons I can't. Many projects I developed are in VB.Net, I need to maintain them and add new functions so I need to stick with it. Learning curve for C# is long. I know it's industry standard and 90% of users use C#, but VB.NET is not dead yet.

> We will keep Visual Basic straightforward and approachable. We will do everything necessary to keep it a first class citizen of the .NET ecosystem: When API shapes evolve as a result of new C# features, for instance, consuming those APIs should feel natural in VB. We will keep a focus on the cross-language tooling experience, recognizing that many VB developers also use C#. We will focus innovation on the core scenarios and domains where VB is popular.

[https://blogs.msdn.microsoft.com/dotnet/2017/02/01/the-net-language-strategy/](url)

**Comment by sdanyliv** [comment]
@yarecky1, with your latest sample - VB.NET compiler adds unnecessary Convert to IEnumerable when generating Expression Tree.
Will check how to ignore this Convert in or code.
