### ISSUE TITLE
Is it possible to do "LIKE" statements using this library?

### ISSUE THREAD

**Issue by ravensorb** [linq2db/linq2db#650]
I am trying to figure out how I can do something like this

```
select id, name, status from tblStatus where status like 'open%';
```

is this currently possible?

**Comment by sdanyliv** [comment]
Yes,
In native way
```cs
where status.StartsWith("open")
```
Or through extension
```cs
where Sql.Like(status, "open%")
```

**Comment by ili** [comment]
Also string.Contains() and string.EndsWith() would be converted to appropriate LIKE

**Comment by ravensorb** [comment]
Perfect -- this was exactly what I was looking for.  Must say -- super impressed with this library so far :)

**Comment by ili** [comment]
You are welcome! )
