### ISSUE TITLE
OData WebApi over Linq2Db

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#655]
I write web-service worked by OData protocol. 
As data access layer using L2DB.
If odata query include expand option, the result expression throw error:
` Multiple queries are not allowed. Set the 'LinqToDB.Common.Configuration.Linq.AllowMultipleQuery' flag to 'true' to allow multiple queries.`

Executable query:
```C#
db.GetTable<Department>()
                .Select(Param_0 => new SelectAllAndExpand()
                {
                    ModelID = "2cd45fee-a6aa-4d0e-9024-0a7fbc48e50b",
                    Instance = Param_0,
                    Container = new NamedProperty()
                    {
                        Name = "DepartmentHierarchyToDepartmentsChildren",
                        Value = IIF(
                                  IIF((Param_0 == null), null, Param_0.DepartmentHierarchyToDepartmentsChildren) == null,
                                  null,
                                  IIF((Param_0 == null), null, Param_0.DepartmentHierarchyToDepartmentsChildren)
                                    .Select(Param_1 => new SelectAll
                                    {
                                        ModelID = "2cd45fee-a6aa-4d0e-9024-0a7fbc48e50b",
                                        Instance = Param_1
                                    })
                                )
                    }
                });
```
How to fix this error without AllowMultipleQuery=true

**Comment by sdanyliv** [comment]
@genusP, we have limited support of expandable propertie (Include, LadWith, etc).
It is a big work before it can be introduced in future releases.
BTW, why you have uses `IIF` function instead of `? :` ?

**Comment by genusP** [comment]
>we have limited support of expandable propertie (Include, LadWith, etc).
For this code the same error:
```C#
db.GetTable<Models.Department>()
    .LoadWith(e => e.DepartmentHierarchyToDepartmentsChildren)
```
> BTW, why you have uses IIF function instead of ? : operator ?
Yes.

**Comment by sdanyliv** [comment]
@genusP, i'll repeat again: we have limited support of such kind of functionality

**Comment by genusP** [comment]
It turns out that LoadWith allows you to load data for an association many to one?
Облом

**Comment by ili** [comment]
We are keeping in mind issues with lack of `LoadWith` functionality. It should be rewritten totally, but for now it is not the main point.

**Comment by ili** [comment]
Will close for now :(
