### ISSUE TITLE
ToListAsync requires MSDTC but should not

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#656]
In correspondence with this: https://github.com/linq2db/linq2db/issues/438

I have used Merge to implement multi update as part of migration from BLTollkit which has API to update collection of items.

Unfortunately it is not a solution yet... During call to merge Linq2Db tries to use MSDTC.
It is very strange because it should use ambient transaction instead of distributed.
Of course MSDTC is not available on Linux and other platforms where Linq2Db can be used.
I afraid it can be related to async programming. I need to investigate more...

But if somebody related to merge can reply it will be good.

**Comment by hardhub** [comment]
I have investigated it a bit more...

Issue is with TransactionScope (async flow enabled) and ToListAsync (from AsyncExtensions).

Originally I mentioned Merge because it was next command executed in transaction scope... But 2 merge commands runs fine... 2 readers not (2nd one raises exception).

So I still do not know the reason... But I will explain what I know... Let's say you have the following (pseudo-code):

```C#
using (TransactionScope transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
     var users1;
     var users2;

      using (context1 = ...)
      {
             users1 = await context1.Users.ToListAsync();
      }

      using (context2 = ...)
      {
            users2 = await context2.Users.ToListAsync();
      }

     // Do something with data...
}
```

I tried to replace this code by new one but pure ADO.Net... I am using ExecuteReaderAsync...

So instead of each context I am using the following code:

```C#
List<User> entities = new List<User>();

using (SqlConnection connection = new SqlConnection(settings))
{
	connection.Open();

	using (SqlCommand command = new SqlCommand("SELECT * FROM [User]", connection))
	{
		using (SqlDataReader reader = await command.ExecuteReaderAsync())
		{

			while (reader.Read())
			{
				string name = reader.GetFieldValue<string>(...);

				User user = User.New();
				user.Name = name;

				entities.Add(user);
			}
		}
	}

	connection.Close();
}
```
All works fine in that case... So we have some issue with Linq2Db from point of view of async flow...
It can be that in some way linq2db does not release first connection and 2nd one makes transaction distributed.

**Comment by hardhub** [comment]
I am sure we need to replace current async code with framework provided calls. For example ExecuteReaderAsync... Also some workaround will be good...

https://github.com/linq2db/linq2db/issues/283#issuecomment-292707299

P.S. It is not "feature" it is "bug".... 
DTC is not supported in Mono.. and most likely will never be supported...

**Comment by hardhub** [comment]
I have tested FirstOrDefaultAsync on the same table and all works fine...
So it can require some small delay to reproduce it like it is for ToListAsync (table has 200 rows).

**Comment by hardhub** [comment]
The latest version from master does not work at all:

IDataContext is disposed Object name: 'DataConnection'.

   at LinqToDB.Data.DataConnection.ThrowOnDisposed()
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.SetQuery(IQueryContext queryContext)
   at LinqToDB.Linq.Query`1.SetCommand(IDataContext dataContext, Expression expr, Object[] parameters, Int32 idx, Boolean clearQueryHints)
   at LinqToDB.Linq.Query`1.<RunQuery>d__11.MoveNext()
   at LinqToDB.Linq.Query`1.<Map>d__69.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by sdanyliv** [comment]
@hardhub, do you mean ToListAsync?

**Comment by hardhub** [comment]
Yes.. I renamed it already...

**Comment by sdanyliv** [comment]
I suppose you have disposed connection befor ToListAsync finished. Your sample from pseudo code shows that situation. Right usage below:
```cs
async void TestImpl(string context)
{
	Test1(context);

	using (var db = GetDataContext(context))
	{
		var list = await db.Parent.ToListAsync();
	}
}
```

**Comment by hardhub** [comment]
What is difference? I do not see anything wrong in my code.
```

      using (context1 = ...)
      {
             users1 = await context1.Users.ToListAsync();
      }

       using (var db = GetDataContext(context))
	{
		var list = await db.Parent.ToListAsync();
	}
```

**Comment by sdanyliv** [comment]
@hardhub, my fault, typing from iPad. Could you please provide with exact code that fail?

**Comment by hardhub** [comment]
I think I will need to create some test project... and share it... because it is hard now to obfuscate real project... But it will be in common as my pseudo code.

**Comment by sdanyliv** [comment]
@hardhub, have you found why your code fails with 'IDataContext is disposed' exception?

**Comment by hardhub** [comment]
Not yet..
I temporarily reverted to previous version.. and enabled MSDTC.
I hope I will find time to do it on next week.

**Comment by sdanyliv** [comment]
Great, it is critical for us to catch probleam early. Many developers have used DataConnection in inproper way so it's why this exception was introduced.

**Comment by hardhub** [comment]
I do not think that it is not properly used.
As I wrote I can guess that it is bad async support.
But let me check of course...

**Comment by hardhub** [comment]
@sdanyliv 

Finally I have investigated the case... All becomes clear... Let's look at this code:

```C#
public static class Job
{
	public static async Task Run()
	{
		await RunNice();
		await RunNice();

		Console.WriteLine("RunNice");

		await RunFail();
		await RunFail();

		Console.WriteLine("RunFail");
	}

	private static async Task RunNice()
	{
		List<Plane> planes = null;

		using (Storage storage = new Storage())
		{
			IQueryable<Plane> queryable = storage.GetTable<Plane>();

			planes = await queryable.ToListAsync();
		}

		List<Plane> output = planes;
	}

	private static async Task RunFail()
	{
		Task<List<Plane>> planes = null;

		using (Storage storage = new Storage())
		{
			IQueryable<Plane> queryable = storage.GetTable<Plane>();

			planes = queryable.ToListAsync();
		}

		List<Plane> output = await planes;
	}
}
```

So as I mentioned it is related to async flow. The difference between RunNice and RunFail is only the way of async usage. In first case we normally await end of execution, so all actions are completed before DbContext releasing. In 2nd case we just returning task for future execution (just another way sometimes used in development). This task will be executed almost immediately but it is enough to get troubles with scope of DbContext and to start new transaction.
Since all that code is running in transaction scope it will require MSDTC (2 parallel transactions escalate it to be distributed):
```C#
using (TransactionScope transaction = new TransactionScope(/* async flow enabled */))
{
	Job.Run().Wait();

	transaction.Complete();
}
```

So all that is reasonable... And I even do not know if it should work in other way.
The single option is to create task which can be executed on the same transaction (shared across transaction scopes) independently of disposed db context. Maybe ExecuteReaderAsync can help to support task-based flow. But as I said I am not sure we need such usage of the tasks. 
In my opinion just normal async API will be much more appreciated...
But let's discuss if it matters....

**Comment by MaceWindu** [comment]
Please check this link https://github.com/linq2db/linq2db/wiki/Managing-data-connection

Let's try to summarize it - linq2db doesn't handle connections outside of data context scope by producing abandoned connections, that's why you had your transaction promoted to distributed before. Starting from 1.8.1 we implemented protection from it and throw exception to prevent such use.

What you can do:
- use recommended approach as in RunNice method
- if you cannot use it - move context scope creation to higher level so it will include task execution

**Comment by hardhub** [comment]
Yes.. I have changed all to awaiting inside context.
And since it is strongly required I think exception is good idea.
So I can say my specific case is solved... 

Only native async support is left... and as I understand it is part of new major version (2.0.0).
