### ISSUE TITLE
Wcf service serializer

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#659]
1. Is it possible to change the serializer that is used for the wcf service? I would like to use protobuf-net.  
Or better said, would there be any performance improvement if I would change, or is the  current serialization method even better?
2. Is there a way to compress the result from db with something like snappy or sharp zip? 

Iean these questions are realy important, because linq2db is realy fast, but if the way to send data slows down the process, then I would us a default way to use a a wcf service.

**Comment by jogibear9988** [comment]
It is possible to change wcf serializer, but if you do so, i would suggest to use netserializer! Also, compression is also possible, see: http://stackoverflow.com/questions/10642600/wcf-custom-binding-for-compression

**Comment by Franki1986** [comment]
Thanks for the response! Because I am new to linq2DB and would realy like to use it in my new projects, is there the possibility for a short example?

Based on the Windows Host example where would I start?
Host:

```
static void Main(string[] args)
		{
			var host = new ServiceHost(new LinqService { AllowUpdates = true }, new Uri("net.tcp://localhost:30304"));

			host.Description.Behaviors.Add(new ServiceMetadataBehavior());
			host.Description.Behaviors.Find<ServiceDebugBehavior>().IncludeExceptionDetailInFaults = true;
			host.AddServiceEndpoint(typeof(IMetadataExchange), MetadataExchangeBindings.CreateMexTcpBinding(), "mex");
			host.AddServiceEndpoint(
				typeof(ILinqService),
				new NetTcpBinding(SecurityMode.None)
				{
					MaxReceivedMessageSize = 10000000,
					MaxBufferPoolSize      = 10000000,
					MaxBufferSize          = 10000000,
					CloseTimeout           = new TimeSpan(00, 01, 00),
					OpenTimeout            = new TimeSpan(00, 01, 00),
					ReceiveTimeout         = new TimeSpan(00, 10, 00),
					SendTimeout            = new TimeSpan(00, 10, 00),
				},
				"LinqOverWCF");

			host.Open();

			Console.WriteLine("Press any...");
			Console.ReadKey();

			host.Close();
		}
```

Client:

```

public partial class NorthwindDB
	{
		public NorthwindDB() : base(
			new NetTcpBinding(SecurityMode.None)
			{
				MaxReceivedMessageSize = 10000000,
				MaxBufferPoolSize      = 10000000,
				MaxBufferSize          = 10000000,
				CloseTimeout           = new TimeSpan(00, 01, 00),
				OpenTimeout            = new TimeSpan(00, 01, 00),
				ReceiveTimeout         = new TimeSpan(00, 10, 00),
				SendTimeout            = new TimeSpan(00, 10, 00),
			},
			new EndpointAddress("net.tcp://localhost:30304/LinqOverWCF"))
		{
			((NetTcpBinding)Binding).ReaderQuotas.MaxStringContentLength = 1000000;
		}
	}
```

**Comment by Franki1986** [comment]
Ok correct me if I am wrong but but to change the serializer to protobuf-net it is enough to ad this to server and client:

`endpoint.Behaviors.Add(new ProtoEndpointBehavior());`

For compression (.NET >= 4.5):

```
public NorthwindDB() {
                                var binding = new CustomBinding();
                                var binaryMessageEncBinding = new BinaryMessageEncodingBindingElement();
                                binaryMessageEncBinding .CompressionFormat = CompressionFormat.GZip;
                                binding.Elements.Add(binaryMessageEncBinding );
                                var tcpTransportBinding= new TcpTransportBindingElement();
                                tcpTransportBinding.MaxBufferSize = 100000000;
                                tcpTransportBinding.MaxReceivedMessageSize = 100000000;
                                binding.Elements.Add(tcpTransportBinding);
                                binding = new CustomBinding(binding);

			base(binding, new EndpointAddress("net.tcp://localhost:30304/LinqOverWCF"))
		
			((NetTcpBinding)Binding).ReaderQuotas.MaxStringContentLength = 1000000;
		}

```

**Comment by MaceWindu** [comment]
I'm looking at how it is implemented and as I can see - you cannot just replace one serializer with another easily. Current implementation doesn't provide serializer abstraction - calls to current serializer (`LinqServiceSerializer`) placed into client and service implementation and serialized query is a string parameter, passed as a parameter of `ILinqService` interface methods.
From other size I don't think you need to replace serializer, because current one is very laconic one already.
E.g. following query serialized like that (566 characters):
```
db.GetTable<TestTable1>().Insert(() => new TestTable1
					{
						Id = RID,
						TestField = TestEnum1.Value2
					});
```

```
0
1 27 0
2 23 0 0 0 0
3 0 0 1:* 1:* 1 0 0 0 0 0 0 - 0 0 0 -
4 -2 12:System.Int32
5 0 4 2:Id 2:ID 0 1 -1 0 1 1 15 - 0 0 0 -
6 -2 12:System.Int64
7 0 6 9:TestField 11:BigIntValue 0 0 0 0 1 1 16 - 0 0 0 -
8 0 4 10:Int32Field 8:IntValue 0 0 0 0 1 1 15 - 0 0 0 -
9 -2 36:Tests.Linq.EnumMappingTests+RawTable
10 7 3 13:LinqDataTypes - - - 13:LinqDataTypes 9 - 3 3 5 7 8 0
11 21 10 2:t1 0
12 28 1 11
13 5 4 3:101
14 10 5 0 13
15 20 0 14 0
16 19 1 15
17 29 16
18 30 0
19 19 0
20 29 19
21 31 0
22 17 2 1 12 0 0 1 1 1 2 0 17 18 20 21 0 0 - 0 -
23 -1 0

```

You can allways improve it by adding compession behavior, because there is no built-in compression in linq2db.

Of course you can always create your own serializer and submit PR, but first check current implementation to measure amount of work: https://github.com/linq2db/linq2db/blob/master/Source/ServiceModel/LinqServiceSerializer.cs.

**Comment by Franki1986** [comment]
Thanks for the answer! This was part of my first question, if there is the necessity to replace it, or if the serializer has enough performance due to the fact that there are no comparisons.
For the second question, is the way I posted it right and can it be used so?

**Comment by MaceWindu** [comment]
Sorry, I didn't used binary encoder with compression, so I cannot answer it. But I don't see a reason why it shouldn't work. Message encoder will not conflict with serialized query/response, because their serialization don't utilize WCF stack.

**Comment by ili** [comment]
1. @Franki1986 there is no necessity to replace current serializer, it is really simple and supposed to be fast enough from one side and compact from another.
1. Speaking about the compression, is it really needed? You do have problems or expect any?

**Comment by Franki1986** [comment]
1. That's ok
2. I have connections over the internet to customers who don't have highspeed connections and I have often to transport huge data for their reports, so this is my weakest layer. I am switching from linq to NHibernate to Linq2DB want to improof every single point.

**Comment by sdanyliv** [comment]
@Franki1986, just try to enable Message encoding and i think it should work.
Please answer in few words. How your reporting works? It is grids, pivot grids? It is some reporting engine?

**Comment by Franki1986** [comment]
@sdanyliv I am using DevExpress XtraReports, you can bind them to Xml or Objectdatasource or DataTable ... [https://documentation.devexpress.com/#XtraReports/CustomDocument2594](DevExpress datasource)

There is even a simple way to bind to linq to sql..
[https://www.devexpress.com/Support/Center/Example/Details/E1455](Xtrareport linq 2 sql datasource)

**Comment by sdanyliv** [comment]
@Franki1986, ok.
As i know XtraReports is server side component and queries are executed on reporting server. 
For which purpose do you need LinqService in that case? Your reporting server connects to database via other app server?

**Comment by Franki1986** [comment]
Ok, it is a little bit more, I have a server that is connected to multiple clients. The server loads data over a WCF service from the clients. Each client has it's own database with user specific and hardware-info data. I cannot connect directly the database from the server because Firebird does not have secure access. Although I do hardware controling from the server -> client connection, so that I do need the service either way.

**Comment by sdanyliv** [comment]
@Franki1986, i see that your system has architecture complicity and maybe caching on reporting server. Try to enable message encoding with gzip.

**Comment by Franki1986** [comment]
:-) yes it is a huge project based on historical development.. I will try and report my results, I will also test if there is a way to use 7zip z standard and report...

**Comment by MaceWindu** [comment]
Looks like all questions addressed. Feel free to reopen if something is still not clear.
