### ISSUE TITLE
InvalidCastException "Column is null" on select from PostgreSQL

### ISSUE THREAD

**Issue by shnipov** [linq2db/linq2db#665]
I'm using linq2db with PostgreSQL 9.6.2
Target framework 4.5.1
linq2db 1.8.0
npgsql 3.2.2

I've updated npgsql from 3.1.8 to 3.2.2 because of better TransactionScope support.

But they've also changed the behavior of `GetSchemaTable()` method in`NpgsqlDataReader : DbDataReader` – now it depends of `CommandBehavior` parameter and by default doesn't return correctly `AllowDBNull` property of columns, it is always false. You should pass `CommandBehavior.KeyInfo` flag if you want extended properties.

So i'm getting `InvalidCastException` "Column is null" when debugging queries on tables with nullable fields. It's getting catched in linq2db `Query` class and seems to work ok, but in general this looks as something is going wrong and could have other bad consequences.

Simplified example:
```csharp
using(var db = new PricelistDB())
{
    List<Pricelist> result = db.Pricelists.Where(x => x.SupplierId == supplierId).ToList()
    // getting the result, but catching exception in debug mode
}

[Table(Schema="pricelist", Name="pricelists")]
public partial class Pricelist
{
	[Column("pricelist_id"), PrimaryKey,  Identity]
	public int PricelistId { get; set; } // integer

	[Column("name"), Nullable]
	public string Name { get; set; } // character varying(256)
}
```
Don't know if it's linq2db problem, may be there is simple workaround, but I didn't find any. Can provide more details if needed.
Could you please share you thougths on this issue?

**Comment by ili** [comment]
Hello @shnipov, 
It would be great to have a stack trace

**Comment by shnipov** [comment]
Here it is:
```
   в Npgsql.BackendMessages.DataRowMessage.CheckNotNull()
   в Npgsql.NpgsqlDataReader.<ReadColumn>d__99`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlDataReader.ReadColumn[T](Int32 ordinal)
   в Npgsql.NpgsqlDataReader.GetDateTime(Int32 ordinal)
   в lambda_method(Closure , QueryContext , IDataContext , IDataReader , Expression , Object[] )
   в LinqToDB.Linq.Query`1.<Map>d__6a.MoveNext() в c:\projects\linq2db\Source\Linq\Query.cs:строка 1201
```

**Comment by sdanyliv** [comment]
@shnipov, great will check that tomorrow.
