### ISSUE TITLE
Double is not converted to proper value - MS SQLServer

### ISSUE THREAD

**Issue by ldenis2** [linq2db/linq2db#668]
Double conversion to SQL query is not correct. Following code doesn't work:
```sql
public static class Functions
{  
     [Sql.Function("dbo.SomeFunction", 0, ServerSideOnly = true)]
        public static double SomeFunction(double value)
        {
            throw new NotImplementedException();
        }
}
db.GetTable<SomeTable>().Select(_ => Functions.SomeFunction(double.MaxValue));
```

The code throws an exception like ----> System.Data.SqlClient.SqlException : The floating point value '1.79769313486232E+308' is out of the range of computer representation (8 bytes).

It happens since the code is converted to SQL query like:
`select dbo.SomeFunction(1.79769313486232E+308) from someTable 
`
but if it were executed like 
`select dbo.SomeFunction(1.7976931348623157E+308) from someTable ` 
it would work just fine.
Please use G17 format for double values.

**Comment by ili** [comment]
Not sure this is a bug... C# & SQL Server have different ranges & precisions for floating point values, I can't see how can we fix it :(

**Comment by sdanyliv** [comment]
@ili, I have solution but there issue with SQL Lite, it returns Infinite in that case.
Will fix that on next week.
Also there are problems with **decimal**

**Comment by MaceWindu** [comment]
@ili this is an issue in linq2db - we should generate float/double literals in roundtrip format, for double it is G17. But yeah, as @sdanyliv mentioned with Sqlite - some providers could also handle FP numbers incorrectly.

**Comment by ili** [comment]
OK, I see :)
