### ISSUE TITLE
[Feature] Support full set of joins

### ISSUE THREAD

**Issue by sdanyliv** [linq2db/linq2db#685]
As from this documentation: https://www.w3schools.com/sql/sql_join.asp
There are four main types of joins:

Join Type| linq2db||
----|----|--
**INNER JOIN**|Fully|Fully supported
**LEFT JOIN**|Fully|Fully supported
**RIGHT JOIN**||There is workaround: swap queries and make left join :)
**FULL OUTER JOIN**||No simple way to define

I propose to support something like this (like with DefaultIfEmpty):
```cs
var q = from t1 in Table1
        from t2 in Table2.Where(t1.Key == t2.Key || t1.Key2 != t2.Key2).FullOuterJoin()
        select new {t1, t2};
```
Or simplified syntax
```cs
var q = from t1 in Table1
        from t2 in Table2.FullOuterJoin(t1.Key == t2.Key && t1.Key2 == t2.Key2)
        select new {t1, t2};
```
I assume that using this syntax we can not replicate it in linq2objects so it's why i have create this issue.

Let's discuss which syntax will be more useful, and maybe you have other ideas.

**Comment by MaceWindu** [comment]
There is also cross/carthesian join

Should this feature cover only joins using linq or joins, defined by AssociationAttribute?

**Comment by jogibear9988** [comment]
Look at https://github.com/fsateler/MoreLINQ/tree/master/MoreLinq they have a few additional operators: https://github.com/fsateler/MoreLINQ/blob/master/MoreLinq/FullGroupJoin.cs

**Comment by sdanyliv** [comment]
@MaceWindu, let's focus on these four. Cross and Cartesian joins already supported.

**cross**
```cs
var q = from t1 in table1
        from t2 in table3
```
**cartesian**
```cs
var q = from t1 in table1
        from t2 in table3
        where t1.Field1 == 1 &&
             t2.Field2 < 10 
```
If you have idea how it may be useful for AssociationAttribute, maybe, but i think left and inner join is enough for associations.

**Comment by sdanyliv** [comment]
@jogibear9988, yes i have found several libraries that supports this functionality for linq to objects, and we can use this code for comparing results. But i'm thinking about declarative defining of SQL join.

**Comment by sdanyliv** [comment]
Implemented and merged.
