### ISSUE TITLE
Is there a way to include Row Count & Filtered Count in Query Result? 

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#687]
I'm looking for a way, so I need only one Query to Database to include the RowCount & and the current Filtered Count in My Result.

My Current Code looks like this:

Wrapper DTO:

    public class CombinedDTOwithCount<T> : IInterlinqDTO where T : BasicDTOwithoutID
    {
        public virtual T DTO { get; set; }

        public virtual long Count { get; set; }

        public virtual long FilteredCount { get; set; }
    }

my query Code looks like this:

        public IQueryable<CombinedDTOwithCount<X>> QueryWithCount<X>() where X : BasicDTOwithoutID
        {
            var qry = from x in DataConnection.GetTable<X>()
                      select new CombinedDTOwithCount<X> {DTO = x, Count = DataConnection.GetTable<X>().Count(), };
            return qry;
        }

But so I only get the Full Count. Now I'm looking that the following:

                var r1 = s.QueryWithCount<WmsLoadCarrierDTO>().Where(x => x.DTO.AA == "A");

Will also include the FullCount (wich works), but how can I include the Count with the Filter Applied?

**Comment by sdanyliv** [comment]
I do not see easy way, it is more related to #331 .
Ideally your have to extract SearchCondition and correct count expression.

**Comment by sdanyliv** [comment]
Closing for now. Will reopen if needed.

**Comment by Franki1986** [comment]
Is there any change to this?
I would also like to do this for the wcf linqservice.
Basically select a filtered table and also select the count of rows. If you use this over the sercice context you have not only the double roundtrip to db but also to your server
