### ISSUE TITLE
BulkCopyOptions Documentation

### ISSUE THREAD

**Issue by dvladimirovich** [linq2db/linq2db#688]
Hi, I'm using your great project and I want to know where I could read about BulkCopyOptions properties? It's not obvious for me what are they for.
Also I need to know colud I insert objects, which has Identity column but its value will be automatically set by SQL Server?

**Comment by sdanyliv** [comment]
Yes we have support for identities.
Check `BulkCopyOptions.RetrieveSequence`

**Comment by dvladimirovich** [comment]
There is no such option! Where did you take it from?

**Comment by MaceWindu** [comment]
`BulkCopyOptions.RetrieveSequence` was added in latest version (1.8)

**Comment by ili** [comment]
`BulkCopyOptions.RetrieveSequence` now supported only for Oracle.
It looks like we should investigate it

**Comment by dvladimirovich** [comment]
I've used simple BulkCopy without any options and it works fine and shame on me it was my mistake because I've forgotten to set identity seed on primary key column in my database...

**Comment by ili** [comment]
@dvladimirovich that's great!

but in any way we do need test for BulkCopy with identity, now most tests are done for tables without identity :(

**Comment by MaceWindu** [comment]
Documentation tracked by #618 and was improved a bit for BulkCopy lately
