### ISSUE TITLE
Associations with delete and update operations

### ISSUE THREAD

**Issue by dvladimirovich** [linq2db/linq2db#689]
Hi, could you please help me if it is correct to use foreign key table in where condition. For instance:
`db.Notifications.Where(n => n.ProductStore.UserId == command.UserId).Set(n => n.Walert, command.WalertToSet);`
Where Notifications table has a ProductStoreId foreign key and ProductStore object as property generated by Linq2Db model generator.

**Comment by sdanyliv** [comment]
@dvladimirovich, it should work. Why not?

**Comment by dvladimirovich** [comment]
Oh, yeah its my mistake. BTW, its great, thank you!
