### ISSUE TITLE
What is FreeTextTable features for?

### ISSUE THREAD

**Issue by dvladimirovich** [linq2db/linq2db#691]
I'm using T4 models generator and I can't understand what purposes resolve this class and methods?
```
#region FreeTextTable

	public class FreeTextKey<T>
	{
		public T   Key;
		public int Rank;
	}
	[FreeTextTableExpression]
	public ITable<FreeTextKey<TKey>> FreeTextTable<TTable,TKey>(string field, string text)
	{
		return this.GetTable<FreeTextKey<TKey>>(
			this,
			((MethodInfo)(MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(TTable), typeof(TKey)),
			field,
			text);
	}
		[FreeTextTableExpression]
	public ITable<FreeTextKey<TKey>> FreeTextTable<TTable,TKey>(Expression<Func<TTable,string>> fieldSelector, string text)
	{
		return this.GetTable<FreeTextKey<TKey>>(
			this,
			((MethodInfo)(MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(TTable), typeof(TKey)),
			fieldSelector,
			text);
	}
#endregion
```
BTW, guys you have great project and I really appreciate your contribution, but I think it would be good to improve the documentation and people won't ask such stupid questions as me=)

**Comment by MaceWindu** [comment]
Those are methods to work with full text search queries in SQL Server.
For example check those tests: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/TableFunctionTests.cs#L161

**Comment by dvladimirovich** [comment]
Ok, thanks!

**Comment by MaceWindu** [comment]
It whould be nice, if T4 generator will add descriptive comments to methods like this

**Comment by MaceWindu** [comment]
Closing answered/non-actionable issues. Feel free to reopen/continue discussion if it wasn't anwsered.
