### ISSUE TITLE
ObjectDisposedException after update to v1.8.0

### ISSUE THREAD

**Issue by dvladimirovich** [linq2db/linq2db#692]
I've been using v1.7.6 and my context calling looks like:
```
using (var db = new DataContext(context.ProviderName, context.ConnectionString))
{
        IEnumerable<someType> result = db.Where(<some search lambda>).AsEnumerable();
        return result;
}
```
After update to v1.8.0 I have an exception thrown:

> System.ObjectDisposedException
> IDataContext is disposed Object name: 'DataConnection'.
> 
> System.ObjectDisposedException: IDataContext is disposed
> Object name: 'DataConnection'.
>    at LinqToDB.Data.DataConnection.ThrowOnDisposed()
>    at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.SetQuery(IQueryContext queryContext)
>    at LinqToDB.Linq.Query`1.SetCommand(IDataContext dataContext, Expression expr, Object[] parameters, Int32 idx, Boolean clearQueryHints)
>    at LinqToDB.Linq.Query`1.<RunQuery>d__11.MoveNext()
>    at LinqToDB.Linq.Query`1.<Map>d__69.MoveNext()
>    at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at System.Linq.GroupedEnumerable`3.GetEnumerator()
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by jogibear9988** [comment]
Try ToList, ToArray, ...
If you call AsEnumerable, Query will be executed outside of the using, wich will not work in 1.8 any more! (a bug was fixed wich could lead to memory leaks!)

**Comment by dvladimirovich** [comment]
Hmm... it's strange, but what about Deferred execution? Thus, people who has been using this approach must change their return types an behaviour?

**Comment by MaceWindu** [comment]
This change was introduced to fix issue when connection to database created after data context disposal. In that situation connection wasn't returned to connection pool after use, which lead to connection pool exhaustion.
If you need to defer your query execution, you should also defer disposal of data context.

**Comment by dvladimirovich** [comment]
I understand, thanks!

**Comment by jogibear9988** [comment]
close?

**Comment by ili** [comment]
@dvladimirovich @MaceWindu  is absolutely right, this is "good" exception, it helps to avoid wrong usage and connection leaks.

According to [documentation](https://msdn.microsoft.com/en-us/library/bb335435(v=vs.110).aspx) `AsEnumerable` do nothing, so query is not executed (the same is for other providers, [for ex.](https://stackoverflow.com/questions/3389855/am-i-misunderstanding-linq-to-sql-asenumerable)

Closing, marking as documentation because we should write that it is anti-pattern.

**Comment by dvladimirovich** [comment]
Am I right that using `IQueryable<>` is also bad practice with your library?

**Comment by jogibear9988** [comment]
No, it's bad practice to use a Iqueryable outside of a using wich created the Iqueryable.
