### ISSUE TITLE
SqlCe schema provider PK duplications causes error on FK generation

### ISSUE THREAD

**Issue by detoxhby** [linq2db/linq2db#695]
Caused by recent change 88c0e54b4dcf95bd5c3951bbc2834568300cb252

These changes made it possible to retrieve FKs correctly but the PKs are duplicated. It is a really old piece of code and was no problem as previously the FKs were just an empty list.

Inside `SchemaProviderBase.GetSchema()` FKs are joined onto PKs and later processed, but PKs contain normal index columns as well as real PKs...and thus causes error on otherColumn selection as `.Single()` fails on multiple results:
`otherColumn = (from c in otherTable.Columns where c.ColumnName == fk.OtherColumn select c).Single();`

This is a huge problem for us as we use SqlCe for integration testing and now the whole pipeline is broken.

**Comment by ili** [comment]
We'll fix it, and publish 1.8.1 in few days.

**Comment by ili** [comment]
@detoxhby I'v failed to reproduce an issue on our test database, for this two tables everything is OK:

```sql
CREATE TABLE Person
(
	PersonID   int          NOT NULL IDENTITY(1,1) CONSTRAINT PK_Person PRIMARY KEY,
	FirstName  nvarchar(50) NOT NULL,
	LastName   nvarchar(50) NOT NULL,
	MiddleName nvarchar(50)     NULL,
	Gender     nchar(1)     NOT NULL
)
GO

-- Doctor Table Extension
CREATE TABLE Doctor
(
	PersonID int          NOT NULL
		CONSTRAINT PK_Doctor        PRIMARY KEY
		CONSTRAINT FK_Doctor_Person --FOREIGN KEY
			REFERENCES Person ([PersonID])
			ON UPDATE CASCADE
			ON DELETE CASCADE,
	Taxonomy nvarchar(50) NOT NULL
)
GO
```
Can you please provide me failing schema?

**Comment by detoxhby** [comment]
Just add an index on any non-PK column and the schemaProvider will read it as PK.

(ex. `CREATE UNIQUE INDEX IX_Firstname ON Person (Firstname)`)

**Comment by ili** [comment]
@detoxhby thanks!
