### ISSUE TITLE
[Suggestion] Create notification list for users who's willing to test new versions on real-life projects before release gets finalised

### ISSUE THREAD

**Issue by detoxhby** [linq2db/linq2db#709]
I would especially volunteer to be on a list to get notification before any new release to be able to test it **fully** out on our complex projects and report any issues. (to help prevent situations like #708)

We could call it **Release Candidate** for easier understanding.

What do you guys think? (@ili @sdanyliv)

**Comment by ili** [comment]
it would be great.
In general all master builds are published to MyGet so it can be easily managed. Before each publishing we can create PR from `master` to `release` (all releases are done from `release` brunch). At this moment it would be just needed to update latest package from MyGet & run tests

**Comment by detoxhby** [comment]
Sounds great! Would the notification occour with linking in the PR to a predefined internal "RC" issue/thread?

**Comment by ili** [comment]
If you "star" us you will receive notifications, if i'm not mistaken

**Comment by detoxhby** [comment]
I have the star on this project for a long time now. The fact is that the default setting for watch is "Not watching" so only get notification where I'm participating or tagged. (which is fine)

This is why an issue/PR with ppl tagged in would be nice.

**Comment by ili** [comment]
Tagged with "ppl"? Not clear how it is...

**Comment by sdanyliv** [comment]
I think it means pople. Like this

@detoxhby, @ili. Preparing for release.

**Comment by ili** [comment]
I see!
I think it can be managed via [teams](https://github.com/blog/1121-introducing-team-mentions)

**Comment by ili** [comment]
@detoxhby lets make a test, i'v created new team and invited you, please accept and i'll try to notify you via team mention :)

**Comment by detoxhby** [comment]
@ili sorry, bad habit: ppl = people

Accepted the invite, thanks! You may create a section called "contribution" in readme to help others join to this proposal.

**Comment by ili** [comment]
@detoxhby yes... contribution guide is in my plan

**Comment by ili** [comment]
group created, closing for now
we'll introduce this practice

**Comment by jogibear9988** [comment]
you can include me too! i'll test on our real live system before each release (but i need a myget/nuget package, i can not change all our projects to use a custom compiled dll)
