### ISSUE TITLE
New ColumnAttribute "Allocate" Property 

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#711]
Could a public property named "Allocate" (and a "HasAllocate" function) be added to the [ColumnAttribute](https://github.com/linq2db/linq2db/blob/master/Source/Mapping/ColumnAttribute.cs) attribute class to be able to craete more accurate "Create Table" sql scripts for VARCHAR data types on DB2 iSeries databases.

See below:
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_61/rzajq/vardatatypes.htm

**Comment by ili** [comment]
Do you know if other databases do support `ALLOCATE` or any analog?

**Comment by tb-mtg** [comment]
Not sure

**Comment by RoyC-Retail-Assist** [comment]
If it is something specific to the iSeries DB2 it could be done as an additional attribute in the ISeries provider.

**Comment by ili** [comment]
Without any additional info I will suggest to implement this behavior in iSeries provider

**Comment by tb-mtg** [comment]
Roy has a good point. I guess an additional attribute is the way to go.
