### ISSUE TITLE
PostgreSQL datareader requests table schema for each column

### ISSUE THREAD

**Issue by breakingthings** [linq2db/linq2db#715]
Hi,

Something has gone wrong with 1.8.2 IsDBNullAllowed function in DataProviderBase.cs called extensively for each column which causes lots of schema querys to database and slows system down to a crawl.

**Comment by MaceWindu** [comment]
I assume you use Npgsql 3.1.9+? Could you try to downgrade to Npgsql 3.1.8 temporary and report wether it helped or not?

**Comment by breakingthings** [comment]
No - the problem is not in npgsql. I did some debugging and the problem is not with npgsql. Npgsql is 2.3.2 - no problems with linq2db version 1.8.0 - the bug appears with 1.8.2. I currently don't have time to debug it properly but it should be easily reproducible - PostgreSQL query tracing shows a lot of  querys like this that are executed when IsDbNullAllowed is called:


SELECT
	     typ.oid AS typoid, nspname, relname, attname, typname, attrelid, attnum, atttypmod, attnotnull,
	     CASE WHEN atthasdef THEN (SELECT pg_get_expr(adbin, cls.oid) FROM pg_attrdef WHERE adrelid = cls.oid AND adnum = attr.attnum) ELSE NULL END AS default,
	     CASE WHEN col.is_updatable = 'YES' THEN true ELSE false END AS is_updatable,
	     EXISTS (
	       SELECT * FROM pg_index
	       WHERE pg_index.indrelid = cls.oid AND
	             pg_index.indisprimary AND
	             attnum = ANY (pg_index.indkey)
	     ) AS isprimarykey,
	     EXISTS (
	       SELECT * FROM pg_index
	       WHERE pg_index.indrelid = cls.oid AND
	             pg_index.indisunique AND
	             attnum = ANY (pg_index.indkey)
	     ) AS isunique
	FROM pg_attribute AS attr
	JOIN pg_type AS typ ON attr.atttypid = typ.oid
	JOIN pg_class AS cls ON cls.oid = attr.attrelid
	JOIN pg_namespace AS ns ON ns.oid = cls.relnamespace
	LEFT OUTER JOIN information_schema.columns AS col ON col.table_schema = nspname AND
	     col.table_name = relname AND
	     col.column_name = attname
	WHERE
	     atttypid <> 0 AND
	     relkind IN ('r', 'v', 'm') AND
	     NOT attisdropped AND
	     nspname NOT IN ('pg_catalog', 'information_schema') AND
	     attnum > 0 AND
	     ((attr.attrelid=238787 AND attr.attnum=2) OR (attr.attrelid=238787 AND attr.attnum=5) OR (attr.attrelid=238787 AND attr.attnum=34) OR (attr.attrelid=238787 AND attr.attnum=10) OR (attr.attrelid=238787 AND attr.attnum=22) OR (attr.attrelid=238787 AND attr.attnum=30) OR (attr.attrelid=238787 AND attr.attnum=31) OR (attr.attrelid=238787 AND attr.attnum=19) OR (attr.attrelid=238787 AND attr.attnum=20) OR (attr.attrelid=238787 AND attr.attnum=23) OR (attr.attrelid=238787 AND attr.attnum=24) OR (attr.attrelid=238787 AND attr.attnum=25) OR (attr.attrelid=238787 AND attr.attnum=27) OR (attr.attrelid=238787 AND attr.attnum=33) OR (attr.attrelid=238787 AND attr.attnum=39) OR (attr.attrelid=238787 AND attr.attnum=37) OR (attr.attrelid=238787 AND attr.attnum=35) OR (attr.attrelid=238787 AND attr.attnum=36) OR (attr.attrelid=238787 AND attr.attnum=38) OR (attr.attrelid=238787 AND attr.attnum=40) OR (attr.attrelid=238787 AND attr.attnum=41) OR (attr.attrelid=238787 AND attr.attnum=18) OR (attr.attrelid=238787 AND attr.attnum=32) OR (attr.attrelid=238787 AND attr.attnum=28) OR (attr.attrelid=238787 AND attr.attnum=16) OR (attr.attrelid=238787 AND attr.attnum=45) OR (attr.attrelid=238787 AND attr.attnum=42) OR (attr.attrelid=238787 AND attr.attnum=43) OR (attr.attrelid=238787 AND attr.attnum=44) OR (attr.attrelid=238787 AND attr.attnum=15) OR (attr.attrelid=238787 AND attr.attnum=17) OR (attr.attrelid=238787 AND attr.attnum=46) OR (attr.attrelid=238787 AND attr.attnum=47) OR (attr.attrelid=238787 AND attr.attnum=48) OR (attr.attrelid=238787 AND attr.attnum=49) OR (attr.attrelid=238787 AND attr.attnum=51) OR (attr.attrelid=238787 AND attr.attnum=11) OR (attr.attrelid=238787 AND attr.attnum=3) OR (attr.attrelid=238787 AND attr.attnum=4) OR (attr.attrelid=238787 AND attr.attnum=1) OR (attr.attrelid=238787 AND attr.attnum=6) OR (attr.attrelid=238787 AND attr.attnum=50) OR (attr.attrelid=238585 AND attr.attnum=5) OR (attr.attrelid=238585 AND attr.attnum=6) OR (attr.attrelid=238585 AND attr.attnum=7) OR (attr.attrelid=238585 AND attr.attnum=8) OR (attr.attrelid=238585 AND attr.attnum=9) OR (attr.attrelid=238585 AND attr.attnum=10) OR (attr.attrelid=238585 AND attr.attnum=11) OR (attr.attrelid=238585 AND attr.attnum=12) OR (attr.attrelid=238585 AND attr.attnum=34) OR (attr.attrelid=238585 AND attr.attnum=36) OR (attr.attrelid=238585 AND attr.attnum=13) OR (attr.attrelid=238585 AND attr.attnum=38) OR (attr.attrelid=238585 AND attr.attnum=14) OR (attr.attrelid=238585 AND attr.attnum=35) OR (attr.attrelid=238585 AND attr.attnum=37) OR (attr.attrelid=238585 AND attr.attnum=15) OR (attr.attrelid=238585 AND attr.attnum=16) OR (attr.attrelid=238585 AND attr.attnum=20) OR (attr.attrelid=238585 AND attr.attnum=17) OR (attr.attrelid=238585 AND attr.attnum=18) OR (attr.attrelid=238585 AND attr.attnum=19) OR (attr.attrelid=238585 AND attr.attnum=22) OR (attr.attrelid=238585 AND attr.attnum=21) OR (attr.attrelid=238585 AND attr.attnum=27) OR (attr.attrelid=238585 AND attr.attnum=28) OR (attr.attrelid=238585 AND attr.attnum=29) OR (attr.attrelid=238585 AND attr.attnum=30) OR (attr.attrelid=238585 AND attr.attnum=23) OR (attr.attrelid=238585 AND attr.attnum=24) OR (attr.attrelid=238585 AND attr.attnum=26) OR (attr.attrelid=238585 AND attr.attnum=43) OR (attr.attrelid=238585 AND attr.attnum=31) OR (attr.attrelid=238585 AND attr.attnum=32) OR (attr.attrelid=238585 AND attr.attnum=33) OR (attr.attrelid=238585 AND attr.attnum=39) OR (attr.attrelid=238585 AND attr.attnum=40) OR (attr.attrelid=238585 AND attr.attnum=41) OR (attr.attrelid=238585 AND attr.attnum=2) OR (attr.attrelid=238585 AND attr.attnum=3) OR (attr.attrelid=238585 AND attr.attnum=1) OR (attr.attrelid=238585 AND attr.attnum=4) OR (attr.attrelid=238585 AND attr.attnum=42) OR (attr.attrelid=239044 AND attr.attnum=8) OR (attr.attrelid=239044 AND attr.attnum=17) OR (attr.attrelid=239044 AND attr.attnum=18) OR (attr.attrelid=239044 AND attr.attnum=22) OR (attr.attrelid=239044 AND attr.attnum=4) OR (attr.attrelid=239044 AND attr.attnum=3) OR (attr.attrelid=239044 AND attr.attnum=2) OR (attr.attrelid=239044 AND attr.attnum=9) OR (attr.attrelid=239044 AND attr.attnum=12) OR (attr.attrelid=239044 AND attr.attnum=11) OR (attr.attrelid=239044 AND attr.attnum=13) OR (attr.attrelid=239044 AND attr.attnum=10) OR (attr.attrelid=239044 AND attr.attnum=14) OR (attr.attrelid=239044 AND attr.attnum=23) OR (attr.attrelid=239044 AND attr.attnum=15) OR (attr.attrelid=239044 AND attr.attnum=16) OR (attr.attrelid=239044 AND attr.attnum=19) OR (attr.attrelid=239044 AND attr.attnum=20) OR (attr.attrelid=239044 AND attr.attnum=21) OR (attr.attrelid=239044 AND attr.attnum=5) OR (attr.attrelid=239044 AND attr.attnum=6) OR (attr.attrelid=239044 AND attr.attnum=1) OR (attr.attrelid=239044 AND attr.attnum=7) OR (attr.attrelid=239044 AND attr.attnum=24) OR (attr.attrelid=239044 AND attr.attnum=8) OR (attr.attrelid=239044 AND attr.attnum=17) OR (attr.attrelid=239044 AND attr.attnum=18) OR (attr.attrelid=239044 AND attr.attnum=22) OR (attr.attrelid=239044 AND attr.attnum=4) OR (attr.attrelid=239044 AND attr.attnum=3) OR (attr.attrelid=239044 AND attr.attnum=2) OR (attr.attrelid=239044 AND attr.attnum=9) OR (attr.attrelid=239044 AND attr.attnum=12) OR (attr.attrelid=239044 AND attr.attnum=11) OR (attr.attrelid=239044 AND attr.attnum=13) OR (attr.attrelid=239044 AND attr.attnum=10) OR (attr.attrelid=239044 AND attr.attnum=14) OR (attr.attrelid=239044 AND attr.attnum=23) OR (attr.attrelid=239044 AND attr.attnum=15) OR (attr.attrelid=239044 AND attr.attnum=16) OR (attr.attrelid=239044 AND attr.attnum=19) OR (attr.attrelid=239044 AND attr.attnum=20) OR (attr.attrelid=239044 AND attr.attnum=21) OR (attr.attrelid=239044 AND attr.attnum=5) OR (attr.attrelid=239044 AND attr.attnum=6) OR (attr.attrelid=239044 AND attr.attnum=1) OR (attr.attrelid=239044 AND attr.attnum=7) OR (attr.attrelid=239044 AND attr.attnum=24) OR (attr.attrelid=239044 AND attr.attnum=8) OR (attr.attrelid=239044 AND attr.attnum=17) OR (attr.attrelid=239044 AND attr.attnum=18) OR (attr.attrelid=239044 AND attr.attnum=22) OR (attr.attrelid=239044 AND attr.attnum=4) OR (attr.attrelid=239044 AND attr.attnum=3) OR (attr.attrelid=239044 AND attr.attnum=2) OR (attr.attrelid=239044 AND attr.attnum=9) OR (attr.attrelid=239044 AND attr.attnum=12) OR (attr.attrelid=239044 AND attr.attnum=11) OR (attr.attrelid=239044 AND attr.attnum=13) OR (attr.attrelid=239044 AND attr.attnum=10) OR (attr.attrelid=239044 AND attr.attnum=14) OR (attr.attrelid=239044 AND attr.attnum=23) OR (attr.attrelid=239044 AND attr.attnum=15) OR (attr.attrelid=239044 AND attr.attnum=16) OR (attr.attrelid=239044 AND attr.attnum=19) OR (attr.attrelid=239044 AND attr.attnum=20) OR (attr.attrelid=239044 AND attr.attnum=21) OR (attr.attrelid=239044 AND attr.attnum=5) OR (attr.attrelid=239044 AND attr.attnum=6) OR (attr.attrelid=239044 AND attr.attnum=1) OR (attr.attrelid=239044 AND attr.attnum=7) OR (attr.attrelid=239044 AND attr.attnum=24) OR (attr.attrelid=238915 AND attr.attnum=12) OR (attr.attrelid=238915 AND attr.attnum=5) OR (attr.attrelid=238915 AND attr.attnum=2) OR (attr.attrelid=238915 AND attr.attnum=4) OR (attr.attrelid=238915 AND attr.attnum=13) OR (attr.attrelid=238915 AND attr.attnum=3) OR (attr.attrelid=238915 AND attr.attnum=11) OR (attr.attrelid=238915 AND attr.attnum=6) OR (attr.attrelid=238915 AND attr.attnum=14) OR (attr.attrelid=238915 AND attr.attnum=15) OR (attr.attrelid=238915 AND attr.attnum=16) OR (attr.attrelid=238915 AND attr.attnum=7) OR (attr.attrelid=238915 AND attr.attnum=8) OR (attr.attrelid=238915 AND attr.attnum=1) OR (attr.attrelid=238915 AND attr.attnum=9) OR (attr.attrelid=238915 AND attr.attnum=17) OR (attr.attrelid=238915 AND attr.attnum=12) OR (attr.attrelid=238915 AND attr.attnum=5) OR (attr.attrelid=238915 AND attr.attnum=2) OR (attr.attrelid=238915 AND attr.attnum=4) OR (attr.attrelid=238915 AND attr.attnum=13) OR (attr.attrelid=238915 AND attr.attnum=3) OR (attr.attrelid=238915 AND attr.attnum=11) OR (attr.attrelid=238915 AND attr.attnum=6) OR (attr.attrelid=238915 AND attr.attnum=14) OR (attr.attrelid=238915 AND attr.attnum=15) OR (attr.attrelid=238915 AND attr.attnum=16) OR (attr.attrelid=238915 AND attr.attnum=7) OR (attr.attrelid=238915 AND attr.attnum=8) OR (attr.attrelid=238915 AND attr.attnum=1) OR (attr.attrelid=238915 AND attr.attnum=9) OR (attr.attrelid=238915 AND attr.attnum=17) OR (attr.attrelid=239125 AND attr.attnum=2) OR (attr.attrelid=239125 AND attr.attnum=3) OR (attr.attrelid=239125 AND attr.attnum=4) OR (attr.attrelid=239125 AND attr.attnum=8) OR (attr.attrelid=239125 AND attr.attnum=14) OR (attr.attrelid=239125 AND attr.attnum=9) OR (attr.attrelid=239125 AND attr.attnum=10) OR (attr.attrelid=239125 AND attr.attnum=11) OR (attr.attrelid=239125 AND attr.attnum=12) OR (attr.attrelid=239125 AND attr.attnum=13) OR (attr.attrelid=239125 AND attr.attnum=16) OR (attr.attrelid=239125 AND attr.attnum=15) OR (attr.attrelid=239125 AND attr.attnum=17) OR (attr.attrelid=239125 AND attr.attnum=19) OR (attr.attrelid=239125 AND attr.attnum=20) OR (attr.attrelid=239125 AND attr.attnum=21) OR (attr.attrelid=239125 AND attr.attnum=5) OR (attr.attrelid=239125 AND attr.attnum=6) OR (attr.attrelid=239125 AND attr.attnum=1) OR (attr.attrelid=239125 AND attr.attnum=7) OR (attr.attrelid=239125 AND attr.attnum=18) OR (attr.attrelid=238915 AND attr.attnum=12) OR (attr.attrelid=238915 AND attr.attnum=5) OR (attr.attrelid=238915 AND attr.attnum=2) OR (attr.attrelid=238915 AND attr.attnum=4) OR (attr.attrelid=238915 AND attr.attnum=13) OR (attr.attrelid=238915 AND attr.attnum=3) OR (attr.attrelid=238915 AND attr.attnum=11) OR (attr.attrelid=238915 AND attr.attnum=6) OR (attr.attrelid=238915 AND attr.attnum=14) OR (attr.attrelid=238915 AND attr.attnum=15) OR (attr.attrelid=238915 AND attr.attnum=16) OR (attr.attrelid=238915 AND attr.attnum=7) OR (attr.attrelid=238915 AND attr.attnum=8) OR (attr.attrelid=238915 AND attr.attnum=1) OR (attr.attrelid=238915 AND attr.attnum=9) OR (attr.attrelid=238915 AND attr.attnum=17) OR (attr.attrelid=238915 AND attr.attnum=12) OR (attr.attrelid=238915 AND attr.attnum=5) OR (attr.attrelid=238915 AND attr.attnum=2) OR (attr.attrelid=238915 AND attr.attnum=4) OR (attr.attrelid=238915 AND attr.attnum=13) OR (attr.attrelid=238915 AND attr.attnum=3) OR (attr.attrelid=238915 AND attr.attnum=11) OR (attr.attrelid=238915 AND attr.attnum=6) OR (attr.attrelid=238915 AND attr.attnum=14) OR (attr.attrelid=238915 AND attr.attnum=15) OR (attr.attrelid=238915 AND attr.attnum=16) OR (attr.attrelid=238915 AND attr.attnum=7) OR (attr.attrelid=238915 AND attr.attnum=8) OR (attr.attrelid=238915 AND attr.attnum=1) OR (attr.attrelid=238915 AND attr.attnum=9) OR (attr.attrelid=238915 AND attr.attnum=17))
	ORDER BY attnum

**Comment by MaceWindu** [comment]
I didn't said it is npgsql issue. In last release we included change, that is used for npgsql versions 3.1.9+ and I'm afraid, it doesn't work well

**Comment by ili** [comment]
In general it should not have any effect for versions lesser then 3.1.9. `CommandBehaviour` does not changed, `IsDbNullAllowed` used to be called for each column always.

**Comment by breakingthings** [comment]
> I didn't said it is npgsql issue. In last release we included change, that is used for npgsql versions 3.1.9+ and I'm afraid, it doesn't work well.

Oh sorry - I read it wrong - yes I'm using npgsql 3.1.9+. And with npgsql 3.2.3 with some columns I get Error and it seems that not always is "IsDbNull" key available and boolean cast throws exception. Thanks for the quick reaction!

**Comment by ili** [comment]
OK we'll look forward to test & fix it!

**Comment by ili** [comment]
The only solution for now I see is to switch off getting table schema from server via not using  `CommandBehavior.KeyInfo`

**Comment by jogibear9988** [comment]
Why do we need to get the schema from server? I think information we need to build our queries comes from our mapping?

**Comment by sdanyliv** [comment]
@igor-tkachev, it is really needed? Also foun that Oracle provider also has issue with this.

**Comment by ili** [comment]
The original idea is build more efficient mapper, for ex, if column can be `DbNull` mapping expression would be like:
```cs
if (dataReader.IsDbNull(0))
    myObject.MyField = null; // or other value, representing null for not nullable types
else
   myObjecy.MyField = dataReader.GetInt32(0);
```

So if column could not be `DbNull` we can avoid checking for null

By the fact I think we should switch this behavior off for some providers, because running additional queries is not cool.

@sdanyliv Oracle runs additional queries too?

**Comment by sdanyliv** [comment]
@ili, no, it just returns imcorrect value.

**Comment by jogibear9988** [comment]
But isn't it the same when i say in mapping that a column is nullable?
