### ISSUE TITLE
Multiple OrderBys do not work 

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#72]
same issue as on bltoolkit:

https://github.com/igor-tkachev/bltoolkit/issues/309

**Comment by jogibear9988** [comment]
Any fix for this?

**Comment by jogibear9988** [comment]
Will you accept a Patch with a Setting for this?

**Comment by igor-tkachev** [comment]
Can you provide an example?

**Comment by jogibear9988** [comment]
the example is in the bltoolkit issue

**Comment by jogibear9988** [comment]
it's because thenby could not be used!

**Comment by ili** [comment]
@jogibear9988 you can make your own extension methods https://github.com/igor-tkachev/bltoolkit/pull/338

**Comment by jogibear9988** [comment]
do you think it's better that everyone declares those methods? would it not be better to include them?
