### ISSUE TITLE
Bug with Implicit and Explicit convert

### ISSUE THREAD

**Issue by sdanyliv** [linq2db/linq2db#722]
Linq2db generates wrong query with Convert for SQL Server and possible for other databases.

### Steps to reproduce
The following test crashes on server side with error: 
**`Arithmetic overflow error converting real to data type numeric`**
```c#
[Test, NorthwindDataContext]
public void Test2(string context)
{
	using (var db = new NorthwindDB(context))
	{
		var actual = (from od in db.OrderDetail
			select
			Sql.AsSql(od.UnitPrice * od.Quantity * (decimal) (1 - od.Discount))).ToArray();

		var expected = (from od in db.OrderDetail
			select
			od.UnitPrice * od.Quantity * (decimal) (1 - od.Discount)).ToArray();

		AreEqual(expected, actual);
	}
}
```
Wrong SQL is here:
```sql
-- Northwind SqlServer.2012
SELECT
	([t1].[UnitPrice] * Convert(Decimal(5,0), [t1].[Quantity])) * Convert(Decimal(7,7), 1 - [t1].[Discount]) as [c1]
FROM
	[dbo].[Order Details] [t1]
```

### Environment details
linq2db version: *1.8.2*  
Database Server: *SQL Server 2012*  
Database Provider: *SqlClient*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.5*

**Comment by sdanyliv** [comment]
Looks like `Convert(Decimal(7,7),` is wrong

**Comment by ili** [comment]
That used to because of SQL `real` should be represented as `double` in c#, i'v changed column definition

But! test would fail even if we:
```sql
SELECT
	([t1].[UnitPrice] * Convert(Decimal(5,0), [t1].[Quantity])) * Convert(Decimal(38,16), 1 - [t1].[Discount]) as [c1]
FROM
	[dbo].[Order Details] [t1]
```

**Comment by sdanyliv** [comment]
Best approach if we do not use any convertations here.

**Comment by sdanyliv** [comment]
If we can not omit convertations automatically, maybe we can introduce new helper function Sql.NoConvert that removes conversions from target expression.

**Comment by ili** [comment]
May be smth. like "RemoveConvert(...)" extension method for linq query...
It is not the best approach but I can't imagine other for now... 

In anyway `decimal(7, 7)` is wrong, I'v prepared #724 to fix id

**Comment by sdanyliv** [comment]
Already fixed. `Sql.NoConvert` added in #870
