### ISSUE TITLE
CreateTable vs Oracle issues

### ISSUE THREAD

**Issue by Lexey** [linq2db/linq2db#723]
There are two issues with the *CreateTable<T>* method.
1) The 4th parameter name *ownerName* is confusing. It should be named *schemaName*.
2) When an explicit schema name is set via the FluentMappingBuilder or via the ownerName parameter it is being respected only for the CREATE TABLE statement. But related CREATE SEQUENCE and CREATE TRIGGER statements have no schema specifications.

A table definition:
```c#
    [Table("FactorList")]
    public class FactorList
    {
        /// <summary>Id</summary>
        [Column, PrimaryKey, Identity, NotNull]
        public int Id { get; set; }
        /// <summary>Name</summary>
        [Column(Length = 255), Nullable]
        public string Name { get; set; }

        #region Associations
        [Association(ThisKey = nameof(Id), OtherKey = nameof(FactorListFactor.FactorListId), CanBeNull = true
            , IsBackReference = true)]
        [NotForeignKey]
        public IEnumerable<FactorListFactor> Factors { get; set; }
        #endregion Associations
    }
```

The create call (1st version):
```c#
MappingSchema.GetFluentMappingBuilder().Entity<FactorList>().HasSchemaName(schemaName);
CreateTable<FactorList>();
```

The create call (2nd version):
```c#
CreateTable<FactorList>(null, null, schemaName);
```

Resulting SQL:

```sql
CREATE TABLE MySchema.FactorList
(
	Id   Int            NOT NULL,
	Name VarChar2(255)      NULL,

	CONSTRAINT PK_FactorList PRIMARY KEY (Id)
)

CREATE SEQUENCE SIDENTITY_FactorList

CREATE OR REPLACE TRIGGER  TIDENTITY_FactorList
BEFORE INSERT ON FactorList FOR EACH ROW
BEGIN
	SELECT SIDENTITY_FactorList.NEXTVAL INTO :NEW.Id FROM dual;
END;
```

### Environment details
linq2db version: *1.8.2*  
Database Server: *Oracle 11g*
Database Provider: *Oracle.Managed*  
Operating system: *Windows 7 SP1*  
Framework version: *.NET Framework 4.6.2*

**Comment by ili** [comment]
@Lexey PR would be great! )))

**Comment by Lexey** [comment]
:) May be later. At this moment I have no time to dig into the 2nd issue.
