### ISSUE TITLE
How to use built in aggregation functions

### ISSUE THREAD

**Issue by edokan** [linq2db/linq2db#73]
I use Linq2Access. I need to use `StDev` in a query. I've tried `Sql.Expression` and `Sql.Function` with no success. How can I make following query work?

```
from c in db.Client
group c by c
into g
select new
{
    T1 = g.Sum(cc => cc.Age),
    T2 = g.StDev(cc => cc.Age)
};
```

**Comment by jogibear9988** [comment]
is this still open?

**Comment by sdanyliv** [comment]
It is related to #353

**Comment by jogibear9988** [comment]
@sdanyliv  I think it should be possible to do smth. like this:

		[Sql.Expression("StDev({1})", ServerSideOnly = true, IsPredicate = true)]
		public static Nullable<Y> StDev<T, Z, Y>(IGrouping<T, Z> value, Expression<Func<Z, Y>> a) where Y : struct
		{
			throw new NotSupportedException();
		}

but it does not work atm.

**Comment by jogibear9988** [comment]
and Sql.Function seems also not to work

**Comment by sdanyliv** [comment]
Currently i'm working on Window Function support. I think it will be done during next week.
It is related to #542

**Comment by jogibear9988** [comment]
Do you only work on window functions, or a genery way for user defined functions?

**Comment by sdanyliv** [comment]
@jogibear9988, i'm working on generic way to define window functions. StdDev is window function

**Comment by genusP** [comment]
Please, add support user defined aggregate function for Sql Server (https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/create-user-defined-aggregates)

**Comment by sdanyliv** [comment]
@genusP, will check how to implement this feature.
