### ISSUE TITLE
WCF service doesn't use provider-specific data read logic

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#730]
Currently we call data reader methods directly in linq service which could lead to different results compared to queries, executed directly.

### Steps to reproduce
PR https://github.com/linq2db/linq2db/pull/727 adds tests that reproduce it (linq service must be enabled for them).

### Environment details
linq2db version: *1.8.2*

**Comment by sdanyliv** [comment]
Also all tests from https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/AnalyticTests.cs
should be enabled for LinqService.

**Comment by MaceWindu** [comment]
Fixed by #1512
