### ISSUE TITLE
Incorrect Oracle create table generation if a table includes Guid 

### ISSUE THREAD

**Issue by Lexey** [linq2db/linq2db#731]
CreateTable<T> generates invalid CREATE TABLE statement if a table has a Guid column without an explicit DB type when Oracle provider is being used.

```c#
    [Table("Calculation")]
    public class Calculation
    {
        /// <summary>The Id</summary>
        [Column, Identity, PrimaryKey, NotNull]
        public int Id { get; set; }
        /// <summary>Client request id</summary>
        [Column, NotNull]
        public Guid RequestId { get; set; }
    }
```
Resulting sql:

```sql
CREATE TABLE pfe.Calculation
(
	Id           Int        NOT NULL,
	RequestId    Guid       NOT NULL,
	Status       Int        NOT NULL,
	PathCount    Int        NOT NULL,
	StartDate    timestamp  NOT NULL,
	TimeHorizon  Float      NOT NULL,
	FactorListId Int        NOT NULL,
	Created      timestamp  NOT NULL,
	Updated      timestamp  NOT NULL,

	CONSTRAINT PK_Calculation PRIMARY KEY (Id)
)
```
Oracle does not have the Guid  column type. It should be raw(16).
An addition of DataType = DataType.Binary, Length = 16 to the column attribute does not help also. After it the generated column type is Binary(16) which is also invalid.
The only obvious way to workaround the problem is to set DbType="Raw(16)" property of the Column attribute.

### Environment details
linq2db version: *1.8.2*  
Database Server: *Oracle 11g*  
Database Provider: *Oracle.Managed*  
Operating system: *Windows 7*  
Framework version: *.NET Framework 4.6.2*

**Comment by Lexey** [comment]
The same problem exists with the byte[] column. In this case generated type is Varbinary. Which is also invalid.

**Comment by Lexey** [comment]
One more problem. In another table I have
        [Column(DataType = DataType.VarBinary, Length = -1), NotNull]
        public byte[] Data { get; set; }
Table creation works fine for SQL Server, but for Oracle it produces the Varbinary type that is not valid for 11g. Correctly it should be mapped to Blob.
I can workaround it with
        [Column(DataType = DataType.Blob), NotNull]
But that breaks SQL Server compatibility since there no mapping for Blob for it.
:(

**Comment by ili** [comment]
About second issue this should help:
```cs
        [Column(DataType = DataType.VarBinary, Length = -1), NotNull]
        [Column(DataType = DataType.Blob, Configuration = DataProviderName.Oracle)]
        public byte[] Data { get; set; }
```

**Comment by ili** [comment]
The smth same should help also with the firs issue, but experiments needed

**Comment by Lexey** [comment]
Thanks. I will try it.

**Comment by Lexey** [comment]
It works for both issues.

```c#
        [NotNull]
        [Column] // sql server version
        [Column(DbType = "Raw(16)", Length = 16, Configuration = ProviderName.Oracle)] //oracle version
        public Guid RequestId { get; set; }

        [NotNull]
        [Column(Length = -1)] // sql server version
        [Column(DataType = DataType.Blob, Configuration = ProviderName.Oracle)] // oracle version
        public byte[] Data { get; set; }
```

**Comment by ili** [comment]
Great :)
Can close?

**Comment by MaceWindu** [comment]
We definitely should find some time later and go over all providers and types.

**Comment by Lexey** [comment]
May be better to keep it and add proper default mappings later.

**Comment by ili** [comment]
Really, shame on me =( this is one minute fix!
