### ISSUE TITLE
Intercepting DB Exceptions

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#733]
We would like to be able to catch database exceptions and handle them as necessary.  We would also like to be database agnostic where possible however each provider returns its own Exception type meaning that we would have to supply catch statements appropriate for each type of database we are supporting.

I'm looking for a way of intercepting DB exceptions before they actually get re-thrown so that the user can supply their own exceptions generated from a single place.

I think that this would need to be in the DataConnection ExecuteNonQuery and ExecuteReader methods.  If these methods were made virtual then a user could simply inherit DataConnection and override these methods wrapping their own try/catch block around the base call and then throwing their own exception as required.

I can supply a PR if this is agreeable.

**Comment by jogibear9988** [comment]
I'd like this idea! In bltoolkit we had implemented a retry for some exceptions !

**Comment by jogibear9988** [comment]
Is this solved with the RetryPolicy?

**Comment by RoyC-Retail-Assist** [comment]
Yes.  Retry Policy works great thanks.
