### ISSUE TITLE
contains fails with access database

### ISSUE THREAD

**Issue by pentest30** [linq2db/linq2db#742]
An unhandled exception of type 'System.Data.OleDb.OleDbException' occurred in System.Data.dll

{"IErrorInfo.GetDescription failed with E_FAIL(0x80004005)."}
      Specialite firstOrDefault = _db.Specialites.FirstOrDefault(x => specialite.Name.Contains(x.Name));

**Comment by sdanyliv** [comment]
@pentest30, please follow our templete. Not enough information for solving your issue.

**Comment by sdanyliv** [comment]
Closing for now. Will reopen if needed.
