### ISSUE TITLE
Dynamic columns

### ISSUE THREAD

**Issue by boris-turk** [linq2db/linq2db#744]
Hi everybody,

let me first say that the linq2db library is a wonderful piece of software, very flexible and powerful. Keep up the great work you are doing!

Now to my problem. I work for a company which has their product on the marked since quite some time. We have to be backwards-compatible with certain core features it provides. One of them is the possibility to define so-called dynamic columns in the DB. Each table (and the associated POCO class) can have additional columns not know in advance. Somebody already explained this issue (in short) in the following ticket:

   https://github.com/linq2db/linq2db/issues/507

The second suggestion from Ili (using dictionary) probably won't work, because this approach can only be used if you are filling several values into one column. But in my case there is one DB column for one value in the dictionary.

I also tried with emit and already prepared a working prototype, but then I discovered the following:

   https://stackoverflow.com/questions/2503645/reflect-emit-dynamic-type-memory-blowup
   https://goo.gl/nvCnnz

I only did some measurements for the first problem mentioned on stackoverflow. A realistic scenario in my case would be 200 dynamically generated classes, each of them having 20 additional properties. When I do that, the CLR allocates additional 10 Mb of memory, quite a lot. The problem is that the user of the system might add/remove/change columns at runtime, without closing the application. For each change (even if it is a tiny one) I have to recreate all 200 dynamically generated classes. One might think that it is OK to recreate just the one that changed, but that one could be referenced by other dynamically generated classes (through Association attribute) and it is not trivial to detect these associations (not to mention that the association chains could be long). Unloading the dynamically generated assembly is most probably not an option, because the dynamic classes might still exist somewhere in memory.

Long story short: do you have an idea how hard would it be to add this kind of feature to linq2db? Maybe it goes against the philosophy of linq2db or you are under time pressure and need to do other important things first. In that case I am willing to invest some of my time and try to come up with a solution, even if it means that I will have my own linq2db build.

It would be necessary to fix at least these things:

 * create the appropriate SELECT statements with additional fields
 * create the INSERT, UPDATE statements with additional fields and parameters
 * fill the POCO instance with additional values
 * make sure that LoadWith also takes the additional values from related entity

You have a good feeling about the library itself, so I am asking you if it would be possible to do such a change in a reasonable amount of time (e.g. one week)? If yes, which are the core classes that need to be fixed?

Thank you in advance for any kind of feedback. Best regards from hot Slovenia :)

Boris Turk

**Comment by ili** [comment]
hi @boris-turk thanks for your good words.

The main question is: how to use dynamic fields.

let's imagine we'll do smth like:
```cs
var ms = MappingSchema.Default;
var fm = ms.GetFulentMappingBuilder();
fm.Entity<MyClass>()
.AddColumn(new ColumnAttribute(Field = "dymamic_int", Type = typeof(int)));

var data = db.GetTable<MyClass>().ToList();
```

and will get:
```sql 
SELECT
   --...
  dymamic_int
FROM MyClass
```
but what next? Where data should be saved? How can we update them? I think we need answer this questions first and then we can find how we can query them from database.

From other side. Look at [Insert](https://github.com/linq2db/linq2db/blob/master/Source/Linq/Query.cs#L581) method. It is really simple - SQL AST is generated and then linq2db builds SQL text from AST and executes it. There are also Delete\Update\etc commands (many commands where LINQ expression is not used made in same way). 

In general you can write needed queries this way (certainly only difference from handmade SQL text is it can be converted for any data provider supported).

**Comment by sdanyliv** [comment]
@boris-turk, i can not imagine how these classes should be used in linq queries.
Please post sample how do you plan to store and manipulate with such kind of columns.

**Comment by igor-tkachev** [comment]
@sdanyliv, definitely, an entity needs some container for such columns. It can be a name/value dictionary.

@boris-turk, to implement it we will need a container for data and a way to provide metadata in run-time. Both are doable. The question is when you will be able to provide metadata info? At the beginning, after some initialization and database use, multiple time during application work, etc?

**Comment by boris-turk** [comment]
Hi everybody,

thank you for the valuable feedback. I will first try to explain how our model looks like. Each POCO class is actually a wrapper around an instance of Dictionary<int,string>, where key represents the index of a field in a DB table (there could be gaps) and the value is the string representation of a piece of data (e.g. DateTime, decimal, etc). I know, it is not the most efficient solution to convert all different types into strings and back, but it is "good enough". This is how the base class looks like (the reduced version):

    public class BaseDto
    {
        private readonly Dictionary<int, string> _values;

        protected BaseDto()
        {
            _values = new Dictionary<int, string>();
        }

        public string GetValue(int fieldNumber)
        {
            string value;
            _values.TryGetValue(fieldNumber, out value);
            return value;
        }

        public void SetValue(int fieldNumber, string value)
        {
            _values[fieldNumber] = value;
        }
    }

And here is an example of a child class Article:

    [Table("Article")]
    public class Article : BaseDto
    {
        [Column("Field_01")]
        public string Description
        {
            get { return GetValue(1);}
            set { SetValue(1, value); }
        }

        [Column("Field_02")]
        public decimal StockQuantity
        {
            get { return GetValue(2).FromStringToDecimal(); }
            set { SetValue(2, value.FromDecimalToStringInvariant()); }
        }
    }

I didn't provide the extension methods like FromStringToDecimal, but you get the idea. We have a pair of extension methods for each type we want to convert to and from string.

With this model I have all the power of LINQ queries. I can for example "ask" the DB which articles have critical stock, e.g.:

    List<Article> criticalArticles = db.GetTable<Article>()
        .Where(x => x.StockQuantity < 5)
        .ToList();

For each POCO class we have created properties which need to be always present in that entity and won't change. For example, the StockQuantity value will always be stored into column "Field_02" in table Article and it will always be of type decimal. The end user cannot remove it or change it. He can only define new columns in a predefined range (specifically in range from 60 till 100).

Now imagine that the end user wants to keep track of article's color. He can use a special tool we developed and define a new column, let's say Field_65, of type string. The tool will do all the DB conversion stuff, i.e. rename the table, create a new one with Field_65 in it, copy data from the old table to the new one, and drop the old one.

The user can also change the input mask (window) on his own and add a new color input field, he can modify the reporting mechanism so that it prints this additional attribute on a paper, etc.

We access and modify the additional columns through the public GetValue and SetValue methods. If the user added field Color to the report, then the report generator tool will somehow call GetValue(65) on an article entity. Probably you get the whole idea by now ...

How to provide meta-data at runtime? Maybe it would be possible to come up with something like this:

    var fm = MappingSchema.Default.GetFluentMappingBuilder();
    fm.Entity<Article>().
        Method<Article>(
            (article, value) => article.SetValue(65, value),
            article => article.GetValue(65)
        ).HasColumnName("Field_65");

The Method would have a similar definition as Property has now, but it would have a getter/setter pair:

    public MethodMappingBuilder<T> Method<T>(
        Expression<Action<T, object>> setter,
        Expression<Func<T, object>> getter)
    {
		return (new MethodMappingBuilder<T>(this, setter, getter)).IsColumn();
    }

OK, if you have a look at my SetValue and GetValue method definitions, you can see that they work with strings. But I could add a pair of methods that operate with objects and then within those methods do the object/string mapping. This is not an issue.

Probably it would be necessary to somehow pass the getter/setter arguments to MemberAccessor class. This one already has the Getter and Setter properties, maybe it would be enough just to create the appropriate instance.

It would be also nice to support certain update and insert features, e.g.:

    db.GetTable<Article>().Set(<somehow_specify_field_65>, "Red").Update();

I hope I did not oversimplify something. It is a bit late, have to go to bed :) Anyway: thank you in advance for any kind of help. By the way: is it possible to donate some money for this project? I would be glad to do it ...

Boris

**Comment by boris-turk** [comment]
Hi,

I forgot to give a more precise answer to Igor's question about when I will be able to provide metadata info. The typical scenario would be that I load all meta-data info from some configuration xml files during application startup (before the DB is accessed) and then pass this meta-data to linq2db through fluent mapping builder. The problem is, that the metadata could change at runtime. The user is allowed to define new columns on-the-fly and operate with those new columns without restarting the application.

So I would need to inform linq2db about dynamic field changes any time. But I guess this would not be an issue if I somehow use a combination of default mapping schema (for fixed columns) and a custom one, which can change at runtime. I have the feeling that mapping schemas are a flexible mechanism that give you the possibility to implement all kind of interesting and "exotic" features like https://github.com/linq2db/linq2db/issues/580.

Best regards,

Boris

**Comment by hoangcuongvn** [comment]
I have a similar problem. The table POCO class is like below
```
public class MyTable
{
  public long ID { get; set; }
  public long V1 { get; set; }
  public long V2 { get; set; }
  public long V3 { get; set; }
  // might be up to V100
}
```

I need to dynamically statistic on V1, V2, V3 through their numbers 1, 2, 3. The code is like below
```
void DoSomethingWithColumn(int i)
{
  var q =
    from t in _db.MyTable
    group by new { V = t.GetValue(i) } into g
    select new { g.Key.V, Count = g.Count() };
  // ...
}
```
So 
If i = 1, DoSomethingWithColumn will statistic on MyTable.V1
If i = 2, DoSomethingWithColumn will statistic on MyTable.V2
If i = 3, DoSomethingWithColumn will statistic on MyTable.V3

I think it might be achieved through using ExprsessionMethod attribute like below. But I do not know how to write that GetValueImpl method. Do you have a clue or a sample code to implement it?
```
public static class MyTableFunctions
{
  ExprsessionMethod("GetValueImpl")
  public static long GetValue(this MyTable entity, int i)
  {
    throw new NotImplementedException();
  }
}
```
