### ISSUE TITLE
Retry Policy

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#751]
Is the RetryPolicy now used as Default, or is the default a "null" RetryPolicy? Do we also Retry in "Transactions" as a Default?

**Comment by ili** [comment]
* Is the RetryPolicy now used as Default, or is the default a "null" RetryPolicy? 
Default is `null` lets suppose this to be "experimental" feature.

* Do we also Retry in "Transactions" as a Default?
I think we do not have Retry in transactions

@andrewvk  @igor-tkachev What do you think about transactions retry, does it doable?

**Comment by andrewvk** [comment]
1) RetryPolicy is null by default, and this behavior chose for performance reasons.
2) Retry for whole transaction is a feature for next release.

**Comment by MaceWindu** [comment]
looks like answered
