### ISSUE TITLE
Association with constant value

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#753]
In table Assignments exist two columns: TargetName, TargetId. This is columns contains target table name and id.
Could I create association property, for entity Request, when TargetName field always contains value 'bda.Requests'?

**Comment by ili** [comment]
You mean that on association you always need to generate query like:
```sql
select *
from Requests t
inner join Assignments a on t.Id = a.TargetId  and a.TargetName = 'bda.Requests'
```

I think no, you would need to deal with this manually, but you can use some helper:
```cs
public static IQuerable<Assignments> RequestAssignments(this IDataContext db) => db.GetTable<Assignments>().Where(_ => _.TargetName == "bda.Requests");

var data = from r in db.GetTable<Requests>()
           from a in db.RequestAssignments()
           select a;
```

**Comment by genusP** [comment]
I use OData library and Association used as Navigation property.
I fork library and add extend handling associations:
```C#
class SomeClass{
  ....
  [Association(ThisKey ="TargetId, TargetName", OtherKey ="Id, const:bda.Requests", Relationship = Relationship.ManyToOne)]
  public Class1 Request { get; set; }
  ....
}
```
If necessary I can make a PR

**Comment by ili** [comment]
@genusP do it! )

**Comment by ili** [comment]
Another question is, should be this constraint applied if I do:
```cs
var data = from r in db.GetTable<Requests>()
           join a in db.RequestAssignments() on r.Id equals a.TargetId
           select a;
```

you see, in this case association would not be used, query would be:
```sql
select *
from Requests t
inner join Assignments a on t.Id = a.TargetId 
```

to cover both cases we do need to introduce this behavior using query optimizer like [here](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Samples/ConcurrencyCheckTests.cs) but adding check to join condition

**Comment by ili** [comment]
```cs
public class Request
{
    [Assosiation(ExpressionPredicate = "RequestAssignmentPredicate")]
    public IEnumerable<Assignment> Assignments { get; set; }

    static Expression<Func<Request, Assignment, bool>> RequestAssignmentPredicate => 
        (r, a) => r.Id == a.TargetId && a.TargetName == "bda.Requests";
}
```

**Comment by igor-tkachev** [comment]
Try this:

```c#
public class Request
{
    [ExpressionMethod("AssignmentsImpl")]
    public IEnumerable<Assignment> Assignments { get; set; }

    static Expression<Func<Request, IDataContext, IEnumerable<Assignment>>> AssignmentsImpl => 
        (r, db) => db.GetTable<Assignment>().Where(a => r.Id == a.TargetId && a.TargetName == "bda.Requests");
}
```

**Comment by genusP** [comment]
Its work. Thanks.

**Comment by sdanyliv** [comment]
Bad news, that you can use this approach only once in the query. Otherwise duplicate joins may appear.

**Comment by genusP** [comment]
i understood. Thanks.

**Comment by sdanyliv** [comment]
I'm preparing approach described by @ili, so follow this issue.

**Comment by genusP** [comment]
Its cool. Thanks for your work.
