### ISSUE TITLE
Lind2DB Core - Sybase

### ISSUE THREAD

**Issue by Quentinb** [linq2db/linq2db#765]
using Linq2DB on a .Net Core 1.1 WebAPI.

When trying to connect to the DB, I get an exception message, looking for Sybase.AdoNet2.AseClient
Should it not be looking for Sybase.AdoNet45.AseClient.dll or Sybase.AdoNet.AseClient.dll ?
ConnectionString = "Data Source=server:5000;Database=DbName"
```
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HL658SVRNJ8R": An unhandled exception was thrown by the application.

System.IO.FileNotFoundException: Could not load file or assembly 'Sybase.AdoNet2.AseClient, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Sybase.AdoNet2.AseClient, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at LinqToDB.DataProvider.DynamicDataProviderBase.get_DataReaderType()
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WebApi.Controllers.CustomerController.Get() in ...\WebApi\Controllers\CustomerController.cs:line 17
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
```
### Environment details
linq2db version: *1.8.3*  
Database Server: *Sybase*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Core 1.1*
Visual Studio 2017

**Comment by MaceWindu** [comment]
@Quentinb , your problem is that linq2db cannot find  any Sybase.AdoNet*.AseClient.dll assembly in the same folder as linq2db assembly. Maybe you try to use it from GAC? Right now it will not work, you need to copy it to your application.

For team:
From source code I see that we try to discover sybase assembly, using following names:
```
Sybase.AdoNet45.AseClient.dll
Sybase.AdoNet4.AseClient.dll
Sybase.AdoNet35.AseClient.dll
Sybase.AdoNet2.AseClient.dll
```
in this order, but we don't throw exception if assembly found. Instead of it we try to use last assembly. This should be fixed to give users more clear error message.
Also we should check if it will work with assembly from GAC and add support for this scenario.

**Comment by MaceWindu** [comment]
@Quentinb , sorry, I see you use .net core so there is no GAC for you. Anyway, check where is your provider assembly placed and get back to us.

**Comment by igor-tkachev** [comment]
@Quentinb , also you can enable fusion log and see what's going on.
I hope fusion log works in core.

**Comment by Quentinb** [comment]
@MaceWindu I've tried copying the dll into the debug\netcoreapp dir as well as the obj\netcoreapp dir with no joy. I'll try a few more tricks on Monday when I'm back at this specific PC.

@igor-tkachev I'll try that, thanks for the tip.

@MaceWindu & @igor-tkachev thanks for your quick response!

**Comment by Quentinb** [comment]
Hi All, I've tried copying the Dll (Sybase.AdoNet4.AseClient) into every possible directory within the project with no luck. Keep getting the same error that the Dll (Sybase.AdoNet2.AseClient) could not be found.

Looking into enabling Fusion Log still...

**Comment by Quentinb** [comment]
@igor-tkachev I've tried Fusion but it does not appear to show up any related results. I've tried running the app under IIS Express as well as the dotnet core debug host (as proved by Visual Studio). The only log entries I see are from these processes starting up. Once I try and access the DB via an API call, nothing new appears in the logs. I do see the exception message in the debug console in VS though.

**Comment by MaceWindu** [comment]
Could you add logging for following data:
```cs
var path = Path.Combine(typeof(SybaseTools).AssemblyEx().GetPath(), "Sybase.AdoNet4.AseClient.dll");

// check what path is used to search for dll
Log(path); // call your log function here

// check if it can be found and there is no permissions issues (shouldn't be an issue)
Log(File.Exists(path)); // call your log function here
```

**Comment by Quentinb** [comment]
Gave that a bash now @igor-tkachev .
C:\Users\<myname>\.nuget\packages\linq2db.core\1.8.3\lib\netstandard1.6\Sybase.AdoNet4.AseClient.dll

I inspected the dir and the Sybase DLL file is not there.

**Comment by sdanyliv** [comment]
Possibly it just can not load dll. AnyCpu, 64 bit, some references missed.
When im starting to give up ususally i'm using [ProcessMonitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) and trying to figure out how system searches for specific DLL

**Comment by MaceWindu** [comment]
@Quentinb thanks for your path. Looks like a bug with assembly search path generation, maybe .net core specific. For now you should be able to workaround it placing your Sybase client assembly there

**Comment by MaceWindu** [comment]
Or try to set CopyAllways=true for linq2db.dll reference

**Comment by Quentinb** [comment]
@MaceWindu thanks for the tips. I've tried both those to no avail. I'll try switching to a full .Net stack. Guess it is a core issue at this stage.

PS: Core does not appear to have the CopyAlways option...

**Comment by MaceWindu** [comment]
Also check this link, maybe it will help
https://github.com/aspnet/Home/issues/593

**Comment by ili** [comment]
@Quentinb is it possible to use .Net 4, .Net 4.5 libraries with .Net Core?
Can you use Sybase.AdoNet45.AseClient.dll directly with without linq2db? It would be great if you can provide test project if it is so

**Comment by igor-tkachev** [comment]
@Quentinb Also you can try resolve Sybase assembly by using the following method
LinqToDB.DataProvider.Sybase.SybaseTools.ResolveSybase(Assembly assembly)

Call it when you application starts.

**Comment by Quentinb** [comment]
@ili it may be possible to use .Net 4.0 and .Net 4.5 libs in core however, this depends on the library's dependencies and actual internal code. .Net Core has a [growing list of supported APIs](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.0) and now with .Net core 2 out, the support is even better.

I have not used the Sybase on its own. We use it with NHibernate currently and want to switch to Linq2DB.

**Comment by jogibear9988** [comment]
I think the use of net45 assemblys in core is firstly possible in core2.0

**Comment by MaceWindu** [comment]
@Quentinb we added support for managed ASE provider with .net core support from DataAction
https://github.com/linq2db/linq2db/pull/1159
You can try it using myget builds.

I will check if it is possible to use official provider with .net core 2 project and then close this issue based on test results.

**Comment by MaceWindu** [comment]
Ok, I've tried to make it work with .net core 2 project and it immediately fails with MissingMethodException in connection constructor
```
MissingMethodException: Method not found: 'System.Security.AccessControl.DirectorySecurity System.IO.Directory.GetAccessControl(System.String)'.
```
This method not available on .net core including version 2.1. See this issue: https://github.com/dotnet/corefx/issues/9872
Note that there is another person there trying to use native provider on core.
Looks like windows compatibility pack provides this method, but I'm not sure how to make existing library to use it. I suspect it only possible if you build against compatibility pack (sorry, not a big .net core specialist :-) ).

I would say we should close this issue, as it is something that should be fixed on SAP side (or wait for .net core team to implement all missing API)

**Comment by MaceWindu** [comment]
Closing for now as non-actionable. We would highly recommend to use DataAction's provider for .net core project. It could miss some features compared to native provider, but you allways could ask them to implement them. With SAP provider you have nobody to ask for help.
