### ISSUE TITLE
Adding exrta where clauses based on entity attributes or interfaces

### ISSUE THREAD

**Issue by AlthalusDGr8** [linq2db/linq2db#768]
In Nhibernate, one can extend the BaseClassMap in order to introduce custom SQL to be included with the queries generated by overriding the default where clauses generation.  Is it possible to do so using Linq2DB?

For Example:
I have an entity which implements the ISoftDeletable interface.  I would like linq2db to automatically add the where clause "IsDeleted = 0" whenever I query for this entity whit out me having to set it up each time in queries?

Am asking because I run a multi tenant application and would like my queries to automatically specify the tenant for the queries being produced

Thanks in advance
 
### Environment details
linq2db version: *1.8.3*  
Database Server: *SQL Server 2012*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.5*

**Comment by MaceWindu** [comment]
Why don't just use something like that?

```cs
class MyDb : DataConnection
{
    public ITable<Table1Record> Table1 => GetTable<Table1Record>();

    public IQueryable<Table2Record> Table1 => GetSoftDeletableTable<Table2Record>();

    private IQueryable<TEntity> GetSoftDeletableTable<TEntity>() where TEntity : ISoftDeletable
    {
        return GetTable<TEntity>().Where(r => r.IsDeleted == 0);
    }
}
```

**Comment by MaceWindu** [comment]
And for tenant you can do something similar by passing tenant to MyDb constructor

**Comment by sdanyliv** [comment]
Even better you can join to other table to filter out records if you have complex criteria.

**Comment by AlthalusDGr8** [comment]
Was thinking whether such a thing can be enforced at a generic repo level. So the select will check the entity if it implements a certain interface and apply the constraints there. The only drawback for this would be the reflection cost on every call.

**Comment by sdanyliv** [comment]
@AlthalusDGr8, it is very specific request, and we trying to avoid implementation of such features. 
NHibernate's code is growing day by day, because they are trying to cover everything and usually slowdown library.

**Comment by sdanyliv** [comment]
Closing discussion.
