### ISSUE TITLE
Is there anyway to query from a Table without create TableClass

### ISSUE THREAD

**Issue by spider58** [linq2db/linq2db#771]
Hello. 

I'm created all tableClass from "A" schema and i can query whatever i want.

I want to query from "C" table from "B" schema  without create table class.

Is this possible?

Thanks Inadvance.

**Comment by sdanyliv** [comment]
Yes it is possible
```c#
db.GetTable<A>().SchemaName("C").TableName("B")
```

**Comment by spider58** [comment]
Thanks for answer but SchemaName is not found under GetTable

**Comment by MaceWindu** [comment]
It's extension method in LinqToDB namespace (https://github.com/linq2db/linq2db/blob/master/Source/LinqExtensions.cs#L82)

**Comment by spider58** [comment]
is there no way to send sql command to db? 

"SELECT usrname from SCHEMANAME.TABLENAME Where id = 55)
--

**Comment by sdanyliv** [comment]
Include LinqToDB namespace and `SchemaName` will be accessible

**Comment by MaceWindu** [comment]
Could you provide your code and link to a sample you use? Beause linq2db doesn't have any PConnection classes at all

**Comment by spider58** [comment]
Thanks. yes now accessible. :))

**Comment by MaceWindu** [comment]
Great, closing then
