### ISSUE TITLE
Open Connection Exception with Retry Policy and Connection string with password

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#772]
If a retry policy is added to a DataConnection where the connection string contains a password then the Connection Open raises an error.

The problem is in RetryingDBConnection
```c#
public override void Open()
{
	_connection.ConnectionString = ConnectionString;
	_policy.Execute(_connection.Open);
}

public override string ConnectionString
{
	get { return _connection.ConnectionString;  }
	set { _connection.ConnectionString = value; }
}

```
This is basically doing _connection.ConnectionString = _connection.Connections string but for some DB Connection objects the Get on ConnectionString returns the connection string minus the password element.  I'm experiencing this on an iSeries DB2 connection but I seem to remember that the behaviour is the same for SQL Server.

e.g. if the ConnectionString is set to 

**"DataSource = server1; UserId = FRED; Password = FREDSPW;"**

ConnectionString Get will return 

**"DataSource = server1; UserId = FRED;"**

Removing the line setting the connection string on the Open method fixes the issue and it is redundant anyway.

```c#
public override void Open()
{
	_policy.Execute(_connection.Open);
}
```
### Environment details
linq2db version: 1.8.3  
Database Server: iSeries DB2 but probably SQL Server also 
Database Provider: Linq2DB4iSeries  
Operating system:  Windows 10
Framework version: .NET Framework 4.6.1

**Comment by MaceWindu** [comment]
Thanks! We aware of the same issue with SAP HANA provider and plan to fix it in next version
