### ISSUE TITLE
InsertWithIdentity returns decimal

### ISSUE THREAD

**Issue by n9** [linq2db/linq2db#774]
The declared return value of `InsertWithIdentity` method is `object`. I have expected that the actual return value will be the same as the identity column (which in my case is `int`). However, the actual return type is `decimal`. 

### Steps to reproduce

```c#
[Table(Name = "Products")]
public class Product
{
	[PrimaryKey, Identity]
	public int Id { get; set; }

	[Column]
	public string ProductCode { get; set; }
}

void Main()
{
	using (var db = new DataConnection(new SqlServerDataProvider("SQL", SqlServerVersion.v2012), Connection))
	{
		db.InsertWithIdentity(new Product
		{
			ProductCode = "X"
		}).GetType().Dump(); // outputs decimal
	}
}
```

### Environment details
linq2db version: *1.8.3*
Database Server: *SQL Server 14*
Database Provider: *SqlServerDataProvider*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7*

**Comment by igor-tkachev** [comment]
This is how your data provider works. Use `Convert.ToInt32.`

**Comment by n9** [comment]
You mean that this is a issue of data provider which maps `numeric(38,0)` to `decimal` and there is no return mapping to get the expected return type?

Will it be hard (for newbie) to change the `InsertWithIdentity` method to use the entity mapping and convert the value? (Which might be [more convenient](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for other newbies.)

**Comment by igor-tkachev** [comment]
No, we can't do that. InsertWithIdentity method can return either Int32, or Int64, or Decimal.
But we can add InsertWithInt32Identity method.

**Comment by n9** [comment]
@igor-tkachev I have hacked a draft: n9/linq2db@88da7a0
