### ISSUE TITLE
Don't escape my Escape Character

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#776]
A manually attached LIKE clause `Sql.Like(f.FIELDNAME, "slot[_]__")` will be translated to `[f].[FIELDNAME] LIKE N'slot[[]_]__'`. What I want is match contents like "slot_01", "slot_02" and so on. I can't match with a `Sql.Like(f.FIELDNAME, "slot%")` or `f.FIELDNAME.StartsWith("slot_")` ...

Is there any option to disable the auto-escaping?

Edit:
Provider is Microsoft SqlServer.

Thanks.

**Comment by sdanyliv** [comment]
It is regression after fixing #169.
Looks like it was fixed in wrong place.

**Comment by sdanyliv** [comment]
@jdistlr, i propose to do this in that way - Implement your own function:

```c#
[Sql.Expression("{0} LIKE {1}", Precedence = LinqToDB.SqlQuery.Precedence.Comparison, IsPredicate = true, ServerSideOnly = true)]
public static bool MyLike(string matchExpression, string pattern)
{
	throw new NotImplementedException();
}
```

**Comment by jdistlr** [comment]
Works perfectly. Thanks a lot!

**Comment by igor-tkachev** [comment]
@jdistlr Did you try Sql.Like(string matchExpression, string pattern**, char? escapeCharacter**) method?

**Comment by sdanyliv** [comment]
@igor-tkachev, that's why this issue was created - Sql.Like has code that add additional escaping.
