### ISSUE TITLE
Unable to get output parameter after querying MySQL stored procedure

### ISSUE THREAD

**Issue by mr-clx** [linq2db/linq2db#783]
Seems the only way to get updated Output parameter is to call CommandInfo.ExecuteProc()

Have some MySQL Stored prodedure : 
`proc(in I, out O)`

Building params list and query procedure
```
var paramOut = new DataParameter("O", 0) { Direction = System.Data.ParameterDirection.Output };
var paramsList = new[]
{
    new DataParameter("I", ".."), 
   paramOut,
}
db.QueryProc<MyDataType>("proc1", paramsList)
```
There is no changes in paramOut after that.
The only way to get result is to call CommandInfo.ExecuteProc():
```
var ci = new CommandInfo(db, "proc", paramsList );
ci.ExecuteProc();  //< -- now we have updated paramOut value
var procResult = ci.QueryProc<RPDeviceUnitHistoryCommon>() // .. execute proc again to get a result set....
```
So, stored procedure executed twice. Not good.
Is it possible to get procedure result set and out parameter using right way?

**Comment by MaceWindu** [comment]
see #81. If nothing changed since then, you need to read your output parameter value from db.Command.Parameters

**Comment by mr-clx** [comment]
Thank you! That works
`var paramOut = db.Command.Parameters["O"] as DbParameter;`
