### ISSUE TITLE
SQLite schema generation error when Foreign Key targets table only

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#784]
I have an SQLite3 database file from a vendor application that is causing schema generation to fail with an exception when generating the schema:

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options) in M:\Dev\GitHub\linq2db\Source\SchemaProvider\SchemaProviderBase.cs:line 156

```

I downloaded the linq2db code to track down the cause and eventually tracked down the source of the issue as the SQL used to generate the table.  A minimal example would be:

```sql
CREATE TABLE `Parent` (
  `KeyField` INTEGER NOT NULL,
  `NonKeyField` TEXT NOT NULL,
  PRIMARY KEY(`KeyField`)
);

CREATE TABLE `Child`
(
  `ParentKey` INTEGER NOT NULL,
  `ChildKey` INTEGER NOT NULL,
  `SomeData` TEXT NOT NULL,
  PRIMARY KEY (`ParentKey`, `ChildKey`),
  FOREIGN KEY (`ParentKey`) REFERENCES Parent ON DELETE CASCADE
);
```

SQLite supports this and correctly cascades deletions.

When generating a schema for the database the foreign key list has an empty string in `FK_TO_COLUMN` which then causes the exception in the lookup of `otherColumn` on line 157.

### Steps to reproduce
Create tables using the above create statements.

The problem can be seen immediately in LINQPad using the LinqToDB driver.  Refresh the database after creating the tables and you will receive a schema error.

For C# create a project, add Nuget packages: System.Data.SQLite.Core, linq2db

Put the following code into the program.cs and run.

```cs
using System;
using LinqToDB.Data;
using LinqToDB.DataProvider.SQLite;

namespace SQLiteErrorTest
{
    public class TestDB : DataConnection
    {
        public TestDB()
            : base(new SQLiteDataProvider(), @"DataSource=M:\Dev\TestData.db")
        { }
    }

    public class Program
    {
        public static void Main()
        {
            var provider = new SQLiteDataProvider();
            var schemaProvider = provider.GetSchemaProvider();
            var schema = schemaProvider.GetSchema(new TestDB());
        }
    }
}
```

The exception will be raised on the `GetSchema` call.

### Proposed Resolution

When a foreign key does not specify a target column name then SQLite appears to fall back on the primary key columns.  To resolve, linq2db needs to take this behavior into account.

Possibly replace `LinqToDB.DataProvider.SQLite.SQLiteSchemaProvider.GetForeignKeys` with:

```cs
protected override List<ForeingKeyInfo> GetForeignKeys(DataConnection dataConnection)
{
	var fks = ((DbConnection)dataConnection.Connection).GetSchema("ForeignKeys");

	var result = 
	(
		from fk in fks.AsEnumerable()
		where fk.Field<string>("CONSTRAINT_TYPE") == "FOREIGN KEY"
		select new ForeingKeyInfo
		{
			Name         = fk.Field<string>("CONSTRAINT_NAME"),
			ThisTableID  = fk.Field<string>("TABLE_CATALOG")   + "." + fk.Field<string>("TABLE_SCHEMA")   + "." + fk.Field<string>("TABLE_NAME"),
			ThisColumn   = fk.Field<string>("FKEY_FROM_COLUMN"),
			OtherTableID = fk.Field<string>("FKEY_TO_CATALOG") + "." + fk.Field<string>("FKEY_TO_SCHEMA") + "." + fk.Field<string>("FKEY_TO_TABLE"),
			OtherColumn  = fk.Field<string>("FKEY_TO_COLUMN"),
			Ordinal      = fk.Field<int>("FKEY_FROM_ORDINAL_POSITION"),
		}
	).ToList();

	if (result.Any(fk => string.IsNullOrEmpty(fk.OtherColumn)))
	{
		var pks = GetPrimaryKeys(dataConnection).ToDictionary(pk => string.Format("{0}:{1}", pk.TableID, pk.Ordinal), pk => pk.ColumnName);
		foreach (var f in result.Where(fk => string.IsNullOrEmpty(fk.OtherColumn)))
		{
			string k = string.Format("{0}:{1}", f.OtherTableID, f.Ordinal);
			if (pks.ContainsKey(k))
				f.OtherColumn = pks[k];
		}
	}
	return result;
}
```

This appears to resolve the issue by matching the foreign key fields to the corresponding primary key fields by ordinal.  

### Environment details
linq2db version: *1.8.3*  
Database Server: *SQLite 3.19.3*  
Database Provider: *SQLite 3.19.3, NuGet: System.Data.SQLite.Core v1.0.105.2*  
Operating system: *Windows 7*  
Framework version: *.NET Framework 4.5.2*

**Comment by ili** [comment]
Closed via #785, thanks! :)
