### ISSUE TITLE
[Idea] More options for constructor generation in T4 templates

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#789]
I've been using the T4 templates recently and have had to tweak the code generation a little to change the way it emits constructors for the data context.  After a little consideration I thought it might handy to have some extra options around constructor generation to allow for a little more flexibility.

So far these are the ideas that I have:

* Flags to suppress generation of constructors such as the default constructor

* Add a constructor option that takes a connection string.

* When constructing from connection string, automatically set the provider based on the template type.

(I use dynamically constructed connection strings a lot and very rarely store them in the application config.)

Any other suggestions would be welcome.

### Implementing...

After playing around a little I came up with the following changes to the templates deployed by the `linq2db.SqlServer` NuGet package which implement some of the above:

***In `LinqToDB.ttinclude`:***

At ~line 29, after `string SchemaDataContextTypeName = "DataContext";`

	bool   ConstructDefault           = true;
	bool   ConstructFromConfiguration = false;
	string ProviderType               = null;

At ~line 96, after `body.Add("InitDataContext();");`

		if (DefaultConfiguration != null)
			DataContextObject.Members.Add(new Method(null, DataContextObject.Name, new string[0], body) { AfterSignature = { ": base(\"" + DefaultConfiguration + "\")" } });
		else if (ConstructDefault)
			DataContextObject.Members.Add(new Method(null, DataContextObject.Name, new string[0], body));
		if (ConstructFromConfiguration)
			DataContextObject.Members.Add(new Method(null, DataContextObject.Name, new[] { "string configuration" }, body) { AfterSignature = { ": base(configuration)" } });
		else if (ProviderType != null)
			DataContextObject.Members.Add(new Method(null, DataContextObject.Name, new[] { "string connectionString" }, body) { AfterSignature = { ": base(\"" + ProviderType + "\", connectionString)" } });

***In `LinqToDB.SqlServer.ttinclude`***

Add the following to each `LoadSqlServerMetadata` method:

    ProviderType = "System.Data.SqlClient";

*This line would go in every `Load*Metadata` method with an appropriate value for each database type.*

---

Using the following options in my main template (`TestDB.SqlServer.tt`):

	DataContextName = "TestDB";
	ConstructDefault = false;

The full list of constructor code generated for the database:

	public TestDB(string connectionString)
		: base("System.Data.SqlClient", connectionString)
	{
		InitDataContext();
	}

**Comment by igor-tkachev** [comment]
@Corey-M, you can create partial class and define any constructor you need.

**Comment by Corey-M** [comment]
@igor-tkachev Yes, I've done something similar any number of times.  Each time I use the templates I would have to do extra work beyond configuring the template.  Yes, I can create a data library for each database I use, but it's easier in a lot of cases to simply run the templates in the project where I'm working with a particular database, especially when I'm developing the database alongside the code.

I could just customise the templates for my own use, and probably will.  I just thought this was a useful addition.

**Comment by igor-tkachev** [comment]
@Corey-M We do not usually accept any specific changes. However, we can always improve our code and make it more flexible to support custom changes. I think we can create another overridable func/action to control constructor generation.

**Comment by igor-tkachev** [comment]
@Corey-M you can now create .ttinclude like this one https://github.com/linq2db/t4models/blob/bd0292c27044933cbbdbca12c5af574ec20835b0/Tests/LinqToDB/SqlServer.ttinclude
and include it in your .tt
https://github.com/linq2db/t4models/blob/bd0292c27044933cbbdbca12c5af574ec20835b0/Tests/LinqToDB/SqlServer.tt#L6

**Comment by Corey-M** [comment]
Nice.  Thanks @igor-tkachev
