### ISSUE TITLE
how can i select some random data?

### ISSUE THREAD

**Issue by ckhker** [linq2db/linq2db#791]
how can i select some random data?
i try to

[Column(Name = "newid()", IsColumn=false)]
public Guid Random { get; set; }

tabale.Take(100).OrderBy(t=>t.Random )
tabale.Take(100).OrderBy(t=>"newid()")

it does't work

i used mssql

**Comment by sdanyliv** [comment]
Try to use Sql.NewGuid()
```cs
tabale.Take(100).OrderBy(t=>Sql.NewGuid())
```

**Comment by sdanyliv** [comment]
Closing that. Looks like it is already answered.
