### ISSUE TITLE
Linq2db execute Stored procedure when I connect to sybase ASE

### ISSUE THREAD

**Issue by eric844** [linq2db/linq2db#792]
Using linq2db with linqpad. Over 150 stored procedure on the database where executed when I tried to connect to the first time and it corrupted our data. 

When we took out the execute permission for stored procedure and tried to reconnect we got error 
10330 You do not have the permission to execute this command. We got 3 error 2812 Store procedure % not found . Specify owner object name.

It seems that when we try to connect to our envireonment linq2db try to execute store proc.

**Comment by igor-tkachev** [comment]
@eric844 when you create LINQ to DB connection you, uncheck "Include Stored Procedures and Functions" option.

**Comment by eric844** [comment]
Is it normal though that it execute all store procs?

Is it a known issue?

**Comment by igor-tkachev** [comment]
Here https://github.com/linq2db/linq2db/blob/master/Source/SchemaProvider/SchemaProviderBase.cs#L410

We call stored procedure with ```CommandBehavior.SchemaOnly``` option. It should not execute stored procedure, it returns schema instead.

**Comment by MaceWindu** [comment]
fixed by #801

**Comment by MaceWindu** [comment]
I will close it when I will add tests

**Comment by MaceWindu** [comment]
I've created test and it looks like Sybase bug. We set proper command behavior, it used by Sybase provider and it returns schema. But server also execute procedure.
I'm not sure if we can do anything here.

**Comment by MaceWindu** [comment]
I think we should disable schema reading for procedures for sybase and add some sybase-specific key to enable it so user will be aware of possible consequences
