### ISSUE TITLE
How to Keep the table column names?

### ISSUE THREAD

**Issue by faraway1989** [linq2db/linq2db#796]
example: person well be People, but i need "person";

**Comment by sdanyliv** [comment]
Please explain what you need more clear.

**Comment by faraway1989** [comment]
My English isn't good enough!!!!


Keep table column headers unchanged,

linq2db DataBase to Model:
[Column("flow_id"),      PrimaryKey(3), NotNull] public decimal   **FlowId**      { get; set; } // numeric(3, 0)
that's what I want:
[Column("flow_id"),      PrimaryKey(3), NotNull] public decimal   **flow_id**     { get; set; } // numeric(3, 0)

**Comment by sdanyliv** [comment]
Look at these options https://github.com/linq2db/t4models
You have to set NormalizName = false in your T4 template.
