### ISSUE TITLE
Feature suggestion: .OutputDeleted()/.OutputUpdated()

### ISSUE THREAD

**Issue by Arithmomaniac** [linq2db/linq2db#797]
Currently, when you call `LinqToDB.LinqExtensions.Delete` or `LinqToDB.LinqExtensions.Update`, you get back the number of items affected.

It would be nice to optionally be able to get back the items that were deleted or updated. In SQL Server, for example, this can be done with the [OUTPUT](https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql) clause.

A couple of ways the API could change to support this:
 * Add overloads with an `out` parameter
 * Have a newly-named member (e.g. `DeleteWithObjects`)

### Environment details
linq2db version: 1.8.3
Database Server: SQL Server 2016

**Comment by genusP** [comment]
INSERT and  MERGE operation also support OUTPUT clause.

**Comment by MaceWindu** [comment]
DELETE support added in rc2: https://github.com/linq2db/linq2db/pull/2284
UPDATE support is currently in work: https://github.com/linq2db/linq2db/pull/2321

**Comment by MaceWindu** [comment]
Gonna close it as we already track it in #869
