### ISSUE TITLE
Firebird: Multiple update or insert

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#806]
Hello,

I would like to create a batch for a list. The BulkCopy does not work, because it has a limit for BulkCopyType.MultipleRows. So is there another way to create a batch?
Firebird has the possibility to create an update or insert with matching columns.
So how could I create a metod that can be called like this : context.UpdateOrInsert(list);

That in the result sql creates something like this:

UPDATE OR INSERT Table (ID, NAME, STREET) VALUES (1, "MAX", "STREET 1") MATCHING (ID);
UPDATE OR INSERT Table (ID, NAME, STREET) VALUES (2, "MAX_1", "STREET 2") MATCHING (ID);
UPDATE OR INSERT Table (ID, NAME, STREET) VALUES (3, "MAX_2", "STREET 3") MATCHING (ID);

A creation of this SQL would be much faster..

**Comment by MaceWindu** [comment]
Check this: https://github.com/linq2db/linq2db/wiki/Merge-API
Will it cover your needs? It will be in next release we currently preparing

**Comment by sdanyliv** [comment]
@Franki1986, also you can check our unit tests as a sample: https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/MergeTests.Operations.Insert.cs

**Comment by Franki1986** [comment]
Thanks for your responses. The problem is that this isn't already released, but rather than this it is not realy what I am looking for. 
I would like to pass a list to a function and create the above sql statement based on the mapping attributes. Is there something to build a query like this? Most of the query builders are internal.

**Comment by MaceWindu** [comment]
If you need to insert or update records from list using primary key fields, it could be achived with following merge command:
```
db.GetTable<T>()
    .Merge()
    .Using(yourList) // here you pass your list
    .OnTargetKey() // make decision on primary key
    .UpdateWhenMatched() // update all fields from mapping
    .InsertWhenNotMatched() // insert all fields from mapping
    .Merge();
```

**Comment by Franki1986** [comment]
Thank you for your responses. Merge is a good way unfortunately it is not released. So I thought there would be a way to overcome this wirh some kind of custom builder. Is there already a release date in plan? Thanks a lot!

**Comment by MaceWindu** [comment]
It should be released next week if we don't find any blocking issues.
As for custom builder - you are right, we don't expose such API.

**Comment by ili** [comment]
Merge released, closing
