### ISSUE TITLE
Creating column with index (not primary)

### ISSUE THREAD

**Issue by dosh1974** [linq2db/linq2db#808]
Sorry to bring this one up here, but I couldn't find any information about this using google, the wiki or snooping around in the source.

Bet there is something obvious I missed!

When using CreateTable<T> to create a table, is there any way to specify that a column should be indexed?
For instance, the TimeStamp column in this class:

```cs
    [Table("Records")]  // <= Attribute or property to make a more complex index?
    public sealed class Record
    {
        [Column(CanBeNull = false, IsPrimaryKey = true, IsIdentity = true)]
        public long RecordId;

        [Column(CanBeNull = false)] // <= Attribute or property to make a simple index?
        public DateTime TimeStamp;

        [Column(DataType = DataType.VarChar, Length = 64, CanBeNull = false)]
        public String Data;
    }
```

If not would it be possible to add something like an [Index] attribute (or boolean flag on the Column attribute).
For more control and complex Index types, I guess that a list of Indexes could be supplied to the CreateTable<T> method!?

**Comment by ili** [comment]
Sorry for long answer.

No we do not support this scenario. In general `CreateTable` has only basic functionality to use it for temporary tables. It is not one for database creation, schema migration & so on.

If you do need now you can create index manually with [Execute](https://linq2db.github.io/api/LinqToDB.Data.DataConnectionExtensions.html#LinqToDB_Data_DataConnectionExtensions_Execute__1_LinqToDB_Data_DataConnection_System_String_) extension method

**Comment by sdanyliv** [comment]
Closing that. Looks like it is already answered.
