### ISSUE TITLE
Update linq2db.core solution from .xproj files to .csproj to add VS2017 support

### ISSUE THREAD

**Issue by VadimGatsura** [linq2db/linq2db#816]
Are you plan to update linq2db.core solution from .xproj projects with project.json files to .csproj to add VS2017 support for .Net Core solution?

Advantages of using .csproj project for .Net Core:
1. First of all, .xproj projects are no longer supported.
2. .Net Standard 2.0 contains DataTable type. Targeting of linq2db.core to .Net Standard 2.0 will allow to use SchemaProvider in .Net Core solutions.

I already tried to update linq2db.core solution, but faced with some issues:
1. Microsoft.Net.Test.Sdk doesn't support .Net Framework 4.0. It can be fixed by removing target to net40 for linq2db.core package or rewriting unit tests with another testing framework.
2. Type Binary from System.Data.Linq in LinqDataTypes not accessible in .Net Standard. It can be fixed by introducing #if !NETSTANDARD directive or deleting Binary field from test models.

I could help with moving to VS2017 for .Net Core solution, but it is necessary to choose the most acceptable ways to solve foregoing issues.

**Comment by MaceWindu** [comment]
We are currently working on the same task for version 2.0. You can check version2 branch.
If you want to help us with this task we can invite you to our development channel in slack to discuss details.

**Comment by VadimGatsura** [comment]
I would like to help you with the task. My username in Slack is @vadimgatsura

**Comment by ili** [comment]
@VadimGatsura it's very easy! you can make pull request to `version2` branch.  Core solution there is ported to vs2017, it is buildable, tests are runnable.
It would be great if can implement Standard 2.0 support. I do have this in plans, but less time (((

**Comment by ili** [comment]
in process
