### ISSUE TITLE
Function on parameter pre-evaluated

### ISSUE THREAD

**Issue by adams85** [linq2db/linq2db#819]
E.g.

```
var name = "Some Category";
ctx.Categories.Where(c => c.Name.ToLower() == name.ToLower())
```

evaluates to

```
-- DataContext MySql
DECLARE @p1 VarChar(13) -- String
SET     @p1 = 'some category'

SELECT
	`t1`.`Id`,
	`t1`.`Name`
FROM
	`categories` `t1`
WHERE
	Lower(`t1`.`Name`) = @p1
```

_name.ToLower()_ is evaluated at the time of sql generation. I assume this is by design but I don't think it's a good idea. .NET and the db engine use a different algorithm (in the particular case the function result depends on the current CultureInfo in .NET but on the collation set on db side). I think the only fail-safe solution is to use DB functions whenever it's possible:

```
-- DataContext MySql
DECLARE @p1 VarChar(13) -- String
SET     @p1 = 'Some Category'

SELECT
	`t1`.`Id`,
	`t1`.`Name`
FROM
	`categories` `t1`
WHERE
	Lower(`t1`.`Name`) = Lower(@p1)
```

This should be at least a configurable behavior. 

(Forget me if I missing something because I'm quite new to linq2db. Apart from this I'm really impressed with your project so far. Keep up the good work!)

linq2db version: *1.8.3*

**Comment by MaceWindu** [comment]
You can use Sql.Lower/Upper functions to state your intent explicitly, otherwise linq2db will choose server/client-side execution based on context

**Comment by adams85** [comment]
I tried

```
ctx.Categories.Where(c => Sql.Lower(c.Name) == Sql.Lower(name));
```
but it resulted in the same sql. (Using v1.8.3.)

**Comment by MaceWindu** [comment]
Looks like calculation still done on client-side. 
Try to wrap call into Sql.AsSql to prevent it.

**Comment by adams85** [comment]
Ok, the following version works:

```
ctx.Categories.Where(c => c.Name.ToLower() == Sql.AsSql(name).ToLower())
```

However, having to wrap all the parameters for function calls in Sql.AsSql() calls is somewhat cumbersome and error-prone. I suggest the following behavior, which is more suitable imo: if not wrapped, the expression should be evaluated on server side (even such simple ones like 1 + 2). If the expression cannot be mapped, an exception should be thrown. Only if forced evaluation is intended, should the expression be wrapped in something like Sql.Evaluate() . Obviously, this would be a breaking change, but it would be great to see it in 2.0.

**Comment by adams85** [comment]
I've checked out the latest RC of v2. Still the same behavior.

Any chance to address this in V2?

**Comment by sdanyliv** [comment]
@adams85, will try to handle this. 
Thanks.

**Comment by adams85** [comment]
Thanks for the fast reply!

Currently I need to use an ugly workaround (involving an IQueryable + IQueryProvider decorator and an ExpressionVisitor to rewrite the queries automatically), it'd be great if I could get rid of this bloat! :)

If I may suggest, you could  keep the original behavior as default so no breaking change would be introduced and add a configuration setting by which eager evaluation can be turned off.

**Comment by sdanyliv** [comment]
If it is not critical, i'll return to this task after implementing OUTPUT for DML operations.

**Comment by adams85** [comment]
Sure, I'd just have found out if I can expect this feature in V2.
