### ISSUE TITLE
select by dynamic primary key

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#840]
I'm trying to create base abstract class for my repositories. The problem is that all of my primary key columns in tables are defined as **table name** + **id** and because of that I cannot have "BaseEntity" class for my models.

My table:
```
table Person
(
    PersonId int,
    ...
)
```
What I'm trying to do:
```
public virtual async Task<T> Get( Guid id )
{
    using ( var db = new DbContext( context.ConnectionString ) )
    {
        return await db.GetTable<T>().FirstOrDefaultAsync( x => **WHAT TO DO HERE** == id );
    }
}
```
Is there any way this could be done?

**Comment by sdanyliv** [comment]
1. You can correct property names before generation `GetColumn("Person", "PersonID")    .MemberName   = "ID";` - sample from here https://github.com/linq2db/t4models
2. You can use the following solution
```c#
		public interface IEntityWithId
		{
			int Id { get; }
		}

		[Table("Person")]
		class PersonEntity : IEntityWithId
		{
			[Column]
			public int PersonId;

			[Column("PersonId")]
			public int Id { get; set; }
		}

		T GetById<T>(IDataContext db, int id)
			where T: class, IEntityWithId
		{
			return db.GetTable<T>().Where(r => r.Id == id).FirstOrDefault();
		}
```
These properties can be generated in T4 also.

**Comment by stsrki** [comment]
I have found another solution. This way I don't need to touch any of my models.

First in my abstract class:
```
public virtual async Task<T> Get( TKey id )
{
    using ( var db = new DbContext( context.ConnectionString ) )
    {
        return await db.GetTable<T>().FirstOrDefaultAsync( PrimaryKeyPredicate( id ) );
    }
}

protected abstract Expression<Func<T, bool>> PrimaryKeyPredicate( TKey id );
```
and then in my implementation class:
```
protected override Expression<Func<Database.Common.Department, bool>> PrimaryKeyPredicate( Guid id )
{
    return x => x.DepartmentId == id;
}
```

**Comment by sdanyliv** [comment]
Great ;) So closing then.
