### ISSUE TITLE
Using the template scripts on a SQL Server database with many schemas

### ISSUE THREAD

**Issue by bryan-c-oconnell** [linq2db/linq2db#844]
I'm wondering if anyone has advice on using the template scripts against a SQL Server database with many schemas. I 'm using linq2db 1.9, and the scripts run just fine, but when they finish I end up with a bunch of duplicate ITable<> definitions and other naming conflicts because the folks who designed the database have tables in different schemas that share the same table name. For example, there's a dbo.Answers table and a log.Answers table, and sometimes even an old.Answers table as well. The database has 7 schemas right now, and unfortunately I'm not able to modify its structure at all to get around the problem.

I'm hoping someone else has run into this situation and can give me some guidance. I'm hoping to find a way to do one of the following:

- A way to just output a data model for the default (dbo.) schema, or a single specified schema.
- A way to output everything as it does now, but include a schema prefix on the table name. Using the sample above, this means I'd get properties for both an ITable<dboAnswers> and ITable<logAnswers> in the data model file.

**Comment by sdanyliv** [comment]
There are two options, that can be set in your T4 file:
```cs
GetSchemaOptions.ExcludedSchemas = new[] { "TestUser", "SYSSTAT" }; // Defines excluded schemas.
GetSchemaOptions.IncludedSchemas = new[] { "TestUser", "SYS" };     // Defines only included schemas.
```
Other availaible options can be found here: https://github.com/linq2db/t4models

**Comment by bryan-c-oconnell** [comment]
Tried it out this morning and `GetSchemaOptions.IncludedSchemas` did the trick for me. Thanks for your help @sdanyliv!
