### ISSUE TITLE
Possibly wrong SQL with ExpressionPredicate

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#845]
First I must say that the final result is working as expected. But when I tried to see generated SQL through _SQL Server Profiler_ I think that it have unnecessary _NOT Boolean_ expression.

This is my ExpressionPredicate
`public static Expression<Func<Employee, Department, bool>> DepartmentPredicate => ( e, d ) => e.DepartmentId == d.DepartmentId && !d.Deleted;`

And this is generated SQL
```
SELECT
*
FROM
    [Common].[Employee] [t4]
    LEFT JOIN [Common].[Department] [t1] ON [t4].[DepartmentId] = [t1].[DepartmentId] AND NOT (1 = [t1].[Deleted])
```
Notice `NOT (1 = [t1].[Deleted])`.
I think this should be `0 = [t1].[Deleted]`.

Any thoughts on this?

### Environment details
linq2db version: *1.9.0*  
Database Server: *SQL Server*  
Framework version: *.NET Framework 4.6.1*

**Comment by MaceWindu** [comment]
Retested it. Right now we generate `1 <> field` condition, but agree that we should use comparison with 0 for boolean values, to avoid issues with badly-typed data.
@sdanyliv could we cover it with conditions refactoring you are working on?

**Comment by sdanyliv** [comment]
It should be, i’m also do not like such condition.

**Comment by stsrki** [comment]
Sometimes in legacy databases boolean fields are not exactly bit or boolean, but int or byte instead. In those situations I understand the check `<> 0`.

**Comment by sdanyliv** [comment]
Anyway it is 1 or 0, we just have to use appropriate comparison in such case.

**Comment by arwyl** [comment]
copy from #1662:

> That may not seem as a big deal, but sometimes MS SQL server doesn't use indexes, when it sees something like "1 <> [x].[SomeBoolProperty]". I cannot figure why, but on two servers
> (both has Microsoft SQL Server 2016 (SP2-CU6) (KB4488536) - 13.0.5292.0 (X64), one has production DB, the other has it's yesterday backup) the same query is planned differently (index is used on test server, not used on prod server)
>

**Comment by MaceWindu** [comment]
Another voice to use 0 as baseline. Working on Access ODBC driver support I've discovered that it is not always 1 or 0... it could be -1 and 0
