### ISSUE TITLE
InsertOrUpdate (InsertOrReplace) vs Merge

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#850]
Hello,

Is the merge api also a better replacement for the InsertOrUpdate method? Or better said, is the InsertOrUpdate theoretically obsolete now?

**Comment by ili** [comment]
I think we'll keep both variants for now. May be in future we'll make `InsertOrReplace` obsolete or redirect it's implementation to Merge API (there is such possibility now for few providers...)

**Comment by Franki1986** [comment]
Thanks for explanation!
