### ISSUE TITLE
Custom Expression for Firebird max items restriction

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#853]
Hello,

as you know Firebird is limited to 1500 items in a 'where in' expression.
So I would like to create a custom expression for an In-Expression where I split the items count in 1500 tuples. I started with your example:

```
[ExpressionMethod("InImpl")]
      public static bool In<T>(this T item, IEnumerable<T> items)
      {
         if (items.Count() <= 1499)
         {
            return items.Contains(item); // this code will run if we execute the method locally   
         }
       
         // Split where in in 100 tuples..
         int rest = items.Count() % 100;
         int count = items.Count() / 100;
         IEnumerable<T> splitted;
         for (int index = 0; index < count; index++)
         {
            splitted = items.Skip(index * 100).Take(100).ToList();
            if (splitted.Contains(item))
            {
               return true;
            }
         }
         // Load the rest
         splitted = items.Skip(count * 100).Take(rest).ToList();
         return splitted.Contains(item);
      }

      public static Expression<Func<T, IEnumerable<T>, bool>> InImpl<T>()
      {
         // LINQ to DB will translate this expression into SQL
         // (it knows out of the box how to translate Contains()
         //return (item, items) => items.Contains(item);
      }
```

The first method that runs local should work, but how to do this in the second method where not a bool is returned but an Expression?

**Comment by sdanyliv** [comment]
Maybe better to create temporary table, bulk copy items to that table, and then join?

**Comment by Franki1986** [comment]
Yeah, but I would like to create something more generic.. 
I think it is even better to not always wirite to the DB. Like I said, the first method localy works, but I don't know how to make it run in the InImpl-method so that I can loop the items..

**Comment by sdanyliv** [comment]
I can not see possibility to do it in that way. 

You can:
- create generic method that uses temporary table (easy to implement)
`public IList<T> FilterByKeys<T, TKey>(IQueryable<T> source, Expression<Func<T, object>> prop IEnumerable<TKey> keys)`
- create generic method with the same signature that runs N queries and collect them in list 

Obviously first solution should be faster.

**Comment by sdanyliv** [comment]
Closing, already answered.

**Comment by Franki1986** [comment]
Hello @sdanyliv,

I came across this another time.
But I have problems to implement the first method you mentioned 'FilterByKeys'.
The problem is I don't know what the method would look like?
