### ISSUE TITLE
After GroupBy materialization not work

### ISSUE THREAD

**Issue by SergeyKabaev** [linq2db/linq2db#855]
Использую шаблон Репозитарий.
Данные для сложного объекта запрашиваются вот так:

            using (var db = GetConnection())
            {
                    db.BeginTransaction(IsolationLevel.ReadUncommitted);
                    var users = db.GetTable<User>()
                        .AsEnumerable();
                    ...

                    var userRoleLookups = db.GetTable<UserRole>()
                        .GroupBy(userRole => userRole.UserId)
                        .AsEnumerable().ToList() // AsEnumerable и ToList не работают
                        .ToDictionary(item => item.Key, item => item.AsEnumerable());
                    .....
                    users.ForEach(user =>
                    {
                        ...
                        user.CoreUsers = coreUserLookups.TryGetOrDefault(user.Id);
                        ...
                    });

                    db.CommitTransaction();
           }

Данный код успешно отрабатывает, соединение закрывается, но далее при запросе элементов
коллекции  user.CoreUsers получаю exception о закрытом DataConnection.
После GroupBy() ни ToList(), ни AsEnumerable(), ни ToDictionary() коллекцию не материализуют.

Если поменять местами строки
                        .GroupBy(userRole => userRole.UserId)
                        .AsEnumerable().ToList() 
и материализовать коллекцию ДО группировки, то ошибки не происходит.

If you are seeing an exception, include the full exceptions details (message and stack trace).
### Environment details
linq2db version: *1.9.0*  
Database Server: SqlServer
Operating system: Windows 10
Framework version: NET Framework 4.5

**Comment by sdanyliv** [comment]
It's not a SQL, you are trying to group items and then get list of them grouped in collections.
In your situation you have to group items on client side.

```cs
               var userRoleLookups = db.GetTable<UserRole>()
                    .AsEnumerable()
                    .GroupBy(userRole => userRole.UserId)
                    .ToDictionary(item => item.Key, item => item.ToList());
```

**Comment by SergeyKabaev** [comment]
ok

**Comment by sdanyliv** [comment]
It's well known mistake when using linq2db.
We even have guard to protect from such kind of queries.
https://github.com/linq2db/linq2db/blob/af6f22acf05d2cbfa7ca8a9d360ffa1419561dcb/Source/Common/Configuration.cs#L125
