### ISSUE TITLE
field-mapper error

### ISSUE THREAD

**Issue by SergeyKabaev** [linq2db/linq2db#857]
Sql table 

```sql
CREATE TABLE brn_awhds.dbo.t_Skill_Group (
  SkillTargetID INT NOT NULL
  ......
 )
```

My data model

    public class CoreSkillGroup
    {
        [Column]
        public int SkillTargetId { get; set; }
        ......
    }

Query

        public IEnumerable<CoreSkillGroup> GetSkillGroups()
        {
            using (dbConnection = ....)
            {
                return ExecuteQuery((conn) => conn.Query<CoreSkillGroup>(
                    " SELECT                                     " +
                    "   tsg.SkillTargetId                        " + // if tsg.SkillTargetId - field always is 0, if tsg.SkillTargetID - OK
                    ....
                    " FROM brn_awhds.dbo.t_Skill_Group AS tsg    ")
                   .ToList());
            }
        }

After query execution property CoreSkillGroup.SkillTargetId always equal 0.
If i change property name to SkillTarget_ID_, then this property have normal values.
I think that the mapper has a problem when linking sql-fields and object property if their names differ at the case-sensitive level.

### Environment details
linq2db version: *1.9.0*  
Database Server: SqlServer
Operating system: Windows 10
Framework version: NET Framework 4.5

**Comment by igor-tkachev** [comment]
linq2db does not  support case-sensitive mapping in this case.

**Comment by SergeyKabaev** [comment]
ok, thanx
