### ISSUE TITLE
Increment value in row with one query

### ISSUE THREAD

**Issue by WhiteBearSpirit** [linq2db/linq2db#864]
Question: how can I increment one value in one row with one query?
Let's say I have following table:
`create table Orders
(
  OrderId int not null,
  Quantity int not null
);
insert into Orders values (1, 0);`

In SQL I can make query `UPDATE Orders SET Quantity = Quantity + 1 WHERE OrderId = 1;`

How can I achieve that using linq2db?
`db.Orders
    .Where(o => o.OrderId == 1)
    .Set(o => o.Quantity, /* o.Quantity + 1  -- o does not exist in current context */)
    .Update();`

**Comment by rameel** [comment]
```cs
db
    .Orders
    .Where(o => o.OrderId == 1)
    .Set(o => o.Quantity, o => o.Quantity + 1)
    .Update();
```
and you can try this
```cs
db
    .Orders
    .Where(o => o.OrderId == 1)
    .Update(o => new Order {Quantity = o.Quantity + 1});
```

**Comment by WhiteBearSpirit** [comment]
Thank you, both expressions work perfect, updating only what I want!

**Comment by xlievo** [comment]
How to do null conversion?

create table Orders ( OrderId int, Quantity int ); insert into Orders values (1, null);

db
    .Orders
    .Where(o => o.OrderId == 1)
    .Set(o => o.Quantity, o => Sql.Convert<int, int?>(0, x.Quantity) + 1)
    .Update();
