### ISSUE TITLE
linq2db.core nuget packe bad strong name

### ISSUE THREAD

**Issue by Centurys** [linq2db/linq2db#867]
Hi,

I have been trying to debug web project with linq2db.core library and keep getting error that strong name verification failed:
Could not load file or assembly 'linq2db' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
Then I checked with sn.exe tool:
...\packages\linq2db.Core.1.9.0\lib\net45>sn -v linq2db.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.

Verification of linq2db nuget package is OK:
...\packages\linq2db.1.9.0\lib\net45>sn -v linq2db.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'linq2db.dll' is valid 

Can you double check strong name or better remove it from assemblies :)

### Environment details
linq2db version: 1.9.0
Operating system: Windows 10 
Framework version: .NET Framework 4.6.1

**Comment by Centurys** [comment]
Any plans?
It's a bit boring to copy assembly from other nuget package to deployment environment :)

**Comment by sdanyliv** [comment]
It will be OK if we remove signing for linq2db.core.dll?
Looks like old tooling has some problems.

**Comment by Centurys** [comment]
Yes strong name (signing) removal I think is the best option.
There are many discussions on way its usable, but basically if you don't use GAC (full framework) then there no need to use strong name.

**Comment by sdanyliv** [comment]
We will remove signing in current versions of linq2db core. It will be enabled in version2 which uses new tooling.

**Comment by Centurys** [comment]
Good to hear, will wait for release.
But I don't see why you need to keep strong name in the future?
