### ISSUE TITLE
Output clause in DELETE, INSERT, UPDATE and MERGE

### ISSUE THREAD

**Issue by aleks42** [linq2db/linq2db#869]
Merge in mssql can return affected rows with "output_clause". Are there any plans to support it in Merge API?

**Comment by sdanyliv** [comment]
It is duplicate issue for #797
No milestone yet for implementing this feature.

**Comment by igor-tkachev** [comment]
Output clause is used also in DELETE, INSERT, and UPDATE statements. So, I think we should consider them as well.

DB2 supports something similar - FROM FINAL TABLE.
Oracle, PostgreSQL - RETURNING

**Comment by genusP** [comment]
InsertWithOutput, InsertWithOutputInto for MSSQL  #1703

**Comment by MaceWindu** [comment]
DELETE support added in rc2: https://github.com/linq2db/linq2db/pull/2284
UPDATE support is currently in work: https://github.com/linq2db/linq2db/pull/2321
MERGE: not started yet

**Comment by MaceWindu** [comment]
Remaining providers support PR: #3328 (except query from `returning` for pgsql)
