### ISSUE TITLE
Error GenerateModel code for postgresql

### ISSUE THREAD

**Issue by yuzd** [linq2db/linq2db#871]
![image](https://user-images.githubusercontent.com/16083659/31343454-438bbf84-ad42-11e7-93ff-dfd565c05b62.png)

![image](https://user-images.githubusercontent.com/16083659/31343534-778357a2-ad42-11e7-9563-32ada273975a.png)

![image](https://user-images.githubusercontent.com/16083659/31343513-6b59446e-ad42-11e7-8754-048a44f04c0b.png)

**Comment by sdanyliv** [comment]
@yuzd, unusual situation here. PostgreSQL should not allow to create FK Constraints with same name within schema.

**Comment by yuzd** [comment]
@sdanyliv 

I read the code about generate the fks for models.
“key” should be unique.
And no matter what the “key” is Will not affect.
So I made the following modification.
![image](https://user-images.githubusercontent.com/16083659/31719745-09a7ce96-b447-11e7-9ecb-b349be63fe95.png)

What do you think of it.does there is a problem?

**Comment by sdanyliv** [comment]
I'll check this tomorrow. BTW, can you post script for these three tables with Fk's?

**Comment by yuzd** [comment]
CREATE TABLE public.t_driver_allowance_config
(
  guid character varying(36) NOT NULL, -- GUID
  driver_kpi_config_guid character varying(36) NOT NULL, 
  allowance numeric NOT NULL, 
  online_duration numeric, 
  is_delete boolean, 
  CONSTRAINT pk_t_driver_allowance_config PRIMARY KEY (guid),
  CONSTRAINT fk_t_driver_reference_t_driver FOREIGN KEY (driver_kpi_config_guid)
      REFERENCES public.t_driver_kpi_config (guid) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);

CREATE TABLE public.t_driver_bonus_config
(
  guid character varying(36) NOT NULL,
  driver_kpi_config_guid character varying(36) NOT NULL,
  bonus numeric, 
  start time without time zone, 
  "end" time without time zone, 
  is_delete boolean, 
  CONSTRAINT pk_t_driver_bonus_config PRIMARY KEY (guid),
  CONSTRAINT fk_t_driver_reference_t_driver FOREIGN KEY (driver_kpi_config_guid)
      REFERENCES public.t_driver_kpi_config (guid) MATCH SIMPLE
      ON UPDATE RESTRICT ON DELETE RESTRICT
)
WITH (
  OIDS=FALSE
);

CREATE TABLE public.t_driver_kpi_config
(
  guid character varying(36) NOT NULL,
  basic_allowance numeric NOT NULL,
  allow_reject integer, 
  allow_overstep integer,
  create_date timestamp without time zone,
  is_delete boolean, 
  CONSTRAINT pk_t_driver_kpi_config PRIMARY KEY (guid)
)
WITH (
  OIDS=FALSE
);

**Comment by sdanyliv** [comment]
I've reproduced problem and prepared PR. I hope it may help to fix many other similar problems.

**Comment by yuzd** [comment]
thanks
