### ISSUE TITLE
DB2 Connectivity in .Net

### ISSUE THREAD

**Issue by SipunGit** [linq2db/linq2db#874]
As mentioned i have copied CopyMe.DB2.tt.txt file and placed it in my model folder then i have removed the .txt extension and changed the LoadDB2Metadata("MyServer", "50000", "MyDatabase", "MyUser", "TestPassword"); method by providing my connection details.When i save this .tt file it creates all the tables entities but when i call the db object it throws me an error in generated.cs class.The error throws near the default constructor(	public MyDatabaseDB()
{
InitDataContext();
}) like "Object reference not set to an instance of object".This is challenging and i am facing this issue for more than a week now.Please let me know if there is any fix for the same.Also i need to know the way to call a schema which is not default because now it creates entities by targeting to default schema.

**Comment by sdanyliv** [comment]
Please provide with call stack an full error message.
As mentioned here https://github.com/linq2db/t4models
You can control which schema should be used.
```cs
GetSchemaOptions.ExcludedSchemas = new[] { "TestUser", "SYSSTAT" }; // Defines excluded schemas.
GetSchemaOptions.IncludedSchemas = new[] { "TestUser", "SYS" };     // Defines only included schemas.
```

**Comment by SipunGit** [comment]
Server Error in '/' Application.

Object reference not set to an instance of an object. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 



Line 37: 		public ITable<XACTEVENTMONTBL>        XACTEVENTMONTBL        { get { return this.GetTable<XACTEVENTMONTBL>(); } }
Line 38: 
Line 39: 		public CGRDBDB()
Line 40: 		{
Line 41: 			InitDataContext();
  

 Source File:  C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\Linq2DbModel\PlanMatchWeb.generated.cs    Line:  39 

Stack Trace: 



[NullReferenceException: Object reference not set to an instance of an object.]
   LinqToDB.Data.DataConnection..ctor(String configurationString) in c:\projects\linq2db\Source\Data\DataConnection.cs:69
   LinqToDB.Data.DataConnection..ctor() in c:\projects\linq2db\Source\Data\DataConnection.cs:36
   PlanMatchWebAPI.Linq2DbModel.CGRDBDB..ctor() in C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\Linq2DbModel\PlanMatchWeb.generated.cs:39
   PlanMatchWebAPI.Controllers.HomeController.Index() in C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\Controllers\HomeController.cs:16
   lambda_method(Closure , ControllerBase , Object[] ) +61
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9744373
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

  


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1099.0

**Comment by SipunGit** [comment]
**After using ExcludedSchemas getting the below error while generating the model.**

Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LinqToDB.DataProvider.DB2.DB2LUWSchemaProvider.<GetForeignKeys>b__ce(<>f__AnonymousType1b`5 fk)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.DataProvider.DB2.DB2LUWSchemaProvider.GetForeignKeys(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating2D0B55B00D7D7AE09C22CE9420BB6118E42D98FA2E0646D03D1E79853F221335A9EA7373D2979546BB035879B70F332E63FD222E9E9B632B855399E01469A363.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\LinqToDB.Templates\DataModel.ttinclude:line 91
   at Microsoft.VisualStudio.TextTemplating2D0B55B00D7D7AE09C22CE9420BB6118E42D98FA2E0646D03D1E79853F221335A9EA7373D2979546BB035879B70F332E63FD222E9E9B632B855399E01469A363.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\LinqToDB.Templates\DataModel.ttinclude:line 361
   at Microsoft.VisualStudio.TextTemplating2D0B55B00D7D7AE09C22CE9420BB6118E42D98FA2E0646D03D1E79853F221335A9EA7373D2979546BB035879B70F332E63FD222E9E9B632B855399E01469A363.GeneratedTextTransformation.LoadDB2Metadata(String server, String port, String database, String uid, String password) in C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\LinqToDB.Templates\LinqToDB.DB2.ttinclude:line 26
   at Microsoft.VisualStudio.TextTemplating2D0B55B00D7D7AE09C22CE9420BB6118E42D98FA2E0646D03D1E79853F221335A9EA7373D2979546BB035879B70F332E63FD222E9E9B632B855399E01469A363.GeneratedTextTransformation.TransformText() in C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\Linq2DbModel\PlanMatchWeb.tt:line 48	PlanMatchWebAPI	C:\Users\AF48331\Documents\rhimedicareplanmatch\PlanMatchWebAPI\LinqToDB.Templates\DataModel.ttinclude	91

**Comment by sdanyliv** [comment]
Not sure (away from computer) but looks like you have problem with configuration n Web.config which is required.

**Comment by sdanyliv** [comment]
With T4. Exception is possible if you have excluded schema with table that is part of foreign key. Will handle it later.

**Comment by SipunGit** [comment]
If i have a problem with web.config file then i believe it should not create the entities for default schema.

**Comment by sdanyliv** [comment]
T4 templates have own connection mechanism, application should have it's own. Read tt file from start. I has all needed instructions.
T4 templates were designed to use without linq2db also, to just generate entities from database.
Linq2db requires config file or defining connection in runtime.

**Comment by SipunGit** [comment]
I am still getting that error.Do i need to update the Linq2db dll from Nuget?

**Comment by sdanyliv** [comment]
Please checkout linq2db sources and add linq2db.csproj project to your solution (it should be easy). Add reference to this project and debug what happened.
I've reviewed our current sources no NullReference exception should appear.

**Comment by sdanyliv** [comment]
Looks like it is duplicate for #906
