### ISSUE TITLE
Operand error: double precision % integer with PostgreSQL

### ISSUE THREAD

**Issue by ws77** [linq2db/linq2db#882]
Hello,

I'm using DevExpress with linq2db.
When grouping data in a pivotgrid in DevExpress it generates automatic linq code to retrieve data.
This linq expression is then translated to sql.
Here is a simple example for the sql command generated by linq2db:
SELECT Extract(DOY from t1."BeginDate") % 7 FROM "public".MyTable t1

The exceution of this query then produces the described error.
```
Error message:
Npgsql.PostgresException: "42883: Operator not existing: double precision % integer"
```
To fix it, I changed the "Extract({0} from {{0}}" string for Sql.DatePart(PN.PostgreSQL, ...) in "Sql.cs"
to "Cast(Extract({0} from {{0}}) as int)" as Postgres cannot do a modulo operation on a double precision result.
With the fix the result is a int and the modulo operator is working.

Is it possible to fix this error in the next version?

### Environment details
linq2db version: 1.9.0
Database Server: PostgreSQL 9.6.4
Database Provider: Npgsql 3.2.3
Operating system: Windows 10
Framework version: .NET Framework 4.5

**Comment by sdanyliv** [comment]
@ws77, can you provide original linq query? Datepart is generated by grid?

**Comment by ws77** [comment]
Unfortunately I don’t have the original linq query, as I do not have the source code from DevExpress.
The complete query is generated by the grid.

I think, the problem is the combination of the datepart function with the following modulo operand, as the generated sql statement contains both.
A sql statement with a datepart and without a modulo is no problem.



Von: Svyatoslav Danyliv [mailto:notifications@github.com]
Gesendet: Freitag, 20. Oktober 2017 11:15
An: linq2db/linq2db <linq2db@noreply.github.com>
Cc: Schmidl Stefan <Stefan.Schmidl@fee.de>; Mention <mention@noreply.github.com>
Betreff: Re: [linq2db/linq2db] Operand error: double precision % integer with PostgreSQL (#882)


@ws77<https://github.com/ws77>, can you provide original linq query? Datepart is generated by grid?

**Comment by sdanyliv** [comment]
Working on fix. Will be delivered soon.
