### ISSUE TITLE
HANA 2.0 SP2

### ISSUE THREAD

**Issue by ldzierza** [linq2db/linq2db#887]
Hello
I'm looking for linq2db for HANA 2.0 SP2.

Can you help me?

Thank you
Lech

**Comment by sdanyliv** [comment]
@ldzierza, some problems?

**Comment by MaceWindu** [comment]
@ldzierza, linq2db works with SAP HANA 2.0 (we even run tests against it). If you have any specific problem with it, feel free to create an issue and we will look into it.
