### ISSUE TITLE
InsertWithIdentity exception for Access provider

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#888]
Hello,
  if I try to insert a new record in the table Group that contains only one field named ID, the autoincrement key.
  The vb code is:

`Dim groupId = db.Groups.InsertWithIdentity(Function() New Group)`

I get this exception:

```
Si è verificata l'eccezione LinqToDB.Linq.LinqException
  HResult=0x80131500
  Messaggio='new Group()' cannot be converted to SQL.
  Origine=linq2db
  Analisi dello stack:
   in LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   in LinqToDB.Linq.Builder.UpdateBuilder.BuildSetter(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext sequence)
   in LinqToDB.Linq.Builder.InsertBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   in LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   in LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   in LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   in LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   in LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   in LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   in LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   in LinqToDB.LinqExtensions.InsertWithIdentity[T](ITable`1 target, Expression`1 setter)

```

### Environment details
linq2db version: *1.9.0*  
Database Server: *Access 2016*  
Database Provider: *Microsoft.ACE.OLEDB.12.0*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7*

Regards,
  Filippo.

**Comment by sdanyliv** [comment]
@filippobottega, strange, it should work. But try oveload function without `Function()`

**Comment by filippobottega** [comment]
Hello Svjatoslav,
  if add a new field on the Group table, named Dummy, the subsequent statement works well:

Dim groupId = db.Groups.InsertWithIdentity(Function() New Group With {.Dummy = String.Empty})

  Sorry but I don't understand your sentence: "try oveload function without Function()".

  Regards,
    Filippo.

**Comment by sdanyliv** [comment]
Just insert new object
```vb
db.Groups.InsertWithIdentity(New Group)
```

**Comment by filippobottega** [comment]
If I write:

` Dim groupId = db.Groups.InsertWithIdentity(New Group)`

![2017-10-24 17_32_35-pdfdatamining - microsoft visual studio](https://user-images.githubusercontent.com/2587684/31952646-66e2ecfa-b8e1-11e7-926f-73ad98fc6eaf.png)


I get the error:

`Errore	BC30311	Non è possibile convertire il valore di tipo 'Group' in 'Expression(Of Func(Of Group))'.`

(Sorry for the italian language...)

**Comment by sdanyliv** [comment]
My fault (typing from iPad)

```vb
Dim groupId = db.InsertWithIdentity(New Group)
```

**Comment by filippobottega** [comment]
Thank you! It works!

**Comment by sdanyliv** [comment]
I think problem that INSERT sql statement neds something to insert. In previous version you have tried to insert "nothing" into Group. 
Will check it tomorrow.

**Comment by sdanyliv** [comment]
Same as #891
