### ISSUE TITLE
Access BulkCopy create empty rows

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#891]
Hello,
  when I use BulkCopy extension, empty rows are created.
  The number of rows created is correct but data is empty even if source is an array of not empty data.
  The rows are created in the correct table.

```vb
  ' groupFiles is an array of GroupFile objects
  db.BulkCopy(groupFiles)
```

### Environment details
linq2db version: 1.9.0
Database Server: Access 2016
Database Provider: Microsoft.ACE.OLEDB.12.0
Operating system: Windows 10
Framework version: .NET Framework 4.7

  Regards,
    Filippo.

**Comment by sdanyliv** [comment]
@filippobottega, could you please post table script and group class definition?

**Comment by filippobottega** [comment]
Class definition:

```c#
	[Table("GroupFiles")]
	public partial class GroupFile
	{
		[Identity] public int IDGroup { get; set; } // Long
		[Identity] public int IDFile  { get; set; } // Long
	}
```

Table script:

```sql
create table GroupFiles
(
 IDGroup INTEGER null,
 IDFile INTEGER null
)
```

**Comment by sdanyliv** [comment]
You are expecting that BulkCopy should fill Identity fields? They are marked as identity in database?

**Comment by filippobottega** [comment]
Yes,
  IDGroup and IDFile are together primary key.

**Comment by sdanyliv** [comment]
For which purpose? You are trying to do something unusual.
I'll check why it's not working but looks like you are trying to insert EMPTY records into database again. Identity columns are ignored for insert. So nothing to insert,

**Comment by filippobottega** [comment]
Sorry,
  I have changed my previous comment that was wrong.
  I checked that IDGroup and IDFile are only Numeric fields.
  I have rebuild the generated.cs file and I confirm that IDGroup and IDFile fields has the [Identity] attribute. In the database they are not autonumber fields, they are simple numeric fields.

  Filippo

**Comment by sdanyliv** [comment]
>I have rebuild the generated.cs file and I confirm that IDGroup and IDFile fields has the [Identity] attribute. In the database they are not autonumber fields, they are simple numeric fields.

Just clarification. If [Identity] attribute is set, fields may not be used for inserting. Because linq2db expects that these fields will be filled by Database Engine.

**Comment by filippobottega** [comment]
Thank you for your clarification.
Now I have to understand why Access.tt adds [Identity] attribute to IDGroup and IDFile fields.
There are also other fields signed as [Identity] in other tables but I don't understand how the Access.tt template decides how to add [Identity] to the columns.

**Comment by filippobottega** [comment]
Please note that the statement:
```vb
db.GroupFiles.Insert(Function() New GroupFile With {.IDGroup = groupId, .IDFile = fileID})
```
works well, inserting the values even if the fields are marked as Identity.

**Comment by sdanyliv** [comment]
It may be problem with Access DataProvider or with database.
You can check this line of code: https://github.com/linq2db/linq2db/blob/aac2b54603c8e35609f1cfed0b35b9ad7892b9ca/Source/DataProvider/Access/AccessSchemaProvider.cs#L132

For quick solution just find table and column in your **T4 tt** file and remove IsIdentity from columns:
```cs
GetColumn("GroupFiles", "IDGroup").IsIdentity = false;
GetColumn("GroupFiles", "IDFile").IsIdentity = false;
```

>works well, inserting the values even if the fields are marked as Identity.

It is because in this situation you have forced linq2db to insert these fields.
`Function() New GroupFile With {.IDGroup = groupId, .IDFile = fileID}` is converted to Expression Tree by compiler. Then linq2db analyses this expression and searches for fields to insert. Every field that was mentioned in this expression will be used.

It gives also other benefits. When you need to insert records with current timestamp, you can modify your sample in the following way:

```cs
db.GroupFiles.Insert(Function() New GroupFile With 
  {
     .IDGroup = groupId, 
     .IDFile = fileID, 
     .WhenInserted = Sql.CurrentTimestamp
  })
```
and linq2db will create insert SQL with `Now` function for filling field `WhenInserted`.

**Comment by filippobottega** [comment]
Thank you very much for your explanation.
I have inserted GetColumn statements in my T4 tt file and the generated.cs file was changed accordingly.
I'll try the BulkCopy as soon as possible even if I have discovered that Access bulk copy is nothing else than a loop over all rows. I don't think that performance will change to much.

Best regards,
  Filippo.

**Comment by sdanyliv** [comment]
Usually we emulate BulkCopy if it is not provided by DataProvider, we think in effective way ;)
Any suggestions are appreciated.

So closing issue for now.

**Comment by filippobottega** [comment]
The best way to import large number of records in Access db is using csv files.
An example in this post: [Importing a CSV file into Access from Command Line](https://www.pcreview.co.uk/threads/importing-a-csv-file-into-access-from-command-line.1675815/)

```vb
Option Explicit

Dim oJet 'DAO.DBEngine
Dim oDB 'DAO.Database
Dim strSQL 'String


strSQL = "SELECT * INTO MyTable FROM
[Text;HDR=Yes;Database=D:\Folder\;].FileName#txt"

Set oJet = CreateObject("DAO.DBEngine.36")
Set oDB = oJet.OpenDatabase("D:\Folder\Database.mdb")

oDB.Execute strSQL

oDB.Close
```

Thank you for your excellent project, I really like linq2db.
  Filippo.
