### ISSUE TITLE
MERGE API support for the PostgreSQL provider

### ISSUE THREAD

**Issue by Eykhler** [linq2db/linq2db#892]
The question to the @MaceWindu: do you plan to add MERGE API support into the PostgreSQL provider?

PostgreSQL support Merge query since v8.4 (https://www.postgresql.org/message-id/attachment/23520/sql-merge.html and https://wiki.postgresql.org/wiki/SQL_MERGE)

It's will be appreciated by community:)

**Comment by sdanyliv** [comment]
@Eykhler, maybe you can create PR for this one? Looks like it is not so difficult to support merge api by analogy with other providers.

**Comment by MaceWindu** [comment]
Yep, no problem. But I'm a bit surprised that PostgreSQL support it. Looks like I missed something.

**Comment by MaceWindu** [comment]
Ok, I've checked it again - Merge is not supported even in v10, so first we need to wait for PostgreSQL developers :)

**Comment by MaceWindu** [comment]
I'm closing it for now, as there is nothing we can do in linq2db at this moment to support it.

**Comment by Eykhler** [comment]
Oops, my bad, I've looked at the developers documentation.
Of course, there are UPSERT (https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT) syntax exists, but I think it's functionality is not the same as MERGE.
