### ISSUE TITLE
Stored procedure call didn't consider InheritanceMappingAttribute

### ISSUE THREAD

**Issue by pmatrosov** [linq2db/linq2db#895]
I need to call a MS SQL stored procedure and map resultset to one of classes inherited from base class using InheritanceMappingAttribute. 
If I use something like 
```
dataConnection.QueryProc<BaseClass>("dbo.SpName", DataParameter("@id", @id, DataType.Int64))
```
I got an error that column XXX not belongs to base class (this is true because it belongs to inherited class). How can I do that with Linq2Db? 
Thanks.

**Comment by sdanyliv** [comment]
It is not currently supported. We may consider to do it in version 2 if it really needed. It may take time to implement.
If `dbo.SpName` is table function it can be done by `TableFunction` attribute. Sample is here:
https://github.com/linq2db/linq2db/blob/f2e0d9f9828daf200ca7681ef518b6e3e9b904ba/Tests/Model/ParentChild.cs#L572

**Comment by pmatrosov** [comment]
Thank you for answer and workaround.
This feature is really needed. We're using Linq2Db at big in-house financial system development (previous version was used BLToolkit). And we decided implement some inheritance with such key types as accounts, transactions because this makes our code much more clearer. Sometimes we're using SPs because of too complex Linq code or lack of some SQL features (CTE etc.)

**Comment by sdanyliv** [comment]
Well, will check how to extract this piece of functionality  from TableBuilder.
In verion 2 we plan to support `FromSql` and `CTE`.
