### ISSUE TITLE
Mapping schema for tables created by ServiceStack.Ormlite

### ISSUE THREAD

**Issue by JamesAtPropertyMe** [linq2db/linq2db#900]
We have a database which was used by ServiceStack.Ormlite.MySql. Any columns of Enum types use the enum's name instead integer as stored value. I know I can write [MapValue("Name")] to make a custom mapping. However, there are quite a few places that I need to write. I would like to write a global MappingSchema that can map them once for all.

Similarly, a column of List<string>() or column of a structure stores the data in JSON format. How can I write some generic code to map any non-primitive types to use JSON serialiser/deserialiser? I suppose I should write all such mapping code in a custom MappingSchema subclass. However, I can't find any examples to do such generic mapping (not specific to any particular type). It will be difficult to manage if I need to list all possible types and apply conversion logic to each of them.

Will someone be able to provide some example code?

**Comment by sdanyliv** [comment]
You don't need to create MappingSchema subclass. You can create DataConnection with your own  once defined schema (there is overload constructor). This schema will be combined with current DataProvider's schema.
Schema can be defined by its own methods or throught FluentMappingBuilder, samples in tests: 
https://github.com/linq2db/linq2db/blob/58a2b1029ef4b56625396f5965cb98667f68de3f/Tests/Linq/Mapping/FluentMappingTests.cs

**Comment by JamesAtPropertyMe** [comment]
Hi Svyatoslav,

Thanks for your reply. I think I didn't explain my requirements clearly. The project has about 100 enum types used in classes that are mapped to tables. The current ORM library, ServiceStack.OrmLite, maps the enum name instead of the integer to the table column. I would like to use Linq2db to connect the same classes to the same tables with little changes.

I have found that I can apply [MapValue("EnumName")] to each value to work. However, that will involve adding such attribute to hundreds of values. I also found that if I call "MappingSchema.Default.SetDefaultFromEnumType(typeof(Enum), typeof(string));",  querying of the columns will be mapped to the object properties successfully. However, when I want to write some filter condition that involves comparing an Enum value, the generated SQL still compares the column with an integer (as a string) instead of the enum name. This is where I'm stuck.

**Comment by sdanyliv** [comment]
If you provide me with small project with that problem i can help you.
* sample enum type
* sample model class
* how do you setup mapping
* linq query that produces wrong filter

**Comment by MaceWindu** [comment]
For enums you need to write custom metadata reader and register it in schema.
Below an example of such mapper that use our custom attributes instead of MapValue attribute. You just need to write your logic to generate MapValueAttribute from enum field name.
```cs
class CustomMapValueReader : IMetadataReader
{
    TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, MemberInfo memberInfo, bool inherit)
    {
        if (typeof(TAttribute).Equals(typeof(MapValueAttribute)))
        {
            var ret = new List<Attribute>();
            ret.AddRange(memberInfo.GetCustomAttributes(typeof(MapObjectValueAttribute), false)
                .OfType<MapObjectValueAttribute>().Select(_ => _.UnderlyingAttribute));
            return ret.OfType<TAttribute>().ToArray();
        }

        return Array.Empty<TAttribute>();
    }

    TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, bool inherit)
    {
        return Array.Empty<TAttribute>();
    }
}
```

And use:
```cs
MappingSchema.Default.AddMetadataReader(new CustomMapValueReader());
```

**Comment by JamesAtPropertyMe** [comment]
@MaceWindu Thanks for providing this code example. In this example, it seems that I still need to apply the custom attribute to all enums in the project. What I want to achieve is actually not touching each individual enums because there are about 100 enums in the project. Actually, `MappingSchema.Default.SetDefaultFromEnumType(typeof(Enum), typeof(string));` 80% fulfils my needs. It does help to make linq2db to use enum field names in the query result and inserting values. The broken part is the query filtering. The generated SQL still uses integers to do comparison. @sdanyliv I have created an example project which is [available here](https://github.com/JamesAtPropertyMe/ServiceStackLinq2DbSample):  

In the example, I have an entity definition like this:

```CSharp
[Table("ExampleEntity")]
public class ExampleEntity
{
   [PrimaryKey, Column(DbType = "char(36)"), NotNull]
   public Guid Id { get; set; }

    [Column(DbType = "varchar(50)"), NotNull]
    public EntityType Type { get; set; }

    [Column(DbType = "varchar(255)")]
    public string Detail { get; set; }
}

public enum EntityType
{
    Unknown,
    TypeA,
    TypeB
}
```

When I insert records into the table ExampleEntity using:
```CSharp
var data1 = new ExampleEntity() {
                    Id = Guid.NewGuid(),
                    Type = EntityType.TypeA,
                    Detail = "A TypeA record"
                };
db.Insert(data1);
```

I got SQL statement as I expected:
```SQL
DECLARE @Id Guid
SET     @Id = 'e99c95f9-a54d-40f1-82b3-7d47c2a9461b'
DECLARE @Type1 VarChar(5) -- String
SET     @Type1 = 'TypeA' -- This is what I expect
DECLARE @Detail VarChar(14) -- String
SET     @Detail = 'A TypeA record'

INSERT INTO `ExampleEntity`
(
    `Id`,
    `Type`,
    `Detail`
 )
VALUES
(
   @Id,
   @Type1,
   @Detail
)
```

However, if I filter by the Type using this code: ` var typeACount = db.ExampleEntities.Where(E => E.Type == EntityType.TypeA).Count();`, I got this SQL which doesn't use field name in the comparison:
```SQL
SELECT
Count(*) as `cnt`
FROM
`ExampleEntity` `t1`
WHERE
`t1`.`Type` = '1' -- I would expect 'TypeA' here
```

Your help are very much appreciated.

**Comment by MaceWindu** [comment]
@JamesAtPropertyMe , no you don't need to apply any attributes. It was example with attributes, but in your implementation you can implement second method, which will be called for enum itself and leave first method return empty list.
In that method you just need to get enum fields and create MapValueAttribute for each of them. Something like this (didn't tested, so maybe small adjustments required):
```cs
class MapFieldNameValueReader : IMetadataReader
        {
            TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, MemberInfo memberInfo, bool inherit)
            {
                return Array.Empty<TAttribute>();
            }

            TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, bool inherit)
            {
                if (typeof(TAttribute).Equals(typeof(MapValueAttribute)) && type.IsEnum)
                {
                    return type.GetEnumValues()
                        .Cast<object>()
                        .Select(val => new MapValueAttribute(val) { Value = type.GetEnumName(val) })
                        .Cast<TAttribute>()
                        .ToArray();
                }

                return Array.Empty<TAttribute>();
            }
        }
```

**Comment by JamesAtPropertyMe** [comment]
@MaceWindu Thanks for your hint. After a couple of attempts, I work out the code that seems to work. The code is:
```CSharp
 class MapFieldNameValueReader : IMetadataReader
        {
            TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, MemberInfo memberInfo, bool inherit)
            {
                if (typeof(TAttribute).Equals(typeof(MapValueAttribute)) && type.IsEnum)
                {
                    var value = Enum.Parse(type, memberInfo.Name);
                    return new MapValueAttribute[] { new MapValueAttribute(value) { Value = memberInfo.Name } }
                        .OfType<TAttribute>()
                        .ToArray();
                }

                return Array.Empty<TAttribute>();

            }

            TAttribute[] IMetadataReader.GetAttributes<TAttribute>(Type type, bool inherit)
            {
                return Array.Empty<TAttribute>();
            }
        }
```
I found the first method is called for each enum field of a enum-typed column of a model class/table when linq2db is doing the mapping. The second method doesn't seem to get called regarding enum types.

**Comment by sdanyliv** [comment]
@JamesAtPropertyMe, just checked your sample and found that SetDefaultFromEnumType it's just telling to linq2db to which db type map Enum. It is not right solution.
You have to use solution that you already prepared in last message.

**Comment by JamesAtPropertyMe** [comment]
Thanks for checking the sample code, @sdanyliv . So far so good now. I'm closing this issue for now.
