### ISSUE TITLE
[Typo] DataConnectionExtensions.MergAsync()

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#907]
There's a typo in [DataConnectionExtensions](https://github.com/linq2db/linq2db/blob/master/Source/Data/DataConnectionExtensions.cs#L1971)
```
	public static Task<int> MergAsync<T>(...)
```
It will be a good idea to check the codebase with a spellchecker. I'm not sure if there is a free VS extension for it, but R# has a ReSpeller Free plugin.

**Comment by sdanyliv** [comment]
Thanks for finding. Fixed in 2d5a97375e414f7358089ea2d9addfabac898ff8
