### ISSUE TITLE
What is the way to set command execution timeout?

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#910]
I am looking for the way to increase timeout for command.
Is there any way to set default timeout or per command timeout?

**Comment by sdanyliv** [comment]
db.CommanTimеout = 50 ?

**Comment by hardhub** [comment]
Yes, thanks! ))
I have found it even in my own code.
So it is strange that I was not able to find it before (even googled)...
```c#
this.CommandTimeout = 600; // 10 minutes
```
