### ISSUE TITLE
Unable to compile my code due to inclusion of System.SerializableAttribute in linq2db

### ISSUE THREAD

**Issue by mnmr** [linq2db/linq2db#915]
I'm working on a .NET Standard 2.0 project that includes some POCO models marked for serialization. However, after including linq2db 1.9.0 elsewhere in my solution (but referenced implicitly/indirectly in the project that fails to build, as it depends on projects that do use linq2db), I can no longer compile the code . The errors I am seeing look like this:

Models\Foo\Bar.cs(8,6): error CS0433: The type 'SerializableAttribute' exists in both 'linq2db, Version=1.9.0.0, Culture=neutral, PublicKeyToken=f19f8aed7feff67e' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

There is no explicit reference to linq2db in the failing project. As it stands I'll have to eliminate linq2db completely from the solution in order to get the code to work.

Question is, why would you expose a type that does not belong in linq2db? And why would you expose a type that has been around since .NET 1.0? If these is indeed a need for this somehow, can we please put it in a separate and optional assembly?

**Comment by mnmr** [comment]
I was able to work around this by excluding linq2db in the referenced project. The code base in not in a state where I can confirm if this leads to other problems. The modified package reference looks like this:

    <PackageReference Include="linq2db.Core" Version="1.9.0">
        <PrivateAssets>all</PrivateAssets>
    </PackageReference>

**Comment by MaceWindu** [comment]
#839 duplicate 
will be fixed in next release
