### ISSUE TITLE
Read out Metadata of all mapped Types...

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#924]
I still have the Problem, I need to get all Metadata of all Mapped types to extracte Table and Column Names for a Reporting Tool.

I tried to use GetEntites() of MappingSchema wich was introduced 
 closing this commit: https://github.com/linq2db/linq2db/issues/637
But it returns a empty list of Types, and after it the mapping schema is not yet ready filled with the entities...

I use Fluent mapping!

**Comment by sdanyliv** [comment]
@jogibear9988, PR will be appreciated. You know many things in that area.

**Comment by jogibear9988** [comment]
i look... only thought maybe I did smth. wrong

**Comment by jogibear9988** [comment]
I've looked at the Code. It would be good if the Mapping Schema could return all the mapped Types. For this, every MetaDataReader should return a List of it's types. Should I add a GetMappedTypes function to IMetaDataReader and MappingSchema (but that would be a breaking change, because I had to modify a Interface)?

**Comment by jogibear9988** [comment]
Another Problem on my COde was, I used GetFluentMappingBuilder() call for each type, so I had a huge tree of MetaDataReaders...

**Comment by jogibear9988** [comment]
@sdanyliv as now version2 branch is merged, i should i work on this? will a change of the interfaces be accepted?

**Comment by sdanyliv** [comment]
Please use current master branch. I will review your PR.

**Comment by jogibear9988** [comment]
I'll look to work on this this week

**Comment by jogibear9988** [comment]
is fixed in #1587

**Comment by MaceWindu** [comment]
#1587 merged
