### ISSUE TITLE
DataConnection not should Dispose external connection, which was installed in closed state

### ISSUE THREAD

**Issue by dmitry-lipetsk** [linq2db/linq2db#927]
### Environment details
linq2db version: *1.10.0*
Framework version: *.NET Framework 4.6.2*

-----
I create DataConnection object with explicit alive closed connection object.

When I call DataConnection.get_Connection, linq2db opens my closed connection.

When DataConnection disposed, it disposes my connection object.

From my point of view, in this case linq2db should call "connection.Close" instead "connection.Dispose"

linq2db can dispose connection only when it creates connection object itself.

Test scenario in free form:
```cs
 [Test]
 public static void Test_001__ok()
 {
  var cn_str=TestServices.Conf__GetCnStr();

  using(var cn=new xdb.OleDbConnection(cn_str))
  {
   Assert.AreEqual
    (ConnectionState.Closed,
     cn.State);

   using(var db=TestServices.OleDbTools__CreateDataConnection(cn))
   {
    Assert.AreEqual
     (ConnectionState.Closed,
      cn.State);

    Assert.IsNotNull(db.Connection);

    Assert.AreEqual
     (ConnectionState.Open,
      cn.State);

    Assert.AreSame(cn,db.Connection);

    Assert.IsNull(db.ConnectionString);
   }//using db

   //Our connection still alive [ !!!! FAILED !!!! ]
   Assert.AreEqual
    (cn_str,
     cn.ConnectionString);

   //Our connection will close
   Assert.AreEqual
    (ConnectionState.Closed,
     cn.State);
  }//using cn
 }//Test_001__ok
```

**Comment by ili** [comment]
I'll prepare PR to fix an issue

**Comment by dmitry-lipetsk** [comment]
Now is ok. Thank you.
