### ISSUE TITLE
CreateTable: SQLite needs Integer—not BigInt—for AUTOINCREMENT fields

### ISSUE THREAD

**Issue by quole** [linq2db/linq2db#930]
SQL generated by `CreateTable()` can look something like this:

> CREATE TABLE [FailTable]( [id] **BigInt** PRIMARY KEY AUTOINCREMENT )

which SQLite considers invalid and produces this error:

> AUTOINCREMENT is only allowed on an **INTEGER** PRIMARY KEY

SQLite does not actually have **BigInt** type, instead automatically replacing it with **Integer** via its "[type affinity](https://sqlite.org/datatype3.html)" system. However, for some reason, ~~(possibly a bug in SQLite)~~ SQLite has [decided to be very strict about its syntax for the special "INTEGER PRIMARY KEY" column](https://sqlite.org/lang_createtable.html#rowid), which acts like an alias for `rowid`, and is the only column to allow AUTOINCREMENT. So in this special case it fails to treat the two type declarations synonymously, and the user (or linq2db in this case) needs to replace **BigInt** with **Integer** manually to avoid the above error. e.g.

> CREATE TABLE [OkTable]( [id] **Integer** PRIMARY KEY AUTOINCREMENT )

linq2db should replace **BigInt** with **Integer** in its SQL generation when creating tables for SQLite. **BigInt** is treated the same as **Integer** in SQLite, except for the special case of INTEGER PRIMARY KEY, which cannot be written as BIGINT PRIMARY KEY.

I am using version 1.10.0 via NuGet.

(Workaround: To avoid other problems with trying to roundtrip the database schema, I'm working around this by just copying the `create table` SQL into my code instead, and removing AUTOINCREMENT while I'm at it. But still it's a bug that should be fixed.)

**Comment by quole** [comment]
Background in case I missed too much context: I use `LoadSQLiteMetadata` and `GenerateModel()` through a `SQLite.tt` template to load in an SQLite database schema. In case the user deletes the database file, my user application attempts to re-create it from scratch. It does this by re-creating each table with `db.CreateTable<>()`. This fails because the SQL generated for SQLite contains **BigInt** instead of **Integer**, leading to the "AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY" error.

**Comment by sdanyliv** [comment]
@quole, it is bad idea, we do not support CodeFirst approach. CreateTable is useful for creating Temporary tables. 
I suggest to use [FluentMigrator](https://github.com/fluentmigrator/fluentmigrator)
Here is a sample how to execute migration in your application
[execute-fluentmigrator-migrations-from-code](https://stackoverflow.com/questions/2751373/execute-fluentmigrator-migrations-from-code)
What do you need - dynamically generate single migration based on your entities.

**Comment by sdanyliv** [comment]
Closing. As designed.
