### ISSUE TITLE
Oracle : wrong join clause generation

### ISSUE THREAD

**Issue by laurentKTR** [linq2db/linq2db#932]
If in my tables definitions i have 2 columns that can be null and I'm doing a join on them
the query parser add extra tests that are for me invalid

![image](https://user-images.githubusercontent.com/5880174/33216916-2954f49c-d136-11e7-85aa-ea9993502782.png)

var query = from i in db.GetTable<IMPORT>() join o in db.GetTable<ORM>() i.LABEL equals o.LABEL select i

I'm expecting such generated SQL 
SELECT *   FROM IMPORT i inner join ORM o on i.LABEL = o.LABEL 
=> RESULTS = 1 row
and i have 
SELECT *   FROM IMPORT i inner join ORM o on i.LABEL is null and o.LABEL is null OR   i.LABEL = o.LABEL  => RESULTS = 5 rows

this query   is false for me : you are returning a cartesian product

### Steps to reproduce
```c#
public class Import
             {
                    [Column, NotNull] public int Id { get; set; }
                    [Column, Nullable] public string Label { get; set; }
             }

             public class Orm
             {
                    [Column, NotNull] public int Id { get; set; }
                    [Column, Nullable] public string Label { get; set; }
             }

             [Test, OracleDataContext]
             public void InnerJoinOnNullableFieldsTest(string context)
             {
                    var datas1 = new List<Import>( new[] { new Import { Id = 1, Label = "LINQ2DB"}, new Import { Id = 2, Label = null }, new Import { Id = 3, Label = null } });
                    var datas2 = new List<Orm>(new[] { new Orm { Id = 1, Label = "BLTOOLKIT" }, new Orm { Id = 2, Label = "ENTITY" }, new Orm { Id = 3, Label = null }, new Orm { Id = 4, Label = "LINQ2DB" }, new Orm { Id = 5, Label = null }, });

                    using (var db = new DataConnection(context))
                    {
                           try
                           {
                                  db.CreateTable<Import>();
                                  db.CreateTable<Orm>();

                                  foreach (var data1 in datas1)
                                        db.Insert(data1);

                                  foreach (var data2 in datas2)
                                        db.Insert(data2);

                                  var query = from a in db.GetTable<Import>()
                                              join b in db.GetTable<Orm>() on a.Label equals b.Label
                                              select a;


                                  var res  = query.ToList();
                                  Assert.That(res, !Is.Null);
                                  Assert.That(res.Count, Is.EqualTo(1));

                           }
                           finally
                           {
                                  db.DropTable<Import>();
                                  db.DropTable<Orm>();
                           }

                    }
             }

```

![image](https://user-images.githubusercontent.com/5880174/33217224-463ba6fe-d137-11e7-878e-35170a1d604f.png)

If i'm removing the check on is SelectQuery.Colum then these predicates "on i.LABEL is null and o.LABEL is null" are not generated

Actually i'm using a very very old version of linq2db ( 1.0.2.5 ) that doesn't generated these extra predicates

When migrating to last version, my queries return too many lines !!!

Regards

### Environment details
linq2db version: all since nuget exists
Database Server: *E.g. Oracle * 
Database Provider: *ManagedDataAccess, DataAccess
Operating system: 7/10
Framework version: 4.5

**Comment by ili** [comment]
Hello @laurentKTR 

This is default behavior, we are trying to be maximum same as `linq2objects`. 

With 1.10.1 release it would be configurable with:
```cs
LinqToDB.Configuration.Linq.CompareNullsAsValues = false;
```

Set this option in application startup.

**Comment by laurentKTR** [comment]
thanks you very much, very quick answer and fix 👏
