### ISSUE TITLE
Could not compile master with VS2017

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#933]
I got the following error:

      error MSB4018: Unerwarteter Fehler bei der EnsureBindingRedirects-Aufgabe.

I've had to remove the line 

	<Import Project="..\..\Redist\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets" Condition="Exists('..\..\Redist\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets') AND '$(TargetFramework)' == 'net40'" />

from the csproj. Then it compiled!

**Comment by sdanyliv** [comment]
@jogibear9988, do you still have this error?

**Comment by jogibear9988** [comment]
Does work now...
