### ISSUE TITLE
Potentially adding a new data provider

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#946]
Seeing as oracle has been so blatantly late to the game for dotnet support, I've considered creating a OracleDevart provider to sit along side the oracle.native/oracle.managed. I understand the root namespace is different, but much of the core querying functionality is pretty much identical to classes in the managed library etc.

Is it safe to assume that because this depends on a commercial library, we wouldn't want contributed to core code base?

Also, I'm specifically trying to fix this so I can deploy this code on .net core, is the v2 codebase thats supposed to allow targeting .net core 2.0, just being developed in main branch, or is that being developed elsewhere??

Finally, do you guys have a recommendation about how to develop this other provider whilst still providing tests etc?

**Comment by dmitry-lipetsk** [comment]
Hello,

I try to write external DataProvider for my ADO.NET provider (lcpi.data.oledb at nuget).

Seem, it is not diffucult, but require some improvements in LinqToDB infrastructure.

As start point I use the exists DataProvider (Firebird).

About tests and LinqToDB.

I clone LinqToDB and added to my solution the projects from LinqToDB
LinqToDB\LinqToDB.csproj
Tests\Linq\Tests.csproj
Tests\VisualBasic\Tests.VisualBasic.vbproj
Tests\FSharp\Tests.FSharp.fsproj
Tests\Model\Tests.Model.csproj
Tests\Utils\Tests.Utils.csproj

For run existing LinqToDB tests with my provider it was necessary to change the tests. It was not difficult.

**Comment by RoyC-Retail-Assist** [comment]
[https://github.com/LinqToDB4iSeries/Linq2DB4iSeries](url) is a DataProvider for DB2 for IBM iSeries.  The unit tests are little behind the current Linq2Db ones but it may give you good place to start.

**Comment by jogibear9988** [comment]
@MaceWindu @sdanyliv 
is there any news about devart support?

**Comment by MaceWindu** [comment]
Nope. Somebody just need to do it :)

**Comment by MaceWindu** [comment]
Couple of recent examples how to add new provider implementation for already supported database:
Sybase: https://github.com/linq2db/linq2db/pull/1159
MySqlConnector: https://github.com/linq2db/linq2db/pull/1470 +  https://github.com/linq2db/linq2db/pull/1484

**Comment by ronnyek** [comment]
Just as a side note... oracles .net core drivers have been out for a bit, and do work with linq2db (the reason I was originally pushing for devart)

Not to say it wouldn't be worthwhile to support the devart driver

**Comment by lytico** [comment]
I started to implement this:

https://github.com/lytico/linq2db/tree/Oracle.Devart.Lytico

but my (commercial) project manager stopped me :/

so if someone is interested, and makes me an offer ...
I think its about 80 manhours to finish (including passing the unit-tests as far as possible)

**Comment by MaceWindu** [comment]
@GonzoSpire what do you think? I think you can handle it

**Comment by viceroypenguin** [comment]
Now that Oracle supports .Net Core, this is no longer necessary

**Comment by MaceWindu** [comment]
#3598
