### ISSUE TITLE
Can't build LinqToDB.csproj in Visual Studio 2017

### ISSUE THREAD

**Issue by DmitriiGaidukov** [linq2db/linq2db#947]
I wanted to run linq2db's code in debbuger, but in building process I am running into a whole bunch of syntax errors.
Please help me to find out what i missed in my configuration. I am using Visual Sudo 2017 v15.2.

error  example:

Error	CS1003	Syntax error, '(' expected	LinqToDB(net40), LinqToDB(net45), LinqToDB(net451), LinqToDB(netcoreapp2.0), LinqToDB(netstandard1.6), LinqToDB(netstandard2.0)	C:\Projects\linq2db\Source\LinqToDB\Data\DataConnectionExtensions.cs	1773	Active

on the line 

public static Task<int> DeleteAsync<T>(
			[NotNull] this IDataContext dataContext, T obj, CancellationToken token = default)

**Comment by evilbloodydemon** [comment]
It's C# 7.1 syntax, so 15.3+ version of VS is required

**Comment by DmitriiGaidukov** [comment]
@evilbloodydemon , thanks a lot! I've updated VS up to 15.5 and it's built ok.
