### ISSUE TITLE
MSSQL: using enums and generated SQL

### ISSUE THREAD

**Issue by ghost** [linq2db/linq2db#95]
Hi.
I found next problem:

I have table with some 'Type' field which is defined as TINYINT.
I'm create enum based on byte and replace member type in data model on enum type.
I.e. i'm have something like this:

``` csharp
public partial class Account
{
    [PrimaryKey, Identity] public int           Id    { get; set; } // int
    [Column,     NotNull ] public AccountType   Type  { get; set; } // tinyint
}

public enum AccountType : byte
{
        Checking = 1,
        Savings = 2,
}
```

Once i'm trying use Type field in where clauses linq2db generates weird predicate:

``` sql
Convert(Int, [t1].[Type]) = 1
```

Which is ofcourse prevents use database indexes on this fields.

This problem can be solved, or this is caused by linq expressions nature?
Can you propose workaround?

**Comment by sdanyliv** [comment]
I saw this problem also. Will check.
