### ISSUE TITLE
Join not removed, even if no column used

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#954]
Don't know if this is realy an issue.

If I've the following Linq:

				var first = db.Order.GroupJoin(db.OrderDetail, c => c.OrderID, d => d.OrderID, (c, lj) => new {c, lj})
					.SelectMany(t => t.lj.DefaultIfEmpty(), (t, lp) => t.c).First();

the following Sql is created:

	SELECT
		[c1].[OrderID],
		[c1].[CustomerID],
		[c1].[EmployeeID],
		[c1].[OrderDate],
		[c1].[RequiredDate],
		[c1].[ShippedDate],
		[c1].[ShipVia],
		[c1].[Freight],
		[c1].[ShipName],
		[c1].[ShipAddress],
		[c1].[ShipCity],
		[c1].[ShipRegion],
		[c1].[ShipPostalCode],
		[c1].[ShipCountry]
	FROM
		[Orders] [c1]
			LEFT JOIN [Order Details] [lj] ON [c1].[OrderID] = [lj].[OrderID]
	LIMIT 1

but the Join is not needed, because none of the Columns of the "Order Details" Table are used. Shouldn't Linq2Db remove it from the SQL?

**Comment by sdanyliv** [comment]
OrderDetails has primary key not OrderID. Join should be removed when we join to RIGHT side via PrimaryKeys. Otherwise we lose record multiplication which maybe was meant when defining this query.

**Comment by jogibear9988** [comment]
you're right...

**Comment by jogibear9988** [comment]
thx
