### ISSUE TITLE
How to do null conversion?

### ISSUE THREAD

**Issue by xlievo** [linq2db/linq2db#955]
create table Orders ( OrderId int, Quantity int ); insert into Orders values (1, null);

```cs
db
  .Orders
  .Where(o => o.OrderId == 1)
  .Set(o => o.Quantity, o => Sql.Convert<int, int?>(0, o.Quantity) + 1)
  .Update();
```
Thank!

**Comment by sdanyliv** [comment]
You can do that in different ways
```cs
db
  .Orders
  .Where(o => o.OrderId == 1)
  .Set(o => o.Quantity, o => o.Quantity ?? 0 + 1)
  .Update();
```
Or create Sql Extension `ISNULL`. Many samples is here:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Sql/Sql.cs#L673

**Comment by xlievo** [comment]
db
  .Orders
  .Where(o => o.OrderId == 1)
  .Set(o => o.Quantity, o => (o.Quantity ?? 0) + 1)
  .Update();

Thank you!

**Comment by xlievo** [comment]
db
  .Orders
  .Where(o => o.OrderId == 1)
  .Set(o => o.Quantity, o => (o.Quantity ?? 0) + 1)
  .Update();

Thanks very much!
