### ISSUE TITLE
Add support for fluent mapping of ExpressionPredicate

### ISSUE THREAD

**Issue by nathan-parkinson** [linq2db/linq2db#961]
Please can the option to use fluently mapping to set an ExpressionPredicate be added to linq2db.  

Some thing like 
```c#
mapper.Entity<Person>()
    .Association(x => x.Address, x => x.AddressId, y => y.AddressId, (x, y) => !y.IsDeleted)
```
Sorry if this is already in the library.  I have looked but cannot see a way to do this.  

This would do
```c#
mapper.Entity<Person>()
    .Association(x => x.Address, x => x.AddressId, y => y.AddressId, nameof(Person.AddressPredicate));
```
But it would be nicer to not have to add a property to the model class just for the ORM mappings.  It seems a shame to avoid all the attributes in the model and then have to add a property for none standard joins.

Currently, this seems to be the only way to add ExpressionPredicate without using attributes 

```c#
mapper.Entity<Person>()
    .HasAttribute(new AssociationAttribute() 
    { 
        Storage = nameof(Person.Address), 
        CanBeNull = true, 
        ThisKey = nameof(Person.AddressId), 
        OtherKey = nameof(Address.AddressId), 
        ExpressionPredicate = nameof(Person.AddressPredicate) 
    });
```

**Comment by sdanyliv** [comment]
Will add this soon. Thanks for reporting.
