### ISSUE TITLE
Некорректное значение по умолчанию для флага _disposeConnection

### ISSUE THREAD

**Issue by chipshelby** [linq2db/linq2db#962]
Флажок, который ломает всё.
Из-за того что конструкторы класс DataConnection имеют неконсистентный вид,
а именно нет единой точки инициализации, а так же из-за того что
новый флаг _disposeConnection устанавливается по умолчанию в true
появляется возможность неконсистентого использования библиотекой.
Пример:
мы используем конструктор всегда один public DataConnection(IDataProvider, IDbConnection, disposeConnection),
где disposeConnection выставляем false, и далее мы не ожидаем что библиотека будет создавать
соединение как-то иначе, но внутренний код при исполнении запросов через IQueryRunner IDataContext.GetQueryRunner
получает соединение DataConnection GetDataConnection(), где флаг по умолчанию true.
Как итог, получается создание нового соединения с попыткой создания распределенной транзакции, чего
не хотелось бы, так как это приводит к "Network access for Distributed Transaction Manager (MSDTC) has been disabled.
Please enable DTC for network access in the security configuration for MSDTC using the Component Services Administrative tool.."

**Comment by igor-tkachev** [comment]
Can you provide a test example?

**Comment by rsivanov** [comment]
Пример кода, в котором воспроизводится ошибка ниже. В примере используется XUnit и Automapper. LoadWith приводит к эскалации транзакции, так как внутри создается DataConnection без параметров. В предыдущем сообщении подробно описаны причины. Для решения нужно всего лишь задать корректное значение по умолчанию для _disposeConnection - false.

using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using LinqToDB;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;
using Xunit;

namespace Linq2DbTests
{
	public class CategoryDto
	{
		public int CategoryID;

		public string CategoryName;

		public List<ProductDto> Products;
	}

	public class ProductDto
	{
		[PrimaryKey, Identity] public int ProductID;
		[Column, NotNull] public string ProductName;
	}

	[Table("Categories")]
	public class Category
	{
		[PrimaryKey, Identity] public int CategoryID;
		[Column, NotNull] public string CategoryName;
		[Column] public string Description;

		[Association(ThisKey = "CategoryID", OtherKey = "CategoryID")]
		public List<Product> Products;
	}

	[Table(Name = "Products")]
	public class Product
	{
		[PrimaryKey, Identity] public int ProductID;
		[Column, NotNull] public string ProductName;
		[Column] public int? CategoryID;
		[Column] public string QuantityPerUnit;
		[Association(ThisKey = "CategoryID", OtherKey = "CategoryID")] public Category Category;
	}

	public class Linq2DbDistributedTransactionsTests
    {
		[Fact]
		public void Linq2DbPromotesLocalTransactionToDistributed()
		{
			var sqlException = Assert.Throws<System.Data.SqlClient.SqlException>(() =>
			{
				Mapper.Initialize(cfg =>
				{
					cfg.CreateMap<Category, CategoryDto>();
					cfg.CreateMap<Product, ProductDto>();
				});
				LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
				using (var scope = new TransactionScope())
				using (var db =
					SqlServerTools.CreateDataConnection("Data Source=.\\LocalMsSql;Database=Northwind;Integrated Security=SSPI"))
				{

					var firstCategoryName = db.GetTable<Category>().Where(c => c.CategoryID == 1).Select(c => c.CategoryName)
						.FirstOrDefault();

					var categoryDtos = db.GetTable<Category>().LoadWith(c => c.Products).ProjectTo<CategoryDto>().ToList();

					scope.Complete();
				}
			});

			Assert.Contains("MSDTC", sqlException.Message);
		}
    }
}

**Comment by MaceWindu** [comment]
I have reviewed this flag and don't anything wrong:
- this flag controls ownership of external connection, passed to `DataConnection`, that's why it is `true` by default for conntections, created by `DataConnection` itself
- when `DataConnection` cloned, cloned instance receives new connection and use `_disposeConnection=true`, because cloned `DataConnection` owns new conection instance
- one exception to previous statement: when we work with MARS-enabled connection, we pass original connection to cloned `DataConnection`, and in this case we set `_disposeConnection=false`, because cloned `DataConnection` doesn't own passed connection

Anyway, in v3 starting from preview 2 we use new `LoadWith` implementation, which executes all load operations on same connection.
We still use cloning for LINQ-style GroupBy queries, but such queries concidered bad idea anyway.

**Comment by Powerz** [comment]
Hi @MaceWindu , 

Meanwhile, the issue persists in v**3.1.2**.

I managed to reproduce it with the code similar to the example provided above by @rsivanov. My real code is using projection, which, I assume, results in something similar to `LoadWith`.

```csharp
using (var transaction = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.Serializable }, TransactionScopeAsyncFlowOption.Enabled))
using (var db = SqlServerTools.CreateDataConnection("Data Source=.\\LocalMsSql;Database=Northwind;Integrated Security=SSPI"))
{
    var stuff = await _db.GetTable<SomeTable>()
                                      .Where(x => x.Id == id)
                                      .ProjectTo<SomeEntity>(_mapper.ConfigurationProvider) // which implicitly joins AnotherTable
                                      .FirstAsync();

    transaction.Complete();
}

// The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION
```

Could you please reopen this issue and investigate?

**Comment by sdanyliv** [comment]
Create new issue with your model and Automapper configuration.
