### ISSUE TITLE
Define SchemaProviderBase::ToTypeName as public and static

### ISSUE THREAD

**Issue by dmitry-lipetsk** [linq2db/linq2db#963]
linq2db version: *master* 

SchemaProviderBase::ToValidName defined as public and static method

But SchemaProviderBase::ToTypeName defined as protected and non-static.

As I understand, these methods have identical nature and might be defined in unified form: public+static

**Comment by sdanyliv** [comment]
Fixed in 36c3101b7a0b047f9f439a0ed2fa66de23d3dd0e
