### ISSUE TITLE
Tests CharIndex1 and CharIndex2 supported by Firebird

### ISSUE THREAD

**Issue by dmitry-lipetsk** [linq2db/linq2db#966]
linq2db version: *master*  

Tests\Linq\Linq\StringFunctionTests.cs
- CharIndex1
- CharIndex2

These tests supported by Firebird data provider.

------ 1
DataConnection: -- Firebird
SELECT
	t1.FirstName,
	t1.PersonID,
	t1.LastName,
	t1.MiddleName,
	t1.Gender
FROM
	Person t1
WHERE
	Position('oh', t1.FirstName) = 2 AND t1.PersonID = 1

DataConnection: Query Execution Time: 00:00:00.0280006

DataConnection: Total Execution Time: 00:00:00.3205403. Rows Count: 1.

------ 2
DataConnection: -- Firebird
SELECT
	t1.FirstName,
	t1.PersonID,
	t1.LastName,
	t1.MiddleName,
	t1.Gender
FROM
	Person t1
WHERE
	Position('p', t1.LastName, 2) = 3 AND t1.PersonID = 1

DataConnection: Query Execution Time: 00:00:00.0230004

DataConnection: Total Execution Time: 00:00:00.3068433. Rows Count: 1.

**Comment by sdanyliv** [comment]
Fixed in 4ca152b4a53a7e85589d0c9071062fd7a5784681
