### ISSUE TITLE
Lazy return with deferred execution inside DataConnection

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#971]
You should reconsider your _Done right vs Done wrong_ :
actually a queryable would not make sense if you want to enumerate it always  from the very first fetch.

What you describe as _closing the connection_ appears a misunderstanding or a bug.

In functional languages, lazy evaluation and IO monad are the principled elements behind the expressions that you deem wrong. 

Of course C# is not Haskell and there can be a problem with async because it is a special case... anyway you should support a paradigm like F# with effects, handlers, contexts, _continuations_...

In **one** word, deferred execution return types are not doing it wrong: they are **good** patterns.

**Comment by sdanyliv** [comment]
EF works in the same way. We need to track connection and return to the pool. It is limited resource.
You can use Dependency resolver for acquiring DataConnection per web request and use everything without disposing connection.

**Comment by giuliohome** [comment]
Thank you but I don't use EF. I like and use linq2db.
I have software in prod that returns enunerable. 
I'm pretty confident it works 
Are you really sure about the dangling connections and the bad code statement? 
Thanks for your support

**Comment by giuliohome** [comment]
Thank you but I don't use EF. I like and use linq2db.
I have software in prod that returns enunerable. 
I'm pretty confident it works 
Are you really sure about the dangling connections and the bad code statement? 
Thanks for your support

**Comment by sdanyliv** [comment]
>Thank you but I don't use EF. I like and use linq2db.

And that is great ;)

Imagine situation
```cs
foreach (var e1 = GetEntities1())
  foreach (var e2 = GetEntities2())
  {
     return;
  }
```
Here we have two opened connections that are not returned to the pool. I can not see silver bullet that may help here.

**Comment by giuliohome** [comment]
Enumerable is not queryable: the first access materialize the whole collection in memory.

**Comment by sdanyliv** [comment]
Nope, it enumerates through DataReader, if you cast IQueryable to IEnumerable. But i need to look at your usual code first.

**Comment by giuliohome** [comment]
It opens conn, enumerates all and closes: are you saying it opens, then only does a Read on the DataReader till the next iteration? I'm surprised... 
But even in that case though your guidelines could be to add the ToList() after the GetEntities () and not inside the using DataConnection

**Comment by sdanyliv** [comment]
Yes, it is because, for example SQL Server data provider may send records continuosly to speedup records processing.
ToList() enumerates everything and returns prepared collection. 
And it is already in Done Right section.

**Comment by giuliohome** [comment]
Ehm... I see that ToList() after GetEntities() is the very first example of the Done Wrong section

**Comment by sdanyliv** [comment]
In **done wrong** section you have disposed connection and trying to enumerate entities throught DataReader using that connection.
Maybe there is solution to close connection immediately after disposing enumerator. We have to think about this.

**Comment by giuliohome** [comment]
Wait there is a point where I "strongly" ;-) disagree: 

I do not have closed/disposed the connection there when I enumerate. It is completely corrected IMO

**Comment by sdanyliv** [comment]
We have to synchronize ))
Post sample of your usual linq2db usage in methods.

**Comment by sdanyliv** [comment]
I’ve missed second sample
```cs
public IEnumerable<Person> GetPersons()
{
    // ToList call sends query to database and DataContext releases connection
    return new DataContext().GetTable<Person>().ToList();
}
```
Looks like DataContext should work as axpected and release connection after enumeration.

**Comment by giuliohome** [comment]
I think so. I'm not able to compile code at the moment but  you've understood what I mean: it should release the connection after the ToList() enumeration (that always worked fine in my experience and I believe it is  also correct by design)

**Comment by sdanyliv** [comment]
Yes it’s why it was introduced. It opens and closes connection automatically when you need data.
My fault. I have to test it deeply by myself.

**Comment by MaceWindu** [comment]
Not sure I understand issue here :). Please reopen if you have example where you think linq2db manage connections incorrectly.

**Comment by giuliohome** [comment]
Look https://github.com/giuliohome/issue971/blob/master/CmdIssue971/NotWrong.cs
Since GetPersons1 works fine you don't have any problem in closing the connection before enumerating a lazy collection, so  GetPersons0 is crashing maybe only for a wrong memory management .
In other words one would expect that GetPersons0 to be the linq equivalent of the pure sql GetPersons3  which is returning a lazy enumerable after closing and disposing the connection from which it is retrieved.
According to your contrived reasoning, applied to the SqlClient, GetPersons3 should fail with an ObjectDisposedException while it is perfectly fine and working as expected. So the crash of GetPersons0  is not well motivated and justifiable in my opinion.

**Comment by sdanyliv** [comment]
Will review.

**Comment by MaceWindu** [comment]
We don't plan to support operations on disposed context. Instead you already could use `DataContext` or `DataConnection` with `CloseAfterUse=true` flag and don't dispose them manually:

```cs
// data context
var dc = new DataContext(...) { CloseAfterUse = true };

// data connection (property is not public, so you need to cast to interface)
IDataContext db = new DataConnection(...);
db.CloseAfterUse = true;
```

This way context will open connection on request and close it after use.

**Comment by giuliohome** [comment]
Are you really writing to me after 5 years???

**Comment by MaceWindu** [comment]
😄 we are reviewing existing issues before next major release
