### ISSUE TITLE
Use build in Linq serializer 

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#972]
Hello,

I am getting more and more a fan of linq2db and am trying to find a solution for a simple linq serializer/deserializer.
I have found a lib of esskar [Serialize.Linq](https://github.com/esskar/Serialize.Linq) that seems to do what I want. But based on a one person project I am not sure if this is a reliable way.
Is there a way to use your internal serialization for linq expressions without using any database provider?
So just pass Expressions or Func<> queries.

**Comment by sdanyliv** [comment]
We do not serialize Expessions. Expressions are converted to AST, and AST has serialization.

**Comment by Franki1986** [comment]
Is there a way to encapsulate this to get the desired functionality? I mean something like 
Serialize(Expression) and Deserialize(Expression)

**Comment by sdanyliv** [comment]
There is no way to convert AST to Expression back.
For which purpose do you need Expression serialization?

**Comment by Franki1986** [comment]
I have multiple WCF services and not all are based on database accesses. 
To filter in a dynamic way I wanted to pass some Func<T, bool>, so that the filter parameters don't have to change between client and server. 
Another point is that I would like to load data over linq2db (Expression as parameter) and after that combine other data and filter by another expression passed to the server.
The problem is that most of our clients have bad internet connections, so that the less data you pass the better it is. So I have to filter as much as I can on server side.

**Comment by sdanyliv** [comment]
You should try proposed library. Also you can find realizations in OData libraries but they also transforms Expression to AST, but with functionality to apply AST to queryable.

**Comment by jogibear9988** [comment]
I use this library for that: https://github.com/dotnetprojects/Interlinq-2

**Comment by Franki1986** [comment]
Thanks for the tip
