### ISSUE TITLE
Cannot connect to db2

### ISSUE THREAD

**Issue by dconner2006** [linq2db/linq2db#976]
I figured it out, all fileds need to be capitals.

Describe your issue.
Get error when try to connect to db2, sql0206N "fieldname is not valid in the context wehre it is used"

Thanks 

If you have a question, first try to check our [wiki](https://github.com/linq2db/linq2db/wiki) and search in [issues](https://github.com/linq2db/linq2db/issues) - maybe your question already answered there.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
<code with error and mapping classes>
```

### Environment details
linq2db version: *1.10.0*  
Database Server: *E.g. PostgreSQL 9.6.3*  
Database Provider: *E.g. Npgsql 3.2.3*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
Please fill template fields. Stack trace, versions etc. Steps to reproduce.

**Comment by sdanyliv** [comment]
Non relevant.
