### ISSUE TITLE
Error using bulkcopy

### ISSUE THREAD

**Issue by dconner2006** [linq2db/linq2db#978]
Getting an error trying to use the bulkcopy "The given columnMapping does not match up with an column in the source or destination.  How do I create a column mapping?

Thanks

```cs
using (var db = new SqlServerConnection())
{
       //db.MappingSchema.ColumnComparisonOption = StringComparison.OrdinalIgnoreCase;
               
        db.BulkCopy(vehs);
}
```

**Comment by sdanyliv** [comment]
Please do not post template fields. Fill them. They are important. Or remove NOT YOUR text.

**Comment by dconner2006** [comment]
WIll do

**Comment by dconner2006** [comment]
Can you please provide an example of how to create a mapping? thanks

**Comment by sdanyliv** [comment]
At first post your class, table definition, which database do you use.
Looks like you have problem not with mapping.

**Comment by dconner2006** [comment]
I capitalized all the fields in the table to match the class and it worked. However, I specified m.ColumnComparisonOption = StringComparison.InvariantCultureIgnoreCase; should that ignore the case of the field?

**Comment by sdanyliv** [comment]
This option is not used for bulk copy.
And again, post your class and table definition. Otherwise we have useless discussion.

**Comment by dconner2006** [comment]
[Table("TSTRUCT21")]
    public class Vehicles
    {
        [Column, Nullable]
        public string HIERARCHY_ID { get; set; }
        [Column, Nullable]
        public string PARENT_HIER_ID { get; set; }
        [Column, Nullable]
        public string STS_FLG { get; set; }
        [Column, Nullable]
        public string HIERARCHY_DESC { get; set; }
        [Column, Nullable]
        public string DEPT_CODE { get; set; }
        [Column, Nullable]
        public string EFF_DT { get; set; }
        [Column, Nullable]
        public string EXP_DT { get; set; }
        [Column, Nullable]
        public string CRET_ID { get; set; }
        [Column, Nullable]
        public string CRET_DT { get; set; }
        [Column, Nullable]
        public string LUPDT_ID { get; set; }
        [Column, Nullable]
        public string LUPDT_TS { get; set; }
        [Column, Nullable]
        public string RLEVEL01 { get; set; }
        [Column, Nullable]
        public string RLEVEL02 { get; set; }
        [Column, Nullable]
        public string RLEVEL03 { get; set; }
        [Column, Nullable]
        public string RLEVEL04 { get; set; }
        [Column, Nullable]
        public string RLEVEL05 { get; set; }
        [Column, Nullable]
        public string RLEVEL06 { get; set; }
        [Column, Nullable]
        public string RLEVEL07 { get; set; }
        [Column, Nullable]
        public string RLEVEL08 { get; set; }
        [Column, Nullable]
        public string RLEVEL09 { get; set; }
        [Column, Nullable]
        public string RLEVEL10 { get; set; }
        [Column, Nullable]
        public string RLEVEL11 { get; set; }
        [Column, Nullable]
        public string RLEVEL12 { get; set; }
        [Column, Nullable]
        public string RLEVEL13 { get; set; }
        [Column, Nullable]
        public string RLEVEL14 { get; set; }
        [Column, Nullable]
        public string RLEVEL15 { get; set; }
        [Column, Nullable]
        public string DEPT { get; set; }
        [Column, Nullable]
        public string AVP { get; set; }
        [Column, Nullable]
        public string DIR { get; set; }
        [Column, Nullable]
        public string REGION { get; set; }
        [Column, Nullable]
        public string DIVN { get; set; }
        [Column, Nullable]
        public string MGR { get; set; }
        [Column, Nullable]
        public string SUPV { get; set; }
        [Column, Nullable]
        public string EMAIL_ADDRESS { get; set; }
    }

CREATE TABLE [dbo].[tStruct21](
	[HIERARCHY_ID] [varchar](10) NULL,
	[PARENT_HIER_ID] [varchar](7) NULL,
	[STS_FLG] [varchar](1) NULL,
	[HIERARCHY_DESC] [varchar](50) NULL,
	[DEPT_CODE] [varchar](6) NULL,
	[EFF_DT] [date] NULL,
	[EXP_DT] [date] NULL,
	[CRET_ID] [varchar](8) NULL,
	[CRET_DT] [date] NULL,
	[LUPDT_ID] [varchar](8) NULL,
	[LUPDT_TS] [timestamp] NULL,
	[RLEVEL01] [varchar](5) NULL,
	[RLEVEL02] [varchar](5) NULL,
	[RLEVEL03] [varchar](5) NULL,
	[RLEVEL04] [varchar](5) NULL,
	[RLEVEL05] [varchar](5) NULL,
	[RLEVEL06] [varchar](5) NULL,
	[RLEVEL07] [varchar](5) NULL,
	[RLEVEL08] [varchar](5) NULL,
	[RLEVEL09] [varchar](5) NULL,
	[RLEVEL10] [varchar](5) NULL,
	[RLEVEL11] [varchar](5) NULL,
	[RLEVEL12] [varchar](5) NULL,
	[RLEVEL13] [varchar](5) NULL,
	[RLEVEL14] [varchar](5) NULL,
	[RLEVEL15] [varchar](5) NULL,
	[DEPT] [varchar](6) NULL,
	[AVP] [varchar](5) NULL,
	[DIR] [varchar](5) NULL,
	[REGION] [varchar](5) NULL,
	[DIVN] [varchar](5) NULL,
	[MGR] [varchar](5) NULL,
	[SUPV] [varchar](5) NULL,
	[EMAIL_ADDRESS] [varchar](50) NULL
) ON [PRIMARY]

**Comment by sdanyliv** [comment]
Looks like SQL Server needs case sensitive names for BulkCopy.
Changing column attribute to uppercase name may solve your issue
For example: 
```cs
[Column("HIERARCHY_ID")]
public string HierarchyId { get; set; }
```

**Comment by dconner2006** [comment]
That will work. Thanks,. Quick question, are you going to make linq2db work on objects or just databases queries. I ask because I would like to us the analytic functions i.e. lag on objects. 
Thanks

**Comment by sdanyliv** [comment]
Nope, only linq to db.
There is other library for that https://github.com/morelinq/MoreLINQ
