### ISSUE TITLE
OUTPUT: PostgreSQL support (RETURNING  clause)

### ISSUE THREAD

**Issue by Shkarlatov** [linq2db/linq2db#979]
Using postgres I use "returning *" when inserting or updating data. 
This allows you to get not only the primary key but also all the fields. 
Is it possible to do this with linq2db?

 I think in some cases this is more convenient than inserting data and then selecting them. 
If you use "returning *", you get an atomic operation and you do not need to select the primary key type.

Something like
```csharp
T obj = db.Insert<T>(T item);
T obj = db.Update<T>(T item);
```

**Comment by sdanyliv** [comment]
This feature is in our TODO list. After CTE feature, we will start implementing this one.

**Comment by CoskunSunali** [comment]
What a great feature to be used if and when available.

**Comment by sdanyliv** [comment]
There is already branch for this. Currently implemented functions `InsertWithOutput` and `InsertWithOutputInto` and only for SQL Server. I'll return to this soon.

**Comment by picolino** [comment]
Upvote for feature implementation

**Comment by MaceWindu** [comment]
Implementation PR #3328
