### ISSUE TITLE
Wrong plan for inner join (Firebird internal issue) 

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#982]
Hello, 

It looks like firebird has an internal bug regarding inner join plans. 
If you make an inner join on big tables you will get a natural plan for the inner joined table, this can cause big performance problems.
Example can be found here :

http://tracker.firebirdsql.org/browse/CORE-3707

This is not a linq2db issue, but due to the fact that this issue won't be fixed soon, can we create a generic between solution?
Maybe something like adding a 'where primariy key is not null' to the hole sql, where primary key is of the non inner joined table.

**Comment by sdanyliv** [comment]
I did not get idea how we can help here.
Please post which queries do you expect before and after.
Also note that we also have subqueries.

**Comment by Franki1986** [comment]
```
       [Table("PERSONS")]
       public class Person
      {
                  [PrimaryKey, Identity] public Int32 Id { get; set; }
                  [Column]public String Name { get; set; }
                  [Column] String FirstName { get; set; }
                  // There is an index on Age column in the db
                  [Column, NotNull]public Int32 Age { get; set; }
                  [Column]public IList<Student> StudentList { get; set; }
      }
      [Table("STUDENTS")]      
      public class Student
      {
         [PrimaryKey, Identity] public String LastName { get; set; }
         [Column]public String StudentNo{ get; set; }
         [Column] public Int32 Status { get; set; }
         [Column, NotNull]public Int32 PersonId { get; set; }
      }
```


Let's say I want to  select all students which Person age is greater than 20:

Sql would be:

```
select s.* from STUDENTS s
join PERSONS p on p.Id = s.PersonId
where p.AGE > 20;
```

simple select statement, but although there is an index on AGE, firebird won't use it (reported BUG).
 
firebirds tip was to add a +0 , but I think this is an ugly and not generic solution:

```
select s.* from STUDENTS s
join PERSONS p on p.Id+0 = s.PersonId
where p.AGE > 20;
```

I would suggest something like:

```
select s.* from STUDENTS s
join PERSONS p on p.Id+0 = s.PersonId
where p.AGE > 20 and p.ID is not NULL;
```

this would fix the issue and could be done in a generic way. 
So we could have a firebird configuration property like 'AddIdCheckForJoinIndexIssue' (or what else name) that would attach a 'inner.PrimaryKey is not NULL' to an inner join.

**Comment by sdanyliv** [comment]
Second solution also has +0. It’s by mistake?

**Comment by Franki1986** [comment]
Yes, my fault

**Comment by sdanyliv** [comment]
How about composite keys?

**Comment by sdanyliv** [comment]
So we have to add not null check for each field that were introduced in JOIN condition?

**Comment by Franki1986** [comment]
Sorry for the delay! I did some tests with composite keys and it looks like there it has no effect! Damn....!!
This is an ugly bug from firebird side! 
Is there an alternative of using inner joins?

**Comment by sdanyliv** [comment]
What does it mean, alternative for inner joins?

**Comment by Franki1986** [comment]
I mean an alternative to resolve this problem, but I think the only way is using a left join with a null check of the associated table.

```
select s.* from STUDENTS s
left join PERSONS p on p.Id = s.PersonId
where s.PersonId is not NULL;
```

This query produces a right plan without natural.

**Comment by sdanyliv** [comment]
We can do that automatically. But after 2.0 alpha release.

**Comment by Franki1986** [comment]
Sounds awesome that you are thinking about this! It's not a beautifull way to solve it, but I don't see another way.. Thanks!!!

Should be closed then or moved?

**Comment by MaceWindu** [comment]
For now we will allow sql optimizer subclassing for Firebird to allow user implement such functionality outside of linq2db
