### ISSUE TITLE
1.10.2 Package

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#986]
Are there any release notes for Package version 1.10.2 published on 27th January?

**Comment by jogibear9988** [comment]
Only this issue https://github.com/linq2db/linq2db/issues/983 is fixed

**Comment by sdanyliv** [comment]
@RoyC-Retail-Assist, we have plans to release 2.0.alpha soon. And we are trying to fix new issues only in 2.0 branch (master).
There a lot of changes in SQL AST, so your provider might not work.

**Comment by RoyC-Retail-Assist** [comment]
Thanks for the heads up.

I'll investigate what is needed to be done for the DB2i provider when you release 2.0.alpha.  Fingers crossed it won't be a massive amount of work.

**Comment by sdanyliv** [comment]
Let me know if you need some corrections from our side.
Thanks.
