### ISSUE TITLE
How to insert with both table name and identity at one time?

### ISSUE THREAD

**Issue by KasatkinaMariya** [linq2db/linq2db#987]
When I insert, I often have to specify table name explicitly:
```c#
public static void InsertWithTableName<T>(this DataConnection db, T obj)
{
	db.Insert(obj, obj.GetType().Name);
}
```
The reason is that T is often declared as abstract generated class (to have Concrete Table Inheritance  #848 ), not as concrete table class and linq2db can't find corresponding table.

Sometimes tables have id field with identity:
```c#
public partial class EntityA : EntityBase
{
	[PrimaryKey, Identity] public long Id { get; set; } // bigint
}
```
and it's very useful to obtain generated id:
```c#
var newId = db.InsertWithInt64Identity(obj);
```
Is there a way to insert with both table name and identity simultaneously? Something like:
```c#
public void ProcessEntity(EntityBase entity)
{
	...
	var insertedId = db.InsertWithInt64Identity(entity, entity.GetType().Name);
	...
}
```

### Environment details
linq2db version: *1.9.0*  
Database Server: *PostgreSQL 9.6*  
Database Provider: *Npgsql 3.2.6*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.5.2*

**Comment by sdanyliv** [comment]
Currently there is no easy way to do that, but you can use this function:
```cs
db.GetTable<T>().TableName("SomeName").InsertWithInt64Identity(<setter expression>)
```
Setter expression needs to be generated dynamically. It should be lambda expression without parameters that returns entity that needs to be inserted:
```cs
new T
{
  Field1 = "Value1",
  Field2 = "Value2",
  ...
}
```
Sample call is here:
https://github.com/linq2db/linq2db/blob/cf160d92b7062d1af7581abeb7185b20a0fdde94/Tests/Linq/Update/InsertTests.cs#L693

**Comment by sdanyliv** [comment]
Another way, if you create data connection exactly before inserting, you can set new MappingSchema with corrected TableName for specific type.

https://github.com/linq2db/linq2db/blob/cf160d92b7062d1af7581abeb7185b20a0fdde94/Tests/Linq/Mapping/FluentMappingTests.cs#L55

**Comment by sdanyliv** [comment]
Also it can be dynamically generated method chain
```cs
db.GetTable<T>().TableName("NewName")
   .Value(o => o.Field1,  () => obj.Field1)
   .Value(o => o.Field2,  () => obj.Field2)
   ...
   .InsertWithInt64Identity();
```

**Comment by sdanyliv** [comment]
Looks like issue already answered. Will reopen if needed.

**Comment by KasatkinaMariya** [comment]
> Looks like issue already answered. Will reopen if needed.

Yes, you explained enough variants to do it. Thank you a lot!
