### ISSUE TITLE
 primary key  and unique in SQLServerCe

### ISSUE THREAD

**Issue by jackylinwh** [linq2db/linq2db#99]
My DB type is Microsoft SQL Server Compact.
I created a table like bellow:
![a](https://cloud.githubusercontent.com/assets/8254731/3685523/66d9ec28-130c-11e4-85c5-cf96eb45f7d6.jpg)
Note:This table has a primary key "ID", and a unique column.
I got an ERROR when generate code: "Running transformation: System.ArgumentException: An item with the same key has already been added."

**Comment by sdanyliv** [comment]
@jackylinwh, will reopen if this is still problem.
