### ISSUE TITLE
Why LinqToDB.DataProvider.MySql.MySqlSchemaProvider miss GetProcedures

### ISSUE THREAD

**Issue by zleeeway** [linq2db/linq2db#991]
LinqToDB.DataProvider.MySql.MySqlSchemaProvider miss GetProcedures and GetProcedureParameters, it cause MySql.tt can't generate procedure from database.

**Comment by sdanyliv** [comment]
@zleeeway, If you have knowledge how to retrieve this information - PR will be appreciated.
But note that we need parameters information.

**Comment by zleeeway** [comment]
@sdanyliv It is not a runtime bug, but a source code missing.

**Comment by zleeeway** [comment]
select * from mysql.proc;

select * from information_schema.PARAMETERS;

**Comment by sdanyliv** [comment]
Great, it will be very appreciated if you create these two functions. And it will be released soon with version 2.0.
Thanks!

**Comment by sdanyliv** [comment]
Someone can handle this? I have a lot of tasks to do. If MySql returns enough data we can grab stored procedures.
