### ISSUE TITLE
Bug or incorrect how-to at https://github.com/linq2db/linq2db#net-core

### ISSUE THREAD

**Issue by rollinghours** [linq2db/linq2db#992]
Hi, this looks like a bug or documentation issue. 

I'm looking for a way to set a run-time generated connection string without using parameterized constructor.  I've tried to follow the example at https://github.com/linq2db/linq2db#net-core but without success. 

Looking deeper I've found that the read-only property DataConnection.ConnectionString is being set only in constructors, making the code `DataConnection.DefaultSettings = new Linq2DbConnectionSettings();` called later in partial InitDataContext() useless. 

I'm using .Net 4.6.1, It is said to be working on both .net core and regular .net. 

Is there a workaround? Thanks.

### Steps to reproduce
Here is how I'm trying to set it:
```c#
namespace DataModels
{
    public partial class SandRepoModelTimeLogDB : LinqToDB.Data.DataConnection
    {
        partial void InitDataContext()
        {
            DefaultSettings = new Linq2DbConnectionSettings();
        }
    }

    public class ConnectionStringSettings : IConnectionStringSettings
    {
        public string ConnectionString { get; set; }
        public string Name { get; set; }
        public string ProviderName { get; set; }
        public bool IsGlobal => false;
    }

    public class Linq2DbConnectionSettings : ILinqToDBSettings
    {
        public IEnumerable<IDataProviderSettings> DataProviders
        {
            get { yield break; }
        }

        public string DefaultConfiguration => "RuntimeCfg";
        public string DefaultDataProvider => "SqlServer";

        public IEnumerable<IConnectionStringSettings> ConnectionStrings
        {
            get
            {
                //this never gets called:
                yield return
                    new ConnectionStringSettings
                    {
                        Name = "RuntimeCfg",
                        ProviderName = "SqlServer",
                        ConnectionString = "Data Source=(localdb)\\ProjectsV13;Database=SandRepo.ModelTimeLog;Integrated Security=true"
                    };
            }
        }
    }
}
```

### Environment details
linq2db version: *1.10.2*  
Database Server: *Sql Server 2016*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.6.1*

**Comment by ili** [comment]
This is now default behavior. It is suggested that all configuration is prepared before `DataConnection` instanced first time.  So you should make all configurations in your `Main()` method.

I think we can make some method to reset cached configuration, but I don't suppose this to be good idea for high load multithread application\service.

As workaround I can suggest smth like:
```cs
    public partial class SandRepoModelTimeLogDB : LinqToDB.Data.DataConnection
    {
        public static Func<string> ConnectionStringGetter;

        public SandRepoModelTimeLogDB() : base("SqlServer", ConnectionStringGetter())
        {
        }

    }
```

**Comment by rollinghours** [comment]
Ok, that makes sense. But the parameterless contstructor is already defined in the auto-generated part of SandRepoModelTimeLogDB. I guess I have to edit a tt template.

**Comment by ili** [comment]
you can set `GenerateConstructors          = false` in your `tt` file to avoid generating `DataConnection` constructor

**Comment by sdanyliv** [comment]
Or set `BaseDataContextClass` and create your own implementation of base class.

**Comment by MaceWindu** [comment]
Closing. Please reopen if you still have issues with it
