### ISSUE TITLE
Load base class entity and "LoadWith" ref properties of derived classes 

### ISSUE THREAD

**Issue by dubbeglas** [linq2db/linq2db#994]
Given the following scenario mapped with Inheritance (Attributes missing and not necessary to understand)

```c#
    public class Eye
    {
        public string Xy { get; set; }
    }

    public class Animal
    {
        public string Name { get; set; }

        public string Discriminator { get; set; }
    }

    public class Dog : Animal
    {
        public Eye Bla { get; set; }
    }
```

Loading all "Animal"s gives me "Animal"s and "Dog"s.
```c#
db.GetTable<Animal>().ToList();

```

To load the ref property Bla in Dog I expected something like

```c#
db.GetTable<Animal>().LoadWith<Dog>(x => x.Bla)
```

How can I "LoadWith" the Bla property?

**Comment by sdanyliv** [comment]
I need to check sources if it is possible. Usually i do not use inheritance when working with database. DB is not OOP ;)

**Comment by dubbeglas** [comment]
It was not my idea... ;-)

**Comment by jogibear9988** [comment]
@sdanyliv @ili @igor-tkachev please review
