### ISSUE TITLE
LoadWith ExpressionPredicate Not Working

### ISSUE THREAD

**Issue by devinlyons** [linq2db/linq2db#995]
The title pretty much sums it up. I forked linq2db and created a test that revels the bug.

https://github.com/devinlyons/linq2db/commit/474d10ed2197b60b685159ac3bec153b8e30c505

### Environment details
linq2db version: *1.10.2*  
Database Server: *All*  
Database Provider: *All*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7*

**Comment by devinlyons** [comment]
I updated the code to use the latest version of linq2db.

https://github.com/devinlyons/linq2db/commit/ad6f0f576542dd5a1f465521cdcfb23e5b9538d4

### Environment details
linq2db version: 2.2.0
Database Server: All
Database Provider: All
Operating system: Windows 10
Framework version: .NET Framework 4.7

**Comment by MaceWindu** [comment]
@sdanyliv we need to test it against new implementation

**Comment by MaceWindu** [comment]
Fixed by #1756
