### ISSUE TITLE
SQLite DateAdd with data from table not being constructed properly

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#998]
When trying to do a date add in a where clause where the date is a column in the table and the days to add is also a column is constructing incorrect SQL.

```c#
public class TestData
{
	public DateTime FromDate { get; set; }
	public DateTime ToDate { get; set; }
	public int Days { get; set; }
}
```

```c#
var provider = new SQLiteDataProvider();

using (var ctx = new DataConnection(provider, "FullUri=file::memory:?cache=shared; ToFullPath=false"))
{
        var tbl = ctx.CreateTable<TestData>();
        ctx.Insert(new TestData { FromDate = new DateTime(2018, 1, 1), ToDate = new DateTime(2018, 1, 3), Days = 5});

        var result = tbl.Count(t => t.FromDate.AddDays(t.Days) > t.ToDate);
}
```
I'm expecting result to be 1 however it is returning zero.

The SQL generated is:

```sql
SELECT
	Count(*) as [cnt]
FROM
	[TestData] [t1]
WHERE
	DateTime(DateTime([t1].[FromDate], 'Cast([t1].[Days] as Float) Day')) > DateTime([t1].[ToDate])
```
The t1.Days is included in the string literal.

```sql
'Cast([t1].[Days] as Float) Day'
```

The where clause needs to be constructed similar to:

```sql
DateTime(DateTime([t1].[FromDate], '+' || [t1].[Days] ||' Day')) > DateTime([t1].[ToDate])
```

### Environment details
linq2db version: 1.10.2  
Database Server: SQLite
Database Provider: SQLite  
Operating system:  Windows 10
Framework version: .NET Framework 4.6.2

**Comment by sdanyliv** [comment]
@RoyC-Retail-Assist, PR will be appreciated ;)
Currently we are really busy. There are two major features in implementation.
