### ISSUE TITLE
Projection for composite object property includes all columns

### ISSUE THREAD

**Issue by randomdima** [linq2db/linq2db#999]
Hi.

If i create composite object property as described in [docs](https://linq2db.github.io/api/LinqToDB.Mapping.ColumnAttribute.html#LinqToDB_Mapping_ColumnAttribute_MemberName).
And select only part of it:
`db.Users.Select(u => u.Residence.City)`
Actual sql select will contain all fields.

Is there workaround?

linq2db.Core 1.10.2
SQL Server Data Provider 2012

**Comment by sdanyliv** [comment]
@randomdima, it is doable by defining Associations
https://github.com/linq2db/linq2db/blob/doc-associations/Doc/articles/model/associations.md

Not sure that mapping that you have used is appropriate way for LINQ Queries.

**Comment by MaceWindu** [comment]
Looks like it was fixed at some point. Works in v3
